/* Actions – Spec v1.8 Wave 4 (§4.26, §12.20): mốc thu M1/M2/M3 gắn cho Payment Allocation, mở kỳ lương → Payroll Assignment Snapshot → hiệu suất → Payroll Rule → lương theo phòng
   → cấu phần §4.26.5 → Review → Điều chỉnh có lý do → Duyệt → Khóa (→ danh sách chi lương + Payroll Cost Allocation) → Reopen có audit. Chi lương §4.26.8 (từng người / hàng loạt / import / partial).
   Không tạo Expense "Lương" (§4.26.10, §4.27.4). */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, Au = TH.auth, X = TH.actions;
  const err = (m) => { throw new Error(m); };
  const req = (v, m) => { if (v === undefined || v === null || v === '' || (typeof v === 'number' && isNaN(v))) err(m); return v; };
  const me = () => (St.state.session || {}).userId || null;
  const done = () => { St.save(); St.emit('change'); };
  const hist = (p, type, text, extra = {}) => { (p.history = p.history || []).push(Object.assign({ at: F.nowISO(), by: me(), type, text }, extra)); };

  /* ================= Mốc thu M1/M2/M3 (§4.26.2, GAP-PAY-01) ================= */
  X.tagMilestones = (paymentId) => { let n = 0; St.rawAll('paymentAllocations').filter(a => a && (!paymentId || a.paymentId === paymentId)).forEach(a => { const p = St.rawGet('payments', a.paymentId), inv = St.rawGet('invoices', a.invoiceId); if (!p || !inv) return; const m = Q.milestoneOf(p.date, inv.period); if (a.milestone !== m) { a.milestone = m; a.milestoneDay = Number(String(p.date).slice(8, 10)); n++; } }); return n; };
  ['recordPayment', 'adjustPaymentAllocations', 'matchPayment'].forEach(k => { const orig = X[k]; if (!orig) return; X[k] = function () { const r = orig.apply(this, arguments); try { X.tagMilestones(); } catch (e) { } return r; }; });

  /* ================= Bảng lương ================= */
  const periodStart = (p) => p + '-01';
  const activeEmployees = (period) => St.rawAll('employees').filter(e => e && (e.status !== 'resigned' || (e.resignedAt && String(e.resignedAt).slice(0, 7) >= period)));
  const net = (r) => Math.round(r.base + r.lunch + r.fuel + r.leadAllowance + r.support + r.perfTotal + r.adjustmentTotal - r.deductions);
  const rebuild = (p) => {
    const prev = {}; Q.payrollResults(p.id).forEach(r => { prev[r.employeeId] = r; });
    St.removeWhere('payrollAssignmentSnapshots', s => s.payrollId === p.id); St.removeWhere('payrollResults', r => r.payrollId === p.id);
    const rows = Q.perfRows(p.period); const endDate = Q.periodEndDate(p.period);
    rows.forEach(r => St.add('payrollAssignmentSnapshots', { payrollId: p.id, period: p.period, employeeId: r.employeeId, buildingId: r.buildingId, role: r.role, assignmentId: r.assignmentId, rooms: r.rooms, listed: r.listed, receivable: r.receivable, M1: r.M1, M2: r.M2, M3: r.M3, after3: r.after3, service: r.service, serviceRatio: Math.round(r.serviceRatio * 10000) / 100, extra: r.extra, collected: r.collected, efficiency: r.efficiency, ruleVersionId: r.ruleVersionId, ruleCode: r.ruleCode, tier: r.tier, ratePerRoom: r.ratePerRoom, roomSalary: r.roomSalary, snapshotAt: F.nowISO() }));
    const emps = activeEmployees(p.period); let total = 0;
    emps.forEach(e => { const cfg = Q.employeePayroll(e); const mine = rows.filter(r => r.employeeId === e.id); const old = prev[e.id] || {}; const adjustments = old.adjustments || []; const r = { payrollId: p.id, period: p.period, employeeId: e.id, orgUnitId: (Q.employeeUnit(e.id, endDate) || {}).id || null, positionCode: (Q.employeePosition(e.id, endDate) || {}).code || '', base: cfg.base, lunch: cfg.lunch, fuel: cfg.fuel, leadAllowance: cfg.leadAllowance, support: cfg.support, perfTotal: F.sum(mine, x => x.roomSalary), buildings: mine.length, rooms: F.sum(mine, x => x.rooms), adjustments, adjustmentTotal: F.sum(adjustments, a => a.amount), deductions: old.deductions || 0, deductionNote: old.deductionNote || '', ruleVersionIds: [...new Set(mine.map(x => x.ruleVersionId).filter(Boolean))], bankAccount: cfg.bankAccount || null, net: 0 }; r.net = net(r); total += r.net; St.add('payrollResults', r); });
    p.total = total; p.employees = emps.length; p.snapshotAt = F.nowISO(); p.snapshotBy = me(); p.buildings = [...new Set(rows.map(r => r.buildingId))].length; p.ruleVersionIds = [...new Set(rows.map(r => r.ruleVersionId).filter(Boolean))];
  };
  const recompute = (p) => { p.total = F.sum(Q.payrollResults(p.id), r => { r.adjustmentTotal = F.sum(r.adjustments || [], a => a.amount); r.net = net(r); return r.net; }); };
  const core = {};
  core.open = (period, { refresh } = {}) => { req(period, 'Kỳ lương'); let p = Q.payroll(period); if (p && p.status !== 'draft') err('Bảng lương ' + F.periodLabel(period) + ' đang ' + Q.label('payroll', p.status) + ' – chỉ Nháp mới tính lại (§4.26.10)'); const isNew = !p; if (!p) p = St.add('payrolls', { code: 'BL-' + period, period, status: 'draft', createdBy: me(), history: [], total: 0, note: '' }); rebuild(p); p.note = 'Snapshot phân công tại ' + F.date(Q.periodEndDate(period)) + ' · thu M1/M2/M3 từ Payment Allocation'; hist(p, isNew ? 'open' : 'refresh', isNew ? 'Mở kỳ lương – snapshot phân công & thu tiền' : 'Refresh dữ liệu (kỳ chưa khóa)'); St.audit(isNew ? 'open' : 'refresh', 'payroll', p.id, (isNew ? 'Mở kỳ lương ' : 'Refresh bảng lương ') + p.code + ' – ' + p.employees + ' NV, ' + F.vnd(p.total)); return p; };
  core.submit = (period) => { const p = Q.payroll(period); if (!p) err('Chưa mở kỳ lương'); if (p.status !== 'draft') err('Bảng lương không ở trạng thái Nháp'); if (!Q.payrollResults(p.id).length) err('Bảng lương chưa có dòng nào'); p.status = 'review'; p.submittedAt = F.nowISO(); p.submittedBy = me(); hist(p, 'submit', 'Gửi review'); St.audit('submit', 'payroll', p.id, 'Gửi review ' + p.code); return p; };
  core.return = (period, reason) => { const p = Q.payroll(period); if (!p || p.status !== 'review') err('Bảng lương không ở trạng thái Chờ duyệt'); req(reason, 'Nhập lý do trả lại'); p.status = 'draft'; hist(p, 'return', 'Trả lại: ' + reason); St.audit('return', 'payroll', p.id, 'Trả lại bảng lương ' + p.code, { reason }); return p; };
  core.approve = (period) => { const p = Q.payroll(period); if (!p || p.status !== 'review') err('Bảng lương chưa ở trạng thái Chờ duyệt'); p.status = 'approved'; p.approvedAt = F.nowISO(); p.approvedBy = me(); hist(p, 'approve', 'Duyệt bảng lương'); St.audit('approve', 'payroll', p.id, 'Duyệt ' + p.code + ' ' + F.vnd(p.total)); return p; };
  const allocateCost = (p) => {
    St.removeWhere('payrollCostAllocations', a => a.payrollId === p.id); const rule = Q.allocationRule(Q.periodEndDate(p.period)); const live = St.rawAll('buildings').filter(b => b && !b.stub && b.status !== 'inactive');
    Q.payrollResults(p.id).forEach(r => { if (!r.net) return; const snaps = Q.payrollSnapshots(p.id, r.employeeId);
      if (snaps.length) { const w = snaps.map(s => ({ b: s.buildingId, w: s.roomSalary || s.rooms || 1 })); const tw = F.sum(w, x => x.w) || 1; let acc = 0; w.forEach((x, i) => { const amt = i === w.length - 1 ? r.net - acc : Math.round(r.net * x.w / tw); acc += amt; St.add('payrollCostAllocations', { payrollId: p.id, period: p.period, employeeId: r.employeeId, buildingId: x.b, amount: amt, method: 'DIRECT_SNAPSHOT', ruleVersionId: null }); }); }
      else { const pv = Q.allocationPreview({ amount: r.net, method: (rule && rule.payrollShared) || 'ROOM_COUNT', period: p.period, buildingIds: live.map(b => b.id) }); pv.rows.forEach(x => St.add('payrollCostAllocations', { payrollId: p.id, period: p.period, employeeId: r.employeeId, buildingId: x.buildingId, amount: x.amount, pct: x.pct, method: pv.method, ruleVersionId: rule ? rule.id : null })); } });
  };
  core.lock = (period) => { const p = Q.payroll(period); if (!p || p.status !== 'approved') err('Chỉ khóa bảng lương Đã duyệt'); p.status = 'locked'; p.lockedAt = F.nowISO(); p.lockedBy = me(); hist(p, 'lock', 'Khóa bảng lương');
    St.removeWhere('salaryPayments', s => s.payrollId === p.id && s.amountPaid <= 0);
    Q.payrollResults(p.id).forEach(r => { if (r.net <= 0) return; if (St.rawAll('salaryPayments').some(s => s && s.payrollId === p.id && s.employeeId === r.employeeId)) return; St.add('salaryPayments', { code: St.nextCode('salaryPayments', 'CL-' + period.replace('-', '') + '-', 3), payrollId: p.id, period, employeeId: r.employeeId, amountDue: r.net, amountPaid: 0, status: 'unpaid', bankAccount: r.bankAccount ? Object.assign({}, r.bankAccount) : null, payments: [], note: '' }); });
    allocateCost(p); St.audit('lock', 'payroll', p.id, 'Khóa bảng lương ' + p.code + ' – tạo ' + St.rawAll('salaryPayments').filter(s => s && s.payrollId === p.id).length + ' khoản chi lương, phân bổ chi phí lương theo tòa'); return p; };
  core.reopen = (period, reason) => { const p = Q.payroll(period); if (!p || !['approved', 'locked'].includes(p.status)) err('Chỉ mở lại bảng lương Đã duyệt / Đã khóa'); req(reason, 'Nhập lý do mở lại'); if (St.rawAll('salaryPayments').some(s => s && s.payrollId === p.id && s.amountPaid > 0)) err('Kỳ đã có khoản chi lương – không mở lại (hủy/điều chỉnh khoản chi trước)'); const before = p.status; St.removeWhere('salaryPayments', s => s.payrollId === p.id); St.removeWhere('payrollCostAllocations', a => a.payrollId === p.id); p.status = 'draft'; p.reopenedAt = F.nowISO(); p.reopenedBy = me(); p.reopenReason = reason; hist(p, 'reopen', 'Mở lại: ' + reason); St.audit('reopen', 'payroll', p.id, 'Mở lại bảng lương ' + p.code, { before, after: 'draft', reason }); return p; };
  core.adjust = (period, employeeId, { amount, reason }) => { const p = Q.payroll(period); if (!p || !['draft', 'review'].includes(p.status)) err('Chỉ điều chỉnh khi bảng lương Nháp / Chờ duyệt'); const r = Q.payrollResult(p.id, employeeId); if (!r) err('Không có dòng lương của nhân viên'); const amt = F.num(amount); if (!amt) err('Số tiền điều chỉnh khác 0'); req(reason, 'Điều chỉnh bắt buộc có lý do (§4.26.10)'); (r.adjustments = r.adjustments || []).push({ amount: amt, reason, by: me(), at: F.nowISO() }); recompute(p); hist(p, 'adjust', (amt > 0 ? '+' : '') + F.vnd(amt) + ' ' + Q.employeeName(employeeId) + ': ' + reason); St.audit('adjust', 'payroll', p.id, 'Điều chỉnh lương ' + Q.employeeName(employeeId) + ' ' + (amt > 0 ? '+' : '') + F.vnd(amt), { reason, after: r.net }); return r; };
  core.deduction = (period, employeeId, { amount, reason }) => { const p = Q.payroll(period); if (!p || !['draft', 'review'].includes(p.status)) err('Chỉ sửa khấu trừ khi bảng lương Nháp / Chờ duyệt'); const r = Q.payrollResult(p.id, employeeId); if (!r) err('Không có dòng lương'); const amt = Math.max(0, F.num(amount)); req(reason, 'Khấu trừ bắt buộc có lý do'); const before = r.deductions; r.deductions = amt; r.deductionNote = reason; recompute(p); hist(p, 'deduction', 'Khấu trừ ' + Q.employeeName(employeeId) + ' ' + F.vnd(amt) + ': ' + reason); St.audit('deduction', 'payroll', p.id, 'Khấu trừ ' + Q.employeeName(employeeId) + ' ' + F.vnd(amt), { before, after: amt, reason }); return r; };

  X.openPayrollPeriod = (period) => { Au.need('payroll.manage'); const p = core.open(period); done(); return p; };
  X.refreshPayroll = X.openPayrollPeriod; X.buildPayroll = X.openPayrollPeriod;
  X.submitPayroll = (period) => { Au.need('payroll.manage'); const p = core.submit(period); done(); return p; };
  X.returnPayroll = (period, reason) => { Au.need('payroll.approve'); const p = core.return(period, reason); done(); return p; };
  X.approvePayroll = (period) => { Au.need('payroll.approve'); const p = core.approve(period); done(); return p; };
  X.lockPayroll = (period) => { Au.need('payroll.lock'); const p = core.lock(period); done(); return p; };
  X.reopenPayroll = (period, reason) => { Au.need('payroll.reopen'); const p = core.reopen(period, reason); done(); return p; };
  X.adjustPayrollLine = (period, employeeId, d) => { Au.need('payroll.manage'); const r = core.adjust(period, employeeId, d); done(); return r; };
  X.setPayrollDeduction = (period, employeeId, d) => { Au.need('payroll.manage'); const r = core.deduction(period, employeeId, d); done(); return r; };
  X.savePayrollConfig = (employeeId, cfg) => { Au.need('hr.manage'); const e = St.get('employees', employeeId); if (!e) err('Không tìm thấy nhân viên'); const before = Object.assign({}, e.payroll || {}); e.payroll = Object.assign({}, e.payroll || {}, { base: F.num(cfg.base), lunch: F.num(cfg.lunch), fuel: F.num(cfg.fuel), leadAllowance: F.num(cfg.leadAllowance), support: F.num(cfg.support), bankAccount: cfg.bankAccount || (e.payroll || {}).bankAccount || null }); e.salaryBase = e.payroll.base; St.audit('payroll_config', 'employee', e.id, 'Cập nhật cấu phần lương ' + e.name, { before, after: e.payroll }); done(); return e; };
  X.savePayrollRule = (d) => { Au.need('payroll.manage'); req(d.code, 'Mã rule'); req(d.effectiveFrom, 'Ngày hiệu lực'); const tiers = (d.tiers || []).map(t => ({ from: F.num(t.from), to: t.to === '' || t.to == null ? null : F.num(t.to), rate: F.num(t.rate), label: t.label || '' })).filter(t => !isNaN(t.from)); if (!tiers.length) err('Cần ít nhất một bậc hiệu suất'); let r; if (d.id) { r = St.get('payrollRuleVersions', d.id); if (!r) err('Không tìm thấy rule'); if (St.rawAll('payrollAssignmentSnapshots').some(s => s && s.ruleVersionId === r.id)) err('Rule đã dùng cho bảng lương – tạo version mới thay vì sửa (§4.26.10)'); Object.assign(r, { name: d.name || r.name, effectiveFrom: d.effectiveFrom, effectiveTo: d.effectiveTo || '', roles: d.roles || r.roles, tiers, collectedFormula: d.collectedFormula || r.collectedFormula, note: d.note || '' }); } else r = St.add('payrollRuleVersions', { code: d.code, name: d.name || d.code, effectiveFrom: d.effectiveFrom, effectiveTo: d.effectiveTo || '', roles: d.roles || ['manager'], tiers, collectedFormula: d.collectedFormula || 'M123_MINUS_SERVICE_PLUS_EXTRA', status: 'active', confirmation: 'NEED_BUSINESS_CONFIRMATION', note: d.note || '', createdBy: me() }); St.audit('save', 'payrollRule', r.id, 'Lưu Payroll Rule ' + r.code + ' hiệu lực ' + F.date(r.effectiveFrom)); done(); return r; };
  X.exportPayroll = (period) => { const p = Q.payroll(period); if (!p) err('Chưa có bảng lương'); const rows = Q.payrollResults(p.id).map(r => { const e = Q.employee(r.employeeId); return [e.code, e.name, (Q.orgUnit(r.orgUnitId) || {}).name || '', r.buildings, r.rooms, r.base, r.lunch, r.fuel, r.leadAllowance, r.support, r.perfTotal, r.adjustmentTotal, r.deductions, r.net]; }); F.download(p.code + '.csv', F.csv(rows, ['Mã NV', 'Họ tên', 'Đơn vị', 'Số tòa', 'Số phòng', 'Lương cơ bản', 'PC ăn trưa', 'PC xăng xe', 'Lương trưởng nhóm', 'Lương hỗ trợ', 'Lương hiệu suất theo phòng', 'Điều chỉnh', 'Khấu trừ', 'Thực nhận']), 'text/csv'); return rows.length; };
  X.exportPerformance = (period, rows) => { const out = rows.map(r => [r.employee.code, r.employee.name, Q.label('payrollRole', r.role), r.building.code || r.building.name, r.rooms, r.listed, r.receivable, r.M1, r.M2, r.M3, r.after3, r.service, Math.round(r.serviceRatio * 1000) / 10, r.extra, r.collected, r.efficiency, r.ratePerRoom, r.roomSalary]); F.download('hieu-suat-thu-tien-' + period + '.csv', F.csv(out, ['Mã NV', 'Họ tên', 'Vai trò', 'Mã tòa', 'Số phòng', 'DT niêm yết', 'DT phải thu', 'DT mốc 1', 'DT mốc 2', 'DT mốc 3', 'Tổng DT sau 3 mốc', 'Dịch vụ', 'Tỉ lệ DV/DT (%)', 'DT thu thêm', 'Tổng DT thu được', 'Hiệu suất (%)', 'Mức lương/phòng', 'Tổng lương theo phòng']), 'text/csv'); return out.length; };

  /* ================= Chi lương (§4.26.8) ================= */
  const applySalary = (s, { amount, date, method, ref, evidence, note }) => { const amt = F.num(amount); if (amt <= 0) err('Số tiền chi phải lớn hơn 0'); const rem = s.amountDue - s.amountPaid; if (amt > rem + 0.5) err('Số chi ' + F.vnd(amt) + ' vượt còn phải chi ' + F.vnd(rem)); req(date, 'Ngày chi'); req(method, 'Phương thức chi'); (s.payments = s.payments || []).push({ amount: amt, date, method, ref: ref || '', evidence: evidence || '', note: note || '', by: me(), at: F.nowISO() }); s.amountPaid += amt; s.lastPaidAt = date; s.status = Q.salaryStatus(s); s.paidBy = me(); return s; };
  X.recordSalaryPayment = (id, d) => { Au.need('salary.pay'); const s = St.get('salaryPayments', id); if (!s) err('Không tìm thấy khoản chi lương'); if (['cancelled'].includes(s.status)) err('Khoản chi đã hủy'); const p = St.get('payrolls', s.payrollId); if (!p || p.status !== 'locked') err('Chỉ chi lương cho bảng lương Đã khóa (§4.26.10)'); applySalary(s, d); St.audit('salary_pay', 'salaryPayment', s.id, 'Chi lương ' + Q.employeeName(s.employeeId) + ' ' + F.vnd(F.num(d.amount)) + ' (' + s.code + ' – ' + Q.label('salaryPay', s.status) + ')'); done(); return s; };
  X.bulkSalaryPayments = (period, { ids, date, method = 'Chuyển khoản', ref = '', evidence = '' }) => { Au.need('salary.pay'); const p = Q.payroll(period); if (!p || p.status !== 'locked') err('Chỉ chi lương cho bảng lương Đã khóa'); const set = ids && ids.length ? new Set(ids) : null; const rows = Q.salaryPayments({ period }).filter(s => (!set || set.has(s.id)) && ['unpaid', 'partial', 'failed'].includes(s.status) && s.amountDue - s.amountPaid > 0); if (!rows.length) err('Không có khoản nào còn phải chi'); const batchId = 'SAL-' + Date.now().toString(36); rows.forEach(s => { if (s.status === 'failed') s.status = 'unpaid'; applySalary(s, { amount: s.amountDue - s.amountPaid, date: date || F.today(), method, ref: ref ? ref + '-' + (Q.employee(s.employeeId).code || '') : '', evidence, note: 'Chi hàng loạt ' + batchId }); }); St.audit('salary_bulk', 'payroll', p.id, 'Chi lương hàng loạt ' + rows.length + ' NV – ' + F.vnd(F.sum(rows, s => s.amountDue)), { batchId }); done(); return { count: rows.length, total: F.sum(rows, s => s.payments[s.payments.length - 1].amount), batchId }; };
  X.markSalaryFailed = (id, reason) => { Au.need('salary.pay'); const s = St.get('salaryPayments', id); if (!s) err('Không tìm thấy'); req(reason, 'Nhập lý do lỗi'); s.status = 'failed'; s.failReason = reason; (s.payments = s.payments || []).push({ amount: 0, date: F.today(), method: '', ref: '', note: 'Chi lỗi: ' + reason, by: me(), at: F.nowISO(), failed: true }); St.audit('salary_failed', 'salaryPayment', s.id, 'Chi lương lỗi ' + s.code + ': ' + reason); done(); return s; };
  X.cancelSalaryPayment = (id, reason) => { Au.need('salary.pay'); const s = St.get('salaryPayments', id); if (!s) err('Không tìm thấy'); req(reason, 'Nhập lý do hủy'); if (s.amountPaid > 0) err('Đã chi ' + F.vnd(s.amountPaid) + ' – dùng Điều chỉnh thay vì hủy'); s.status = 'cancelled'; s.cancelReason = reason; St.audit('salary_cancel', 'salaryPayment', s.id, 'Hủy khoản chi ' + s.code + ': ' + reason); done(); return s; };
  X.adjustSalaryPayment = (id, { amountDue, reason }) => { Au.need('salary.pay'); const s = St.get('salaryPayments', id); if (!s) err('Không tìm thấy'); req(reason, 'Nhập lý do điều chỉnh'); const amt = F.num(amountDue); if (amt < s.amountPaid) err('Số phải chi không nhỏ hơn số đã chi'); const before = s.amountDue; s.amountDue = amt; s.adjustReason = reason; s.status = amt <= s.amountPaid + 0.5 ? 'paid' : 'adjusted'; St.audit('salary_adjust', 'salaryPayment', s.id, 'Điều chỉnh khoản chi ' + s.code + ' ' + F.vnd(before) + ' → ' + F.vnd(amt), { before, after: amt, reason }); done(); return s; };
  X.exportSalaryPayments = (rows, period) => { const out = rows.map(s => { const e = Q.employee(s.employeeId); return [s.code, e.code, e.name, (Q.employeeUnit(s.employeeId) || {}).name || '', s.amountDue, s.amountPaid, Math.max(0, s.amountDue - s.amountPaid), s.lastPaidAt || '', (s.bankAccount || {}).bank || '', (s.bankAccount || {}).number || '', Q.label('salaryPay', s.status)]; }); F.download('chi-luong-' + period + '.csv', F.csv(out, ['Mã', 'Mã NV', 'Họ tên', 'Đơn vị', 'Phải chi', 'Đã chi', 'Còn phải chi', 'Ngày chi gần nhất', 'Ngân hàng', 'Số TK', 'Trạng thái']), 'text/csv'); return out.length; };
  // Tương thích guide P3: "Ghi nhận chi lương" cả kỳ = khóa (nếu Đã duyệt) rồi chi hàng loạt – KHÔNG tạo Expense (§4.27.4)
  X.payPayroll = (period, { date, ref } = {}) => { const p = Q.payroll(period); if (!p) err('Chưa có bảng lương'); if (p.status === 'approved') X.lockPayroll(period); if (Q.payroll(period).status !== 'locked') err('Bảng lương chưa khóa'); const r = X.bulkSalaryPayments(period, { date, ref }); return Object.assign({ expenseIds: [] }, Q.payroll(period), { paidCount: r.count }); };

  /* ================= Import kết quả chi lương (type salaryResult) ================= */
  { const orig = X.runImport; X.runImport = function (o) { if (o.type !== 'salaryResult') return orig.apply(this, arguments); Au.need('salary.pay'); const key = o.key || ('import:' + o.checksum); St.state.meta.idem = St.state.meta.idem || {}; if (St.state.meta.idem[key]) return Object.assign({ duplicate: true }, St.state.meta.idem[key]); let created = 0, skipped = 0; o.rows.forEach(r => { if (r.status === 'error') { skipped++; return; } const d = r.data; const e = St.one('employees', x => x.code === d.empCode); const s = e ? St.one('salaryPayments', x => x.employeeId === e.id && x.period === d.period && x.status !== 'cancelled') : null; if (!s) { skipped++; return; } try { if ((d.result || '').toLowerCase().startsWith('l') || /fail|lỗi/i.test(d.result || '')) { s.status = 'failed'; s.failReason = 'Kết quả GD: ' + (d.result || 'lỗi'); created++; return; } applySalary(s, { amount: d.amount, date: d.date || F.today(), method: 'Chuyển khoản', ref: d.ref || '', note: 'Import ' + o.fileName }); created++; } catch (e) { skipped++; } }); const job = St.add('importJobs', { type: 'salaryResult', fileName: o.fileName, rows: o.rows.length, valid: o.rows.filter(r => r.status === 'ok').length, warn: 0, error: o.rows.filter(r => r.status === 'error').length, created, skipped, status: 'done', createdBy: me(), checksum: o.checksum, code: St.nextCode('importJobs', 'IMP-' + F.today().slice(0, 7).replace('-', '') + '-', 3), typeLabel: 'Kết quả chi lương' }); St.audit('import', 'importJobs', job.id, 'Import kết quả chi lương ' + o.fileName + ': cập nhật ' + created + ', bỏ qua ' + skipped); St.state.meta.idem[key] = { id: job.id, code: job.code, created, skipped }; done(); return job; }; }

  /* ================= Kịch bản demo W4 (chạy 1 lần sau migrate – cần selectors đầy đủ) ================= */
  X.ensureW4Scenario = () => {
    const meta = St.state.meta; if (!meta || meta.w4ScenarioDone || !St.rawAll('buildings').length) return; meta.w4ScenarioDone = true;
    const sess = St.state.session; try {
      X.tagMilestones();
      const cur = meta.period || '2026-10'; const [y, m] = cur.split('-').map(Number); const prev = m === 1 ? (y - 1) + '-12' : y + '-' + F.pad(m - 1);
      St.removeWhere('payrolls', p => p.source === 'seed' && !p.w4); St.removeWhere('salaryPayments', () => true); St.removeWhere('payrollAssignmentSnapshots', () => true); St.removeWhere('payrollResults', () => true); St.removeWhere('payrollCostAllocations', () => true);
      const admin = St.rawAll('users').find(u => u && u.username === 'admin'); St.state.session = admin ? { userId: admin.id, role: 'admin', name: admin.name } : St.state.session;
      // Kỳ trước: mở → điều chỉnh có lý do → review → duyệt → khóa → chi lương (phần lớn đã chi, 2 chi một phần, 1 chi lỗi, 1 chưa chi)
      const p9 = core.open(prev); p9.w4 = true; const rs = Q.payrollResults(p9.id); if (rs[0]) core.adjust(prev, rs[0].employeeId, { amount: 500000, reason: 'Thưởng hỗ trợ bàn giao phòng đột xuất' }); if (rs[1]) core.deduction(prev, rs[1].employeeId, { amount: 300000, reason: 'Tạm ứng kỳ trước chưa hoàn' }); core.submit(prev); core.approve(prev); core.lock(prev);
      const kt = St.rawAll('users').find(u => u && u.username === 'ketoan'); if (kt) St.state.session = { userId: kt.id, role: 'accountant', name: kt.name };
      const sp = Q.salaryPayments({ period: prev }); const payDate = cur + '-05'; sp.forEach((s, i) => { if (i === sp.length - 1) return; if (i === sp.length - 2) { s.status = 'failed'; s.failReason = 'Sai số tài khoản nhận'; return; } if (i >= sp.length - 4) { applySalary(s, { amount: Math.round(s.amountDue * 0.6 / 1000) * 1000, date: payDate, method: 'Chuyển khoản', ref: 'UNC-' + prev.replace('-', '') + '-' + F.pad(i + 1, 3), note: 'Chi đợt 1' }); return; } applySalary(s, { amount: s.amountDue, date: payDate, method: 'Chuyển khoản', ref: 'UNC-' + prev.replace('-', '') + '-' + F.pad(i + 1, 3), evidence: 'unc_chi_luong_' + prev + '.pdf' }); });
      ['open', 'submit', 'approve', 'lock'].forEach((t, i) => { const h = (p9.history || []).find(x => x.type === t); if (h) h.at = cur + '-0' + (i + 2) + 'T09:00'; }); Object.assign(p9, { createdAt: cur + '-02T09:00', snapshotAt: cur + '-02T09:00', submittedAt: cur + '-03T09:00', approvedAt: cur + '-04T09:00', lockedAt: cur + '-05T09:00' }); (p9.history || []).filter(x => ['adjust', 'deduction'].includes(x.type)).forEach(h => { h.at = cur + '-02T10:00'; });
      // Kỳ hiện tại: mở kỳ (Nháp) để demo hiệu suất → lương
      const p10 = core.open(cur); p10.w4 = true;
    } catch (e) { console.warn('W4 scenario', e); } finally { St.state.session = sess; St.save(); }
  };
})(window.TH);
