/* Actions – Spec v1.8 Wave 4 (§4.27, §12.21): phiếu chi phí đủ dữ liệu tối thiểu (§4.27.2), hoa hồng P1 nhập vào Chi phí (§4.27.5), phân bổ chi phí chung theo
   Allocation Rule DIRECT / ROOM_COUNT / REVENUE / BUILDING_COUNT / MANUAL_RATIO cho tòa hoặc nhóm T/S/G (§4.27.7, §12.21.4), import chi phí (§4.27.1) có phát hiện trùng, hủy/điều chỉnh có audit. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, Au = TH.auth, X = TH.actions;
  const err = (m) => { throw new Error(m); };
  const req = (v, m) => { if (v === undefined || v === null || v === '' || (typeof v === 'number' && isNaN(v))) err(m); return v; };
  const me = () => (St.state.session || {}).userId || null;
  const done = () => { St.save(); St.emit('change'); };
  const periodOpen = (period, what) => { if (X.assertPeriodOpen) X.assertPeriodOpen(period, what); };
  const SYSTEM_PREFIX = /^VH-L-/;

  const applyAllocation = (ex, a, { silent } = {}) => {
    const method = a.method || 'MANUAL_RATIO'; if (!Q.L.allocMethod[method]) err('Phương thức phân bổ không hợp lệ');
    const pv = Q.allocationPreview({ amount: ex.amount, method, buildingIds: a.buildingIds, buildingType: a.buildingType, period: ex.accountingPeriod, ratios: a.ratios });
    if (!pv.rows.length) err('Chưa chọn tòa / nhóm tòa nhận phân bổ');
    if (method === 'MANUAL_RATIO') { const tot = F.sum(pv.rows, r => r.basis); if (Math.round(tot) !== 100) err('Tổng tỷ lệ phân bổ phải bằng 100% (hiện ' + tot + '%)'); }
    if (F.sum(pv.rows, r => r.basis) <= 0) err('Cơ sở phân bổ bằng 0 (' + Q.label('allocMethod', method) + ') – chọn phương thức khác');
    const rule = Q.allocationRule(ex.date);
    St.removeWhere('expenseAllocations', x => x.expenseId === ex.id);
    pv.rows.forEach(r => St.add('expenseAllocations', { expenseId: ex.id, buildingId: r.buildingId, pct: r.pct, amount: r.amount, basis: r.basis, method, buildingType: a.buildingType || '', ruleVersionId: rule ? rule.id : null, period: ex.accountingPeriod, confirmedBy: me(), confirmedAt: F.nowISO() }));
    ex.allocation = { method, buildingType: a.buildingType || '', buildingIds: pv.rows.map(r => r.buildingId), ruleVersionId: rule ? rule.id : null, at: F.nowISO(), by: me() }; ex.status = 'allocated';
    if (!silent) St.audit('allocate', 'expense', ex.id, 'Phân bổ ' + ex.code + ' ' + F.vnd(ex.amount) + ' – ' + Q.label('allocMethod', method) + ' cho ' + pv.rows.length + ' tòa' + (a.buildingType ? ' nhóm ' + a.buildingType : ''), { after: pv.rows.map(r => ({ buildingId: r.buildingId, pct: r.pct, amount: r.amount })) });
    return pv;
  };

  X.saveExpense = (d) => {
    Au.need('expenses.manage'); const date = d.docDate || d.date; req(date, 'Ngày chứng từ'); const amount = F.num(d.amount); if (amount <= 0) err('Số tiền phải lớn hơn 0');
    const GROUP_MAP = { 'Mua sắm TS': 'GV-TB', 'Thuê nhà': 'GV-THUE', 'Điện nước': 'GV-DIEN', 'Marketing': 'BH-MKT', 'Sửa chữa': 'VH-SC', 'Khác': 'VH-KHAC', 'Hoa hồng': 'BH-HH' }; const catCode = Q.expenseAlias(d.categoryCode || GROUP_MAP[d.group] || ''); const cat = Q.expenseCategory(catCode); if (!cat.code || !cat.parentCode) err('Chọn hạng mục chi phí (cấp chi tiết) theo danh mục §4.27.3'); if (cat.status === 'system' || SYSTEM_PREFIX.test(cat.code)) err('Lương/chi lương không nhập lại vào Chi phí – lấy từ Payroll (§4.27.4)');
    const common = !d.buildingId; if (common && !Au.can('expenses.manageCommon')) err('Chi phí chung cần vai trò Admin/Kế toán');
    const accountingPeriod = d.accountingPeriod || F.period(date); if (d.id) { const old = St.get('expenses', d.id); if (old) periodOpen(old.accountingPeriod || F.period(old.date), 'sửa chi phí'); if (old && old.status === 'reversed') err('Phiếu đã hủy – không sửa'); }
    periodOpen(accountingPeriod, 'ghi nhận chi phí');
    const commission = cat.code === 'BH-HH' ? { saleId: d.saleId || '', recipient: d.recipient || (d.saleId ? Q.userName(d.saleId) : ''), roomId: d.roomId || '', paidDate: d.paidDate || date } : null;
    const payload = { date, docDate: date, recordDate: d.recordDate || F.today(), accountingPeriod, categoryCode: cat.code, group: cat.name, desc: d.desc || '', buildingId: d.buildingId || null, amount, recordType: d.recordType || (common ? 'common' : (cat.code === 'GV-TB' ? 'asset' : 'ops')), method: d.method || 'cash', depreciationMonths: d.method === 'depreciation' ? (d.depreciationMonths || 36) : undefined, supplier: d.supplier || '', payMethod: d.payMethod || 'bank', evidence: d.evidence || '', note: d.note || '', dataSource: d.dataSource || 'manual', commission, confirmedBy: d.confirmedBy || me(), confirmedAt: F.nowISO() };
    let ex; if (d.id) { const before = Object.assign({}, St.get('expenses', d.id)); ex = St.update('expenses', d.id, payload); (ex.revisions = ex.revisions || []).push({ at: F.nowISO(), by: me(), before: { date: before.date, amount: before.amount, categoryCode: before.categoryCode, buildingId: before.buildingId, desc: before.desc } }); } else ex = St.add('expenses', Object.assign({ code: St.nextCode('expenses', 'CP', 4), createdBy: me(), status: 'recorded' }, payload));
    if (common) { const alloc = d.allocation || (d.allocations && d.allocations.length ? { method: 'MANUAL_RATIO', buildingIds: d.allocations.map(a => a.buildingId).filter(Boolean), ratios: Object.fromEntries(d.allocations.filter(a => a.buildingId).map(a => [a.buildingId, F.num(a.pct)])) } : null); if (alloc && alloc.method) applyAllocation(ex, alloc, { silent: true }); else { St.removeWhere('expenseAllocations', a => a.expenseId === ex.id); ex.status = 'pending_alloc'; ex.allocation = null; } }
    else { St.removeWhere('expenseAllocations', a => a.expenseId === ex.id); St.add('expenseAllocations', { expenseId: ex.id, buildingId: ex.buildingId, pct: 100, amount, method: 'DIRECT', period: accountingPeriod, confirmedBy: me(), confirmedAt: F.nowISO() }); ex.allocation = { method: 'DIRECT', buildingIds: [ex.buildingId] }; ex.status = 'recorded'; }
    St.audit(d.id ? 'update' : 'save', 'expense', ex.id, (d.id ? 'Cập nhật' : 'Lưu') + ' chi phí ' + ex.code + ' ' + F.vnd(amount) + ' · ' + cat.name + (ex.buildingId ? ' · ' + (Q.building(ex.buildingId).name || '') : ' · chung (' + Q.label('expenseStatus', ex.status) + ')'), { after: { amount, categoryCode: cat.code, buildingId: ex.buildingId } }); done(); return ex;
  };
  X.allocateExpense = (expenseId, a) => { Au.need('expenses.manageCommon'); const ex = St.get('expenses', expenseId); if (!ex) err('Không tìm thấy chi phí'); if (ex.status === 'reversed') err('Phiếu đã hủy'); periodOpen(ex.accountingPeriod || F.period(ex.date), 'phân bổ chi phí'); if (ex.buildingId && a.method !== 'DIRECT') { ex.buildingId = null; ex.recordType = 'common'; } const pv = applyAllocation(ex, a); done(); return pv; };
  X.reverseExpense = (id, reason) => { Au.need('expenses.manage'); const ex = St.get('expenses', id); if (!ex) err('Không tìm thấy chi phí'); req(reason, 'Nhập lý do hủy'); if (ex.status === 'reversed') err('Phiếu đã hủy'); periodOpen(ex.accountingPeriod || F.period(ex.date), 'hủy chi phí'); const before = ex.status; ex.status = 'reversed'; ex.reversedAt = F.nowISO(); ex.reversedBy = me(); ex.reverseReason = reason; St.removeWhere('expenseAllocations', a => a.expenseId === ex.id); St.audit('reverse', 'expense', ex.id, 'Hủy phiếu chi phí ' + ex.code + ' ' + F.vnd(ex.amount), { before, after: 'reversed', reason }); done(); return ex; };
  X.deleteExpense = (id) => { const ex = St.get('expenses', id); if (!ex) err('Không tìm thấy'); if (ex.source === 'seed') err('Chi phí demo: dùng Hủy phiếu (có audit) thay vì xóa'); St.remove('expenses', id); St.removeWhere('expenseAllocations', a => a.expenseId === id); St.audit('delete', 'expense', id, 'Xóa chi phí ' + ex.code); done(); };
  X.saveAllocationRule = (d) => { Au.need('expenses.manageCommon'); req(d.code, 'Mã rule'); req(d.effectiveFrom, 'Ngày hiệu lực'); let r; if (d.id) { r = St.get('allocationRules', d.id); if (!r) err('Không tìm thấy'); Object.assign(r, { name: d.name || r.name, effectiveFrom: d.effectiveFrom, effectiveTo: d.effectiveTo || '', defaults: d.defaults || r.defaults, fallback: d.fallback || r.fallback, payrollShared: d.payrollShared || r.payrollShared }); } else r = St.add('allocationRules', { code: d.code, name: d.name || d.code, effectiveFrom: d.effectiveFrom, effectiveTo: d.effectiveTo || '', defaults: d.defaults || {}, fallback: d.fallback || 'ROOM_COUNT', payrollShared: d.payrollShared || 'ROOM_COUNT', status: 'active', createdBy: me() }); St.audit('save', 'allocationRule', r.id, 'Lưu Allocation Rule ' + r.code); done(); return r; };

  /* ---- Import chi phí (type expense): dòng lỗi/trùng bị bỏ qua và đếm vào Work Queue "Import chi phí lỗi" ---- */
  X.expenseDuplicateOf = (d, excludeId) => { const amt = F.num(d.amount); const desc = F.norm(d.desc || ''); return St.rawAll('expenses').find(e => e && e.id !== excludeId && e.status !== 'reversed' && (e.docDate || e.date) === d.date && Math.abs(e.amount - amt) < 1 && F.norm(e.desc || '') === desc) || null; };
  X.resolveBuildingCode = (s) => { const n = F.norm(String(s || '')); if (!n || ['chung', 'common', 'cp chung'].includes(n)) return { common: true }; const b = St.rawAll('buildings').find(b => b && !b.stub && (F.norm(b.code) === n || F.norm(b.name) === n || F.norm(b.name.replace(/^tòa\s+/i, '')) === n)); return b ? { building: b } : { missing: true }; };
  X.resolveExpenseCategory = (s) => { const n = F.norm(String(s || '')); if (!n) return null; const all = Q.expenseTree().flatMap(p => p.children); return all.find(c => F.norm(c.code) === n) || all.find(c => F.norm(c.name) === n) || all.find(c => F.norm(c.name).includes(n) || n.includes(F.norm(c.name))) || null; };
  { const orig = X.runImport; X.runImport = function (o) { if (o.type !== 'expense') return orig.apply(this, arguments); Au.need('expenses.manage'); const key = o.key || ('import:' + o.checksum); St.state.meta.idem = St.state.meta.idem || {}; if (St.state.meta.idem[key]) return Object.assign({ duplicate: true }, St.state.meta.idem[key]);
    let created = 0, skipped = 0; const ids = []; const batchId = 'IMPX-' + Date.now().toString(36);
    o.rows.forEach(r => { if (r.status === 'error') { skipped++; return; } const d = r.data; const cat = X.resolveExpenseCategory(d.categoryCode); const b = X.resolveBuildingCode(d.buildingCode); if (!cat || b.missing) { skipped++; return; } try { const ex = X.saveExpense({ docDate: d.date, categoryCode: cat.code, desc: d.desc || cat.name, buildingId: b.building ? b.building.id : null, amount: d.amount, supplier: d.supplier || '', payMethod: /tiền mặt|cash/i.test(d.payMethod || '') ? 'cash' : 'bank', evidence: d.evidence || '', note: d.note || '', dataSource: 'import', allocation: b.common ? { method: Q.defaultAllocMethod(cat.code), buildingIds: [] } : null }); ex.importBatchId = batchId; ex.importFile = o.fileName; ids.push(ex.id); created++; } catch (e) { skipped++; } });
    const job = St.add('importJobs', { type: 'expense', fileName: o.fileName, rows: o.rows.length, valid: o.rows.filter(r => r.status === 'ok').length, warn: o.rows.filter(r => r.status === 'warn').length, error: o.rows.filter(r => r.status === 'error').length, created, skipped, status: skipped ? 'partial' : 'done', createdBy: me(), checksum: o.checksum, code: St.nextCode('importJobs', 'IMP-' + F.today().slice(0, 7).replace('-', '') + '-', 3), typeLabel: 'Chi phí', expenseIds: ids, batchId, lines: o.rows.map(r => ({ i: r.i, data: r.data, status: r.status === 'error' ? 'failed' : 'ok', reason: (r.issues || []).join('; ') })), progress: 100, ok: created, failed: skipped, updatedAt: F.nowISO(), attempts: [{ n: 1, at: F.nowISO(), by: me(), total: o.rows.length, ok: created, failed: skipped, status: skipped ? 'partial' : 'done', note: skipped ? 'Bỏ qua ' + skipped + ' dòng lỗi/trùng' : 'Hoàn tất' }] });
    St.audit('import', 'importJobs', job.id, 'Import chi phí từ ' + o.fileName + ': tạo ' + created + ', bỏ qua ' + skipped + ' (dòng lỗi/trùng)', { batchId }); St.state.meta.idem[key] = { id: job.id, code: job.code, created, skipped }; done(); return job; }; }
})(window.TH);
