/* Actions – Spec v1.8 Wave 3: state machine phòng có lịch sử (§12.5), workflow hợp đồng Dự thảo → Chờ duyệt → Hiệu lực → Chờ gia hạn / Chờ kết thúc → Chờ quyết toán → Đã kết thúc (§12.7.3),
   kết thúc HĐ đủ bước: chỉ số cuối → hóa đơn cuối → công nợ → cọc → khấu trừ → hồ sơ hoàn cọc (§4.17, §12.16), Work Queue HĐ sắp hết (§12.15), điện nước theo kỳ (§12.10),
   kỳ hóa đơn (§12.11.1), thu tiền thừa/tạm ứng/chưa xác định (§4.15), HĐ đầu vào workflow + HKD + loại tòa (§12.3), tài liệu có phiên bản (§4.5), khách: trạng thái & bulk (§4.8). */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, Au = TH.auth, X = TH.actions;
  const err = (m) => { throw new Error(m); };
  const req = (v, m) => { if (v === undefined || v === null || v === '' || (typeof v === 'number' && isNaN(v))) err(m); return v; };
  const me = () => (St.state.session || {}).userId || null;
  const meName = () => (St.state.session || {}).name || 'Hệ thống';
  const done = () => { St.save(); St.emit('change'); };
  const periodCode = (p = F.today().slice(0, 7)) => String(p).replace('-', '');
  const wrap = (name, after) => { const orig = X[name]; if (!orig) return; X[name] = function () { const res = orig.apply(this, arguments); try { after(res, arguments); } catch (e) { console.warn('hook', name, e); } return res; }; };
  const event = (c, type, extra = {}) => St.add('contractEvents', Object.assign({ contractId: c.id, type, date: F.today(), at: F.nowISO(), by: me(), buildingId: c.buildingId, roomId: c.roomId, tenantId: c.tenantId }, extra));

  /* ================= Phòng: chuyển trạng thái có lịch sử (§12.5.3–4) ================= */
  const pushHistory = (room, from, to, extra = {}) => St.add('roomStatusHistory', Object.assign({ roomId: room.id, buildingId: room.buildingId, from, to, at: F.nowISO(), date: F.today(), by: me(), byName: meName(), reason: '', refType: null, refId: null }, extra));
  X.roomStatus = (roomId, to, opts = {}) => {
    const r = St.rawGet('rooms', roomId); if (!r) err('Không tìm thấy phòng'); const from = r.status; if (from === to) return r;
    if (!opts.force && !(Q.ROOM_TRANSITIONS[from] || []).includes(to)) err('Không thể chuyển ' + Q.label('room', from) + ' → ' + Q.label('room', to) + ' (§12.5.3)');
    Object.assign(r, { status: to, physical: to === 'maintenance' ? 'maintenance' : to === 'cleaning' ? 'needs_clean' : 'good' }); if (to === 'ready') r.readyDate = F.today();
    pushHistory(r, from, to, { reason: opts.reason || '', refType: opts.refType || null, refId: opts.refId || null });
    if (!opts.silent) St.audit('room_status', 'room', r.id, r.code + ': ' + Q.label('room', from) + ' → ' + Q.label('room', to) + (opts.reason ? ' – ' + opts.reason : ''), { before: { status: from }, after: { status: to }, reason: opts.reason || '' });
    St.save(); return r;
  };
  /* Bảo hiểm: mọi thay đổi room.status ở nơi khác (hold, kích hoạt HĐ, onboarding...) đều được ghi lịch sử khi render */
  X.syncRoomHistory = () => { let n = 0; St.rawAll('rooms').forEach(r => { if (!r) return; const last = Q.roomStatusHistory(r.id)[0]; if (!last) { pushHistory(r, null, r.status, { reason: 'Khởi tạo lịch sử', at: r.createdAt || F.nowISO() }); n++; } else if (last.to !== r.status) { pushHistory(r, last.to, r.status, { reason: 'Đồng bộ từ nghiệp vụ', refType: 'auto' }); n++; } }); if (n) St.save(); return n; };
  X.setRoomStatus = (id, status, note) => { Au.need('rooms.manage', { type: 'room', record: St.get('rooms', id) }); const r = Q.room(id); if (Q.activeContractOfRoom(id) && status !== 'vacating') err('Phòng đang có hợp đồng ràng buộc – kết thúc/xác nhận trả phòng trước'); X.roomStatus(id, status, { reason: note || '' }); done(); return r; };
  X.confirmCleaned = (id, { toMaintenance = false, note = '' } = {}) => { const r = Q.room(id); Au.need('rooms.manage', { type: 'room', record: r }); if (r.status !== 'cleaning') err('Phòng không ở trạng thái Chờ dọn'); X.roomStatus(id, toMaintenance ? 'maintenance' : 'ready', { reason: toMaintenance ? 'Cần sửa chữa sau dọn' + (note ? ' – ' + note : '') : 'Xác nhận dọn xong / nghiệm thu' + (note ? ' – ' + note : '') }); St.audit('confirmCleaned', 'room', id, (toMaintenance ? 'Chuyển bảo trì sau dọn phòng ' : 'Xác nhận dọn xong phòng ') + r.code); done(); return r; };
  X.acceptMaintenance = (id, note = '') => { const r = Q.room(id); Au.need('rooms.manage', { type: 'room', record: r }); if (r.status !== 'maintenance') err('Phòng không ở trạng thái Bảo trì'); X.roomStatus(id, 'ready', { reason: 'Nghiệm thu sửa chữa' + (note ? ' – ' + note : '') }); done(); return r; };
  X.updateRoomPrice = ({ roomId, price, effectiveFrom, reason = '' }) => {
    const r = St.rawGet('rooms', roomId); if (!r) err('Không tìm thấy phòng'); Au.need('rooms.manage', { type: 'room', record: r }); req(effectiveFrom, 'Ngày hiệu lực'); const p = F.num(price); if (!(p > 0)) err('Giá phải > 0');
    if (St.rawAll('roomPriceHistory').some(x => x && x.roomId === roomId && x.effectiveFrom === effectiveFrom)) err('Đã có giá hiệu lực từ ' + F.date(effectiveFrom));
    const h = St.add('roomPriceHistory', { roomId, buildingId: r.buildingId, price: p, effectiveFrom, reason, by: me(), byName: meName(), previous: r.price });
    if (effectiveFrom <= F.today()) r.price = p;
    St.audit('room_price', 'room', roomId, 'Cập nhật giá niêm yết ' + r.code + ' → ' + F.vnd(p) + ' từ ' + F.date(effectiveFrom), { before: { price: h.previous }, after: { price: p, effectiveFrom }, reason }); done(); return h;
  };
  X.applyRoomPrices = (date = F.today()) => { let n = 0; St.rawAll('rooms').forEach(r => { if (!r) return; const p = Q.roomPriceAt(r.id, date); if (p && p !== Number(r.price)) { r.price = p; n++; } }); if (n) St.save(); return n; };

  /* ================= Hợp đồng: workflow (§12.7.3) ================= */
  const live = (c) => ['active', 'pending_renewal', 'pending_end'].includes(c.status);
  X.submitContract = (id) => { const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); if (c.status !== 'draft') err('Chỉ gửi duyệt hợp đồng Dự thảo'); if (!c.tenantId || !c.roomId || !c.start || !c.end || !(c.price > 0)) err('Hợp đồng thiếu khách/phòng/thời hạn/giá'); c.status = 'pending_approval'; c.submittedAt = F.nowISO(); c.submittedBy = me(); St.audit('submit', 'contract', id, 'Gửi duyệt hợp đồng ' + c.code); done(); return c; };
  X.returnContract = (id, reason) => { const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); if (c.status !== 'pending_approval') err('Hợp đồng không ở trạng thái Chờ duyệt'); req(reason, 'Nhập lý do trả sửa'); c.status = 'draft'; c.returnReason = reason; St.audit('return', 'contract', id, 'Trả sửa hợp đồng ' + c.code + ': ' + reason, { reason }); done(); return c; };
  X.approveContract = (id, opts = {}) => { const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); if (!TH.auth.can('contracts.approve') && !['admin', 'qltong', 'tpvh', 'accountant'].includes(Au.role())) err('Chỉ Admin / Quản lý Tổng / TPVH / Kế toán được duyệt hợp đồng'); if (c.status !== 'pending_approval') err('Hợp đồng không ở trạng thái Chờ duyệt'); c.approvedAt = F.nowISO(); c.approvedBy = me(); St.audit('approve', 'contract', id, 'Duyệt hợp đồng ' + c.code); return X.activateContract(id, opts.key || ('approve:' + id), opts); };
  wrap('activateContract', (c, args) => { if (!c || c.duplicate || c.status !== 'active') return; if (!c.termNo) { const prev = c.renewedFromId ? St.rawGet('contracts', c.renewedFromId) : null; c.termNo = prev ? (Number(prev.termNo) || 1) + 1 : 1; c.contractType = c.contractType || (prev ? 'renewal' : 'new'); } if (!Q.contractEvents(c.id).some(e => e.type === 'ACTIVATED')) event(c, 'ACTIVATED', { date: c.start }); if (c.renewedFromId) { const prev = St.rawGet('contracts', c.renewedFromId); if (prev && prev.status === 'ended' && !Q.contractEvents(prev.id).some(e => e.type === 'RENEWED')) event(prev, 'RENEWED', { date: c.start, refId: c.id }); } const room = St.rawGet('rooms', c.roomId); if (room && room.status === 'occupied') { const last = Q.roomStatusHistory(room.id)[0]; if (!last || last.to !== 'occupied') pushHistory(room, last ? last.to : null, 'occupied', { reason: 'Kích hoạt HĐ ' + c.code, refType: 'contract', refId: c.id }); } });
  wrap('renewContract', (n, args) => { if (!n) return; const old = St.rawGet('contracts', args[0]); if (old && old.status === 'active') { old.status = 'pending_renewal'; St.audit('status', 'contract', old.id, old.code + ' → Chờ gia hạn (HĐ mới ' + n.code + ' đang dự thảo)'); } n.contractType = 'renewal'; n.termNo = (Number(old && old.termNo) || 1) + 1; n.contractNo = ''; St.save(); });
  wrap('cancelContract', (c, args) => { const x = St.rawGet('contracts', args[0]); if (x && x.renewedFromId) { const old = St.rawGet('contracts', x.renewedFromId); if (old && old.status === 'pending_renewal') { old.status = 'active'; old.renewedToId = null; St.audit('status', 'contract', old.id, old.code + ' → Hiệu lực (hủy HĐ gia hạn ' + x.code + ')'); St.save(); } } });
  X.cancelRenewal = (oldId) => { const old = St.get('contracts', oldId); if (!old) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: old }); if (old.status !== 'pending_renewal') err('Hợp đồng không ở trạng thái Chờ gia hạn'); const n = old.renewedToId ? St.rawGet('contracts', old.renewedToId) : null; if (n && n.status === 'draft') { n.status = 'cancelled'; n.cancelReason = 'Hủy kế hoạch gia hạn'; } old.status = 'active'; old.renewedToId = null; St.audit('status', 'contract', oldId, 'Hủy kế hoạch gia hạn ' + old.code); done(); return old; };
  /* Xác nhận trả phòng (§12.7.2): HĐ → Chờ kết thúc, phòng → Sắp trống, tạo sự kiện */
  X.confirmMoveOut = (id, { noticeDate, moveOutDate, endType = 'early_tenant', reasonCode = '', note = '' } = {}) => {
    const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); if (!live(c) || c.status === 'pending_end') err('Hợp đồng không ở trạng thái Hiệu lực'); req(moveOutDate, 'Ngày ra dự kiến'); if (moveOutDate < c.start) err('Ngày ra không được trước ngày bắt đầu');
    Object.assign(c, { status: 'pending_end', noticeDate: noticeDate || F.today(), moveOutDate, endType, endReasonCode: reasonCode, endNote: note });
    if (c.renewedToId) { const n = St.rawGet('contracts', c.renewedToId); if (n && n.status === 'draft') { n.status = 'cancelled'; n.cancelReason = 'Khách trả phòng'; } c.renewedToId = null; }
    const room = St.rawGet('rooms', c.roomId); if (room && room.status === 'occupied') X.roomStatus(room.id, 'vacating', { reason: 'Xác nhận trả phòng ' + F.date(moveOutDate) + ' (' + c.code + ')', refType: 'contract', refId: c.id, silent: true });
    event(c, 'MOVE_OUT_CONFIRMED', { date: moveOutDate, endType }); St.audit('move_out', 'contract', id, 'Xác nhận trả phòng ' + c.code + ' – ra ngày ' + F.date(moveOutDate) + ' (' + Q.label('endType', endType) + ')', { after: { moveOutDate, endType, noticeDate } }); done(); return c;
  };
  /* Kết thúc / quyết toán (§4.17, §12.16): chỉ số cuối → hóa đơn cuối → công nợ → cọc → khấu trừ → hồ sơ hoàn cọc; HĐ → Chờ quyết toán */
  X.endContract = (id, p = {}) => {
    const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); if (!live(c)) err('Hợp đồng không còn hiệu lực');
    const moveOut = req(p.actualEnd || p.moveOutDate || c.moveOutDate, 'Ngày ra thực tế'); if (moveOut < c.start) err('Ngày kết thúc thực tế không được trước ngày bắt đầu');
    if (c.status !== 'pending_end') X.confirmMoveOut(id, { noticeDate: p.noticeDate, moveOutDate: moveOut, endType: p.endType, reasonCode: p.reasonCode, note: p.note });
    Object.assign(c, { moveOutDate: moveOut, endType: p.endType || c.endType || 'early_tenant', endReasonCode: p.reasonCode || c.endReasonCode || '', endReason: p.reasonText || (Q.endReasonOptions().find(x => x[0] === (p.reasonCode || c.endReasonCode)) || [])[1] || c.endReason || '', endNote: p.note || c.endNote || '' });
    const room = Q.room(c.roomId); const period = F.period(moveOut); const readings = [];
    /* 1. Chỉ số cuối (CLOSING) */
    ['electric', 'water'].forEach(type => { const v = p.readings && p.readings[type] != null && p.readings[type] !== '' ? Number(p.readings[type]) : null; if (v == null) return; const prevList = St.rawAll('meterReadings').filter(m => m && m.roomId === c.roomId && m.type === type && m.readingType !== 'CLOSING').sort((a, b) => F.cmp(b.period || b.readingDate || '', a.period || a.readingDate || '')); const prev = prevList[0] ? Number(prevList[0].curr) : 0; if (v < prev) err('Chỉ số cuối ' + (type === 'electric' ? 'điện' : 'nước') + ' (' + v + ') nhỏ hơn chỉ số gần nhất (' + prev + ')'); const meter = Q.meter(c.roomId, type); const r = St.add('meterReadings', { roomId: c.roomId, meterId: meter ? meter.id : null, contractId: c.id, type, readingType: 'CLOSING', period, readingDate: moveOut, prev, curr: v, unit: type === 'electric' ? 'kWh' : 'm³', status: 'confirmed', enteredBy: me(), note: 'Chỉ số cuối khi trả phòng' }); readings.push(r); });
    /* 2. Hóa đơn cuối / quyết toán */
    let inv = null; const existing = St.one('invoices', i => i.contractId === c.id && i.period === period && i.docStatus !== 'cancelled');
    const lines = []; const svc = F.by(St.all('services'), 'code'); const S = k => (svc[k] || [{}])[0];
    if (!existing) { const [y, m] = period.split('-').map(Number); const dim = new Date(y, m, 0).getDate(); const startDay = c.start && F.period(c.start) === period ? Number(c.start.slice(8, 10)) : 1; const days = Number(moveOut.slice(8, 10)) - startDay + 1; const rent = Math.round(c.price * days / dim / 1000) * 1000; if (rent > 0) lines.push({ item: 'Tiền phòng', desc: 'Tiền phòng ' + F.periodLabel(period).toLowerCase() + ' (' + days + '/' + dim + ' ngày đến ' + F.date(moveOut) + ')', qty: 1, unitPrice: rent, kind: 'rent', lineType: 'RENT', unit: 'tháng' }); Q.contractServices(c.id).forEach(s => { const sv = Q.service(s.serviceId); if (sv.method === 'meter') return; lines.push({ item: s.name, desc: s.name + ' ' + F.periodLabel(period).toLowerCase() + ' (kỳ cuối)', qty: s.qty, unitPrice: s.price, kind: 'service', lineType: 'SERVICE', serviceId: s.serviceId, unit: s.unit }); }); }
    readings.forEach(r => { const use = Number(r.curr) - Number(r.prev); if (use <= 0) return; const code = r.type === 'electric' ? 'DIEN' : 'NUOC'; const price = X.meterPrice ? X.meterPrice(c, code, period) : S(code).price; lines.push({ item: r.type === 'electric' ? 'Điện' : 'Nước', desc: (r.type === 'electric' ? 'Tiền điện' : 'Tiền nước') + ' chốt trả phòng (' + use + ' ' + r.unit + ' x ' + F.vnd(price) + ')', qty: use, unitPrice: price, kind: r.type, lineType: 'SERVICE', serviceId: S(code).id, unit: r.unit, sourceReadingId: r.id, meterId: r.id }); });
    (p.penalties || []).forEach(x => { if (F.num(x.amount) > 0) lines.push({ item: x.item || 'Phạt', desc: x.desc || x.item || 'Phạt theo điều khoản', qty: 1, unitPrice: F.num(x.amount), kind: 'service', lineType: 'PENALTY', unit: 'lần' }); });
    if (lines.length) { const due = moveOut; inv = St.add('invoices', { code: St.nextCode('invoices', 'HD-' + periodCode(period) + '-', 3), contractId: c.id, roomId: c.roomId, buildingId: c.buildingId, tenantId: c.tenantId, period, issueDate: null, dueDate: due, docStatus: 'draft', total: 0, adjustment: 0, carriedOver: Q.contractDebt(c.id), note: 'Hóa đơn cuối / quyết toán trả phòng ' + F.date(moveOut), final: true, createdBy: me(), reminderCount: 0, lastReminderAt: null, accountingNote: '', snapshot: { contractCode: c.code, price: c.price, tenantName: Q.tenant(c.tenantId).name, roomCode: room.code } }); lines.forEach((l, i) => St.add('invoiceLines', Object.assign({ invoiceId: inv.id, seq: i + 1, amount: l.qty * l.unitPrice }, l))); inv.total = F.sum(Q.invLines(inv.id), l => l.amount); readings.forEach(r => { r.status = 'used'; }); if (p.issueFinal !== false) { inv.docStatus = 'issued'; inv.issueDate = F.today(); if (inv.dueDate < inv.issueDate) inv.dueDate = inv.issueDate; } St.audit('final_invoice', 'invoice', inv.id, 'Hóa đơn cuối ' + inv.code + ' ' + F.vnd(inv.total) + (inv.docStatus === 'issued' ? ' (đã phát hành)' : ' (nháp)') + ' – trả phòng ' + c.code); }
    /* 3–5. Công nợ → cọc → khấu trừ → hồ sơ hoàn cọc (Nháp) */
    const debt = Q.contractDebt(c.id); const bal = Q.depositBalance(c.id); const depositHeld = bal.holding > 0 ? bal.holding : Number(c.deposit) || 0;
    const debtOffset = p.debtOffset == null ? debt : Math.min(F.num(p.debtOffset), debt);
    let rf = null;
    if (p.createRefund !== false && !c.renewedToId) { rf = X.saveRefund({ contractId: c.id, moveOutDate: moveOut, offsetDebt: debtOffset > 0, debtOffset, deductions: p.deductions || [], inspection: p.inspection || {}, assetCheck: p.assetCheck || [], depositHeld, endType: c.endType }); }
    /* 6. Trạng thái */
    Object.assign(c, { status: 'pending_settlement', actualEnd: moveOut, settledAt: F.nowISO(), settledBy: me(), settlement: { debt, debtOffset, depositHeld, finalInvoiceId: inv ? inv.id : null, closingReadingIds: readings.map(r => r.id), assetCheck: p.assetCheck || [], evidence: p.evidence || [] } });
    if (room.status === 'vacating' || room.status === 'occupied') { if (moveOut <= F.today()) X.roomStatus(room.id, 'cleaning', { reason: 'Khách đã trả phòng ' + F.date(moveOut) + ' (' + c.code + ')', refType: 'contract', refId: c.id, silent: true, force: true }); }
    event(c, 'SETTLED', { date: moveOut, refId: rf ? rf.id : null });
    St.audit('settle', 'contract', c.id, 'Quyết toán trả phòng ' + c.code + ' – ' + Q.label('endType', c.endType) + ', ra ' + F.date(moveOut) + (inv ? ', hóa đơn cuối ' + inv.code : '') + ', công nợ ' + F.vnd(debt) + ' (bù trừ ' + F.vnd(debtOffset) + ')' + (rf ? ', hồ sơ hoàn cọc ' + rf.code : ''), { after: { endType: c.endType, moveOut, debt, debtOffset, depositHeld } });
    done(); return { contract: c, refund: rf, invoice: inv, readings };
  };
  /* Đóng HĐ sau hoàn cọc (§12.16.3): Chờ quyết toán → Đã kết thúc; phòng Sắp trống → Chờ dọn (hoàn cọc không tự làm phòng Sẵn sàng) */
  X.closeContract = (id, note = '', opts = {}) => {
    const c = St.rawGet('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); if (!opts.system) Au.need('contracts.manage', { type: 'contract', record: c }); if (!['pending_settlement', 'pending_end'].includes(c.status)) err('Hợp đồng không ở trạng thái Chờ quyết toán');
    const rf = St.one('refunds', r => r.contractId === c.id && !['rejected'].includes(r.status)); if (rf && !['refunded', 'approved'].includes(rf.status) && !note) err('Hồ sơ hoàn cọc ' + rf.code + ' đang ' + Q.label('refund', rf.status) + ' – hoàn cọc xong hoặc nhập lý do đóng sớm');
    Object.assign(c, { status: 'ended', actualEnd: c.actualEnd || c.moveOutDate || F.today(), endedAt: F.nowISO(), endedBy: me() });
    const room = St.rawGet('rooms', c.roomId); if (room && (room.status === 'vacating' || room.status === 'occupied')) X.roomStatus(room.id, 'cleaning', { reason: 'Kết thúc HĐ ' + c.code, refType: 'contract', refId: c.id, silent: true, force: true });
    event(c, ['early_tenant', 'early_company', 'breach'].includes(c.endType) ? 'EARLY_TERMINATION' : 'ENDED', { date: c.actualEnd, note });
    if (c.endType === 'breach' && rf && rf.status === 'refunded' && rf.refundAmount === 0) { /* giữ lại toàn bộ cọc */ }
    St.audit('close', 'contract', id, 'Kết thúc hợp đồng ' + c.code + ' (' + Q.label('endType', c.endType || 'other') + ')' + (note ? ' – ' + note : ''), { reason: note }); done(); return c;
  };
  wrap('recordRefundPaid', (rf) => { if (!rf) return; const c = St.rawGet('contracts', rf.contractId); if (c && ['pending_settlement', 'pending_end'].includes(c.status)) { try { X.closeContract(c.id, '', { system: true }); } catch (e) { console.warn('closeContract', e); } } });
  X.forfeitDeposit = (id, reason) => { const c = St.get('contracts', id); if (!c) err('Không tìm thấy hợp đồng'); Au.need('refunds.approve'); req(reason, 'Nhập lý do giữ lại cọc'); const bal = Q.depositBalance(id); if (!(bal.holding > 0)) err('Không còn cọc đang giữ'); X.depositEntry({ contractId: id, type: 'FORFEITED', amount: bal.holding, date: F.today(), refType: 'contract', refId: id, note: 'Giữ lại cọc: ' + reason }); St.audit('forfeit', 'contract', id, 'Giữ lại toàn bộ cọc ' + F.vnd(bal.holding) + ' – ' + reason, { reason }); if (['pending_settlement', 'pending_end'].includes(c.status)) X.closeContract(id, 'Giữ lại cọc: ' + reason); done(); return c; };
  /* Tương thích: X.terminateContract cũ → luồng kết thúc đủ bước với chỉ số cuối = chỉ số gần nhất */
  X.terminateContract = (id, { actualEnd, reason, toCleaning = true, createRefund = true } = {}) => {
    const map = { 'Hết hạn, không gia hạn': 'on_time', 'Khách trả phòng sớm': 'early_tenant', 'Phá hợp đồng': 'breach', 'Chuyển phòng': 'other', 'Khác': 'other' }; const endType = map[reason] || 'early_tenant';
    const last = (type) => { const l = St.rawAll('meterReadings').filter(m => m && m.roomId === (St.rawGet('contracts', id) || {}).roomId && m.type === type && m.readingType !== 'CLOSING').sort((a, b) => F.cmp(b.period || b.readingDate || '', a.period || a.readingDate || ''))[0]; return l ? Number(l.curr) : null; };
    const r = X.endContract(id, { actualEnd, endType, reasonCode: endType, reasonText: reason, readings: { electric: last('electric'), water: last('water') }, issueFinal: true, debtOffset: 0, createRefund });
    return { contract: r.contract, refund: r.refund, invoice: r.invoice };
  };
  X.activateDueMoveOuts = () => { let n = 0; St.rawAll('contracts').forEach(c => { if (!c || c.status !== 'pending_end' || !c.moveOutDate || c.moveOutDate > F.today()) return; const room = St.rawGet('rooms', c.roomId); if (room && room.status === 'vacating') { X.roomStatus(room.id, 'cleaning', { reason: 'Đến ngày trả phòng ' + F.date(c.moveOutDate) + ' (' + c.code + ')', refType: 'contract', refId: c.id, silent: true }); n++; } }); return n; };

  /* ================= Work Queue HĐ sắp hết (§12.15) ================= */
  X.addFollowUp = ({ contractId, channel = 'Điện thoại', result = 'contacted', note = '', nextDeadline = '', assigneeId = null }) => {
    const c = St.get('contracts', contractId); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); if (!Q.L.followUp[result]) err('Kết quả không hợp lệ');
    const f = St.add('contractFollowUps', { contractId, at: F.nowISO(), date: F.today(), by: me(), byName: meName(), channel, result, note, nextDeadline: nextDeadline || '', assigneeId: assigneeId || c.followUpAssigneeId || null });
    if (assigneeId) c.followUpAssigneeId = assigneeId; c.followUpResult = result; c.followUpAt = f.at;
    St.audit('follow_up', 'contract', contractId, 'Liên hệ gia hạn ' + c.code + ': ' + Q.label('followUp', result) + (note ? ' – ' + note : ''), { after: { channel, result, nextDeadline } }); done(); return f;
  };
  X.assignFollowUp = (contractId, employeeId) => { const c = St.get('contracts', contractId); if (!c) err('Không tìm thấy hợp đồng'); Au.need('contracts.manage', { type: 'contract', record: c }); c.followUpAssigneeId = employeeId || null; St.audit('assign', 'contract', contractId, 'Giao xử lý HĐ sắp hết ' + c.code + ' → ' + (employeeId ? Q.employeeName(employeeId) : 'bỏ giao')); done(); return c; };

  /* ================= Điện nước theo kỳ (§12.10) ================= */
  X.saveMeterRow = ({ roomId, period, type, curr, photo = '', note = '', contractId = null, allowRollover = false }) => {
    Au.need('meterReadings.manage'); if (Q.periodLocked(period)) err('Kỳ ' + F.periodLabel(period) + ' đã khóa'); const r = Q.room(roomId); if (!r.id) err('Không tìm thấy phòng');
    const prevList = St.rawAll('meterReadings').filter(m => m && m.roomId === roomId && m.type === type && ((m.period && m.period < period) || m.readingType === 'OPENING') && m.status !== 'reopened' && m.readingType !== 'CLOSING').sort((a, b) => F.cmp(b.period || b.readingDate || '', a.period || a.readingDate || '')); const prev = prevList[0] ? Number(prevList[0].curr) : 0;
    const v = Number(curr); if (isNaN(v)) err('Chỉ số không hợp lệ'); if (v < prev && !allowRollover) err('Chỉ số mới (' + v + ') nhỏ hơn chỉ số cũ (' + prev + ') – rollover phải được duyệt');
    let m = St.one('meterReadings', x => x.roomId === roomId && x.period === period && x.type === type && x.readingType !== 'OPENING' && x.status !== 'reopened');
    if (m && m.status === 'used') err('Chỉ số đã dùng phát hành hóa đơn – dùng Mở lại (có quyền) trước khi sửa');
    const meter = Q.meter(roomId, type); const c = contractId || (Q.activeContractOfRoom(roomId) || {}).id || null;
    if (m) Object.assign(m, { prev, curr: v, photo: photo || m.photo || '', note: note || m.note || '', enteredBy: me(), readingDate: F.today(), rollover: v < prev }); else m = St.add('meterReadings', { roomId, meterId: meter ? meter.id : null, contractId: c, period, type, readingType: 'PERIOD', readingDate: F.today(), prev, curr: v, unit: type === 'electric' ? 'kWh' : 'm³', status: 'draft', photo, note, enteredBy: me(), rollover: v < prev });
    St.save(); return m;
  };
  X.copyPrevReadings = (period, buildingId) => { Au.need('meterReadings.manage'); let n = 0; Q.meterRows(period, { buildingId }).forEach(row => { if (!row.contract) return; ['electric', 'water'].forEach(type => { const m = row[type]; if (m.notApplicable || m.cur) return; X.saveMeterRow({ roomId: row.room.id, period, type, curr: m.prevValue, note: 'Copy chỉ số kỳ trước' }); n++; }); }); St.audit('meter', 'meterReadings', period, 'Copy chỉ số kỳ trước làm chỉ số cũ cho ' + n + ' công tơ kỳ ' + F.periodLabel(period)); done(); return n; };
  X.attachReadingPhoto = (id, fileName) => { Au.need('meterReadings.manage'); const m = St.rawGet('meterReadings', id); if (!m) err('Không tìm thấy chỉ số'); m.photo = fileName; m.photoAt = F.nowISO(); St.save(); return m; };
  X.confirmReadings = (period, { buildingId = null, ids = null } = {}) => { Au.need('meterReadings.manage'); const rows = Q.meterRows(period, { buildingId }); const bad = []; let n = 0; rows.forEach(row => ['electric', 'water'].forEach(type => { const m = row[type]; if (!m.cur || (ids && !ids.includes(m.cur.id))) return; if (m.issues.some(i => i === 'new<old' || i === 'duplicate')) { bad.push(row.room.code + ' ' + type); return; } if (m.cur.status === 'draft' || m.cur.status === 'reopened') { m.cur.status = 'confirmed'; m.cur.confirmedBy = me(); m.cur.confirmedAt = F.nowISO(); n++; } }));  St.audit('meter_confirm', 'meterReadings', period, 'Xác nhận ' + n + ' chỉ số kỳ ' + F.periodLabel(period) + (bad.length ? ' (bỏ qua ' + bad.length + ' lỗi)' : '')); done(); return { confirmed: n, skipped: bad }; };
  X.reopenReading = (id, reason) => { if (!['admin', 'accountant', 'qltong'].includes(Au.role())) err('Chỉ Admin / Kế toán được mở lại chỉ số'); const m = St.rawGet('meterReadings', id); if (!m) err('Không tìm thấy chỉ số'); req(reason, 'Nhập lý do mở lại'); if (m.status === 'used') { const line = St.rawAll('invoiceLines').find(l => l && (l.sourceReadingId === id || l.meterId === id)); const inv = line ? St.rawGet('invoices', line.invoiceId) : null; if (inv && inv.docStatus === 'issued') err('Chỉ số đã dùng cho hóa đơn ' + inv.code + ' đã phát hành – hủy/điều chỉnh hóa đơn trước'); } const before = m.status; m.status = 'reopened'; m.reopenedBy = me(); m.reopenReason = reason; St.audit('meter_reopen', 'meterReadings', id, 'Mở lại chỉ số ' + Q.room(m.roomId).code + ' ' + (m.type === 'electric' ? 'điện' : 'nước') + ' kỳ ' + F.periodLabel(m.period) + ': ' + reason, { before: { status: before }, after: { status: 'reopened' }, reason }); done(); return m; };

  /* ================= Kỳ hóa đơn (§12.11.1) ================= */
  X.ensureBillingPeriod = (period) => { let bp = Q.billingPeriod(period); if (bp) return bp; const [y, m] = period.split('-').map(Number); const to = F.toISO(new Date(y, m, 0)); bp = St.add('billingPeriods', { code: period, from: period + '-01', to, closeDate: to, issueDate: F.addDays(to, -5), status: 'OPEN', lockedAt: null, lockedBy: null, note: '' }); return bp; };
  X.setBillingPeriod = (period, patch) => { Au.need('advancedTools'); const bp = X.ensureBillingPeriod(period); if (bp.status === 'LOCKED') err('Kỳ đã khóa'); Object.assign(bp, patch); St.audit('period', 'billingPeriod', bp.id, 'Cập nhật kỳ ' + F.periodLabel(period), { after: patch }); done(); return bp; };
  X.reviewBillingPeriod = (period) => { Au.need('advancedTools'); const bp = X.ensureBillingPeriod(period); if (bp.status === 'LOCKED') err('Kỳ đã khóa'); bp.status = 'REVIEWING'; St.audit('period', 'billingPeriod', bp.id, 'Kỳ ' + F.periodLabel(period) + ' → Đang rà soát'); done(); return bp; };
  X.lockBillingPeriod = (period, { force = false } = {}) => { if (!['admin', 'accountant', 'qltong'].includes(Au.role())) err('Chỉ Admin / Kế toán được khóa kỳ'); const bp = X.ensureBillingPeriod(period); if (bp.status === 'LOCKED') return bp; const st = Q.periodStats(period); if (st.drafts && !force) err('Còn ' + st.drafts + ' hóa đơn nháp của kỳ – phát hành hoặc hủy trước khi khóa'); if (st.readingsPending && !force) err('Còn ' + st.readingsPending + ' chỉ số chưa xác nhận'); Object.assign(bp, { status: 'LOCKED', lockedAt: F.nowISO(), lockedBy: me(), snapshot: st }); St.audit('period_lock', 'billingPeriod', bp.id, 'Khóa kỳ ' + F.periodLabel(period) + ' – ' + st.issued + ' hóa đơn, ' + F.vnd(st.total), { after: st }); done(); return bp; };
  X.reopenBillingPeriod = (period, reason) => { if (!['admin', 'qltong'].includes(Au.role())) err('Chỉ Admin được mở lại kỳ'); const bp = Q.billingPeriod(period); if (!bp || bp.status !== 'LOCKED') err('Kỳ chưa khóa'); req(reason, 'Nhập lý do mở lại'); Object.assign(bp, { status: 'REVIEWING', reopenedAt: F.nowISO(), reopenedBy: me(), reopenReason: reason }); St.audit('period_reopen', 'billingPeriod', bp.id, 'Mở lại kỳ ' + F.periodLabel(period) + ': ' + reason, { reason }); done(); return bp; };
  const lockGuard = (name, periodOf) => { const orig = X[name]; if (!orig) return; X[name] = function () { const p = periodOf.apply(null, arguments); if (p && Q.periodLockedW3(p)) err('Kỳ ' + F.periodLabel(p) + ' đã khóa – mở lại kỳ trước khi thao tác'); return orig.apply(this, arguments); }; };
  lockGuard('createInvoiceDrafts', (d) => d && d.period); lockGuard('issueInvoice', (id) => (St.rawGet('invoices', id) || {}).period); lockGuard('saveMeterReadings', (period) => period);

  /* ================= Thu tiền: chưa xác định / tạm ứng (§4.15) ================= */
  X.recordUnidentified = ({ amount, date, method = 'Chuyển khoản', ref = '', note = '', transferContent = '' }) => { Au.need('payments.record'); const amt = F.num(amount); if (amt <= 0) err('Số tiền phải > 0'); req(date, 'Ngày nhận'); const p = St.add('payments', { code: St.nextCode('payments', 'PAY-' + periodCode(F.period(date)) + '-', 3), tenantId: null, roomId: null, buildingId: null, date, amount: amt, method, ref, evidence: '', note, status: 'recorded', unidentified: true, transferContent, createdBy: me(), bank: method === 'Chuyển khoản' ? 'Vietcombank' : '' }); St.audit('payment', 'payment', p.id, 'Tiền chưa xác định ' + p.code + ' ' + F.vnd(amt) + (transferContent ? ' – "' + transferContent + '"' : '')); done(); return p; };
  X.matchPayment = (paymentId, { tenantId, allocations = [], advance = false }) => { Au.need('payments.record'); const p = St.rawGet('payments', paymentId); if (!p) err('Không tìm thấy khoản thu'); req(tenantId, 'Chọn khách'); const t = Q.tenant(tenantId); if (!t.id) err('Không tìm thấy khách'); const allocs = allocations.map(a => ({ invoiceId: a.invoiceId, amount: F.num(a.amount) })).filter(a => a.amount > 0); const already = F.sum(St.rawAll('paymentAllocations').filter(a => a && a.paymentId === paymentId), a => a.amount); if (already + F.sum(allocs, a => a.amount) > Number(p.amount) + 0.5) err('Tổng phân bổ vượt số tiền'); allocs.forEach(a => { const inv = St.rawGet('invoices', a.invoiceId); if (!inv || inv.tenantId !== tenantId) err('Hóa đơn không thuộc khách'); if (a.amount > Q.invRemaining(inv) + 0.5) err('Phân bổ vượt số còn lại của ' + inv.code); St.add('paymentAllocations', { paymentId, invoiceId: a.invoiceId, amount: a.amount }); }); const room = Q.tenantRoomNow(t); Object.assign(p, { tenantId, roomId: room ? room.id : p.roomId, buildingId: room ? room.buildingId : p.buildingId, unidentified: false, advance: !!advance, matchedAt: F.nowISO(), matchedBy: me() }); St.audit('match', 'payment', paymentId, 'Ghép khoản thu ' + p.code + ' → ' + t.name + (allocs.length ? ' (' + allocs.length + ' hóa đơn)' : advance ? ' (tạm ứng)' : ''), { after: { tenantId, allocations: allocs, advance } }); done(); return p; };
  X.markAdvance = (paymentId, advance = true) => { Au.need('payments.record'); const p = St.rawGet('payments', paymentId); if (!p) err('Không tìm thấy khoản thu'); p.advance = !!advance; St.audit('payment', 'payment', paymentId, (advance ? 'Đánh dấu tạm ứng ' : 'Bỏ đánh dấu tạm ứng ') + p.code); done(); return p; };

  /* ================= HĐ đầu vào (§12.3) ================= */
  wrap('saveLandlordContract', (c, args) => { const d = args[0] || {}; if (!c) return; if (c.hkdStatus == null) c.hkdStatus = d.hkdStatus || 'unregistered'; if (!c.pccc) c.pccc = d.pccc || { status: 'none', expiry: '' }; if (d.priceSchedule) c.priceSchedule = d.priceSchedule; if (d.dueDay != null) c.dueDay = Number(d.dueDay) || 5; if (d.bankAccount) c.bankAccount = d.bankAccount; if (d.buildingType) { c.buildingType = d.buildingType; c.typeEffectiveFrom = d.typeEffectiveFrom || c.start; } if (d.handoverAssets) c.handoverAssets = d.handoverAssets; if (d.contractNo) c.contractNo = d.contractNo; if (!c.status) c.status = 'active'; if (d.status) c.status = d.status; St.save(); });
  const applyLcType = (lc) => { if (!lc.buildingType || !X.setBuildingType) return; (lc.buildingIds || []).forEach(bid => { const cur = Q.buildingTypeAt(bid, lc.typeEffectiveFrom || lc.start); if (cur === lc.buildingType) return; try { X.setBuildingType({ buildingId: bid, type: lc.buildingType, effectiveFrom: lc.typeEffectiveFrom || lc.start, reason: 'Theo HĐ đầu vào ' + lc.code, sourceType: 'landlordContract', sourceId: lc.id }); } catch (e) { console.warn('lc type', e.message); } }); };
  X.activateLandlordContract = (id) => { Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); if (lc.status !== 'draft') err('Chỉ kích hoạt HĐ Dự thảo'); lc.status = 'active'; lc.activatedAt = F.nowISO(); lc.activatedBy = me(); applyLcType(lc); St.audit('activate', 'landlordContract', id, 'Kích hoạt HĐ đầu vào ' + lc.code); done(); return lc; };
  X.endLandlordContract = (id, { end, reason = '' } = {}) => { Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); if (lc.status === 'ended') err('HĐ đã kết thúc'); const active = (lc.buildingIds || []).filter(bid => St.rawAll('contracts').some(c => c && c.buildingId === bid && live(c))); if (active.length && !reason) err('Tòa còn ' + active.length + ' HĐ thuê hiệu lực – nhập lý do kết thúc sớm'); Object.assign(lc, { status: 'ended', end: end || F.today(), endReason: reason, endedAt: F.nowISO(), endedBy: me() }); St.audit('end', 'landlordContract', id, 'Kết thúc HĐ đầu vào ' + lc.code + (reason ? ': ' + reason : ''), { reason }); done(); return lc; };
  X.renewLandlordContract = (id, { end, rent, deposit, signedDate } = {}) => { Au.need('landlords.manage'); const old = St.get('landlordContracts', id); if (!old) err('Không tìm thấy HĐ đầu vào'); req(end, 'Ngày kết thúc mới'); if (end <= old.end) err('Ngày kết thúc mới phải sau ' + F.date(old.end)); const n = St.add('landlordContracts', Object.assign({}, old, { id: undefined, code: old.code + '-GH' + ((old.renewalNo || 0) + 1), status: 'draft', start: F.addDays(old.end, 1), end, rent: rent != null ? F.num(rent) : old.rent, deposit: deposit != null ? F.num(deposit) : old.deposit, signedDate: signedDate || F.today(), renewedFromId: old.id, renewalNo: (old.renewalNo || 0) + 1, createdAt: undefined, source: undefined, activatedAt: null, priceSchedule: [] })); old.renewedToId = n.id; St.audit('renew', 'landlordContract', id, 'Lập HĐ đầu vào gia hạn ' + n.code + ' (dự thảo) đến ' + F.date(end)); done(); return n; };
  X.setHkdStatus = (id, status, reason = '', opts = {}) => { if (!opts.auto) Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); if (!['registered', 'unregistered'].includes(status)) err('Trạng thái HKD không hợp lệ'); if (!opts.auto && !reason) err('Nhập lý do thay đổi trạng thái HKD'); const before = lc.hkdStatus || 'unregistered'; if (before === status) return lc; lc.hkdStatus = status; (lc.hkdHistory = lc.hkdHistory || []).push({ at: F.nowISO(), by: me(), from: before, to: status, reason: reason || (opts.auto ? 'Tự động khi thêm Giấy đăng ký HKD' : ''), docId: opts.docId || null }); St.audit('hkd', 'landlordContract', id, 'Trạng thái HKD ' + lc.code + ': ' + Q.label('hkd', before) + ' → ' + Q.label('hkd', status) + (reason ? ' – ' + reason : ''), { before: { hkdStatus: before }, after: { hkdStatus: status }, reason }); done(); return lc; };
  X.setPccc = (id, { status, expiry = '', note = '' }) => { Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); const before = lc.pccc || {}; lc.pccc = { status: status || 'none', expiry, note }; St.audit('pccc', 'landlordContract', id, 'Cập nhật PCCC ' + lc.code + ': ' + Q.label('pccc', lc.pccc.status) + (expiry ? ' đến ' + F.date(expiry) : ''), { before, after: lc.pccc }); done(); return lc; };
  X.savePriceSchedule = (id, rows) => { Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); const list = (rows || []).filter(x => x && x.from && F.num(x.price) > 0).map(x => ({ from: x.from, price: F.num(x.price), note: x.note || '' })).sort((a, b) => F.cmp(a.from, b.from)); const before = lc.priceSchedule || []; lc.priceSchedule = list; (lc.priceHistory = lc.priceHistory || []).push({ at: F.nowISO(), by: me(), schedule: list }); St.audit('price_schedule', 'landlordContract', id, 'Cập nhật lịch tăng giá ' + lc.code + ' (' + list.length + ' mốc)', { before, after: list }); done(); return lc; };
  X.setLcBuildingType = (id, { type, effectiveFrom, reason = '' }) => { Au.need('landlords.manage'); const lc = St.get('landlordContracts', id); if (!lc) err('Không tìm thấy HĐ đầu vào'); req(type, 'Chọn loại tòa'); req(effectiveFrom, 'Ngày hiệu lực'); lc.buildingType = type; lc.typeEffectiveFrom = effectiveFrom; if (lc.status !== 'draft') (lc.buildingIds || []).forEach(bid => X.setBuildingType({ buildingId: bid, type, effectiveFrom, reason: reason || 'Theo HĐ đầu vào ' + lc.code, sourceType: 'landlordContract', sourceId: lc.id })); St.audit('lc_type', 'landlordContract', id, 'Ký hiệu loại tòa theo HĐ ' + lc.code + ' → ' + type + ' từ ' + F.date(effectiveFrom), { after: { type, effectiveFrom }, reason }); done(); return lc; };

  /* ================= Tài liệu: docType, phiên bản, HKD tự động (§4.5, §7.3) ================= */
  const LABEL_DOCTYPE = [[/hkd|hộ kinh doanh|đkkd|dkkd/i, 'hkd'], [/pccc/i, 'pccc'], [/sổ đỏ|so do/i, 'deed'], [/phụ lục/i, 'annex'], [/hợp đồng|hop dong|hd_/i, 'contract'], [/bàn giao/i, 'handover'], [/cccd|cmnd|giấy tờ khách/i, 'id'], [/biên lai|chứng từ|uy_nhiem/i, 'receipt'], [/\.(jpe?g|png)$/i, 'photo']];
  X.guessDocType = (name) => { const s = String(name || ''); const hit = LABEL_DOCTYPE.find(([re]) => re.test(s)); return hit ? hit[1] : 'other'; };
  wrap('addDocument', (d, args) => { if (!d) return; const file = args[2] || {}; d.docType = file.docType || X.guessDocType(d.name || d.fileName); d.version = d.version || 1; if (file.supersedesId) { const old = St.rawGet('documents', file.supersedesId); if (old) { old.supersededById = d.id; d.version = (Number(old.version) || 1) + 1; d.supersedesId = old.id; St.audit('replace', d.entityType, d.entityId, 'Thay thế tài liệu ' + (old.name || old.fileName) + ' → phiên bản ' + d.version + ' (file cũ được giữ)'); } }
    // §4.5: tài liệu "Giấy đăng ký HKD" gắn đúng HĐ đầu vào / tòa / chủ nhà → HKD = Đã đăng ký
    if (d.docType === 'hkd') { let lcs = []; if (d.entityType === 'landlordContract') lcs = [St.rawGet('landlordContracts', d.entityId)]; else if (d.entityType === 'building') lcs = St.rawAll('landlordContracts').filter(x => x && (x.buildingIds || []).includes(d.entityId) && x.status !== 'ended'); else if (d.entityType === 'landlord') lcs = St.rawAll('landlordContracts').filter(x => x && x.landlordId === d.entityId && x.status !== 'ended'); lcs.filter(Boolean).forEach(lc => { if ((lc.hkdStatus || 'unregistered') !== 'registered') X.setHkdStatus(lc.id, 'registered', '', { auto: true, docId: d.id }); }); }
    St.save(); });
  X.replaceDocument = (oldId, file) => { const old = St.rawGet('documents', oldId); if (!old) err('Không tìm thấy tài liệu'); return X.addDocument(old.entityType, old.entityId, Object.assign({}, file, { supersedesId: oldId, docType: file.docType || old.docType })); };

  /* ================= Khách: trạng thái & bulk (§4.8, §12.6.5) ================= */
  X.setTenantStatus = (id, status, reason = '') => { const t = St.get('tenants', id); if (!t) err('Không tìm thấy khách'); Au.need('tenants.manage', { type: 'tenant', record: t }); if (!Q.customerStatusOptions().some(o => o[0] === status)) err('Trạng thái không hợp lệ'); const before = t.status || 'active'; if (before === status) return t; t.status = status; t.statusAt = F.nowISO(); t.statusBy = me(); St.audit('status', 'tenant', id, 'Trạng thái khách ' + t.name + ': ' + before + ' → ' + status + (reason ? ' – ' + reason : ''), { before: { status: before }, after: { status }, reason }); done(); return t; };
  X.bulkTenantStatus = (ids, status, reason = '') => { Au.need('tenants.manage'); if (!ids || !ids.length) err('Chưa chọn khách'); if (!Q.customerStatusOptions().some(o => o[0] === status)) err('Trạng thái không hợp lệ'); const batchId = 'bulk-' + Date.now().toString(36); let n = 0; ids.forEach(id => { const t = St.get('tenants', id); if (!t) return; if (!Au.inScope('tenant', t)) return; const before = t.status || 'active'; if (before === status) return; t.status = status; t.statusAt = F.nowISO(); t.statusBy = me(); St.audit('status', 'tenant', id, 'Trạng thái khách ' + t.name + ': ' + before + ' → ' + status + ' (batch)', { before: { status: before }, after: { status }, reason, batchId }); n++; }); St.audit('bulk_status', 'tenant', null, 'Cập nhật trạng thái hàng loạt → ' + status + ' cho ' + n + '/' + ids.length + ' khách' + (reason ? ' – ' + reason : ''), { batchId, after: { status, count: n }, reason }); done(); return { batchId, updated: n }; };
  /* Export theo đúng filter (§12.6.6): file ghi thời điểm, người xuất, điều kiện lọc */
  X.exportCsv = ({ fileName, header, rows, filters = {}, entity = '' }) => { const meta = ['# Xuất lúc ' + F.datetime(F.nowISO()) + ' bởi ' + meName() + ' (' + Au.role() + ')', '# Điều kiện lọc: ' + (Object.entries(filters).filter(([, v]) => v).map(([k, v]) => k + '=' + v).join('; ') || 'không'), '# Số dòng: ' + rows.length]; const csv = meta.join('\n') + '\n' + F.csv(rows, header); F.download(fileName, csv); St.audit('export', entity || 'export', null, 'Xuất ' + fileName + ' (' + rows.length + ' dòng)', { after: { filters, count: rows.length } }); return csv; };
})(window.TH);

