/* Actions Phase 3 – mở rộng TH.actions. Ném Error khi vi phạm quy tắc; UI bắt và toast. Chỉ có tác dụng khi TH.phase.on(3).
   Nguyên tắc SRS: kiểm kê không tự tạo chi phí/giảm tài sản (FR-MNT-02); nghỉ việc giữ tham chiếu (FR-HR-01); tỷ lệ vốn nhập tay (FR-SHR-02);
   bảng phân phối ≠ đã chuyển tiền (UC-08); chi lương/mua sắm qua chi phí P1 và bị chặn khi kỳ khóa (FR-FIN-08). */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, Au = TH.auth, X = TH.actions;
  const err = (m) => { throw new Error(m); };
  const req = (v, m) => { if (v === undefined || v === null || v === '' || (typeof v === 'number' && isNaN(v))) err(m); return v; };
  const me = () => (St.state.session || {}).userId || null;
  const done = () => { St.save(); St.emit('change'); };
  const on3 = () => TH.phase && TH.phase.on(3);
  const need3 = () => { if (!on3()) err('Chức năng thuộc Phase 3 – bật Phase 3 trong Công cụ nâng cao'); };
  const idem = (key, fn) => { if (!key) return fn(); St.state.meta.idem = St.state.meta.idem || {}; if (St.state.meta.idem[key]) return Object.assign({ duplicate: true }, St.state.meta.idem[key]); const res = fn(); try { St.state.meta.idem[key] = JSON.parse(JSON.stringify(res)); } catch (e) { St.state.meta.idem[key] = { id: res && res.id, code: res && res.code }; } St.save(); return res; };
  const periodOpen = (period, what) => { if (X.assertPeriodOpen) X.assertPeriodOpen(period, what); };
  const hist = (e, type, text) => { (e.history = e.history || []).push({ at: F.nowISO(), type, text, by: me() }); };
  const COND_ROOM = { good: 'Tốt', minor: 'Cần bảo dưỡng', replace: 'Hỏng', broken: 'Hỏng', lost: 'Hỏng' };
  const syncRoomAsset = (a) => { if (!a.roomAssetId) return; const ra = St.get('roomAssets', a.roomAssetId); if (ra) { ra.condition = COND_ROOM[a.condition] || 'Tốt'; } };

  /* ================= Tài sản ================= */
  X.saveAsset = (d) => {
    need3(); Au.need('assets.manage', d.buildingId ? { buildingId: d.buildingId } : null); req(d.name, 'Tên tài sản'); req(d.category, 'Loại tài sản'); req(d.buildingId, 'Tòa nhà');
    const room = d.roomId ? St.get('rooms', d.roomId) : null; if (d.roomId && !room) err('Phòng không hợp lệ');
    const payload = { name: d.name.trim(), category: d.category, buildingId: d.buildingId, roomId: room ? room.id : null, area: room ? room.code : (d.area || 'Khu vực chung'), qty: Math.max(1, F.num(d.qty) || 1), cost: F.num(d.cost) || 0, startDate: d.startDate || F.today(), depMonths: F.num(d.depMonths) || 36, ownership: d.ownership || 'company', note: d.note || '' };
    let a;
    if (d.id) { a = St.get('assets', d.id); if (!a) err('Không tìm thấy tài sản'); Object.assign(a, payload); hist(a, 'edit', 'Cập nhật thông tin'); }
    else {
      a = St.add('assets', Object.assign({ code: St.nextCode('assets', 'TS-', 4), condition: d.condition || 'good', status: 'active', qr: '', history: [], createdBy: me() }, payload)); a.qr = 'QR-' + a.code.slice(3); hist(a, 'create', 'Ghi nhận vào sổ tài sản');
      if (room) { const ra = St.add('roomAssets', { roomId: room.id, name: a.name, qty: a.qty, condition: COND_ROOM[a.condition] }); a.roomAssetId = ra.id; }
      if (d.recordExpense && a.cost > 0) { // BR-08: tiền mua ghi dòng tiền 1 lần; khấu hao vào kết quả vận hành – không ghi 2 lần
        periodOpen(F.period(a.startDate), 'ghi nhận chi phí mua sắm');
        const ex = X.saveExpense({ date: a.startDate, group: 'Mua sắm TS', desc: 'Mua ' + a.name + ' (' + a.code + ')', buildingId: a.buildingId, amount: a.cost * a.qty, recordType: 'asset', method: 'depreciation', depreciationMonths: a.depMonths, note: 'Tự tạo từ sổ tài sản', evidence: '' });
        a.expenseId = ex.id; hist(a, 'expense', 'Ghi nhận chi phí ' + ex.code + ' – khấu hao ' + a.depMonths + ' tháng');
      }
    }
    St.audit('save', 'asset', a.id, (d.id ? 'Cập nhật' : 'Thêm') + ' tài sản ' + a.code + ' ' + a.name); done(); return a;
  };
  X.setAssetCondition = (id, condition, note) => { need3(); const a = St.get('assets', id); if (!a) err('Không tìm thấy tài sản'); if (!Q.L.assetCond[condition]) err('Tình trạng không hợp lệ'); Au.need(Au.can('inventory.record') ? 'inventory.record' : 'assets.manage', { buildingId: a.buildingId }); const prev = a.condition; a.condition = condition; syncRoomAsset(a); hist(a, 'condition', Q.label('assetCond', prev) + ' → ' + Q.label('assetCond', condition) + (note ? ' – ' + note : '')); St.audit('condition', 'asset', a.id, 'Đổi tình trạng ' + a.code + ': ' + Q.label('assetCond', condition)); done(); return a; };
  X.disposeAsset = (id, reason) => { need3(); Au.need('assets.manage'); const a = St.get('assets', id); if (!a) err('Không tìm thấy tài sản'); if (a.status === 'disposed') err('Tài sản đã thanh lý'); a.status = 'disposed'; a.disposedAt = F.nowISO(); a.disposeReason = reason || ''; hist(a, 'dispose', 'Thanh lý – ' + (reason || 'không ghi lý do')); if (a.roomAssetId) { St.remove('roomAssets', a.roomAssetId); } St.audit('dispose', 'asset', a.id, 'Thanh lý tài sản ' + a.code); done(); return a; };

  /* ================= Kiểm kê (FR-MNT-02) ================= */
  X.startInventory = ({ period, buildingIds, note }) => {
    need3(); Au.need('inventory.manage'); req(period, 'Kỳ kiểm kê'); if (!/^\d{4}-\d{2}$/.test(period)) err('Kỳ phải có dạng YYYY-MM');
    const live = St.where('buildings', b => !b.stub).map(b => b.id); const ids = (buildingIds && buildingIds.length ? buildingIds : live).filter(id => live.includes(id)); if (!ids.length) err('Chọn ít nhất một tòa');
    const exist = St.one('inventories', i => i.period === period); if (exist) { if (exist.status === 'done') err('Kỳ ' + F.periodLabel(period) + ' đã có biên bản hoàn thành ' + exist.code); return Object.assign({ existed: true }, exist); }
    const inv = St.add('inventories', { code: 'BB-KK-' + period, period, buildingIds: ids, status: 'in_progress', startDate: F.today(), finishedAt: null, createdBy: me(), note: note || '', summary: null });
    const assets = St.where('assets', a => a.status === 'active' && ids.includes(a.buildingId)); assets.forEach(a => St.add('inventoryLines', { inventoryId: inv.id, assetId: a.id, prevCondition: a.condition, condition: null, checkedBy: null, checkedAt: null, photo: false, note: '', status: 'pending' }));
    inv.summary = Q.inventoryStats(inv); St.audit('create', 'inventory', inv.id, 'Bắt đầu kiểm kê ' + inv.code + ' (' + assets.length + ' tài sản)'); done(); return inv;
  };
  X.recordInventoryLine = (lineId, { condition, note, photo }) => {
    need3(); const l = St.get('inventoryLines', lineId); if (!l) err('Không tìm thấy dòng kiểm kê'); const inv = St.get('inventories', l.inventoryId); if (!inv || inv.status === 'done') err('Đợt kiểm kê đã hoàn thành – không sửa được');
    const a = St.get('assets', l.assetId); Au.need('inventory.record', { buildingId: a.buildingId }); if (!Q.L.assetCond[condition]) err('Chọn tình trạng');
    l.prevCondition = l.status === 'pending' ? a.condition : l.prevCondition; l.condition = condition; l.note = note || ''; l.photo = !!photo; l.checkedBy = (St.state.session || {}).name; l.checkedById = me(); l.checkedAt = F.nowISO(); l.status = condition === 'good' ? 'done' : 'needs_action';
    if (a.condition !== condition) { a.condition = condition; syncRoomAsset(a); hist(a, 'inventory', 'Kiểm kê ' + inv.code + ': ' + Q.label('assetCond', condition) + (note ? ' – ' + note : '')); }
    inv.summary = Q.inventoryStats(inv); St.audit('record', 'inventory', inv.id, 'Ghi kết quả ' + a.code + ' – ' + Q.label('assetCond', condition)); done(); return l;
  };
  X.bulkInventoryGood = (lineIds) => { need3(); let n = 0; lineIds.forEach(id => { const l = St.get('inventoryLines', id); if (l && l.status === 'pending') { X.recordInventoryLine(id, { condition: 'good' }); n++; } }); return n; };
  X.finishInventory = (id) => { // AC-FR-MNT-02-2: chỉ chốt kết quả; không tạo chi phí, không giảm tài sản
    need3(); Au.need('inventory.manage'); const inv = St.get('inventories', id); if (!inv) err('Không tìm thấy đợt kiểm kê'); if (inv.status === 'done') return inv;
    const stats = Q.inventoryStats(inv); if (!stats.checked) err('Chưa có tài sản nào được kiểm kê');
    inv.status = 'done'; inv.finishedAt = F.nowISO(); inv.finishedBy = me(); inv.summary = stats; St.audit('finish', 'inventory', inv.id, 'Hoàn tất kiểm kê ' + inv.code + ': ' + stats.checked + '/' + stats.total + ' tài sản, ' + stats.needsAction + ' cần xử lý'); done(); return inv;
  };
  X.exportInventory = (id) => { const inv = St.get('inventories', id); if (!inv) err('Không tìm thấy đợt kiểm kê'); const rows = Q.inventoryLines(inv).map(({ line, asset }) => [asset.code, asset.name, Q.building(asset.buildingId).name, asset.area, Q.label('assetCond', line.prevCondition || asset.condition), line.condition ? Q.label('assetCond', line.condition) : '', line.checkedBy || '', line.checkedAt ? F.datetime(line.checkedAt) : '', Q.label('invLine', line.status), line.note || '']); F.download(inv.code + '.csv', F.csv(rows, ['Mã tài sản', 'Tên', 'Tòa', 'Khu vực', 'Tình trạng trước', 'Tình trạng hiện tại', 'Người kiểm kê', 'Ngày kiểm kê', 'Trạng thái', 'Ghi chú']), 'text/csv'); return rows.length; };
  X.incidentFromLine = (lineId) => { need3(); const l = St.get('inventoryLines', lineId); const a = St.get('assets', l.assetId); if (!(TH.phase.on(2) && X.saveIncident)) err('Tạo sự cố thuộc Phase 2 – bật Phase 2 để lập sự cố từ kết quả kiểm kê'); if (l.incidentId) return St.get('incidents', l.incidentId); const inc = X.saveIncident({ buildingId: a.buildingId, roomId: a.roomId || '', category: ({ dienlanh: 'Điều hòa', pccc: 'PCCC', thangmay: 'Thang máy', chieusang: 'Chiếu sáng', dien: 'Điện', noithat: 'Nội thất' })[a.category] || 'Khác', priority: ['replace', 'broken'].includes(l.condition) ? 'high' : 'medium', desc: 'Từ kiểm kê ' + Q.inventory(l.inventoryId).code + ': ' + a.code + ' ' + a.name + ' – ' + Q.label('assetCond', l.condition) + (l.note ? '. ' + l.note : ''), assetId: a.id }); l.incidentId = inc.id; done(); return inc; };

  /* ================= Nhân sự (FR-HR-01/03, FR-BLD-07) ================= */
  X.saveEmployee = (d) => {
    need3(); Au.need('hr.manage'); req(d.name, 'Họ tên'); req(d.dept, 'Phòng ban'); req(d.title, 'Chức danh'); req(d.phone, 'Số điện thoại'); req(d.startDate, 'Ngày vào làm');
    const dup = St.one('employees', e => e.phone.replace(/\s/g, '') === String(d.phone).replace(/\s/g, '') && e.id !== d.id); if (dup) err('Số điện thoại đã thuộc nhân viên ' + dup.code + ' – ' + dup.name);
    const payload = { name: d.name.trim(), dept: d.dept, title: d.title, phone: d.phone, email: d.email || '', address: d.address || '', workType: d.workType || 'Toàn thời gian', managerId: d.managerId || null, area: d.area || 'Tất cả khu vực', startDate: d.startDate, probationEnd: d.probationEnd || null, note: d.note || '' };
    if (Au.can('hr.manage')) { payload.salaryBase = F.num(d.salaryBase) || 0; payload.titleAllowance = F.num(d.titleAllowance) || 0; }
    let e; if (d.id) { e = St.get('employees', d.id); if (!e) err('Không tìm thấy nhân viên'); Object.assign(e, payload); hist(e, 'profile', 'Cập nhật hồ sơ'); }
    else { e = St.add('employees', Object.assign({ code: St.nextCode('employees', 'NV', 3), status: d.probationEnd && d.probationEnd >= F.today() ? 'probation' : (d.status || 'working'), documents: [], history: [], userId: null, createdBy: me() }, payload)); hist(e, 'join', 'Vào làm – ' + e.title); }
    St.audit('save', 'employee', e.id, (d.id ? 'Cập nhật' : 'Thêm') + ' nhân viên ' + e.code + ' ' + e.name); done(); return e;
  };
  X.setEmployeeStatus = (id, status, reason) => { // AC-FR-HR-01-1: nghỉ việc không xóa – chứng từ cũ vẫn tham chiếu tên
    need3(); Au.need('hr.manage'); const e = St.get('employees', id); if (!e) err('Không tìm thấy nhân viên'); if (!Q.L.employee[status]) err('Trạng thái không hợp lệ'); if (e.status === status) return e;
    const prev = e.status; e.status = status; if (status === 'resigned') { e.resignedAt = F.today(); St.where('buildingAssignments', a => a.employeeId === e.id && a.status === 'active').forEach(a => { a.status = 'ended'; a.end = F.today(); }); if (e.userId) { const u = St.get('users', e.userId); if (u && u.role !== 'admin') u.status = 'expired'; } }
    hist(e, 'status', Q.label('employee', prev) + ' → ' + Q.label('employee', status) + (reason ? ' – ' + reason : '')); St.audit('status', 'employee', e.id, e.code + ' ' + e.name + ': ' + Q.label('employee', status)); done(); return e;
  };
  X.assignBuilding = ({ employeeId, buildingId, role, primary, start }) => {
    need3(); Au.need('hr.manage'); const e = St.get('employees', employeeId); if (!e) err('Không tìm thấy nhân viên'); req(buildingId, 'Tòa nhà'); req(role, 'Vai trò phụ trách'); if (e.status === 'resigned') err('Nhân viên đã nghỉ việc');
    const cur = St.one('buildingAssignments', a => a.employeeId === e.id && a.buildingId === buildingId && a.status === 'active'); if (cur) err('Nhân viên đang phụ trách tòa này (' + Q.label('assignRole', cur.role) + ')');
    if (primary) St.where('buildingAssignments', a => a.employeeId === e.id && a.status === 'active' && a.primary).forEach(a => { a.primary = false; });
    const a = St.add('buildingAssignments', { employeeId: e.id, buildingId, role, primary: !!primary, start: start || F.today(), end: null, status: 'active', by: me() });
    hist(e, 'assign', 'Phân công ' + Q.building(buildingId).name + ' – ' + Q.label('assignRole', role) + (primary ? ' (chính)' : '')); St.audit('assign', 'employee', e.id, e.name + ' phụ trách ' + Q.building(buildingId).name); done(); return a;
  };
  X.endAssignment = (id) => { need3(); Au.need('hr.manage'); const a = St.get('buildingAssignments', id); if (!a || a.status !== 'active') err('Phân công không còn hiệu lực'); a.status = 'ended'; a.end = F.today(); const e = St.get('employees', a.employeeId); if (e) hist(e, 'assign', 'Kết thúc phụ trách ' + Q.building(a.buildingId).name); done(); return a; };
  X.addEmployeeDoc = (id, { name, fileName, size }) => { need3(); Au.need('hr.manage'); const e = St.get('employees', id); if (!e) err('Không tìm thấy nhân viên'); req(name, 'Loại tài liệu'); req(fileName, 'File'); const doc = { id: F.uid('doc'), name, fileName, date: F.today(), size: size || '' }; (e.documents = e.documents || []).push(doc); hist(e, 'doc', 'Thêm tài liệu ' + name); done(); return doc; };
  X.removeEmployeeDoc = (id, docId) => { need3(); Au.need('hr.manage'); const e = St.get('employees', id); e.documents = (e.documents || []).filter(x => x.id !== docId); done(); };

  /* ================= Chấm công (mô phỏng – ngoài SRS §2.2) ================= */
  const ensureSheet = (employeeId, period) => { let t = Q.timesheet(employeeId, period); if (!t) t = St.add('timesheets', { employeeId, period, days: {}, workDays: 0, offDays: 0, late: 0, otHours: 0, status: 'draft' }); return t; };
  const recount = (t) => { let w = 0, off = 0; Object.values(t.days || {}).forEach(c => { if (c === 'P') w++; else if (c === 'H') w += .5; else if (c === 'L' || c === 'A') off++; }); t.workDays = w; t.offDays = off; };
  X.markAttendance = (employeeId, date, code) => { need3(); Au.need('timesheet.manage'); if (!Q.L.attCode[code]) err('Ký hiệu không hợp lệ'); const t = ensureSheet(employeeId, F.period(date)); if (t.status === 'confirmed') err('Bảng công ' + F.periodLabel(t.period) + ' đã xác nhận – không sửa'); t.days[date] = code; recount(t); done(); return t; };
  X.fillTimesheet = (period, f = {}) => { need3(); Au.need('timesheet.manage'); const [y, m] = period.split('-').map(Number); const n = new Date(y, m, 0).getDate(); const upto = F.period(F.today()) === period ? F.today() : (period < F.period(F.today()) ? period + '-' + F.pad(n) : null); if (!upto) err('Chưa đến kỳ ' + F.periodLabel(period)); let filled = 0; Q.filterEmployees(f).forEach(e => { const t = ensureSheet(e.id, period); if (t.status === 'confirmed') return; for (let d = 1; d <= n; d++) { const iso = period + '-' + F.pad(d); if (iso > upto) break; if (t.days[iso]) continue; t.days[iso] = new Date(y, m - 1, d).getDay() === 0 ? 'O' : (e.status === 'leave' ? 'L' : 'P'); filled++; } recount(t); }); done(); return filled; };
  X.confirmTimesheet = (period, f = {}) => { need3(); Au.need('timesheet.manage'); let n = 0; Q.filterEmployees(f).forEach(e => { const t = ensureSheet(e.id, period); if (t.status === 'confirmed') return; if (!Object.keys(t.days).length) return; t.status = 'confirmed'; t.confirmedBy = me(); t.confirmedAt = F.nowISO(); n++; }); if (!n) err('Không có bảng công nào để xác nhận (chưa chấm công hoặc đã xác nhận)'); St.audit('confirm', 'timesheet', period, 'Xác nhận bảng công ' + F.periodLabel(period) + ' – ' + n + ' nhân viên'); done(); return n; };

  /* ================= Lương (FR-HR-02 / BR-14 – công thức TBD OI-15) ================= */
  const BUILDING_ALLOW = 500000; // phụ cấp số nhà (vận hành) – đơn giá mẫu, OI-15
  X.payrollLines = (period) => Q.filterEmployees().map(e => { const ts = Q.timesheet(e.id, period); const std = Q.workDaysStd(period); const wd = ts ? ts.workDays : std; const nB = Q.assignmentsOf(e.id).length; const bAllow = e.dept === 'vanhanh' ? nB * BUILDING_ALLOW : 0; const comm = e.dept === 'kinhdoanh' && e.userId ? F.sum(St.where('commissions', c => c.status === 'paid' && F.period(c.paidAt || c.paidDate || c.updatedAt || c.createdAt) === period && (Q.deal(c.dealId) || {}).saleId === e.userId), c => c.amount || 0) : 0; const base = Math.round((e.salaryBase || 0) * Math.min(1, wd / std) / 1000) * 1000; const ded = Math.round(base * 0.105 / 1000) * 1000; return { employeeId: e.id, base, titleAllowance: e.titleAllowance || 0, buildingAllowance: bAllow, buildingCount: nB, commission: comm, deductions: ded, total: base + (e.titleAllowance || 0) + bAllow + comm - ded, workDays: wd, std }; });
  X.buildPayroll = (period) => { need3(); Au.need('payroll.manage'); req(period, 'Kỳ lương'); let p = Q.payroll(period); if (p && !['draft'].includes(p.status)) err('Bảng lương ' + F.periodLabel(period) + ' đang ' + Q.label('payroll', p.status) + ' – không tính lại'); const ts = Q.timesheetStats(period); const lines = X.payrollLines(period); if (!p) p = St.add('payrolls', { code: 'BL-' + period, period, status: 'draft', lines, total: F.sum(lines, l => l.total), createdBy: me(), expenseIds: [], note: '' }); else { p.lines = lines; p.total = F.sum(lines, l => l.total); p.updatedAt = F.nowISO(); } p.note = ts.confirmed ? 'Tính từ bảng công đã xác nhận' : 'Bảng công chưa xác nhận đủ – số tạm tính'; St.audit('build', 'payroll', p.id, 'Tính bảng lương ' + p.code + ' ' + F.vnd(p.total)); done(); return p; };
  X.submitPayroll = (period) => { need3(); Au.need('payroll.manage'); const p = Q.payroll(period); if (!p) err('Chưa tính bảng lương'); if (p.status !== 'draft') err('Bảng lương không ở trạng thái Nháp'); if (!Q.timesheetStats(period).confirmed) err('Xác nhận bảng công ' + F.periodLabel(period) + ' trước khi gửi duyệt'); p.status = 'review'; p.submittedAt = F.nowISO(); p.submittedBy = me(); St.audit('submit', 'payroll', p.id, 'Gửi duyệt ' + p.code); done(); return p; };
  X.approvePayroll = (period) => { need3(); Au.need('payroll.approve'); const p = Q.payroll(period); if (!p || p.status !== 'review') err('Bảng lương chưa ở trạng thái Chờ duyệt'); p.status = 'approved'; p.approvedAt = F.nowISO(); p.approvedBy = me(); St.audit('approve', 'payroll', p.id, 'Duyệt ' + p.code); done(); return p; };
  X.payPayroll = (period, { date, ref } = {}) => idem('payroll:' + period, () => { // → chi phí nhóm Lương theo tòa (FR-FIN-12); kỳ khóa → chặn (FR-FIN-08)
    need3(); Au.need('payroll.approve'); const p = Q.payroll(period); if (!p || p.status !== 'approved') err('Bảng lương chưa được duyệt'); const d = date || F.today(); periodOpen(F.period(d), 'ghi nhận chi lương');
    const by = Q.payrollByBuilding(p); const ids = []; const bs = St.where('buildings', b => !b.stub);
    by.forEach(x => { const b = bs.find(bb => bb.name.replace('Tòa ', '') === x.label); const ex = X.saveExpense({ date: d, group: 'Lương', desc: 'Chi lương ' + F.periodLabel(period) + (b ? ' – ' + b.name : ' – chung'), buildingId: b ? b.id : null, amount: x.value, recordType: 'ops', method: 'bank', evidence: ref || p.code, note: 'Tự tạo từ bảng lương ' + p.code, allocations: b ? [] : bs.map((bb, i) => ({ buildingId: bb.id, pct: i === bs.length - 1 ? 100 - Math.floor(100 / bs.length) * (bs.length - 1) : Math.floor(100 / bs.length) })) }); ids.push(ex.id); });
    p.status = 'paid'; p.paidAt = F.nowISO(); p.paidBy = me(); p.paidDate = d; p.ref = ref || ''; p.expenseIds = ids; St.audit('pay', 'payroll', p.id, 'Ghi nhận chi lương ' + p.code + ' ' + F.vnd(p.total) + ' (' + ids.length + ' chi phí)'); done(); return p;
  });
  X.exportPayroll = (period) => { const p = Q.payroll(period); if (!p) err('Chưa có bảng lương'); const rows = p.lines.map(l => { const e = Q.employee(l.employeeId); return [e.code, e.name, Q.deptLabel(e.dept), l.workDays, l.base, l.titleAllowance, l.buildingAllowance, l.commission, l.deductions, l.total]; }); F.download(p.code + '.csv', F.csv(rows, ['Mã NV', 'Họ tên', 'Phòng ban', 'Ngày công', 'Lương cứng', 'PC chức danh', 'PC số nhà', 'Hoa hồng', 'Khấu trừ', 'Thực lĩnh']), 'text/csv'); return rows.length; };

  /* ================= Dự án / cổ đông (FR-SHR-01/02) ================= */
  X.saveProject = (d) => { need3(); Au.need('projects.manage'); req(d.name, 'Tên dự án'); req(d.buildingId, 'Tòa nhà'); const cap = F.num(d.capital); if (cap <= 0) err('Vốn điều lệ phải lớn hơn 0'); const dup = St.one('projects', p => p.buildingId === d.buildingId && p.id !== d.id); if (dup) err('Tòa này đã thuộc dự án ' + dup.code); const payload = { name: d.name.trim(), buildingId: d.buildingId, capital: cap, status: d.status || 'raising', startDate: d.startDate || F.today(), expectedRoi: F.num(d.expectedRoi) || 0, note: d.note || '' }; let p; if (d.id) p = St.update('projects', d.id, payload); else p = St.add('projects', Object.assign({ code: St.nextCode('projects', 'DA-', 3), createdBy: me() }, payload)); St.audit('save', 'project', p.id, (d.id ? 'Cập nhật' : 'Tạo') + ' dự án ' + p.code); done(); return p; };
  X.closeProject = (id) => { need3(); Au.need('projects.manage'); const p = St.get('projects', id); p.status = 'closed'; St.audit('close', 'project', id, 'Đóng dự án ' + p.code); done(); return p; };
  X.saveShareholder = (d) => {
    need3(); Au.need('shareholders.manage'); req(d.name, 'Tên cổ đông');
    const payload = { name: d.name.trim(), email: d.email || '', phone: d.phone || '', idNumber: d.idNumber || '', note: d.note || '' };
    let s; if (d.id) s = St.update('shareholders', d.id, payload); else s = St.add('shareholders', Object.assign({ code: St.nextCode('shareholders', 'CD-', 3), status: 'active', userId: null, createdBy: me() }, payload));
    (d.commitments || []).forEach(c => X.saveCommitment(Object.assign({ shareholderId: s.id }, c)));
    St.audit('save', 'shareholder', s.id, (d.id ? 'Cập nhật' : 'Thêm') + ' cổ đông ' + s.code + ' ' + s.name); done(); return s;
  };
  X.saveCommitment = ({ shareholderId, projectId, ratio, committed, effectiveDate }) => { // AC-FR-SHR-02-1: tỷ lệ nhập tay, không tự tính từ tiền; Σ ratio/dự án ≤ 100%
    need3(); Au.need('shareholders.manage'); const p = St.get('projects', projectId); if (!p) err('Chọn dự án'); ratio = Number(ratio); if (!(ratio > 0 && ratio <= 100)) err('Tỷ lệ vốn phải trong khoảng 0–100%');
    const others = F.sum(St.where('capitalCommitments', c => c.projectId === projectId && c.shareholderId !== shareholderId), c => c.ratio); if (others + ratio > 100.0001) err('Tổng tỷ lệ của ' + p.name + ' vượt 100% (đã có ' + Math.round(others * 100) / 100 + '%)');
    const amt = F.num(committed) || Math.round(p.capital * ratio / 100); let c = St.one('capitalCommitments', x => x.projectId === projectId && x.shareholderId === shareholderId);
    if (c) Object.assign(c, { ratio, committed: amt, effectiveDate: effectiveDate || c.effectiveDate }); else c = St.add('capitalCommitments', { shareholderId, projectId, ratio, committed: amt, effectiveDate: effectiveDate || F.today(), by: me() });
    const sh = St.get('shareholders', shareholderId); if (sh && sh.userId) { const u = St.get('users', sh.userId); if (u) u.buildingIds = [...new Set(St.where('capitalCommitments', x => x.shareholderId === sh.id).map(x => Q.project(x.projectId).buildingId))]; }
    St.save(); return c;
  };
  X.createContributionRound = ({ projectId, round, dueDate, total, kind, note }) => { // AC-FR-SHR-01-2: sinh nghĩa vụ cho từng cổ đông theo tỷ lệ
    need3(); Au.need('contributions.record'); const p = St.get('projects', projectId); if (!p) err('Chọn dự án'); req(dueDate, 'Hạn góp'); const cms = St.where('capitalCommitments', c => c.projectId === projectId); if (!cms.length) err('Dự án chưa có cổ đông cam kết'); const amount = F.num(total); if (amount <= 0) err('Tổng đợt phải lớn hơn 0');
    const label = round || 'Đợt ' + (St.where('contributions', c => c.projectId === projectId && c.kind !== 'periodic').length + 1); const out = [];
    cms.forEach(c => { const amt = Math.round(amount * c.ratio / 100 / 1000) * 1000; if (amt <= 0) return; out.push(St.add('contributions', { code: St.nextCode('contributions', 'GV-' + String(dueDate).slice(0, 7).replace('-', '') + '-', 3), kind: kind || 'capital', shareholderId: c.shareholderId, projectId, round: label, amount: amt, dueDate, paidAmount: 0, paidDate: null, ref: '', status: 'scheduled', source: 'auto', note: note || '', createdBy: me() })); });
    St.audit('create', 'contribution', p.id, 'Tạo ' + label + ' – ' + p.name + ': ' + out.length + ' nghĩa vụ, ' + F.vnd(amount)); done(); return out;
  };
  X.recordContribution = (id, { amount, date, ref, note }) => idem('contrib:' + id + ':' + (ref || date), () => { // AC-FR-SHR-01: không coi cam kết là thực góp – chỉ ghi khi có tiền/chứng từ
    need3(); Au.need('contributions.record'); const c = St.get('contributions', id); if (!c) err('Không tìm thấy nghĩa vụ góp vốn'); const amt = F.num(amount); if (amt <= 0) err('Số tiền phải lớn hơn 0'); const rem = c.amount - (c.paidAmount || 0); if (amt > rem + 1) err('Vượt số còn phải góp ' + F.vnd(rem));
    c.paidAmount = (c.paidAmount || 0) + amt; c.paidDate = date || F.today(); c.ref = ref || c.ref; if (note) c.note = note; (c.history = c.history || []).push({ at: F.nowISO(), amount: amt, date: c.paidDate, ref: ref || '', by: me() }); c.status = c.paidAmount >= c.amount ? 'paid' : 'partial';
    St.audit('record', 'contribution', c.id, 'Ghi nhận góp vốn ' + Q.shareholder(c.shareholderId).name + ' ' + F.vnd(amt) + ' – ' + Q.project(c.projectId).name); done(); return c;
  });
  X.createDistribution = ({ label, projectId, profit, date, note }) => { // AC-FR-SHR-02-2: Σ dòng + chênh làm tròn = tổng duyệt; chặn chia cho 0
    need3(); Au.need('distributions.manage'); req(label, 'Kỳ phân phối'); const amt = F.num(profit); if (amt <= 0) err('Lợi nhuận được phân phối phải lớn hơn 0 (kỳ lỗ chưa có quy tắc – OI-17)'); if (Q.totalCapital(projectId) <= 0) err('Tổng vốn bằng 0 – không tính được tỷ lệ');
    if (St.one('distributions', x => x.label === label && (x.projectId || '') === (projectId || ''))) err('Kỳ ' + label + ' đã có bảng phân phối');
    const rows = Q.shareholderRows({ projectId }).filter(r => r.ratio > 0); const lines = rows.map(r => ({ shareholderId: r.s.id, ratio: r.ratio, amount: Math.round(amt * r.ratio / 100), rounding: 0 })); const sum = F.sum(lines, l => l.amount); if (lines.length && sum !== amt) { const big = lines.reduce((a, b) => a.amount > b.amount ? a : b); big.rounding = amt - sum; big.amount += amt - sum; }
    const d = St.add('distributions', { code: 'PP-' + String(label).replace(/[^\w]/g, '-').replace(/-+/g, '-'), label, projectId: projectId || '', profit: amt, planned: amt, date: date || F.today(), status: 'planned', lines, approvedBy: null, approvedAt: null, paidAt: null, note: note || 'Tỷ lệ = tỷ lệ vốn nhập tay tại thời điểm lập (OI-17)', createdBy: me() });
    St.audit('create', 'distribution', d.id, 'Lập bảng phân phối ' + label + ' ' + F.vnd(amt)); done(); return d;
  };
  X.processDistribution = (id) => { need3(); Au.need('distributions.manage'); const d = St.get('distributions', id); if (d.status !== 'planned') err('Chỉ chuyển kỳ Chờ phân phối sang Đang xử lý'); d.status = 'processing'; done(); return d; };
  X.approveDistribution = (id) => { need3(); Au.need('distributions.approve'); const d = St.get('distributions', id); if (!d) err('Không tìm thấy kỳ phân phối'); if (!['planned', 'processing'].includes(d.status)) err('Kỳ đã duyệt/đã chi'); if (!d.lines.length) err('Bảng phân phối trống'); d.status = 'approved'; d.approvedBy = me(); d.approvedAt = F.nowISO(); St.audit('approve', 'distribution', d.id, 'Duyệt bảng phân phối ' + d.label); done(); return d; };
  X.payDistribution = (id, { date, ref } = {}) => idem('dist:' + id, () => { // chỉ đánh dấu đã chi – không tạo chi phí (phân phối lợi nhuận ≠ chi phí vận hành)
    need3(); Au.need('distributions.manage'); const d = St.get('distributions', id); if (!d || d.status !== 'approved') err('Bảng phân phối chưa được duyệt'); d.status = 'paid'; d.paidAt = F.nowISO(); d.paidBy = me(); d.paidDate = date || F.today(); d.ref = ref || ''; St.audit('pay', 'distribution', d.id, 'Ghi nhận đã chi phân phối ' + d.label + ' ' + F.vnd(d.profit)); done(); return d;
  });
  X.exportDistribution = (id) => { const d = St.get('distributions', id); const rows = Q.distributionLines(d).map(l => [l.s.code, l.s.name, l.ratio + '%', l.amount, l.rounding]); F.download(d.code + '.csv', F.csv(rows, ['Mã', 'Cổ đông', 'Tỷ lệ', 'Số tiền', 'Làm tròn']), 'text/csv'); return rows.length; };

  /* ================= Ngân hàng (mô phỏng – scope §4.5) ================= */
  X.importBankStatement = ({ rows, accountId, fileName }) => idem('bank:' + F.hash(fileName + ':' + rows.length + ':' + JSON.stringify(rows[0] || {})), () => {
    need3(); Au.need('bank.manage'); const acc = St.get('bankAccounts', accountId) || St.all('bankAccounts')[0]; if (!acc) err('Chọn tài khoản'); let added = 0, dup = 0;
    rows.forEach(r => { const d = r.data || r; const amount = F.num(d.amount); if (!amount || !d.date) return; const ref = (d.refCode || d.ref || '').trim(); if (ref && St.one('bankTransactions', t => t.ref === ref)) { dup++; return; } St.add('bankTransactions', { code: St.nextCode('bankTransactions', 'GD', 4), accountId: acc.id, date: d.date, amount, dir: d.dir === 'out' || amount < 0 ? 'out' : 'in', desc: d.content || d.desc || (d.tenantName ? d.tenantName + ' CK' : ''), ref: ref || ('IMP' + Date.now().toString().slice(-6) + added), matchStatus: 'unmatched', paymentId: null, invoiceId: null, fileName, raw: d }); added++; });
    St.audit('import', 'bank', acc.id, 'Nhập sao kê ' + fileName + ': ' + added + ' giao dịch, ' + dup + ' trùng'); done(); return { added, dup, accountId: acc.id };
  });
  X.reconcileBank = () => { // chạy 4 quy tắc ghép của bảng kê P2 cho dòng chưa khớp; matched → khoản thu (idempotent theo ref)
    need3(); Au.need('bank.manage'); if (!X.matchStatement || !TH.phase.on(2)) err('Đối soát tự động dùng quy tắc ghép bảng kê của Phase 2 – bật Phase 2 để chạy');
    const txs = St.where('bankTransactions', t => t.dir === 'in' && ['unmatched', 'check'].includes(t.matchStatus)); if (!txs.length) return { matched: 0, check: 0, total: 0 };
    const rows = txs.map((t, i) => ({ i, data: Object.assign({ date: t.date, amount: t.amount, refCode: t.ref, content: t.desc, method: 'Chuyển khoản' }, t.raw || {}, { invoiceCode: (t.raw || {}).invoiceCode || ((t.desc || '').match(/HD-?\d{4}-?\d{3}/i) || [])[0] || '', tenantName: (t.raw || {}).tenantName || '' }) }));
    const res = X.matchStatement(rows); let matched = 0, check = 0;
    res.forEach((r, i) => { const t = txs[i]; if (r.status === 'matched') { const inv = St.get('invoices', r.invoiceId); const p = X.recordPayment({ tenantId: inv.tenantId, date: t.date, amount: t.amount, method: 'Chuyển khoản', ref: t.ref, evidence: 'Sao kê ' + Q.bankAccount(t.accountId).bank, note: 'Đối soát ngân hàng tự động – ' + t.desc, allocations: [{ invoiceId: inv.id, amount: r.alloc }] }, 'bank:' + t.ref); p.kind = 'bank'; t.matchStatus = 'matched'; t.paymentId = p.id; t.invoiceId = inv.id; t.rule = r.rule; matched++; } else if (r.status === 'duplicate') { const p = St.one('payments', x => x.ref === t.ref && x.status === 'recorded'); if (p) { t.matchStatus = 'matched'; t.paymentId = p.id; matched++; } } else if (r.status === 'check') { t.matchStatus = 'check'; t.invoiceId = r.invoiceId; t.reason = r.reason; check++; } else { t.reason = r.reason; } });
    St.audit('reconcile', 'bank', '', 'Đối soát tự động: ' + matched + ' khớp, ' + check + ' cần kiểm tra'); done(); return { matched, check, total: txs.length };
  };
  X.matchBankTx = (id, invoiceId) => idem('bankmatch:' + id, () => { need3(); Au.need('bank.manage'); const t = St.get('bankTransactions', id); if (!t || t.matchStatus === 'matched') err('Giao dịch đã khớp'); const inv = St.get('invoices', invoiceId); if (!inv) err('Chọn hóa đơn'); if (inv.docStatus === 'draft') err('Hóa đơn chưa phát hành'); const rem = Q.invRemaining(inv); if (rem <= 0) err('Hóa đơn đã thu đủ'); const p = X.recordPayment({ tenantId: inv.tenantId, date: t.date, amount: t.amount, method: 'Chuyển khoản', ref: t.ref, evidence: 'Sao kê ' + Q.bankAccount(t.accountId).bank, note: 'Khớp thủ công – ' + t.desc, allocations: [{ invoiceId: inv.id, amount: Math.min(rem, t.amount) }] }, 'bank:' + t.ref); p.kind = 'bank'; t.matchStatus = 'matched'; t.paymentId = p.id; t.invoiceId = inv.id; t.rule = 5; St.audit('match', 'bank', t.id, 'Khớp tay ' + t.ref + ' → ' + inv.code); done(); return t; });
  X.ignoreBankTx = (id, reason) => { need3(); Au.need('bank.manage'); const t = St.get('bankTransactions', id); if (!t) err('Không tìm thấy giao dịch'); if (t.matchStatus === 'matched') err('Giao dịch đã khớp'); t.matchStatus = 'ignored'; t.reason = reason || 'Bỏ qua thủ công'; done(); return t; };
  X.createPaymentQr = (invoiceId) => { need3(); Au.need('bank.manage'); const inv = St.get('invoices', invoiceId); if (!inv) err('Chọn hóa đơn'); const acc = St.one('bankAccounts', a => a.qrEnabled) || St.all('bankAccounts')[0]; const rem = Q.invRemaining(inv); if (rem <= 0) err('Hóa đơn đã thu đủ'); const qr = { invoiceId: inv.id, code: inv.code, amount: rem, account: acc, content: 'TIMO ' + inv.code + ' ' + (Q.room(inv.roomId).code || ''), text: 'VIETQR|' + acc.number + '|' + rem + '|' + inv.code }; inv.qrCreatedAt = F.nowISO(); St.audit('qr', 'invoice', inv.id, 'Tạo QR thanh toán ' + inv.code + ' ' + F.vnd(rem)); St.save(); return qr; };
})(window.TH);
