/* Actions – Spec v1.8 Wave 5: kỳ báo cáo Open → Reviewing → Locked (snapshot freeze metric version / allocation / loại tòa / payroll allocation / share snapshot) → Reopen có lý do (§12.23.13);
   xác nhận Metric Definition (Q-RPT-xxx → CONFIRMED, tăng version); cổ phần theo tòa không ghi đè lịch sử (§4.30); góp vốn theo tòa → đợt → phân bổ theo share (§4.31);
   phân phối lợi nhuận generate từ báo cáo đã khóa với tỷ lệ snapshot (§4.32, §12.22.5); kịch bản demo G1 06/2026 (golden A). */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, Au = TH.auth, X = TH.actions, E = TH.reportP1, M = TH.metrics;
  const err = (m) => { throw new Error(m); };
  const req = (v, m) => { if (v === undefined || v === null || v === '' || (typeof v === 'number' && isNaN(v))) err(m); return v; };
  const me = () => (St.state.session || {}).userId || null;
  const meName = () => { const u = Au.user(); return u ? u.name : 'Hệ thống'; };
  const done = () => { St.save(); St.emit('change'); };
  const hist = (p, type, text, extra = {}) => { (p.history = p.history || []).push(Object.assign({ at: F.nowISO(), by: me(), byName: meName(), type, text }, extra)); };
  const raw = (c) => St.rawAll(c).filter(Boolean);

  /* ================= Kỳ báo cáo §12.23.1 / §12.23.13 ================= */
  X.ensureReportPeriod = (period) => { let rp = Q.reportPeriod(period); if (rp) return rp; const { from, to } = E.range(period); rp = St.add('reportPeriods', { code: 'RP-' + period, period, periodType: 'MONTH', year: Number(period.slice(0, 4)), month: Number(period.slice(5, 7)), fromDate: from, toDate: to, cutoffAt: null, status: 'OPEN', metricVersion: M.version(), allocationVersion: (Q.allocationRules ? Q.allocationRules().map(r => r.code).join(',') : ''), generatedAt: null, lockedAt: null, lockedBy: null, note: '', history: [{ at: F.nowISO(), by: me(), byName: meName(), type: 'open', text: 'Mở kỳ báo cáo' }] }); return rp; };
  X.reviewReportPeriod = (period) => { Au.need('reports.view'); const rp = X.ensureReportPeriod(period); if (!['OPEN', 'REOPENED'].includes(rp.status)) err('Chỉ gửi review kỳ Đang mở / Đã mở lại'); const prev = rp.status; rp.status = 'REVIEWING'; rp.cutoffAt = F.nowISO(); hist(rp, 'review', 'Gửi review – cutoff ' + F.datetime(rp.cutoffAt)); St.audit('review', 'reportPeriod', rp.id, 'Kỳ báo cáo ' + rp.code + ' → Đang review', { before: prev, after: 'REVIEWING' }); done(); return rp; };
  X.returnReportPeriod = (period, reason) => { Au.need('reports.view'); const rp = Q.reportPeriod(period); if (!rp || rp.status !== 'REVIEWING') err('Chỉ trả lại kỳ Đang review'); req(reason, 'Nhập lý do trả lại (lỗi dữ liệu)'); rp.status = 'OPEN'; hist(rp, 'return', 'Trả lại: ' + reason); St.audit('return', 'reportPeriod', rp.id, 'Kỳ ' + rp.code + ' trả lại – ' + reason, { reason, before: 'REVIEWING', after: 'OPEN' }); done(); return rp; };
  /* Khóa: freeze Metric Definition Version, Allocation Version, loại tòa theo kỳ, Payroll Cost Allocation, Building Share Snapshot, metric values (§12.23.13) */
  X.lockReportPeriod = (period, o = {}) => {
    Au.need('reports.lock'); const rp = X.ensureReportPeriod(period); if (!['REVIEWING', 'REOPENED'].includes(rp.status) && !o.force) err('Chỉ khóa kỳ Đang review (Open → Reviewing → Locked)');
    const at = o.at || F.nowISO(); const by = o.by || me();
    St.removeWhere('reportMetricValues', x => raw('reportSnapshots').some(s => s.reportPeriodId === rp.id && s.id === x.snapshotId)); St.removeWhere('reportSnapshots', s => s.reportPeriodId === rp.id);
    const bs = E.liveBuildings(period); const perB = [];
    const compact = (rows) => (rows || []).slice(0, 80).map(r => ({ type: r.type, id: r.id, label: r.label, sub: r.sub, amount: r.amount, href: r.href, chain: r.chain }));
    bs.forEach(b => { const r = E.compute(period, b.id); const shares = E.shares(period, b.id, r.values); const snap = St.add('reportSnapshots', { reportPeriodId: rp.id, period, reportType: 'A', buildingId: b.id, buildingType: r.buildingType, generatedAt: at, generatedBy: by, status: 'LOCKED', sourceVersion: { metricVersion: M.version(), allocationVersion: rp.allocationVersion, buildingType: r.buildingType }, shares: { rows: shares.rows, totalPct: shares.totalPct, ok: shares.ok, snapshotAt: r.to } }); M.P1.forEach(d => St.add('reportMetricValues', { snapshotId: snap.id, metricCode: d.code, totalValue: r.values[d.code] != null ? r.values[d.code] : null, tValue: null, sValue: null, gValue: null, drilldownCount: (r.drill[d.code] || []).length, detail: compact(r.drill[d.code]), status: M.effectiveStatus(d.code) })); St.add('reportMetricValues', { snapshotId: snap.id, metricCode: 'SERVICE_INPUT_COST', totalValue: r.values.SERVICE_INPUT_COST || 0, drilldownCount: 0, detail: [] }); perB.push({ buildingId: b.id, code: b.code, name: b.name, type: r.buildingType, values: r.values, frozen: true }); });
    const agg = E.aggregate(perB); const snapB = St.add('reportSnapshots', { reportPeriodId: rp.id, period, reportType: 'B', buildingId: null, buildingType: null, generatedAt: at, generatedBy: by, status: 'LOCKED', sourceVersion: { metricVersion: M.version(), allocationVersion: rp.allocationVersion }, buildings: perB.map(x => ({ buildingId: x.buildingId, code: x.code, name: x.name, type: x.type, values: x.values })) });
    M.P1.forEach(d => St.add('reportMetricValues', { snapshotId: snapB.id, metricCode: d.code, totalValue: agg.values[d.code] != null ? agg.values[d.code] : null, tValue: agg.T[d.code], sValue: agg.S[d.code], gValue: agg.G[d.code], drilldownCount: perB.length, detail: [], status: M.effectiveStatus(d.code) }));
    const prev = rp.status; rp.status = 'LOCKED'; rp.lockedAt = at; rp.lockedBy = by; rp.generatedAt = at; rp.metricVersion = M.version(); rp.buildingCount = bs.length; hist(rp, 'lock', 'Khóa kỳ – ' + bs.length + ' snapshot tòa + 1 snapshot T/S/G; freeze metric ' + rp.metricVersion + ', allocation ' + (rp.allocationVersion || '-') + ', loại tòa, payroll allocation, share snapshot', { at });
    St.audit('lock', 'reportPeriod', rp.id, 'Khóa kỳ báo cáo ' + rp.code + ' (' + bs.length + ' tòa)', { before: prev, after: 'LOCKED' }); St.audit('event', 'reportPeriod', rp.id, 'PROFIT_REPORT_LOCKED ' + period, { event: 'PROFIT_REPORT_LOCKED' });
    done(); return rp;
  };
  X.reopenReportPeriod = (period, reason) => { Au.need('reports.reopen'); const rp = Q.reportPeriod(period); if (!rp || rp.status !== 'LOCKED') err('Chỉ mở lại kỳ Đã khóa'); req(reason, 'Mở lại kỳ bắt buộc có lý do (audit)'); const confirmed = raw('profitDistributions').filter(d => d.period === period && d.status === 'confirmed'); if (confirmed.length) err('Kỳ đã có ' + confirmed.length + ' bảng phân phối lợi nhuận đã xác nhận – hủy phân phối trước khi mở lại'); rp.status = 'REOPENED'; rp.reopenedAt = F.nowISO(); rp.reopenedBy = me(); rp.reopenReason = reason; hist(rp, 'reopen', 'Mở lại: ' + reason); St.audit('reopen', 'reportPeriod', rp.id, 'Mở lại kỳ báo cáo ' + rp.code + ' – ' + reason, { reason, before: 'LOCKED', after: 'REOPENED' }); done(); return rp; };
  X.exportReportA = (period, buildingId) => { const r = E.building(period, buildingId); F.download('bao-cao-toa-' + (r.building.code || buildingId) + '-' + period + '.csv', E.exportA(r), 'text/csv'); St.audit('export', 'report', buildingId, 'Xuất Report A ' + (r.building.code || '') + ' ' + period); };
  X.exportReportB = (period) => { const s = E.summary(period); F.download('bao-cao-kinh-doanh-TSG-' + period + '.csv', E.exportB(s), 'text/csv'); St.audit('export', 'report', period, 'Xuất Report B ' + period); };
  X.exportReconcile = (id) => { const r = E.reconcile(id); if (!r) err('Không có golden dataset'); F.download('doi-soat-' + r.golden.code + '.csv', F.csv(r.rows.map(x => [x.code, x.excelValue, x.systemValue, x.diff, x.pctDiff, x.status, x.note]), ['metric_code', 'excel_value', 'system_value', 'difference', 'difference_percent', 'status', 'note']), 'text/csv'); };
  /* Xác nhận metric: NEED_BUSINESS_CONFIRMATION → CONFIRMED, tăng version, lưu người ký (§12.23.15) */
  X.confirmMetric = (code, { note, decision } = {}) => { Au.need('metrics.manage'); const d = M.def(code); if (!d) err('Không có metric ' + code); req(decision, 'Nhập quyết định nghiệp vụ đã chốt'); let o = raw('metricDefinitions').find(x => x.code === code); if (!o) o = St.add('metricDefinitions', { code, version: d.version, status: d.status, effectiveFrom: d.effectiveFrom, history: [] }); const prev = o.status; o.history = o.history || []; o.history.push({ at: F.nowISO(), by: me(), byName: meName(), from: prev, to: 'CONFIRMED', version: (o.version || 1) + 1, decision, note: note || '' }); o.status = 'CONFIRMED'; o.version = (o.version || 1) + 1; o.effectiveFrom = F.today(); o.confirmedBy = me(); o.confirmedAt = F.nowISO(); o.decision = decision; St.audit('confirm', 'metricDefinition', code, 'Xác nhận metric ' + code + ' v' + o.version + ' – ' + decision, { before: prev, after: 'CONFIRMED', reason: decision }); done(); return o; };
  X.revertMetric = (code, reason) => { Au.need('metrics.manage'); const o = raw('metricDefinitions').find(x => x.code === code); if (!o) err('Metric chưa có ghi đè'); req(reason, 'Nhập lý do'); o.history.push({ at: F.nowISO(), by: me(), byName: meName(), from: o.status, to: 'NEED_BUSINESS_CONFIRMATION', version: o.version + 1, decision: reason }); o.status = 'NEED_BUSINESS_CONFIRMATION'; o.version += 1; St.audit('revert', 'metricDefinition', code, 'Đưa metric ' + code + ' về chờ chốt – ' + reason, { reason }); done(); return o; };

  /* ================= Cổ đông §4.29 / cổ phần theo tòa §4.30 ================= */
  X.saveShareholder = (d) => { Au.need('shareholders.manage'); req(d.name, 'Nhập họ tên / pháp nhân'); const dup = raw('shareholders').find(s => s.id !== d.id && ((d.idNumber && s.idNumber === d.idNumber) || (d.taxCode && s.taxCode === d.taxCode))); if (dup) err('Trùng CCCD/MST với cổ đông ' + dup.code); const patch = { name: d.name, idNumber: d.idNumber || '', taxCode: d.taxCode || '', phone: d.phone || '', email: d.email || '', bankAccount: d.bankAccount || '', bankName: d.bankName || '', entityType: d.entityType || 'person', note: d.note || '', status: d.status || 'active' }; let s; if (d.id) { s = St.update('shareholders', d.id, patch); St.audit('save', 'shareholder', s.id, 'Cập nhật cổ đông ' + s.code); } else { s = St.add('shareholders', Object.assign({ code: St.nextCode('shareholders', 'CD-', 3), userId: null }, patch)); St.audit('create', 'shareholder', s.id, 'Thêm cổ đông ' + s.code + ' ' + s.name); } if (d.commitments && d.commitments.length && X.saveCommitment) d.commitments.forEach(c => X.saveCommitment(Object.assign({ shareholderId: s.id }, c))); done(); return s; };
  X.deactivateShareholder = (id, reason) => { Au.need('shareholders.manage'); const s = St.get('shareholders', id); if (!s) err('Không tìm thấy cổ đông'); const active = Q.shareholderBuildings(id); if (active.length) err('Cổ đông còn cổ phần hiệu lực tại ' + active.map(x => x.b.name).join(', ') + ' – chuyển nhượng (kết thúc hiệu lực) trước khi ngừng'); req(reason, 'Nhập lý do'); s.status = 'inactive'; s.inactiveAt = F.nowISO(); s.inactiveReason = reason; St.audit('deactivate', 'shareholder', id, 'Ngừng hoạt động cổ đông ' + s.code + ' – ' + reason, { reason }); done(); return s; };
  X.activateShareholder = (id) => { Au.need('shareholders.manage'); const s = St.get('shareholders', id); s.status = 'active'; St.audit('activate', 'shareholder', id, 'Kích hoạt lại cổ đông ' + s.code); done(); return s; };
  /* Cấu hình cổ phần một tòa từ ngày hiệu lực: record mới cho cổ đông đổi tỷ lệ, record cũ đóng effectiveTo = from − 1; tổng tại ngày = 100% */
  X.configureShares = ({ buildingId, effectiveFrom, rows, basis, document, reason }) => {
    Au.need('shares.manage'); req(buildingId, 'Chọn tòa'); req(effectiveFrom, 'Chọn ngày hiệu lực'); const clean = (rows || []).map(r => ({ shareholderId: r.shareholderId, percentage: Math.round(Number(r.percentage || 0) * 100) / 100 })).filter(r => r.shareholderId && r.percentage > 0);
    if (!clean.length) err('Nhập ít nhất một cổ đông có tỷ lệ > 0'); const ids = clean.map(r => r.shareholderId); if (new Set(ids).size !== ids.length) err('Một cổ đông xuất hiện 2 lần'); const total = Math.round(F.sum(clean, r => r.percentage) * 100) / 100; if (Math.abs(total - 100) > 0.005) err('Tổng tỷ lệ tại ' + F.date(effectiveFrom) + ' = ' + total + '% – phải bằng 100% (§4.30)');
    const locked = raw('reportPeriods').filter(p => p.status === 'LOCKED' && p.toDate >= effectiveFrom && effectiveFrom <= F.today()); if (locked.length) err('Không đổi cổ phần hồi tố vào kỳ đã khóa ' + locked.map(p => p.code).join(', ') + ' – báo cáo kỳ cũ dùng share snapshot; chọn ngày hiệu lực từ hôm nay trở đi');
    const cur = Q.buildingShares(buildingId, effectiveFrom); const before = cur.map(s => ({ shareholderId: s.shareholderId, percentage: s.percentage })); let changed = 0;
    const b = Q.building(buildingId);
    cur.forEach(s => { const nw = clean.find(r => r.shareholderId === s.shareholderId); if (nw && Math.abs(nw.percentage - s.percentage) < 0.005 && s.effectiveFrom < effectiveFrom) return; if (s.effectiveFrom >= effectiveFrom) { if (s.effectiveFrom === effectiveFrom && nw) { s.percentage = nw.percentage; changed++; return; } s.status = 'cancelled'; changed++; return; } s.effectiveTo = F.addDays(effectiveFrom, -1); changed++; });
    clean.forEach(r => { const same = cur.find(s => s.shareholderId === r.shareholderId); if (same && Math.abs(same.percentage - r.percentage) < 0.005 && same.effectiveFrom < effectiveFrom && same.status !== 'cancelled' && !(same.effectiveTo && same.effectiveTo < effectiveFrom)) { same.effectiveTo = ''; return; } if (same && same.effectiveFrom === effectiveFrom && same.status !== 'cancelled') return; St.add('buildingShares', { buildingId, shareholderId: r.shareholderId, percentage: r.percentage, effectiveFrom, effectiveTo: '', basis: basis || 'Nghị quyết cổ đông', document: document || '', reason: reason || '', status: 'active', createdBy: me() }); changed++; });
    St.audit('configure', 'buildingShares', buildingId, 'Cấu hình cổ phần ' + (b.name || '') + ' hiệu lực ' + F.date(effectiveFrom) + ' (' + clean.length + ' cổ đông = 100%)', { before, after: clean, reason: reason || '' }); done(); return { changed, total };
  };
  X.exportShareTable = (buildingId, date) => { const b = Q.building(buildingId); St.audit('export', 'buildingShares', buildingId, 'Export share table ' + (b.name || '') + ' tại ' + F.date(date || F.today())); const rows = Q.buildingShares(buildingId, date).map(s => { const sh = Q.shareholder(s.shareholderId); return [sh.code, sh.name, s.percentage, s.effectiveFrom, s.effectiveTo || '', s.basis || '', s.document || '']; }); F.download('co-phan-' + (b.code || buildingId) + '-' + (date || F.today()) + '.csv', F.csv(rows, ['Mã', 'Cổ đông', 'Tỷ lệ %', 'Hiệu lực từ', 'Hiệu lực đến', 'Cơ sở', 'Tài liệu']), 'text/csv'); };

  /* ================= Góp vốn theo tòa §4.31 ================= */
  X.createCapitalCall = ({ buildingId, name, total, dueDate, note, asOf }) => { Au.need('contributions.record'); req(buildingId, 'Chọn tòa'); const amt = F.num(total); if (amt <= 0) err('Tổng cần góp phải > 0'); req(dueDate, 'Chọn hạn góp'); const date = asOf || F.today(); const shares = Q.buildingShares(buildingId, date); if (!shares.length) err('Tòa chưa có cổ phần hiệu lực – cấu hình cổ phần trước'); if (Math.abs(Q.buildingShareTotal(buildingId, date) - 100) > 0.005) err('Tổng cổ phần tại ' + F.date(date) + ' ≠ 100% – không phân bổ được'); const b = Q.building(buildingId); const call = St.add('capitalCalls', { code: St.nextCode('capitalCalls', 'GV-' + String(dueDate).slice(0, 7).replace('-', '') + '-', 3), buildingId, name: name || 'Đợt góp vốn', total: amt, dueDate, note: note || '', shareDate: date, status: 'open', createdBy: me() }); let acc = 0; shares.forEach((s, i) => { const required = i === shares.length - 1 ? amt - acc : Math.round(amt * s.percentage / 100 / 1000) * 1000; acc += required; St.add('capitalPayments', { capitalCallId: call.id, shareholderId: s.shareholderId, percentage: s.percentage, required, paid: 0, paidDate: null, ref: '', note: '', history: [] }); }); St.audit('create', 'capitalCall', call.id, 'Tạo ' + call.code + ' ' + (b.name || '') + ' – ' + F.vnd(amt) + ' phân bổ ' + shares.length + ' cổ đông theo cổ phần ' + F.date(date)); done(); return call; };
  X.recordCapitalPayment = (lineId, { amount, date, ref, note }) => { Au.need('contributions.record'); const l = St.get('capitalPayments', lineId); if (!l) err('Không tìm thấy dòng góp vốn'); const amt = F.num(amount); if (amt <= 0) err('Số tiền phải > 0'); const rem = l.required - (l.paid || 0); if (amt > rem + 0.5) err('Vượt số còn phải góp ' + F.vnd(rem)); req(ref, 'Nhập chứng từ / UNC (không coi cam kết là thực góp)'); l.paid = (l.paid || 0) + amt; l.paidDate = date || F.today(); l.ref = ref; if (note) l.note = note; (l.history = l.history || []).push({ at: F.nowISO(), by: me(), amount: amt, date: l.paidDate, ref }); const call = Q.capitalCall(l.capitalCallId); const sh = Q.shareholder(l.shareholderId); if (Q.capitalCallStatus(call) === 'done') call.status = 'done'; St.audit('capital_pay', 'capitalPayment', lineId, 'Góp vốn ' + (call.code || '') + ' – ' + (sh.name || '') + ' ' + F.vnd(amt) + ' · ' + ref); done(); return l; };
  X.cancelCapitalCall = (id, reason) => { Au.need('contributions.record'); const c = St.get('capitalCalls', id); if (raw('capitalPayments').some(l => l.capitalCallId === id && l.paid > 0)) err('Đợt đã có tiền góp – không hủy'); req(reason, 'Nhập lý do'); c.status = 'cancelled'; c.cancelReason = reason; St.audit('cancel', 'capitalCall', id, 'Hủy ' + c.code + ' – ' + reason, { reason }); done(); return c; };
  X.exportCapitalCall = (id) => { const c = Q.capitalCall(id); const rows = Q.capitalLines(id).map(l => [l.s.code, l.s.name, l.percentage, l.required, l.paid || 0, l.required - (l.paid || 0), c.dueDate, l.paidDate || '', l.ref || '', l.note || '']); F.download(c.code + '.csv', F.csv(rows, ['Mã', 'Cổ đông', 'Tỷ lệ %', 'Phải góp', 'Đã góp', 'Còn thiếu', 'Hạn góp', 'Ngày góp', 'Chứng từ', 'Ghi chú']), 'text/csv'); };

  /* ================= Phân phối lợi nhuận từ báo cáo đã khóa §4.32 / §12.22.5 ================= */
  X.generateDistribution = (period, buildingId, o = {}) => {
    Au.need('distributions.manage'); const rp = Q.reportPeriod(period); if (!rp || rp.status !== 'LOCKED') err('Chỉ generate từ kỳ báo cáo Đã khóa (PROFIT_REPORT_LOCKED)'); const snap = E.snapshot(period, 'A', buildingId); if (!snap) err('Kỳ ' + period + ' chưa có snapshot cho tòa này');
    const r = E.fromSnapshot(snap); const v = r.values; const shares = (snap.shares && snap.shares.rows) || []; if (!shares.length) err('Snapshot không có cổ phần – cấu hình cổ phần tòa trước khi khóa kỳ'); if (!snap.shares.ok) err('Tổng cổ phần snapshot = ' + snap.shares.totalPct + '% ≠ 100%');
    const dup = raw('profitDistributions').find(d => d.period === period && d.buildingId === buildingId && d.status !== 'cancelled'); if (dup) err('Đã có bảng phân phối ' + dup.code + ' cho kỳ/tòa này');
    const profit = o.profit != null ? F.num(o.profit) : Number(v.NET_PROFIT || 0); const b = Q.building(buildingId);
    let acc = 0; const lines = shares.map((s, i) => { const net = i === shares.length - 1 ? Math.round((profit - acc) * 100) / 100 : Math.round(profit * s.percentage / 100 * 100) / 100; acc += net; return { shareholderId: s.shareholderId, name: s.name, percentage: s.percentage, capital: s.capital, grossShare: Math.round((v.GROSS_PROFIT || 0) * s.percentage / 100 * 100) / 100, netShare: net, totalReceive: Math.round(((s.capital || 0) + net) * 100) / 100 }; });
    const d = St.add('profitDistributions', { code: St.nextCode('profitDistributions', 'PL-' + period.replace('-', '') + '-', 3), period, buildingId, reportPeriodId: rp.id, snapshotId: snap.id, profitDistributable: profit, grossProfit: v.GROSS_PROFIT || 0, netProfit: v.NET_PROFIT || 0, totalRevenue: v.TOTAL_REVENUE || 0, basis: o.profit != null ? 'Nhập theo quyết định (khác NET_PROFIT snapshot ' + F.vnd(v.NET_PROFIT || 0) + ')' : 'NET_PROFIT snapshot kỳ ' + period, lines, status: 'draft', confirmedAt: null, confirmedBy: null, note: o.note || '', createdBy: me(), history: [{ at: o.at || F.nowISO(), by: me(), byName: meName(), type: 'generate', text: 'Generate từ báo cáo khóa ' + rp.code }] });
    St.audit('generate', 'profitDistribution', d.id, 'Generate phân phối LN ' + d.code + ' ' + (b.name || '') + ' kỳ ' + period + ' – ' + F.vnd(profit) + ' × ' + lines.length + ' cổ đông (tỷ lệ snapshot)'); done(); return d;
  };
  X.submitDistribution = (id) => { Au.need('distributions.manage'); const d = St.get('profitDistributions', id); if (d.status !== 'draft') err('Chỉ gửi xác nhận bảng Nháp'); d.status = 'review'; hist(d, 'submit', 'Gửi xác nhận'); St.audit('submit', 'profitDistribution', id, 'Gửi xác nhận ' + d.code); done(); return d; };
  X.confirmDistribution = (id, note) => { Au.need('distributions.approve'); const d = St.get('profitDistributions', id); if (!['draft', 'review'].includes(d.status)) err('Bảng đã xác nhận/hủy'); d.status = 'confirmed'; d.confirmedAt = F.nowISO(); d.confirmedBy = me(); if (note) d.note = note; hist(d, 'confirm', 'Xác nhận – snapshot tỷ lệ & lợi nhuận đã chốt'); St.audit('confirm', 'profitDistribution', id, 'Xác nhận phân phối LN ' + d.code + ' – ' + F.vnd(d.profitDistributable)); done(); return d; };
  X.cancelDistribution = (id, reason) => { Au.need('distributions.manage'); const d = St.get('profitDistributions', id); req(reason, 'Nhập lý do hủy'); d.status = 'cancelled'; d.cancelReason = reason; hist(d, 'cancel', 'Hủy: ' + reason); St.audit('cancel', 'profitDistribution', id, 'Hủy ' + d.code + ' – ' + reason, { reason }); done(); return d; };
  X.exportProfitDistribution = (id) => { const d = Q.profitDistribution(id); F.download(d.code + '.csv', F.csv(d.lines.map(l => [l.name, l.percentage, l.capital, l.grossShare, l.netShare, l.totalReceive]), ['Cổ đông', 'Tỷ lệ % snapshot', 'Vốn', 'LN gộp × %', 'LN ròng × %', 'Tổng nhận']), 'text/csv'); };

  /* ================= Kịch bản demo W5 (chạy 1 lần sau migrate; cần engine) ================= */
  X.ensureW5Scenario = () => {
    const st = St.state; if (!st.meta || st.meta.w5ScenarioDone || !st.meta.w5Migrated) return; st.meta.w5ScenarioDone = true;
    const sess = st.session; const ketoan = raw('users').find(u => u.username === 'ketoan') || raw('users').find(u => u.role === 'accountant'); const admin = raw('users').find(u => u.role === 'admin');
    try {
      if (TH.seed && TH.seed.ensureG1Payroll) TH.seed.ensureG1Payroll(st);
      const asUser = (u) => ({ userId: u.id, role: u.role, name: u.name }); st.session = asUser(ketoan || admin);
      // Kỳ 06/2026: Open → Reviewing → Locked (05/07/2026) → generate phân phối LN G1 → xác nhận (Admin)
      if (!Q.reportPeriod('2026-06') || Q.reportPeriod('2026-06').status !== 'LOCKED') { const rp = X.ensureReportPeriod('2026-06'); rp.history = [{ at: '2026-07-01T09:00', by: st.session.userId, byName: 'Kế toán', type: 'open', text: 'Mở kỳ báo cáo' }]; rp.status = 'OPEN'; X.reviewReportPeriod('2026-06'); rp.cutoffAt = '2026-07-03T17:00'; rp.history[rp.history.length - 1].at = '2026-07-03T17:00'; X.lockReportPeriod('2026-06', { at: '2026-07-05T10:00', by: st.session.userId }); rp.history[rp.history.length - 1].at = '2026-07-05T10:00'; }
      const g1 = raw('buildings').find(b => b.code === 'G1'); if (g1 && !raw('profitDistributions').some(d => d.buildingId === g1.id && d.period === '2026-06')) { const d = X.generateDistribution('2026-06', g1.id, { at: '2026-07-06T09:00', profit: 3077280.96, note: 'LN được phân phối theo báo cáo tháng 6 workbook (golden NET_PROFIT 3.077.280,96); NET_PROFIT hệ thống thấp hơn do TOTAL_REVENUE chưa chốt Q-RPT-001' }); d.createdAt = '2026-07-06T09:00'; X.submitDistribution(d.id); st.session = asUser(admin); X.confirmDistribution(d.id, 'Xác nhận theo báo cáo tháng 6 đã khóa'); d.confirmedAt = '2026-07-08T15:00'; }
      // Kỳ 09/2026 đang review (cutoff 03/10), kỳ hiện tại mở
      st.session = asUser(ketoan || admin); if (!Q.reportPeriod('2026-09')) { X.reviewReportPeriod('2026-09'); const rp = Q.reportPeriod('2026-09'); rp.cutoffAt = '2026-10-03T17:00'; rp.history.forEach(h => h.at = h.type === 'open' ? '2026-10-01T09:00' : '2026-10-03T17:00'); } X.ensureReportPeriod(st.meta.period || '2026-10');
      // Audit demo do kịch bản sinh → gỡ userId để không tính là thao tác người dùng trong guide
      raw('auditLog').filter(a => a.entityType === 'reportPeriod' || a.entityType === 'profitDistribution').forEach(a => { if (a.at >= F.today()) { a.scenario = true; a.userId = null; } });
    } catch (e) { console.warn('w5 scenario', e); }
    finally { st.session = sess; St.save(); }
  };
})(window.TH);
