/* Panel Hướng dẫn – luồng Phase 2 (F11–F15, F08.5) + runAllP2. Chỉ hiện khi TH.phase.on(2); progress lưu chung store.state.guide. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, X = TH.actions, G = TH.guide; if (!G) return;
  const u = (c, f) => St.where(c, x => x.source === 'user' && (!f || f(x)));
  const last = (arr) => arr.sort((a, b) => F.cmp(b.createdAt || '', a.createdAt || ''))[0] || null;
  /* ngữ cảnh P2: record do người demo tạo */
  const ctx2 = () => {
    const lead = last(u('leads')); const viewing = lead ? last(u('viewings', v => v.leadId === lead.id)) : null; const hold = lead ? last(u('holds', h => h.leadId === lead.id)) : null; const deal = lead ? last(u('deals', d => d.leadId === lead.id)) : null; const contract = deal && deal.contractId ? St.get('contracts', deal.contractId) : null; const comm = deal ? St.one('commissions', c => c.dealId === deal.id) : null;
    const ocr = last(u('ocrExtractions')); const stJob = last(u('importJobs', j => j.type === 'statement')); const obJob = last(u('importJobs', j => j.type === 'opening')); const inc = last(u('incidents')); const sch = last(u('maintenanceSchedules')); const p10 = St.one('periods', p => p.period === '2026-10');
    const hero = St.one('zaloBatches', b => b.code === 'ZL-202610-104'); const heroRetry = hero ? St.where('zaloMessages', m => m.batchId === hero.id && m.retryOfId).length : 0;
    const rf = last(St.where('refunds', r => (r.history || []).some(h => h.status === 'needs_edit')));
    return { lead, viewing, hold, deal, contract, comm, ocr, stJob, obJob, inc, sch, p10, hero, heroRetry, rf, visited: St.state.guide.visited || {} };
  };
  const v = (c, path) => Object.keys(c.visited).some(k => k === path || k.startsWith(path + '?'));
  const P2 = [
    { key: 'F11', title: 'CRM: Lead → Chốt thuê', golive: '', phase: 2, ms: [
      { id: 'F11.1', title: 'Thêm lead', route: '#/crm/leads', role: 'sale', how: 'Chuyển vai trò Sale. Kinh doanh → Khách hàng / Lead → "+ Thêm lead" (hoặc "+ Thêm lead" cuối cột Kanban). Điền Họ tên, SĐT, Nguồn, Tòa quan tâm, ngân sách.', expect: 'Lead xuất hiện ở cột "Mới" với mức ưu tiên; trùng SĐT sẽ được cảnh báo (FR-SAL-01).', check: c => !!c.lead, hl: 'lead-add', sample: { kind: 'form', form: 'lead', values: { name: 'Lê Demo Lead', phone: '0912 555 666', email: 'demo.lead@gmail.com', channel: 'Form website', roomType: 'Căn hộ 1PN', people: 2, budgetMin: 7000000, budgetMax: 10000000, moveInDate: F.addDays(F.today(), 10), temp: 'hot', note: 'Cần chuyển vào đầu tháng, ưu tiên tầng cao' }, open: 'Bấm "+ Thêm lead" trước khi điền; chọn Nguồn khách và tick Tòa quan tâm' } },
      { id: 'F11.2', title: 'Ghi cuộc gọi & đặt lịch xem', route: c => c.lead ? '#/crm/leads/' + c.lead.id : '#/crm/leads', role: 'sale', how: 'Mở chi tiết lead → "Gọi khách" (kết quả Khách quan tâm) → "Đặt lịch xem": chọn phòng Sẵn sàng, ngày ≥ hôm nay, giờ, nhân viên, địa điểm → "Xác nhận lịch xem".', expect: 'Lead tự chuyển Mới → Đã liên hệ → Hẹn xem; lịch LX-… hiện ở tab Lịch xem phòng và ở Lịch xem sắp tới.', check: c => !!c.viewing, hl: 'lead-viewing' },
      { id: 'F11.3', title: 'Ghi kết quả xem → Cân nhắc', route: '#/crm/viewings', role: 'sale', how: 'Kinh doanh → Lịch xem phòng → dòng lịch vừa tạo → "Ghi kết quả" → "Đã xem – quan tâm".', expect: 'Lịch → Đã xem; lead → Cân nhắc, mức ưu tiên Cao; hoạt động được ghi vào timeline.', check: c => c.viewing && c.viewing.status === 'done' && c.lead && ['considering', 'held', 'won'].includes(c.lead.status), hl: 'viewings-table' },
      { id: 'F11.4', title: 'Giữ chỗ phòng', route: c => c.lead ? '#/crm/holds/new?lead=' + c.lead.id : '#/crm/holds/new', role: 'sale', how: 'Từ chi tiết lead bấm "Giữ chỗ" → chọn phòng Sẵn sàng → thời hạn ≤ 14 ngày, phí giữ chỗ, hình thức TT, người nhận, điều kiện hủy → "Xác nhận giữ chỗ".', expect: 'Phòng → Giữ chỗ (kiểm tra ở Phòng); lead → Giữ chỗ; khách thuê được tạo từ lead; countdown hết hạn chạy.', check: c => !!c.hold, hl: 'hold-confirm', sample: { kind: 'form', form: 'hold', values: { start: F.today(), until: F.addDays(F.today(), 7), fee: 2000000, feeMethod: 'Chuyển khoản', cancelPolicy: 'forfeit', note: 'Khách đang cân nhắc, giữ phòng để chờ xác nhận công ty.' }, open: 'Ở bước 3 của wizard Giữ chỗ (đã chọn lead + phòng)' } },
      { id: 'F11.5', title: 'Chốt thuê → tạo & kích hoạt HĐ', route: c => c.lead ? '#/crm/deals/new?lead=' + c.lead.id : '#/crm/deals/new', role: 'sale', how: '"Chốt thuê" → xác nhận khách thuê (tìm theo SĐT / tạo từ lead) → phòng đang giữ chỗ → điều khoản (ngày vào, thời hạn, giá, cọc, dịch vụ, số người) → "Xác nhận chốt thuê". Hệ thống chuyển sang Tạo hợp đồng đã điền sẵn → Lưu → chuyển vai trò Vận hành → "Xác nhận & kích hoạt".', expect: 'Giao dịch GD… Chờ ký HĐ → sau kích hoạt: Đang thuê; hold → Đã chuyển đổi; phòng → Đang thuê; lead → Chốt thuê.', check: c => c.deal && c.contract && c.contract.status === 'active', hl: 'deal-confirm' },
      { id: 'F11.6', title: 'Thu cọc → hoa hồng đủ điều kiện → ghi chi', route: c => c.deal ? '#/crm/deals/' + c.deal.id : '#/crm/deals', role: 'accountant', how: 'Chuyển vai trò Kế toán. Giao dịch & hoa hồng → mở giao dịch → "Thu tiền cọc" (đủ số cọc) → cột Điều kiện chi trả thành Đủ điều kiện (BR-13) → "Ghi nhận chi hoa hồng" (ngày + tham chiếu).', expect: 'Hoa hồng → Đã chi (bấm lại không tạo trùng – idempotent); chi phí nhóm Hoa hồng xuất hiện ở Chi phí.', check: c => c.comm && c.comm.status === 'paid', hl: 'commission-pay' },
    ] },
    { key: 'F12', title: 'OCR hợp đồng', golive: '', phase: 2, ms: [
      { id: 'F12.1', title: 'Dùng file mẫu, chạy trích xuất', route: '#/contracts/ocr', role: 'ops', how: 'Chuyển vai trò Vận hành. Hợp đồng → Tạo hợp đồng → chọn "Tải hợp đồng để hỗ trợ điền" (hoặc mở trực tiếp #/contracts/ocr) → "Dùng file mẫu".', expect: 'Thanh tiến độ trích xuất chạy ~2s → màn Review: parser đọc template "Hợp đồng cho thuê phòng" (4 trang) theo Điều 1–4, 5 trường Cần kiểm tra (tên, SĐT, mã phòng, ngày kết thúc, tiền cọc) + bảng tài sản bàn giao.', check: c => c.ocr && ['review', 'created'].includes(c.ocr.status), hl: 'ocr-sample', sample: { kind: 'file', name: 'HD-cho-thue-phong-mau.txt', purpose: 'Hợp đồng theo template "HĐ mới của Linh" đã điền, dùng để trích xuất (PDF điền trên máy cũng đọc được qua pdf.js)', rows: 4, cols: '4 trang: bên A/B, Điều 1 phòng, Điều 2 bảng tài sản, Điều 3 thời hạn, Điều 4 giá/cọc/đơn giá DV/ngân hàng', relations: 'Phòng Sẵn sàng của Tòa Sunrise; khách Nguyễn Thị Hương', errors: '5 trường cố tình sai: tên viết hoa không dấu, SĐT thiếu số, mã phòng thiếu dấu chấm, ngày kết thúc sai năm, tiền cọc lệch giá thuê' } },
      { id: 'F12.2', title: 'Sửa 5 trường Cần kiểm tra', route: c => c.ocr ? '#/contracts/ocr?id=' + c.ocr.id : '#/contracts/ocr', role: 'ops', how: 'Sửa trực tiếp hoặc bấm ✓ xác nhận từng trường có chip "Cần kiểm tra". Trường tiền (giá, cọc) bắt buộc xác nhận (BR-03). Chọn đúng phòng trong danh sách.', expect: 'Chip mất khi đã sửa/xác nhận; ô "trường cần kiểm tra" về 0; highlight trên trang HĐ chuyển vàng → xanh.', check: c => c.ocr && (c.ocr.fields || []).length && c.ocr.fields.every(f => f.confirmed) },
      { id: 'F12.3', title: 'Tạo hợp đồng từ trích xuất', route: c => c.ocr ? '#/contracts/ocr?id=' + c.ocr.id : '#/contracts/ocr', role: 'ops', how: 'Card "Kết quả trích xuất" cho biết khách thuê khớp hệ thống (SĐT/CCCD) hay chưa; nếu chưa, khách được tạo tự động từ thông tin HĐ khi bấm "Tạo hợp đồng" (hoặc bấm "Tạo khách thuê" để sửa trước). Form Tạo hợp đồng hiện banner "Dữ liệu từ trích xuất" đã điền sẵn khách, phòng, thời hạn, giá, cọc, dịch vụ, xe → "Lưu hợp đồng".', expect: 'Hợp đồng Dự thảo có nguồn OCR; lần trích xuất → Đã tạo HĐ.', check: c => c.ocr && c.ocr.status === 'created' && !!c.ocr.contractId, hl: 'ocr-create' },
    ] },
    { key: 'F13', title: 'Import bảng kê & đối soát', golive: '', phase: 2, ms: [
      { id: 'F13.1', title: 'Import bảng kê file mẫu → mapping', route: '#/finance/statement-import', role: 'accountant', how: 'Chuyển vai trò Kế toán. Tài chính → Nhập bảng kê thu tiền → "Dùng file mẫu" → kiểm tra mapping cột → "Tiếp tục review & ghép".', expect: '5 KPI (Tổng/Đã ghép/Cần kiểm tra/Trùng/Chưa phân bổ); bảng preview có chip kết quả ghép theo 4 quy tắc.', check: c => v(c, '/finance/statement-import'), hl: 'stmt-sample', sample: { kind: 'file', name: 'mau-bang-ke-thu-tien.csv', purpose: 'Bảng kê thu tiền từ ngân hàng', rows: 20, cols: 'Ngày GD, Số tiền, Mã ngoài, Mã hóa đơn, Mã HĐ, Phòng, Khách, Phương thức, Nội dung', relations: 'Mã hóa đơn/HĐ/phòng/khách của dữ liệu hiện có', errors: '2 dòng trùng mã ngoài; 2 dòng không ghép; 2 dòng hóa đơn nháp (cần kiểm tra); 2 dòng ghép khách + số tiền ±5%' } },
      { id: 'F13.2', title: 'Xử lý tay 1 dòng & duyệt ghi nhận', route: '#/finance/statement-import', role: 'accountant', how: 'Bấm ✎ trên một dòng "Cần kiểm tra" → chọn hóa đơn → Ghép; rồi "Duyệt ghi nhận".', expect: 'Mỗi dòng Đã ghép tạo 1 khoản thu (kind=statement); dòng trùng không tạo; chuyển sang chi tiết Data Job IMP-…', check: c => !!c.stJob, hl: 'stmt-commit' },
      { id: 'F13.3', title: 'Data Job: Kiểm tra lại → Thử lại', route: c => c.stJob ? '#/settings/jobs/' + c.stJob.id : '#/settings/jobs', role: 'accountant', how: 'Ở chi tiết job: dòng "Cần kiểm tra" do hóa đơn nháp → phát hành hóa đơn đó (Hóa đơn → Nháp → Phát hành) → quay lại job → "Kiểm tra lại" → "Thử lại phần đủ điều kiện".', expect: 'Dòng đổi thành "Đủ điều kiện thử lại" rồi "Thành công"; Lịch sử lần thử có #2; không tạo khoản thu trùng.', check: c => c.stJob && (c.stJob.attempts || []).length >= 2, hl: 'job-retry' },
      { id: 'F13.4', title: 'Chuyển số dư đầu kỳ (file mẫu)', route: '#/finance/opening-balance', role: 'accountant', how: 'Tài chính → Chuyển số dư ban đầu → mốc 01/11/2026 → "Tiếp tục" → "Dùng file mẫu" → xem đối chiếu (Hợp lệ/Chênh lệch/Cần kiểm tra) → tick dòng → "Xác nhận chuyển số dư".', expect: 'Mỗi HĐ được chọn có 1 hóa đơn opening (kỳ 11/2026) + khoản thu opening cho phần đã thu; công nợ P1 hiển thị bình thường.', check: c => !!c.obJob, hl: 'ob-commit', sample: { kind: 'file', name: 'mau-so-du-dau-ky.csv', purpose: 'Số dư công nợ/cọc từ hệ thống cũ', rows: 13, cols: 'Khách hàng, Mã hợp đồng, Phòng, Phải thu, Đã thu, Cọc giữ, Nguồn dữ liệu', relations: 'Mã HĐ hiện có', errors: '2 dòng cọc chênh lệch với hệ thống; 1 dòng HĐ không tồn tại (HD-2025-042)' } },
    ] },
    { key: 'F14', title: 'Bảo trì & bảo dưỡng', golive: '', phase: 2, ms: [
      { id: 'F14.1', title: 'Tạo sự cố từ chi tiết phòng', route: '#/rooms', role: 'ops', how: 'Chuyển vai trò Vận hành. Phòng → mở một phòng → "Tạo sự cố" (card Sự cố gần nhất hoặc menu Hành động): hạng mục, ưu tiên, mô tả, người phụ trách Kỹ thuật.', expect: 'Sự cố SC-… gắn tòa/phòng (FR-MNT-03); hiện ở tab Sự cố của phòng và ở Bảo trì & sự cố.', check: c => !!c.inc, hl: 'rooms-table', sample: { kind: 'form', form: 'incident', values: { category: 'Điều hòa', priority: 'high', desc: 'Máy lạnh không lạnh, có tiếng kêu lạ khi khởi động', dueDate: F.addDays(F.today(), 2), cost: 1500000 }, open: 'Bấm "Tạo sự cố" ở chi tiết phòng trước khi điền; chọn Người phụ trách' } },
      { id: 'F14.2', title: 'Kỹ thuật bắt đầu xử lý', route: c => c.inc ? '#/maintenance/incidents/' + c.inc.id : '#/maintenance', role: 'kythuat', how: 'Chuyển vai trò Kỹ thuật (chỉ có khi P2 bật) → Bảo trì - Sửa chữa → mở sự cố → "Bắt đầu xử lý".', expect: 'Trạng thái → Đang xử lý; timeline có mốc Bắt đầu.', check: c => c.inc && ['in_progress', 'done'].includes(c.inc.status), hl: 'incident-start' },
      { id: 'F14.3', title: 'Hoàn tất kèm chi phí', route: c => c.inc ? '#/maintenance/incidents/' + c.inc.id : '#/maintenance', role: 'kythuat', how: '"Hoàn tất" → nhập chi phí thực tế, NCC, ghi chú, ảnh → Hoàn tất.', expect: 'Sự cố → Hoàn tất; chi phí nhóm Sửa chữa gắn tòa/phòng xuất hiện ở Tài chính → Chi phí, liên kết mã sự cố.', check: c => c.inc && c.inc.status === 'done' && !!c.inc.expenseId, hl: 'incident-done' },
      { id: 'F14.4', title: 'Tạo lịch bảo dưỡng trong 7 ngày', route: '#/maintenance/schedules', role: 'ops', how: 'Chuyển vai trò Vận hành. Lịch bảo dưỡng → "Tạo lịch bảo dưỡng": thiết bị, tòa, chu kỳ, ngày trong 7 ngày tới, NCC, checklist.', expect: 'Pill hiện trên lịch tháng; KPI "Sắp đến hạn" tăng; chuông thông báo có "Lịch bảo dưỡng sắp đến hạn" (BR-16).', check: c => c.sch && Q.scheduleStatus(c.sch) === 'due_soon', hl: 'schedule-add', sample: { kind: 'form', form: 'schedule', values: { equipType: 'Thang máy', item: 'Bảo dưỡng thang máy - demo', cycle: 'monthly', date: F.addDays(F.today(), 3), note: 'Kiểm tra cáp, phanh, chạy thử' }, open: 'Bấm "Tạo lịch bảo dưỡng" trước khi điền; chọn Tòa và NCC' } },
    ] },
    { key: 'F15', title: 'Báo cáo, kỳ & Zalo nâng cao', golive: '', phase: 2, ms: [
      { id: 'F15.1', title: 'Tạo báo cáo Tỷ lệ lấp đầy → bản ghi → tải CSV', route: '#/reports/new', role: 'admin', how: 'Chuyển vai trò Admin. Báo cáo → Trung tâm báo cáo → "Tạo báo cáo" → chọn loại "Tỷ lệ lấp đầy" → Từ kỳ 09/2026, Đến kỳ 10/2026 → "Tạo báo cáo" → ở bản ghi bấm "Tải CSV".', expect: 'Bản ghi BC-xxxx với KPI, bảng Tổng hợp theo kỳ (2 dòng) và xem trước 3 trang; file CSV có cột Kỳ; danh sách Trung tâm báo cáo liệt kê bản ghi; loại OI không chọn được.', check: c => St.all('reportRuns').some(x => x.createdAt >= (St.state.meta.p2SeededAt || '')) },
      { id: 'F15.2', title: 'Dòng tiền → checklist → Khóa kỳ 10/2026', route: '#/reports/cashflow', role: 'accountant', how: 'Chuyển vai trò Kế toán. Báo cáo dòng tiền & quản lý kỳ → tick các mục còn thiếu trong Danh sách công việc kỳ (mục tự động chưa đạt có thể xác nhận tay sau khi rà soát) → "Khóa kỳ" → xác nhận.', expect: 'Kỳ 10/2026 → Đã khóa, số liệu snapshot; tạo hóa đơn/thu tiền/chi phí trong kỳ 10/2026 bị chặn (thử ghi nhận thu → lỗi FR-FIN-08).', check: c => c.p10 && c.p10.status === 'locked', hl: 'period-lock' },
      { id: 'F15.3', title: 'Zalo: Retry bản ghi lỗi (403/408)', route: c => c.hero ? '#/zalo/batches/' + c.hero.id : '#/zalo/history', role: 'admin', how: 'Chuyển vai trò Admin. Lịch sử gửi → đợt ZL-202610-104 → xem cột Nhà cung cấp phản hồi (200/300/403/408) → "Retry bản ghi lỗi".', expect: 'Chỉ tin 403/408 được xếp hàng lại (300 = lỗi vĩnh viễn, không retry); tin đã giao không gửi lại (FR-ZAL-04); log phản hồi & donut lỗi cập nhật.', check: c => c.heroRetry > 0, hl: 'zalo-retry' },
    ] },
    { key: 'F08.5', title: 'Hoàn cọc: Yêu cầu chỉnh sửa', golive: '', phase: 2, ms: [
      { id: 'F08.5.1', title: 'Kế toán yêu cầu chỉnh sửa', route: '#/refunds?status=pending', role: 'accountant', how: 'Chuyển vai trò Kế toán. Hoàn cọc → mở hồ sơ Chờ duyệt → "Yêu cầu chỉnh sửa" (nêu nội dung).', expect: 'Hồ sơ → Cần chỉnh sửa; lịch sử duyệt & ghi chú nội bộ ghi lại yêu cầu (SRS §6).', check: c => !!c.rf, hl: 'refunds-table' },
      { id: 'F08.5.2', title: 'Vận hành sửa khấu trừ → gửi duyệt lại', route: c => c.rf ? '#/refunds/' + c.rf.id : '#/refunds', role: 'ops', how: 'Chuyển vai trò Vận hành → mở hồ sơ Cần chỉnh sửa → "Thêm hạng mục"/sửa bảng khấu trừ (FR-FIN-07) → "Gửi duyệt".', expect: 'Hồ sơ → Chờ duyệt; tổng khấu trừ & đề nghị hoàn tính lại.', check: c => c.rf && ['pending', 'approved', 'refunded'].includes(c.rf.status) && (c.rf.history || []).filter(h => h.status === 'pending').length >= 2, hl: 'refund-submit' },
      { id: 'F08.5.3', title: 'Duyệt hồ sơ', route: c => c.rf ? '#/refunds/' + c.rf.id : '#/refunds', role: 'accountant', how: 'Chuyển vai trò Kế toán → "Duyệt".', expect: 'Hồ sơ → Đã duyệt; stepper trạng thái sang bước 3.', check: c => c.rf && ['approved', 'refunded'].includes(c.rf.status), hl: 'refund-approve' },
    ] },
  ];
  G.FLOWS.push(...P2);
  /* check() của luồng P2 dùng ctx2 – bọc lại để nhận đúng ngữ cảnh */
  P2.forEach(f => f.ms.forEach(m => { const chk = m.check; const rt = m.route; m.check = (c) => chk(Object.assign({}, c, ctx2())); if (typeof rt === 'function') m.route = (c) => rt(Object.assign({}, c || {}, ctx2())); }));

  /* Chạy kỹ thuật F11→F15 (Công cụ nâng cao) */
  G.runAllP2 = async () => {
    if (!TH.phase.on(2)) throw new Error('Bật Phase 2 trước');
    const wait = (ms) => new Promise(r => setTimeout(r, ms)); const prevRole = TH.auth.role(); const log = []; const tag = Date.now().toString().slice(-4);
    ['2026-10', St.state.meta.period].forEach(p => { if (Q.periodLocked(p)) { TH.auth.switchRole('admin'); X.unlockPeriod(p, 'Chạy lại kịch bản demo'); log.push('Mở lại kỳ ' + p + ' để chạy lại'); } });
    // F11
    TH.auth.switchRole('sale'); const sale = TH.auth.user();
    const lead = X.saveLead({ name: 'Lead Auto ' + tag, phone: '093' + Date.now().toString().slice(-7).replace(/(\d{1})(\d{3})(\d{3})/, '$1 $2 $3'), sourceId: (St.all('leadSources')[0] || (TH.seed.catalogP2(St.state), St.all('leadSources')[0])).id, roomType: 'Căn hộ 1PN', people: 2, budgetMin: 6000000, budgetMax: 10000000, buildingIds: [], saleId: sale.id, temp: 'hot' }); log.push('Lead ' + lead.code);
    X.addLeadActivity(lead.id, { type: 'call', result: 'interested', note: 'Auto' });
    const room = St.where('rooms', r => r.status === 'ready').sort((a, b) => a.code.localeCompare(b.code))[0]; if (!room) throw new Error('Không còn phòng Sẵn sàng');
    const vw = X.saveViewing({ leadId: lead.id, roomId: room.id, date: F.today(), time: '16:00', saleId: sale.id, remind: 'Gửi Zalo', place: 'Sảnh', force: true }); X.viewingResult(vw.id, { result: 'interested', note: 'Auto' });
    const hold = X.createHoldP2({ leadId: lead.id, roomId: room.id, start: F.today(), until: F.addDays(F.today(), 7), fee: 2000000, feeMethod: 'Chuyển khoản', receiverId: sale.id, cancelPolicy: 'forfeit' }); log.push('Giữ chỗ ' + hold.code);
    const deal = X.createDeal({ leadId: lead.id, roomId: room.id, moveIn: F.addDays(F.today(), 3), months: 12, price: room.price, deposit: room.price * 2, cycle: 'monthly', serviceIds: room.defaultServiceIds || [], people: 2 }); log.push('Giao dịch ' + deal.code);
    TH.auth.switchRole('ops'); const svc = (room.defaultServiceIds || []).map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: '' }; });
    const c = X.saveContractDraft({ tenantId: deal.tenantId, roomId: room.id, start: deal.moveIn, end: F.addDays(F.addMonths(deal.moveIn, 12), -1), payDay: 5, listPrice: room.price, price: room.price, deposit: room.price * 2, services: svc, members: [{ name: lead.name, relation: 'Người thuê (chính)', phone: lead.phone }], dealId: deal.id }); X.activateContract(c.id, 'auto2:' + c.id); log.push('HĐ ' + c.code);
    TH.auth.switchRole('accountant'); X.recordDealDeposit(deal.id, { amount: deal.deposit - (deal.depositPaid || 0), date: F.today(), method: 'Chuyển khoản', ref: 'AUTO' + tag }); X.payCommission(deal.id, { date: F.today(), ref: 'UNC-AUTO' + tag }); log.push('Hoa hồng đã chi');
    // F12
    TH.auth.switchRole('ops'); const o = X.ocrUpload({ fileName: 'HD-cho-thue-phong-mau.txt', size: 12 * 1024, sample: true, pages: 4 }); X.ocrExtract(o.id); X.ocrFinish(o.id); const spec = TH.ocr.sampleSpec(); const room2 = St.where('rooms', r => r.status === 'ready' && r.id !== room.id)[0] || spec.room; [['tenantName', spec.tenantName], ['phone', spec.phone], ['roomCode', room2.code], ['end', spec.end], ['deposit', String(spec.deposit)]].forEach(([k, val]) => X.ocrSetField(o.id, k, val, true)); o.fields.forEach(f => f.confirmed = true);
    const t2 = X.saveTenant({ name: spec.tenantName + ' ' + tag, phone: '094' + Date.now().toString().slice(-7).replace(/(\d{1})(\d{3})(\d{3})/, '$1 $2 $3') }); const c2 = X.saveContractDraft({ tenantId: t2.id, roomId: room2.id, start: F.fromVN(spec.start), end: F.fromVN(spec.end), payDay: 5, listPrice: room2.price, price: spec.price, deposit: spec.deposit, services: [], members: [{ name: t2.name, relation: 'Người thuê (chính)', phone: t2.phone }], ocrId: o.id }); log.push('OCR → HĐ ' + c2.code);
    // F13
    TH.auth.switchRole('accountant'); const rows = TH.imp.rowsToObjects(TH.imp.parse(TH.imp.statementSample().map(r => r.map(String)), TH.imp.STATEMENT.fields, TH.imp.STATEMENT.aliases)); rows.forEach((r, i) => { if (r.data.refCode && i < 15) r.data.refCode += '-' + tag; }); const matched = X.matchStatement(rows); if (!matched.some(r => r.status === 'matched')) log.push('Bảng kê: không còn hóa đơn nợ để ghép – bỏ qua F13.1-3'); else { const job = X.commitStatement({ rows: matched, fileName: 'mau-bang-ke-auto-' + tag + '.csv', checksum: 'auto-' + tag, period: St.state.meta.period }); log.push('Bảng kê ' + job.code + ' (' + job.created + ' khoản thu)');
    const draftLine = (job.lines || []).find(l => l.status === 'check' && l.invoiceId && (St.get('invoices', l.invoiceId) || {}).docStatus === 'draft'); if (draftLine) X.issueInvoice(draftLine.invoiceId); X.recheckJob(job.id); try { X.retryJob(job.id); } catch (e) { (job.attempts = job.attempts || []).push({ n: job.attempts.length + 1, at: F.nowISO(), by: (St.state.session || {}).userId, total: 0, ok: 0, failed: 0, status: 'done', note: 'Auto: ' + e.message }); } }
    const obRows = TH.imp.rowsToObjects(TH.imp.parse(TH.imp.openingSample().map(r => r.map(String)), TH.imp.OPENING.fields, TH.imp.OPENING.aliases)); const rec = X.reconcileOpening(obRows, '2026-11-01'); rec.forEach(r => r.selected = r.status === 'valid'); if (!rec.some(r => r.selected)) log.push('Số dư đầu kỳ: đã chuyển mốc 01/11/2026 trước đó – bỏ qua'); else { const ob = X.commitOpening({ rows: rec, asOf: '2026-11-01', fileName: 'mau-so-du-auto-' + tag + '.csv', checksum: 'auto-ob-' + tag }); log.push('Số dư ' + ob.code); }
    // F14
    TH.auth.switchRole('ops'); const inc = X.saveIncident({ buildingId: room.buildingId, roomId: room.id, category: 'Điều hòa', priority: 'high', desc: 'Auto – máy lạnh không lạnh', assigneeId: (St.one('users', u => u.username === 'kythuat') || {}).id }); TH.auth.switchRole('kythuat'); X.startIncident(inc.id); X.completeIncident(inc.id, { cost: 1500000, note: 'Auto' }); log.push('Sự cố ' + inc.code + ' hoàn tất');
    TH.auth.switchRole('ops'); const sch = X.saveSchedule({ equipType: 'Thang máy', item: 'Bảo dưỡng thang máy - auto ' + tag, buildingId: room.buildingId, cycle: 'monthly', date: F.addDays(F.today(), 3), vendorId: (St.all('vendors')[0] || {}).id }); log.push('Lịch BD ' + sch.code);
    // F15
    TH.auth.switchRole('admin'); X.setReportFavorite('occupancy', true); if (!St.all('reportRuns').some(x => x.type === 'occupancy' && x.createdAt >= (St.state.meta.p2SeededAt || ''))) X.createReportRun({ type: 'occupancy', periodFrom: '2026-09', periodTo: '2026-10' });
    TH.auth.switchRole('accountant'); ['revenue', 'expenses', 'debt', 'bank', 'review'].forEach(k => X.setPeriodCheck('2026-10', k, true)); try { if (Q.periodLocked('2026-10')) { TH.auth.switchRole('admin'); X.unlockPeriod('2026-10', 'Chạy lại kịch bản demo'); TH.auth.switchRole('accountant'); } X.lockPeriod('2026-10'); log.push('Khóa kỳ 10/2026'); } catch (e) { log.push('Khóa kỳ: ' + e.message); }
    TH.auth.switchRole('admin'); const hero = St.one('zaloBatches', b => b.code === 'ZL-202610-104'); if (hero) { try { X.retryBatch(hero.id); log.push('Retry Zalo 403/408'); } catch (e) { log.push('Retry: ' + e.message); } }
    // F08.5
    TH.auth.switchRole('ops'); const rf = St.one('refunds', r => r.status === 'pending' && r.code === 'RC202610-001') || St.one('refunds', r => r.status === 'pending'); TH.auth.switchRole('accountant'); if (rf) { X.requestRefundEdit(rf.id, 'Auto – bổ sung báo giá sơn tường'); TH.auth.switchRole('ops'); X.saveRefundDeductions(rf.id, Q.refundDeductions(rf.id).map(d => Object.assign({}, d)).concat([{ group: 'Sửa chữa', desc: 'Sơn lại tường (auto)', qty: 1, unitPrice: 500000, amount: 500000, evidenceCount: 1 }])); X.submitRefund(rf.id); TH.auth.switchRole('accountant'); X.approveRefund(rf.id); log.push('Hoàn cọc ' + rf.code + ' duyệt lại'); }
    await wait(1200);
    TH.auth.switchRole(prevRole === 'sale' || prevRole === 'kythuat' ? 'admin' : (prevRole || 'admin')); TH.layout.refreshTop(); St.state.guide.visited = Object.assign(St.state.guide.visited || {}, { '/crm/leads': 1, '/crm/viewings': 1, '/finance/statement-import': 1, '/finance/opening-balance': 1, '/reports/hub': 1, '/reports/cashflow': 1, '/maintenance': 1, '/contracts/ocr': 1 }); G.evaluate('sync');
    return log.join(' · ');
  };
})(window.TH);
