/* Panel Hướng dẫn – Phase 1 spec v1.8 Wave 5: F16 "Báo cáo tháng & đối soát" (§4.28, §12.23) và F17 "Cổ đông & chia lợi nhuận" (§4.29–4.32) + runAllW5. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, X = TH.actions, G = TH.guide; if (!G) return;
  const ctx = () => { const period = St.state.meta.period; const audit = St.rawAll('auditLog').filter(a => a && a.userId && !a.scenario); return { period, audit, visited: St.state.guide.visited || {}, g1: St.rawAll('buildings').find(b => b && b.code === 'G1') }; };
  const v = (c, path) => Object.keys(c.visited).some(k => k === path || k.startsWith(path + '?'));
  const W5 = [
    { key: 'F16', title: 'Báo cáo tháng: Report A/B → drill-down → khóa kỳ → đối soát golden', golive: '', ms: [
      { id: 'F16.1', title: 'Xem Report A tòa G1 kỳ 06/2026 (đã khóa) và drill-down', route: '#/reports/building-profit?period=2026-06', role: 'accountant', how: 'Chuyển vai trò Kế toán. Báo cáo → Báo cáo chi tiết tòa: chọn kỳ 06/2026, tòa G1; bấm kính lúp ở dòng "Doanh thu tiền phòng" → xem từng Invoice Line; thử drill "Chi phí lương" → Payroll Cost Allocation.', expect: 'Layout 12 nhóm §12.23.3, mỗi dòng có metric_code + trạng thái (Chờ chốt cho TOTAL_REVENUE, FORFEITED_DEPOSIT, phòng mới/trống/phá HĐ, HH/CPBH…); snapshot đã khóa 05/07/2026; bảng cổ phần 9 cổ đông = 100% với LN gộp/ròng × %.', check: c => v(c, '/reports/building-profit'), hl: 'ra-table' },
      { id: 'F16.2', title: 'Report B kỳ hiện tại: Total = T + S + G, tỷ lệ tính lại', route: '#/reports/business-summary', role: 'accountant', how: 'Báo cáo → Báo cáo kinh doanh T/S/G: xem cột Total/T/S/G; bấm số của nhóm G → danh sách tòa → Report A tòa.', expect: 'Loại tòa resolve theo Building Type History tại kỳ; chi phí chung & lương đã allocation trước khi aggregate; KPI báo "TOTAL = T + S + G ✓"; NET_MARGIN của Total tính từ NET_PROFIT/TOTAL_REVENUE tổng, không average.', check: c => v(c, '/reports/business-summary'), hl: 'rb-table' },
      { id: 'F16.3', title: 'Gửi review → Khóa kỳ hiện tại (snapshot)', route: '#/reports/periods', role: 'accountant', how: 'Báo cáo → Kỳ báo cáo: kỳ hiện tại bấm "Gửi review" rồi "Khóa kỳ". Sau đó mở Report A một tòa: sửa/thêm chi phí kỳ này ở Tài chính → Chi phí rồi quay lại – báo cáo không đổi (chip "Dữ liệu sống hiện lệch…").', expect: 'Kỳ → Đã khóa; sinh snapshot mỗi tòa + T/S/G; freeze metric version, allocation version, loại tòa, payroll allocation, share snapshot; audit PROFIT_REPORT_LOCKED. Mở lại (Admin) bắt buộc lý do.', check: c => c.audit.some(a => a.action === 'lock' && a.entityType === 'reportPeriod'), hl: 'rp-lock' },
      { id: 'F16.4', title: 'Đối soát golden G1 tháng 6 & ký xác nhận metric', route: '#/reports/reconcile', role: 'admin', how: 'Chuyển vai trò Admin. Báo cáo → Đối soát Excel: chọn "Golden Report A – G1 tháng 06/2026" → xem status từng metric; sang Metric Registry bấm "Xác nhận" một metric chờ chốt (VD NEW_ROOM_COUNT) nhập quyết định.', expect: 'RENT/ELECTRIC/WATER/…/COGS/OPERATING_SELLING_COST/TOTAL_COST = MATCH (từng line, không chỉ tổng); TOTAL_REVENUE, GROSS/NET_PROFIT, count = NEED_BUSINESS_CONFIRMATION kèm Q-RPT; Golden B tháng 8 = SOURCE_DATA_DIFFERENCE có ghi chú. Xác nhận metric tăng version, kỳ đã khóa giữ version cũ.', check: c => v(c, '/reports/reconcile') && (c.audit.some(a => a.action === 'confirm' && a.entityType === 'metricDefinition') || v(c, '/reports/metrics')), hl: 'rc-table' },
    ] },
    { key: 'F17', title: 'Cổ đông → cổ phần theo tòa → góp vốn → chia lợi nhuận từ báo cáo khóa', golive: '', ms: [
      { id: 'F17.1', title: 'Cấu hình cổ phần tòa theo ngày hiệu lực (tổng 100%, không ghi đè lịch sử)', route: '#/investment/shares', role: 'accountant', how: 'Chuyển vai trò Kế toán. Đầu tư → Cổ phần theo tòa: chọn G1, đổi "Tỷ lệ theo ngày" sang 30/06/2026 rồi hôm nay để thấy tỷ lệ khác nhau (An 7% → 5%, Lan 5% → 7% từ 01/09). Bấm "Cấu hình cổ phần": chuyển 1% giữa hai cổ đông từ ngày mai → Lưu.', expect: 'Tổng tại mọi ngày = 100% (lệch bị chặn); record cũ đóng effectiveTo, record mới từ ngày hiệu lực; lịch sử giữ nguyên; không đổi hồi tố vào kỳ đã khóa (báo cáo cũ dùng share snapshot).', check: c => c.audit.some(a => a.action === 'configure' && a.entityType === 'buildingShares'), hl: 'shares-config' },
      { id: 'F17.2', title: 'Tạo đợt góp vốn theo tòa → ghi nhận góp có chứng từ', route: '#/investment/shareholders?tab=capital', role: 'accountant', how: 'Đầu tư → Cổ đông → tab Góp vốn theo tòa → "Tạo đợt góp vốn" (tòa, tổng cần góp, hạn) → xem phân bổ theo cổ phần → Tạo. Mở đợt → "Ghi nhận" một cổ đông với UNC.', expect: 'Mỗi cổ đông: tỷ lệ, phải góp, đã góp, còn thiếu, hạn, ngày góp, chứng từ, ghi chú; không coi cam kết là thực góp; đợt → Đã góp đủ khi mọi dòng đủ.', check: c => c.audit.some(a => a.action === 'capital_pay'), hl: 'capital-table' },
      { id: 'F17.3', title: 'Generate phân phối LN từ kỳ đã khóa → xác nhận', route: '#/investment/shareholders?tab=profit', role: 'admin', how: 'Chuyển vai trò Admin. Tab Phân phối lợi nhuận → "Generate từ báo cáo khóa": chọn kỳ đã khóa (kỳ vừa khóa ở F16.3) và tòa → Generate → mở bảng → "Xác nhận".', expect: 'LN được phân phối = NET_PROFIT snapshot × tỷ lệ cổ phần snapshot; cột Vốn, LN gộp × %, LN ròng × %, Tổng nhận; chỉ generate được từ kỳ Locked; đổi cổ phần sau đó không đổi bảng; kỳ có bảng đã xác nhận không mở lại được.', check: c => c.audit.some(a => a.action === 'confirm' && a.entityType === 'profitDistribution'), hl: 'profit-table' },
      { id: 'F17.4', title: 'Chi tiết cổ đông & Export share table', route: '#/investment/shareholders', role: 'accountant', how: 'Chuyển vai trò Kế toán. Tab Cổ đông → "Xem" một cổ đông (tòa tham gia, lịch sử tỷ lệ, vốn góp, phần LN được phân bổ; thử "Ngừng hoạt động" – bị chặn khi còn cổ phần). Sang Cổ phần theo tòa → "Export share table". (Vai trò Cổ đông read-only thuộc cổng cổ đông Phase 3.)', expect: 'Master cổ đông có CCCD/MST, TK ngân hàng, trạng thái; chi tiết đủ 4 khối §4.29; export CSV tỷ lệ tại ngày chọn.', check: c => c.audit.some(a => a.action === 'export' && a.entityType === 'buildingShares'), hl: 'shares-export' },
    ] },
  ];
  const idx = G.FLOWS.findIndex(f => f.key === 'F15');
  G.FLOWS.splice(idx >= 0 ? idx + 1 : G.FLOWS.length, 0, ...W5);
  W5.forEach(f => f.ms.forEach(m => { const chk = m.check; m.check = (c) => chk(Object.assign({}, c, ctx())); }));

  G.runAllW5 = async () => {
    const log = []; const prevRole = TH.auth.role(); const period = St.state.meta.period; const tag = Date.now().toString().slice(-4);
    TH.auth.switchRole('accountant');
    // F16: review → lock kỳ hiện tại
    let rp = Q.reportPeriod(period); if (!rp || ['OPEN', 'REOPENED'].includes(rp.status)) X.reviewReportPeriod(period); rp = Q.reportPeriod(period); if (rp.status === 'REVIEWING') X.lockReportPeriod(period); log.push('Kỳ ' + period + ' ' + Q.label('reportPeriod', Q.reportPeriod(period).status));
    // F17.1: cấu hình cổ phần G1 từ ngày mai (chuyển 1% giữa 2 cổ đông đầu)
    const g1 = St.rawAll('buildings').find(b => b && b.code === 'G1'); if (g1) { const from = F.addDays(F.today(), 1); const cur = Q.buildingShares(g1.id, from); if (cur.length >= 2) { const rows = cur.map(s => ({ shareholderId: s.shareholderId, percentage: s.percentage })); rows[0].percentage = Math.round((rows[0].percentage - 1) * 100) / 100; rows[1].percentage = Math.round((rows[1].percentage + 1) * 100) / 100; X.configureShares({ buildingId: g1.id, effectiveFrom: from, rows, basis: 'Auto ' + tag, reason: 'Chuyển 1% (auto)' }); log.push('Cổ phần G1 từ ' + from + ' = ' + Q.buildingShareTotal(g1.id, from) + '%'); } }
    // F17.2: đợt góp vốn + ghi nhận
    if (g1) { const call = X.createCapitalCall({ buildingId: g1.id, name: 'Auto ' + tag, total: 45000000, dueDate: F.addDays(F.today(), 14) }); const l = Q.capitalLines(call.id)[0]; if (l) X.recordCapitalPayment(l.id, { amount: l.required, date: F.today(), ref: 'UNC-AUTO' + tag }); log.push('Góp vốn ' + call.code); X.exportShareTable(g1.id, F.today()); }
    // F17.3: generate phân phối từ kỳ vừa khóa → xác nhận
    TH.auth.switchRole('admin'); const bs = TH.reportP1.liveBuildings(period); const target = bs.find(b => !St.rawAll('profitDistributions').some(d => d && d.period === period && d.buildingId === b.id && d.status !== 'cancelled') && Q.buildingShares(b.id, Q.periodEndDate(period)).length); if (target) { try { const d = X.generateDistribution(period, target.id); X.confirmDistribution(d.id, 'Auto ' + tag); log.push('Phân phối ' + d.code + ' ' + F.vnd(d.profitDistributable)); } catch (e) { log.push('Phân phối: ' + e.message); } }
    St.state.guide.visited = Object.assign(St.state.guide.visited || {}, { '/reports/building-profit': 1, '/reports/business-summary': 1, '/reports/periods': 1, '/reports/reconcile': 1, '/reports/metrics': 1, '/investment/shares': 1, '/investment/shareholders': 1 });
    if (prevRole && prevRole !== 'admin') try { TH.auth.switchRole(prevRole); } catch (e) { }
    return log.join(' · ');
  };
})(window.TH);
