/* Panel Hướng dẫn – Phase 1 spec v1.8 Wave 4: F14 "Hiệu suất thu tiền → bảng lương → chi lương" (§4.26, §12.20) và F15 "Import chi phí & phân bổ chi phí chung" (§4.27, §12.21) + runAllW4. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, X = TH.actions, G = TH.guide; if (!G) return;
  const ctx = () => { const period = St.state.meta.period; const pay = Q.payroll(period); const sal = Q.salaryPayments({ period }); const impx = St.rawAll('importJobs').filter(j => j && j.type === 'expense' && j.source === 'user'); const alloc = St.rawAll('auditLog').filter(a => a && a.action === 'allocate' && a.entityType === 'expense'); return { period, pay, sal, impx, alloc, visited: St.state.guide.visited || {} }; };
  const v = (c, path) => Object.keys(c.visited).some(k => k === path || k.startsWith(path + '?'));
  const W4 = [
    { key: 'F14', title: 'Hiệu suất thu tiền → bảng lương → chi lương', golive: '', ms: [
      { id: 'F14.1', title: 'Xem hiệu suất thu tiền M1/M2/M3 theo NV × tòa', route: '#/hr/collection-performance', role: 'admin', how: 'Nhân sự → Hiệu suất thu tiền: chọn kỳ, lọc tổ chức/NV/tòa; bấm kính lúp trên một dòng để drill-down về giao dịch thu.', expect: 'Mỗi dòng NV × tòa: số phòng, DT niêm yết, DT phải thu, thu M1/M2/M3, tổng sau 3 mốc, dịch vụ, tỷ lệ DV/DT, thu thêm, tổng DT thu được, hiệu suất % (mẫu số = DT niêm yết), mức lương/phòng theo Payroll Rule, lương theo phòng. Mọi số thu truy được về Payment Allocation (§4.26.10).', check: c => v(c, '/hr/collection-performance'), hl: 'perf-table' },
      { id: 'F14.2', title: 'Mở kỳ lương → snapshot → điều chỉnh có lý do → gửi review', route: '#/hr/payroll', role: 'hr', how: 'Chuyển vai trò Nhân sự. Nhân sự → Bảng lương: nếu chưa có bấm "Mở kỳ lương"; bấm biểu tượng điều chỉnh trên một dòng, nhập số tiền + lý do; bấm "Gửi review".', expect: 'Bảng lương Nháp có snapshot NV + tòa + kỳ (drill-down §4.26.7); cấu phần §4.26.5: cơ bản + ăn trưa + xăng xe + trưởng nhóm + hỗ trợ + lương hiệu suất + điều chỉnh − khấu trừ; không có hoa hồng Sale / PC số nhà. Điều chỉnh không lý do bị chặn.', check: c => !!c.pay && ['review', 'approved', 'locked'].includes(c.pay.status), hl: 'pay-submit' },
      { id: 'F14.3', title: 'Duyệt → Khóa bảng lương', route: '#/hr/payroll', role: 'accountant', how: 'Chuyển vai trò Kế toán → "Duyệt" → "Khóa bảng lương". Thử "Mở lại" (chỉ Admin, cần lý do).', expect: 'Trạng thái Đã khóa; sinh danh sách chi lương + Payroll Cost Allocation theo tòa (NV trực tiếp theo snapshot, vai trò chung theo Allocation Rule). Không tạo chi phí "Lương" ở Tài chính → Chi phí (§4.27.4).', check: c => !!c.pay && c.pay.status === 'locked', hl: 'pay-lock' },
      { id: 'F14.4', title: 'Chi lương: từng người / hàng loạt / import kết quả', route: '#/hr/salary-payments', role: 'accountant', how: 'Nhân sự → Chi lương: "Ghi nhận chi" một người (thử chi một phần), rồi "Chi hàng loạt" phần còn lại; có thể Import kết quả GD (file mẫu).', expect: 'Trạng thái Chưa chi → Chi một phần → Đã chi (+ Chi lỗi / Đã hủy / Đã điều chỉnh); TK nhận snapshot, mã GD, chứng từ, người thực hiện, lịch sử chi; tổng phải chi / đã chi / còn phải chi.', check: c => St.rawAll('auditLog').some(a => a && ['salary_pay', 'salary_bulk'].includes(a.action) && a.userId), hl: 'salary-table' },
    ] },
    { key: 'F15', title: 'Import chi phí & phân bổ chi phí chung', golive: '', ms: [
      { id: 'F15.1', title: 'Import chi phí từ file mẫu – phát hiện dòng trùng', route: '#/settings/import?type=expense', role: 'accountant', how: 'Tài chính → Chi phí → "Import chi phí" → "Dùng file mẫu" → mapping → kiểm tra → xác nhận. File mẫu có 1 dòng trùng phiếu đã có, 1 tòa không tồn tại, 1 hạng mục sai.', expect: 'Dòng trùng (ngày + số tiền + nội dung) và dòng lỗi bị chặn, không tạo; dòng CHUNG tạo phiếu Chờ phân bổ; phiếu tạo có nguồn Import, Work Queue "Import chi phí lỗi" đếm dòng lỗi.', check: c => c.impx.length > 0, hl: 'import-sample' },
      { id: 'F15.2', title: 'Phân bổ chi phí chung theo số phòng / doanh thu / nhóm T-S-G', route: '#/expenses?status=pending_alloc', role: 'accountant', how: 'Tài chính → Chi phí → lọc Chờ phân bổ → "Phân bổ" trên phiếu văn phòng: chọn phương thức (Theo số phòng / Theo doanh thu / Theo số tòa / Tỷ lệ nhập tay) và phạm vi (tòa hoặc nhóm T/S/G) → xem preview → Xác nhận.', expect: 'Expense Allocation lưu phiếu nguồn, tòa nhận, cơ sở, tỷ lệ, số tiền, phương thức, kỳ, người xác nhận (§12.21.4); phiếu → Đã phân bổ; hạng mục Hoa hồng có Sale/phòng/ngày TT (§4.27.5).', check: c => c.alloc.length > 0, hl: 'expense-alloc' },
    ] },
  ];
  const idx = G.FLOWS.findIndex(f => f.key === 'F13');
  G.FLOWS.splice(idx >= 0 ? idx + 1 : G.FLOWS.length, 0, ...W4);
  W4.forEach(f => f.ms.forEach(m => { const chk = m.check; m.check = (c) => chk(Object.assign({}, c, ctx())); }));

  G.runAllW4 = async () => {
    const log = []; const prevRole = TH.auth.role(); const period = St.state.meta.period; const tag = Date.now().toString().slice(-4);
    // F14: mở kỳ (nếu cần) → điều chỉnh → review → duyệt → khóa → chi lương
    TH.auth.switchRole('hr'); let p = Q.payroll(period); if (!p) p = X.openPayrollPeriod(period); if (p.status === 'draft') { const r = Q.payrollResults(p.id)[0]; if (r) X.adjustPayrollLine(period, r.employeeId, { amount: 300000, reason: 'Auto ' + tag + ' – hỗ trợ bàn giao' }); X.submitPayroll(period); }
    TH.auth.switchRole('accountant'); if (Q.payroll(period).status === 'review') X.approvePayroll(period); if (Q.payroll(period).status === 'approved') X.lockPayroll(period); log.push('Bảng lương ' + Q.payroll(period).code + ' ' + Q.label('payroll', Q.payroll(period).status));
    const sp = Q.salaryPayments({ period }).filter(s => ['unpaid', 'partial', 'failed'].includes(s.status)); if (sp[0]) X.recordSalaryPayment(sp[0].id, { amount: Math.round((sp[0].amountDue - sp[0].amountPaid) / 2 / 1000) * 1000, date: F.today(), method: 'Chuyển khoản', ref: 'UNC-AUTO' + tag, evidence: 'unc_auto.pdf' }); try { const b = X.bulkSalaryPayments(period, { date: F.today(), ref: 'UNC-AUTO' + tag }); log.push('Chi lương ' + b.count + ' khoản'); } catch (e) { log.push('Chi lương: ' + e.message); }
    // F15: import chi phí (file mẫu) + phân bổ chi phí chung
    const cur = period; const b0 = St.where('buildings', b => !b.stub && b.status !== 'inactive')[0]; const rows = [{ i: 1, status: 'ok', issues: [], data: { date: cur + '-18', categoryCode: 'GV-DIEN', desc: 'Auto ' + tag + ' điện hành lang', buildingCode: b0 ? b0.code : '', amount: '1234000', supplier: 'EVN' } }, { i: 2, status: 'warn', issues: [], data: { date: cur + '-18', categoryCode: 'VH-VP', desc: 'Auto ' + tag + ' văn phòng phẩm', buildingCode: 'CHUNG', amount: '900000', supplier: 'Thiên Long' } }, { i: 3, status: 'error', issues: ['Tòa không tồn tại'], data: { date: cur + '-18', categoryCode: 'GV-RAC', desc: 'Auto lỗi', buildingCode: 'Tòa ABC', amount: '100' } }];
    const job = X.runImport({ type: 'expense', fileName: 'auto-' + tag + '.csv', rows, checksum: 'auto-' + tag }); log.push('Import chi phí ' + job.code + ' tạo ' + job.created + ' bỏ qua ' + job.skipped);
    const pend = St.where('expenses', e => e.status === 'pending_alloc')[0]; if (pend) { const r = X.allocateExpense(pend.id, { method: 'ROOM_COUNT', buildingIds: St.where('buildings', b => !b.stub && b.status !== 'inactive').map(b => b.id) }); log.push('Phân bổ ' + pend.code + ' cho ' + r.rows.length + ' tòa'); }
    St.state.guide.visited = Object.assign(St.state.guide.visited || {}, { '/hr/collection-performance': 1, '/hr/payroll': 1, '/hr/salary-payments': 1, '/settings/import?type=expense': 1, '/expenses': 1 });
    if (prevRole && prevRole !== 'accountant') try { TH.auth.switchRole(prevRole); } catch (e) { }
    return log.join(' · ');
  };
})(window.TH);
