/* Panel Hướng dẫn – luồng Phase 3 (F16 Kiểm kê tài sản, F17 Nhân sự → Lương, F18 Cổ đông & vốn góp, F19 Ngân hàng) + runAllP3. Chỉ hiện khi TH.phase.on(3); progress lưu chung store.state.guide. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store, X = TH.actions, G = TH.guide; if (!G) return;
  const u = (c, f) => St.where(c, x => x.source === 'user' && (!f || f(x)));
  const last = (arr) => arr.sort((a, b) => F.cmp(b.createdAt || '', a.createdAt || ''))[0] || null;
  const nextPeriod = () => F.period(F.addMonths(F.today(), 1));
  /* ngữ cảnh P3: record do người demo tạo */
  const ctx3 = () => {
    const inv = last(u('inventories')) || St.one('inventories', i => i.status === 'in_progress');
    const invLines = inv ? St.where('inventoryLines', l => l.inventoryId === inv.id && l.checkedById) : [];
    const emp = last(u('employees')); const assign = emp ? St.one('buildingAssignments', a => a.employeeId === emp.id && a.status === 'active') : null;
    const period = St.state.meta.period; const ts = Q.timesheetStats(period); const pay = Q.payroll(period);
    const sh = last(u('shareholders')); const rounds = u('contributions'); const paidRound = rounds.find(c => c.paidAmount > 0) || St.one('contributions', c => c.source !== 'seed' && c.paidAmount > 0) || St.one('contributions', c => (c.history || []).length);
    const dist = last(u('distributions'));
    const bankTx = u('bankTransactions'); const bankMatched = bankTx.filter(t => t.matchStatus === 'matched'); const manual = St.where('bankTransactions', t => t.rule === 5);
    return { inv, invLines, invUserDone: !!inv && inv.status === 'done' && inv.source === 'user', emp, assign, ts, pay, sh, rounds, paidRound, dist, bankTx, bankMatched, manual, visited: St.state.guide.visited || {} };
  };
  const v = (c, path) => Object.keys(c.visited).some(k => k === path || k.startsWith(path + '?'));
  const P3 = [
    { key: 'F16', title: 'Kiểm kê tài sản', golive: '', phase: 3, ms: [
      { id: 'F16.1', title: 'Bắt đầu đợt kiểm kê kỳ tới', route: () => '#/assets/inventory?period=' + nextPeriod(), role: 'accountant', how: 'Chuyển vai trò Kế toán. Đầu tư → Tài sản → Kiểm kê (hoặc Bảo trì → tab Kiểm kê hàng tháng) → chọn tháng ' + F.periodLabel(nextPeriod()) + ' → "Bắt đầu kiểm kê" → tick tòa → xác nhận.', expect: 'Tạo biên bản BB-KK-' + nextPeriod() + ' trạng thái Đang kiểm kê với toàn bộ tài sản đang sử dụng ở trạng thái Chưa kiểm kê (FR-MNT-02).', check: c => !!c.inv && c.inv.source === 'user', hl: 'inv-start' },
      { id: 'F16.2', title: 'Cập nhật tình trạng 1 tài sản', route: c => c.inv ? '#/assets/inventory?period=' + c.inv.period + '&status=pending' : '#/assets/inventory', role: 'ops', how: 'Chuyển vai trò Vận hành (tòa được giao). Bấm "Xem" trên một dòng Chưa kiểm kê → chọn tình trạng "Hư hỏng nhẹ", ghi chú, gắn ảnh → "Lưu kết quả".', expect: 'Dòng chuyển Cần xử lý, lưu người kiểm kê + thời điểm + ảnh; tình trạng tài sản (và tài sản trong phòng ở P1) đồng bộ; KPI Cần xử lý tăng.', check: c => c.invLines.length > 0, hl: 'inv-record', sample: { kind: 'form', form: 'inventory', values: { condition: 'minor', note: 'Cửa tủ lạnh bị lệch bản lề, còn hoạt động – đề xuất bảo dưỡng' }, open: 'Bấm "Xem" trên một dòng Chưa kiểm kê trước khi điền' } },
      { id: 'F16.3', title: 'Đánh dấu hàng loạt Bình thường', route: c => c.inv ? '#/assets/inventory?period=' + c.inv.period + '&status=pending' : '#/assets/inventory', role: 'ops', how: 'Tick nhiều dòng Chưa kiểm kê → "Đánh dấu Bình thường (đã chọn)".', expect: 'Các dòng chuyển Hoàn thành với người kiểm kê là bạn; tiến độ đợt tăng.', check: c => c.invLines.filter(l => l.status === 'done').length >= 2, hl: 'inventory-table' },
      { id: 'F16.4', title: 'Hoàn tất kiểm kê & xuất biên bản', route: c => c.inv ? '#/assets/inventory/' + c.inv.id : '#/assets/inventory', role: 'accountant', how: 'Chuyển vai trò Kế toán → mở biên bản → "Hoàn tất kiểm kê" → "Xuất biên bản" (CSV).', expect: 'Biên bản → Đã hoàn thành, không sửa được kết quả; không có chi phí/giảm tài sản nào được tạo (AC-FR-MNT-02-2); tài sản Cần xử lý có nút "Tạo sự cố" (Phase 2).', check: c => c.invUserDone, hl: 'inv-finish' },
    ] },
    { key: 'F17', title: 'Nhân sự → phân công → công → lương', golive: '', phase: 3, ms: [
      { id: 'F17.1', title: 'Thêm nhân viên', route: '#/hr', role: 'hr', how: 'Chuyển vai trò Nhân sự. Nhân sự → Nhân viên → "+ Thêm nhân viên": họ tên, phòng ban, chức danh, SĐT, ngày vào làm, ngày hết thử việc, lương cơ bản.', expect: 'Nhân viên NV… trạng thái Thử việc xuất hiện trong danh sách và ở "Sắp hết thử việc"; trùng SĐT bị chặn.', check: c => !!c.emp, hl: 'emp-add', sample: { kind: 'form', form: 'employee', values: { name: 'Lê Demo Nhân Sự', dept: 'vanhanh', title: 'Nhân viên', phone: '0912 000 777', email: 'demo.ns@timohouse.vn', address: 'Quận 7, TP.HCM', workType: 'Toàn thời gian', startDate: F.today(), probationEnd: F.addDays(F.today(), 45), area: 'Khu Q.7', salaryBase: 9000000, titleAllowance: 500000 }, open: 'Bấm "+ Thêm nhân viên" trước khi điền' } },
      { id: 'F17.2', title: 'Phân công tòa chính', route: c => c.emp ? '#/hr/' + c.emp.id : '#/hr', role: 'hr', how: 'Mở chi tiết nhân viên → "Phân công tòa nhà": chọn tòa, vai trò NV vận hành, tick Tòa chính.', expect: 'Card Tòa nhà phụ trách có tòa với chip Chính; tab Phân công ghi lịch sử (FR-BLD-07); phụ cấp số nhà tính theo số tòa.', check: c => !!c.assign, hl: 'emp-assign' },
      { id: 'F17.3', title: 'Xác nhận bảng công kỳ hiện tại', route: '#/hr/timesheet', role: 'hr', how: 'Nhân sự → Chấm công → "Điền mặc định" (nếu còn ô trống) → "Xác nhận bảng công".', expect: 'Bảng công → Đã xác nhận, ô chấm công khóa; bảng lương dùng số công này.', check: c => c.ts.confirmed, hl: 'ts-confirm' },
      { id: 'F17.4', title: 'Tính lương → gửi duyệt → duyệt → chi', route: '#/hr/payroll', role: 'hr', how: 'Nhân sự → Lương thưởng → "Tính bảng lương kỳ" → "Gửi duyệt". Chuyển vai trò Kế toán → "Duyệt" → "Ghi nhận chi lương".', expect: 'Bảng lương qua Nháp → Chờ duyệt → Đã duyệt → Đã chi; chi phí nhóm "Lương" theo tòa xuất hiện ở Tài chính → Chi phí (kỳ đã khóa sẽ bị chặn – FR-FIN-08).', check: c => c.pay && c.pay.status === 'paid', hl: 'pay-build' },
    ] },
    { key: 'F18', title: 'Cổ đông, vốn góp & phân phối', golive: '', phase: 3, ms: [
      { id: 'F18.1', title: 'Thêm cổ đông với tỷ lệ theo dự án', route: '#/investment/shareholders', role: 'accountant', how: 'Chuyển vai trò Kế toán. Đầu tư → Hiệu quả đầu tư (Cổ đông & vốn góp) → "+ Thêm cổ đông": thông tin + nhập tỷ lệ % cho 1–2 dự án còn dư tỷ lệ.', expect: 'Cổ đông CD-… xuất hiện với trạng thái Chưa góp; tỷ lệ lưu đúng như nhập (AC-FR-SHR-02-1); vượt 100%/dự án bị chặn.', check: c => !!c.sh, hl: 'sh-add', sample: { kind: 'form', form: 'shareholder', values: { name: 'Lê Demo Cổ Đông', email: 'demo.codong@gmail.com', phone: '0913 000 888', idNumber: '079012345678' }, open: 'Bấm "+ Thêm cổ đông"; sau khi điền, nhập tỷ lệ (ví dụ 5) cho dự án Sunrise – lưu ý tổng tỷ lệ Sunrise hiện đã 100%, hãy giảm tỷ lệ cổ đông khác hoặc chọn dự án còn dư' } },
      { id: 'F18.2', title: 'Tạo đợt góp vốn → nghĩa vụ theo tỷ lệ', route: '#/investment/shareholders?tab=contributions', role: 'accountant', how: '"Tạo khoản góp vốn": chọn dự án, tên đợt, hạn, tổng đợt → xem preview nghĩa vụ từng cổ đông → "Tạo đợt góp vốn".', expect: 'Tab Đóng góp theo kỳ có 1 nghĩa vụ/cổ đông của dự án (AC-FR-SHR-01-2), trạng thái Chưa đến hạn; Lịch đóng góp sắp tới cập nhật.', check: c => c.rounds.length > 0, hl: 'round-add', sample: { kind: 'form', form: 'round', values: { round: 'Đợt góp vốn bổ sung 11/2026', dueDate: F.addDays(F.today(), 10), total: 500000000, note: 'Bổ sung vốn sửa chữa thang máy' }, open: 'Bấm "Tạo khoản góp vốn" trước khi điền; chọn Dự án' } },
      { id: 'F18.3', title: 'Ghi nhận góp vốn', route: '#/investment/shareholders?tab=contributions', role: 'accountant', how: 'Trên một nghĩa vụ chưa góp bấm "Ghi nhận": số tiền, ngày, UNC → Ghi nhận.', expect: 'Nghĩa vụ → Đã góp (hoặc Góp một phần); cột Số vốn đã góp tăng; bấm lại cùng chứng từ không tạo trùng (idempotent).', check: c => !!c.paidRound, hl: 'contrib-record' },
      { id: 'F18.4', title: 'Lập bảng phân phối → duyệt → ghi đã chi', route: '#/investment/shareholders?tab=distributions', role: 'accountant', how: '"Tạo phân phối": kỳ, lợi nhuận được phân phối → xem preview + làm tròn → Lập. Mở bảng → chuyển vai trò Admin "Duyệt" → Kế toán "Ghi nhận đã chi".', expect: 'Kỳ phân phối qua Chờ → Đã duyệt → Đã chi; Σ dòng + làm tròn = lợi nhuận duyệt (AC-FR-SHR-02-2); không tạo chi phí vận hành.', check: c => c.dist && c.dist.status === 'paid', hl: 'dist-add', sample: { kind: 'form', form: 'distribution', values: { label: 'Q4/2026 (demo)', profit: 900000000, date: F.addDays(F.today(), 30) }, open: 'Bấm "Tạo phân phối" trước khi điền' } },
      { id: 'F18.5', title: 'Xem với vai trò Cổ đông (read-only)', route: '#/investment/shareholders', role: 'codong', how: 'Chuyển vai trò Cổ đông (Trần Minh Đức – góp Sunrise/Moonlight/Riverside). Xem Cổ đông & vốn góp, Dự án, Hiệu quả đầu tư.', expect: 'Chỉ thấy dòng của mình và các dự án/tòa đã góp (Central, Garden không hiện – FR-SHR-03 AC-2); không có nút Thêm/Ghi nhận/Duyệt (FR-SHR-04 AC-2); Nhân sự/Tài chính không truy cập được.', check: c => (St.state.guide.visitedRole || {})['codong:/investment/shareholders'] || false, hl: 'shareholders-table' },
    ] },
    { key: 'F19', title: 'Ngân hàng & đối soát', golive: '', phase: 3, ms: [
      { id: 'F19.1', title: 'Nhập sao kê mẫu → đối soát tự động', route: '#/finance/bank', role: 'accountant', how: 'Chuyển vai trò Kế toán. Tài chính → Ngân hàng → "Nhập sao kê" → "Dùng file mẫu" → "Nhập sao kê" → "Đối soát tự động" (cần Phase 2 bật để dùng quy tắc ghép bảng kê).', expect: 'Giao dịch mới xuất hiện Chưa khớp; sau đối soát: dòng khớp mã hóa đơn/HĐ → Đã khớp + tạo khoản thu; dòng mơ hồ → Cần kiểm tra; trùng mã giao dịch không tạo trùng.', check: c => c.bankMatched.length > 0, hl: 'bank-import-btn', sample: { kind: 'file', name: 'mau-sao-ke-ngan-hang.csv', purpose: 'Sao kê ngân hàng (giao dịch tiền vào)', rows: 20, cols: 'Ngày giao dịch, Số tiền, Mã giao dịch, Mã hóa đơn, Mã hợp đồng, Phòng, Khách thuê, Phương thức, Nội dung', relations: 'Mã hóa đơn/HĐ/phòng/khách của dữ liệu hiện có', errors: '2 dòng trùng mã giao dịch; 2 dòng không khớp; 2 dòng hóa đơn nháp (cần kiểm tra)' } },
      { id: 'F19.2', title: 'Khớp thủ công 1 giao dịch', route: '#/finance/bank?status=unmatched&period=all', role: 'accountant', how: 'Lọc Chưa khớp → bấm "Khớp" trên một giao dịch → chọn hóa đơn còn nợ → "Khớp & ghi nhận thu".', expect: 'Giao dịch → Đã khớp, liên kết khoản thu PAY-…; hóa đơn giảm còn nợ tương ứng.', check: c => c.manual.length > 0, hl: 'bank-match' },
    ] },
  ];
  G.FLOWS.push(...P3);
  /* check()/route() của luồng P3 dùng ctx3 – bọc lại để nhận đúng ngữ cảnh */
  P3.forEach(f => f.ms.forEach(m => { const chk = m.check; const rt = m.route; m.check = (c) => chk(Object.assign({}, c, ctx3())); if (typeof rt === 'function') m.route = (c) => rt(Object.assign({}, c || {}, ctx3())); }));
  /* mốc F18.5: ghi nhận route đã xem với vai trò cổ đông */
  St.on((what) => { try { const s = St.state.session; if (s && s.role === 'codong' && location.hash.startsWith('#/investment/shareholders')) { St.state.guide.visitedRole = St.state.guide.visitedRole || {}; if (!St.state.guide.visitedRole['codong:/investment/shareholders']) { St.state.guide.visitedRole['codong:/investment/shareholders'] = 1; St.save(); G.evaluate('sync'); } } } catch (e) { } });
  window.addEventListener('hashchange', () => setTimeout(() => St.emit('route-p3'), 50));
  /* file mẫu sao kê: sinh từ dữ liệu hiện có (quy tắc ghép P2) */
  const sampleFile0 = G.sampleFile; G.sampleFile = (m) => { if (m && m.sample && m.sample.name === 'mau-sao-ke-ngan-hang.csv' && TH.imp && TH.imp.statementSample) { const rows = TH.imp.statementSample(); rows[0] = ['Ngày giao dịch', 'Số tiền', 'Mã giao dịch', 'Mã hóa đơn', 'Mã hợp đồng', 'Phòng', 'Khách thuê', 'Phương thức', 'Nội dung']; return new File(['﻿' + F.csv(rows.slice(1), rows[0])], m.sample.name, { type: 'text/csv' }); } return sampleFile0(m); };

  /* Chạy kỹ thuật F16→F19 (Công cụ nâng cao) */
  G.runAllP3 = async () => {
    if (!TH.phase.on(3)) throw new Error('Bật Phase 3 trước');
    const wait = (ms) => new Promise(r => setTimeout(r, ms)); const prevRole = TH.auth.role(); const log = []; const tag = Date.now().toString().slice(-4);
    // F16
    TH.auth.switchRole('accountant'); const per = nextPeriod(); let inv = St.one('inventories', i => i.period === per); if (inv && inv.status === 'done') { const p2 = F.period(F.addMonths(F.today(), 2)); inv = X.startInventory({ period: p2, buildingIds: [] }); } else inv = X.startInventory({ period: per, buildingIds: [] }); log.push('Kiểm kê ' + inv.code);
    TH.auth.switchRole('admin'); const pend = St.where('inventoryLines', l => l.inventoryId === inv.id && l.status === 'pending'); if (pend.length) { X.recordInventoryLine(pend[0].id, { condition: 'minor', note: 'Auto – hư hỏng nhẹ', photo: true }); X.bulkInventoryGood(pend.slice(1, 6).map(l => l.id)); } TH.auth.switchRole('accountant'); X.finishInventory(inv.id); log.push('Hoàn tất kiểm kê');
    // F17
    TH.auth.switchRole('hr'); const emp = X.saveEmployee({ name: 'NV Auto ' + tag, dept: 'vanhanh', title: 'Nhân viên', phone: '091' + Date.now().toString().slice(-7).replace(/(\d{1})(\d{3})(\d{3})/, '$1 $2 $3'), email: 'auto' + tag + '@timohouse.vn', startDate: F.today(), probationEnd: F.addDays(F.today(), 45), area: 'Khu Q.7', salaryBase: 9000000, titleAllowance: 500000 }); log.push('NV ' + emp.code);
    const b0 = St.where('buildings', b => !b.stub)[0]; X.assignBuilding({ employeeId: emp.id, buildingId: b0.id, role: 'ops', primary: true });
    const period = St.state.meta.period; try { X.fillTimesheet(period); } catch (e) { } try { X.confirmTimesheet(period); } catch (e) { log.push('Bảng công: ' + e.message); }
    let pay = Q.payroll(period); if (!pay || pay.status === 'draft') { pay = X.buildPayroll(period); X.submitPayroll(period); } TH.auth.switchRole('accountant'); if (Q.payroll(period).status === 'review') X.approvePayroll(period); if (Q.payroll(period).status === 'approved') { if (Q.periodLocked && Q.periodLocked(F.period(F.today()))) { TH.auth.switchRole('admin'); X.unlockPeriod(F.period(F.today()), 'Chạy kịch bản demo'); TH.auth.switchRole('accountant'); } X.payPayroll(period, { ref: 'UNC-AUTO' + tag }); } log.push('Lương ' + Q.payroll(period).code + ' ' + Q.label('payroll', Q.payroll(period).status));
    // F18
    TH.auth.switchRole('accountant'); const proj = St.all('projects').map(p => ({ p, used: F.sum(St.where('capitalCommitments', c => c.projectId === p.id), c => c.ratio) })).sort((a, b) => a.used - b.used)[0]; let ratio = Math.round((100 - proj.used) * 100) / 100; if (ratio <= 0) { const big = St.where('capitalCommitments', c => c.projectId === proj.p.id).sort((a, b) => b.ratio - a.ratio)[0]; big.ratio = Math.round((big.ratio - 2) * 100) / 100; ratio = 2; } ratio = Math.min(ratio, 5);
    const sh = X.saveShareholder({ name: 'Cổ đông Auto ' + tag, email: 'auto' + tag + '@gmail.com', phone: '0914 000 ' + tag.slice(0, 3), commitments: [{ projectId: proj.p.id, ratio, effectiveDate: F.today() }] }); log.push('Cổ đông ' + sh.code + ' ' + ratio + '% ' + proj.p.name);
    const rounds = X.createContributionRound({ projectId: proj.p.id, round: 'Đợt auto ' + tag, dueDate: F.addDays(F.today(), 10), total: 200000000 }); const mine = rounds.find(c => c.shareholderId === sh.id) || rounds[0]; X.recordContribution(mine.id, { amount: mine.amount, date: F.today(), ref: 'UNC-AUTO' + tag }); log.push('Đợt góp vốn ' + rounds.length + ' nghĩa vụ, ghi nhận 1');
    const dist = X.createDistribution({ label: 'Auto ' + tag, profit: 600000000, date: F.addDays(F.today(), 30) }); TH.auth.switchRole('admin'); X.approveDistribution(dist.id); TH.auth.switchRole('accountant'); X.payDistribution(dist.id, { ref: 'UNC-AUTO' + tag }); log.push('Phân phối ' + dist.label + ' đã chi');
    St.state.guide.visitedRole = Object.assign(St.state.guide.visitedRole || {}, { 'codong:/investment/shareholders': 1 });
    // F19
    if (TH.phase.on(2) && TH.imp && TH.imp.statementSample) { const rows = TH.imp.rowsToObjects(TH.imp.parse(TH.imp.statementSample().map(r => r.map(String)), TH.imp.STATEMENT.fields, TH.imp.STATEMENT.aliases)); rows.forEach((r, i) => { if (r.data.refCode) r.data.refCode += '-B' + tag; }); const r = X.importBankStatement({ rows, accountId: (St.all('bankAccounts')[0] || {}).id, fileName: 'mau-sao-ke-auto-' + tag + '.csv' }); const rec = X.reconcileBank(); log.push('Sao kê ' + r.added + ' GD, khớp ' + rec.matched); const un = St.one('bankTransactions', t => t.dir === 'in' && ['unmatched', 'check'].includes(t.matchStatus)); const inv2 = St.where('invoices', i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0)[0]; if (un && inv2) { X.matchBankTx(un.id, inv2.id); log.push('Khớp tay ' + un.ref); } } else log.push('Ngân hàng: bật Phase 2 để đối soát – bỏ qua F19');
    await wait(800);
    TH.auth.switchRole(['sale', 'kythuat', 'hr', 'codong'].includes(prevRole) ? 'admin' : (prevRole || 'admin')); TH.layout.refreshTop(); St.state.guide.visited = Object.assign(St.state.guide.visited || {}, { '/assets/inventory': 1, '/hr': 1, '/hr/timesheet': 1, '/hr/payroll': 1, '/investment/shareholders': 1, '/finance/bank': 1 }); G.evaluate('sync');
    return log.join(' · ');
  };
})(window.TH);
