/* Panel Hướng dẫn thao tác – thụ động, không tạo record (spec v1.5, cắt scope Phase 1) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const G = { KEY: 'timehouse-guide-p1-v1', openState: false };
  const ROLE = { admin: 'Quản trị viên', accountant: 'Kế toán', ops: 'Vận hành', sale: 'Sale', kythuat: 'Kỹ thuật', any: 'Bất kỳ' };
  /* ---- ngữ cảnh: record do người demo tạo ---- */
  const ctx = () => {
    const pin = (St.state.guide && St.state.guide.pin) || {};
    const uT = St.where('tenants', t => t.source === 'user'); const uC = St.where('contracts', c => c.source === 'user'); const mainC = (pin.contractId && St.get('contracts', pin.contractId)) || uC.filter(c => c.status !== 'cancelled').sort((a, b) => F.cmp(b.createdAt, a.createdAt))[0] || null;
    const room = mainC ? Q.room(mainC.roomId) : null; const uInv = mainC ? St.where('invoices', i => i.contractId === mainC.id && i.source === 'user' && i.docStatus !== 'cancelled') : []; const inv = (pin.invoiceId && uInv.find(i => i.id === pin.invoiceId)) || uInv.sort((a, b) => F.cmp(b.createdAt, a.createdAt))[0] || null;
    const pay = inv ? St.where('payments', p => p.source === 'user' && p.status === 'recorded' && Q.payAllocs(p.id).some(a => a.invoiceId === inv.id)).sort((a, b) => F.cmp(b.createdAt, a.createdAt))[0] : null;
    const msgs = mainC ? St.where('zaloMessages', m => m.source === 'user' && (m.tenantId === mainC.tenantId)) : []; const batches = [...new Set(msgs.map(m => m.batchId))].map(id => St.get('zaloBatches', id)).filter(Boolean).sort((a, b) => F.cmp(a.createdAt, b.createdAt));
    const b1 = batches.find(b => ['issued', 'reminder', 'manual', 'due_soon'].includes(b.sourceKey) || b.eventKey === 'reminder') || batches[0] || null; const b2 = pay ? (batches.find(b => b !== b1 && b.createdAt >= pay.createdAt && (b.eventKey === 'debt' || ['overdue', 'debt', 'due_soon'].includes(b.sourceKey))) || null) : null;
    const rf = mainC ? ((pin.refundId && St.get('refunds', pin.refundId)) || St.one('refunds', r => r.contractId === mainC.id)) : null; const cleaned = room ? St.one('auditLog', l => l.action === 'confirmCleaned' && l.entityId === room.id) : null;
    return { uT, uC, mainC, room, uInv, inv, pay, msgs, batches, b1, b2, rf, cleaned, visited: St.state.guide.visited || {} };
  };
  const v = (c, path) => Object.keys(c.visited).some(k => k === path || k.startsWith(path + '?') || (path.endsWith('/') && k.startsWith(path)));
  /* ---- 10 luồng / 36 mốc ---- */
  G.FLOWS = [
    { key: 'S0', title: 'Khởi động', golive: '', ms: [
      { id: 'S0.1', title: 'Đăng nhập hệ thống', route: '#/login', role: 'admin', how: 'Đăng nhập bằng tài khoản admin (mật khẩu bất kỳ). Có thể bấm chip "admin – Quản trị viên".', expect: 'Vào Tổng quan, topbar hiện tên Nguyễn Văn Minh – Quản trị viên.', check: () => !!St.state.session, hl: 'login-card' },
      { id: 'S0.2', title: 'Xem Tổng quan', route: '#/dashboard', role: 'any', how: 'Quan sát 4 KPI phòng, Tổng quan tài chính, 2 biểu đồ và bảng Top khoản quá hạn.', expect: 'Số phòng Sẵn sàng, Giữ chỗ và Tiến độ thu hiển thị; nút "Nhắc thu" trên từng dòng quá hạn.', check: c => v(c, '/dashboard'), hl: 'dash-kpi' },
      { id: 'S0.3', title: 'Kiểm tra danh mục dịch vụ & bảng giá', route: '#/settings/catalog', role: 'admin', how: 'Mở Cấu hình → Danh mục dùng chung. Chọn 1 dịch vụ để xem giá, phạm vi và lịch sử áp dụng.', expect: '7 dịch vụ (Điện 3.500/kWh, Nước 20.000/m³, Internet, Thang máy, Phí quản lý, Sạc xe điện, Gửi xe) đang hoạt động.', check: c => v(c, '/settings/catalog') && St.where('services', s => s.status === 'active').length > 0, hl: 'catalog-table' },
      { id: 'S0.4', title: 'Xem phòng sẵn sàng cho thuê', route: '#/rooms?status=ready', role: 'ops', how: 'Mở Vận hành → Phòng, lọc tab "Sẵn sàng". Ghi nhớ một mã phòng để tạo hợp đồng.', expect: 'Danh sách phòng Sẵn sàng có nút "Giữ chỗ" và "Tạo hợp đồng" trên mỗi dòng.', check: c => v(c, '/rooms') && St.where('rooms', r => r.status === 'ready').length > 0, hl: 'rooms-table' },
    ] },
    { key: 'F01', title: 'Tạo khách thuê', golive: '1', ms: [
      { id: 'F01.1', title: 'Mở form Thêm khách thuê', route: '#/tenants', role: 'ops', how: 'Vào Vận hành → Khách thuê, bấm "+ Thêm khách thuê". Drawer form mở bên phải.', expect: 'Form có Họ tên*, SĐT*, Zalo, Email, CCCD, Nghề nghiệp, Phân khúc (nhập tay – BR-18).', check: c => v(c, '/tenants'), hl: 'tenant-add' },
      { id: 'F01.2', title: 'Lưu khách thuê mới', route: '#/tenants', role: 'ops', how: 'Điền Họ tên, SĐT (có thể dùng "Điền dữ liệu mẫu") rồi bấm "Lưu khách thuê".', expect: 'Toast "Đã lưu khách…", khách xuất hiện đầu danh sách với chip "mới", trạng thái Khách mới.', check: c => c.uT.length > 0, hl: 'tenant-add', sample: { kind: 'form', form: 'tenant', values: { name: 'Nguyễn Demo Khách', phone: '0912 000 111', zalo: '0912 000 111', email: 'demo.khach@gmail.com', idNumber: '012345678999', dob: '1995-06-15', job: 'Kỹ sư phần mềm', segment: 'Chuyên gia', note: '1 xe máy – biển 59X1-123.45' }, open: 'Bấm "+ Thêm khách thuê" trước khi điền' } },
    ] },
    { key: 'F02', title: 'Chọn phòng & tạo hợp đồng', golive: '2, 3, 4', ms: [
      { id: 'F02.1', title: 'Chọn phòng sẵn sàng → Tạo hợp đồng', route: '#/rooms?status=ready', role: 'ops', how: 'Tại danh sách phòng Sẵn sàng, bấm "+ Tạo hợp đồng" trên một phòng (hoặc "Giữ chỗ" trước rồi tạo HĐ).', expect: 'Mở màn Tạo hợp đồng với phòng đã chọn sẵn, giá tham chiếu và dịch vụ mặc định được nạp.', check: c => v(c, '/contracts/new'), hl: 'rooms-table' },
      { id: 'F02.2', title: 'Chọn khách, thời hạn, chu kỳ thanh toán', route: '#/contracts/new', role: 'ops', how: 'Chọn khách thuê vừa tạo; đặt ngày bắt đầu/kết thúc (12 tháng); ngày thanh toán hàng tháng.', expect: 'Panel Tóm tắt cập nhật khách, phòng, thời hạn; checklist tick xanh.', check: c => c.uC.length > 0 || (c.mainC && c.mainC.tenantId), hl: 'contract-save', sample: { kind: 'form', form: 'contract', values: { start: '2024-11-01', end: '2025-10-31', payDay: '5', listPrice: 6500000, price: 6000000, deposit: 12000000, note: 'Không nuôi thú cưng. Bàn giao đủ nội thất theo biên bản.' }, open: 'Mở Tạo hợp đồng và chọn khách + phòng trước; mẫu điền thời hạn, giá, cọc' } },
      { id: 'F02.3', title: 'Thiết lập giá thuê, cọc, dịch vụ', route: '#/contracts/new', role: 'ops', how: 'Nhập Giá niêm yết, Giá thuê thực tế (BR-06), Tiền cọc; kiểm tra bảng Dịch vụ đi kèm (thêm Gửi xe nếu có xe – BR-05). Bấm "Lưu hợp đồng →".', expect: 'Chuyển sang bước Review & lưu, hợp đồng ở trạng thái Dự thảo.', check: c => c.mainC && c.mainC.price > 0 && (Q.contractServices(c.mainC.id).length > 0 || c.mainC.status !== 'draft'), hl: 'price' },
      { id: 'F02.4', title: 'Xác nhận & kích hoạt hợp đồng', route: c => c.mainC && c.mainC.status === 'draft' ? '#/contracts/new?id=' + c.mainC.id + '&step=5' : '#/contracts?status=draft', role: 'ops', how: 'Tại bước Review bấm "Xác nhận & kích hoạt hợp đồng" → xác nhận.', expect: 'HĐ → Hiệu lực; phòng → Đang thuê (kiểm tra ở Phòng); cọc ghi nhận đang giữ.', check: c => c.mainC && c.mainC.status !== 'draft' && c.room && (c.room.status === 'occupied' || c.mainC.status === 'ended'), hl: 'contract-activate' },
    ] },
    { key: 'F03', title: 'Điện nước & hóa đơn', golive: '5, 6', ms: [
      { id: 'F03.1', title: 'Mở Tạo hóa đơn theo kỳ', route: '#/invoices', role: 'accountant', how: 'Chuyển vai trò Kế toán. Vào Tài chính → Hóa đơn → "+ Tạo hóa đơn theo kỳ". Chọn kỳ Tháng 10/2024, tòa của phòng vừa ký.', expect: 'Wizard 4 bước; bảng phòng liệt kê HĐ hiệu lực với cảnh báo "Thiếu chỉ số"/"Đã có hóa đơn".', check: c => v(c, '/invoices/batch'), hl: 'invoice-batch' },
      { id: 'F03.2', title: 'Nhập chỉ số điện nước cho phòng mới', route: c => '#/invoices/batch?step=2' + (c.mainC ? '&buildingId=' + c.mainC.buildingId : ''), role: 'accountant', how: 'Nhập Chỉ số điện mới / nước mới cho phòng của hợp đồng vừa tạo (chỉ số mới ≥ cũ). Bấm "Lưu tạm".', expect: 'SL điện/nước tự tính; toast "Đã lưu tạm N chỉ số"; phòng không còn cảnh báo Thiếu chỉ số.', check: c => c.room && St.where('meterReadings', m => m.roomId === c.room.id && m.source === 'user').length >= 2, hl: 'meter-save', sample: { kind: 'form', form: 'meter', values: { electricCurr: '+150', waterCurr: '+12' }, open: 'Ở bước 2 của wizard; mẫu điền chỉ số mới = cũ + 150 kWh và + 12 m³ cho các dòng trống' } },
      { id: 'F03.3', title: 'Preflight & tạo hóa đơn nháp', route: c => '#/invoices/batch?step=3' + (c.mainC ? '&buildingId=' + c.mainC.buildingId : ''), role: 'accountant', how: 'Bấm "Tiếp tục preflight →", xem dòng phí dự kiến, rồi "Tạo N hóa đơn nháp".', expect: 'Kết quả tạo hiển thị mã hóa đơn nháp của phòng mới; dòng thiếu chỉ số bị bỏ qua (không lấy 0).', check: c => c.uInv.length > 0, hl: 'invoice-create' },
      { id: 'F03.4', title: 'Phát hành hóa đơn', route: c => c.inv ? '#/invoices/' + c.inv.id : '#/invoices?doc=draft', role: 'accountant', how: 'Mở hóa đơn nháp vừa tạo → "Phát hành" (hoặc "Phát hành bản nháp hợp lệ" ở danh sách).', expect: 'Chứng từ → Đã phát hành, Trạng thái thu → Chưa thu; hóa đơn xuất hiện trong Thu tiền & công nợ.', check: c => c.inv && c.inv.docStatus !== 'draft', hl: 'invoice-issue' },
    ] },
    { key: 'F04', title: 'Gửi hóa đơn qua Zalo', golive: '7', ms: [
      { id: 'F04.1', title: 'Tạo đợt gửi từ hóa đơn vừa phát hành', route: '#/zalo/batches/new?src=issued&step=3', role: 'admin', how: 'Thông báo → Tạo đợt gửi → nguồn "Hóa đơn vừa phát hành" → mẫu nhắc tiền → Preview người nhận (hoặc dùng nút "Gửi nhắc tiền" ngay trên hóa đơn).', expect: 'Khách mới nằm trong danh sách Đủ điều kiện với số tiền hóa đơn; khách đã trả đủ bị Bỏ qua (FR-ZAL-02).', check: c => v(c, '/zalo/batches/new') || c.batches.length > 0, hl: 'zalo-recipients' },
      { id: 'F04.2', title: 'Xác nhận gửi', route: '#/zalo/batches/new?src=issued&step=3', role: 'admin', how: 'Bấm "Xác nhận gửi" → đồng ý. Hệ thống chuyển tới chi tiết đợt gửi.', expect: 'Đợt gửi mới (ZL-202410-0xx) trạng thái Đang gửi; tiến độ chạy theo thời gian thực.', check: c => !!c.b1, hl: 'zalo-send' },
      { id: 'F04.3', title: 'Theo dõi kết quả gửi', route: '#/zalo/history', role: 'admin', how: 'Ở chi tiết đợt gửi xem 7 ô trạng thái (Chờ xử lý → Đã giao / Thất bại / Chưa rõ). Mở tab "Nhắc tiền" trên hóa đơn để thấy lịch sử.', expect: 'Đợt gửi kết thúc với trạng thái Thành công/Một phần; tin của khách mới hiện "Đã giao".', check: c => c.b1 && ['done', 'partial', 'failed'].includes(c.b1.status) },
    ] },
    { key: 'F05', title: 'Công nợ & thu tiền một phần', golive: '8, 9, 10', ms: [
      { id: 'F05.1', title: 'Xem công nợ', route: '#/receivables', role: 'accountant', how: 'Tài chính → Thu tiền & công nợ. Tìm hóa đơn của khách mới (gõ mã phòng vào ô tìm kiếm).', expect: 'Dòng công nợ hiện Tổng, Đã thu 0, Còn lại = tổng, trạng thái nhắc "Đã nhắc" sau F04.', check: c => v(c, '/receivables'), hl: 'receivables-table' },
      { id: 'F05.2', title: 'Ghi nhận thu tiền một phần', route: '#/receivables', role: 'accountant', how: 'Bấm "Thu tiền thủ công" ở đầu trang → chọn khách mới → nhập Số tiền NHỎ HƠN còn lại (vd 3.000.000), phương thức, mã tham chiếu → "Tự động phân bổ" → "Xác nhận ghi nhận". (Nút "Xác nhận thu tiền" trên dòng dùng khi thu ĐỦ một lần kèm minh chứng.)', expect: 'Toast "Đã ghi nhận khoản thu PAY-…"; chuyển tới Chi tiết khoản thu; hóa đơn → Thu một phần.', check: c => !!c.pay, hl: 'receivable-pay', sample: { kind: 'form', form: 'payment', values: { amount: 3000000, method: 'Chuyển khoản', ref: 'CK' + '289104', note: 'Khách thanh toán một phần tiền nhà tháng 10' }, open: 'Mở drawer Thu tiền thủ công (nút ở đầu trang Thu tiền & công nợ), chọn khách mới trước khi điền' } },
      { id: 'F05.3', title: 'Xem chi tiết khoản thu', route: c => c.pay ? '#/payments/' + c.pay.id : '#/receivables', role: 'accountant', how: 'Tại Chi tiết khoản thu: kiểm tra Phân bổ công nợ, Thông tin giao dịch, Lịch sử xử lý.', expect: 'Đã phân bổ = số tiền thu; "Còn lại sau phân bổ" = tổng − đã thu; trạng thái hóa đơn Thu một phần.', check: c => c.pay && v(c, '/payments/' + c.pay.id) },
      { id: 'F05.4', title: 'Theo dõi số còn nợ', route: '#/receivables', role: 'accountant', how: 'Quay lại Thu tiền & công nợ hoặc mở hóa đơn: kiểm tra Còn lại.', expect: 'Hóa đơn của khách mới: Đã thu = số vừa thu, Còn lại > 0, chip "Thu một phần" (VD 5.700.000 − 3.000.000 = 2.700.000).', check: c => c.inv && Q.invPayStatus(c.inv) === 'partial' || (c.inv && Q.invPayStatus(c.inv) === 'paid' && c.pay) },
    ] },
    { key: 'F06', title: 'Nhắc công nợ qua Zalo', golive: '11', ms: [
      { id: 'F06.1', title: 'Tạo đợt nhắc công nợ', route: '#/receivables', role: 'admin', how: 'Tại Thu tiền & công nợ tick dòng của khách mới → "Gửi nhắc Zalo" → chọn mẫu nhắc công nợ → Gửi. (Khách vừa nhận tin trong 3 ngày sẽ bị bỏ qua theo rule – tick "Vẫn gửi" để ghi đè khi demo.)', expect: 'Preview hiện số còn nợ MỚI (sau khi thu một phần) – re-check công nợ trước khi gửi.', check: c => !!c.b2, hl: 'receivables-table' },
      { id: 'F06.2', title: 'Xác nhận gửi & theo dõi', route: '#/zalo/history', role: 'admin', how: 'Xác nhận gửi, theo dõi tiến độ tới khi kết thúc.', expect: 'Đợt gửi Thành công/Một phần; tin của khách mới có "Còn nợ hiện tại" đúng số dư.', check: c => c.b2 && ['done', 'partial', 'failed'].includes(c.b2.status) },
      { id: 'F06.3', title: 'Thử lại tin lỗi (nếu có)', route: '#/zalo/history?status=partial', role: 'admin', how: 'Mở đợt gửi có tin Thất bại → "Thử lại các tin đủ điều kiện". Không gửi lại người đã nhận (FR-ZAL-04).', expect: 'Chỉ tin Thất bại/Chưa rõ được xếp hàng lại; tin Đã giao giữ nguyên.', check: c => c.b2 && ['done', 'partial', 'failed'].includes(c.b2.status) && (Q.batchCounts(c.b2.id).failed === 0 || St.where('zaloMessages', m => m.batchId === c.b2.id && m.retryOfId).length > 0), hl: 'zalo-retry' },
    ] },
    { key: 'F07', title: 'Kết thúc hợp đồng', golive: '12, 14', ms: [
      { id: 'F07.1', title: 'Mở hợp đồng của khách mới', route: c => c.mainC ? '#/contracts/' + c.mainC.id : '#/contracts?status=active', role: 'ops', how: 'Chuyển vai trò Vận hành. Vận hành → Hợp đồng → mở hợp đồng vừa tạo.', expect: 'Chi tiết HĐ với nút "Kết thúc hợp đồng", KPI công nợ còn lại.', check: c => c.mainC && v(c, '/contracts/' + c.mainC.id), hl: 'contracts-table' },
      { id: 'F07.2', title: 'Ghi nhận kết thúc → phòng Chờ dọn', route: c => c.mainC ? '#/contracts/' + c.mainC.id : '#/contracts?status=active', role: 'ops', how: 'Bấm "Kết thúc hợp đồng", giữ tick "Chuyển phòng sang Chờ dọn" và "Tạo hồ sơ hoàn cọc" → Xác nhận.', expect: 'HĐ → Đã kết thúc; phòng → Chờ dọn (không Sẵn sàng – BR-02); hồ sơ hoàn cọc Nháp được tạo với công nợ còn lại.', check: c => c.mainC && c.mainC.status === 'ended' && c.room && ['cleaning', 'ready'].includes(c.room.status) && !!c.rf, hl: 'contract-terminate' },
    ] },
    { key: 'F08', title: 'Hoàn cọc', golive: '13', ms: [
      { id: 'F08.1', title: 'Lập phương án hoàn cọc', route: c => c.rf ? '#/refunds/new?id=' + c.rf.id + '&step=3' : '#/refunds', role: 'ops', how: 'Tài chính → Hoàn cọc → mở hồ sơ Nháp của khách mới → "Sửa phương án". Kiểm tra hiện trạng, thêm dòng khấu trừ kèm bằng chứng ("Thêm" bằng chứng). Khấu hao 200.000đ/phòng (BR-12).', expect: 'Số tiền hoàn = Cọc − khấu trừ (không tự bù nợ – OI-07). Bằng chữ hiển thị đúng.', check: c => c.rf && Q.refundDeductions(c.rf.id).length >= 1 && (St.one('auditLog', l => l.action === 'save' && l.entityType === 'refund' && l.entityId === c.rf.id) || c.rf.status !== 'draft'), hl: 'refund-review' },
      { id: 'F08.2', title: 'Gửi duyệt', route: c => c.rf ? '#/refunds/new?id=' + c.rf.id + '&step=4' : '#/refunds', role: 'ops', how: 'Bước Review → "Gửi duyệt hoàn cọc".', expect: 'Hồ sơ → Chờ duyệt; Vận hành KHÔNG thấy nút Duyệt (chỉ Admin/Kế toán – FR-FIN-07).', check: c => c.rf && c.rf.status !== 'draft', hl: 'refund-submit' },
      { id: 'F08.3', title: 'Kế toán duyệt hồ sơ', route: c => c.rf ? '#/refunds/' + c.rf.id : '#/refunds?status=pending', role: 'accountant', how: 'Chuyển vai trò Kế toán → mở hồ sơ → "Duyệt hoàn cọc" (hoặc thử "Từ chối" để xem vòng quay lại chỉnh sửa).', expect: 'Hồ sơ → Đã duyệt; ghi chú "Duyệt ≠ đã chuyển tiền".', check: c => c.rf && ['approved', 'refunded'].includes(c.rf.status), hl: 'refund-approve' },
      { id: 'F08.4', title: 'Ghi nhận đã hoàn (kèm bằng chứng)', route: c => c.rf ? '#/refunds/' + c.rf.id : '#/refunds?status=approved', role: 'accountant', how: 'Bấm "Ghi nhận đã hoàn" → ngày, phương thức, đính kèm bằng chứng (bắt buộc) → Xác nhận.', expect: 'Hồ sơ → Đã hoàn; phòng VẪN Chờ dọn (không tự Sẵn sàng); có thể gửi Zalo "Đã hoàn cọc".', check: c => c.rf && c.rf.status === 'refunded', hl: 'refund-paid', sample: { kind: 'file', name: 'uy_nhiem_chi_hoan_coc.pdf', purpose: 'Bằng chứng hoàn tiền cho hồ sơ hoàn cọc', rows: 1, cols: 'PDF 1 trang', relations: 'Gắn với mã hồ sơ RC…', errors: 'Không', content: 'UY NHIEM CHI - HOAN COC\nNguoi nhan: khach thue demo\nSo tien: theo ho so\nNgay: ' + F.today() } },
    ] },
    { key: 'F09', title: 'Dọn phòng & mở cho thuê lại', golive: '15, 16', ms: [
      { id: 'F09.1', title: 'Xác nhận dọn xong', route: '#/rooms?status=cleaning', role: 'ops', how: 'Chuyển vai trò Vận hành. Phòng → tab "Chờ dọn" → bấm "Xác nhận dọn xong" trên phòng của khách mới.', expect: 'Toast "Phòng … đã Sẵn sàng"; phòng rời khỏi tab Chờ dọn.', check: c => c.room && c.mainC && c.mainC.status === 'ended' && !!c.cleaned, hl: 'confirm-clean' },
      { id: 'F09.2', title: 'Phòng trở lại Sẵn sàng', route: '#/rooms?status=ready', role: 'ops', how: 'Lọc tab "Sẵn sàng" và tìm lại mã phòng.', expect: 'Phòng hiện Sẵn sàng với nút Giữ chỗ / Tạo hợp đồng – vòng đời Phase 1 hoàn tất.', check: c => c.room && c.room.status === 'ready' && !!c.cleaned, hl: 'rooms-table' },
    ] },
    { key: 'F10', title: 'Bổ trợ (tùy chọn)', golive: '', ms: [
      { id: 'F10.1', title: 'Thêm chi phí', route: '#/expenses', role: 'accountant', how: 'Tài chính → Chi phí → "+ Thêm chi phí". Thử "Chi phí chung" với phân bổ 40/30/20/10.', expect: 'Chi phí xuất hiện đầu danh sách; tổng phân bổ phải = 100% (FR-FIN-05).', check: () => St.where('expenses', e => e.source === 'user').length > 0, hl: 'expense-add', sample: { kind: 'form', form: 'expense', values: { date: F.today(), group: 'Sửa chữa', desc: 'Sửa khóa cửa phòng demo', amount: 350000, note: 'Thợ khóa Minh Tâm' }, open: 'Bấm "+ Thêm chi phí" trước khi điền' } },
      { id: 'F10.2', title: 'Import khách bằng file mẫu', route: '#/settings/import?type=tenant', role: 'admin', how: 'Cấu hình → Import dữ liệu → Khách thuê → "Dùng file mẫu" (10 dòng, có lỗi cố ý) → mapping → kiểm tra → xác nhận import.', expect: 'KPI Hợp lệ/Cần kiểm tra/Lỗi; dòng lỗi bị bỏ qua; khách hợp lệ được tạo.', check: () => St.where('importJobs', j => j.source === 'user').length > 0, hl: 'import-sample', sample: { kind: 'file', name: 'mau-import-tenant.csv', purpose: 'Import khách thuê hàng loạt', rows: 10, cols: 'Họ tên, SĐT, CCCD, Phòng, Ngày bắt đầu thuê, Zalo', relations: 'Mã phòng tham chiếu danh mục phòng', errors: 'Dòng 3 trùng SĐT khách Lê Quang Huy (0909 876 543); dòng 4 CCCD sai định dạng; dòng 5 thiếu SĐT & ngày tương lai; dòng 6 phòng không tồn tại' } },
      { id: 'F10.3', title: 'Tạo tài khoản Vận hành', route: '#/settings/users', role: 'admin', how: 'Cấu hình → Tài khoản & phân quyền → "Tạo tài khoản", vai trò Quản lý/Vận hành, phân công tòa.', expect: 'Tài khoản mới hiện với chip vai trò Vận hành và phạm vi tòa đã chọn.', check: () => St.where('users', u => u.source === 'user').length > 0, hl: 'user-add', sample: { kind: 'form', form: 'user', values: { name: 'Lê Demo Vận Hành', email: 'demo.vanhanh@timohouse.vn', phone: '0913 222 333', role: 'ops', effectiveDate: F.today() }, open: 'Bấm "Tạo tài khoản" trước khi điền' } },
      { id: 'F10.4', title: 'Xuất báo cáo công nợ', route: '#/reports?tab=debt', role: 'accountant', how: 'Báo cáo → Báo cáo công nợ → "Xuất CSV".', expect: 'File CSV tải về với phải thu/đã thu/còn nợ theo tòa.', check: c => v(c, '/reports') },
    ] },
  ];
  // Phase 2: luồng có phase:2 chỉ hiện khi TH.phase.on(2) (tắt P2 → panel y hệt bản P1: 10 luồng / 36 mốc)
  G.flows = () => G.FLOWS.filter(f => !f.phase || (TH.phase && TH.phase.on(f.phase)));
  G.all = () => G.flows().flatMap(f => f.ms.map(m => Object.assign({ flow: f.key, phase: f.phase }, m)));
  /* ---- đánh giá ---- */
  G.evaluate = (what) => {
    const g = St.state.guide = St.state.guide || { done: {}, ts: {}, visited: {} }; g.done = g.done || {}; g.ts = g.ts || {}; g.visited = g.visited || {};
    if (what === 'route' && TH.router.current) { const p = TH.router.current.path; const qs = Object.keys(TH.router.current.query || {}).length ? '?' + new URLSearchParams(TH.router.current.query).toString() : ''; g.visited[p + qs] = F.nowISO(); g.visited[p] = F.nowISO(); }
    const c = ctx(); let changed = false;
    // ghim record chính của chuỗi demo để tiến độ không tụt khi tạo thêm HĐ/hóa đơn khác
    g.pin = g.pin || {}; if (c.mainC && c.mainC.status !== 'draft' && !g.pin.contractId) g.pin.contractId = c.mainC.id; if (c.inv && c.inv.docStatus !== 'draft' && !g.pin.invoiceId) g.pin.invoiceId = c.inv.id; if (c.rf && !g.pin.refundId) g.pin.refundId = c.rf.id;
    G.all().forEach(m => { let ok = false; try { ok = !!m.check(c); } catch (e) { ok = false; } if (ok && !g.done[m.id]) { g.done[m.id] = true; g.ts[m.id] = F.nowISO(); changed = true; } else if (!ok && g.done[m.id] && !m.id.startsWith('S0') && !/\.1$/.test(m.id)) { delete g.done[m.id]; changed = true; } });
    St.save(); try { localStorage.setItem(G.KEY, JSON.stringify({ done: g.done, ts: g.ts, current: g.current })); } catch (e) { }
    G.render(); return changed;
  };
  G.current = () => { const g = St.state.guide; for (const f of G.flows()) { const m = f.ms.find(x => !g.done[x.id]); if (m) return { flow: f, ms: m }; } return null; };
  G.status = (m) => { const g = St.state.guide; if (g.done[m.id]) return 'done'; const cur = G.current(); if (cur && cur.ms.id === m.id) return 'active'; const all = G.all(); const idx = all.findIndex(x => x.id === m.id); return all.slice(0, idx).every(x => g.done[x.id]) ? 'active' : 'pending'; };
  /* ---- panel ---- */
  G.init = () => { const root = document.getElementById('guide-root'); root.innerHTML = `<aside class="guide" aria-label="Hướng dẫn thao tác"><div class="guide-h"><h3>${I('book-open')} Hướng dẫn thao tác</h3><div class="row gap4">${U.iconBtn('list', 'g-all', 'Xem toàn bộ luồng')}${U.iconBtn('x', 'g-close', 'Đóng')}</div></div><div class="guide-b" id="guide-body"></div><div class="guide-f"><span id="guide-foot">16 điều kiện Go-live Phase 1 · 10 luồng</span><a class="link" data-act="g-reset">Reset tiến độ</a></div></aside>`;
    U.bind(root, {
      'g-close': () => G.toggle(false), 'g-all': () => { G.showAll = !G.showAll; G.render(); }, 'g-reset': async () => { if (await U.confirm({ title: 'Reset tiến độ hướng dẫn?', text: 'Chỉ xóa trạng thái mốc; dữ liệu nghiệp vụ giữ nguyên. Mốc sẽ được nhận diện lại từ dữ liệu hiện có.', ok: 'Reset' })) G.resetProgress(); },
      'g-go': (el) => { const m = G.find(el.dataset.id); TH.go(G.routeOf(m)); setTimeout(() => m.hl && U.highlight(`[data-guide="${m.hl}"]`), 350); },
      'g-role': (el) => { const m = G.find(el.dataset.id); if (m.role === 'any' || TH.auth.role() === m.role) return U.toast('info', 'Vai trò hiện tại đã phù hợp'); TH.auth.switchRole(m.role); TH.layout.refreshTop(); TH.router.refresh(); U.toast('ok', 'Đã chuyển vai trò', ROLE[m.role]); },
      'g-sample': (el) => G.openSample(el.dataset.id), 'g-fill': (el) => G.useSample(el.dataset.id, false), 'g-refill': (el) => G.useSample(el.dataset.id, true), 'g-dl': (el) => G.downloadSample(el.dataset.id), 'g-usefile': (el) => G.useFile(el.dataset.id),
      'g-pick': (el) => { St.state.guide.current = el.dataset.k; G.showAll = false; G.render(); },
    });
    G.showAll = false; G.render();
    try { if (localStorage.getItem(G.KEY + ':open') === '1') G.toggle(true); } catch (e) { }
  };
  G.find = (id) => G.all().find(m => m.id === id);
  G.routeOf = (m, c) => typeof m.route === 'function' ? m.route(c || ctx()) : m.route;
  G.toggle = (on) => { const open = on == null ? !document.body.classList.contains('guide-open') : on; document.body.classList.toggle('guide-open', open); try { localStorage.setItem(G.KEY + ':open', open ? '1' : '0'); } catch (e) { } if (open) G.render(); };
  G.open = (flowKey) => { if (flowKey) St.state.guide.current = flowKey; G.toggle(true); };
  G.render = () => {
    const body = document.getElementById('guide-body'); if (!body) return; const g = St.state.guide; const all = G.all(); const done = all.filter(m => g.done[m.id]).length;
    const cur = G.current(); const focusFlow = (g.current && G.flows().find(f => f.key === g.current)) || (cur ? cur.flow : G.flows()[G.flows().length - 1]);
    const flowMs = focusFlow.ms; const curMs = flowMs.find(m => !g.done[m.id]) || null; const next = curMs ? all[all.findIndex(m => m.id === curMs.id) + 1] : null;
    const stChip = (s) => s === 'done' ? U.chip('Hoàn thành', 'green') : s === 'active' ? U.chip('Đang thực hiện', 'blue') : U.chip('Chưa sẵn sàng', 'gray');
    const flowDone = (f) => f.ms.filter(m => g.done[m.id]).length;
    let html = `<div class="prog"><span class="bold" style="color:var(--text)">${done}/${all.length} mốc</span><div class="progress"><i style="width:${Math.round(done / all.length * 100)}%"></i></div><span>${Math.round(done / all.length * 100)}%</span></div>`;
    if (G.showAll) { html += `<div class="fl-list">${G.flows().map(f => { const d = flowDone(f); const s = d === f.ms.length ? 'done' : (cur && cur.flow.key === f.key) ? 'active' : d > 0 ? 'active' : 'pending'; return `<div class="fl-row ${focusFlow.key === f.key ? 'cur' : ''}" data-act="g-pick" data-k="${f.key}"><b>${f.key}</b><span>${esc(f.title)}${f.phase ? ' ' + TH.phase.tag(f.phase) : ''}</span>${f.golive ? `<span class="xs muted">Go-live #${f.golive}</span>` : ''}<span class="st">${d}/${f.ms.length} ${stChip(s)}</span></div>`; }).join('')}</div><div class="xs muted">Tiền đề: mỗi luồng cần luồng trước hoàn thành (S0 → F01 → F02 → … → F09). F10 độc lập.</div>`; }
    else {
      html += `<div class="fl"><div class="fh"><span>${focusFlow.key} · ${esc(focusFlow.title)}${focusFlow.phase ? ' ' + TH.phase.tag(focusFlow.phase) : ''}</span><span class="xs muted">${flowDone(focusFlow)}/${flowMs.length}${focusFlow.golive ? ' · Go-live #' + focusFlow.golive : ''}</span></div><div class="sub-ms">${flowMs.map(m => `<div class="it ${g.done[m.id] ? 'done' : (curMs && curMs.id === m.id ? 'cur' : '')}">${I(g.done[m.id] ? 'check-circle' : curMs && curMs.id === m.id ? 'arrow-right' : 'minus-circle')} <span>${m.id} ${esc(m.title)}</span></div>`).join('')}</div>`;
      if (curMs) {
        const m = curMs; const roleOk = m.role === 'any' || TH.auth.role() === m.role;
        html += `<div class="ms"><div class="mt"><span>${m.id} · ${esc(m.title)}</span>${stChip(G.status(m))}</div><dl><dt>Màn hình</dt><dd><code>${esc(G.routeOf(m))}</code></dd><dt>Vai trò</dt><dd>${ROLE[m.role]}${roleOk ? ' <span class="green">✓</span>' : ' <span class="amber">(đang là ' + ROLE[TH.auth.role()] + ')</span>'}</dd><dt>Thao tác</dt><dd>${esc(m.how)}</dd><dt>Kết quả phải thấy</dt><dd>${esc(m.expect)}</dd>${next ? `<dt>Mốc tiếp theo</dt><dd class="muted">${next.id} ${esc(next.title)}</dd>` : ''}</dl>
          <div class="gacts">${U.btn({ label: 'Đi tới màn hình', icon: 'arrow-right', cls: 'btn-primary', size: 'btn-sm', act: 'g-go', attrs: { 'data-id': m.id } })}${!roleOk ? U.btn({ label: 'Chuyển vai trò → ' + ROLE[m.role], icon: 'user', cls: 'btn-outline', size: 'btn-sm', act: 'g-role', attrs: { 'data-id': m.id } }) : ''}${m.sample ? U.btn({ label: 'Xem dữ liệu mẫu', icon: 'eye', cls: 'btn-outline', size: 'btn-sm', act: 'g-sample', attrs: { 'data-id': m.id } }) : ''}${m.sample && m.sample.kind === 'form' ? U.btn({ label: 'Điền dữ liệu mẫu', icon: 'pencil', cls: 'btn-outline', size: 'btn-sm', act: 'g-fill', attrs: { 'data-id': m.id } }) + U.btn({ label: 'Điền lại', icon: 'rotate-ccw', cls: 'btn-ghost', size: 'btn-sm', act: 'g-refill', attrs: { 'data-id': m.id } }) : ''}${m.sample && m.sample.kind === 'file' ? U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-outline', size: 'btn-sm', act: 'g-dl', attrs: { 'data-id': m.id } }) + U.btn({ label: 'Dùng file mẫu', icon: 'file-check', cls: 'btn-outline', size: 'btn-sm', act: 'g-usefile', attrs: { 'data-id': m.id } }) : ''}</div>${m.sample && m.sample.open ? `<div class="xs muted mt8">${I('info')} ${esc(m.sample.open)}</div>` : ''}</div>`;
      } else html += `<div class="ms">${U.note('ok', 'Luồng ' + focusFlow.key + ' hoàn thành', cur ? 'Mốc tiếp theo: ' + cur.ms.id + ' ' + esc(cur.ms.title) + ' (' + cur.flow.key + ')' : 'Toàn bộ 16 điều kiện Go-live đã được thực hiện 🎉')}${cur ? `<div class="gacts">${U.btn({ label: 'Sang luồng ' + cur.flow.key, icon: 'arrow-right', cls: 'btn-primary', size: 'btn-sm', act: 'g-pick', attrs: { 'data-k': cur.flow.key } })}</div>` : ''}</div>`;
      html += `</div><details><summary>Nguyên tắc hướng dẫn</summary><div class="xs muted mt8">Các nút trong panel không tạo record, không submit. Record chỉ được tạo qua nút Lưu/Xác nhận của màn nghiệp vụ. Mốc được đánh giá lại sau mỗi render/save/action/route; dữ liệu do bạn tạo (không phải seed) mới được tính. Chạy tự động chỉ có trong Công cụ nâng cao (sidebar).</div></details>`;
    }
    body.innerHTML = html; const gf = document.getElementById('guide-foot'); if (gf) gf.textContent = '16 điều kiện Go-live P1 · 10 luồng' + (TH.phase && TH.phase.on(2) ? ' · + ' + G.flows().filter(f => f.phase === 2).length + ' luồng Phase 2' : '');
  };
  /* ---- dữ liệu mẫu ---- */
  G.openSample = (id) => { const m = G.find(id); if (!m || !m.sample) return; const s = m.sample; U.modal({ title: 'Dữ liệu mẫu – ' + m.id, sub: s.kind === 'form' ? 'Giá trị form (chỉ điền khi form đang mở; không submit)' : 'Metadata file mẫu (không đưa vào hệ thống khi xem)', body: s.kind === 'form' ? `<div class="sample-meta"><dl>${Object.entries(s.values).map(([k, val]) => `<dt>${esc(k)}</dt><dd>${esc(typeof val === 'number' ? F.vnd(val) : val)}</dd>`).join('')}</dl></div>${s.open ? U.note('info', '', esc(s.open)) : ''}` : `<div class="sample-meta"><dl><dt>Mục đích</dt><dd>${esc(s.purpose)}</dd><dt>Tên file</dt><dd class="mono">${esc(s.name)}</dd><dt>Số dòng</dt><dd>${s.rows}</dd><dt>Cột</dt><dd>${esc(s.cols)}</dd><dt>Quan hệ mã</dt><dd>${esc(s.relations || '-')}</dd><dt>Lỗi cố ý</dt><dd>${esc(s.errors)}</dd></dl></div>` }); };
  G.useSample = (id, force) => {
    const m = G.find(id); if (!m || !m.sample || m.sample.kind !== 'form') return; const s = m.sample;
    const scope = document.querySelector('.overlay .drawer, .overlay .modal') || (s.form === 'contract' ? document.getElementById('cf') : s.form === 'meter' ? document.getElementById('content') : s.form === 'hold' ? document.getElementById('hf') : s.form === 'deal' ? document.getElementById('df') : null);
    if (!scope) return U.toast('warn', 'Form chưa mở', s.open || 'Mở form nghiệp vụ trước rồi bấm Điền dữ liệu mẫu');
    let n = 0;
    if (s.form === 'meter') { scope.querySelectorAll('input[data-m=electricCurr]:not([disabled]), input[data-m=waterCurr]:not([disabled])').forEach(inp => { if (inp.value && !force) return; const prev = scope.querySelector(`input[data-m=${inp.dataset.m.replace('Curr', 'Prev')}][data-r="${inp.dataset.r}"]`); inp.value = Number(prev.value) + (inp.dataset.m === 'electricCurr' ? 150 : 12); inp.dispatchEvent(new Event('input', { bubbles: true })); n++; }); }
    else Object.entries(s.values).forEach(([k, val]) => { const el = scope.querySelector(`[name="${k}"]`); if (!el) return; if (el.value && !force && !(el.tagName === 'SELECT' && !el.value)) return; if (el.hasAttribute('data-money')) el.value = F.vnd(val); else el.value = val; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); n++; });
    U.toast(n ? 'ok' : 'info', n ? 'Đã điền ' + n + ' trường mẫu' : 'Không có trường trống để điền', 'Chưa submit – kiểm tra rồi bấm Lưu/Xác nhận');
  };
  G.sampleFile = (m) => { const s = m.sample; if (s.name.endsWith('.csv')) { const T = { tenant: 'tenant' }; const rows = [['Họ tên', 'SĐT', 'CCCD', 'Phòng', 'Ngày bắt đầu thuê', 'Zalo'], ['Nguyễn Văn An', '0901 111 222', '012345678901', 'A.01.01', '2024-10-01', 'an.nguyen93'], ['Trần Thị Bình', '0902 333 444', '012345678902', 'B.01.02', '2024-10-05', ''], ['Lê Quang Huy', '0909 876 543', '', 'C.08.02', '2024-10-10', ''], ['Phạm Thu Trang', '0904 555 666', '01234', 'A.16.08', '2024-10-12', ''], ['Hoàng Nam Khánh', '', '012345678905', 'D.03.06', '2025-01-01', ''], ['Vũ Thị Mai', '0905 777 888', '012345678906', 'Z.99.99', '2024-09-30', ''], ['Đặng Quốc Bảo', '0906 999 000', '', 'A.02.02', '2024-10-15', 'bao.dq'], ['Ngô Yến Nhi', '0907 121 212', '012345678908', 'B.02.01', '2024-10-18', ''], ['Phan Văn Long', '0908 343 434', '012345678909', 'C.01.01', '2024-10-20', ''], ['Bùi Thị Hạnh', '0909 565 656', '012345678910', 'D.01.01', '2024-10-22', '']]; return new File(['﻿' + F.csv(rows.slice(1), rows[0])], s.name, { type: 'text/csv' }); } return new File([s.content || 'DEMO'], s.name, { type: 'application/pdf' }); };
  G.downloadSample = (id) => { const m = G.find(id); const f = G.sampleFile(m); const a = document.createElement('a'); a.href = URL.createObjectURL(f); a.download = f.name; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 500); U.toast('ok', 'Đã tải ' + f.name, 'File không được đưa vào hệ thống'); };
  G.useFile = (id) => { const m = G.find(id); const f = G.sampleFile(m); const inp = document.querySelector('.overlay [data-dz] input[type=file]') || document.querySelector('#content [data-dz] input[type=file]'); if (!inp) return U.toast('warn', 'Chưa có ô tải file trên màn hình', 'Mở màn nghiệp vụ có vùng kéo thả trước'); const dt = new DataTransfer(); dt.items.add(f); inp.files = dt.files; inp.dispatchEvent(new Event('change', { bubbles: true })); U.toast('ok', 'Đã gắn ' + f.name + ' vào ô tải file', 'Chưa mapping/validate/commit – tiếp tục thao tác trên màn hình'); };
  G.resetProgress = () => { St.state.guide = { done: {}, ts: {}, visited: {}, current: null, pin: {} }; St.saveNow(); try { localStorage.removeItem(G.KEY); } catch (e) { } G.evaluate('sync'); };
  /* ---- Chạy toàn bộ kịch bản (Công cụ nâng cao) ---- */
  G.runAll = async () => {
    const wait = (ms) => new Promise(r => setTimeout(r, ms)); const prevRole = TH.auth.role(); const log = [];
    if (TH.phase && TH.phase.on(2) && Q.periodLocked && Q.periodLocked(St.state.meta.period)) { TH.auth.switchRole('admin'); X.unlockPeriod(St.state.meta.period, 'Chạy lại kịch bản demo'); log.push('Mở lại kỳ ' + St.state.meta.period + ' (đã khóa bởi kịch bản P2)'); }
    TH.auth.switchRole('ops');
    const t = X.saveTenant({ name: 'Khách Auto ' + Date.now().toString().slice(-4), phone: '091' + Date.now().toString().slice(-7).replace(/(\d{1})(\d{3})(\d{3})/, '$1 $2 $3'), job: 'Kỹ sư', segment: 'Chuyên gia' }); log.push('Khách ' + t.code);
    const room = St.where('rooms', r => r.status === 'ready').sort((a, b) => a.code.localeCompare(b.code))[0]; if (!room) throw new Error('Không còn phòng Sẵn sàng');
    const svc = room.defaultServiceIds.map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: '' }; });
    const c = X.saveContractDraft({ tenantId: t.id, roomId: room.id, start: '2024-10-01', end: '2025-09-30', payDay: 5, listPrice: room.price, price: room.price, deposit: room.price * 2, services: svc, members: [{ name: t.name, relation: 'Người thuê (chính)', phone: t.phone }] }); X.activateContract(c.id, 'auto:' + c.id); log.push('HĐ ' + c.code + ' phòng ' + room.code);
    TH.auth.switchRole('accountant'); const period = St.state.meta.period; const rows = X.batchRows(period, [room.buildingId]).filter(r => r.room.id === room.id);
    X.saveMeterReadings(period, [{ roomId: room.id, electricPrev: rows[0].electricPrev, electricCurr: rows[0].electricPrev + 150, waterPrev: rows[0].waterPrev, waterCurr: rows[0].waterPrev + 12 }]);
    const res = X.createInvoiceDrafts({ period, contractIds: [c.id], services: ['RENT', 'DIEN', 'NUOC', 'FIXED'], issueNow: false, key: 'auto-inv:' + c.id }); const inv = res.created[0]; if (!inv) throw new Error('Không tạo được hóa đơn'); X.issueInvoice(inv.id); log.push('Hóa đơn ' + inv.code + ' ' + F.vnd(inv.total));
    TH.auth.switchRole('admin'); const tpl1 = St.one('zaloTemplates', x => x.eventKey === 'reminder'); const b1 = X.createZaloBatch({ name: 'Auto – gửi hóa đơn', eventKey: 'reminder', sourceKey: 'manual', templateId: tpl1.id, recipients: X.buildRecipients('manual', { invoiceIds: [inv.id], ignoreRecent: true }), sendMode: 'now', key: 'auto-z1:' + inv.id }); log.push('Zalo ' + b1.code);
    await wait(1500);
    TH.auth.switchRole('accountant'); const part = Math.round(inv.total * 0.5 / 100000) * 100000; const pay = X.recordPayment({ tenantId: t.id, date: F.today(), amount: part, method: 'Chuyển khoản', ref: 'AUTO' + Date.now().toString().slice(-5), allocations: [{ invoiceId: inv.id, amount: part }], note: 'Thu một phần (auto)' }, 'auto-pay:' + inv.id); log.push('Thu ' + pay.code + ' ' + F.vnd(part) + ' – còn ' + F.vnd(Q.invRemaining(inv)));
    TH.auth.switchRole('admin'); const tpl2 = St.one('zaloTemplates', x => x.eventKey === 'debt'); const b2 = X.createZaloBatch({ name: 'Auto – nhắc công nợ', eventKey: 'debt', sourceKey: 'manual', templateId: tpl2.id, recipients: X.buildRecipients('manual', { invoiceIds: [inv.id], ignoreRecent: true }), sendMode: 'now', key: 'auto-z2:' + inv.id }); log.push('Zalo nhắc nợ ' + b2.code);
    TH.auth.switchRole('ops'); const term = X.terminateContract(c.id, { actualEnd: F.today(), reason: 'Khách trả phòng sớm', toCleaning: true, createRefund: true }); const rf = term.refund; log.push('Kết thúc HĐ, hồ sơ ' + rf.code);
    X.saveRefund({ id: rf.id, contractId: c.id, deductions: [{ group: 'Khấu hao', desc: 'Khấu hao cố định theo phòng (BR-12)', amount: 200000, evidenceCount: 1 }, { group: 'Dịch vụ', desc: 'Vệ sinh phòng', amount: 200000, evidenceCount: 1 }], offsetDebt: false, inspection: { wall: 'ok', furniture: 'minor', utilities: 'ok', devices: 'ok' } }); X.submitRefund(rf.id);
    TH.auth.switchRole('accountant'); X.approveRefund(rf.id); X.recordRefundPaid(rf.id, { paidDate: F.today(), paidMethod: 'Chuyển khoản', paidRef: 'UNC' + Date.now().toString().slice(-5), paidEvidence: 'uy_nhiem_chi.pdf' }); log.push('Hoàn cọc ' + F.vnd(rf.refundAmount));
    TH.auth.switchRole('ops'); X.confirmCleaned(room.id); log.push('Phòng ' + room.code + ' → Sẵn sàng');
    TH.auth.switchRole(prevRole || 'admin'); TH.layout.refreshTop(); St.state.guide.visited = Object.assign(St.state.guide.visited || {}, { '/dashboard': 1, '/settings/catalog': 1, '/rooms': 1, '/tenants': 1, '/contracts/new': 1, '/invoices/batch': 1, '/zalo/batches/new': 1, '/receivables': 1, ['/payments/' + pay.id]: 1, ['/contracts/' + c.id]: 1, '/refunds/new': 1, '/reports': 1 }); G.evaluate('sync');
    return log.join(' · ');
  };
  TH.guide = G;
})(window.TH);
