/* Workbook alignment metric registry – every number explains its formula. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store;
  const expenseTotal = (scope, parentCodes) => F.sum(Q.expenseRollup(scope).filter(x => parentCodes.includes(x.code)), x => x.total);
  const operating = scope => {
    const ids = scope.buildingIds || [], p = scope.period;
    const rows = ids.map(id => Q.operatingResult ? Q.operatingResult(p, { buildingId: id }) : { revenue: 0, opex: 0, dep: 0, result: 0 });
    return { revenue: F.sum(rows, x => x.revenue), opex: F.sum(rows, x => x.opex), dep: F.sum(rows, x => x.dep), result: F.sum(rows, x => x.result) };
  };
  const defs = {
    'revenue.rent': { label: 'Tiền nhà', formula: 'Σ dòng hóa đơn tiền phòng đã phát hành trong kỳ', includes: 'Tiền thuê phòng', excludes: 'Cọc, hoàn cọc, dịch vụ', status: 'approved', owner: 'Finance', compute: s => Q.revenueSplit(s).rent },
    'revenue.newDeposit': { label: 'Cọc mới', formula: 'Σ tiền cọc đã nhận của giao dịch chốt trong kỳ', includes: 'Dòng tiền cọc', excludes: 'Doanh thu kế toán', status: 'assumed', owner: 'Ngọc', compute: s => Q.revenueSplit(s).newDeposit },
    'revenue.penalty': { label: 'Phá hợp đồng', formula: 'Σ khấu trừ khác có lý do phá/hủy hợp đồng', includes: 'Phạt/khấu trừ', excludes: 'Khấu hao, sửa chữa, vệ sinh', status: 'assumed', owner: 'Ngọc', compute: s => Q.revenueSplit(s).penalty },
    'collection.progress': { label: 'Tiến độ thu', formula: 'Σ đã thu ÷ Σ phải thu của hóa đơn phát hành', includes: 'Thanh toán còn hiệu lực', excludes: 'Hóa đơn nháp/hủy', status: 'approved', owner: 'Finance', compute: s => { const invs = St.all('invoices').filter(i => s.buildingIds.includes(i.buildingId || Q.contract(i.contractId).buildingId) && (!s.period || i.period === s.period) && !['draft', 'cancelled'].includes(i.docStatus)); const total = F.sum(invs, i => i.total || 0), paid = F.sum(invs, i => Q.invPaid(i)); return total ? Math.round(paid / total * 1000) / 10 : 0; } },
    'profit.actual': { label: 'Lợi nhuận thực thu', formula: 'Thu tiền thuê + cọc mới + phạt HĐ − toàn bộ chi thực chi − hoàn cọc', includes: 'Cọc mới, mua thiết bị ở chi', excludes: 'Khoản chưa thu/chưa chi', status: 'assumed', owner: 'Ngọc', compute: s => { const rev = Q.revenueSplit(s); const exp = expenseTotal(s, ['GV', 'DV', 'VH', 'BH']); const refunds = F.sum(St.all('refunds').filter(r => s.buildingIds.includes(r.buildingId) && (!s.period || F.period(r.paidDate || r.requestDate) === s.period) && r.status === 'refunded'), r => r.refundAmount || 0); return rev.rent + rev.newDeposit + rev.penalty - exp - refunds; } },
    'profit.business': { label: 'Lợi nhuận kinh doanh', formula: 'Doanh thu thuê/dịch vụ/phạt − chi phí vận hành', includes: 'Doanh thu hóa đơn, OPEX, khấu hao', excludes: 'Cọc mới, hoàn cọc, mua thiết bị', status: 'approved', owner: 'Finance', compute: s => operating(s).result },
    'margin.rent': { label: 'Biên tiền thuê', formula: 'Doanh thu tiền nhà ÷ chi phí thuê nhà', includes: 'Tiền phòng; GV-THUE', excludes: 'Dịch vụ và chi phí khác', status: 'assumed', owner: 'Ngọc', compute: s => { const cost = F.sum(Q.expenseRollup(s).flatMap(x => x.children).filter(x => x.code === 'GV-THUE'), x => x.total); return cost ? Math.round(Q.revenueSplit(s).rent / cost * 1000) / 10 : 0; } },
    'cost.base': { label: 'Chi phí gốc', formula: 'Σ nhóm Giá vốn (GV)', includes: 'Thuê nhà, mua thiết bị', excludes: 'DV, VH, BH', status: 'assumed', owner: 'Finance', compute: s => expenseTotal(s, ['GV']) },
    'cost.fixed': { label: 'Chi phí cố định', formula: 'Σ nhóm Giá gốc dịch vụ + Vận hành', includes: 'DV, VH', excludes: 'BH', status: 'assumed', owner: 'Finance', compute: s => expenseTotal(s, ['DV', 'VH']) },
    'cost.variable': { label: 'Chi phí phát sinh', formula: 'Σ nhóm Bán hàng phát sinh', includes: 'Marketing, sửa chữa, khác', excludes: 'GV, DV, VH', status: 'assumed', owner: 'Finance', compute: s => expenseTotal(s, ['BH']) },
    'occupancy.rate': { label: 'Tỷ lệ lấp đầy', formula: 'Ngày phòng có khách ÷ tổng ngày phòng khả dụng', includes: 'Hợp đồng có hiệu lực trong kỳ', excludes: 'Tòa ngừng/bảo trì', status: 'approved', owner: 'Vận hành', compute: s => { const rows = s.buildingIds.map(id => Q.occupancy(s.period, id)).filter(x => !x.na); const total = F.sum(rows, x => x.total || 0); return total ? Math.round(F.sum(rows, x => x.days || 0) / total * 1000) / 10 : 0; } },
    'vacancy.days': { label: 'Ngày trống', formula: 'Tổng ngày phòng không có hợp đồng trong kỳ', includes: 'Phòng đang vận hành', excludes: 'Tòa ngừng/bảo trì', status: 'assumed', owner: 'Vận hành', compute: s => { const rows = s.buildingIds.map(id => Q.occupancy(s.period, id)).filter(x => !x.na); return F.sum(rows, x => (x.total || 0) - (x.days || 0)); } },
    'utility.diff': { label: 'Chênh lệch điện nước', formula: 'Doanh thu điện nước − chi phí điện nước', includes: 'Invoice line điện/nước; DV-DIEN, DV-NUOC', excludes: 'Dịch vụ khác', status: 'assumed', owner: 'Finance', compute: s => F.sum(Q.utilityLedger(s), x => x.diff) },
    'ontime.rate': { label: 'Tỷ lệ đúng hạn', formula: 'Hóa đơn thu đủ trước/đúng hạn ÷ hóa đơn đến hạn', includes: 'Hóa đơn đến hạn trong kỳ', excludes: 'Nháp/hủy/trả thiếu', status: 'assumed', owner: 'Finance', compute: s => Q.onTimeRate(s).rate },
    'roi.capital': { label: 'Lợi nhuận / vốn', formula: 'Lợi nhuận kinh doanh năm hóa ÷ vốn dự án', includes: 'Vốn dự án', excludes: 'Tài sản chủ nhà', status: 'assumed', owner: 'Ngọc', compute: s => { const capital = F.sum(St.all('projects').filter(p => s.buildingIds.includes(p.buildingId)), p => p.capital || 0); return capital ? Math.round(TH.metrics.value('profit.business', s) * 12 / capital * 1000) / 10 : 0; } },
    'roi.asset': { label: 'Lợi nhuận / tài sản', formula: 'Lợi nhuận kinh doanh năm hóa ÷ nguyên giá tài sản công ty', includes: 'Tài sản ownership=company', excludes: 'Tài sản chủ nhà', status: 'assumed', owner: 'Ngọc', compute: s => { const assets = F.sum(Q.shareholderAssetSummary(s), x => x.assetValue); return assets ? Math.round(TH.metrics.value('profit.business', s) * 12 / assets * 1000) / 10 : 0; } }
  };
  const M = { defs };
  M.value = (key, scope) => defs[key] ? defs[key].compute(scope) : null;
  M.get = key => defs[key] || null;
  M.info = key => { const d = defs[key]; if (!d) return ''; return `<div class="metric-formula"><b>${F.esc(d.label)}</b>${d.status === 'assumed' ? '<span class="chip amber">Giả định</span>' : '<span class="chip green">Đã duyệt</span>'}<p>${F.esc(d.formula)}</p><dl><dt>Bao gồm</dt><dd>${F.esc(d.includes)}</dd><dt>Loại trừ</dt><dd>${F.esc(d.excludes)}</dd><dt>Owner</dt><dd>${F.esc(d.owner)}</dd></dl></div>`; };
  M.snapshotLabel = scope => `Kỳ ${scope.period === 'all' ? 'tất cả' : F.periodShort(scope.period)} · tính lúc ${new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })} ${F.date(F.today())}`;
  TH.metrics = M;
})(window.TH);
