/* Spec v1.8 §7.6 / §12.23 – Metric Registry Phase 1: mọi chỉ tiêu của 2 báo cáo Excel có metric_code ổn định, nhóm, đơn vị, loại công thức,
   biểu thức, nguồn dữ liệu, date basis, version và business_confirmation_status (CONFIRMED / NEED_BUSINESS_CONFIRMATION / DEPRECATED).
   Registry cũ (TH.metrics.defs – Workbook alignment) giữ nguyên cho Report Hub; TH.metrics.P1 là registry theo spec. Trạng thái/phiên bản có thể ghi đè
   qua collection metricDefinitions (X.confirmMetric) – không hard-code suy đoán (§12.23.14 mục 15). */
(function (TH) {
  const F = TH.f, St = TH.store; const M = TH.metrics = TH.metrics || {};
  const NEED = 'NEED_BUSINESS_CONFIRMATION', OK = 'CONFIRMED';
  const G = { REV: 'DOANH THU', DEP: 'CỌC / HOÀN CỌC', ROOM: 'SỐ LƯỢNG PHÒNG', RENT: 'DOANH THU TIỀN NHÀ', SVC: 'DOANH THU DỊCH VỤ', COGS: 'GIÁ VỐN', OPEX: 'CHI PHÍ BÁN HÀNG / VẬN HÀNH', TC: 'TỔNG CHI PHÍ', GP: 'LỢI NHUẬN GỘP', NP: 'LỢI NHUẬN RÒNG', RATIO: 'CÁC TỶ LỆ', SHARE: 'CỔ ĐÔNG / VỐN / CHIA LỢI NHUẬN' };
  M.P1_GROUPS = Object.values(G);
  const S = (code, label, group, o) => Object.assign({ code, label, group, unit: 'MONEY', formulaType: 'SOURCE', deps: [], status: OK, version: 1, effectiveFrom: '2026-01-01', additive: true }, o);
  const FM = (code, label, group, formula, deps, o = {}) => Object.assign(S(code, label, group, { formulaType: 'FORMULA', formula, deps, source: 'Metric tổng hợp', dateBasis: 'Theo metric thành phần' }), o);
  const R = (code, excel, num, den, o = {}) => Object.assign(S(code, excel, G.RATIO, { unit: 'PERCENT', formulaType: 'FORMULA', formula: num + ' / ' + den, deps: [num, den], num, den, additive: false, source: 'Metric tổng hợp', dateBasis: 'Theo tử số/mẫu số', excel }), o);
  const EXP = (code, label, cats, o = {}) => Object.assign(S(code, label, G.COGS, { source: 'Expense / Expense Allocation', dateBasis: 'accounting_period', formula: 'Σ phiếu chi hạng mục ' + cats.join(', ') + ' (trực tiếp tòa hoặc đã phân bổ về tòa), bỏ phiếu hủy', cats }), o);
  const DEFS = [
    S('TOTAL_REVENUE', 'Tổng doanh thu', G.REV, { formulaType: 'FORMULA', formula: 'RENT_REVENUE + SERVICE_REVENUE (v1 – theo Revenue Recognition Rule chờ chốt)', deps: ['RENT_REVENUE', 'SERVICE_REVENUE'], source: 'Metric tổng hợp', dateBasis: 'billing_period', status: NEED, question: 'Q-RPT-001', note: 'Workbook "Tháng 8": Tổng doanh thu ≠ Tiền phòng + Dịch vụ. Candidate: tiền phòng, dịch vụ, cọc bị giữ, khoản thu khác, điều chỉnh, phạt.' }),
    S('NEW_DEPOSIT', 'Cọc phòng mới', G.DEP, { source: 'Deposit Ledger', dateBasis: 'received_at', formula: 'Σ bút toán RECEIVED trong kỳ (cọc nhận của HĐ tòa)' }),
    S('FORFEITED_DEPOSIT', 'Cọc khách bỏ không ở', G.DEP, { source: 'Settlement / Deposit Ledger', dateBasis: 'Ngày duyệt quyết toán', formula: 'Σ bút toán DEDUCTED (cọc giữ lại theo quyết toán đã duyệt)', status: NEED, question: 'Q-RPT-002', note: 'Khuyến nghị: chỉ ghi nhận sau khi settlement được duyệt.' }),
    S('REFUND_AMOUNT', 'Hoàn cọc', G.DEP, { source: 'Refund Case', dateBasis: 'refund_date', formula: 'Σ số thực hoàn của hồ sơ Đã hoàn theo ngày hoàn' }),
    S('EARLY_TERMINATION_COUNT', 'Phòng phá hợp đồng', G.ROOM, { unit: 'COUNT', source: 'Contract Event', dateBasis: 'event date (actual_end_date)', formula: 'Count Contract Event EARLY_TERMINATION trong kỳ', status: NEED, question: 'Q-RPT-005', note: 'Cần chốt actual_end_date hay approved_termination_date.' }),
    S('NEW_ROOM_COUNT', 'Phòng mới', G.ROOM, { unit: 'COUNT', source: 'Contract', dateBasis: 'start_date', formula: 'Count HĐ (loại mới) có ngày bắt đầu trong kỳ', status: NEED, question: 'Q-RPT-003' }),
    S('VACANT_ROOM_COUNT', 'Phòng trống', G.ROOM, { unit: 'COUNT', source: 'Room Status History', dateBasis: 'Ngày cuối kỳ', formula: 'Count phòng trạng thái trống (Sẵn sàng/Chờ dọn/Bảo trì) tại ngày cuối kỳ', status: NEED, question: 'Q-RPT-004', note: 'Candidate: trống tại cuối kỳ · từng trống trong kỳ · vacant room-days.' }),
    S('ROOM_COUNT', 'Tổng số phòng', G.ROOM, { unit: 'COUNT', source: 'Room', dateBasis: 'Ngày cuối kỳ', formula: 'Count phòng đang khai thác của tòa' }),
    S('OCCUPANCY_RATE', 'Tỷ lệ lấp đầy', G.ROOM, { unit: 'PERCENT', additive: false, formulaType: 'FORMULA', source: 'Contract / Room', dateBasis: 'Ngày-phòng trong kỳ', formula: 'Ngày-phòng có HĐ hiệu lực / tổng ngày-phòng khả dụng', deps: ['ROOM_COUNT'] }),
    S('RENT_REVENUE', 'Doanh thu tiền phòng', G.RENT, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line lineType RENT của hóa đơn đã phát hành trong kỳ' }),
    S('ELECTRIC_REVENUE', 'Điện', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ ELECTRIC (DIEN)', svc: ['DIEN'] }),
    S('WATER_REVENUE', 'Nước', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ WATER (NUOC)', svc: ['NUOC'] }),
    S('CLEANING_REVENUE', 'Vệ sinh', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ CLEANING (VESINH)', svc: ['VESINH'] }),
    S('INTERNET_REVENUE', 'Mạng', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ INTERNET', svc: ['INTERNET'] }),
    S('ELECTRIC_VEHICLE_REVENUE', 'Xe điện', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ sạc xe điện (SACXE)', svc: ['SACXE'] }),
    S('ELEVATOR_REVENUE', 'Thang máy', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ thang máy (THANGMAY)', svc: ['THANGMAY'] }),
    S('WASHING_REVENUE', 'Máy giặt', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line dịch vụ máy giặt (MAYGIAT)', svc: ['MAYGIAT'] }),
    S('OTHER_SERVICE_REVENUE', 'Dịch vụ khác', G.SVC, { source: 'Invoice Line', dateBasis: 'billing_period', formula: 'Σ Invoice Line SERVICE/PENALTY/ADJUSTMENT còn lại (gửi xe, phí quản lý, điện chung, phạt…)', svc: ['*'] }),
    FM('SERVICE_REVENUE', 'Tổng doanh thu dịch vụ', G.SVC, 'ELECTRIC + WATER + CLEANING + INTERNET + ELECTRIC_VEHICLE + ELEVATOR + WASHING + OTHER_SERVICE', ['ELECTRIC_REVENUE', 'WATER_REVENUE', 'CLEANING_REVENUE', 'INTERNET_REVENUE', 'ELECTRIC_VEHICLE_REVENUE', 'ELEVATOR_REVENUE', 'WASHING_REVENUE', 'OTHER_SERVICE_REVENUE'], { source: 'Invoice Line', dateBasis: 'billing_period' }),
    EXP('HEAD_LEASE_COST', 'Tiền thuê nhà', ['GV-THUE'], { note: 'Q-RPT-011: thuê nhà chu kỳ 3 tháng report theo cash hay phân bổ theo tháng – hiện theo kỳ hạch toán của phiếu.' }),
    EXP('EQUIPMENT_PURCHASE_COST', 'Mua thêm thiết bị', ['GV-TB'], { note: 'Q-RPT-008: ghi nhận 100% chi phí kỳ.' }),
    EXP('ELECTRIC_INPUT_COST', 'Giá gốc điện', ['GV-DIEN']), EXP('WATER_INPUT_COST', 'Giá gốc nước', ['GV-NUOC']), EXP('INTERNET_INPUT_COST', 'Giá gốc mạng', ['GV-MANG']),
    EXP('GARBAGE_COST', 'Phí rác', ['GV-RAC']), EXP('ENVIRONMENT_COST', 'Phí môi trường', ['GV-MT']), EXP('ELEVATOR_MAINT_COST', 'Bảo trì thang máy', ['GV-TM']),
    FM('COGS', 'Giá vốn', G.COGS, 'HEAD_LEASE + EQUIPMENT + ELECTRIC_INPUT + WATER_INPUT + INTERNET_INPUT + GARBAGE + ENVIRONMENT + ELEVATOR_MAINT (Excel: SUM(C22:C33))', ['HEAD_LEASE_COST', 'EQUIPMENT_PURCHASE_COST', 'ELECTRIC_INPUT_COST', 'WATER_INPUT_COST', 'INTERNET_INPUT_COST', 'GARBAGE_COST', 'ENVIRONMENT_COST', 'ELEVATOR_MAINT_COST'], { structure: true }),
    S('SALARY_COST', 'Chi phí lương', G.OPEX, { source: 'Payroll Cost Allocation', dateBasis: 'payroll_period', formula: 'Σ Payroll Cost Allocation về tòa của bảng lương Đã khóa (NV trực tiếp theo assignment snapshot; vai trò chung theo Allocation Rule)', note: 'Q-RPT-010: rule phân bổ lương quản lý tổng/kế toán/văn phòng.' }),
    Object.assign(EXP('OFFICE_COST', 'Thuê & DV văn phòng', ['VH-VP']), { group: G.OPEX, source: 'Expense Allocation' }),
    Object.assign(EXP('MARKETING_COST', 'Marketing', ['BH-MKT']), { group: G.OPEX }),
    Object.assign(EXP('COMMISSION_COST', 'Hoa hồng', ['BH-HH']), { group: G.OPEX }),
    Object.assign(EXP('REPAIR_COST', 'Sửa chữa / bảo trì', ['VH-SC', 'VH-TT']), { group: G.OPEX }),
    Object.assign(EXP('OTHER_COST', 'Chi phí khác', ['VH-KHAC']), { group: G.OPEX, question: 'Q-RPT-006', note: 'Data CONFIRMED (VH-KHAC); mapping thêm category vào CPK cần chốt.' }),
    FM('OPERATING_SELLING_COST', 'Tổng CPBH / vận hành', G.OPEX, 'SALARY + OFFICE + MARKETING + COMMISSION + REPAIR + OTHER (Excel: SUM(C35:C70))', ['SALARY_COST', 'OFFICE_COST', 'MARKETING_COST', 'COMMISSION_COST', 'REPAIR_COST', 'OTHER_COST'], { structure: true, alias: 'OPERATING_EXPENSE' }),
    FM('TOTAL_COST', 'Tổng chi phí', G.TC, 'COGS + OPERATING_SELLING_COST', ['COGS', 'OPERATING_SELLING_COST']),
    FM('GROSS_PROFIT', 'Lợi nhuận gộp', G.GP, 'TOTAL_REVENUE − COGS', ['TOTAL_REVENUE', 'COGS']),
    FM('NET_PROFIT', 'Lợi nhuận ròng', G.NP, 'TOTAL_REVENUE − TOTAL_COST', ['TOTAL_REVENUE', 'TOTAL_COST']),
    R('NET_MARGIN', 'LNR/DT', 'NET_PROFIT', 'TOTAL_REVENUE'), R('GROSS_MARGIN', 'LNG/DT', 'GROSS_PROFIT', 'TOTAL_REVENUE'), R('NET_PROFIT_OVER_COGS', 'LNR/GV', 'NET_PROFIT', 'COGS'), R('NET_PROFIT_OVER_GROSS_PROFIT', 'LNR/LNG', 'NET_PROFIT', 'GROSS_PROFIT'), R('TOTAL_COST_OVER_GROSS_PROFIT', 'CP/LNG', 'TOTAL_COST', 'GROSS_PROFIT'), R('COGS_OVER_REVENUE', 'GV/DT', 'COGS', 'TOTAL_REVENUE'), R('OPERATING_SELLING_COST_OVER_REVENUE', 'CPBH/DT', 'OPERATING_SELLING_COST', 'TOTAL_REVENUE'), R('TOTAL_COST_OVER_REVENUE', 'TCP/DT', 'TOTAL_COST', 'TOTAL_REVENUE'),
    R('SALARY_OVER_OPERATING_SELLING_COST', 'LƯƠNG/CPBH', 'SALARY_COST', 'OPERATING_SELLING_COST', { structure: true }),
    R('HH_OVER_OPERATING_SELLING_COST', 'HH/CPBH', 'COMMISSION_COST', 'OPERATING_SELLING_COST', { status: NEED, question: 'Q-RPT-006', note: 'HH = chỉ Hoa hồng hay Marketing + Hoa hồng? Tạm: chỉ Hoa hồng.' }),
    R('OTHER_COST_OVER_OPERATING_SELLING_COST', 'CPK/CPBH', 'OTHER_COST', 'OPERATING_SELLING_COST', { structure: true }),
    R('SERVICE_REVENUE_OVER_INPUT_COST', 'DT DV/GIÁ NHẬP', 'SERVICE_REVENUE', 'SERVICE_INPUT_COST', { status: NEED, question: 'Q-RPT-007', note: 'Tử/mẫu chưa chốt. Tạm: DT dịch vụ / (giá gốc điện + nước + mạng + rác + môi trường + thang máy).', deps: ['SERVICE_REVENUE', 'ELECTRIC_INPUT_COST', 'WATER_INPUT_COST', 'INTERNET_INPUT_COST', 'GARBAGE_COST', 'ENVIRONMENT_COST', 'ELEVATOR_MAINT_COST'] }),
    R('RENT_REVENUE_OVER_HEAD_LEASE', 'DT TIỀN NHÀ/GIÁ THUÊ NHÀ', 'RENT_REVENUE', 'HEAD_LEASE_COST'),
  ];
  const byCode = {}; DEFS.forEach(d => byCode[d.code] = d);
  M.P1 = DEFS; M.P1_BY = byCode;
  M.P1_QUESTIONS = { 'Q-RPT-001': 'Tổng doanh thu gồm chính xác những khoản nào?', 'Q-RPT-002': 'Cọc bị giữ được ghi nhận vào doanh thu ở thời điểm nào?', 'Q-RPT-003': 'Định nghĩa chính thức của "phòng mới"?', 'Q-RPT-004': 'Định nghĩa chính thức của "phòng trống"?', 'Q-RPT-005': 'Định nghĩa "phòng phá hợp đồng" và date basis?', 'Q-RPT-006': '"HH/CPBH" gồm những category nào?', 'Q-RPT-007': '"DT DV/GIÁ NHẬP" lấy tử số và mẫu số nào?', 'Q-RPT-008': 'Mua thêm thiết bị ghi nhận 100% chi phí kỳ hay có rule khác?', 'Q-RPT-009': 'Chi phí chung phân bổ T/S/G theo rule nào?', 'Q-RPT-010': 'Lương quản lý tổng/kế toán/văn phòng phân bổ theo rule nào?', 'Q-RPT-011': 'Tiền thuê nhà đầu vào chu kỳ 3 tháng report theo cash hay phân bổ theo tháng?', 'Q-RPT-012': 'Rule làm tròn tiền và percentage?' };
  /* Định nghĩa hiệu lực = registry code + ghi đè từ collection metricDefinitions (status/version do nghiệp vụ ký xác nhận) */
  M.def = (code) => { const d = byCode[code]; if (!d) return null; const o = (St.rawAll('metricDefinitions') || []).find(x => x && x.code === code); return o ? Object.assign({}, d, { status: o.status || d.status, version: o.version || d.version, effectiveFrom: o.effectiveFrom || d.effectiveFrom, confirmedBy: o.confirmedBy, confirmedAt: o.confirmedAt, history: o.history || [] }) : Object.assign({}, d, { history: [] }); };
  M.defs1 = () => DEFS.map(d => M.def(d.code));
  M.version = () => { const vs = M.defs1().map(d => d.version || 1); return 'v' + Math.max(...vs) + '.' + F.sum(vs, v => v); }; // "metric_definition_version" gộp – đổi khi có metric được xác nhận
  /* Trạng thái hiệu lực có tính lan truyền: metric tổng hợp phụ thuộc metric chưa chốt cũng chưa chốt */
  M.effectiveStatus = (code, seen = new Set()) => { const d = M.def(code); if (!d || seen.has(code)) return OK; seen.add(code); if (d.status === NEED) return NEED; if (d.status === 'DEPRECATED') return 'DEPRECATED'; for (const dep of d.deps || []) { if (byCode[dep] && M.effectiveStatus(dep, seen) === NEED) return NEED; } return OK; };
  M.needChain = (code) => { const d = M.def(code); if (!d) return []; if (d.status === NEED) return [code]; return (d.deps || []).flatMap(x => byCode[x] ? M.needChain(x) : []).filter((v, i, a) => a.indexOf(v) === i); };
  M.statusChip = (st) => st === NEED ? TH.ui.chip('Chờ chốt', 'amber') : st === 'DEPRECATED' ? TH.ui.chip('Ngừng dùng', 'gray') : TH.ui.chip('Đã xác nhận', 'green');
  M.fmt = (d, v) => { if (v == null || isNaN(v)) return '—'; if (d.unit === 'PERCENT') return (Math.round(v * 100) / 100).toLocaleString('vi-VN') + '%'; if (d.unit === 'COUNT') return String(Math.round(v)); const r = Math.round(v * 1000) / 1000; if (Number.isInteger(r)) return F.vnd(r); const abs = Math.abs(r), i = Math.floor(abs); const dec = String(Math.round((abs - i) * 1000) / 1000).slice(2); return (r < 0 ? '-' : '') + F.vnd(i) + '.' + dec; };
  const oldInfo = M.info;
  M.info = (key) => { const d = byCode[key] ? M.def(key) : null; if (!d) return oldInfo ? oldInfo(key) : ''; const st = M.effectiveStatus(d.code); const chain = M.needChain(d.code).filter(c => c !== d.code); return `<div class="metric-formula"><b><code>${F.esc(d.code)}</code> ${F.esc(d.excel && d.excel !== d.label ? d.label + ' (' + d.excel + ')' : d.label)}</b>${M.statusChip(st)}<p>${F.esc(d.formula || '')}</p><dl><dt>Nhóm</dt><dd>${F.esc(d.group)}</dd><dt>Đơn vị</dt><dd>${d.unit} · ${d.formulaType}</dd><dt>Nguồn</dt><dd>${F.esc(d.source || '')}</dd><dt>Date basis</dt><dd>${F.esc(d.dateBasis || '')}</dd><dt>Version</dt><dd>v${d.version} · hiệu lực ${F.date(d.effectiveFrom)}</dd>${d.question ? `<dt>Câu hỏi</dt><dd>${F.esc(d.question)} – ${F.esc(M.P1_QUESTIONS[d.question] || '')}</dd>` : ''}${chain.length ? `<dt>Phụ thuộc chưa chốt</dt><dd>${chain.map(c => '<code>' + F.esc(c) + '</code>').join(' ')}</dd>` : ''}${d.note ? `<dt>Ghi chú</dt><dd>${F.esc(d.note)}</dd>` : ''}</dl></div>`; };
})(window.TH);
