/* Manifest route Phase 1 + Phase 2 + Phase 3 – dữ liệu thuần, là nguồn duy nhất cho router, sidebar và scripts/check-rbac.mjs.
   ui = mã màn hình đặc tả; ms = mốc đầu tiên có màn (1A / 1B / 2 / 3); menu = mục sidebar được tô sáng. */
(function (TH) {
  const R = [
    { path: '/dashboard', ui: 'UI-01', title: 'Tổng quan', menu: 'dashboard', perm: 'dashboard.view', ms: '1A' },
    { path: '/owners', ui: 'UI-04', title: 'Chủ nhà', menu: 'owners', perm: 'owners.view', ms: '1A' },
    { path: '/owners/new', ui: 'UI-04', title: 'Thêm chủ nhà', menu: 'owners', perm: 'owners.manage', ms: '1A' },
    { path: '/owner-profiles/:id', ui: 'UI-04', title: 'Hồ sơ chủ nhà', menu: 'owners', perm: 'owners.view', ms: '1A' },
    { path: '/tenants/intake', ui: 'UI-07', title: 'Thêm khách hàng', menu: 'tenants', perm: 'tenants.manage', ms: '1A' },
    { path: '/buildings', ui: 'UI-02', title: 'Tòa nhà', menu: 'buildings', perm: 'buildings.view', ms: '1A' },
    { path: '/buildings/:id', ui: 'UI-03', title: 'Chi tiết tòa nhà', menu: 'buildings', perm: 'buildings.view', ms: '1A' },
    { path: '/owners/:id', ui: 'UI-04', title: 'Chủ nhà & hợp đồng đầu vào', menu: 'buildings', perm: 'owners.view', ms: '1A' },
    { path: '/owner-payments', ui: 'UI-05', title: 'Lịch trả chủ nhà', menu: 'expenses', perm: 'ownerPayments.view', ms: '1A' },
    { path: '/tenants', ui: 'UI-06', title: 'Khách thuê', menu: 'tenants', perm: 'tenants.view', ms: '1A' },
    { path: '/contracts', ui: 'UI-48', title: 'Hợp đồng thuê', menu: 'contracts', perm: 'tenants.view', ms: '1A' },
    { path: '/tenants/new', ui: 'UI-07', title: 'Tạo khách & lượt thuê', menu: 'tenants', perm: 'tenants.manage', ms: '1A' },
    { path: '/stays/:id', ui: 'UI-07', title: 'Chi tiết lượt thuê', menu: 'tenants', perm: 'tenants.view', ms: '1A', also: ['UI-08', 'UI-09'] },
    { path: '/billing/readings', ui: 'UI-10', title: 'Chỉ số điện nước', menu: 'billing', perm: 'readings.view', ms: '1A' },
    { path: '/billing/invoices', ui: 'UI-11', title: 'Hóa đơn', menu: 'billing', perm: 'invoices.view', ms: '1A' },
    { path: '/billing/invoices/:id', ui: 'UI-12', title: 'Chi tiết hóa đơn', menu: 'billing', perm: 'invoices.view', ms: '1A' },
    { path: '/print/invoice/:id', ui: 'UI-12', title: 'Bản in hóa đơn', menu: 'billing', perm: 'invoices.view', ms: '1A', print: true },
    { path: '/billing/receipts', ui: 'UI-13', title: 'Phiếu thu', menu: 'billing', perm: 'payments.view', ms: '1A' },
    { path: '/billing/receipts/new', ui: 'UI-13', title: 'Ghi nhận thu tiền', menu: 'billing', perm: 'payments.record', ms: '1A' },
    { path: '/billing/receipts/:id', ui: 'UI-13', title: 'Chi tiết phiếu thu', menu: 'billing', perm: 'payments.view', ms: '1A' },
    { path: '/billing/debts', ui: 'UI-14', title: 'Công nợ & tiến độ thu', menu: 'billing', perm: 'debts.viewStatus', ms: '1A' },
    { path: '/expenses', ui: 'UI-15', title: 'Chi phí', menu: 'expenses', perm: 'expenses.view', ms: '1A' },
    { path: '/expenses/allocation', ui: 'UI-16', title: 'Phân bổ chi phí chung', menu: 'expenses', perm: 'allocation.view', ms: '1B' },
    { path: '/refunds', ui: 'UI-17', title: 'Hoàn cọc', menu: 'refunds', perm: 'refunds.view', ms: '1A' },
    { path: '/refunds/:id', ui: 'UI-18', title: 'Phiếu hoàn cọc', menu: 'refunds', perm: 'refunds.view', ms: '1A' },
    { path: '/print/refund/:id', ui: 'UI-18', title: 'Bản in phiếu hoàn cọc', menu: 'refunds', perm: 'refunds.view', ms: '1A', print: true },
    { path: '/hr', ui: 'UI-23', title: 'Nhân sự', menu: 'hr', perm: 'hr.view', ms: '1A' },
    { path: '/hr/staff/:id', ui: 'UI-23', title: 'Hồ sơ nhân viên', menu: 'hr', perm: 'hr.view', ms: '1A' },
    { path: '/hr/assignments', ui: 'UI-24', title: 'Phân công & tổ chức', menu: 'hr', perm: 'hr.view', ms: '1A' },
    { path: '/hr/payroll', ui: 'UI-25', title: 'Bảng lương', menu: 'hr', perm: 'payroll.view', ms: '1B' },
    { path: '/reports', ui: 'UI-27', title: 'Báo cáo', menu: 'reports', perm: 'reports.view', ms: '1B' },
    { path: '/reports/total', ui: 'UI-29', title: 'Báo cáo tổng (LN dòng tiền)', menu: 'reports', perm: 'reports.view', ms: '1B' },
    { path: '/reports/business', ui: 'UI-30', title: 'Báo cáo kinh doanh', menu: 'reports', perm: 'reports.view', ms: '1B' },
    { path: '/reports/buildings', ui: 'UI-28', title: 'Báo cáo theo tòa', menu: 'reports', perm: 'reports.view', ms: '1B' },
    { path: '/zalo', ui: 'UI-39', title: 'Thông báo Zalo', menu: 'zalo', perm: 'zalo.view', ms: '1A' },
    { path: '/zalo/inbox', ui: 'UI-39', title: 'Phản hồi Zalo', menu: 'zalo', perm: 'zalo.inbox', ms: '2' },
    { path: '/zalo/batches/:id', ui: 'UI-39', title: 'Chi tiết đợt gửi', menu: 'zalo', perm: 'zalo.view', ms: '1A' },
    { path: '/import', ui: 'UI-37', title: 'Import dữ liệu', menu: 'import', perm: 'import.view', ms: '1A' },
    { path: '/settings', ui: 'UI-38', title: 'Cài đặt', menu: 'settings', perm: 'settings.view', ms: '1A' },
    /* --- Phase 2 --- */
    { path: '/sales', ui: 'UI-19', title: 'Tổng quan hàng hóa', menu: 'sales', perm: 'sales.view', ms: '2' },
    { path: '/sales/leads', ui: 'UI-20', title: 'Khách tiềm năng & lượt xem', menu: 'leads', perm: 'sales.view', ms: '2' },
    { path: '/sales/deals', ui: 'UI-21', title: 'Giao dịch chốt', menu: 'deals', perm: 'sales.view', ms: '2' },
    { path: '/sales/deals/:id', ui: 'UI-21', title: 'Chi tiết giao dịch', menu: 'deals', perm: 'sales.view', ms: '2' },
    { path: '/sales/commission', ui: 'UI-22', title: 'Hoa hồng & nhân sự sale', menu: 'commission', perm: 'commission.view', ms: '2' },
    { path: '/repairs', ui: 'UI-47', title: 'Sổ sửa chữa & ứng chi vật tư', menu: 'repairs', perm: 'repairs.view', ms: '2' },
    { path: '/documents', ui: 'UI-26', title: 'Kho tài liệu', menu: 'documents', perm: 'documents.view', ms: '2' },
    { path: '/ocr/:id', ui: 'UI-08', title: 'Rà soát OCR hợp đồng', menu: 'tenants', perm: 'ocr.review', ms: '2' },
    { path: '/shares', ui: 'UI-31', title: 'Cổ đông & tỷ lệ góp', menu: 'shares', perm: 'shares.view', ms: '2' },
    { path: '/shares/:id', ui: 'UI-32', title: 'Bảng kê chia lãi', menu: 'shares', perm: 'shares.view', ms: '2' },
    { path: '/reports/costs', ui: 'UI-42', title: 'Chi phí giá vốn / cố định / phát sinh', menu: 'reports', perm: 'reports.ops', ms: '2' },
    { path: '/reports/amduong', ui: 'UI-43', title: 'Âm dương điện nước', menu: 'reports', perm: 'reports.ops', ms: '2' },
    { path: '/reports/repairs', ui: 'UI-44', title: 'Chi phí sửa chữa, vệ sinh', menu: 'reports', perm: 'reports.ops', ms: '2' },
    { path: '/reports/rooms', ui: 'UI-45', title: 'Báo cáo phòng vận hành', menu: 'reports', perm: 'reports.ops', ms: '2' },
    { path: '/reports/sales', ui: 'UI-46', title: 'Khách hàng & doanh số sale', menu: 'reports', perm: 'reports.ops', ms: '2' },
    /* --- Phase 3 --- */
    { path: '/assets', ui: 'UI-34', title: 'Tài sản & thiết bị', menu: 'assets', perm: 'assets.view', ms: '3' },
    { path: '/assets/maintenance', ui: 'UI-35', title: 'Lịch bảo dưỡng', menu: 'assets', perm: 'maintenance.view', ms: '3' },
    { path: '/assets/inventory', ui: 'UI-36', title: 'Kiểm kê tài sản', menu: 'assets', perm: 'inventory.view', ms: '3' },
    { path: '/shares/capital', ui: 'UI-33', title: 'Góp vốn, cọc, tài sản & chi thực', menu: 'shares', perm: 'capital.view', ms: '3' },
    { path: '/reports/forecast', ui: 'UI-40', title: 'Dự kiến lợi nhuận', menu: 'reports', perm: 'forecast.view', ms: '3' },
    { path: '/reports/efficiency', ui: 'UI-41', title: 'Hiệu quả vốn, tài sản & tiền nhà', menu: 'reports', perm: 'efficiency.view', ms: '3' },
  ];
  /* Sidebar (đặc tả §1.2): mục chỉ hiện khi vai trò có quyền và mốc hiện tại đã mở route */
  const NAV = [
    { key: 'dashboard', label: 'Tổng quan', icon: 'home', href: '#/dashboard' },
    { group: 'Vận hành', icon: 'building', items: [
      { key: 'owners', label: 'Chủ nhà', href: '#/owners' },
      { key: 'buildings', label: 'Tòa nhà', href: '#/buildings' },
      { key: 'tenants', label: 'Khách hàng', href: '#/tenants' },
      { key: 'contracts', label: 'Hợp đồng thuê', href: '#/contracts' },
      { key: 'repairs', label: 'Sổ sửa chữa', href: '#/repairs' },
      { key: 'assets', label: 'Tài sản & bảo trì', href: '#/assets', alts: ['#/assets/maintenance', '#/assets/inventory'] },
      { key: 'documents', label: 'Tài liệu', href: '#/documents' },
    ] },
    { group: 'Kinh doanh', icon: 'briefcase', items: [
      { key: 'sales', label: 'Tổng quan hàng', href: '#/sales' },
      { key: 'leads', label: 'Khách xem', href: '#/sales/leads' },
      { key: 'deals', label: 'Giao dịch chốt', href: '#/sales/deals' },
      { key: 'commission', label: 'Hoa hồng', href: '#/sales/commission' },
    ] },
    { group: 'Tài chính', icon: 'wallet', items: [
      { key: 'billing', label: 'Hóa đơn & thu tiền', href: '#/billing/invoices', alts: ['#/billing/readings', '#/billing/debts'] },
      { key: 'expenses', label: 'Chi phí', href: '#/expenses', alts: ['#/owner-payments'] },
      { key: 'refunds', label: 'Hoàn cọc', href: '#/refunds' },
      { key: 'shares', label: 'Cổ đông', href: '#/shares', alts: ['#/shares/capital'] },
      { key: 'reports', label: 'Báo cáo', href: '#/reports', alts: ['#/reports/costs', '#/reports/efficiency'] },
    ] },
    { group: 'Nhân sự', icon: 'users', items: [
      { key: 'hr', label: 'Nhân sự & lương', href: '#/hr' },
    ] },
  ];
  const FOOT = [
    { key: 'zalo', label: 'Thông báo Zalo', icon: 'message', href: '#/zalo', alts: ['#/zalo/inbox'] },
    { key: 'import', label: 'Import dữ liệu', icon: 'upload', href: '#/import' },
    { key: 'settings', label: 'Cài đặt', icon: 'settings', href: '#/settings' },
  ];
  TH.routes = { ROUTES: R, NAV, FOOT, PHASE1_UI: ['UI-01', 'UI-02', 'UI-03', 'UI-04', 'UI-05', 'UI-06', 'UI-07', 'UI-08', 'UI-09', 'UI-10', 'UI-11', 'UI-12', 'UI-13', 'UI-14', 'UI-15', 'UI-16', 'UI-17', 'UI-18', 'UI-23', 'UI-24', 'UI-25', 'UI-27', 'UI-28', 'UI-29', 'UI-30', 'UI-37', 'UI-38', 'UI-39', 'UI-48'],
    PHASE2_UI: ['UI-19', 'UI-20', 'UI-21', 'UI-22', 'UI-26', 'UI-31', 'UI-32', 'UI-42', 'UI-43', 'UI-44', 'UI-45', 'UI-46', 'UI-47'],
    PHASE3_UI: ['UI-33', 'UI-34', 'UI-35', 'UI-36', 'UI-40', 'UI-41'] };
})(window.TH);
