/* Seed / migration – Spec v1.8 Wave 3: lịch sử trạng thái & giá phòng (§12.5), sự kiện HĐ + loại/lần HĐ (§12.7), trạng thái khách là field (§4.8), kỳ hóa đơn (§12.11.1),
   HĐ đầu vào: trạng thái/HKD/PCCC/lịch giá (§12.3), tài liệu docType/version (§4.5), kịch bản demo: HĐ chờ duyệt / chờ gia hạn / chờ kết thúc (phòng Sắp trống) / chờ quyết toán, follow-up HĐ sắp hết.
   Additive & idempotent (meta.w3Migrated). */
(function (TH) {
  const F = TH.f, seed = TH.seed = TH.seed || {};
  const T = F.DEMO_TODAY;
  const mk = (st, col, obj) => { obj.id = obj.id || F.uid(col.slice(0, 3)); obj.source = obj.source || 'seed'; obj.createdAt = obj.createdAt || '2026-01-01T08:00'; st[col].push(obj); return obj; };
  const userBy = (st, username) => st.users.find(u => u && u.username === username) || null;
  const bByName = (st, name) => st.buildings.find(b => b && b.name === name) || null;
  const LIVE = ['active', 'pending_renewal', 'pending_end'];

  const migrateRooms = (st) => {
    st.roomStatusHistory = st.roomStatusHistory || []; st.roomPriceHistory = st.roomPriceHistory || [];
    st.rooms.forEach(r => { if (!r) return; if (!st.roomStatusHistory.some(h => h && h.roomId === r.id)) { const c = st.contracts.find(x => x && x.roomId === r.id && LIVE.includes(x.status)); if (c && r.status === 'occupied') { mk(st, 'roomStatusHistory', { roomId: r.id, buildingId: r.buildingId, from: null, to: 'ready', at: (r.createdAt || '2026-01-01T08:00'), date: (r.createdAt || '2026-01-01').slice(0, 10), by: null, byName: 'Chuyển đổi', reason: 'Khởi tạo' }); mk(st, 'roomStatusHistory', { roomId: r.id, buildingId: r.buildingId, from: 'ready', to: 'occupied', at: c.start + 'T08:00', date: c.start, by: null, byName: 'Chuyển đổi', reason: 'Kích hoạt HĐ ' + c.code, refType: 'contract', refId: c.id }); } else mk(st, 'roomStatusHistory', { roomId: r.id, buildingId: r.buildingId, from: null, to: r.status, at: (r.createdAt || '2026-01-01T08:00'), date: (r.createdAt || '2026-01-01').slice(0, 10), by: null, byName: 'Chuyển đổi', reason: 'Khởi tạo lịch sử (dữ liệu chuyển đổi)' }); } if (!st.roomPriceHistory.some(h => h && h.roomId === r.id)) mk(st, 'roomPriceHistory', { roomId: r.id, buildingId: r.buildingId, price: Number(r.price) || 0, effectiveFrom: '2026-01-01', reason: 'Giá niêm yết ban đầu', by: null, byName: 'Chuyển đổi' }); });
  };
  const migrateContracts = (st) => {
    st.contractEvents = st.contractEvents || []; st.contractFollowUps = st.contractFollowUps || [];
    const chainNo = (c) => { let n = 1; let x = c; let g = 0; while (x && x.renewedFromId && g++ < 20) { x = st.contracts.find(y => y && y.id === x.renewedFromId); if (x) n++; } return n; };
    st.contracts.forEach(c => { if (!c) return; if (!c.contractType) c.contractType = c.renewedFromId ? 'renewal' : 'new'; if (!c.termNo) c.termNo = chainNo(c); if (!c.endType && c.status === 'ended') c.endType = /vi phạm|phá/i.test(c.endReason || '') ? 'breach' : /sớm/i.test(c.endReason || '') ? 'early_tenant' : /gia hạn/i.test(c.endReason || '') ? 'renew' : 'on_time';
      const ev = (type, date, extra = {}) => { if (!st.contractEvents.some(e => e && e.contractId === c.id && e.type === type)) mk(st, 'contractEvents', Object.assign({ contractId: c.id, type, date, at: date + 'T08:00', by: null, buildingId: c.buildingId, roomId: c.roomId, tenantId: c.tenantId }, extra)); };
      if (['active', 'pending_renewal', 'pending_end', 'pending_settlement', 'ended'].includes(c.status)) ev('ACTIVATED', c.start);
      if (c.status === 'ended') { ev(['early_tenant', 'early_company', 'breach'].includes(c.endType) ? 'EARLY_TERMINATION' : 'ENDED', c.actualEnd || c.end); if (c.renewedToId) ev('RENEWED', c.actualEnd || c.end, { refId: c.renewedToId }); } });
  };
  const migrateTenants = (st) => { st.tenants.forEach(t => { if (!t) return; if (!t.status || !['active', 'inactive', 'blocked'].includes(t.status)) t.status = 'active'; }); };
  const migrateBilling = (st) => {
    st.billingPeriods = st.billingPeriods || [];
    const periods = new Set(st.invoices.filter(i => i && i.period).map(i => i.period)); periods.add(st.meta.period || '2026-10');
    [...periods].sort().forEach(p => { if (st.billingPeriods.some(b => b && b.code === p)) return; const [y, m] = p.split('-').map(Number); const to = F.toISO(new Date(y, m, 0)); const p2 = (st.periods || []).find(x => x && (x.period === p || x.code === p)); const locked = p < (st.meta.period || '2026-10') || (p2 && (p2.status === 'locked' || p2.locked)); mk(st, 'billingPeriods', { code: p, from: p + '-01', to, closeDate: to, issueDate: F.addDays(to, -5), status: locked ? 'LOCKED' : 'OPEN', lockedAt: locked ? to + 'T18:00' : null, lockedBy: locked ? (userBy(st, 'ketoan') || {}).id || null : null, note: locked ? 'Khóa theo dữ liệu chuyển đổi' : '' }); });
    st.invoiceLines.forEach(l => { if (!l) return; if (!l.lineType) l.lineType = l.kind === 'rent' ? 'RENT' : (l.kind === 'penalty' ? 'PENALTY' : l.kind === 'adjust' ? 'ADJUSTMENT' : 'SERVICE'); if (!l.unit) l.unit = l.kind === 'rent' ? 'tháng' : l.kind === 'electric' ? 'kWh' : l.kind === 'water' ? 'm³' : ''; if (!l.sourceReadingId && l.meterId) l.sourceReadingId = l.meterId; });
    st.invoices.forEach(i => { if (!i) return; if (i.adjustment == null) i.adjustment = 0; if (i.carriedOver == null) i.carriedOver = 0; });
  };
  const migrateLandlordContracts = (st) => {
    st.landlordContracts.forEach(lc => { if (!lc) return; if (!lc.status || lc.status === 'active') lc.status = lc.end < T ? 'ended' : 'active'; if (!lc.hkdStatus) { const hasDoc = st.documents.some(d => d && ((d.entityType === 'landlord' && d.entityId === lc.landlordId) || (d.entityType === 'building' && (lc.buildingIds || []).includes(d.entityId))) && /hkd|đkkd|hộ kinh doanh/i.test(d.name || '')); lc.hkdStatus = hasDoc ? 'registered' : 'unregistered'; } if (!lc.pccc) { const b = st.buildings.find(x => x && (lc.buildingIds || []).includes(x.id)); lc.pccc = b && b.licenseExpiry ? { status: 'valid', expiry: b.licenseExpiry } : { status: 'none', expiry: '' }; } if (lc.dueDay == null) lc.dueDay = 5; if (!lc.priceSchedule) lc.priceSchedule = []; if (!lc.buildingType) { const b = st.buildings.find(x => x && (lc.buildingIds || []).includes(x.id)); if (b) { lc.buildingType = b.buildingType || 'T'; lc.typeEffectiveFrom = lc.start; } } });
    st.documents.forEach(d => { if (!d) return; if (!d.docType) { const n = String(d.name || d.fileName || ''); d.docType = /hkd|đkkd|hộ kinh doanh/i.test(n) ? 'hkd' : /pccc/i.test(n) ? 'pccc' : /sổ đỏ|so_do/i.test(n) ? 'deed' : /phụ lục/i.test(n) ? 'annex' : /hợp đồng|hd_/i.test(n) ? 'contract' : /bàn giao/i.test(n) ? 'handover' : /cccd|cmnd/i.test(n) ? 'id' : /uy_nhiem|biên lai|chứng từ/i.test(n) ? 'receipt' : /\.(jpe?g|png)$/i.test(n) ? 'photo' : 'other'; } if (!d.version) d.version = 1; });
  };
  /* Kịch bản demo §12.7.3 / §12.15 */
  const seedScenario = (st) => {
    const ops = userBy(st, 'vanhanh') || {}; const now = T + 'T09:00';
    const pick = (bName, pred) => { const b = bByName(st, bName); return b ? st.contracts.filter(c => c && c.buildingId === b.id && c.status === 'active' && pred(c)) : []; };
    // 1. HĐ chờ duyệt: 1 HĐ dự thảo (nếu có) → pending_approval
    const draft = st.contracts.find(c => c && c.status === 'draft' && c.source !== 'user'); if (draft) { draft.status = 'pending_approval'; draft.submittedAt = now; draft.submittedBy = ops.id || null; }
    // 2. Chờ kết thúc: khách báo trả phòng ngày 05/11 → phòng Sắp trống
    const c1 = pick('Tòa Ocean', c => F.daysUntil(c.end) > 60)[0] || st.contracts.find(c => c && c.status === 'active' && F.daysUntil(c.end) > 60 && st.rooms.some(r => r && r.id === c.roomId && r.status === 'occupied')); if (c1 && !st.contracts.some(c => c && c.status === 'pending_end')) { Object.assign(c1, { status: 'pending_end', noticeDate: F.addDays(T, -3), moveOutDate: F.addDays(T, 8), endType: 'early_tenant', endReasonCode: 'early_tenant', endNote: 'Khách chuyển công tác' }); const r = st.rooms.find(x => x && x.id === c1.roomId); if (r) { r.status = 'vacating'; mk(st, 'roomStatusHistory', { roomId: r.id, buildingId: r.buildingId, from: 'occupied', to: 'vacating', at: F.addDays(T, -3) + 'T10:00', date: F.addDays(T, -3), by: ops.id || null, byName: ops.name || 'Vận hành', reason: 'Xác nhận trả phòng ' + F.date(F.addDays(T, 8)), refType: 'contract', refId: c1.id }); } mk(st, 'contractEvents', { contractId: c1.id, type: 'MOVE_OUT_CONFIRMED', date: F.addDays(T, -3), at: F.addDays(T, -3) + 'T10:00', by: ops.id || null, buildingId: c1.buildingId, roomId: c1.roomId, tenantId: c1.tenantId, endType: 'early_tenant' }); }
    // 3. Chờ gia hạn: HĐ sắp hết có HĐ gia hạn dự thảo
    const c2 = st.contracts.find(c => c && c.status === 'active' && F.daysUntil(c.end) <= 35 && F.daysUntil(c.end) > 5 && !c.renewedToId); if (c2 && !st.contracts.some(c => c && c.status === 'pending_renewal')) { const n = mk(st, 'contracts', Object.assign({}, c2, { id: undefined, code: 'HD-2026-' + F.pad(st.contracts.length + 1, 3), start: F.addDays(c2.end, 1), end: F.addDays(F.addMonths(c2.end, 12), 0), status: 'draft', signedDate: null, renewedFromId: c2.id, renewedToId: null, createdAt: now, activatedAt: null, depositPaymentId: null, depositPaidAt: null, contractType: 'renewal', termNo: (c2.termNo || 1) + 1, note: 'HĐ gia hạn – dự thảo từ Work Queue' })); c2.status = 'pending_renewal'; c2.renewedToId = n.id; st.contractServices.filter(s => s && s.contractId === c2.id).forEach(s => mk(st, 'contractServices', Object.assign({}, s, { id: undefined, contractId: n.id, createdAt: now }))); mk(st, 'contractFollowUps', { contractId: c2.id, at: F.addDays(T, -2) + 'T15:00', date: F.addDays(T, -2), by: ops.id || null, byName: ops.name || 'Vận hành', channel: 'Điện thoại', result: 'renew', note: 'Khách đồng ý gia hạn 12 tháng, giữ giá', nextDeadline: F.addDays(T, 5) }); c2.followUpResult = 'renew'; c2.followUpAt = F.addDays(T, -2) + 'T15:00'; }
    // 4. Follow-up cho vài HĐ sắp hết khác
    st.contracts.filter(c => c && c.status === 'active' && F.daysUntil(c.end) <= 35 && !c.renewedToId).slice(0, 3).forEach((c, i) => { if (st.contractFollowUps.some(f => f && f.contractId === c.id)) return; const res = ['contacted', 'no_response', 'on_time'][i]; mk(st, 'contractFollowUps', { contractId: c.id, at: F.addDays(T, -(i + 1)) + 'T14:00', date: F.addDays(T, -(i + 1)), by: ops.id || null, byName: ops.name || 'Vận hành', channel: i === 1 ? 'Zalo' : 'Điện thoại', result: res, note: res === 'contacted' ? 'Khách cân nhắc, hẹn trả lời' : res === 'no_response' ? 'Gọi 2 lần không nghe máy' : 'Khách trả phòng đúng hạn', nextDeadline: F.addDays(T, 3 + i) }); c.followUpResult = res; c.followUpAt = F.addDays(T, -(i + 1)) + 'T14:00'; });
    // 5. Tiền chưa xác định
    if (!st.payments.some(p => p && p.unidentified)) mk(st, 'payments', { code: 'PAY-202610-900', tenantId: null, roomId: null, buildingId: null, date: F.addDays(T, -1), amount: 3200000, method: 'Chuyển khoản', ref: 'FT26102900123', evidence: '', note: 'Nội dung CK không khớp phòng/khách', status: 'recorded', unidentified: true, transferContent: 'CK TIEN PHONG T10', createdBy: (userBy(st, 'ketoan') || {}).id || null, bank: 'Vietcombank', createdAt: F.addDays(T, -1) + 'T09:30' });
    // 6. Lịch tăng giá HĐ đầu vào Sunrise
    const sun = bByName(st, 'Tòa Sunrise'); const lc = sun ? st.landlordContracts.find(x => x && (x.buildingIds || []).includes(sun.id) && x.status === 'active') : null; if (lc && !(lc.priceSchedule || []).length) { lc.priceSchedule = [{ from: F.addMonths(lc.start, 24), price: Math.round(Number(lc.rent) * 1.05 / 100000) * 100000, note: 'Tăng 5% sau giữ giá 24 tháng' }]; lc.bankAccount = { bank: 'BIDV', name: 'ĐỖ THỊ THÙY LINH', no: '2120368058' }; lc.contractNo = '01/2026/HĐT-SUNRISE'; }
  };
  seed.migrateW3 = (st) => {
    ['roomStatusHistory', 'roomPriceHistory', 'contractEvents', 'contractFollowUps', 'billingPeriods'].forEach(c => { if (!Array.isArray(st[c])) st[c] = []; });
    if (st.meta.w3Migrated) return st;
    migrateRooms(st); migrateContracts(st); migrateTenants(st); migrateBilling(st); migrateLandlordContracts(st); seedScenario(st);
    st.meta.w3Migrated = true; st.meta.w3MigratedAt = F.nowISO(); return st;
  };
})(window.TH);
