/* Seed / migration spec v1.8 Wave 5 (additive & idempotent – meta.w5Migrated):
   - Cổ phần theo tòa (buildingShares) chuyển từ cam kết vốn theo dự án (P3) với ngày hiệu lực; góp vốn theo tòa (capitalCalls/capitalPayments) từ đợt góp vốn cũ.
   - Tòa G1 (loại G) tái lập Golden Report A tháng 06/2026 (§12.23.12): 12 phòng, hóa đơn/dòng dịch vụ, cọc/hoàn cọc, 3 phá HĐ, 2 phòng mới, 1 phòng trống, chi phí giá vốn & CPBH,
     9 cổ đông = 100% (đổi tỷ lệ từ 01/09/2026 để demo "báo cáo kỳ cũ dùng tỷ lệ đúng kỳ"), đợt góp vốn.
   - goldenDatasets: Golden A (G1 06/2026) và Golden B (tháng 8 toàn hệ thống – chỉ giá trị kỳ vọng).
   Lương G1 06/2026 + kỳ báo cáo/snapshot/phân phối dựng ở X.ensureW5Scenario (sau kịch bản W4). */
(function (TH) {
  const F = TH.f; const seed = TH.seed = TH.seed || {};
  const mk = (st, col, obj) => { st[col] = st[col] || []; obj.id = obj.id || F.uid(col.slice(0, 3)); obj.source = obj.source || 'seed'; obj.createdAt = obj.createdAt || '2026-01-01T08:00'; st[col].push(obj); return obj; };
  const userBy = (st, u) => st.users.find(x => x && x.username === u) || null;
  const COLS = ['metricDefinitions', 'reportPeriods', 'reportSnapshots', 'reportMetricValues', 'goldenDatasets', 'buildingShares', 'capitalCalls', 'capitalPayments', 'profitDistributions'];

  function migrateShares(st) {
    st.shareholders.forEach(s => { if (!s) return; if (s.taxCode == null) s.taxCode = ''; if (!s.entityType) s.entityType = 'person'; if (!s.status) s.status = 'active'; if (!s.bankAccount) { const n = (s.name || '').split(' '); s.bankAccount = 'VCB 0071 00' + F.pad(Math.abs(F.hash ? F.hash(s.code || s.name) : (s.code || '').length * 7919) % 1000000, 6); s.bankName = 'Vietcombank – ' + (n.slice(-2).join(' ') || s.name); } });
    if (!st.buildingShares.length && st.capitalCommitments.length) {
      st.capitalCommitments.forEach(c => { if (!c) return; const p = st.projects.find(x => x && x.id === c.projectId); if (!p || !p.buildingId) return; mk(st, 'buildingShares', { buildingId: p.buildingId, shareholderId: c.shareholderId, percentage: Math.round(Number(c.ratio || 0) * 100) / 100, effectiveFrom: c.effectiveDate || p.startDate || '2025-03-01', effectiveTo: '', basis: 'Cam kết vốn dự án ' + p.code, document: '', status: 'active', migratedFrom: c.id, createdAt: (c.effectiveDate || '2025-03-01') + 'T08:00' }); });
    }
    if (!st.capitalCalls.length && st.contributions.length) {
      const groups = {}; st.contributions.filter(c => c && c.kind === 'capital').forEach(c => { const p = st.projects.find(x => x && x.id === c.projectId); if (!p) return; const k = p.buildingId + '|' + c.round; (groups[k] = groups[k] || { p, round: c.round, dueDate: c.dueDate, lines: [] }).lines.push(c); });
      Object.values(groups).forEach(g => { const total = F.sum(g.lines, l => l.amount); const call = mk(st, 'capitalCalls', { code: 'GV-' + String(g.dueDate).slice(0, 7).replace('-', '') + '-' + F.pad(st.capitalCalls.length + 1, 3), buildingId: g.p.buildingId, name: 'Đợt ' + g.round + ' – ' + g.p.name, total, dueDate: g.dueDate, note: 'Chuyển từ đợt góp vốn theo dự án (P3)', shareDate: g.lines[0].createdAt ? g.lines[0].createdAt.slice(0, 10) : g.dueDate, status: g.lines.every(l => l.status === 'paid') ? 'done' : 'open', createdAt: g.lines[0].createdAt || '2025-03-01T08:00' }); g.lines.forEach(l => { const share = st.capitalCommitments.find(c => c && c.shareholderId === l.shareholderId && c.projectId === g.p.id); mk(st, 'capitalPayments', { capitalCallId: call.id, shareholderId: l.shareholderId, percentage: share ? share.ratio : Math.round(l.amount / total * 10000) / 100, required: l.amount, paid: l.paidAmount || 0, paidDate: l.paidDate || null, ref: l.ref || '', note: l.note || '', migratedFrom: l.id, history: l.paidAmount ? [{ at: (l.paidDate || g.dueDate) + 'T10:00', amount: l.paidAmount, date: l.paidDate, ref: l.ref }] : [] }); }); });
    }
  }

  /* ===== Tòa G1 – dữ liệu 06/2026 khớp Golden A ===== */
  function seedG1(st) {
    if (st.buildings.some(b => b && b.code === 'G1')) return;
    const ketoan = userBy(st, 'ketoan') || st.users.find(u => u && u.role === 'accountant'); const admin = userBy(st, 'admin') || st.users.find(u => u && u.role === 'admin'); const vh = userBy(st, 'vanhanh') || st.users.find(u => u && u.role === 'ops');
    const svc = (code) => st.services.find(s => s && s.code === code) || {};
    const ll = mk(st, 'landlords', { code: 'CN-G1', name: 'Bà Trịnh Thị Gấm', type: 'person', taxCode: '', phone: '0918 555 001', email: 'gam.tt@gmail.com', address: 'Hà Nội', bankAccount: 'VCB 0011 00 778899', buildingIds: [], status: 'active', managerId: vh ? vh.id : null, cycleMonths: 1, createdAt: '2025-12-01T08:00' });
    const b = mk(st, 'buildings', { code: 'G1', name: 'Tòa G1', address: '15 Ngõ 68 Cầu Giấy, Hà Nội', district: 'Cầu Giấy', floors: 4, perFloor: 3, prefix: 'G1', managerId: vh ? vh.id : null, landlordId: ll.id, payCycle: 1, payDay: 5, status: 'active', stub: false, roomCount: 12, imageIdx: 5, amenities: ['Thang máy', 'Camera 24/7', 'Máy giặt chung', 'Sạc xe điện'], buildingType: 'G', operatingSince: '2026-01-01', createdAt: '2025-12-15T08:00', note: 'Tòa mẫu golden dataset – Báo cáo tháng 6 (spec §12.23.12)' });
    ll.buildingIds = [b.id];
    mk(st, 'landlordContracts', { code: 'HD-CN-G1-001', landlordId: ll.id, buildingIds: [b.id], start: '2026-01-01', end: '2028-12-31', rent: 48000000, deposit: 96000000, priceHoldMonths: 24, cycleMonths: 1, signedDate: '2025-12-20', status: 'active', managerId: vh ? vh.id : null, type: 'Hợp đồng thuê tòa nhà', hkdStatus: 'registered', pcccStatus: 'ok', buildingTypeCode: 'G', note: 'Trả chủ nhà hàng tháng 48.000.000 – ghi vào Chi phí GV-THUE theo kỳ hạch toán', createdAt: '2025-12-20T08:00' });
    mk(st, 'buildingTypeHistory', { buildingId: b.id, type: 'G', effectiveFrom: '2026-01-01', effectiveTo: '', sourceType: 'landlordContract', reason: 'Ký hiệu G theo HĐ đầu vào', by: null, createdAt: '2026-01-01T08:00' });
    mk(st, 'servicePrices', { serviceId: svc('NUOC').id, scope: 'BUILDING', buildingId: b.id, price: 14000, effectiveFrom: '2026-01-01', effectiveTo: '', status: 'active', note: 'Giá nước riêng tòa G1', createdAt: '2026-01-01T08:00' });
    const emp = st.employees.find(e => e && e.status !== 'resigned' && e.dept === 'vanhanh' && e.userId) || st.employees.find(e => e && e.status !== 'resigned'); if (emp) mk(st, 'buildingAssignments', { employeeId: emp.id, buildingId: b.id, role: 'manager', primary: false, start: '2026-01-01', end: null, status: 'active', orgUnitId: (st.employmentAssignments.find(a => a && a.employeeId === emp.id) || {}).orgUnitId || null, reason: 'Phụ trách tòa G1 từ khi vận hành', note: '', roomScope: '', approvedAt: '2025-12-28T08:00', approvedBy: admin ? admin.id : null, createdAt: '2025-12-28T08:00' });
    const RENT = 3980000; const rooms = []; for (let i = 1; i <= 12; i++) rooms.push(mk(st, 'rooms', { code: 'G1.' + F.pad(Math.ceil(i / 3)) + '.' + F.pad(((i - 1) % 3) + 1), buildingId: b.id, floor: Math.ceil(i / 3), type: i <= 8 ? 'Studio' : 'Phòng đôi', area: i <= 8 ? 25 : 30, price: RENT, physical: 'good', status: 'occupied', managerId: b.managerId, direction: ['Hướng Đông', 'Hướng Nam', 'Hướng Tây'][i % 3], furniture: 'Đầy đủ', defaultServiceIds: [svc('INTERNET').id].filter(Boolean), createdAt: '2025-12-20T08:00' }));
    const NAMES = ['Nguyễn Hải Anh', 'Trần Thu Hà', 'Lê Minh Quân', 'Phạm Ngọc Diệp', 'Vũ Tuấn Kiệt', 'Đỗ Thanh Mai', 'Bùi Đức Long', 'Hoàng Yến Nhi', 'Ngô Bảo Châu', 'Đinh Văn Sơn', 'Lý Thu Trang', 'Mai Quốc Việt', 'Tạ Hồng Nhung', 'Cao Minh Đức', 'Phan Thị Lệ'];
    let tN = st.tenants.length + 1; const tenants = NAMES.map((n, i) => mk(st, 'tenants', { code: 'KH' + F.pad(tN++, 5), name: n, phone: '09' + F.pad(31000000 + i * 1237, 8), zalo: '', email: F.slug(n.split(' ').slice(-1)[0]) + '.g1' + i + '@gmail.com', idNumber: '00120' + F.pad(1000000 + i * 3571, 7), dob: '199' + (i % 9) + '-0' + ((i % 8) + 1) + '-1' + (i % 9), job: 'Nhân viên văn phòng', segment: 'Người đi làm', verified: true, managerId: b.managerId, status: 'active', note: '', createdAt: '2025-12-28T08:00' }));
    if (!tenants[0].email) tenants[0].email = 'haianh.g1@gmail.com';
    let cN = 1; const events = []; const contract = (room, tenant, start, end, o = {}) => { const c = mk(st, 'contracts', Object.assign({ code: 'HD-G1-' + F.pad(cN++, 3), roomId: room.id, buildingId: b.id, tenantId: tenant.id, start, end, listPrice: RENT, price: RENT, deposit: o.deposit != null ? o.deposit : RENT, cycle: 'monthly', payDay: 5, status: 'active', managerId: b.managerId, signedDate: F.addDays(start, -3), note: '', renewedFromId: null, renewedToId: null, contractType: 'new', termNo: 1, activatedAt: start + 'T09:00', depositPaidAt: start, createdAt: F.addDays(start, -3) + 'T09:00' }, o)); mk(st, 'contractServices', { contractId: c.id, serviceId: svc('INTERNET').id, name: 'Internet', unit: 'Tháng', price: 200000, qty: 1, note: 'FPT' }); mk(st, 'contractTenants', { contractId: c.id, tenantId: tenant.id, role: 'primary', name: tenant.name, phone: tenant.phone, idNumber: tenant.idNumber, createdAt: c.createdAt }); mk(st, 'depositLedger', { contractId: c.id, tenantId: tenant.id, buildingId: b.id, roomId: room.id, type: 'RECEIVABLE', amount: c.deposit, date: c.signedDate, refType: 'contract', refId: c.id, note: 'Cọc theo HĐ', createdAt: c.createdAt }); mk(st, 'depositLedger', { contractId: c.id, tenantId: tenant.id, buildingId: b.id, roomId: room.id, type: 'RECEIVED', amount: c.deposit, date: start, refType: 'contract', refId: c.id, note: 'Nhận cọc phòng ' + room.code, createdAt: start + 'T09:00' }); events.push(mk(st, 'contractEvents', { contractId: c.id, type: 'ACTIVATED', date: start, at: start + 'T09:00', by: vh ? vh.id : null, buildingId: b.id, roomId: room.id, tenantId: tenant.id, createdAt: start + 'T09:00' })); return c; };
    const cs = {};
    for (let i = 3; i <= 9; i++) cs[i] = contract(rooms[i - 1], tenants[i - 1], '2026-01-01', '2026-12-31');
    cs[1] = contract(rooms[0], tenants[0], '2026-06-01', '2027-05-31', { deposit: 1900000 }); cs[2] = contract(rooms[1], tenants[1], '2026-06-01', '2027-05-31', { deposit: 1900000 });
    const endEarly = (c, room, tenant, endDate, reason) => { c.status = 'ended'; c.actualEnd = endDate; c.endReason = reason; c.endedAt = endDate + 'T17:00'; events.push(mk(st, 'contractEvents', { contractId: c.id, type: 'EARLY_TERMINATION', date: endDate, at: endDate + 'T17:00', by: vh ? vh.id : null, buildingId: b.id, roomId: room.id, tenantId: tenant.id, reason, plannedEnd: c.end, createdAt: endDate + 'T17:00' })); events.push(mk(st, 'contractEvents', { contractId: c.id, type: 'ENDED', date: endDate, at: endDate + 'T17:30', by: vh ? vh.id : null, buildingId: b.id, roomId: room.id, tenantId: tenant.id, createdAt: endDate + 'T17:30' })); };
    const old10 = contract(rooms[9], tenants[9], '2026-01-01', '2026-12-31'); endEarly(old10, rooms[9], tenants[9], '2026-06-30', 'Khách chuyển công tác');
    const old11 = contract(rooms[10], tenants[10], '2026-01-01', '2026-12-31'); endEarly(old11, rooms[10], tenants[10], '2026-06-30', 'Khách mua nhà');
    const old12 = contract(rooms[11], tenants[11], '2026-01-01', '2026-12-31'); endEarly(old12, rooms[11], tenants[11], '2026-06-20', 'Khách bỏ phòng không báo trước');
    cs[10] = contract(rooms[9], tenants[12], '2026-07-01', '2027-06-30'); cs[11] = contract(rooms[10], tenants[13], '2026-07-01', '2027-06-30'); cs[12] = contract(rooms[11], tenants[14], '2026-08-01', '2027-07-31');
    // Hoàn cọc: phòng 12 giữ lại 1.000.000 (phá HĐ) hoàn 2.980.000 ngày 25/06; phòng 10/11 hoàn đủ tháng 7
    const refund = (c, room, tenant, moveOut, ded, paidDate) => { const rf = mk(st, 'refunds', { code: 'RC' + moveOut.slice(0, 7).replace('-', '') + '-G' + room.code.slice(-2), contractId: c.id, tenantId: tenant.id, roomId: room.id, buildingId: b.id, requestDate: F.addDays(moveOut, 1), moveOutDate: moveOut, deposit: c.deposit, debt: 0, offsetDebt: false, deductionsTotal: ded, refundAmount: c.deposit - ded, status: 'refunded', handlerId: ketoan ? ketoan.id : null, approverRole: 'Kế toán trưởng', rejectReason: '', approvedAt: F.addDays(moveOut, 2) + 'T10:00', approvedBy: ketoan ? ketoan.id : null, paidDate, paidRef: 'CK-G1-' + moveOut.replace(/-/g, '').slice(2), createdAt: F.addDays(moveOut, 1) + 'T09:00' }); if (ded) { mk(st, 'refundDeductions', { refundId: rf.id, group: 'Khác', groupCode: 'KHAC', desc: 'Phạt phá hợp đồng – giữ lại cọc theo quyết toán', amount: ded, evidenceCount: 1, status: 'confirmed', createdAt: rf.createdAt }); mk(st, 'depositLedger', { contractId: c.id, tenantId: tenant.id, buildingId: b.id, roomId: room.id, type: 'DEDUCTED', amount: ded, date: F.addDays(moveOut, 2), refType: 'refund', refId: rf.id, note: 'Giữ lại cọc – quyết toán ' + rf.code, createdAt: F.addDays(moveOut, 2) + 'T10:00' }); } mk(st, 'depositLedger', { contractId: c.id, tenantId: tenant.id, buildingId: b.id, roomId: room.id, type: 'REFUNDED', amount: c.deposit - ded, date: paidDate, refType: 'refund', refId: rf.id, note: 'Hoàn cọc ' + rf.code, createdAt: paidDate + 'T15:00' }); return rf; };
    refund(old12, rooms[11], tenants[11], '2026-06-20', 1000000, '2026-06-25'); refund(old10, rooms[9], tenants[9], '2026-06-30', 0, '2026-07-05'); refund(old11, rooms[10], tenants[10], '2026-07-01', 0, '2026-07-06');
    // Lịch sử trạng thái phòng (Room Status History): phòng 12 trống từ 20/06 → ready 23/06 → thuê lại 01/08
    const hist = (room, from, to, at, reason) => mk(st, 'roomStatusHistory', { roomId: room.id, buildingId: b.id, from, to, at, date: at.slice(0, 10), by: vh ? vh.id : null, byName: vh ? vh.name : 'Hệ thống', reason, refType: null, refId: null, createdAt: at });
    rooms.forEach((r, i) => { const n = i + 1; if (n <= 2) { hist(r, null, 'ready', '2026-01-01T08:00', 'Khởi tạo'); hist(r, 'ready', 'occupied', '2026-06-01T09:00', 'Kích hoạt HĐ ' + cs[n].code); } else if (n === 12) { hist(r, null, 'occupied', '2026-01-01T09:00', 'Kích hoạt HĐ ' + old12.code); hist(r, 'occupied', 'cleaning', '2026-06-20T17:00', 'Khách trả phòng – phá HĐ'); hist(r, 'cleaning', 'ready', '2026-06-23T10:00', 'Nghiệm thu dọn phòng'); hist(r, 'ready', 'occupied', '2026-08-01T09:00', 'Kích hoạt HĐ ' + cs[12].code); } else hist(r, null, 'occupied', '2026-01-01T09:00', 'Kích hoạt HĐ'); });
    // Hóa đơn 06/2026 (golden) + 07..10/2026 (đã thu đủ M1)
    let invN = 1, payN = 1; const invoice = (c, period, lines, issue) => { const inv = mk(st, 'invoices', { code: 'HD-' + period.replace('-', '') + '-G' + F.pad(invN++, 2), contractId: c.id, roomId: c.roomId, buildingId: b.id, tenantId: c.tenantId, period, issueDate: issue, dueDate: period + '-05', docStatus: 'issued', total: 0, adjustment: 0, carriedOver: 0, note: '', createdBy: ketoan ? ketoan.id : null, createdAt: issue + 'T09:00', reminderCount: 0, lastReminderAt: null, accountingNote: '', snapshot: { contractCode: c.code, price: c.price, tenantName: (st.tenants.find(t => t.id === c.tenantId) || {}).name, roomCode: (st.rooms.find(r => r.id === c.roomId) || {}).code } }); lines.forEach((l, k) => mk(st, 'invoiceLines', { invoiceId: inv.id, seq: k + 1, item: l.item, desc: l.desc || l.item, qty: l.qty, unitPrice: l.unitPrice, amount: Math.round(l.qty * l.unitPrice * 1000) / 1000, kind: l.kind, lineType: l.kind === 'rent' ? 'RENT' : 'SERVICE', unit: l.unit || '', serviceId: l.serviceId || null, createdAt: issue + 'T09:00' })); inv.total = F.sum(st.invoiceLines.filter(l => l.invoiceId === inv.id), l => l.amount); const payDate = period + '-05'; const p = mk(st, 'payments', { code: 'PAY-' + period.replace('-', '') + '-G' + F.pad(payN++, 2), tenantId: c.tenantId, roomId: c.roomId, buildingId: b.id, date: payDate, amount: inv.total, method: 'Chuyển khoản', ref: 'FT' + payDate.replace(/-/g, '').slice(2) + 'G' + F.pad(invN, 2), evidence: 'bien_lai.pdf', note: 'Thanh toán ' + F.periodLabel(period).toLowerCase() + ' phòng ' + inv.snapshot.roomCode, status: 'recorded', createdBy: ketoan ? ketoan.id : null, bank: 'Vietcombank', transferContent: 'TT ' + inv.snapshot.roomCode + ' ' + period, createdAt: payDate + 'T09:25' }); mk(st, 'paymentAllocations', { paymentId: p.id, invoiceId: inv.id, amount: inv.total, milestone: 'M1', createdAt: payDate + 'T09:25' }); return inv; };
    const L = (item, qty, unitPrice, kind, code, unit, desc) => ({ item, qty, unitPrice, kind, serviceId: code ? svc(code).id : null, unit, desc });
    const juneRooms = [cs[1], cs[2], cs[3], cs[4], cs[5], cs[6], cs[7], cs[8], cs[9], old10, old11, old12];
    juneRooms.forEach((c, i) => { const n = i + 1; const lines = [L('Tiền phòng', 1, RENT, 'rent', null, 'tháng', 'Tiền thuê phòng tháng 06/2026'), L('Điện', n <= 10 ? 300 : 280, 3500, 'electric', 'DIEN', 'kWh', 'Tiền điện (' + (n <= 10 ? 300 : 280) + ' kWh × 3.500)'), L('Nước', n <= 8 ? 20 : 19, 14000, 'water', 'NUOC', 'm³', 'Tiền nước (' + (n <= 8 ? 20 : 19) + ' m³ × 14.000 – giá tòa G1)')]; if (n <= 8) { lines.push(L('Vệ sinh', 1, 169000, 'service', 'VESINH', 'tháng')); lines.push(L('Thang máy', 1, 161500, 'service', 'THANGMAY', 'tháng')); lines.push(L('Máy giặt', 1, 169000, 'service', 'MAYGIAT', 'tháng')); } if (n === 1) lines.push(L('Mạng', 1, 853333.333, 'service', 'INTERNET', 'tháng', 'Internet tòa – gói 2.560.000/quý ÷ 3')); if (n <= 3) lines.push(L('Sạc xe điện', 1, 150000, 'service', 'SACXE', 'tháng')); invoice(c, '2026-06', lines, '2026-06-01'); });
    ['2026-07', '2026-08', '2026-09', '2026-10'].forEach((period, pi) => { const list = [cs[1], cs[2], cs[3], cs[4], cs[5], cs[6], cs[7], cs[8], cs[9], cs[10], cs[11]].concat(period >= '2026-08' ? [cs[12]] : []); list.forEach((c, i) => { const kwh = 240 + ((i * 7 + pi * 11) % 60), m3 = 17 + ((i + pi) % 5); invoice(c, period, [L('Tiền phòng', 1, RENT, 'rent', null, 'tháng', 'Tiền thuê phòng ' + F.periodLabel(period).toLowerCase()), L('Điện', kwh, 3500, 'electric', 'DIEN', 'kWh', 'Tiền điện (' + kwh + ' kWh × 3.500)'), L('Nước', m3, 14000, 'water', 'NUOC', 'm³', 'Tiền nước (' + m3 + ' m³ × 14.000)'), L('Internet', 1, 200000, 'service', 'INTERNET', 'tháng')], period + '-01'); }); });
    // Chi phí 06/2026 G1 (giá vốn + CPBH) – trực tiếp tòa; văn phòng chung phân bổ tỷ lệ tay 20% về G1
    const cat = (code) => st.expenseGroups.find(g => g && g.code === code) || {};
    const ex = (o) => mk(st, 'expenses', Object.assign({ code: 'CP' + F.pad(st.expenses.length + 1, 4), date: o.docDate, recordDate: o.docDate, accountingPeriod: o.docDate.slice(0, 7), group: cat(o.categoryCode).name || '', recordType: o.buildingId ? 'ops' : 'common', method: 'bank', payMethod: 'bank', evidence: (o.evidence || 'ct_' + o.categoryCode.toLowerCase() + '_202606.pdf'), note: o.note || '', status: o.buildingId ? 'recorded' : 'pending_alloc', createdBy: ketoan ? ketoan.id : null, confirmedBy: ketoan ? ketoan.id : null, dataSource: o.dataSource || 'manual', createdAt: o.docDate + 'T09:00' }, o));
    const direct = (docDate, categoryCode, desc, amount, supplier, extra = {}) => { const e = ex(Object.assign({ docDate, categoryCode, desc, amount, supplier, buildingId: b.id }, extra)); mk(st, 'expenseAllocations', { expenseId: e.id, buildingId: b.id, pct: 100, amount, method: 'DIRECT', period: '2026-06', confirmedBy: ketoan ? ketoan.id : null, confirmedAt: docDate + 'T09:00', createdAt: docDate + 'T09:00' }); return e; };
    direct('2026-06-03', 'GV-THUE', 'Tiền thuê nhà tháng 06/2026 – Tòa G1 (HĐ HD-CN-G1-001)', 48000000, 'Bà Trịnh Thị Gấm', { evidence: 'unc_thue_nha_g1_202606.pdf' });
    direct('2026-06-12', 'GV-TB', 'Mua thêm bình nóng lạnh phòng G1.04.03', 500000, 'Điện máy Xanh');
    direct('2026-06-28', 'GV-DIEN', 'Tiền điện EVN tháng 06/2026 – công tơ tổng G1', 17258594, 'EVN Hà Nội', { dataSource: 'import', evidence: 'hoa_don_evn_g1_202606.pdf' });
    direct('2026-06-28', 'GV-NUOC', 'Tiền nước sạch tháng 06/2026 – G1', 300000, 'Nước sạch Hà Nội', { dataSource: 'import' });
    direct('2026-06-30', 'GV-RAC', 'Phí thu gom rác tháng 06/2026 – G1', 300000, 'Môi trường đô thị', { dataSource: 'import' });
    direct('2026-06-15', 'BH-MKT', 'Chạy quảng cáo Facebook phòng trống G1 tháng 6', 1500000, 'Meta Ads');
    direct('2026-06-05', 'BH-HH', 'Hoa hồng chốt phòng G1.01.01 & G1.01.02 (HĐ 01/06)', 1000000, 'Sale Nguyễn Văn Sale', { commission: { saleName: 'Nguyễn Văn Sale', roomCodes: 'G1.01.01, G1.01.02', paidDate: '2026-06-05' } });
    direct('2026-06-22', 'VH-SC', 'Sửa khóa cửa & vòi nước phòng G1.04.03 sau khi khách trả', 500000, 'Thợ Minh Tâm');
    direct('2026-06-30', 'VH-KHAC', 'Chi phí khác tháng 6 – vật tư vệ sinh, bóng đèn hành lang', 276125.04, 'Siêu thị Vinmart');
    const office = ex({ docDate: '2026-06-30', categoryCode: 'VH-VP', desc: 'Thuê & dịch vụ văn phòng tháng 06/2026 (chung – phân bổ tỷ lệ tay)', amount: 6000000, supplier: 'Toà nhà văn phòng ABC', buildingId: null, status: 'allocated', allocation: { method: 'MANUAL_RATIO' } });
    const others = st.buildings.filter(x => x && !x.stub && x.id !== b.id && x.status !== 'inactive').slice(0, 4); const ratios = [[b.id, 20]].concat(others.map(x => [x.id, Math.round(80 / others.length * 100) / 100]));
    ratios.forEach(([bid, pct], i) => mk(st, 'expenseAllocations', { expenseId: office.id, buildingId: bid, pct, amount: Math.round(6000000 * pct / 100 * 100) / 100, basis: 'Tỷ lệ nhập tay', method: 'MANUAL_RATIO', period: '2026-06', confirmedBy: ketoan ? ketoan.id : null, confirmedAt: '2026-06-30T10:00', createdAt: '2026-06-30T10:00' }));
    // Cổ đông thứ 9 + cổ phần G1 = 100% từ 01/01/2026; đổi tỷ lệ từ 01/09/2026 (An 7 → 5, Lan 5 → 7)
    let lan = st.shareholders.find(s => s && s.name === 'Bùi Thị Lan'); if (!lan) lan = mk(st, 'shareholders', { code: 'CD-' + F.pad(st.shareholders.length + 1, 3), name: 'Bùi Thị Lan', email: 'lan.bt@gmail.com', phone: '0912 333 444', idNumber: '079088001234', taxCode: '', entityType: 'person', bankAccount: 'VCB 0071 00 445566', bankName: 'Vietcombank – Bùi Thị Lan', userId: null, status: 'active', note: 'Cổ đông tòa G1', createdAt: '2025-12-01T08:00' });
    const shs = st.shareholders.filter(s => s && s.id !== lan.id).slice(0, 8); const PCT = [20, 15, 15, 10, 10, 10, 8, 7];
    const share = (sh, pct, from, to, o = {}) => mk(st, 'buildingShares', Object.assign({ buildingId: b.id, shareholderId: sh.id, percentage: pct, effectiveFrom: from, effectiveTo: to || '', basis: 'Biên bản góp vốn G1 12/2025', document: 'BB-GV-G1-2025.pdf', status: 'active', createdAt: from + 'T08:00' }, o));
    const an = shs.find(s => s.name === 'Ngô Văn An') || shs[7];
    shs.forEach((sh, i) => { if (sh.id === an.id) return; share(sh, PCT[i], '2026-01-01', ''); });
    share(an, 7, '2026-01-01', '2026-08-31'); share(an, 5, '2026-09-01', '', { basis: 'Chuyển nhượng 2% cho Bùi Thị Lan', document: 'HD-CN-G1-0901.pdf' });
    share(lan, 5, '2026-01-01', '2026-08-31'); share(lan, 7, '2026-09-01', '', { basis: 'Nhận chuyển nhượng 2% từ Ngô Văn An', document: 'HD-CN-G1-0901.pdf' });
    // Góp vốn G1: đợt 1 (1,8 tỷ) đã góp đủ 12/2025; đợt 2 (90 triệu bổ sung thiết bị) hạn +7 ngày, mới góp 4 người
    const T = F.today(); const shares0 = st.buildingShares.filter(s => s.buildingId === b.id && s.effectiveFrom === '2026-01-01');
    const call = (code, name, total, dueDate, shareDate, paidFn, createdAt) => { const c = mk(st, 'capitalCalls', { code, buildingId: b.id, name, total, dueDate, note: '', shareDate, status: 'open', createdAt }); let acc = 0; shares0.forEach((s, i) => { const required = i === shares0.length - 1 ? total - acc : Math.round(total * s.percentage / 100 / 1000) * 1000; acc += required; const paid = paidFn(i, required); mk(st, 'capitalPayments', { capitalCallId: c.id, shareholderId: s.shareholderId, percentage: s.percentage, required, paid: paid.amount, paidDate: paid.date, ref: paid.ref, note: '', history: paid.amount ? [{ at: paid.date + 'T10:00', amount: paid.amount, date: paid.date, ref: paid.ref }] : [], createdAt }); }); if (st.capitalPayments.filter(l => l.capitalCallId === c.id).every(l => l.paid >= l.required)) c.status = 'done'; return c; };
    call('GV-202512-G01', 'Đợt 1 – Góp vốn ban đầu Tòa G1', 1800000000, '2025-12-15', '2026-01-01', (i, req) => ({ amount: req, date: '2025-12-' + F.pad(8 + i), ref: 'UNC-G1-' + F.pad(101 + i) }), '2025-12-01T08:00');
    call('GV-' + F.addDays(T, 7).slice(0, 7).replace('-', '') + '-G02', 'Đợt 2 – Bổ sung thiết bị & PCCC G1', 90000000, F.addDays(T, 7), T, (i, req) => i < 4 ? { amount: req, date: F.addDays(T, -3 + i), ref: 'UNC-G1-' + F.pad(201 + i) } : { amount: 0, date: null, ref: '' }, F.addDays(T, -10) + 'T08:00');
    const cdUser = userBy(st, 'codong'); if (cdUser && cdUser.buildingIds && !cdUser.buildingIds.includes(b.id)) cdUser.buildingIds.push(b.id);
  }

  function seedGolden(st) {
    if (st.goldenDatasets.length) return;
    mk(st, 'goldenDatasets', { code: 'GOLDEN-A-G1-202606', name: 'Golden Report A – G1 tháng 06/2026', reportType: 'A', period: '2026-06', buildingCode: 'G1', sourceSheet: 'Báo cáo tháng 6 (workbook nguồn)', shareholderCount: 9, shareTotal: 100, note: 'Golden test check từng line và share allocation, không chỉ số tổng (§12.23.12)', values: { TOTAL_REVENUE: 79912000, NEW_DEPOSIT: 3800000, FORFEITED_DEPOSIT: 1000000, NEW_ROOM_COUNT: 2, EARLY_TERMINATION_COUNT: 3, VACANT_ROOM_COUNT: 1, RENT_REVENUE: 47760000, ELECTRIC_REVENUE: 12460000, WATER_REVENUE: 3304000, CLEANING_REVENUE: 1352000, INTERNET_REVENUE: 853333.333, ELECTRIC_VEHICLE_REVENUE: 450000, ELEVATOR_REVENUE: 1292000, WASHING_REVENUE: 1352000, SERVICE_REVENUE: 21063333.333, HEAD_LEASE_COST: 48000000, EQUIPMENT_PURCHASE_COST: 500000, ELECTRIC_INPUT_COST: 17258594, WATER_INPUT_COST: 300000, INTERNET_INPUT_COST: 0, GARBAGE_COST: 300000, COGS: 66358594, OPERATING_SELLING_COST: 10476125.04, TOTAL_COST: 76834719.04, GROSS_PROFIT: 13553406, NET_PROFIT: 3077280.96, NET_MARGIN: 3.85 }, createdAt: '2026-07-01T08:00' });
    mk(st, 'goldenDatasets', { code: 'GOLDEN-B-202608', name: 'Golden Report B – Tháng 08/2026 toàn hệ thống (T/S/G)', reportType: 'B', period: '2026-08', buildingCode: '', sourceSheet: 'Báo cáo kinh doanh Tháng 8 (workbook nguồn)', note: 'Chỉ lưu giá trị kỳ vọng – dữ liệu mockup không tái lập nguồn toàn hệ thống → SOURCE_DATA_DIFFERENCE có ghi chú', values: { TOTAL_REVENUE: { total: 7036256236, T: 2527702129, S: 3551745507, G: 956808600 }, NEW_DEPOSIT: 371850000, FORFEITED_DEPOSIT: 18400000, REFUND_AMOUNT: 104968774, EARLY_TERMINATION_COUNT: 39, NEW_ROOM_COUNT: 95, VACANT_ROOM_COUNT: 11, RENT_REVENUE: 5021511225.80645, SERVICE_REVENUE: 1745169586.02, HEAD_LEASE_COST: 4086483333.33, EQUIPMENT_PURCHASE_COST: 35380000, ELECTRIC_INPUT_COST: 935197739, WATER_INPUT_COST: 202388331.67, INTERNET_INPUT_COST: 33982034.58, GARBAGE_COST: 20593333.33, ENVIRONMENT_COST: 1904000, ELEVATOR_MAINT_COST: 1000000, COGS: 5316928771.92, OPERATING_SELLING_COST: 696928495.37, TOTAL_COST: 6013857267.28, GROSS_PROFIT: 1719327464.08, NET_PROFIT: 1022398968.72, NET_MARGIN: 14.53 }, createdAt: '2026-09-01T08:00' });
  }

  seed.migrateW5 = (st) => {
    COLS.forEach(c => { if (!Array.isArray(st[c])) st[c] = []; });
    if (st.meta.w5Migrated) return;
    st.meta.w5Migrated = true; st.meta.w5ScenarioDone = false;
    migrateShares(st); seedG1(st); seedGolden(st);
  };
  /* Lương G1 06/2026 (bảng lương đã khóa + Payroll Cost Allocation 6.000.000 về G1) – gọi từ X.ensureW5Scenario sau kịch bản W4 */
  seed.ensureG1Payroll = (st) => {
    const b = st.buildings.find(x => x && x.code === 'G1'); if (!b) return; if (st.payrolls.some(p => p && p.period === '2026-06' && p.g1)) return;
    const ketoan = userBy(st, 'ketoan') || st.users.find(u => u && u.role === 'accountant'); const hr = userBy(st, 'nhansu') || ketoan;
    const emps = st.employees.filter(e => e && e.status !== 'resigned').slice(0, 2); if (!emps.length) return;
    const p = mk(st, 'payrolls', { code: 'BL-2026-06', period: '2026-06', status: 'locked', w4: true, g1: true, lines: [], total: 6000000, createdBy: hr ? hr.id : null, submittedAt: '2026-07-01T10:00', approvedBy: ketoan ? ketoan.id : null, approvedAt: '2026-07-02T15:00', lockedAt: '2026-07-03T09:00', lockedBy: ketoan ? ketoan.id : null, expenseIds: [], note: 'Kỳ 06/2026 – bảng lương đã khóa (phần phân bổ tòa G1 tái lập golden)', history: [{ at: '2026-07-03T09:00', by: ketoan ? ketoan.id : null, type: 'lock', text: 'Khóa bảng lương' }], createdAt: '2026-07-01T09:00' });
    const amounts = [3500000, 2500000];
    emps.forEach((e, i) => { const r = mk(st, 'payrollResults', { payrollId: p.id, period: '2026-06', employeeId: e.id, base: amounts[i], lunch: 0, fuel: 0, leadAllowance: 0, support: 0, perfTotal: 0, buildings: 1, rooms: 12, adjustments: [], adjustmentTotal: 0, deductions: 0, deductionTotal: 0, net: amounts[i], createdAt: '2026-07-01T09:00' }); mk(st, 'payrollCostAllocations', { payrollId: p.id, payrollResultId: r.id, period: '2026-06', employeeId: e.id, buildingId: b.id, amount: amounts[i], method: 'DIRECT_SNAPSHOT', ruleVersionId: null, createdAt: '2026-07-03T09:00' }); mk(st, 'salaryPayments', { code: 'CL-202606-G' + (i + 1), payrollId: p.id, period: '2026-06', employeeId: e.id, amountDue: amounts[i], amountPaid: amounts[i], status: 'paid', bankAccount: null, payments: [{ amount: amounts[i], date: '2026-07-05', method: 'Chuyển khoản', ref: 'UNC-L0626-' + (i + 1), by: ketoan ? ketoan.id : null }], note: '', createdAt: '2026-07-05T10:00' }); });
  };
})(window.TH);
