/* Seed Phase 2 – chạy cuối seed.run và khi migrate state cũ. Chỉ THÊM record P2 (leads, viewings, deals, incidents, schedules, jobs, đợt Zalo hero…),
   không đổi số liệu P1 (không sinh payments/invoices mới). Deterministic (rng riêng). Idempotent qua meta.p2Seeded. */
(function (TH) {
  const F = TH.f, seed = TH.seed; const H = seed.helpers;
  const T = F.DEMO_TODAY;
  const mk = (st, col, obj) => { obj.id = obj.id || F.uid(col.slice(0, 3)); obj.source = obj.source || 'seed'; obj.createdAt = obj.createdAt || '2024-10-01T08:00'; st[col].push(obj); return obj; };
  const byName = (st, col, name) => st[col].find(x => x && x.name === name);
  const userBy = (st, username) => st.users.find(u => u && u.username === username) || st.users[0];
  const roomByCode = (st, code) => st.rooms.find(r => r && r.code === code);

  /* ---------- Tài khoản P2 ---------- */
  function addUsersP2(st) {
    st.users.forEach(u => { if (u && u.role === 'tech') u.role = 'kythuat'; });
    const add = (username, name, email, phone, role, scope, extra = {}) => { if (st.users.some(u => u && u.username === username)) return; st.users.push(Object.assign({ id: F.uid('usr'), source: 'seed', createdAt: '2024-09-01T08:00', username, name, email, phone, role, scope, status: 'active', lastLogin: '2024-10-22T09:00', effectiveDate: '2024-09-01', note: 'Tài khoản demo Phase 2', commissionRate: 10 }, extra)); };
    add('sale', 'Nguyễn Thị Hương', 'sale@timohouse.vn', '0909 123 456', 'sale', 'Khu vực TP.HCM', { note: 'Tài khoản demo Phase 2 – Sale (Chuyên viên kinh doanh)' });
    add('kythuat', 'Trần Minh Đức', 'kythuat@timohouse.vn', '0909 234 567', 'kythuat', 'Tòa Sunrise, Tòa Moonlight', { note: 'Tài khoản demo Phase 2 – Kỹ thuật' });
    add('lthuong', 'Lê Thị Hương', 'huonglt@timohouse.vn', '0925 111 222', 'sale', 'Khu vực Hà Nội');
    add('ntquynh', 'Ngô Thị Quỳnh', 'quynhnt@timohouse.vn', '0926 222 333', 'sale', 'Khu vực TP.HCM');
    add('nvhung', 'Nguyễn Văn Hùng', 'hungnv@timohouse.vn', '0927 333 444', 'sale', 'Khu vực TP.HCM');
    add('pqminh', 'Phạm Quang Minh', 'minhpq@timohouse.vn', '0928 444 555', 'sale', 'Khu vực Hà Nội');
  }
  /* ---------- Danh mục P2 (giữ khi Xóa trắng) ---------- */
  seed.catalogP2 = (st) => {
    if (!st.leadSources.length) [['FB', 'Facebook', 'share'], ['ZL', 'Zalo', 'message'], ['GG', 'Google Ads', 'globe'], ['TT', 'TikTok', 'play'], ['WEB', 'Website', 'globe'], ['REF', 'Giới thiệu', 'users'], ['FLY', 'Tờ rơi', 'file-text'], ['POST', 'Đăng tin', 'megaphone']].forEach(([code, name, icon]) => mk(st, 'leadSources', { code, name, icon, status: 'active' }));
    if (!st.vendors.length) [['Thang Máy Việt', 'Thang máy', '028 3999 1234'], ['HVAC Pro', 'Điều hòa / Máy bơm', '028 3888 5678'], ['CleanTech', 'Vệ sinh / Máy giặt chung', '028 3777 9012'], ['PCCC An Toàn', 'PCCC', '028 3666 3456'], ['AquaCare', 'Máy lọc nước', '028 3555 7890']].forEach(([name, field, contact]) => mk(st, 'vendors', { name, field, contact, status: 'active' }));
    if (!st.periods.length) { mk(st, 'periods', { period: '2024-09', status: 'locked', checklist: { revenue: true, expenses: true, debt: true, bank: true, review: true, submit: true }, lockedAt: '2024-10-05T17:30', lockedBy: userBy(st, 'ketoan').id, snapshot: null }); mk(st, 'periods', { period: '2024-10', status: 'open', checklist: { revenue: true, expenses: true, debt: true, bank: true, review: false, submit: false }, lockedAt: null, lockedBy: null, snapshot: null }); }
    // Sự kiện Zalo P2 (ẩn khi P2 tắt – zalo.js lọc theo phase)
    const tmk = (col, o) => mk(st, col, o);
    if (!st.zaloTemplates.some(t => t.eventKey === 'viewing_reminder')) {
      const t1 = tmk('zaloTemplates', { code: 'TM_LICH_XEM_001', name: 'Nhắc lịch xem phòng', eventKey: 'viewing_reminder', body: '📅 Xin chào anh/chị {ten_khach},\nTimoHouse nhắc lịch xem phòng {so_phong} – {toa_nha} vào {ngay_den_han}.\nNhân viên phụ trách sẽ đón anh/chị tại sảnh lễ tân. Cảm ơn anh/chị!', phase: 2 });
      const t2 = tmk('zaloTemplates', { code: 'TM_BAO_DUONG_001', name: 'Thông báo bảo dưỡng định kỳ', eventKey: 'maintenance_due', body: '🔧 Kính gửi cư dân {toa_nha},\nBan quản lý sẽ bảo dưỡng {noi_dung} vào {ngay_den_han}. Mong cư dân thông cảm.\nTrân trọng, TimoHouse.', phase: 2 });
      tmk('zaloEvents', { key: 'viewing_reminder', name: 'Nhắc lịch xem phòng', desc: 'Nhắc khách tiềm năng trước giờ hẹn xem phòng', enabled: true, condition: 'Lịch xem phòng ở trạng thái Đã lên lịch', buildingId: '', offsetDays: 1, offsetDir: 'before', templateId: t1.id, channel: 'Zalo (OA TimoHouse)', fallback: 'Không sử dụng', recipient: 'Khách tiềm năng (lead)', note: '', phase: 2 });
      tmk('zaloEvents', { key: 'maintenance_due', name: 'Bảo dưỡng định kỳ', desc: 'Thông báo cư dân trước ngày bảo dưỡng thiết bị', enabled: false, condition: 'Lịch bảo dưỡng sắp đến hạn trong 7 ngày', buildingId: '', offsetDays: 2, offsetDir: 'before', templateId: t2.id, channel: 'Zalo (OA TimoHouse)', fallback: 'Không sử dụng', recipient: 'Khách thuê (người đại diện hợp đồng)', note: '', phase: 2 });
    }
    st.meta.zaloPolicy = st.meta.zaloPolicy || { maxRetry: 3, gapMinutes: 15, retryCodes: ['403', '408'], fallbackSms: false };
    st.meta.reportPrefs = st.meta.reportPrefs || { favorites: ['occupancy', 'cashflow', 'debt-by-building', 'operating-result', 'sales-performance', 'refunds', 'expense-by-building', 'roi'], recent: [['cashflow', '2024-10-28T07:30'], ['occupancy', '2024-10-28T04:10'], ['debt-by-building', '2024-10-27T09:00'], ['sales-performance', '2024-10-26T15:20'], ['expense-by-building', '2024-10-25T10:00'], ['room-status', '2024-10-24T09:30'], ['maintenance', '2024-10-23T11:00'], ['leads-funnel', '2024-10-22T16:00'], ['refunds', '2024-10-21T09:00'], ['collection-daily', '2024-10-20T09:00'], ['operating-result', '2024-10-19T14:00'], ['customer-segment', '2024-10-18T10:00']] };
  };

  /* ---------- Seed nghiệp vụ P2 ---------- */
  seed.phase2 = (st) => {
    if (st.meta.p2Seeded) return st;
    addUsersP2(st); seed.catalogP2(st);
    const r = H.rng(20241104); const pick = (a) => a[Math.floor(r() * a.length)]; const rint = (a, b) => a + Math.floor(r() * (b - a + 1));
    const name = () => pick(H.HO) + ' ' + pick(H.DEM) + ' ' + pick(H.TEN); const phone = () => '09' + F.pad(rint(10, 99)) + ' ' + F.pad(rint(0, 999), 3) + ' ' + F.pad(rint(0, 999), 3);
    const U = (u) => userBy(st, u).id; const src = F.by(st.leadSources, 'code'); const S = (c) => src[c] ? src[c][0].id : st.leadSources[0].id;
    const B = {}; st.buildings.forEach(b => B[b.name] = b); const bId = (n) => (B[n] || st.buildings[0]).id;
    const hero5 = st.buildings.filter(b => !b.stub).slice(0, 5);
    const SALES = ['sale', 'lthuong', 'ttmai', 'dqbao', 'lgphuc', 'ntquynh', 'nvhung', 'pqminh'].map(U);
    const TECH = ['kythuat', 'lvthanh', 'pvquan', 'cxson'].map(U); const OPS = ['vanhanh', 'lequanghuy', 'hnkhanh', 'tranminhduc', 'pttrang', 'dvnam', 'dtmy'].map(U);
    const ROOM_TYPES = ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn'];
    const readyRooms = st.rooms.filter(x => x.status === 'ready').sort((a, b) => a.code.localeCompare(b.code));
    const pickReady = (bName) => { const rs = readyRooms.filter(x => !bName || x.buildingId === bId(bName)); return rs.length ? rs[rint(0, rs.length - 1)] : readyRooms[0]; };

    /* ----- Lead ----- */
    let ldN = 1; const leads = [];
    const addLead = (o) => { const created = o.createdAt || ('2024-10-' + F.pad(rint(1, 27)) + 'T' + F.pad(rint(8, 18)) + ':' + F.pad(rint(0, 59))); const l = mk(st, 'leads', Object.assign({ code: 'LD-2024-' + F.pad(ldN++, 3), name: name(), phone: phone(), email: '', sourceId: S(pick(['FB', 'ZL', 'GG', 'TT', 'WEB', 'REF', 'FLY', 'POST'])), channel: pick(['Inbox Facebook', 'Zalo OA', 'Form website', 'Gọi hotline', 'Giới thiệu']), roomType: pick(ROOM_TYPES), people: rint(1, 3), budgetMin: rint(5, 10) * 1000000, budgetMax: 0, buildingIds: [pick(hero5).id], moveInDate: F.addDays(T, rint(3, 40)), saleId: pick(SALES), status: 'new', temp: pick(['hot', 'warm', 'warm', 'cold']), note: '', lostReason: '', tenantId: null, createdAt: created, updatedAt: created }, o)); if (!l.budgetMax) l.budgetMax = l.budgetMin + rint(3, 5) * 1000000; if (!l.email) l.email = F.slug(l.name.split(' ').slice(-1)[0]) + '.' + F.slug(l.name.split(' ')[0]) + '@gmail.com'; leads.push(l); return l; };
    const act = (l, type, note, at, by, extra = {}) => mk(st, 'leadActivities', Object.assign({ leadId: l.id, type, note, at: at || l.updatedAt, by: by || l.saleId }, extra));
    const KB = { // [tên, sđt, nguồn, tòa, ngân sách từ, đến, ngày, sale, nhiệt độ]
      new: [['Nguyễn Thị Mai', '0901 234 568', 'FB', 'Tòa Sunrise', 8, 12, '21', 'dqbao', 'hot'], ['Trần Văn Nam', '0902 345 679', 'WEB', 'Tòa Moonlight', 5, 8, '21', 'lgphuc', 'warm'], ['Lê Thu Hà', '0903 456 780', 'REF', 'Tòa Central', 7, 10, '20', 'nvhung', 'warm'], ['Phạm Thảo Vy', '0904 567 891', 'ZL', 'Tòa Riverside', 6, 9, '20', 'sale', 'hot'], ['Đặng Quốc Huy', '0932 111 223', 'GG', 'Tòa Garden', 5, 7, '19', 'ttmai', 'warm']],
      contacted: [['Hoàng Nam Khánh', '0904 567 892', 'ZL', 'Tòa Riverside', 6, 9, '20', 'sale', 'warm'], ['Vũ Thị Mai', '0905 678 902', 'TT', 'Tòa Sunrise', 9, 14, '19', 'ttmai', 'warm'], ['Ngô Xuân Tùng', '0906 789 013', 'WEB', 'Tòa Garden', 5, 7, '19', 'dqbao', 'cold'], ['Võ Hoàng Long', '0902 345 680', 'FB', 'Tòa Moonlight', 7, 11, '18', 'lthuong', 'hot']],
      viewing: [['Phạm Minh Đức', '0907 890 124', 'GG', 'Tòa Sunrise', 10, 15, '18', 'nvhung', 'hot'], ['Lê Quang Huy', '0908 901 235', 'FB', 'Tòa Moonlight', 6, 10, '18', 'pqminh', 'warm'], ['Đỗ Thảo Vy', '0909 012 346', 'REF', 'Tòa Central', 5, 12, '17', 'lthuong', 'warm'], ['Lê Tuấn Anh', '0903 456 790', 'ZL', 'Tòa Riverside', 8, 12, '17', 'sale', 'warm']],
      considering: [['Trần Minh Đức', '0901 234 567', 'WEB', 'Tòa Sunrise', 8, 12, '12', 'sale', 'warm'], ['Nguyễn Minh Anh', '0910 123 457', 'ZL', 'Tòa Riverside', 7, 11, '16', 'sale', 'warm'], ['Trần Thị Hương', '0911 234 568', 'WEB', 'Tòa Garden', 5, 8, '15', 'nvhung', 'cold'], ['Bùi Anh Tuấn', '0912 345 679', 'FB', 'Tòa Moonlight', 9, 13, '14', 'pqminh', 'warm']],
      held: [['Phan Thị Lan', '0913 456 790', 'TT', 'Tòa Sunrise', 10, 15, '21', 'dqbao', 'hot'], ['Lê Văn Thành', '0914 567 891', 'GG', 'Tòa Central', 6, 9, '11', 'lthuong', 'warm'], ['Nguyễn Thị Quỳnh', '0915 678 902', 'REF', 'Tòa Riverside', 8, 12, '10', 'nvhung', 'warm']],
      won: [['Hoàng Văn Long', '0918 901 235', 'FB', 'Tòa Central', 6.5, 9.5, '02', 'lthuong', 'hot'], ['Nguyễn Thị Hương', '0917 890 124', 'ZL', 'Tòa Moonlight', 7, 11, '05', 'nvhung', 'hot']],
    };
    const COUNT = { new: 8, contacted: 12, viewing: 10, considering: 8, held: 6, won: 4 };
    const board = {};
    Object.entries(COUNT).forEach(([status, n]) => { board[status] = []; for (let i = 0; i < n; i++) { const h = KB[status][i]; const l = addLead(h ? { name: h[0], phone: h[1], sourceId: S(h[2]), buildingIds: [bId(h[3])], budgetMin: h[4] * 1000000, budgetMax: h[5] * 1000000, createdAt: '2024-10-' + h[6] + 'T' + F.pad(rint(8, 17)) + ':' + F.pad(rint(0, 59)), saleId: U(h[7]), temp: h[8], status } : { status }); board[status].push(l); } });
    // Hero LD-2024-081: Trần Minh Đức (đang cân nhắc) – khớp PNG 04/03
    const hero = board.considering[0]; hero.code = 'LD-2024-081'; hero.email = 'duc.tm@gmail.com'; hero.channel = 'Google Ads'; hero.roomType = 'Căn hộ 1PN'; hero.people = 2; hero.buildingIds = [bId('Tòa Sunrise'), bId('Tòa Moonlight')]; hero.moveInDate = '2024-11-05'; hero.note = 'Khách đang tìm căn hộ để ở, dự kiến chuyển vào đầu tháng 11. Ưu tiên căn sáng, ít ồn, có thang máy. Có thể đi xem trong tuần này.'; hero.createdAt = '2024-10-12T14:30'; hero.updatedAt = '2024-10-18T09:30'; hero.area = 'Tất cả khu vực'; hero.otherReq = 'Tầng cao, view thoáng, gần thang máy'; hero.depositAbility = 'Có thể cọc ngay nếu phù hợp'; hero.termMonths = 12;
    const p1Duc = st.tenants.find(t => t.name === 'Trần Minh Đức' && t.code === 'KH00123'); if (p1Duc) hero.tenantId = null; // chỉ liên kết khi chốt thuê (theo SĐT)
    act(hero, 'create', 'Nguyễn Thị Hương tạo lead từ nguồn Website', '2024-10-12T14:30', U('sale'));
    act(hero, 'call', 'Gọi điện tư vấn, giới thiệu một số căn phù hợp. Khách quan tâm, hẹn gửi thêm thông tin.', '2024-10-16T09:15', U('sale'), { result: 'interested' });
    act(hero, 'zalo', 'Gửi hình ảnh và bảng giá các căn 1PN tại Sunrise', '2024-10-18T09:30', U('sale'));
    act(hero, 'viewing', 'Đặt lịch xem phòng tòa Sunrise vào ' + F.date(F.addDays(T, 1)) + ' 10:00', '2024-10-18T09:30', U('sale'));
    act(hero, 'note', 'Khách rất quan tâm căn 1PN Sunrise, hẹn đi xem thứ 7. Cần chuẩn bị thông tin chi tiết và hình ảnh thực tế.', '2024-10-18T10:15', U('sale'));
    act(hero, 'note', 'Khách hỏi thêm về phí dịch vụ, gửi bảng giá qua Zalo.', '2024-10-17T16:20', U('kythuat'));
    act(hero, 'note', 'Khách muốn xem thêm các căn ở tòa Moonlight. Đang so sánh với 2 dự án khác.', '2024-10-16T09:10', U('sale'));
    // Hoạt động cho các lead trên bảng
    leads.forEach(l => { if (l === hero) return; act(l, 'create', 'Tạo lead từ nguồn ' + (src[Object.keys(src).find(k => src[k][0].id === l.sourceId)] || [{ name: '' }])[0].name, l.createdAt); if (l.status !== 'new') act(l, 'call', pick(['Gọi tư vấn, khách quan tâm', 'Khách hỏi giá và dịch vụ', 'Hẹn gửi thêm hình ảnh phòng', 'Khách cân nhắc thêm với gia đình']), F.addDays(l.createdAt.slice(0, 10), 1) + 'T10:00', l.saleId, { result: 'interested' }); });
    // Lead đã mất (62) + lead chốt thuê cũ (gắn giao dịch) – để KPI tháng = 124 lead mới, funnel giảm dần
    for (let i = 0; i < 62; i++) { const l = addLead({ status: 'lost', lostReason: pick(['Không liên lạc được', 'Đã thuê nơi khác', 'Ngân sách không phù hợp', 'Hoãn kế hoạch chuyển'], 0), temp: 'cold', updatedAt: '2024-10-' + F.pad(rint(5, 27)) + 'T15:00' }); act(l, 'create', 'Tạo lead', l.createdAt); if (i < 24) act(l, 'call', 'Gọi tư vấn', l.createdAt, l.saleId); if (i < 16) act(l, 'viewing', 'Đã xem phòng', l.createdAt); act(l, 'lost', l.lostReason, l.updatedAt); }

    /* ----- Lịch xem phòng (38 trong tháng 10) ----- */
    let lxN = 1; const viewings = [];
    const addViewing = (l, room, date, time, o = {}) => { const v = mk(st, 'viewings', Object.assign({ code: 'LX-202410-' + F.pad(lxN++, 3), leadId: l.id, roomId: room.id, buildingId: room.buildingId, date, time, saleId: l.saleId, remind: 'Gửi Zalo + Email', place: (st.buildings.find(b => b.id === room.buildingId) || {}).name + ' - Sảnh lễ tân', note: '', status: 'scheduled', result: '', resultNote: '', createdAt: F.addDays(date, -2) + 'T09:00' }, o)); viewings.push(v); return v; };
    const hist = [['B.05.01', '2024-10-15', '14:00', 'done', 'considering', 'Khách thích, đang cân nhắc'], ['A.16.08', '2024-10-10', '10:00', 'done', 'considering', 'Khách thấy giá cao'], ['C.08.02', '2024-10-05', '16:00', 'cancelled', '', 'Khách bận đột xuất']];
    hist.forEach(([code, d, t, s, res, nt]) => { const room = roomByCode(st, code) || pickReady(); addViewing(hero, room, d, t, { status: s, result: res, resultNote: nt, saleId: pick(SALES) }); });
    addViewing(hero, pickReady('Tòa Sunrise'), F.addDays(T, 1), '10:00', { note: 'Khách quan tâm view thoáng, ưu tiên tầng cao. Dẫn xem thêm 1-2 phòng tương tự.', saleId: U('sale'), confirmed: true });
    board.viewing.forEach((l, i) => addViewing(l, pickReady(), i < 5 ? T : F.addDays(T, rint(1, 6)), ['09:00', '10:30', '14:00', '15:30', '16:00'][i % 5], { confirmed: i % 3 !== 2 }));
    board.considering.slice(1).concat(board.held, board.won).forEach(l => addViewing(l, pickReady(), '2024-10-' + F.pad(rint(3, 24)), pick(['09:00', '10:00', '14:00', '16:00']), { status: 'done', result: pick(['interested', 'considering']), resultNote: pick(['Khách hài lòng, sẽ phản hồi sớm', 'Khách muốn so sánh thêm', 'Khách hỏi thêm về nội thất']) }));
    const lostLeads = leads.filter(l => l.status === 'lost'); let vi = 0;
    while (viewings.length < 38) { const l = lostLeads[vi++ % lostLeads.length]; addViewing(l, pickReady(), '2024-10-' + F.pad(rint(2, 26)), pick(['09:00', '11:00', '15:00']), { status: pick(['done', 'done', 'cancelled', 'no_show']), result: 'declined', resultNote: 'Khách không phù hợp' }); }

    /* ----- Giữ chỗ: nâng cấp hold P1 + gắn 6 lead cột Giữ chỗ ----- */
    let gcN = 1;
    st.holds.forEach(h => { if (h.code) return; h.code = 'GC-202410-' + F.pad(gcN++, 3); h.status = h.status || 'active'; h.start = h.start || F.addDays(h.until, -7); h.expiresAt = h.until; h.fee = h.deposit; h.feeMethod = h.feeMethod || 'Chuyển khoản'; h.receiverId = h.receiverId || h.createdBy; h.cancelPolicy = h.cancelPolicy || 'forfeit'; h.autoExpire = true; h.requireDeposit = true; h.lockFromSales = false; h.leadId = h.leadId || null; });
    const p1Holds = st.holds.filter(h => h.status === 'active' && !h.leadId && st.tenants.find(t => t.id === h.tenantId && t.name !== 'Nguyễn Thị Hương')).slice(0, 6);
    board.held.forEach((l, i) => { const h = p1Holds[i]; if (!h) return; const t = st.tenants.find(x => x.id === h.tenantId); if (t) { t.name = l.name; t.phone = l.phone; t.zalo = l.phone; t.email = l.email; t.fromLeadId = l.id; } l.tenantId = h.tenantId; h.leadId = l.id; h.fee = h.deposit = 2000000; act(l, 'hold', 'Giữ chỗ phòng ' + (st.rooms.find(x => x.id === h.roomId) || {}).code + ' đến ' + F.date(h.until), h.start + 'T10:00'); });

    /* ----- Giao dịch & hoa hồng (32: 18 tháng 10 + 14 tháng 9) ----- */
    let gdN = 123; const deals = [];
    const activeC = st.contracts.filter(c => c.status === 'active' && !c.dealId).sort((a, b) => F.cmp(b.start, a.start)).slice(0, 28);
    const dealFor = (c, i) => {
      const t = st.tenants.find(x => x.id === c.tenantId); const room = st.rooms.find(x => x.id === c.roomId);
      const closed = i < 14 ? '2024-10-' + F.pad(20 - i) : '2024-09-' + F.pad(30 - (i - 14) * 2);
      const lead = addLead({ name: t.name, phone: t.phone, email: t.email, status: 'won', temp: 'hot', buildingIds: [room.buildingId], budgetMin: c.price - 1000000, budgetMax: c.price + 2000000, roomType: room.type, createdAt: F.addDays(closed, -rint(3, 9)) + 'T09:00', updatedAt: closed + 'T11:00' });
      act(lead, 'create', 'Tạo lead', lead.createdAt); act(lead, 'viewing', 'Đã xem phòng ' + room.code, F.addDays(closed, -2) + 'T10:00');
      lead.name = t.name; lead.phone = t.phone; lead.tenantId = t.id; lead.status = 'won'; lead.updatedAt = closed + 'T11:00';
      const sale = lead.saleId; const depositPaid = i % 4 === 3 ? Math.round(c.deposit * 0.5) : c.deposit;
      const d = mk(st, 'deals', { code: 'GD' + F.pad(gdN++, 5), leadId: lead.id, tenantId: t.id, roomId: room.id, buildingId: room.buildingId, saleId: sale, holdId: null, moveIn: c.start, months: Math.max(1, F.monthsDiff(c.start, c.end)), price: c.price, deposit: c.deposit, cycle: 'monthly', serviceIds: st.contractServices.filter(s => s.contractId === c.id).map(s => s.serviceId).filter(Boolean), people: rint(1, 2), note: '', status: 'active', contractId: c.id, closedAt: closed, depositPaid, createdBy: sale, createdAt: closed + 'T11:00' });
      c.dealId = d.id; act(lead, 'deal', 'Chốt thuê ' + d.code + ' – phòng ' + room.code, closed + 'T11:00', sale);
      mk(st, 'commissions', { dealId: d.id, saleId: sale, rate: 10, amount: Math.round(c.price * 0.1), status: 'provisional', paidAt: null, paidRef: '', expenseId: null });
      deals.push(d); if (i < 6) mk(st, 'holds', { code: 'GC-202410-' + F.pad(gcN++, 3), roomId: room.id, tenantId: t.id, leadId: lead.id, start: F.addDays(closed, -5), until: F.addDays(closed, 2), expiresAt: F.addDays(closed, 2), deposit: 2000000, fee: 2000000, feeMethod: 'Chuyển khoản', receiverId: sale, cancelPolicy: 'deduct', autoExpire: true, requireDeposit: true, lockFromSales: false, note: 'Giữ chỗ trước khi chốt', status: 'converted', dealId: d.id, createdBy: sale, createdAt: F.addDays(closed, -5) + 'T10:00' });
      return d;
    };
    activeC.forEach(dealFor);
    // 4 giao dịch mới chốt, chờ ký HĐ (lead cột Chốt thuê)
    board.won.forEach((l, i) => { if (deals.some(d => d.leadId === l.id)) return; const room = pickReady(); const t = mk(st, 'tenants', { code: 'KH' + F.pad((st.meta.counters && st.meta.counters.tenant || 300) + i, 5), name: l.name, phone: l.phone, zalo: l.phone, email: l.email, idNumber: '', dob: '', job: 'Nhân viên văn phòng', segment: 'Văn phòng', verified: false, managerId: room.managerId, note: 'Tạo từ lead ' + l.code, fromLeadId: l.id, createdAt: l.updatedAt }); l.tenantId = t.id; const d = mk(st, 'deals', { code: 'GD' + F.pad(gdN++, 5), leadId: l.id, tenantId: t.id, roomId: room.id, buildingId: room.buildingId, saleId: l.saleId, holdId: null, moveIn: F.addDays(T, rint(3, 10)), months: 12, price: room.price, deposit: room.price * 2, cycle: 'monthly', serviceIds: room.defaultServiceIds || [], people: 1, note: 'Chờ ký hợp đồng', status: 'pending_contract', contractId: null, closedAt: '2024-10-' + F.pad(24 + i), depositPaid: 0, createdBy: l.saleId, createdAt: '2024-10-' + F.pad(24 + i) + 'T11:00' }); mk(st, 'commissions', { dealId: d.id, saleId: l.saleId, rate: 10, amount: Math.round(room.price * 0.1), status: 'provisional', paidAt: null, paidRef: '', expenseId: null }); act(l, 'deal', 'Chốt thuê ' + d.code, d.createdAt, l.saleId); deals.push(d); if (st.meta.counters) st.meta.counters.tenant = (st.meta.counters.tenant || 300) + 4; });

    /* ----- Sự cố (18) ----- */
    const SC = [ // [phòng, hạng mục, ưu tiên, phụ trách, hạn, trạng thái, chi phí]
      ['A.12.03', 'Điện', 'urgent', 'kythuat', '2024-10-10', 'in_progress', 1200000], ['B.05.01', 'Nước', 'high', 'vanhanh', '2024-10-12', 'in_progress', 850000], ['C.08.02', 'Điều hòa', 'medium', 'lequanghuy', '2024-10-15', 'in_progress', 2300000], ['A.16.08', 'Thang máy', 'urgent', 'pttrang', '2024-10-09', 'in_progress', 5600000],
      ['D.03.06', 'Cửa khóa', 'low', 'hnkhanh', '2024-10-20', 'new', 350000], ['B.07.03', 'Nội thất', 'medium', 'pvquan', '2024-10-18', 'in_progress', 1800000], ['C.10.01', 'PCCC', 'high', 'cxson', '2024-10-16', 'done', 2100000], ['A.03.02', 'Nước', 'medium', 'lvthanh', '2024-10-22', 'new', 0],
      ['D.10.04', 'Chiếu sáng', 'low', 'lvthanh', '2024-10-25', 'new', 420000], ['B.09.03', 'Khác', 'medium', 'dvnam', '2024-10-19', 'done', 1100000], ['A.05.02', 'Điện', 'high', 'kythuat', '2024-10-30', 'assigned', 1500000], ['B.03.04', 'Nước', 'medium', 'pvquan', '2024-10-31', 'assigned', 1400000],
      ['C.02.01', 'Điều hòa', 'medium', 'cxson', '2024-11-02', 'assigned', 1800000], ['D.06.02', 'Điện', 'urgent', 'kythuat', '2024-10-29', 'in_progress', 2600000], ['A.08.04', 'Nước', 'low', 'lvthanh', '2024-11-03', 'assigned', 600000], ['B.11.02', 'Nước', 'medium', 'pvquan', '2024-11-04', 'assigned', 1400000],
      ['C.05.03', 'Nội thất', 'low', 'dvnam', '2024-11-05', 'assigned', 1100000], ['E.02.01', 'Khác', 'medium', 'dtmy', '2024-10-27', 'done', 2300000]];
    SC.forEach((s, i) => { const room = roomByCode(st, s[0]) || pickReady(); const b = st.buildings.find(x => x.id === room.buildingId); const created = F.addDays(s[4], -rint(3, 8)); const inc = mk(st, 'incidents', { code: 'SC-202410-' + F.pad(i + 1, 3), buildingId: room.buildingId, roomId: room.id, category: s[1], priority: s[2], desc: pick(['Khách báo ' + s[1].toLowerCase() + ' hỏng, cần kiểm tra sớm', 'Phát hiện khi kiểm tra định kỳ', 'Cư dân phản ánh qua Zalo OA']) + ' – phòng ' + room.code + ' (' + b.name + ')', dueDate: s[4], assigneeId: s[5] === 'new' ? null : U(s[3]), status: s[5], cost: s[6], vendorId: s[1] === 'Thang máy' ? byName(st, 'vendors', 'Thang Máy Việt').id : s[1] === 'PCCC' ? byName(st, 'vendors', 'PCCC An Toàn').id : null, expenseId: null, photos: s[5] === 'new' ? [] : ['anh_hien_truong_1.jpg'], createdBy: pick(OPS), createdAt: created + 'T' + F.pad(rint(8, 17)) + ':00', doneAt: s[5] === 'done' ? F.addDays(s[4], -1) + 'T16:00' : null }); mk(st, 'incidentUpdates', { incidentId: inc.id, at: inc.createdAt, by: inc.createdBy, type: 'create', note: 'Tạo sự cố' }); if (inc.assigneeId) mk(st, 'incidentUpdates', { incidentId: inc.id, at: F.addDays(created, 1) + 'T09:00', by: pick(OPS), type: 'assign', note: 'Phân công ' + (st.users.find(u => u.id === inc.assigneeId) || {}).name }); if (['in_progress', 'done'].includes(inc.status)) mk(st, 'incidentUpdates', { incidentId: inc.id, at: F.addDays(created, 1) + 'T14:00', by: inc.assigneeId, type: 'start', note: 'Bắt đầu xử lý' }); if (inc.status === 'done') mk(st, 'incidentUpdates', { incidentId: inc.id, at: inc.doneAt, by: inc.assigneeId, type: 'done', note: 'Hoàn tất – chi phí ' + F.vnd(inc.cost) }); });

    /* ----- Lịch bảo dưỡng (50, tháng 10/2024) ----- */
    const V = (n) => byName(st, 'vendors', n).id; const EQ = { 'Thang máy': ['Thang Máy Việt', 'monthly'], 'Máy bơm': ['HVAC Pro', 'q'], 'Máy giặt chung': ['CleanTech', 'monthly'], 'PCCC': ['PCCC An Toàn', 'h'], 'Máy lọc nước': ['AquaCare', 'q'], 'Máy phát điện': ['HVAC Pro', 'h'], 'Điều hòa': ['HVAC Pro', 'q'] };
    const CAL = [['01', 'Thang máy', 'A'], ['03', 'Máy bơm', 'B'], ['05', 'PCCC', 'C'], ['07', 'Máy lọc nước', 'A'], ['09', 'Máy giặt chung', 'B'], ['11', 'Thang máy', 'B'], ['15', 'Máy bơm', 'A'], ['17', 'PCCC', 'A'], ['19', 'Máy lọc nước', 'C'], ['21', 'Thang máy', 'C'], ['23', 'Máy giặt chung', 'A'], ['25', 'Máy bơm', 'C'], ['28', 'PCCC', 'B'], ['30', 'Máy lọc nước', 'B']];
    const BN = { A: 'Tòa Sunrise', B: 'Tòa Moonlight', C: 'Tòa Riverside', D: 'Tòa Central', E: 'Tòa Garden' };
    let bdN = 1; const schedules = [];
    const addSch = (dateISO, eq, bKey, status, o = {}) => { const [vendor, cycle] = EQ[eq] || ['HVAC Pro', 'q']; const s = mk(st, 'maintenanceSchedules', Object.assign({ code: 'BD-202410-' + F.pad(bdN++, 3), item: eq + (o.suffix || ''), equipType: eq, buildingId: bId(BN[bKey]), cycle, date: dateISO, vendorId: V(vendor), assigneeId: pick(TECH.concat(OPS)), checklist: [{ text: 'Kiểm tra tổng thể', done: status === 'done' }, { text: 'Vệ sinh / tra dầu', done: status === 'done' }, { text: 'Chạy thử & ghi nhận', done: status === 'done' }], note: '', status, doneAt: status === 'done' ? dateISO + 'T16:00' : null, cost: status === 'done' ? rint(5, 30) * 100000 : 0, expenseId: null, nextId: null, createdAt: F.addMonths(dateISO, -1) + 'T09:00' }, o)); schedules.push(s); return s; };
    CAL.forEach(([d, eq, b]) => { const iso = '2024-10-' + d; addSch(iso, eq, b, iso < T ? (['15', '17', '21'].includes(d) ? 'in_progress' : ['03', '25'].includes(d) ? 'scheduled' : 'done') : 'scheduled', { suffix: ' - ' + b }); });
    // 50 lịch: thêm cho đủ (hoàn thành 26, đang làm 12, sắp đến hạn 8, quá hạn 4)
    const eqs = Object.keys(EQ); const bks = ['A', 'B', 'C', 'D', 'E'];
    const need = { done: 26, in_progress: 12, due_soon: 8, overdue: 4 }; const cnt = { done: 0, in_progress: 0, due_soon: 0, overdue: 0 };
    schedules.forEach(s => { if (s.status === 'done') cnt.done++; else if (s.status === 'in_progress') cnt.in_progress++; else if (s.date < T) cnt.overdue++; else if (F.daysBetween(T, s.date) <= 7) cnt.due_soon++; });
    Object.entries(need).forEach(([k, n]) => { while (cnt[k] < n) { const eq = eqs[rint(0, eqs.length - 1)], b = bks[rint(0, bks.length - 1)]; if (k === 'done') addSch('2024-10-' + F.pad(rint(1, 26)), eq, b, 'done'); else if (k === 'in_progress') addSch('2024-10-' + F.pad(rint(20, 27)), eq, b, 'in_progress'); else if (k === 'due_soon') addSch(F.addDays(T, rint(0, 7)), eq, b, 'scheduled'); else addSch('2024-10-' + F.pad(rint(8, 24)), eq, b, 'scheduled'); cnt[k]++; } });

    /* ----- Data Jobs (38) ----- */
    const jobsHero = [ // [mã, loại, file, người tạo, tiến độ, ok, lỗi, trạng thái, cập nhật]
      ['IMP-202410-001', 'tenant', 'khach_thue.xlsx', 'kythuat', 60, 120, 8, 'running', '2024-10-20T14:25'], ['IMP-202410-002', 'room', 'phong.xlsx', 'vanhanh', 100, 45, 0, 'done', '2024-10-20T11:30'], ['IMP-202410-003', 'contract', 'hop_dong.xlsx', 'lequanghuy', 100, 86, 2, 'needs_check', '2024-10-19T16:10'],
      ['IMP-202410-004', 'meter', 'chi_so_dien_nuoc_T10_2024.xlsx', 'vanhanh', 82, 1020, 228, 'partial', '2024-10-19T09:15'], ['IMP-202410-005', 'opening', 'so_du_ban_dau.xlsx', 'hnkhanh', 100, 125, 0, 'done', '2024-10-18T21:40'], ['IMP-202410-006', 'tenant', 'khach_thue_dot2.xlsx', 'dvnam', 80, 200, 12, 'running', '2024-10-18T15:20'],
      ['IMP-202410-007', 'room', 'phong_moi.xlsx', 'lthuong', 100, 68, 0, 'done', '2024-10-17T10:05'], ['IMP-202410-008', 'contract', 'hop_dong_Q4.xlsx', 'nvhung', 10, 15, 28, 'failed', '2024-10-16T13:50'], ['IMP-202410-009', 'meter', 'chi_so_T10.xlsx', 'ptlan', 100, 412, 0, 'done', '2024-10-15T08:30'], ['IMP-202410-010', 'opening', 'so_du_t10.xlsx', 'dqbao', 100, 33, 1, 'needs_check', '2024-10-14T17:45']];
    const JT = { tenant: 'Khách thuê', room: 'Phòng', contract: 'Hợp đồng', meter: 'Chỉ số điện nước', opening: 'Số dư ban đầu', statement: 'Bảng kê thu tiền', invoice: 'Hóa đơn', lead: 'Lead' };
    const mkJob = (o) => mk(st, 'importJobs', Object.assign({ fileSize: (rint(3, 30) / 10).toFixed(1) + ' MB', rows: (o.ok || 0) + (o.failed || 0), valid: o.ok || 0, warn: 0, error: o.failed || 0, created: o.ok || 0, skipped: o.failed || 0, mapping: [], rules: [], lines: [], attempts: [], buildingLabel: 'Tất cả tòa nhà', period: '2024-10', note: '', checksum: 'seed-' + (o.code || F.uid()), typeLabel: JT[o.type] }, o));
    st.importJobs.forEach(j => { if (!j.code) { j.code = 'IMP-202410-000'; j.progress = 100; j.ok = j.valid; j.failed = j.error; j.lines = j.lines || []; j.attempts = j.attempts || [{ n: 1, at: j.createdAt, by: j.createdBy, total: j.rows, ok: j.valid, failed: j.error, status: 'done', note: 'Import Phase 1' }]; j.typeLabel = JT[j.type]; j.updatedAt = j.createdAt; } });
    jobsHero.forEach(h => { const total = h[5] + h[6]; const j = mkJob({ code: h[0], type: h[1], fileName: h[2], createdBy: U(h[3]), progress: h[4], ok: h[5], failed: h[6], status: h[7], updatedAt: h[8], createdAt: F.addDays(h[8].slice(0, 10), 0) + 'T' + F.pad(Number(h[8].slice(11, 13)) - 1) + ':30', rows: total, valid: h[5], error: h[6] });
      j.attempts = [{ n: 1, at: j.createdAt, by: j.createdBy, total, ok: h[5], failed: h[6], status: h[7], note: h[6] ? 'Phát hiện ' + h[6] + ' dòng lỗi. Vui lòng kiểm tra file và thử lại.' : 'Hoàn tất không lỗi' }]; });
    const j4 = st.importJobs.find(j => j.code === 'IMP-202410-004');
    if (j4) {
      j4.fileSize = '2.4 MB'; j4.buildingLabel = 'Tòa Sunrise, Tòa Moonlight'; j4.createdAt = '2024-10-15T14:30'; j4.uploadedAt = '2024-10-15T14:28'; j4.note = ''; j4.rows = 1248; j4.total = 1248; j4.progress = 82;
      j4.mapping = ['Mã phòng', 'Kỳ', 'Điện mới', 'Nước mới']; j4.rules = ['Bắt buộc: Mã phòng, Kỳ', 'Chỉ số là số, không âm', 'Kiểm tra tồn tại phòng trong hệ thống', 'Không cho phép trùng kỳ đã có']; j4.mappingTemplate = 'Mẫu tiêu chuẩn - Điện nước (v1.2)'; j4.sheet = 'Sheet1'; j4.startRow = 2; j4.dupPolicy = 'Bỏ qua (giữ bản ghi cũ)'; j4.updateIfExists = 'Có (cập nhật chỉ số mới)';
      j4.attempts = [{ n: 1, at: '2024-10-15T14:32', by: j4.createdBy, total: 1248, ok: 856, failed: 392, status: 'failed', note: 'Phát hiện 392 dòng lỗi. Vui lòng kiểm tra file và thử lại.' }, { n: 2, at: '2024-10-15T15:05', by: j4.createdBy, total: 1248, ok: 1020, failed: 228, status: 'partial', note: 'Thử lại các dòng đủ điều kiện sau khi đã chỉnh sửa dữ liệu nguồn.' }];
      const rooms2 = st.rooms.filter(x => [bId('Tòa Sunrise'), bId('Tòa Moonlight'), bId('Tòa Riverside'), bId('Tòa Central')].includes(x.buildingId)).sort((a, b) => a.code.localeCompare(b.code));
      const first = [['A.12.03', 120, 58, 'ok', ''], ['B.05.01', 210, 102, 'ok', ''], ['C.08.02', null, 76, 'failed', 'Thiếu chỉ số điện'], ['D.03.06', 180, 0, 'check', 'Chỉ số nước bằng 0'], ['A.16.08', 95, 44, 'ok', ''], ['ZZ.99', 120, 66, 'failed', 'Không tìm thấy phòng trong hệ thống'], ['B.07.03', 310, 120, 'ok', '']];
      const lines = []; for (let i = 0; i < 1248; i++) { const f = first[i]; const room = f ? roomByCode(st, f[0]) : rooms2[i % rooms2.length]; const per = f ? '10/2024' : ['07/2024', '08/2024', '09/2024', '10/2024'][Math.floor(i / rooms2.length) % 4]; const e = f ? f[1] : rint(60, 320), w = f ? f[2] : rint(5, 130); let stt = f ? f[3] : (i % 100 < 82 ? 'ok' : i % 100 < 96 ? 'failed' : 'check'); let reason = f ? f[4] : stt === 'failed' ? pick(['Thiếu chỉ số điện', 'Chỉ số nước < kỳ trước', 'Kỳ sai định dạng']) : stt === 'check' ? 'Chỉ số nước bằng 0' : ''; lines.push({ i: i + 1, src: (f ? f[0] : room.code) + ' | ' + (e == null ? '-' : e) + ' | ' + (w == null ? '-' : w) + ' | ' + per, data: { roomCode: f ? f[0] : room.code, period: per.split('/').reverse().join('-'), electricCurr: e, waterCurr: w }, status: stt, reason, roomId: room && (!f || f[0] !== 'ZZ.99') ? room.id : null, hash: F.hash('m4:' + i) }); }
      const okN = lines.filter(x => x.status === 'ok').length; let k = 0; lines.forEach(x => { if (x.status === 'ok' && k++ >= 1020) x.status = 'skipped'; }); j4.lines = lines; j4.ok = 1020; j4.failed = 228; j4.valid = 1020; j4.error = 228; void okN;
    }
    // Job sinh thêm cho đủ 38
    let extra = 0; const types = ['tenant', 'room', 'meter', 'invoice', 'contract'];
    while (st.importJobs.length < 38) { extra++; const tp = types[extra % types.length]; const okN = rint(20, 300), fail = extra % 5 === 0 ? rint(1, 12) : 0; const day = F.pad(rint(1, 28)); const mon = extra % 3 === 0 ? '09' : '10'; mkJob({ code: 'IMP-2024' + mon + '-' + F.pad(10 + extra, 3), type: tp, fileName: tp + '_2024' + mon + '_' + extra + '.csv', createdBy: pick(OPS.concat([U('ketoan'), U('admin')])), progress: extra % 9 === 0 ? rint(20, 90) : 100, ok: okN, failed: fail, status: extra % 9 === 0 ? 'running' : fail ? 'partial' : 'done', createdAt: '2024-' + mon + '-' + day + 'T09:00', updatedAt: '2024-' + mon + '-' + day + 'T09:20', rows: okN + fail, valid: okN, error: fail, attempts: [{ n: 1, at: '2024-' + mon + '-' + day + 'T09:00', total: okN + fail, ok: okN, failed: fail, status: fail ? 'partial' : 'done', note: '' }] }); }

    /* ----- Zalo: đợt gửi hero ZL-202410-104 (124 tin, provider code) ----- */
    if (!st.zaloBatches.some(b => b.code === 'ZL-202410-104')) {
      const tpl = st.zaloTemplates.find(t => t.eventKey === 'reminder');
      const b = mk(st, 'zaloBatches', { code: 'ZL-202410-104', name: 'Nhắc tiền phòng tháng 10', eventKey: 'reminder', sourceKey: 'due_soon', audience: 'Khách thuê đang hoạt động', plannedCount: 124, sentCount: 118, failedCount: 4, sentAt: '2024-10-18T09:00', startedAt: '2024-10-18T08:55', finishedAt: '2024-10-18T09:25', createdAt: '2024-10-18T08:30', createdBy: U('admin'), status: 'partial', templateId: tpl.id, scopeLabel: 'Tất cả tòa nhà', period: '2024-10', sendMode: 'now', rules: 'Re-check công nợ trước khi gửi · Chỉ gửi 1 tin / khách / kỳ', note: 'Nhắc tiền phòng định kỳ tháng 10/2024', errors: 'Số Zalo không tồn tại (300), Template rejected (403), Timeout (408)', phase: 2, log: [] });
      const invs = st.invoices.filter(i => i.period === '2024-10' && i.docStatus !== 'draft' && i.docStatus !== 'cancelled').slice(0, 124);
      const CODES = { 2: ['300', 'Số không tồn tại', 'ZLM-1001'], 4: ['403', 'Template rejected', 'ZLM-2003'], 6: ['408', 'Timeout', 'ZLM-4008'], 8: ['300', 'Số không tồn tại', 'ZLM-1001'], 12: ['403', 'Template rejected', 'ZLM-2003'], 14: ['408', 'Timeout', 'ZLM-4008'] };
      invs.forEach((inv, k) => { const t = st.tenants.find(x => x.id === inv.tenantId) || {}; const c = CODES[k]; const at = '2024-10-18T09:' + F.pad(Math.min(25, Math.floor(k / 5))); const m = mk(st, 'zaloMessages', { batchId: b.id, tenantId: inv.tenantId, roomId: inv.roomId, buildingId: inv.buildingId, invoiceId: inv.id, channel: 'Zalo', templateCode: tpl.code, status: c ? 'failed' : 'delivered', errorCode: c ? c[2] : '', providerCode: c ? c[0] : '200', providerMsg: c ? c[1] : 'OK', sentAt: at, phone: t.phone || '', content: '', amountAtSend: inv.total, retryOfId: null, attempt: 1, attempts: [{ n: 1, at, code: c ? c[0] : '200', msg: c ? c[1] : 'OK' }] }); if (k < 5 || c) b.log.push({ at: at + ':' + F.pad(rint(10, 59)), roomId: inv.roomId, phone: t.phone || '', code: m.providerCode, msg: m.providerMsg }); });
      b.log.sort((x, y) => F.cmp(x.at, y.at)); b.plannedCount = invs.length; b.sentCount = invs.length - 6; b.failedCount = 4;
    }
    // Đợt P1 loại p2_* → sự kiện thật của P2
    st.zaloBatches.forEach(b => { if (b.eventKey === 'p2_viewing') { b.eventKey = 'viewing_reminder'; b.phase = 2; } if (b.eventKey === 'p2_care') { b.eventKey = 'care'; b.phase = 2; } });

    /* ----- Hoàn cọc: bổ sung hiện trạng, ảnh, ghi chú, lịch sử (PNG 03/09) ----- */
    st.refunds.forEach(rf => { if (rf.inspection2) return; rf.inspection2 = { general: 'ok', furniture: (rf.inspection || {}).furniture === 'minor' ? 'minor' : 'ok', cleaning: 'ok', keys: 'ok', devices: 'ok' }; rf.photos = rf.status === 'draft' ? [] : ['phong_ngu.jpg', 'tuong.jpg', 'wc.jpg', 'bep.jpg', 'ban_cong.jpg', 'cua.jpg', 'tu.jpg', 'sofa.jpg', 'den.jpg'].slice(0, rf.status === 'refunded' ? 9 : 8); rf.notes = rf.status === 'pending' ? [{ at: F.addDays(rf.requestDate, 2) + 'T14:25', by: U('lequanghuy'), text: 'Đề nghị kiểm tra kỹ hình ảnh và đối chiếu với biên bản bàn giao. Hạng mục sơn tường cần báo giá lại.', tag: 'Nội bộ' }] : []; rf.history = [{ at: rf.requestDate + 'T09:15', by: rf.handlerId, status: 'draft', note: 'Tạo yêu cầu hoàn cọc' }]; if (rf.status !== 'draft') rf.history.push({ at: F.addDays(rf.requestDate, 2) + 'T14:20', by: rf.handlerId, status: 'pending', note: 'Chuyển đến quản lý để phê duyệt' }); if (rf.status === 'rejected') rf.history.push({ at: F.addDays(rf.requestDate, 3) + 'T10:00', by: U('ketoan'), status: 'rejected', note: rf.rejectReason }); if (rf.approvedAt) rf.history.push({ at: rf.approvedAt, by: rf.approvedBy, status: 'approved', note: 'Duyệt hoàn cọc' }); if (rf.status === 'refunded') rf.history.push({ at: rf.paidDate + 'T15:00', by: U('ketoan'), status: 'refunded', note: 'Đã hoàn tiền ' + rf.paidMethod }); });

    /* ----- Khấu hao: chi phí method=depreciation có số tháng ----- */
    st.expenses.forEach(e => { if (e.method === 'depreciation' && !e.depreciationMonths) e.depreciationMonths = 36; });

    st.meta.counters = Object.assign(st.meta.counters || {}, { lead: ldN, viewing: lxN, hold: gcN, deal: gdN, schedule: bdN });
    st.meta.p2Seeded = true; st.meta.p2SeededAt = F.nowISO();
    return st;
  };
})(window.TH);
