/* Seed / migration – Spec v1.8 Wave 4: danh mục chi phí §4.27.3 (GV / BH / VH, bỏ mã Lương khỏi nhập tay), phiếu chi phí đủ dữ liệu §4.27.2 + nguồn dữ liệu, Allocation Rule (§4.27.7),
   Payroll Rule Version (§4.26.4), cấu phần lương NV (§4.26.5), mốc thu M1/M2/M3 cho Payment Allocation (§4.26.2), kịch bản demo: chi phí import (có dòng lỗi), hoa hồng, chi phí chung chờ phân bổ.
   Additive & idempotent (meta.w4Migrated). Bảng lương/chi lương demo dựng ở X.ensureW4Scenario (cần selectors). */
(function (TH) {
  const F = TH.f, seed = TH.seed = TH.seed || {};
  const T = F.DEMO_TODAY;
  const mk = (st, col, obj) => { st[col] = st[col] || []; obj.id = obj.id || F.uid(col.slice(0, 3)); obj.source = obj.source || 'seed'; obj.createdAt = obj.createdAt || '2026-01-01T08:00'; st[col].push(obj); return obj; };
  const userBy = (st, username) => st.users.find(u => u && u.username === username) || null;
  const bByName = (st, name) => st.buildings.find(b => b && b.name === name) || null;
  const MS = [['M1', 5], ['M2', 10], ['M3', 15]];
  const milestoneOf = (date, period) => { if (!date || !period) return 'LATE'; const p = String(date).slice(0, 7); if (p < period) return 'M1'; if (p > period) return 'LATE'; const day = Number(String(date).slice(8, 10)); const hit = MS.find(m => day <= m[1]); return hit ? hit[0] : 'LATE'; };

  const migrateExpenseGroups = (st) => {
    const g = (code) => st.expenseGroups.find(x => x && x.code === code);
    const ensure = (code, name, parentCode, sortOrder, extra = {}) => { let x = g(code); if (!x) x = mk(st, 'expenseGroups', { code, name, fullName: name, parentCode, status: 'active', sortOrder }); else Object.assign(x, { name, fullName: name, parentCode, sortOrder, status: 'active', aliasOf: undefined }); Object.assign(x, extra); return x; };
    ensure('GV', 'Giá vốn', null, 1); ensure('BH', 'Chi phí bán hàng', null, 2); ensure('VH', 'Chi phí vận hành', null, 3);
    [['GV-THUE', 'Tiền thuê nhà'], ['GV-TB', 'Mua thêm thiết bị'], ['GV-DIEN', 'Giá gốc điện'], ['GV-NUOC', 'Giá gốc nước'], ['GV-MANG', 'Giá gốc mạng / Internet'], ['GV-RAC', 'Phí rác'], ['GV-MT', 'Phí môi trường'], ['GV-TM', 'Bảo trì thang máy']].forEach(([c, n], i) => ensure(c, n, 'GV', i + 1));
    [['BH-MKT', 'Marketing'], ['BH-HH', 'Hoa hồng']].forEach(([c, n], i) => ensure(c, n, 'BH', i + 1));
    [['VH-SC', 'Sửa chữa'], ['VH-TT', 'Thay thế'], ['VH-VP', 'Văn phòng'], ['VH-KHAC', 'Chi phí khác']].forEach(([c, n], i) => ensure(c, n, 'VH', i + 1));
    const ALIAS = { 'DV-DIEN': 'GV-DIEN', 'DV-NUOC': 'GV-NUOC', 'DV-MANG': 'GV-MANG', 'DV-RAC': 'GV-RAC', 'DV-MT': 'GV-MT', 'DV-TM': 'GV-TM', 'BH-SC': 'VH-SC', 'BH-KHAC': 'VH-KHAC' };
    Object.entries(ALIAS).forEach(([old, nw]) => { const x = g(old); if (x) Object.assign(x, { aliasOf: nw, status: 'alias' }); });
    const dv = g('DV'); if (dv) Object.assign(dv, { status: 'alias', aliasOf: 'GV', name: 'Giá gốc dịch vụ (gộp vào Giá vốn)' });
    st.expenseGroups.forEach(x => { if (!x) return; if (/^VH-L-/.test(x.code)) { x.status = 'system'; x.note = 'Lương lấy từ Payroll/Chi lương – không nhập tay (§4.27.4)'; } if (/^NC\d/.test(x.code)) x.status = 'alias'; });
    const NC = { 'Thuê nhà': 'GV-THUE', 'Mua sắm TS': 'GV-TB', 'Điện nước': 'GV-DIEN', 'Lương': 'VH-L-QL', 'Marketing': 'BH-MKT', 'Sửa chữa': 'VH-SC', 'Khác': 'VH-KHAC' };
    st.expenseGroups.forEach(x => { if (x && /^NC\d/.test(x.code) && NC[x.name]) x.aliasOf = NC[x.name]; });
    const resolve = (code) => { let c = code; let n = 0; while (n++ < 5) { const x = g(c); if (x && x.aliasOf) c = x.aliasOf; else if (ALIAS[c]) c = ALIAS[c]; else break; } return c; };
    // Chi phí "Lương" seed cũ: bỏ (payroll là nguồn duy nhất – §4.26.10); chi phí khác: map mã mới + backfill dữ liệu tối thiểu §4.27.2
    st.expenses = st.expenses.filter(e => e && !(e.source === 'seed' && (/^VH-L-/.test(resolve(e.categoryCode || '')) || e.group === 'Lương' || /lương/i.test(e.desc || ''))));
    const exIds = new Set(st.expenses.map(e => e.id)); st.expenseAllocations = (st.expenseAllocations || []).filter(a => a && exIds.has(a.expenseId));
    st.expenses.forEach(e => { e.categoryCode = resolve(e.categoryCode || NC[e.group] || 'VH-KHAC'); const cat = g(e.categoryCode) || {}; e.group = cat.name || e.group; if (!e.docDate) e.docDate = e.date; if (!e.recordDate) e.recordDate = e.createdAt ? String(e.createdAt).slice(0, 10) : e.date; if (!e.accountingPeriod) e.accountingPeriod = String(e.date).slice(0, 7); if (!e.dataSource) e.dataSource = e.landlordPaymentId || /tự tạo/i.test(e.note || '') ? 'system' : (/import/i.test(e.note || '') ? 'import' : 'manual'); if (!e.payMethod) e.payMethod = e.method === 'cash' && e.amount < 3000000 ? 'cash' : 'bank'; if (!e.supplier) e.supplier = e.categoryCode === 'GV-DIEN' ? 'EVN' : e.categoryCode === 'GV-NUOC' ? 'Cấp nước' : e.categoryCode === 'GV-THUE' ? 'Chủ nhà' : e.categoryCode === 'BH-MKT' ? 'Meta Ads' : ''; if (!e.status) e.status = 'recorded'; if (!e.confirmedBy) e.confirmedBy = e.createdBy || null;
      if (!e.buildingId) { const allocs = st.expenseAllocations.filter(a => a.expenseId === e.id); if (allocs.length) { e.status = 'allocated'; e.allocation = e.allocation || { method: 'MANUAL_RATIO', buildingIds: allocs.map(a => a.buildingId) }; allocs.forEach(a => { if (!a.method) a.method = 'MANUAL_RATIO'; if (!a.period) a.period = e.accountingPeriod; }); } else e.status = 'pending_alloc'; } });
  };

  const seedRules = (st) => {
    if (!(st.allocationRules || []).length) mk(st, 'allocationRules', { code: 'AR-2026-01', name: 'Quy tắc phân bổ chi phí chung 2026', effectiveFrom: '2026-01-01', effectiveTo: '', status: 'active', defaults: { 'VH-VP': 'ROOM_COUNT', 'BH-MKT': 'REVENUE', 'VH-KHAC': 'BUILDING_COUNT', 'GV-MANG': 'ROOM_COUNT' }, fallback: 'ROOM_COUNT', payrollShared: 'ROOM_COUNT', note: 'Văn phòng theo số phòng, Marketing theo doanh thu, khác theo số tòa; lương vai trò chung theo số phòng (§12.23.7)' });
    if (!(st.payrollRuleVersions || []).length) {
      mk(st, 'payrollRuleVersions', { code: 'PR-2026-01', name: 'Mức lương/phòng – Phụ trách chính', effectiveFrom: '2026-01-01', effectiveTo: '', roles: ['manager'], collectedFormula: 'M123_MINUS_SERVICE_PLUS_EXTRA', tiers: [{ from: 90, to: null, rate: 150000, label: '≥ 90%' }, { from: 75, to: 90, rate: 120000, label: '75–90%' }, { from: 60, to: 75, rate: 90000, label: '60–75%' }, { from: 40, to: 60, rate: 60000, label: '40–60%' }, { from: 0, to: 40, rate: 30000, label: '< 40%' }], status: 'active', confirmation: 'NEED_BUSINESS_CONFIRMATION', note: 'Bậc giả định từ sheet Bảng lương – chờ khách chốt (§4.26.4)', createdAt: '2026-01-01T08:00' });
      mk(st, 'payrollRuleVersions', { code: 'PR-2026-01S', name: 'Mức lương/phòng – Nhân sự hỗ trợ', effectiveFrom: '2026-01-01', effectiveTo: '', roles: ['support'], collectedFormula: 'M123_MINUS_SERVICE_PLUS_EXTRA', tiers: [{ from: 90, to: null, rate: 60000, label: '≥ 90%' }, { from: 75, to: 90, rate: 50000, label: '75–90%' }, { from: 60, to: 75, rate: 40000, label: '60–75%' }, { from: 40, to: 60, rate: 25000, label: '40–60%' }, { from: 0, to: 40, rate: 15000, label: '< 40%' }], status: 'active', confirmation: 'NEED_BUSINESS_CONFIRMATION', note: 'Hỗ trợ hưởng ~40% mức Phụ trách chính (giả định)', createdAt: '2026-01-01T08:00' });
    }
  };
  const migrateEmployees = (st) => {
    const BANKS = ['Vietcombank', 'Techcombank', 'BIDV', 'MB Bank', 'ACB'];
    const posOf = (e) => { const a = (st.employmentAssignments || []).find(x => x && x.employeeId === e.id && x.isPrimary && x.status !== 'cancelled'); const p = a ? (st.positions || []).find(x => x && x.id === a.positionId) : null; return p ? p.code : ''; };
    st.employees.forEach((e, i) => { if (!e || (e.payroll && e.payroll.base != null)) return; const pos = posOf(e); const lead = ['QLT', 'TPVH', 'QLKV', 'TN'].includes(pos); const hasSupport = (st.buildingAssignments || []).some(a => a && a.employeeId === e.id && a.role === 'support' && ['active', 'approved'].includes(a.status)); const ops = e.dept === 'vanhanh' || ['NVVH', 'QLKV', 'TPVH'].includes(pos);
      e.payroll = { base: Number(e.salaryBase || 8000000), lunch: 730000, fuel: ops ? 500000 : 300000, leadAllowance: lead ? Number(e.titleAllowance || 0) : 0, support: hasSupport ? 1000000 : 0, bankAccount: { bank: BANKS[i % BANKS.length], number: String(1000 + i * 37) + '0' + String(2000 + i * 11) + String(50 + (i % 40)), name: F.norm((e.name || '').replace(/đ/g, 'd').replace(/Đ/g, 'D')).toUpperCase().replace(/[^A-Z ]/g, '') } }; });
  };
  const migrateAllocations = (st) => { const pays = {}; st.payments.forEach(p => { if (p) pays[p.id] = p; }); const invs = {}; st.invoices.forEach(i => { if (i) invs[i.id] = i; }); (st.paymentAllocations || []).forEach(a => { if (!a || a.milestone) return; const p = pays[a.paymentId], inv = invs[a.invoiceId]; if (p && inv) { a.milestone = milestoneOf(p.date, inv.period); a.milestoneDay = Number(String(p.date).slice(8, 10)); } }); };

  const scenario = (st) => {
    const cur = st.meta.period || '2026-10'; const admin = userBy(st, 'admin') || st.users[0]; const ketoan = userBy(st, 'ketoan') || admin;
    const B = { SR: bByName(st, 'Tòa Sunrise'), ML: bByName(st, 'Tòa Moonlight'), RS: bByName(st, 'Tòa Riverside'), CT: bByName(st, 'Tòa Central'), GD: bByName(st, 'Tòa Garden') };
    const live = st.buildings.filter(b => b && !b.stub && b.status !== 'inactive');
    const ex = (o) => { if (st.expenses.some(e => e && e.desc === o.desc && e.amount === o.amount)) return null; const cat = st.expenseGroups.find(g => g && g.code === o.categoryCode) || {}; return mk(st, 'expenses', Object.assign({ code: 'CP' + F.pad(st.expenses.length + 1, 4), date: o.docDate, docDate: o.docDate, recordDate: o.recordDate || o.docDate, accountingPeriod: String(o.docDate).slice(0, 7), group: cat.name || '', recordType: o.buildingId ? 'ops' : 'common', method: 'cash', evidence: o.evidence || '', note: o.note || '', status: o.buildingId ? 'recorded' : 'pending_alloc', createdBy: ketoan.id, confirmedBy: ketoan.id, payMethod: o.payMethod || 'bank', dataSource: o.dataSource || 'manual', createdAt: o.docDate + 'T09:00' }, o)); };
    const batch = 'IMPX-SEED-' + cur.replace('-', '');
    // Import chi phí giá gốc dịch vụ + hoa hồng (nguồn Import, §4.27.4/§4.27.5)
    [[B.ML, 'GV-NUOC', 'Tiền nước tháng ' + cur.slice(5) + '/' + cur.slice(0, 4) + ' – Moonlight', 3150000, 'Cấp nước Phú Nhuận'], [B.RS, 'GV-MANG', 'Cước Internet tháng ' + cur.slice(5) + ' – Riverside', 2400000, 'VNPT'], [B.CT, 'GV-RAC', 'Phí thu gom rác tháng ' + cur.slice(5) + ' – Central', 900000, 'Môi trường đô thị'], [B.GD, 'GV-TM', 'Bảo trì thang máy quý IV – Garden', 6500000, 'Mitsubishi Elevator'], [B.SR, 'GV-MT', 'Phí môi trường tháng ' + cur.slice(5) + ' – Sunrise', 750000, 'Môi trường đô thị']].forEach(([b, cat, desc, amount, supplier], i) => { if (!b) return; const e = ex({ docDate: cur + '-' + F.pad(6 + i), categoryCode: cat, desc, buildingId: b.id, amount, supplier, dataSource: 'import', evidence: 'hoa_don_' + cat.toLowerCase() + '_' + cur + '.pdf' }); if (e) { e.importBatchId = batch; e.importFile = 'mau-import-chi-phi.csv'; } });
    const sale = st.users.find(u => u && u.role === 'sale') || null; const roomsCT = B.CT ? st.rooms.filter(r => r && r.buildingId === B.CT.id).slice(0, 2) : [];
    [[B.CT, 'Hoa hồng ký HĐ mới ' + (roomsCT[0] ? roomsCT[0].code : 'D.01.01') + ' – tháng ' + cur.slice(5), 1500000, roomsCT[0]], [B.SR, 'Hoa hồng gia hạn HĐ – Sunrise tháng ' + cur.slice(5), 800000, null]].forEach(([b, desc, amount, room], i) => { if (!b) return; ex({ docDate: cur + '-' + F.pad(12 + i), categoryCode: 'BH-HH', desc, buildingId: b.id, amount, supplier: sale ? sale.name : 'Nhân viên kinh doanh', dataSource: i === 0 ? 'import' : 'manual', commission: { saleId: sale ? sale.id : '', recipient: sale ? sale.name : '', roomId: room ? room.id : '', paidDate: cur + '-' + F.pad(12 + i) }, evidence: 'phieu_chi_hoa_hong_' + F.pad(i + 1, 2) + '.pdf' }); });
    if (B.GD) ex({ docDate: cur + '-09', categoryCode: 'VH-TT', desc: 'Thay bình nóng lạnh phòng ' + ((st.rooms.find(r => r && r.buildingId === B.GD.id) || {}).code || 'E.01.01'), buildingId: B.GD.id, amount: 3200000, supplier: 'Điện máy Xanh', evidence: 'hd_binh_nong_lanh.pdf' });
    // Chi phí chung: 1 chờ phân bổ (demo Fm.allocateExpense), 1 đã phân bổ theo số phòng (Allocation Rule)
    ex({ docDate: cur + '-03', categoryCode: 'VH-VP', desc: 'Thuê văn phòng điều hành tháng ' + cur.slice(5) + '/' + cur.slice(0, 4), buildingId: null, amount: 18000000, supplier: 'Tòa nhà văn phòng Q.7', note: 'Chi phí chung – chọn phương thức phân bổ (§4.27.7)' });
    const off = ex({ docDate: cur + '-04', categoryCode: 'VH-VP', desc: 'Văn phòng phẩm & phần mềm tháng ' + cur.slice(5), buildingId: null, amount: 4200000, supplier: 'Thiên Long / Google Workspace' });
    if (off) { const rule = (st.allocationRules || [])[0]; const rooms = (b) => st.rooms.filter(r => r && r.buildingId === b.id && r.status !== 'inactive').length; const tw = live.reduce((s, b) => s + rooms(b), 0) || 1; let acc = 0; live.forEach((b, i) => { const amt = i === live.length - 1 ? off.amount - acc : Math.round(off.amount * rooms(b) / tw); acc += amt; mk(st, 'expenseAllocations', { expenseId: off.id, buildingId: b.id, pct: Math.round(rooms(b) / tw * 10000) / 100, amount: amt, basis: rooms(b), method: 'ROOM_COUNT', ruleVersionId: rule ? rule.id : null, period: cur, confirmedBy: ketoan.id, confirmedAt: cur + '-04T10:00' }); }); off.status = 'allocated'; off.allocation = { method: 'ROOM_COUNT', buildingIds: live.map(b => b.id), ruleVersionId: rule ? rule.id : null, at: cur + '-04T10:00', by: ketoan.id }; }
    // Import job chi phí có 2 dòng lỗi (trùng + tòa không tồn tại) → Work Queue "Import chi phí lỗi"
    if (!(st.importJobs || []).some(j => j && j.type === 'expense')) mk(st, 'importJobs', { code: 'IMP-' + cur.replace('-', '') + '-090', type: 'expense', typeLabel: 'Chi phí', fileName: 'mau-import-chi-phi.csv', rows: 8, valid: 6, warn: 0, error: 2, created: 6, skipped: 2, status: 'partial', createdBy: ketoan.id, checksum: 'seed-' + batch, batchId: batch, progress: 100, ok: 6, failed: 2, updatedAt: cur + '-06T09:30', createdAt: cur + '-06T09:30', lines: [{ i: 7, data: { date: cur + '-02', categoryCode: 'GV-DIEN', desc: 'Tiền điện tháng ' + cur.slice(5) + '/' + cur.slice(0, 4), buildingCode: 'TH-HBT-01', amount: '4500000' }, status: 'failed', reason: 'Trùng với CP0001 (ngày + số tiền + diễn giải)' }, { i: 8, data: { date: cur + '-05', categoryCode: 'GV-RAC', desc: 'Phí rác', buildingCode: 'Tòa ABC', amount: '600000' }, status: 'failed', reason: 'Tòa "Tòa ABC" không tồn tại' }], attempts: [{ n: 1, at: cur + '-06T09:30', by: ketoan.id, total: 8, ok: 6, failed: 2, status: 'partial', note: 'Bỏ qua 2 dòng lỗi/trùng' }] });
  };

  seed.migrateW4 = (st) => {
    if (!st || !Array.isArray(st.buildings) || !st.buildings.length) return; st.meta = st.meta || {};
    ['payrollRuleVersions', 'payrollAssignmentSnapshots', 'payrollResults', 'salaryPayments', 'payrollCostAllocations', 'allocationRules'].forEach(c => { if (!Array.isArray(st[c])) st[c] = []; });
    if (st.meta.w4Migrated) return;
    try { migrateExpenseGroups(st); seedRules(st); migrateEmployees(st); migrateAllocations(st); scenario(st); } catch (e) { console.warn('migrate w4', e); }
    st.meta.w4Migrated = true; st.meta.w4ScenarioDone = false;
  };
})(window.TH);
