/* Selectors spec v1.8 Wave 5 – kỳ báo cáo (§12.23.1/13), cổ phần theo tòa có hiệu lực (§4.30), góp vốn theo tòa (§4.31), phân phối lợi nhuận snapshot (§4.32), golden dataset. */
(function (TH) {
  const F = TH.f, Q = TH.q, St = TH.store; const raw = (c) => St.rawAll(c).filter(Boolean); const get = (c, id) => St.rawGet(c, id) || {};
  Object.assign(Q.L, {
    reportPeriod: { OPEN: ['Đang mở', 'gray'], REVIEWING: ['Đang review', 'amber'], LOCKED: ['Đã khóa', 'green'], REOPENED: ['Đã mở lại', 'red'] },
    metricStatus: { CONFIRMED: ['Đã xác nhận', 'green'], NEED_BUSINESS_CONFIRMATION: ['Chờ chốt', 'amber'], DEPRECATED: ['Ngừng dùng', 'gray'] },
    reconStatus: { MATCH: ['Khớp', 'green'], ROUNDING_DIFFERENCE: ['Lệch làm tròn', 'blue'], RULE_DIFFERENCE: ['Lệch rule', 'amber'], SOURCE_DATA_DIFFERENCE: ['Lệch dữ liệu nguồn', 'red'], NEED_BUSINESS_CONFIRMATION: ['Chờ chốt', 'amber'] },
    profitDist: { draft: ['Nháp', 'gray'], review: ['Chờ xác nhận', 'amber'], confirmed: ['Đã xác nhận', 'green'], cancelled: ['Đã hủy', 'red'] },
    capitalCall: { open: ['Đang góp', 'amber'], overdue: ['Quá hạn', 'red'], done: ['Đã góp đủ', 'green'], cancelled: ['Đã hủy', 'gray'] },
    capitalLine: { unpaid: ['Chưa góp', 'gray'], partial: ['Góp một phần', 'amber'], paid: ['Đã góp', 'green'], overdue: ['Quá hạn', 'red'] },
    shareholderStatus: { active: ['Đang hoạt động', 'green'], inactive: ['Ngừng hoạt động', 'gray'] },
  });
  /* ---- Kỳ báo cáo ---- */
  Q.reportPeriod = (period) => raw('reportPeriods').find(p => p.period === period) || null;
  Q.reportPeriods = () => { const set = new Set(raw('reportPeriods').map(p => p.period).concat(raw('invoices').map(i => i.period)).concat([St.state.meta.period])); return [...set].filter(Boolean).sort().reverse(); };
  Q.reportPeriodRows = () => Q.reportPeriods().map(period => { const rp = Q.reportPeriod(period); const snaps = rp ? raw('reportSnapshots').filter(s => s.reportPeriodId === rp.id) : []; return { period, rp, status: rp ? rp.status : 'OPEN', snapA: snaps.filter(s => s.reportType === 'A').length, snapB: snaps.filter(s => s.reportType === 'B').length, dists: raw('profitDistributions').filter(d => d.period === period).length }; });
  Q.reportLocked = (period) => { const rp = Q.reportPeriod(period); return !!rp && rp.status === 'LOCKED'; };
  /* ---- Cổ phần theo tòa: record theo ngày hiệu lực, không ghi đè ---- */
  Q.buildingShares = (bid, date) => { date = date || F.today(); return raw('buildingShares').filter(s => s.buildingId === bid && s.status !== 'cancelled' && s.effectiveFrom <= date && (!s.effectiveTo || s.effectiveTo >= date)).sort((a, b) => b.percentage - a.percentage || F.cmp(a.effectiveFrom, b.effectiveFrom)); };
  Q.buildingShareTotal = (bid, date) => Math.round(F.sum(Q.buildingShares(bid, date), s => Number(s.percentage || 0)) * 100) / 100;
  Q.shareHistory = (bid) => raw('buildingShares').filter(s => s.buildingId === bid).sort((a, b) => F.cmp(b.effectiveFrom, a.effectiveFrom) || F.cmp(b.createdAt || '', a.createdAt || ''));
  Q.shareChangeDates = (bid) => [...new Set(raw('buildingShares').filter(s => s.buildingId === bid).flatMap(s => [s.effectiveFrom, s.effectiveTo ? F.addDays(s.effectiveTo, 1) : null]).filter(Boolean))].sort();
  Q.shareBuildings = () => raw('buildings').filter(b => !b.stub).map(b => { const cur = Q.buildingShares(b.id); const total = Q.buildingShareTotal(b.id); return { b, shares: cur, total, ok: Math.abs(total - 100) < 0.005, count: cur.length, changes: Q.shareChangeDates(b.id).length }; });
  Q.shareholderBuildings = (shId, date) => raw('buildings').filter(b => !b.stub && Q.buildingShares(b.id, date).some(s => s.shareholderId === shId)).map(b => ({ b, share: Q.buildingShares(b.id, date).find(s => s.shareholderId === shId) }));
  Q.shareholderShareHistory = (shId) => raw('buildingShares').filter(s => s.shareholderId === shId).sort((a, b) => F.cmp(b.effectiveFrom, a.effectiveFrom));
  /* ---- Góp vốn theo tòa §4.31 ---- */
  Q.capitalCall = (id) => get('capitalCalls', id);
  Q.capitalLines = (callId) => raw('capitalPayments').filter(l => l.capitalCallId === callId).map(l => Object.assign({}, l, { s: get('shareholders', l.shareholderId), st: Q.capitalLineStatus(l) })).sort((a, b) => b.required - a.required);
  Q.capitalLineStatus = (l) => { const rem = Number(l.required || 0) - Number(l.paid || 0); if (rem <= 0) return 'paid'; const call = get('capitalCalls', l.capitalCallId); if (call.dueDate && call.dueDate < F.today()) return 'overdue'; return Number(l.paid || 0) > 0 ? 'partial' : 'unpaid'; };
  Q.capitalCallStatus = (c) => { if (c.status === 'cancelled') return 'cancelled'; const ls = raw('capitalPayments').filter(l => l.capitalCallId === c.id); if (ls.length && ls.every(l => Number(l.paid || 0) >= Number(l.required || 0))) return 'done'; return c.dueDate < F.today() ? 'overdue' : 'open'; };
  Q.capitalCalls = (f = {}) => raw('capitalCalls').filter(c => (!f.buildingId || c.buildingId === f.buildingId) && (!f.shareholderId || raw('capitalPayments').some(l => l.capitalCallId === c.id && l.shareholderId === f.shareholderId))).map(c => { const ls = raw('capitalPayments').filter(l => l.capitalCallId === c.id); return Object.assign({}, c, { b: get('buildings', c.buildingId), st: Q.capitalCallStatus(c), required: F.sum(ls, l => Number(l.required || 0)), paid: F.sum(ls, l => Number(l.paid || 0)), lines: ls.length }); }).filter(c => !f.status || c.st === f.status).sort((a, b) => F.cmp(b.dueDate, a.dueDate));
  Q.shareholderCapital = (shId, bid, date) => F.sum(raw('capitalPayments').filter(l => l.shareholderId === shId && get('capitalCalls', l.capitalCallId).buildingId === bid && (!date || !l.paidDate || l.paidDate <= date)), l => Number(l.paid || 0));
  Q.capitalStats = (f = {}) => { const cs = Q.capitalCalls(f); return { calls: cs.length, required: F.sum(cs, c => c.required), paid: F.sum(cs, c => c.paid), missing: F.sum(cs, c => Math.max(0, c.required - c.paid)), overdue: cs.filter(c => c.st === 'overdue').length }; };
  /* ---- Phân phối lợi nhuận §4.32 ---- */
  Q.profitDistributions = (f = {}) => raw('profitDistributions').filter(d => (!f.period || d.period === f.period) && (!f.buildingId || d.buildingId === f.buildingId) && (!f.status || d.status === f.status) && (!f.shareholderId || (d.lines || []).some(l => l.shareholderId === f.shareholderId))).map(d => Object.assign({}, d, { b: get('buildings', d.buildingId) })).sort((a, b) => F.cmp(b.period, a.period) || F.cmp(b.createdAt || '', a.createdAt || ''));
  Q.profitDistribution = (id) => get('profitDistributions', id);
  Q.distStats = (f = {}) => { const ds = Q.profitDistributions(f); return { count: ds.length, confirmed: ds.filter(d => d.status === 'confirmed').length, profit: F.sum(ds.filter(d => d.status === 'confirmed'), d => Number(d.profitDistributable || 0)), pending: ds.filter(d => ['draft', 'review'].includes(d.status)).length }; };
  Q.goldenDatasets = () => raw('goldenDatasets').sort((a, b) => F.cmp(a.code, b.code));
  /* Shareholder master §4.29 */
  Q.shareholderRows5 = (f = {}) => raw('shareholders').filter(s => (!f.status || (s.status || 'active') === f.status) && (!f.s || F.norm(s.code + ' ' + s.name + ' ' + (s.email || '') + ' ' + (s.phone || '') + ' ' + (s.idNumber || '') + ' ' + (s.taxCode || '')).includes(F.norm(f.s)))).map(s => { const bs = Q.shareholderBuildings(s.id); const capital = F.sum(bs, x => Q.shareholderCapital(s.id, x.b.id)); const missing = F.sum(raw('capitalPayments').filter(l => l.shareholderId === s.id), l => Math.max(0, Number(l.required || 0) - Number(l.paid || 0))); const profit = F.sum(raw('profitDistributions').filter(d => d.status === 'confirmed'), d => F.sum((d.lines || []).filter(l => l.shareholderId === s.id), l => Number(l.netShare || 0))); return { s, buildings: bs, capital, missing, profit, status: s.status || 'active' }; }).filter(r => !f.buildingId || r.buildings.some(x => x.b.id === f.buildingId)).sort((a, b) => F.cmp(a.s.code, b.s.code));
  const todoPrev = Q.todo; Q.todo = () => { const t = todoPrev(); t.reportReviewing = raw('reportPeriods').filter(p => p.status === 'REVIEWING').length; t.capitalOverdue = raw('capitalCalls').filter(c => Q.capitalCallStatus(c) === 'overdue').length; t.distPending = raw('profitDistributions').filter(d => ['draft', 'review'].includes(d.status)).length; t.metricsPending = TH.metrics && TH.metrics.defs1 ? TH.metrics.defs1().filter(d => d.status === 'NEED_BUSINESS_CONFIRMATION').length : 0; return t; };
})(window.TH);
