/* Phase 3 – Tài sản: Sổ tài sản (#/assets, tự thiết kế), Kiểm kê tài sản (#/assets/inventory – PNG 06/03), Biên bản kiểm kê (#/assets/inventory/:id), tab Tài sản của tòa */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, C = TH.chart, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const bName = (id) => Q.building(id).name || '-';
  const liveB = () => St.where('buildings', b => !b.stub);
  const catOpts = () => Object.entries(Q.L.assetCat).map(([k, v]) => [k, v[0]]);
  const condOpts = () => Object.entries(Q.L.assetCond).map(([k, v]) => [k, v[0]]);
  const roomOpts = (bId) => St.where('rooms', r => r.buildingId === bId).sort((a, b) => a.code.localeCompare(b.code)).map(r => [r.id, r.code]);

  /* ---- Forms ---- */
  Fm.asset = (a = {}, opts = {}) => {
    const bs = liveB(); const bId = a.buildingId || opts.buildingId || (bs[0] || {}).id;
    const m = U.drawer({ title: a.id ? 'Sửa tài sản ' + a.code : 'Thêm tài sản', sub: 'Mã tài sản, tòa, loại, nguyên giá, thời điểm sử dụng, thời gian khấu hao dự kiến (FR-BLD-04)', body: `<div class="form-grid">${U.field({ label: 'Tên tài sản', req: true, input: U.input({ name: 'name', value: a.name || '', placeholder: 'Điều hòa Daikin 1.5HP' }), cls: 'span2' })}${U.field({ label: 'Loại tài sản', req: true, input: U.select({ name: 'category', value: a.category || '', placeholder: 'Chọn loại', options: catOpts() }) })}${U.field({ label: 'Nguồn sở hữu', input: U.select({ name: 'ownership', value: a.ownership || 'company', options: Object.entries(Q.L.ownership) }) })}${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: bId, options: bs.map(b => [b.id, b.name]), attrs: { id: 'as-b' } }) })}${U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: a.roomId || opts.roomId || '', all: 'Khu vực chung', options: roomOpts(bId), attrs: { id: 'as-r' } }), help: 'Để trống nếu là tài sản khu vực chung' })}${U.field({ label: 'Khu vực (nếu không thuộc phòng)', input: U.input({ name: 'area', value: a.roomId ? '' : (a.area || ''), placeholder: 'Sảnh tầng 1 / Hành lang / Tầng hầm' }) })}${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', type: 'number', value: a.qty || 1 }) })}${U.field({ label: 'Nguyên giá (VND)', input: U.money({ name: 'cost', value: a.cost || '' }) })}${U.field({ label: 'Ngày đưa vào sử dụng', input: U.date({ name: 'startDate', value: a.startDate || F.today() }) })}${U.field({ label: 'Số tháng khấu hao dự kiến', input: U.input({ name: 'depMonths', type: 'number', value: a.depMonths || 36 }), help: 'Đường thẳng theo tháng – 3–5 năm là giả định, chờ chốt OI-11' })}${a.id ? '' : U.field({ label: 'Tình trạng ban đầu', input: U.select({ name: 'condition', value: 'good', options: condOpts() }) })}${a.id ? '' : `<div class="field span2">${U.check({ name: 'recordExpense', label: 'Ghi nhận chi phí mua sắm thiết bị (nhóm Mua sắm TS, khấu hao theo số tháng trên – BR-08: tiền mua vào dòng tiền một lần, khấu hao vào kết quả vận hành)', checked: false })}</div>`}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: a.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: a.id ? 'Lưu thay đổi' : 'Thêm tài sản', icon: 'package', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'asset-save' } }) });
    m.el.querySelector('#as-b').addEventListener('change', (e) => { const sel = m.el.querySelector('#as-r'); sel.innerHTML = '<option value="">Khu vực chung</option>' + roomOpts(e.target.value).map(([v, l]) => `<option value="${v}">${esc(l)}</option>`).join(''); });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = a.id; const r = X.saveAsset(d); m.close(); ok((a.id ? 'Đã cập nhật ' : 'Đã thêm tài sản ') + r.code, r.name + (r.expenseId ? ' · đã ghi chi phí mua sắm' : '')); opts.after && opts.after(r); } });
  };
  const condModal = (line, asset, opts = {}) => { // Cập nhật tình trạng khi kiểm kê (FR-MNT-02: người, thời điểm, bằng chứng)
    const m = U.modal({ title: 'Cập nhật tình trạng ' + asset.code, sub: esc(asset.name) + ' · ' + esc(bName(asset.buildingId)) + ' · ' + esc(asset.area || ''), body: `${U.field({ label: 'Tình trạng trước', input: `<div class="mt4">${Q.chip('assetCond', line ? (line.prevCondition || asset.condition) : asset.condition)}</div>` })}${U.field({ label: 'Tình trạng hiện tại', req: true, input: U.select({ name: 'condition', value: (line && line.condition) || asset.condition || 'good', options: condOpts() }), cls: 'mt12' })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: (line && line.note) || '', placeholder: 'Mô tả hư hỏng, vị trí, đề xuất xử lý…' }), cls: 'mt12' })}<div class="field mt12"><label>Ảnh minh chứng</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng) – nên chụp khi tình trạng ≠ Bình thường' })}</div>${U.note('info', '', 'Kết quả kiểm kê chỉ ghi nhận hiện trạng – không tự tạo chi phí hay giảm tài sản (AC-FR-MNT-02-2).')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu kết quả', icon: 'check', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'inv-record-save' } }) });
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); d.photo = U.dzFiles(m.el, 'ph').length > 0; let r; if (line) r = X.recordInventoryLine(line.id, d); else r = X.setAssetCondition(asset.id, d.condition, d.note); m.close(); ok('Đã cập nhật ' + asset.code, Q.label('assetCond', d.condition)); opts.after && opts.after(r); } });
  };
  const assetView = (a) => {
    const last = Q.assetLastLine(a.id); const hist = (a.history || []).slice().reverse().slice(0, 8);
    const m = U.drawer({ title: esc(a.code) + ' – ' + esc(a.name), sub: `${esc(bName(a.buildingId))} · ${esc(a.area || '')} · ${Q.chip('assetCond', a.condition)} ${Q.chip('asset', a.status)}`, wide: true, body: `<div class="two-col"><div class="side-stack">${U.card({ title: 'Thông tin tài sản', icon: 'package', body: U.kv([['Mã tài sản', esc(a.code)], ['Loại', esc(Q.assetCatLabel(a.category))], ['Tòa nhà', esc(bName(a.buildingId))], ['Phòng / khu vực', a.roomId ? U.link('#/rooms/' + a.roomId, esc(Q.room(a.roomId).code || a.area)) : esc(a.area || '-')], ['Số lượng', a.qty], ['Nguồn sở hữu', esc(Q.L.ownership[a.ownership] || '-')], ['Nguyên giá', F.vnd(a.cost || 0)], ['Ngày sử dụng', F.date(a.startDate)], ['Khấu hao dự kiến', (a.depMonths || 0) + ' tháng <span class="muted small">(OI-11)</span>'], ['Giá trị còn lại (tạm tính)', F.vnd(Q.assetRemaining(a))], ['Chi phí mua sắm', a.expenseId ? U.link('#/expenses?s=' + encodeURIComponent((St.get('expenses', a.expenseId) || {}).code || ''), esc((St.get('expenses', a.expenseId) || {}).code || 'Xem')) : '<span class="muted">Không ghi nhận qua sổ</span>'], ['Ghi chú', esc(a.note || '-')]], 'one') })}${U.card({ title: 'Lịch sử tình trạng', icon: 'history', body: hist.length ? U.timeline(hist.map(h => ({ when: F.datetime(h.at), title: ({ create: 'Ghi nhận', edit: 'Cập nhật', condition: 'Đổi tình trạng', inventory: 'Kiểm kê', dispose: 'Thanh lý', expense: 'Chi phí' })[h.type] || h.type, sub: h.text, color: h.type === 'dispose' ? 'red' : h.type === 'inventory' ? 'amber' : 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) })}</div><aside class="side-stack">${U.card({ title: 'Mã QR tài sản', icon: 'qr-code', body: `${U.qrBox(a.qr || a.code)}<div class="tc small muted mt8">${esc(a.qr || a.code)} · quét bằng app mobile khi kiểm kê (mô phỏng)</div>` })}${U.card({ title: 'Kiểm kê gần nhất', icon: 'clipboard-check', body: last ? U.kv([['Đợt', esc(Q.inventory(last.inventoryId).code || '')], ['Kết quả', Q.chip('assetCond', last.condition)], ['Người kiểm kê', esc(last.checkedBy || '-')], ['Thời điểm', F.datetime(last.checkedAt)], ['Ảnh minh chứng', last.photo ? 'Có' : 'Không'], ['Ghi chú', esc(last.note || '-')]], 'one') : '<div class="muted small">Chưa được kiểm kê</div>' })}</aside></div>`, footer: U.btn({ label: 'Đóng', act: 'c' }) + (a.status === 'active' && TH.auth.can('assets.manage') ? U.btn({ label: 'Sửa', icon: 'pencil', cls: 'btn-outline', act: 'e' }) : '') + (a.status === 'active' && (TH.auth.can('inventory.record') || TH.auth.can('assets.manage')) ? U.btn({ label: 'Đổi tình trạng', icon: 'activity', cls: 'btn-primary', act: 'cond' }) : '') });
    U.bind(m.el, { c: () => m.close(), e: () => { m.close(); Fm.asset(a); }, cond: () => { m.close(); condModal(null, a); } });
  };
  const assetMenu = (el, a) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => assetView(a) }, { label: 'Sửa', icon: 'pencil', disabled: !TH.auth.can('assets.manage') || a.status !== 'active', onClick: () => Fm.asset(a) }, { label: 'Đổi tình trạng', icon: 'activity', disabled: a.status !== 'active' || !(TH.auth.can('inventory.record') || TH.auth.can('assets.manage')), onClick: () => condModal(null, a) }, { label: 'In mã QR', icon: 'qr-code', onClick: () => qrModal([a]) }, '-', { label: 'Thanh lý', icon: 'x-circle', danger: true, disabled: !TH.auth.can('assets.manage') || a.status !== 'active', onClick: async () => { const r = await U.confirm({ title: 'Thanh lý ' + a.code + '?', text: 'Tài sản chuyển sang Đã thanh lý, không còn trong đợt kiểm kê mới. Không tự sinh bút toán giảm tài sản (chờ OI-11).', body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Thanh lý', danger: true }); if (r) { X.disposeAsset(a.id, r.reason); ok('Đã thanh lý ' + a.code); } } }]);
  const qrModal = (assets) => { const m = U.modal({ title: 'In mã QR tài sản (' + assets.length + ')', size: 'lg', body: `<div class="grid grid-4">${assets.slice(0, 12).map(a => `<div class="tc small">${U.qrBox(a.qr || a.code, 110)}<b class="mt4" style="display:block">${esc(a.code)}</b><span class="muted">${esc(a.name)}</span></div>`).join('')}</div>${assets.length > 12 ? `<div class="muted small mt8">… và ${assets.length - 12} mã khác</div>` : ''}${U.note('info', '', 'Bản demo mô phỏng mã QR – bản thật xuất PDF tem dán theo tòa/phòng.')}`, footer: U.btn({ label: 'Đóng', act: 'c' }) + U.btn({ label: 'Tải tem QR', icon: 'printer', cls: 'btn-primary', act: 'p' }) }); U.bind(m.el, { c: () => m.close(), p: () => U.fakePdf('Tem QR tai san', assets.map(a => a.code + ' | ' + a.name + ' | ' + bName(a.buildingId) + ' | ' + (a.area || ''))) }); };
  TH.pages.assetView = assetView; TH.pages.assetCondModal = condModal;

  /* ================= #/assets – Sổ tài sản (tự thiết kế) ================= */
  TH.router.register('/assets', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Tài sản' }]);
    const f = { s: q.s || '', buildingId: q.buildingId || '', roomId: q.roomId || '', category: q.category || '', condition: q.condition || '', ownership: q.ownership || '', status: q.status || 'active' };
    const rows = Q.filterAssets(f).sort((a, b) => F.cmp(a.code, b.code)); const st = Q.assetStats({ buildingId: f.buildingId }); const inv = Q.latestInventory(); const invSt = Q.inventoryStats(inv);
    root.innerHTML = `${U.pageHead({ title: 'Tài sản', phase: 3, sub: 'Danh mục tài sản theo tòa/phòng, mã QR, nguyên giá và khấu hao dự kiến (FR-BLD-04). ' + U.demoNote('<span class="chip gray">Tự thiết kế – không có PNG</span>') + '', acts: [U.btn({ label: 'Thêm tài sản', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !TH.auth.can('assets.manage'), attrs: { 'data-guide': 'asset-add' } }), U.btn({ label: 'In mã QR', icon: 'qr-code', cls: 'btn-outline', act: 'qr' }), U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Mã, tên tài sản, khu vực…', icon: 'search', attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: liveB().map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại tài sản', input: U.select({ name: 'category', value: f.category, all: 'Tất cả loại', options: catOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tình trạng', input: U.select({ name: 'condition', value: f.condition, all: 'Tất cả tình trạng', options: condOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Nguồn sở hữu', input: U.select({ name: 'ownership', value: f.ownership, all: 'Tất cả', options: Object.entries(Q.L.ownership), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.asset).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng tài sản', value: st.total, cap: 'Tại ' + st.buildings + ' tòa nhà', icon: 'package', tone: 'blue' })}${U.kpi({ label: 'Nguyên giá', value: F.vnd(st.cost), cap: 'VND – tổng giá trị đầu tư', icon: 'coins', tone: 'green' })}${U.kpi({ label: 'Giá trị còn lại', value: F.vnd(st.remaining), cap: 'Khấu hao đường thẳng – tạm tính (OI-11)', icon: 'trending-down', tone: 'amber' })}${U.kpi({ label: 'Cần thay thế / hỏng', value: st.bad, cap: st.minor + ' hư hỏng nhẹ', icon: 'alert-triangle', tone: 'red', valueCls: st.bad ? 'red' : '' })}</div>
    ${U.relatedStrip({ id: 'assets-related', cls: 'mb16', items: [
      { key: 'by-cat', title: 'Cơ cấu theo loại', icon: 'chart-pie', summary: st.total + ' tài sản · ' + st.byCat.length + ' nhóm', meta: st.byCat.length ? 'Nhiều nhất: ' + esc(st.byCat.slice().sort((a, b) => b.value - a.value)[0].label) : 'Chưa có tài sản', body: C.donutLegend(st.byCat, 140, String(st.total), 'tài sản') },
      { key: 'by-building', title: 'Tài sản theo tòa', icon: 'building', summary: st.buildings + ' tòa nhà', meta: st.byBuilding.length ? 'Nhiều nhất: ' + esc(st.byBuilding.slice().sort((a, b) => b.value - a.value)[0].label) : '', body: C.vbar({ items: st.byBuilding, height: 180 }) },
      { key: 'inventory', title: 'Kiểm kê kỳ này', icon: 'clipboard-check', summary: inv ? esc(inv.code) + ' ' + Q.chip('inventory', inv.status) : 'Chưa có đợt kiểm kê', meta: inv ? `${invSt.checked}/${invSt.total} đã kiểm kê · ${invSt.needsAction} cần xử lý` : 'Mở Kiểm kê tài sản để bắt đầu', actions: `<a class="link small" href="#/assets/inventory">Mở kiểm kê →</a>`, body: inv ? `<div class="row between"><b>${esc(inv.code)}</b>${Q.chip('inventory', inv.status)}</div>${U.progress(invSt.total ? invSt.checked / invSt.total * 100 : 0)}<div class="small muted mt8">${invSt.checked}/${invSt.total} đã kiểm kê · ${invSt.needsAction} cần xử lý · ${invSt.broken} hư hỏng</div>` : U.empty({ title: 'Chưa có đợt kiểm kê' }) }
    ] })}
    ${U.card({ title: 'Danh sách tài sản (' + rows.length + ')', icon: 'list', actions: U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', cls: 'btn-ghost', act: 'cols' }), body: null, id: 'at', attrs: 'data-guide="assets-table"' })}`;
    const cols = [{ key: 'code', label: 'Mã', sortable: true, render: a => `<a class="link bold" data-act="view" data-id="${a.id}" href="#/assets?s=${a.code}">${esc(a.code)}</a>` }, { key: 'name', label: 'Tên tài sản', sortable: true, render: a => `<div class="row gap8">${U.thumb(a, 32)}${U.cell2(esc(a.name), esc(Q.assetCatLabel(a.category)))}</div>` }, { key: 'building', label: 'Tòa', sortable: true, sortVal: a => bName(a.buildingId), render: a => esc(bName(a.buildingId)) }, { key: 'area', label: 'Phòng / Khu vực', render: a => a.roomId ? U.link('#/rooms/' + a.roomId, esc(a.area)) : esc(a.area || '-') }, { key: 'cost', label: 'Nguyên giá', num: true, sortable: true, render: a => F.vnd(a.cost || 0) }, { key: 'startDate', label: 'Ngày dùng', sortable: true, render: a => F.date(a.startDate) }, { key: 'depMonths', label: 'KH (tháng)', num: true, render: a => a.depMonths || '-' }, { key: 'remaining', label: 'Còn lại', num: true, sortable: true, sortVal: a => Q.assetRemaining(a), render: a => F.vnd(Q.assetRemaining(a)) }, { key: 'condition', label: 'Tình trạng', sortable: true, render: a => Q.chip('assetCond', a.condition) + (a.status === 'disposed' ? ' ' + Q.chip('asset', 'disposed') : '') }, { key: 'actions', label: 'Thao tác', render: a => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': a.id } }), U.moreBtn(a.id)]), hideable: false }];
    const tbl = U.table(root.querySelector('#at'), { rows, unit: 'tài sản', selectable: true, colPrefsKey: 'assets', cols });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, add: () => Fm.asset({}, { buildingId: f.buildingId }), view: (el) => assetView(St.get('assets', el.dataset.id)), more: (el) => assetMenu(el, St.get('assets', el.dataset.id)), cols: (b) => U.columnMenu(b, tbl, cols), qr: () => { const ids = tbl.selected(); const list = ids.length ? ids.map(id => St.get('assets', id)) : rows.slice(0, 12); qrModal(list); }, export: () => { F.download('so-tai-san.csv', F.csv(rows.map(a => [a.code, a.name, Q.assetCatLabel(a.category), bName(a.buildingId), a.area, a.qty, a.cost || 0, a.startDate, a.depMonths, Q.assetRemaining(a), Q.label('assetCond', a.condition), Q.label('asset', a.status)]), ['Mã', 'Tên', 'Loại', 'Tòa', 'Phòng/Khu vực', 'SL', 'Nguyên giá', 'Ngày dùng', 'KH tháng', 'Còn lại', 'Tình trạng', 'Trạng thái']), 'text/csv'); ok('Đã xuất danh sách tài sản'); } });
  }, { menu: 'assets', permission: 'assets.view', phase: 3, scopeKey: 'assets' });

  /* ================= #/assets/inventory – Kiểm kê tài sản (PNG 06/03) ================= */
  const startModal = (period) => {
    const m = U.modal({ title: 'Bắt đầu kiểm kê', sub: 'Đợt kiểm kê hàng tháng – Admin/Kế toán phụ trách (FR-MNT-02, BR-16)', body: `${U.field({ label: 'Kỳ kiểm kê', req: true, input: U.select({ name: 'period', value: period, options: Q.inventoryPeriods().map(x => [x, F.periodLabel(x)]) }) })}<div class="field mt12"><label>Tòa nhà</label><div class="grid grid-2">${liveB().map(b => U.check({ name: 'b_' + b.id, label: esc(b.name) + ' <span class="muted small">(' + St.where('assets', a => a.buildingId === b.id && a.status === 'active').length + ' tài sản)</span>', checked: true })).join('')}</div></div>${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', placeholder: 'Phạm vi, người phụ trách…' }), cls: 'mt12' })}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Bắt đầu kiểm kê', icon: 'play', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'inv-start-save' } }) });
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const ids = liveB().filter(b => d['b_' + b.id]).map(b => b.id); const r = X.startInventory({ period: d.period, buildingIds: ids, note: d.note }); m.close(); if (r.existed) U.toast('info', 'Đã mở đợt ' + r.code, 'Kỳ này đang kiểm kê – tiếp tục cập nhật'); else ok('Đã tạo ' + r.code, Q.inventoryStats(r).total + ' tài sản cần kiểm kê'); TH.router.replaceQuery({ period: d.period }); TH.router.refresh(); } });
  };
  const lineMenu = (el, line, asset, inv) => U.menu(el, [{ label: 'Xem tài sản', icon: 'eye', onClick: () => assetView(asset) }, { label: 'Cập nhật tình trạng', icon: 'clipboard-check', disabled: inv.status === 'done' || !TH.auth.can('inventory.record', { buildingId: asset.buildingId }), onClick: () => condModal(line, asset) }, { label: 'Tạo sự cố từ kết quả', icon: 'wrench', phase: 2, disabled: line.status !== 'needs_action', onClick: () => { const inc = X.incidentFromLine(line.id); ok('Đã tạo sự cố ' + inc.code, 'Xem ở Bảo trì - Sửa chữa'); } }, { label: 'In mã QR', icon: 'qr-code', onClick: () => qrModal([asset]) }]);
  TH.router.register('/assets/inventory', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Tài sản', href: '#/assets' }, { label: 'Kiểm kê tài sản' }]);
    const periods = Q.inventoryPeriods(); const period = q.period || (Q.latestInventory() || {}).period || St.state.meta.period; const inv = Q.inventoryOf(period);
    const f = { buildingId: q.buildingId || '', area: q.area || '', category: q.category || '', status: q.status || '', s: q.s || '' };
    const rows = Q.inventoryLines(inv, f).sort((a, b) => F.cmp(a.asset.code, b.asset.code)); const st = Q.inventoryStats(inv); const latest = inv || Q.latestInventory(); const lst = Q.inventoryStats(latest);
    const canManage = TH.auth.can('inventory.manage'); const pctChecked = st.total ? F.pct(st.checked, st.total) : 0;
    root.innerHTML = `${U.pageHead({ title: 'Kiểm kê tài sản', phase: 3, sub: 'Quản lý và theo dõi hoạt động kiểm kê tài sản định kỳ theo tháng.', acts: [U.btn({ label: 'Bắt đầu kiểm kê', icon: 'plus', cls: 'btn-primary', act: 'start', disabled: !canManage, attrs: { 'data-guide': 'inv-start' } }), latest && latest.status === 'in_progress' && canManage ? U.btn({ label: 'Hoàn tất kiểm kê', icon: 'check', cls: 'btn-outline', act: 'finish', attrs: { 'data-id': latest.id, 'data-guide': 'inv-finish' } }) : '', U.btn({ label: 'Xuất biên bản', icon: 'download', cls: 'btn-outline', act: 'export-report', disabled: !inv })] })}
    ${U.filterbar([U.field({ label: 'Kỳ kiểm kê', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: liveB().map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Khu vực', input: U.select({ name: 'area', value: f.area, all: 'Tất cả khu vực', options: [['room', 'Trong phòng'], ['common', 'Khu vực chung']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại tài sản', input: U.select({ name: 'category', value: f.category, all: 'Tất cả loại tài sản', options: catOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái kiểm kê', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.invLine).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tài sản', value: st.total, cap: 'Tại ' + (st.buildings || liveB().length) + ' tòa nhà', icon: 'package', tone: 'blue' })}${U.kpi({ label: 'Đã kiểm kê', value: st.checked, cap: pctChecked + '% tổng tài sản', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Cần xử lý', value: st.needsAction, cap: F.pct(st.needsAction, st.total) + '% tổng tài sản', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Hư hỏng', value: st.broken, cap: F.pct(st.broken, st.total) + '% tổng tài sản', icon: 'alert-triangle', tone: 'red', valueCls: st.broken ? 'red' : '' })}</div>
    ${U.relatedStrip({ id: 'inventory-related', cls: 'mb16', items: [
      { key: 'latest', title: 'Biên bản kiểm kê gần nhất', icon: 'file-text', summary: latest ? esc(latest.code) + ' ' + Q.chip('inventory', latest.status) : 'Chưa có biên bản', meta: latest ? `${lst.checked}/${lst.total} đã kiểm kê · ${lst.needsAction} cần xử lý · ${lst.broken} hư hỏng` : 'Bấm "Bắt đầu kiểm kê" để tạo đợt', actions: `<a class="link small" href="#/assets/inventory?period=${latest ? latest.period : period}">Xem tất cả →</a>`, body: latest ? `<div class="row gap12 mb12"><div class="thumb" style="width:44px;height:44px;background:var(--blue-bg);color:var(--blue)">${I('clipboard-list')}</div><div class="grow"><b>Biên bản kiểm kê ${F.periodLabel(latest.period).toLowerCase()}</b><div class="mt4">${Q.chip('inventory', latest.status)}</div></div></div>${U.kv([['Mã biên bản', esc(latest.code)], ['Thời gian', F.date(latest.startDate) + ' – ' + (latest.finishedAt ? F.date(latest.finishedAt) : 'nay')], ['Tổng tài sản', lst.total], ['Đã kiểm kê', lst.checked + ' (' + F.pct(lst.checked, lst.total) + '%)'], ['Cần xử lý', lst.needsAction + ' (' + F.pct(lst.needsAction, lst.total) + '%)'], ['Hư hỏng', lst.broken + ' (' + F.pct(lst.broken, lst.total) + '%)'], ['Người lập', esc(Q.userName(latest.createdBy))], ['Ngày lập', F.datetime(latest.createdAt)]])}<div class="row gap8 mt12">${U.btn({ label: 'Xem biên bản', icon: 'file-text', cls: 'btn-outline', act: 'open-report', attrs: { 'data-id': latest.id } })}${latest.status === 'in_progress' && canManage ? U.btn({ label: 'Hoàn tất kiểm kê', icon: 'check', cls: 'btn-primary', act: 'finish', attrs: { 'data-id': latest.id } }) : ''}</div>` : '<div class="muted small">Chưa có biên bản</div>' },
      { key: 'guide', title: 'Hướng dẫn kiểm kê', icon: 'info', summary: '4 bước', meta: 'Bắt đầu → kiểm tra → ảnh minh chứng → hoàn tất', body: `<ol class="guide-steps"><li>Chọn tháng kiểm kê và nhấn "Bắt đầu kiểm kê".</li><li>Kiểm tra thực tế từng tài sản và cập nhật tình trạng.</li><li>Chụp ảnh minh chứng (nếu cần).</li><li>Hoàn tất kiểm kê và xuất biên bản.</li></ol><a class="link small" data-act="open-guide" data-flow="F16">Xem hướng dẫn chi tiết →</a>` },
      { key: 'tips', title: 'Mẹo sử dụng', icon: 'check-circle', summary: 'Quét QR bằng mobile', meta: 'Bản demo: mở tài sản → "In mã QR"', body: '<div class="small">Bạn có thể sử dụng ứng dụng mobile để quét mã QR tài sản khi kiểm kê để nhanh chóng cập nhật thông tin. Bản demo: mở tài sản → "In mã QR".</div>' }
    ] })}
    ${inv ? U.card({ title: 'Danh sách tài sản (' + rows.length + ' tài sản)', icon: 'list', actions: U.btn({ label: 'Đánh dấu Bình thường (đã chọn)', icon: 'check', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-good', disabled: inv.status === 'done' || !TH.auth.can('inventory.record') }), body: null, id: 'it', attrs: 'data-guide="inventory-table"' }) : U.card({ body: U.empty({ icon: 'clipboard-check', title: 'Chưa có đợt kiểm kê ' + F.periodLabel(period), text: 'Chọn tháng khác hoặc bấm "Bắt đầu kiểm kê" để tạo đợt kiểm kê cho kỳ này (Admin/Kế toán).', action: canManage ? U.btn({ label: 'Bắt đầu kiểm kê', icon: 'plus', cls: 'btn-primary', size: 'btn-sm', act: 'start' }) : '' }) })}`;
    let tbl = null;
    if (inv) tbl = U.table(root.querySelector('#it'), { rows, unit: 'tài sản', selectable: true, selectableIf: r => r.line.status === 'pending', rowKey: r => r.line.id, colPrefsKey: 'inventory', cols: [{ key: 'code', label: 'Mã tài sản', sortable: true, sortVal: r => r.asset.code, render: r => `<a class="link bold" data-act="view" data-id="${r.asset.id}" href="#/assets/inventory">${esc(r.asset.code)}</a>` }, { key: 'name', label: 'Tên tài sản', sortable: true, sortVal: r => r.asset.name, render: r => esc(r.asset.name) }, { key: 'building', label: 'Tòa nhà', sortable: true, sortVal: r => bName(r.asset.buildingId), render: r => esc(bName(r.asset.buildingId)) }, { key: 'area', label: 'Khu vực', render: r => esc(r.asset.area || '-') }, { key: 'prev', label: 'Tình trạng trước', render: r => Q.chip('assetCond', r.line.prevCondition || 'good') }, { key: 'cond', label: 'Tình trạng hiện tại', sortable: true, sortVal: r => r.line.condition || 'zz', render: r => r.line.condition ? Q.chip('assetCond', r.line.condition) : '<span class="muted">—</span>' }, { key: 'by', label: 'Người kiểm kê', render: r => r.line.checkedBy ? U.avatarCell({ name: r.line.checkedBy }) : '<span class="muted">—</span>' }, { key: 'at', label: 'Ngày kiểm kê', sortable: true, sortVal: r => r.line.checkedAt || '', render: r => r.line.checkedAt ? F.date(r.line.checkedAt) : '<span class="muted">—</span>' }, { key: 'photo', label: 'Ảnh', render: r => r.line.photo ? U.thumb(r.asset, 36) : `<div class="thumb" style="width:36px;height:36px;background:var(--gray-bg);color:var(--muted)" title="Chưa có ảnh">${I('camera')}</div>` }, { key: 'status', label: 'Trạng thái', sortable: true, sortVal: r => r.line.status, render: r => Q.chip('invLine', r.line.status) }, { key: 'actions', label: 'Thao tác', render: r => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'record', attrs: { 'data-id': r.line.id, 'data-guide': r.line.status === 'pending' ? 'inv-record' : '' } }), U.moreBtn(r.line.id)]), hideable: false }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ period }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { 'open-guide': (el) => TH.guide && TH.guide.open(el.dataset.flow), reset: () => { TH.router.replaceQuery({ period }); TH.router.refresh(); }, start: () => startModal(period), view: (el) => assetView(St.get('assets', el.dataset.id)), record: (el) => { const l = St.get('inventoryLines', el.dataset.id); const a = St.get('assets', l.assetId); if (inv.status === 'done' || !TH.auth.can('inventory.record', { buildingId: a.buildingId })) assetView(a); else condModal(l, a); }, more: (el) => { const l = St.get('inventoryLines', el.dataset.id); lineMenu(el, l, St.get('assets', l.assetId), inv); }, 'bulk-good': () => { const ids = tbl ? tbl.selected() : []; if (!ids.length) return U.toast('warn', 'Chọn tài sản chưa kiểm kê'); const n = X.bulkInventoryGood(ids); ok('Đã ghi nhận ' + n + ' tài sản Bình thường'); }, 'open-report': (el) => TH.go('#/assets/inventory/' + el.dataset.id), finish: async (el) => { const i = St.get('inventories', el.dataset.id); const s = Q.inventoryStats(i); if (await U.confirm({ title: 'Hoàn tất ' + i.code + '?', text: `${s.checked}/${s.total} tài sản đã kiểm kê (${s.pending} chưa kiểm). Sau khi hoàn tất không sửa kết quả; biên bản dùng để xuất và lưu trữ. Không tạo chi phí hay giảm tài sản (AC-FR-MNT-02-2).`, ok: 'Hoàn tất' })) { X.finishInventory(i.id); ok('Đã hoàn tất ' + i.code); } }, 'export-report': () => { if (!inv) return; const n = X.exportInventory(inv.id); ok('Đã xuất biên bản ' + inv.code, n + ' dòng (CSV)'); } });
  }, { menu: 'inventory', permission: 'inventory.view', phase: 3, scopeKey: 'inventory' });

  /* ================= #/assets/inventory/:id – Biên bản kiểm kê ================= */
  TH.router.register('/assets/inventory/:id', (root, p) => {
    const inv = St.get('inventories', p.id); if (!inv) { root.innerHTML = U.empty({ title: 'Không tìm thấy biên bản' }); return; }
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Tài sản', href: '#/assets' }, { label: 'Kiểm kê tài sản', href: '#/assets/inventory' }, { label: inv.code }]);
    const st = Q.inventoryStats(inv); const rows = Q.inventoryLines(inv); const byB = (inv.buildingIds || []).map(id => { const ls = rows.filter(r => r.asset.buildingId === id); return { id, name: bName(id), total: ls.length, checked: ls.filter(r => r.line.status !== 'pending').length, na: ls.filter(r => r.line.status === 'needs_action').length, broken: ls.filter(r => ['replace', 'broken', 'lost'].includes(r.line.condition)).length }; });
    const canManage = TH.auth.can('inventory.manage');
    root.innerHTML = `${U.pageHead({ back: '#/assets/inventory?period=' + inv.period, title: esc(inv.code), phase: 3, chips: ' ' + Q.chip('inventory', inv.status, 'lg'), sub: `Biên bản kiểm kê ${F.periodLabel(inv.period).toLowerCase()} • ${(inv.buildingIds || []).length} tòa • Lập ${F.datetime(inv.createdAt)} bởi ${esc(Q.userName(inv.createdBy))}`, acts: [U.btn({ label: 'Xuất biên bản', icon: 'download', cls: 'btn-outline', act: 'export-report' }), inv.status === 'in_progress' && canManage ? U.btn({ label: 'Hoàn tất kiểm kê', icon: 'check', cls: 'btn-primary', act: 'finish', attrs: { 'data-guide': 'inv-finish' } }) : ''] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tài sản', value: st.total, cap: 'Trong phạm vi kiểm kê', icon: 'package', tone: 'blue' })}${U.kpi({ label: 'Đã kiểm kê', value: st.checked, cap: F.pct(st.checked, st.total) + '%', icon: 'check-circle', tone: 'green', bar: F.pct(st.checked, st.total) })}${U.kpi({ label: 'Cần xử lý', value: st.needsAction, cap: 'Tình trạng ≠ Bình thường', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Hư hỏng', value: st.broken, cap: 'Cần thay thế / hỏng / mất', icon: 'alert-triangle', tone: 'red' })}</div>
    ${U.relatedStrip({ id: 'inventory-detail-related', cls: 'mb16', items: [
      { key: 'info', title: 'Thông tin biên bản', icon: 'file-text', summary: F.periodLabel(inv.period) + ' · ' + (inv.buildingIds || []).length + ' tòa', meta: 'Người lập: ' + esc(Q.userName(inv.createdBy)) + (inv.finishedBy ? ' · Hoàn tất: ' + esc(Q.userName(inv.finishedBy)) : ''), body: U.kv([['Mã biên bản', esc(inv.code)], ['Kỳ', F.periodLabel(inv.period)], ['Thời gian', F.date(inv.startDate) + ' – ' + (inv.finishedAt ? F.date(inv.finishedAt) : 'đang thực hiện')], ['Người lập', esc(Q.userName(inv.createdBy))], ['Người hoàn tất', inv.finishedBy ? esc(Q.userName(inv.finishedBy)) : '-'], ['Ghi chú', esc(inv.note || '-')]]) },
      { key: 'timeline', title: 'Tiến trình', icon: 'history', summary: inv.finishedAt ? 'Đã hoàn tất' : st.checked ? 'Đang ghi kết quả' : 'Mới bắt đầu', meta: st.checked + '/' + st.total + ' tài sản đã kiểm kê', body: U.timeline([{ when: F.datetime(inv.createdAt), title: 'Bắt đầu kiểm kê', sub: Q.userName(inv.createdBy), color: 'blue', fill: true }, { when: rows.filter(r => r.line.checkedAt).length ? F.datetime(rows.filter(r => r.line.checkedAt).sort((a, b) => F.cmp(b.line.checkedAt, a.line.checkedAt))[0].line.checkedAt) : '', title: 'Ghi kết quả', sub: st.checked + '/' + st.total + ' tài sản', color: 'amber', fill: st.checked > 0 }, { when: inv.finishedAt ? F.datetime(inv.finishedAt) : '', title: 'Hoàn tất', sub: inv.finishedAt ? Q.userName(inv.finishedBy) : 'Chưa hoàn tất', color: 'green', fill: !!inv.finishedAt }]) },
      { key: 'rule', title: 'Quy tắc', icon: 'shield-check', summary: 'Không tự tạo chi phí', meta: 'FR-MNT-02 · đề xuất xử lý → tạo sự cố (Phase 2)', body: U.note('info', 'Quy tắc', 'Kết quả kiểm kê không tự chuyển thành chi phí hoặc giảm tài sản trước quyết định hợp lệ (FR-MNT-02). Đề xuất xử lý → tạo sự cố (Phase 2).') }
    ] })}
    <div class="side-stack">${U.card({ title: 'Kết quả theo tòa', icon: 'building', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Tòa nhà</th><th class="num">Tài sản</th><th class="num">Đã kiểm</th><th class="num">Cần xử lý</th><th class="num">Hư hỏng</th><th>Tiến độ</th></tr></thead><tbody>${byB.map(b => `<tr><td><b>${esc(b.name)}</b></td><td class="num">${b.total}</td><td class="num">${b.checked}</td><td class="num ${b.na ? 'amber bold' : ''}">${b.na}</td><td class="num ${b.broken ? 'red bold' : ''}">${b.broken}</td><td>${U.progress(F.pct(b.checked, b.total), b.checked === b.total ? 'green' : '')}</td></tr>`).join('')}</tbody></table></div>` })}
    ${U.card({ title: 'Tài sản cần xử lý (' + st.needsAction + ')', icon: 'alert-triangle', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Mã</th><th>Tên</th><th>Tòa / khu vực</th><th>Tình trạng</th><th>Người kiểm kê</th><th>Ghi chú</th><th></th></tr></thead><tbody>${rows.filter(r => r.line.status === 'needs_action').map(r => `<tr><td><a class="link bold" data-act="view" data-id="${r.asset.id}" href="#/assets/inventory/${inv.id}">${esc(r.asset.code)}</a></td><td>${esc(r.asset.name)}</td><td>${U.cell2(esc(bName(r.asset.buildingId)), esc(r.asset.area || ''))}</td><td>${Q.chip('assetCond', r.line.condition)}</td><td>${esc(r.line.checkedBy || '')}</td><td class="small muted">${esc(r.line.note || '')}</td><td class="tr">${r.line.incidentId ? U.link('#/maintenance/incidents/' + r.line.incidentId, 'Sự cố', 'small') : U.btn({ label: 'Tạo sự cố', size: 'btn-sm', cls: 'btn-ghost', act: 'inc', phase: 2, attrs: { 'data-id': r.line.id } })}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Không có tài sản cần xử lý</td></tr>'}</tbody></table></div>` })}</div>`;
    U.bind(root, { view: (el) => assetView(St.get('assets', el.dataset.id)), inc: (el) => { const inc = X.incidentFromLine(el.dataset.id); ok('Đã tạo sự cố ' + inc.code); }, finish: async () => { if (await U.confirm({ title: 'Hoàn tất ' + inv.code + '?', text: `${st.checked}/${st.total} đã kiểm kê. Sau khi hoàn tất không sửa kết quả.`, ok: 'Hoàn tất' })) { X.finishInventory(inv.id); ok('Đã hoàn tất ' + inv.code); } }, 'export-report': () => { const n = X.exportInventory(inv.id); ok('Đã xuất biên bản', n + ' dòng'); } });
  }, { menu: 'inventory', permission: 'inventory.view', phase: 3, scopeKey: 'inventory', resource: { type: 'inventory' } });

  /* ---- Tab Tài sản ở chi tiết tòa (buildings.js) ---- */
  TH.pages.buildingAssetsTab = (body, b) => {
    const rows = St.where('assets', a => a.buildingId === b.id && a.status === 'active').sort((x, y) => F.cmp(x.code, y.code)); const st = Q.assetStats({ buildingId: b.id }); const inv = Q.latestInventory(); const lines = inv ? Q.inventoryLines(inv, { buildingId: b.id }) : [];
    body.innerHTML = `<div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tài sản', value: st.total, cap: st.byCat.length + ' nhóm', icon: 'package', tone: 'blue', mini: true })}${U.kpi({ label: 'Nguyên giá', value: F.vnd(st.cost), cap: 'VND', icon: 'coins', tone: 'green', mini: true })}${U.kpi({ label: 'Giá trị còn lại', value: F.vnd(st.remaining), cap: 'Tạm tính (OI-11)', icon: 'trending-down', tone: 'amber', mini: true })}${U.kpi({ label: 'Cần xử lý', value: st.bad + st.minor, cap: st.bad + ' hư hỏng', icon: 'alert-triangle', tone: 'red', mini: true })}</div>
    ${U.card({ title: 'Tài sản chủ nhà <span class="muted" style="font-weight:400">(' + rows.filter(a => a.ownership === 'landlord').length + ')</span>', sub: 'Thuộc sở hữu chủ nhà theo hợp đồng thuê tòa – không tính vào vốn/ROI của công ty.', icon: 'home', body: null, id: 'bat-landlord', cls: 'mb16' })}
    ${U.card({ title: 'Tài sản đầu tư <span class="muted" style="font-weight:400">(' + rows.filter(a => a.ownership !== 'landlord').length + ')</span> ' + TH.phase.tag(3), sub: 'Công ty/cổ đông đầu tư – tính vào nguyên giá tài sản và ROI.', icon: 'package', actions: U.btn({ label: 'Kiểm kê tòa này', icon: 'clipboard-check', size: 'btn-sm', cls: 'btn-outline', act: 'go-inv' }) + U.btn({ label: 'Thêm tài sản', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-asset3', disabled: !TH.auth.can('assets.manage', { buildingId: b.id }) }), body: null, id: 'bat-company' })}`;
    // Hai lưới tách theo quyền sở hữu (workbook: "danh sách chủ nhà và danh sách đầu tư"), dùng chung bộ cột.
    const assetCols = [{ key: 'code', label: 'Mã', render: a => `<a class="link bold" data-act="view-asset" data-id="${a.id}" href="#/buildings/${b.id}?tab=assets">${esc(a.code)}</a>` }, { key: 'name', label: 'Tên', render: a => `<div class="row gap8">${U.thumb(a, 30)}${esc(a.name)}</div>` }, { key: 'area', label: 'Phòng / khu vực', render: a => esc(a.area || '-') }, { key: 'cost', label: 'Nguyên giá', num: true, render: a => F.vnd(a.cost || 0) }, { key: 'condition', label: 'Tình trạng', render: a => Q.chip('assetCond', a.condition) }, { key: 'inv', label: 'Kiểm kê ' + (inv ? F.periodShort ? F.periodShort(inv.period) : inv.period : ''), render: a => { const l = lines.find(x => x.asset.id === a.id); return l ? Q.chip('invLine', l.line.status) : '<span class="muted">—</span>'; } }];
    U.table(body.querySelector('#bat-landlord'), { rows: rows.filter(a => a.ownership === 'landlord'), unit: 'tài sản', pageSize: 5, cols: assetCols, empty: U.empty({ icon: 'home', title: 'Chưa ghi nhận tài sản chủ nhà', text: 'Thêm tài sản và chọn Quyền sở hữu = Chủ nhà.' }) });
    U.table(body.querySelector('#bat-company'), { rows: rows.filter(a => a.ownership !== 'landlord'), unit: 'tài sản', pageSize: 10, cols: assetCols });
    body.addEventListener('click', (e) => { const el = e.target.closest('[data-act]'); if (!el) return; if (el.dataset.act === 'view-asset') { e.preventDefault(); assetView(St.get('assets', el.dataset.id)); } if (el.dataset.act === 'go-inv') TH.go('#/assets/inventory?buildingId=' + b.id); if (el.dataset.act === 'add-asset3') Fm.asset({}, { buildingId: b.id }); });
  };
})(window.TH);
