/* Phase 1 – Phân công tòa nhà: single source of truth cho quản lý tòa (spec v1.8 §4.25, §12.19).
   Views: Hiện tại / Sắp tới / Chờ duyệt / Lịch sử; Thay đổi quản lý (§4.25.4); điều chuyển hàng loạt; cảnh báo tòa thiếu Phụ trách chính & trùng thời gian; export. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const canM = () => TH.auth.can('assignments.manage'), canA = () => TH.auth.can('assignments.approve');
  const roleOpts = () => (Q.md('assignmentRole').length ? Q.md('assignmentRole').map(m => [m.code, m.name]) : Object.entries(Q.L.assignRole).filter(([k]) => k !== 'ops').map(([k, v]) => [k, v[0]]));
  const empOpts = (unitId) => Q.employeeOptions({ orgUnitId: unitId || '' });
  const liveB = () => St.rawAll('buildings').filter(b => b && !b.stub && b.status !== 'inactive');
  const roleChip = (r) => Q.chip('assignRole', r);

  /* ---- Drawer: Thay đổi quản lý / tạo phân công (§4.25.4) ---- */
  const assignForm = (pre = {}) => {
    const b = pre.buildingId ? Q.building(pre.buildingId) : null; const cur = b ? Q.buildingManager(b.id) : {}; const up = b ? Q.upcomingManager(b.id) : null;
    const m = U.drawer({ title: pre.role === 'manager' || !pre.role ? 'Thay đổi quản lý tòa' : 'Tạo phân công', sub: 'Chọn tòa → nhân viên → vai trò → ngày hiệu lực → lý do → gửi duyệt / xác nhận (§4.25.4)', wide: true, body: `<div class="form-grid">
      ${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: pre.buildingId || '', placeholder: 'Chọn tòa', options: liveB().map(x => [x.id, x.name + ' · ' + x.code]), attrs: { 'data-on': 'bld' } }), cls: 'span2' })}
      <div class="span2" id="af-current">${b ? U.note('info', 'Quản lý hiện tại: ' + esc(cur.name || 'Chưa phân công'), up ? 'Đã có kế hoạch: ' + esc(up.name) + ' từ ' + F.date(up.assignment.start) + ' – phân công mới sẽ thay thế kế hoạch này nếu trùng.' : 'Phụ trách chính mới sẽ tự kết thúc phân công của người cũ vào ngày hiệu lực − 1 (§4.25.5).') : ''}</div>
      ${U.field({ label: 'Lọc theo đơn vị', input: U.select({ name: 'orgUnitId', value: pre.orgUnitId || '', all: 'Tất cả đơn vị', options: Q.orgOptions(), attrs: { 'data-on': 'unit' } }) })}
      ${U.field({ label: 'Nhân viên', req: true, input: U.select({ name: 'employeeId', value: pre.employeeId || '', placeholder: 'Chọn nhân viên', options: empOpts(pre.orgUnitId) }) })}
      ${U.field({ label: 'Vai trò phân công', req: true, input: U.select({ name: 'role', value: pre.role || 'manager', options: roleOpts() }), help: 'Chỉ Phụ trách chính quyết định Quản lý tòa trong Dashboard, báo cáo, công nợ, bảng lương (§4.25.2)' })}
      ${U.field({ label: 'Phạm vi phòng (nếu ngoại lệ)', input: U.input({ name: 'roomScope', value: pre.roomScope || '', placeholder: 'VD: Tầng 1–3' }) })}
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'start', value: pre.start || F.today() }), help: 'Phân công tương lai không đổi quản lý hiện tại trước ngày này' })}
      ${U.field({ label: 'Đến ngày (tùy chọn)', input: U.date({ name: 'end', value: pre.end || '' }) })}
      ${U.field({ label: 'Lý do thay đổi / điều chuyển', req: true, input: U.textarea({ name: 'reason', value: pre.reason || '', rows: 2, placeholder: 'Bắt buộc – lưu audit (§4.25.1)' }), cls: 'span2' })}
      ${U.field({ label: 'Ghi chú', input: U.input({ name: 'note', value: pre.note || '' }), cls: 'span2' })}</div>
      ${U.note('warn', 'Workflow', 'Dự thảo → Chờ duyệt → Đã duyệt → Đang hiệu lực → Hết hiệu lực. Admin/Quản lý Tổng có thể "Xác nhận ngay"; TPVH/Nhân sự gửi duyệt (§4.25.6).')}`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Gửi duyệt', icon: 'send', act: 'submit', cls: canA() ? 'btn-outline' : 'btn-primary', attrs: { 'data-guide': 'assign-submit' } }) + (canA() ? U.btn({ label: 'Xác nhận ngay', icon: 'check-circle', act: 'confirm', cls: 'btn-primary', attrs: { 'data-guide': 'assign-confirm' } }) : '') });
    const form = m.el;
    U.onChange(form, { bld: (el) => { const bb = Q.building(el.value); const c = Q.buildingManager(bb.id), u = Q.upcomingManager(bb.id); form.querySelector('#af-current').innerHTML = U.note('info', 'Quản lý hiện tại: ' + esc(c.name || 'Chưa phân công'), u ? 'Đã có kế hoạch: ' + esc(u.name) + ' từ ' + F.date(u.assignment.start) : 'Phụ trách chính mới sẽ tự kết thúc phân công người cũ ngày hiệu lực − 1'); }, unit: (el) => { const sel = form.querySelector('select[name=employeeId]'); sel.innerHTML = '<option value="" disabled selected>Chọn nhân viên</option>' + empOpts(el.value).map(([v, l]) => `<option value="${v}">${esc(l)}</option>`).join(''); } });
    const save = (confirm) => { try { const d = m.data(); const r = X.createAssignment({ buildingId: d.buildingId, employeeId: d.employeeId, role: d.role, start: d.start, end: d.end, reason: d.reason, note: d.note, roomScope: d.roomScope, confirm }); m.close(); ok(confirm ? 'Đã xác nhận phân công' : 'Đã gửi duyệt phân công', Q.employeeName(r.employeeId) + ' – ' + Q.label('assignRole', r.role) + ' – ' + Q.building(r.buildingId).name + ' từ ' + F.date(r.start)); if (pre.onDone) pre.onDone(r); } catch (e) { U.toast('err', 'Không tạo được phân công', e.message); } };
    U.bind(form, { cancel: () => m.close(), submit: () => save(false), confirm: () => save(true) });
    return m;
  };
  const transferForm = (pre = {}) => {
    const emps = St.rawAll('employees').filter(e => e && e.status !== 'resigned');
    const bOf = (id) => id ? Q.buildingsOfEmployee(id, F.today(), { role: 'manager' }) : [];
    const m = U.drawer({ title: 'Điều chuyển nhiều tòa', sub: 'Chuyển toàn bộ/một phần tòa Phụ trách chính từ NV A sang NV B cùng ngày hiệu lực (§4.25.3)', wide: true, body: `<div class="form-grid">
      ${U.field({ label: 'Từ nhân viên', req: true, input: U.select({ name: 'from', value: pre.fromEmployeeId || '', placeholder: 'Chọn NV', options: emps.filter(e => bOf(e.id).length).map(e => [e.id, e.name + ' (' + bOf(e.id).length + ' tòa)']), attrs: { 'data-on': 'from' } }) })}
      ${U.field({ label: 'Sang nhân viên', req: true, input: U.select({ name: 'to', placeholder: 'Chọn NV nhận', options: emps.map(e => [e.id, e.name + ' (' + e.code + ')']) }) })}
      <div class="span2" id="tf-b">${pre.fromEmployeeId ? bOf(pre.fromEmployeeId).map(b => U.check({ name: 'b_' + b.id, label: b.name, checked: true })).join('') : '<span class="muted small">Chọn nhân viên nguồn để hiện danh sách tòa</span>'}</div>
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'start', value: F.addDays(F.today(), 1) }) })}
      ${U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Điều chuyển…' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Gửi duyệt', icon: 'send', act: 'submit', cls: 'btn-outline' }) + (canA() ? U.btn({ label: 'Xác nhận ngay', icon: 'check-circle', act: 'confirm', cls: 'btn-primary' }) : '') });
    U.onChange(m.el, { from: (el) => { m.el.querySelector('#tf-b').innerHTML = bOf(el.value).map(b => U.check({ name: 'b_' + b.id, label: b.name, checked: true })).join('') || '<span class="muted small">NV này không là Phụ trách chính tòa nào</span>'; } });
    const save = (confirm) => { try { const d = m.data(); const ids = Object.keys(d).filter(k => k.startsWith('b_') && d[k]).map(k => k.slice(2)); const out = X.bulkTransfer({ fromEmployeeId: d.from, toEmployeeId: d.to, buildingIds: ids, start: d.start, reason: d.reason, confirm }); m.close(); ok('Đã ' + (confirm ? 'xác nhận' : 'gửi duyệt') + ' điều chuyển ' + out.length + ' tòa'); } catch (e) { U.toast('err', 'Không điều chuyển được', e.message); } };
    U.bind(m.el, { cancel: () => m.close(), submit: () => save(false), confirm: () => save(true) });
  };
  TH.forms.assignment = assignForm; TH.forms.transfer = transferForm;

  /* ---- Actions dòng ---- */
  const rowMenu = (el, a) => {
    const items = [{ label: 'Xem tòa', icon: 'building', onClick: () => TH.go('#/buildings/' + a.buildingId + '?tab=staff') }, { label: 'Xem nhân viên', icon: 'user', onClick: () => TH.go('#/hr/' + a.employeeId + '?tab=assign') }, '-'];
    if (a.status === 'pending' && canA()) items.push({ label: 'Duyệt', icon: 'check-circle', onClick: () => { try { X.approveAssignment(a.id); ok('Đã duyệt phân công'); } catch (e) { U.toast('err', 'Không duyệt được', e.message); } } }, { label: 'Từ chối', icon: 'x-circle', danger: true, onClick: async () => { const r = await U.confirm({ title: 'Từ chối phân công?', body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) }), ok: 'Từ chối', danger: true }); if (r) { try { X.rejectAssignment(a.id, r.reason); ok('Đã từ chối'); } catch (e) { U.toast('err', 'Không từ chối được', e.message); } } } });
    if (['pending', 'approved', 'draft'].includes(a.status) && canM()) items.push({ label: 'Hủy kế hoạch', icon: 'minus-circle', danger: true, onClick: async () => { const r = await U.confirm({ title: 'Hủy kế hoạch phân công?', text: 'Chỉ hủy được trước ngày hiệu lực; bản ghi được giữ với trạng thái Đã hủy.', body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Hủy kế hoạch', danger: true }); if (r) { try { X.cancelAssignment(a.id, r.reason); ok('Đã hủy kế hoạch'); } catch (e) { U.toast('err', 'Không hủy được', e.message); } } } });
    if (a.status === 'active' && canM()) items.push({ label: 'Thay đổi quản lý tòa này', icon: 'user-check', onClick: () => assignForm({ buildingId: a.buildingId, role: 'manager' }) }, { label: 'Kết thúc phân công', icon: 'x-circle', danger: true, onClick: async () => { const r = await U.confirm({ title: 'Kết thúc phân công?', text: 'Không xóa cứng – lưu ngày kết thúc và lý do (§4.25.5).', body: U.field({ label: 'Ngày kết thúc', input: U.date({ name: 'end', value: F.today() }) }) + U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Kết thúc', danger: true }); if (r) { try { X.endAssignment(a.id, r.end, r.reason); ok('Đã kết thúc phân công'); } catch (e) { U.toast('err', 'Không kết thúc được', e.message); } } } });
    U.menu(el, items);
  };
  TH.pages.assignmentMenu = rowMenu;

  /* ---- Trang ---- */
  TH.router.register('/hr/assignments/new', (root, p, q) => { TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Phân công tòa nhà', href: '#/hr/assignments' }, { label: 'Thay đổi quản lý' }]); root.innerHTML = U.card({ body: U.empty({ icon: 'building', title: 'Thay đổi quản lý tòa', text: 'Mọi thao tác thêm/sửa/đổi quản lý đều thực hiện tại module Phân công tòa nhà (§4.6).', action: U.btn({ label: 'Mở form', cls: 'btn-primary', size: 'btn-sm', act: 'open' }) }) }); const open = () => assignForm({ buildingId: q.buildingId || '', employeeId: q.employeeId || '', role: q.role || 'manager', onDone: () => TH.go('#/hr/assignments?view=upcoming' + (q.buildingId ? '&buildingId=' + q.buildingId : '')) }); U.bind(root, { open }); open(); }, { menu: 'assignments', permission: 'assignments.manage' });

  TH.router.register('/hr/assignments', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Phân công tòa nhà' }]);
    const view = q.view || 'current'; const date = q.date || F.today();
    const f = { orgUnitId: q.orgUnitId || '', employeeId: q.employeeId || '', buildingId: q.buildingId || '', role: q.role || '', s: q.s || '' };
    const all = St.rawAll('buildingAssignments').filter(Boolean);
    const inUnit = (a) => { if (!f.orgUnitId) return true; const ids = new Set(Q.orgDescendants(f.orgUnitId, date)); const eu = Q.employeeUnit(a.employeeId, date); return ids.has(a.orgUnitId) || ids.has(eu.id); };
    const base = all.filter(a => (!f.employeeId || a.employeeId === f.employeeId) && (!f.buildingId || a.buildingId === f.buildingId) && (!f.role || a.role === f.role) && inUnit(a) && (!f.s || F.norm(Q.employeeName(a.employeeId) + ' ' + Q.building(a.buildingId).name + ' ' + (a.reason || '')).includes(F.norm(f.s))));
    const isCur = (a) => ['active', 'ended', 'approved'].includes(a.status) && a.start <= date && (!a.end || a.end >= date);
    const sets = { current: base.filter(isCur), upcoming: base.filter(a => a.status === 'approved' && a.start > date), pending: base.filter(a => ['pending', 'draft'].includes(a.status)), history: base };
    const rows = (sets[view] || sets.current).slice().sort((a, b) => view === 'history' ? F.cmp(b.start, a.start) : F.cmp(a.start, b.start) || F.cmp(Q.building(a.buildingId).name, Q.building(b.buildingId).name));
    const missing = Q.buildingsMissingManager(date); const overlaps = all.filter(a => ['active', 'approved', 'pending'].includes(a.status) && Q.assignmentOverlaps(a).length);
    // Bảng §4.25.9 theo nhân viên (nhà/phòng hiện tại & sắp tới)
    const empIds = [...new Set(rows.map(a => a.employeeId))];
    root.innerHTML = `${U.pageHead({ title: 'Phân công tòa nhà', sub: 'Nguồn dữ liệu chuẩn duy nhất cho Quản lý hiện tại / sắp tới của tòa; Dashboard, công nợ, bảng lương chỉ đọc từ đây (§4.25).', acts: [U.btn({ label: 'Thay đổi quản lý', icon: 'user-check', cls: 'btn-primary', act: 'change', disabled: !canM(), attrs: { 'data-guide': 'assign-new' } }), U.btn({ label: 'Tạo phân công', icon: 'plus', cls: 'btn-outline', act: 'new', disabled: !canM() }), U.btn({ label: 'Điều chuyển hàng loạt', icon: 'arrow-left-right', cls: 'btn-outline', act: 'transfer', disabled: !canM() }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${missing.length ? U.note('warn', missing.length + ' tòa chưa có Phụ trách chính tại ' + F.date(date), missing.map(b => U.link('#/hr/assignments/new?buildingId=' + b.id, esc(b.name))).join(', ')) + '<div class="mb16"></div>' : ''}
    ${overlaps.length ? U.note('danger', overlaps.length + ' phân công trùng thời gian', 'Cùng nhân viên – cùng tòa – chồng hiệu lực: ' + [...new Set(overlaps.map(a => Q.employeeName(a.employeeId) + ' / ' + Q.building(a.buildingId).name))].join('; ')) + '<div class="mb16"></div>' : ''}
    ${U.statusTabs([{ key: 'current', label: 'Hiện tại', count: sets.current.length, color: 'green' }, { key: 'upcoming', label: 'Sắp tới', count: sets.upcoming.length, color: 'blue' }, { key: 'pending', label: 'Chờ duyệt', count: sets.pending.length, color: 'amber' }, { key: 'history', label: 'Lịch sử', count: base.length }], view)}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhân viên, tòa, lý do…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Tổ chức (gồm đơn vị con)', input: U.select({ name: 'orgUnitId', value: f.orgUnitId, all: 'Toàn công ty', options: Q.orgOptions(date), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Nhân viên', input: U.select({ name: 'employeeId', value: f.employeeId, all: 'Tất cả nhân viên', options: Q.employeeOptions({ orgUnitId: f.orgUnitId, date }), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa', options: St.rawAll('buildings').filter(b => b && !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Vai trò', input: U.select({ name: 'role', value: f.role, all: 'Tất cả vai trò', options: roleOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Ngày tham chiếu', input: U.date({ name: 'date', value: date, attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.card({ title: ({ current: 'Phân công hiệu lực tại ' + F.date(date), upcoming: 'Đã duyệt – chờ đến ngày hiệu lực', pending: 'Đề xuất chờ duyệt', history: 'Toàn bộ lịch sử phân công' })[view] + ` <span class="muted" style="font-weight:400">(${rows.length})</span>`, body: null, id: 'tbl', attrs: 'data-guide="assignments-table"' })}
    ${view === 'current' ? U.card({ title: 'Tổng hợp theo nhân viên (§4.25.9)', icon: 'users', sub: 'Số nhà/phòng hiện tại & sắp tới tính từ assignment và danh mục phòng – không nhập tay', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Nhân viên</th><th>Đơn vị</th><th class="num">Nhà hiện tại</th><th class="num">Phòng hiện tại</th><th class="num">Nhà sắp tới</th><th class="num">Phòng sắp tới</th></tr></thead><tbody>${empIds.map(id => { const w = Q.assignmentWorkload(id, date); return `<tr><td>${U.link('#/hr/' + id, esc(Q.employeeName(id)), 'bold')}</td><td>${esc(Q.employeeUnit(id, date).name || '-')}</td><td class="num">${w.current.length}</td><td class="num">${w.currentRooms}</td><td class="num">${w.upcoming.length}</td><td class="num">${w.upcomingRooms}</td></tr>`; }).join('') || '<tr><td colspan="6" class="muted tc">Không có dữ liệu</td></tr>'}</tbody></table>` }) : ''}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl').appendChild(wrap);
    U.table(wrap, { rows, unit: 'phân công', pageSize: 15, rowKey: a => a.id, cols: [
      { key: 'b', label: 'Tòa nhà', sortable: true, sortVal: a => Q.building(a.buildingId).name, render: a => U.cell2(U.link('#/buildings/' + a.buildingId + '?tab=staff', esc(Q.building(a.buildingId).name), 'bold'), esc(Q.building(a.buildingId).code || '')) },
      { key: 'e', label: 'Nhân viên', sortable: true, sortVal: a => Q.employeeName(a.employeeId), render: a => U.cell2(U.link('#/hr/' + a.employeeId, esc(Q.employeeName(a.employeeId))), esc(Q.employeeUnit(a.employeeId, a.start).name || Q.orgUnit(a.orgUnitId).name || '')) },
      { key: 'role', label: 'Vai trò', render: a => roleChip(a.role) + (a.roomScope ? ` <span class="xs muted">${esc(a.roomScope)}</span>` : '') },
      { key: 'start', label: 'Từ ngày', sortable: true, render: a => F.date(a.start) }, { key: 'end', label: 'Đến ngày', render: a => a.end ? F.date(a.end) : '<span class="muted">—</span>' },
      { key: 'status', label: 'Trạng thái', render: a => Q.chip('assignment', a.status) },
      { key: 'reason', label: 'Lý do / ghi chú', render: a => `<span class="small">${esc(a.reason || '')}</span>${a.endReason ? `<div class="xs muted">Kết thúc: ${esc(a.endReason)}</div>` : ''}${a.rejectReason ? `<div class="xs red">Từ chối: ${esc(a.rejectReason)}</div>` : ''}` },
      { key: 'by', label: 'Tạo / duyệt', render: a => `<span class="xs">${esc(Q.userName(a.createdBy) === '-' ? 'Hệ thống' : Q.userName(a.createdBy))}${a.approvedBy ? ' → ' + esc(Q.userName(a.approvedBy)) : ''}</span>` },
      { key: 'actions', label: '', render: a => U.rowActions([a.status === 'pending' && canA() ? U.actBtn({ icon: 'check', label: 'Duyệt', act: 'approve', tone: 'primary', attrs: { 'data-id': a.id, 'data-guide': 'assign-approve' } }) : '', U.moreBtn(a.id)]), hideable: false }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ view }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, {
      stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { view: el.dataset.key, date })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({ view }); TH.router.refresh(); },
      change: () => assignForm({ buildingId: f.buildingId, role: 'manager', orgUnitId: f.orgUnitId }), new: () => assignForm({ buildingId: f.buildingId, role: 'support', orgUnitId: f.orgUnitId }), transfer: () => transferForm({ fromEmployeeId: f.employeeId }),
      approve: (el) => { try { X.approveAssignment(el.dataset.id); ok('Đã duyệt phân công', 'Phụ trách chính cũ (nếu có) kết thúc ngày hiệu lực − 1'); } catch (e) { U.toast('err', 'Không duyệt được', e.message); } },
      more: (el) => rowMenu(el, Q.assignment(el.dataset.id)),
      export: () => { F.download('phan-cong-' + view + '-' + date + '.csv', F.csv(rows.map(a => [Q.building(a.buildingId).code, Q.building(a.buildingId).name, Q.employeeName(a.employeeId), Q.employeeUnit(a.employeeId, a.start).name || '', Q.label('assignRole', a.role), a.start, a.end || '', Q.label('assignment', a.status), a.reason || '']), ['Mã tòa', 'Tòa', 'Nhân viên', 'Đơn vị', 'Vai trò', 'Từ ngày', 'Đến ngày', 'Trạng thái', 'Lý do']), 'text/csv'); ok('Đã xuất danh sách phân công theo bộ lọc'); },
    });
  }, { menu: 'assignments', permission: 'assignments.view' });
})(window.TH);
