/* Phase 3 – Ngân hàng & đối soát (#/finance/bank – tự thiết kế, mô phỏng theo scope §4.5; ngoài SRS v1.2 §2.2). Tái dùng parser TH.imp + quy tắc ghép bảng kê P2. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Imp = TH.imp, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const COLORS = { VCB: '#0F6B3A', TCB: '#C8102E', ACB: '#0033A0' };
  const accCard = (a) => { const st = Q.bankStats({ accountId: a.id, period: St.state.meta.period }); return `<div class="bank-acc"><div class="lg" style="background:${COLORS[a.code] || '#334155'}">${esc(a.code)}</div><div class="grow"><b>${esc(a.bank)}</b><small>${esc(a.number)} · ${esc(a.name)}</small></div><div class="tr"><b>${F.vnd(a.balance)}</b><small class="muted">${st.count} GD tháng · ${a.qrEnabled ? U.chip('QR', 'blue') : ''}</small></div></div>`; };
  /* File mẫu sao kê: 20 dòng sinh từ dữ liệu hiện có (khớp mã HĐ/hóa đơn, khớp khách + số tiền, không khớp, trùng) – dùng lại statementSample P2 nếu có */
  const bankSample = () => { if (Imp && Imp.statementSample) { const rows = Imp.statementSample(); rows[0] = ['Ngày giao dịch', 'Số tiền', 'Mã giao dịch', 'Mã hóa đơn', 'Mã hợp đồng', 'Phòng', 'Khách thuê', 'Phương thức', 'Nội dung']; return rows.map(r => r.map(String)); } return [['Ngày giao dịch', 'Số tiền', 'Mã giao dịch', 'Nội dung'], [F.today(), '5000000', 'FT0001', 'CK tien phong']]; };
  const importModal = () => {
    const m = U.modal({ title: 'Nhập sao kê ngân hàng', sub: 'CSV (UTF-8): Ngày, Số tiền, Mã giao dịch, Nội dung (+ Mã hóa đơn/HĐ/Phòng/Khách nếu có). Trùng mã giao dịch → bỏ qua.', size: 'lg', body: `${U.field({ label: 'Tài khoản nhận', input: U.select({ name: 'accountId', value: (St.all('bankAccounts')[0] || {}).id, options: St.all('bankAccounts').map(a => [a.id, a.bank + ' – ' + a.number]) }) })}<div class="field mt12"><label>File sao kê</label>${U.dropzone({ name: 'bk', multiple: false, accept: '.csv', hint: 'CSV, tối đa 5MB (bản demo offline không đọc .xlsx)' })}</div><div class="row gap8 mt8">${U.btn({ label: 'Dùng file mẫu', icon: 'file-text', size: 'btn-sm', cls: 'btn-outline', act: 'sample', attrs: { 'data-guide': 'bank-sample' } })}${U.btn({ label: 'Tải file mẫu', icon: 'download', size: 'btn-sm', cls: 'btn-ghost', act: 'dl' })}</div>${U.note('info', '', 'Sau khi nhập, bấm "Đối soát tự động" để ghép với hóa đơn theo 4 quy tắc của bảng kê (Phase 2); dòng khớp → tạo khoản thu.')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Nhập sao kê', icon: 'upload', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'bank-import' } }) });
    const doImport = (rows, fileName) => { const parsed = Imp.parse(rows, Imp.STATEMENT.fields, Imp.STATEMENT.aliases); const objs = Imp.rowsToObjects(parsed); const r = X.importBankStatement({ rows: objs, accountId: m.data().accountId, fileName }); m.close(); ok(r.duplicate ? 'Sao kê này đã nhập trước đó' : 'Đã nhập ' + r.added + ' giao dịch', r.dup ? r.dup + ' dòng trùng mã giao dịch bỏ qua' : fileName); };
    U.bind(m.el, { c: () => m.close(), dl: () => { F.download('mau-sao-ke-ngan-hang.csv', F.csv(bankSample().slice(1), bankSample()[0]), 'text/csv'); ok('Đã tải file mẫu'); }, sample: () => doImport(bankSample(), 'mau-sao-ke-ngan-hang.csv'), s: async () => { const f = U.dzFiles(m.el, 'bk')[0]; if (!f) throw new Error('Chọn file CSV hoặc dùng file mẫu'); const r = await Imp.readFile(f); doImport(r.rows.map(x => x.map(String)), f.name); } });
  };
  const matchModal = (t) => {
    const invs = St.where('invoices', i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0).sort((a, b) => Math.abs(Q.invRemaining(a) - t.amount) - Math.abs(Q.invRemaining(b) - t.amount)).slice(0, 40);
    const m = U.modal({ title: 'Khớp thủ công ' + esc(t.ref), sub: F.date(t.date) + ' · ' + F.vnd(t.amount) + ' · ' + esc(t.desc), body: `${t.reason ? U.note('warn', '', esc(t.reason)) : ''}${U.field({ label: 'Hóa đơn còn nợ (gần số tiền nhất trước)', req: true, input: U.select({ name: 'invoiceId', value: t.invoiceId || '', placeholder: 'Chọn hóa đơn', options: invs.map(i => [i.id, i.code + ' · ' + (Q.tenant(i.tenantId).name || '') + ' · ' + (Q.room(i.roomId).code || '') + ' · còn ' + F.vnd(Q.invRemaining(i))]) }), cls: 'mt12' })}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Bỏ qua giao dịch', icon: 'x', cls: 'btn-ghost', act: 'ig' }) + U.btn({ label: 'Khớp & ghi nhận thu', icon: 'check', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'bank-match-save' } }) });
    U.bind(m.el, { c: () => m.close(), ig: () => { X.ignoreBankTx(t.id, 'Bỏ qua thủ công'); m.close(); ok('Đã bỏ qua giao dịch'); }, s: () => { const d = m.data(); const r = X.matchBankTx(t.id, d.invoiceId); m.close(); ok('Đã khớp ' + t.ref, 'Tạo khoản thu cho ' + (St.get('invoices', d.invoiceId) || {}).code); } });
  };
  const qrModal = () => {
    const invs = St.where('invoices', i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0).sort((a, b) => F.cmp(a.dueDate, b.dueDate)).slice(0, 60);
    const m = U.modal({ title: 'Tạo QR thanh toán (VietQR – mô phỏng)', sub: 'Khách quét QR chuyển khoản đúng nội dung → webhook ngân hàng tự khớp hóa đơn (scope §4.5)', body: `${U.field({ label: 'Hóa đơn chưa thu', req: true, input: U.select({ name: 'invoiceId', placeholder: 'Chọn hóa đơn', options: invs.map(i => [i.id, i.code + ' · ' + (Q.tenant(i.tenantId).name || '') + ' · còn ' + F.vnd(Q.invRemaining(i))]), attrs: { id: 'qr-inv' } }) })}<div id="qr-out" class="mt16 tc muted small">Chọn hóa đơn để sinh mã QR</div>`, footer: U.btn({ label: 'Đóng', act: 'c' }) + U.btn({ label: 'Gửi QR qua Zalo', icon: 'send', cls: 'btn-primary', act: 'send', phase: 2 }) });
    m.el.querySelector('#qr-inv').addEventListener('change', (e) => { const qr = X.createPaymentQr(e.target.value); m._qr = qr; m.el.querySelector('#qr-out').innerHTML = `${U.qrBox(qr.text, 160)}<div class="mt8"><b>${F.vnd(qr.amount)} VND</b><div class="small">${esc(qr.account.bank)} · ${esc(qr.account.number)} · ${esc(qr.account.name)}</div><div class="small muted">Nội dung: <code>${esc(qr.content)}</code></div></div>`; });
    U.bind(m.el, { c: () => m.close(), send: () => { if (!m._qr) throw new Error('Chọn hóa đơn trước'); ok('Đã gửi QR qua Zalo (mô phỏng)', m._qr.code + ' – ' + F.vnd(m._qr.amount)); m.close(); } });
  };
  const txView = (t) => { const p = t.paymentId ? St.get('payments', t.paymentId) : null; const inv = t.invoiceId ? St.get('invoices', t.invoiceId) : null; const ex = t.expenseId ? St.get('expenses', t.expenseId) : null; const m = U.modal({ title: 'Giao dịch ' + esc(t.code), sub: esc(Q.bankAccount(t.accountId).bank) + ' · ' + F.date(t.date), size: 'sm', body: U.kv([['Mã giao dịch', esc(t.ref)], ['Nội dung', esc(t.desc)], ['Số tiền', (t.dir === 'in' ? '+' : '−') + F.vnd(t.amount)], ['Kết quả đối soát', Q.chip('bankTx', t.matchStatus) + (t.rule ? ' <span class="xs muted">quy tắc ' + t.rule + '</span>' : '')], ['Lý do', esc(t.reason || '-')], ['Khoản thu', p ? U.link('#/payments/' + p.id, esc(p.code || 'Xem')) : '-'], ['Hóa đơn', inv ? U.link('#/invoices/' + inv.id, esc(inv.code)) : '-'], ['Chi phí', ex ? U.link('#/expenses?s=' + encodeURIComponent(ex.code), esc(ex.code)) : '-'], ['Nguồn', esc(t.fileName || 'Kết nối ngân hàng (mô phỏng)')]], 'one'), footer: U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'c' }) }); U.bind(m.el, { c: () => m.close() }); };
  const txMenu = (el, t) => U.menu(el, [{ label: 'Xem', icon: 'eye', onClick: () => txView(t) }, { label: 'Khớp thủ công', icon: 'git-merge', disabled: t.dir !== 'in' || t.matchStatus === 'matched' || !TH.auth.can('bank.manage'), onClick: () => matchModal(t) }, { label: 'Bỏ qua', icon: 'x-circle', disabled: t.matchStatus === 'matched' || t.matchStatus === 'ignored' || !TH.auth.can('bank.manage'), onClick: () => { X.ignoreBankTx(t.id); ok('Đã bỏ qua ' + t.ref); } }]);

  TH.router.register('/finance/bank', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Ngân hàng' }]);
    const period = TH.router.periodOf(q); const f = { accountId: q.accountId || '', dir: q.dir || '', status: q.status || '', s: q.s || '', period };
    const rows = Q.bankTxs(f); const st = Q.bankStats(f); const accs = St.all('bankAccounts'); const last = St.where('auditLog', l => l.entityType === 'bank' && l.action === 'reconcile')[0];
    const periods = [...new Set(St.all('bankTransactions').map(t => F.period(t.date)).concat(['2026-10', '2026-09']))].sort().reverse();
    root.innerHTML = `${U.pageHead({ title: 'Ngân hàng & đối soát', phase: 3, sub: 'Tài khoản, sao kê, đối soát tự động và QR thanh toán. <span class="chip gray">Tự thiết kế – không có PNG</span> <span class="chip amber">Mô phỏng – ngoài SRS §2.2 (scope §4.5)</span>', acts: [U.btn({ label: 'Nhập sao kê', icon: 'upload', cls: 'btn-outline', act: 'import', disabled: !TH.auth.can('bank.manage'), attrs: { 'data-guide': 'bank-import-btn' } }), U.btn({ label: 'Đối soát tự động', icon: 'git-merge', cls: 'btn-primary', act: 'reconcile', disabled: !TH.auth.can('bank.manage'), attrs: { 'data-guide': 'bank-reconcile' } }), U.btn({ label: 'Tạo QR thanh toán', icon: 'qr-code', cls: 'btn-outline', act: 'qr', disabled: !TH.auth.can('bank.manage') })] })}
    <div class="grid grid-3 mb16">${accs.map(accCard).join('')}</div>
    ${U.filterbar([U.field({ label: 'Tài khoản', input: U.select({ name: 'accountId', value: f.accountId, all: 'Tất cả tài khoản', options: accs.map(a => [a.id, a.bank]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Thời gian', input: U.select({ name: 'period', value: period || 'all', options: [['all', 'Tất cả']].concat(periods.map(x => [x, F.periodLabel(x)])), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Chiều', input: U.select({ name: 'dir', value: f.dir, all: 'Vào & ra', options: [['in', 'Tiền vào'], ['out', 'Tiền ra']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Đối soát', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.bankTx).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nội dung, mã giao dịch…', icon: 'search', attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tiền vào', value: F.vnd(st.in), cap: period ? F.periodLabel(period) : 'Tất cả', icon: 'arrow-up', tone: 'green' })}${U.kpi({ label: 'Tiền ra', value: F.vnd(st.out), cap: 'Chi qua ngân hàng', icon: 'arrow-down', tone: 'red' })}${U.kpi({ label: 'Đã khớp', value: st.pct + '%', cap: st.matched + '/' + st.count + ' giao dịch', icon: 'check-circle', tone: 'blue', bar: st.pct })}${U.kpi({ label: 'Chưa khớp', value: st.unmatched, cap: st.check + ' cần kiểm tra', icon: 'alert-triangle', tone: 'amber', valueCls: st.unmatched ? 'red' : '' })}</div>
    ${(() => { const rules = Imp && Imp.STATEMENT && Imp.STATEMENT.rules ? Imp.STATEMENT.rules : [['Mã hóa đơn', ''], ['Mã hợp đồng', ''], ['Khách + số tiền ±5%', ''], ['Phòng + ngày ±3', '']]; return U.relatedStrip({ id: 'bank-related', cls: 'mb16', items: [
      { key: 'rules', title: 'Quy tắc đối soát', icon: 'list', summary: rules.length + ' quy tắc', meta: rules.map(r => r[0]).join(' → '), body: `<ol class="guide-steps">${rules.map(r => `<li><b>${esc(r[0])}</b>${r[1] ? '<div class="xs muted">' + esc(r[1]) + '</div>' : ''}</li>`).join('')}</ol><div class="xs muted">Trùng mã giao dịch với khoản thu đã có → gắn khoản thu cũ, không tạo trùng (idempotent).</div>` },
      { key: 'last', title: 'Kết quả đối soát gần nhất', icon: 'history', summary: last ? esc(last.summary) : 'Chưa chạy đối soát', meta: last ? F.datetime(last.at) + ' · ' + esc(last.userName) : 'Bấm "Đối soát tự động" để chạy 4 quy tắc', body: last ? U.kv([['Thời điểm', F.datetime(last.at)], ['Người chạy', esc(last.userName)], ['Kết quả', esc(last.summary)]]) : '<div class="muted small">Chưa chạy đối soát trong phiên này</div>' },
      { key: 'qr', title: 'Kết nối & QR', icon: 'qr-code', summary: 'Webhook <span class="chip green">Đang bật (mô phỏng)</span>', meta: 'QR động: ' + esc((accs.find(a => a.qrEnabled) || {}).bank || '-'), body: `<div class="small">Webhook thanh toán: <span class="chip green">Đang bật (mô phỏng)</span><br>QR động theo hóa đơn: tài khoản ${esc((accs.find(a => a.qrEnabled) || {}).bank || '-')}.<br>Phí chuyển khoản, đối soát cuối ngày và QR thật cần tích hợp ngân hàng – ngoài phạm vi SRS v1.2.</div>` }
    ] }); })()}
    ${U.card({ title: 'Giao dịch ngân hàng (' + rows.length + ')', icon: 'landmark', body: null, id: 'bt', attrs: 'data-guide="bank-table"' })}`;
    U.table(root.querySelector('#bt'), { rows, unit: 'giao dịch', colPrefsKey: 'bank', cols: [{ key: 'date', label: 'Ngày', sortable: true, render: t => F.date(t.date) }, { key: 'acc', label: 'Tài khoản', render: t => `<span class="chip" style="background:${COLORS[Q.bankAccount(t.accountId).code] || '#334155'}22;color:${COLORS[Q.bankAccount(t.accountId).code] || '#334155'}">${esc(Q.bankAccount(t.accountId).code || '')}</span>` }, { key: 'desc', label: 'Nội dung', render: t => U.cell2(esc(t.desc), esc(t.ref)) }, { key: 'in', label: 'Tiền vào', num: true, sortable: true, sortVal: t => t.dir === 'in' ? t.amount : 0, render: t => t.dir === 'in' ? `<span class="green bold">${F.vnd(t.amount)}</span>` : '' }, { key: 'out', label: 'Tiền ra', num: true, sortable: true, sortVal: t => t.dir === 'out' ? t.amount : 0, render: t => t.dir === 'out' ? `<span class="red">${F.vnd(t.amount)}</span>` : '' }, { key: 'status', label: 'Đối soát', sortable: true, sortVal: t => t.matchStatus, render: t => Q.chip('bankTx', t.matchStatus) + (t.reason && t.matchStatus !== 'matched' ? `<div class="xs muted">${esc(t.reason)}</div>` : '') }, { key: 'link', label: 'Liên kết', render: t => t.paymentId ? U.link('#/payments/' + t.paymentId, esc((St.get('payments', t.paymentId) || {}).code || 'Khoản thu'), 'small') : t.expenseId ? U.link('#/expenses?s=' + encodeURIComponent((St.get('expenses', t.expenseId) || {}).code || ''), esc((St.get('expenses', t.expenseId) || {}).code || 'Chi phí'), 'small') : t.invoiceId ? U.link('#/invoices/' + t.invoiceId, esc((St.get('invoices', t.invoiceId) || {}).code || ''), 'small') : '<span class="muted">—</span>' }, { key: 'actions', label: '', render: t => U.rowActions([t.dir === 'in' && ['unmatched', 'check'].includes(t.matchStatus) && TH.auth.can('bank.manage') ? U.btn({ label: 'Khớp', icon: 'git-merge', size: 'btn-sm', cls: 'btn-outline', act: 'match', attrs: { 'data-id': t.id, 'data-guide': 'bank-match' } }) : U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': t.id } }), U.moreBtn(t.id)]), hideable: false }] });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d, { period: d.period || 'all' })); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, import: () => importModal(), reconcile: () => { const r = X.reconcileBank(); ok('Đối soát xong: ' + r.matched + ' khớp, ' + r.check + ' cần kiểm tra', r.total + ' giao dịch chưa khớp được xử lý'); }, qr: () => qrModal(), match: (el) => matchModal(St.get('bankTransactions', el.dataset.id)), view: (el) => txView(St.get('bankTransactions', el.dataset.id)), more: (el) => txMenu(el, St.get('bankTransactions', el.dataset.id)) });
  }, { menu: 'bank', permission: 'bank.view', phase: 3, scopeKey: 'bank', noAutoRefresh: 'timer' });
})(window.TH);
