/* Phase 1 (spec v1.8 §12.11.1) – Kỳ hóa đơn (Billing Period): mã kỳ, từ/đến ngày, ngày chốt, ngày phát hành, trạng thái OPEN → REVIEWING → LOCKED (mở lại có lý do); khóa kỳ chặn tạo/phát hành hóa đơn & sửa chỉ số của kỳ. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  TH.router.register('/finance/periods', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Kỳ hóa đơn' }]);
    const cur = St.state.meta.period; X.ensureBillingPeriod(cur); const next = (() => { const [y, m] = cur.split('-').map(Number); const d = new Date(y, m, 1); return F.toISO(d).slice(0, 7); })(); X.ensureBillingPeriod(next);
    const list = Q.billingPeriods().map(bp => Object.assign({ bp, st: Q.periodStats(bp.code) }));
    const sel = q.sel ? list.find(x => x.bp.code === q.sel) : list.find(x => x.bp.code === cur) || list[0];
    const canLock = ['admin', 'accountant', 'qltong'].includes(TH.auth.role());
    root.innerHTML = `${U.pageHead({ title: 'Kỳ hóa đơn', sub: 'Billing Period là đơn vị chốt điện nước, lập & phát hành hóa đơn; Contract + Room + Kỳ chỉ có một hóa đơn hợp lệ. Khóa kỳ (lock) chặn tạo/phát hành hóa đơn và sửa chỉ số của kỳ; mở lại phải có lý do (§12.11.1, §12.11.6).', acts: [U.btn({ label: 'Điện / Nước kỳ ' + F.periodShort(cur), icon: 'zap', cls: 'btn-outline', act: 'meters' }), U.btn({ label: 'Lập hóa đơn kỳ ' + F.periodShort(cur), icon: 'receipt', cls: 'btn-primary', act: 'batch' })] })}
      <div class="two-col wide" style="grid-template-columns:minmax(0,1.2fr) minmax(0,1fr)"><div>${U.card({ title: 'Danh sách kỳ', icon: 'calendar', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Kỳ</th><th>Từ – đến</th><th>Ngày chốt</th><th>Ngày phát hành</th><th class="num">Hóa đơn</th><th class="num">Phải thu</th><th class="num">Đã thu</th><th>Trạng thái</th><th></th></tr></thead><tbody>${list.map(x => `<tr class="${sel && sel.bp.code === x.bp.code ? 'selected' : ''}"><td><a class="link bold" data-act="sel" data-code="${x.bp.code}">${F.periodLabel(x.bp.code)}</a>${x.bp.code === cur ? ' <span class="chip blue xs">hiện tại</span>' : ''}</td><td class="xs">${F.date(x.bp.from)} – ${F.date(x.bp.to)}</td><td class="xs">${F.date(x.bp.closeDate)}</td><td class="xs">${F.date(x.bp.issueDate)}</td><td class="num">${x.st.issued}${x.st.drafts ? ' <span class="amber xs">+' + x.st.drafts + ' nháp</span>' : ''}</td><td class="num">${F.vnd(x.st.total)}</td><td class="num">${F.vnd(x.st.collected)}</td><td>${Q.chip('billingPeriod', x.bp.status)}</td><td class="tr">${x.bp.status === 'LOCKED' ? U.iconBtn('unlock', 'reopen', 'Mở lại kỳ', { 'data-code': x.bp.code, disabled: !['admin', 'qltong'].includes(TH.auth.role()) }) : U.iconBtn('lock', 'lock', 'Khóa kỳ', { 'data-code': x.bp.code, disabled: !canLock })}</td></tr>`).join('')}</tbody></table>` })}</div>
      <div class="side-stack">${sel ? U.card({ title: 'Kỳ ' + F.periodLabel(sel.bp.code), icon: 'info', actions: Q.chip('billingPeriod', sel.bp.status), body: U.kv([['Mã kỳ', esc(sel.bp.code)], ['Từ – đến', F.date(sel.bp.from) + ' – ' + F.date(sel.bp.to)], ['Ngày chốt điện nước', F.date(sel.bp.closeDate)], ['Ngày phát hành dự kiến', F.date(sel.bp.issueDate)], ['Chỉ số', sel.st.readings + ' (' + sel.st.readingsPending + ' chưa xác nhận)'], ['Hóa đơn', sel.st.issued + ' phát hành · ' + sel.st.drafts + ' nháp'], ['Phải thu / đã thu', F.vnd(sel.st.total) + ' / ' + F.vnd(sel.st.collected)], ['Thu tiền / chi phí trong kỳ', sel.st.payments + ' khoản thu · ' + sel.st.expenses + ' chi phí'], ['Khóa', sel.bp.lockedAt ? F.datetime(sel.bp.lockedAt) + ' · ' + esc(Q.userName(sel.bp.lockedBy)) : '-'], ['Mở lại', sel.bp.reopenedAt ? F.datetime(sel.bp.reopenedAt) + ' · ' + esc(sel.bp.reopenReason || '') : '-']], 'one') + `<div class="row gap8 mt12 wrap">${sel.bp.status === 'OPEN' ? U.btn({ label: 'Chuyển rà soát', icon: 'search', size: 'btn-sm', cls: 'btn-outline', act: 'review', attrs: { 'data-code': sel.bp.code }, disabled: !canLock }) : ''}${sel.bp.status !== 'LOCKED' ? U.btn({ label: 'Sửa ngày chốt / phát hành', icon: 'pencil', size: 'btn-sm', cls: 'btn-ghost', act: 'edit', attrs: { 'data-code': sel.bp.code }, disabled: !canLock }) + U.btn({ label: 'Khóa kỳ', icon: 'lock', size: 'btn-sm', cls: 'btn-primary', act: 'lock', attrs: { 'data-code': sel.bp.code, 'data-guide': 'period-lock' }, disabled: !canLock }) : U.btn({ label: 'Mở lại kỳ (có lý do)', icon: 'unlock', size: 'btn-sm', cls: 'btn-outline', act: 'reopen', attrs: { 'data-code': sel.bp.code }, disabled: !['admin', 'qltong'].includes(TH.auth.role()) })}</div>` }) : ''}${U.note('info', 'Checklist trước khi khóa', 'Chỉ số điện nước đã xác nhận · Hóa đơn nháp đã phát hành hoặc hủy · Thu tiền đã ghi nhận. Sau khóa: sai sót xử lý bằng điều chỉnh/hủy có audit ở kỳ sau (§4.14).')}</div></div>`;
    U.bind(root, {
      sel: (el) => { TH.router.replaceQuery({ sel: el.dataset.code }); TH.router.refresh(); }, meters: () => TH.go('#/meters?period=' + cur), batch: () => TH.go('#/invoices/batch?period=' + cur),
      review: (el) => { try { X.reviewBillingPeriod(el.dataset.code); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
      edit: (el) => { const bp = Q.billingPeriod(el.dataset.code); const m = U.modal({ title: 'Kỳ ' + F.periodLabel(bp.code), size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Ngày chốt', input: U.date({ name: 'closeDate', value: bp.closeDate }) })}${U.field({ label: 'Ngày phát hành', input: U.date({ name: 'issueDate', value: bp.issueDate }) })}${U.field({ label: 'Ghi chú', input: U.input({ name: 'note', value: bp.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.setBillingPeriod(bp.code, m.data()); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      lock: async (el) => { const code = el.dataset.code; const st = Q.periodStats(code); const ok = await U.confirm({ title: 'Khóa kỳ ' + F.periodLabel(code) + '?', text: st.issued + ' hóa đơn đã phát hành, ' + F.vnd(st.total) + '. ' + (st.drafts ? st.drafts + ' hóa đơn nháp sẽ chặn khóa (tick bỏ qua để khóa cưỡng bức). ' : '') + 'Sau khóa không tạo/phát hành hóa đơn, không sửa chỉ số của kỳ.', ok: 'Khóa kỳ', body: st.drafts || st.readingsPending ? U.check({ name: 'force', label: 'Khóa cưỡng bức (bỏ qua nháp / chỉ số chưa xác nhận)' }) : '' }); if (!ok) return; try { X.lockBillingPeriod(code, { force: !!ok.force }); U.toast('ok', 'Đã khóa kỳ ' + F.periodLabel(code)); TH.router.refresh(); } catch (e) { U.toast('err', 'Không khóa được', e.message); } },
      reopen: (el) => { const code = el.dataset.code; const m = U.modal({ title: 'Mở lại kỳ ' + F.periodLabel(code), size: 'sm', body: U.field({ label: 'Lý do', req: true, input: U.textarea({ name: 'reason', rows: 3 }) }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Mở lại', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.reopenBillingPeriod(code, m.data().reason); m.close(); U.toast('ok', 'Đã mở lại kỳ – trạng thái Đang rà soát'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
    });
  }, { menu: 'billing-periods', permission: 'invoices.view' });
})(window.TH);
