(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const cycleChip = (b) => { const p = Q.buildingNextDue(b.id); if (!p) return '<span class="muted">-</span>'; const d = F.daysUntil(p.dueDate); return U.chip(d + ' ngày', d <= 22 ? 'red' : d <= 45 ? 'amber' : 'blue'); };
  const buildingMenu = (btn, b) => {
    const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/buildings/' + b.id) }];
    if (TH.auth.can('buildings.manage')) items.push({ label: 'Sửa', icon: 'pencil', onClick: () => Fm.building(b) });
    if (TH.auth.can('landlordPayments.manage')) items.push({ label: 'Ghi nhận trả chủ nhà', icon: 'banknote', onClick: () => { const p = Q.buildingNextDue(b.id); if (!p) return U.toast('info', 'Không có kỳ thanh toán chờ'); Fm.landlordPaid(p); } });
    if (TH.auth.can('buildings.manage')) items.push('-', b.status === 'inactive' ? { label: 'Kích hoạt lại', icon: 'check', onClick: () => { X.setBuildingStatus(b.id, 'active'); U.toast('ok', 'Đã kích hoạt tòa'); } } : { label: 'Ngừng sử dụng', icon: 'minus-circle', danger: true, onClick: async () => { if (await U.confirm({ title: 'Ngừng sử dụng ' + b.name + '?', text: 'Tòa có hợp đồng hiệu lực sẽ bị chặn (FR-BLD-02). Không xóa vật lý dữ liệu.', ok: 'Ngừng sử dụng', danger: true })) { X.deactivateBuilding(b.id); U.toast('ok', 'Đã ngừng sử dụng tòa'); } } });
    U.menu(btn, items);
  };
  /* ---------- Danh sách tòa ---------- */
  TH.router.register('/buildings', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Tòa nhà' }]);
    const f = { s: q.s || '', district: q.district || '', managerId: q.managerId || '', status: q.status || '', view: q.view || 'table' };
    const all = St.all('buildings');
    const rows = all.filter(b => (!f.s || F.norm(b.name + b.code + b.address).includes(F.norm(f.s))) && (!f.district || b.district === f.district) && (!f.managerId || b.managerId === f.managerId) && (!f.status || b.status === f.status));
    const totalRooms = F.sum(all, b => b.stub ? b.roomCount : Q.roomsOf(b.id).length); const ready = St.where('rooms', r => r.status === 'ready').length;
    const due30 = all.filter(b => { const p = Q.buildingNextDue(b.id); return p && F.daysUntil(p.dueDate) <= 30; }).length;
    root.innerHTML = `${U.pageHead({ title: 'Tòa nhà', sub: 'Quản lý danh sách tòa nhà, thông tin cơ bản, tình trạng hoạt động và người phụ trách.', acts: [U.btn({ label: 'Thêm tòa', icon: 'plus', cls: 'btn-primary', act: 'add' }), U.btn({ label: 'Import tòa', icon: 'upload', cls: 'btn-outline', act: 'import' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo mã, tên tòa, địa chỉ...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Khu vực', input: U.select({ name: 'district', value: f.district, all: 'Tất cả khu vực', options: Q.districts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả người phụ trách', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.building).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Hiển thị', input: `<div class="seg"><button type="button" class="${f.view === 'table' ? 'on' : ''}" data-act="view" data-v="table">${I('table')} Bảng</button><button type="button" class="${f.view === 'card' ? 'on' : ''}" data-act="view" data-v="card">${I('grid')} Thẻ</button></div>` })])}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng số tòa', value: all.length, cap: 'Tăng 3 tòa so với tháng trước', icon: 'building', tone: 'blue', delta: 12 })}${U.kpi({ label: 'Tổng số phòng', value: totalRooms, cap: 'Thuộc ' + all.length + ' tòa nhà', icon: 'door', tone: 'amber', delta: 8 })}${U.kpi({ label: 'Phòng sẵn sàng', value: ready, cap: 'Đang trống, sẵn sàng cho thuê', icon: 'check-circle', tone: 'green', delta: 6 })}${U.kpi({ label: 'Tòa sắp đến kỳ trả chủ nhà', value: due30, cap: 'Trong 30 ngày tới', icon: 'clock', tone: 'amber', delta: 67, deltaDir: 'down' })}</div>
    ${f.view === 'card' ? `<div class="card-grid">${rows.map(b => { const s = Q.roomStats(Q.roomsOf(b.id)); return `<div class="card bcard"><div class="t"><div><h4><a class="link" href="#/buildings/${b.id}">${esc(b.name)}</a></h4><div class="xs muted">${esc(b.code)}</div></div>${Q.chip('building', b.status)}</div><div class="addr">${I('map-pin')} ${esc(b.address)}</div><div class="stats"><span><b>${b.stub ? b.roomCount : s.total}</b>Phòng</span><span><b>${s.ready}</b>Sẵn sàng</span><span><b>${s.occupied}</b>Đang thuê</span><span><b>${b.payCycle} th</b>Chu kỳ</span></div><div class="row between mt8"><span class="small muted">${esc(Q.userName(b.managerId))}</span>${cycleChip(b)}</div></div>`; }).join('')}</div>` : U.card({ title: 'Danh sách tòa nhà', actions: U.btn({ label: 'Lưu bộ lọc', icon: 'bookmark', size: 'btn-sm', p2: true, act: 'save-filter' }) + U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', act: 'cols' }) + U.iconBtn('more', 'more-h', 'Thêm'), body: null, id: 'tbl-card' })}`;
    if (f.view === 'table') {
      const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
      const cols = [
        { key: 'n', label: '#', render: (r, i) => i + 1, width: '40px', hideable: false },
        { key: 'code', label: 'Mã tòa', sortable: true, render: b => U.link('#/buildings/' + b.id, esc(b.code), 'bold') },
        { key: 'name', label: 'Tên tòa / Địa chỉ', sortable: true, render: b => U.cell2(`<b>${esc(b.name)}</b>`, I('map-pin') + ' ' + esc(b.address)) },
        { key: 'district', label: 'Khu vực', sortable: true },
        { key: 'rooms', label: 'Số phòng', num: true, sortable: true, sortVal: b => b.stub ? b.roomCount : Q.roomsOf(b.id).length, render: b => b.stub ? b.roomCount : Q.roomsOf(b.id).length },
        { key: 'ready', label: 'Phòng sẵn sàng', num: true, render: b => { const rs = Q.roomsOf(b.id); const n = rs.filter(r => r.status === 'ready').length; return rs.length ? n + ' <span class="muted">(' + F.pct(n, rs.length) + '%)</span>' : '-'; } },
        { key: 'cycle', label: 'Chu kỳ trả chủ nhà', render: b => cycleChip(b) + ` <span class="xs muted">${b.payCycle} tháng</span>` },
        { key: 'manager', label: 'Quản lý phụ trách', render: b => `<span class="row">${U.avatar(Q.userName(b.managerId), 'sm')}${esc(Q.userName(b.managerId))}</span>` },
        { key: 'status', label: 'Trạng thái', sortable: true, render: b => Q.chip('building', b.status) },
        { key: 'actions', label: 'Thao tác', render: b => U.rowActions([U.moreBtn(b.id)]), hideable: false },
      ];
      const tbl = U.table(wrap, { rows, cols, unit: 'tòa nhà', colPrefsKey: 'buildings', sortKey: 'code' });
      root._tbl = tbl; root._cols = cols;
    }
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { add: () => Fm.building(), import: () => TH.go('#/settings/import?type=building'), view: (b) => { TH.router.replaceQuery(Object.assign({}, f, { view: b.dataset.v })); TH.router.refresh(); }, cols: (b) => U.columnMenu(b, root._tbl, root._cols), 'more-h': (b) => U.menu(b, [{ label: 'Xuất danh sách (CSV)', icon: 'download', onClick: () => { F.download('toa-nha.csv', F.csv(rows.map(x => [x.code, x.name, x.address, x.district, Q.roomsOf(x.id).length, x.payCycle, Q.userName(x.managerId), Q.label('building', x.status)]), ['Mã', 'Tên', 'Địa chỉ', 'Khu vực', 'Số phòng', 'Chu kỳ', 'Quản lý', 'Trạng thái']), 'text/csv'); } }]), more: (b) => buildingMenu(b, St.get('buildings', b.dataset.id)) });
  }, { menu: 'buildings', permission: 'buildings.view' });

  /* ---------- Chi tiết tòa ---------- */
  TH.router.register('/buildings/:id', (root, p, q) => {
    const b = St.get('buildings', p.id); if (!b) { root.innerHTML = U.empty({ title: 'Không tìm thấy tòa' }); return; }
    const tab = q.tab || 'rooms'; const l = St.get('landlords', b.landlordId) || {}; const rooms = Q.roomsOf(b.id); const rs = Q.roomStats(rooms); const mgr = Q.user(b.managerId);
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Tòa nhà', href: '#/buildings' }, { label: b.code }]);
    const nextDue = Q.buildingNextDue(b.id); const lastPaid = Q.landlordPayments(b.landlordId).filter(x => x.status === 'paid').slice(-1)[0];
    const tabs = [{ key: 'overview', label: 'Tổng quan' }, { key: 'landlord', label: 'Chủ nhà & HĐ đầu vào' }, { key: 'rooms', label: 'Phòng' }, { key: 'services', label: 'Dịch vụ' }, { key: 'assets', label: 'Tài sản', phase: 3 }, { key: 'expenses', label: 'Chi phí' }, { key: 'perf', label: 'Hiệu suất', p2: true }, { key: 'docs', label: 'Tài liệu' }, { key: 'history', label: 'Lịch sử' }];
    root.innerHTML = `<div class="card mb16"><div class="card-b"><div class="detail-head" style="margin:0"><img class="thumb" src="assets/login-hero.svg" alt=""><div><h1>${esc(b.name)} <span class="chip gray lg">${esc(b.code)}</span> ${Q.chipDot('building', b.status)}</h1><div class="meta"><span>${I('map-pin')} ${esc(b.address)}</span></div></div><div class="acts">${U.btn({ label: 'Hành động', icon: 'chevron-down', cls: 'btn-outline', act: 'actions' })}${U.iconBtn('more', 'more2', 'Thêm', {}, 'bordered')}</div></div></div>
      <div class="info-strip">${[['map-pin', 'Địa chỉ', b.address], ['layers', 'Khu vực', b.district], ['building', 'Số tầng', b.floors + ' tầng'], ['door', 'Số phòng', (b.stub ? b.roomCount : rooms.length) + ' phòng'], ['user', 'Người phụ trách', (mgr.name || '-') + (mgr.phone ? '<br><span class="muted">' + mgr.phone + '</span>' : '')]].map(([ic, k, v]) => `<div class="it">${I(ic)}<div><small>${k}</small><b>${v}</b></div></div>`).join('')}</div></div>
    ${U.tabs(tabs, tab)}<div id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'rooms') {
      const related = [
        { key: 'payment-cycle', title: 'Chu kỳ trả chủ nhà', icon: 'clock', summary: b.payCycle + ' tháng/lần', meta: 'Ngày thanh toán: ' + F.pad(b.payDay), body: `<div class="vl" style="font-size:20px;font-weight:700;color:var(--text)">${b.payCycle} tháng/lần</div><div class="small muted mt4">Ngày thanh toán: ${F.pad(b.payDay)} · Kỳ tới: ${nextDue ? F.date(nextDue.dueDate) + ' (' + F.daysUntil(nextDue.dueDate) + ' ngày)' : '-'}</div>` },
        { key: 'landlord', title: 'Chủ nhà', icon: 'user-check', summary: l.id ? esc(l.name) : 'Chưa gán chủ nhà', meta: l.id ? esc(l.phone || l.email || '-') : 'Cập nhật trong thông tin tòa', actions: l.id ? U.btn({ label: 'Xem chi tiết', icon: 'info', cls: 'btn-outline', size: 'btn-sm', act: 'go-landlord' }) : '', body: l.id ? `<b style="font-size:15px;color:var(--text)">${esc(l.name)}</b><div class="small muted mt4">${l.taxCode ? 'MST: ' + esc(l.taxCode) + '<br>' : ''}${I('phone')} ${esc(l.phone)}<br>${I('mail')} ${esc(l.email)}</div>` : U.empty({ title: 'Chưa gán chủ nhà', action: U.btn({ label: 'Sửa tòa', size: 'btn-sm', act: 'edit' }) }) },
        { key: 'latest-payment', title: 'Thanh toán gần nhất', icon: 'calendar-check', summary: lastPaid ? F.vnd(lastPaid.amount) + ' VND' : 'Chưa có thanh toán', meta: lastPaid ? F.date(lastPaid.paidDate) : nextDue ? 'Kỳ tới ' + F.date(nextDue.dueDate) : 'Chưa có lịch trả', actions: l.id ? `<a class="link small" href="#/landlords/${l.id}?tab=payments">Xem lịch sử →</a>` : '', body: lastPaid ? `${Q.chip('lpay', 'paid')}<div style="font-size:20px;font-weight:700;color:var(--text);margin-top:8px">${F.vnd(lastPaid.amount)} VND</div><div class="small muted mt4">Kỳ thanh toán: ${esc(lastPaid.periodLabel)}<br>Ngày thanh toán: ${F.date(lastPaid.paidDate)}</div>` : '<div class="muted small">Chưa có kỳ đã thanh toán</div>' + (nextDue ? `<div class="mt8">${Q.chip('lpay', nextDue.status)} ${F.vnd(nextDue.amount)} – hạn ${F.date(nextDue.dueDate)}</div>` : '') }
      ];
      body.innerHTML = `${U.section('Danh sách phòng', 'Quản lý thông tin phòng, trạng thái, khách thuê và hợp đồng của tòa nhà.', U.btn({ label: 'Thêm phòng', icon: 'plus', cls: 'btn-primary', act: 'add-room' }) + U.btn({ label: 'Import phòng', icon: 'upload', cls: 'btn-outline', act: 'import-rooms' }) + U.btn({ label: 'Tạo nhiều phòng', icon: 'grid', cls: 'btn-outline', act: 'bulk' }))}
        ${U.relatedStrip({ id: 'building-room-related', items: related, cls: 'mb16' })}
        <div class="grid grid-4 mb16">${U.kpi({ mini: true, label: 'Tổng số phòng', value: rs.total, cap: '100% tổng quỹ phòng', icon: 'door', tone: 'blue' })}${U.kpi({ mini: true, label: 'Đang thuê', value: rs.occupied, cap: F.pct(rs.occupied, rs.total) + '%', icon: 'users', tone: 'green' })}${U.kpi({ mini: true, label: 'Sẵn sàng', value: rs.ready, cap: F.pct(rs.ready, rs.total) + '%', icon: 'check-circle', tone: 'blue' })}${U.kpi({ mini: true, label: 'Chờ dọn', value: rs.cleaning, cap: F.pct(rs.cleaning, rs.total) + '%', icon: 'brush', tone: 'amber' })}</div>
        <div class="card"><div class="filterbar" style="border-bottom:1px solid var(--border)">${U.field({ input: U.input({ name: 'rs', placeholder: 'Tìm kiếm theo mã phòng, khách thuê...', icon: 'search', value: q.rs || '', attrs: { 'data-on': 'rf' } }), cls: 'wide' })}${U.field({ input: U.select({ name: 'floor', value: q.floor || '', all: 'Tất cả tầng', options: [...new Set(rooms.map(r => r.floor))].sort((a, c) => a - c).map(fl => [fl, 'Tầng ' + fl]), attrs: { 'data-on': 'rf' } }) })}${U.field({ input: U.select({ name: 'rstatus', value: q.rstatus || '', all: 'Tất cả trạng thái', options: Object.entries(Q.L.room).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'rf' } }) })}${U.btn({ label: 'Bộ lọc', icon: 'filter', cls: 'btn-outline' })}</div><div id="room-tbl"></div></div>`;
      const rrows = rooms.filter(r => (!q.rs || F.norm(r.code + (Q.roomTenant(r.id) || {}).name).includes(F.norm(q.rs))) && (!q.floor || String(r.floor) === q.floor) && (!q.rstatus || r.status === q.rstatus)).sort((a, c) => a.code.localeCompare(c.code));
      U.table(body.querySelector('#room-tbl'), { rows: rrows, selectable: true, unit: 'phòng', cols: [
        { key: 'code', label: 'Mã phòng', sortable: true, render: r => U.link('#/rooms/' + r.id, esc(r.code), 'bold') }, { key: 'floor', label: 'Tầng', sortable: true },
        { key: 'status', label: 'Trạng thái', sortable: true, render: r => Q.chipDot('room', r.status) }, { key: 'price', label: 'Giá tham chiếu', num: true, sortable: true, render: r => F.vnd(r.price) },
        { key: 'tenant', label: 'Khách hiện tại', render: r => { const t = Q.roomTenant(r.id); return t ? U.link('#/tenants/' + t.id, esc(t.name)) : '-'; } },
        { key: 'contract', label: 'HĐ hiện tại', render: r => { const c = Q.activeContractOfRoom(r.id); return c ? U.cell2(U.link('#/contracts/' + c.id, c.code), F.date(c.start) + ' - ' + F.date(c.end)) : '-'; } },
        { key: 'debt', label: 'Công nợ', num: true, render: r => { const d = Q.roomDebt(r.id); return `<span class="${d ? 'red bold' : 'green'}">${F.vnd(d)}</span>`; } },
        { key: 'actions', label: 'Thao tác', render: r => U.rowActions([U.moreBtn(r.id)]) }] });
    }
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin tòa', icon: 'building', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }), body: U.kv([['Mã tòa', esc(b.code)], ['Tên tòa', esc(b.name)], ['Địa chỉ', esc(b.address)], ['Khu vực', esc(b.district)], ['Số tầng', b.floors], ['Số phòng', rooms.length], ['Tiền tố mã phòng', esc(b.prefix)], ['Tiện ích', (b.amenities || []).join(', ') || '-'], ['Trạng thái ĐKKD', esc(b.license || 'Đã đăng ký')], ['Người phụ trách', esc(mgr.name || '-')], ['Trạng thái', Q.chip('building', b.status)]]) })}${U.card({ title: 'Tình trạng phòng', icon: 'door', body: `<div class="grid grid-3">${Object.entries(Q.L.room).map(([k, v]) => U.stat(v[0], rs[k] || 0)).join('')}</div>${TH.chart.stackedBar({ groups: [{ label: b.name, values: [rs.occupied, rs.ready, rs.held, rs.maintenance, rs.cleaning + rs.inactive] }], series: [{ color: '#1D4ED8' }, { color: '#BFDBFE', dark: true }, { color: '#FCD34D', dark: true }, { color: '#F97316' }, { color: '#CBD5E1', dark: true }], height: 180 })}` })}</div>`;
    if (tab === 'landlord') { const lcs = Q.landlordContracts(b.landlordId); body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Chủ nhà', icon: 'user-check', actions: l.id ? U.btn({ label: 'Xem chủ nhà', icon: 'external-link', size: 'btn-sm', cls: 'btn-outline', act: 'go-landlord' }) : '', body: l.id ? U.kv([['Tên', esc(l.name)], ['Loại', l.type === 'company' ? 'Công ty' : 'Cá nhân'], ['SĐT', esc(l.phone)], ['Email', esc(l.email)], ['MST', esc(l.taxCode || '-')], ['Tài khoản nhận tiền', esc(l.bankAccount || '-')], ['Trạng thái', Q.chip('landlord', l.status)]], 'one') : U.empty({ title: 'Chưa gán chủ nhà' }) })}${U.card({ title: 'Hợp đồng đầu vào', icon: 'file-text', actions: l.id ? U.btn({ label: 'Thêm HĐ', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'add-lc' }) : '', body: lcs.length ? lcs.map(c => U.kv([['Mã HĐ', esc(c.code) + ' ' + Q.chip('lcontract', c.status)], ['Thời gian', F.date(c.start) + ' – ' + F.date(c.end)], ['Giá thuê', F.vnd(c.rent) + ' đ/tháng'], ['Cọc', F.vnd(c.deposit) + ' đ'], ['Giữ giá', c.priceHoldMonths + ' tháng'], ['Chu kỳ trả', c.cycleMonths + ' tháng/lần']], 'one')).join('<hr class="mt12 mb12" style="border:0;border-top:1px solid var(--border)">') : U.empty({ title: 'Chưa có hợp đồng đầu vào' }) })}</div>`; }
    if (tab === 'services') { const svcs = St.where('services', s => s.status === 'active' && (s.scope === 'all' || (s.buildingIds || []).includes(b.id))); body.innerHTML = U.card({ title: 'Bảng giá áp dụng cho tòa', icon: 'sliders', actions: U.btn({ label: 'Danh mục dùng chung', icon: 'external-link', size: 'btn-sm', cls: 'btn-outline', act: 'go-catalog' }), body: null, id: 'svc-card' }); const w = document.createElement('div'); body.querySelector('#svc-card').appendChild(w); U.table(w, { rows: svcs, noPager: true, cols: [{ key: 'name', label: 'Dịch vụ', render: s => `<span class="row"><span class="svc-icon">${I(s.icon || 'package')}</span><b>${esc(s.name)}</b></span>` }, { key: 'unit', label: 'Đơn vị' }, { key: 'method', label: 'Cách tính', render: s => ({ fixed: 'Theo gói cố định', meter: 'Theo chỉ số', per_room: 'Theo phòng', per_vehicle: 'Theo xe' })[s.method] }, { key: 'price', label: 'Giá', num: true, render: s => F.vnd(s.price) }, { key: 'eff', label: 'Hiệu lực', render: s => F.date(s.effectiveFrom) }, { key: 'rooms', label: 'Phòng áp dụng mặc định', num: true, render: s => rooms.filter(r => (r.defaultServiceIds || []).includes(s.id)).length || (s.method === 'meter' ? 'Tất cả' : 0) }] }); }
    if (tab === 'expenses') { const exs = St.where('expenses', e => e.buildingId === b.id || St.one('expenseAllocations', a => a.expenseId === e.id && a.buildingId === b.id)); body.innerHTML = U.card({ title: 'Chi phí liên quan tòa', icon: 'credit-card', sub: 'Gồm chi phí riêng và phần được phân bổ từ chi phí chung (FR-FIN-05)', actions: U.btn({ label: 'Thêm chi phí', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-exp' }), body: null, id: 'exp-card' }); const w = document.createElement('div'); body.querySelector('#exp-card').appendChild(w); U.table(w, { rows: exs, unit: 'khoản', cols: [{ key: 'code', label: 'Mã', render: e => U.link('#/expenses?s=' + e.code, e.code) }, { key: 'date', label: 'Ngày', render: e => F.date(e.date) }, { key: 'group', label: 'Nhóm chi', render: e => U.chip(e.group, Q.L.expGroup[e.group] || 'gray') }, { key: 'desc', label: 'Diễn giải' }, { key: 'amt', label: 'Số tiền tòa chịu', num: true, render: e => { if (e.buildingId === b.id) return F.vnd(e.amount); const a = St.one('expenseAllocations', x => x.expenseId === e.id && x.buildingId === b.id); return F.vnd(a ? a.amount : 0) + ' <span class="xs muted">(' + (a ? a.pct : 0) + '% chung)</span>'; } }, { key: 'type', label: 'Loại', render: e => Q.L.recordType[e.recordType] }] }); }
    if (tab === 'docs') { const docs = St.where('documents', d => (d.entityType === 'building' && d.entityId === b.id) || (d.entityType === 'landlord' && d.entityId === b.landlordId)); body.innerHTML = U.card({ title: 'Hồ sơ & tài liệu', icon: 'folder', sub: 'Gồm tài liệu tòa và hồ sơ chủ nhà liên kết', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('download', 'dl', 'Tải', { 'data-name': d.fileName }) + (d.source === 'user' ? U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }) : ''))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' }) }); }
    if (tab === 'history') { const logs = St.where('auditLog', x => (x.entityType === 'building' && x.entityId === b.id) || (x.entityType === 'room' && rooms.some(r => r.id === x.entityId))).slice(0, 40); body.innerHTML = U.card({ title: 'Lịch sử thao tác', icon: 'history', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    if (tab === 'perf' && TH.phase.on(2)) { const per = St.state.meta.period; const occ = Q.occupancy(per, b.id); const cf = Q.cashflow(per, { buildingId: b.id }); const op = Q.operatingResult(per, { buildingId: b.id }); body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Hiệu suất (tạm tính)', value: occ.na ? 'N/A' : occ.pct + '%', cap: occ.na ? 'Tòa bảo trì/ngừng – không đủ điều kiện (OI-12)' : occ.days + ' / ' + occ.total + ' ngày có khách (BR-09)', icon: 'gauge', tone: 'blue' })}${U.kpi({ label: 'Thu trong kỳ', value: F.vnd(cf.income), cap: F.periodLabel(per), icon: 'arrow-up', tone: 'green' })}${U.kpi({ label: 'Chi trong kỳ', value: F.vnd(cf.expense), cap: 'Không gồm khấu hao', icon: 'arrow-down', tone: 'red' })}${U.kpi({ label: 'Lợi nhuận vận hành', value: F.vnd(op.result), cap: 'BR-10 – tạm tính', icon: 'trending-up', tone: 'purple' })}</div>` + U.card({ title: 'Hiệu suất tòa ' + TH.phase.tag(2), icon: 'gauge', sub: 'Hiệu suất = ngày có khách / ngày trong kỳ (BR-09, OI-12); tòa bảo trì = N/A', actions: `<a class="link small" href="#/reports/r/occupancy?buildingId=${b.id}">Báo cáo tỷ lệ lấp đầy →</a>`, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Kỳ</th><th class="num">Ngày có khách</th><th class="num">Ngày kỳ</th><th class="num">Hiệu suất</th><th class="num">Thu</th><th class="num">Chi</th><th class="num">Lợi nhuận VH</th></tr></thead><tbody>${['2026-08', '2026-09', '2026-10'].map(p => { const o = Q.occupancy(p, b.id); const c2 = Q.cashflow(p, { buildingId: b.id }); const r2 = Q.operatingResult(p, { buildingId: b.id }); return `<tr><td>${F.periodLabel(p)}</td><td class="num">${o.na ? '-' : o.days}</td><td class="num">${o.na ? '-' : o.total}</td><td class="num bold">${o.na ? 'N/A' : o.pct + '%'}</td><td class="num">${F.vnd(c2.income)}</td><td class="num">${F.vnd(c2.expense)}</td><td class="num">${F.vnd(r2.result)}</td></tr>`; }).join('')}</tbody></table>` }); }
    else if (tab === 'assets' && TH.phase.on(3) && TH.pages.buildingAssetsTab) TH.pages.buildingAssetsTab(body, b);
    else if (['assets', 'perf'].includes(tab)) body.innerHTML = U.card({ body: U.empty({ icon: 'package', title: tab === 'assets' ? 'Tài sản theo tòa – Phase 3' : 'Hiệu suất tòa – Phase 2', text: tab === 'assets' ? 'Danh mục tài sản, QR, kiểm kê hàng tháng (FR-BLD-04, FR-MNT-02).' : 'Hiệu suất = ngày có khách / ngày trong kỳ; công thức chờ chốt OI-12.', action: U.btn({ label: 'Xem scope Phase 2/3', act: 'p2', size: 'btn-sm', cls: 'btn-outline', attrs: { 'data-key': tab === 'assets' ? 'assets' : 'cashbook' } }) }) });
    U.onChange(root, { rf: () => { const d = U.formData(body.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, q, d, { tab })); TH.router.refresh(); } });
    U.bind(root, {
      tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, edit: () => Fm.building(b), 'add-room': () => Fm.room({}, b.id), bulk: () => Fm.roomsBulk(b.id), 'import-rooms': () => TH.go('#/settings/import?type=room'), 'go-landlord': () => TH.go('#/landlords/' + l.id), 'go-catalog': () => TH.go('#/settings/catalog'), 'add-lc': () => Fm.landlordContract(l.id, { buildingIds: [b.id] }), 'add-exp': () => Fm.expense({ buildingId: b.id }), upload: () => Fm.upload('building', b.id), dl: (el) => U.fakePdf(el.dataset.name, ['Tòa: ' + b.name]), 'rm-doc': (el) => { X.removeDocument(el.dataset.id); }, p2: (el) => TH.go('#/coming-soon/' + el.dataset.key),
      actions: (el) => U.menu(el, [{ label: 'Sửa tòa', icon: 'pencil', onClick: () => Fm.building(b) }, { label: 'Ghi nhận trả chủ nhà', icon: 'banknote', onClick: () => { if (!nextDue) return U.toast('info', 'Không có kỳ chờ thanh toán'); Fm.landlordPaid(nextDue); } }, { label: 'Tải lên tài liệu', icon: 'upload', onClick: () => Fm.upload('building', b.id) }, '-', { label: 'Ngừng sử dụng', icon: 'minus-circle', danger: true, disabled: !TH.auth.can('deactivateBuilding'), title: TH.auth.can('deactivateBuilding') ? '' : 'Cần vai trò Quản trị viên (FR-BLD-02)', onClick: async () => { if (await U.confirm({ title: 'Ngừng sử dụng tòa?', text: 'Chặn nếu còn phòng đang thuê/giữ chỗ hoặc HĐ dự thảo (FR-BLD-02). Phòng trống sẽ chuyển Ngừng sử dụng.', ok: 'Ngừng', danger: true })) { try { X.deactivateBuilding(b.id); U.toast('ok', 'Đã ngừng sử dụng tòa'); } catch (e) { U.toast('err', 'Không thể ngừng', e.message); } } } }]),
      more2: (el) => U.menu(el, [{ label: 'Tạo hợp đồng cho phòng trống', icon: 'file-plus', onClick: () => TH.go('#/rooms?buildingId=' + b.id + '&status=ready') }, { label: 'Tạo hóa đơn theo kỳ cho tòa', icon: 'receipt', onClick: () => TH.go('#/invoices/batch?buildingId=' + b.id) }]),
      more: (el) => TH.pages.roomMenu(el, St.get('rooms', el.dataset.id)),
    });
  }, { menu: 'buildings', permission: 'buildings.view', resource: { type: 'building' } });
  /* Phase 2: lưu bộ lọc (meta.savedFilters[route]) – dùng chung cho Tòa nhà / Khách thuê */
  TH.pages.saveFilter = async (route) => { const q = TH.router.current.query || {}; const r = await U.confirm({ title: 'Lưu bộ lọc hiện tại', body: U.field({ label: 'Tên bộ lọc', req: true, input: U.input({ name: 'name', placeholder: 'VD: Tòa HCM đang hoạt động' }) }) + `<div class="xs muted mt8">Điều kiện: ${esc(Object.entries(q).map(([k, v]) => k + '=' + v).join(', ') || '(không có)')}</div>`, ok: 'Lưu' }); if (r && r.name) { X.saveFilterPreset(route, r.name, q); U.toast('ok', 'Đã lưu bộ lọc "' + r.name + '"'); TH.router.refresh(); } };
  TH.pages.filterMenu = (el, route) => { const list = ((St.state.meta.savedFilters || {})[route] || []); U.menu(el, [{ header: 'Bộ lọc đã lưu' }, ...(list.length ? list.map(x => ({ label: x.name, icon: 'bookmark', onClick: () => { TH.router.replaceQuery(x.query); TH.router.refresh(); } })) : [{ label: 'Chưa có bộ lọc', disabled: true }]), '-', { label: 'Lưu bộ lọc hiện tại…', icon: 'plus', onClick: () => TH.pages.saveFilter(route) }, ...(list.length ? [{ label: 'Xóa tất cả bộ lọc đã lưu', icon: 'trash', danger: true, onClick: () => { list.forEach(x => X.removeFilterPreset(route, x.id)); U.toast('ok', 'Đã xóa'); } }] : [])]); };
  document.addEventListener('click', (e) => { const el = e.target.closest('[data-act="save-filter"]'); if (!el || el.disabled) return; e.preventDefault(); TH.pages.filterMenu(el, TH.router.current.path); });
})(window.TH);
