(function (TH) {
  const S = TH.store, Q = TH.q, X = TH.actions, F = TH.f, U = TH.ui, K = TH.kit, esc = F.esc;
  TH.pages.shareNav = (bid, cur) => '<div class="row wrap gap8 mb16">' + [['/shares', 'Cổ phần (UI-31)'], ['/shares/' + bid, 'Bảng kê (UI-32)'], ['/shares/capital', 'Góp vốn / chi thực (UI-33)']].map(([href, label]) => `<a class="btn btn-sm ${href === cur ? 'btn-primary' : 'btn-ghost'}" href="#${href}${href === '/shares/' + bid ? '' : '?building=' + bid}">${label}</a>`).join('') + '</div>';
  TH.pages.capitalTxnDrawer = (kind, l) => K.formDrawer({ title: { contribute: 'Ghi nhận góp vốn', withdraw: 'Ghi nhận rút vốn', payout: 'Chi thực theo M' }[kind], sub: Q.building(l.buildingId).code + ' · ' + Q.shareholder(l.shareholderId).name, modal: true, note: U.note('info', '', kind === 'payout' ? 'M là nghĩa vụ từ bảng kê đã khóa, không phải giao dịch chi. Còn phải trả ' + F.vnd(l.remaining) : 'Lịch theo kỳ trả chủ nhà; còn phải góp ' + F.vnd(l.remaining)), fields: [
    { name: 'amount', label: 'Số tiền', type: 'money', req: true, value: kind === 'withdraw' ? l.paid : l.remaining }, { name: 'date', label: 'Ngày', type: 'date', value: F.today(), req: true },
    { name: 'method', label: 'Phương thức', type: 'select', options: [['bank', 'Chuyển khoản'], ['cash', 'Tiền mặt']], value: 'bank' },
    { name: 'docId', label: 'Chứng từ góp vốn', type: 'select', options: Q.documentsScoped().filter(d => d.status === 'current' && d.objectType === 'shareholder' && d.objectId === l.shareholderId && d.buildingId === l.buildingId).map(d => [d.id, d.name]) },
    { name: 'reason', label: 'Ghi chú / lý do rút vốn', type: 'textarea', req: kind === 'withdraw', span: true }], onSubmit: d => { X[{ contribute: 'recordContribution', withdraw: 'recordWithdrawal', payout: 'recordPayout' }[kind]](Object.assign({}, d, { ownerPaymentId: l.ownerPaymentId, shareRunId: l.shareRunId, shareholderId: l.shareholderId })); U.toast('ok', 'Đã ghi giao dịch'); } });
  TH.router.handle('/shares/capital', (root, p, q) => {
    const codong = TH.auth.role() === 'codong', blds = Q.shareBuildings().filter(b => TH.auth.inScope(b.id)), bid = q.building || (blds[0] || {}).id;
    if (!bid || !TH.auth.inScope(bid)) { root.innerHTML = U.empty({ title: 'Tòa ngoài phạm vi được xem' }); return; }
    const f = { building: bid, sh: codong ? TH.auth.shareholderId() : q.sh, from: q.from, to: q.to }, schedule = Q.capitalSchedule(f), payouts = Q.capitalPayouts(f), txns = Q.capitalTxns(f);
    const tabs = [{ key: 'lich-dong', label: 'Lịch đóng tiền nhà' }, { key: 'chi-thuc', label: 'Chi thực' }, { key: 'tai-san-coc', label: 'Tài sản / cọc' }, { key: 'dau-tu-ban-dau', label: 'Đầu tư ban đầu' }, { key: 'lich-su', label: 'Lịch sử' }], tab = K.pickTab(tabs, q.tab, 'lich-dong');
    const sum = (rows, key) => rows.reduce((s, r) => s + r[key], 0), dueNow = schedule.filter(l => l.dueDate <= F.today()), initial = Q.capitalInitial(bid);
    root.innerHTML = U.pageHead({ title: 'Góp vốn, cọc, tài sản & chi thực', sub: 'Tách nghĩa vụ góp theo UI-05 và chi thực theo M đã khóa UI-32 · ' + (codong ? 'Chỉ giao dịch của tôi' : 'Gồm quỹ CHUNG') }) + TH.pages.shareNav(bid, '/shares/capital')
      + K.filters([{ name: 'building', label: 'Tòa', options: blds.map(b => [b.id, b.code]), value: bid, all: false }, ...(codong ? [] : [{ name: 'sh', label: 'Cổ đông', options: S.all('shareholders').map(h => [h.id, h.code + ' · ' + h.name]) }]), { name: 'from', label: 'Từ ngày', type: 'date' }, { name: 'to', label: 'Đến ngày', type: 'date' }], q)
      + '<div class="grid grid-3 mt16 mb16">' + [ ['Phải góp đến nay', sum(dueNow, 'due')], ['Đã góp đến nay', sum(dueNow, 'paid')], ['Còn phải góp', sum(dueNow, 'remaining'), schedule.filter(l => l.status === 'overdue').length + ' quá hạn · ' + schedule.filter(l => l.soon).length + ' sắp đến hạn'], ['Nghĩa vụ chi theo bảng kê đã khóa ΣM', sum(payouts, 'due')], ['Đã trả', sum(payouts, 'paid')], ['Còn phải trả', sum(payouts, 'remaining')] ].map(([label, value, cap]) => U.kpi({ label, value: F.vnd(value), cap: cap || '', icon: 'wallet', tone: 'blue' })).join('') + '</div>' + U.tabs(tabs, tab) + '<div id="capbody" class="mt16"></div>';
    K.bindFilters(root); U.bind(root, { tab: el => TH.router.setQuery({ tab: el.dataset.key }) }); const body = root.querySelector('#capbody');
    if (tab === 'lich-dong') {
      body.innerHTML = K.tableCard('ctable', 'Lịch góp theo kỳ trả chủ nhà (không lưu lịch riêng)');
      U.table(body.querySelector('#ctable'), { rows: schedule, pageSize: 18, cols: [
        { key: 'p', label: 'Kỳ / hạn', render: l => U.cell2(TH.auth.can('owners.view') ? U.link('#/owner-payments?building=' + bid, l.from + ' · ' + l.months + ' tháng') : esc(l.from), F.date(l.dueDate)) },
        { key: 'h', label: 'Cổ đông', render: l => esc(Q.shareholder(l.shareholderId).code + ' · ' + Q.shareholder(l.shareholderId).name) }, { key: 'r', label: 'Tỷ lệ', num: true, render: l => l.pct + '%' },
        { key: 'd', label: 'Tiền kỳ / phải góp', num: true, render: l => U.cell2(F.vnd(l.due), F.vnd(l.periodAmount) + ' × ' + l.pct + '%') }, { key: 'paid', label: 'Đã góp', num: true, render: l => F.vnd(l.paid) }, { key: 'rem', label: 'Còn lại', num: true, render: l => F.vnd(l.remaining) },
        { key: 's', label: 'Trạng thái', render: l => U.chip({ paid: 'Đủ', overdue: 'Quá hạn', partial: 'Thiếu', unpaid: 'Chưa góp' }[l.status], l.status === 'overdue' ? 'red' : l.status === 'paid' ? 'green' : 'gray') + (l.soon ? U.chip('Sắp đến hạn', 'amber') : '') },
        { key: 'a', label: '', render: l => (l.remaining > 0 ? U.btn({ label: 'Ghi góp', act: 'contribute', attrs: { 'data-id': l.id }, perm: 'capital.manage', size: 'btn-xs' }) : '') + (l.paid > 0 ? U.btn({ label: 'Rút vốn', act: 'withdraw', attrs: { 'data-id': l.id }, perm: 'capital.manage', size: 'btn-xs' }) : '') }] });
    }
    if (tab === 'chi-thuc') {
      body.innerHTML = U.note('info', 'M không phải giao dịch chi', 'Chỉ bảng kê đã khóa mới phát sinh nghĩa vụ. Ghi chi thực tạo giao dịch riêng; số tiền không vượt M còn lại.') + '<div class="mt16">' + K.tableCard('ctable', 'Nghĩa vụ chi theo bảng kê đã khóa') + '</div>';
      U.table(body.querySelector('#ctable'), { rows: payouts, pageSize: 18, cols: [{ key: 'p', label: 'Bảng kê', render: l => U.link('#/shares/' + bid + '?period=' + l.period, F.periodShort(l.period)) }, { key: 'h', label: 'Cổ đông', render: l => esc(Q.shareholder(l.shareholderId).name) }, { key: 'm', label: 'M', num: true, render: l => F.vnd(l.due) }, { key: 'paid', label: 'Đã trả', num: true, render: l => F.vnd(l.paid) }, { key: 'rem', label: 'Còn trả', num: true, render: l => F.vnd(l.remaining) + (l.overpaid ? '<small class="d-block red">Đã trả dư ' + F.vnd(l.overpaid) + '</small>' : '') }, { key: 'a', label: '', render: l => l.remaining > 0 ? U.btn({ label: 'Chi thực', act: 'payout', attrs: { 'data-id': l.id }, perm: 'capital.manage', size: 'btn-xs' }) : '' }] });
      body.insertAdjacentHTML('beforeend', U.card({ title: 'Giao dịch chi thực', body: txns.filter(t => t.kind === 'payout' && t.status !== 'void').map(t => `<div class="mini-row"><b>${F.date(t.date)}</b><span>${esc(t.method === 'bank' ? 'Chuyển khoản' : 'Tiền mặt')} · ${t.docId ? esc((S.get('documents', t.docId) || {}).name || t.docId) : 'Chưa gắn chứng từ'}</span><b>${F.vnd(t.amount)}</b></div>`).join('') || 'Chưa chi thực' }));
    }
    if (tab === 'tai-san-coc') {
      if (q.from && q.to && q.from > q.to) { body.innerHTML = U.note('warn','Khoảng ngày không hợp lệ','Từ ngày phải trước hoặc bằng Đến ngày'); return; }
      const stats = Q.capitalAssetsAt(bid,q.to || F.today());
      body.innerHTML = U.note('info','Số dư tại '+F.date(stats.at),'Tài sản/cọc lấy tại Đến ngày; giá trị còn lại theo kỳ khấu hao '+F.periodLabel(stats.period)+'. Từ ngày dùng cho các tab giao dịch, không trừ số dư đầu kỳ.')
        + U.card({ title:'Cọc chủ nhà – tài sản phải thu hồi',body:'<b>'+(stats.deposit == null ? 'Chưa đủ dữ liệu lịch sử' : F.vnd(stats.deposit))+'</b><p class="small muted">Thu hồi khi kết thúc hợp đồng; không vào doanh thu.</p>' })
        + '<div class="mt16">'+U.card({title:'Tài sản theo tòa',body:'<table class="tbl compact"><thead><tr><th>Mã / tên</th><th>Sở hữu</th><th>SL</th><th class="num">Còn lại</th></tr></thead><tbody>'+stats.assets.map(a=>'<tr><td>'+esc(a.code+' · '+a.name)+'</td><td>'+esc(TH.calc.assets.ownLabel(a.ownership))+'</td><td>'+a.qty+'</td><td class="num">'+(a.remaining == null ? 'Chưa đủ dữ liệu / chính sách KH' : F.vnd(a.remaining))+'</td></tr>').join('')+'</tbody></table>'})+'</div>';
    }
    if (tab === 'dau-tu-ban-dau') {
      if (!initial) body.innerHTML = U.empty({ title: 'Chưa có dữ liệu đầu tư ban đầu tòa này' });
      else { const r = initial.result;
        body.innerHTML = K.kpis([['Chi', r.expense], ['Thu', r.receipt], ['Chênh lệch', r.difference], ['Đã đóng', r.paid], ['Thực nhận', r.received]].map(([label, value]) => ({ label, value: F.vnd(value), icon: 'wallet', tone: 'blue' }))) + U.card({ title: 'THU CHI BAN ĐẦU G1 · SRC-07', body: `<table class="tbl compact"><thead><tr><th>Diễn giải / nguồn</th><th class="num">Chi</th><th class="num">Thu</th></tr></thead><tbody>${initial.lines.map(l => `<tr><td>${esc(l.label)}<small class="d-block muted">${esc(l.source_ref)}</small></td><td class="num">${F.vnd(l.expense)}</td><td class="num">${F.vnd(l.receipt)}</td></tr>`).join('')}</tbody></table>` })
          + '<div class="mt16">' + U.card({ title: 'Theo cổ đông', body: `<table class="tbl compact"><thead><tr><th>Cổ đông</th><th class="num">Tỷ lệ</th><th class="num">Phần lỗ</th><th class="num">Đã đóng</th><th class="num">Thực nhận</th></tr></thead><tbody>${r.holders.map(h => `<tr><td>${esc(Q.shareholder(h.shareholderId).name)}</td><td class="num">${h.pct}%</td><td class="num">${F.vnd(h.loss)}</td><td class="num">${F.vnd(h.paid)}</td><td class="num">${F.vnd(h.received)}</td></tr>`).join('')}</tbody></table>` }) + '</div>'
          + '<div class="mt16">' + U.card({ title: '8 khoản đầu tư · ' + F.vnd(r.investment), sub: 'Đã nằm trong THU CHI E39–E53 – tính 1 lần. Tài sản bắt đầu khấu hao 2026-10.', body: initial.assets.map(a => `<div class="mini-row"><span>${esc(a.name)}<small class="d-block muted">Trùng ${esc(a.dupOf)}</small></span><b>${F.vnd(a.cost)}</b></div>`).join('') }) + '</div>';
      }
    }
    if (tab === 'lich-su') {
      body.innerHTML = K.tableCard('ctable', 'Giao dịch góp / rút / chi thực');
      U.table(body.querySelector('#ctable'), { rows: txns, pageSize: 20, cols: [{ key: 'c', label: 'Mã / ngày', render: t => U.cell2(esc(t.code), F.date(t.date)) }, { key: 'h', label: 'Cổ đông', render: t => esc(Q.shareholder(t.shareholderId).name) }, { key: 'k', label: 'Loại', render: t => esc({ contribute: 'Góp', withdraw: 'Rút vốn', payout: 'Chi thực' }[t.kind]) }, { key: 'm', label: 'Tiền', num: true, render: t => F.vnd(t.amount) }, { key: 'd', label: 'Chứng từ / lý do', render: t => (t.docId && Q.canDownloadDoc(S.get('documents', t.docId)) ? `<a data-act="doc" data-id="${t.docId}">${esc((S.get('documents', t.docId) || {}).name)}</a>` : '') + '<small>' + esc(t.voidReason || t.reason || '') + '</small>' }, { key: 'a', label: 'Trạng thái', render: t => t.status === 'void' ? U.chip('Đã hủy', 'gray') : U.btn({ label: 'Hủy', act: 'void', attrs: { 'data-id': t.id }, perm: 'capital.manage', size: 'btn-xs' }) }] });
    }
    K.wrapTables(root);
    U.bind(root, { contribute: el => TH.pages.capitalTxnDrawer('contribute', schedule.find(l => l.id === el.dataset.id)), withdraw: el => TH.pages.capitalTxnDrawer('withdraw', schedule.find(l => l.id === el.dataset.id)), payout: el => TH.pages.capitalTxnDrawer('payout', payouts.find(l => l.id === el.dataset.id)), doc: el => TH.pages.docDownload(el.dataset.id), void: el => K.formDrawer({ title: 'Hủy giao dịch vốn', fields: [{ name: 'reason', label: 'Lý do', req: true, type: 'textarea', span: true }], onSubmit: d => X.voidShareTxn(el.dataset.id, d.reason) }) });
  });
})(window.TH);
