/* Spec v1.8 §4.26.1/§4.26.11 – Hiệu suất thu tiền (#/hr/collection-performance): bảng NV × tòa (số phòng, DT niêm yết, DT phải thu, M1/M2/M3, tổng sau 3 mốc, DV, tỷ lệ DV/DT,
   thu thêm, tổng DT thu được, hiệu suất %, mức lương/phòng, lương theo phòng); lọc kỳ / tổ chức / NV / tòa; drill-down về giao dịch thu (Payment Allocation). */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc, C = TH.chart;
  const pct = (x) => (Math.round(x * 1000) / 10) + '%';
  const effChip = (e) => U.chip(e + '%', e >= 90 ? 'green' : e >= 75 ? 'blue' : e >= 60 ? 'amber' : 'red');
  const drill = (row) => {
    const c = Q.buildingCollection(row.buildingId, row.period); const rule = St.get('payrollRuleVersions', row.ruleVersionId) || Q.payrollRule(Q.periodEndDate(row.period), { role: row.role });
    const byM = ['M1', 'M2', 'M3', 'LATE'].map(m => ({ m, list: c.allocs.filter(a => a.milestone === m) }));
    U.modal({ title: 'Drill-down – ' + esc(row.employee.name) + ' · ' + esc(row.building.name), wide: true, sub: 'Kỳ ' + F.periodLabel(row.period) + ' · ' + Q.label('payrollRole', row.role) + ' · mọi số thu truy được về Payment / Payment Allocation (§4.26.10)', body: `
      <div class="grid grid-4 mb12">${U.miniStat({ label: 'Số phòng', value: row.rooms, icon: 'door', tone: 'blue' })}${U.miniStat({ label: 'DT niêm yết', value: F.vnd(row.listed), icon: 'tag', tone: 'gray' })}${U.miniStat({ label: 'Tổng DT thu được', value: F.vnd(row.collected), icon: 'banknote', tone: 'green' })}${U.miniStat({ label: 'Hiệu suất', value: row.efficiency + '%', icon: 'trending-up', tone: 'amber' })}</div>
      ${U.kv([['Công thức', '<code>Tổng DT sau 3 mốc = M1 + M2 + M3</code> · <code>Tỉ lệ DV/DT = Dịch vụ / DT phải thu</code> · <code>Hiệu suất = Tổng DT thu được / DT niêm yết × 100</code> · <code>Lương theo phòng = Số phòng × Mức lương/phòng</code>'], ['Tổng DT thu được', (rule ? esc({ M123: 'M1+M2+M3', M123_PLUS_EXTRA: 'M1+M2+M3 + Thu thêm', M123_MINUS_SERVICE: 'M1+M2+M3 − Dịch vụ', M123_MINUS_SERVICE_PLUS_EXTRA: 'M1+M2+M3 − Dịch vụ + Thu thêm' }[rule.collectedFormula] || rule.collectedFormula) : '-') + ' = ' + F.vnd(row.after3) + ' − ' + F.vnd(row.service) + ' + ' + F.vnd(row.extra) + ' = <b>' + F.vnd(row.collected) + '</b> ' + U.chip('Chờ chốt §4.26.3', 'amber')], ['Payroll Rule', (rule ? esc(rule.code + ' – ' + rule.name) + ' · bậc ' + esc(row.tier) + ' → ' : '') + '<b>' + F.vnd(row.ratePerRoom) + '/phòng</b> × ' + row.rooms + ' = <b>' + F.vnd(row.roomSalary) + '</b>' + (rule && rule.confirmation ? ' ' + U.chip('NEED_BUSINESS_CONFIRMATION', 'amber') : '')]], 'one')}
      <div class="tbl-wrap mt12"><table class="tbl compact"><thead><tr><th>Mốc</th><th class="num">Số khoản</th><th class="num">Số tiền</th><th>Giao dịch thu (Payment → Hóa đơn)</th></tr></thead><tbody>${byM.map(x => `<tr><td>${Q.chip('milestone', x.m)}${x.m === 'LATE' ? ' <span class="xs muted">thu thêm</span>' : ''}</td><td class="num">${x.list.length}</td><td class="num"><b>${F.vnd(F.sum(x.list, a => a.amount))}</b></td><td class="xs">${x.list.slice(0, 12).map(a => { const inv = St.get('invoices', a.invoiceId) || {}; return U.link('#/payments/' + a.paymentId, esc(a.payment.code)) + ' ' + F.date(a.payment.date) + ' → ' + esc(inv.code || '') + ' ' + F.vnd(a.amount); }).join('<br>') + (x.list.length > 12 ? '<br>… +' + (x.list.length - 12) + ' khoản' : '') || '<span class="muted">—</span>'}</td></tr>`).join('')}<tr class="dist-total"><td>Dịch vụ (Invoice Line SERVICE)</td><td></td><td class="num">${F.vnd(row.service)}</td><td class="xs muted">Tỉ lệ DV/DT = ${pct(row.serviceRatio)} · ${U.link('#/invoices?buildingId=' + row.buildingId + '&period=' + row.period, 'xem hóa đơn tòa')}</td></tr></tbody></table></div>`, footer: U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'close' }), onMount: (m) => U.bind(m.el, { close: () => m.close() }) });
  };
  TH.pages.perfDrill = drill;

  TH.router.register('/hr/collection-performance', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Hiệu suất thu tiền' }]);
    const period = q.period || St.state.meta.period; const f = { period, orgUnitId: q.orgUnitId || '', employeeId: q.employeeId || '', buildingId: q.buildingId || '', role: q.role || '' };
    const rows = Q.perfRows(period, f).filter(r => !f.role || r.role === f.role); const t = Q.perfTotals(rows); const ms = Q.milestones(); const pr = Q.payroll(period);
    const byB = {}; rows.forEach(r => { if (!byB[r.buildingId]) byB[r.buildingId] = r; });
    root.innerHTML = `${U.pageHead({ title: 'Hiệu suất thu tiền', sub: 'Thu M1/M2/M3 theo tòa phụ trách → tổng sau 3 mốc → tách dịch vụ → cộng thu thêm → hiệu suất → mức lương/phòng (§4.26.1–4.26.3). Nguồn: Payment Allocation gắn mốc thu, không nhập tay.', acts: [U.btn({ label: pr ? 'Mở bảng lương ' + F.periodShort(period) : 'Mở kỳ lương', icon: 'banknote', cls: 'btn-primary', act: 'payroll', attrs: { 'data-guide': 'perf-payroll' } }), U.btn({ label: 'Export', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.dimFilter(f, { dims: ['period', 'orgUnitId', 'employeeId', 'buildingId'], inline: 4, extraFields: U.field({ label: 'Vai trò phân công', input: U.select({ name: 'role', value: f.role, all: 'Phụ trách chính + Hỗ trợ', options: [['manager', 'Phụ trách chính'], ['support', 'Hỗ trợ']], attrs: { 'data-on': 'f' } }) }) })}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'DT niêm yết', value: F.vnd(t.listed), cap: t.rooms + ' phòng · ' + Object.keys(byB).length + ' tòa · ' + t.rows + ' dòng NV×tòa', icon: 'tag', tone: 'blue' })}${U.kpi({ label: 'Tổng DT sau 3 mốc', value: F.vnd(t.after3), cap: ms.map(m => m.code + ' ≤ ' + F.pad(m.day)).join(' · ') + ' · M1 ' + F.short(t.M1) + ' / M2 ' + F.short(t.M2) + ' / M3 ' + F.short(t.M3), icon: 'calendar-check', tone: 'green' })}${U.kpi({ label: 'Dịch vụ / thu thêm', value: F.vnd(t.service), cap: 'Tỉ lệ DV/DT ' + pct(t.serviceRatio) + ' · thu thêm ' + F.short(t.extra), icon: 'zap', tone: 'amber' })}${U.kpi({ label: 'Hiệu suất chung', value: t.efficiency + '%', cap: 'Tổng DT thu được ' + F.short(t.collected) + ' / DT niêm yết → lương theo phòng ' + F.short(t.roomSalary), icon: 'trending-up', tone: 'purple' })}</div>
    ${period === '2026-09' && St.state.meta.collectionWorkbookSummary ? U.card({ title: 'Tiến độ thu theo quản lý · chốt 16/09/2026 (sổ nguồn)', icon: 'file-spreadsheet', sub: 'Đối chiếu import · không tạo giao dịch Payment từ số tổng hợp', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Quản lý</th><th class="num">DT phải thu</th><th class="num">Thực thu</th><th class="num">Tỷ lệ</th><th class="num">Phá HĐ phải thu</th><th class="num">Phá HĐ thu được</th></tr></thead><tbody>${St.state.meta.collectionWorkbookSummary.map(x=>`<tr><td>${esc(x.managerName)}</td><td class="num">${F.vnd(x.receivable)}</td><td class="num">${F.vnd(x.collected)}</td><td class="num"><b class="${x.rate>100?'amber':''}">${String(x.rate).replace('.',',')}%</b></td><td class="num">${F.vnd(x.terminatedReceivable)}</td><td class="num">${F.vnd(x.terminatedCollected)}</td></tr>`).join('')}</tbody></table></div>${U.note('warn','Đối chiếu số người vượt 100%',`Sổ nguồn này thể hiện ${St.state.meta.collectionWorkbookSummary.filter(x=>x.rate>100).length} quản lý trên 100%. Bản plan nêu 4; cần đối chiếu với workbook đầy đủ. Các tỷ lệ đã được giữ nguyên như nguồn.`)}` }) : ''}
    ${U.relatedStrip({ id: 'perf-related', cls: 'mb16', items: [
      { key: 'formula', title: 'Công thức & rule', icon: 'info', summary: 'Hiệu suất = Tổng DT thu được / DT niêm yết × 100', meta: 'Mẫu số là DT niêm yết, không phải DT phải thu (§4.26.3)', body: `<div class="small">${U.kv([['Tổng DT sau 3 mốc', 'M1 + M2 + M3'], ['Tỉ lệ DV/DT', 'Dịch vụ / DT phải thu'], ['Tổng DT thu được', 'M1+M2+M3 − Dịch vụ + Thu thêm ' + U.chip('Chờ chốt §4.26.3', 'amber')], ['Hiệu suất (%)', 'Tổng DT thu được / DT niêm yết × 100'], ['Lương theo phòng', 'Số phòng × Mức lương/phòng (Payroll Rule Version §4.26.4)']], 'one')}</div>` },
      { key: 'rules', title: 'Payroll Rule Version', icon: 'sliders', summary: Q.payrollRules().filter(r => r.status !== 'inactive').length + ' version hiệu lực', meta: Q.payrollRules().map(r => r.code).join(' · '), actions: TH.auth.can('payroll.manage') ? U.btn({ label: 'Thêm version', icon: 'plus', size: 'btn-xs', cls: 'btn-outline', act: 'rule-add' }) : '', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Version</th><th>Đối tượng</th><th>Hiệu lực</th><th>Bậc → mức lương/phòng</th><th></th></tr></thead><tbody>${Q.payrollRules().map(r => `<tr><td><b>${esc(r.code)}</b><div class="xs muted">${esc(r.name)}</div></td><td>${(r.roles || []).map(x => Q.chip('payrollRole', x)).join(' ')}</td><td class="xs">${F.date(r.effectiveFrom)}${r.effectiveTo ? ' → ' + F.date(r.effectiveTo) : ' → ∞'}</td><td class="xs">${(r.tiers || []).map(tt => esc(tt.label || (tt.from + '–' + (tt.to == null ? '∞' : tt.to) + '%')) + ': ' + F.vnd(tt.rate)).join(' · ')} ${r.confirmation ? U.chip('Chờ chốt', 'amber') : ''}</td><td>${TH.auth.can('payroll.manage') ? U.iconBtn('pencil', 'rule-edit', 'Sửa / tạo version', { 'data-id': r.id }) : ''}</td></tr>`).join('')}</tbody></table></div>` },
      { key: 'chart', title: 'Hiệu suất theo tòa', icon: 'bar-chart-2', summary: Object.keys(byB).length + ' tòa', meta: Object.values(byB).slice(0, 3).map(r => (r.building.name || '').replace('Tòa ', '') + ' ' + r.efficiency + '%').join(' · '), body: Object.keys(byB).length ? C.vbar({ items: Object.values(byB).map(r => ({ label: (r.building.name || '').replace('Tòa ', ''), value: r.efficiency })), height: 170, unit: '%' }) : '<div class="muted small">Không có dữ liệu</div>' }
    ] })}
    ${U.card({ title: 'Hiệu suất theo nhân viên × tòa (' + rows.length + ')', icon: 'clipboard-list', sub: 'Snapshot theo NV + tòa + kỳ khi mở kỳ lương – đổi phân công sau không đổi bảng lương đã chốt (§4.26.1)', body: null, id: 'perf-tbl', attrs: 'data-guide="perf-table"' })}`;
    const cols = [
      { key: 'emp', label: 'Nhân viên', render: r => U.cell2(U.link('#/hr/' + r.employeeId, esc(r.employee.name), 'bold'), esc((Q.employeeUnit(r.employeeId) || {}).name || r.employee.code)) },
      { key: 'b', label: 'Mã tòa', render: r => U.cell2(U.link('#/buildings/' + r.buildingId, esc(r.building.code || '')), esc((r.building.name || '').replace('Tòa ', '')) + ' · ' + Q.label('payrollRole', r.role)) },
      { key: 'rooms', label: 'Số phòng', num: true, sortable: true, render: r => r.rooms },
      { key: 'listed', label: 'DT niêm yết', num: true, sortable: true, render: r => F.vnd(r.listed) },
      { key: 'recv', label: 'DT phải thu', num: true, sortable: true, render: r => F.vnd(r.receivable) },
      { key: 'm1', label: 'DT mốc 1', num: true, render: r => F.vnd(r.M1) }, { key: 'm2', label: 'DT mốc 2', num: true, render: r => F.vnd(r.M2) }, { key: 'm3', label: 'DT mốc 3', num: true, render: r => F.vnd(r.M3) },
      { key: 'after3', label: 'Tổng DT sau 3 mốc', num: true, sortable: true, render: r => `<b>${F.vnd(r.after3)}</b>` },
      { key: 'svc', label: 'Dịch vụ', num: true, render: r => F.vnd(r.service) }, { key: 'svcr', label: 'Tỉ lệ DV/DT', num: true, render: r => pct(r.serviceRatio) },
      { key: 'extra', label: 'DT thu thêm', num: true, render: r => F.vnd(r.extra) },
      { key: 'col', label: 'Tổng DT thu được', num: true, sortable: true, sortVal: r => r.collected, render: r => `<b>${F.vnd(r.collected)}</b>` },
      { key: 'eff', label: 'Hiệu suất (%)', num: true, sortable: true, sortVal: r => r.efficiency, render: r => effChip(r.efficiency) },
      { key: 'rate', label: 'Mức lương/phòng', num: true, render: r => `<span title="${esc(r.ruleCode + ' · bậc ' + r.tier)}">${F.vnd(r.ratePerRoom)}</span>` },
      { key: 'sal', label: 'Tổng lương theo phòng', num: true, sortable: true, sortVal: r => r.roomSalary, render: r => `<b>${F.vnd(r.roomSalary)}</b>` },
      { key: 'actions', label: '', render: r => U.iconBtn('search', 'drill', 'Drill-down giao dịch thu', { 'data-key': r.key, 'data-guide': 'perf-drill' }), hideable: false }];
    const tbl = U.table(root.querySelector('#perf-tbl'), { rows, unit: 'dòng', pageSize: 20, colPrefsKey: 'perf', cols, footer: (rs) => { const tt = Q.perfTotals(rs); return `<tr class="dist-total"><td colspan="2">Tổng (${rs.length})</td><td class="num">${tt.rooms}</td><td class="num">${F.vnd(tt.listed)}</td><td class="num">${F.vnd(tt.receivable)}</td><td class="num">${F.vnd(tt.M1)}</td><td class="num">${F.vnd(tt.M2)}</td><td class="num">${F.vnd(tt.M3)}</td><td class="num">${F.vnd(tt.after3)}</td><td class="num">${F.vnd(tt.service)}</td><td class="num">${pct(tt.serviceRatio)}</td><td class="num">${F.vnd(tt.extra)}</td><td class="num">${F.vnd(tt.collected)}</td><td class="num">${tt.efficiency}%</td><td></td><td class="num">${F.vnd(tt.roomSalary)}</td><td></td></tr>`; } });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, payroll: () => TH.go('#/hr/payroll?period=' + period), export: () => { const n = X.exportPerformance(period, rows); U.toast('ok', 'Đã xuất hiệu suất thu tiền', n + ' dòng'); }, drill: (b) => { const r = rows.find(x => x.key === b.dataset.key); if (r) drill(r); }, 'rule-add': () => TH.forms.payrollRule(), 'rule-edit': (b) => TH.forms.payrollRule(St.get('payrollRuleVersions', b.dataset.id)) });
  }, { menu: 'collection-perf', permission: 'performance.view', scopeKey: 'hr' });
})(window.TH);
