(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const cMenu = (btn, c) => { const s = Q.contractStatus(c); const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/contracts/' + c.id) }];
    if (c.status === 'draft') items.push({ label: 'Sửa nháp', icon: 'pencil', onClick: () => TH.go('#/contracts/new?id=' + c.id) }, { label: 'Kích hoạt', icon: 'check-circle', onClick: () => TH.go('#/contracts/new?id=' + c.id + '&step=5') }, { label: 'Hủy', icon: 'x-circle', danger: true, onClick: () => Fm.cancelContract(c) });
    if (c.status === 'active') items.push({ label: 'Gia hạn', icon: 'refresh', onClick: () => Fm.renew(c) }, { label: 'Tạo hóa đơn', icon: 'receipt', onClick: () => TH.go('#/invoices/batch?buildingId=' + c.buildingId + '&room=' + c.roomId) }, { label: 'Kết thúc hợp đồng', icon: 'x-circle', danger: true, onClick: () => Fm.terminate(c) });
    items.push('-', { label: 'Tải PDF', icon: 'download', onClick: () => U.fakePdf('Hop dong ' + c.code, ['Khách: ' + Q.tenant(c.tenantId).name, 'Phòng: ' + Q.room(c.roomId).code, 'Thời hạn: ' + F.date(c.start) + ' - ' + F.date(c.end), 'Giá: ' + F.vnd(c.price), 'Cọc: ' + F.vnd(c.deposit)]) }); U.menu(btn, items); };
  /* ---------- Danh sách ---------- */
  TH.router.register('/contracts', (root, p, q) => {
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Hợp đồng' }]);
    const f = { s: q.s || '', buildingId: q.buildingId || '', status: q.status || '', exp: q.exp || '', managerId: q.managerId || '' };
    const all = St.all('contracts'); const withS = all.map(c => ({ c, s: Q.contractStatus(c) }));
    const cnt = (k) => k ? withS.filter(x => x.s === k).length : all.length;
    const rows = withS.filter(x => (!f.s || F.norm(x.c.code + ' ' + Q.tenant(x.c.tenantId).name + ' ' + Q.tenant(x.c.tenantId).phone).includes(F.norm(f.s))) && (!f.buildingId || x.c.buildingId === f.buildingId) && (!f.status || (f.status === 'active' ? ['active', 'expiring'].includes(x.s) : x.s === f.status)) && (!f.exp || (x.s === 'expiring')) && (!f.managerId || x.c.managerId === f.managerId)).sort((a, b) => F.cmp(b.c.createdAt || b.c.start, a.c.createdAt || a.c.start));
    root.innerHTML = `${U.pageHead({ title: 'Hợp đồng', sub: 'Theo dõi hiệu lực, thời hạn và các hợp đồng cần hành động.', acts: [U.btn({ label: 'Tạo hợp đồng', icon: 'plus', cls: 'btn-primary', act: 'new', attrs: { 'data-guide': 'contract-new' } })] })}
    ${U.statusTabs([{ key: '', label: 'Tất cả', count: cnt() }, { key: 'draft', label: 'Dự thảo', count: cnt('draft'), color: 'gray' }, { key: 'active', label: 'Hiệu lực', count: cnt('active') + cnt('expiring'), color: 'green' }, { key: 'expiring', label: 'Sắp hết hạn', count: cnt('expiring'), color: 'amber' }, { key: 'ended', label: 'Đã kết thúc', count: cnt('ended'), color: 'gray' }, { key: 'cancelled', label: 'Hủy', count: cnt('cancelled'), color: 'red' }], f.status)}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Mã hợp đồng, khách thuê, số điện thoại...', icon: 'search' }), cls: 'wide' }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kỳ hết hạn', input: U.select({ name: 'exp', value: f.exp, all: 'Tất cả thời gian', options: [['35', 'Trong 35 ngày tới']], attrs: { 'data-on': 'f' } }) }), `<details class="filter-more"><summary>${I('filter')} Bộ lọc khác</summary><div class="filter-pop">${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả nhân viên', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })}</div></details>`], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.card({ title: `Danh sách hợp đồng <span class="muted" style="font-weight:400">(${rows.length})</span>`, actions: U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', size: 'btn-sm', act: 'export' }), body: null, id: 'tbl-card', attrs: 'data-guide="contracts-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, selectable: true, unit: 'hợp đồng', rowKey: x => x.c.id, rowHref: x => '#/contracts/' + x.c.id, densityControl: true, cols: [
      { key: 'code', label: 'Hợp đồng / Khách', sortable: true, sortVal: x => x.c.code, render: x => U.cell2(U.link('#/contracts/' + x.c.id, esc(x.c.code), 'bold'), U.link('#/tenants/' + x.c.tenantId, esc(Q.tenant(x.c.tenantId).name))) },
      { key: 'room', label: 'Phòng / Tòa', render: x => U.cell2(esc(Q.room(x.c.roomId).code), esc(Q.building(x.c.buildingId).name)) }, { key: 'term', label: 'Thời hạn', sortable: true, sortVal: x => x.c.end, render: x => U.cell2(Q.contractTermLabel(x.c), F.date(x.c.start) + ' – ' + F.date(x.c.actualEnd || x.c.end)) },
      { key: 'price', label: 'Giá thuê', num: true, render: x => F.vnd(x.c.price) }, { key: 'dep', label: 'Tiền cọc', num: true, render: x => F.vnd(x.c.deposit) }, { key: 'mgr', label: 'Người phụ trách', render: x => esc(Q.userName(x.c.managerId)) }, { key: 'st', label: 'Trạng thái', sortable: true, sortVal: x => x.s, render: x => Q.chip('contract', x.s) },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': x.c.id } }), x.c.status === 'active' ? U.actBtn({ icon: 'refresh', label: 'Gia hạn', act: 'renew', attrs: { 'data-id': x.c.id } }) : '', U.moreBtn(x.c.id)]) }] });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { new: () => TH.go('#/contracts/new'), stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { status: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => TH.go('#/contracts/' + b.dataset.id), renew: (b) => Fm.renew(St.get('contracts', b.dataset.id)), more: (b) => cMenu(b, St.get('contracts', b.dataset.id)), export: () => { F.download('hop-dong.csv', F.csv(rows.map(x => [x.c.code, Q.tenant(x.c.tenantId).name, Q.room(x.c.roomId).code, x.c.start, x.c.end, x.c.price, x.c.deposit, Q.label('contract', x.s)]), ['Mã', 'Khách', 'Phòng', 'Bắt đầu', 'Kết thúc', 'Giá', 'Cọc', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất danh sách'); } });
  }, { menu: 'contracts', permission: 'contracts.view' });

  /* ---------- Tạo hợp đồng ---------- */
  const STEPS = [{ title: 'Khách & phòng', sub: 'Chọn khách, phòng, thời hạn' }, { title: 'Giá, dịch vụ & thành viên', sub: 'Giá thuê, cọc, dịch vụ, người ở' }, { title: 'Kiểm tra & kích hoạt', sub: 'Review, lưu nháp hoặc kích hoạt' }];
  TH.router.register('/contracts/new', (root, p, q) => {
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Tạo hợp đồng' }]);
    const draft = q.id ? St.get('contracts', q.id) : null; const step = q.step === '5' && draft && draft.status === 'draft' ? 5 : 1;
    if (step === 5) return renderReview(root, draft);
    // Phase 2: prefill từ giao dịch chốt thuê (?deal=) hoặc trích xuất OCR (?ocr=)
    const deal = q.deal && TH.phase.on(2) ? St.get('deals', q.deal) : null; const ocr = q.ocr ? Q.ocrJob(q.ocr) : null; const of = (k) => { const x = ocr && (ocr.fields || []).find(f => f.key === k); return x ? x.value : ''; };
    const ocrE = ocr && TH.ocrParser ? TH.ocrParser.entities(ocr) : null; const ocrRoom = ocrE ? (ocrE.room.match || St.one('rooms', r => r.code === of('roomCode'))) : null; const ocrTenant = ocrE && ocrE.tenant.match && !ocrE.tenant.weak ? ocrE.tenant.match : null;
    const room0 = q.room ? Q.room(q.room) : (draft ? Q.room(draft.roomId) : deal ? Q.room(deal.roomId) : ocrRoom);
    const d = { tenantId: q.tenant || (draft ? draft.tenantId : deal ? deal.tenantId : ocrTenant ? ocrTenant.id : ''), roomId: room0 ? room0.id : '', buildingId: room0 ? room0.buildingId : '', start: draft ? draft.start : deal ? deal.moveIn : ocr ? F.fromVN(of('start')) : '2026-11-01', end: draft ? draft.end : deal ? F.addDays(F.addMonths(deal.moveIn, deal.months || 12), -1) : ocr ? F.fromVN(of('end')) : '2027-10-31', payDay: draft ? draft.payDay : ocr ? Number(of('payDay')) || 25 : 5, listPrice: draft ? draft.listPrice : (room0 ? room0.price : ''), price: draft ? draft.price : deal ? deal.price : ocr ? F.num(of('price')) : (room0 ? room0.price : ''), deposit: draft ? draft.deposit : deal ? deal.deposit : ocr ? F.num(of('deposit')) : (room0 ? room0.price * 2 : ''), note: draft ? draft.note : deal ? deal.note : ocr ? [of('transferNote') ? 'Nội dung CK: ' + of('transferNote') : '', of('note')].filter(Boolean).join(' · ') : '' };
    /* OCR (template HĐ cho thuê phòng): đơn giá dịch vụ → mã dịch vụ catalog (điện/nước tính theo công tơ nên không đưa vào dịch vụ HĐ); giá lấy từ hợp đồng nếu có, số xe → GUIXE qty + dòng xe */
    const ocrVehicles = ocr ? Math.max(0, Math.min(10, F.num(of('vehicleCount')))) : 0; const ocrSvc = ocr ? { INTERNET: F.num(of('svc_internet')), QUANLY: F.num(of('svc_common')), GUIXE: ocrVehicles ? (F.num(of('svc_ebike')) || F.num(of('svc_evcar'))) : 0 } : null;
    let services = draft ? Q.contractServices(draft.id).map(s => Object.assign({}, s)) : deal ? (deal.serviceIds || []).map(id => { const s = Q.service(id); return s.id ? { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: '' } : null; }).filter(Boolean).concat((deal.extraServices || []).map(x => ({ serviceId: null, name: x.name, unit: x.unit || 'Tháng', price: x.price, qty: x.qty || 1, note: 'Theo thỏa thuận chốt thuê' }))) : ocrSvc ? St.where('services', s => s.status === 'active' && ocrSvc[s.code]).map(s => ({ serviceId: s.id, name: s.name, unit: s.unit, price: ocrSvc[s.code] || s.price, qty: s.code === 'GUIXE' ? ocrVehicles || 1 : 1, note: 'Từ trích xuất' + (ocrSvc[s.code] && ocrSvc[s.code] !== s.price ? ' – đơn giá theo HĐ' : '') })) : (room0 ? (room0.defaultServiceIds || []).map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: Q.servicePrice(s.id, room0.buildingId, d.start || F.today()), qty: 1, note: s.code === 'INTERNET' ? 'FPT' : s.code === 'GUIXE' ? 'Tầng hầm B1' : '' }; }) : []);
    let members = draft ? Q.contractMembers(draft.id).map(m => Object.assign({}, m)) : (d.tenantId ? [{ name: Q.tenant(d.tenantId).name, dob: Q.tenant(d.tenantId).dob, idNumber: Q.tenant(d.tenantId).idNumber, relation: 'Người thuê (chính)', phone: Q.tenant(d.tenantId).phone, note: '' }] : []);
    let vehicles = draft && draft.vehicles ? draft.vehicles.map(v => Object.assign({}, v)) : ocrVehicles ? Array.from({ length: ocrVehicles }, () => ({ type: 'Xe máy', plate: '' })) : [];
    const svcOpts = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const rooms = St.where('rooms', r => (['ready', 'held'].includes(r.status) || (draft && r.id === draft.roomId)));
    const svcRows = () => services.map((s, i) => `<tr><td>${i + 1}</td><td>${U.select({ name: 'sv_id_' + i, value: s.serviceId || '', cls: 'sm', all: 'Dịch vụ khác', options: svcOpts.map(x => [x.id, x.name]), attrs: { 'data-on': 'svc' } })}</td><td>${U.input({ name: 'sv_unit_' + i, value: s.unit, cls: 'sm', attrs: { style: 'width:80px' } })}</td><td><input class="inp sm tr" data-money name="sv_price_${i}" value="${F.vnd(s.price)}" style="width:110px"></td><td><input class="inp sm tr" type="number" min="0" name="sv_qty_${i}" value="${s.qty}" style="width:80px"></td><td class="num bold" data-amt="${i}">${F.vnd(s.price * s.qty)}</td><td>${U.input({ name: 'sv_note_' + i, value: s.note || '', cls: 'sm', placeholder: '-' })}</td><td>${U.iconBtn('trash', 'rm-svc', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    const memRows = () => members.map((m, i) => `<tr><td>${i + 1}</td><td>${U.input({ name: 'mb_name_' + i, value: m.name, cls: 'sm', placeholder: 'Họ và tên' })}</td><td>${U.date({ name: 'mb_dob_' + i, value: m.dob || '', cls: 'sm' })}</td><td>${U.input({ name: 'mb_id_' + i, value: m.idNumber || '', cls: 'sm', placeholder: '12 số' })}</td><td>${U.select({ name: 'mb_rel_' + i, value: m.relation, cls: 'sm', options: ['Người thuê (chính)', 'Vợ/Chồng', 'Con', 'Anh/Chị/Em', 'Bạn cùng phòng', 'Khác'] })}</td><td>${U.input({ name: 'mb_phone_' + i, value: m.phone || '', cls: 'sm' })}</td><td>${U.input({ name: 'mb_note_' + i, value: m.note || '', cls: 'sm', placeholder: '-' })}</td><td>${U.iconBtn('trash', 'rm-mb', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    const vehicleRows = () => vehicles.map((v, i) => `<tr><td>${i + 1}</td><td>${U.select({ name: 'vh_type_' + i, value: v.type || 'Xe máy', cls: 'sm', options: ['Xe máy', 'Ô tô', 'Xe đạp điện', 'Khác'] })}</td><td>${U.input({ name: 'vh_plate_' + i, value: v.plate || '', cls: 'sm', placeholder: 'Ví dụ: 59A1-123.45' })}</td><td>${U.iconBtn('trash', 'rm-vh', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    const p2Banner = deal ? U.note('ok', 'Dữ liệu từ giao dịch chốt thuê ' + esc(deal.code) + ' ' + TH.phase.tag(2), 'Khách, phòng, giá, cọc, dịch vụ đã được điền sẵn từ wizard Chốt thuê. Kích hoạt HĐ → giao dịch chuyển Đang thuê, hoa hồng đủ điều kiện khi cọc thu đủ (BR-13).') + '<div class="mb16"></div>' : ocr ? U.note('ok', 'Dữ liệu từ trích xuất ' + esc(ocr.code) + ' – đã review ' + (ocr.fields || []).filter(f => f.confirmed).length + '/' + (ocr.fields || []).length + ' trường', (ocrTenant ? 'Khách thuê khớp SĐT/tên: <b>' + esc(ocrTenant.name) + '</b>. ' : 'Chưa có khách thuê khớp – bấm "Thêm khách thuê" (tên: ' + esc(of('tenantName')) + ', SĐT: ' + esc(of('phone')) + '). ') + (ocrRoom ? 'Phòng <b>' + esc(ocrRoom.code) + '</b>. ' : 'Không tìm thấy phòng mã ' + esc(of('roomCode')) + ' – chọn lại. ') + 'Nguồn HĐ = <code>ocr</code>.') + '<div class="mb16"></div>' : '';
    root.innerHTML = `${U.pageHead({ title: 'Tạo hợp đồng', sub: 'Tạo mới hợp đồng thuê nhà, căn hộ cho khách hàng. Vui lòng điền đầy đủ thông tin theo các bước.', phase: deal ? 2 : 0 })}${p2Banner}${U.wizard(STEPS, 0)}
    <div class="two-col wide"><form id="cf" class="col" style="gap:16px" autocomplete="off">
      ${draft || deal || ocr ? '' : U.card({ title: 'Chọn cách tạo hợp đồng', icon: 'file-plus', body: `<div class="radio-cards">${U.radioCard({ name: 'mode', value: 'upload', checked: false, title: 'Tải hợp đồng để hỗ trợ điền', text: 'Tải lên file hợp đồng (PDF, DOCX). Hệ thống sẽ trích xuất thông tin để điền tự động.', icon: 'upload', iconCls: 'green' })}${U.radioCard({ name: 'mode', value: 'manual', checked: true, title: 'Nhập tay', text: 'Điền thông tin thủ công vào form.', icon: 'pencil', iconCls: 'blue' })}</div><div id="ocr-note" hidden class="mt12">${U.note('info', 'Trích xuất hợp đồng (OCR)', 'Chuyển sang màn Trích xuất hợp đồng để upload và review theo nhóm entity (spec v1.8 §12.8).')}<div class="mt8">${U.dropzone({ name: 'cfile', hint: 'PDF, DOCX – chỉ đính kèm, không trích xuất' })}</div></div>` })}
      <div class="card"><div class="card-b">
        <div class="fs"><div class="fs-h">${I('user')}Thông tin khách thuê</div><div class="form-grid-4">${U.field({ label: 'Khách thuê', req: true, input: U.select({ name: 'tenantId', value: d.tenantId, placeholder: 'Chọn khách thuê', options: Fm.opt.tenants(), attrs: { 'data-on': 'tenant' } }), cls: 'span2', help: `Chưa có khách? <a class="link" data-act="new-tenant">Thêm khách thuê</a>` })}${U.field({ label: 'Số điện thoại', input: U.input({ name: 'tphone', value: d.tenantId ? Q.tenant(d.tenantId).phone : '', readonly: true }) })}${U.field({ label: 'Email', input: U.input({ name: 'temail', value: d.tenantId ? Q.tenant(d.tenantId).email : '', readonly: true }) })}</div></div>
        <div class="fs"><div class="fs-h">${I('home')}Thông tin phòng</div><div class="form-grid-5">${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: d.buildingId, placeholder: 'Chọn tòa', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'building' } }) })}${U.field({ label: 'Phòng', req: true, input: U.select({ name: 'roomId', value: d.roomId, placeholder: 'Chọn phòng', options: rooms.filter(r => !d.buildingId || r.buildingId === d.buildingId).map(r => [r.id, r.code + (r.status === 'held' ? ' (giữ chỗ)' : '')]), attrs: { 'data-on': 'room' } }), help: 'Chỉ hiện phòng Sẵn sàng / Giữ chỗ' })}${U.field({ label: 'Loại phòng', input: U.input({ name: 'rtype', value: room0 ? room0.type : '', readonly: true }) })}${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'rarea', value: room0 ? room0.area : '', readonly: true }) })}${U.field({ label: 'Tình trạng', input: `<div class="inp" id="rstatus">${room0 ? Q.chipDot('room', room0.status) : '-'}</div>` })}</div></div>
        <div class="grid grid-2"><div class="fs"><div class="fs-h">${I('calendar')}Thời hạn thuê</div><div class="form-grid-3">${U.field({ label: 'Ngày bắt đầu', req: true, input: U.date({ name: 'start', value: d.start }) })}${U.field({ label: 'Ngày kết thúc', req: true, input: U.date({ name: 'end', value: d.end }) })}${U.field({ label: 'Thời hạn', input: U.input({ name: 'term', value: '', readonly: true }) })}</div></div>
        <div class="fs"><div class="fs-h">${I('credit-card')}Chu kỳ thanh toán</div><div class="form-grid">${U.field({ label: 'Chu kỳ thanh toán', req: true, input: U.select({ name: 'cycle', value: 'monthly', options: [['monthly', 'Hàng tháng']], attrs: { title: 'Chu kỳ theo quý thuộc Phase 2' } }) })}${U.field({ label: 'Ngày thanh toán hàng tháng', req: true, input: U.select({ name: 'payDay', value: d.payDay, options: [1, 5, 10, 15, 20, 25].map(x => [x, F.pad(x)]) }) })}</div></div></div>
        <div class="fs"><div class="fs-h">${I('coins')}Giá thuê, cọc và phụ phí</div><div class="form-grid-3">${U.field({ label: 'Giá niêm yết (VND)', req: true, input: U.money({ name: 'listPrice', value: d.listPrice }) })}${U.field({ label: 'Giá thuê thực tế (VND)', req: true, input: U.money({ name: 'price', value: d.price, attrs: { 'data-guide': 'price' } }), help: '<span id="price-help"></span>' })}${U.field({ label: 'Tiền cọc (VND)', req: true, input: U.money({ name: 'deposit', value: d.deposit }), help: '<span id="dep-help"></span>' })}</div><div class="xs muted mt8">Giá niêm yết và giá thực tế là hai giá riêng, cùng hiển thị trên hóa đơn (BR-06).</div></div>
        <div class="fs"><div class="fs-h">${I('sliders')}Dịch vụ đi kèm</div><div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá (VND)</th><th class="num">Số lượng / Mức sử dụng</th><th class="num">Thành tiền (VND)</th><th>Ghi chú</th><th></th></tr></thead><tbody id="svc-body">${svcRows()}</tbody></table></div>${U.btn({ label: 'Thêm dịch vụ', icon: 'plus', act: 'add-svc', cls: 'btn-outline mt8', size: 'btn-sm' })}<div class="xs muted mt8">Điện/Nước tính theo chỉ số hàng tháng, không nhập ở đây. Số xe không giới hạn (BR-05).</div></div>
        <div class="fs"><div class="fs-h">${I('users')}Danh sách thành viên ở</div><div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Họ và tên <span class="red">*</span></th><th>Ngày sinh</th><th>CMND/CCCD</th><th>Quan hệ</th><th>Số điện thoại</th><th>Ghi chú</th><th></th></tr></thead><tbody id="mb-body">${memRows()}</tbody></table></div>${U.btn({ label: 'Thêm thành viên', icon: 'plus', act: 'add-mb', cls: 'btn-outline mt8', size: 'btn-sm' })}</div>
        <div class="fs"><div class="fs-h">${I('car')}Phương tiện đăng ký</div><div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Loại phương tiện</th><th>Biển số</th><th></th></tr></thead><tbody id="vh-body">${vehicleRows()}</tbody></table></div>${U.btn({ label: 'Thêm phương tiện', icon: 'plus', act: 'add-vh', cls: 'btn-outline mt8', size: 'btn-sm' })}<div class="xs muted mt8">Không giới hạn số lượng; biển số được chuẩn hóa chữ in hoa khi lưu.</div></div>
        <div class="fs"><div class="fs-h">${I('file-text')}Điều khoản đặc biệt</div>${U.textarea({ name: 'note', value: d.note, placeholder: 'Ghi chú điều khoản riêng (nếu có)…' })}</div>
      </div></div>
      <div class="wz-foot">${U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', act: 'draft', cls: 'btn-outline' })}${U.btn({ label: 'Lưu hợp đồng →', act: 'next', cls: 'btn-primary', attrs: { 'data-guide': 'contract-save' } })}</div></div></form>
      <aside class="side-stack" id="summary"></aside></div>`;
    const form = root.querySelector('#cf');
    const read = () => { const v = U.formData(form); services = services.map((s, i) => ({ serviceId: v['sv_id_' + i] || null, name: v['sv_id_' + i] ? Q.service(v['sv_id_' + i]).name : (s.name || 'Dịch vụ khác'), unit: v['sv_unit_' + i], price: F.num(v['sv_price_' + i]), qty: Number(v['sv_qty_' + i]) || 0, note: v['sv_note_' + i] })); members = members.map((m, i) => ({ name: v['mb_name_' + i], dob: v['mb_dob_' + i], idNumber: v['mb_id_' + i], relation: v['mb_rel_' + i], phone: v['mb_phone_' + i], note: v['mb_note_' + i] })); vehicles = vehicles.map((x, i) => ({ type: v['vh_type_' + i] || x.type, plate: v['vh_plate_' + i] || '' })); return { id: draft ? draft.id : undefined, tenantId: v.tenantId, roomId: v.roomId, start: v.start, end: v.end, payDay: Number(v.payDay), listPrice: v.listPrice, price: v.price, deposit: v.deposit, note: v.note, services, members, vehicles, dealId: deal ? deal.id : (draft && draft.dealId) || undefined, ocrId: ocr ? ocr.id : (draft && draft.ocrId) || undefined }; };
    const localDraftKey = 'timohouse.draft.contract.new'; let dirty = false, saveTimer = null;
    const clearLocalDraft = () => { try { sessionStorage.removeItem(localDraftKey); } catch (e) { } dirty = false; };
    const saveLocalDraft = () => { if (draft) return; clearTimeout(saveTimer); saveTimer = setTimeout(() => { try { sessionStorage.setItem(localDraftKey, JSON.stringify({ at: Date.now(), values: U.formData(form) })); } catch (e) { } }, 250); };
    const summary = () => { const v = read(); const t = v.tenantId ? Q.tenant(v.tenantId) : null; const r = v.roomId ? Q.room(v.roomId) : null; const months = v.start && v.end && v.end > v.start ? F.monthsDiff(v.start, v.end) : 0; form.querySelector('input[name=term]').value = months ? months + ' tháng' : ''; const svcTotal = F.sum(v.services, s => s.price * s.qty); v.services.forEach((s, i) => { const c = form.querySelector(`[data-amt="${i}"]`); if (c) c.textContent = F.vnd(s.price * s.qty); }); const diff = v.listPrice && v.price ? v.price - v.listPrice : 0; form.querySelector('#price-help').innerHTML = diff ? `<span class="${diff < 0 ? 'green' : 'red'}">${diff < 0 ? '↓' : '↑'} ${Math.abs(Math.round(diff / v.listPrice * 100))}%</span> ${diff < 0 ? 'Thấp hơn' : 'Cao hơn'} ${F.vnd(Math.abs(diff))} đ so với giá niêm yết` : ''; form.querySelector('#dep-help').textContent = v.deposit && v.price ? 'Tương đương ' + (Math.round(v.deposit / v.price * 10) / 10) + ' tháng tiền thuê' : '';
      const checks = [[!!t, 'Đã chọn khách thuê'], [!!r, 'Đã chọn phòng'], [months > 0, 'Đã thiết lập thời hạn thuê'], [v.price > 0 && v.deposit >= 0 && v.deposit !== '', 'Đã thiết lập giá thuê và cọc'], [v.services.length > 0, 'Đã có dịch vụ đi kèm (' + v.services.length + ' dịch vụ)'], [v.members.filter(m => m.name).length > 0, 'Đã có ' + v.members.filter(m => m.name).length + ' thành viên ở']];
      root.querySelector('#summary').innerHTML = U.card({ title: 'Tóm tắt hợp đồng', icon: 'clipboard-check', body: `<div class="fs" style="margin-top:0"><div class="fs-h" style="font-size:13.5px">${I('user')}Thông tin khách thuê<a class="link small ml-auto" data-act="focus" data-t="tenantId">${I('pencil')} Chỉnh sửa</a></div>${t ? `<div class="row gap12">${U.avatar(t.name)}<div><b style="color:var(--text)">${esc(t.name)}</b><div class="xs muted">${esc(t.code)}<br>${I('phone')} ${esc(t.phone)}<br>${I('mail')} ${esc(t.email || '-')}</div></div></div>` : '<div class="muted small">Chưa chọn khách</div>'}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('home')}Thông tin phòng<a class="link small ml-auto" data-act="focus" data-t="roomId">${I('pencil')} Chỉnh sửa</a></div>${r ? `<div class="row gap12"><div class="photo" style="width:64px;height:48px"></div><div><b style="color:var(--text)">${esc(r.code)}</b><div class="xs muted">${esc(Q.building(r.buildingId).name)}<br>${esc(r.type)} • ${r.area} m²</div></div><span class="ml-auto">${Q.chipDot('room', r.status)}</span></div>` : '<div class="muted small">Chưa chọn phòng</div>'}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('calendar')}Thời hạn thuê</div>${U.kv([['Ngày bắt đầu', v.start ? F.date(v.start) : '-'], ['Ngày kết thúc', v.end ? F.date(v.end) : '-'], ['Thời hạn', months ? months + ' tháng' : '-']], 'one')}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('coins')}Tài chính (ước tính)</div>${U.kv([['Giá thuê (thực tế)', F.vnd(v.price) + ' đ/tháng'], ['Tổng dịch vụ', F.vnd(svcTotal) + ' đ/tháng']], 'one')}<div class="hl-row blue mt8"><span>Tổng tiền hàng tháng</span><span>${F.vnd((v.price || 0) + svcTotal)} đ</span></div><div class="hl-row amber mt8"><span>Tiền cọc</span><span>${F.vnd(v.deposit)} đ</span></div></div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('alert-triangle')}Kiểm tra & cảnh báo</div><div class="check-list">${checks.map(([ok, l]) => `<div class="it">${I(ok ? 'check-circle' : 'x-circle', ok ? 'green' : 'red')}<span>${l}</span></div>`).join('')}<div class="it">${I('alert-circle', 'amber')}<span class="amber">Nhớ kiểm tra điều khoản đặc biệt trong bước cuối</span></div><div class="it">${I('info', 'blue')}<span>Sau khi lưu, hợp đồng sẽ ở trạng thái "Dự thảo"</span></div></div></div>` }); };
    const setRoom = (rid) => { const r = rid ? Q.room(rid) : null; form.querySelector('input[name=rtype]').value = r ? r.type : ''; form.querySelector('input[name=rarea]').value = r ? r.area : ''; form.querySelector('#rstatus').innerHTML = r ? Q.chipDot('room', r.status) : '-'; if (r && !draft) { form.querySelector('input[name=listPrice]').value = F.vnd(r.price); form.querySelector('input[name=price]').value = F.vnd(r.price); form.querySelector('input[name=deposit]').value = F.vnd(r.price * 2); if (!services.length) { services = (r.defaultServiceIds || []).map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: '' }; }); form.querySelector('#svc-body').innerHTML = svcRows(); } } };
    U.onChange(root, {
      tenant: (el) => { const t = Q.tenant(el.value); form.querySelector('input[name=tphone]').value = t.phone || ''; form.querySelector('input[name=temail]').value = t.email || ''; read(); if (!members.length || (members.length === 1 && !members[0].name)) { members = [{ name: t.name, dob: t.dob, idNumber: t.idNumber, relation: 'Người thuê (chính)', phone: t.phone, note: '' }]; form.querySelector('#mb-body').innerHTML = memRows(); } summary(); },
      building: (el) => { const sel = form.querySelector('select[name=roomId]'); sel.innerHTML = '<option value="" disabled selected>Chọn phòng</option>' + rooms.filter(r => r.buildingId === el.value).map(r => `<option value="${r.id}">${r.code}${r.status === 'held' ? ' (giữ chỗ)' : ''}</option>`).join(''); setRoom(''); summary(); },
      room: (el) => { const r = Q.room(el.value); form.querySelector('select[name=buildingId]').value = r.buildingId; setRoom(el.value); const h = Q.roomHold(el.value); if (h && !form.querySelector('select[name=tenantId]').value) { form.querySelector('select[name=tenantId]').value = h.tenantId; form.querySelector('select[name=tenantId]').dispatchEvent(new Event('change', { bubbles: true })); } summary(); },
      svc: (el) => { const i = Number(el.name.split('_')[2]); const s = Q.service(el.value); if (s.id) { const bid = (form.querySelector('select[name=buildingId]') || {}).value || d.buildingId; form.querySelector(`input[name=sv_unit_${i}]`).value = s.unit; form.querySelector(`input[name=sv_price_${i}]`).value = F.vnd(Q.servicePrice(s.id, bid, (form.querySelector('input[name=start]') || {}).value || F.today())); } summary(); },
    });
    form.addEventListener('input', () => { dirty = true; saveLocalDraft(); summary(); }); form.addEventListener('change', (e) => { dirty = true; saveLocalDraft(); if (e.target.name === 'mode') { if (e.target.value === 'upload' && TH.phase.on(2)) { TH.go('#/contracts/ocr'); return; } root.querySelector('#ocr-note').hidden = e.target.value !== 'upload'; form.querySelectorAll('.radio-card').forEach(rc => rc.classList.toggle('on', rc.querySelector('input').checked)); } summary(); });
    U.onInput(form); U.bindDropzones(form);
    // Stepper phản ánh section đang thao tác (focus/scroll) – 1 trang form, 4 bước nhập + Review
    const setStep = (k) => { root.querySelectorAll('.wz-step').forEach((el, i) => { el.classList.toggle('done', i < k); el.classList.toggle('on', i === k); el.querySelector('.n').innerHTML = i < k ? I('check') : String(i + 1); }); root.querySelectorAll('.wz-line').forEach((el, i) => el.classList.toggle('done', i < k)); };
    const SEC_STEP = [0, 0, 0, 1, 1, 1, 1, 1, 1]; root.querySelectorAll('#cf .fs').forEach((el, i) => { el.dataset.step = SEC_STEP[i] != null ? SEC_STEP[i] : 1; });
    root.addEventListener('focusin', (e) => { const fs = e.target.closest('.fs'); if (fs && fs.dataset.step != null) setStep(Number(fs.dataset.step)); });
    const onScroll = () => { const secs = [...root.querySelectorAll('#cf .fs')]; if (!secs.length || !document.contains(root)) return; const cur = secs.filter(el => el.getBoundingClientRect().top <= 160).pop(); setStep(cur ? Number(cur.dataset.step) : 0); };
    if (TH._cfScroll) window.removeEventListener('scroll', TH._cfScroll); TH._cfScroll = onScroll; window.addEventListener('scroll', onScroll, { passive: true });
    U.bind(root, {
      'add-svc': () => { read(); const bid0 = (form.querySelector('select[name=buildingId]') || {}).value || d.buildingId; services.push({ serviceId: svcOpts[0].id, name: svcOpts[0].name, unit: svcOpts[0].unit, price: Q.servicePrice(svcOpts[0].id, bid0, (form.querySelector('input[name=start]') || {}).value || F.today()), qty: 1, note: '' }); form.querySelector('#svc-body').innerHTML = svcRows(); summary(); }, 'rm-svc': (b) => { read(); services.splice(Number(b.dataset.i), 1); form.querySelector('#svc-body').innerHTML = svcRows(); summary(); },
      'add-mb': () => { read(); members.push({ name: '', dob: '', idNumber: '', relation: 'Bạn cùng phòng', phone: '', note: '' }); form.querySelector('#mb-body').innerHTML = memRows(); summary(); }, 'rm-mb': (b) => { read(); members.splice(Number(b.dataset.i), 1); form.querySelector('#mb-body').innerHTML = memRows(); summary(); },
      'add-vh': () => { read(); vehicles.push({ type: 'Xe máy', plate: '' }); form.querySelector('#vh-body').innerHTML = vehicleRows(); summary(); }, 'rm-vh': (b) => { read(); vehicles.splice(Number(b.dataset.i), 1); form.querySelector('#vh-body').innerHTML = vehicleRows(); summary(); },
      focus: (b) => { const el = form.querySelector(`[name="${b.dataset.t}"]`); el && el.focus(); el && el.scrollIntoView({ behavior: 'smooth', block: 'center' }); },
      'new-tenant': () => Fm.tenant(ocr ? { name: of('tenantName'), phone: of('phone'), idNumber: of('idNumber'), idPlace: of('idPlace'), dob: F.fromVN(of('dob')), address: of('address'), note: 'Tạo từ trích xuất hợp đồng ' + ocr.code } : {}, (t) => { if (ocr) X.ocrSetTenant(ocr.id, t.id); const sel = form.querySelector('select[name=tenantId]'); sel.insertAdjacentHTML('afterbegin', `<option value="${t.id}">${esc(t.name)} (${t.code}) – ${esc(t.phone)}</option>`); sel.value = t.id; sel.dispatchEvent(new Event('change', { bubbles: true })); }),
      cancel: async () => { if (await U.confirm({ title: 'Hủy tạo hợp đồng?', text: 'Dữ liệu chưa lưu sẽ mất.', ok: 'Hủy tạo', danger: true })) { clearLocalDraft(); TH.go('#/contracts'); } },
      draft: () => { try { const c = X.saveContractDraft(read()); clearLocalDraft(); U.toast('ok', 'Đã lưu nháp ' + c.code, 'Hợp đồng ở trạng thái Dự thảo'); TH.go('#/contracts/new?id=' + c.id); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      next: () => { try { const v = read(); if (!v.tenantId) throw new Error('Chọn khách thuê'); if (!v.roomId) throw new Error('Chọn phòng'); if (!v.price) throw new Error('Nhập giá thuê thực tế'); if (v.end <= v.start) throw new Error('Ngày kết thúc phải sau ngày bắt đầu'); if (!v.members.some(m => m.name)) throw new Error('Cần ít nhất một thành viên ở'); const c = X.saveContractDraft(v); clearLocalDraft(); TH.go('#/contracts/new?id=' + c.id + '&step=5'); } catch (e) { U.toast('err', 'Chưa thể tiếp tục', e.message); } },
    });
    if (!draft) try { const saved = JSON.parse(sessionStorage.getItem(localDraftKey) || 'null'); if (saved && saved.values) { Object.entries(saved.values).forEach(([name, value]) => { const el = form.elements[name]; if (!el || el.type === 'file' || el.type === 'radio') return; if (el.type === 'checkbox') el.checked = !!value; else el.value = value; }); dirty = true; U.toast('info', 'Đã khôi phục bản nháp cục bộ', 'Dữ liệu chưa lưu từ phiên làm việc trước.'); } } catch (e) { }
    if (TH._contractUnload) window.removeEventListener('beforeunload', TH._contractUnload); TH._contractUnload = (e) => { if (dirty && document.contains(form)) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', TH._contractUnload);
    // tránh re-render form khi store đổi (lưu nháp) — router.refresh chỉ khi đổi route
    summary();
  }, { menu: 'contracts', permission: 'contracts.manage', noAutoRefresh: true });
  function renderReview(root, c) {
    const t = Q.tenant(c.tenantId), r = Q.room(c.roomId), svcs = Q.contractServices(c.id), mbs = Q.contractMembers(c.id);
    const svcTotal = F.sum(svcs, s => s.price * s.qty); const clash = St.one('contracts', x => x.roomId === c.roomId && x.id !== c.id && x.id !== c.renewedFromId && x.status === 'active'); const prevC = c.renewedFromId ? St.get('contracts', c.renewedFromId) : null;
    const lc = Q.landlordContractOf(r.buildingId, c.start) || Q.landlordContractOf(r.buildingId); const lcWarn = lc && c.end > lc.end; const dealDep = TH.phase.on(2) ? St.one('deals', d => (d.contractId === c.id || d.id === c.dealId) && (d.depositPaid || 0) > 0) : null; const depositDone = c.depositPaymentId ? 'phiếu thu ' + ((St.get('payments', c.depositPaymentId) || {}).code || '') : prevC && prevC.depositPaymentId ? 'HĐ cũ ' + prevC.code + ' (cọc chuyển tiếp)' : dealDep ? 'giao dịch ' + dealDep.code + ' (' + F.vnd(dealDep.depositPaid) + ')' : '';
    root.innerHTML = `${U.pageHead({ title: 'Tạo hợp đồng', sub: 'Bước 3/3 – Kiểm tra lại toàn bộ thông tin trước khi kích hoạt. Kích hoạt sẽ chuyển phòng sang Đang thuê.' })}${U.wizard(STEPS, 2)}
    <div class="two-col"><div class="side-stack">${U.card({ title: 'Review hợp đồng ' + esc(c.code), icon: 'clipboard-check', actions: Q.chip('contract', 'draft'), body: `<div class="grid grid-2">${U.kv([['Khách thuê', esc(t.name) + ' (' + esc(t.code) + ')'], ['SĐT', esc(t.phone)], ['Phòng', esc(r.code) + ' · ' + esc(Q.building(r.buildingId).name)], ['Tình trạng phòng', Q.chipDot('room', r.status)], ['Thời hạn', F.date(c.start) + ' – ' + F.date(c.end) + ' (' + F.monthsDiff(c.start, c.end) + ' tháng)'], ['Ngày thanh toán', 'Ngày ' + F.pad(c.payDay) + ' hàng tháng']], 'one')}${U.kv([['Giá niêm yết', F.vnd(c.listPrice) + ' đ'], ['Giá thuê thực tế', '<span class="blue">' + F.vnd(c.price) + ' đ</span>'], ['Tiền cọc', F.vnd(c.deposit) + ' đ'], ['Dịch vụ cố định', F.vnd(svcTotal) + ' đ/tháng'], ['Tổng tiền hàng tháng', '<b>' + F.vnd(c.price + svcTotal) + ' đ</b>'], ['Điều khoản đặc biệt', esc(c.note || 'Không có')]], 'one')}</div>` })}
      ${U.card({ title: 'Dịch vụ đi kèm (' + svcs.length + ')', icon: 'sliders', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá</th><th class="num">SL</th><th class="num">Thành tiền</th><th>Ghi chú</th></tr></thead><tbody>${svcs.map(s => `<tr><td>${esc(s.name)}</td><td>${esc(s.unit)}</td><td class="num">${F.vnd(s.price)}</td><td class="num">${s.qty}</td><td class="num">${F.vnd(s.price * s.qty)}</td><td>${esc(s.note || '-')}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Không có</td></tr>'}</tbody></table>` })}
      ${U.card({ title: 'Thành viên ở (' + mbs.length + ')', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Họ tên</th><th>Ngày sinh</th><th>CCCD</th><th>Quan hệ</th><th>SĐT</th></tr></thead><tbody>${mbs.map(m => `<tr><td>${esc(m.name)}</td><td>${m.dob ? F.date(m.dob) : '-'}</td><td>${esc(m.idNumber || '-')}</td><td>${esc(m.relation)}</td><td>${esc(m.phone || '-')}</td></tr>`).join('')}</tbody></table>` })}
      <div class="wz-foot">${U.btn({ label: '← Quay lại sửa', act: 'back', cls: 'btn-ghost' })}<div class="row">${U.btn({ label: 'Giữ ở Dự thảo', act: 'keep', cls: 'btn-outline' })}${U.btn({ label: 'Xác nhận & kích hoạt hợp đồng', icon: 'check-circle', act: 'activate', cls: 'btn-primary', disabled: !!clash || !lc, attrs: { 'data-guide': 'contract-activate' } })}</div></div></div>
      <aside class="side-stack">${U.card({ title: 'Kiểm tra trước kích hoạt', icon: 'shield-check', attrs: 'data-collapse-ready="1"', body: `<div class="check-list">${[[prevC ? r.status === 'occupied' : ['ready', 'held'].includes(r.status), prevC ? 'Gia hạn từ ' + prevC.code + ' – phòng giữ nguyên Đang thuê, HĐ cũ kết thúc ' + F.date(F.addDays(c.start, -1)) : 'Phòng đang ' + Q.label('room', r.status) + (['ready', 'held'].includes(r.status) ? ' – hợp lệ' : ' – không thể kích hoạt')], [!clash, clash ? 'Trùng HĐ hiệu lực ' + clash.code : 'Không trùng hợp đồng hiệu lực (FR-CUS-02)'], [!!lc, lc ? 'HĐ đầu vào ' + esc(lc.code) + ' hiệu lực đến ' + F.date(lc.end) : esc(Q.building(r.buildingId).name) + ' chưa có HĐ đầu vào hiệu lực – <a class="link" href="#/buildings/' + r.buildingId + '?tab=landlord">bổ sung HĐ với chủ nhà</a>'], ...(lcWarn ? [['warn', 'HĐ khách kết thúc ' + F.date(c.end) + ' sau HĐ chủ nhà (' + F.date(lc.end) + ') – cần gia hạn HĐ đầu vào']] : []), [c.end > c.start, 'Ngày kết thúc sau ngày bắt đầu'], [c.price > 0, 'Đã có giá thuê thực tế'], [mbs.length > 0, 'Có ' + mbs.length + ' thành viên ở'], [true, 'Hóa đơn sẽ snapshot giá/dịch vụ theo kỳ (BR-21)']].map(([ok, l]) => `<div class="it">${ok === 'warn' ? I('alert-circle', 'amber') : I(ok ? 'check-circle' : 'x-circle', ok ? 'green' : 'red')}<span>${l}</span></div>`).join('')}</div>` })}${U.card({ title: 'Chứng từ khi kích hoạt', icon: 'receipt', attrs: 'data-collapse-ready="1"', body: `<div class="col gap8" id="act-opts">${U.check({ name: 'depositNow', label: 'Ghi nhận thu tiền cọc <b>' + F.vnd(c.deposit) + '</b> ngay', checked: !depositDone && c.deposit > 0 && TH.auth.can('payments.record'), attrs: (!TH.auth.can('payments.record') || depositDone || !(c.deposit > 0)) ? { disabled: true } : {} })}<div class="grid grid-2">${U.field({ label: 'Phương thức', input: U.select({ name: 'depositMethod', value: 'Tiền mặt', options: St.where('payMethods', m => m.status === 'active').map(m => m.name) }) })}${U.field({ label: 'Ngày thu', input: U.date({ name: 'depositDate', value: F.today() }) })}</div>${depositDone ? '<div class="small muted">Cọc đã thu qua ' + esc(depositDone) + '.</div>' : ''}${U.check({ name: 'firstInvoice', label: 'Tạo hóa đơn nháp kỳ <b>' + F.periodLabel(F.period(c.start)) + '</b> (tiền phòng tính theo ngày + dịch vụ cố định)', checked: true })}<div class="small muted">Điện nước nhập ở Tạo hóa đơn theo kỳ; hóa đơn nháp cần Admin/Kế toán phát hành.</div></div>` })}${U.note('info', 'Sau khi kích hoạt', 'Hợp đồng → Hiệu lực, phòng → Đang thuê. Các chứng từ chọn ở trên được tạo tự động và liên kết với hợp đồng.')}</aside></div>`;
    U.bind(root, { back: () => TH.go('#/contracts/new?id=' + c.id), keep: () => { U.toast('ok', 'Hợp đồng ' + c.code + ' đang ở Dự thảo'); TH.go('#/contracts/' + c.id); }, activate: async () => { if (await U.confirm({ title: 'Kích hoạt hợp đồng ' + c.code + '?', text: prevC ? 'Hợp đồng cũ ' + prevC.code + ' kết thúc ngày ' + F.date(F.addDays(c.start, -1)) + '; phòng ' + r.code + ' giữ nguyên Đang thuê.' : 'Phòng ' + r.code + ' chuyển sang Đang thuê.', ok: 'Kích hoạt' })) { try { const o = U.formData(root.querySelector('#act-opts')); X.activateContract(c.id, 'act:' + c.id, o); const ex = X.lastActivation || {}; const sub = ['Phòng ' + r.code + ' → Đang thuê'].concat(ex.payment ? ['Thu cọc ' + ex.payment.code] : [], ex.invoice ? ['Hóa đơn nháp ' + ex.invoice.code] : [], ex.notes || []).join(' · '); U.toast(ex.notes && ex.notes.length ? 'warn' : 'ok', 'Đã kích hoạt hợp đồng ' + c.code, sub, 6000); TH.go('#/contracts/' + c.id); } catch (e) { U.toast('err', 'Không kích hoạt được', e.message); } } } });
  }

  /* ---------- Chi tiết hợp đồng ---------- */
  TH.router.register('/contracts/:id', (root, p, q) => {
    const c = St.get('contracts', p.id); if (!c) { root.innerHTML = U.empty({ title: 'Không tìm thấy hợp đồng' }); return; }
    const t = Q.tenant(c.tenantId), r = Q.room(c.roomId), b = Q.building(c.buildingId), s = Q.contractStatus(c), svcs = Q.contractServices(c.id), mbs = Q.contractMembers(c.id), tab = q.tab || 'overview'; const cts = Q.contractTenants(c.id), ledger = Q.depositLedger(c.id), dbal = Q.depositBalance(c.id), hAssets = Q.contractHandoverAssets(c.id), pterms = Q.contractPaymentTerms(c.id), rclause = Q.contractRenewal(c.id), ocrJob = c.ocrJobId ? Q.ocrJob(c.ocrJobId) : null;
    const invs = St.where('invoices', i => i.contractId === c.id && i.docStatus !== 'cancelled').sort((a, z) => F.cmp(z.period, a.period)); const debt = F.sum(invs.filter(i => i.docStatus !== 'draft'), i => Q.invRemaining(i)); const rf = St.one('refunds', x => x.contractId === c.id);
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: c.code }]);
    const acts = []; if (c.status === 'draft') acts.push(U.btn({ label: 'Sửa nháp', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Kích hoạt', icon: 'check-circle', cls: 'btn-primary', act: 'activate' }));
    if (c.status === 'active') acts.push(U.btn({ label: 'Tạo hóa đơn', icon: 'receipt', cls: 'btn-primary', act: 'inv' }), U.btn({ label: 'Gia hạn', icon: 'refresh', cls: 'btn-outline', act: 'renew' }), U.btn({ label: 'Kết thúc hợp đồng', icon: 'x-circle', cls: 'btn-ghost', act: 'terminate', attrs: { 'data-guide': 'contract-terminate', style: 'color:var(--red)' } }));
    if (c.status === 'ended' && !rf && !c.renewedToId) acts.push(U.btn({ label: 'Lập phương án hoàn cọc', icon: 'hand-coins', cls: 'btn-primary', act: 'refund' }));
    if (rf) acts.push(U.btn({ label: 'Hồ sơ hoàn cọc ' + rf.code, icon: 'hand-coins', cls: 'btn-outline', act: 'go-refund' }));
    acts.push(U.iconBtn('more', 'more', 'Thêm thao tác (Tải PDF…)', {}, 'bordered'));
    root.innerHTML = `${U.pageHead({ back: '#/contracts', title: esc(c.code), chips: ' ' + Q.chip('contract', s, 'lg'), sub: `${esc(t.name)} • ${esc(r.code)} - ${esc(b.name)} • ${F.date(c.start)} – ${F.date(c.actualEnd || c.end)}${c.renewedFromId ? ' • Gia hạn từ ' + U.link('#/contracts/' + c.renewedFromId, Q.contract(c.renewedFromId).code) : ''}${c.renewedToId ? ' • Đã gia hạn → ' + U.link('#/contracts/' + c.renewedToId, Q.contract(c.renewedToId).code) : ''}`, acts })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Giá thuê thực tế', value: F.vnd(c.price), cap: 'Niêm yết ' + F.vnd(c.listPrice) + ' đ', icon: 'dollar', tone: 'amber' })}${U.kpi({ label: 'Tiền cọc', value: F.vnd(c.deposit), cap: rf ? 'Hoàn cọc: ' + Q.label('refund', rf.status) : ledger.length ? (dbal.unpaid > 0 ? 'Còn phải thu ' + F.vnd(dbal.unpaid) : 'Đang giữ ' + F.vnd(dbal.holding)) + ' · ledger ' + ledger.length + ' bút toán' : (c.status === 'active' ? (c.depositPaymentId ? 'Đã thu ' + F.date(c.depositPaidAt) + ' · đang giữ' : 'Đang giữ · chưa ghi nhận thu') : '-'), icon: 'shield', tone: 'blue' })}${U.kpi({ label: 'Công nợ', value: F.vnd(debt), cap: invs.length + ' hóa đơn', icon: 'alert-circle', tone: 'red', valueCls: debt ? 'red' : '' })}${U.kpi({ label: c.status === 'active' ? 'Còn lại' : 'Trạng thái', value: c.status === 'active' ? F.daysUntil(c.end) + ' ngày' : Q.label('contract', s), cap: c.status === 'active' ? 'Kết thúc ' + F.date(c.end) + (s === 'expiring' ? ' – sắp hết hạn (≤35 ngày)' : '') : (c.actualEnd ? 'Kết thúc thực tế ' + F.date(c.actualEnd) : ''), icon: 'clock', tone: s === 'expiring' ? 'amber' : 'green' })}</div>
    ${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'members', label: 'Người thuê', count: cts.filter(x => !x.to).length }, { key: 'services', label: 'Dịch vụ & xe' }, { key: 'deposit', label: 'Cọc', count: ledger.length }, { key: 'terms', label: 'Điều khoản & bàn giao' }, { key: 'invoices', label: 'Hóa đơn', count: invs.length }, { key: 'docs', label: 'Tài liệu' }, { key: 'log', label: 'Lịch sử' }], tab)}<div id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin hợp đồng', icon: 'file-text', body: U.kv([['Mã HĐ', esc(c.code) + (c.contractNo ? ' <span class="muted small">· số HĐ giấy ' + esc(c.contractNo) + '</span>' : '')], ['Nguồn', c.source === 'ocr' && ocrJob ? U.chip('OCR ' + ocrJob.code, 'purple') + ' ' + U.link('#/contracts/ocr?id=' + ocrJob.id, 'Xem job') : (c.source === 'ocr' ? U.chip('OCR', 'purple') : 'Nhập tay')], ['Trạng thái', Q.chip('contract', s)], ['Kỳ hợp đồng', Q.contractTermLabel(c)], ['Ngày ký', F.date(c.signedDate)], ['Ngày bắt đầu', F.date(c.start)], ['Ngày kết thúc', F.date(c.end)], ['Kết thúc thực tế', c.actualEnd ? F.date(c.actualEnd) : '-'], ['Lý do kết thúc', esc(c.endReason || '-')], ['Chu kỳ thanh toán', 'Hàng tháng, ngày ' + F.pad(c.payDay)], ['Người phụ trách', esc(Q.userName(c.managerId))], ['Ghi chú / điều khoản', esc(c.note || '-') + ' <a class="link small" data-act="edit-note">' + I('pencil') + ' Sửa</a>' + (c.noteAt ? '<div class="xs muted">Cập nhật ' + F.datetime(c.noteAt) + (c.noteBy ? ' · ' + esc(c.noteBy) : '') + '</div>' : '')]], 'one') })}${U.card({ title: 'Khách thuê & phòng', icon: 'user', body: `<div class="row gap12 mb12">${U.avatar(t.name, 'lg')}<div><b style="font-size:15px;color:var(--text)">${U.link('#/tenants/' + t.id, esc(t.name))}</b><div class="small muted">${esc(t.code)} · ${I('phone')} ${esc(t.phone)}</div></div></div>${U.kv([['Phòng', U.link('#/rooms/' + r.id, esc(r.code))], ['Mã tòa · phòng', esc(F.roomRef(b, r))], ['Tòa nhà', U.link('#/buildings/' + b.id, esc(b.name))], ['Loại / diện tích', esc(r.type) + ' · ' + r.area + ' m²'], ['Trạng thái phòng', Q.chipDot('room', r.status)], ['Tổng tiền hàng tháng (ước)', F.vnd(Q.contractMonthly(c)) + ' đ']], 'one')}` })}</div>`;
    if (tab === 'services') body.innerHTML = U.card({ title: 'Dịch vụ áp dụng & phương tiện', icon: 'sliders', sub: 'Snapshot giá theo hợp đồng (BR-21); số xe không giới hạn (BR-05)', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá</th><th class="num">Số lượng</th><th class="num">Thành tiền/tháng</th><th>Ghi chú</th></tr></thead><tbody>${svcs.map((x, i) => `<tr><td>${i + 1}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td class="num">${F.vnd(x.price)}</td><td class="num">${x.qty}</td><td class="num">${F.vnd(x.price * x.qty)}</td><td>${esc(x.note || '-')}</td></tr>`).join('')}<tr><td colspan="5"><b>Điện, Nước</b></td><td colspan="2" class="muted">Theo chỉ số hàng tháng – nhập tại Tạo hóa đơn theo kỳ</td></tr></tbody></table><div class="fs"><div class="fs-h">${I('car')}Phương tiện (${(c.vehicles || []).length})</div>${(c.vehicles || []).length ? `<table class="tbl compact"><thead><tr><th>#</th><th>Loại</th><th>Biển số</th></tr></thead><tbody>${c.vehicles.map((v, i) => `<tr><td>${i + 1}</td><td>${esc(v.type)}</td><td><b>${esc(v.plate || '-')}</b></td></tr>`).join('')}</tbody></table>` : '<div class="muted small">Chưa đăng ký phương tiện.</div>'}</div>` });
    if (tab === 'members') body.innerHTML = U.card({ title: 'Người thuê theo hợp đồng (§4.8)', icon: 'users', sub: 'Khách đứng tên + người ở cùng – mỗi người là một hồ sơ khách riêng liên kết hợp đồng (CONTRACT_TENANT)', actions: c.status !== 'ended' ? U.btn({ label: 'Thêm người ở cùng', icon: 'user-plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-ct' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Vai trò</th><th>Họ tên</th><th>Hồ sơ khách</th><th>SĐT</th><th>CCCD</th><th>Ngày sinh</th><th>Quan hệ</th><th>Từ – đến</th><th></th></tr></thead><tbody>${cts.map((m, i) => { const tt = m.tenantId ? Q.tenant(m.tenantId) : null; return `<tr class="${m.to ? 'muted' : ''}"><td>${i + 1}</td><td>${Q.chip('contractTenantRole', m.role)}</td><td><b>${esc(tt ? tt.name : m.name)}</b></td><td>${tt ? U.link('#/tenants/' + tt.id, esc(tt.code)) : '<span class="chip amber">Chưa liên kết</span> ' + U.btn({ label: 'Liên kết', size: 'btn-sm', cls: 'btn-ghost', act: 'link-ct', attrs: { 'data-id': m.id } })}</td><td>${esc(tt ? tt.phone : (m.phone || '-'))}</td><td>${esc(tt ? (tt.idNumber || '-') : (m.idNumber || '-'))}</td><td>${(tt ? tt.dob : m.dob) ? F.date(tt ? tt.dob : m.dob) : '-'}</td><td>${esc(m.relation || (m.role === 'primary' ? 'Người thuê (chính)' : '-'))}</td><td class="xs">${F.date(m.from || c.start)} – ${m.to ? F.date(m.to) : 'nay'}</td><td class="tr">${m.role === 'cohabitant' && !m.to ? U.iconBtn('log-out', 'rm-ct', 'Ghi nhận rời đi', { 'data-id': m.id }) : ''}</td></tr>`; }).join('') || '<tr><td colspan="10" class="muted tc">Chưa có</td></tr>'}</tbody></table>${mbs.length > cts.length ? '<div class="xs muted" style="padding:8px 12px">Thành viên nhập tay cũ: ' + mbs.map(m => esc(m.name)).join(', ') + '</div>' : ''}` });
    if (tab === 'deposit') body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ mini: true, label: 'Phải thu', value: F.vnd(dbal.receivable), icon: 'shield', tone: 'amber' })}${U.kpi({ mini: true, label: 'Đã thu / chuyển tiếp', value: F.vnd(dbal.received), icon: 'check-circle', tone: 'green' })}${U.kpi({ mini: true, label: 'Khấu trừ / bù trừ / hoàn', value: F.vnd(dbal.deducted + dbal.offset + dbal.refunded + dbal.forfeited + dbal.transferredOut), icon: 'minus-circle', tone: 'red' })}${U.kpi({ mini: true, label: 'Đang giữ', value: F.vnd(dbal.holding), cap: dbal.unpaid ? 'còn phải thu ' + F.vnd(dbal.unpaid) : '', icon: 'wallet', tone: 'blue' })}</div>` + U.card({ title: 'Deposit Ledger (§10.11, §4.18)', icon: 'book', sub: 'RECEIVABLE → RECEIVED → (TRANSFERRED khi gia hạn) → DEDUCTED / OFFSET / REFUNDED / FORFEITED khi kết thúc – nguồn cho NEW_DEPOSIT, FORFEITED_DEPOSIT, REFUND_AMOUNT', actions: dbal.unpaid > 0 && c.status !== 'ended' ? U.btn({ label: 'Ghi nhận thu cọc', icon: 'hand-coins', size: 'btn-sm', cls: 'btn-primary', act: 'dep-recv' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Ngày</th><th>Loại</th><th class="num">Số tiền</th><th>Tham chiếu</th><th>Ghi chú</th><th>Người ghi</th></tr></thead><tbody>${ledger.map(x => `<tr><td>${F.date(x.date)}</td><td>${Q.chip('depositLedger', x.type)}</td><td class="num ${x.amount < 0 ? 'red' : ''}">${x.amount < 0 ? '−' : ''}${F.vnd(Math.abs(x.amount))}</td><td class="xs">${x.refType === 'refund' && x.refId ? U.link('#/refunds/' + x.refId, esc((St.rawGet('refunds', x.refId) || {}).code || 'Hồ sơ hoàn cọc')) : x.refType === 'payment' && x.refId ? esc((St.rawGet('payments', x.refId) || {}).code || 'Phiếu thu') : x.sourceOcr ? U.link('#/contracts/ocr?id=' + x.sourceOcr.jobId, 'OCR ' + esc(x.sourceOcr.jobCode || '')) : esc(x.refType || '-')}</td><td class="xs">${esc(x.note || '')}</td><td class="xs">${esc(x.createdBy ? Q.userName(x.createdBy) : (x.source === 'seed' ? 'Chuyển đổi' : ''))}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Chưa có bút toán cọc</td></tr>'}</tbody></table>` });
    if (tab === 'terms') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Điều khoản thanh toán (§12.8.13)', icon: 'credit-card', sub: 'Cấu hình/tham chiếu cho billing & nhắc nợ – không tự tạo Payment', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-ghost', act: 'edit-terms' }), body: pterms ? U.kv([['Ngày gửi thông báo', pterms.notifyDay ? 'Ngày ' + pterms.notifyDay : '-'], ['Khoảng ngày thanh toán', (pterms.payFrom || '-') + ' → ' + (pterms.payTo || '-') + ' của kỳ trước'], ['Hình thức', esc(pterms.method || '-')], ['Ngân hàng / chủ TK / số TK', esc([pterms.bankName, pterms.bankAccountName, pterms.bankAccountNo].filter(Boolean).join(' · ') || '-')], ['Nội dung CK', esc(pterms.transferTemplate || '-')], ['Phạt chậm trả', pterms.lateFeePerDay ? F.vnd(pterms.lateFeePerDay) + ' đ/ngày · grace ' + (pterms.graceDays || 0) + ' ngày (chỉ áp dụng khi rule được duyệt)' : '-'], ['Nguồn', pterms.source === 'ocr' ? U.chip('OCR', 'purple') : esc(pterms.source || 'nhập tay')]], 'one') : U.empty({ title: 'Chưa có điều khoản thanh toán' }) })}${U.card({ title: 'Gia hạn / báo trước (§12.8.14)', icon: 'refresh', sub: 'Chỉ tạo cảnh báo Work Queue – không tự gia hạn (AC-12)', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-ghost', act: 'edit-renewal' }), body: rclause ? U.kv([['Loại', esc(rclause.renewalType || '-')], ['Kỳ gia hạn', rclause.renewalMonths ? rclause.renewalMonths + ' tháng' : '-'], ['Báo trước', rclause.noticeDays ? rclause.noticeDays + ' ngày → cảnh báo từ ' + F.date(F.addDays(c.end, -rclause.noticeDays)) : '-'], ['Điều khoản gốc', esc(rclause.rawClause || '-')], ['Nguồn', rclause.source === 'ocr' ? U.chip('OCR', 'purple') : esc(rclause.source || 'nhập tay')]], 'one') : U.empty({ title: 'Chưa có điều khoản gia hạn' }) })}</div>` + U.card({ title: 'Tài sản bàn giao (§12.8.12)', icon: 'package', sub: hAssets.length + ' dòng – đối chiếu khi trả phòng / quyết toán', actions: U.btn({ label: 'Thêm dòng', icon: 'plus', size: 'btn-sm', cls: 'btn-ghost', act: 'add-asset' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Tài sản</th><th>Nhóm</th><th class="num">SL</th><th>Đơn vị</th><th>Tình trạng</th><th>Ghi chú</th><th>Nguồn</th></tr></thead><tbody>${hAssets.map((a, i) => `<tr><td>${i + 1}</td><td><b>${esc(a.name)}</b></td><td class="xs">${a.group === 'furniture' ? 'Nội thất' : a.group === 'device' ? 'Thiết bị' : esc(a.group || '')}</td><td class="num">${esc(a.qty || '1')}</td><td>${esc(a.unit || '')}</td><td>${esc(a.condition || '')}</td><td class="xs">${esc(a.note || '')}</td><td class="xs">${a.sourceOcr ? U.link('#/contracts/ocr?id=' + a.sourceOcr.jobId, 'OCR tr.' + (a.sourcePage || '')) : 'nhập tay'}</td></tr>`).join('') || '<tr><td colspan="8" class="muted tc">Chưa có dòng tài sản bàn giao (HĐ nhập tay dùng tài sản phòng)</td></tr>'}</tbody></table>` });
    if (tab === 'invoices') { body.innerHTML = U.card({ title: 'Hóa đơn của hợp đồng', icon: 'receipt', actions: c.status === 'active' ? U.btn({ label: 'Tạo hóa đơn', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'inv' }) : '', body: null, id: 'ic' }); const w = document.createElement('div'); body.querySelector('#ic').appendChild(w); U.table(w, { rows: invs, unit: 'hóa đơn', cols: [{ key: 'code', label: 'Mã', render: i => U.link('#/invoices/' + i.id, i.code) }, { key: 'period', label: 'Kỳ', render: i => F.periodShort(i.period) }, { key: 'issue', label: 'Phát hành', render: i => F.date(i.issueDate) }, { key: 'due', label: 'Hạn', render: i => F.date(i.dueDate) }, { key: 'total', label: 'Tổng', num: true, render: i => F.vnd(i.total) }, { key: 'paid', label: 'Đã thu', num: true, render: i => F.vnd(Q.invPaid(i)) }, { key: 'rem', label: 'Còn lại', num: true, render: i => `<span class="${Q.invRemaining(i) ? 'red bold' : ''}">${F.vnd(Q.invRemaining(i))}</span>` }, { key: 'doc', label: 'Chứng từ', render: i => Q.chip('invDoc', i.docStatus) }, { key: 'pay', label: 'Thu', render: i => i.docStatus === 'draft' ? '-' : Q.invPayChip(i) }], empty: U.empty({ title: 'Chưa có hóa đơn' }) }); }
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'contract' && d.entityId === c.id); body.innerHTML = U.card({ title: 'Tài liệu hợp đồng', icon: 'folder', actions: U.btn({ label: 'Tải lên HĐ đã ký', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có file hợp đồng', text: 'Tải lên bản hợp đồng đã ký (PDF/JPG) hoặc tạo HĐ từ OCR để file tự gắn vào đây (docType contract, nguồn OCR).' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => (x.entityType === 'contract' && x.entityId === c.id) || (x.entityType === 'invoice' && invs.some(i => i.id === x.entityId)) || (rf && x.entityType === 'refund' && x.entityId === rf.id)); body.innerHTML = U.card({ title: 'Lịch sử', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'edit-note': () => { const m = U.modal({ title: 'Ghi chú / điều khoản hợp đồng', size: 'sm', body: U.textarea({ name: 'note', value: c.note || '', rows: 5, placeholder: 'Điều khoản đặc biệt, thỏa thuận thêm…' }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { X.updateContractNote(c.id, m.data().note); m.close(); U.toast('ok', 'Đã lưu ghi chú hợp đồng'); } }); }, edit: () => TH.go('#/contracts/new?id=' + c.id), activate: () => TH.go('#/contracts/new?id=' + c.id + '&step=5'), inv: () => TH.go('#/invoices/batch?buildingId=' + c.buildingId + '&room=' + c.roomId), renew: () => Fm.renew(c), terminate: () => Fm.terminate(c), refund: () => TH.go('#/refunds/new?contract=' + c.id), 'go-refund': () => TH.go('#/refunds/' + rf.id), pdf: () => U.fakePdf('Hop dong ' + c.code, ['Khách: ' + t.name, 'Phòng: ' + r.code + ' – ' + b.name, 'Thời hạn: ' + F.date(c.start) + ' – ' + F.date(c.end), 'Giá thuê: ' + F.vnd(c.price), 'Cọc: ' + F.vnd(c.deposit)]), upload: () => Fm.upload('contract', c.id), 'rm-doc': (el) => X.removeDocument(el.dataset.id), more: (el) => cMenu(el, c),
      'add-ct': () => { const opts = St.all('tenants').filter(x => x.id !== c.tenantId && !cts.some(m => m.tenantId === x.id && !m.to)).sort((a, z) => F.cmp(a.name, z.name)).map(x => [x.id, x.name + ' · ' + (x.phone || '') + ' (' + x.code + ')']); const m = U.modal({ title: 'Thêm người ở cùng', sub: 'Chọn hồ sơ khách có sẵn hoặc tạo hồ sơ mới (match CCCD → SĐT → tên+ngày sinh)', body: `<div class="form-grid">${U.field({ label: 'Khách có sẵn', input: U.select({ name: 'tenantId', all: '— Tạo hồ sơ mới —', options: opts }), cls: 'span2' })}${U.field({ label: 'Họ tên (mới)', input: U.input({ name: 'name' }) })}${U.field({ label: 'SĐT (mới)', input: U.input({ name: 'phone' }) })}${U.field({ label: 'CCCD', input: U.input({ name: 'idNumber' }) })}${U.field({ label: 'Ngày sinh', input: U.date({ name: 'dob' }) })}${U.field({ label: 'Quan hệ', input: U.select({ name: 'relation', value: 'Bạn cùng phòng', options: ['Vợ/Chồng', 'Bạn cùng phòng', 'Con', 'Anh/Chị/Em', 'Khác'] }) })}${U.field({ label: 'Từ ngày', input: U.date({ name: 'from', value: F.today() }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Thêm', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { try { const d = m.data(); X.addContractTenant({ contractId: c.id, tenantId: d.tenantId || null, newTenant: d.tenantId ? null : { name: d.name, phone: d.phone, idNumber: d.idNumber, dob: d.dob }, relation: d.relation, from: d.from }); m.close(); U.toast('ok', 'Đã thêm người ở cùng'); TH.router.refresh(); } catch (e) { U.toast('err', 'Không thêm được', e.message); } } }); },
      'rm-ct': async (el) => { if (!(await U.confirm({ title: 'Ghi nhận người ở cùng rời đi?', text: 'Hồ sơ khách vẫn giữ nguyên; liên kết với hợp đồng kết thúc hôm nay.' }))) return; try { X.removeContractTenant(el.dataset.id); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
      'link-ct': (el) => { const ct = St.rawGet('contractTenants', el.dataset.id); const r = Q.tenantMatch({ name: ct.name, phone: ct.phone, idNumber: ct.idNumber, dob: ct.dob }); const opts = St.all('tenants').sort((a, z) => F.cmp(a.name, z.name)).map(x => [x.id, x.name + ' · ' + (x.phone || '') + ' (' + x.code + ')']); const m = U.modal({ title: 'Liên kết hồ sơ khách', sub: esc(ct.name) + (r.match ? ' – gợi ý ' + esc(r.match.name) + ' (' + esc(r.matchBy) + ')' : ' – không tìm thấy hồ sơ khớp'), size: 'sm', body: U.field({ label: 'Hồ sơ khách', input: U.select({ name: 'tenantId', value: r.match ? r.match.id : '', placeholder: 'Chọn…', options: opts }) }) + '<div class="xs muted mt8">Hoặc tạo hồ sơ mới tại Khách thuê rồi liên kết.</div>', footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Liên kết', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { try { X.linkContractTenant(ct.id, m.data().tenantId); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'dep-recv': () => { const m = U.modal({ title: 'Ghi nhận thu cọc', sub: 'Còn phải thu ' + F.vnd(dbal.unpaid) + ' – ghi RECEIVED vào Deposit Ledger', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount', value: dbal.unpaid }) })}${U.field({ label: 'Ngày thu', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', input: U.select({ name: 'method', value: 'Chuyển khoản', options: ['Chuyển khoản', 'Tiền mặt'] }) })}${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Ghi nhận', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { try { const d = m.data(); X.recordDepositReceived({ contractId: c.id, amount: F.num(d.amount), date: d.date, method: d.method, ref: d.ref }); m.close(); U.toast('ok', 'Đã ghi nhận thu cọc'); TH.router.refresh(); } catch (e) { U.toast('err', 'Không ghi được', e.message); } } }); },
      'edit-terms': () => { const t0 = pterms || {}; const m = U.modal({ title: 'Điều khoản thanh toán', body: `<div class="form-grid">${U.field({ label: 'Ngày gửi thông báo', input: U.input({ name: 'notifyDay', type: 'number', value: t0.notifyDay || 25 }) })}${U.field({ label: 'Thanh toán từ ngày', input: U.input({ name: 'payFrom', type: 'number', value: t0.payFrom || 25 }) })}${U.field({ label: 'Đến ngày', input: U.input({ name: 'payTo', type: 'number', value: t0.payTo || 30 }) })}${U.field({ label: 'Hình thức', input: U.select({ name: 'method', value: t0.method || 'Chuyển khoản', options: ['Chuyển khoản', 'Tiền mặt'] }) })}${U.field({ label: 'Ngân hàng', input: U.input({ name: 'bankName', value: t0.bankName || '' }) })}${U.field({ label: 'Chủ tài khoản', input: U.input({ name: 'bankAccountName', value: t0.bankAccountName || '' }) })}${U.field({ label: 'Số tài khoản', input: U.input({ name: 'bankAccountNo', value: t0.bankAccountNo || '' }) })}${U.field({ label: 'Nội dung CK (template)', input: U.input({ name: 'transferTemplate', value: t0.transferTemplate || '{room} - {building} - {customer_name}' }) })}${U.field({ label: 'Phạt chậm trả (đ/ngày)', input: U.money({ name: 'lateFeePerDay', value: t0.lateFeePerDay || 0 }) })}${U.field({ label: 'Grace (ngày)', input: U.input({ name: 'graceDays', type: 'number', value: t0.graceDays || 0 }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { const d = m.data(); const rec = { notifyDay: Number(d.notifyDay) || 0, payFrom: Number(d.payFrom) || 0, payTo: Number(d.payTo) || 0, method: d.method, bankName: d.bankName, bankAccountName: d.bankAccountName, bankAccountNo: d.bankAccountNo, transferTemplate: d.transferTemplate, lateFeePerDay: F.num(d.lateFeePerDay), graceDays: Number(d.graceDays) || 0 }; if (pterms) St.update('contractPaymentTerms', pterms.id, rec); else St.add('contractPaymentTerms', Object.assign({ contractId: c.id, dueDay: c.payDay, source: 'manual' }, rec)); St.audit('update', 'contract', c.id, 'Cập nhật điều khoản thanh toán ' + c.code, { before: t0, after: rec }); m.close(); TH.router.refresh(); } }); },
      'edit-renewal': () => { const r0 = rclause || {}; const m = U.modal({ title: 'Điều khoản gia hạn / báo trước', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Loại', input: U.select({ name: 'renewalType', value: r0.renewalType || 'AUTO_RENEW_CLAUSE', options: [['AUTO_RENEW_CLAUSE', 'Tự gia hạn (điều khoản)'], ['MANUAL', 'Gia hạn thủ công'], ['NONE', 'Không gia hạn']] }), cls: 'span2' })}${U.field({ label: 'Kỳ gia hạn (tháng)', input: U.input({ name: 'renewalMonths', type: 'number', value: r0.renewalMonths || 12 }) })}${U.field({ label: 'Báo trước (ngày)', input: U.input({ name: 'noticeDays', type: 'number', value: r0.noticeDays || 30 }) })}${U.field({ label: 'Điều khoản gốc', input: U.textarea({ name: 'rawClause', value: r0.rawClause || '', rows: 3 }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { const d = m.data(); const rec = { renewalType: d.renewalType, renewalMonths: Number(d.renewalMonths) || 0, noticeDays: Number(d.noticeDays) || 0, rawClause: d.rawClause }; if (rclause) St.update('contractRenewalClauses', rclause.id, rec); else St.add('contractRenewalClauses', Object.assign({ contractId: c.id, source: 'manual' }, rec)); St.audit('update', 'contract', c.id, 'Cập nhật điều khoản gia hạn ' + c.code, { before: r0, after: rec }); m.close(); TH.router.refresh(); } }); },
      'add-asset': () => { const m = U.modal({ title: 'Thêm tài sản bàn giao', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name' }), cls: 'span2' })}${U.field({ label: 'Nhóm', input: U.select({ name: 'group', value: 'furniture', options: [['furniture', 'Nội thất'], ['device', 'Thiết bị']] }) })}${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', value: '1' }) })}${U.field({ label: 'Đơn vị', input: U.input({ name: 'unit', value: 'cái' }) })}${U.field({ label: 'Tình trạng', input: U.input({ name: 'condition', value: 'Bình thường' }) })}${U.field({ label: 'Ghi chú', input: U.input({ name: 'note' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'x' }) + U.btn({ label: 'Thêm', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { x: () => m.close(), s: () => { const d = m.data(); if (!d.name) return U.toast('warn', 'Nhập tên tài sản'); St.add('contractHandoverAssets', { contractId: c.id, roomId: c.roomId, name: d.name, group: d.group, qty: d.qty, unit: d.unit, condition: d.condition, note: d.note, source: 'manual' }); St.audit('update', 'contract', c.id, 'Thêm tài sản bàn giao ' + d.name); m.close(); TH.router.refresh(); } }); } });
  }, { menu: 'contracts', permission: 'contracts.view', resource: { type: 'contract' } });
})(window.TH);
