(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const cMenu = (btn, c) => { const s = Q.contractStatus(c); const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/contracts/' + c.id) }];
    if (c.status === 'draft') items.push({ label: 'Sửa nháp', icon: 'pencil', onClick: () => TH.go('#/contracts/new?id=' + c.id) }, { label: 'Kích hoạt', icon: 'check-circle', onClick: () => TH.go('#/contracts/new?id=' + c.id + '&step=5') }, { label: 'Hủy', icon: 'x-circle', danger: true, onClick: () => Fm.cancelContract(c) });
    if (c.status === 'active') items.push({ label: 'Gia hạn', icon: 'refresh', onClick: () => Fm.renew(c) }, { label: 'Tạo hóa đơn', icon: 'receipt', onClick: () => TH.go('#/invoices/batch?buildingId=' + c.buildingId + '&room=' + c.roomId) }, { label: 'Kết thúc hợp đồng', icon: 'x-circle', danger: true, onClick: () => Fm.terminate(c) });
    items.push('-', { label: 'Tải PDF', icon: 'download', onClick: () => U.fakePdf('Hop dong ' + c.code, ['Khách: ' + Q.tenant(c.tenantId).name, 'Phòng: ' + Q.room(c.roomId).code, 'Thời hạn: ' + F.date(c.start) + ' - ' + F.date(c.end), 'Giá: ' + F.vnd(c.price), 'Cọc: ' + F.vnd(c.deposit)]) }); U.menu(btn, items); };
  /* ---------- Danh sách ---------- */
  TH.router.register('/contracts', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng' }]);
    const f = { s: q.s || '', buildingId: q.buildingId || '', status: q.status || '', exp: q.exp || '', managerId: q.managerId || '' };
    const all = St.all('contracts'); const withS = all.map(c => ({ c, s: Q.contractStatus(c) }));
    const cnt = (k) => k ? withS.filter(x => x.s === k).length : all.length;
    const rows = withS.filter(x => (!f.s || F.norm(x.c.code + ' ' + Q.tenant(x.c.tenantId).name + ' ' + Q.tenant(x.c.tenantId).phone).includes(F.norm(f.s))) && (!f.buildingId || x.c.buildingId === f.buildingId) && (!f.status || (f.status === 'active' ? ['active', 'expiring'].includes(x.s) : x.s === f.status)) && (!f.exp || (x.s === 'expiring')) && (!f.managerId || x.c.managerId === f.managerId)).sort((a, b) => F.cmp(b.c.createdAt || b.c.start, a.c.createdAt || a.c.start));
    root.innerHTML = `${U.pageHead({ title: 'Hợp đồng', sub: 'Theo dõi danh sách hợp đồng thuê và trạng thái hiệu lực.', acts: [U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' }), U.btn({ label: 'Tạo hợp đồng', icon: 'plus', cls: 'btn-primary', act: 'new', attrs: { 'data-guide': 'contract-new' } })] })}
    ${U.statusTabs([{ key: '', label: 'Tất cả', count: cnt() }, { key: 'draft', label: 'Dự thảo', count: cnt('draft'), color: 'gray' }, { key: 'active', label: 'Hiệu lực', count: cnt('active') + cnt('expiring'), color: 'green' }, { key: 'expiring', label: 'Sắp hết hạn', count: cnt('expiring'), color: 'amber' }, { key: 'ended', label: 'Đã kết thúc', count: cnt('ended'), color: 'gray' }, { key: 'cancelled', label: 'Hủy', count: cnt('cancelled'), color: 'red' }], f.status)}
    ${U.filterbar([U.field({ label: 'Tìm kiếm hợp đồng', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã hợp đồng, tên khách thuê, sđt...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kỳ hết hạn', input: U.select({ name: 'exp', value: f.exp, all: 'Tất cả thời gian', options: [['35', 'Trong 35 ngày tới']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả nhân viên', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng HĐ', value: cnt(), cap: 'Tổng số hợp đồng', icon: 'file-text', tone: 'blue', delta: 12 })}${U.kpi({ label: 'Hiệu lực', value: cnt('active') + cnt('expiring'), cap: 'Đang có hiệu lực (gồm sắp hết hạn)', icon: 'check-circle', tone: 'green', delta: 8 })}${U.kpi({ label: 'Sắp hết hạn', value: cnt('expiring'), cap: 'Hết hạn trong 35 ngày tới (BR-04)', icon: 'clock', tone: 'amber', delta: 10, deltaDir: 'down' })}${U.kpi({ label: 'Dự thảo', value: cnt('draft'), cap: 'Chờ hoàn thiện', icon: 'pencil', tone: 'purple', delta: 33 })}</div>
    ${U.card({ title: 'Danh sách hợp đồng', body: null, id: 'tbl-card', attrs: 'data-guide="contracts-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, selectable: true, unit: 'hợp đồng', rowKey: x => x.c.id, cols: [
      { key: 'code', label: 'Mã HĐ', sortable: true, sortVal: x => x.c.code, render: x => U.link('#/contracts/' + x.c.id, esc(x.c.code), 'bold') }, { key: 't', label: 'Khách thuê', render: x => U.link('#/tenants/' + x.c.tenantId, esc(Q.tenant(x.c.tenantId).name)) },
      { key: 'room', label: 'Phòng / Tòa', render: x => U.cell2(esc(Q.room(x.c.roomId).code), esc(Q.building(x.c.buildingId).name)) }, { key: 'start', label: 'Ngày bắt đầu', sortable: true, sortVal: x => x.c.start, render: x => F.date(x.c.start) }, { key: 'end', label: 'Ngày kết thúc', sortable: true, sortVal: x => x.c.end, render: x => F.date(x.c.actualEnd || x.c.end) },
      { key: 'price', label: 'Giá thuê (VND)', num: true, render: x => F.vnd(x.c.price) }, { key: 'dep', label: 'Tiền cọc (VND)', num: true, render: x => F.vnd(x.c.deposit) }, { key: 'st', label: 'Trạng thái', sortable: true, sortVal: x => x.s, render: x => Q.chip('contract', x.s) },
      { key: 'left', label: 'Còn lại', render: x => { if (x.c.status !== 'active') return '-'; const d = F.daysUntil(x.c.end); return `<span class="${d <= 35 ? 'red bold' : ''}">${d} ngày</span>`; } }, { key: 'mgr', label: 'Người phụ trách', render: x => esc(Q.userName(x.c.managerId)) },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': x.c.id } }), x.c.status === 'active' ? U.actBtn({ icon: 'refresh', label: 'Gia hạn', act: 'renew', attrs: { 'data-id': x.c.id } }) : '', U.moreBtn(x.c.id)]) }] });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { new: () => TH.go('#/contracts/new'), stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { status: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => TH.go('#/contracts/' + b.dataset.id), renew: (b) => Fm.renew(St.get('contracts', b.dataset.id)), more: (b) => cMenu(b, St.get('contracts', b.dataset.id)), export: () => { F.download('hop-dong.csv', F.csv(rows.map(x => [x.c.code, Q.tenant(x.c.tenantId).name, Q.room(x.c.roomId).code, x.c.start, x.c.end, x.c.price, x.c.deposit, Q.label('contract', x.s)]), ['Mã', 'Khách', 'Phòng', 'Bắt đầu', 'Kết thúc', 'Giá', 'Cọc', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất danh sách'); } });
  }, { menu: 'contracts', permission: 'contracts.view' });

  /* ---------- Tạo hợp đồng ---------- */
  const STEPS = [{ title: 'Nguồn dữ liệu', sub: 'Tải file hoặc nhập tay' }, { title: 'Khách & phòng', sub: 'Chọn khách và phòng' }, { title: 'Giá thuê & cọc', sub: 'Thiết lập giá và thanh toán' }, { title: 'Dịch vụ & thành viên ở', sub: 'Dịch vụ, người ở, điều khoản' }, { title: 'Review & lưu', sub: 'Kiểm tra và hoàn tất' }];
  TH.router.register('/contracts/new', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Tạo hợp đồng' }]);
    const draft = q.id ? St.get('contracts', q.id) : null; const step = q.step === '5' && draft && draft.status === 'draft' ? 5 : 1;
    if (step === 5) return renderReview(root, draft);
    const room0 = q.room ? Q.room(q.room) : (draft ? Q.room(draft.roomId) : null);
    const d = { tenantId: q.tenant || (draft ? draft.tenantId : ''), roomId: room0 ? room0.id : '', buildingId: room0 ? room0.buildingId : '', start: draft ? draft.start : '2024-11-01', end: draft ? draft.end : '2025-10-31', payDay: draft ? draft.payDay : 5, listPrice: draft ? draft.listPrice : (room0 ? room0.price : ''), price: draft ? draft.price : (room0 ? room0.price : ''), deposit: draft ? draft.deposit : (room0 ? room0.price * 2 : ''), note: draft ? draft.note : '' };
    let services = draft ? Q.contractServices(draft.id).map(s => Object.assign({}, s)) : (room0 ? (room0.defaultServiceIds || []).map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: s.code === 'INTERNET' ? 'FPT' : s.code === 'GUIXE' ? 'Tầng hầm B1' : '' }; }) : []);
    let members = draft ? Q.contractMembers(draft.id).map(m => Object.assign({}, m)) : (d.tenantId ? [{ name: Q.tenant(d.tenantId).name, dob: Q.tenant(d.tenantId).dob, idNumber: Q.tenant(d.tenantId).idNumber, relation: 'Người thuê (chính)', phone: Q.tenant(d.tenantId).phone, note: '' }] : []);
    const svcOpts = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const rooms = St.where('rooms', r => (['ready', 'held'].includes(r.status) || (draft && r.id === draft.roomId)));
    const svcRows = () => services.map((s, i) => `<tr><td>${i + 1}</td><td>${U.select({ name: 'sv_id_' + i, value: s.serviceId || '', cls: 'sm', all: 'Dịch vụ khác', options: svcOpts.map(x => [x.id, x.name]), attrs: { 'data-on': 'svc' } })}</td><td>${U.input({ name: 'sv_unit_' + i, value: s.unit, cls: 'sm', attrs: { style: 'width:80px' } })}</td><td><input class="inp sm tr" data-money name="sv_price_${i}" value="${F.vnd(s.price)}" style="width:110px"></td><td><input class="inp sm tr" type="number" min="0" name="sv_qty_${i}" value="${s.qty}" style="width:80px"></td><td class="num bold" data-amt="${i}">${F.vnd(s.price * s.qty)}</td><td>${U.input({ name: 'sv_note_' + i, value: s.note || '', cls: 'sm', placeholder: '-' })}</td><td>${U.iconBtn('trash', 'rm-svc', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    const memRows = () => members.map((m, i) => `<tr><td>${i + 1}</td><td>${U.input({ name: 'mb_name_' + i, value: m.name, cls: 'sm', placeholder: 'Họ và tên' })}</td><td>${U.date({ name: 'mb_dob_' + i, value: m.dob || '', cls: 'sm' })}</td><td>${U.input({ name: 'mb_id_' + i, value: m.idNumber || '', cls: 'sm', placeholder: '12 số' })}</td><td>${U.select({ name: 'mb_rel_' + i, value: m.relation, cls: 'sm', options: ['Người thuê (chính)', 'Vợ/Chồng', 'Con', 'Anh/Chị/Em', 'Bạn cùng phòng', 'Khác'] })}</td><td>${U.input({ name: 'mb_phone_' + i, value: m.phone || '', cls: 'sm' })}</td><td>${U.input({ name: 'mb_note_' + i, value: m.note || '', cls: 'sm', placeholder: '-' })}</td><td>${U.iconBtn('trash', 'rm-mb', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    root.innerHTML = `${U.pageHead({ title: 'Tạo hợp đồng', sub: 'Tạo mới hợp đồng thuê nhà, căn hộ cho khách hàng. Vui lòng điền đầy đủ thông tin theo các bước.' })}${U.wizard(STEPS, 1)}
    <div class="two-col wide"><form id="cf" class="col" style="gap:16px" autocomplete="off">
      ${U.card({ title: 'Chọn cách tạo hợp đồng', icon: 'file-plus', body: `<div class="radio-cards">${U.radioCard({ name: 'mode', value: 'upload', checked: false, title: 'Tải hợp đồng để hỗ trợ điền', text: 'Tải lên file hợp đồng (PDF, DOCX). Hệ thống sẽ trích xuất thông tin để điền tự động.', icon: 'upload', iconCls: 'green' })}${U.radioCard({ name: 'mode', value: 'manual', checked: true, title: 'Nhập tay', text: 'Điền thông tin thủ công vào form.', icon: 'pencil', iconCls: 'blue' })}</div><div id="ocr-note" hidden class="mt12">${U.note('warn', 'Trích xuất hợp đồng (OCR) thuộc Phase 2', 'BR-03/FR-CUS-02: upload + trích xuất + review sẽ triển khai ở Phase 2. Bản demo Phase 1 cho phép đính kèm file hợp đồng đã ký và nhập tay. <a class="link" href="#/coming-soon/ocr">Xem scope</a>')}<div class="mt8">${U.dropzone({ name: 'cfile', hint: 'PDF, DOCX – chỉ đính kèm, không trích xuất' })}</div></div>` })}
      <div class="card"><div class="card-b">
        <div class="fs"><div class="fs-h">${I('user')}Thông tin khách thuê</div><div class="form-grid-4">${U.field({ label: 'Khách hàng', req: true, input: U.select({ name: 'tenantId', value: d.tenantId, placeholder: 'Chọn khách thuê', options: Fm.opt.tenants(), attrs: { 'data-on': 'tenant' } }), cls: 'span2', help: `Chưa có khách? <a class="link" data-act="new-tenant">Thêm khách thuê</a>` })}${U.field({ label: 'Số điện thoại', input: U.input({ name: 'tphone', value: d.tenantId ? Q.tenant(d.tenantId).phone : '', readonly: true }) })}${U.field({ label: 'Email', input: U.input({ name: 'temail', value: d.tenantId ? Q.tenant(d.tenantId).email : '', readonly: true }) })}</div></div>
        <div class="fs"><div class="fs-h">${I('home')}Thông tin phòng</div><div class="form-grid-5">${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: d.buildingId, placeholder: 'Chọn tòa', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'building' } }) })}${U.field({ label: 'Phòng', req: true, input: U.select({ name: 'roomId', value: d.roomId, placeholder: 'Chọn phòng', options: rooms.filter(r => !d.buildingId || r.buildingId === d.buildingId).map(r => [r.id, r.code + (r.status === 'held' ? ' (giữ chỗ)' : '')]), attrs: { 'data-on': 'room' } }), help: 'Chỉ hiện phòng Sẵn sàng / Giữ chỗ' })}${U.field({ label: 'Loại phòng', input: U.input({ name: 'rtype', value: room0 ? room0.type : '', readonly: true }) })}${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'rarea', value: room0 ? room0.area : '', readonly: true }) })}${U.field({ label: 'Tình trạng', input: `<div class="inp" id="rstatus">${room0 ? Q.chipDot('room', room0.status) : '-'}</div>` })}</div></div>
        <div class="grid grid-2"><div class="fs"><div class="fs-h">${I('calendar')}Thời hạn thuê</div><div class="form-grid-3">${U.field({ label: 'Ngày bắt đầu', req: true, input: U.date({ name: 'start', value: d.start }) })}${U.field({ label: 'Ngày kết thúc', req: true, input: U.date({ name: 'end', value: d.end }) })}${U.field({ label: 'Thời hạn', input: U.input({ name: 'term', value: '', readonly: true }) })}</div></div>
        <div class="fs"><div class="fs-h">${I('credit-card')}Chu kỳ thanh toán</div><div class="form-grid">${U.field({ label: 'Chu kỳ thanh toán', req: true, input: U.select({ name: 'cycle', value: 'monthly', options: [['monthly', 'Hàng tháng']], attrs: { title: 'Chu kỳ theo quý thuộc Phase 2' } }) })}${U.field({ label: 'Ngày thanh toán hàng tháng', req: true, input: U.select({ name: 'payDay', value: d.payDay, options: [1, 5, 10, 15, 20, 25].map(x => [x, F.pad(x)]) }) })}</div></div></div>
        <div class="fs"><div class="fs-h">${I('coins')}Giá thuê, cọc và phụ phí</div><div class="form-grid-3">${U.field({ label: 'Giá niêm yết (VND)', req: true, input: U.money({ name: 'listPrice', value: d.listPrice }) })}${U.field({ label: 'Giá thuê thực tế (VND)', req: true, input: U.money({ name: 'price', value: d.price, attrs: { 'data-guide': 'price' } }), help: '<span id="price-help"></span>' })}${U.field({ label: 'Tiền cọc (VND)', req: true, input: U.money({ name: 'deposit', value: d.deposit }), help: '<span id="dep-help"></span>' })}</div><div class="xs muted mt8">Giá niêm yết và giá thực tế là hai giá riêng, cùng hiển thị trên hóa đơn (BR-06).</div></div>
        <div class="fs"><div class="fs-h">${I('sliders')}Dịch vụ đi kèm</div><div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá (VND)</th><th class="num">Số lượng / Mức sử dụng</th><th class="num">Thành tiền (VND)</th><th>Ghi chú</th><th></th></tr></thead><tbody id="svc-body">${svcRows()}</tbody></table></div>${U.btn({ label: 'Thêm dịch vụ', icon: 'plus', act: 'add-svc', cls: 'btn-outline mt8', size: 'btn-sm' })}<div class="xs muted mt8">Điện/Nước tính theo chỉ số hàng tháng, không nhập ở đây. Số xe không giới hạn (BR-05).</div></div>
        <div class="fs"><div class="fs-h">${I('users')}Danh sách thành viên ở</div><div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Họ và tên <span class="red">*</span></th><th>Ngày sinh</th><th>CMND/CCCD</th><th>Quan hệ</th><th>Số điện thoại</th><th>Ghi chú</th><th></th></tr></thead><tbody id="mb-body">${memRows()}</tbody></table></div>${U.btn({ label: 'Thêm thành viên', icon: 'plus', act: 'add-mb', cls: 'btn-outline mt8', size: 'btn-sm' })}</div>
        <div class="fs"><div class="fs-h">${I('file-text')}Điều khoản đặc biệt</div>${U.textarea({ name: 'note', value: d.note, placeholder: 'Ghi chú điều khoản riêng (nếu có)…' })}</div>
      </div></div>
      <div class="wz-foot">${U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', act: 'draft', cls: 'btn-outline' })}${U.btn({ label: 'Lưu hợp đồng →', act: 'next', cls: 'btn-primary', attrs: { 'data-guide': 'contract-save' } })}</div></div></form>
      <aside class="side-stack" id="summary"></aside></div>`;
    const form = root.querySelector('#cf');
    const read = () => { const v = U.formData(form); services = services.map((s, i) => ({ serviceId: v['sv_id_' + i] || null, name: v['sv_id_' + i] ? Q.service(v['sv_id_' + i]).name : (s.name || 'Dịch vụ khác'), unit: v['sv_unit_' + i], price: F.num(v['sv_price_' + i]), qty: Number(v['sv_qty_' + i]) || 0, note: v['sv_note_' + i] })); members = members.map((m, i) => ({ name: v['mb_name_' + i], dob: v['mb_dob_' + i], idNumber: v['mb_id_' + i], relation: v['mb_rel_' + i], phone: v['mb_phone_' + i], note: v['mb_note_' + i] })); return { id: draft ? draft.id : undefined, tenantId: v.tenantId, roomId: v.roomId, start: v.start, end: v.end, payDay: Number(v.payDay), listPrice: v.listPrice, price: v.price, deposit: v.deposit, note: v.note, services, members }; };
    const summary = () => { const v = read(); const t = v.tenantId ? Q.tenant(v.tenantId) : null; const r = v.roomId ? Q.room(v.roomId) : null; const months = v.start && v.end && v.end > v.start ? F.monthsDiff(v.start, v.end) : 0; form.querySelector('input[name=term]').value = months ? months + ' tháng' : ''; const svcTotal = F.sum(v.services, s => s.price * s.qty); v.services.forEach((s, i) => { const c = form.querySelector(`[data-amt="${i}"]`); if (c) c.textContent = F.vnd(s.price * s.qty); }); const diff = v.listPrice && v.price ? v.price - v.listPrice : 0; form.querySelector('#price-help').innerHTML = diff ? `<span class="${diff < 0 ? 'green' : 'red'}">${diff < 0 ? '↓' : '↑'} ${Math.abs(Math.round(diff / v.listPrice * 100))}%</span> ${diff < 0 ? 'Thấp hơn' : 'Cao hơn'} ${F.vnd(Math.abs(diff))} đ so với giá niêm yết` : ''; form.querySelector('#dep-help').textContent = v.deposit && v.price ? 'Tương đương ' + (Math.round(v.deposit / v.price * 10) / 10) + ' tháng tiền thuê' : '';
      const checks = [[!!t, 'Đã chọn khách thuê'], [!!r, 'Đã chọn phòng'], [months > 0, 'Đã thiết lập thời hạn thuê'], [v.price > 0 && v.deposit >= 0 && v.deposit !== '', 'Đã thiết lập giá thuê và cọc'], [v.services.length > 0, 'Đã có dịch vụ đi kèm (' + v.services.length + ' dịch vụ)'], [v.members.filter(m => m.name).length > 0, 'Đã có ' + v.members.filter(m => m.name).length + ' thành viên ở']];
      root.querySelector('#summary').innerHTML = U.card({ title: 'Tóm tắt hợp đồng', icon: 'clipboard-check', body: `<div class="fs" style="margin-top:0"><div class="fs-h" style="font-size:13.5px">${I('user')}Thông tin khách thuê<a class="link small ml-auto" data-act="focus" data-t="tenantId">${I('pencil')} Chỉnh sửa</a></div>${t ? `<div class="row gap12">${U.avatar(t.name)}<div><b style="color:var(--text)">${esc(t.name)}</b><div class="xs muted">${esc(t.code)}<br>${I('phone')} ${esc(t.phone)}<br>${I('mail')} ${esc(t.email || '-')}</div></div></div>` : '<div class="muted small">Chưa chọn khách</div>'}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('home')}Thông tin phòng<a class="link small ml-auto" data-act="focus" data-t="roomId">${I('pencil')} Chỉnh sửa</a></div>${r ? `<div class="row gap12"><div class="photo" style="width:64px;height:48px"></div><div><b style="color:var(--text)">${esc(r.code)}</b><div class="xs muted">${esc(Q.building(r.buildingId).name)}<br>${esc(r.type)} • ${r.area} m²</div></div><span class="ml-auto">${Q.chipDot('room', r.status)}</span></div>` : '<div class="muted small">Chưa chọn phòng</div>'}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('calendar')}Thời hạn thuê</div>${U.kv([['Ngày bắt đầu', v.start ? F.date(v.start) : '-'], ['Ngày kết thúc', v.end ? F.date(v.end) : '-'], ['Thời hạn', months ? months + ' tháng' : '-']], 'one')}</div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('coins')}Tài chính (ước tính)</div>${U.kv([['Giá thuê (thực tế)', F.vnd(v.price) + ' đ/tháng'], ['Tổng dịch vụ', F.vnd(svcTotal) + ' đ/tháng']], 'one')}<div class="hl-row blue mt8"><span>Tổng tiền hàng tháng</span><span>${F.vnd((v.price || 0) + svcTotal)} đ</span></div><div class="hl-row amber mt8"><span>Tiền cọc</span><span>${F.vnd(v.deposit)} đ</span></div></div>
        <div class="fs"><div class="fs-h" style="font-size:13.5px">${I('alert-triangle')}Kiểm tra & cảnh báo</div><div class="check-list">${checks.map(([ok, l]) => `<div class="it">${I(ok ? 'check-circle' : 'x-circle', ok ? 'green' : 'red')}<span>${l}</span></div>`).join('')}<div class="it">${I('alert-circle', 'amber')}<span class="amber">Nhớ kiểm tra điều khoản đặc biệt trong bước cuối</span></div><div class="it">${I('info', 'blue')}<span>Sau khi lưu, hợp đồng sẽ ở trạng thái "Dự thảo"</span></div></div></div>` }); };
    const setRoom = (rid) => { const r = rid ? Q.room(rid) : null; form.querySelector('input[name=rtype]').value = r ? r.type : ''; form.querySelector('input[name=rarea]').value = r ? r.area : ''; form.querySelector('#rstatus').innerHTML = r ? Q.chipDot('room', r.status) : '-'; if (r && !draft) { form.querySelector('input[name=listPrice]').value = F.vnd(r.price); form.querySelector('input[name=price]').value = F.vnd(r.price); form.querySelector('input[name=deposit]').value = F.vnd(r.price * 2); if (!services.length) { services = (r.defaultServiceIds || []).map(id => { const s = Q.service(id); return { serviceId: s.id, name: s.name, unit: s.unit, price: s.price, qty: 1, note: '' }; }); form.querySelector('#svc-body').innerHTML = svcRows(); } } };
    U.onChange(root, {
      tenant: (el) => { const t = Q.tenant(el.value); form.querySelector('input[name=tphone]').value = t.phone || ''; form.querySelector('input[name=temail]').value = t.email || ''; read(); if (!members.length || (members.length === 1 && !members[0].name)) { members = [{ name: t.name, dob: t.dob, idNumber: t.idNumber, relation: 'Người thuê (chính)', phone: t.phone, note: '' }]; form.querySelector('#mb-body').innerHTML = memRows(); } summary(); },
      building: (el) => { const sel = form.querySelector('select[name=roomId]'); sel.innerHTML = '<option value="" disabled selected>Chọn phòng</option>' + rooms.filter(r => r.buildingId === el.value).map(r => `<option value="${r.id}">${r.code}${r.status === 'held' ? ' (giữ chỗ)' : ''}</option>`).join(''); setRoom(''); summary(); },
      room: (el) => { const r = Q.room(el.value); form.querySelector('select[name=buildingId]').value = r.buildingId; setRoom(el.value); const h = Q.roomHold(el.value); if (h && !form.querySelector('select[name=tenantId]').value) { form.querySelector('select[name=tenantId]').value = h.tenantId; form.querySelector('select[name=tenantId]').dispatchEvent(new Event('change', { bubbles: true })); } summary(); },
      svc: (el) => { const i = Number(el.name.split('_')[2]); const s = Q.service(el.value); if (s.id) { form.querySelector(`input[name=sv_unit_${i}]`).value = s.unit; form.querySelector(`input[name=sv_price_${i}]`).value = F.vnd(s.price); } summary(); },
    });
    form.addEventListener('input', () => summary()); form.addEventListener('change', (e) => { if (e.target.name === 'mode') { root.querySelector('#ocr-note').hidden = e.target.value !== 'upload'; form.querySelectorAll('.radio-card').forEach(rc => rc.classList.toggle('on', rc.querySelector('input').checked)); } summary(); });
    U.onInput(form); U.bindDropzones(form);
    // Stepper phản ánh section đang thao tác (focus/scroll) – 1 trang form, 4 bước nhập + Review
    const setStep = (k) => { root.querySelectorAll('.wz-step').forEach((el, i) => { el.classList.toggle('done', i < k); el.classList.toggle('on', i === k); el.querySelector('.n').innerHTML = i < k ? I('check') : String(i + 1); }); root.querySelectorAll('.wz-line').forEach((el, i) => el.classList.toggle('done', i < k)); };
    const SEC_STEP = [1, 1, 2, 2, 2, 3, 3, 3]; root.querySelectorAll('#cf .fs').forEach((el, i) => { el.dataset.step = SEC_STEP[i] != null ? SEC_STEP[i] : 3; });
    root.addEventListener('focusin', (e) => { const fs = e.target.closest('.fs'); if (fs && fs.dataset.step) setStep(Number(fs.dataset.step)); });
    const onScroll = () => { const secs = [...root.querySelectorAll('#cf .fs')]; if (!secs.length || !document.contains(root)) return; const cur = secs.filter(el => el.getBoundingClientRect().top <= 160).pop(); setStep(cur ? Number(cur.dataset.step) : 1); };
    if (TH._cfScroll) window.removeEventListener('scroll', TH._cfScroll); TH._cfScroll = onScroll; window.addEventListener('scroll', onScroll, { passive: true });
    U.bind(root, {
      'add-svc': () => { read(); services.push({ serviceId: svcOpts[0].id, name: svcOpts[0].name, unit: svcOpts[0].unit, price: svcOpts[0].price, qty: 1, note: '' }); form.querySelector('#svc-body').innerHTML = svcRows(); summary(); }, 'rm-svc': (b) => { read(); services.splice(Number(b.dataset.i), 1); form.querySelector('#svc-body').innerHTML = svcRows(); summary(); },
      'add-mb': () => { read(); members.push({ name: '', dob: '', idNumber: '', relation: 'Bạn cùng phòng', phone: '', note: '' }); form.querySelector('#mb-body').innerHTML = memRows(); summary(); }, 'rm-mb': (b) => { read(); members.splice(Number(b.dataset.i), 1); form.querySelector('#mb-body').innerHTML = memRows(); summary(); },
      focus: (b) => { const el = form.querySelector(`[name="${b.dataset.t}"]`); el && el.focus(); el && el.scrollIntoView({ behavior: 'smooth', block: 'center' }); },
      'new-tenant': () => Fm.tenant({}, (t) => { const sel = form.querySelector('select[name=tenantId]'); sel.insertAdjacentHTML('afterbegin', `<option value="${t.id}">${esc(t.name)} (${t.code}) – ${esc(t.phone)}</option>`); sel.value = t.id; sel.dispatchEvent(new Event('change', { bubbles: true })); }),
      cancel: async () => { if (await U.confirm({ title: 'Hủy tạo hợp đồng?', text: 'Dữ liệu chưa lưu sẽ mất.', ok: 'Hủy tạo', danger: true })) TH.go('#/contracts'); },
      draft: () => { try { const c = X.saveContractDraft(read()); U.toast('ok', 'Đã lưu nháp ' + c.code, 'Hợp đồng ở trạng thái Dự thảo'); TH.go('#/contracts/new?id=' + c.id); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      next: () => { try { const v = read(); if (!v.tenantId) throw new Error('Chọn khách thuê'); if (!v.roomId) throw new Error('Chọn phòng'); if (!v.price) throw new Error('Nhập giá thuê thực tế'); if (v.end <= v.start) throw new Error('Ngày kết thúc phải sau ngày bắt đầu'); if (!v.members.some(m => m.name)) throw new Error('Cần ít nhất một thành viên ở'); const c = X.saveContractDraft(v); TH.go('#/contracts/new?id=' + c.id + '&step=5'); } catch (e) { U.toast('err', 'Chưa thể tiếp tục', e.message); } },
    });
    // tránh re-render form khi store đổi (lưu nháp) — router.refresh chỉ khi đổi route
    summary();
  }, { menu: 'contracts', permission: 'contracts.manage', noAutoRefresh: true });
  function renderReview(root, c) {
    const t = Q.tenant(c.tenantId), r = Q.room(c.roomId), svcs = Q.contractServices(c.id), mbs = Q.contractMembers(c.id);
    const svcTotal = F.sum(svcs, s => s.price * s.qty); const clash = St.one('contracts', x => x.roomId === c.roomId && x.id !== c.id && x.status === 'active');
    root.innerHTML = `${U.pageHead({ title: 'Tạo hợp đồng', sub: 'Bước 5/5 – Kiểm tra lại toàn bộ thông tin trước khi kích hoạt. Kích hoạt sẽ chuyển phòng sang Đang thuê.' })}${U.wizard(STEPS, 4)}
    <div class="two-col"><div class="side-stack">${U.card({ title: 'Review hợp đồng ' + esc(c.code), icon: 'clipboard-check', actions: Q.chip('contract', 'draft'), body: `<div class="grid grid-2">${U.kv([['Khách thuê', esc(t.name) + ' (' + esc(t.code) + ')'], ['SĐT', esc(t.phone)], ['Phòng', esc(r.code) + ' · ' + esc(Q.building(r.buildingId).name)], ['Tình trạng phòng', Q.chipDot('room', r.status)], ['Thời hạn', F.date(c.start) + ' – ' + F.date(c.end) + ' (' + F.monthsDiff(c.start, c.end) + ' tháng)'], ['Ngày thanh toán', 'Ngày ' + F.pad(c.payDay) + ' hàng tháng']], 'one')}${U.kv([['Giá niêm yết', F.vnd(c.listPrice) + ' đ'], ['Giá thuê thực tế', '<span class="blue">' + F.vnd(c.price) + ' đ</span>'], ['Tiền cọc', F.vnd(c.deposit) + ' đ'], ['Dịch vụ cố định', F.vnd(svcTotal) + ' đ/tháng'], ['Tổng tiền hàng tháng', '<b>' + F.vnd(c.price + svcTotal) + ' đ</b>'], ['Điều khoản đặc biệt', esc(c.note || 'Không có')]], 'one')}</div>` })}
      ${U.card({ title: 'Dịch vụ đi kèm (' + svcs.length + ')', icon: 'sliders', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá</th><th class="num">SL</th><th class="num">Thành tiền</th><th>Ghi chú</th></tr></thead><tbody>${svcs.map(s => `<tr><td>${esc(s.name)}</td><td>${esc(s.unit)}</td><td class="num">${F.vnd(s.price)}</td><td class="num">${s.qty}</td><td class="num">${F.vnd(s.price * s.qty)}</td><td>${esc(s.note || '-')}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Không có</td></tr>'}</tbody></table>` })}
      ${U.card({ title: 'Thành viên ở (' + mbs.length + ')', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Họ tên</th><th>Ngày sinh</th><th>CCCD</th><th>Quan hệ</th><th>SĐT</th></tr></thead><tbody>${mbs.map(m => `<tr><td>${esc(m.name)}</td><td>${m.dob ? F.date(m.dob) : '-'}</td><td>${esc(m.idNumber || '-')}</td><td>${esc(m.relation)}</td><td>${esc(m.phone || '-')}</td></tr>`).join('')}</tbody></table>` })}
      <div class="wz-foot">${U.btn({ label: '← Quay lại sửa', act: 'back', cls: 'btn-ghost' })}<div class="row">${U.btn({ label: 'Giữ ở Dự thảo', act: 'keep', cls: 'btn-outline' })}${U.btn({ label: 'Xác nhận & kích hoạt hợp đồng', icon: 'check-circle', act: 'activate', cls: 'btn-primary', disabled: !!clash, attrs: { 'data-guide': 'contract-activate' } })}</div></div></div>
      <aside class="side-stack">${U.card({ title: 'Kiểm tra trước kích hoạt', icon: 'shield-check', body: `<div class="check-list">${[[['ready', 'held'].includes(r.status), 'Phòng đang ' + Q.label('room', r.status) + (['ready', 'held'].includes(r.status) ? ' – hợp lệ' : ' – không thể kích hoạt')], [!clash, clash ? 'Trùng HĐ hiệu lực ' + clash.code : 'Không trùng hợp đồng hiệu lực (FR-CUS-02)'], [c.end > c.start, 'Ngày kết thúc sau ngày bắt đầu'], [c.price > 0, 'Đã có giá thuê thực tế'], [mbs.length > 0, 'Có ' + mbs.length + ' thành viên ở'], [true, 'Hóa đơn sẽ snapshot giá/dịch vụ theo kỳ (BR-21)']].map(([ok, l]) => `<div class="it">${I(ok ? 'check-circle' : 'x-circle', ok ? 'green' : 'red')}<span>${l}</span></div>`).join('')}</div>` })}${U.note('info', 'Sau khi kích hoạt', 'Hợp đồng → Hiệu lực, phòng → Đang thuê, cọc ghi nhận đang giữ. Bước tiếp theo: nhập điện nước & tạo hóa đơn kỳ ' + F.periodLabel(St.state.meta.period) + '.')}</aside></div>`;
    U.bind(root, { back: () => TH.go('#/contracts/new?id=' + c.id), keep: () => { U.toast('ok', 'Hợp đồng ' + c.code + ' đang ở Dự thảo'); TH.go('#/contracts/' + c.id); }, activate: async () => { if (await U.confirm({ title: 'Kích hoạt hợp đồng ' + c.code + '?', text: 'Phòng ' + r.code + ' chuyển sang Đang thuê.', ok: 'Kích hoạt' })) { try { X.activateContract(c.id, 'act:' + c.id); U.toast('ok', 'Đã kích hoạt hợp đồng ' + c.code, 'Phòng ' + r.code + ' → Đang thuê'); TH.go('#/contracts/' + c.id); } catch (e) { U.toast('err', 'Không kích hoạt được', e.message); } } } });
  }

  /* ---------- Chi tiết hợp đồng ---------- */
  TH.router.register('/contracts/:id', (root, p, q) => {
    const c = St.get('contracts', p.id); if (!c) { root.innerHTML = U.empty({ title: 'Không tìm thấy hợp đồng' }); return; }
    const t = Q.tenant(c.tenantId), r = Q.room(c.roomId), b = Q.building(c.buildingId), s = Q.contractStatus(c), svcs = Q.contractServices(c.id), mbs = Q.contractMembers(c.id), tab = q.tab || 'overview';
    const invs = St.where('invoices', i => i.contractId === c.id && i.docStatus !== 'cancelled').sort((a, z) => F.cmp(z.period, a.period)); const debt = F.sum(invs.filter(i => i.docStatus !== 'draft'), i => Q.invRemaining(i)); const rf = St.one('refunds', x => x.contractId === c.id);
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: c.code }]);
    const acts = []; if (c.status === 'draft') acts.push(U.btn({ label: 'Sửa nháp', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Kích hoạt', icon: 'check-circle', cls: 'btn-primary', act: 'activate' }));
    if (c.status === 'active') acts.push(U.btn({ label: 'Tạo hóa đơn', icon: 'receipt', cls: 'btn-outline', act: 'inv' }), U.btn({ label: 'Gia hạn', icon: 'refresh', cls: 'btn-outline', act: 'renew' }), U.btn({ label: 'Kết thúc hợp đồng', icon: 'x-circle', cls: 'btn-danger', act: 'terminate', attrs: { 'data-guide': 'contract-terminate' } }));
    if (c.status === 'ended' && !rf && !c.renewedToId) acts.push(U.btn({ label: 'Lập phương án hoàn cọc', icon: 'hand-coins', cls: 'btn-primary', act: 'refund' }));
    if (rf) acts.push(U.btn({ label: 'Hồ sơ hoàn cọc ' + rf.code, icon: 'hand-coins', cls: 'btn-outline', act: 'go-refund' }));
    acts.push(U.btn({ label: 'Tải PDF', icon: 'download', cls: 'btn-outline', act: 'pdf' }), U.iconBtn('more', 'more', 'Thêm', {}, 'bordered'));
    root.innerHTML = `${U.pageHead({ back: '#/contracts', title: esc(c.code), chips: ' ' + Q.chip('contract', s, 'lg'), sub: `${esc(t.name)} • ${esc(r.code)} - ${esc(b.name)} • ${F.date(c.start)} – ${F.date(c.actualEnd || c.end)}${c.renewedFromId ? ' • Gia hạn từ ' + U.link('#/contracts/' + c.renewedFromId, Q.contract(c.renewedFromId).code) : ''}${c.renewedToId ? ' • Đã gia hạn → ' + U.link('#/contracts/' + c.renewedToId, Q.contract(c.renewedToId).code) : ''}`, acts })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Giá thuê thực tế', value: F.vnd(c.price), cap: 'Niêm yết ' + F.vnd(c.listPrice) + ' đ', icon: 'dollar', tone: 'amber' })}${U.kpi({ label: 'Tiền cọc', value: F.vnd(c.deposit), cap: rf ? 'Hoàn cọc: ' + Q.label('refund', rf.status) : c.status === 'active' ? 'Đang giữ' : '-', icon: 'shield', tone: 'blue' })}${U.kpi({ label: 'Công nợ', value: F.vnd(debt), cap: invs.length + ' hóa đơn', icon: 'alert-circle', tone: 'red', valueCls: debt ? 'red' : '' })}${U.kpi({ label: c.status === 'active' ? 'Còn lại' : 'Trạng thái', value: c.status === 'active' ? F.daysUntil(c.end) + ' ngày' : Q.label('contract', s), cap: c.status === 'active' ? 'Kết thúc ' + F.date(c.end) + (s === 'expiring' ? ' – sắp hết hạn (≤35 ngày)' : '') : (c.actualEnd ? 'Kết thúc thực tế ' + F.date(c.actualEnd) : ''), icon: 'clock', tone: s === 'expiring' ? 'amber' : 'green' })}</div>
    ${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'services', label: 'Dịch vụ & xe' }, { key: 'members', label: 'Thành viên' }, { key: 'invoices', label: 'Hóa đơn', count: invs.length }, { key: 'docs', label: 'Tài liệu' }, { key: 'log', label: 'Lịch sử' }], tab)}<div id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin hợp đồng', icon: 'file-text', body: U.kv([['Mã HĐ', esc(c.code)], ['Trạng thái', Q.chip('contract', s)], ['Ngày ký', F.date(c.signedDate)], ['Ngày bắt đầu', F.date(c.start)], ['Ngày kết thúc', F.date(c.end)], ['Kết thúc thực tế', c.actualEnd ? F.date(c.actualEnd) : '-'], ['Lý do kết thúc', esc(c.endReason || '-')], ['Chu kỳ thanh toán', 'Hàng tháng, ngày ' + F.pad(c.payDay)], ['Người phụ trách', esc(Q.userName(c.managerId))], ['Ghi chú / điều khoản', esc(c.note || '-') + ' <a class="link small" data-act="edit-note">' + I('pencil') + ' Sửa</a>' + (c.noteAt ? '<div class="xs muted">Cập nhật ' + F.datetime(c.noteAt) + (c.noteBy ? ' · ' + esc(c.noteBy) : '') + '</div>' : '')]], 'one') })}${U.card({ title: 'Khách thuê & phòng', icon: 'user', body: `<div class="row gap12 mb12">${U.avatar(t.name, 'lg')}<div><b style="font-size:15px;color:var(--text)">${U.link('#/tenants/' + t.id, esc(t.name))}</b><div class="small muted">${esc(t.code)} · ${I('phone')} ${esc(t.phone)}</div></div></div>${U.kv([['Phòng', U.link('#/rooms/' + r.id, esc(r.code))], ['Tòa nhà', U.link('#/buildings/' + b.id, esc(b.name))], ['Loại / diện tích', esc(r.type) + ' · ' + r.area + ' m²'], ['Trạng thái phòng', Q.chipDot('room', r.status)], ['Tổng tiền hàng tháng (ước)', F.vnd(Q.contractMonthly(c)) + ' đ']], 'one')}` })}</div>`;
    if (tab === 'services') body.innerHTML = U.card({ title: 'Dịch vụ áp dụng & phương tiện', icon: 'sliders', sub: 'Snapshot giá theo hợp đồng (BR-21); số xe không giới hạn (BR-05)', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Dịch vụ</th><th>Đơn vị</th><th class="num">Đơn giá</th><th class="num">Số lượng</th><th class="num">Thành tiền/tháng</th><th>Ghi chú</th></tr></thead><tbody>${svcs.map((x, i) => `<tr><td>${i + 1}</td><td>${esc(x.name)}</td><td>${esc(x.unit)}</td><td class="num">${F.vnd(x.price)}</td><td class="num">${x.qty}</td><td class="num">${F.vnd(x.price * x.qty)}</td><td>${esc(x.note || '-')}</td></tr>`).join('')}<tr><td colspan="5"><b>Điện, Nước</b></td><td colspan="2" class="muted">Theo chỉ số hàng tháng – nhập tại Tạo hóa đơn theo kỳ</td></tr></tbody></table>` });
    if (tab === 'members') body.innerHTML = U.card({ title: 'Thành viên ở', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Họ tên</th><th>Ngày sinh</th><th>CCCD</th><th>Quan hệ</th><th>SĐT</th><th>Ghi chú</th></tr></thead><tbody>${mbs.map((m, i) => `<tr><td>${i + 1}</td><td><b>${esc(m.name)}</b></td><td>${m.dob ? F.date(m.dob) : '-'}</td><td>${esc(m.idNumber || '-')}</td><td>${esc(m.relation)}</td><td>${esc(m.phone || '-')}</td><td>${esc(m.note || '-')}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Chưa có</td></tr>'}</tbody></table>` });
    if (tab === 'invoices') { body.innerHTML = U.card({ title: 'Hóa đơn của hợp đồng', icon: 'receipt', actions: c.status === 'active' ? U.btn({ label: 'Tạo hóa đơn', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'inv' }) : '', body: null, id: 'ic' }); const w = document.createElement('div'); body.querySelector('#ic').appendChild(w); U.table(w, { rows: invs, unit: 'hóa đơn', cols: [{ key: 'code', label: 'Mã', render: i => U.link('#/invoices/' + i.id, i.code) }, { key: 'period', label: 'Kỳ', render: i => F.periodShort(i.period) }, { key: 'issue', label: 'Phát hành', render: i => F.date(i.issueDate) }, { key: 'due', label: 'Hạn', render: i => F.date(i.dueDate) }, { key: 'total', label: 'Tổng', num: true, render: i => F.vnd(i.total) }, { key: 'paid', label: 'Đã thu', num: true, render: i => F.vnd(Q.invPaid(i)) }, { key: 'rem', label: 'Còn lại', num: true, render: i => `<span class="${Q.invRemaining(i) ? 'red bold' : ''}">${F.vnd(Q.invRemaining(i))}</span>` }, { key: 'doc', label: 'Chứng từ', render: i => Q.chip('invDoc', i.docStatus) }, { key: 'pay', label: 'Thu', render: i => i.docStatus === 'draft' ? '-' : Q.invPayChip(i) }], empty: U.empty({ title: 'Chưa có hóa đơn' }) }); }
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'contract' && d.entityId === c.id); body.innerHTML = U.card({ title: 'Tài liệu hợp đồng', icon: 'folder', actions: U.btn({ label: 'Tải lên HĐ đã ký', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có file hợp đồng', text: 'Tải lên bản hợp đồng đã ký (PDF/JPG). Trích xuất OCR thuộc Phase 2.' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => (x.entityType === 'contract' && x.entityId === c.id) || (x.entityType === 'invoice' && invs.some(i => i.id === x.entityId)) || (rf && x.entityType === 'refund' && x.entityId === rf.id)); body.innerHTML = U.card({ title: 'Lịch sử', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'edit-note': () => { const m = U.modal({ title: 'Ghi chú / điều khoản hợp đồng', size: 'sm', body: U.textarea({ name: 'note', value: c.note || '', rows: 5, placeholder: 'Điều khoản đặc biệt, thỏa thuận thêm…' }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { X.updateContractNote(c.id, m.data().note); m.close(); U.toast('ok', 'Đã lưu ghi chú hợp đồng'); } }); }, edit: () => TH.go('#/contracts/new?id=' + c.id), activate: () => TH.go('#/contracts/new?id=' + c.id + '&step=5'), inv: () => TH.go('#/invoices/batch?buildingId=' + c.buildingId + '&room=' + c.roomId), renew: () => Fm.renew(c), terminate: () => Fm.terminate(c), refund: () => TH.go('#/refunds/new?contract=' + c.id), 'go-refund': () => TH.go('#/refunds/' + rf.id), pdf: () => U.fakePdf('Hop dong ' + c.code, ['Khách: ' + t.name, 'Phòng: ' + r.code + ' – ' + b.name, 'Thời hạn: ' + F.date(c.start) + ' – ' + F.date(c.end), 'Giá thuê: ' + F.vnd(c.price), 'Cọc: ' + F.vnd(c.deposit)]), upload: () => Fm.upload('contract', c.id), 'rm-doc': (el) => X.removeDocument(el.dataset.id), more: (el) => cMenu(el, c) });
  }, { menu: 'contracts', permission: 'contracts.view', resource: { type: 'contract' } });
})(window.TH);
