(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, esc = F.esc, C = TH.chart;

  const queueRow = (x) => `<a class="work-row" href="${x.href}"><span class="work-icon ${x.tone || 'blue'}">${I(x.icon)}</span><span class="grow"><b>${esc(x.label)}</b><small>${esc(x.note || 'Mở danh sách để xử lý')}</small></span><strong class="${x.tone || 'blue'}">${x.count}</strong>${I('chevron-right')}</a>`;
  const metric = (label, value, note, icon, tone = 'blue', href = '') => `<${href ? 'a href="' + href + '"' : 'div'} class="focus-kpi ${href ? 'clickable' : ''}"><span class="focus-kpi-icon ${tone}">${I(icon)}</span><span><small>${esc(label)}</small><strong>${value}</strong><em>${esc(note)}</em></span></${href ? 'a' : 'div'}>`;
  const wbMetric = (key, label, value, note, icon, tone, href) => `<a href="${href}" class="focus-kpi clickable wb-kpi"><span class="focus-kpi-icon ${tone}">${I(icon)}</span><span><small>${esc(label)} ${U.metricInfo(key)}</small><strong>${value}</strong><em>${esc(note)}</em></span></a>`;

  const dashboardModel = (role, period, f) => {
    const rooms = Q.filterRooms(f), rs = Q.roomStats(rooms), fin = Q.finance(period, f), todo = Q.todo();
    const expiring = St.where('contracts', c => Q.contractStatus(c) === 'expiring' && rooms.some(r => r.id === c.roomId)).length;
    const overdueAmount = fin.overdueInv.reduce((sum, inv) => sum + Q.invRemaining(inv), 0);
    const base = { title: 'Tổng quan', subtitle: 'Tình hình quan trọng và công việc cần ưu tiên hôm nay.', rooms, rs, fin, queue: [], kpis: [], chart: 'occupancy' };

    if (role === 'accountant') return Object.assign(base, {
      title: 'Công việc của tôi', subtitle: 'Tổng quan tài chính – theo dõi dòng tiền, công nợ và các chứng từ cần xử lý.', chart: 'collection',
      kpis: [metric('Phải thu trong kỳ', F.short(fin.receivable), fin.count + ' hóa đơn', 'receipt'), metric('Đã thu', F.short(fin.collected), fin.pct + '% kế hoạch', 'check-circle', 'green'), metric('Quá hạn', F.short(overdueAmount), fin.overdueInv.length + ' khoản', 'alert-circle', 'red', '#/receivables?overdue=1&period=all'), metric('Hoàn cọc chờ xử lý', todo.refunds || 0, 'Hồ sơ đang xử lý', 'hand-coins', 'amber', '#/refunds?status=processing')],
      queue: [{ label: 'OCR chờ review', count: todo.ocrReview || 0, icon: 'file-check', tone: 'purple', href: '#/contracts/ocr', note: 'Review nhóm entity → Validate → Commit (§12.8)' }, { label: 'Công nợ quá hạn', count: todo.overdue || fin.overdueInv.length, icon: 'alert-circle', tone: 'red', href: '#/receivables?overdue=1&period=all', note: 'Ưu tiên theo số ngày quá hạn' }, { label: 'Hóa đơn nháp chờ phát hành', count: todo.drafts || 0, icon: 'file-plus', tone: 'amber', href: '#/invoices?doc=draft&period=all', note: 'Kiểm tra trước khi phát hành' }, { label: 'Hoàn cọc đang xử lý', count: todo.refunds || 0, icon: 'hand-coins', tone: 'blue', href: '#/refunds?status=processing', note: 'Duyệt và ghi nhận thanh toán' }, { label: 'Chi lương chưa hoàn tất', count: todo.salaryUnpaid || 0, icon: 'banknote', tone: 'amber', href: '#/hr/salary-payments', note: 'Từ bảng lương đã khóa (§4.26.8)' }, { label: 'Import chi phí lỗi / chờ phân bổ', count: (todo.expenseImportErrors || 0) + (todo.expensePendingAlloc || 0), icon: 'upload', tone: 'gray', href: '#/expenses?status=pending_alloc', note: 'Dòng lỗi import & chi phí chung chưa phân bổ' }]
    });
    if (role === 'ops') return Object.assign(base, {
      title: 'Công việc của tôi', subtitle: 'Bàn làm việc vận hành – tập trung vào phòng, hợp đồng và các việc phát sinh trong ngày.',
      kpis: [metric('Phòng sẵn sàng', rs.ready, 'Có thể cho thuê ngay', 'door', 'green', '#/rooms?status=ready'), metric('Chờ dọn', rs.cleaning, 'Cần bàn giao lại', 'brush', 'amber', '#/rooms?status=cleaning'), metric('Hợp đồng sắp hết hạn', expiring, 'Trong 35 ngày', 'clock', 'red', '#/contracts?status=expiring'), metric('Đang giữ chỗ', rs.held, 'Chờ ký hợp đồng', 'bookmark', 'blue', '#/rooms?status=held')],
      queue: [{ label: 'OCR chờ review', count: todo.ocrReview || 0, icon: 'file-check', tone: 'purple', href: '#/contracts/ocr', note: 'Hợp đồng giấy đã tải, chờ review & commit' }, { label: 'Hợp đồng sắp hết hạn', count: expiring, icon: 'file-text', tone: 'red', href: '#/contracts?status=expiring', note: 'Liên hệ gia hạn hoặc chuẩn bị trả phòng' }, { label: 'Phòng chờ dọn', count: rs.cleaning, icon: 'brush', tone: 'amber', href: '#/rooms?status=cleaning', note: 'Xác nhận dọn xong để mở bán lại' }, { label: 'Hoàn cọc đang xử lý', count: todo.refunds || 0, icon: 'hand-coins', tone: 'blue', href: '#/refunds?status=processing', note: 'Bổ sung hiện trạng và bằng chứng' }, ...(TH.phase.on(2) ? [{ label: 'Lịch bảo dưỡng sắp đến hạn', count: todo.maintenanceDue || 0, icon: 'wrench', tone: 'amber', href: '#/maintenance/schedules?status=due_soon', note: 'Đến hạn trong 7 ngày' }] : [])]
    });
    if (role === 'sale') {
      const leads = St.all('leads'), viewings = St.all('viewings'), holds = St.all('holds');
      return Object.assign(base, { title: 'Công việc của tôi', subtitle: 'Bàn làm việc kinh doanh – lead cần chăm sóc, lịch xem phòng và cơ hội chốt thuê.', chart: 'pipeline', kpis: [metric('Lead đang mở', leads.filter(x => !['won', 'lost'].includes(x.status)).length, 'Cần tiếp tục chăm sóc', 'users', 'blue', '#/crm/leads'), metric('Lịch xem hôm nay', todo.viewingsToday || 0, 'Đã lên lịch', 'calendar-check', 'green', '#/crm/viewings?status=scheduled'), metric('Đang giữ chỗ', holds.filter(x => !['expired', 'converted', 'cancelled'].includes(x.status)).length, 'Theo dõi hạn giữ', 'clock', 'amber', '#/crm/holds'), metric('Phòng sẵn sàng', rs.ready, 'Có thể giới thiệu', 'door', 'green', '#/rooms?status=ready')], queue: [{ label: 'Lead cần liên hệ', count: leads.filter(x => ['new', 'contacted'].includes(x.status)).length, icon: 'phone', tone: 'red', href: '#/crm/leads', note: 'Ưu tiên lead mới và chưa có lịch hẹn' }, { label: 'Lịch xem hôm nay', count: todo.viewingsToday || 0, icon: 'calendar-check', tone: 'green', href: '#/crm/viewings?status=scheduled', note: 'Xác nhận khách và phòng trước giờ hẹn' }, { label: 'Giữ chỗ cần theo dõi', count: holds.filter(x => !['expired', 'converted', 'cancelled'].includes(x.status)).length, icon: 'clock', tone: 'amber', href: '#/crm/holds', note: 'Tránh giữ chỗ quá hạn' }] });
    }
    if (role === 'kythuat') {
      const incidents = St.all('incidents'), open = incidents.filter(x => !['done', 'closed', 'cancelled'].includes(x.status));
      return Object.assign(base, { title: 'Công việc của tôi', subtitle: 'Bàn làm việc kỹ thuật – sự cố được giao và lịch bảo dưỡng cần thực hiện.', kpis: [metric('Sự cố đang mở', open.length, 'Đang chờ xử lý', 'wrench', 'red', '#/maintenance?assignee=me'), metric('Ưu tiên cao', open.filter(x => ['high', 'urgent'].includes(x.priority)).length, 'Cần xử lý trước', 'alert-triangle', 'amber', '#/maintenance?assignee=me&priority=high'), metric('Lịch sắp đến hạn', todo.maintenanceDue || 0, 'Trong 7 ngày', 'calendar-clock', 'blue', '#/maintenance/schedules?status=due_soon'), metric('Tài sản cần xử lý', todo.inventoryPending || 0, 'Sau kiểm kê', 'package', 'purple', '#/assets/inventory?status=needs_action')], queue: [{ label: 'Sự cố ưu tiên cao', count: open.filter(x => ['high', 'urgent'].includes(x.priority)).length, icon: 'alert-triangle', tone: 'red', href: '#/maintenance?assignee=me&priority=high', note: 'Cập nhật tiến độ và bằng chứng' }, { label: 'Lịch bảo dưỡng sắp đến hạn', count: todo.maintenanceDue || 0, icon: 'calendar-clock', tone: 'amber', href: '#/maintenance/schedules?status=due_soon', note: 'Kiểm tra vật tư trước khi thực hiện' }, { label: 'Sự cố đang mở', count: open.length, icon: 'wrench', tone: 'blue', href: '#/maintenance?assignee=me', note: 'Danh sách công việc được giao' }] });
    }
    if (role === 'hr') {
      const employees = St.all('employees'), payrolls = St.all('payrolls');
      return Object.assign(base, { title: 'Công việc của tôi', subtitle: 'Bàn làm việc nhân sự – hồ sơ nhân viên, chấm công và kỳ lương cần hoàn tất.', chart: 'none', kpis: [metric('Nhân viên', employees.length, 'Trong hệ thống', 'users', 'blue', '#/hr'), metric('Sắp hết thử việc', todo.probationEnding || 0, 'Cần đánh giá', 'clock', 'amber', '#/hr?status=probation'), metric('Kỳ lương đang mở', payrolls.filter(x => !['paid', 'closed', 'locked'].includes(x.status)).length, 'Mở kỳ → review → duyệt → khóa', 'banknote', 'green', '#/hr/payroll'), metric('Chấm công', 'Hôm nay', 'Mở bảng chấm công', 'calendar-check', 'purple', '#/hr/timesheet')], queue: [{ label: 'Nhân viên sắp hết thử việc', count: todo.probationEnding || 0, icon: 'user-check', tone: 'amber', href: '#/hr?status=probation', note: 'Chuẩn bị đánh giá và quyết định' }, { label: 'Kỳ lương cần xử lý', count: payrolls.filter(x => !['paid', 'closed', 'locked'].includes(x.status)).length, icon: 'banknote', tone: 'blue', href: '#/hr/payroll', note: 'Hiệu suất M1/M2/M3 → rule → review → duyệt → khóa' }, { label: 'Chi lương chưa hoàn tất', count: todo.salaryUnpaid || 0, icon: 'hand-coins', tone: 'amber', href: '#/hr/salary-payments', note: 'Chưa chi / chi một phần / chi lỗi' }] });
    }
    if (role === 'codong') {
      const projects = St.all('projects'), contributions = St.all('contributions');
      return Object.assign(base, { title: 'Tổng quan đầu tư', subtitle: 'Theo dõi dự án, tiến độ góp vốn và hiệu quả phân phối.', chart: 'none', kpis: [metric('Dự án đang theo dõi', projects.length, 'Theo phạm vi đầu tư', 'folder', 'blue', '#/investment/projects'), metric('Đợt góp vốn đến hạn', todo.contributionsDue || 0, 'Cần hoàn tất', 'hand-coins', 'amber', '#/investment/shareholders?tab=contributions&status=due'), metric('Giao dịch góp vốn', contributions.length, 'Đã ghi nhận', 'coins', 'green', '#/investment/shareholders?tab=contributions'), metric('Hiệu quả đầu tư', 'ROI', 'Xem báo cáo chi tiết', 'trending-up', 'purple', '#/investment/roi')], queue: [{ label: 'Đợt góp vốn đến hạn', count: todo.contributionsDue || 0, icon: 'hand-coins', tone: 'amber', href: '#/investment/shareholders?tab=contributions&status=due', note: 'Theo dõi phần vốn cam kết' }, { label: 'Dự án trong danh mục', count: projects.length, icon: 'folder', tone: 'blue', href: '#/investment/projects', note: 'Xem tiến độ và hiệu quả' }] });
    }
    return Object.assign(base, {
      kpis: [metric('Phòng sẵn sàng', rs.ready, 'Trên tổng ' + rs.total + ' phòng', 'door', 'green', '#/rooms?status=ready'), metric('Hợp đồng sắp hết hạn', expiring, 'Trong 35 ngày', 'clock', 'amber', '#/contracts?status=expiring'), metric('Tiến độ thu', fin.pct + '%', 'Đã thu ' + F.short(fin.collected), 'calendar-check', 'purple', '#/receivables'), metric('Công nợ quá hạn', F.short(overdueAmount), fin.overdueInv.length + ' khoản', 'alert-circle', 'red', '#/receivables?overdue=1&period=all')],
      queue: [{ label: 'OCR chờ review', count: todo.ocrReview || 0, icon: 'file-check', tone: 'purple', href: '#/contracts/ocr', note: 'Review nhóm entity → Validate → Commit' }, { label: 'Hợp đồng sắp hết hạn', count: todo.expiring || expiring, icon: 'clock', tone: 'amber', href: '#/contracts/expiring', note: 'Work Queue: liên hệ → gia hạn / trả phòng' }, { label: 'Hóa đơn chưa phát hành', count: todo.draftInvoices || 0, icon: 'file-plus', tone: 'amber', href: '#/invoices?doc=draft&period=all', note: 'Nháp cần kiểm tra & phát hành' }, { label: 'Khách còn nợ', count: todo.debtors || 0, icon: 'alert-circle', tone: 'red', href: '#/receivables?period=all', note: (todo.overdue || 0) + ' hóa đơn quá hạn' }, { label: 'Tin Zalo gửi lỗi', count: todo.zaloFailed || 0, icon: 'send', tone: 'red', href: '#/zalo/history?hasFailed=1', note: 'Kiểm tra và gửi lại' }, { label: 'HĐ chờ quyết toán', count: todo.settlementPending || 0, icon: 'x-circle', tone: 'orange', href: '#/contracts?status=pending_settlement', note: 'Chờ kết thúc / chờ quyết toán trả phòng' }, { label: 'Hoàn cọc chờ duyệt', count: todo.refundsApproval || 0, icon: 'hand-coins', tone: 'blue', href: '#/refunds?status=pending', note: (todo.refunds || 0) + ' hồ sơ đang xử lý' }, { label: 'Phòng chờ dọn', count: todo.cleaningRooms || 0, icon: 'brush', tone: 'teal', href: '#/rooms?status=cleaning', note: 'Xác nhận dọn xong / nghiệm thu' }, { label: 'Import chi phí lỗi', count: todo.expenseImportErrors || 0, icon: 'upload', tone: 'gray', href: '#/settings/import?type=expense', note: (todo.expensePendingAlloc || 0) + ' chi phí chung chờ phân bổ · dòng lỗi/trùng cần sửa & import lại' }, { label: 'Kỳ trả chủ nhà đến hạn', count: todo.landlordDue || 0, icon: 'banknote', tone: 'amber', href: '#/landlords?upcoming=1', note: 'Đến hạn trong 7 ngày' }]
    });
  };

  TH.router.register('/dashboard', (root, params, q) => {
    const role = TH.auth.role(), period = q.period || St.state.meta.period, dashboardView = role === 'admin' ? (q.view || 'work') : 'work';
    const f = { period, orgUnitId: q.orgUnitId || '', employeeId: q.employeeId || '', areaId: q.areaId || '', buildingId: q.buildingId || '', buildingType: q.buildingType || '', managerId: q.managerId || '', leadId: q.leadId || '' }, scope = Q.scope(f);
    const m = dashboardModel(role, period, f);
    const buildings = St.where('buildings', b => !b.stub && scope.buildingIds.includes(b.id));
    const groups = buildings.map(b => { const s = Q.roomStats(Q.roomsOf(b.id)); return { label: b.name, sub: '(' + s.total + ' phòng)', values: [s.occupied, s.ready, s.held, s.maintenance, s.cleaning + s.inactive] }; });
    const finB = buildings.map(b => { const x = Q.finance(period, { buildingId: b.id }); return { label: b.name, a: x.collected, b: x.remaining }; });
    const contextualFilter = ['admin', 'accountant', 'qltong', 'tpvh', 'hr'].includes(role) ? U.dimFilter(f, { dims: ['period', 'orgUnitId', 'employeeId', 'areaId', 'buildingType', 'buildingId', 'managerId', 'leadId'], inline: 3 }) : '';
    const scopeNote = f.orgUnitId || f.employeeId ? U.note('info', 'Phạm vi theo cây tổ chức tại ' + F.date(scope.date || Q.periodEndDate(period)), (f.orgUnitId ? 'Đơn vị <b>' + esc(Q.orgUnit(f.orgUnitId).name || '') + '</b> + đơn vị con → nhân sự → tòa do Phụ trách chính (§4.3). ' : '') + (f.employeeId ? 'Nhân sự <b>' + esc(Q.employeeName(f.employeeId)) + '</b>. ' : '') + '<b>' + scope.buildingIds.length + ' tòa</b>: ' + scope.buildingIds.map(id => esc(Q.building(id).name)).join(', ')) + '<div class="mb16"></div>' : '';
    const occupancyChart = U.card({ title: 'Trạng thái phòng theo tòa', icon: 'bar-chart-2', actions: C.legend([{ label: 'Đang ở', color: '#1D4ED8' }, { label: 'Trống', color: '#BFDBFE' }, { label: 'Giữ chỗ', color: '#FCD34D' }, { label: 'Bảo trì', color: '#F97316' }]), body: C.stackedBar({ groups, series: [{ color: '#1D4ED8' }, { color: '#BFDBFE', dark: true }, { color: '#FCD34D', dark: true }, { color: '#F97316' }, { color: '#CBD5E1', dark: true }] }) });
    const collectionChart = U.card({ title: 'Tiến độ thu theo tòa', icon: 'trending-up', body: C.barLine({ groups: finB }) });
    const chart = m.chart === 'collection' ? collectionChart : m.chart === 'none' ? '' : occupancyChart;
    const viewSwitch = role === 'admin' ? `<div class="dashboard-view-switch"><button type="button" data-act="view-work" class="${dashboardView === 'work' ? 'on' : ''}">${I('square-check')} Công việc</button><button type="button" data-act="view-exec" class="${dashboardView === 'exec' ? 'on' : ''}">${I('bar-chart-2')} Điều hành</button></div>` : '';
    const vacancy = Q.vacancy(scope), revenue = Q.revenueSplit(scope);
    const wbBlocks = `${U.section('Phòng trống ' + U.assume())}<div class="focus-kpis wb-kpi-grid" data-guide="dash-kpi">${wbMetric('occupancy.rate', 'Trống có thể ở ngay', vacancy.immediate.length, 'Có thể ở ngay trong tháng', 'door', 'green', '#/rooms?vac=immediate')}${wbMetric('vacancy.days', 'Trống cuối tháng', vacancy.endOfMonth.length, 'Dự kiến trống cuối kỳ', 'calendar', 'blue', '#/rooms?vac=endOfMonth')}${wbMetric('vacancy.days', 'Trống chờ xử lý', vacancy.waiting.length, 'Giữ chỗ hoặc chờ dọn', 'clock', 'amber', '#/rooms?vac=waiting')}</div>${U.section('Thu trong kỳ')}<div class="focus-kpis wb-kpi-grid">${wbMetric('revenue.rent', 'Doanh thu tiền thuê', F.short(revenue.rent), 'Tiền nhà đã phát hành', 'receipt', 'blue', '#/receivables')}${wbMetric('revenue.newDeposit', 'Tiền cọc mới', F.short(revenue.newDeposit), 'Dòng tiền vào, không phải doanh thu', 'piggy', 'green', '#/finance/deposits?tab=deposit')}${wbMetric('revenue.penalty', 'Phạt / khấu trừ', F.short(revenue.penalty), 'Khoản phạt/khấu trừ', 'alert-triangle', 'purple', '#/refunds?reason=break')}</div>`;
    const fk = Q.financeKpis(period, scope); const ms = Q.milestones();
    const kpiFinance = `${U.section('Tài chính (§4.1 – 10 chỉ tiêu)')}<div class="focus-kpis wb-kpi-grid" data-guide="dash-finance">${metric('Tổng phải thu', F.short(fk.receivable), fk.count + ' hóa đơn ' + F.periodShort(period), 'receipt', 'blue', '#/receivables?period=' + period)}${metric('Đã thu', F.short(fk.collected), fk.pct + '% phải thu', 'check-circle', 'green', '#/receivables?period=' + period + '&pay=paid')}${metric('Còn phải thu', F.short(fk.remaining), 'chưa thu trong kỳ', 'clock', 'amber', '#/receivables?period=' + period)}${metric('Quá hạn', F.short(fk.overdue), fk.overdueCount + ' hóa đơn', 'alert-circle', 'red', '#/receivables?overdue=1&period=' + period)}${metric('Thu M1', F.short(fk.M1), 'đến ngày ' + F.pad((ms[0] || {}).day || 5), 'calendar-check', 'green', '#/receivables?period=' + period + '&milestone=M1')}${metric('Thu M2', F.short(fk.M2), 'đến ngày ' + F.pad((ms[1] || {}).day || 10), 'calendar-check', 'blue', '#/receivables?period=' + period + '&milestone=M2')}${metric('Thu M3', F.short(fk.M3), 'đến ngày ' + F.pad((ms[2] || {}).day || 15) + ' · sau mốc ' + F.short(fk.LATE), 'calendar-check', 'amber', '#/receivables?period=' + period + '&milestone=M3')}${metric('Thu thừa / tạm ứng', F.short(fk.overpaid), 'chưa phân bổ', 'bookmark', 'purple', '#/receivables?period=' + period + '&pay=overpaid')}${metric('Cọc đang giữ', F.short(fk.depositHolding), 'Deposit Ledger', 'piggy', 'teal', '#/finance/deposits')}${metric('Cọc chờ hoàn', F.short(fk.depositPendingRefund), 'HĐ kết thúc còn giữ cọc', 'hand-coins', 'orange', '#/refunds?status=processing')}</div>`;
    const rk = Q.roomKpis(m.rooms); const ck = Q.contractKpis(St.where('contracts', c => m.rooms.some(r => r.id === c.roomId)));
    const kpiRooms = `${U.section('Phòng (§4.1)')}<div class="focus-kpis wb-kpi-grid">${metric('Tổng tòa', rk.buildings, 'trong phạm vi', 'building', 'blue', '#/buildings')}${metric('Tổng phòng', rk.total, rk.inactive + ' ngừng khai thác', 'door', 'blue', '#/rooms')}${metric('Đang thuê', rk.occupied, 'HĐ hiệu lực', 'user-check', 'green', '#/rooms?status=occupied')}${metric('Sẵn sàng', rk.ready, 'cho thuê ngay', 'check-circle', 'green', '#/rooms?status=ready')}${metric('Giữ chỗ', rk.held, 'đang giữ', 'clock', 'amber', '#/rooms?status=held')}${metric('Chờ dọn', rk.cleaning, 'chờ nghiệm thu', 'brush', 'orange', '#/rooms?status=cleaning')}${metric('Bảo trì', rk.maintenance, 'đang sửa', 'wrench', 'red', '#/rooms?status=maintenance')}${metric('Sắp trống', rk.vacating, 'đã xác nhận trả', 'log-out', 'purple', '#/rooms?status=vacating')}${metric('Tỷ lệ lấp đầy', rk.occupancy + '%', '(đang thuê + sắp trống) / khai thác', 'trending-up', 'teal', '#/rooms')}</div>
      ${U.section('Hợp đồng (§4.1)')}<div class="focus-kpis wb-kpi-grid">${metric('Hiệu lực', ck.active, 'gồm sắp hết hạn', 'file-text', 'green', '#/contracts?status=active')}${metric('Sắp hết hạn', ck.expiring, '≤ 35 ngày', 'clock', 'amber', '#/contracts/expiring')}${metric('Còn ≤ 35 ngày', ck.within35, 'Work Queue', 'calendar', 'amber', '#/contracts/expiring')}${metric('Chờ gia hạn', ck.pending_renewal, 'HĐ mới dự thảo', 'refresh', 'purple', '#/contracts?status=pending_renewal')}${metric('Chờ kết thúc', ck.pending_end, 'đã xác nhận trả', 'log-out', 'orange', '#/contracts?status=pending_end')}${metric('Chờ quyết toán', ck.pending_settlement, 'hoàn cọc / hóa đơn cuối', 'x-circle', 'red', '#/contracts?status=pending_settlement')}${metric('Phá HĐ trong kỳ', ck.breach, 'kết thúc do vi phạm ' + F.periodShort(period), 'alert-triangle', 'red', '#/contracts?status=ended')}${metric('Chờ duyệt', ck.pending_approval, 'gửi duyệt', 'send', 'blue', '#/contracts?status=pending_approval')}</div>`;
    const dashboardBody = role === 'admin' && dashboardView === 'exec' ? `${wbBlocks}<div class="grid grid-1 dashboard-exec">${collectionChart}</div>` : `<div class="focus-kpis" data-guide="dash-kpi">${m.kpis.join('')}</div>${['admin', 'ops', 'qltong', 'tpvh'].includes(role) ? kpiRooms : ''}${['admin', 'accountant', 'qltong', 'tpvh'].includes(role) ? kpiFinance : ''}<div class="dashboard-focus ${chart ? '' : 'single'}">${U.card({ title: 'Việc cần xử lý', icon: 'square-check', sub: 'Sắp xếp theo mức độ ưu tiên', body: `<div class="work-list">${m.queue.map(queueRow).join('') || U.empty({ title: 'Không có việc tồn đọng', text: 'Mọi công việc quan trọng đã được xử lý.' })}</div>` })}${chart}</div>`;
    TH.router.crumb([{ label: m.title }]);
    root.innerHTML = `${U.pageHead({ title: m.title, sub: m.subtitle, acts: role === 'admin' ? [U.btn({ label: 'Xuất báo cáo', icon: 'download', cls: 'btn-outline', act: 'export' })] : [] })}
      <div class="dashboard-context-row">${viewSwitch}${contextualFilter}</div>${scopeNote}${dashboardBody}`;
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { 'view-work': () => { TH.router.replaceQuery(Object.assign({}, f, { view: 'work' })); TH.router.refresh(); }, 'view-exec': () => { TH.router.replaceQuery(Object.assign({}, f, { view: 'exec' })); TH.router.refresh(); }, export: () => { const rows = buildings.map(b => { const s = Q.roomStats(Q.roomsOf(b.id)), x = Q.finance(period, { buildingId: b.id }); return [b.code, b.name, Q.buildingManagerName(b.id, scope.date), (Q.buildingUnit(b.id, scope.date) || {}).name || '', s.total, s.occupied, s.ready, x.receivable, x.collected, x.remaining]; }); F.download('tong-quan-' + period + '.csv', F.csv(rows, ['Mã tòa', 'Tòa', 'Quản lý (tại kỳ)', 'Đơn vị', 'Tổng phòng', 'Đang thuê', 'Sẵn sàng', 'Phải thu', 'Đã thu', 'Còn nợ']), 'text/csv'); U.toast('ok', 'Đã xuất báo cáo tổng quan'); } });
    U.bindMetricInfo(root);
  }, { menu: 'dashboard', permission: 'dashboard.view' });
})(window.TH);
