/* UI-26 Kho tài liệu (tra cứu, tải lên, phiên bản) · UI-08 mở rộng: màn rà soát OCR hợp đồng (E05 sai/thiếu → không áp dụng; E06 đã rà → áp dụng biểu phí). */
(function (TH) {
  const S = TH.store, F = TH.f, U = TH.ui, K = TH.kit, Q = TH.q, X = TH.actions, esc = F.esc;
  const tLabel = (k) => ((Q.DOC_TYPES.find(x => x[0] === k) || [])[1]) || k;
  /* E1: danh sách tài liệu được tải (không cần quyền xem kho) – dùng ở chi tiết giao dịch (sale) và sổ sửa chữa (kỹ thuật) */
  TH.pages.docDownloadList = (docs) => docs.length ? docs.map(d => `<div class="mini-row"><span>${U.chip(tLabel(d.type), 'gray')} ${esc(d.name)} <span class="muted small">v${d.version || 1}</span></span>${U.actBtn({ icon: 'download', label: 'Tải xuống', act: 'docdl', attrs: { 'data-id': d.id } })}</div>`).join('') : '<p class="small muted">Chưa có tài liệu được phép tải</p>';
  TH.pages.docDownload = async (id) => { const d = K.act(() => X.downloadDocument(id)); if (!d) return; if (d.blobId) { try { await TH.intakeFiles.download(d.blobId); U.toast('ok', 'Đã tải ' + d.name); } catch (e) { U.toast('err', e.message); } } else U.toast('info', d.name + ' là bản ghi demo cũ, không có file gốc trong trình duyệt.'); };
  TH.router.handle('/documents', (root, p, q) => {
    let rows = Q.documentsScoped().filter(d => q.all ? true : d.status === 'current');
    const allCur = rows;
    if (q.type) rows = rows.filter(d => d.type === q.type);
    if (q.building) rows = rows.filter(d => d.buildingId === q.building);
    if (q.obj) rows = rows.filter(d => d.objectType === q.obj);
    if (q.q) rows = rows.filter(d => K.match(q.q, d.name, d.code, (Q.building(d.buildingId) || {}).code, Q.roomCode(d.roomId)));
    rows.sort((a, b) => String(b.uploadedAt).localeCompare(String(a.uploadedAt)));
    const soon = allCur.filter(d => d.validTo && d.validTo >= F.today() && d.validTo <= F.addDays(F.today(), 60));
    root.innerHTML = U.pageHead({ title: 'Kho tài liệu', sub: 'Sổ đỏ, PCCC, HĐ chủ nhà, HĐ khách, phụ lục, biên bản bàn giao, chứng từ, ảnh chỉ số, tài sản · sửa = tải phiên bản mới · tài liệu gắn giao dịch không xóa · chỉ thấy tòa được giao (CH-03)', acts: [U.btn({ label: 'Tải lên', icon: 'upload', cls: 'btn-primary', act: 'up', perm: 'documents.upload' })] })
      + `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tài liệu hiện hành', value: allCur.length, icon: 'folder', tone: 'blue' })}${U.kpi({ label: 'HĐ khách', value: allCur.filter(d => d.type === 'tenant_contract').length, cap: 'từ file hợp đồng của lượt thuê', icon: 'file-text', tone: 'green' })}
        ${U.kpi({ label: 'HĐ chủ nhà', value: allCur.filter(d => d.type === 'owner_contract').length, icon: 'landmark', tone: 'purple' })}${U.kpi({ label: 'Sắp hết hiệu lực (60 ngày)', value: soon.length, icon: 'calendar-clock', tone: soon.length ? 'amber' : 'gray' })}</div>`
      + K.filters([{ name: 'q', type: 'search', label: 'Tìm', placeholder: 'Tên file, mã, tòa, phòng' }, { name: 'type', label: 'Loại', options: Q.DOC_TYPES }, { name: 'building', label: 'Tòa', options: K.buildingOpts() }, { name: 'obj', label: 'Gắn với', options: Object.entries(Q.OBJ_TYPES) }, { name: 'all', label: 'Phiên bản', options: [['1', 'Gồm cả bản cũ']] }], q)
      + '<div class="mt16">' + K.tableCard('t', rows.length + ' tài liệu') + '</div>';
    K.bindFilters(root);
    U.table(root.querySelector('#t'), { rows, pageSize: 25, cols: [
      { key: 'n', label: 'Tài liệu', render: d => U.cell2(`<b>${esc(d.name)}</b>`, esc(d.code || 'HĐ lượt thuê') + ' · ' + Math.round((d.size || 0) / 1024) + ' KB') }, { key: 't', label: 'Loại', render: d => U.chip(tLabel(d.type), d.type === 'tenant_contract' ? 'green' : d.type === 'owner_contract' ? 'purple' : 'gray') },
      { key: 'o', label: 'Gắn với', render: d => { const h = Q.docObjectHref(d); const lbl = (Q.OBJ_TYPES[d.objectType] || '') + (d.objectType === 'stay' ? ' ' + ((Q.stay(d.objectId) || {}).code || '') : ''); return h ? `<a href="${h}">${esc(lbl)}</a>` : esc(lbl); } },
      { key: 'b', label: 'Tòa / phòng', render: d => `<span class="code">${esc((Q.building(d.buildingId) || {}).code || '')}${d.roomId ? ' · ' + esc(Q.roomCode(d.roomId)) : ''}</span>` }, { key: 'v', label: 'Phiên bản', num: true, render: d => 'v' + (d.version || 1) + (d.status === 'superseded' ? ' ' + U.chip('bản cũ', 'gray') : '') },
      { key: 'h', label: 'Hiệu lực đến', render: d => d.validTo ? F.date(d.validTo) : '–' }, { key: 'u', label: 'Tải lên', render: d => U.cell2(esc(d.uploadedBy || ''), F.date(String(d.uploadedAt || '').slice(0, 10))) },
      { key: 'q', label: 'Quyền xem / tải', render: d => `<span class="small muted">${esc(['owner_contract', 'red_book', 'pccc'].includes(d.type) ? 'Admin · kế toán · QL/leader/TP trong phạm vi tòa' : 'Vai trò có quyền tài liệu, trong phạm vi tòa')}</span>` },
      { key: 'dl', label: '', render: d => U.actBtn({ icon: 'download', label: 'Tải xuống', act: 'dl', attrs: { 'data-id': d.id } }) + (d.source === 'contractFile' && TH.ms.on('2') ? ' ' + U.chip((Q.OCR_ST[d.ocrStatus] || Q.OCR_ST.uploaded)[0], (Q.OCR_ST[d.ocrStatus] || Q.OCR_ST.uploaded)[1]) : '') },
      { key: 'actions', label: '', render: d => d.source === 'contractFile' ? (TH.auth.can('ocr.review') && TH.ms.on('2') ? U.actBtn({ icon: 'eye', label: 'Rà soát OCR', act: 'ocr', attrs: { 'data-id': d.fileId } }) : '') : U.rowActions([d.prevId || d.status === 'superseded' ? U.actBtn({ icon: 'history', label: 'Các phiên bản', act: 'ver', attrs: { 'data-id': d.id } }) : '', d.status === 'current' ? U.actBtn({ icon: 'upload', label: 'Tải phiên bản mới', act: 'newv', attrs: { 'data-id': d.id }, perm: 'documents.upload' }) : '', d.status === 'current' ? U.actBtn({ icon: 'trash', label: 'Xóa', act: 'del', attrs: { 'data-id': d.id }, perm: 'documents.upload', tone: 'red' }) : ''].filter(Boolean)) }] });
    U.bind(root, {
      up: () => K.formDrawer({ title: 'Tải tài liệu lên', wide: true, fields: [{ name: 'type', label: 'Loại', type: 'select', options: Q.DOC_TYPES.filter(x => x[0] !== 'tenant_contract'), req: true }, { name: 'buildingId', label: 'Tòa', type: 'select', options: K.buildingOpts(), req: true },
        { name: 'objectType', label: 'Gắn với', type: 'select', options: Object.entries(Q.OBJ_TYPES).filter(([k]) => ['building', 'room', 'stay', 'ownerContract', 'payment', 'expense'].includes(k)), value: 'building' }, { name: 'ref', label: 'Mã phòng / mã khách / mã phiếu thu / mã chứng từ chi', placeholder: 'vd 202G13, KH-202G13A001, PT-202609-0001, CP-202609-001', help: 'Bắt buộc khi gắn Phòng, Lượt thuê / khách, Phiếu thu hoặc Chứng từ chi (Lượt thuê: mã khách hoặc mã phòng đang ở)' }, { name: 'name', label: 'Tên file', req: true, placeholder: 'vd Bien-ban-ban-giao.pdf' }, { name: 'validTo', label: 'Hiệu lực đến', type: 'date' }, { name: 'note', label: 'Ghi chú', span: true }],
        note: U.note('info', '', 'HĐ khách tải ở tab Hợp đồng của lượt thuê (UI-07) – hiện ở đây kèm phiên OCR.'), submit: 'Tải lên', onSubmit: (x) => { const oc = x.objectType === 'ownerContract' ? S.one('ownerContracts', c => c.buildingId === x.buildingId) : null; const ref = String(x.ref || '').trim().toUpperCase(); const bc = (Q.building(x.buildingId) || {}).code || '';
          const room = x.objectType === 'room' ? (Q.room('r_' + ref) || Q.room('r_' + ref + bc)) : null; const ex = x.objectType === 'expense' ? S.one('expenses', e => e.code.toUpperCase() === ref) : null;
          const st = x.objectType === 'stay' ? (S.one('stays', s => s.customerId.toUpperCase() === ref || String(s.code).toUpperCase() === ref) || Q.currentStay((Q.room('r_' + ref) || Q.room('r_' + ref + bc) || {}).id)) : null;
          const py = x.objectType === 'payment' ? S.one('payments', y => String(y.code).toUpperCase() === ref) : null;
          X.uploadDocument(Object.assign({}, x, { objectId: oc ? oc.id : ex ? ex.id : st ? st.id : py ? py.id : ['stay', 'payment'].includes(x.objectType) ? null : x.buildingId, roomId: room ? room.id : null, size: 350000 })); U.toast('ok', 'Đã tải lên'); } }),
      newv: (el) => { const d = S.get('documents', el.dataset.id); K.formDrawer({ title: 'Phiên bản mới – ' + esc(d.name), modal: true, fields: [{ name: 'name', label: 'Tên file', value: d.name, req: true }, { name: 'validTo', label: 'Hiệu lực đến', type: 'date', value: d.validTo || '' }, { name: 'note', label: 'Nội dung thay đổi', span: true }], submit: 'Tải phiên bản ' + ((d.version || 1) + 1), onSubmit: (x) => { X.uploadDocument(Object.assign({}, x, { replaceId: d.id, size: d.size })); U.toast('ok', 'Đã tạo phiên bản mới'); } }); },
      ver: (el) => { const vs = Q.docVersions(el.dataset.id); U.drawer({ title: 'Các phiên bản', body: U.timeline(vs.map(v => ({ when: F.date(String(v.uploadedAt).slice(0, 10)), title: 'v' + v.version + ' · ' + v.name, sub: esc((v.uploadedBy || '') + (v.note ? ' · ' + v.note : '')), color: v.status === 'current' ? 'green' : 'gray' }))) }); },
      del: (el) => K.formDrawer({ title: 'Xóa tài liệu', modal: true, note: U.note('warn', '', 'Tài liệu gắn HĐ chủ nhà / lượt thuê / hóa đơn / phiếu thu / phiếu hoàn / chứng từ chi không xóa được – chỉ tải phiên bản mới.'), fields: [{ name: 'reason', label: 'Lý do', req: true, span: true }], submit: 'Xóa', onSubmit: (x) => { X.deleteDocument(el.dataset.id, x.reason); U.toast('ok', 'Đã xóa'); } }),
      dl: (el) => TH.pages.docDownload(el.dataset.id),
      ocr: async (el) => {const f=S.get('contractFiles',el.dataset.id);try{await TH.intakeFiles.startStay(f.stayId,f.blobId);}catch(e){U.toast('err',e.message);} },
    });
  });

  /* ---------- UI-08: rà soát OCR ---------- */
  const conf = (c) => U.chip(Math.round(c * 100) + '%', c >= 0.9 ? 'green' : c >= 0.7 ? 'amber' : 'red');
  TH.router.handle('/ocr/:id', (root, p) => {
    const o = Q.ocrSession(p.id); if (!o) { root.innerHTML = U.card({ body: U.empty({ title: 'Không tìm thấy phiên OCR' }) }); return; }
    const s = Q.stay(o.stayId); if (!TH.auth.inScope(s.buildingId)) { root.innerHTML = U.card({ body: U.empty({ icon: 'lock', title: 'Lượt thuê ngoài phạm vi được giao' }) }); return; }
    const f = S.get('contractFiles', o.fileId) || {}; const ready = Q.ocrReady(o); const open = o.status === 'review';
    TH.layout.crumb([{ label: 'Lượt thuê ' + s.code, href: '#/stays/' + s.id + '?tab=hop-dong' }, { label: 'OCR phiên ' + o.run }]);
    const ST = Q.OCR_ST;
    root.innerHTML = U.pageHead({ title: 'Rà soát OCR hợp đồng ' + U.chip(ST[o.status][0], ST[o.status][1], true), back: '#/stays/' + s.id + '?tab=hop-dong', sub: `${esc(f.name || '')} · phiên ${o.run} · ${esc(Q.stayLabel(s))} · OCR không ghi thẳng vào hóa đơn`,
      acts: [U.btn({ label: 'Chạy lại OCR', icon: 'refresh', act: 'rerun', perm: 'ocr.review' }), open ? U.btn({ label: 'Áp dụng vào biểu phí', icon: 'check-circle', cls: ready.ok ? 'btn-primary' : 'btn-ghost', act: 'apply', perm: 'rates.manage' }) : ''] })
      + U.wizard([{ title: 'Tải file', sub: 'xong' }, { title: 'Trích xuất', sub: o.status === 'error' ? 'lỗi' : 'xong' }, { title: 'Rà soát', sub: Object.keys(o.confirmed).length + '/' + Q.OCR_GROUPS.length + ' nhóm' }, { title: 'Áp dụng biểu phí', sub: o.status === 'applied' ? F.datetime(o.appliedAt) : '' }], o.status === 'applied' ? 4 : o.status === 'error' ? 1 : ready.ok ? 3 : 2)
      + (o.status === 'error' ? U.note('danger', 'Không đọc được', esc(o.error) + ' – file vẫn được lưu nhưng biểu phí không kích hoạt; nhập tay ở tab Biểu phí kèm bằng chứng.') : '')
      + (open && !ready.ok ? U.note('warn', 'Chưa áp dụng được (E05)', [...ready.req.map(x => 'Thiếu ' + x), ...ready.missing.map(x => 'Chưa rà nhóm "' + x + '"')].map(esc).join(' · ')) : '')
      + (o.status === 'superseded' ? U.note('warn', 'Phiên đã được thay', 'Đã chạy lại OCR – mở phiên mới nhất để rà soát và áp dụng; phiên này chỉ để xem lại.') : '')
      + (o.status === 'applied' ? U.note('ok', 'Đã áp dụng (E06)', `Phiên biểu phí mới do ${esc(o.appliedBy)} áp dụng ${F.datetime(o.appliedAt)} – ${o.edited.length} trường đã sửa so với bản OCR gốc. Hóa đơn đã phát hành không đổi.`) : '')
      + `<div class="two-col"><div>${U.card({ title: 'Bản gốc (mô phỏng)', icon: 'file-text', body: `<div class="ocr-doc">${[1, 2, 3].map(pg => `<div class="ocr-page"><div class="small muted">Trang ${pg}/${o.pages}</div>${o.fields.filter(x => x.page === pg).map(x => `<div class="ocr-line ${x.confidence < 0.7 ? 'low' : ''}"><span class="muted">${esc(x.region)}:</span> ${esc(x.label)} … <b>${esc(String(x.raw === '' ? '▯▯▯' : x.raw))}</b></div>`).join('')}</div>`).join('')}</div>` })}</div>
      <div class="side-stack">${Q.OCR_GROUPS.map(([g, gl]) => { const done = o.confirmed[g]; const fs = o.fields.filter(x => x.group === g);
        return U.card({ title: gl, icon: done ? 'check-circle' : 'list', sub: done ? 'Đã rà – ' + esc(done.by) : '', actions: open && !done ? U.btn({ label: 'Xác nhận nhóm', size: 'btn-xs', act: 'conf', attrs: { 'data-g': g } }) : '',
          bodyCls: 'flush', body: `<div class="tbl-wrap"><table class="tbl compact ocr-tbl"><thead><tr><th>Trường</th><th>Giá trị</th><th class="num">Tin cậy</th></tr></thead><tbody>${fs.map(x => `<tr><td>${esc(x.label)}${Q.OCR_REQUIRED.includes(x.key) ? ' <span class="red">*</span>' : ''}<small class="d-block muted">tr.${x.page} · ${esc(x.region)}</small></td>
            <td>${open ? `<input class="inp sm" data-k="${x.key}" value="${esc(String(x.value))}">` : esc(String(x.value))}${x.edited ? ' ' + U.chip('đã sửa', 'blue') : ''}</td><td class="num">${conf(x.confidence)}</td></tr>`).join('')}</tbody></table></div>` }); }).join('')}</div></div>`;
    /* E06: so sánh giá đang áp dụng với bản OCR trước khi áp */
    const cmp = () => { const cur = Q.rateOf(o.stayId) || { items: {} }; const rows = [['Giá thuê / tháng', cur.rent, (o.fields.find(x => x.key === 'rent') || {}).value], ...o.fields.filter(x => x.key.startsWith('fee_')).map(x => [x.label, ((cur.items || {})[x.key.slice(4)] || {}).unit, x.value])];
      const tv = (k, v) => v == null || v === '' ? '–' : /Date$/.test(k) ? F.date(v) : k === 'deposit' ? F.vnd(v) : esc(String(v));
      return '<table class="tbl compact"><thead><tr><th>Khoản</th><th class="num">Đang áp dụng</th><th class="num">Theo OCR</th></tr></thead><tbody>' + rows.map(([l, a, b]) => { const nb = Q.ocrValue('rent', b); const n = nb === '' || nb == null ? null : nb; return `<tr><td>${esc(l)}</td><td class="num">${a != null ? F.vnd(a) : '–'}</td><td class="num">${n != null ? `<b class="${n !== Number(a || 0) ? 'amber' : ''}">${F.vnd(n)}</b>` : '–'}</td></tr>`; }).join('')
        + Q.ocrTermsCompare(o).map(t => `<tr><td>${esc(t.label)}${t.locked ? ' <span class="small muted">(đã có HĐ phát hành – không đổi)</span>' : ''}</td><td class="num">${tv(t.key, t.cur)}</td><td class="num">${t.next != null && String(t.next) !== String(t.cur ?? '') ? `<b class="${t.locked ? 'muted' : 'amber'}">${tv(t.key, t.next)}</b>` : tv(t.key, t.next)}</td></tr>`).join('') + '</tbody></table>'; };
    root.querySelectorAll('input[data-k]').forEach(inp => inp.addEventListener('change', () => K.act(() => X.ocrSetField(o.id, inp.dataset.k, inp.value))));
    U.bind(root, {
      conf: (el) => { const g = el.dataset.g; const iss = Q.ocrGroupIssues(o, g, false); if (iss.length && iss.every(x => /độ tin cậy/.test(x))) { U.confirm({ title: 'Trường độ tin cậy thấp', text: iss.join(' · ') + '. Xác nhận đã đối chiếu với bản gốc?', ok: 'Đã đối chiếu – xác nhận' }).then(ok => { if (ok) K.act(() => X.ocrConfirmGroup(o.id, g, true), 'Đã xác nhận nhóm'); }); } else K.act(() => X.ocrConfirmGroup(o.id, g), 'Đã xác nhận nhóm'); },
      rerun: () => { const n = K.act(() => X.runOcr(o.fileId)); if (n) TH.go('#/ocr/' + n.id); },
      apply: () => K.formDrawer({ title: 'Áp dụng OCR vào biểu phí', modal: true, note: U.note('info', '', 'Tạo phiên biểu phí mới có ngày hiệu lực (UI-09). Chỉ áp cho hóa đơn chưa phát hành từ ngày này; hóa đơn đã phát hành không đổi.') + '<div class="mt8"><b class="small">So sánh giá cũ / mới (E06)</b>' + cmp() + '</div>',
        fields: [{ name: 'from', label: 'Hiệu lực từ', type: 'date', value: TH.calc.dates.periodStart(TH.calc.dates.nextPeriod(S.meta.period)), req: true }, { name: 'reason', label: 'Ghi chú', span: true }], submit: 'Áp dụng', onSubmit: (x) => { const r = X.ocrApply(o.id, x); U.toast('ok', 'Đã áp dụng biểu phí và điều khoản HĐ từ OCR', [r.warnIssued && r.warnIssued.length ? 'Đã có hóa đơn phát hành kỳ ' + r.warnIssued.join(', ') + ' – không đổi, điều chỉnh riêng nếu cần' : '', r.terms && r.terms.skipped.length ? 'Ngày ký / nhận / tính tiền không đổi vì đã có hóa đơn phát hành' : '', r.depositWarn ? 'Cọc theo HĐ ' + F.vnd(r.depositWarn.contract) + ' khác số đã thu ' + F.vnd(r.depositWarn.held) + ' – kiểm tra sổ cọc' : ''].filter(Boolean).join(' · ')); } }),
    });
  });
})(window.TH);
