(function (TH) {
  const S = TH.store, Q = TH.q, F = TH.f, U = TH.ui, K = TH.kit, esc = F.esc;
  TH.router.handle('/reports/efficiency', (root, p, q) => {
    const period = q.period || '2026-08', codong = TH.auth.role() === 'codong', hasExcel = (S.get('periods', period) || {}).source === 'excel_parallel', source = !codong && hasExcel && q.source === 'excel' ? 'excel' : 'web';
    const report = TH.qe.build(period, { basis: q.basis || 'business', source, group: q.group, area: q.area, manager: codong ? null : q.manager }), totals = report.totals.TOTAL;
    const ratio = (v, why) => v == null ? `<span class="muted"${why ? ` title="${esc(why)}"` : ''}>${esc(why || 'Chờ dữ liệu')}</span>` : F.pctv(v, 2);
    root.innerHTML = U.pageHead({ title: 'Hiệu quả vốn, tài sản & tiền nhà', sub: 'LN/vốn = LNR/GV (dòng 51); biên tiền nhà = DT tiền phòng / tiền thuê (dòng 59). LN/tài sản = LNR kinh doanh / giá trị còn lại tài sản công ty – chỉ tòa đã có số dư tài sản nền (UI-37 / đầu tư ban đầu UI-33).', acts: [U.btn({ label: 'Xuất Excel', act: 'exp', icon: 'download' })] })
      + K.filters([{ name: 'period', label: 'Kỳ', options: K.periodOpts(), value: period, all: false }, { name: 'basis', label: 'Báo cáo cơ sở', options: [['business', 'Kinh doanh'], ['total', 'Tổng (dòng tiền)']], value: 'business', all: false }, ...(codong ? [] : [{ name: 'source', label: 'Nguồn', options: [['web', 'Theo web'], ...(hasExcel ? [['excel', 'Như Excel']] : [])], value: 'web', all: false }]), { name: 'group', label: 'Nhóm', options: K.groupOpts() }, { name: 'area', label: 'Khu vực', options: K.areaOpts() }, ...(codong ? [] : [{ name: 'manager', label: 'Trưởng phòng', options: Q.teamLeaders(TH.calc.dates.periodEnd(period)).filter(e => e.title === 'TPVH').map(e => [e.id, e.name]) }])], q)
      + U.note('warn', 'Công thức hiệu quả là phương án OQ-24', 'Số chính thức dùng Báo cáo kinh doanh theo Excel. LN/tài sản chỉ hiển thị khi mọi tài sản trong mẫu số có chính sách khấu hao đã xác nhận.')
      + '<div class="grid grid-3 mt16 mb16">' + U.kpi({ label: 'LN / vốn', value: ratio(totals.profitOnCapital), icon: 'trending-up', tone: 'blue' }) + U.kpi({ label: 'LN / tài sản', value: ratio(totals.profitOnAssets, totals.covered ? '' : 'Chờ chính sách tài sản'), cap: totals.covered + '/' + totals.total + ' tòa đủ chính sách tài sản · LNR kinh doanh', icon: 'package', tone: 'teal' }) + U.kpi({ label: 'Biên tiền nhà', value: totals.rentMargin == null ? 'Chờ dữ liệu' : F.dec(totals.rentMargin, 5) + ' lần', icon: 'building', tone: 'purple' }) + '</div>'
      + K.tableCard('etable', 'Hiệu quả theo tòa') + '<div class="mt16">' + U.card({ title: 'Tổng theo nhóm', body: `<table class="tbl compact"><thead><tr><th>Nhóm</th><th>LN/vốn</th><th>LN/tài sản</th><th>Biên tiền nhà</th><th class="num">Giá trị TS</th></tr></thead><tbody>${['T', 'S', 'G', 'TOTAL'].map(g => { const t = report.totals[g]; return `<tr><td>${g === 'TOTAL' ? 'TỔNG' : g}</td><td>${ratio(t.profitOnCapital)}</td><td>${ratio(t.profitOnAssets)}</td><td>${t.rentMargin == null ? 'Chờ dữ liệu' : F.dec(t.rentMargin, 5)}</td><td class="num">${F.vnd(t.nbv)}</td></tr>`; }).join('')}</tbody></table>` }) + '</div>';
    if (!codong && q.source === 'excel' && !hasExcel) root.insertAdjacentHTML('afterbegin', U.note('info', 'Chưa có benchmark Excel kỳ này', 'Đang hiển thị số web. Chọn kỳ song song Excel để đối chiếu.'));
    K.bindFilters(root, ['basis', 'source']);
    U.table(root.querySelector('#etable'), { rows: report.rows, pageSize: 20, cols: [
      { key: 'b', label: 'Tòa / nhóm', render: r => TH.auth.can('reports.drill') ? U.link('#/reports/buildings?period=' + period + '&building=' + r.buildingId, r.code + ' · ' + r.group) : esc(r.code + ' · ' + r.group) },
      { key: 'area', label: 'Khu vực / TP', render: r => U.cell2(esc((S.get('areas', r.areaId) || {}).name || '–'), codong ? '' : esc((Q.emp(r.managerId) || {}).name || '–')) },
      ...[['rev_rent', 'DT phòng'], ['cost_rent', 'Tiền thuê/tháng'], ['lnr', 'LNR'], ['gv', 'GV']].map(([key, label]) => ({ key, label, num: true, render: r => F.vnd(r[key]) })),
      { key: 'margin', label: 'Biên tiền nhà', num: true, render: r => r.rentMargin == null ? 'Chờ dữ liệu' : F.dec(r.rentMargin, 5) }, { key: 'capital', label: 'LN/vốn', num: true, render: r => ratio(r.profitOnCapital) },
      { key: 'nbv', label: 'TS còn lại', num: true, render: r => TH.auth.can('assets.view') ? U.link('#/assets?building=' + r.buildingId + '&period=' + period, F.vnd(r.nbv)) : F.vnd(r.nbv) }, { key: 'assets', label: 'LN/tài sản', num: true, render: r => ratio(r.profitOnAssets, r.assetsPending) }] });
    K.wrapTables(root);
    U.bind(root, { exp: () => K.xls('hieu-qua-' + period + '.xls', 'HIỆU QUẢ', [period, ['Cách tính', report.basis + ' · ' + report.source], ['Trạng thái nghiệp vụ', 'Phương án OQ-24 · chờ khách xác nhận'], ['Phiên bản quy tắc', period + ' · OQ-24'], ['Nguồn', report.policyRef || 'OQ-24'], ['Phạm vi', TH.auth.buildingScope() ? 'Tòa của tài khoản' : 'Theo bộ lọc']], ['Tòa', 'Nhóm', 'DT phòng', 'Tiền thuê', 'Biên tiền nhà', 'LNR', 'GV', 'LN/vốn', 'TS còn lại', 'LN/tài sản'], report.rows.map(r => [r.code, r.group, r.rev_rent, r.cost_rent, r.rentMargin, r.lnr, r.gv, r.profitOnCapital, r.nbv, r.profitOnAssets == null ? 'Chờ chính sách – ' + r.assetsPending : r.profitOnAssets])) });
  });
})(window.TH);
