(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  TH.router.register('/expenses', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Chi phí' }]);
    const period = TH.router.periodOf(q);
    const f = { s: q.s || '', group: q.group || '', buildingId: q.buildingId || '', type: q.type || '', period, createdBy: q.createdBy || '' };
    const all = St.where('expenses', e => !f.period || F.period(e.date) === f.period);
    const rows = all.filter(e => (!f.s || F.norm(e.code + ' ' + e.desc + ' ' + (e.evidence || '')).includes(F.norm(f.s))) && (!f.group || e.group === f.group) && (!f.buildingId || e.buildingId === f.buildingId || (f.buildingId === 'common' && !e.buildingId)) && (!f.type || e.recordType === f.type) && (!f.createdBy || e.createdBy === f.createdBy)).sort((a, b) => F.cmp(b.date, a.date) || F.cmp(b.code, a.code));
    const tot = F.sum(all, e => e.amount), ops = F.sum(all.filter(e => e.recordType === 'ops'), e => e.amount), asset = F.sum(all.filter(e => e.recordType === 'asset'), e => e.amount), pend = F.sum(all.filter(e => e.status === 'pending_alloc'), e => e.amount);
    root.innerHTML = `${U.pageHead({ title: 'Chi phí', sub: 'Quản lý và theo dõi các khoản chi phí vận hành, mua sắm, sửa chữa và chi phí khác.', acts: [U.btn({ label: 'Thêm chi phí', icon: 'plus', cls: 'btn-primary', act: 'add', attrs: { 'data-guide': 'expense-add' } })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo mã, diễn giải, chứng từ...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Nhóm chi', input: U.select({ name: 'group', value: f.group, all: 'Tất cả nhóm chi', options: St.all('expenseGroups').map(g => g.name), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: [...(TH.auth.can('expenses.manageCommon') ? [['common', 'Chi phí chung']] : []), ...St.where('buildings', b => !b.stub).map(b => [b.id, b.name])], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại ghi nhận', input: U.select({ name: 'type', value: f.type, all: 'Tất cả', options: Object.entries(Q.L.recordType).filter(([k]) => k !== 'common' || TH.auth.can('expenses.manageCommon')), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Thời gian', input: U.select({ name: 'period', value: f.period, all: 'Tất cả', options: [...new Set(St.all('expenses').map(e => F.period(e.date)))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người tạo', input: U.select({ name: 'createdBy', value: f.createdBy, all: 'Tất cả', options: [...new Set(St.all('expenses').map(e => e.createdBy))].map(id => [id, Q.userName(id)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng chi tháng', value: F.vnd(tot), cap: 'So với tháng trước', icon: 'wallet', tone: 'green', delta: 12 })}${U.kpi({ label: 'Chi vận hành', value: F.vnd(ops), cap: F.pct(ops, tot) + '% tổng chi', icon: 'settings', tone: 'blue', delta: 8, deltaDir: 'down' })}${U.kpi({ label: 'Mua sắm tài sản', value: F.vnd(asset), cap: F.pct(asset, tot) + '% tổng chi', icon: 'package', tone: 'blue', delta: 15 })}${U.kpi({ label: 'Chờ phân bổ', value: F.vnd(pend), cap: F.pct(pend, tot) + '% tổng chi', icon: 'clock', tone: 'amber', delta: 25, deltaDir: 'down' })}</div>
    ${U.card({ title: `Danh sách chi phí <span class="muted" style="font-weight:400">(${rows.length} khoản)</span>`, actions: U.btn({ label: 'Xuất file', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export' }), body: null, id: 'tbl-card' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, selectable: true, unit: 'khoản', cols: [
      { key: 'code', label: 'Mã', sortable: true, render: e => `<b>${esc(e.code)}</b>` }, { key: 'date', label: 'Ngày', sortable: true, render: e => F.date(e.date) }, { key: 'group', label: 'Nhóm chi', render: e => U.chip(e.group, Q.L.expGroup[e.group] || 'gray') }, { key: 'desc', label: 'Diễn giải', render: e => esc(e.desc) },
      { key: 'b', label: 'Tòa', render: e => e.buildingId ? esc(Q.building(e.buildingId).name) : `<span class="muted">${e.status === 'pending_alloc' ? 'Chờ phân bổ' : 'Chung (đã phân bổ)'}</span>` }, { key: 'amount', label: 'Số tiền (VND)', num: true, sortable: true, render: e => F.vnd(e.amount) },
      { key: 'type', label: 'Loại ghi nhận', render: e => Q.L.recordType[e.recordType] + (e.method === 'depreciation' ? ' <span class="tag-p">KH</span>' : '') }, { key: 'ev', label: 'Chứng từ', render: e => e.evidence ? `<a class="link" data-act="dl" data-n="${esc(e.evidence)}">${I('file-text')} ${esc(e.evidence)}</a>` : '-' }, { key: 'by', label: 'Người tạo', render: e => esc(Q.userName(e.createdBy)) },
      { key: 'actions', label: 'Thao tác', render: e => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': e.id } }), U.moreBtn(e.id)]) }] });
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelector('.filterbar'))) });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') TH.router.applyFilter(f, { s: e.target.value }); });
    const view = (e) => { const allocs = St.where('expenseAllocations', a => a.expenseId === e.id); U.modal({ title: 'Chi phí ' + e.code, body: U.kv([['Ngày', F.date(e.date)], ['Nhóm chi', U.chip(e.group, Q.L.expGroup[e.group] || 'gray')], ['Diễn giải', esc(e.desc)], ['Số tiền', F.vnd(e.amount) + ' đ'], ['Tòa', e.buildingId ? esc(Q.building(e.buildingId).name) : 'Chi phí chung'], ['Loại', Q.L.recordType[e.recordType]], ['Phương thức', e.method === 'depreciation' ? (TH.phase.on(2) ? 'Khấu hao ' + (e.depreciationMonths || 36) + ' tháng (đường thẳng, OI-11)' : 'Khấu hao (P2)') : 'Tiền mặt'], ['Chứng từ', esc(e.evidence || '-')], ['Ghi chú', esc(e.note || '-')], ['Người tạo', esc(Q.userName(e.createdBy))]], 'one') + (allocs.length ? `<div class="mt12 small bold">Phân bổ theo tòa</div><table class="tbl compact mt8">${allocs.map(a => `<tr><td>${esc(Q.building(a.buildingId).name)}</td><td class="num">${a.pct}%</td><td class="num">${F.vnd(a.amount)}</td></tr>`).join('')}</table>` : ''), footer: U.btn({ label: 'Sửa', icon: 'pencil', cls: 'btn-outline', act: 'e' }) + U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'c' }), onMount: (m) => U.bind(m.el, { e: () => { m.close(); Fm.expense(e); }, c: () => m.close() }) }); };
    U.bind(root, { add: () => Fm.expense(), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => view(St.get('expenses', b.dataset.id)), dl: (b) => U.fakePdf(b.dataset.n, ['Chứng từ chi phí mô phỏng']), export: () => { F.download('chi-phi-' + (f.period || 'all') + '.csv', F.csv(rows.map(e => [e.code, e.date, e.group, e.desc, e.buildingId ? Q.building(e.buildingId).name : 'Chung', e.amount, Q.L.recordType[e.recordType], e.evidence || '', Q.userName(e.createdBy)]), ['Mã', 'Ngày', 'Nhóm', 'Diễn giải', 'Tòa', 'Số tiền', 'Loại', 'Chứng từ', 'Người tạo']), 'text/csv'); U.toast('ok', 'Đã xuất file'); },
      more: (b) => { const e = St.get('expenses', b.dataset.id); U.menu(b, [{ label: 'Xem', icon: 'eye', onClick: () => view(e) }, { label: 'Sửa', icon: 'pencil', onClick: () => Fm.expense(e) }, { label: 'Phân bổ theo tòa', icon: 'percent', disabled: !!e.buildingId, onClick: () => Fm.expense(e) }, '-', { label: 'Xóa', icon: 'trash', danger: true, disabled: e.source === 'seed', title: e.source === 'seed' ? 'Chỉ xóa chi phí tạo trong phiên demo' : '', onClick: async () => { if (await U.confirm({ title: 'Xóa chi phí ' + e.code + '?', ok: 'Xóa', danger: true })) { X.deleteExpense(e.id); U.toast('ok', 'Đã xóa'); } } }]); } });
  }, { menu: 'expenses', permission: 'expenses.view' });
})(window.TH);
