/* Phase 1 (spec v1.8 §4.11, §12.15) – Work Queue Hợp đồng sắp hết hạn: cột đầy đủ, ghi nhận liên hệ, kết quả Gia hạn / Trả đúng hạn / Chấm dứt sớm / Chưa phản hồi, assign người xử lý, export.
   Hệ thống chỉ tạo work queue – không tự gia hạn / tự kết thúc. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  TH.router.register('/contracts/expiring', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Hợp đồng sắp hết hạn' }]);
    const f = { days: q.days || '35', orgUnitId: q.orgUnitId || '', buildingId: q.buildingId || '', result: q.result || '', assigneeId: q.assigneeId || '', s: q.s || '' };
    const all = Q.expiringQueue({ days: Number(f.days), orgUnitId: f.orgUnitId, buildingId: f.buildingId });
    const rows = all.filter(x => (!f.result || (f.result === 'none' ? !x.result : x.result === f.result)) && (!f.assigneeId || x.assigneeId === f.assigneeId) && (!f.s || F.norm(x.c.code + ' ' + x.tenant.name + ' ' + x.tenant.phone + ' ' + x.room.code).includes(F.norm(f.s))));
    const cnt = (k) => all.filter(x => k === 'none' ? !x.result : x.result === k).length;
    const emps = St.rawAll('employees').filter(e => e && e.status !== 'resigned').sort((a, b) => F.cmp(a.name, b.name));
    root.innerHTML = `${U.pageHead({ title: 'Hợp đồng sắp hết hạn', sub: 'Work Queue theo ngày kết thúc (mặc định ≤ 35 ngày, §4.11). Liên hệ khách → chọn kết quả; Gia hạn tạo HĐ mới Dự thảo để review/duyệt; Trả phòng mở luồng kết thúc. Hệ thống không tự gia hạn/kết thúc.', acts: [U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
      <div class="grid grid-4 mb16">${U.kpi({ label: 'Sắp hết hạn', value: all.length, cap: '≤ ' + f.days + ' ngày', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Chưa liên hệ', value: cnt('none'), cap: 'cần gọi/nhắn', icon: 'phone', tone: 'red' })}${U.kpi({ label: 'Đồng ý gia hạn', value: cnt('renew'), cap: 'HĐ mới dự thảo', icon: 'refresh', tone: 'green' })}${U.kpi({ label: 'Trả phòng / chấm dứt', value: cnt('on_time') + cnt('early'), cap: 'chuẩn bị luồng kết thúc', icon: 'log-out', tone: 'purple' })}</div>
      ${U.statusTabs([{ key: '', label: 'Tất cả', count: all.length }, { key: 'none', label: 'Chưa liên hệ', count: cnt('none'), color: 'red' }, { key: 'contacted', label: 'Đã liên hệ', count: cnt('contacted'), color: 'teal' }, { key: 'no_response', label: 'Chưa phản hồi', count: cnt('no_response'), color: 'gray' }, { key: 'renew', label: 'Gia hạn', count: cnt('renew'), color: 'green' }, { key: 'on_time', label: 'Trả đúng hạn', count: cnt('on_time'), color: 'blue' }, { key: 'early', label: 'Chấm dứt sớm', count: cnt('early'), color: 'red' }], f.result)}
      ${U.filterbar([U.field({ label: 'Tìm', input: U.input({ name: 's', value: f.s, placeholder: 'HĐ, khách, SĐT, phòng…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Ngưỡng (ngày)', input: U.select({ name: 'days', value: f.days, options: [['15', '≤ 15 ngày'], ['35', '≤ 35 ngày (mặc định)'], ['60', '≤ 60 ngày'], ['90', '≤ 90 ngày']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tổ chức', input: U.select({ name: 'orgUnitId', value: f.orgUnitId, all: 'Tất cả', options: Q.orgOptions(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người xử lý', input: U.select({ name: 'assigneeId', value: f.assigneeId, all: 'Tất cả', options: emps.map(e => [e.id, e.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
      ${U.card({ title: `Work Queue <span class="muted" style="font-weight:400">(${rows.length})</span>`, body: null, id: 'tbl-card', attrs: 'data-guide="expiring-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, unit: 'hợp đồng', rowKey: x => x.c.id, densityControl: true, sortKey: 'days', cols: [
      { key: 'room', label: 'Tòa / phòng', render: x => U.cell2(U.link('#/rooms/' + x.room.id, esc(x.room.code), 'bold'), esc(x.building.name)) },
      { key: 'tenant', label: 'Khách / SĐT', render: x => U.cell2(U.link('#/tenants/' + x.tenant.id, esc(x.tenant.name)), esc(x.tenant.phone || '')) },
      { key: 'cohab', label: 'Người ở cùng', render: x => x.cohabitants.length ? x.cohabitants.map(m => esc(m.name)).join('<br>') : '<span class="muted">-</span>' },
      { key: 'mgr', label: 'Quản lý', render: x => esc(x.manager.name || Q.buildingManagerName(x.c.buildingId)) },
      { key: 'term', label: 'Bắt đầu – kết thúc', sortable: true, sortVal: x => x.c.end, render: x => U.cell2(U.link('#/contracts/' + x.c.id, esc(x.c.code)), F.date(x.c.start) + ' – ' + F.date(x.c.end)) },
      { key: 'days', label: 'Còn lại', num: true, sortable: true, sortVal: x => x.daysLeft, render: x => `<b class="${x.daysLeft <= 7 ? 'red' : x.daysLeft <= 15 ? 'amber' : ''}">${x.daysLeft} ngày</b>` },
      { key: 'price', label: 'Giá / cọc', num: true, render: x => U.cell2(F.vnd(x.c.price), 'cọc ' + F.vnd(x.c.deposit)) },
      { key: 'debt', label: 'Công nợ', num: true, sortable: true, sortVal: x => x.debt, render: x => `<span class="${x.debt ? 'red bold' : ''}">${F.vnd(x.debt)}</span>` },
      { key: 'last', label: 'Liên hệ gần nhất', render: x => x.last ? U.cell2(F.datetime(x.last.at) + ' · ' + esc(x.last.channel), esc((x.last.note || '').slice(0, 60))) : '<span class="muted">Chưa liên hệ</span>' },
      { key: 'result', label: 'Kết quả', render: x => x.result ? Q.chip('followUp', x.result) : U.chip('Chưa có', 'gray') },
      { key: 'status', label: 'Trạng thái HĐ', render: x => Q.chip('contract', Q.contractStatus(x.c)) },
      { key: 'deadline', label: 'Deadline / SLA', sortable: true, sortVal: x => x.deadline, render: x => `<span class="${x.deadline < F.today() ? 'red' : ''}">${F.date(x.deadline)}</span>` },
      { key: 'assignee', label: 'Người xử lý', render: x => x.assigneeId ? esc(Q.employeeName(x.assigneeId)) : '<span class="muted">Chưa giao</span>' },
      { key: 'actions', label: 'Thao tác', hideable: false, render: x => U.rowActions([U.actBtn({ icon: 'phone', label: 'Ghi nhận liên hệ', act: 'follow', tone: 'primary', attrs: { 'data-id': x.c.id, 'data-guide': 'expiring-follow' } }), U.moreBtn(x.c.id)]) }], empty: U.empty({ icon: 'check-circle', title: 'Không có hợp đồng sắp hết hạn', text: 'Trong ngưỡng ' + f.days + ' ngày.' }) });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, {
      stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { result: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); },
      follow: (b) => { const c = St.get('contracts', b.dataset.id); Fm.followUp(c, () => TH.router.refresh()); },
      more: (b) => { const c = St.get('contracts', b.dataset.id); const x = rows.find(r => r.c.id === c.id) || {}; U.menu(b, [{ label: 'Xem hợp đồng', icon: 'eye', onClick: () => TH.go('#/contracts/' + c.id) }, { label: 'Ghi nhận liên hệ', icon: 'phone', onClick: () => Fm.followUp(c, () => TH.router.refresh()) }, '-', { label: 'Gia hạn → HĐ mới dự thảo', icon: 'refresh', disabled: c.status !== 'active', onClick: () => Fm.renew(c) }, { label: 'Trả phòng đúng hạn', icon: 'log-out', disabled: !['active', 'pending_renewal'].includes(c.status), onClick: () => { X.addFollowUp({ contractId: c.id, result: 'on_time', note: 'Chọn từ Work Queue' }); Fm.confirmMoveOut(c); } }, { label: 'Chấm dứt sớm', icon: 'x-circle', danger: true, disabled: !['active', 'pending_renewal'].includes(c.status), onClick: () => { X.addFollowUp({ contractId: c.id, result: 'early', note: 'Chọn từ Work Queue' }); Fm.confirmMoveOut(c); } }, { label: 'Chưa phản hồi', icon: 'clock', onClick: () => { X.addFollowUp({ contractId: c.id, result: 'no_response', nextDeadline: F.addDays(F.today(), 2) }); U.toast('ok', 'Đã ghi nhận chưa phản hồi'); TH.router.refresh(); } }, '-', { label: 'Giao người xử lý', icon: 'user-plus', onClick: () => { const m = U.modal({ title: 'Giao xử lý ' + c.code, size: 'sm', body: U.field({ label: 'Nhân viên', input: U.select({ name: 'employeeId', value: c.followUpAssigneeId || '', all: 'Bỏ giao', options: emps.map(e => [e.id, e.name]) }) }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Giao', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.assignFollowUp(c.id, m.data().employeeId || null); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); } }, { label: 'Nhắc Zalo', icon: 'send', onClick: () => Fm.zaloQuick({ tenantIds: [c.tenantId], eventKey: 'contract_expiry', title: 'Nhắc hợp đồng sắp hết hạn' }) }]); },
      export: () => X.exportCsv({ fileName: 'hd-sap-het-han-' + F.today() + '.csv', entity: 'contract', filters: f, header: ['Tòa', 'Phòng', 'Khách', 'SĐT', 'Người ở cùng', 'Quản lý', 'Bắt đầu', 'Kết thúc', 'Còn lại (ngày)', 'Giá', 'Cọc', 'Công nợ', 'Liên hệ gần nhất', 'Kết quả', 'Deadline', 'Người xử lý'], rows: rows.map(x => [x.building.name, x.room.code, x.tenant.name, x.tenant.phone, x.cohabitants.map(m => m.name).join('; '), x.manager.name || '', x.c.start, x.c.end, x.daysLeft, x.c.price, x.c.deposit, x.debt, x.last ? x.last.at : '', x.result ? Q.label('followUp', x.result) : '', x.deadline, x.assigneeId ? Q.employeeName(x.assigneeId) : '']) }) });
  }, { menu: 'expiring', permission: 'contracts.view' });
})(window.TH);
