/* Phase 2 – Tài chính nâng cao: Nhập bảng kê thu tiền, Chuyển số dư ban đầu, Sổ cọc, nâng cấp chi tiết Hoàn cọc (needs_edit, hiện trạng, ghi chú) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, Imp = TH.imp, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  TH._wz = TH._wz || {};

  /* ================= #/finance/statement-import ================= */
  TH.router.register('/finance/statement-import', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Thu tiền', href: '#/receivables' }, { label: 'Nhập bảng kê thu tiền' }]);
    if (TH._wz.stmt && Date.now() - (TH._wz.stmt.at || 0) > 30 * 60000) TH._wz.stmt = null; const w = TH._wz.stmt = TH._wz.stmt || { step: 1 }; w.at = Date.now(); const step = w.step; const T = Imp.STATEMENT;
    const STEPS = [{ title: 'Tải file', sub: 'Tải lên bảng kê thu tiền' }, { title: 'Mapping cột', sub: 'Ánh xạ dữ liệu từ file' }, { title: 'Review & ghép', sub: 'Kiểm tra, chỉnh sửa và ghép dữ liệu' }, { title: 'Xác nhận', sub: 'Hoàn tất và ghi nhận' }];
    const head = U.pageHead({ title: 'Nhập bảng kê thu tiền', phase: 2, sub: 'Kiểm tra, ghép dữ liệu và xác nhận ghi nhận thu tiền vào hệ thống.', acts: [U.btn({ label: 'Xem Data Jobs', icon: 'database', cls: 'btn-outline', act: 'jobs' })] });
    const rulesCard = U.card({ title: 'Quy tắc ghép', icon: 'git-merge', body: `<div class="steps">${T.rules.map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>${U.note('info', '', 'Các dòng không khớp theo quy tắc trên sẽ hiển thị là "Không ghép" và cần kiểm tra thủ công. Dòng có mã ngoài đã tồn tại → "Trùng bỏ qua".')}` });
    let main = '', side = rulesCard;
    if (step === 1) main = U.card({ title: 'Bước 1 – Tải file bảng kê', icon: 'upload', sub: 'CSV (UTF-8) từ ngân hàng/kế toán. File .xlsx: lưu thành CSV trước (bản demo offline).', body: `${U.dropzone({ name: 'stmt', hint: 'CSV, tối đa 5MB', multiple: false, accept: '.csv,.txt,.xlsx,.xls' })}<div class="row mt12 gap12">${U.btn({ label: 'Dùng file mẫu (20 dòng: khớp HĐ, khớp khách+số tiền, không ghép, trùng, HĐ nháp)', icon: 'file-check', cls: 'btn-outline', act: 'sample', attrs: { 'data-guide': 'stmt-sample' } })}${U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-ghost', act: 'dl' })}</div>` });
    else if (step === 2) { const miss = Imp.missingRequired(w.parsed, T.fields); main = U.card({ title: 'Bước 2 – Mapping cột', icon: 'arrow-left-right', sub: w.fileName + ' · ' + w.parsed.data.length + ' dòng · ' + w.parsed.header.length + ' cột', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Cột file</th><th>Ví dụ dữ liệu</th><th>Trường hệ thống</th><th>Bắt buộc</th></tr></thead><tbody>${w.parsed.header.map((h, idx) => { const k = Object.entries(w.parsed.map).find(([kk, v]) => v === idx); return `<tr><td><b>${esc(h)}</b></td><td class="muted">${esc((w.parsed.data[0] || [])[idx] || '')}</td><td>${U.select({ name: 'm_' + idx, value: k ? k[0] : '', all: '— Bỏ qua —', options: T.fields.map(f => [f[0], f[1]]), cls: 'sm', attrs: { 'data-on': 'map' } })}</td><td>${k && T.fields.find(f => f[0] === k[0])[2] ? U.chip('Có', 'red') : U.chip('Không', 'gray')}</td></tr>`; }).join('')}</tbody></table>` }) + `<div class="wz-foot">${U.btn({ label: '← Tải file khác', cls: 'btn-ghost', act: 'to1' })}${U.btn({ label: 'Tiếp tục review & ghép →', cls: 'btn-primary', act: 'to3', disabled: miss.length > 0 })}</div>${miss.length ? U.note('warn', 'Thiếu trường bắt buộc', miss.join(', ')) : ''}`; }
    else {
      const rows = w.rows; const cnt = (s) => rows.filter(r => r.status === s).length; const sum = (s) => F.sum(rows.filter(r => r.status === s), r => F.num(r.data.amount));
      const f = w.filter || ''; const s = w.search || ''; const shown = rows.filter(r => (!f || r.status === f) && (!s || F.norm(Object.values(r.data).join(' ')).includes(F.norm(s))));
      main = `<div class="grid grid-5 mb16">${U.kpi({ label: 'Tổng giao dịch', value: rows.length, cap: 'Dòng dữ liệu từ file', icon: 'file-text', tone: 'blue' })}${U.kpi({ label: 'Đã ghép', value: cnt('matched'), cap: 'Có thể ghi nhận thu tiền', icon: 'check-circle', tone: 'green', delta: F.pct(cnt('matched'), rows.length) })}${U.kpi({ label: 'Cần kiểm tra', value: cnt('check'), cap: 'Cần kiểm tra thông tin', icon: 'alert-triangle', tone: 'amber', delta: F.pct(cnt('check'), rows.length), deltaDir: 'down' })}${U.kpi({ label: 'Trùng bỏ qua', value: cnt('duplicate') + cnt('skipped'), cap: 'Đã có trong hệ thống', icon: 'info', tone: 'gray', delta: F.pct(cnt('duplicate') + cnt('skipped'), rows.length), deltaDir: 'down' })}${U.kpi({ label: 'Chưa phân bổ', value: cnt('unmatched'), cap: 'Không tìm thấy đối tượng', icon: 'x-circle', tone: 'red', delta: F.pct(cnt('unmatched'), rows.length), deltaDir: 'down' })}</div>
      ${U.card({ title: `Dữ liệu preview (${rows.length} dòng)`, icon: 'table', actions: `<div class="row">${U.input({ name: 'ss', value: s, placeholder: 'Tìm kiếm trong bảng…', icon: 'search', cls: 'sm', attrs: { id: 'ss', style: 'width:200px' } })}${U.select({ name: 'sf', value: f, all: 'Bộ lọc: tất cả', options: Object.entries(Q.L.match).map(([k, v]) => [k, v[0]]), cls: 'sm', attrs: { 'data-on': 'sf', style: 'width:auto' } })}${U.btn({ label: 'Tùy chỉnh cột', icon: 'settings', size: 'btn-sm', cls: 'btn-outline', act: 'cols' })}</div>`, body: null, id: 'st' })}`;
      side = rulesCard + U.card({ title: 'Kết quả dự kiến', icon: 'check-circle', body: U.stat3([['Tổng tiền sẽ ghi nhận', F.vnd(sum('matched')), 'green'], ['Tiền cần kiểm tra', F.vnd(sum('check')), 'amber'], ['Tiền chưa phân bổ', F.vnd(sum('unmatched')), 'red']]).replace('class="stat3"', 'class="stat3" style="grid-template-columns:1fr"') + `<div class="xs muted mt8">Từ ${cnt('matched')} / ${cnt('check')} / ${cnt('unmatched')} giao dịch</div>` });
      w._shown = shown;
    }
    root.innerHTML = `${head}${U.wizard(STEPS, step - 1)}<div class="two-col wide">${'<div class="side-stack">' + main + '</div>'}<aside class="side-stack">${side}</aside></div>${step >= 3 ? `<div class="wz-foot mt16"><div class="row">${U.btn({ label: 'Quay lại', icon: 'arrow-left', cls: 'btn-outline', act: 'to2' })}${U.btn({ label: 'Tải dòng lỗi', icon: 'download', cls: 'btn-outline', act: 'dl-err' })}<span class="small muted">Xuất file các dòng không ghép được</span></div><div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${U.btn({ label: 'Duyệt ghi nhận', icon: 'arrow-right', cls: 'btn-primary', act: 'commit', disabled: !TH.auth.can('statement.import') || !w.rows.some(r => r.status === 'matched'), title: TH.auth.can('statement.import') ? '' : 'Chỉ Admin/Kế toán', attrs: { 'data-guide': 'stmt-commit' } })}</div></div>` : ''}`;
    if (step >= 3) { const cols = [{ key: 'i', label: '#', width: '40px' }, { key: 'date', label: 'Ngày giao dịch', render: r => F.date(r.data.date) }, { key: 'amount', label: 'Số tiền (VND)', num: true, sortable: true, sortVal: r => F.num(r.data.amount), render: r => F.vnd(F.num(r.data.amount)) }, { key: 'ref', label: 'Mã ngoài', render: r => `<span class="blue">${esc(r.data.refCode || '-')}</span>` }, { key: 'inv', label: 'Mã hóa đơn', render: r => r.invoiceId ? U.link('#/invoices/' + r.invoiceId, esc((St.get('invoices', r.invoiceId) || {}).code || '')) : esc(r.data.invoiceCode || '-') }, { key: 'ctr', label: 'Mã hợp đồng', render: r => esc(r.data.contractCode || (r.invoiceId ? Q.contract((St.get('invoices', r.invoiceId) || {}).contractId).code || '-' : '-')) }, { key: 'room', label: 'Phòng / Tòa', render: r => { const inv = r.invoiceId ? St.get('invoices', r.invoiceId) : null; return inv ? `<span class="blue">${esc(Q.room(inv.roomId).code)}</span>` : esc(r.data.roomCode || '-'); } }, { key: 'tenant', label: 'Khách thuê', render: r => esc(r.tenantId ? Q.tenant(r.tenantId).name : (r.data.tenantName || '-')) }, { key: 'method', label: 'Phương thức', render: r => esc(r.data.method || '-') }, { key: 'status', label: 'Kết quả ghép', sortable: true, render: r => (r.status === 'skipped' ? U.chip('Bỏ qua', 'gray') : U.matchChip(r.status)) + (r.reason ? `<div class="xs muted">${esc(r.reason)}</div>` : '') }, { key: 'alloc', label: 'Tiền phân bổ', num: true, render: r => F.vnd(r.alloc || 0) }, { key: 'unalloc', label: 'Tiền chưa phân bổ', num: true, render: r => `<span class="${r.unalloc ? 'red' : ''}">${F.vnd(r.unalloc || 0)}</span>` }, { key: 'actions', label: '', render: r => ['check', 'unmatched'].includes(r.status) ? U.actBtn({ icon: 'pencil', label: 'Ghép thủ công', act: 'resolve', attrs: { 'data-i': r.i } }) : '', hideable: false }];
      const tbl = U.table(root.querySelector('#st'), { rows: w._shown, unit: 'dòng', rowClass: r => r.status === 'unmatched' ? 'tint-red' : r.status === 'check' ? 'tint-amber' : '', colPrefsKey: 'stmt', cols }); w._tbl = tbl; w._cols = cols;
      root.querySelector('#ss').addEventListener('input', (e) => { w.search = e.target.value; const s2 = F.norm(w.search); w._shown = rows.filter(r => (!f || r.status === f) && (!s2 || F.norm(Object.values(r.data).join(' ')).includes(s2))); tbl.setRows(w._shown); }); }
    U.bindDropzones(root, async (files) => { const f = files[0]; if (!f) return; try { const r = await Imp.readFile(f); w.parsed = Imp.parse(r.rows, T.fields, T.aliases); w.fileName = f.name; w.checksum = r.checksum; w.step = 2; TH.router.refresh(); } catch (e) { U.toast('err', 'Không đọc được file', e.message); } });
    U.onChange(root, { map: () => { const m = {}; root.querySelectorAll('select[name^=m_]').forEach(s => { if (s.value) m[s.value] = Number(s.name.slice(2)); }); w.parsed.map = m; TH.router.refresh(); }, sf: (el) => { w.filter = el.value; TH.router.refresh(); } });
    U.bind(root, {
      jobs: () => TH.go('#/settings/jobs'), sample: () => { const rows = Imp.statementSample(); const r = Imp.fromRows(rows, 'mau-bang-ke-thu-tien.csv'); w.parsed = Imp.parse(r.rows, T.fields, T.aliases); w.fileName = r.fileName; w.checksum = r.checksum; w.step = 2; TH.router.refresh(); }, dl: () => { const rows = Imp.statementSample(); F.download('mau-bang-ke-thu-tien.csv', F.csv(rows.slice(1), rows[0]), 'text/csv'); ok('Đã tải file mẫu bảng kê'); },
      to1: () => { TH._wz.stmt = { step: 1 }; TH.router.refresh(); }, to3: () => { w.rows = X.matchStatement(Imp.rowsToObjects(w.parsed)); w.step = 3; TH.router.refresh(); }, cols: (el) => U.columnMenu(el, w._tbl, w._cols),
      resolve: (el) => { const row = w.rows.find(r => r.i === Number(el.dataset.i)); const cands = St.where('invoices', i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0).sort((a, b) => F.cmp(b.dueDate, a.dueDate)).slice(0, 200); const m = U.modal({ title: 'Ghép thủ công dòng #' + row.i, sub: F.date(row.data.date) + ' · ' + F.vnd(F.num(row.data.amount)) + ' · ' + (row.data.refCode || '') + ' – ' + row.reason, body: `${U.field({ label: 'Hóa đơn còn nợ', input: U.select({ name: 'invoiceId', value: row.invoiceId || '', placeholder: 'Chọn hóa đơn', options: cands.map(i => [i.id, i.code + ' – ' + Q.tenant(i.tenantId).name + ' – ' + Q.room(i.roomId).code + ' – còn ' + F.vnd(Q.invRemaining(i))]) }), help: row.invoiceId && (St.get('invoices', row.invoiceId) || {}).docStatus === 'draft' ? 'Hóa đơn ' + St.get('invoices', row.invoiceId).code + ' đang Nháp – phát hành trước rồi Kiểm tra lại ở Data Job, hoặc chọn hóa đơn khác.' : '' })}`, footer: U.btn({ label: 'Bỏ qua dòng này', cls: 'btn-ghost', act: 'skip' }) + U.btn({ label: 'Ghép', cls: 'btn-primary', act: 'ok' }) }); U.bind(m.el, { skip: () => { X.resolveStatementRow(row, { skip: true }); m.close(); TH.router.refresh(); }, ok: () => { X.resolveStatementRow(row, { invoiceId: m.data().invoiceId }); m.close(); ok('Đã ghép dòng #' + row.i); TH.router.refresh(); } }); },
      'dl-err': () => { const bad = w.rows.filter(r => r.status !== 'matched'); F.download('bang-ke-dong-loi.csv', F.csv(bad.map(r => [r.i, r.data.date, r.data.amount, r.data.refCode, r.data.invoiceCode, r.data.contractCode, r.data.roomCode, r.data.tenantName, Q.label('match', r.status), r.reason]), ['#', 'Ngày', 'Số tiền', 'Mã ngoài', 'Mã HĐ', 'Mã hợp đồng', 'Phòng', 'Khách', 'Kết quả', 'Lý do']), 'text/csv'); ok('Đã tải ' + bad.length + ' dòng lỗi'); }, draft: () => { St.state.meta.drafts = St.state.meta.drafts || {}; St.state.meta.drafts.statement = { fileName: w.fileName, at: F.nowISO() }; St.save(); ok('Đã lưu nháp phiên nhập bảng kê'); },
      commit: async () => { const n = w.rows.filter(r => r.status === 'matched').length; if (await U.confirm({ title: 'Duyệt ghi nhận ' + n + ' khoản thu?', text: 'Mỗi dòng Đã ghép tạo 1 khoản thu (kind=statement) phân bổ vào hóa đơn ghép; phần dư ghi "chưa phân bổ". Idempotent theo checksum file. Dòng Cần kiểm tra/Không ghép được lưu vào Data Job để xử lý tiếp.', ok: 'Duyệt ghi nhận' })) { try { const job = X.commitStatement({ rows: w.rows, fileName: w.fileName, checksum: w.checksum, period: St.state.meta.period }); TH._wz.stmt = null; if (job.duplicate) U.toast('warn', 'Bảng kê này đã được duyệt trước đó', 'Không tạo khoản thu trùng'); else ok('Đã ghi nhận ' + job.created + ' khoản thu', 'Tác vụ ' + job.code); TH.go('#/settings/jobs/' + job.id); } catch (e) { U.toast('err', 'Không ghi nhận được', e.message); } } },
    });
  }, { menu: 'statement', permission: 'statement.import', phase: 2, scopeKey: 'statement', noAutoRefresh: true });

  /* ================= #/finance/opening-balance ================= */
  TH.router.register('/finance/opening-balance', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Chuyển số dư ban đầu' }]);
    const w = TH._wz.opening = TH._wz.opening || { step: 1, asOf: '2026-11-01', buildingId: '', kind: '' }; const step = w.step; const T = Imp.OPENING;
    const STEPS = [{ title: 'Chọn mốc & phạm vi', sub: 'Chọn thời điểm và phạm vi dữ liệu' }, { title: 'Tải file số dư', sub: 'Tải lên file từ hệ thống cũ' }, { title: 'Đối chiếu', sub: 'Kiểm tra và đối chiếu dữ liệu' }, { title: 'Xác nhận', sub: 'Xác nhận chuyển số dư' }];
    const filter = U.filterbar([U.field({ label: 'Mốc chuyển đổi', req: true, input: U.date({ name: 'asOf', value: w.asOf, attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: w.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại dữ liệu', input: U.select({ name: 'kind', value: w.kind, all: 'Tất cả', options: [['debt', 'Công nợ'], ['deposit', 'Cọc']], attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }));
    let body = '';
    if (step === 1) body = `<div class="two-col">${U.card({ title: 'Bước 1 – Mốc & phạm vi', icon: 'calendar', body: `${U.note('info', 'Số dư đầu kỳ', 'Số dư công nợ/cọc từ hệ thống cũ được chuyển vào TimoHouse tại mốc ' + F.date(w.asOf) + '. Mỗi hợp đồng tạo <b>1 hóa đơn kind=opening</b> (kỳ ' + F.periodLabel(F.period(w.asOf)) + ', đã phát hành) và <b>1 khoản thu kind=opening</b> cho phần "Đã thu trước đó" → công nợ/nhắc nợ Phase 1 hoạt động tự nhiên, không sinh khoản thu mới ngoài số dư. Quyết định kỹ thuật của mockup – BA xác nhận.')}<div class="wz-foot mt16"><span></span>${U.btn({ label: 'Tiếp tục tải file →', cls: 'btn-primary', act: 'to2' })}</div>` })}<aside class="side-stack">${U.card({ title: 'Lưu ý quan trọng', icon: 'info', body: '<div class="small">Số dư đầu kỳ chỉ được chuyển sang hệ thống và không tạo ra các khoản thu mới. Vui lòng kiểm tra kỹ trước khi xác nhận. Hoàn tác bằng cách hủy hóa đơn opening (Admin).</div>' })}</aside></div>`;
    else if (step === 2) body = `<div class="two-col">${U.card({ title: 'Bước 2 – Tải file số dư', icon: 'upload', sub: 'Cột: Khách hàng, Mã hợp đồng*, Phòng, Phải thu*, Đã thu*, Cọc giữ, Nguồn dữ liệu', body: `${U.dropzone({ name: 'ob', hint: 'CSV, tối đa 5MB', multiple: false, accept: '.csv,.txt,.xlsx,.xls' })}<div class="row mt12 gap12">${U.btn({ label: 'Dùng file mẫu (12 dòng, 2 chênh lệch, 1 không tìm thấy HĐ)', icon: 'file-check', cls: 'btn-outline', act: 'sample', attrs: { 'data-guide': 'ob-sample' } })}${U.btn({ label: 'Dùng file mẫu lớn (124 dòng)', icon: 'file-check', cls: 'btn-ghost', act: 'sample-large' })}${U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-ghost', act: 'dl' })}</div><div class="wz-foot mt16">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: 'to1' })}<span></span></div>` })}<aside class="side-stack">${U.card({ title: 'Quy tắc đối chiếu', icon: 'shield-check', body: `<div class="steps">${[['Hợp lệ', 'HĐ tồn tại, cọc file = cọc hệ thống, đã thu ≤ phải thu.'], ['Chênh lệch', 'Cọc file ≠ cọc hệ thống → chọn nguồn đúng (file/hệ thống) trước khi xác nhận.'], ['Cần kiểm tra', 'Không tìm thấy hợp đồng hoặc số liệu bất thường – không chuyển.']].map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` })}</aside></div>`;
    else {
      const rows = w.rows.filter(r => (!w.buildingId || (r.contractId && Q.contract(r.contractId).buildingId === w.buildingId)) && (!w.kind || (w.kind === 'debt' ? r.debt > 0 : r.deposit > 0))); const cnt = (s) => rows.filter(r => r.status === s).length; const val = (s) => F.sum(rows.filter(r => r.status === s), r => r.receivable);
      const rec = F.sum(rows, r => r.receivable), paid = F.sum(rows, r => r.paid), dep = F.sum(rows, r => r.deposit);
      body = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Phải thu đầu kỳ', value: F.vnd(rec), cap: rows.length + ' khách thuê', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã thu trước đó', value: F.vnd(paid), cap: F.pct(paid, rec) + '% trên tổng phải thu', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn nợ chuyển vào', value: F.vnd(rec - paid), cap: F.pct(rec - paid, rec) + '% trên tổng phải thu', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Cọc đang giữ', value: F.vnd(dep), cap: rows.filter(r => r.deposit).length + ' hợp đồng', icon: 'database', tone: 'purple' })}</div>
      <div class="two-col wide"><div class="side-stack">${U.card({ title: `Danh sách đối chiếu số dư (${rows.length} dòng)`, icon: 'users', actions: U.btn({ label: 'Nhập lại file', icon: 'upload', size: 'btn-sm', cls: 'btn-outline', act: 'to2' }), body: null, id: 'ot' })}</div>
      <aside class="side-stack">${U.card({ title: 'Tóm tắt đối chiếu', icon: 'clipboard-check', body: `${U.stat3([['Tổng dòng hợp lệ', cnt('valid') + ' <small class="muted">(' + F.pct(cnt('valid'), rows.length) + '%)</small>', 'green'], ['Tổng dòng chênh lệch', cnt('diff') + ' <small class="muted">(' + F.pct(cnt('diff'), rows.length) + '%)</small>', 'red'], ['Số dòng cần kiểm tra', cnt('check') + ' <small class="muted">(' + F.pct(cnt('check'), rows.length) + '%)</small>', 'amber']]).replace('class="stat3"', 'class="stat3" style="grid-template-columns:1fr"')}<div class="bold mt12 mb8">Tổng giá trị theo trạng thái</div>${U.kv([['<span class="green">●</span> Giá trị hợp lệ', F.vnd(val('valid'))], ['<span class="red">●</span> Giá trị chênh lệch', F.vnd(val('diff'))], ['<span class="amber">●</span> Giá trị cần kiểm tra', F.vnd(val('check'))], ['Tổng phải thu đầu kỳ', '<b>' + F.vnd(rec) + '</b>'], ['Tổng cọc giữ', '<b>' + F.vnd(dep) + '</b>']], 'one')}` })}${U.note('info', 'Lưu ý quan trọng', 'Số dư đầu kỳ chỉ được chuyển sang hệ thống và không tạo ra các khoản thu mới. Vui lòng kiểm tra kỹ trước khi xác nhận.')}</aside></div>
      <div class="wz-foot mt16"><div class="row">${U.btn({ label: 'Tải lỗi', icon: 'download', cls: 'btn-outline', act: 'dl-err' })}<span class="small muted">Tải danh sách các dòng có lỗi hoặc chênh lệch</span></div><div class="row">${U.btn({ label: 'Quay lại', icon: 'arrow-left', cls: 'btn-outline', act: 'to2' })}${U.btn({ label: 'Xác nhận chuyển số dư', icon: 'arrow-right', cls: 'btn-primary', act: 'commit', disabled: !TH.auth.can('openingBalance.manage') || !rows.some(r => r.selected), attrs: { 'data-guide': 'ob-commit' } })}</div></div>`;
      w._shown = rows;
    }
    root.innerHTML = `${U.pageHead({ title: 'Chuyển số dư ban đầu', phase: 2, sub: 'Nhập và đối chiếu số dư công nợ, cọc từ hệ thống cũ trước khi xác nhận chuyển sang TimoHouse.', acts: [U.btn({ label: 'Xem Data Jobs', icon: 'database', cls: 'btn-outline', act: 'jobs' })] })}${U.wizard(STEPS, step - 1)}${filter}${body}`;
    if (step >= 3) { const tbl = U.table(root.querySelector('#ot'), { rows: w._shown, unit: 'dòng', selectable: true, selectableIf: r => r.status === 'valid' || r.status === 'diff', rowKey: r => String(r.i), onSelect: (ids) => { w.rows.forEach(r => r.selected = ids.includes(String(r.i))); root.querySelector('[data-act=commit]').disabled = !w.rows.some(r => r.selected); }, rowClass: r => r.status === 'diff' ? 'tint-red' : r.status === 'check' ? 'tint-amber' : '', cols: [{ key: 'i', label: '#', width: '36px' }, { key: 'tenant', label: 'Khách hàng / Hợp đồng', render: r => U.cell2(esc(r.tenantId ? Q.tenant(r.tenantId).name : r.data.tenantName || '-'), esc(r.data.contractCode)) }, { key: 'room', label: 'Phòng / Tòa', render: r => r.roomId ? U.cell2(`<span class="blue">${esc(Q.room(r.roomId).code)}</span>`, esc(Q.building(Q.room(r.roomId).buildingId).name)) : esc(r.data.roomCode || '-') }, { key: 'rec', label: 'Phải thu (VND)', num: true, render: r => F.vnd(r.receivable) }, { key: 'paid', label: 'Đã thu (VND)', num: true, render: r => F.vnd(r.paid) }, { key: 'debt', label: 'Còn nợ (VND)', num: true, render: r => `<span class="${r.debt > 0 ? 'red bold' : ''}">${F.vnd(r.debt)}</span>` }, { key: 'dep', label: 'Cọc giữ (VND)', num: true, render: r => F.vnd(r.deposit) + (r.status === 'diff' ? `<div class="xs muted">HT: ${F.vnd(r.sysDeposit)}</div>` : '') }, { key: 'src', label: 'Nguồn dữ liệu', render: r => U.chip(r.sourceType, 'gray') }, { key: 'status', label: 'Trạng thái đối chiếu', sortable: true, render: r => Q.chip('opening', r.status) + (r.reason && r.status !== 'valid' ? `<div class="xs muted">${esc(r.reason)}</div>` : '') + (r.status === 'diff' ? `<div class="mt4"><select class="inp sm" data-on="src" data-i="${r.i}" style="width:auto"><option value="file" ${r.useSource === 'file' ? 'selected' : ''}>Lấy cọc theo file</option><option value="system" ${r.useSource === 'system' ? 'selected' : ''}>Giữ cọc hệ thống</option></select></div>` : '') }] }); w.rows.forEach(r => { if (r.selected) tbl.state.selected.add(String(r.i)); }); tbl.render(); }
    U.bindDropzones(root, async (files) => { const f = files[0]; if (!f) return; try { const r = await Imp.readFile(f); w.parsed = Imp.parse(r.rows, T.fields, T.aliases); const miss = Imp.missingRequired(w.parsed, T.fields); if (miss.length) throw new Error('Thiếu cột bắt buộc: ' + miss.join(', ')); w.fileName = f.name; w.checksum = r.checksum; w.rows = X.reconcileOpening(Imp.rowsToObjects(w.parsed), w.asOf); w.rows.forEach(x => x.selected = x.status === 'valid'); w.step = 3; TH.router.refresh(); } catch (e) { U.toast('err', 'Không đọc được file', e.message); } });
    const useSample = (rows, name) => { const r = Imp.fromRows(rows, name); w.parsed = Imp.parse(r.rows, T.fields, T.aliases); w.fileName = r.fileName; w.checksum = r.checksum; w.rows = X.reconcileOpening(Imp.rowsToObjects(w.parsed), w.asOf); w.rows.forEach(x => x.selected = x.status === 'valid'); w.step = 3; TH.router.refresh(); };
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); const changedAsOf = d.asOf !== w.asOf; Object.assign(w, d); if (changedAsOf && w.rows) { w.rows = X.reconcileOpening(w.rows.map(r => ({ i: r.i, data: r.data })), w.asOf); w.rows.forEach(x => x.selected = x.status === 'valid'); } TH.router.refresh(); }, src: (el) => { const r = w.rows.find(x => x.i === Number(el.dataset.i)); if (r) r.useSource = el.value; } });
    U.bind(root, { jobs: () => TH.go('#/settings/jobs'), reset: () => { Object.assign(w, { buildingId: '', kind: '' }); TH.router.refresh(); }, restart: () => { TH._wz.opening = null; TH.router.refresh(); }, to1: () => { w.step = 1; TH.router.refresh(); }, to2: () => { w.step = 2; TH.router.refresh(); }, sample: () => useSample(Imp.openingSample(), 'mau-so-du-dau-ky.csv'), 'sample-large': () => useSample(Imp.openingSampleLarge(), 'so-du-dau-ky-124.csv'), dl: () => { const rows = Imp.openingSample(); F.download('mau-so-du-dau-ky.csv', F.csv(rows.slice(1), rows[0]), 'text/csv'); ok('Đã tải file mẫu'); },
      'dl-err': () => { const bad = w.rows.filter(r => r.status !== 'valid'); F.download('so-du-dong-loi.csv', F.csv(bad.map(r => [r.i, r.data.contractCode, r.receivable, r.paid, r.deposit, r.sysDeposit, Q.label('opening', r.status), r.reason]), ['#', 'Mã HĐ', 'Phải thu', 'Đã thu', 'Cọc file', 'Cọc hệ thống', 'Trạng thái', 'Lý do']), 'text/csv'); ok('Đã tải ' + bad.length + ' dòng lỗi/chênh lệch'); },
      commit: async () => { const sel = w.rows.filter(r => r.selected); if (await U.confirm({ title: 'Xác nhận chuyển số dư ' + sel.length + ' hợp đồng?', text: 'Mốc ' + F.date(w.asOf) + '. Tạo hóa đơn opening + khoản thu opening cho phần đã thu; dòng chênh lệch dùng nguồn đã chọn. Idempotent theo mốc + HĐ.', ok: 'Xác nhận chuyển số dư' })) { try { const job = X.commitOpening({ rows: w.rows, asOf: w.asOf, fileName: w.fileName, checksum: w.checksum }); TH._wz.opening = null; if (job.duplicate) U.toast('warn', 'File này đã chuyển số dư trước đó'); else ok('Đã chuyển số dư ' + job.created + ' hợp đồng', 'Tác vụ ' + job.code); TH.go('#/settings/jobs/' + job.id); } catch (e) { U.toast('err', 'Không chuyển được', e.message); } } } });
  }, { menu: 'opening', permission: 'openingBalance.manage', phase: 2, scopeKey: 'opening', noAutoRefresh: true });

  /* ================= #/finance/deposits – Sổ cọc ================= */
  TH.router.register('/finance/deposits', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Quản lý cọc' }]);
    const f = { kind: q.kind || '', s: q.s || '', buildingId: q.buildingId || '' }; const all = Q.deposits();
    const rows = all.filter(r => (!f.kind || r.kind === f.kind) && (!f.buildingId || Q.room(r.roomId).buildingId === f.buildingId) && (!f.s || F.norm(Q.tenant(r.tenantId).name + ' ' + Q.room(r.roomId).code + ' ' + r.ref).includes(F.norm(f.s))));
    const holding = F.sum(all.filter(r => r.kind === 'deposit'), r => r.amount), fees = F.sum(all.filter(r => r.kind === 'hold'), r => r.amount), refunded = F.sum(all.filter(r => r.kind === 'refund' && r.status === 'refunded' && F.period(r.date) === St.state.meta.period), r => r.amount), pending = F.sum(all.filter(r => r.kind === 'refund' && r.status === 'pending_refund'), r => r.amount);
    root.innerHTML = `${U.pageHead({ title: 'Quản lý cọc', phase: 2, sub: 'Sổ cọc khách thuê: cọc hợp đồng đang giữ, phí giữ chỗ, hoàn cọc – tách với cọc trả chủ nhà (FR-FIN-06/07).', acts: [U.btn({ label: 'Xuất CSV', icon: 'download', cls: 'btn-primary', act: 'export' })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Cọc đang giữ', value: F.vnd(holding), cap: all.filter(r => r.kind === 'deposit').length + ' hợp đồng hiệu lực', icon: 'shield', tone: 'blue' })}${U.kpi({ label: 'Phí giữ chỗ', value: F.vnd(fees), cap: all.filter(r => r.kind === 'hold').length + ' giữ chỗ đang hiệu lực', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Đã hoàn tháng này', value: F.vnd(refunded), cap: F.periodLabel(St.state.meta.period), icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Chờ hoàn', value: F.vnd(pending), cap: all.filter(r => r.kind === 'refund' && r.status === 'pending_refund').length + ' hồ sơ đang xử lý', icon: 'hand-coins', tone: 'red' })}</div>
    ${U.statusTabs([{ key: '', label: 'Tất cả', count: all.length }, { key: 'deposit', label: 'Cọc hợp đồng', count: all.filter(r => r.kind === 'deposit').length, color: 'blue' }, { key: 'hold', label: 'Phí giữ chỗ', count: all.filter(r => r.kind === 'hold').length, color: 'amber' }, { key: 'refund', label: 'Hoàn cọc', count: all.filter(r => r.kind === 'refund').length, color: 'green' }], f.kind)}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Khách, phòng, mã…', icon: 'search', attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.card({ title: 'Sổ cọc', body: null, id: 'dpt' })}`;
    U.table(root.querySelector('#dpt'), { rows, unit: 'dòng', cols: [{ key: 'tenant', label: 'Khách', render: r => U.link('#/tenants/' + r.tenantId, esc(Q.tenant(r.tenantId).name || '-')) }, { key: 'room', label: 'Phòng', render: r => U.cell2(esc(Q.room(r.roomId).code || '-'), esc(Q.building(Q.room(r.roomId).buildingId).name || '')) }, { key: 'label', label: 'Loại', render: r => U.chip(r.label, { deposit: 'blue', hold: 'amber', refund: 'green' }[r.kind]) }, { key: 'amount', label: 'Số tiền', num: true, sortable: true, render: r => F.vnd(r.amount) }, { key: 'date', label: 'Ngày', sortable: true, render: r => F.date(r.date) }, { key: 'status', label: 'Trạng thái', render: r => ({ holding: U.chip('Đang giữ', 'blue'), refunded: U.chip('Đã hoàn', 'green'), pending_refund: U.chip('Chờ hoàn', 'amber') })[r.status] }, { key: 'ref', label: 'Tham chiếu', render: r => U.link(r.href, esc(r.ref)) }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { kind: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, export: () => { F.download('so-coc.csv', F.csv(rows.map(r => [Q.tenant(r.tenantId).name, Q.room(r.roomId).code, r.label, r.amount, r.date, r.status, r.ref]), ['Khách', 'Phòng', 'Loại', 'Số tiền', 'Ngày', 'Trạng thái', 'Tham chiếu']), 'text/csv'); ok('Đã xuất sổ cọc'); } });
  }, { menu: 'deposits', permission: 'deposits.view', phase: 2, scopeKey: 'deposits' });

  /* ================= Nâng cấp #/refunds/:id khi P2 bật (PNG 03/09) ================= */
  const rt = TH.router.routes.find(r => r.pattern === '/refunds/:id'); const p1Refund = rt && rt.handler;
  const INSPECT = [['general', 'Tình trạng chung', ['Bình thường', 'Có hư hỏng']], ['furniture', 'Nội thất', ['Đầy đủ', 'Có hư hỏng nhỏ', 'Hư hỏng nặng']], ['cleaning', 'Vệ sinh', ['Đạt yêu cầu', 'Chưa đạt']], ['keys', 'Chìa khóa', ['Đã bàn giao', 'Thiếu']], ['devices', 'Thiết bị', ['Hoạt động bình thường', 'Có lỗi']]];
  const inspLabel = (k, v) => { const it = INSPECT.find(x => x[0] === k); return v === 'ok' ? it[2][0] : v === 'minor' ? it[2][1] : it[2][2] || it[2][1]; };
  const refundP2 = (root, p) => {
    const rf = St.get('refunds', p.id); if (!rf) { root.innerHTML = U.empty({ title: 'Không tìm thấy hồ sơ' }); return; }
    const t = Q.tenant(rf.tenantId), room = Q.room(rf.roomId), c = Q.contract(rf.contractId), dd = Q.refundDeductions(rf.id), k = Q.refundCompute(rf); const insp = rf.inspection2 || { general: 'ok', furniture: 'ok', cleaning: 'ok', keys: 'ok', devices: 'ok' }; const damaged = Object.values(insp).some(v => v !== 'ok');
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hoàn cọc', href: '#/refunds' }, { label: rf.code }]);
    const canEdit = ['draft', 'needs_edit', 'rejected'].includes(rf.status) && TH.auth.can('refunds.prepare'); const canApprove = TH.auth.can('approveRefund');
    const acts = [];
    if (rf.status === 'pending') acts.push(U.btn({ label: 'Yêu cầu chỉnh sửa', icon: 'pencil', cls: 'btn-outline', act: 'req-edit', disabled: !TH.auth.can('refunds.requestEdit'), attrs: { 'data-guide': 'refund-req-edit' } }), U.btn({ label: 'Từ chối', icon: 'x', cls: 'btn-danger-solid', act: 'reject', disabled: !canApprove }), U.btn({ label: 'Duyệt', icon: 'check', cls: 'btn-primary', act: 'approve', disabled: !canApprove, attrs: { 'data-guide': 'refund-approve' } }));
    if (canEdit) acts.push(U.btn({ label: 'Sửa phương án', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Gửi duyệt', icon: 'send', cls: 'btn-primary', act: 'submit', attrs: { 'data-guide': 'refund-submit' } }));
    if (rf.status === 'approved') acts.push(U.btn({ label: 'Ghi nhận đã hoàn', icon: 'banknote', cls: 'btn-primary', act: 'paid', disabled: !TH.auth.can('recordRefundPaid'), attrs: { 'data-guide': 'refund-paid' } }));
    if (rf.status === 'refunded') acts.push(U.btn({ label: 'Gửi Zalo "Đã hoàn cọc"', icon: 'send', cls: 'btn-outline', act: 'zalo' }), room.status === 'cleaning' ? U.btn({ label: 'Xác nhận dọn xong phòng', icon: 'check', cls: 'btn-primary', act: 'clean' }) : '');
    acts.push(U.iconBtn('more', 'more', 'Thêm', {}, 'bordered'));
    const hist = rf.history || []; const at = (s) => (hist.filter(h => h.status === s).slice(-1)[0] || {});
    const stepIdx = { draft: 0, needs_edit: 0, rejected: 0, pending: 1, approved: 2, refunded: 3 }[rf.status] || 0;
    const stepper = U.stepperStatus([{ label: 'Nháp', date: F.datetime(at('draft').at || rf.requestDate + 'T09:00') }, { label: rf.status === 'needs_edit' ? 'Cần chỉnh sửa' : 'Chờ duyệt', date: at('pending').at ? F.datetime(at('pending').at) : '', sub: at('pending').at ? '' : 'Chưa thực hiện', by: at('pending').at ? 'Chờ quản lý phê duyệt' : '' }, { label: 'Đã duyệt', date: rf.approvedAt ? F.datetime(rf.approvedAt) : '', sub: 'Chưa thực hiện' }, { label: 'Đã hoàn', date: rf.paidDate ? F.date(rf.paidDate) : '', sub: 'Chưa thực hiện' }], stepIdx);
    root.innerHTML = `${U.pageHead({ back: '#/refunds', title: esc(rf.code), phase: 2, chips: ' ' + Q.chip('refund', rf.status, 'lg'), sub: `<b>${esc(t.name)}</b> • Phòng ${esc(room.code)} - ${esc(Q.building(rf.buildingId).name)} • HĐ ${U.link('#/contracts/' + c.id, c.code)}`, acts })}
    ${rf.status === 'needs_edit' ? U.note('warn', 'Yêu cầu chỉnh sửa từ ' + esc(Q.userName(rf.editRequestedBy)) + ' (' + F.datetime(rf.editRequestedAt) + ')', esc(rf.editReason || '') + ' – sửa bảng khấu trừ/hiện trạng rồi Gửi duyệt lại (FR-FIN-07).') + '<div class="mb16"></div>' : ''}${rf.status === 'rejected' ? U.note('danger', 'Hồ sơ bị từ chối', esc(rf.rejectReason)) + '<div class="mb16"></div>' : ''}
    ${stepper}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Cọc giữ (ban đầu)', value: F.vnd(rf.deposit), cap: 'VND', icon: 'banknote', tone: 'green' })}${U.kpi({ label: 'Khấu trừ', value: F.vnd(k.ded), cap: dd.length + ' hạng mục', icon: 'minus-circle', tone: 'amber', valueCls: 'amber' })}${U.kpi({ label: 'Đề nghị hoàn', value: F.vnd(k.refund), cap: 'VND', icon: 'undo', tone: 'blue', valueCls: 'blue' })}${U.kpi({ label: 'Công nợ liên quan', value: F.vnd(Q.contractDebt(rf.contractId)), cap: Q.contractDebt(rf.contractId) ? 'Còn nợ – không bù trừ (OI-07)' : 'Không có công nợ', icon: 'file-text', tone: 'purple' })}</div>
    <div class="two-col wide"><div class="side-stack"><div class="grid grid-2">
      ${U.card({ title: '1. Thông tin trả phòng', icon: 'file-text', actions: canEdit ? U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }) : '', body: U.kv([['Mã hoàn cọc', esc(rf.code)], ['Khách thuê', esc(t.name) + ' <span class="chip blue">' + esc(t.code) + '</span>'], ['Phòng', esc(room.code) + ' - ' + esc(Q.building(rf.buildingId).name)], ['Hợp đồng', U.link('#/contracts/' + c.id, c.code)], ['Ngày trả phòng', F.date(rf.moveOutDate)], ['Ngày đề nghị hoàn', F.date(rf.requestDate)], ['Lý do trả phòng', esc(c.endReason || 'Hết hạn hợp đồng')], ['Ghi chú', esc(rf.note || c.note || 'Khách đã bàn giao đầy đủ chìa khóa và thiết bị.')]], 'one') })}
      ${U.card({ title: '2. Hiện trạng phòng', icon: 'clipboard-check', actions: damaged ? `<span class="chip red">${I('alert-triangle')} Có hư hỏng</span>` : `<span class="chip green">Bình thường</span>`, body: `${U.kv(INSPECT.map(([kk, l]) => [l, U.chip(inspLabel(kk, insp[kk] || 'ok'), insp[kk] === 'ok' ? (kk === 'general' ? 'amber' : 'green') : insp[kk] === 'minor' ? 'red' : 'red')]), 'one')}<div class="row between mt12 mb8"><b class="small">Hình ảnh hiện trạng</b><a class="link small" data-act="photos">Xem tất cả (${(rf.photos || []).length})</a></div><div class="photo-grid">${(rf.photos || []).slice(0, 4).map(ph => `<div class="photo" title="${esc(ph)}"></div>`).join('')}${(rf.photos || []).length > 4 ? `<div class="photo" style="display:grid;place-items:center;color:#fff;font-weight:700">+${(rf.photos || []).length - 4}</div>` : ''}${['draft', 'needs_edit', 'rejected', 'pending'].includes(rf.status) ? '<div class="photo add" data-act="inspect">+ Cập nhật<br>hiện trạng</div>' : ''}</div>` })}</div>
      ${U.card({ title: '3. Bảng khấu trừ', icon: 'list', actions: canEdit ? U.btn({ label: 'Thêm hạng mục', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'ded-add' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Hạng mục</th><th class="num">Số lượng</th><th class="num">Đơn giá (VND)</th><th class="num">Thành tiền (VND)</th><th>Ghi chú</th>${canEdit ? '<th>Thao tác</th>' : ''}</tr></thead><tbody>${dd.map((d, i) => `<tr><td>${i + 1}</td><td><b>${esc(d.desc || d.group)}</b><div class="xs muted">${esc(d.group)}</div></td><td class="num">${d.qty || 1}</td><td class="num">${F.vnd(d.unitPrice || d.amount)}</td><td class="num bold">${F.vnd(d.amount)}</td><td class="small">${esc(d.note || '')}${d.evidenceCount ? ' <span class="xs muted">(' + d.evidenceCount + ' ảnh)</span>' : ''}</td>${canEdit ? `<td>${U.iconBtn('pencil', 'ded-edit', 'Sửa', { 'data-id': d.id })}${U.iconBtn('trash', 'ded-rm', 'Xóa', { 'data-id': d.id }, 'red')}</td>` : ''}</tr>`).join('') || `<tr><td colspan="7" class="muted tc">Không khấu trừ</td></tr>`}</tbody><tfoot><tr><td colspan="4"><b>Tổng khấu trừ</b></td><td class="num blue bold">${F.vnd(k.ded)}</td><td colspan="2"></td></tr></tfoot></table>` })}
      ${U.card({ title: '4. Tổng hợp tính toán', icon: 'coins', body: `<div class="calc-row"><div class="calc-box"><div class="lb">Cọc giữ (ban đầu)</div><div class="vl">${F.vnd(rf.deposit)}</div></div><div class="op">−</div><div class="calc-box"><div class="lb">Tổng khấu trừ</div><div class="vl">${F.vnd(k.ded)}</div></div><div class="op">=</div><div class="calc-box pri"><div class="lb">Đề nghị hoàn</div><div class="vl">${F.vnd(k.refund)}</div></div></div><div class="ok-box mt12">${I('info')}<div><b>Số tiền hoàn bằng chữ</b><br>${esc(F.words(k.refund))}.</div></div>` })}</div>
    <aside class="side-stack">${U.card({ title: '5. Lịch sử duyệt', icon: 'history', actions: '<a class="link small" data-act="hist-all">Hiển thị tất cả</a>', body: U.timeline([{ key: 'draft', title: 'Tạo yêu cầu' }, { key: 'pending', title: 'Chờ duyệt' }, { key: 'approved', title: 'Đã duyệt' }, { key: 'refunded', title: 'Đã hoàn' }].map(s => { const h = at(s.key); const extra = s.key === 'pending' && (rf.status === 'needs_edit' || rf.status === 'rejected') ? at(rf.status) : null; return { when: h.at ? F.datetime(h.at) : '', title: s.title + (extra ? ' → ' + Q.label('refund', rf.status) : ''), sub: h.at ? esc(Q.userName(h.by)) + (h.note ? ' – ' + esc(h.note) : '') + (extra ? '<br>' + esc(Q.userName(extra.by)) + ': ' + esc(extra.note) : '') : 'Chưa thực hiện · ' + ({ pending: 'Chuyển đến quản lý để phê duyệt', approved: 'Sẽ được cập nhật khi phê duyệt', refunded: 'Sẽ được cập nhật khi hoàn tiền' })[s.key], color: h.at ? (s.key === 'refunded' || s.key === 'approved' ? 'green' : 'blue') : 'gray', fill: !!h.at }; })) })}
      ${U.card({ title: 'Ghi chú nội bộ', icon: 'clipboard-check', actions: U.btn({ label: 'Thêm ghi chú', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'note' }), body: (rf.notes || []).map(n => `<div class="note-it">${U.avatar(Q.userName(n.by))}<div class="grow"><div class="row between"><b class="blue">${esc(Q.userName(n.by))}</b><span class="xs muted">${F.datetime(n.at)}</span></div>${n.tag ? U.chip(n.tag, n.tag === 'Yêu cầu' ? 'amber' : 'gray') : ''}<div class="small mt4">${esc(n.text)}</div></div></div>`).join('') || '<div class="muted small">Chưa có ghi chú</div>' })}</aside></div>`;
    const dedModal = (d = {}) => { const m = U.modal({ title: d.id ? 'Sửa hạng mục khấu trừ' : 'Thêm hạng mục khấu trừ', size: 'sm', body: `${U.field({ label: 'Nhóm', input: U.select({ name: 'group', value: d.group || 'Sửa chữa', options: ['Khấu hao', 'Dịch vụ', 'Sửa chữa', 'Công nợ', 'Khác'] }) })}${U.field({ label: 'Hạng mục', req: true, input: U.input({ name: 'desc', value: d.desc || '', placeholder: 'Sơn lại tường phòng ngủ' }), cls: 'mt12' })}<div class="form-grid mt12">${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', value: d.qty || 1, type: 'number', attrs: { min: 1 } }) })}${U.field({ label: 'Đơn giá (VND)', input: U.money({ name: 'unitPrice', value: d.unitPrice || d.amount || '' }) })}</div>${U.field({ label: 'Ghi chú', input: U.input({ name: 'note', value: d.note || '' }), cls: 'mt12' })}${U.note('info', '', 'Số đã duyệt bị đổi → phải gửi duyệt lại (FR-FIN-07). Khấu trừ > 0 cần bằng chứng (FR-FIN-06).')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'refund-ded-save' } }) }); U.bind(m.el, { c: () => m.close(), s: () => { const v = m.data(); const list = dd.map(x => Object.assign({}, x)); const item = { group: v.group, desc: v.desc, qty: F.num(v.qty) || 1, unitPrice: v.unitPrice, amount: (F.num(v.qty) || 1) * F.num(v.unitPrice), note: v.note, evidenceCount: 1 }; if (d.id) { const i = list.findIndex(x => x.id === d.id); list[i] = Object.assign(list[i], item); } else list.push(item); X.saveRefundDeductions(rf.id, list); m.close(); ok('Đã cập nhật bảng khấu trừ'); } }); };
    const inspectModal = () => { const m = U.modal({ title: 'Cập nhật hiện trạng phòng ' + room.code, body: `<div class="col gap12">${INSPECT.map(([kk, l, opts]) => U.field({ label: l, input: U.select({ name: kk, value: insp[kk] || 'ok', options: [['ok', opts[0]], ['minor', opts[1]], ...(opts[2] ? [['major', opts[2]]] : [])] }) })).join('')}<div class="field"><label>Ảnh hiện trạng</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng)' })}</div></div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu hiện trạng', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const v = m.data(); const files = U.dzFiles(m.el, 'ph').map(f => f.name); const i2 = {}; INSPECT.forEach(([kk]) => i2[kk] = v[kk]); X.setRefundInspection(rf.id, { inspection2: i2, photos: (rf.photos || []).concat(files) }); m.close(); ok('Đã cập nhật hiện trạng'); } }); };
    U.bind(root, {
      edit: () => TH.go('#/refunds/new?id=' + rf.id + '&step=3'), submit: async () => { if (await U.confirm({ title: 'Gửi duyệt ' + rf.code + '?', ok: 'Gửi duyệt' })) { X.submitRefund(rf.id); ok('Đã gửi duyệt'); } }, approve: () => Fm.refundApprove(rf), reject: () => Fm.refundReject(rf), paid: () => Fm.refundPaid(rf), clean: async () => { if (await U.confirm({ title: 'Xác nhận dọn xong phòng ' + room.code + '?', ok: 'Xác nhận' })) { X.confirmCleaned(room.id); ok('Phòng đã Sẵn sàng'); } },
      zalo: () => { const recips = X.buildRecipients('refund_done', { refundId: rf.id }); const tpl = St.one('zaloTemplates', x => x.eventKey === 'refund_done'); const b = X.createZaloBatch({ name: 'Thông báo hoàn cọc ' + rf.code, eventKey: 'refund_done', sourceKey: 'refund_done', templateId: tpl.id, recipients: recips, sendMode: 'now', key: 'rfz:' + rf.id }); ok(b.duplicate ? 'Đã gửi trước đó' : 'Đã tạo đợt gửi ' + b.code); if (!b.duplicate) TH.go('#/zalo/batches/' + b.id); },
      'req-edit': async () => { const r = await U.confirm({ title: 'Yêu cầu chỉnh sửa hồ sơ ' + rf.code, text: 'Hồ sơ chuyển sang Cần chỉnh sửa, người lập sửa khấu trừ/hiện trạng rồi gửi duyệt lại (SRS §6).', body: U.field({ label: 'Nội dung cần chỉnh sửa', req: true, input: U.textarea({ name: 'reason', placeholder: 'Bổ sung ảnh và báo giá hạng mục sơn tường…' }) }), ok: 'Gửi yêu cầu' }); if (r) { X.requestRefundEdit(rf.id, r.reason); ok('Đã yêu cầu chỉnh sửa'); } },
      note: async () => { const r = await U.confirm({ title: 'Thêm ghi chú nội bộ', body: U.field({ label: 'Nội dung', input: U.textarea({ name: 'text', rows: 4 }) }), ok: 'Lưu' }); if (r && r.text) { X.addRefundNote(rf.id, r.text); ok('Đã thêm ghi chú'); } }, 'hist-all': () => U.modal({ title: 'Lịch sử xử lý ' + rf.code, body: U.timeline(hist.map(h => ({ when: F.datetime(h.at), title: Q.label('refund', h.status), sub: Q.userName(h.by) + (h.note ? ' – ' + h.note : ''), color: 'blue', fill: true }))) }), photos: () => U.modal({ title: 'Hình ảnh hiện trạng (' + (rf.photos || []).length + ')', body: `<div class="photo-grid">${(rf.photos || []).map(ph => `<div class="photo" title="${esc(ph)}"></div>`).join('') || '<span class="muted">Chưa có ảnh</span>'}</div>` }), inspect: () => inspectModal(),
      'ded-add': () => dedModal(), 'ded-edit': (el) => dedModal(St.get('refundDeductions', el.dataset.id)), 'ded-rm': async (el) => { if (await U.confirm({ title: 'Xóa hạng mục?', ok: 'Xóa', danger: true })) { X.saveRefundDeductions(rf.id, dd.filter(x => x.id !== el.dataset.id)); ok('Đã xóa'); } },
      more: (el) => U.menu(el, [{ label: 'Tải hồ sơ', icon: 'download', onClick: () => U.fakePdf('Ho so hoan coc ' + rf.code, ['Khách: ' + t.name, 'Phòng: ' + room.code, 'Cọc: ' + F.vnd(rf.deposit), ...dd.map(d => '- ' + d.desc + ' ' + F.vnd(d.amount)), 'Hoàn: ' + F.vnd(k.refund)]) }, { label: 'Xem khách thuê', icon: 'user', onClick: () => TH.go('#/tenants/' + t.id) }, { label: 'Xem phòng', icon: 'door', onClick: () => TH.go('#/rooms/' + room.id) }]),
    });
  };
  if (rt) rt.handler = (root, p, q) => (TH.phase.on(2) ? refundP2 : p1Refund)(root, p, q);
})(window.TH);
