(function (TH) {
  const S = TH.store, Q = TH.q, X = TH.actions, F = TH.f, U = TH.ui, K = TH.kit, FC = TH.calc.forecast, esc = F.esc;
  const inputLabels = { J3: 'Mua sắm thiết bị', J4: 'Hóa đơn đã thu', J5: 'Phòng mới đã thu', J6: 'Dự thu nợ hóa đơn', J7: 'Dự thu nợ phòng mới', E4: 'Cọc mới', G4: 'Hoàn cọc' };
  TH.pages.forecastDrawer = (period = S.meta.period, draftDate = period + '-' + String(Q.param('forecastDraftDay')).padStart(2, '0'), excluded = []) => {
    const auto = Q.forecastAuto(period, draftDate, { excluded }), codeOf = id => (Q.building(id) || {}).code, newCodes = Q.forecastNewBuildings(period).map(b => b.code);
    const drawer = K.formDrawer({ title: 'Tạo phiên bản dự kiến – ' + F.periodLabel(period), sub: 'Phiên bản cũ giữ nguyên; lưu một bộ đầu vào cho hai kết quả', wide: true, note: U.note('info', 'Gợi ý đến ' + F.date(draftDate), 'Tỷ lệ thu nợ sau ngày lập kỳ trước: ' + F.pctv(auto.recoveryRate) + '. Chọn ngày lập và phạm vi tòa trước khi nhập: đổi một trong hai sẽ lấy lại gợi ý. Đổi giá trị cần lý do chung hoặc lý do riêng từng dòng.'), fields: [
      { name: 'draftDate', label: 'Ngày lập', type: 'date', value: draftDate, req: true },
      { name: 'excluded', label: 'Loại trừ tòa (mã, cách nhau dấu phẩy)', value: excluded.map(codeOf).join(', '), help: (newCodes.length ? 'Tòa mới nhận trong kỳ: ' + newCodes.join(', ') + ' (Excel "Tính đến G15"). ' : '') + 'Phạm vi: ' + auto.scopeNote, span: true }, { name: 'reason', label: 'Lý do chung khi khác gợi ý', type: 'textarea', span: true },
      ...Object.entries(inputLabels).flatMap(([key, label]) => [{ name: key, label: key + ' · ' + label, type: 'money', value: auto.inputs[key], help: 'Gợi ý ' + F.vnd(auto.inputs[key]) }, { name: 'reason_' + key, label: 'Lý do ' + key }]),
      { name: 'E4parts', label: 'Các phần cọc E4 (phân cách bởi dấu ;)', help: 'Ví dụ: 245700000; 83150000; 317900000; 75950000', span: true },
      ...FC.LINES.filter(l => !['refund', 'cost_equip'].includes(l.key)).flatMap(l => [{ name: 'line_' + l.key, label: l.label, type: 'money', value: auto.lines.find(x => x.key === l.key).value }, { name: 'lineReason_' + l.key, label: 'Lý do ' + l.label }]),
      { name: 'adjustment', label: 'Điều chỉnh doanh thu (+/−)', type: 'number', value: 0 }, { name: 'adjustmentReason', label: 'Lý do điều chỉnh' }],
      onSubmit: d => {
        const inputs = Object.fromEntries(Object.keys(inputLabels).map(k => [k, F.num(d[k])])), inputMeta = Object.fromEntries(Object.keys(inputLabels).map(k => [k, { reason: d['reason_' + k] }]));
        inputs.E4parts = String(d.E4parts || '').split(';').filter(x => x.trim()).map(x => ({ amount: F.num(x) }));
        const lines = FC.LINES.filter(l => !['refund', 'cost_equip'].includes(l.key)).map(l => ({ key: l.key, value: F.num(d['line_' + l.key]), reason: d['lineReason_' + l.key] }));
        const amount = Number(d.adjustment || 0), rec = X.createForecast({ period, draftDate, excludedBuildings: auto.excludedBuildings, inputs, inputMeta, lines, reason: d.reason, adjustments: amount ? [{ amount, reason: d.adjustmentReason }] : [] });
        U.toast('ok', 'Đã tạo v' + rec.version); TH.go('#/reports/forecast?period=' + period + '&version=' + rec.id + '&mode=web');
      } });
    drawer.el.querySelector('[name=draftDate]').addEventListener('change', e => { const date = e.target.value; if (date.slice(0, 7) !== period) { U.setErrors(drawer.el, { draftDate: 'Ngày lập phải thuộc kỳ dự kiến' }); return; } drawer.close(); TH.pages.forecastDrawer(period, date, excluded); });
    drawer.el.querySelector('[name=excluded]').addEventListener('change', e => {
      const codes = String(e.target.value || '').split(/[,;\s]+/).map(x => x.trim().toUpperCase()).filter(Boolean), ids = codes.map(c => (S.all('buildings').find(b => b.code.toUpperCase() === c) || {}).id);
      if (ids.some(id => !id)) { U.setErrors(drawer.el, { excluded: 'Không có tòa: ' + codes.filter((c, i) => !ids[i]).join(', ') }); return; }
      drawer.close(); TH.pages.forecastDrawer(period, drawer.el.querySelector('[name=draftDate]').value || draftDate, [...new Set(ids)]);
    });
    return drawer;
  };
  const resultPanel = (label, v) => U.card({ title: label, body: `<div class="grid grid-3">${[['DT', v.rev_total], ['TCP', v.tcp], ['LN', v.lnr]].map(([k, n]) => `<div><small class="muted">${k}</small><h3>${F.vnd(n)}</h3></div>`).join('')}</div><p class="small mt12">LNR/DT <b>${F.pctv(v.r_lnr_dt, 2)}</b> · LNR/GV <b>${F.pctv(v.r_lnr_gv, 2)}</b> · GV ${F.vnd(v.gv)}</p>` });
  TH.router.handle('/reports/forecast', (root, p, q) => {
    const period = q.period || Q.forecastLatestPeriod() || S.meta.period, versions = Q.forecasts(period), fc = versions.find(f => f.id === q.version) || versions[0], mode = q.mode === 'web' || q.mode === 'excel' ? q.mode : fc && fc.source === 'web' ? 'web' : 'excel', codong = TH.auth.role() === 'codong';
    // Cổ đông (CH-23) chỉ xem dự kiến; không so sánh với số thực tế toàn hệ thống (ngoài phạm vi tòa góp vốn), không xuất
    const tabs = [{ key: 'dau-vao', label: 'Đầu vào' }, { key: 'chi-phi', label: 'Chi phí (24 dòng)' }, { key: 'ket-qua', label: 'Kết quả' }, ...(codong ? [] : [{ key: 'so-sanh', label: 'So sánh thực tế' }]), { key: 'phien-ban', label: 'Phiên bản' }], tab = K.pickTab(tabs, q.tab, 'dau-vao');
    root.innerHTML = U.pageHead({ title: 'Dự kiến lợi nhuận', sub: 'SRC-14 · ' + (fc ? 'v' + fc.version + ' · ' + F.date(fc.draftDate) + ' · ' + fc.scopeNote : 'Chưa có bản dự kiến'), acts: [U.btn({ label: 'Tạo phiên bản', act: 'create', icon: 'plus', cls: 'btn-primary', perm: 'forecast.manage' }), fc && !codong ? U.btn({ label: 'Xuất theo SRC-14', act: 'exp', icon: 'download' }) : ''] })
      + K.filters([{ name: 'period', label: 'Kỳ', options: [...new Set([...S.all('periods').map(p => p.id), ...Q.forecasts().map(f => f.period)])].sort().map(p => [p, F.periodLabel(p)]), value: period, all: false }, { name: 'version', label: 'Phiên bản', options: versions.map(f => [f.id, 'v' + f.version + ' · ' + f.source + ' · ' + F.date(f.draftDate)]), value: fc ? fc.id : '', all: false }, { name: 'mode', label: 'Cách tính', options: [['excel', 'Như Excel'], ['web', 'Theo web (khấu hao tài sản)']], value: mode, all: false }], q)
      + '<div class="mt16 mb16">' + U.note('info', 'Một bộ đầu vào → hai kết quả', 'Dự kiến chưa công bố là số chuẩn. Không drill theo tòa: SRC-14 không chia số theo tòa (GĐ-P3-06).' + (codong ? ' Số dự kiến là toàn hệ thống trong phạm vi bản lập, không riêng tòa góp vốn của bạn.' : '')) + (mode === 'excel' ? U.note('warn', 'Chế độ như Excel', 'Tái hiện cách tính của sheet, kể cả lỗi đã ghi nhận (khấu hao chỉ J3 × 1,6%, không cộng dồn) – không phải số chuẩn. Chọn "Theo web" để xem theo GĐ OQ-11/OQ-19.') : '') + '</div>';
    K.bindFilters(root, ['mode']);
    if (!fc) { root.insertAdjacentHTML('beforeend', U.empty({ title: 'Chưa có bản dự kiến cho kỳ này', text: 'Tạo phiên bản từ gợi ý giao dịch web.' })); U.bind(root, { create: () => TH.pages.forecastDrawer(period) }); return; }
    const result = Q.forecastResult(fc, mode), comparison = codong ? null : Q.forecastVsActual(fc.id, mode);
    root.insertAdjacentHTML('beforeend', '<div class="grid grid-2 mb16">' + resultPanel('Dòng tiền', result.total) + resultPanel('Kinh doanh', result.business) + '</div>' + U.chip(result.benchmark === true ? 'Khớp Excel (' + (fc.form === 'cash' ? 'dòng tiền' : 'kinh doanh') + ')' : result.benchmark === false ? 'Lệch benchmark Excel' : 'Không có benchmark Excel', result.benchmark ? 'green' : 'gray') + (result.legacy ? U.note('info', 'Cách tính sheet dòng tiền cũ', 'Chế độ như Excel dùng J3 × 1,6% để tái hiện nguồn. Chế độ web trừ đủ J3 và hoàn cọc khỏi dòng tiền.') : '') + U.tabs(tabs, tab) + '<div id="fcbody" class="mt16"></div>'); U.bind(root, { tab: el => TH.router.setQuery({ tab: el.dataset.key }) }); const body = root.querySelector('#fcbody');
    if (tab === 'dau-vao') body.innerHTML = U.card({ title: 'Đầu vào, nguồn và lý do', body: `<table class="tbl compact"><thead><tr><th>Ô</th><th>Ý nghĩa</th><th class="num">Giá trị</th><th>Gợi ý / nguồn</th><th>Lý do</th></tr></thead><tbody>${Object.entries(inputLabels).map(([k, label]) => { const meta = (fc.inputMeta || {})[k] || {}; return `<tr><td class="code">${k}</td><td>${label}</td><td class="num">${F.vnd(fc.inputs[k])}</td><td>${meta.suggested == null ? '' : F.vnd(meta.suggested) + '<br>'}${esc(meta.source_ref || '')}<small class="d-block muted">${esc(meta.formula || '')}</small></td><td>${esc(meta.reason || 'Theo nguồn')}${(meta.adjustments || []).map(a => '<small class="d-block muted">' + F.vnd(a.amount) + ' · ' + esc(a.reason) + '</small>').join('')}</td></tr>`; }).join('')}</tbody></table><p class="small mt16">Các phần E4: ${(fc.inputs.E4parts || []).map(p => F.vnd(p.amount)).join(' + ') || 'Không tách phần'}</p>${(fc.adjustments || []).map(a => U.note('info', 'Điều chỉnh ' + F.vnd(a.amount), esc(a.reason))).join('')}` });
    if (tab === 'chi-phi') body.innerHTML = U.card({ title: '24 dòng theo mẫu SRC-14', body: `<table class="tbl compact"><thead><tr><th>Dòng / mã báo cáo</th><th class="num">Giá trị</th><th class="num">Gợi ý / chênh</th><th>Nguồn / công thức / lý do</th></tr></thead><tbody>${FC.LINES.map(l => { const line = fc.lines.find(x => x.key === l.key) || {}; const value = l.key === 'cost_equip' ? result.dep : l.key === 'marketing' ? result.marketing : Number(line.value || 0); return `<tr><td>${esc(l.label)}<small class="d-block code">${l.reportCode}</small></td><td class="num">${F.vnd(value)}</td><td class="num">${line.suggested == null ? '–' : F.vnd(line.suggested) + '<br>' + F.vnd(value - line.suggested)}</td><td>${esc(line.source_ref || '')}<small class="d-block muted">${esc(line.formula || (l.key === 'cost_equip' ? mode === 'excel' ? 'J3 × 1,6%' : 'Khấu hao tài sản cộng dồn' : ''))}</small>${esc(line.reason || '')}</td></tr>`; }).join('')}</tbody></table>` });
    if (tab === 'ket-qua') body.innerHTML = U.card({ title: 'Chỉ số phụ (SRC-14 sheet 8/2025)', sub: 'TCP/DT = tiền nhà + DV + lương + CPPS + HC; LN/DT = 100% − TCP/DT', body: `<table class="tbl compact"><thead><tr><th>Chỉ số</th><th class="num">Dòng tiền</th><th class="num">Kinh doanh</th><th>Mốc</th></tr></thead><tbody>${result.ratios.total.map((r, i) => { const b = result.ratios.business[i]; return `<tr><td>${esc(r.label)}</td><td class="num">${F.pctv(r.value, 2)}</td><td class="num">${r.key === 'hc' ? '–' : F.pctv(b.value, 2)}</td><td class="muted">${esc(r.ref || '')}</td></tr>`; }).join('')}</tbody></table>` });
    if (tab === 'so-sanh') body.innerHTML = comparison.available ? U.note('info', 'Phạm vi: ' + fc.scopeNote, comparison.note) + ['total', 'business'].map(k => U.card({ title: k === 'total' ? 'So với UI-29' : 'So với UI-30', body: `<table class="tbl compact"><thead><tr><th>Chỉ tiêu</th><th class="num">Dự kiến</th><th class="num">Thực tế</th><th class="num">Chênh</th></tr></thead><tbody>${comparison[k].map(r => `<tr><td>${esc(r.key)}</td><td class="num">${r.key.startsWith('r_') ? F.pctv(r.forecast) : F.vnd(r.forecast)}</td><td class="num">${r.key.startsWith('r_') ? F.pctv(r.actual) : F.vnd(r.actual)}</td><td class="num">${r.key.startsWith('r_') ? F.pctv(r.diff) : F.vnd(r.diff)}</td></tr>`).join('')}</tbody></table>` })).join('<div class="mt16"></div>') : U.empty({ title: comparison.reason });
    if (tab === 'phien-ban') body.innerHTML = U.card({ title: 'Các phiên bản bất biến', body: versions.map(v => `<div class="mini-row"><a href="#/reports/forecast?period=${period}&version=${v.id}&tab=dau-vao&mode=${v.source === 'web' ? 'web' : 'excel'}">v${v.version} · ${F.date(v.draftDate)}</a><span>${esc(v.source)} · ${esc(v.scopeNote)}</span></div>`).join('') });
    K.wrapTables(root);
    U.bind(root, { create: () => TH.pages.forecastDrawer(period), exp: () => K.xls('du-kien-' + period + '-v' + fc.version + '.xls', 'DỰ KIẾN LỢI NHUẬN', ['SRC-14 · ' + fc.scopeNote, period + ' · v' + fc.version + ' · ' + mode, 'Ngày lập ' + fc.draftDate], ['Ô / mã', 'Chỉ tiêu', 'Giá trị', 'Nguồn / lý do'], [...Object.entries(inputLabels).map(([k, label]) => [k, label, fc.inputs[k], ((fc.inputMeta || {})[k] || {}).reason || ((fc.inputMeta || {})[k] || {}).source_ref || '']), ...FC.LINES.map(l => [l.reportCode, l.label, l.key === 'cost_equip' ? result.dep : l.key === 'marketing' ? result.marketing : Number((fc.lines.find(x => x.key === l.key) || {}).value || 0), (fc.lines.find(x => x.key === l.key) || {}).reason || '']), ...['total', 'business'].flatMap(k => ['rev_total', 'tcp', 'lnr'].map(c => [k, c, result[k][c], '']))]) });
  });
})(window.TH);
