/* UI-28: contract-month CF/AC, actual payment dates and prepaid costs are separate views. */
(function(TH){
  const F=TH.f,U=TH.ui,St=TH.store,Q=TH.q,X=TH.actions,esc=F.esc;
  const money=n=>n==null?'—':F.vnd(n);
  const month=d=>String(d||'').slice(0,7);
  const months=(start,end)=>{if(!/^\d{4}-\d{2}/.test(start||'')||!/^\d{4}-\d{2}/.test(end||''))return [];const out=[];let y=Number(start.slice(0,4)),m=Number(start.slice(5,7));for(let i=0;i<120&&`${y}-${String(m).padStart(2,'0')}`<=month(end);i++){out.push(`${y}-${String(m).padStart(2,'0')}`);m++;if(m===13){m=1;y++;}}return out;};
  const selectedLease=(buildingId,leases)=>leases.find(c=>(c.buildingIds||[]).includes(buildingId));
  const cfOf=(c,index,buildingId)=>{const free=Array.isArray(c.freeMonths)?c.freeMonths.includes(index+1):index<Number(c.freeMonths||c.rentFreeMonths||0),pct=c.allocations?.[buildingId]??((c.buildingIds||[]).length===1?100:0);return free?0:(Number(c.rent)||0)*Number(pct)/100;};
  const model=(c,payments,year,buildingId)=>{
    const allMonths=months(c?.rentStart||c?.start,c?.end),known=allMonths.length>0,annual=known?allMonths.filter(p=>p.startsWith(year+'-')):payments.filter(x=>x.period?.startsWith(year+'-')).map(x=>x.period);
    const ac=known?F.sum(allMonths,(p,i)=>cfOf(c,i,buildingId))/allMonths.length:null;
    let cumulative=0;
    const rows=[...new Set(annual)].sort().map(p=>{const idx=allMonths.indexOf(p),cf=known?cfOf(c,idx,buildingId):(payments.find(x=>x.period===p)?.amount??null),paid=payments.filter(x=>x.status==='paid'&&month(x.paidDate)===p),actual=paid.length?F.sum(paid,x=>Number(x.paidAmount||x.amount)||0):null;if(cf!=null&&ac!=null)cumulative+=cf-ac;return {period:p,contractRent:c?.rent||null,free:known&&cf===0,cf,ac,actual,prepaid:ac==null?null:cumulative};});
    return {rows,known,ac};
  };
  TH.router.register('/head-lease-costs',(root,p,q)=>{
    TH.router.crumb([{label:'Tài chính'},{label:'Tiền thuê nhà & trả trước'}]);
    const buildings=St.where('buildings',b=>!b.stub&&!b.summaryOnly),buildingId=q.buildingId||buildings[0]?.id||'',year=q.year||St.state.meta.period.slice(0,4),b=Q.building(buildingId),leases=St.where('landlordContracts',c=>(c.buildingIds||[]).includes(buildingId)),lc=selectedLease(buildingId,leases),payments=St.where('landlordPayments',x=>x.buildingId===buildingId&&(x.landlordContractId===lc?.id||!x.landlordContractId)),prepaid=St.where('expenses',x=>x.buildingId===buildingId&&Number(x.prepaidMonths)>0),m=model(lc,payments,year,buildingId),canPay=TH.auth.can('landlordPayments.manage');
    const shares=St.where('buildingShares',x=>x.buildingId===buildingId&&x.status==='active');
    root.innerHTML=`${U.pageHead({title:'Tiền thuê nhà & chi phí trả trước',sub:'UI-28 · Tách chi phí theo tháng hợp đồng, phân bổ kinh doanh và ngày chuyển tiền thực tế.',chips:TH.params.chip('P-15')+TH.params.chip('P-23')+TH.params.chip('P-29'),acts:[lc&&canPay&&m.known?U.btn({label:'Sinh lịch trả',icon:'calendar',cls:'btn-primary',act:'generate'}):'',U.btn({label:'Xuất CSV',icon:'download',cls:'btn-outline',act:'export'})]})}
      ${U.filterbar([U.field({label:'Tòa',input:U.select({name:'buildingId',value:buildingId,options:buildings.map(x=>[x.id,x.name]),attrs:{'data-on':'f'}})}),U.field({label:'Năm',input:U.select({name:'year',value:year,options:[[year,year],['2026','2026'],['2027','2027']],attrs:{'data-on':'f'}})})])}
      ${lc?U.note('info','HĐ đầu vào '+esc(lc.code),`Tiền thuê theo nguồn: <b>${money(lc.rent)} đ/tháng</b> · Chu kỳ trả ${lc.cycleMonths||'—'} tháng · Chủ nhà ${esc((St.get('landlords',lc.landlordId)||{}).name||'chưa có')}. ${m.known?'Thời hạn đã nhập: '+F.date(lc.start)+' – '+F.date(lc.end):'Sổ nguồn G1 không cung cấp ngày bắt đầu/kết thúc HĐ, tháng miễn, lịch trả hoặc ngày chi; không tự suy diễn AC và hạn trả.'}`):U.empty({title:'Chưa có hợp đồng đầu vào',text:'Chọn tòa có HĐ để xem CF, AC và lịch trả.'})}
      <div class="grid grid-3 mb16">${U.kpi({label:'CF theo tháng HĐ đang hiển thị',value:money(F.sum(m.rows,x=>x.cf||0)),icon:'home',tone:'blue'})}${U.kpi({label:'AC mỗi tháng',value:money(m.ac),icon:'file-text',tone:'purple'})}${U.kpi({label:'Trả trước phân bổ tháng',value:money(F.sum(prepaid,x=>Number(x.prepaidMonthly)||0)),icon:'calendar',tone:'amber'})}</div>
      ${U.card({title:'①–⑤ Ba cột đối chiếu · '+year,sub:'CF là chi phí theo tháng HĐ; AC dàn đều cả tháng miễn; lịch trả thực tế là sổ quỹ riêng.',body:m.rows.length?`<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Tháng</th><th class="num">Tiền thuê HĐ</th><th class="num">CF theo tháng</th><th class="num">AC dàn đều</th><th class="num">Đã chuyển thực tế</th><th class="num">Chênh CF − AC lũy kế</th></tr></thead><tbody>${m.rows.map(x=>`<tr><td><b>${F.periodLabel(x.period)}</b></td><td class="num">${x.free?'MIỄN':money(x.contractRent)}</td><td class="num">${money(x.cf)}</td><td class="num">${money(x.ac)}</td><td class="num">${money(x.actual)}</td><td class="num">${money(x.prepaid)}</td></tr>`).join('')}</tbody></table></div>`:U.empty({title:'Chưa có tháng HĐ trong năm này',text:'Nguồn không đủ ngày hiệu lực để lập dãy tháng. Kỳ đã có trong sheet vẫn hiển thị khi chọn năm tương ứng.'})})}
      ${U.card({title:'⑥ Cách đọc ba cột',cls:'mt16',body:'<div class="small">• CF ghi theo <b>tháng hợp đồng</b>, tháng miễn bằng 0.<br>• AC dàn đều tổng tiền thuê suốt thời hạn HĐ, kể cả tháng miễn.<br>• Cột đã chuyển thực tế chỉ lấy phiếu <b>đã trả</b> trong sổ quỹ, không phải chi phí tháng.<br>• Chênh CF − AC lũy kế là khoản trả trước cần đối chiếu; để trống khi HĐ nguồn thiếu thời hạn.</div>'})}
      ${U.card({title:'⑦ Lịch đóng tiền và nghĩa vụ cổ đông',cls:'mt16',sub:'Góp thiếu không chặn công ty trả chủ nhà. Ngày đến hạn chưa có từ nguồn được giữ trống.',body:payments.length?`<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Kỳ / nguồn</th><th>Hạn trả</th><th class="num">Phải trả</th><th class="num">Đã trả</th><th>Trạng thái</th><th>Cổ đông phải góp tại hạn</th><th></th></tr></thead><tbody>${payments.map(x=>`<tr><td><b>${esc(x.periodLabel||x.code||'Kỳ trả')}</b></td><td>${x.dueDate?F.date(x.dueDate):'Chưa có trong nguồn'}</td><td class="num">${money(x.amount)}</td><td class="num">${x.status==='paid'?money(x.paidAmount||x.amount):'—'}</td><td>${U.chip(x.status==='paid'?'Đã trả':x.status==='unconfirmed'?'Chưa xác nhận lịch trả':'Chờ trả',x.status==='paid'?'green':'amber')}</td><td class="small">${x.dueDate&&shares.length?shares.map(s=>`${esc((St.get('shareholders',s.shareholderId)||{}).name||'?')} ${s.percentage}% = ${money(Number(x.amount)*Number(s.percentage)/100)}`).join('<br>'):'Chưa có hạn trả / tỷ lệ hiệu lực'}</td><td>${canPay&&x.dueDate&&x.status!=='paid'?U.btn({label:'Ghi đã trả',cls:'btn-outline',size:'btn-sm',act:'paid',attrs:{'data-id':x.id}}):''}</td></tr>`).join('')}</tbody></table></div>`:U.empty({title:'Chưa có lịch trả',text:'HĐ chưa được sinh lịch hoặc nguồn chưa cung cấp kỳ trả.'})})}
      ${U.card({title:'Chi phí trả trước khác',cls:'mt16',sub:'Số gốc và phân bổ tháng từ chứng từ; không coi ngày ghi sổ là ngày chuyển tiền nếu nguồn không có.',body:prepaid.length?`<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Khoản mục</th><th>Ngày ghi nhận</th><th class="num">Số gốc</th><th class="num">Thời hạn</th><th class="num">Phân bổ / tháng</th></tr></thead><tbody>${prepaid.map(x=>`<tr><td><b>${esc(x.desc)}</b></td><td>${x.docDate?F.date(x.docDate):'Chưa có trong nguồn'}</td><td class="num">${money(x.amount)}</td><td class="num">${x.prepaidMonths} tháng</td><td class="num">${money(x.prepaidMonthly)}</td></tr>`).join('')}</tbody></table></div>`:U.empty({title:'Chưa có khoản trả trước trong nguồn'})})}
      ${U.card({title:'⑧ Phân bổ HĐ nhiều tòa',cls:'mt16',body:lc?`<div class="small">${(lc.buildingIds||[]).map(id=>`${esc(Q.building(id).name||'Tòa chưa rõ')} · ${lc.allocations?.[id]!=null?lc.allocations[id]+'%':(lc.buildingIds.length===1?'100%':'Chưa phân bổ')}`).join(' &nbsp; | &nbsp; ')||'Chưa gắn tòa'} ${lc.buildingIds?.length>1?TH.params.chip('P-15'):''}</div>${canPay&&lc.buildingIds?.length>1?U.btn({label:'Đổi tỷ lệ có lý do',cls:'btn-outline',size:'btn-sm',act:'alloc'}):''}`:U.empty({title:'Chưa chọn HĐ'})})}`;
    U.onChange(root,{f:()=>{TH.router.replaceQuery(U.formData(root.querySelector('.filterbar')));TH.router.refresh();}});
    U.bind(root,{
      export:()=>F.download('tien-thue-nha-'+(b.code||'toa')+'-'+year+'.csv',F.csv(m.rows.map(x=>[x.period,x.contractRent,x.cf,x.ac,x.actual,x.prepaid]),['Tháng','Tiền thuê HĐ','CF theo tháng','AC dàn đều','Đã chuyển thực tế','Chênh lũy kế']),'text/csv'),
      generate:()=>{if(!lc||!m.known)return;const made=X.generateLandlordSchedule(lc.id);U.toast('ok','Đã kiểm tra lịch trả',made.length+' kỳ mới; kỳ trùng được giữ nguyên');TH.router.refresh();},
      paid:el=>{const row=St.get('landlordPayments',el.dataset.id);if(row)TH.forms.landlordPaid(row);},
      alloc:()=>{if(!lc)return;const ids=lc.buildingIds||[];const body=ids.map(id=>U.field({label:Q.building(id).name+' (%)',input:U.input({name:'p_'+id,type:'number',value:lc.allocations?.[id]??'',attrs:{min:0,max:100,step:0.01}})})).join('')+U.field({label:'Lý do / phụ lục',req:true,input:U.input({name:'reason'})});const dialog=U.modal({title:'Phân bổ tiền thuê nhiều tòa',body,footer:U.btn({label:'Lưu tỷ lệ',cls:'btn-primary',act:'save'})});U.bind(dialog.el,{save:()=>{const d=dialog.data(),vals=Object.fromEntries(ids.map(id=>[id,Number(d['p_'+id])]));const sum=F.sum(Object.values(vals));if(!d.reason?.trim()||Math.abs(sum-100)>0.001||Object.values(vals).some(v=>!Number.isFinite(v)||v<0))return U.toast('err','Tỷ lệ phải đủ 100% và có lý do');St.update('landlordContracts',lc.id,{allocations:vals});St.audit('allocate','landlordContract',lc.id,'Đổi tỷ lệ phân bổ tiền thuê',{reason:d.reason.trim(),allocations:vals});dialog.close();TH.router.refresh();}});}
    });
  },{menu:'head-lease-costs',permission:'headLeaseCosts.view'});
})(window.TH);
