/* Phase 3 – Nhân sự: Danh sách NV (#/hr – PNG 07/01), Chi tiết NV (#/hr/:id – PNG 07/02), Chấm công (#/hr/timesheet – tự thiết kế), Lương thưởng (#/hr/payroll – tự thiết kế) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, C = TH.chart, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const liveB = () => St.where('buildings', b => !b.stub);
  const deptOpts = () => Object.entries(Q.L.dept).map(([k, v]) => [k, v[0]]);
  const titleOpts = () => Object.keys(Q.L.title);
  const areaOpts = () => [...new Set(St.all('employees').map(e => e.area).filter(Boolean).concat(['Tất cả khu vực']))];
  const canManage = () => TH.auth.can('hr.manage');
  const shortMail = (m) => { if (!m) return '-'; const [u, d] = m.split('@'); return `<span title="${esc(m)}">${esc(u.slice(0, 8) + (u.length > 8 ? '…' : '') + '@' + (d || '').slice(0, 5) + '…')}</span>`; };

  /* ---- Forms ---- */
  Fm.employee = (e = {}, opts = {}) => {
    const managers = St.where('employees', x => x.id !== e.id && x.status !== 'resigned' && ['Quản lý khu vực', 'Trưởng nhóm'].includes(x.title));
    const m = U.drawer({ title: e.id ? 'Chỉnh sửa ' + e.code : 'Thêm nhân viên', sub: 'Hồ sơ: phòng ban, chức danh, ngày vào làm, thâm niên, trạng thái (FR-HR-01/03)', body: `<div class="form-grid">${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name', value: e.name || '', placeholder: 'Nguyễn Văn A' }), cls: 'span2' })}${U.field({ label: 'Phòng ban', req: true, input: U.select({ name: 'dept', value: e.dept || '', placeholder: 'Chọn phòng ban', options: deptOpts() }) })}${U.field({ label: 'Chức danh', req: true, input: U.select({ name: 'title', value: e.title || '', placeholder: 'Chọn chức danh', options: titleOpts() }) })}${U.field({ label: 'Số điện thoại', req: true, input: U.input({ name: 'phone', value: e.phone || '', placeholder: '0901 234 567' }), help: 'Trùng SĐT với nhân viên khác sẽ bị chặn' })}${U.field({ label: 'Email', input: U.input({ name: 'email', value: e.email || '', placeholder: 'ten@timohouse.vn' }) })}${U.field({ label: 'Địa chỉ', input: U.input({ name: 'address', value: e.address || '' }), cls: 'span2' })}${U.field({ label: 'Hình thức làm việc', input: U.select({ name: 'workType', value: e.workType || 'Toàn thời gian', options: ['Toàn thời gian', 'Bán thời gian', 'Cộng tác viên', 'Thời vụ'] }) })}${U.field({ label: 'Quản lý trực tiếp', input: U.select({ name: 'managerId', value: e.managerId || '', all: 'Không', options: managers.map(x => [x.id, x.name + ' – ' + x.title]) }) })}${U.field({ label: 'Ngày vào làm', req: true, input: U.date({ name: 'startDate', value: e.startDate || F.today() }) })}${U.field({ label: 'Ngày hết thử việc', input: U.date({ name: 'probationEnd', value: e.probationEnd || '' }), help: 'Có ngày hết thử việc ≥ hôm nay → trạng thái Thử việc' })}${U.field({ label: 'Khu vực phụ trách', input: U.input({ name: 'area', value: e.area || '', placeholder: 'Khu Q.7 / Tất cả khu vực', attrs: { list: 'hr-areas' } }) })}<datalist id="hr-areas">${areaOpts().map(a => `<option value="${esc(a)}">`).join('')}</datalist>${canManage() ? U.field({ label: 'Lương cơ bản (VND)', input: U.money({ name: 'salaryBase', value: e.salaryBase || '' }), help: 'Chỉ Nhân sự/Admin thấy (AC-FR-HR-01-2)' }) : ''}${canManage() ? U.field({ label: 'Phụ cấp chức danh (VND)', input: U.money({ name: 'titleAllowance', value: e.titleAllowance || '' }) }) : ''}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: e.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: e.id ? 'Lưu thay đổi' : 'Thêm nhân viên', icon: 'user-plus', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'emp-save' } }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = e.id; const r = X.saveEmployee(d); m.close(); ok((e.id ? 'Đã cập nhật ' : 'Đã thêm nhân viên ') + r.code, r.name); opts.after && opts.after(r); } });
  };
  const assignModal = (e) => {
    const m = U.modal({ title: 'Phân công tòa nhà – ' + esc(e.name), sub: 'Lịch sử phân công theo thời gian (FR-BLD-07)', body: `${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', placeholder: 'Chọn tòa', options: liveB().filter(b => !Q.assignmentsOf(e.id).some(a => a.buildingId === b.id)).map(b => [b.id, b.name]) }) })}${U.field({ label: 'Vai trò phụ trách', req: true, input: U.select({ name: 'role', value: e.dept === 'baotri' ? 'tech' : e.title === 'Quản lý khu vực' || e.dept === 'kinhdoanh' ? 'lead' : 'ops', options: Object.entries(Q.L.assignRole).map(([k, v]) => [k, v[0]]) }), cls: 'mt12' })}${U.field({ label: 'Ngày bắt đầu', input: U.date({ name: 'start', value: F.today() }), cls: 'mt12' })}<div class="mt12">${U.check({ name: 'primary', label: 'Tòa chính (phụ trách chính)', checked: !Q.assignmentsOf(e.id).length })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Phân công', icon: 'building', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'emp-assign-save' } }) });
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); X.assignBuilding({ employeeId: e.id, buildingId: d.buildingId, role: d.role, primary: d.primary, start: d.start }); m.close(); ok('Đã phân công ' + Q.building(d.buildingId).name, e.name); } });
  };
  const statusModal = (e, status) => { const m = U.modal({ title: (status === 'resigned' ? 'Nghỉ việc – ' : status === 'leave' ? 'Tạm nghỉ – ' : 'Đổi trạng thái – ') + esc(e.name), size: 'sm', body: `${U.field({ label: 'Trạng thái mới', input: U.select({ name: 'status', value: status, options: Object.entries(Q.L.employee).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Lý do / ghi chú', input: U.textarea({ name: 'reason', placeholder: 'Nghỉ phép dài hạn, chuyển công tác…' }), cls: 'mt12' })}${U.note('info', '', 'Nghỉ việc không xóa hồ sơ; chứng từ đã lập vẫn giữ tên tham chiếu (AC-FR-HR-01-1); phân công tòa đang hiệu lực sẽ kết thúc.')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Xác nhận', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); X.setEmployeeStatus(e.id, d.status, d.reason); m.close(); ok('Đã cập nhật trạng thái', e.name + ' – ' + Q.label('employee', d.status)); } }); };
  const docModal = (e) => { const m = U.modal({ title: 'Thêm tài liệu – ' + esc(e.name), size: 'sm', body: `${U.field({ label: 'Loại tài liệu', req: true, input: U.select({ name: 'name', placeholder: 'Chọn loại', options: ['Hợp đồng lao động', 'Sơ yếu lý lịch', 'Bản sao CCCD', 'Bằng cấp, chứng chỉ', 'Đánh giá thử việc', 'Quyết định bổ nhiệm', 'Khác'] }) })}<div class="field mt12"><label>File</label>${U.dropzone({ name: 'f', multiple: false, hint: 'PDF/DOCX/JPG (mô phỏng)' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const f = U.dzFiles(m.el, 'f')[0]; X.addEmployeeDoc(e.id, { name: d.name, fileName: f ? f.name : (F.slug(d.name) + '_' + F.slug(e.name) + '.pdf'), size: f ? (f.size / 1024).toFixed(0) + ' KB' : '' }); m.close(); ok('Đã thêm tài liệu', d.name); } }); };
  const empMenu = (el, e) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => TH.go('#/hr/' + e.id) }, { label: 'Chỉnh sửa', icon: 'pencil', disabled: !canManage(), onClick: () => Fm.employee(e) }, { label: 'Phân công tòa', icon: 'building', disabled: !canManage() || e.status === 'resigned', onClick: () => assignModal(e) }, '-', { label: 'Tạm nghỉ', icon: 'clock', disabled: !canManage() || e.status !== 'working', onClick: () => statusModal(e, 'leave') }, { label: 'Đi làm lại', icon: 'check-circle', disabled: !canManage() || e.status !== 'leave', onClick: () => { X.setEmployeeStatus(e.id, 'working', 'Đi làm lại'); ok('Đã cập nhật', e.name + ' – Đang làm việc'); } }, { label: 'Kết thúc thử việc', icon: 'award', disabled: !canManage() || e.status !== 'probation', onClick: () => { X.setEmployeeStatus(e.id, 'working', 'Hết thử việc – chính thức'); ok('Đã chuyển chính thức', e.name); } }, { label: 'Nghỉ việc', icon: 'log-out', danger: true, disabled: !canManage() || e.status === 'resigned', onClick: () => statusModal(e, 'resigned') }, '-', { label: 'Tạo tài khoản đăng nhập', icon: 'key', disabled: !TH.auth.can('users.manage') || !!e.userId, onClick: () => Fm.user({ name: e.name, email: e.email, phone: e.phone, role: e.dept === 'kinhdoanh' ? 'sale' : e.dept === 'baotri' ? 'kythuat' : e.dept === 'taichinh' ? 'accountant' : 'ops', effectiveDate: F.today(), note: 'Từ hồ sơ ' + e.code }) }]);
  TH.pages.employeeMenu = empMenu;

  /* ================= #/hr – Quản lý nhân viên (PNG 07/01) ================= */
  TH.router.register('/hr', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Nhân viên' }]);
    const f = { s: q.s || '', dept: q.dept || '', title: q.title || '', area: q.area || '', status: q.status || '' };
    const rows = Q.filterEmployees(f); const st = Q.employeeStats(); const prob = Q.probationEnding(30).slice(0, 5);
    root.innerHTML = `${U.pageHead({ title: 'Quản lý nhân viên', phase: 3, sub: 'Quản lý thông tin nhân sự, phân công công việc và theo dõi hiệu suất làm việc.', acts: [U.btn({ label: 'Thêm nhân viên', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !canManage(), attrs: { 'data-guide': 'emp-add' } }), U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã nhân viên, họ tên, SĐT, email…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Phòng ban', input: U.select({ name: 'dept', value: f.dept, all: 'Tất cả phòng ban', options: deptOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Chức danh', input: U.select({ name: 'title', value: f.title, all: 'Tất cả chức danh', options: titleOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Khu vực phụ trách', input: U.select({ name: 'area', value: f.area, all: 'Tất cả khu vực', options: areaOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.employee).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng nhân viên', value: st.total, cap: 'Tăng 3 nhân viên so với tháng trước', icon: 'users', tone: 'blue', delta: 12 })}${U.kpi({ label: 'Đang làm việc', value: st.working, cap: F.pct(st.working, st.total) + '% tổng nhân viên', icon: 'check-circle', tone: 'green', delta: 9 })}${U.kpi({ label: 'Tạm nghỉ', value: st.leave, cap: F.pct(st.leave, st.total) + '% tổng nhân viên', icon: 'clock', tone: 'amber', delta: -25 })}${U.kpi({ label: 'Quản lý khu vực', value: st.managers, cap: 'Phụ trách ' + liveB().length + ' khu vực', icon: 'user-check', tone: 'purple', delta: 20 })}</div>
    ${U.relatedStrip({ id: 'hr-related', cls: 'mb16', items: [
      { key: 'dept', title: 'Phân bố theo phòng ban', icon: 'chart-pie', summary: st.total + ' nhân viên · ' + st.byDept.length + ' phòng ban', meta: st.byDept.length ? 'Đông nhất: ' + esc(st.byDept.slice().sort((a, b) => b.value - a.value)[0].label) + ' (' + F.pct(st.byDept.slice().sort((a, b) => b.value - a.value)[0].value, st.total) + '%)' : '', actions: U.iconBtn('more', 'dept-more', 'Xem theo phòng ban'), body: C.donutLegend(st.byDept.map(x => Object.assign({}, x, { text: x.value + ' (' + F.pct(x.value, st.total) + '%)' })), 150, String(st.total), 'Nhân viên') },
      { key: 'probation', title: 'Nhân viên sắp hết hợp đồng thử việc', icon: 'calendar-clock', summary: prob.length ? prob.length + ' nhân viên trong 30 ngày' : 'Không có', meta: prob.length ? 'Gần nhất: ' + esc(prob[0].e.name) + ' · ' + (prob[0].left < 0 ? 'quá ' + Math.abs(prob[0].left) : 'còn ' + prob[0].left) + ' ngày' : 'Không có nhân viên sắp hết thử việc', actions: '<a class="link small" href="#/hr?status=probation">Xem tất cả →</a>', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>#</th><th>Họ tên</th><th>Ngày hết hạn</th><th>Còn lại</th></tr></thead><tbody>${prob.map((x, i) => `<tr><td>${i + 1}</td><td>${U.link('#/hr/' + x.e.id, esc(x.e.name))}</td><td>${F.date(x.e.probationEnd)}</td><td>${U.chip(x.left < 0 ? 'Quá ' + Math.abs(x.left) + ' ngày' : x.left + ' ngày', x.left <= 5 ? 'red' : x.left <= 10 ? 'amber' : 'gray')}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Không có nhân viên sắp hết thử việc</td></tr>'}</tbody></table></div>` }
    ] })}
    ${U.card({ title: 'Danh sách nhân viên (' + rows.length + ' nhân viên)', icon: 'users', actions: U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', cls: 'btn-ghost', act: 'cols' }), body: null, id: 'et', attrs: 'data-guide="employees-table"' })}`;
    const cols = [{ key: 'code', label: 'Mã NV', sortable: true, render: e => U.link('#/hr/' + e.id, esc(e.code), 'bold') }, { key: 'name', label: 'Họ tên', sortable: true, render: e => esc(e.name) }, { key: 'dept', label: 'Phòng ban', sortable: true, sortVal: e => Q.deptLabel(e.dept), render: e => esc(Q.deptLabel(e.dept)) }, { key: 'title', label: 'Chức danh', sortable: true }, { key: 'phone', label: 'SĐT', render: e => esc(e.phone) }, { key: 'email', label: 'Email', render: e => shortMail(e.email) }, { key: 'area', label: 'Khu vực phụ trách', render: e => esc(e.area || '-') }, { key: 'building', label: 'Tòa nhà phụ trách', render: e => { const b = Q.primaryBuilding(e.id); return b.name ? esc(b.name.replace('Tòa ', '')) : '-'; } }, { key: 'status', label: 'Trạng thái', sortable: true, render: e => Q.chip('employee', e.status) }, { key: 'startDate', label: 'Ngày vào làm', sortable: true, render: e => F.date(e.startDate) }, { key: 'actions', label: 'Thao tác', render: e => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': e.id } }), U.moreBtn(e.id)]), hideable: false }];
    const tbl = U.table(root.querySelector('#et'), { rows, unit: 'nhân viên', selectable: true, colPrefsKey: 'employees', cols });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, add: () => Fm.employee({}), view: (el) => TH.go('#/hr/' + el.dataset.id), more: (el) => empMenu(el, St.get('employees', el.dataset.id)), cols: (b) => U.columnMenu(b, tbl, cols), 'dept-more': (b) => U.menu(b, st.byDept.map(x => ({ label: x.label + ' (' + x.value + ')', onClick: () => { TH.router.replaceQuery({ dept: x.key }); TH.router.refresh(); } }))), export: () => { F.download('danh-sach-nhan-vien.csv', F.csv(rows.map(e => [e.code, e.name, Q.deptLabel(e.dept), e.title, e.phone, e.email, e.area, Q.primaryBuilding(e.id).name || '', Q.label('employee', e.status), e.startDate]), ['Mã NV', 'Họ tên', 'Phòng ban', 'Chức danh', 'SĐT', 'Email', 'Khu vực', 'Tòa phụ trách', 'Trạng thái', 'Ngày vào làm']), 'text/csv'); ok('Đã xuất danh sách'); } });
  }, { menu: 'hr', permission: 'hr.view', phase: 3, scopeKey: 'hr' });

  /* ================= #/hr/timesheet – Chấm công (tự thiết kế, mô phỏng) ================= */
  TH.router.register('/hr/timesheet', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Chấm công' }]);
    const periods = Q.payrollPeriods(); const period = q.period || St.state.meta.period; const f = { dept: q.dept || '', buildingId: q.buildingId || '' };
    const emps = Q.filterEmployees(f); const sheets = {}; emps.forEach(e => { const t = Q.timesheet(e.id, period); if (t) sheets[e.id] = t; }); const st = Q.timesheetStats(period, f); const canEdit = TH.auth.can('timesheet.manage');
    root.innerHTML = `${U.pageHead({ title: 'Chấm công', phase: 3, sub: 'Bảng công theo tháng – nguồn ngày công cho bảng lương. <span class="chip gray">Tự thiết kế – không có PNG</span> <span class="chip amber">Mô phỏng – ngoài scope SRS §2.2</span>', acts: [U.btn({ label: 'Điền mặc định', icon: 'sparkles', cls: 'btn-outline', act: 'fill', disabled: !canEdit || st.confirmed }), U.btn({ label: 'Xác nhận bảng công', icon: 'check', cls: 'btn-primary', act: 'confirm', disabled: !canEdit || st.confirmed, attrs: { 'data-guide': 'ts-confirm' } }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phòng ban', input: U.select({ name: 'dept', value: f.dept, all: 'Tất cả phòng ban', options: deptOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa phụ trách', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa', options: liveB().map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Ngày công chuẩn', value: st.std, cap: F.periodLabel(period) + ' (T2–T7)', icon: 'calendar', tone: 'blue' })}${U.kpi({ label: F.period(F.today()) === period ? 'Đi làm hôm nay' : 'Công bình quân', value: st.present, cap: F.period(F.today()) === period ? 'trên ' + emps.length + ' nhân viên' : 'ngày/nhân viên', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Nghỉ phép / vắng', value: st.leave, cap: 'lượt trong kỳ', icon: 'calendar-x', tone: 'amber' })}${U.kpi({ label: 'Đi muộn / OT', value: st.late + ' / ' + st.ot + 'h', cap: 'lượt muộn / giờ tăng ca', icon: 'clock', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'timesheet-related', cls: 'mb16', items: [
      { key: 'legend', title: 'Chú giải', icon: 'info', summary: Object.keys(Q.L.attCode).length + ' ký hiệu', meta: Object.entries(Q.L.attCode).map(([k, v]) => k + ' ' + v[0]).join(' · '), body: `<div class="att-legend">${Object.entries(Q.L.attCode).map(([k, v]) => `<span class="row gap8"><span class="c-${k} att-cell"><button type="button" class="att-btn">${k}</button></span>${esc(v[0])}</span>`).join('')}</div>` },
      { key: 'status', title: 'Trạng thái bảng công', icon: 'check-circle', summary: (st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft')) + ' ' + st.count + '/' + emps.length + ' bảng công', meta: (() => { const t = Object.values(sheets).find(x => x.confirmedBy); return t ? 'Xác nhận bởi ' + esc(Q.userName(t.confirmedBy)) + ' · ' + F.datetime(t.confirmedAt) : 'Chưa xác nhận – dùng cho bảng lương ' + F.periodLabel(period); })(), body: U.kv([['Kỳ', F.periodLabel(period)], ['Số bảng công', st.count + '/' + emps.length], ['Trạng thái', st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft')], ['Người xác nhận', (() => { const t = Object.values(sheets).find(x => x.confirmedBy); return t ? esc(Q.userName(t.confirmedBy)) + ' · ' + F.datetime(t.confirmedAt) : '-'; })()], ['Dùng cho', U.link('#/hr/payroll?period=' + period, 'Bảng lương ' + F.periodLabel(period))]]) },
      { key: 'note', title: 'Ghi chú', icon: 'book-open', summary: 'Mô phỏng ngoài SRS §2.2', meta: 'Cấp ngày công cho bảng lương (FR-HR-02)', body: U.note('info', 'Ghi chú', 'Chấm công/BHXH/thuế nằm ngoài phạm vi SRS v1.2 §2.2 – màn này mô phỏng theo scope §4.2 để cấp ngày công cho bảng lương (FR-HR-02).') }
    ] })}
    ${U.card({ title: 'Bảng công ' + F.periodLabel(period) + ' (' + emps.length + ' nhân viên)', icon: 'clipboard-list', sub: canEdit && !st.confirmed ? 'Bấm vào ô để đổi ký hiệu' : '', actions: st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft'), bodyCls: 'tight', body: U.attendanceGrid({ employees: emps, period, sheets, editable: canEdit && !st.confirmed }) })}`;
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ period }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, att: (el) => U.menu(el, [{ header: Q.employeeName(el.dataset.emp) + ' · ' + F.date(el.dataset.date) }, ...Object.entries(Q.L.attCode).map(([k, v]) => ({ label: k + ' – ' + v[0], onClick: () => X.markAttendance(el.dataset.emp, el.dataset.date, k) }))]), fill: () => { const n = X.fillTimesheet(period, f); ok('Đã điền ' + n + ' ô', 'P ngày làm việc, O chủ nhật, L nếu tạm nghỉ'); }, confirm: async () => { if (await U.confirm({ title: 'Xác nhận bảng công ' + F.periodLabel(period) + '?', text: 'Sau xác nhận không sửa ô chấm công; bảng lương tính theo số công này.', ok: 'Xác nhận' })) { const n = X.confirmTimesheet(period, f); ok('Đã xác nhận bảng công', n + ' nhân viên'); } }, export: () => { F.download('bang-cong-' + period + '.csv', F.csv(emps.map(e => { const t = sheets[e.id] || {}; return [e.code, e.name, Q.deptLabel(e.dept), t.workDays || 0, t.offDays || 0, t.late || 0, t.otHours || 0, Q.label('timesheet', t.status || 'draft')]; }), ['Mã NV', 'Họ tên', 'Phòng ban', 'Công', 'Nghỉ', 'Muộn', 'OT', 'Trạng thái']), 'text/csv'); ok('Đã xuất bảng công'); } });
  }, { menu: 'timesheet', permission: 'timesheet.view', phase: 3, scopeKey: 'timesheet' });

  /* ================= #/hr/payroll – Lương thưởng (tự thiết kế, FR-HR-02) ================= */
  TH.router.register('/hr/payroll', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Lương thưởng' }]);
    const periods = Q.payrollPeriods(); const period = q.period || St.state.meta.period; const f = { dept: q.dept || '' }; const pr = Q.payroll(period); const st = Q.payrollStats(pr); const ts = Q.timesheetStats(period);
    const lines = pr ? pr.lines.filter(l => !f.dept || Q.employee(l.employeeId).dept === f.dept) : []; const status = pr ? pr.status : 'none'; const stepIdx = { draft: 0, review: 1, approved: 2, paid: 3 }[status];
    const canM = TH.auth.can('payroll.manage'), canA = TH.auth.can('payroll.approve');
    const acts = [U.btn({ label: pr ? 'Tính lại bảng lương' : 'Tính bảng lương kỳ', icon: 'refresh-cw', cls: pr ? 'btn-outline' : 'btn-primary', act: 'build', disabled: !canM || (pr && pr.status !== 'draft'), attrs: { 'data-guide': 'pay-build' } })];
    if (status === 'draft') acts.push(U.btn({ label: 'Gửi duyệt', icon: 'send', cls: 'btn-primary', act: 'submit', disabled: !canM, attrs: { 'data-guide': 'pay-submit' } }));
    if (status === 'review') acts.push(U.btn({ label: 'Duyệt', icon: 'check', cls: 'btn-primary', act: 'approve', disabled: !canA, attrs: { 'data-guide': 'pay-approve' } }));
    if (status === 'approved') acts.push(U.btn({ label: 'Ghi nhận chi lương', icon: 'banknote', cls: 'btn-primary', act: 'pay', disabled: !canA, attrs: { 'data-guide': 'pay-pay' } }));
    acts.push(U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export', disabled: !pr }));
    root.innerHTML = `${U.pageHead({ title: 'Lương thưởng', phase: 3, sub: 'Lương cứng + phụ cấp chức danh + phụ cấp số nhà (vận hành) + hoa hồng Sale theo kỳ (FR-HR-02, BR-14). <span class="chip gray">Tự thiết kế – không có PNG</span>', acts })}
    ${U.filterbar([U.field({ label: 'Kỳ lương', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phòng ban', input: U.select({ name: 'dept', value: f.dept, all: 'Tất cả phòng ban', options: deptOpts(), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.stepperStatus([{ label: 'Nháp', date: pr ? F.date(pr.createdAt) : '', by: pr ? Q.userName(pr.createdBy) : '' }, { label: 'Chờ duyệt', date: pr && pr.submittedAt ? F.date(pr.submittedAt) : '', by: pr && pr.submittedBy ? Q.userName(pr.submittedBy) : '' }, { label: 'Đã duyệt', date: pr && pr.approvedAt ? F.date(pr.approvedAt) : '', by: pr && pr.approvedBy ? Q.userName(pr.approvedBy) : '' }, { label: 'Đã chi', date: pr && pr.paidAt ? F.date(pr.paidAt) : '', by: pr && pr.paidBy ? Q.userName(pr.paidBy) : '' }], pr ? stepIdx : -1)}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng chi lương', value: F.vnd(st.total), cap: st.count + ' nhân viên · ' + (pr ? Q.label('payroll', pr.status) : 'chưa tính'), icon: 'banknote', tone: 'blue' })}${U.kpi({ label: 'Lương cứng', value: F.vnd(st.base), cap: 'Theo ngày công / ' + Q.workDaysStd(period), icon: 'coins', tone: 'green' })}${U.kpi({ label: 'Phụ cấp', value: F.vnd(st.allow), cap: 'Chức danh + số nhà (OI-15)', icon: 'gift', tone: 'amber' })}${U.kpi({ label: 'Hoa hồng Sale', value: F.vnd(st.commission), cap: 'Hoa hồng đã chi trong kỳ (BR-13)', icon: 'hand-coins', tone: 'purple' })}</div>
    ${(() => { const byB = pr ? Q.payrollByBuilding(pr) : []; const hist = St.all('payrolls').slice().sort((a, b) => F.cmp(b.period, a.period)); return U.relatedStrip({ id: 'payroll-related', cls: 'mb16', items: [
      { key: 'formula', title: 'Công thức (BR-14)', icon: 'info', summary: 'Lương cứng + phụ cấp + hoa hồng − khấu trừ', meta: 'Ngày công chuẩn ' + Q.workDaysStd(period) + ' · chờ chốt OI-15', body: `<div class="small"><b>Thực lĩnh</b> = Lương cứng × (công / ${Q.workDaysStd(period)}) + PC chức danh + PC số nhà (vận hành: 500.000 × số tòa phụ trách) + Hoa hồng Sale (đã chi trong kỳ, không tính trùng với CRM) − Khấu trừ 10,5% (BHXH mẫu).</div>${U.note('warn', 'Chờ chốt OI-15', 'Đơn giá phụ cấp, mốc số nhà, nhân sự đổi vai trò giữa tháng và kỳ ghi hoa hồng chưa được xác nhận – số trong demo là giả định.')}` },
      { key: 'by-building', title: 'Chi phí lương theo tòa', icon: 'building', summary: pr ? byB.length + ' tòa · ' + F.vnd(F.sum(byB, x => x.value)) : 'Chưa có bảng lương', meta: byB.length ? 'Cao nhất: ' + esc(byB[0].label) + ' ' + F.vnd(byB[0].value) : 'Tính bảng lương để xem phân bổ', body: pr ? C.vbar({ items: byB.map(x => ({ label: x.label, value: Math.round(x.value / 1e6) })), height: 170, unit: 'tr' }) : '<div class="muted small">Chưa có bảng lương</div>' },
      { key: 'history', title: 'Lịch sử kỳ lương', icon: 'history', summary: hist.length + ' kỳ', meta: hist.length ? 'Gần nhất: ' + F.periodLabel(hist[0].period) + ' · ' + Q.label('payroll', hist[0].status) : 'Chưa có', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Kỳ</th><th class="num">Tổng</th><th>Trạng thái</th></tr></thead><tbody>${hist.map(x => `<tr><td>${U.link('#/hr/payroll?period=' + x.period, F.periodLabel(x.period))}</td><td class="num">${F.vnd(x.total)}</td><td>${Q.chip('payroll', x.status)}</td></tr>`).join('') || '<tr><td colspan="3" class="muted tc">Chưa có</td></tr>'}</tbody></table></div>` }
    ] }); })()}
    ${pr ? U.card({ title: 'Bảng lương ' + esc(pr.code), icon: 'clipboard-list', sub: esc(pr.note || ''), actions: Q.chip('payroll', pr.status), body: null, id: 'pt' }) : U.card({ body: U.empty({ icon: 'banknote', title: 'Chưa có bảng lương ' + F.periodLabel(period), text: ts.confirmed ? 'Bảng công đã xác nhận – bấm "Tính bảng lương kỳ".' : 'Xác nhận bảng công trước để tính chính xác; có thể tính tạm.', action: canM ? U.btn({ label: 'Tính bảng lương kỳ', icon: 'refresh-cw', size: 'btn-sm', cls: 'btn-primary', act: 'build' }) : '' }) })}`;
    if (pr) U.table(root.querySelector('#pt'), { rows: lines, unit: 'nhân viên', pageSize: 10, footer: (rows) => `<tr class="dist-total"><td colspan="3">Tổng cộng (${rows.length})</td><td class="num">${F.vnd(F.sum(rows, l => l.base))}</td><td class="num">${F.vnd(F.sum(rows, l => l.titleAllowance))}</td><td class="num">${F.vnd(F.sum(rows, l => l.buildingAllowance))}</td><td class="num">${F.vnd(F.sum(rows, l => l.commission))}</td><td class="num">${F.vnd(F.sum(rows, l => l.deductions))}</td><td class="num">${F.vnd(F.sum(rows, l => l.total))}</td><td></td></tr>`, cols: [{ key: 'code', label: 'Mã NV', render: l => U.link('#/hr/' + l.employeeId, esc(Q.employee(l.employeeId).code), 'bold') }, { key: 'name', label: 'Họ tên', sortable: true, sortVal: l => Q.employeeName(l.employeeId), render: l => U.cell2(esc(Q.employeeName(l.employeeId)), esc(Q.deptLabel(Q.employee(l.employeeId).dept))) }, { key: 'wd', label: 'Công', num: true, render: l => (l.workDays != null ? l.workDays : '-') }, { key: 'base', label: 'Lương cứng', num: true, sortable: true, render: l => F.vnd(l.base) }, { key: 'ta', label: 'PC chức danh', num: true, render: l => F.vnd(l.titleAllowance) }, { key: 'ba', label: 'PC số nhà', num: true, render: l => l.buildingAllowance ? `<span title="${l.buildingCount} tòa × 500.000">${F.vnd(l.buildingAllowance)}</span>` : '-' }, { key: 'comm', label: 'Hoa hồng', num: true, render: l => l.commission ? U.link('#/crm/deals?saleId=' + (Q.employee(l.employeeId).userId || ''), F.vnd(l.commission)) : '-' }, { key: 'ded', label: 'Khấu trừ', num: true, render: l => F.vnd(l.deductions) }, { key: 'total', label: 'Thực lĩnh', num: true, sortable: true, render: l => `<b>${F.vnd(l.total)}</b>` }, { key: 'actions', label: '', render: l => U.iconBtn('info', 'explain', 'Diễn giải', { 'data-id': l.employeeId }), hideable: false }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ period }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, build: () => { const r = X.buildPayroll(period); ok('Đã tính bảng lương ' + r.code, F.vnd(r.total) + ' · ' + r.note); }, submit: () => { X.submitPayroll(period); ok('Đã gửi duyệt bảng lương', 'Kế toán/Admin duyệt'); }, approve: () => { X.approvePayroll(period); ok('Đã duyệt bảng lương ' + F.periodLabel(period)); }, pay: async () => { const r = await U.confirm({ title: 'Ghi nhận chi lương ' + F.periodLabel(period) + '?', text: 'Tạo chi phí nhóm "Lương" theo tòa phụ trách (FR-FIN-12). Kỳ đã khóa sẽ bị chặn (FR-FIN-08).', body: U.field({ label: 'Ngày chi', input: U.date({ name: 'date', value: F.today() }) }) + U.field({ label: 'Tham chiếu (UNC)', input: U.input({ name: 'ref', placeholder: 'UNC-…' }), cls: 'mt8' }), ok: 'Ghi nhận chi' }); if (r) { const pp = X.payPayroll(period, { date: r.date, ref: r.ref }); ok('Đã ghi nhận chi lương ' + pp.code, (pp.expenseIds || []).length + ' chi phí nhóm Lương'); } }, export: () => { const n = X.exportPayroll(period); ok('Đã xuất bảng lương', n + ' dòng'); }, explain: (el) => { const l = pr.lines.find(x => x.employeeId === el.dataset.id); const e = Q.employee(l.employeeId); U.modal({ title: 'Diễn giải lương – ' + esc(e.name), size: 'sm', body: U.kv([['Ngày công', l.workDays + ' / ' + (l.std || Q.workDaysStd(period))], ['Lương cơ bản', F.vnd(e.salaryBase || 0)], ['Lương cứng theo công', F.vnd(l.base)], ['PC chức danh (' + esc(e.title) + ')', F.vnd(l.titleAllowance)], ['PC số nhà (' + l.buildingCount + ' tòa)', F.vnd(l.buildingAllowance)], ['Hoa hồng đã chi', F.vnd(l.commission)], ['Khấu trừ 10,5%', '−' + F.vnd(l.deductions)], ['Thực lĩnh', '<b>' + F.vnd(l.total) + '</b>']], 'one'), footer: U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'close' }) }); } });
  }, { menu: 'payroll', permission: 'payroll.view', phase: 3, scopeKey: 'payroll' });
  /* ================= #/hr/:id – Chi tiết nhân viên (PNG 07/02) ================= */
  TH.router.register('/hr/:id', (root, p, q) => {
    const e = St.get('employees', p.id); if (!e) { root.innerHTML = U.empty({ title: 'Không tìm thấy nhân viên' }); return; }
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Nhân viên', href: '#/hr' }, { label: 'Chi tiết nhân viên' }]);
    const tab = q.tab || 'overview'; const period = St.state.meta.period; const as = Q.assignmentsOf(e.id); const kpi = Q.employeeKpi(e, period); const acts = Q.employeeActivities(e, 4); const week = Q.employeeWeek(e); const mgr = e.managerId ? Q.employee(e.managerId) : null; const u = e.userId ? Q.user(e.userId) : null;
    const contractsMonth = e.userId ? St.where('contracts', c => c.managerId === e.userId && F.period(c.createdAt || c.start) === period).length + kpi.deals : 0;
    root.innerHTML = `${U.pageHead({ title: 'Chi tiết nhân viên', phase: 3, sub: 'Xem và quản lý thông tin chi tiết của nhân viên trong hệ thống.', back: '#/hr', acts: [U.btn({ label: 'Chỉnh sửa', icon: 'pencil', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), U.btn({ label: 'Phân công tòa nhà', icon: 'building', cls: 'btn-outline', act: 'assign', disabled: !canManage() || e.status === 'resigned', attrs: { 'data-guide': 'emp-assign' } }), U.btn({ label: 'Cập nhật hồ sơ', icon: 'user-plus', cls: 'btn-primary', act: 'profile', disabled: !canManage() })] })}
    ${U.profileHero({ name: e.name, chip: Q.chipDot('employee', e.status), meta: [['Mã nhân viên', esc(e.code)], ['Chức danh', esc(e.title)], ['Phòng ban', esc(Q.deptLabel(e.dept))], ['Ngày vào làm', I('calendar') + ' ' + F.date(e.startDate), 'Đã làm việc ' + Q.seniority(e.startDate)]] })}
    <div class="two-col">
      <div class="side-stack">${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'assign', label: 'Phân công', count: as.length }, { key: 'docs', label: 'Hồ sơ', count: (e.documents || []).length }, { key: 'history', label: 'Lịch sử' }], tab, 'card-tabs')}<div id="tab-body" class="side-stack"></div></div>
      <aside class="side-stack">${U.card({ title: 'Thống kê nhanh', icon: 'bar-chart', body: `<div class="grid grid-2">${U.miniStat({ label: 'Tòa nhà phụ trách', value: as.length, icon: 'building', tone: 'blue' })}${U.miniStat({ label: 'Lead đang xử lý', value: kpi.openLeads, icon: 'users', tone: 'green' })}${U.miniStat({ label: 'Hợp đồng trong tháng', value: contractsMonth, icon: 'file-text', tone: 'amber' })}${U.miniStat({ label: 'Tỷ lệ hài lòng KH', value: '92%', icon: 'check-circle', tone: 'purple' })}</div><div class="xs muted mt8">Tỷ lệ hài lòng: số mẫu – chưa có nguồn dữ liệu trong SRS.</div>` })}
      ${U.card({ title: 'Lịch làm việc tuần này', icon: 'calendar', actions: '<a class="link small" href="#/maintenance/schedules">Xem tất cả →</a>', bodyCls: 'tight', body: `<div class="week-list">${week.map((dd, i) => `<div class="week-row ${dd.date === F.today() ? 'today' : ''}"><div class="wk-d"><b>Th ${i + 2}</b><small>${dd.date.slice(8, 10)}/${dd.date.slice(5, 7)}</small></div><div class="grow">${dd.items.map(it => `<div class="wk-it"><span class="dot" style="background:var(--${it.color === 'blue' ? 'primary' : it.color === 'green' ? 'green-500' : it.color === 'amber' ? 'amber-500' : it.color === 'red' ? 'red-500' : it.color === 'purple' ? 'purple' : 'teal'})"></span><div><span class="small muted">${esc(it.time)}</span><b>${esc(it.title)}</b><small>${esc(it.place)}</small></div></div>`).join('') || '<span class="muted small">Trống</span>'}</div></div>`).join('')}</div>` })}
      ${U.card({ title: 'Tài liệu liên quan', icon: 'folder', actions: U.btn({ label: 'Thêm tài liệu', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'doc-add', disabled: !canManage() }), body: (e.documents || []).length ? `<div class="file-list">${e.documents.map(d => U.fileItem({ name: d.name, fileName: d.fileName, date: d.date, size: d.size }, U.moreBtn(d.id, 'data-doc="1"'))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' }) })}</aside></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin liên hệ', icon: 'id-card', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), body: U.kv([[I('user') + ' Họ tên', esc(e.name)], [I('mail') + ' Email', esc(e.email || '-')], [I('phone') + ' Số điện thoại', esc(e.phone)], [I('map-pin') + ' Địa chỉ', esc(e.address || '-')]].map(([k, v]) => [k.replace(/<[^>]+>/g, '').trim(), v]), 'one') })}${U.card({ title: 'Thông tin công việc', icon: 'briefcase', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), body: U.kv([['Mã nhân viên', esc(e.code)], ['Chức danh', esc(e.title)], ['Phòng ban', esc(Q.deptLabel(e.dept))], ['Hình thức làm việc', esc(e.workType || '-')], ['Quản lý trực tiếp', mgr ? U.link('#/hr/' + mgr.id, esc(mgr.name)) : '-'], ['Ngày vào làm', F.date(e.startDate)], ['Trạng thái', Q.chip('employee', e.status)], ['Tài khoản', u ? esc(u.username) + ' – ' + esc(TH.auth.ROLE_LABEL[u.role] || u.role) : '<span class="muted">Chưa có</span>']], 'one') })}</div>
    <div class="grid grid-2">${U.card({ title: 'Tòa nhà phụ trách', icon: 'building', actions: U.btn({ label: 'Phân công thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'assign', disabled: !canManage() || e.status === 'resigned' }), body: as.length ? as.map(a => { const b = Q.building(a.buildingId); return `<div class="up-row"><div class="thumb" style="width:52px;height:44px;background:var(--blue-bg);color:var(--blue)">${I('building-2')}</div><div class="grow"><b>${U.link('#/buildings/' + b.id, esc(b.name || ''))}</b><div class="small muted">${esc(b.address || '')}</div><div class="xs muted">${Q.label('assignRole', a.role)} · từ ${F.date(a.start)}</div></div>${a.primary ? U.chip('Chính', 'blue') : U.chip('Phụ', 'gray')}</div>`; }).join('') : U.empty({ icon: 'building', title: 'Chưa phân công tòa' }) })}
    ${U.card({ title: 'KPI cá nhân', icon: 'trending-up', sub: '(' + F.periodLabel(period) + ')', actions: `<a class="link small" href="${e.userId ? '#/crm?saleId=' + e.userId : '#/crm'}">Xem chi tiết →</a>`, body: kpi.hasUser ? `<div class="grid grid-2">${U.miniStat({ label: 'Lead đã xử lý', value: kpi.leads, icon: 'user', tone: 'green', delta: 20 })}${U.miniStat({ label: 'Hợp đồng thành công', value: kpi.deals, icon: 'file-text', tone: 'blue', delta: 14 })}${U.miniStat({ label: 'Doanh thu mang về (VND)', value: F.vnd(kpi.revenue), icon: 'dollar', tone: 'amber' })}${U.miniStat({ label: 'Tỷ lệ chuyển đổi', value: kpi.rate + '%', icon: 'target', tone: 'purple', delta: 28 })}</div><div class="xs muted mt8">Tính từ lead/giao dịch CRM (Phase 2) theo tài khoản ${esc(u ? u.username : '')}.</div>` : U.empty({ icon: 'trending-up', title: 'Chưa gắn tài khoản', text: 'KPI tính từ hoạt động CRM/bảo trì theo tài khoản đăng nhập của nhân viên.' }) })}</div>
    ${U.card({ title: 'Hoạt động gần đây', icon: 'activity', actions: `<a class="link small" href="#/hr/${e.id}?tab=history">Xem tất cả →</a>`, body: acts.length ? U.timeline(acts.map(a => ({ when: F.datetime(a.at), title: a.title, sub: a.sub + ' · ' + e.name, color: a.color, fill: true }))) : U.empty({ title: 'Chưa có hoạt động' }) })}`;
    if (tab === 'assign') body.innerHTML = U.card({ title: 'Lịch sử phân công tòa (FR-BLD-07)', icon: 'building', actions: U.btn({ label: 'Phân công', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'assign', disabled: !canManage() || e.status === 'resigned' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Tòa nhà</th><th>Vai trò</th><th>Từ ngày</th><th>Đến ngày</th><th>Chính</th><th>Trạng thái</th><th></th></tr></thead><tbody>${Q.assignmentsOf(e.id, false).sort((a, b) => F.cmp(b.start, a.start)).map(a => `<tr><td>${U.link('#/buildings/' + a.buildingId, esc(Q.building(a.buildingId).name || ''))}</td><td>${Q.chip('assignRole', a.role)}</td><td>${F.date(a.start)}</td><td>${a.end ? F.date(a.end) : '—'}</td><td>${a.primary ? I('check') : ''}</td><td>${Q.chip('assignment', a.status)}</td><td class="tr">${a.status === 'active' && canManage() ? U.btn({ label: 'Kết thúc', size: 'btn-sm', cls: 'btn-ghost', act: 'end-assign', attrs: { 'data-id': a.id } }) : ''}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Chưa có phân công</td></tr>'}</tbody></table>` });
    if (tab === 'docs') body.innerHTML = U.card({ title: 'Hồ sơ nhân sự', icon: 'folder', actions: U.btn({ label: 'Thêm tài liệu', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'doc-add', disabled: !canManage() }), body: `${canManage() ? U.kv([['Lương cơ bản', F.vnd(e.salaryBase || 0)], ['Phụ cấp chức danh', F.vnd(e.titleAllowance || 0)], ['Phụ cấp số nhà', e.dept === 'vanhanh' ? as.length + ' tòa × 500.000 (OI-15)' : 'Không áp dụng'], ['Hình thức', esc(e.workType || '-')]], 'one') + '<hr class="mt12 mb12">' : U.note('info', '', 'Trường lương chỉ hiển thị cho Nhân sự/Admin (AC-FR-HR-01-2).')}${(e.documents || []).length ? `<div class="file-list">${e.documents.map(d => U.fileItem({ name: d.name, fileName: d.fileName, date: d.date, size: d.size }, U.moreBtn(d.id, 'data-doc="1"'))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' })}` });
    if (tab === 'history') body.innerHTML = U.card({ title: 'Lịch sử', icon: 'history', body: Q.employeeActivities(e, 30).length ? U.timeline(Q.employeeActivities(e, 30).map(a => ({ when: F.datetime(a.at), title: a.title, sub: a.sub, color: a.color }))) : U.empty({ title: 'Chưa có lịch sử' }) });
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, edit: () => Fm.employee(e), assign: () => assignModal(e), profile: () => Fm.employee(e), 'doc-add': () => docModal(e), 'end-assign': async (el) => { if (await U.confirm({ title: 'Kết thúc phân công?', text: 'Giữ lịch sử, ngày kết thúc = hôm nay.', ok: 'Kết thúc' })) { X.endAssignment(el.dataset.id); ok('Đã kết thúc phân công'); } }, more: (el) => { if (el.dataset.doc) { const d = (e.documents || []).find(x => x.id === el.dataset.id); U.menu(el, [{ label: 'Tải xuống', icon: 'download', onClick: () => U.fakePdf(d.name, ['Nhân viên: ' + e.name, 'File: ' + d.fileName, 'Ngày: ' + F.date(d.date)]) }, { label: 'Xóa', icon: 'trash', danger: true, disabled: !canManage(), onClick: () => { X.removeEmployeeDoc(e.id, d.id); ok('Đã xóa tài liệu'); } }]); } else empMenu(el, e); } });
  }, { menu: 'hr', permission: 'hr.view', phase: 3, scopeKey: 'hr' });

})(window.TH);
