/* Nhân sự (spec v1.8 §4.24, §4.26): Danh sách NV (#/hr), Chi tiết NV (#/hr/:id), Chấm công (#/hr/timesheet – mô phỏng ngoài spec), Bảng lương (#/hr/payroll – §4.26.5–4.26.7) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, C = TH.chart, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const liveB = () => St.where('buildings', b => !b.stub);
  const deptOpts = () => Object.entries(Q.L.dept).map(([k, v]) => [k, v[0]]);
  const titleOpts = () => Object.keys(Q.L.title);
  const areaOpts = () => [...new Set(St.all('employees').map(e => e.area).filter(Boolean).concat(['Tất cả khu vực']))];
  const payrollCostCode = e => /quản lý khu vực/i.test(e.title || '') ? 'VH-L-QL' : /quản lý tòa/i.test(e.title || '') ? 'VH-L-QLT' : /vận hành/i.test(e.title || '') ? 'VH-L-TPVH' : /sale|kinh doanh/i.test((e.title || '') + ' ' + (e.dept || '')) ? 'VH-L-NVKD' : /vệ sinh/i.test(e.title || '') ? 'VH-L-VS' : /kỹ thuật/i.test(e.title || '') ? 'VH-L-KT' : 'VH-L-NGUON';
  const canManage = () => TH.auth.can('hr.manage');
  const shortMail = (m) => { if (!m) return '-'; const [u, d] = m.split('@'); return `<span title="${esc(m)}">${esc(u.slice(0, 8) + (u.length > 8 ? '…' : '') + '@' + (d || '').slice(0, 5) + '…')}</span>`; };

  /* ---- Forms ---- */
  Fm.employee = (e = {}, opts = {}) => {
    const managers = St.where('employees', x => x.id !== e.id && x.status !== 'resigned' && ['Quản lý khu vực', 'Trưởng nhóm'].includes(x.title));
    const m = U.drawer({ title: e.id ? 'Chỉnh sửa ' + e.code : 'Thêm nhân viên', sub: 'Hồ sơ: phòng ban, chức danh, ngày vào làm, thâm niên, trạng thái (FR-HR-01/03)', body: `<div class="form-grid">${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name', value: e.name || '', placeholder: 'Nguyễn Văn A' }), cls: 'span2' })}${U.field({ label: 'Phòng ban', req: true, input: U.select({ name: 'dept', value: e.dept || '', placeholder: 'Chọn phòng ban', options: deptOpts() }) })}${U.field({ label: 'Chức danh', req: true, input: U.select({ name: 'title', value: e.title || '', placeholder: 'Chọn chức danh', options: titleOpts() }) })}${U.field({ label: 'Số điện thoại', req: true, input: U.input({ name: 'phone', value: e.phone || '', placeholder: '0901 234 567' }), help: 'Trùng SĐT với nhân viên khác sẽ bị chặn' })}${U.field({ label: 'Email', input: U.input({ name: 'email', value: e.email || '', placeholder: 'ten@timohouse.vn' }) })}${U.field({ label: 'Địa chỉ', input: U.input({ name: 'address', value: e.address || '' }), cls: 'span2' })}${U.field({ label: 'Hình thức làm việc', input: U.select({ name: 'workType', value: e.workType || 'Toàn thời gian', options: ['Toàn thời gian', 'Bán thời gian', 'Cộng tác viên', 'Thời vụ'] }) })}${U.field({ label: 'Quản lý trực tiếp', input: U.select({ name: 'managerId', value: e.managerId || '', all: 'Không', options: managers.map(x => [x.id, x.name + ' – ' + x.title]) }) })}${U.field({ label: 'Ngày vào làm', req: true, input: U.date({ name: 'startDate', value: e.startDate || F.today() }) })}${U.field({ label: 'Ngày hết thử việc', input: U.date({ name: 'probationEnd', value: e.probationEnd || '' }), help: 'Có ngày hết thử việc ≥ hôm nay → trạng thái Thử việc' })}${U.field({ label: 'Khu vực phụ trách', input: U.input({ name: 'area', value: e.area || '', placeholder: 'Khu Q.7 / Tất cả khu vực', attrs: { list: 'hr-areas' } }) })}<datalist id="hr-areas">${areaOpts().map(a => `<option value="${esc(a)}">`).join('')}</datalist>${canManage() ? U.field({ label: 'Lương cơ bản (VND)', input: U.money({ name: 'salaryBase', value: e.salaryBase || '' }), help: 'Chỉ Nhân sự/Admin thấy (AC-FR-HR-01-2)' }) : ''}${canManage() ? U.field({ label: 'Phụ cấp chức danh (VND)', input: U.money({ name: 'titleAllowance', value: e.titleAllowance || '' }) }) : ''}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: e.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: e.id ? 'Lưu thay đổi' : 'Thêm nhân viên', icon: 'user-plus', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'emp-save' } }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = e.id; const r = X.saveEmployee(d); m.close(); ok((e.id ? 'Đã cập nhật ' : 'Đã thêm nhân viên ') + r.code, r.name); opts.after && opts.after(r); } });
  };
  const assignModal = (e) => {
    const m = U.modal({ title: 'Phân công tòa nhà – ' + esc(e.name), sub: 'Lịch sử phân công theo thời gian (FR-BLD-07)', body: `${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', placeholder: 'Chọn tòa', options: liveB().filter(b => !Q.assignmentsOf(e.id).some(a => a.buildingId === b.id)).map(b => [b.id, b.name]) }) })}${U.field({ label: 'Vai trò phụ trách', req: true, input: U.select({ name: 'role', value: e.dept === 'baotri' ? 'tech' : e.title === 'Quản lý khu vực' || e.dept === 'kinhdoanh' ? 'lead' : 'ops', options: Object.entries(Q.L.assignRole).map(([k, v]) => [k, v[0]]) }), cls: 'mt12' })}${U.field({ label: 'Ngày bắt đầu', input: U.date({ name: 'start', value: F.today() }), cls: 'mt12' })}<div class="mt12">${U.check({ name: 'primary', label: 'Tòa chính (phụ trách chính)', checked: !Q.assignmentsOf(e.id).length })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Phân công', icon: 'building', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'emp-assign-save' } }) });
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); X.assignBuilding({ employeeId: e.id, buildingId: d.buildingId, role: d.role, primary: d.primary, start: d.start }); m.close(); ok('Đã phân công ' + Q.building(d.buildingId).name, e.name); } });
  };
  const statusModal = (e, status) => { const m = U.modal({ title: (status === 'resigned' ? 'Nghỉ việc – ' : status === 'leave' ? 'Tạm nghỉ – ' : 'Đổi trạng thái – ') + esc(e.name), size: 'sm', body: `${U.field({ label: 'Trạng thái mới', input: U.select({ name: 'status', value: status, options: Object.entries(Q.L.employee).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Lý do / ghi chú', input: U.textarea({ name: 'reason', placeholder: 'Nghỉ phép dài hạn, chuyển công tác…' }), cls: 'mt12' })}${U.note('info', '', 'Nghỉ việc không xóa hồ sơ; chứng từ đã lập vẫn giữ tên tham chiếu (AC-FR-HR-01-1); phân công tòa đang hiệu lực sẽ kết thúc.')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Xác nhận', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); X.setEmployeeStatus(e.id, d.status, d.reason); m.close(); ok('Đã cập nhật trạng thái', e.name + ' – ' + Q.label('employee', d.status)); } }); };
  const docModal = (e) => { const m = U.modal({ title: 'Thêm tài liệu – ' + esc(e.name), size: 'sm', body: `${U.field({ label: 'Loại tài liệu', req: true, input: U.select({ name: 'name', placeholder: 'Chọn loại', options: ['Hợp đồng lao động', 'Sơ yếu lý lịch', 'Bản sao CCCD', 'Bằng cấp, chứng chỉ', 'Đánh giá thử việc', 'Quyết định bổ nhiệm', 'Khác'] }) })}<div class="field mt12"><label>File</label>${U.dropzone({ name: 'f', multiple: false, hint: 'PDF/DOCX/JPG (mô phỏng)' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const f = U.dzFiles(m.el, 'f')[0]; X.addEmployeeDoc(e.id, { name: d.name, fileName: f ? f.name : (F.slug(d.name) + '_' + F.slug(e.name) + '.pdf'), size: f ? (f.size / 1024).toFixed(0) + ' KB' : '' }); m.close(); ok('Đã thêm tài liệu', d.name); } }); };
  const empMenu = (el, e) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => TH.go('#/hr/' + e.id) }, { label: 'Chỉnh sửa', icon: 'pencil', disabled: !canManage(), onClick: () => Fm.employee(e) }, { label: 'Phân công tòa', icon: 'building', disabled: !canManage() || e.status === 'resigned', onClick: () => assignModal(e) }, '-', { label: 'Tạm nghỉ', icon: 'clock', disabled: !canManage() || e.status !== 'working', onClick: () => statusModal(e, 'leave') }, { label: 'Đi làm lại', icon: 'check-circle', disabled: !canManage() || e.status !== 'leave', onClick: () => { X.setEmployeeStatus(e.id, 'working', 'Đi làm lại'); ok('Đã cập nhật', e.name + ' – Đang làm việc'); } }, { label: 'Kết thúc thử việc', icon: 'award', disabled: !canManage() || e.status !== 'probation', onClick: () => { X.setEmployeeStatus(e.id, 'working', 'Hết thử việc – chính thức'); ok('Đã chuyển chính thức', e.name); } }, { label: 'Nghỉ việc', icon: 'log-out', danger: true, disabled: !canManage() || e.status === 'resigned', onClick: () => statusModal(e, 'resigned') }, '-', { label: 'Tạo tài khoản đăng nhập', icon: 'key', disabled: !TH.auth.can('users.manage') || !!e.userId, onClick: () => Fm.user({ name: e.name, email: e.email, phone: e.phone, role: e.dept === 'kinhdoanh' ? 'sale' : e.dept === 'baotri' ? 'kythuat' : e.dept === 'taichinh' ? 'accountant' : 'ops', effectiveDate: F.today(), note: 'Từ hồ sơ ' + e.code }) }]);
  TH.pages.employeeMenu = empMenu;

  /* ================= #/hr – Quản lý nhân viên (PNG 07/01) ================= */
  TH.router.register('/hr', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Nhân viên' }]);
    const f = { s: q.s || '', dept: q.dept || '', title: q.title || '', areaId: q.areaId || '', status: q.status || '' };
    const rows = Q.filterEmployees(f).filter(e => !f.areaId || e.areaId === f.areaId); const st = Q.employeeStats(); const prob = Q.probationEnding(30).slice(0, 5);
    root.innerHTML = `${U.pageHead({ title: 'Nhân viên', sub: 'Hồ sơ nhân viên, đơn vị tổ chức, chức danh và phân công tòa (spec v1.8 §4.24).', acts: [U.btn({ label: 'Thêm nhân viên', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !canManage(), attrs: { 'data-guide': 'emp-add' } }), U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã nhân viên, họ tên, SĐT, email…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Phòng ban', input: U.select({ name: 'dept', value: f.dept, all: 'Tất cả phòng ban', options: deptOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Chức danh', input: U.select({ name: 'title', value: f.title, all: 'Tất cả chức danh', options: titleOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Khu nhà phụ trách', input: U.select({ name: 'areaId', value: f.areaId, all: 'Tất cả khu nhà', options: Q.areas().map(a => [a.id, a.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.employee).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng nhân viên', value: st.total, cap: 'Tăng 3 nhân viên so với tháng trước', icon: 'users', tone: 'blue' })}${U.kpi({ label: 'Đang làm việc', value: st.working, cap: F.pct(st.working, st.total) + '% tổng nhân viên', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Tạm nghỉ', value: st.leave, cap: F.pct(st.leave, st.total) + '% tổng nhân viên', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Quản lý khu vực', value: st.managers, cap: 'Phụ trách ' + liveB().length + ' khu vực', icon: 'user-check', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'hr-related', cls: 'mb16', items: [
      { key: 'dept', title: 'Phân bố theo phòng ban', icon: 'chart-pie', summary: st.total + ' nhân viên · ' + st.byDept.length + ' phòng ban', meta: st.byDept.length ? 'Đông nhất: ' + esc(st.byDept.slice().sort((a, b) => b.value - a.value)[0].label) + ' (' + F.pct(st.byDept.slice().sort((a, b) => b.value - a.value)[0].value, st.total) + '%)' : '', actions: U.iconBtn('more', 'dept-more', 'Xem theo phòng ban'), body: C.donutLegend(st.byDept.map(x => Object.assign({}, x, { text: x.value + ' (' + F.pct(x.value, st.total) + '%)' })), 150, String(st.total), 'Nhân viên') },
      { key: 'probation', title: 'Nhân viên sắp hết hợp đồng thử việc', icon: 'calendar-clock', summary: prob.length ? prob.length + ' nhân viên trong 30 ngày' : 'Không có', meta: prob.length ? 'Gần nhất: ' + esc(prob[0].e.name) + ' · ' + (prob[0].left < 0 ? 'quá ' + Math.abs(prob[0].left) : 'còn ' + prob[0].left) + ' ngày' : 'Không có nhân viên sắp hết thử việc', actions: '<a class="link small" href="#/hr?status=probation">Xem tất cả →</a>', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>#</th><th>Họ tên</th><th>Ngày hết hạn</th><th>Còn lại</th></tr></thead><tbody>${prob.map((x, i) => `<tr><td>${i + 1}</td><td>${U.link('#/hr/' + x.e.id, esc(x.e.name))}</td><td>${F.date(x.e.probationEnd)}</td><td>${U.chip(x.left < 0 ? 'Quá ' + Math.abs(x.left) + ' ngày' : x.left + ' ngày', x.left <= 5 ? 'red' : x.left <= 10 ? 'amber' : 'gray')}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Không có nhân viên sắp hết thử việc</td></tr>'}</tbody></table></div>` }
    ] })}
    ${U.card({ title: 'Danh sách nhân viên (' + rows.length + ' nhân viên)', icon: 'users', actions: U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', cls: 'btn-ghost', act: 'cols' }), body: null, id: 'et', attrs: 'data-guide="employees-table"' })}`;
    const cols = [{ key: 'code', label: 'Mã NV', sortable: true, render: e => U.link('#/hr/' + e.id, esc(e.code), 'bold') }, { key: 'name', label: 'Họ tên', sortable: true, render: e => esc(e.name) }, { key: 'unit', label: 'Đơn vị tổ chức', sortable: true, sortVal: e => Q.employeeUnit(e.id).name || '', render: e => { const u = Q.employeeUnit(e.id); return u.id ? U.cell2(esc(u.name), esc(Q.orgAncestors(u.id).slice(0, -1).map(x => x.name).slice(-1)[0] || '')) : `<span class="muted">${esc(Q.deptLabel(e.dept))}</span>`; } }, { key: 'title', label: 'Chức danh', sortable: true, render: e => esc((Q.employeePosition(e.id) || {}).name || e.title || '-') }, { key: 'phone', label: 'SĐT', render: e => esc(e.phone) }, { key: 'email', label: 'Email', render: e => shortMail(e.email) }, { key: 'area', label: 'Khu vực phụ trách', render: e => esc(e.area || '-') }, { key: 'building', label: 'Tòa nhà phụ trách', render: e => { const b = Q.primaryBuilding(e.id); return b.name ? esc(b.name.replace('Tòa ', '')) : '-'; } }, { key: 'status', label: 'Trạng thái', sortable: true, render: e => Q.chip('employee', e.status) }, { key: 'startDate', label: 'Ngày vào làm', sortable: true, render: e => F.date(e.startDate) }, { key: 'actions', label: 'Thao tác', render: e => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': e.id } }), U.moreBtn(e.id)]), hideable: false }];
    cols.splice(cols.length - 1, 0, { key: 'workload', label: 'Tòa / phòng quản lý', render: e => { const w = Q.staffWorkload(e.id); return U.cell2(w.buildings + ' tòa', w.rooms + ' phòng'); } });
    const tbl = U.table(root.querySelector('#et'), { rows, unit: 'nhân viên', selectable: true, colPrefsKey: 'employees', cols });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, add: () => Fm.employee({}), view: (el) => TH.go('#/hr/' + el.dataset.id), more: (el) => empMenu(el, St.get('employees', el.dataset.id)), cols: (b) => U.columnMenu(b, tbl, cols), 'dept-more': (b) => U.menu(b, st.byDept.map(x => ({ label: x.label + ' (' + x.value + ')', onClick: () => { TH.router.replaceQuery({ dept: x.key }); TH.router.refresh(); } }))), export: () => { F.download('danh-sach-nhan-vien.csv', F.csv(rows.map(e => [e.code, e.name, Q.deptLabel(e.dept), e.title, e.phone, e.email, e.area, Q.primaryBuilding(e.id).name || '', Q.label('employee', e.status), e.startDate]), ['Mã NV', 'Họ tên', 'Phòng ban', 'Chức danh', 'SĐT', 'Email', 'Khu vực', 'Tòa phụ trách', 'Trạng thái', 'Ngày vào làm']), 'text/csv'); ok('Đã xuất danh sách'); } });
  }, { menu: 'hr', permission: 'hr.view', scopeKey: 'hr' });

  /* ================= #/hr/timesheet – Chấm công (tự thiết kế, mô phỏng) ================= */
  TH.router.register('/hr/timesheet', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Chấm công' }]);
    const periods = Q.payrollPeriods(); const period = q.period || St.state.meta.period; const f = { dept: q.dept || '', buildingId: q.buildingId || '' };
    const emps = Q.filterEmployees(f); const sheets = {}; emps.forEach(e => { const t = Q.timesheet(e.id, period); if (t) sheets[e.id] = t; }); const st = Q.timesheetStats(period, f); const canEdit = TH.auth.can('timesheet.manage');
    root.innerHTML = `${U.pageHead({ title: 'Chấm công', phase: 3, sub: 'Bảng công theo tháng – nguồn ngày công cho bảng lương. ' + U.demoNote('<span class="chip gray">Tự thiết kế – không có PNG</span>') + ' ' + U.demoNote('<span class="chip amber">Mô phỏng – ngoài scope SRS §2.2</span>') + '', acts: [U.btn({ label: 'Điền mặc định', icon: 'sparkles', cls: 'btn-outline', act: 'fill', disabled: !canEdit || st.confirmed }), U.btn({ label: 'Xác nhận bảng công', icon: 'check', cls: 'btn-primary', act: 'confirm', disabled: !canEdit || st.confirmed, attrs: { 'data-guide': 'ts-confirm' } }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phòng ban', input: U.select({ name: 'dept', value: f.dept, all: 'Tất cả phòng ban', options: deptOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa phụ trách', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa', options: liveB().map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Ngày công chuẩn', value: st.std, cap: F.periodLabel(period) + ' (T2–T7)', icon: 'calendar', tone: 'blue' })}${U.kpi({ label: F.period(F.today()) === period ? 'Đi làm hôm nay' : 'Công bình quân', value: st.present, cap: F.period(F.today()) === period ? 'trên ' + emps.length + ' nhân viên' : 'ngày/nhân viên', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Nghỉ phép / vắng', value: st.leave, cap: 'lượt trong kỳ', icon: 'calendar-x', tone: 'amber' })}${U.kpi({ label: 'Đi muộn / OT', value: st.late + ' / ' + st.ot + 'h', cap: 'lượt muộn / giờ tăng ca', icon: 'clock', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'timesheet-related', cls: 'mb16', items: [
      { key: 'legend', title: 'Chú giải', icon: 'info', summary: Object.keys(Q.L.attCode).length + ' ký hiệu', meta: Object.entries(Q.L.attCode).map(([k, v]) => k + ' ' + v[0]).join(' · '), body: `<div class="att-legend">${Object.entries(Q.L.attCode).map(([k, v]) => `<span class="row gap8"><span class="c-${k} att-cell"><button type="button" class="att-btn">${k}</button></span>${esc(v[0])}</span>`).join('')}</div>` },
      { key: 'status', title: 'Trạng thái bảng công', icon: 'check-circle', summary: (st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft')) + ' ' + st.count + '/' + emps.length + ' bảng công', meta: (() => { const t = Object.values(sheets).find(x => x.confirmedBy); return t ? 'Xác nhận bởi ' + esc(Q.userName(t.confirmedBy)) + ' · ' + F.datetime(t.confirmedAt) : 'Chưa xác nhận – dùng cho bảng lương ' + F.periodLabel(period); })(), body: U.kv([['Kỳ', F.periodLabel(period)], ['Số bảng công', st.count + '/' + emps.length], ['Trạng thái', st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft')], ['Người xác nhận', (() => { const t = Object.values(sheets).find(x => x.confirmedBy); return t ? esc(Q.userName(t.confirmedBy)) + ' · ' + F.datetime(t.confirmedAt) : '-'; })()], ['Dùng cho', U.link('#/hr/payroll?period=' + period, 'Bảng lương ' + F.periodLabel(period))]]) },
      { key: 'note', title: 'Ghi chú', icon: 'book-open', summary: U.demoNote('Mô phỏng ngoài SRS §2.2') || 'Cách tính ngày công', meta: 'Cấp ngày công cho bảng lương (FR-HR-02)', body: U.note('info', 'Ghi chú', 'Chấm công/BHXH/thuế nằm ngoài phạm vi SRS v1.2 §2.2 – màn này mô phỏng theo scope §4.2 để cấp ngày công cho bảng lương (FR-HR-02).') }
    ] })}
    ${U.card({ title: 'Bảng công ' + F.periodLabel(period) + ' (' + emps.length + ' nhân viên)', icon: 'clipboard-list', sub: canEdit && !st.confirmed ? 'Bấm vào ô để đổi ký hiệu' : '', actions: st.confirmed ? Q.chip('timesheet', 'confirmed') : Q.chip('timesheet', 'draft'), bodyCls: 'tight', body: U.attendanceGrid({ employees: emps, period, sheets, editable: canEdit && !st.confirmed }) })}`;
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ period }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, att: (el) => U.menu(el, [{ header: Q.employeeName(el.dataset.emp) + ' · ' + F.date(el.dataset.date) }, ...Object.entries(Q.L.attCode).map(([k, v]) => ({ label: k + ' – ' + v[0], onClick: () => X.markAttendance(el.dataset.emp, el.dataset.date, k) }))]), fill: () => { const n = X.fillTimesheet(period, f); ok('Đã điền ' + n + ' ô', 'P ngày làm việc, O chủ nhật, L nếu tạm nghỉ'); }, confirm: async () => { if (await U.confirm({ title: 'Xác nhận bảng công ' + F.periodLabel(period) + '?', text: 'Sau xác nhận không sửa ô chấm công; bảng lương tính theo số công này.', ok: 'Xác nhận' })) { const n = X.confirmTimesheet(period, f); ok('Đã xác nhận bảng công', n + ' nhân viên'); } }, export: () => { F.download('bang-cong-' + period + '.csv', F.csv(emps.map(e => { const t = sheets[e.id] || {}; return [e.code, e.name, Q.deptLabel(e.dept), t.workDays || 0, t.offDays || 0, t.late || 0, t.otHours || 0, Q.label('timesheet', t.status || 'draft')]; }), ['Mã NV', 'Họ tên', 'Phòng ban', 'Công', 'Nghỉ', 'Muộn', 'OT', 'Trạng thái']), 'text/csv'); ok('Đã xuất bảng công'); } });
  }, { menu: 'timesheet', permission: 'timesheet.view', phase: 3, scopeKey: 'timesheet' });

  /* ================= #/hr/payroll – Bảng lương (spec v1.8 §4.26.5–4.26.7, §12.20) ================= */
  TH.router.register('/hr/payroll', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Bảng lương' }]);
    const periods = Q.payrollPeriods(); const period = q.period || St.state.meta.period; const f = { orgUnitId: q.orgUnitId || '', emp: q.emp || '' }; const pr = Q.payroll(period); const st = Q.payrollStats(pr);
    const unitEmp = f.orgUnitId ? new Set(Q.employeesOfUnits(Q.orgDescendants(f.orgUnitId), Q.periodEndDate(period)).map(e => e.id)) : null;
    const results = pr ? Q.payrollResults(pr.id).filter(r => (!unitEmp || unitEmp.has(r.employeeId)) && (!f.emp || r.employeeId === f.emp)) : []; const status = pr ? pr.status : 'none'; const stepIdx = { draft: 0, review: 1, approved: 2, locked: 3, paid: 3 }[status];
    const canM = TH.auth.can('payroll.manage'), canA = TH.auth.can('payroll.approve'), canL = TH.auth.can('payroll.lock'), canR = TH.auth.can('payroll.reopen'); const sal = pr ? Q.salaryTotals(Q.salaryPayments({ period })) : null;
    const acts = [];
    if (!pr) acts.push(U.btn({ label: 'Mở kỳ lương ' + F.periodShort(period), icon: 'play', cls: 'btn-primary', act: 'open', disabled: !canM, attrs: { 'data-guide': 'pay-open' } }));
    if (status === 'draft') acts.push(U.btn({ label: 'Refresh dữ liệu', icon: 'refresh-cw', cls: 'btn-outline', act: 'refresh', disabled: !canM, title: 'Snapshot lại phân công & thu tiền khi kỳ chưa khóa' }), U.btn({ label: 'Gửi review', icon: 'send', cls: 'btn-primary', act: 'submit', disabled: !canM, attrs: { 'data-guide': 'pay-submit' } }));
    if (status === 'review') acts.push(U.btn({ label: 'Trả lại', icon: 'undo', cls: 'btn-outline', act: 'return', disabled: !canA }), U.btn({ label: 'Duyệt', icon: 'check', cls: 'btn-primary', act: 'approve', disabled: !canA, attrs: { 'data-guide': 'pay-approve' } }));
    if (status === 'approved') acts.push(U.btn({ label: 'Khóa bảng lương', icon: 'lock', cls: 'btn-primary', act: 'lock', disabled: !canL, attrs: { 'data-guide': 'pay-lock' }, title: 'Khóa → sinh danh sách chi lương + phân bổ chi phí lương theo tòa' }));
    if (['approved', 'locked'].includes(status)) acts.push(U.btn({ label: 'Mở lại', icon: 'unlock', cls: 'btn-outline', act: 'reopen', disabled: !canR, title: 'Chỉ Admin, có lý do/audit' }));
    if (status === 'locked') acts.push(U.btn({ label: 'Chi lương', icon: 'banknote', cls: 'btn-primary', act: 'salary', attrs: { 'data-guide': 'pay-salary' } }));
    acts.push(U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export', disabled: !pr }));
    const byB = pr ? Q.payrollByBuilding(pr) : []; const hist = St.all('payrolls').slice().sort((a, b) => F.cmp(b.period, a.period));
    root.innerHTML = `${U.pageHead({ title: 'Bảng lương', sub: 'Mở kỳ → snapshot phân công tòa → thu M1/M2/M3 → hiệu suất → Payroll Rule → lương theo phòng → cộng cơ bản/phụ cấp → Review → Điều chỉnh có lý do → Duyệt → Khóa (§4.26.6). Không tạo/sửa phân công tại đây.', acts })}
    ${U.filterbar([U.field({ label: 'Kỳ lương', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Đơn vị', input: U.select({ name: 'orgUnitId', value: f.orgUnitId, all: 'Toàn công ty', options: Q.orgOptions ? Q.orgOptions() : [], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Nhân viên', input: U.select({ name: 'emp', value: f.emp, all: 'Tất cả nhân viên', options: (pr ? Q.payrollResults(pr.id) : []).map(r => [r.employeeId, Q.employeeName(r.employeeId)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.stepperStatus([{ label: 'Nháp', date: pr ? F.date((pr.createdAt || '').slice(0, 10)) : '', by: pr ? Q.userName(pr.createdBy) : '' }, { label: 'Chờ duyệt', date: pr && pr.submittedAt ? F.date(pr.submittedAt) : '', by: pr && pr.submittedBy ? Q.userName(pr.submittedBy) : '' }, { label: 'Đã duyệt', date: pr && pr.approvedAt ? F.date(pr.approvedAt) : '', by: pr && pr.approvedBy ? Q.userName(pr.approvedBy) : '' }, { label: 'Đã khóa', date: pr && pr.lockedAt ? F.date(pr.lockedAt) : '', by: pr && pr.lockedBy ? Q.userName(pr.lockedBy) : '' }], pr ? stepIdx : -1)}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng thực nhận', value: F.vnd(st.total), cap: st.count + ' nhân viên · ' + (pr ? Q.label('payroll', pr.status) : 'chưa mở kỳ'), icon: 'banknote', tone: 'blue' })}${U.kpi({ label: 'Lương hiệu suất theo phòng', value: F.vnd(st.perf), cap: 'Số phòng × mức lương/phòng (Payroll Rule)', icon: 'trending-up', tone: 'green' })}${U.kpi({ label: 'Cơ bản + phụ cấp', value: F.vnd(st.base + st.allow), cap: 'Cơ bản ' + F.short(st.base) + ' · ăn trưa/xăng xe/trưởng nhóm/hỗ trợ ' + F.short(st.allow), icon: 'coins', tone: 'amber' })}${U.kpi({ label: 'Điều chỉnh / khấu trừ', value: (st.adjust >= 0 ? '+' : '') + F.short(st.adjust) + ' / −' + F.short(st.deductions), cap: sal ? 'Chi lương: ' + F.short(sal.paid) + ' / ' + F.short(sal.due) : 'Điều chỉnh bắt buộc có lý do', icon: 'sliders', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'payroll-related', cls: 'mb16', items: [
      { key: 'formula', title: 'Công thức (§4.26.5)', icon: 'info', summary: 'Thực nhận = Cơ bản + PC ăn trưa + PC xăng xe + Lương trưởng nhóm + Lương hỗ trợ + Lương hiệu suất + Điều chỉnh − Khấu trừ', meta: (pr && pr.ruleVersionIds ? 'Rule snapshot: ' + pr.ruleVersionIds.map(id => (St.get('payrollRuleVersions', id) || {}).code).filter(Boolean).join(', ') : 'Payroll Rule Version có hiệu lực') + ' · không tính hoa hồng Sale (§4.27.5)', body: `<div class="small">${U.kv([['Lương hiệu suất theo phòng', 'Σ (Số phòng tòa × Mức lương/phòng theo bậc hiệu suất) – snapshot NV + tòa + kỳ'], ['Hiệu suất', 'Tổng DT thu được / DT niêm yết × 100 (Hiệu suất thu tiền)'], ['Rule version', pr && pr.ruleVersionIds && pr.ruleVersionIds.length ? pr.ruleVersionIds.map(id => { const r = St.get('payrollRuleVersions', id) || {}; return esc(r.code || '') + ' ' + (r.confirmation ? U.chip('Chờ chốt', 'amber') : ''); }).join(' · ') : '—'], ['Snapshot', pr ? F.datetime(pr.snapshotAt) + ' · ' + (pr.buildings || 0) + ' tòa' : '—']], 'one')}${U.note('warn', 'Chờ chốt §4.26.3/§4.26.4', 'Sheet nguồn không lưu công thức Tổng DT thu được và bậc mức lương/phòng – demo dùng rule giả định; kỳ cũ giữ snapshot version.')}</div>` },
      { key: 'by-building', title: 'Chi phí lương theo tòa (Payroll Cost Allocation)', icon: 'building', summary: pr ? byB.length + ' tòa · ' + F.vnd(F.sum(byB, x => x.value)) : 'Chưa có bảng lương', meta: byB.length ? 'Cao nhất: ' + esc(byB[0].label) + ' ' + F.vnd(byB[0].value) + (status === 'locked' ? ' · NV trực tiếp theo snapshot, vai trò chung theo Allocation Rule' : ' · tạm tính theo lương hiệu suất – chốt khi khóa') : 'Mở kỳ lương để xem phân bổ', body: pr && byB.length ? C.vbar({ items: byB.map(x => ({ label: x.label, value: Math.round(x.value / 1e6) })), height: 170, unit: 'tr' }) : '<div class="muted small">Chưa có bảng lương</div>' },
      { key: 'history', title: 'Lịch sử kỳ lương & audit', icon: 'history', summary: hist.length + ' kỳ', meta: pr && pr.history && pr.history.length ? 'Gần nhất: ' + esc(pr.history[pr.history.length - 1].text) : 'Chưa có', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Kỳ</th><th class="num">Tổng</th><th>Trạng thái</th></tr></thead><tbody>${hist.map(x => `<tr><td>${U.link('#/hr/payroll?period=' + x.period, F.periodLabel(x.period))}</td><td class="num">${F.vnd(x.total)}</td><td>${Q.chip('payroll', x.status)}</td></tr>`).join('') || '<tr><td colspan="3" class="muted tc">Chưa có</td></tr>'}</tbody></table></div>${pr && pr.history && pr.history.length ? '<div class="small bold mt12">Lịch sử ' + esc(pr.code) + '</div>' + U.timeline(pr.history.slice().reverse().slice(0, 8).map(h => ({ when: F.datetime(h.at), title: h.text, sub: Q.userName(h.by), color: h.type === 'lock' ? 'green' : h.type === 'reopen' ? 'red' : h.type === 'adjust' || h.type === 'deduction' ? 'amber' : 'blue', fill: true }))) : ''}` }
    ] })}
    ${pr ? U.card({ title: 'Bảng lương ' + esc(pr.code) + ' (' + results.length + ' nhân viên)', icon: 'clipboard-list', sub: esc(pr.note || ''), actions: Q.chip('payroll', pr.status) + ' ' + U.btn({ label: 'Hiệu suất thu tiền', icon: 'trending-up', size: 'btn-sm', cls: 'btn-outline', act: 'perf' }), body: null, id: 'pt', attrs: 'data-guide="payroll-table"' }) : U.card({ body: U.empty({ icon: 'banknote', title: 'Chưa mở kỳ lương ' + F.periodLabel(period), text: 'Mở kỳ để snapshot phân công tòa & số thu M1/M2/M3 từ Payment Allocation – không nhập tay (§4.26.10).', action: canM ? U.btn({ label: 'Mở kỳ lương', icon: 'play', size: 'btn-sm', cls: 'btn-primary', act: 'open' }) : '' }) })}`;
    const editable = pr && ['draft', 'review'].includes(pr.status) && canM;
    if (pr) U.table(root.querySelector('#pt'), { rows: results, unit: 'nhân viên', pageSize: 15, colPrefsKey: 'payroll', footer: (rows) => `<tr class="dist-total"><td colspan="2">Tổng cộng (${rows.length})</td><td class="num">${F.sum(rows, l => l.rooms)}</td><td class="num">${F.vnd(F.sum(rows, l => l.base))}</td><td class="num">${F.vnd(F.sum(rows, l => l.lunch))}</td><td class="num">${F.vnd(F.sum(rows, l => l.fuel))}</td><td class="num">${F.vnd(F.sum(rows, l => l.leadAllowance))}</td><td class="num">${F.vnd(F.sum(rows, l => l.support))}</td><td class="num">${F.vnd(F.sum(rows, l => l.perfTotal))}</td><td class="num">${F.vnd(F.sum(rows, l => l.adjustmentTotal))}</td><td class="num">${F.vnd(F.sum(rows, l => l.deductions))}</td><td class="num">${F.vnd(F.sum(rows, l => l.net))}</td><td></td></tr>`, cols: [
      { key: 'emp', label: 'Nhân viên', sortable: true, sortVal: l => Q.employeeName(l.employeeId), render: l => U.cell2(U.link('#/hr/' + l.employeeId, esc(Q.employeeName(l.employeeId)), 'bold'), esc((Q.orgUnit(l.orgUnitId) || {}).name || Q.employee(l.employeeId).code || '')) },
      { key: 'pos', label: 'Chức danh', render: l => esc((Q.employeePosition(l.employeeId, Q.periodEndDate(period)) || {}).name || Q.employee(l.employeeId).title || '-') },
      { key: 'rooms', label: 'Tòa / phòng', num: true, render: l => l.buildings ? l.buildings + ' tòa · ' + l.rooms : '-' },
      { key: 'base', label: 'Lương cơ bản', num: true, sortable: true, render: l => F.vnd(l.base) },
      { key: 'lunch', label: 'PC ăn trưa', num: true, render: l => F.vnd(l.lunch) },
      { key: 'fuel', label: 'PC xăng xe', num: true, render: l => F.vnd(l.fuel) },
      { key: 'lead', label: 'Lương trưởng nhóm', num: true, render: l => l.leadAllowance ? F.vnd(l.leadAllowance) : '-' },
      { key: 'support', label: 'Lương hỗ trợ', num: true, render: l => l.support ? F.vnd(l.support) : '-' },
      { key: 'perf', label: 'Lương hiệu suất theo phòng', num: true, sortable: true, sortVal: l => l.perfTotal, render: l => l.perfTotal ? `<b>${F.vnd(l.perfTotal)}</b>` : '-' },
      { key: 'adj', label: 'Điều chỉnh', num: true, render: l => l.adjustmentTotal ? `<span class="${l.adjustmentTotal > 0 ? 'green' : 'red'}" title="${esc((l.adjustments || []).map(a => a.reason).join('; '))}">${l.adjustmentTotal > 0 ? '+' : ''}${F.vnd(l.adjustmentTotal)}</span>` : '-' },
      { key: 'ded', label: 'Khấu trừ', num: true, render: l => l.deductions ? `<span class="red" title="${esc(l.deductionNote || '')}">−${F.vnd(l.deductions)}</span>` : '-' },
      { key: 'net', label: 'Thực nhận', num: true, sortable: true, sortVal: l => l.net, render: l => `<b>${F.vnd(l.net)}</b>` },
      { key: 'actions', label: '', render: l => U.rowActions([U.iconBtn('search', 'drill', 'Drill-down §4.26.7', { 'data-id': l.employeeId, 'data-guide': 'pay-drill' }), editable ? U.iconBtn('sliders', 'adjust', 'Điều chỉnh có lý do', { 'data-id': l.employeeId, 'data-guide': 'pay-adjust' }) : '', editable ? U.iconBtn('minus-circle', 'deduction', 'Khấu trừ', { 'data-id': l.employeeId }) : '']), hideable: false }] });
    const drill = (employeeId) => { const e = Q.employee(employeeId); const r = Q.payrollResult(pr.id, employeeId) || {}; const snaps = Q.payrollSnapshots(pr.id, employeeId); U.modal({ title: 'Drill-down lương – ' + esc(e.name), wide: true, sub: 'NV → tòa phụ trách trong kỳ → số phòng → DT → M1/M2/M3 → DV → thu thêm → hiệu suất → mức lương/phòng → lương từng tòa (§4.26.7 – đối soát sheet Bảng lương)', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Tòa</th><th>Vai trò</th><th class="num">Phòng</th><th class="num">DT niêm yết</th><th class="num">DT phải thu</th><th class="num">M1</th><th class="num">M2</th><th class="num">M3</th><th class="num">Sau 3 mốc</th><th class="num">Dịch vụ</th><th class="num">Thu thêm</th><th class="num">Tổng DT thu được</th><th class="num">Hiệu suất</th><th class="num">Mức/phòng</th><th class="num">Lương tòa</th><th></th></tr></thead><tbody>${snaps.map(s => `<tr><td>${esc((Q.building(s.buildingId).name || '').replace('Tòa ', ''))}</td><td>${Q.chip('payrollRole', s.role)}</td><td class="num">${s.rooms}</td><td class="num">${F.vnd(s.listed)}</td><td class="num">${F.vnd(s.receivable)}</td><td class="num">${F.vnd(s.M1)}</td><td class="num">${F.vnd(s.M2)}</td><td class="num">${F.vnd(s.M3)}</td><td class="num">${F.vnd(s.after3)}</td><td class="num">${F.vnd(s.service)}</td><td class="num">${F.vnd(s.extra)}</td><td class="num"><b>${F.vnd(s.collected)}</b></td><td class="num">${s.efficiency}%</td><td class="num" title="${esc(s.ruleCode + ' · ' + s.tier)}">${F.vnd(s.ratePerRoom)}</td><td class="num"><b>${F.vnd(s.roomSalary)}</b></td><td>${U.iconBtn('search', 'snap-drill', 'Giao dịch thu', { 'data-b': s.buildingId, 'data-role': s.role })}</td></tr>`).join('') || '<tr><td colspan="16" class="muted tc">Không phụ trách tòa trong kỳ (Phụ trách chính / Hỗ trợ)</td></tr>'}</tbody></table></div><div class="mt12">${U.kv([['Lương cơ bản', F.vnd(r.base)], ['PC ăn trưa + xăng xe', F.vnd((r.lunch || 0) + (r.fuel || 0))], ['Lương trưởng nhóm / hỗ trợ', F.vnd(r.leadAllowance || 0) + ' / ' + F.vnd(r.support || 0)], ['Tổng lương hiệu suất theo phòng', '<b>' + F.vnd(r.perfTotal || 0) + '</b>'], ['Điều chỉnh', (r.adjustments || []).map(a => (a.amount > 0 ? '+' : '') + F.vnd(a.amount) + ' – ' + esc(a.reason) + ' (' + esc(Q.userName(a.by)) + ')').join('<br>') || '—'], ['Khấu trừ', r.deductions ? '−' + F.vnd(r.deductions) + ' – ' + esc(r.deductionNote || '') : '—'], ['Thực nhận', '<b>' + F.vnd(r.net || 0) + '</b>']], 'one')}</div>`, footer: U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'close' }), onMount: (m) => U.bind(m.el, { close: () => m.close(), 'snap-drill': (b) => { const row = Q.perfRows(period, { employeeId, buildingId: b.dataset.b }).find(x => x.role === b.dataset.role) ; if (row && TH.pages.perfDrill) TH.pages.perfDrill(row); } }) }); };
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ period }, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    const act = (fn, msg) => { try { const r = fn(); ok(typeof msg === 'function' ? msg(r) : msg); } catch (e) { U.toast('err', 'Không thực hiện được', e.message); } };
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, open: () => act(() => X.openPayrollPeriod(period), r => 'Đã mở kỳ lương ' + r.code + ' – ' + r.employees + ' NV, ' + F.vnd(r.total)), refresh: () => act(() => X.refreshPayroll(period), 'Đã refresh snapshot phân công & thu tiền'), submit: () => act(() => X.submitPayroll(period), 'Đã gửi review bảng lương'), return: () => Fm.payrollReturn(period), approve: () => act(() => X.approvePayroll(period), 'Đã duyệt bảng lương ' + F.periodLabel(period)), lock: async () => { if (await U.confirm({ title: 'Khóa bảng lương ' + F.periodLabel(period) + '?', text: 'Sau khóa: sinh danh sách chi lương, phân bổ chi phí lương theo tòa (Payroll Cost Allocation); chỉ Admin mở lại có lý do.', ok: 'Khóa' })) act(() => X.lockPayroll(period), r => 'Đã khóa ' + r.code + ' – danh sách chi lương đã sẵn sàng'); }, reopen: () => Fm.payrollReopen(period), salary: () => TH.go('#/hr/salary-payments?period=' + period), perf: () => TH.go('#/hr/collection-performance?period=' + period), export: () => act(() => X.exportPayroll(period), n => 'Đã xuất bảng lương ' + n + ' dòng'), drill: (el) => drill(el.dataset.id), adjust: (el) => Fm.payrollAdjust(period, el.dataset.id), deduction: (el) => Fm.payrollDeduction(period, el.dataset.id) });
  }, { menu: 'payroll', permission: 'payroll.view', scopeKey: 'payroll' });
  /* ================= #/hr/:id – Chi tiết nhân viên (PNG 07/02) ================= */
  TH.router.register('/hr/:id', (root, p, q) => {
    const e = St.get('employees', p.id); if (!e) { root.innerHTML = U.empty({ title: 'Không tìm thấy nhân viên' }); return; }
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Nhân viên', href: '#/hr' }, { label: 'Chi tiết nhân viên' }]);
    const tab = q.tab || 'overview'; const period = St.state.meta.period; const as = Q.assignmentsOf(e.id); const kpi = Q.employeeKpi(e, period); const acts = Q.employeeActivities(e, 4); const week = Q.employeeWeek(e); const mgr = e.managerId ? Q.employee(e.managerId) : null; const u = e.userId ? Q.user(e.userId) : null;
    const contractsMonth = e.userId ? St.where('contracts', c => c.managerId === e.userId && F.period(c.createdAt || c.start) === period).length + kpi.deals : 0;
    root.innerHTML = `${U.pageHead({ title: 'Chi tiết nhân viên', sub: 'Xem và quản lý thông tin chi tiết của nhân viên trong hệ thống.', back: '#/hr', acts: [U.btn({ label: 'Chỉnh sửa', icon: 'pencil', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), U.btn({ label: 'Phân công tòa nhà', icon: 'building', cls: 'btn-outline', act: 'assign', disabled: !canManage() || e.status === 'resigned', attrs: { 'data-guide': 'emp-assign' } }), U.btn({ label: 'Cập nhật hồ sơ', icon: 'user-plus', cls: 'btn-primary', act: 'profile', disabled: !canManage() })] })}
    ${U.profileHero({ name: e.name, chip: Q.chipDot('employee', e.status), meta: [['Mã nhân viên', esc(e.code)], ['Chức danh', esc(e.title)], ['Phòng ban', esc(Q.deptLabel(e.dept))], ['Ngày vào làm', I('calendar') + ' ' + F.date(e.startDate), 'Đã làm việc ' + Q.seniority(e.startDate)]] })}
    <div class="two-col">
      <div class="side-stack">${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'assign', label: 'Phân công', count: as.length }, { key: 'docs', label: 'Hồ sơ', count: (e.documents || []).length }, { key: 'history', label: 'Lịch sử' }], tab, 'card-tabs')}<div id="tab-body" class="side-stack"></div></div>
      <aside class="side-stack">${U.card({ title: 'Thống kê nhanh', icon: 'bar-chart', body: `<div class="grid grid-2">${U.miniStat({ label: 'Tòa nhà phụ trách', value: Q.staffWorkload(e.id).buildings, icon: 'building', tone: 'blue' })}${U.miniStat({ label: 'Phòng quản lý', value: Q.staffWorkload(e.id).rooms, icon: 'door', tone: 'green' })}${U.miniStat({ label: 'Lead đang xử lý', value: kpi.openLeads, icon: 'users', tone: 'amber' })}${U.miniStat({ label: 'Hợp đồng trong tháng', value: contractsMonth, icon: 'file-text', tone: 'purple' })}</div>` })}
      ${U.card({ title: 'Lịch làm việc tuần này', icon: 'calendar', actions: '<a class="link small" href="#/maintenance/schedules">Xem tất cả →</a>', bodyCls: 'tight', body: `<div class="week-list">${week.map((dd, i) => `<div class="week-row ${dd.date === F.today() ? 'today' : ''}"><div class="wk-d"><b>Th ${i + 2}</b><small>${dd.date.slice(8, 10)}/${dd.date.slice(5, 7)}</small></div><div class="grow">${dd.items.map(it => `<div class="wk-it"><span class="dot" style="background:var(--${it.color === 'blue' ? 'primary' : it.color === 'green' ? 'green-500' : it.color === 'amber' ? 'amber-500' : it.color === 'red' ? 'red-500' : it.color === 'purple' ? 'purple' : 'teal'})"></span><div><span class="small muted">${esc(it.time)}</span><b>${esc(it.title)}</b><small>${esc(it.place)}</small></div></div>`).join('') || '<span class="muted small">Trống</span>'}</div></div>`).join('')}</div>` })}
      ${U.card({ title: 'Tài liệu liên quan', icon: 'folder', actions: U.btn({ label: 'Thêm tài liệu', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'doc-add', disabled: !canManage() }), body: (e.documents || []).length ? `<div class="file-list">${e.documents.map(d => U.fileItem({ name: d.name, fileName: d.fileName, date: d.date, size: d.size }, U.moreBtn(d.id, 'data-doc="1"'))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' }) })}</aside></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin liên hệ', icon: 'id-card', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), body: U.kv([[I('user') + ' Họ tên', esc(e.name)], [I('mail') + ' Email', esc(e.email || '-')], [I('phone') + ' Số điện thoại', esc(e.phone)], [I('map-pin') + ' Địa chỉ', esc(e.address || '-')]].map(([k, v]) => [k.replace(/<[^>]+>/g, '').trim(), v]), 'one') })}${U.card({ title: 'Thông tin công việc', icon: 'briefcase', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit', disabled: !canManage() }), body: U.kv([['Mã nhân viên', esc(e.code)], ['Đơn vị chính', (() => { const u = Q.employeeUnit(e.id); return u.id ? U.link('#/hr/org?unit=' + u.id, esc(Q.orgPath(u.id))) : esc(Q.deptLabel(e.dept)); })()], ['Chức danh', esc((Q.employeePosition(e.id) || {}).name || e.title)], ['Kiêm nhiệm', Q.employmentAt(e.id).filter(a => !a.isPrimary).map(a => esc(Q.orgUnit(a.orgUnitId).name)).join(', ') || '-'], ['Lead của đơn vị', (() => { const u = Q.employeeUnit(e.id); const l = u.id ? Q.orgLead(u.id) : {}; return l.id ? (l.id === e.id ? '<b>Chính nhân viên này</b>' : U.link('#/hr/' + l.id, esc(l.name))) : '-'; })()], ['Hình thức làm việc', esc(e.workType || '-')], ['Quản lý trực tiếp', mgr ? U.link('#/hr/' + mgr.id, esc(mgr.name)) : '-'], ['Ngày vào làm', F.date(e.startDate)], ['Trạng thái', Q.chip('employee', e.status)], ['Tài khoản', u ? esc(u.username) + ' – ' + esc(TH.auth.ROLE_LABEL[u.role] || u.role) : '<span class="muted">Chưa có</span>']], 'one') })}</div>
    <div class="grid grid-2">${U.card({ title: 'Tòa nhà phụ trách', icon: 'building', actions: U.btn({ label: 'Phân công thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'assign', disabled: !canManage() || e.status === 'resigned' }), body: as.length ? as.map(a => { const b = Q.building(a.buildingId); return `<div class="up-row"><div class="thumb" style="width:52px;height:44px;background:var(--blue-bg);color:var(--blue)">${I('building-2')}</div><div class="grow"><b>${U.link('#/buildings/' + b.id, esc(b.name || ''))}</b><div class="small muted">${esc(b.address || '')}</div><div class="xs muted">${Q.label('assignRole', a.role)} · từ ${F.date(a.start)}</div></div>${a.primary ? U.chip('Chính', 'blue') : U.chip('Phụ', 'gray')}</div>`; }).join('') : U.empty({ icon: 'building', title: 'Chưa phân công tòa' }) })}
    ${U.card({ title: 'KPI cá nhân', icon: 'trending-up', sub: '(' + F.periodLabel(period) + ')', actions: `<a class="link small" href="${e.userId ? '#/crm?saleId=' + e.userId : '#/crm'}">Xem chi tiết →</a>`, body: kpi.hasUser ? `<div class="grid grid-2">${U.miniStat({ label: 'Lead đã xử lý', value: kpi.leads, icon: 'user', tone: 'green' })}${U.miniStat({ label: 'Hợp đồng thành công', value: kpi.deals, icon: 'file-text', tone: 'blue' })}${U.miniStat({ label: 'Doanh thu mang về (VND)', value: F.vnd(kpi.revenue), icon: 'dollar', tone: 'amber' })}${U.miniStat({ label: 'Tỷ lệ chuyển đổi', value: kpi.rate + '%', icon: 'target', tone: 'purple' })}</div><div class="xs muted mt8">Tính từ lead/giao dịch CRM (Phase 2) theo tài khoản ${esc(u ? u.username : '')}.</div>` : U.empty({ icon: 'trending-up', title: 'Chưa gắn tài khoản', text: 'KPI tính từ hoạt động CRM/bảo trì theo tài khoản đăng nhập của nhân viên.' }) })}</div>
    ${U.card({ title: 'Hoạt động gần đây', icon: 'activity', actions: `<a class="link small" href="#/hr/${e.id}?tab=history">Xem tất cả →</a>`, body: acts.length ? U.timeline(acts.map(a => ({ when: F.datetime(a.at), title: a.title, sub: a.sub + ' · ' + e.name, color: a.color, fill: true }))) : U.empty({ title: 'Chưa có hoạt động' }) })}`;
    if (tab === 'assign') { const list = Q.assignmentsOf(e.id, false).sort((a, b) => F.cmp(b.start, a.start)); const w = Q.assignmentWorkload(e.id); body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ mini: true, label: 'Nhà hiện tại', value: w.current.length, cap: w.currentRooms + ' phòng', icon: 'building', tone: 'blue' })}${U.kpi({ mini: true, label: 'Nhà sắp tới', value: w.upcoming.length, cap: w.upcomingRooms + ' phòng', icon: 'calendar-clock', tone: 'purple' })}${U.kpi({ mini: true, label: 'Phụ trách chính', value: w.current.filter(b => (Q.managerAssignment(b.id) || {}).employeeId === e.id).length, cap: 'tòa quyết định scope/lương', icon: 'user-check', tone: 'green' })}${U.kpi({ mini: true, label: 'Chờ duyệt', value: list.filter(a => a.status === 'pending').length, cap: 'đề xuất', icon: 'clock', tone: 'amber' })}</div>` + U.card({ title: 'Phân công tòa nhà (§4.25)', icon: 'building', sub: 'Nguồn chuẩn duy nhất – workflow Dự thảo → Chờ duyệt → Đã duyệt → Đang hiệu lực → Hết hiệu lực', actions: U.btn({ label: 'Phân công', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'assign', disabled: !canManage() || e.status === 'resigned' }) + `<a class="btn btn-outline btn-sm" href="#/hr/assignments?employeeId=${e.id}&view=history">Mở màn Phân công</a>`, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Tòa nhà</th><th>Vai trò</th><th>Từ ngày</th><th>Đến ngày</th><th>Trạng thái</th><th>Lý do</th><th></th></tr></thead><tbody>${list.map(a => `<tr><td>${U.link('#/buildings/' + a.buildingId + '?tab=staff', esc(Q.building(a.buildingId).name || ''))}</td><td>${Q.chip('assignRole', a.role)}</td><td>${F.date(a.start)}</td><td>${a.end ? F.date(a.end) : '—'}</td><td>${Q.chip('assignment', a.status)}</td><td class="xs">${esc(a.reason || '')}</td><td class="tr">${TH.pages.assignmentMenu ? U.moreBtn(a.id, 'data-asn="1"') : ''}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Chưa có phân công</td></tr>'}</tbody></table>` }); }
    if (tab === 'docs') body.innerHTML = U.card({ title: 'Hồ sơ nhân sự', icon: 'folder', actions: U.btn({ label: 'Thêm tài liệu', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'doc-add', disabled: !canManage() }), body: `${canManage() ? (() => { const c = Q.employeePayroll(e); return U.kv([['Lương cơ bản', F.vnd(c.base)], ['PC ăn trưa / xăng xe', F.vnd(c.lunch) + ' / ' + F.vnd(c.fuel)], ['Lương trưởng nhóm / hỗ trợ', F.vnd(c.leadAllowance) + ' / ' + F.vnd(c.support)], ['Lương hiệu suất theo phòng', 'Tính khi mở kỳ lương (thu M1/M2/M3 × Payroll Rule – §4.26)'], ['TK nhận lương', c.bankAccount ? esc((c.bankAccount.bank || '') + ' · ' + (c.bankAccount.number || '')) : '<span class="muted">Chưa có</span>'], ['Hình thức', esc(e.workType || '-')]], 'one') + '<div class="mt8">' + U.btn({ label: 'Cấu phần lương', icon: 'sliders', size: 'btn-sm', cls: 'btn-outline', act: 'pay-config' }) + '</div><hr class="mt12 mb12">'; })() : U.note('info', '', 'Trường lương chỉ hiển thị cho Nhân sự/Admin (AC-FR-HR-01-2).')}${(e.documents || []).length ? `<div class="file-list">${e.documents.map(d => U.fileItem({ name: d.name, fileName: d.fileName, date: d.date, size: d.size }, U.moreBtn(d.id, 'data-doc="1"'))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' })}` });
    if (tab === 'history') body.innerHTML = U.card({ title: 'Lịch sử', icon: 'history', body: Q.employeeActivities(e, 30).length ? U.timeline(Q.employeeActivities(e, 30).map(a => ({ when: F.datetime(a.at), title: a.title, sub: a.sub, color: a.color }))) : U.empty({ title: 'Chưa có lịch sử' }) });
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'pay-config': () => Fm.payrollConfig(e), edit: () => Fm.employee(e), assign: () => TH.forms.assignment ? TH.forms.assignment({ employeeId: e.id, role: 'support', onDone: () => TH.router.refresh() }) : assignModal(e), profile: () => Fm.employee(e), 'doc-add': () => docModal(e), 'end-assign': async (el) => { if (await U.confirm({ title: 'Kết thúc phân công?', text: 'Giữ lịch sử, ngày kết thúc = hôm nay.', ok: 'Kết thúc' })) { X.endAssignment(el.dataset.id); ok('Đã kết thúc phân công'); } }, more: (el) => { if (el.dataset.asn) return TH.pages.assignmentMenu(el, Q.assignment(el.dataset.id)); if (el.dataset.doc) { const d = (e.documents || []).find(x => x.id === el.dataset.id); U.menu(el, [{ label: 'Tải xuống', icon: 'download', onClick: () => U.fakePdf(d.name, ['Nhân viên: ' + e.name, 'File: ' + d.fileName, 'Ngày: ' + F.date(d.date)]) }, { label: 'Xóa', icon: 'trash', danger: true, disabled: !canManage(), onClick: () => { X.removeEmployeeDoc(e.id, d.id); ok('Đã xóa tài liệu'); } }]); } else empMenu(el, e); } });
  }, { menu: 'hr', permission: 'hr.view', scopeKey: 'hr' });

})(window.TH);
