/* Shared four-step workspace: all entry modes keep the same editable draft. */
(function(TH){
  const I=TH.intake,B=TH.intakeFiles,S=TH.store,U=TH.ui,F=TH.f,esc=F.esc;
  const button=(text,act,extra='')=>`<button type="button" class="btn" data-intake="${act}" ${extra}>${esc(text)}</button>`;
  const source=s=>s?`${s.file||'Nhập tay'}${s.sheet?' · '+s.sheet+'!'+(s.cell||s.row||''):''}${s.page?' · trang '+s.page:''}${s.confidence!=null?' · OCR '+Math.round(s.confidence)+'%':''}${s.raw!=null?' · '+String(s.raw):''}`:'';
  const options=(rows,value)=>rows.map(([id,label])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(label)}</option>`).join('');
  const attachmentList=target=>S.where('intakeAttachments',a=>a.targetId===target).map(a=>`<p>${esc(a.name)} ${button('Tải file gốc','file',`data-file="${esc(a.fileId)}"`)}</p>`).join('');
  TH.intakeAttachmentList=attachmentList;
  TH.router.handle('/owners',(root)=>{
    root.innerHTML=U.pageHead({title:'Chủ nhà',sub:'Mỗi chủ nhà một hồ sơ, liên kết nhiều hợp đồng và tòa',acts:[U.btn({label:'Thêm chủ nhà',href:'#/owners/new',cls:'btn-primary',perm:'owners.manage'})]})+`<div class="card intake-list">${S.all('owners').map(o=>{const contracts=S.where('ownerContracts',c=>c.ownerId===o.id);return `<p><a href="#/owner-profiles/${esc(o.id)}"><strong>${esc(o.name)}</strong></a> · ${esc(o.phone||'Chưa có SĐT')}<br><span class="muted">${contracts.length} hợp đồng · ${contracts.map(c=>esc(TH.q.building(c.buildingId)?.code||'')).join(', ')}</span></p>`;}).join('')||'Chưa có hồ sơ'}</div>`;
  });
  TH.router.handle('/owner-profiles/:id',(root,p)=>{
    const owner=S.get('owners',p.id);if(!owner){root.textContent='Không tìm thấy chủ nhà';return;}
    const contracts=S.where('ownerContracts',c=>c.ownerId===owner.id);
    root.innerHTML=U.pageHead({title:esc(owner.name),back:'#/owners',sub:esc([owner.phone,owner.idNo,owner.address,owner.bank].filter(Boolean).join(' · '))})+contracts.map(c=>{const result=S.one('intakeResults',x=>x.targetId===c.id);return U.card({title:esc(c.contractCode||c.code),body:`<p><a href="#/owners/${esc(c.id)}">Chi tiết hợp đồng / phụ lục</a> · <a href="#/buildings/${esc(c.buildingId)}">Tòa ${esc(TH.q.building(c.buildingId)?.code)}</a> · <a href="#/owner-payments">Lịch trả chủ nhà</a></p><p>${F.date(c.startDate)} → ${F.date(c.endDate)} · ${F.vnd(TH.actions.ownerRentAt(c.id,c.startDate))}/tháng · kỳ ${c.payCycleMonths} tháng</p>${attachmentList(c.id)}${result?`<details><summary>Nguồn và lịch sử xác nhận</summary><pre>${esc(JSON.stringify({sources:result.draft.sources,history:result.draft.history},null,2))}</pre></details>`:''}`});}).join('');
    root.querySelectorAll('[data-file]').forEach(el=>el.onclick=()=>B.download(el.dataset.file).catch(e=>U.toast('error',e.message)));
  });
  async function workspace(root,p,q,kind){
    let draft=I.blank(kind),step=0,mode=q.mode||'contract',queue=[],sheets=[],selectedFile,controller,busy=false,message='';
    draft.id=F.uid('intake');draft.history=[];
    if(q.draft){try{draft=await B.getDraft(q.draft);if(!draft||draft.kind!==kind)throw new Error('Không tìm thấy bản nháp phù hợp');}catch(e){root.textContent=e.message;return;}}
    if(q.room&&kind==='tenant'&&!draft.data.roomCode){const r=TH.q.room(q.room),b=r&&TH.q.building(r.buildingId);if(b){draft.data.roomCode=r.code;draft.data.buildingCode=b.code;draft.data.buildingAddress=b.address;}}
    const steps=kind==='owner'?['Chủ nhà','Hợp đồng đầu vào','Tòa và phòng','Rà soát']:['Khách hàng','Tòa và phòng','Hợp đồng và biểu phí','Rà soát'];
    const persist=async()=>{await B.saveDraft(draft);TH.router.replaceQuery({...q,draft:draft.id,mode});};
    const change=(key,value)=>{const old=draft.data[key];if(String(old??'')===String(value??''))return;draft.history.push({at:F.nowISO(),by:S.session?.userId,key,before:old,value,source:draft.sources[key]});draft.data[key]=value;draft.sources[key]={file:'Nhập tay',raw:value,at:F.nowISO()};delete draft.existingChoices?.[key];draft.sourceErrors=draft.sourceErrors.filter(e=>e.key!==key);draft.reviewed=false;};
    const input=(f)=>{
      const [key,label,type,required]=f,v=draft.data[key]??'',id='intake-'+key;
      let control;
      if(type==='area'||type==='manager'||type==='status'||type==='partyType'){
        const rows=type==='area'?S.all('areas').map(a=>[a.id,a.name||a.id]):type==='manager'?S.all('employees').map(a=>[a.id,a.name]):type==='partyType'?[['individual','Cá nhân'],['legal','Pháp nhân']]:[['pending','Hợp đồng mới: chờ nhận, giữ phòng'],['active','Dữ liệu vận hành: đang ở']];
        control=`<select id="${id}" data-field="${key}">${options([['','Chọn…'],...rows],v)}</select>`;
      }else if(type==='textarea')control=`<textarea id="${id}" rows="3" data-field="${key}">${esc(v)}</textarea>`;
      else control=`<input id="${id}" type="${type}" data-field="${key}" value="${esc(v)}" ${type==='number'?'step="any"':''}>`;
      return `<div class="intake-field"><label for="${id}">${esc(label)}${required?' *':''}</label>${control}<small class="muted">${esc(source(draft.sources[key]))}</small></div>`;
    };
    const roomEditor=()=>`<p>Chỉ thêm phòng được ghi rõ trong nguồn. Một dòng: <b>số phòng | tầng | loại khai thác | giá niêm yết | giá quản lý | giá thuê</b>.</p><p class="muted">Loại khai thác: timehouse, owner_live, owner_tenant, meter_common.</p><label for="intake-rooms">Danh sách phòng (${draft.rooms.length})</label><textarea id="intake-rooms" rows="10">${esc(draft.rooms.map(r=>[r.number,r.floor,r.exploitation,r.listPrice??'',r.mgmtPrice??'',r.price??''].join(' | ')).join('\n'))}</textarea>`;
    const fees=()=>`<h3>Biểu phí hiệu lực từ ngày tính tiền phòng</h3><div class="intake-fees">${I.fees.map(([key,label,method])=>`<label>${esc(label)}<input aria-label="Đơn giá ${esc(label)}" type="number" min="0" data-fee="${key}" value="${draft.items[key]?.unit??''}" placeholder="Không thu"><select aria-label="Cách tính ${esc(label)}" data-method="${key}">${options([['meter','Theo chỉ số (kWh/m³)'],['person','Theo người'],['room','Theo phòng'],['vehicle','Theo xe'],['fixed','Cố định']],draft.items[key]?.method||method)}</select><small>${esc(source(draft.sources['fee:'+key]))}</small></label>`).join('')}</div>`;
    const schedule=()=>{const d=draft.data;if(!(d.rent>0&&d.startDate&&d.endDate&&d.payMonths>0))return '<p>Hoàn thiện thời hạn, giá và kỳ trả để xem lịch dự kiến.</p>';let from=d.startDate.slice(0,8)+'01',cur=F.today().slice(0,8)+'01';if(from<cur)from=cur;const until=F.addMonths(cur,12),rows=[];for(let month=from;month<until&&month<=d.endDate&&rows.length<12;month=F.addMonths(month,+d.payMonths)){const months=Array.from({length:+d.payMonths},(_,i)=>F.addMonths(month,i)).filter(x=>x<=d.endDate).length,dueMonth=F.addMonths(month,+d.dueMonthOffset||0),last=+TH.calc.dates.addDays(F.addMonths(dueMonth,1),-1).slice(-2),due=dueMonth.slice(0,8)+String(Math.min(+d.dueDay||1,last)).padStart(2,'0');rows.push(`<tr><td>${F.date(month)}</td><td>${months} tháng</td><td>${F.date(due)}</td><td>${F.vnd(months*d.rent)}</td></tr>`);}return rows.length?`<table class="tbl compact"><thead><tr><th>Từ kỳ</th><th>Thời lượng</th><th>Hạn trả</th><th>Số phải trả</th></tr></thead><tbody>${rows.join('')}</tbody></table><p class="muted">Hiển thị lịch trong 12 tháng tới; các kỳ tiếp theo được tạo khi vận hành gia hạn lịch.</p>`:'<p>Hợp đồng bắt đầu ngoài cửa sổ lịch 12 tháng tới.</p>';};
    const planned=review=>kind==='owner'?`<div class="intake-summary"><p>Chủ nhà: <b>${review.links.party?'Liên kết hồ sơ hiện có':'Tạo mới'}</b> · Hợp đồng: <b>${review.links.contract?'Liên kết':'Tạo mới'}</b> · Tòa: <b>${review.links.building?'Liên kết':'Tạo mới'}</b> · Phòng mới: <b>${draft.rooms.filter(r=>!S.one('rooms',x=>I.code(x.code)===I.code(r.code))).length}</b> / ${draft.rooms.length}</p><h3>Lịch trả chủ nhà dự kiến</h3>${schedule()}</div>`:`<div class="intake-summary"><p>Khách hàng: <b>${review.links.party?'Liên kết hồ sơ hiện có':'Tạo mới'}</b> · Phòng: <b>${review.links.room?esc(review.links.room.code):'Chưa khớp'}</b> · Lượt thuê: <b>${review.links.stay?'Liên kết':'Tạo mới'}</b> · Trạng thái: <b>${esc(draft.data.status||'Chưa chọn')}</b></p><p>Giá thuê ${F.vnd(draft.data.rent||0)}/tháng · cọc hợp đồng ${F.vnd(draft.data.deposit||0)} · ${Object.keys(draft.items).length} loại phí từ ${F.date(draft.data.startDate)}.</p><p>Cọc cũ đang giữ: ${F.vnd(draft.data.openingDeposit||0)}; nợ đầu kỳ: ${F.vnd(draft.data.openingDebt||0)}; đề xuất thu chờ chứng từ: ${F.vnd(draft.data.declaredPaid||0)}.</p></div>`;
    const render=()=>{
      const review=I.validate(draft),section=kind==='owner'?step:step===1?2:step===2?1:step;
      root.innerHTML=U.pageHead({title:kind==='owner'?'Thêm chủ nhà':'Thêm khách hàng',back:kind==='owner'?'#/owners':'#/tenants',sub:'Đọc file thật, lưu trên trình duyệt này. Chỉ ghi hồ sơ chính thức sau khi rà soát.'})+`<div class="intake-workspace">
        <div class="card intake-panel"><div class="intake-toolbar" role="group" aria-label="Cách nhập">${[['contract','Trích xuất từ hợp đồng'],['manual','Nhập thông tin thủ công'],['excel','Import Excel/CSV']].map(([key,label])=>button(label,'mode',`data-mode="${key}" aria-pressed="${mode===key}"`)).join('')}${button('Mẫu Excel','template')}${button('Lưu nháp','save')}${button('Mở bản nháp','drafts')}</div>
        <p class="muted">Có thể kết hợp hợp đồng, Excel bổ sung và nhập tay trong cùng bản nháp. File Word chỉ dùng đối chiếu; hãy xuất PDF để trích xuất.</p>
        ${mode!=='manual'?`<label for="intake-file">${mode==='contract'?'Hợp đồng PDF/JPG/PNG':'Workbook XLSX hoặc CSV'}</label><input id="intake-file" type="file" accept="${mode==='contract'?'.pdf,.jpg,.jpeg,.png':'.xlsx,.csv'}" ${busy?'disabled':''}>`:''}
        <div id="intake-progress" role="status" aria-live="polite">${esc(message)}</div>${busy?button('Hủy đọc file','cancel'):''}
        ${sheets.length?`<label for="intake-sheet">Chọn sheet / phạm vi nhập</label><select id="intake-sheet">${options(sheets.map((s,i)=>[i,s.name]),0)}</select><div id="intake-mapping"></div>${button('Đọc các dòng trong sheet','sheet')}</div>`:'</div>'}
        ${queue.length?`<div class="card intake-panel"><h3>${queue.length} bộ hồ sơ từ sheet</h3><p>Chọn từng bộ để bổ sung hoặc gộp vào hồ sơ đang làm. Chỉ bộ hợp lệ và được chọn mới được ghi.</p>${queue.map((d,i)=>`<p><input type="checkbox" data-select="${i}" aria-label="Chọn dòng ${d.sourceRow}" ${d.selected?'checked':''}> ${esc(d.data.roomCode||d.data.buildingCode||'Chưa có mã')} · ${esc(d.data.name||'Thiếu tên')} · ${esc(I.validate(d).status)} ${button('Mở sửa','queue',`data-index="${i}"`)} ${button('Gộp nguồn','merge',`data-index="${i}"`)}</p>`).join('')}${button('Xác nhận các bộ đã chọn, hợp lệ','batch')}</div>`:''}
        <nav class="intake-toolbar" aria-label="Các bước">${steps.map((s,i)=>button(`${i+1}. ${s}`,'step',`data-step="${i}" aria-current="${step===i?'step':'false'}"`)).join('')}</nav>
        <section class="card intake-panel"><h2>${steps[step]}</h2>
        ${step<3?`<div class="form-grid">${I.fields[kind].filter(f=>f[4]===section).map(input).join('')}</div>${step===0?`<label for="intake-existing-party">Liên kết hồ sơ ${kind==='owner'?'chủ nhà':'khách hàng'} đã có (chọn khi đã đối chiếu giấy tờ)</label><select id="intake-existing-party">${options([['','Tự đối chiếu theo giấy tờ / SĐT'],...S.all(kind==='owner'?'owners':'customers').map(x=>[x.id,x.name+' · '+(x.phone||x.idNo||x.id)])],draft.selectedPartyId||'')}</select>`:''}${kind==='owner'&&step===2?roomEditor():''}${kind==='tenant'&&step===2?fees():''}${kind==='tenant'&&step===1?`<label for="intake-existing-room">Đối chiếu phòng hiện có (chọn để áp dụng mã và địa chỉ)</label><select id="intake-existing-room">${options([['','Chọn phòng'],...S.all('rooms').filter(r=>TH.auth.inScope(r.buildingId)&&r.exploitation!=='meter_common').map(r=>[r.id,r.code+' · '+TH.q.building(r.buildingId)?.address])],'')}</select>`:''}`:
          `<p><strong>${esc(review.status)}</strong> · ${esc(draft.data.name||'Thiếu tên')} → ${esc(draft.data.buildingCode||'Thiếu tòa')} ${esc(draft.data.roomCode||'')} · ${draft.rooms.length} phòng trong nguồn</p>
          ${planned(review)}
          <div role="alert">${review.errors.map(e=>`<p class="red">${esc(e)}</p>`).join('')}</div>${review.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}
          ${draft.conflicts.map((c,i)=>`<div class="intake-conflict"><b>${esc(c.key)}</b><p>Đang dùng: ${esc(JSON.stringify(c.before))}</p><p>Nguồn bổ sung: ${esc(JSON.stringify(c.next))} · ${esc(source(c.source))}</p>${button('Giữ giá trị hiện tại','resolve',`data-index="${i}" data-choice="old"`)} ${button('Áp dụng nguồn bổ sung','resolve',`data-index="${i}" data-choice="new"`)}</div>`).join('')}
          ${review.existingConflicts.map(c=>`<div class="intake-conflict"><b>${esc(c.label)}</b><p>Hồ sơ hiện có: ${esc(c.before)}</p><p>Giá trị nguồn: ${esc(c.next)} · ${esc(source(c.source))}</p>${draft.existingChoices?.[c.key]==='source'?'<p>Đã chọn áp dụng nguồn mới.</p>':''}${button('Giữ hồ sơ hiện có','existing',`data-key="${esc(c.key)}" data-choice="old"`)} ${button('Áp dụng giá trị từ nguồn','existing',`data-key="${esc(c.key)}" data-choice="source"`)}</div>`).join('')}
          ${draft.sourceErrors.map((e,i)=>`<div class="intake-conflict"><p>${esc(e.message)}</p>${button('Đã đối chiếu ô này, không dùng giá trị lỗi','dismiss',`data-index="${i}"`)}</div>`).join('')}
          <details><summary>Toàn bộ trường và nguồn trích xuất</summary>${I.fields[kind].map(f=>`<p><b>${esc(f[1])}:</b> ${esc(draft.data[f[0]]??'—')}<br><small>${esc(source(draft.sources[f[0]]))}</small></p>`).join('')}</details>
          ${draft.rooms.length?`<details><summary>${draft.rooms.length} phòng và nguồn từng trường</summary>${draft.rooms.map(r=>`<p><b>${esc(r.code)}</b> · ${esc(r.exploitation)} · ${F.vnd(r.listPrice??0)} / ${F.vnd(r.mgmtPrice??0)} / ${F.vnd(r.price??0)}<br><small>${esc(source(r.source))} · ${esc(JSON.stringify(r.sources||{}))}</small></p>`).join('')}</details>`:''}
          <label><input type="checkbox" id="intake-confirm" ${draft.reviewed?'checked':''}> Tôi đã đối chiếu nguồn, trạng thái, phí, các số dư và đồng ý liên kết các hồ sơ hiện có.</label>
          ${button('Xác nhận tạo hồ sơ','commit',review.errors.length?'disabled':'')}`}
        <div class="intake-toolbar mt16">${step?button('Quay lại','prev'):''}${step<3?button('Tiếp tục','next'):''}</div></section>
        <div class="card intake-panel"><h3>File gốc và lịch sử</h3>${draft.files.map(f=>`<p>${esc(f.name)} ${button('Tải file gốc','file',`data-file="${esc(f.id)}"`)}</p>`).join('')||'<p>Chưa đính kèm file.</p>'}<details><summary>${draft.history?.length||0} lần chỉnh sửa / xác nhận</summary><pre>${esc(JSON.stringify(draft.history||[],null,2))}</pre></details></div></div>`;
      root.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>change(el.dataset.field,el.type==='number'?(el.value===''?'':Number(el.value)):el.value));
      root.querySelectorAll('[data-fee], [data-method]').forEach(el=>el.onchange=()=>{const old=JSON.stringify(draft.items);for(const [key,,method] of I.fees){const value=root.querySelector(`[data-fee="${key}"]`).value;if(value==='')delete draft.items[key];else {draft.items[key]={unit:Number(value),method:root.querySelector(`[data-method="${key}"]`).value||method};draft.sources['fee:'+key]={file:'Nhập tay',raw:JSON.stringify(draft.items[key]),at:F.nowISO()};}}if(old!==JSON.stringify(draft.items))draft.history.push({at:F.nowISO(),by:S.session?.userId,action:'edit-fees',before:JSON.parse(old),value:JSON.parse(JSON.stringify(draft.items))});draft.reviewed=false;});
      const rooms=root.querySelector('#intake-rooms');if(rooms)rooms.onchange=()=>{const old=JSON.parse(JSON.stringify(draft.rooms));draft.rooms=rooms.value.split('\n').filter(x=>x.trim()).map(line=>{const [n,f,e,l,m,r]=line.split('|').map(x=>x.trim()),code=I.roomCode(n,draft.data.buildingCode),before=old.find(x=>x.code===code),value={code,number:n.toUpperCase(),floor:+f,exploitation:e||'timehouse',listPrice:l===''?undefined:+l,mgmtPrice:m===''?undefined:+m,price:r===''?undefined:+r},sources={...(before?.sources||{})};for(const key of ['number','floor','exploitation','listPrice','mgmtPrice','price'])if(String(before?.[key]??'')!==String(value[key]??''))sources[key]={file:'Nhập tay',raw:value[key],at:F.nowISO()};return {...value,source:before?.source,sources};});draft.history.push({at:F.nowISO(),by:S.session?.userId,action:'edit-rooms',before:old,value:draft.rooms});draft.reviewed=false;};
      const room=root.querySelector('#intake-existing-room');if(room)room.onchange=()=>{const r=TH.q.room(room.value);if(!r)return;const b=TH.q.building(r.buildingId);change('roomCode',r.code);change('buildingCode',b.code);change('buildingAddress',b.address);render();};
      const party=root.querySelector('#intake-existing-party');if(party)party.onchange=()=>{draft.selectedPartyId=party.value||null;draft.existingChoices={};draft.history.push({at:F.nowISO(),by:S.session?.userId,action:'select-existing-party',partyId:draft.selectedPartyId});draft.reviewed=false;render();};
      const confirm=root.querySelector('#intake-confirm');if(confirm)confirm.onchange=()=>{draft.reviewed=confirm.checked;};
      root.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>{queue[+el.dataset.select].selected=el.checked;});
      root.querySelectorAll('[data-intake]').forEach(el=>el.onclick=async()=>{try{await action(el);}catch(e){message=e.message+(e.fields?' · '+Object.values(e.fields).join('; '):'');render();}});
      const upload=root.querySelector('#intake-file');if(upload)upload.onchange=()=>read(upload.files[0]);
      const sh=root.querySelector('#intake-sheet');if(sh){sh.onchange=mapping;mapping();}
    };
    function mapping(){
      const s=sheets[+root.querySelector('#intake-sheet').value],profile=I.sheetProfile(s.name),box=root.querySelector('#intake-mapping');
      if(profile!=='template'){box.innerHTML=`<p>${profile==='reference'?'Sheet này chỉ đối chiếu, không tạo hồ sơ.':'Ánh xạ nguồn: '+esc(profile)+'. Bỏ dòng tổng; giữ ô/công thức; thiếu tên, ngày hoặc địa chỉ phải bổ sung. HOÀN CỌC chỉ đối chiếu.'}</p>`;return;}
      const map=I.mapping(s.rows[0]||[]),keys=[...new Set([...I.fields[kind].map(f=>f[0]),'number','floor','exploitation','listPrice','mgmtPrice','price',...I.fees.flatMap(([k])=>[k+'Unit',k+'Method'])])];
      box.innerHTML=`<details open><summary>Ánh xạ cột — dòng đầu là tiêu đề</summary><div class="form-grid">${(s.rows[0]||[]).map((h,i)=>`<label>${esc(h||'Cột '+(i+1))}<select data-map="${i}">${options([['','Không nhập'],...keys.map(k=>[k,I.fields[kind].find(f=>f[0]===k)?.[1]||k])],Object.keys(map).find(k=>map[k]===i)||'')}</select></label>`).join('')}</div></details>`;
    }
    async function read(file){if(!file)return;busy=true;message='Đang lưu file gốc…';controller=new AbortController();render();try{
      const f=await B.addFile(file,kind);if(!draft.files.some(x=>x.id===f.id))draft.files.push(f);selectedFile=f;
      if(/\.(xlsx|csv)$/i.test(file.name)){sheets=await B.workbook(file);message='Chọn sheet, kiểm tra ánh xạ rồi đọc dòng.';}
      else{const pages=await B.contract(file,{signal:controller.signal,progress:(m)=>{message=m;const el=root.querySelector('#intake-progress');if(el)el.textContent=m;}});const data=I.extract(kind,pages,file.name);draft.extractedPages=[...(draft.extractedPages||[]),...pages.map(p=>({...p,file:file.name}))];I.merge(draft,data);message='Đã đọc '+pages.length+' trang. Các trường nhận dạng phải được đối chiếu; phần chưa đọc được để trống.';}
      await persist();
    }catch(e){message=e.name==='AbortError'?'Đã hủy. Có thể chọn lại file để thử lại.':e.message;}finally{busy=false;render();}}
    async function action(el){
      const act=el.dataset.intake;
      if(act==='mode'){mode=el.dataset.mode;render();}
      if(act==='step'){step=+el.dataset.step;render();}
      if(act==='next'||act==='prev'){await persist();step+=act==='next'?1:-1;render();}
      if(act==='save'){await persist();message='Đã lưu bản nháp trong trình duyệt.';render();}
      if(act==='cancel')controller?.abort();
      if(act==='template')await B.template(kind);
      if(act==='file')await B.download(el.dataset.file);
      if(act==='drafts'){const drafts=await B.drafts(kind);message='';root.querySelector('#intake-progress').innerHTML=drafts.map(d=>`<p><a href="#/${kind==='owner'?'owners/new':'tenants/intake'}?draft=${encodeURIComponent(d.id)}">${esc(d.data.name||d.data.buildingCode||'Chưa có tên')} · ${esc(d.updatedAt)}</a></p>`).join('')||'Chưa có bản nháp';}
      if(act==='sheet'){
        const s=sheets[+root.querySelector('#intake-sheet').value];let map=null;
        if(I.sheetProfile(s.name)==='template'){map={};root.querySelectorAll('[data-map]').forEach(el=>{if(el.value){if(map[el.value]!=null)throw new Error('Hai cột cùng ánh xạ '+el.value);map[el.value]=+el.dataset.map;}});}
        queue=I.fromRows(kind,s.rows,{file:selectedFile.name,sheet:s.name,cells:s.cells,mapping:map,asOf:F.today()});
        for(const d of queue){d.id=F.uid('intake');d.files=[selectedFile];d.history=[];await B.saveDraft(d);}message=queue.length+' bộ hồ sơ; chọn mở sửa hoặc gộp vào hồ sơ hiện tại.';render();
      }
      if(act==='queue'){await persist();draft=queue[+el.dataset.index];step=0;await persist();render();}
      if(act==='merge'){const other=queue[+el.dataset.index];if(other===draft)throw new Error('Đang mở chính hồ sơ này');I.merge(draft,other);for(const f of other.files)if(!draft.files.some(x=>x.id===f.id))draft.files.push(f);await persist();render();}
      if(act==='resolve'){const c=draft.conflicts[+el.dataset.index];if(el.dataset.choice==='new'){if(c.key.startsWith('fee:')){draft.items[c.key.slice(4)]=c.next;draft.sources[c.key]=c.source;}else if(c.key.startsWith('room:')){const [,code,key]=c.key.split(':'),r=draft.rooms.find(r=>r.code===code);r[key]=c.next;r.sources||={};r.sources[key]=c.source;}else{draft.data[c.key]=c.next;draft.sources[c.key]=c.source;}}draft.history.push({at:F.nowISO(),action:'resolve',...c,choice:el.dataset.choice});draft.conflicts.splice(+el.dataset.index,1);render();}
      if(act==='existing'){const c=I.validate(draft).existingConflicts.find(x=>x.key===el.dataset.key);if(!c)throw new Error('Xung đột đã được xử lý');draft.existingChoices||={};if(el.dataset.choice==='old'){draft.data[c.key]=c.before;draft.sources[c.key]={file:'Hồ sơ hiện có',raw:c.before};delete draft.existingChoices[c.key];}else draft.existingChoices[c.key]='source';draft.history.push({at:F.nowISO(),by:S.session?.userId,action:'choose-existing-conflict',key:c.key,choice:el.dataset.choice,before:c.before,next:c.next,source:c.source});draft.reviewed=false;render();}
      if(act==='dismiss'){const e=draft.sourceErrors.splice(+el.dataset.index,1)[0];draft.history.push({at:F.nowISO(),by:S.session?.userId,action:'dismiss-source-error',error:e});draft.reviewed=false;render();}
      if(act==='commit'){await persist();const result=I.commit(draft);await B.saveDraft(draft).catch(()=>{});TH.go(result.href);}
      if(act==='batch'){const selected=queue.filter(d=>d.selected);if(!selected.length)throw new Error('Chọn ít nhất một bộ hồ sơ');let count=0,failed=0;for(const d of selected){if(I.validate(d).errors.length){failed++;continue;}try{d.reviewed=true;await B.saveDraft(d);I.commit(d);count++;}catch(e){d.sourceErrors.push({key:'commit',message:e.message});await B.saveDraft(d);failed++;}}message=`Đã nhập ${count} bộ hợp lệ; ${failed} bộ lỗi giữ trong bản nháp.`;render();}
    }
    render();
    if(q.read){const fileId=q.read;delete q.read;try{const f=await B.file(fileId);await read(f.blob);}catch(e){message=e.message;render();}}
  }
  TH.router.handle('/owners/new',(r,p,q)=>workspace(r,p,q,'owner'));
  TH.router.handle('/tenants/intake',(r,p,q)=>workspace(r,p,q,'tenant'));
})(window.TH);
