/* Phase 3 – Đầu tư: Cổ đông, vốn góp & phân phối (#/investment/shareholders – PNG 09/01, 3 tab), Dự án (#/investment/projects – tự thiết kế), Hiệu quả đầu tư (#/investment/roi – tự thiết kế) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, C = TH.chart, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const liveB = () => St.where('buildings', b => !b.stub);
  const projOpts = () => St.all('projects').map(p => [p.id, p.name]);
  const canM = () => TH.auth.can('shareholders.manage');
  const isCodong = () => TH.auth.role() === 'codong';

  /* ---- Forms ---- */
  Fm.shareholder = (s = {}) => {
    const cms = s.id ? Q.commitmentsOf(s.id) : []; const projects = St.all('projects');
    const rowsHtml = projects.map(p => { const c = cms.find(x => x.projectId === p.id) || {}; const others = F.sum(St.where('capitalCommitments', x => x.projectId === p.id && x.shareholderId !== s.id), x => x.ratio); return `<tr><td>${esc(p.name)}<div class="xs muted">Vốn ${F.vnd(p.capital)} · còn ${Math.max(0, Math.round((100 - others) * 100) / 100)}% chưa cam kết</div></td><td><input class="inp sm tr" type="number" step="0.01" min="0" max="100" name="r_${p.id}" value="${c.ratio || ''}" placeholder="0" style="width:90px"></td><td>${U.money({ name: 'c_' + p.id, value: c.committed || '' })}</td><td><input class="inp sm" type="date" name="d_${p.id}" value="${c.effectiveDate || F.today()}"></td></tr>`; }).join('');
    const m = U.drawer({ title: s.id ? 'Sửa cổ đông ' + s.code : 'Thêm cổ đông', sub: 'Cổ đông có thể góp vào nhiều tòa; tỷ lệ vốn nhập tay theo từng dự án (BR-15, FR-SHR-02)', wide: true, body: `<div class="form-grid">${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name', value: s.name || '' }) })}${U.field({ label: 'CCCD', input: U.input({ name: 'idNumber', value: s.idNumber || '' }) })}${U.field({ label: 'Email', input: U.input({ name: 'email', value: s.email || '', placeholder: 'ten@gmail.com' }) })}${U.field({ label: 'Số điện thoại', input: U.input({ name: 'phone', value: s.phone || '' }) })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: s.note || '', rows: 2 }), cls: 'span2' })}</div><h4 class="mt16 mb8">Cam kết vốn theo dự án</h4><div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Dự án</th><th>Tỷ lệ % (nhập tay)</th><th>Vốn cam kết</th><th>Hiệu lực</th></tr></thead><tbody>${rowsHtml}</tbody></table></div>${U.note('info', '', 'Tỷ lệ được lưu đúng như nhập – không tự tính lại từ tiền (AC-FR-SHR-02-1). Để trống vốn cam kết → tự tính = tỷ lệ × vốn điều lệ. Tổng tỷ lệ mỗi dự án không vượt 100%.')}`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: s.id ? 'Lưu' : 'Thêm cổ đông', icon: 'user-plus', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'sh-save' } }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = s.id; d.commitments = projects.filter(p => Number(d['r_' + p.id]) > 0).map(p => ({ projectId: p.id, ratio: Number(d['r_' + p.id]), committed: d['c_' + p.id], effectiveDate: d['d_' + p.id] })); if (!d.commitments.length && !s.id) throw new Error('Nhập tỷ lệ vốn cho ít nhất một dự án'); const r = X.saveShareholder(d); m.close(); ok((s.id ? 'Đã cập nhật ' : 'Đã thêm cổ đông ') + r.code, r.name); } });
  };
  const roundModal = (projectId) => {
    const preview = (pid, total) => { const cms = St.where('capitalCommitments', c => c.projectId === pid); return cms.length ? `<table class="tbl compact"><thead><tr><th>Cổ đông</th><th class="num">Tỷ lệ</th><th class="num">Nghĩa vụ</th></tr></thead><tbody>${cms.map(c => `<tr><td>${esc(Q.shareholder(c.shareholderId).name)}</td><td class="num">${c.ratio}%</td><td class="num">${F.vnd(Math.round(total * c.ratio / 100 / 1000) * 1000)}</td></tr>`).join('')}</tbody></table>` : '<div class="muted small">Dự án chưa có cổ đông cam kết</div>'; };
    const m = U.modal({ title: 'Tạo khoản góp vốn', sub: 'Sinh nghĩa vụ đóng góp cho từng cổ đông theo tỷ lệ vốn (AC-FR-SHR-01-2)', size: 'lg', body: `<div class="form-grid">${U.field({ label: 'Dự án', req: true, input: U.select({ name: 'projectId', value: projectId || (St.all('projects')[0] || {}).id, options: projOpts(), attrs: { id: 'rd-p' } }) })}${U.field({ label: 'Loại', input: U.select({ name: 'kind', value: 'capital', options: Object.entries(Q.L.contribKind) }), help: 'Định kỳ = gắn kỳ trả chủ nhà của tòa (BR-15)' })}${U.field({ label: 'Tên đợt', input: U.input({ name: 'round', placeholder: 'Đợt góp vốn lần 2' }) })}${U.field({ label: 'Hạn góp', req: true, input: U.date({ name: 'dueDate', value: F.addDays(F.today(), 14) }) })}${U.field({ label: 'Tổng đợt (VND)', req: true, input: U.money({ name: 'total', value: '', attrs: { id: 'rd-t' } }) })}${U.field({ label: 'Ghi chú', input: U.input({ name: 'note' }) })}</div><div class="mt12" id="rd-prev">${preview(projectId || (St.all('projects')[0] || {}).id, 0)}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Tạo đợt góp vốn', icon: 'hand-coins', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'round-save' } }) });
    const upd = () => { const d = m.data(); m.el.querySelector('#rd-prev').innerHTML = preview(d.projectId, F.num(d.total)); }; m.el.querySelector('#rd-p').addEventListener('change', upd); m.el.querySelector('#rd-t').addEventListener('input', upd);
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const out = X.createContributionRound({ projectId: d.projectId, round: d.round, dueDate: d.dueDate, total: d.total, kind: d.kind, note: d.note }); m.close(); ok('Đã tạo ' + out.length + ' nghĩa vụ góp vốn', Q.project(d.projectId).name); TH.router.replaceQuery({ tab: 'contributions' }); TH.router.refresh(); } });
  };
  const recordModal = (c) => { const rem = c.amount - (c.paidAmount || 0); const m = U.modal({ title: 'Ghi nhận góp vốn', sub: esc(Q.shareholder(c.shareholderId).name) + ' · ' + esc(Q.project(c.projectId).name) + ' · ' + esc(String(c.round)), size: 'sm', body: `${U.kv([['Nghĩa vụ', F.vnd(c.amount)], ['Đã góp', F.vnd(c.paidAmount || 0)], ['Còn phải góp', '<b class="red">' + F.vnd(rem) + '</b>'], ['Hạn', F.date(c.dueDate)]], 'one')}<div class="form-grid mt12">${U.field({ label: 'Số tiền thực góp', req: true, input: U.money({ name: 'amount', value: rem }) })}${U.field({ label: 'Ngày', input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Chứng từ / UNC', input: U.input({ name: 'ref', placeholder: 'UNC-1234' }), cls: 'span2' })}</div>${U.note('info', '', 'Không coi vốn cam kết là vốn thực góp – chỉ ghi khi có tiền/chứng từ (FR-SHR-01).')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Ghi nhận', icon: 'check', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'contrib-save' } }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const r = X.recordContribution(c.id, d); m.close(); ok(r.duplicate ? 'Đã ghi nhận trước đó' : 'Đã ghi nhận góp vốn', F.vnd(F.num(d.amount)) + ' – ' + Q.label('contribution', Q.contributionStatus(St.get('contributions', c.id)))); } }); };
  const distModal = () => {
    const suggest = (() => { try { const p = St.state.meta.period; const op = Q.operatingResult ? Q.operatingResult(p) : null; return op && op.profit > 0 ? op.profit : 0; } catch (e) { return 0; } })();
    const preview = (pid, profit) => { const rows = Q.shareholderRows({ projectId: pid }).filter(r => r.ratio > 0); const lines = rows.map(r => ({ r, amt: Math.round(profit * r.ratio / 100) })); const sum = F.sum(lines, l => l.amt); return `<table class="tbl compact"><thead><tr><th>Cổ đông</th><th class="num">Tỷ lệ hiệu lực</th><th class="num">Phân phối</th></tr></thead><tbody>${lines.map(l => `<tr><td>${esc(l.r.s.name)}</td><td class="num">${l.r.ratio}%</td><td class="num">${F.vnd(l.amt)}</td></tr>`).join('')}<tr class="dist-total"><td>Tổng</td><td class="num">${Math.round(F.sum(rows, r => r.ratio) * 100) / 100}%</td><td class="num">${F.vnd(sum)}${profit && sum !== profit ? ` <span class="xs muted">(làm tròn ${profit - sum >= 0 ? '+' : ''}${F.vnd(profit - sum)})</span>` : ''}</td></tr></tbody></table>`; };
    const m = U.modal({ title: 'Tạo phân phối lợi nhuận', sub: 'Bảng phân phối theo tỷ lệ vốn hiệu lực; xử lý làm tròn; duyệt trước công bố (UC-08)', size: 'lg', body: `<div class="form-grid">${U.field({ label: 'Kỳ phân phối', req: true, input: U.input({ name: 'label', placeholder: 'Q4/2026', value: '' }) })}${U.field({ label: 'Dự án', input: U.select({ name: 'projectId', value: '', all: 'Tất cả dự án', options: projOpts(), attrs: { id: 'ds-p' } }) })}${U.field({ label: 'Lợi nhuận được phân phối (VND)', req: true, input: U.money({ name: 'profit', value: suggest || '', attrs: { id: 'ds-t' } }), help: suggest ? 'Gợi ý từ Kết quả vận hành kỳ ' + F.periodLabel(St.state.meta.period) + ' (Phase 2, tạm tính)' : 'Nhập số được duyệt từ báo cáo kỳ đã chốt' })}${U.field({ label: 'Ngày dự kiến', input: U.date({ name: 'date', value: F.addDays(F.today(), 30) }) })}</div><div class="mt12" id="ds-prev">${preview('', F.num(suggest))}</div>${U.note('warn', 'OI-17', 'Cơ sở lợi nhuận, góp/rút giữa kỳ, kỳ lỗ và làm tròn chưa được xác nhận – bảng này chỉ là dự thảo chờ duyệt; không đồng nghĩa đã chuyển tiền.')}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lập bảng phân phối', icon: 'chart-pie', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'dist-save' } }) });
    const upd = () => { const d = m.data(); m.el.querySelector('#ds-prev').innerHTML = preview(d.projectId, F.num(d.profit)); }; m.el.querySelector('#ds-p').addEventListener('change', upd); m.el.querySelector('#ds-t').addEventListener('input', upd);
    U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const r = X.createDistribution(d); m.close(); ok('Đã lập bảng phân phối ' + r.label, F.vnd(r.profit) + ' · ' + r.lines.length + ' cổ đông'); TH.router.replaceQuery({ tab: 'distributions' }); TH.router.refresh(); } });
  };
  const distDrawer = (d) => {
    const lines = Q.distributionLines(d); const canAppr = TH.auth.can('distributions.approve'), canMg = TH.auth.can('distributions.manage'); const shownProfit = isCodong() ? F.sum(lines, l => l.amount) : d.profit;
    const m = U.drawer({ title: 'Bảng phân phối ' + esc(d.label), sub: `${d.projectId ? esc(Q.project(d.projectId).name) : 'Tất cả dự án'} · ${Q.chip('distribution', d.status)} · ${F.vnd(shownProfit)}`, wide: true, body: `<div class="two-col"><div>${U.card({ title: 'Phần mỗi cổ đông', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Cổ đông</th><th class="num">Tỷ lệ hiệu lực</th><th class="num">Số tiền</th><th class="num">Làm tròn</th></tr></thead><tbody>${lines.map((l, i) => `<tr><td>${i + 1}</td><td>${U.avatarCell({ name: l.s.name, sub: l.s.email })}</td><td class="num">${l.ratio}%</td><td class="num"><b>${F.vnd(l.amount)}</b></td><td class="num muted">${l.rounding ? (l.rounding > 0 ? '+' : '') + F.vnd(l.rounding) : '-'}</td></tr>`).join('')}<tr class="dist-total"><td colspan="2">Tổng cộng</td><td class="num">${Math.round(F.sum(lines, l => l.ratio) * 100) / 100}%</td><td class="num">${F.vnd(F.sum(lines, l => l.amount))}</td><td class="num">${F.vnd(F.sum(lines, l => l.rounding))}</td></tr></tbody></table>` })}</div><aside class="side-stack">${U.card({ title: 'Thông tin', icon: 'info', body: U.kv([['Mã', esc(d.code)], ['Kỳ', esc(d.label)], [isCodong() ? 'Phần được phân phối' : 'Lợi nhuận được phân phối', F.vnd(shownProfit)], ['Ngày dự kiến', F.date(d.date)], ['Người duyệt', d.approvedBy ? esc(Q.userName(d.approvedBy)) + ' · ' + F.datetime(d.approvedAt) : '-'], ['Đã chi', d.paidAt ? F.datetime(d.paidAt) + (d.ref ? ' · ' + esc(d.ref) : '') : '-'], ['Ghi chú', esc(d.note || '')]], 'one') })}${U.note('info', '', 'Tổng phần phân phối + chênh làm tròn = tổng được duyệt (AC-FR-SHR-02-2). Bảng đã duyệt không đồng nghĩa tiền đã chuyển.')}</aside></div>`, footer: U.btn({ label: 'Đóng', act: 'c' }) + U.btn({ label: 'Xuất bảng', icon: 'download', cls: 'btn-outline', act: 'x' }) + (d.status === 'planned' && canMg ? U.btn({ label: 'Bắt đầu xử lý', icon: 'play', cls: 'btn-outline', act: 'proc' }) : '') + (['planned', 'processing'].includes(d.status) && canAppr ? U.btn({ label: 'Duyệt', icon: 'check', cls: 'btn-primary', act: 'approve', attrs: { 'data-guide': 'dist-approve' } }) : '') + (d.status === 'approved' && canMg ? U.btn({ label: 'Ghi nhận đã chi', icon: 'banknote', cls: 'btn-primary', act: 'pay', attrs: { 'data-guide': 'dist-pay' } }) : '') });
    U.bind(m.el, { c: () => m.close(), x: () => { X.exportDistribution(d.id); ok('Đã xuất bảng phân phối'); }, proc: () => { X.processDistribution(d.id); m.close(); ok('Đã chuyển sang Đang xử lý'); }, approve: () => { X.approveDistribution(d.id); m.close(); ok('Đã duyệt bảng phân phối ' + d.label); }, pay: async () => { const r = await U.confirm({ title: 'Ghi nhận đã chi ' + d.label + '?', text: 'Chỉ đánh dấu đã chuyển tiền cho cổ đông – không tạo chi phí vận hành.', body: U.field({ label: 'Tham chiếu', input: U.input({ name: 'ref', placeholder: 'UNC-…' }) }), ok: 'Ghi nhận' }); if (r) { X.payDistribution(d.id, { ref: r.ref }); m.close(); ok('Đã ghi nhận chi phân phối ' + d.label); } } });
  };
  const shView = (s) => {
    const row = Q.shareholderRow(s, '', Q.currentDistribution()); const cs = Q.contributions({ shareholderId: s.id }); const ds = St.all('distributions').filter(d => (d.lines || []).some(l => l.shareholderId === s.id));
    const m = U.drawer({ title: esc(s.name), sub: esc(s.code) + ' · ' + esc(s.email || '') + ' · ' + esc(s.phone || '') + ' · ' + Q.chip('shareholder', row.status), wide: true, body: `<div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tỷ lệ góp vốn', value: row.ratio + '%', cap: 'Trên tổng vốn điều lệ', icon: 'percent', tone: 'blue', mini: true })}${U.kpi({ label: 'Vốn cam kết', value: F.vnd(row.committed), cap: row.projects.length + ' dự án', icon: 'coins', tone: 'purple', mini: true })}${U.kpi({ label: 'Đã góp', value: F.vnd(row.paid), cap: 'Thực góp', icon: 'check-circle', tone: 'green', mini: true })}${U.kpi({ label: 'Còn thiếu', value: F.vnd(row.missing), cap: 'Đến hạn/sắp đến hạn', icon: 'alert-triangle', tone: 'red', mini: true, valueCls: row.missing ? 'red' : '' })}</div>${U.card({ title: 'Cam kết theo dự án', icon: 'folder', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Dự án</th><th class="num">Tỷ lệ (nhập tay)</th><th class="num">Cam kết</th><th>Hiệu lực</th></tr></thead><tbody>${Q.commitmentsOf(s.id).map(c => `<tr><td>${esc(Q.project(c.projectId).name)}</td><td class="num">${c.ratio}%</td><td class="num">${F.vnd(c.committed)}</td><td>${F.date(c.effectiveDate)}</td></tr>`).join('')}</tbody></table>` })}${U.card({ title: 'Lịch sử góp vốn', icon: 'history', cls: 'mt16', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Dự án</th><th>Đợt</th><th>Hạn</th><th class="num">Nghĩa vụ</th><th class="num">Đã góp</th><th>Trạng thái</th></tr></thead><tbody>${cs.map(c => `<tr><td>${esc(c.code)}</td><td>${esc(Q.project(c.projectId).name)}</td><td>${esc(String(c.round))}<div class="xs muted">${Q.L.contribKind[c.kind]}</div></td><td>${F.date(c.dueDate)}</td><td class="num">${F.vnd(c.amount)}</td><td class="num">${F.vnd(c.paidAmount || 0)}</td><td>${Q.chip('contribution', c.st)}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Chưa có</td></tr>'}</tbody></table>` })}${U.card({ title: 'Phân phối lợi nhuận', icon: 'chart-pie', cls: 'mt16', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Kỳ</th><th class="num">Tỷ lệ</th><th class="num">Số tiền</th><th>Trạng thái</th></tr></thead><tbody>${ds.map(d => { const l = d.lines.find(x => x.shareholderId === s.id); return `<tr><td>${esc(d.label)}</td><td class="num">${l.ratio}%</td><td class="num">${F.vnd(l.amount)}</td><td>${Q.chip('distribution', d.status)}</td></tr>`; }).join('') || '<tr><td colspan="4" class="muted tc">Chưa có</td></tr>'}</tbody></table>` })}`, footer: U.btn({ label: 'Đóng', act: 'c' }) + (canM() ? U.btn({ label: 'Sửa', icon: 'pencil', cls: 'btn-outline', act: 'e' }) : '') });
    U.bind(m.el, { c: () => m.close(), e: () => { m.close(); Fm.shareholder(s); } });
  };
  const shMenu = (el, s) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => shView(s) }, { label: 'Sửa / cam kết vốn', icon: 'pencil', disabled: !canM(), onClick: () => Fm.shareholder(s) }, { label: 'Ghi nhận góp vốn', icon: 'hand-coins', disabled: !TH.auth.can('contributions.record'), onClick: () => { const c = Q.contributions({ shareholderId: s.id }).find(x => x.st !== 'paid'); if (!c) return U.toast('info', 'Không có nghĩa vụ chưa góp', s.name); recordModal(c); } }, { label: 'Lịch sử', icon: 'history', onClick: () => shView(s) }]);
  const contribMenu = (el, c) => U.menu(el, [{ label: 'Ghi nhận góp vốn', icon: 'hand-coins', disabled: c.st === 'paid' || !TH.auth.can('contributions.record'), onClick: () => recordModal(c) }, { label: 'Nhắc Zalo', icon: 'send', phase: 2, disabled: c.st === 'paid' || !TH.auth.can('zalo.send'), onClick: () => { U.toast('ok', 'Đã tạo nhắc góp vốn (mô phỏng)', Q.shareholder(c.shareholderId).name + ' – ' + F.vnd(c.amount - (c.paidAmount || 0))); } }, { label: 'Xem chứng từ', icon: 'file-text', disabled: !c.ref, onClick: () => U.fakePdf('Chung tu gop von ' + c.code, ['Cổ đông: ' + Q.shareholder(c.shareholderId).name, 'Dự án: ' + Q.project(c.projectId).name, 'Số tiền: ' + F.vnd(c.paidAmount), 'Tham chiếu: ' + c.ref]) }, { label: 'Xem cổ đông', icon: 'user', onClick: () => shView(Q.shareholder(c.shareholderId)) }]);

  /* ================= #/investment/shareholders – PNG 09/01 ================= */
  TH.router.register('/investment/shareholders', (root, p, q) => {
    TH.router.crumb([{ label: 'Đầu tư' }, { label: 'Cổ đông & vốn góp' }]);
    const tab = q.tab || 'shareholders'; const f = { projectId: q.projectId || '', buildingId: q.buildingId || '', period: q.period || St.state.meta.period, s: q.s || '', status: q.status || '', kind: q.kind || '' };
    const my = isCodong() ? Q.myShareholder() : null; const st = Q.shareholderStats({ projectId: f.projectId }); const rows = Q.shareholderRows(f).filter(r => !my || r.s.id === my.id);
    const upC = Q.upcomingContributions(4), upD = Q.upcomingDistributions(4); const dist = st.dist;
    root.innerHTML = `${U.pageHead({ title: 'Cổ đông, vốn góp & phân phối', phase: 3, sub: 'Quản lý danh sách cổ đông, theo dõi vốn góp và phân phối lợi nhuận cho các dự án đầu tư.' + (my ? ' <span class="chip blue">Cổ đông – chỉ xem tòa đã góp (FR-SHR-03)</span>' : ''), acts: [U.btn({ label: 'Thêm cổ đông', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !canM(), attrs: { 'data-guide': 'sh-add' } }), U.btn({ label: 'Tạo khoản góp vốn', icon: 'database', cls: 'btn-outline', act: 'add-round', disabled: !TH.auth.can('contributions.record'), attrs: { 'data-guide': 'round-add' } }), U.btn({ label: 'Tạo phân phối', icon: 'send', cls: 'btn-outline', act: 'add-dist', disabled: !TH.auth.can('distributions.manage'), attrs: { 'data-guide': 'dist-add' } }), U.btn({ label: 'Hiệu quả theo tòa', icon: 'trending-up', cls: 'btn-ghost', act: 'roi' })] })}
    <div class="card mb16"><div class="card-b" style="padding-bottom:0">${U.tabs([{ key: 'shareholders', label: 'Cổ đông', icon: 'users', count: st.count }, { key: 'contributions', label: 'Đóng góp theo kỳ', icon: 'calendar' }, { key: 'distributions', label: 'Phân phối lợi nhuận', icon: 'bar-chart' }, { key: 'summary', label: 'Tài sản & cọc theo tòa', icon: 'building' }], tab, 'boxed')}</div>
    <div class="card-b">${U.filterbar([U.field({ label: 'Dự án', input: U.select({ name: 'projectId', value: f.projectId, all: 'Tất cả dự án', options: projOpts(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập tên cổ đông, email, SĐT…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), tab === 'contributions' ? U.field({ label: 'Loại', input: U.select({ name: 'kind', value: f.kind, all: 'Tất cả', options: Object.entries(Q.L.contribKind), attrs: { 'data-on': 'f' } }) }) : '', U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(tab === 'contributions' ? Q.L.contribution : tab === 'distributions' ? Q.L.distribution : Q.L.shareholder).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' })).replace('class="card filters"', 'class="filters"')}</div></div>
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng cổ đông', value: st.count, cap: 'Đang tham gia đầu tư', icon: 'users', tone: 'blue', delta: 14 })}${U.kpi({ label: 'Tổng vốn góp', value: F.vnd(st.committed), cap: F.pct(st.committed, st.capital) + '% vốn điều lệ · thực góp ' + F.short(st.paid), icon: 'database', tone: 'amber', delta: 12 })}${U.kpi({ label: 'Lợi nhuận kỳ này', value: F.vnd(st.profit), cap: st.profitLabel ? 'Kỳ ' + st.profitLabel + ' · ' + F.periodLabel(St.state.meta.period) : 'Chưa có kỳ phân phối', icon: 'bar-chart', tone: 'blue', delta: 18 })}${U.kpi({ label: 'Đã phân phối', value: F.vnd(st.distributed), cap: st.planPct + '% kế hoạch', icon: 'send', tone: 'purple', delta: 0, bar: st.planPct })}</div>
    ${U.relatedStrip({ id: 'shareholders-related', cls: 'mb16', items: [
      { key: 'contrib', title: 'Lịch đóng góp sắp tới', icon: 'calendar', summary: upC.length ? upC.length + ' đợt · ' + F.vnd(F.sum(upC, c => c.amount - (c.paidAmount || 0))) + ' VND' : 'Không có đợt sắp tới', meta: upC.length ? (upC[0].st === 'due' ? 'Đến hạn hôm nay: ' : upC[0].st === 'overdue' ? 'Quá hạn: ' : 'Gần nhất ' + F.date(upC[0].dueDate) + ': ') + esc(Q.project(upC[0].projectId).name) : '', actions: `<a class="link small" href="#/investment/shareholders?tab=contributions">Xem tất cả →</a>`, body: upC.map(c => { const days = Q.contributionDays(c); const tone = c.st === 'due' || c.st === 'overdue' ? 'red' : days <= 3 ? 'amber' : ''; return `<div class="up-row">${U.dateTile(c.dueDate, tone === 'red' ? '' : tone)}<div class="grow"><b>${esc(c.kind === 'periodic' ? 'Đóng góp định kỳ ' + c.round : String(c.round).startsWith('Đợt') ? c.round : 'Đợt góp vốn lần ' + c.round)} - ${esc(Q.project(c.projectId).name)}</b><div class="small muted">${I('user')} ${esc(Q.shareholder(c.shareholderId).name)}${c.kind === 'periodic' ? ' <span class="xs">(+' + (Q.contributions({ projectId: c.projectId, kind: 'periodic' }).filter(x => x.dueDate === c.dueDate).length - 1) + ' cổ đông)</span>' : ''}<br>${I('coins')} ${F.vnd(c.amount - (c.paidAmount || 0))} VND</div></div>${c.st === 'due' ? U.chip('Đến hạn', 'red') : c.st === 'overdue' ? U.chip('Quá hạn ' + Math.abs(days) + ' ngày', 'red') : U.chip('Còn ' + days + ' ngày', days <= 3 ? 'amber' : 'blue')}</div>`; }).join('') || '<div class="muted small">Không có đợt sắp tới</div>' },
      { key: 'dist', title: 'Lịch phân phối sắp tới', icon: 'chart-pie', summary: upD.length ? upD.length + ' kỳ · ' + F.vnd(F.sum(upD, d => d.profit)) + ' VND' : 'Không có kỳ sắp tới', meta: upD.length ? esc(upD[0].label) + ' ' + Q.chip('distribution', upD[0].status) : '', actions: `<a class="link small" href="#/investment/shareholders?tab=distributions">Xem tất cả →</a>`, body: upD.map(d => `<div class="up-row">${U.dateTile(d.date, d.status === 'processing' ? '' : 'amber')}<div class="grow"><b>Phân phối lợi nhuận ${esc(d.label)}</b><div class="small muted">${I('users')} ${d.projectId ? esc(Q.project(d.projectId).name) : 'Tất cả cổ đông'}<br>${I('coins')} ${d.status === 'planned' ? 'Dự kiến: ' : ''}${F.vnd(d.profit)} VND</div></div>${Q.chip('distribution', d.status)}</div>`).join('') || '<div class="muted small">Không có kỳ sắp tới</div>' }
    ] })}
    <div class="side-stack" id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    if (tab === 'summary') {
      const scope = Q.scope({ period: f.period, buildingId: f.buildingId, shareholderId: my ? my.id : '' }); const sr = Q.shareholderAssetSummary(scope);
      body.innerHTML = `${U.dimFilter(f, { dims: ['period', 'buildingId'], inline: 2 })}${U.card({ title: 'Tài sản & cọc theo tòa', icon: 'building', sub: 'Nguyên giá tài sản công ty, cọc đang giữ và phân phối theo kỳ', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Tòa nhà</th><th class="num">Nguyên giá tài sản</th><th class="num">Cọc đang giữ</th><th class="num">Phân phối kỳ</th></tr></thead><tbody>${sr.map(x => `<tr><td>${U.link('#/buildings/' + x.buildingId, esc(x.building.name))}</td><td class="num">${F.vnd(x.assetValue)}</td><td class="num">${F.vnd(x.deposits)}</td><td class="num">${F.vnd(x.distribution)}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Không có dữ liệu trong phạm vi</td></tr>'}</tbody></table>` })}`;
    }
    if (tab === 'shareholders') {
      body.innerHTML = `${U.card({ title: 'Danh sách cổ đông (' + rows.length + ')', icon: 'users', body: null, id: 'sht', attrs: 'data-guide="shareholders-table"' })}<div class="grid grid-2">${U.card({ title: 'Cơ cấu vốn góp theo cổ đông', icon: 'chart-pie', body: C.donutLegend(Q.capitalStructure(f.projectId), 150, F.short(st.committed).replace(' tỷ', 'B').replace(' ', ''), 'VND') })}${U.card({ title: 'Tình hình góp vốn', icon: 'check-circle', body: U.progressRows([{ label: 'Đã góp đủ', count: st.byStatus.paid + ' cổ đông', pct: F.pct(st.byStatus.paid, st.count), color: 'var(--green-500)' }, { label: 'Còn thiếu', count: st.byStatus.missing + ' cổ đông', pct: F.pct(st.byStatus.missing, st.count), color: 'var(--red-500)' }, { label: 'Chưa góp', count: st.byStatus.none + ' cổ đông', pct: F.pct(st.byStatus.none, st.count), color: 'var(--gray)' }]) })}</div>`;
      U.table(body.querySelector('#sht'), { rows, unit: 'cổ đông', selectable: !my, rowKey: r => r.s.id, footer: (rs) => `<tr class="dist-total"><td colspan="${my ? 2 : 3}">Tổng cộng</td><td class="num">${Math.round(F.sum(rs, r => r.ratio) * 100) / 100}%</td><td class="num">${F.vnd(F.sum(rs, r => r.paid))}</td><td class="num red">${F.vnd(F.sum(rs, r => r.missing))}</td><td class="num">${F.vnd(F.sum(rs, r => r.share))}</td><td>-</td><td></td></tr>`, cols: [{ key: 'i', label: '#', render: (r, i) => i + 1 }, { key: 'name', label: 'Cổ đông', sortable: true, sortVal: r => r.s.name, render: r => U.avatarCell({ name: r.s.name, sub: esc(r.s.email || ''), href: '#/investment/shareholders?s=' + encodeURIComponent(r.s.code) }) }, { key: 'ratio', label: 'Tỷ lệ góp vốn', num: true, sortable: true, render: r => r.ratio.toFixed(2) + '%' }, { key: 'paid', label: 'Số vốn đã góp', num: true, sortable: true, render: r => F.vnd(r.paid) }, { key: 'missing', label: 'Số vốn còn thiếu', num: true, sortable: true, render: r => `<span class="${r.missing ? 'red bold' : ''}">${F.vnd(r.missing)}</span>` }, { key: 'share', label: 'Phân phối kỳ này', num: true, sortable: true, render: r => F.vnd(r.share) }, { key: 'status', label: 'Trạng thái', sortable: true, render: r => Q.chip('shareholder', r.status) }, { key: 'actions', label: 'Thao tác', render: r => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': r.s.id } }), U.moreBtn(r.s.id)]), hideable: false }] });
    }
    if (tab === 'contributions') {
      const cs = Q.contributions(f).filter(c => !my || c.shareholderId === my.id); const cst = Q.contributionStats();
      body.innerHTML = `<div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Đến hạn / quá hạn', value: cst.due, cap: cst.overdue + ' quá hạn', icon: 'alert-triangle', tone: 'red', mini: true })}${U.kpi({ label: 'Đã góp kỳ này', value: F.vnd(cst.paidPeriod), cap: F.periodLabel(St.state.meta.period), icon: 'check-circle', tone: 'green', mini: true })}${U.kpi({ label: 'Còn phải góp', value: F.vnd(cst.missing), cap: 'Tất cả nghĩa vụ chưa hoàn tất', icon: 'coins', tone: 'amber', mini: true })}${U.kpi({ label: 'Kỳ trả chủ nhà', value: liveB().map(b => (b.payCycle || 3) + 'T').join('/'), cap: 'Chu kỳ theo tòa (BR-11) → sinh nghĩa vụ định kỳ (BR-15)', icon: 'calendar', tone: 'blue', mini: true })}</div>${U.card({ title: 'Nghĩa vụ đóng góp (' + cs.length + ')', icon: 'calendar', sub: 'Đợt góp vốn cam kết + đóng góp định kỳ theo kỳ trả chủ nhà của từng tòa (FR-SHR-01 AC-2)', body: null, id: 'ct', attrs: 'data-guide="contributions-table"' })}`;
      U.table(body.querySelector('#ct'), { rows: cs, unit: 'nghĩa vụ', sortKey: 'dueDate', cols: [{ key: 'code', label: 'Mã đợt', sortable: true, render: c => `<b>${esc(c.code)}</b><div class="xs muted">${Q.L.contribKind[c.kind]}</div>` }, { key: 'project', label: 'Dự án', sortable: true, sortVal: c => Q.project(c.projectId).name, render: c => esc(Q.project(c.projectId).name) }, { key: 'round', label: 'Đợt', render: c => esc(String(c.round)) }, { key: 'sh', label: 'Cổ đông', render: c => U.avatarCell({ name: Q.shareholder(c.shareholderId).name }) }, { key: 'dueDate', label: 'Hạn', sortable: true, render: c => F.date(c.dueDate) }, { key: 'amount', label: 'Số tiền', num: true, sortable: true, render: c => F.vnd(c.amount) }, { key: 'paid', label: 'Đã góp', num: true, render: c => F.vnd(c.paidAmount || 0) + (c.paidDate ? `<div class="xs muted">${F.date(c.paidDate)}</div>` : '') }, { key: 'rem', label: 'Còn thiếu', num: true, render: c => `<span class="${c.amount - (c.paidAmount || 0) > 0 && c.st !== 'scheduled' ? 'red bold' : ''}">${F.vnd(c.amount - (c.paidAmount || 0))}</span>` }, { key: 'st', label: 'Trạng thái', sortable: true, render: c => Q.chip('contribution', c.st) }, { key: 'actions', label: '', render: c => U.rowActions([c.st !== 'paid' && TH.auth.can('contributions.record') ? U.btn({ label: 'Ghi nhận', icon: 'hand-coins', size: 'btn-sm', cls: 'btn-outline', act: 'record', attrs: { 'data-id': c.id, 'data-guide': 'contrib-record' } }) : '', U.moreBtn(c.id)]), hideable: false }] });
    }
    if (tab === 'distributions') {
      const ds = St.all('distributions').filter(d => (!f.status || d.status === f.status) && (!f.projectId || !d.projectId || d.projectId === f.projectId)).sort((a, b) => F.cmp(b.date, a.date));
      body.innerHTML = U.card({ title: 'Kỳ phân phối lợi nhuận (' + ds.length + ')', icon: 'bar-chart', sub: 'Tỷ lệ = tỷ lệ vốn nhập tay tại thời điểm lập; không dùng tỷ lệ hiện tại hồi tố (FR-SHR-02)', body: null, id: 'dt', attrs: 'data-guide="distributions-table"' });
      U.table(body.querySelector('#dt'), { rows: ds, unit: 'kỳ', cols: [{ key: 'code', label: 'Mã', render: d => `<b>${esc(d.code)}</b>` }, { key: 'label', label: 'Kỳ', sortable: true, render: d => esc(d.label) }, { key: 'project', label: 'Dự án', render: d => d.projectId ? esc(Q.project(d.projectId).name) : 'Tất cả dự án' }, { key: 'date', label: 'Ngày', sortable: true, render: d => F.date(d.date) }, { key: 'profit', label: my ? 'Phần của tôi' : 'Lợi nhuận phân phối', num: true, sortable: true, render: d => F.vnd(my ? (((d.lines || []).find(l => l.shareholderId === my.id) || {}).amount || 0) : d.profit) }, { key: 'mine', label: my ? 'Tỷ lệ của tôi' : 'Số cổ đông', num: true, render: d => my ? ((((d.lines || []).find(l => l.shareholderId === my.id) || {}).ratio || 0) + '%') : (d.lines || []).length }, { key: 'status', label: 'Trạng thái', sortable: true, render: d => Q.chip('distribution', d.status) }, { key: 'actions', label: '', render: d => U.rowActions([U.btn({ label: 'Bảng phân phối', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'open-dist', attrs: { 'data-id': d.id, 'data-guide': 'dist-open' } })]), hideable: false }] });
    }
    U.onChange(root, { f: (el) => { TH.router.replaceQuery(Object.assign({ tab }, f, U.formData(el.closest('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key, projectId: f.projectId }); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({ tab }); TH.router.refresh(); }, add: () => Fm.shareholder({}), 'add-round': () => roundModal(f.projectId), 'add-dist': () => distModal(), roi: () => TH.go('#/investment/roi'), view: (el) => shView(St.get('shareholders', el.dataset.id)), more: (el) => { const c = St.get('contributions', el.dataset.id); if (c) return contribMenu(el, Object.assign({}, c, { st: Q.contributionStatus(c) })); shMenu(el, St.get('shareholders', el.dataset.id)); }, record: (el) => { const c = St.get('contributions', el.dataset.id); recordModal(Object.assign({}, c, { st: Q.contributionStatus(c) })); }, 'open-dist': (el) => distDrawer(St.get('distributions', el.dataset.id)) });
  }, { menu: 'shareholders', permission: 'shareholders.view', phase: 3, scopeKey: 'shareholders' });

  /* ================= #/investment/projects – Dự án (tự thiết kế) ================= */
  Fm.project = (p = {}) => { const used = St.all('projects').filter(x => x.id !== p.id).map(x => x.buildingId); const m = U.modal({ title: p.id ? 'Sửa dự án ' + p.code : 'Thêm dự án', sub: '1 dự án = 1 tòa; vốn điều lệ là cơ sở tính tỷ lệ cam kết', body: `<div class="form-grid">${U.field({ label: 'Tên dự án', req: true, input: U.input({ name: 'name', value: p.name || '', placeholder: 'Dự án Lotus' }), cls: 'span2' })}${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: p.buildingId || '', placeholder: 'Chọn tòa', options: St.all('buildings').filter(b => !used.includes(b.id)).map(b => [b.id, b.name + (b.stub ? ' (chưa vận hành)' : '')]) }) })}${U.field({ label: 'Vốn điều lệ (VND)', req: true, input: U.money({ name: 'capital', value: p.capital || '' }) })}${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: p.status || 'raising', options: Object.entries(Q.L.project).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Ngày bắt đầu', input: U.date({ name: 'startDate', value: p.startDate || F.today() }) })}${U.field({ label: 'ROI kỳ vọng (%/năm)', input: U.input({ name: 'expectedRoi', type: 'number', value: p.expectedRoi || 15 }) })}${U.field({ label: 'Mô tả', input: U.textarea({ name: 'note', value: p.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: p.id ? 'Lưu' : 'Thêm dự án', icon: 'folder', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); d.id = p.id; const r = X.saveProject(d); m.close(); ok((p.id ? 'Đã cập nhật ' : 'Đã tạo dự án ') + r.code, r.name); } }); };
  const projectDrawer = (p) => {
    const r = Q.projectRow(p); const rows = Q.shareholderRows({ projectId: p.id }); const cs = Q.contributions({ projectId: p.id }); const assets = St.where('assets', a => a.buildingId === p.buildingId && a.status === 'active');
    const m = U.drawer({ title: esc(p.name), sub: esc(r.b.name || '') + ' · ' + Q.chip('project', p.status) + ' · Vốn điều lệ ' + F.vnd(p.capital), wide: true, body: `<div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Thực góp', value: F.vnd(r.paid), cap: r.pct + '% vốn điều lệ', icon: 'coins', tone: 'green', mini: true, bar: r.pct })}${U.kpi({ label: 'Cổ đông', value: r.shareholders, cap: r.ratio + '% đã cam kết', icon: 'users', tone: 'blue', mini: true })}${U.kpi({ label: 'Tài sản', value: assets.length, cap: F.vnd(F.sum(assets, a => a.cost || 0)), icon: 'package', tone: 'purple', mini: true })}${U.kpi({ label: 'ROI tạm tính', value: r.roi.roi + '%', cap: 'LN kỳ ' + F.periodLabel(St.state.meta.period) + ' ' + F.vnd(r.roi.profit), icon: 'trending-up', tone: r.roi.tone === 'good' ? 'green' : r.roi.tone === 'fair' ? 'amber' : 'red', mini: true })}</div>${U.card({ title: 'Cổ đông & tỷ lệ', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Cổ đông</th><th class="num">Tỷ lệ</th><th class="num">Cam kết</th><th class="num">Đã góp</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(x => `<tr><td>${esc(x.s.name)}</td><td class="num">${x.ratio}%</td><td class="num">${F.vnd(x.committed)}</td><td class="num">${F.vnd(x.paid)}</td><td>${Q.chip('shareholder', x.status)}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Chưa có cổ đông</td></tr>'}</tbody></table>` })}${U.card({ title: 'Đợt góp vốn', icon: 'calendar', cls: 'mt16', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Đợt</th><th>Cổ đông</th><th>Hạn</th><th class="num">Số tiền</th><th>Trạng thái</th></tr></thead><tbody>${cs.slice(0, 12).map(c => `<tr><td>${esc(c.code)}</td><td>${esc(String(c.round))}</td><td>${esc(Q.shareholder(c.shareholderId).name)}</td><td>${F.date(c.dueDate)}</td><td class="num">${F.vnd(c.amount)}</td><td>${Q.chip('contribution', c.st)}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Chưa có</td></tr>'}</tbody></table>` })}<div class="row gap8 mt16">${U.btn({ label: 'Xem tài sản của tòa', icon: 'package', cls: 'btn-outline', act: 'assets' })}${U.btn({ label: 'Hiệu quả đầu tư', icon: 'trending-up', cls: 'btn-outline', act: 'roi' })}${U.btn({ label: 'Chi tiết tòa', icon: 'building', cls: 'btn-outline', act: 'b' })}</div>`, footer: U.btn({ label: 'Đóng', act: 'c' }) + (TH.auth.can('projects.manage') ? U.btn({ label: 'Sửa', icon: 'pencil', cls: 'btn-outline', act: 'e' }) : '') + (TH.auth.can('projects.manage') && p.status !== 'closed' ? U.btn({ label: 'Đóng dự án', icon: 'x-circle', cls: 'btn-ghost', act: 'close-p' }) : '') });
    U.bind(m.el, { c: () => m.close(), e: () => { m.close(); Fm.project(p); }, assets: () => { m.close(); TH.go('#/assets?buildingId=' + p.buildingId); }, roi: () => { m.close(); TH.go('#/investment/roi'); }, b: () => { m.close(); TH.go('#/buildings/' + p.buildingId); }, 'close-p': async () => { if (await U.confirm({ title: 'Đóng dự án ' + p.name + '?', ok: 'Đóng dự án', danger: true })) { X.closeProject(p.id); m.close(); ok('Đã đóng dự án'); } } });
  };
  TH.router.register('/investment/projects', (root, p, q) => {
    TH.router.crumb([{ label: 'Đầu tư' }, { label: 'Dự án' }]);
    const view = q.view || 'grid'; const my = isCodong() ? Q.myShareholder() : null; const rows = St.all('projects').map(Q.projectRow).filter(r => !q.status || r.p.status === q.status).filter(r => !my || Q.commitmentsOf(my.id, r.p.id).length);
    const total = F.sum(rows, r => r.p.capital), paid = F.sum(rows, r => r.paid), missing = F.sum(rows.flatMap(r => Q.contributions({ projectId: r.p.id, kind: 'capital' }).filter(c => c.st !== 'paid')), c => c.amount - (c.paidAmount || 0));
    root.innerHTML = `${U.pageHead({ title: 'Dự án đầu tư', phase: 3, sub: 'Mỗi dự án gắn 1 tòa; theo dõi vốn điều lệ, thực góp, cổ đông và hiệu quả. <span class="chip gray">Tự thiết kế – không có PNG</span>', acts: [U.btn({ label: 'Thêm dự án', icon: 'plus', cls: 'btn-primary', act: 'add-project', disabled: !TH.auth.can('projects.manage') }), U.btn({ label: view === 'grid' ? 'Xem bảng' : 'Xem thẻ', icon: view === 'grid' ? 'list' : 'grid', cls: 'btn-outline', act: 'toggle' })] })}
    ${U.filterbar([U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: q.status || '', all: 'Tất cả', options: Object.entries(Q.L.project).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Dự án đang vận hành', value: rows.filter(r => r.p.status === 'operating').length, cap: rows.length + ' dự án', icon: 'folder', tone: 'blue' })}${U.kpi({ label: 'Tổng vốn điều lệ', value: F.vnd(total), cap: 'VND', icon: 'database', tone: 'amber' })}${U.kpi({ label: 'Vốn thực góp', value: F.vnd(paid), cap: F.pct(paid, total) + '% vốn điều lệ', icon: 'check-circle', tone: 'green', bar: F.pct(paid, total) })}${U.kpi({ label: 'Còn thiếu', value: F.vnd(missing), cap: 'Nghĩa vụ chưa góp', icon: 'alert-triangle', tone: 'red', valueCls: missing ? 'red' : '' })}</div>
    ${view === 'grid' ? `<div class="proj-grid">${rows.map(U.projectCard).join('') || U.empty({ title: 'Chưa có dự án' })}</div>` : U.card({ title: 'Danh sách dự án', icon: 'folder', body: null, id: 'pjt' })}`;
    if (view !== 'grid') U.table(root.querySelector('#pjt'), { rows, unit: 'dự án', cols: [{ key: 'code', label: 'Mã', render: r => `<a class="link bold" data-act="open" data-id="${r.p.id}" href="#/investment/projects">${esc(r.p.code)}</a>` }, { key: 'name', label: 'Dự án', sortable: true, sortVal: r => r.p.name, render: r => U.cell2(esc(r.p.name), esc(r.b.name || '')) }, { key: 'status', label: 'Trạng thái', render: r => Q.chip('project', r.p.status) }, { key: 'capital', label: 'Vốn điều lệ', num: true, sortable: true, sortVal: r => r.p.capital, render: r => F.vnd(r.p.capital) }, { key: 'paid', label: 'Thực góp', num: true, render: r => F.vnd(r.paid) + ' (' + r.pct + '%)' }, { key: 'sh', label: 'Cổ đông', num: true, render: r => r.shareholders }, { key: 'assets', label: 'Tài sản', num: true, render: r => r.assets }, { key: 'roi', label: 'ROI', num: true, sortable: true, sortVal: r => r.roi.roi, render: r => `<span class="tone-${r.roi.tone} bold">${r.roi.roi}%</span>` }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({ view }, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, 'add-project': () => Fm.project({}), toggle: () => { TH.router.replaceQuery({ view: view === 'grid' ? 'table' : 'grid', status: q.status || '' }); TH.router.refresh(); }, open: (el) => projectDrawer(St.get('projects', el.dataset.id)) });
  }, { menu: 'projects', permission: 'projects.view', phase: 3, scopeKey: 'projects' });

  /* ================= #/investment/roi – Hiệu quả đầu tư (tự thiết kế) ================= */
  TH.router.register('/investment/roi', (root, p, q) => {
    TH.router.crumb([{ label: 'Đầu tư' }, { label: 'Hiệu quả đầu tư' }]);
    const period = TH.router.periodOf(q) || St.state.meta.period; const my = isCodong() ? Q.myShareholder() : null; const myB = my ? Q.commitmentsOf(my.id).map(c => Q.project(c.projectId).buildingId) : null;
    const rows = Q.roiRows(period).filter(r => (!q.buildingId || r.b.id === q.buildingId) && (!myB || myB.includes(r.b.id)));
    const tot = { capital: F.sum(rows, r => r.capital), income: F.sum(rows, r => r.income), expense: F.sum(rows, r => r.expense + r.dep), profit: F.sum(rows, r => r.profit) }; const avg = tot.capital ? Math.round(tot.profit * 12 / tot.capital * 1000) / 10 : 0;
    const periods = [...new Set(St.all('invoices').map(i => i.period).concat(['2026-10', '2026-09']))].sort().reverse();
    root.innerHTML = `${U.pageHead({ title: 'Hiệu quả đầu tư', phase: 3, sub: 'Hiệu suất và lợi nhuận theo tòa/dự án – công thức tạm tính. <span class="chip gray">Tự thiết kế – không có PNG</span>', acts: [U.btn({ label: 'Cổ đông & vốn góp', icon: 'users', cls: 'btn-outline', act: 'sh' }), U.btn({ label: 'Xuất CSV', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: q.buildingId || '', all: 'Tất cả tòa nhà', options: liveB().map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.note('warn', 'Công thức tạm tính – chờ chốt OI-10/12/13/17', 'Vốn = vốn điều lệ dự án + nguyên giá tài sản; Doanh thu = thu thật trong kỳ (FR-REP-02); Chi phí = chi phí kỳ (không gồm cọc/hoàn cọc) + khấu hao tháng (BR-08); ROI năm hóa = LN tháng × 12 / Vốn. Tòa bảo trì/ngừng: tỷ lệ lấp đầy N/A (OI-12).')}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng vốn đầu tư', value: F.vnd(tot.capital), cap: rows.length + ' tòa/dự án', icon: 'database', tone: 'blue' })}${U.kpi({ label: 'Doanh thu kỳ', value: F.vnd(tot.income), cap: F.periodLabel(period), icon: 'arrow-up', tone: 'green' })}${U.kpi({ label: 'Lợi nhuận kỳ', value: F.vnd(tot.profit), cap: 'Sau chi phí + khấu hao ' + F.vnd(F.sum(rows, r => r.dep)), icon: 'trending-up', tone: tot.profit >= 0 ? 'green' : 'red' })}${U.kpi({ label: 'ROI bình quân (năm hóa)', value: avg + '%', cap: 'Tạm tính', icon: 'percent', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'roi-related', cls: 'mb16', items: [
      { key: 'profit', title: 'Lợi nhuận theo tòa (triệu)', icon: 'bar-chart', summary: F.vnd(tot.profit) + ' VND', meta: rows.length ? 'Cao nhất: ' + esc((rows.slice().sort((a, b) => b.profit - a.profit)[0].b.name || '').replace('Tòa ', '')) : '', body: C.vbar({ items: rows.map(r => ({ label: (r.b.name || '').replace('Tòa ', ''), value: Math.round(r.profit / 1e6) })), height: 200 }) },
      { key: 'capital', title: 'Cơ cấu vốn đầu tư', icon: 'chart-pie', summary: F.vnd(tot.capital) + ' VND', meta: rows.length + ' tòa/dự án', body: C.donutLegend(rows.map((r, i) => ({ label: (r.b.name || '').replace('Tòa ', ''), value: r.capital, color: ['#2563EB', '#60A5FA', '#F59E0B', '#F97316', '#7C3AED', '#94A3B8'][i % 6], text: F.short(r.capital) })), 140, F.short(tot.capital).replace(' tỷ', 'B'), 'VND') }
    ] })}
    ${U.card({ title: 'Hiệu quả theo tòa', icon: 'building', body: null, id: 'rt' })}`;
    U.table(root.querySelector('#rt'), { rows, unit: 'tòa', noPager: true, footer: () => `<tr class="dist-total"><td>Tổng</td><td class="num">${F.vnd(tot.capital)}</td><td class="num">${F.vnd(tot.income)}</td><td class="num">${F.vnd(tot.expense)}</td><td class="num">${F.vnd(tot.profit)}</td><td class="num">${avg}%</td><td></td><td></td><td></td></tr>`, cols: [{ key: 'b', label: 'Tòa / dự án', render: r => U.cell2(U.link('#/buildings/' + r.b.id, esc(r.b.name || '')), esc((St.one('projects', x => x.buildingId === r.b.id) || {}).name || 'Chưa lập dự án')) }, { key: 'capital', label: 'Vốn', num: true, sortable: true, render: r => F.vnd(r.capital) }, { key: 'income', label: 'Doanh thu', num: true, sortable: true, render: r => F.vnd(r.income) }, { key: 'expense', label: 'Chi phí + KH', num: true, render: r => F.vnd(r.expense + r.dep) }, { key: 'profit', label: 'Lợi nhuận', num: true, sortable: true, render: r => `<span class="${r.profit < 0 ? 'red' : ''}">${F.vnd(r.profit)}</span>` }, { key: 'roi', label: 'ROI %', num: true, sortable: true, render: r => `<b class="tone-${r.tone}">${r.roi}%</b>` }, { key: 'payback', label: 'Hoàn vốn (năm)', num: true, render: r => r.payback != null ? r.payback : '—' }, { key: 'occ', label: 'Lấp đầy', num: true, render: r => r.occupancy != null ? r.occupancy + '%' : 'N/A' }, { key: 'tone', label: 'Đánh giá', render: r => Q.chip('roiTone', r.tone) }] });
    U.onChange(root, { f: () => TH.router.applyFilter({ buildingId: q.buildingId || '', period }, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, sh: () => TH.go('#/investment/shareholders'), export: () => { F.download('hieu-qua-dau-tu-' + period + '.csv', F.csv(rows.map(r => [r.b.name, r.capital, r.income, r.expense + r.dep, r.profit, r.roi, r.payback || '', r.occupancy != null ? r.occupancy : 'N/A']), ['Tòa', 'Vốn', 'Doanh thu', 'Chi phí + KH', 'Lợi nhuận', 'ROI %', 'Hoàn vốn', 'Lấp đầy']), 'text/csv'); ok('Đã xuất báo cáo'); } });
  }, { menu: 'roi', permission: 'roi.view', phase: 3, scopeKey: 'roi' });
})(window.TH);
