(function (TH) {
  const S = TH.store, Q = TH.q, X = TH.actions, F = TH.f, U = TH.ui, K = TH.kit, AS = TH.calc.assets, esc = F.esc;
  const proposalLabel = { qty: 'Số lượng', condition: 'Tình trạng', location: 'Vị trí', add: 'Thêm tài sản', remove: 'Loại bỏ' };
  const proposalValue = (kind, v) => kind === 'condition' ? AS.condLabel(v) : kind === 'location' ? ((v && v.roomId ? Q.roomCode(v.roomId) : '') + ' ' + ((v || {}).position || '')) : kind === 'add' ? (v || {}).name : kind === 'remove' ? 'Loại khỏi danh mục' : String(v == null ? '–' : v);
  TH.pages.invStatusLabel = s => ({ open: 'Chưa nhập', entered: 'Chờ duyệt kép', approved: 'Đã duyệt' }[s.status]);
  TH.pages.inventoryEntryDrawer = s => K.formDrawer({ title: 'Nhập kết quả kiểm kê – ' + Q.building(s.buildingId).code, sub: s.period + ' · số lượng và tình trạng tách riêng', wide: true, fields: s.lines.flatMap(l => {
    const a = Q.asset(l.assetId); return [{ name: 'qty_' + a.id, label: a.code + ' · ' + a.name + ' (sổ ' + l.bookQty + ')', type: 'number', value: l.actualQty == null ? l.bookQty : l.actualQty, req: true }, { name: 'cond_' + a.id, label: 'Tình trạng', type: 'select', options: AS.CONDITIONS, value: l.condition }, { name: 'note_' + a.id, label: 'Ghi chú', value: l.note }, { name: 'doc_' + a.id, label: 'Ảnh / chứng từ kiểm kê', type: 'select', value: (l.docIds || [])[0] || '', options: Q.downloadableDocs(d => d.buildingId === s.buildingId && ['asset', 'handover', 'other'].includes(d.type)).map(d => [d.id, d.name]), help: 'Chọn ảnh hoặc biên bản đã tải lên Kho tài liệu' }]; }), onSubmit: d => { X.enterInventory(s.period, s.buildingId, s.lines.map(l => ({ assetId: l.assetId, actualQty: d['qty_' + l.assetId], condition: d['cond_' + l.assetId], note: d['note_' + l.assetId], docIds: d['doc_' + l.assetId] ? [d['doc_' + l.assetId]] : [] }))); U.toast('ok', 'Đã nhập; cần admin và kế toán duyệt'); } });
  TH.pages.inventoryProposalDrawer = s => {
    const d = K.formDrawer({ title: 'Đề xuất sửa danh mục', wide: true, note: U.note('info', '', 'Chỉ áp sau đủ hai người duyệt; không tạo chi phí. Tài sản có nguyên giá dùng Thanh lý UI-34 khi cần loại bỏ.'), fields: [
      { name: 'assetId', label: 'Tài sản', type: 'select', options: s.lines.map(l => [l.assetId, Q.asset(l.assetId).code + ' · ' + Q.asset(l.assetId).name]) },
      { name: 'kind', label: 'Loại thay đổi', type: 'select', value: 'qty', options: [['qty', 'Số lượng'], ['condition', 'Tình trạng'], ['location', 'Vị trí'], ['add', 'Thêm tài sản chưa có giá trị'], ['remove', 'Loại bỏ tài sản không có giá trị']] },
      { name: 'qty', label: 'Số lượng mới', type: 'number', value: 1 }, { name: 'condition', label: 'Tình trạng mới', type: 'select', options: AS.CONDITIONS, value: 'good' },
      { name: 'position', label: 'Vị trí mới' }, { name: 'roomId', label: 'Phòng', type: 'select', options: (Q.roomsByBuilding()[s.buildingId] || []).map(r => [r.id, r.code]) },
      { name: 'name', label: 'Tên (khi thêm)' }, { name: 'type', label: 'Loại tài sản', type: 'select', options: AS.TYPES, value: 'other' }, { name: 'ownership', label: 'Sở hữu', type: 'select', options: AS.OWNERSHIP, value: 'owner' },
      { name: 'reason', label: 'Lý do / căn cứ', type: 'textarea', req: true, span: true }], onSubmit: x => {
      const to = x.kind === 'qty' ? Number(x.qty) : x.kind === 'condition' ? x.condition : x.kind === 'location' ? { buildingId: s.buildingId, roomId: x.roomId || null, position: x.position } : x.kind === 'add' ? { name: x.name, type: x.type, ownership: x.ownership, qty: Number(x.qty), condition: x.condition, roomId: x.roomId || null, position: x.position, receivedDate: F.today(), cost: 0 } : 'void';
      X.proposeAssetChange(s.id, { kind: x.kind, assetId: x.kind === 'add' ? null : x.assetId, to, reason: x.reason }); U.toast('ok', 'Đã lưu đề xuất; duyệt lại từ đầu');
    } }); return d;
  };
  TH.router.handle('/assets/inventory', (root, p, q) => {
    const period = q.period || S.meta.period, sessions = Q.inventorySessions(period), bid = q.building || (sessions[0] || {}).buildingId;
    const s = sessions.find(s => s.buildingId === bid);
    root.innerHTML = U.pageHead({ title: 'Kiểm kê tài sản', sub: 'Mỗi tòa một phiên tháng; tự mở ngày 01 · chỉ áp đề xuất sau admin + kế toán duyệt' }) + TH.pages.assetNav('/assets/inventory') + K.filters([{ name: 'period', label: 'Kỳ', options: K.periodOpts().filter(([p]) => p <= F.period(F.today())), value: period, all: false }, {name:'type',label:'Loại tài sản',options:AS.TYPES}], q)
      + '<div class="grid inventory-layout mt16"><div>' + U.card({ title: 'Phiên theo tòa', body: sessions.map(x => `<a class="mini-row ${x.buildingId === bid ? 'blue' : ''}" href="#/assets/inventory?period=${period}&building=${x.buildingId}${q.type ? "&type=" + encodeURIComponent(q.type) : ""}"><b>${esc(Q.building(x.buildingId).code)}</b><span>${esc(TH.pages.invStatusLabel(x))}<small class="d-block muted">Tự mở 01/${period.slice(5)}</small></span></a>`).join('') || U.empty({ title: 'Không có tài sản trong kỳ' }) }) + '</div><div>'
      + (s ? U.card({ title: 'Kết quả ' + Q.building(bid).code, sub: TH.pages.invStatusLabel(s) + ' · ' + Object.keys(s.approvals).length + '/2 duyệt', actions: [s.status !== 'approved' ? U.btn({ label: 'Nhập kết quả', act: 'enter', perm: 'inventory.enter' }) : '', s.status === 'entered' ? U.btn({ label: 'Đề xuất sửa danh mục', act: 'propose', perm: 'inventory.enter' }) : '', U.btn({ label: 'Xuất chênh', act: 'exp', icon: 'download' }), ...['admin', 'ketoan'].map(role => s.status === 'entered' && !s.approvals[role] ? U.btn({ label: 'Duyệt (' + TH.auth.roleLabel(role) + ')', act: 'approve', attrs: { 'data-role': role }, perm: role === 'admin' ? 'inventory.approve.admin' : 'inventory.approve.ketoan', cls: 'btn-primary' }) : '')].join(''), body: '<div id="lines"></div>' }) + '<div class="mt16">' + U.card({ title: 'Đề xuất danh mục', body: s.proposals.length ? s.proposals.map(p => `<div class="mini-row"><b>${esc(proposalLabel[p.kind])} · ${esc((Q.asset(p.assetId) || {}).code || 'Thêm')}</b><span>${p.from == null ? '' : esc(proposalValue(p.kind, p.from)) + ' → '}${esc(proposalValue(p.kind, p.to))}<small class="d-block muted">${esc(p.reason)}</small></span></div>`).join('') : 'Chưa có đề xuất' }) + '</div>' : U.empty({ title: 'Chọn phiên theo tòa' })) + '</div></div>';
    K.bindFilters(root, ['building']);
    if (!s) return;
    const visibleLines = s.lines.filter(l => !q.type || Q.asset(l.assetId)?.type === q.type);
    U.table(root.querySelector('#lines'), { rows: visibleLines, pageSize: 20, cols: [
      { key: 'a', label: 'Tài sản', render: l => U.cell2(esc(Q.asset(l.assetId).code + ' · ' + Q.asset(l.assetId).name), esc(Q.asset(l.assetId).position || Q.roomCode(Q.asset(l.assetId).roomId))) },
      { key: 'b', label: 'Số sổ', num: true, render: l => l.bookQty }, { key: 'c', label: 'Số thực', num: true, render: l => l.actualQty == null ? '–' : l.actualQty },
      { key: 'd', label: 'Chênh SL', render: l => l.actualQty == null ? 'Chưa nhập' : l.actualQty === l.bookQty ? U.chip('Đủ', 'green') : U.chip((l.actualQty < l.bookQty ? 'Thiếu ' : 'Dư ') + Math.abs(l.actualQty - l.bookQty), 'amber') },
      { key: 'e', label: 'Tình trạng', render: l => esc(AS.condLabel(l.condition)) }, { key: 'f', label: 'Người kiểm / ảnh', render: l => esc((S.get('users', l.checkedBy) || {}).name || l.checkedBy || '') + '<small class="d-block muted">' + esc((l.docIds || []).join(', ')) + '</small>' }] });
    U.bind(root, { enter: () => TH.pages.inventoryEntryDrawer(s), propose: () => TH.pages.inventoryProposalDrawer(s), approve: el => K.act(() => X.approveInventory(s.id, el.dataset.role), 'Đã ghi duyệt'), exp: () => K.xls('kiem-ke-' + period + '-' + Q.building(bid).code + '.xls', 'CHÊNH KIỂM KÊ', ['Kiểm kê ' + Q.building(bid).code, period, TH.pages.invStatusLabel(s),q.type?AS.TYPES.find(x=>x[0]===q.type)?.[1]||q.type:'Tất cả loại tài sản'], ['Mã', 'Tên', 'Sổ', 'Thực', 'Chênh SL', 'Tình trạng', 'Ghi chú'], visibleLines.filter(l => l.actualQty != null && (l.actualQty !== l.bookQty || l.condition !== (l.bookCondition || Q.asset(l.assetId).condition))).map(l => [Q.asset(l.assetId).code, Q.asset(l.assetId).name, l.bookQty, l.actualQty, l.actualQty - l.bookQty, AS.condLabel(l.condition), l.note])) });
  });
})(window.TH);
