(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const invMenu = (btn, inv) => { const rem = Q.invRemaining(inv); const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/invoices/' + inv.id) }];
    if (inv.docStatus === 'draft') items.push({ label: 'Phát hành', icon: 'send', disabled: !TH.auth.can('issueInvoice'), title: TH.auth.can('issueInvoice') ? '' : 'Cần vai trò Admin/Kế toán', onClick: () => { X.issueInvoice(inv.id); U.toast('ok', 'Đã phát hành ' + inv.code); } }, { label: 'Hủy nháp', icon: 'x-circle', danger: true, onClick: async () => { if (await U.confirm({ title: 'Hủy hóa đơn nháp ' + inv.code + '?', ok: 'Hủy nháp', danger: true })) { X.cancelDraftInvoice(inv.id); U.toast('ok', 'Đã hủy nháp'); } } });
    else { items.push({ label: 'Xác nhận thu tiền', icon: 'dollar', disabled: rem <= 0, onClick: () => Fm.confirmPayments({ invoiceIds: [inv.id] }) }, { label: 'Thu một phần / phân bổ thủ công', icon: 'clipboard-check', disabled: rem <= 0, onClick: () => Fm.payment({ invoiceId: inv.id }) }, { label: 'Gửi nhắc Zalo', icon: 'send', disabled: rem <= 0, onClick: () => Fm.zaloQuick({ invoiceIds: [inv.id], eventKey: 'debt' }) }, { label: 'Điều chỉnh', icon: 'pencil', disabled: !TH.auth.can('adjustInvoice'), onClick: () => Fm.adjustInvoice(inv) }); }
    items.push('-', { label: 'Tải PDF', icon: 'download', onClick: () => pdf(inv) }); U.menu(btn, items); };
  const pdf = (inv) => U.fakePdf('Hoa don ' + inv.code, ['Khách: ' + Q.tenant(inv.tenantId).name, 'Phòng: ' + Q.room(inv.roomId).code + ' – ' + Q.building(inv.buildingId).name, 'Kỳ: ' + F.periodLabel(inv.period), 'Hạn thanh toán: ' + F.date(inv.dueDate), '', ...Q.invLines(inv.id).map(l => l.item + ': ' + l.qty + ' x ' + F.vnd(l.unitPrice) + ' = ' + F.vnd(l.amount)), '', 'TỔNG CỘNG: ' + F.vnd(inv.total) + ' VND', 'Đã thu: ' + F.vnd(Q.invPaid(inv)), 'Còn lại: ' + F.vnd(Q.invRemaining(inv))]);
  TH.pages.invMenu = invMenu;
  /* ---------- Danh sách ---------- */
  TH.router.register('/invoices', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hóa đơn' }]);
    const period = TH.router.periodOf(q);
    const f = { period, areaId: q.areaId || '', buildingId: q.buildingId || '', buildingType: q.buildingType || '', managerId: q.managerId || '', leadId: q.leadId || '', doc: q.doc || '', pay: q.pay || '', overdue: q.overdue || '', s: q.s || '', tab: q.tab || '', room: q.room || '', min: q.min || '', max: q.max || '', reminded: q.reminded || '' }, scope = Q.scope({ period, areaId: q.areaId, buildingId: q.buildingId, buildingType: q.buildingType, managerId: q.managerId, leadId: q.leadId });
    const wasReminded = (i) => (i.reminderCount || 0) > 0 || !!St.one('zaloMessages', m => m.invoiceId === i.id && ['delivered', 'accepted'].includes(m.status));
    const all = St.where('invoices', i => i.docStatus !== 'cancelled' && scope.buildingIds.includes(i.buildingId || Q.contract(i.contractId).buildingId) && (!f.period || i.period === f.period) && (!f.room || i.roomId === f.room)).map(i => ({ i, pay: Q.invPayStatus(i), over: Q.invOverdue(i), rem: Q.invRemaining(i), paid: Q.invPaid(i) }));
    const cnt = { all: all.length, draft: all.filter(x => x.i.docStatus === 'draft').length, issued: all.filter(x => x.i.docStatus === 'issued').length, unpaid: all.filter(x => x.i.docStatus !== 'draft' && x.pay === 'unpaid').length, partial: all.filter(x => x.pay === 'partial').length, paid: all.filter(x => x.pay === 'paid').length, overdue: all.filter(x => x.over).length, adjusted: all.filter(x => x.i.docStatus === 'adjusted').length };
    const tabF = { '': () => true, draft: x => x.i.docStatus === 'draft', issued: x => x.i.docStatus === 'issued', unpaid: x => x.i.docStatus !== 'draft' && x.pay === 'unpaid', partial: x => x.pay === 'partial', paid: x => x.pay === 'paid', overdue: x => x.over, adjusted: x => x.i.docStatus === 'adjusted' }[f.tab] || (() => true);
    const rows = all.filter(x => tabF(x) && (!f.buildingId || x.i.buildingId === f.buildingId) && (!f.doc || x.i.docStatus === f.doc) && (!f.pay || x.pay === f.pay) && (!f.overdue || (f.overdue === 'yes' ? x.over : !x.over)) && (!f.min || x.i.total >= F.num(f.min)) && (!f.max || x.i.total <= F.num(f.max)) && (!f.reminded || (f.reminded === '1') === wasReminded(x.i)) && (!f.s || F.norm(x.i.code + ' ' + Q.tenant(x.i.tenantId).name + ' ' + Q.room(x.i.roomId).code).includes(F.norm(f.s)))).sort((a, b) => F.cmp(a.i.code, b.i.code));
    const issued = all.filter(x => x.i.docStatus !== 'draft'); const totRec = F.sum(issued, x => x.i.total), totPaid = F.sum(issued, x => x.paid);
    const prevP = f.period ? Q.prevPeriod(f.period) : ''; const prevAll = prevP ? St.where('invoices', i => i.docStatus !== 'cancelled' && scope.buildingIds.includes(i.buildingId || Q.contract(i.contractId).buildingId) && i.period === prevP && (!f.room || i.roomId === f.room)) : []; const prevIssued = prevAll.filter(i => i.docStatus !== 'draft'); const prevRec = F.sum(prevIssued, i => i.total), prevPaid = F.sum(prevIssued, i => Q.invPaid(i));
    root.innerHTML = `${U.pageHead({ title: 'Hóa đơn', sub: 'Quản lý, theo dõi và phát hành hóa đơn cho khách thuê.', acts: [U.btn({ label: 'Tạo hóa đơn theo kỳ', icon: 'plus', cls: 'btn-primary', act: 'batch', attrs: { 'data-guide': 'invoice-batch' } }), U.btn({ label: 'Phát hành bản nháp hợp lệ', icon: 'arrow-left-right', cls: 'btn-outline', act: 'issue-valid', disabled: !TH.auth.can('issueInvoice'), title: TH.auth.can('issueInvoice') ? '' : 'Cần vai trò Admin/Kế toán' }), U.iconBtn('more', 'page-more', 'Thêm thao tác', {}, 'bordered')] })}
    ${f.room ? U.note('info', 'Đang lọc theo phòng ' + esc(Q.room(f.room).code || '') + ' – ' + esc(Q.building(Q.room(f.room).buildingId).name || ''), '<a class="link" data-act="clear-room">Bỏ lọc phòng</a>') : ''}
    ${U.statusTabs([['', 'Tất cả', cnt.all], ['draft', 'Nháp', cnt.draft], ['issued', 'Đã phát hành', cnt.issued], ['unpaid', 'Chưa thu', cnt.unpaid], ['partial', 'Thu một phần', cnt.partial], ['paid', 'Thu đủ', cnt.paid], ['overdue', 'Quá hạn', cnt.overdue], ['adjusted', 'Đã điều chỉnh', cnt.adjusted]].map(([k, l, c]) => ({ key: k, label: l, count: c })), f.tab)}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: f.period, all: 'Tất cả kỳ', options: [...new Set(St.all('invoices').map(i => i.period))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái chứng từ', input: U.select({ name: 'doc', value: f.doc, all: 'Tất cả', options: Object.entries(Q.L.invDoc).filter(([k]) => k !== 'cancelled').map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái thu', input: U.select({ name: 'pay', value: f.pay, all: 'Tất cả', options: [['unpaid', 'Chưa thu'], ['partial', 'Thu một phần'], ['paid', 'Thu đủ']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Quá hạn', input: U.select({ name: 'overdue', value: f.overdue, all: 'Tất cả', options: [['yes', 'Quá hạn'], ['no', 'Chưa quá hạn']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo mã, khách hàng, phòng...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.dimMore(f, ['areaId', 'buildingType', 'managerId', 'leadId'])], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }) + U.btn({ label: 'Bộ lọc nâng cao', icon: 'filter', cls: 'btn-outline', p2: true, act: 'adv-filter' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng hóa đơn', value: cnt.all, cap: f.period ? 'Trong kỳ ' + F.periodLabel(f.period) : 'Tất cả kỳ', icon: 'receipt', tone: 'blue', delta: prevP ? Q.deltaPct(cnt.all, prevAll.length) : null })}${U.kpi({ label: 'Tổng phải thu', value: F.vnd(totRec), cap: 'Tổng giá trị hóa đơn đã phát hành', icon: 'dollar', tone: 'amber', delta: prevP ? Q.deltaPct(totRec, prevRec) : null })}${U.kpi({ label: 'Đã thu', value: F.vnd(totPaid), cap: F.pct(totPaid, totRec) + '% tổng phải thu', icon: 'check-circle', tone: 'green', delta: prevP ? Q.deltaPct(totPaid, prevPaid) : null })}${U.kpi({ label: 'Còn phải thu', value: F.vnd(totRec - totPaid), cap: F.pct(totRec - totPaid, totRec) + '% tổng phải thu', icon: 'alert-circle', tone: 'red', delta: prevP ? Q.deltaPct(totRec - totPaid, prevRec - prevPaid) : null })}</div>
    ${U.card({ title: 'Danh sách hóa đơn', actions: `<span id="bulk-acts" class="row"></span>` + U.btn({ label: 'Bộ cột', icon: 'columns', size: 'btn-sm', cls: 'btn-outline', act: 'cols' }), body: null, id: 'tbl-card', attrs: 'data-guide="invoices-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const tbl = U.table(wrap, { rows, selectable: true, unit: 'hóa đơn', rowKey: x => x.i.id, colPrefsKey: 'invoices', onSelect: (ids) => { const sel = ids.map(id => St.get('invoices', id)); const el = root.querySelector('#bulk-acts'); const payable = sel.filter(i => i.docStatus !== 'draft' && Q.invRemaining(i) > 0); el.innerHTML = ids.length ? `<span class="small muted">${ids.length} đã chọn</span>${TH.auth.can('invoices.prepare') ? U.btn({ label: 'Phát hành', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-issue', disabled: !sel.some(i => i.docStatus === 'draft') }) : ''}${TH.auth.can('zalo.send') ? U.btn({ label: 'Gửi nhắc Zalo', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-zalo', disabled: !payable.length }) : ''}${U.btn({ label: 'Xác nhận thu tiền' + (payable.length ? ' (' + payable.length + ')' : ''), icon: 'dollar', size: 'btn-sm', cls: 'btn-primary', act: 'bulk-pay', disabled: !payable.length, title: payable.length ? 'Thu đủ số còn lại kèm minh chứng' : 'Chọn hóa đơn đã phát hành còn nợ' })}` : ''; }, cols: [
      { key: 'code', label: 'Mã hóa đơn', sortable: true, sortVal: x => x.i.code, render: x => U.link('#/invoices/' + x.i.id, esc(x.i.code), 'bold') }, { key: 'period', label: 'Kỳ', render: x => F.periodShort(x.i.period) },
      { key: 't', label: 'Khách', render: x => U.link('#/tenants/' + x.i.tenantId, esc(Q.tenant(x.i.tenantId).name)) }, { key: 'room', label: 'Phòng / Tòa', render: x => U.cell2(esc(Q.room(x.i.roomId).code), esc(Q.building(x.i.buildingId).name)) },
      { key: 'due', label: 'Hạn thanh toán', sortable: true, sortVal: x => x.i.dueDate, render: x => `<span class="${x.over ? 'red' : ''}">${F.date(x.i.dueDate)}</span>` },
      { key: 'total', label: 'Tổng tiền', num: true, sortable: true, sortVal: x => x.i.total, render: x => F.vnd(x.i.total) }, { key: 'paid', label: 'Đã thu', num: true, render: x => F.vnd(x.paid) }, { key: 'rem', label: 'Còn lại', num: true, render: x => `<span class="${x.rem && x.over ? 'red bold' : ''}">${F.vnd(x.rem)}</span>` },
      { key: 'doc', label: 'Trạng thái chứng từ', render: x => Q.chip('invDoc', x.i.docStatus) }, { key: 'pay', label: 'Trạng thái thu', render: x => x.i.docStatus === 'draft' ? '<span class="muted">–</span>' : Q.invPayChip(x.i) },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': x.i.id } }), x.i.docStatus !== 'draft' && x.rem > 0 ? U.actBtn({ icon: 'dollar', label: 'Xác nhận thu tiền', act: 'pay', tone: 'primary', attrs: { 'data-id': x.i.id } }) : '', U.moreBtn(x.i.id)]), hideable: false }] });
    const wbCols = [
      { key: 'ref', label: 'Mã tòa · phòng', render: x => esc(F.roomRef(Q.building(x.i.buildingId), Q.room(x.i.roomId))) },
      { key: 'manager', label: 'Quản lý', render: x => esc(Q.userName(Q.building(x.i.buildingId).managerId)) },
      { key: 'deposit', label: 'Tiền cọc', num: true, render: x => F.vnd(Q.contract(x.i.contractId).deposit || 0) },
      { key: 'listPrice', label: 'Giá niêm yết', num: true, render: x => F.vnd(Q.contract(x.i.contractId).listPrice || 0) },
      { key: 'price', label: 'Giá cho thuê', num: true, render: x => F.vnd(Q.contract(x.i.contractId).price || 0) },
      { key: 'paidMonths', label: 'Số tháng đã TT', num: true, render: x => Q.paidMonths(Q.contract(x.i.contractId)) },
      { key: 'lastPay', label: 'Ngày thu gần nhất', render: x => F.date(Q.lastPaymentDate(x.i)) }
    ];
    tbl.state.opts.cols.push(...wbCols); tbl.state.opts.presets = { doisoat: { label: 'Đối soát', cols: ['ref', 'manager', 'deposit', 'listPrice', 'price', 'paidMonths', 'total', 'paid', 'rem', 'lastPay', 'due', 'pay', 'actions'] } }; tbl.render();
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelector('.filterbar'))) });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') TH.router.applyFilter(f, { s: e.target.value }); });
    U.bind(root, {
      batch: () => TH.go('#/invoices/batch'), import: () => TH.go('#/settings/import?type=invoice&back=' + encodeURIComponent('#/invoices?tab=draft&period=all')), pay: (b) => Fm.confirmPayments({ invoiceIds: [b.dataset.id] }), 'bulk-pay': () => Fm.confirmPayments({ invoiceIds: tbl.selected() }), stab: (el) => TH.router.applyFilter(f, { tab: el.dataset.key }), 'clear-room': () => TH.router.applyFilter(f, { room: '' }), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => TH.go('#/invoices/' + b.dataset.id), more: (b) => invMenu(b, St.get('invoices', b.dataset.id)), cols: b => U.columnMenu(b, tbl, tbl.state.opts.cols),
      export: () => { F.download('hoa-don-' + (f.period || 'all') + '.csv', U.tableCsv(tbl, rows), 'text/csv'); U.toast('ok', 'Đã xuất danh sách hóa đơn theo bộ cột đang chọn'); },
      'page-more': (el) => U.menu(el, [{ label: 'Import hóa đơn', icon: 'upload', onClick: () => TH.go('#/settings/import?type=invoice&back=' + encodeURIComponent('#/invoices?tab=draft&period=all')) }, { label: 'Xuất danh sách (CSV)', icon: 'download', onClick: () => { F.download('hoa-don-' + (f.period || 'all') + '.csv', U.tableCsv(tbl, rows), 'text/csv'); U.toast('ok', 'Đã xuất danh sách hóa đơn theo bộ cột đang chọn'); } }]),
      'issue-valid': async () => { const drafts = St.where('invoices', i => i.docStatus === 'draft' && Q.invLines(i.id).length && (!f.period || i.period === f.period)); if (!drafts.length) return U.toast('info', 'Không có hóa đơn nháp hợp lệ'); const ok = await U.confirm({ title: 'Phát hành ' + drafts.length + ' hóa đơn nháp hợp lệ?', text: 'Chỉ phát hành nháp đã đủ dòng phí (không thiếu chỉ số). Thao tác idempotent – chạy lại không tạo trùng (NFR-03).', ok: 'Phát hành', body: `<div class="tbl-wrap" style="max-height:220px;overflow:auto"><table class="tbl compact">${drafts.map(i => `<tr><td>${i.code}</td><td>${esc(Q.tenant(i.tenantId).name)}</td><td class="num">${F.vnd(i.total)}</td></tr>`).join('')}</table></div>` }); if (ok) { const n = X.issueInvoices(drafts.map(i => i.id)); U.toast('ok', 'Đã phát hành ' + n + ' hóa đơn'); } },
      'bulk-issue': () => { const n = X.issueInvoices(tbl.selected()); U.toast('ok', 'Đã phát hành ' + n + ' hóa đơn'); }, 'bulk-zalo': () => Fm.zaloQuick({ invoiceIds: tbl.selected().filter(id => St.get('invoices', id).docStatus !== 'draft'), eventKey: 'debt', title: 'Gửi nhắc tiền cho hóa đơn đã chọn' }),
    });
  }, { menu: 'invoices', permission: 'invoices.view' });

  /* ---------- Tạo hóa đơn theo kỳ (wizard) ---------- */
  const BSTEPS = [{ title: 'Chọn kỳ & phạm vi', sub: 'Chọn tháng, tòa nhà, dịch vụ' }, { title: 'Điện nước & dịch vụ', sub: 'Nhập và kiểm tra chỉ số' }, { title: 'Preflight & preview', sub: 'Kiểm tra dữ liệu, xem trước' }, { title: 'Tạo nháp', sub: 'Tạo hóa đơn hàng loạt' }];
  TH.router.register('/invoices/batch', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hóa đơn', href: '#/invoices' }, { label: 'Tạo theo kỳ' }]);
    const step = Number(q.step || (q.buildingId || q.room ? 2 : 1)); const period = q.period || St.state.meta.period;
    const bIds = q.buildingId ? q.buildingId.split(',') : St.where('buildings', b => !b.stub).map(b => b.id).slice(0, 2);
    const svcSel = q.svc ? q.svc.split(',') : ['RENT', 'DIEN', 'NUOC', 'FIXED']; const canIssue = TH.auth.can('issueInvoice'); const issueLater = !canIssue || q.issue !== 'now';
    let rows = X.batchRows(period, bIds); if (q.room) rows = rows.filter(r => r.room.id === q.room);
    const valid = rows.filter(r => r.valid), need = rows.filter(r => !r.valid); const est = F.sum(valid, r => r.rent + r.fixed + (r.electricCurr - r.electricPrev) * r.priceE + (r.waterCurr - r.waterPrev) * r.priceW);
    const go = (extra) => { TH.router.replaceQuery(Object.assign({ step, period, buildingId: bIds.join(','), svc: svcSel.join(','), issue: issueLater ? 'later' : 'now', room: q.room || '' }, extra)); TH.router.refresh(); };
    const scopeBar = U.card({ cls: 'mb16', body: `<div class="filterbar" style="padding:0">${U.field({ label: 'Kỳ hóa đơn', input: U.select({ name: 'period', value: period, options: ['2026-09', '2026-10', '2026-11', '2026-12'].map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'scope' } }) })}<div class="field wide"><label>Tòa nhà<span class="req">*</span></label><div class="chips-inp">${bIds.map(id => `<span class="chipx">${esc(Q.building(id).name)}<button data-act="rm-b" data-id="${id}">×</button></span>`).join('')}<select class="inp sm" style="border:0;width:auto;flex:1;min-width:120px" data-on="add-b"><option value="">+ Thêm tòa</option>${St.where('b' + 'uildings', b => !b.stub && !bIds.includes(b.id)).map(b => `<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div></div><div class="field wide"><label>Dịch vụ áp dụng<span class="req">*</span></label><div class="chips-inp">${[['RENT', 'Tiền phòng'], ['DIEN', 'Điện'], ['NUOC', 'Nước'], ['FIXED', 'Dịch vụ cố định']].map(([k, l]) => `<label class="chk" style="margin-right:6px"><input type="checkbox" data-on="svc" value="${k}" ${svcSel.includes(k) ? 'checked' : ''} ${k === 'RENT' ? 'disabled' : ''}> ${l}</label>`).join('')}</div></div><div class="field">${U.check({ name: 'later', label: 'Phát hành sau ' + I('info'), checked: issueLater, attrs: { 'data-on': 'issue', disabled: !canIssue, title: canIssue ? '' : 'Cần vai trò Admin/Kế toán để phát hành ngay' } })}<div class="help">${canIssue ? 'Chỉ tạo nháp, chưa phát hành đến khách thuê' : 'Vận hành chỉ tạo nháp – phát hành cần Admin/Kế toán (FR-FIN-01)'}</div></div></div>` });
    const summary = `<div class="side-stack">${U.card({ title: 'Tóm tắt kỳ hóa đơn', icon: 'clipboard-check', body: `<div class="col gap12">${U.kpi({ label: 'Tổng số phòng', value: rows.length, cap: 'Trong ' + bIds.length + ' tòa nhà, có HĐ hiệu lực', icon: 'door', tone: 'blue' })}${U.kpi({ label: 'Hợp lệ', value: valid.length, cap: 'Đủ dữ liệu, sẵn sàng tạo nháp', icon: 'check-circle', tone: 'green', delta: F.pct(valid.length, rows.length) })}${U.kpi({ label: 'Cần kiểm tra', value: need.length, cap: 'Thiếu chỉ số, đã có hóa đơn hoặc có cảnh báo', icon: 'alert-triangle', tone: 'red', delta: F.pct(need.length, rows.length), deltaDir: 'down' })}${U.kpi({ label: 'Dự thu (tạm tính)', value: F.vnd(est), cap: 'Tổng tiền phòng, dịch vụ và điện nước của phòng hợp lệ', icon: 'coins', tone: 'amber' })}</div>` })}${U.note('info', 'Quy tắc', 'Không tạo trùng cùng HĐ/kỳ; dòng thiếu chỉ số bị loại, không lấy 0 rồi phát hành (FR-FIN-01/02). Chỉ số mới < cũ cần luồng thay công tơ.')}</div>`;
    let main = '';
    if (step === 1) main = U.card({ title: 'Bước 1 – Chọn kỳ & phạm vi', icon: 'calendar', body: `<p class="small muted mb12">Chọn tháng lập hóa đơn, các tòa và loại dịch vụ. Hệ thống nạp toàn bộ hợp đồng đang hiệu lực trong phạm vi.</p>${U.kv([['Kỳ', F.periodLabel(period)], ['Tòa', bIds.map(id => Q.building(id).name).join(', ') || '<span class="red">Chưa chọn</span>'], ['Hợp đồng hiệu lực', rows.length], ['Chưa có hóa đơn kỳ này', rows.filter(r => !r.invoice).length], ['Đã có hóa đơn kỳ này', rows.filter(r => r.invoice).length]], 'one')}` }) + `<div class="wz-foot"><span></span>${U.btn({ label: 'Tiếp tục nhập chỉ số →', cls: 'btn-primary', act: 'to2', disabled: !bIds.length })}</div>`;
    if (step === 2) main = `${U.card({ title: `Danh sách phòng <span class="muted" style="font-weight:400">(${rows.length} phòng)</span>`, actions: U.btn({ label: 'Nhập hàng loạt', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'bulk' }), body: null, id: 'mt' })}<div class="wz-foot"><div class="row">${U.btn({ label: 'Import chỉ số', icon: 'upload', cls: 'btn-outline', act: 'import' })}<span class="small muted">Hỗ trợ file CSV/Excel. Tải mẫu <a class="link" data-act="sample">tại đây</a>.</span></div><div class="row">${U.btn({ label: 'Lưu tạm', icon: 'save', cls: 'btn-outline', act: 'save', attrs: { 'data-guide': 'meter-save' } })}${U.btn({ label: 'Tiếp tục preflight →', cls: 'btn-primary', act: 'to3' })}</div></div>`;
    if (step === 3) main = `${U.card({ title: 'Preflight – kiểm tra dữ liệu & xem trước', icon: 'shield-check', sub: valid.length + ' phòng hợp lệ sẽ được tạo; ' + need.length + ' phòng bị loại', body: null, id: 'pf' })}<div class="wz-foot">${U.btn({ label: '← Quay lại nhập chỉ số', cls: 'btn-ghost', act: 'to2' })}${U.btn({ label: 'Tạo ' + valid.length + ' hóa đơn ' + (issueLater ? 'nháp' : 'và phát hành') + ' →', icon: 'file-plus', cls: 'btn-primary', act: 'create', disabled: !valid.length, attrs: { 'data-guide': 'invoice-create' } })}</div>`;
    if (step === 4) { const res = TH._batchResult && TH._batchResult.created ? TH._batchResult : { created: [], skipped: [] }; main = U.card({ title: 'Kết quả tạo hóa đơn', icon: 'check-circle', body: `${U.note(res.created.length ? 'ok' : 'warn', 'Đã tạo ' + res.created.length + ' hóa đơn ' + (issueLater ? 'nháp' : 'và phát hành'), res.skipped.length ? res.skipped.length + ' phòng bị bỏ qua: ' + res.skipped.map(s => Q.room(s.c.roomId).code + ' (' + s.why + ')').join(', ') : 'Không có phòng bị bỏ qua.')}<div class="tbl-wrap mt12"><table class="tbl compact"><thead><tr><th>Mã hóa đơn</th><th>Phòng</th><th>Khách</th><th class="num">Tổng</th><th>Trạng thái</th><th></th></tr></thead><tbody>${res.created.map(i => `<tr><td>${U.link('#/invoices/' + i.id, i.code)}</td><td>${esc(Q.room(i.roomId).code)}</td><td>${esc(Q.tenant(i.tenantId).name)}</td><td class="num">${F.vnd(i.total)}</td><td>${Q.chip('invDoc', i.docStatus)}</td><td>${U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': i.id } })}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Không có</td></tr>'}</tbody></table></div><div class="row mt16 gap12">${U.btn({ label: 'Về danh sách hóa đơn', cls: 'btn-primary', act: 'list' })}${issueLater && res.created.length ? U.btn({ label: 'Phát hành ngay ' + res.created.length + ' nháp', icon: 'send', cls: 'btn-outline', act: 'issue-now', disabled: !TH.auth.can('issueInvoice') }) : ''}${res.created.length && !issueLater ? U.btn({ label: 'Gửi hóa đơn qua Zalo', icon: 'send', cls: 'btn-outline', act: 'zalo' }) : ''}</div>` }); }
    root.innerHTML = `${U.pageHead({ title: 'Tạo hóa đơn theo kỳ', sub: 'Lập hóa đơn hàng loạt theo tháng và kiểm tra dữ liệu trước khi tạo nháp.' })}${U.wizard(BSTEPS, step - 1)}${step < 4 ? scopeBar : ''}<div class="two-col wide"><div>${main}</div>${step < 4 ? summary : ''}</div>`;
    if (step === 2) U.table(root.querySelector('#mt'), { rows, unit: 'phòng', noPager: true, editable: true, rowKey: r => r.room.id, rowClass: r => r.invoice ? 'tint-blue' : '', cols: [
      { key: 'room', label: 'Phòng / Tòa', render: r => U.cell2(`<b>${esc(r.room.code)}</b>`, esc(Q.building(r.room.buildingId).name)) },
      { key: 'ep', label: 'Chỉ số điện cũ', num: true, render: r => `<input class="inp sm tr" type="number" data-m="electricPrev" data-r="${r.room.id}" value="${r.electricPrev}" ${r.invoice ? 'disabled' : ''} style="width:90px">` }, { key: 'ec', label: 'Chỉ số điện mới', num: true, render: r => `<input class="inp sm tr" type="number" data-m="electricCurr" data-r="${r.room.id}" value="${r.electricCurr ?? ''}" ${r.invoice ? 'disabled' : ''} style="width:90px">` }, { key: 'eu', label: 'SL điện (kWh)', num: true, render: r => r.electricCurr != null ? `<span class="computed" data-u="e-${r.room.id}">${r.electricCurr - r.electricPrev}</span>` : `<span class="muted" data-u="e-${r.room.id}">-</span>` },
      { key: 'wp', label: 'Chỉ số nước cũ', num: true, render: r => `<input class="inp sm tr" type="number" data-m="waterPrev" data-r="${r.room.id}" value="${r.waterPrev}" ${r.invoice ? 'disabled' : ''} style="width:80px">` }, { key: 'wc', label: 'Chỉ số nước mới', num: true, render: r => `<input class="inp sm tr" type="number" data-m="waterCurr" data-r="${r.room.id}" value="${r.waterCurr ?? ''}" ${r.invoice ? 'disabled' : ''} style="width:80px">` }, { key: 'wu', label: 'SL nước (m³)', num: true, render: r => r.waterCurr != null ? `<span class="computed" data-u="w-${r.room.id}">${r.waterCurr - r.waterPrev}</span>` : `<span class="muted" data-u="w-${r.room.id}">-</span>` },
      { key: 'rent', label: 'Tiền phòng (VND)', num: true, render: r => F.vnd(r.rent) }, { key: 'fixed', label: 'DV cố định (VND)', num: true, render: r => F.vnd(r.fixed) },
      { key: 'w', label: 'Cảnh báo', render: r => r.warns.length ? r.warns.map(w => U.chip(w, /Thiếu|<|Đã có hóa/.test(w) ? 'red' : w.startsWith('Đã') ? 'blue' : 'amber')).join(' ') : '<span class="muted">-</span>' }] });
    if (step === 3) U.table(root.querySelector('#pf'), { rows, unit: 'phòng', pageSize: 20, rowClass: r => r.valid ? '' : 'tint-red', cols: [
      { key: 'room', label: 'Phòng / Tòa', render: r => U.cell2(`<b>${esc(r.room.code)}</b>`, esc(Q.building(r.room.buildingId).name)) }, { key: 't', label: 'Khách', render: r => esc(Q.tenant(r.contract.tenantId).name) },
      { key: 'rent', label: 'Tiền phòng', num: true, render: r => F.vnd(r.rent) }, { key: 'fixed', label: 'DV cố định', num: true, render: r => F.vnd(r.fixed) }, { key: 'e', label: 'Điện', num: true, render: r => r.electricCurr != null ? (r.electricCurr - r.electricPrev) + ' × ' + F.vnd(r.priceE) + ' = ' + F.vnd((r.electricCurr - r.electricPrev) * r.priceE) : '<span class="red">Thiếu</span>' }, { key: 'wt', label: 'Nước', num: true, render: r => r.waterCurr != null ? (r.waterCurr - r.waterPrev) + ' × ' + F.vnd(r.priceW) + ' = ' + F.vnd((r.waterCurr - r.waterPrev) * r.priceW) : '<span class="red">Thiếu</span>' },
      { key: 'tot', label: 'Tổng dự kiến', num: true, render: r => r.valid ? `<b>${F.vnd(r.rent + r.fixed + (r.electricCurr - r.electricPrev) * r.priceE + (r.waterCurr - r.waterPrev) * r.priceW)}</b>` : '-' }, { key: 'due', label: 'Hạn thanh toán', render: r => F.date(period + '-' + F.pad(Math.min(28, r.contract.payDay))) }, { key: 'st', label: 'Kết quả', render: r => r.valid ? U.chip('Sẽ tạo', 'green') : r.warns.map(w => U.chip(w, 'red')).join(' ') }] });
    const collectMeters = () => { const map = {}; root.querySelectorAll('input[data-m]').forEach(inp => { if (inp.disabled) return; const r = map[inp.dataset.r] = map[inp.dataset.r] || { roomId: inp.dataset.r, contractId: ((rows.find(x => x.room.id === inp.dataset.r) || {}).contract || {}).id || null }; r[inp.dataset.m] = inp.value === '' ? null : Number(inp.value); }); return Object.values(map); };
    const meterToast = (res) => U.toast(res.skipped.length ? 'warn' : 'ok', 'Đã lưu tạm ' + res.saved + ' chỉ số', res.skipped.length ? 'Bỏ qua ' + res.skipped.length + ' dòng: ' + res.skipped.slice(0, 4).join(', ') + (res.skipped.length > 4 ? '…' : '') : 'Chỉ số nháp, chưa lập hóa đơn');
    root.addEventListener('input', (e) => { if (!e.target.matches('input[data-m]')) return; const rid = e.target.dataset.r; const g = (m) => { const el = root.querySelector(`input[data-m=${m}][data-r="${rid}"]`); return el && el.value !== '' ? Number(el.value) : null; }; [['e', 'electric'], ['w', 'water']].forEach(([k, t]) => { const prev = g(t + 'Prev'), cur = g(t + 'Curr'); const el = root.querySelector(`[data-u="${k}-${rid}"]`); if (!el) return; if (cur == null) { el.className = 'muted'; el.textContent = '-'; } else if (cur < prev) { el.className = 'computed red'; el.textContent = 'Lỗi'; } else { el.className = 'computed'; el.textContent = cur - prev; } }); });
    U.onChange(root, { scope: (el) => go({ period: el.value }), 'add-b': (el) => { if (el.value) go({ buildingId: [...bIds, el.value].join(',') }); }, svc: (el) => { const next = new Set(svcSel); if (el.checked) next.add(el.value); else next.delete(el.value); next.add('RENT'); go({ svc: [...next].join(',') }); }, issue: (el) => go({ issue: el.checked ? 'later' : 'now' }) });
    U.bind(root, {
      'rm-b': (el) => go({ buildingId: bIds.filter(x => x !== el.dataset.id).join(',') }), to2: () => go({ step: 2 }), to3: () => { const res = X.saveMeterReadings(period, collectMeters()); if (res.skipped.length) meterToast(res); TH._batchKey = F.uid('batch'); go({ step: 3 }); }, list: () => TH.go('#/invoices?period=' + period), view: (b) => TH.go('#/invoices/' + b.dataset.id),
      save: () => { const res = X.saveMeterReadings(period, collectMeters()); meterToast(res); go({ step: 2 }); },
      bulk: (b) => U.menu(b, [{ label: 'Chỉ số mới = cũ + trung bình kỳ trước', icon: 'copy', onClick: () => { root.querySelectorAll('input[data-m=electricCurr]:not([disabled])').forEach(i => { if (!i.value) { const prev = root.querySelector(`input[data-m=electricPrev][data-r="${i.dataset.r}"]`); i.value = Number(prev.value) + 150; i.dispatchEvent(new Event('input', { bubbles: true })); } }); root.querySelectorAll('input[data-m=waterCurr]:not([disabled])').forEach(i => { if (!i.value) { const prev = root.querySelector(`input[data-m=waterPrev][data-r="${i.dataset.r}"]`); i.value = Number(prev.value) + 12; i.dispatchEvent(new Event('input', { bubbles: true })); } }); U.toast('ok', 'Đã điền chỉ số ước tính cho các dòng trống', 'Chỉ điền trường trống – kiểm tra lại trước khi lưu'); } }, { label: 'Xóa chỉ số mới chưa lưu', icon: 'trash', onClick: () => root.querySelectorAll('input[data-m$=Curr]:not([disabled])').forEach(i => { i.value = ''; i.dispatchEvent(new Event('input', { bubbles: true })); }) }]),
      import: () => TH.go('#/settings/import?type=meter&period=' + period + '&back=' + encodeURIComponent('#/invoices/batch?step=2&period=' + period + '&buildingId=' + bIds.join(','))), sample: () => { F.download('mau-chi-so-dien-nuoc.csv', F.csv(rows.slice(0, 5).map(r => [r.room.code, period, r.electricPrev, r.electricPrev + 150, r.waterPrev, r.waterPrev + 12]), ['Mã phòng', 'Kỳ', 'Điện cũ', 'Điện mới', 'Nước cũ', 'Nước mới']), 'text/csv'); U.toast('ok', 'Đã tải file mẫu chỉ số'); },
      create: async () => { const ok = await U.confirm({ title: 'Tạo ' + valid.length + ' hóa đơn kỳ ' + F.periodLabel(period) + '?', text: issueLater ? 'Hóa đơn ở trạng thái Nháp; phát hành sau tại danh sách hóa đơn.' : 'Hóa đơn được phát hành ngay và xuất hiện trong công nợ.', ok: 'Tạo hóa đơn' }); if (!ok) return; try { const res = X.createInvoiceDrafts({ period, contractIds: valid.map(r => r.contract.id), services: svcSel, issueNow: !issueLater, key: TH._batchKey || (TH._batchKey = F.uid('batch')) }); TH._batchResult = res; TH._batchKey = null; U.toast(res.duplicate ? 'warn' : 'ok', res.duplicate ? 'Yêu cầu trùng – không tạo thêm' : 'Đã tạo ' + (res.created || []).length + ' hóa đơn'); go({ step: 4 }); } catch (e) { U.toast('err', 'Không tạo được', e.message); } },
      'issue-now': () => { const res = TH._batchResult; const n = X.issueInvoices(res.created.map(i => i.id)); res.created = res.created.map(i => St.get('invoices', i.id)); U.toast('ok', 'Đã phát hành ' + n + ' hóa đơn'); TH.router.replaceQuery(Object.assign({}, q, { issue: 'now' })); TH.router.refresh(); },
      zalo: () => Fm.zaloQuick({ invoiceIds: TH._batchResult.created.map(i => i.id), eventKey: 'reminder', title: 'Gửi hóa đơn vừa phát hành qua Zalo' }),
    });
  }, { menu: 'invoices', permission: 'invoices.prepare', noAutoRefresh: true });

  /* ---------- Chi tiết hóa đơn ---------- */
  TH.router.register('/invoices/:id', (root, p, q) => {
    const inv = St.get('invoices', p.id); if (!inv) { root.innerHTML = U.empty({ title: 'Không tìm thấy hóa đơn' }); return; }
    const t = Q.tenant(inv.tenantId), r = Q.room(inv.roomId), b = Q.building(inv.buildingId), c = Q.contract(inv.contractId), lines = Q.invLines(inv.id), paid = Q.invPaid(inv), rem = Q.invRemaining(inv), over = Q.invOverdue(inv), pays = Q.paymentsOfInvoice(inv.id), rems = Q.invReminders(inv.id), tab = q.tab || 'lines';
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hóa đơn', href: '#/invoices' }, { label: inv.code }]);
    const isDraft = inv.docStatus === 'draft';
    const related = [
      { key: 'tenant', title: 'Thông tin khách thuê', icon: 'user', summary: esc(t.name), meta: esc(t.code) + ' · ' + esc(t.phone), actions: `<a class="link small" href="#/tenants/${t.id}">${I('external-link')} Xem</a>`, body: `<div class="row gap12">${U.avatar(t.name)}<div><b style="color:var(--text)">${esc(t.name)}</b><div class="xs muted">${esc(t.code)}<br>${I('phone')} ${esc(t.phone)}<br>${I('mail')} ${esc(t.email || '-')}</div></div></div>` },
      { key: 'contract', title: 'Thông tin hợp đồng', icon: 'file-text', summary: esc(c.code || '-'), meta: esc(r.code) + ' · ' + esc(b.name), actions: `<a class="link small" href="#/contracts/${c.id}">Xem chi tiết</a>`, body: U.kv([['Mã hợp đồng', esc(c.code || '-')], ['Tòa nhà', esc(b.name)], ['Phòng', esc(r.code)], ['Thời hạn thuê', F.date(c.start) + ' - ' + F.date(c.end)], ['Trạng thái', Q.chip('contract', Q.contractStatus(c))]], 'one') },
      { key: 'accounting-note', title: 'Ghi chú kế toán', icon: 'pencil', summary: inv.accountingNote ? 'Đã có ghi chú' : 'Chưa có ghi chú', meta: inv.accountingNoteAt ? 'Cập nhật ' + F.datetime(inv.accountingNoteAt) : 'Có thể bổ sung khi cần', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-xs', cls: 'btn-outline', act: 'note' }), body: inv.accountingNote ? `<div class="note-box warn" style="display:block">${esc(inv.accountingNote)}</div><div class="xs muted mt8">Cập nhật bởi ${esc(inv.accountingNoteBy || 'Nguyễn Văn Minh')} • ${inv.accountingNoteAt ? F.datetime(inv.accountingNoteAt) : '10/10/2026 14:30'}</div>` : '<div class="muted small">Chưa có ghi chú</div>' },
      { key: 'reminder-status', title: 'Trạng thái nhắc tiền', icon: 'send', summary: over ? 'Đã quá hạn' : rem ? 'Chưa đến hạn' : 'Đã thu đủ', meta: rems.filter(m => ['delivered', 'accepted'].includes(m.status)).length + ' lần đã nhắc', actions: !isDraft && rem > 0 ? U.btn({ label: 'Gửi nhắc tiền', icon: 'send', size: 'btn-xs', cls: 'btn-outline', act: 'remind' }) : '', body: U.kv([['Trạng thái', over ? U.chip('Đã quá hạn', 'red') : rem ? U.chip('Chưa đến hạn', 'blue') : U.chip('Đã thu đủ', 'green')], ['Số lần đã nhắc', rems.filter(m => ['delivered', 'accepted'].includes(m.status)).length + ' lần'], ['Lần nhắc gần nhất', rems.length ? F.datetime(rems.slice().sort((a, z) => F.cmp(z.sentAt || '', a.sentAt || ''))[0].sentAt) : inv.lastReminderAt ? F.datetime(inv.lastReminderAt) : '-'], ['Kênh nhắc', 'Zalo (ZBS Template)'], ['Người thực hiện', rems.length ? esc(Q.userName((St.get('zaloBatches', rems[0].batchId) || {}).createdBy)) : '-']], 'one') + `<a class="link small" href="#/invoices/${inv.id}?tab=reminders">Xem lịch sử nhắc tiền →</a>` }
    ];
    root.innerHTML = `${U.pageHead({ back: '#/invoices', title: esc(inv.code), chips: ' ' + Q.chip('invDoc', inv.docStatus, 'lg') + (isDraft ? '' : ' ' + Q.invPayChip(inv).replace('class="chip', 'class="chip lg')), sub: `${esc(t.name)} • ${esc(r.code)} - ${esc(b.name)} • Kỳ ${F.periodShort(inv.period)}`, acts: [isDraft ? U.btn({ label: 'Phát hành', icon: 'send', cls: 'btn-primary', act: 'issue', disabled: !TH.auth.can('issueInvoice'), title: TH.auth.can('issueInvoice') ? '' : 'Cần vai trò Admin/Kế toán', attrs: { 'data-guide': 'invoice-issue' } }) : U.btn({ label: 'Xác nhận thu tiền', icon: 'dollar', cls: 'btn-primary', act: 'pay', disabled: rem <= 0, title: 'Thu đủ số còn lại kèm minh chứng', attrs: { 'data-guide': 'invoice-pay' } }), !isDraft ? U.btn({ label: 'Gửi nhắc tiền', icon: 'send', cls: 'btn-outline', act: 'remind', disabled: rem <= 0 }) : '', U.btn({ label: 'Tải PDF', icon: 'download', cls: 'btn-outline', act: 'pdf' }), U.iconBtn('more', 'more', 'Thêm', {}, 'bordered')] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tiền', value: F.vnd(inv.total), cap: 'VND', icon: 'dollar', tone: 'amber' })}${U.kpi({ label: 'Đã thu', value: F.vnd(paid), cap: 'VND', icon: 'check-circle', tone: 'green', delta: F.pct(paid, inv.total) })}${U.kpi({ label: 'Còn lại', value: F.vnd(rem), cap: 'VND', icon: 'alert-circle', tone: 'red', valueCls: rem ? 'red' : '', delta: F.pct(rem, inv.total), deltaDir: 'down' })}${U.kpi({ label: 'Hạn thanh toán', value: F.date(inv.dueDate), cap: over ? '<span class="red">Quá hạn ' + Q.invOverdueDays(inv) + ' ngày</span>' : (rem ? 'Còn ' + F.daysUntil(inv.dueDate) + ' ngày' : 'Đã thu đủ'), icon: 'calendar', tone: 'purple', valueCls: 'sm' })}</div>
    ${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'lines', label: 'Chi tiết tính tiền' }, { key: 'payments', label: 'Lịch sử thu', count: pays.length }, { key: 'reminders', label: 'Nhắc tiền', count: rems.length }, { key: 'docs', label: 'Tài liệu' }, { key: 'log', label: 'Lịch sử' }], tab)}
    ${U.relatedStrip({ id: 'invoice-related', items: related, cls: 'mb16' })}<div class="side-stack" id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    const linesCard = U.card({ title: 'Chi tiết các khoản thu', icon: 'list', actions: isDraft ? U.btn({ label: 'Thêm dòng', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'add-line' }) : U.btn({ label: 'Điều chỉnh', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'adjust', disabled: !TH.auth.can('adjustInvoice') }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Khoản mục</th><th>Mô tả</th><th class="num">Số lượng</th><th class="num">Đơn giá (VND)</th><th class="num">Thành tiền (VND)</th></tr></thead><tbody>${lines.map((l, i) => `<tr><td>${i + 1}</td><td><b>${esc(l.item)}</b></td><td>${esc(l.desc)}</td><td class="num">${l.qty}</td><td class="num ${l.unitPrice < 0 ? 'red' : ''}">${F.vnd(l.unitPrice)}</td><td class="num ${l.amount < 0 ? 'red' : ''}">${F.vnd(l.amount)}</td></tr>`).join('')}</tbody></table><div class="sum-box" style="margin:12px 18px;border-radius:10px"><div class="it"><span>Tổng tiền hàng</span><b>${F.vnd(F.sum(lines.filter(l => l.amount > 0), l => l.amount))}</b></div><div class="it"><span>Giảm giá / điều chỉnh</span><b class="${F.sum(lines.filter(l => l.amount < 0), l => l.amount) ? 'red' : ''}">${F.vnd(F.sum(lines.filter(l => l.amount < 0), l => l.amount))}</b></div><div class="it" style="border-top:1px solid var(--primary-100);padding-top:8px"><span class="bold">Tổng cộng</span><b class="blue" style="font-size:20px">${F.vnd(inv.total)}</b></div></div>` });
    const payCard = U.card({ title: 'Lịch sử thanh toán', icon: 'history', bodyCls: 'tight', body: pays.length ? `<table class="tbl compact"><thead><tr><th>#</th><th>Ngày thanh toán</th><th class="num">Số tiền (VND)</th><th>Phương thức</th><th>Người thu</th><th>Ghi chú</th><th>Chứng từ</th></tr></thead><tbody>${pays.map((x, i) => `<tr class="${x.payment.status === 'reversed' ? 'tint-red' : ''}"><td>${i + 1}</td><td>${U.link('#/payments/' + x.payment.id, F.date(x.payment.date))}</td><td class="num">${F.vnd(x.alloc.amount)} ${x.payment.status === 'reversed' ? U.chip('Đã hoàn tác', 'red') : ''}</td><td>${esc(x.payment.method)}</td><td>${esc(Q.userName(x.payment.createdBy))}</td><td>${esc(x.payment.note || '-')}</td><td>${x.payment.evidence ? I('file-text') + ' ' + esc(x.payment.evidence) : '-'}</td></tr>`).join('')}</tbody></table>` : U.empty({ icon: 'file-x', title: 'Chưa có giao dịch thanh toán nào', text: isDraft ? 'Hóa đơn nháp – phát hành trước khi ghi nhận thu tiền.' : 'Hóa đơn này chưa được thanh toán. Xác nhận thu tiền kèm minh chứng để cập nhật trạng thái.', action: isDraft ? '' : U.btn({ label: 'Xác nhận thu tiền', icon: 'dollar', cls: 'btn-primary', act: 'pay' }) }) });
    if (tab === 'lines') body.innerHTML = linesCard + payCard;
    if (tab === 'overview') body.innerHTML = U.card({ title: 'Tổng quan hóa đơn', icon: 'receipt', body: U.kv([['Mã hóa đơn', esc(inv.code)], ['Kỳ', F.periodLabel(inv.period)], ['Ngày phát hành', inv.issueDate ? F.date(inv.issueDate) : '<span class="muted">Chưa phát hành</span>'], ['Hạn thanh toán', F.date(inv.dueDate)], ['Cờ công nợ (BR-07)', Q.invDebtFlag(inv) ? U.chip('Cần xử lý công nợ – phát hành ≥ 5 ngày', 'amber') : U.chip('Chưa đến ngưỡng', 'gray')], ['Trạng thái chứng từ', Q.chip('invDoc', inv.docStatus)], ['Trạng thái thu', isDraft ? '-' : Q.invPayChip(inv)], ['Giá niêm yết / thực tế (BR-06)', F.vnd(c.listPrice) + ' / <b>' + F.vnd(c.price) + '</b>'], ['Người tạo', esc(Q.userName(inv.createdBy))], ['Tạo lúc', F.datetime(inv.createdAt)]]) }) + payCard;
    if (tab === 'payments') body.innerHTML = payCard;
    if (tab === 'reminders') body.innerHTML = U.card({ title: 'Lịch sử nhắc tiền qua Zalo', icon: 'send', sub: 'Gửi thành công không đồng nghĩa khách đã thanh toán (FR-ZAL-05)', bodyCls: 'tight', body: rems.length ? `<table class="tbl compact"><thead><tr><th>Thời gian</th><th>Đợt gửi</th><th>Kênh</th><th>Template</th><th>Trạng thái</th><th>Mã lỗi</th><th></th></tr></thead><tbody>${rems.sort((a, z) => F.cmp(z.sentAt || '', a.sentAt || '')).map(m => { const bt = St.get('zaloBatches', m.batchId) || {}; return `<tr><td>${F.datetime(m.sentAt)}</td><td>${U.link('#/zalo/batches/' + bt.id, bt.code || '-')}</td><td>Zalo</td><td class="mono xs">${esc(m.templateCode)}</td><td>${Q.chip('zmsg', m.status)}</td><td class="red">${esc(m.errorCode || '-')}</td><td>${m.content ? U.actBtn({ icon: 'message', label: 'Nội dung', act: 'msg', attrs: { 'data-id': m.id } }) : ''}</td></tr>`; }).join('')}</tbody></table>` : U.empty({ icon: 'send', title: 'Chưa nhắc tiền cho hóa đơn này', action: rem > 0 && !isDraft ? U.btn({ label: 'Gửi nhắc tiền', icon: 'send', cls: 'btn-primary', act: 'remind' }) : '' }) });
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'invoice' && d.entityId === inv.id); body.innerHTML = U.card({ title: 'Tài liệu', icon: 'folder', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d)).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu', text: 'Bản PDF hóa đơn, biên nhận…' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => x.entityType === 'invoice' && x.entityId === inv.id); body.innerHTML = U.card({ title: 'Lịch sử', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, {
      tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, pay: () => Fm.confirmPayments({ invoiceIds: [inv.id] }), remind: () => Fm.zaloQuick({ invoiceIds: [inv.id], eventKey: over ? 'debt' : 'reminder', title: 'Gửi nhắc tiền hóa đơn ' + inv.code }), pdf: () => pdf(inv), adjust: () => Fm.adjustInvoice(inv), more: (el) => invMenu(el, inv), upload: () => Fm.upload('invoice', inv.id),
      issue: async () => { if (await U.confirm({ title: 'Phát hành hóa đơn ' + inv.code + '?', text: 'Tổng ' + F.vnd(inv.total) + ' đ. Sau phát hành, giá và số lượng được khóa theo kỳ (BR-21); sửa sai phải qua Điều chỉnh.', ok: 'Phát hành' })) { try { X.issueInvoice(inv.id); U.toast('ok', 'Đã phát hành ' + inv.code); } catch (e) { U.toast('err', 'Không phát hành được', e.message); } } },
      note: () => { const m = U.modal({ title: 'Ghi chú kế toán', size: 'sm', body: U.textarea({ name: 'note', value: inv.accountingNote || '', rows: 4 }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { X.updateInvoiceNote(inv.id, m.data().note); m.close(); U.toast('ok', 'Đã lưu ghi chú'); } }); },
      'add-line': () => { const svcs = St.where('services', x => x.status === 'active' && x.method !== 'meter'); const opts = svcs.map(x => ['svc:' + x.id, x.name + ' (' + F.vnd(Q.servicePrice(x.id, inv.buildingId)) + '/' + x.unit + ')']).concat([['PENALTY', 'Phạt (chậm trả / vi phạm)'], ['ADJUSTMENT', 'Điều chỉnh (+/−, cần chứng từ)'], ['OTHER', 'Khoản khác']]); const m = U.modal({ title: 'Thêm dòng hóa đơn (nháp)', size: 'sm', sub: 'Loại dòng §4.14: Tiền phòng · Điện · Nước · Internet · Vệ sinh · Thang máy · Xe · Máy giặt · Điện chung · Phạt · Điều chỉnh · Khoản khác', body: `<div class="form-grid">${U.field({ label: 'Loại dòng', req: true, input: U.select({ name: 'kind', options: opts, attrs: { id: 'al-kind' } }), cls: 'span2' })}${U.field({ label: 'Diễn giải / chứng từ', input: U.input({ name: 'item', placeholder: 'VD: Vệ sinh phòng tháng 10' }), cls: 'span2' })}${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', type: 'number', value: 1 }) })}${U.field({ label: 'Đơn giá', input: U.money({ name: 'unitPrice', attrs: { id: 'al-price' } }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Thêm', cls: 'btn-primary', act: 's' }) }); m.el.querySelector('#al-kind').addEventListener('change', (e) => { const v = e.target.value; if (v.startsWith('svc:')) { const sv = Q.service(v.slice(4)); m.el.querySelector('#al-price').value = F.vnd(Q.servicePrice(sv.id, inv.buildingId)); m.el.querySelector('input[name=item]').value = sv.name + ' ' + F.periodLabel(inv.period).toLowerCase(); } }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); let lineType = 'SERVICE', serviceId = null, unit = '', item = d.item; if (d.kind.startsWith('svc:')) { const sv = Q.service(d.kind.slice(4)); serviceId = sv.id; unit = sv.unit; item = item || sv.name; } else { lineType = d.kind; item = item || Q.label('lineType', d.kind); } X.addInvoiceLine(inv.id, { item, desc: item, qty: d.qty, unitPrice: d.unitPrice, lineType, serviceId, unit }); m.close(); U.toast('ok', 'Đã thêm dòng ' + Q.label('lineType', lineType)); } catch (e) { U.toast('err', 'Không thêm được', e.message); } } }); },
      msg: (el) => { const m = St.get('zaloMessages', el.dataset.id); U.modal({ title: 'Nội dung đã gửi', size: 'sm', body: U.phone(m.content, F.datetime(m.sentAt)) }); },
    });
  }, { menu: 'invoices', permission: 'invoices.view', resource: { type: 'invoice' } });
  /* Phase 2: bộ lọc nâng cao hóa đơn (drawer) – áp vào query của trang danh sách */
  document.addEventListener('click', (e) => { const el = e.target.closest('[data-act="adv-filter"]'); if (!el || el.disabled) return; e.preventDefault(); const q = TH.router.current.query || {}; const m = U.drawer({ title: 'Bộ lọc nâng cao ' + TH.phase.tag(2), sub: 'Lọc theo tòa, khách, khoảng tiền, trạng thái nhắc', body: `<div class="form-grid">${U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: q.buildingId || '', all: 'Tất cả', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]) }) })}${U.field({ label: 'Khách thuê (tên/mã)', input: U.input({ name: 's', value: q.s || '' }) })}${U.field({ label: 'Số tiền từ', input: U.money({ name: 'min', value: q.min || '' }) })}${U.field({ label: 'Đến', input: U.money({ name: 'max', value: q.max || '' }) })}${U.field({ label: 'Đã nhắc Zalo', input: U.select({ name: 'reminded', value: q.reminded || '', all: 'Tất cả', options: [['1', 'Đã nhắc'], ['0', 'Chưa nhắc']] }) })}${U.field({ label: 'Trạng thái thu', input: U.select({ name: 'pay', value: q.pay || '', all: 'Tất cả', options: Object.entries(Q.L.invPay).filter(([k]) => k !== 'overdue').map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Quá hạn', input: U.select({ name: 'overdue', value: q.overdue || '', all: 'Tất cả', options: [['yes', 'Quá hạn'], ['no', 'Chưa quá hạn']] }) })}</div>`, footer: U.btn({ label: 'Xóa lọc', act: 'clear' }) + U.btn({ label: 'Áp dụng', cls: 'btn-primary', act: 'apply' }) }); U.bind(m.el, { clear: () => { m.close(); TH.router.replaceQuery({}); TH.router.refresh(); }, apply: () => { const d = m.data(); m.close(); TH.router.replaceQuery(Object.assign({}, q, { buildingId: d.buildingId, s: d.s, min: d.min || '', max: d.max || '', reminded: d.reminded, pay: d.pay, overdue: d.overdue })); TH.router.refresh(); } }); });
})(window.TH);
