/* Phase 2 – Nhập dữ liệu & tác vụ (Data Jobs): danh sách, chi tiết job, kiểm tra lại, thử lại phần đủ điều kiện */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const jobType = (j) => Q.L.jobType[j.type] || j.typeLabel || j.type;
  const jobRoute = { tenant: '#/settings/import?type=tenant', room: '#/settings/import?type=room', contract: '#/settings/import?type=contract', meter: '#/settings/import?type=meter', invoice: '#/settings/import?type=invoice', statement: '#/finance/statement-import', opening: '#/finance/opening-balance', lead: '#/settings/import?type=lead' };
  const canManage = () => TH.auth.can('dataJobs.manage');
  const jobMenu = (el, j) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => TH.go('#/settings/jobs/' + j.id) }, { label: 'Thử lại phần lỗi', icon: 'refresh-cw', disabled: !canManage() || !(j.lines || []).some(l => ['failed', 'check', 'ready'].includes(l.status)), onClick: () => TH.go('#/settings/jobs/' + j.id) }, { label: 'Tải dòng lỗi', icon: 'download', onClick: () => dlErrors(j) }, '-', { label: 'Hủy (đang chạy)', icon: 'x-circle', danger: true, disabled: !canManage() || j.status !== 'running', onClick: () => { X.cancelJob(j.id); ok('Đã hủy tác vụ'); } }]);
  const dlErrors = (j) => { const bad = (j.lines || []).filter(l => l.status !== 'ok'); F.download(j.code + '-dong-loi.csv', F.csv(bad.map(l => [l.i, l.src, Q.label('jobLine', l.status), l.reason]), ['#', 'Dữ liệu nguồn', 'Kết quả', 'Lý do']), 'text/csv'); ok('Đã tải ' + bad.length + ' dòng lỗi', bad.length ? '' : 'Job lịch sử không lưu chi tiết dòng'); };
  const TEMPLATES = { tenant: [['Họ tên', 'SĐT', 'CCCD', 'Phòng', 'Ngày bắt đầu thuê', 'Zalo']], room: [['Mã tòa', 'Mã phòng', 'Tầng', 'Loại', 'Diện tích', 'Giá']], contract: [['SĐT', 'Phòng', 'Bắt đầu', 'Kết thúc', 'Giá', 'Cọc']], meter: [['Mã phòng', 'Kỳ', 'Điện cũ', 'Điện mới', 'Nước cũ', 'Nước mới']], invoice: [['Mã phòng', 'Kỳ', 'Tiền phòng', 'Tiền điện', 'Tiền nước', 'Dịch vụ khác', 'Mô tả', 'Hạn thanh toán', 'Ghi chú']], statement: () => TH.imp.statementSample(), opening: () => TH.imp.openingSample(), lead: () => TH.imp.leadSample() };

  TH.router.register('/settings/jobs', (root, p, q) => {
    TH.router.crumb([{ label: 'Cấu hình' }, { label: 'Tác vụ dữ liệu' }]);
    X.resumeJobs();
    const f = { s: q.s || '', type: q.type || '', status: q.status || '', createdBy: q.createdBy || '', period: q.period || '' }; const all = St.all('importJobs').map(j => Object.assign({ code: 'IMP-000', progress: 100, ok: j.valid, failed: j.error }, j));
    const rows = all.filter(j => (!f.s || F.norm(j.code + ' ' + j.fileName + ' ' + Q.userName(j.createdBy)).includes(F.norm(f.s))) && (!f.type || j.type === f.type) && (!f.status || j.status === f.status) && (!f.createdBy || j.createdBy === f.createdBy) && (!f.period || F.period(j.createdAt) === f.period)).sort((a, b) => F.cmp(b.updatedAt || b.createdAt, a.updatedAt || a.createdAt));
    const cnt = (s) => all.filter(j => j.status === s).length; const errN = all.filter(j => ['failed', 'needs_check', 'partial'].includes(j.status)).length;
    root.innerHTML = `${U.pageHead({ title: 'Tác vụ dữ liệu', phase: 2, sub: 'Theo dõi các tác vụ import dữ liệu, xử lý nền và kết quả lỗi', acts: [U.btn({ label: 'Tạo tác vụ import', icon: 'plus', cls: 'btn-primary', act: 'add', attrs: { 'data-guide': 'job-add' } }), U.btn({ label: 'Tải template', icon: 'download', cls: 'btn-outline', act: 'tpl' })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tác vụ', value: all.length, cap: 'Tất cả tác vụ import và xử lý', icon: 'file-text', tone: 'blue' })}${U.kpi({ label: 'Đang chạy', value: cnt('running'), cap: 'Đang xử lý trong hệ thống', icon: 'refresh-cw', tone: 'blue' })}${U.kpi({ label: 'Hoàn tất', value: cnt('done'), cap: 'Hoàn thành thành công', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Có lỗi', value: errN, cap: 'Cần kiểm tra và xử lý', icon: 'alert-circle', tone: 'red' })}</div>
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo mã tác vụ, tệp tin, người tạo...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Loại dữ liệu', input: U.select({ name: 'type', value: f.type, all: 'Tất cả', options: Object.entries(Q.L.jobType), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.job).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người tạo', input: U.select({ name: 'createdBy', value: f.createdBy, all: 'Tất cả', options: [...new Set(all.map(j => j.createdBy))].filter(Boolean).map(id => [id, Q.userName(id)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: f.period, all: 'Tất cả kỳ', options: [...new Set(all.map(j => F.period(j.createdAt)))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.relatedStrip({ id: 'jobs-related', cls: 'mb16', items: [
      { key: 'guide', title: 'Hướng dẫn nhập dữ liệu', icon: 'book-open', summary: '6 bước', meta: 'Tải template → upload → mapping → preview → xác nhận → theo dõi', body: `<div class="steps">${[['Tải template', 'Tải file template theo loại dữ liệu (CSV) với đúng định dạng.'], ['Upload file', 'Chọn và tải lên file dữ liệu từ máy tính của bạn.'], ['Mapping dữ liệu', 'Ánh xạ cột trong file với trường dữ liệu của hệ thống.'], ['Preview dữ liệu', 'Xem trước dữ liệu và kiểm tra các lỗi (nếu có).'], ['Xác nhận import', 'Xác nhận và bắt đầu tạo tác vụ xử lý dữ liệu.'], ['Theo dõi kết quả', 'Theo dõi tiến độ, kết quả và xử lý các lỗi phát sinh.']].map(([t, s], i) => `<div class="st"><div class="n" style="background:var(--primary);color:#fff">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` },
      { key: 'notes', title: 'Lưu ý quan trọng', icon: 'info', summary: '5 lưu ý', meta: 'Đúng template · không trống trường bắt buộc · idempotent theo checksum', body: '<ul class="small" style="padding-left:18px;line-height:1.8;margin:0"><li>Sử dụng đúng template do hệ thống cung cấp.</li><li>Đảm bảo dữ liệu đúng định dạng và không để trống các trường bắt buộc.</li><li>Với file lớn, hệ thống sẽ xử lý nền. Bạn có thể thoát trang và quay lại sau.</li><li>Kiểm tra kỹ kết quả và xử lý các bản ghi lỗi (nếu có).</li><li>Import idempotent theo checksum file – chạy lại không tạo trùng.</li></ul><div class="tr mt8"><a class="link small" data-act="open-guide" data-flow="F13">Xem hướng dẫn chi tiết →</a></div>' }
    ] })}
    ${U.card({ title: 'Danh sách tác vụ', icon: 'list', body: null, id: 'jt', attrs: 'data-guide="jobs-table"' })}`;
    U.table(root.querySelector('#jt'), { rows, unit: 'tác vụ', selectable: true, colPrefsKey: 'jobs', cols: [{ key: 'code', label: 'Mã tác vụ', sortable: true, render: j => U.link('#/settings/jobs/' + j.id, esc(j.code), 'bold') }, { key: 'type', label: 'Loại dữ liệu', sortable: true, render: j => esc(jobType(j)) }, { key: 'fileName', label: 'Tệp nguồn', sortable: true, render: j => `<span class="small">${esc(j.fileName)}</span>` }, { key: 'by', label: 'Người tạo', render: j => esc(Q.userName(j.createdBy)) }, { key: 'progress', label: 'Tiến độ', render: j => `<span data-job-progress="${j.id}">${U.progress(Q.jobProgress(j), j.status === 'failed' ? 'red' : j.status === 'done' ? 'green' : '')}</span>` }, { key: 'ok', label: 'Thành công', num: true, render: j => `<span class="green">${j.ok != null ? j.ok : j.valid}</span>` }, { key: 'failed', label: 'Lỗi', num: true, render: j => `<span class="${(j.failed || j.error) ? 'red bold' : ''}">${j.failed != null ? j.failed : j.error}</span>` }, { key: 'status', label: 'Trạng thái', sortable: true, render: j => Q.chip('job', j.status) }, { key: 'upd', label: 'Cập nhật lần cuối', sortable: true, sortVal: j => j.updatedAt || j.createdAt, render: j => F.datetime(j.updatedAt || j.createdAt) }, { key: 'actions', label: 'Thao tác', render: j => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': j.id } }), U.moreBtn(j.id)]), hideable: false }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { 'open-guide': (el) => TH.guide && TH.guide.open(el.dataset.flow), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (el) => TH.go('#/settings/jobs/' + el.dataset.id), more: (el) => jobMenu(el, St.get('importJobs', el.dataset.id)), add: (el) => U.menu(el, [{ header: 'Chọn loại dữ liệu' }, ...Object.entries(Q.L.jobType).map(([k, l]) => ({ label: l, icon: { statement: 'database', opening: 'file-spreadsheet', lead: 'user' }[k] || 'upload', onClick: () => TH.go(jobRoute[k]) }))]), tpl: (el) => U.menu(el, [{ header: 'Tải template theo loại' }, ...Object.entries(Q.L.jobType).map(([k, l]) => ({ label: l + ' (.csv)', icon: 'download', onClick: () => { const t = TEMPLATES[k]; const rows = typeof t === 'function' ? t() : t; F.download('template-' + k + '.csv', F.csv(rows.slice(1), rows[0]), 'text/csv'); ok('Đã tải template ' + l, 'CSV (bản demo offline không kèm .xlsx)'); } }))]) });
  }, { menu: 'jobs', permission: 'dataJobs.view', phase: 2, scopeKey: 'jobs', noAutoRefresh: 'timer' });

  TH.router.register('/settings/jobs/:id', (root, p, q) => {
    const j = St.get('importJobs', p.id); if (!j) { root.innerHTML = U.empty({ title: 'Không tìm thấy tác vụ' }); return; }
    TH.router.crumb([{ label: 'Cấu hình' }, { label: 'Tác vụ dữ liệu', href: '#/settings/jobs' }, { label: 'Chi tiết tác vụ' }]); X.resumeJobs();
    const lines = j.lines || []; const total = j.rows || lines.length; const okN = j.ok != null ? j.ok : j.valid; const failN = j.failed != null ? j.failed : j.error; const pct = Q.jobProgress(j);
    const f = { s: q.s || '', st: q.st || '' }; const shown = lines.filter(l => (!f.st || l.status === f.st) && (!f.s || F.norm(l.src + ' ' + l.reason).includes(F.norm(f.s))));
    const readyN = lines.filter(l => l.status === 'ready').length; const badN = lines.filter(l => ['failed', 'check'].includes(l.status)).length;
    root.innerHTML = `<a class="link small" href="#/settings/jobs">${I('arrow-left')} Quay lại danh sách</a>
    ${U.pageHead({ title: 'Job ' + esc(j.code), phase: 2, chips: ' ' + Q.chip('job', j.status, 'lg'), sub: `<div class="lead-meta"><span>${I('file-text')} <b>Import ${esc(jobType(j).toLowerCase())}</b></span><span>${I('building')} ${esc(j.buildingLabel || 'Tất cả tòa nhà')}</span><span>${I('calendar')} Kỳ ${F.periodShort(j.period || F.period(j.createdAt))}</span></div><div class="lead-meta"><span>${I('user')} ${esc(Q.userName(j.createdBy))}</span><span>${I('clock')} Tạo lúc ${F.datetime(j.createdAt)}</span></div>`, acts: [U.btn({ label: 'Tải dòng lỗi', icon: 'download', cls: 'btn-outline', act: 'dl-err' }), U.btn({ label: 'Kiểm tra lại', icon: 'refresh-cw', cls: 'btn-outline', act: 'recheck', disabled: !canManage() || !badN, title: badN ? 'Re-validate ' + badN + ' dòng lỗi/cần kiểm tra với dữ liệu hiện tại' : 'Không có dòng lỗi', attrs: { 'data-guide': 'job-recheck' } }), U.btn({ label: 'Thử lại phần đủ điều kiện' + (readyN ? ' (' + readyN + ')' : ''), icon: 'play', cls: 'btn-primary', act: 'retry', disabled: !canManage() || !readyN, title: readyN ? '' : 'Bấm Kiểm tra lại trước – chỉ dòng đã hợp lệ mới được thử lại', attrs: { 'data-guide': 'job-retry' } })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng dòng', value: F.vnd(total), cap: 'Tổng số dòng trong file', icon: 'file-text', tone: 'blue' })}${U.kpi({ label: 'Thành công', value: F.vnd(okN), cap: 'Đã import thành công', icon: 'check-circle', tone: 'green', delta: F.pct(okN, total) })}${U.kpi({ label: 'Lỗi / Bỏ qua', value: F.vnd(total - okN), cap: 'Bao gồm dòng lỗi và bỏ qua', icon: 'x-circle', tone: 'red', delta: F.pct(total - okN, total), deltaDir: 'down' })}${U.kpi({ label: 'Tiến độ xử lý', value: pct + '%', cap: 'Đã xử lý ' + F.vnd(Math.round(total * pct / 100)) + ' / ' + F.vnd(total) + ' dòng', icon: 'pie-chart', tone: 'purple', bar: pct })}</div>
    ${(() => { const at = (j.attempts || []).slice().reverse(); return U.relatedStrip({ id: 'job-related', cls: 'mb16', items: [
      { key: 'attempts', title: 'Lịch sử lần thử', icon: 'history', summary: at.length ? at.length + ' lần thử ' + Q.chip('job', at[0].status || 'done') : 'Chưa có lần thử', meta: at.length ? 'Gần nhất #' + at[0].n + ' · ' + F.datetime(at[0].at) + ' · ' + F.vnd(at[0].ok) + ' thành công / ' + F.vnd(at[0].failed) + ' lỗi' : '', body: at.map(a => `<div class="tl-icon" style="align-items:stretch"><div class="ic ${a.status === 'done' ? 'green' : a.status === 'failed' ? 'red' : 'blue'}">#${a.n}</div><div class="grow"><div class="row between"><span class="chip blue">#${a.n}</span>${Q.chip('job', a.status || 'done')}</div><div class="xs muted mt4">${F.datetime(a.at)}<br>Bởi ${esc(Q.userName(a.by || j.createdBy))}</div><div class="mt8" style="background:var(--gray-bg);border-radius:8px;padding:8px 10px">${U.kv([['Tổng dòng', F.vnd(a.total)], ['Thành công', F.vnd(a.ok)], ['Lỗi / Bỏ qua', `<span class="red">${F.vnd(a.failed)}</span>`]])}</div>${a.note ? `<div class="note-box ${a.status === 'failed' ? 'danger' : 'info'} mt8" style="margin-bottom:0"><div class="small">${esc(a.note)}</div></div>` : ''}</div></div>`).join('') || '<div class="muted small">Chưa có lần thử</div>' }
    ] }); })()}
    <div class="side-stack">${U.card({ title: 'Thông tin đầu vào', icon: 'file-text', actions: U.btn({ label: 'Tải file', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'dl-file' }), body: `<div class="grid grid-4" style="gap:14px">${[['Tên file', `${I('file-text')} <b class="blue">${esc(j.fileName)}</b> <span class="muted small">(${esc(j.fileSize || '-')})</span>`], ['Loại file', /\.xlsx?$/i.test(j.fileName) ? 'Excel (.xlsx)' : 'CSV (UTF-8)'], ['Ngày upload', F.datetime(j.uploadedAt || j.createdAt)], ['Người upload', esc(Q.userName(j.createdBy))], ['Nguồn dữ liệu', 'Từ máy tính cá nhân'], ['Ghi chú', esc(j.note || '-')]].map(([k, v]) => `<div><div class="xs muted">${k}</div><div class="mt4 small">${v}</div></div>`).join('')}</div>` })}
      ${U.card({ title: 'Thiết lập mapping & xử lý', icon: 'settings', body: `<div class="grid grid-2">${U.kv([['Mẫu mapping', esc(j.mappingTemplate || 'Mẫu tiêu chuẩn - ' + jobType(j))], ['Sheet dữ liệu', esc(j.sheet || 'Sheet1')], ['Dòng bắt đầu đọc', j.startRow || 2], ['Xử lý dòng trùng', esc(j.dupPolicy || 'Bỏ qua (giữ bản ghi cũ)')], ['Cập nhật nếu tồn tại', esc(j.updateIfExists || 'Không')]], 'one')}<div><div class="small muted mb4">Cột mapping</div><div class="check-list mb12">${(j.mapping || []).map(m => `<div class="it">${I('check-circle', 'green')}<span>${esc(m)}</span></div>`).join('') || '<span class="muted small">-</span>'}</div><div class="small muted mb4">Quy tắc validate</div><div class="check-list">${(j.rules || []).map(m => `<div class="it">${I('check-circle', 'green')}<span>${esc(m)}</span></div>`).join('') || '<span class="muted small">-</span>'}</div></div></div>` })}
      ${U.card({ title: `Kết quả xử lý từng dòng (${F.vnd(lines.length)} dòng)`, icon: 'list', actions: `<div class="row">${U.input({ name: 's', value: f.s, placeholder: 'Tìm kiếm theo mã phòng, dữ liệu nguồn…', icon: 'search', cls: 'sm', attrs: { id: 'ls', style: 'width:230px' } })}${U.select({ name: 'st', value: f.st, all: 'Tất cả kết quả', options: [['ok', 'Thành công'], ['failed', 'Thất bại'], ['check', 'Cần kiểm tra'], ['ready', 'Đủ điều kiện thử lại'], ['skipped', 'Bỏ qua']], cls: 'sm', attrs: { 'data-on': 'st', style: 'width:auto' } })}${U.btn({ label: 'Tải xuống', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'dl-lines' })}</div>`, body: null, id: 'lt' })}</div>`;
    U.table(root.querySelector('#lt'), { rows: shown, unit: 'dòng', selectable: true, rowKey: l => String(l.i), rowClass: l => l.status === 'failed' ? 'tint-red' : l.status === 'check' ? 'tint-amber' : '', cols: [{ key: 'i', label: 'STT', width: '50px' }, { key: 'src', label: 'Dữ liệu nguồn', render: l => `<span class="mono small">${esc(l.src)}</span>` }, { key: 'status', label: 'Kết quả', sortable: true, render: l => l.status === 'ready' ? U.chip('Đủ điều kiện thử lại', 'blue') : Q.chip('jobLine', l.status) }, { key: 'reason', label: 'Lý do lỗi / Thông báo', render: l => esc(l.reason || '-') }, { key: 'link', label: 'Liên kết bản ghi', render: l => l.link ? `<a class="link" href="${l.link}">${I('external-link')} ${l.link.startsWith('#/rooms') ? 'Xem phòng' : l.link.startsWith('#/payments') ? 'Xem khoản thu' : l.link.startsWith('#/tenants') ? 'Xem khách' : l.link.startsWith('#/invoices') ? 'Xem hóa đơn' : 'Xem bản ghi'}</a>` : (l.roomId ? `<a class="link" href="#/rooms/${l.roomId}">${I('external-link')} Xem phòng</a>` : '-') }, { key: 'actions', label: 'Hành động', render: l => U.iconBtn('more', 'lmore', 'Thao tác', { 'data-i': l.i }), hideable: false }], empty: U.empty({ icon: 'database', title: 'Job lịch sử – không lưu chi tiết từng dòng', text: 'Các tác vụ tạo mới trong bản demo sẽ có kết quả từng dòng.' }) });
    root.querySelector('#ls').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.onChange(root, { st: (el) => { TH.router.replaceQuery(Object.assign({}, f, { st: el.value })); TH.router.refresh(); } });
    U.bind(root, {
      'dl-err': () => dlErrors(j), 'dl-lines': () => { F.download(j.code + '-ket-qua.csv', F.csv(lines.map(l => [l.i, l.src, Q.label('jobLine', l.status), l.reason]), ['#', 'Dữ liệu nguồn', 'Kết quả', 'Lý do']), 'text/csv'); ok('Đã tải kết quả'); }, 'dl-file': () => { F.download(j.fileName.replace(/\.xlsx?$/i, '.csv'), F.csv(lines.slice(0, 200).map(l => Object.values(l.data || {})), Object.keys((lines[0] || {}).data || { src: 'Dữ liệu' })), 'text/csv'); ok('Đã tải file nguồn (CSV)'); },
      recheck: () => { const n = X.recheckJob(j.id); ok('Đã kiểm tra lại', n ? n + ' dòng đổi trạng thái – dòng "Đủ điều kiện thử lại" có thể commit' : 'Không có thay đổi – chỉnh dữ liệu nguồn hoặc tạo bản ghi thiếu (phòng/hóa đơn) rồi kiểm tra lại'); },
      retry: async () => { if (await U.confirm({ title: 'Thử lại ' + readyN + ' dòng đủ điều kiện?', text: 'Chỉ commit các dòng đã hợp lệ sau Kiểm tra lại; idempotent theo hash dòng – không tạo trùng. Ghi thêm lần thử mới vào lịch sử.', ok: 'Thử lại' })) { try { const r = X.retryJob(j.id); ok('Thử lại xong: ' + r.ok + ' thành công, ' + r.failed + ' lỗi'); } catch (e) { U.toast('err', 'Không thử lại được', e.message); } } },
      lmore: (el) => { const l = lines.find(x => x.i === Number(el.dataset.i)); U.menu(el, [l.link || l.roomId ? { label: 'Xem bản ghi', icon: 'external-link', onClick: () => TH.go(l.link || '#/rooms/' + l.roomId) } : { label: 'Chưa có bản ghi liên kết', icon: 'info', disabled: true }, { label: 'Sửa dữ liệu nguồn', icon: 'pencil', disabled: !canManage() || l.status === 'ok', onClick: () => { const m = U.modal({ title: 'Sửa dữ liệu nguồn dòng #' + l.i, size: 'sm', body: `<div class="col gap12">${Object.entries(l.data || {}).map(([k, v]) => U.field({ label: k, input: U.input({ name: k, value: v == null ? '' : v }) })).join('')}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu & kiểm tra lại', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { X.editJobLine(j.id, l.i, m.data()); X.recheckJob(j.id); m.close(); ok('Đã sửa dòng #' + l.i); } }); } }, { label: 'Bỏ qua dòng', icon: 'minus-circle', disabled: l.status === 'ok' || l.status === 'skipped', onClick: () => { X.skipJobLine(j.id, l.i); ok('Đã bỏ qua dòng #' + l.i); } }]); },
    });
  }, { menu: 'jobs', permission: 'dataJobs.view', phase: 2, scopeKey: 'jobs', resource: { type: 'importJob' } });
  /* Job đang chạy: cập nhật thanh tiến độ tại chỗ (danh sách không refresh để giữ ô tìm kiếm); job xong → render lại */
  St.on((what, d) => { if (what !== 'change' || !d || d.source !== 'timer') return; const cur = TH.router.current; if (!cur || cur.path !== '/settings/jobs') return; let finished = false; document.querySelectorAll('[data-job-progress]').forEach(el => { const j = St.get('importJobs', el.dataset.jobProgress); if (!j) return; if (j.status !== 'running') finished = true; el.innerHTML = U.progress(Q.jobProgress(j), j.status === 'failed' ? 'red' : j.status === 'done' ? 'green' : ''); }); if (finished) TH.router.refresh(); });
})(window.TH);
