(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const periodCode = (period = F.today().slice(0, 7)) => String(period || F.today().slice(0, 7)).replace('-', '');
  const onboardingState = (landlord = null, step = 1) => ({
    at: Date.now(), step, landlordId: landlord ? landlord.id : '',
    landlord: landlord ? { id: landlord.id, type: landlord.type || 'person', name: landlord.name || '', phone: landlord.phone || '', email: landlord.email || '', taxCode: landlord.taxCode || '', bankAccount: landlord.bankAccount || '', address: landlord.address || '', cycleMonths: Number(landlord.cycleMonths) || 3, status: landlord.status === 'paused' ? 'paused' : 'active', managerId: landlord.managerId || (TH.auth.user() || {}).id } : { type: 'person', name: '', phone: '', email: '', taxCode: '', bankAccount: '', address: '', cycleMonths: 3, status: 'active', managerId: (TH.auth.user() || {}).id },
    selectedBuildingIds: [], buildings: [], areas: [], rooms: [], noContract: false,
    contract: { mode: '', signedDate: F.today(), type: 'Hợp đồng thuê tòa nhà', start: F.today(), end: F.addDays(F.addMonths(F.today(), 36), -1), rent: '', deposit: '', priceHoldMonths: 24, cycleMonths: Number((landlord || {}).cycleMonths) || 3, note: '' }
  });
  const openOnboarding = (landlord = null, step = 1) => { TH._wz = TH._wz || {}; TH._wz.landlordOnboarding = onboardingState(landlord, step); TH.go('#/landlords/new' + (landlord ? '?landlordId=' + encodeURIComponent(landlord.id) : '')); };
  const llMenu = (btn, l) => { const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/landlords/' + l.id) }]; if (TH.auth.can('landlords.manage')) items.push({ label: 'Sửa', icon: 'pencil', onClick: () => Fm.landlord(l) }, { label: 'Thêm HĐ đầu vào', icon: 'file-plus', onClick: () => Fm.landlordContract(l.id) }, '-', l.status === 'paused' ? { label: 'Kích hoạt lại', icon: 'check', onClick: () => { X.setLandlordStatus(l.id, 'active'); U.toast('ok', 'Đã kích hoạt'); } } : { label: 'Tạm ngừng hợp tác', icon: 'minus-circle', danger: true, onClick: () => { X.setLandlordStatus(l.id, 'paused'); U.toast('ok', 'Đã tạm ngừng'); } }); U.menu(btn, items); };
  TH.router.register('/landlords', (root, p, q) => {
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Chủ nhà & đối tác' }]);
    const f = { s: q.s || '', status: q.status || '', cycle: q.cycle || '', buildingId: q.buildingId || '', managerId: q.managerId || '', upcoming: q.upcoming || '' };
    const all = St.all('landlords');
    const rows = all.filter(l => (!f.s || F.norm(l.name + l.code + l.phone + l.email).includes(F.norm(f.s))) && (!f.status || Q.landlordStatus(l) === f.status) && (!f.cycle || String(l.cycleMonths) === f.cycle) && (!f.buildingId || l.buildingIds.includes(f.buildingId)) && (!f.managerId || l.managerId === f.managerId) && (!f.upcoming || Q.upcomingLandlordPayments(30).some(p => p.landlordId === l.id)));
    const lcs = St.all('landlordContracts'); const upcoming = Q.upcomingLandlordPayments(30); const dueMonth = St.where('landlordPayments', x => x.status !== 'paid' && F.period(x.dueDate) === St.state.meta.period);
    const missingDocs = all.filter(l => St.where('documents', d => d.entityType === 'landlord' && d.entityId === l.id).length < 4).length;
    root.innerHTML = `${U.pageHead({ title: 'Chủ nhà & đối tác', sub: 'Quản lý chủ nhà cho thuê đầu vào, hợp đồng và lịch thanh toán.', acts: [U.btn({ label: 'Thêm chủ nhà', icon: 'plus', cls: 'btn-primary', act: 'add' }), U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã, tên chủ nhà, SĐT, email...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.landlord).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Chu kỳ trả', input: U.select({ name: 'cycle', value: f.cycle, all: 'Tất cả chu kỳ', options: [[3, '3 tháng'], [4, '4 tháng'], [6, '6 tháng']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Khu vực / Tòa', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả khu vực', options: St.all('buildings').map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả nhân viên', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng chủ nhà', value: all.length, cap: 'Tổng số chủ nhà & đối tác', icon: 'users', tone: 'green' })}${U.kpi({ label: 'Hợp đồng hiệu lực', value: lcs.filter(c => Q.lcStatus(c) !== 'ended').length, cap: lcs.filter(c => Q.lcStatus(c) === 'expiring').length + ' sắp hết hạn (≤ 90 ngày)', icon: 'file-text', tone: 'blue' })}${U.kpi({ label: 'Đến kỳ trả trong tháng', value: dueMonth.length, cap: 'Tổng ' + F.vnd(F.sum(dueMonth, x => x.amount)) + ' VND', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Hồ sơ cần bổ sung', value: missingDocs, cap: 'Thiếu giấy tờ hoặc thông tin', icon: 'alert-triangle', tone: 'red' })}</div>
    ${f.upcoming ? U.note('info', 'Đang lọc chủ nhà có kỳ thanh toán trong 30 ngày tới', '<a class="link" href="#/landlords">Bỏ lọc</a>') + '<div class="mb16"></div>' : ''}
    ${U.relatedStrip({ id: 'landlord-list-related', cls: 'mb16', items: [{ key: 'upcoming-payments', title: 'Kỳ thanh toán sắp tới', icon: 'calendar-clock', summary: upcoming.length + ' kỳ trong 30 ngày', meta: 'Tổng ' + F.vnd(F.sum(upcoming, x => x.amount)) + ' VND', actions: `<a class="link small" href="#/landlords?upcoming=1">Xem tất cả →</a>`, body: (upcoming.length ? `<div class="up-list">${upcoming.slice(0, 6).map(x => { const l = St.get('landlords', x.landlordId) || {}; return `<div class="up-it">${U.avatar(l.name, 'sm')}<div><b>${esc(l.name)}</b><small>${esc(Q.building(x.buildingId).name)} · ${F.date(x.dueDate)}</small></div><div class="amt"><b>${F.vnd(x.amount)}</b><small class="red">Còn ${F.daysUntil(x.dueDate)} ngày</small></div></div>`; }).join('')}</div>` : U.empty({ title: 'Không có kỳ đến hạn trong 30 ngày' })) + U.note('info', 'Lưu ý', 'Kiểm tra và chuẩn bị thanh toán đúng hạn để duy trì quan hệ tốt với chủ nhà.') }] })}
    ${U.card({ title: `Danh sách chủ nhà & đối tác <span class="muted" style="font-weight:400">(${rows.length})</span>`, actions: U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', act: 'cols' }), body: null, id: 'tbl-card' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const cols = [
      { key: 'code', label: 'Mã', sortable: true, render: l => U.link('#/landlords/' + l.id, esc(l.code), 'bold') }, { key: 'name', label: 'Chủ nhà / Đối tác', sortable: true, render: l => `<span class="row">${U.avatar(l.name, 'sm')}<b>${esc(l.name)}</b></span>` },
      { key: 'contact', label: 'Liên hệ', render: l => U.cell2(`<span class="blue">${esc(l.phone)}</span>`, esc(l.email)) },
      { key: 'b', label: 'Số tòa', render: l => l.buildingIds.map(id => esc(Q.building(id).name)).join(', ') || '-' },
      { key: 'lc', label: 'Hợp đồng hiệu lực', render: l => { const c = Q.landlordContracts(l.id).find(x => Q.lcStatus(x) !== 'ended'); return c ? U.cell2(F.date(c.start) + ' - ' + F.date(c.end), Q.chip('lcontract', Q.lcStatus(c))) : (l.buildingIds || []).length ? U.chip('Chưa có HĐ', 'red') : '-'; } },
      { key: 'next', label: 'Lịch trả gần nhất', render: l => { const ps = Q.landlordPayments(l.id).filter(x => x.status !== 'paid' && x.dueDate >= F.today()); return ps[0] ? F.date(ps[0].dueDate) : '-'; } },
      { key: 'cycle', label: 'Chu kỳ trả', render: l => U.chip(l.cycleMonths + ' tháng', 'blue') }, { key: 'status', label: 'Trạng thái', sortable: true, sortVal: l => Q.landlordStatus(l), render: l => Q.chip('landlord', Q.landlordStatus(l)) },
      { key: 'actions', label: 'Thao tác', render: l => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': l.id } }), U.moreBtn(l.id)]) }];
    const tbl = U.table(wrap, { rows, cols, selectable: true, unit: 'chủ nhà', colPrefsKey: 'landlords' });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { add: () => openOnboarding(), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, cols: (b) => U.columnMenu(b, tbl, cols), view: (b) => TH.go('#/landlords/' + b.dataset.id), more: (b) => llMenu(b, St.get('landlords', b.dataset.id)), export: () => { F.download('chu-nha.csv', F.csv(rows.map(l => [l.code, l.name, l.phone, l.email, l.buildingIds.map(id => Q.building(id).name).join('; '), l.cycleMonths, Q.label('landlord', Q.landlordStatus(l))]), ['Mã', 'Tên', 'SĐT', 'Email', 'Tòa', 'Chu kỳ', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất danh sách'); } });
  }, { menu: 'landlords', permission: 'landlords.view' });

  TH.router.register('/landlords/new', (root, p, q) => {
    TH._wz = TH._wz || {};
    const requestedLandlord = q.landlordId ? St.get('landlords', q.landlordId) : null;
    let w = TH._wz.landlordOnboarding;
    if (!w || (q.landlordId || '') !== (w.landlordId || '')) w = TH._wz.landlordOnboarding = onboardingState(requestedLandlord, requestedLandlord ? 2 : 1);
    w.at = Date.now(); w.step = Math.max(1, Math.min(4, Number(w.step) || 1));
    if (w.noContract && w.step === 3) w.step = 4; // không có tòa → không có bước Phòng
    const step = w.step; const editing = !!w.landlordId;
    const STEPS = [{ title: 'Chủ nhà', sub: 'Thông tin liên hệ' }, { title: 'Hợp đồng & tòa nhà', sub: 'HĐ đầu vào và tòa thuộc HĐ' }, { title: 'Phòng', sub: 'Sinh danh sách phòng' }, { title: 'Xác nhận', sub: 'Kiểm tra và lưu' }];
    const managers = Q.managers().map(u => [u.id, u.name]);
    const persistedAreas = Q.areas();
    const areaName = ref => ((w.areas || []).find(a => a.ref === ref) || St.get('areas', ref) || {}).name || '-';
    const areaOptions = () => [...persistedAreas.map(a => [a.id, a.name]), ...(w.areas || []).map(a => [a.ref, a.name + ' (mới)'])];
    const allBuildings = St.where('buildings', b => !b.stub);
    const selectedRefs = () => [...(w.selectedBuildingIds || []).map(id => 'existing:' + id), ...(w.buildings || []).map(b => b.ref)];
    const refBuilding = ref => String(ref).startsWith('existing:') ? St.get('buildings', String(ref).slice(9)) : (w.buildings || []).find(x => x.ref === ref);
    const refLabel = ref => { const b = refBuilding(ref); if (!b) return '-'; return (b.code ? b.code + ' · ' : '') + (b.name || 'Tòa mới chưa đặt tên'); };
    const refPrefix = ref => { const b = refBuilding(ref) || {}; const p = String(b.prefix || '').trim(); if (/^[A-Za-z]/.test(p)) return p.slice(0, 1).toUpperCase(); const seg = String(b.code || '').split('-')[1] || ''; if (/^[A-Za-z]/.test(seg)) return seg[0].toUpperCase(); const n = F.norm(String(b.name || '').replace(/^tòa\s+/i, '')).replace(/[^a-z]/g, ''); return (n[0] || 'x').toUpperCase(); };
    const selectedCount = () => (w.selectedBuildingIds || []).length + (w.buildings || []).length;
    const existingLcs = editing ? Q.landlordContracts(w.landlordId).filter(c => Q.lcStatus(c) !== 'ended') : [];
    const contractMode = () => { if (w.noContract) return 'none'; if (!w.contract.mode && existingLcs.length) return 'existing:' + existingLcs[0].id; if (String(w.contract.mode || '').startsWith('existing:') && existingLcs.some(c => 'existing:' + c.id === w.contract.mode)) return w.contract.mode; return 'new'; };
    const roomSpecOf = ref => (w.rooms || []).find(r => r.ref === ref);
    const roomCount = s => s && !s.skip ? Math.max(0, (Number(s.floorTo) || 0) - (Number(s.floorFrom) || 1) + 1) * (Number(s.perFloor) || 0) : 0;
    const totalRooms = () => selectedRefs().reduce((n, ref) => n + roomCount(roomSpecOf(ref)), 0);
    const schedulePreview = () => contractMode() === 'new' && w.contract.start && w.contract.end ? Q.landlordSchedulePreview({ start: w.contract.start, end: w.contract.end, rent: w.contract.rent, cycleMonths: w.contract.cycleMonths }) : [];
    // Đồng bộ spec phòng theo tòa đang chọn (tòa có sẵn đã có phòng → không sinh)
    const ensureRoomSpecs = () => {
      const refs = selectedRefs(); w.rooms = (w.rooms || []).filter(r => refs.includes(r.ref));
      refs.forEach(ref => { if (roomSpecOf(ref)) return; const b = refBuilding(ref) || {}; const hasRooms = b.id && Q.roomsOf(b.id).length > 0; w.rooms.push({ ref, floorFrom: 1, floorTo: Number(b.floors) || 1, perFloor: Number(b.perFloor) || 4, type: 'Phòng đơn', area: 25, price: 5000000, skip: !!hasRooms, locked: !!hasRooms }); });
    };

    const readLandlord = (validate = false) => {
      const form = root.querySelector('#onboard-landlord'); if (form) Object.assign(w.landlord, U.formData(form));
      w.landlord.cycleMonths = Number(w.landlord.cycleMonths) || 3;
      if (!validate || !form) return true;
      const errs = {}; if (!String(w.landlord.name || '').trim()) errs.name = 'Nhập tên chủ nhà / đối tác'; if (!String(w.landlord.phone || '').trim()) errs.phone = 'Nhập số điện thoại'; U.setErrors(form, errs);
      return !Object.keys(errs).length;
    };
    const readBuildings = () => {
      w.selectedBuildingIds = [...root.querySelectorAll('[data-existing-building]:checked')].map(el => el.dataset.existingBuilding);
      root.querySelectorAll('[data-new-building]').forEach(card => { const b = (w.buildings || []).find(x => x.ref === card.dataset.newBuilding); if (b) Object.assign(b, U.formData(card)); });
    };
    const readContract = () => { const form = root.querySelector('#onboard-contract'); if (!form) return; const d = U.formData(form); if (d.contractMode !== undefined) w.contract.mode = d.contractMode; delete d.contractMode; Object.assign(w.contract, d); };
    const readStep2 = (validate = false) => {
      const nc = root.querySelector('[name=noContract]'); if (nc) w.noContract = nc.checked;
      readContract(); readBuildings();
      if (!validate) return true;
      if (w.noContract) { if (!editing) return true; }
      let ok = true;
      root.querySelectorAll('[data-new-building]').forEach(card => {
        const b = (w.buildings || []).find(x => x.ref === card.dataset.newBuilding); const errs = {};
        if (!String(b.name || '').trim()) errs.name = 'Nhập tên tòa'; if (!String(b.address || '').trim()) errs.address = 'Nhập địa chỉ'; if (!b.areaRef) errs.areaRef = 'Chọn Khu nhà quản lý'; U.setErrors(card, errs); if (Object.keys(errs).length) ok = false;
      });
      const codes = (w.buildings || []).map(b => String(b.code || '').trim()).filter(Boolean); const duplicateDraft = codes.find((x, i) => codes.indexOf(x) !== i); const duplicateStored = codes.find(code => !!St.byCode('buildings', code));
      if (duplicateDraft || duplicateStored) { U.toast('err', 'Mã tòa bị trùng', duplicateDraft || duplicateStored); ok = false; }
      if (!selectedCount()) { U.toast('warn', 'Chưa có tòa nhà', editing ? 'Chọn hoặc khai báo ít nhất một tòa để bổ sung.' : 'Chọn/thêm ít nhất một tòa, hoặc tick "Chưa ký hợp đồng" để chỉ lưu hồ sơ chủ nhà.'); ok = false; }
      if (contractMode() === 'new') {
        const form = root.querySelector('#onboard-contract'); const errs = {};
        if (!w.contract.start) errs.start = 'Chọn ngày bắt đầu'; if (!w.contract.end) errs.end = 'Chọn ngày kết thúc'; else if (w.contract.start && w.contract.end <= w.contract.start) errs.end = 'Ngày kết thúc phải sau ngày bắt đầu'; if (!(F.num(w.contract.rent) > 0)) errs.rent = 'Nhập giá thuê lớn hơn 0';
        if (form) U.setErrors(form, errs); if (Object.keys(errs).length) ok = false;
      }
      return ok;
    };
    const readRooms = (validate = false) => {
      root.querySelectorAll('[data-room-spec]').forEach(card => { const s = roomSpecOf(card.dataset.roomSpec); if (s) Object.assign(s, U.formData(card)); });
      if (!validate) return true;
      let ok = true;
      root.querySelectorAll('[data-room-spec]').forEach(card => { const s = roomSpecOf(card.dataset.roomSpec); if (!s || s.skip) return; const errs = {}; if (!(Number(s.floorFrom) >= 1)) errs.floorFrom = 'Từ tầng ≥ 1'; if (!(Number(s.floorTo) >= Number(s.floorFrom))) errs.floorTo = 'Đến tầng ≥ từ tầng'; if (!(Number(s.perFloor) >= 1 && Number(s.perFloor) <= 20)) errs.perFloor = '1–20 phòng / tầng'; if (!(F.num(s.price) > 0)) errs.price = 'Nhập giá tham chiếu'; U.setErrors(card, errs); if (Object.keys(errs).length) ok = false; });
      return ok;
    };
    const keepCurrentStep = () => { if (step === 1) readLandlord(false); else if (step === 2) readStep2(false); else if (step === 3) readRooms(false); };
    const summary = () => U.card({ title: 'Tóm tắt hồ sơ', icon: 'clipboard-check', body: U.kv([['Chủ nhà', esc(w.landlord.name || 'Chưa nhập')], ['Số điện thoại', esc(w.landlord.phone || '-')], ['Hợp đồng đầu vào', w.noContract ? 'Chưa ký – bổ sung sau' : contractMode() === 'new' ? 'Tạo mới' : 'Gắn vào HĐ hiện có'], ['Tòa thuộc HĐ', selectedCount()], ['Khu nhà tạo mới', (w.areas || []).length], ['Phòng sẽ sinh', totalRooms()]], 'one'), collapsible: true, collapseKey: 'landlord-onboarding-summary' });

    let main = '';
    if (step === 1) main = U.card({ title: editing ? 'Thông tin chủ nhà hiện tại' : 'Bước 1 – Thông tin chủ nhà', icon: 'user-check', sub: editing ? 'Có thể cập nhật thông tin trước khi bổ sung tòa.' : 'Nhập hồ sơ chủ nhà hoặc đối tác cho thuê đầu vào.', body: `<form id="onboard-landlord" class="form-grid">
      ${U.field({ label: 'Loại', input: U.select({ name: 'type', value: w.landlord.type, options: [['person', 'Cá nhân'], ['company', 'Công ty']] }) })}
      ${U.field({ label: 'Tên chủ nhà / đối tác', req: true, name: 'name', input: U.input({ name: 'name', value: w.landlord.name || '', attrs: { autocomplete: 'name' } }) })}
      ${U.field({ label: 'Số điện thoại', req: true, name: 'phone', input: U.input({ name: 'phone', value: w.landlord.phone || '', icon: 'phone', attrs: { autocomplete: 'tel' } }) })}
      ${U.field({ label: 'Email', input: U.input({ name: 'email', value: w.landlord.email || '', type: 'email', icon: 'mail', attrs: { autocomplete: 'email' } }) })}
      ${U.field({ label: 'Mã số thuế', input: U.input({ name: 'taxCode', value: w.landlord.taxCode || '' }) })}
      ${U.field({ label: 'Tài khoản nhận tiền', input: U.input({ name: 'bankAccount', value: w.landlord.bankAccount || '', placeholder: 'Ngân hàng – số tài khoản' }) })}
      ${U.field({ label: 'Địa chỉ', input: U.input({ name: 'address', value: w.landlord.address || '', icon: 'map-pin' }), cls: 'span2' })}
      ${U.field({ label: 'Chu kỳ trả mặc định', input: U.select({ name: 'cycleMonths', value: w.landlord.cycleMonths, options: [[3, '3 tháng'], [4, '4 tháng'], [6, '6 tháng']] }) })}
      ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: w.landlord.managerId || '', options: managers }) })}
      ${U.field({ label: 'Trạng thái hợp tác', input: U.select({ name: 'status', value: w.landlord.status === 'paused' ? 'paused' : 'active', options: [['active', 'Đang hợp tác'], ['paused', 'Tạm ngừng']] }), help: 'Sắp hết hạn được tính tự động theo HĐ đầu vào.' })}
      </form>` }) + `<div class="wz-foot">${U.btn({ label: 'Hủy', cls: 'btn-ghost', act: 'cancel' })}${U.btn({ label: 'Tiếp tục hợp đồng & tòa →', cls: 'btn-primary', act: 'to2' })}</div>`;

    if (step === 2) {
      const mode = contractMode();
      const existingRows = allBuildings.map(b => { const owner = b.landlordId ? St.get('landlords', b.landlordId) : null; const other = owner && owner.id !== w.landlordId; const linked = owner && owner.id === w.landlordId; const checked = (w.selectedBuildingIds || []).includes(b.id); const nRooms = Q.roomsOf(b.id).length; return `<label class="row between" style="padding:10px 0;border-bottom:1px solid var(--border);align-items:flex-start"><span class="row gap12"><input type="checkbox" ${linked ? 'data-linked-building="1" checked disabled' : `data-existing-building="${esc(b.id)}" ${checked ? 'checked' : ''} ${other ? 'disabled' : ''}`}><span><b>${esc(b.code)} · ${esc(b.name)}</b><small class="muted" style="display:block">${esc(b.address || '-')} · ${esc(Q.area(b.areaId).name || b.district || 'Chưa gán Khu nhà')} · ${nRooms ? nRooms + ' phòng' : 'chưa có phòng'}</small></span></span>${other ? U.chip('Thuộc ' + owner.name, 'gray') : linked ? U.chip('Đã liên kết', 'green') : U.chip('Chưa có chủ nhà', 'blue')}</label>`; }).join('');
      const newCards = (w.buildings || []).map((b, i) => U.card({ title: 'Tòa mới ' + (i + 1), icon: 'building', actions: U.iconBtn('trash', 'remove-building', 'Xóa tòa nháp', { 'data-ref': b.ref }), cls: 'mb16', attrs: `data-new-building="${esc(b.ref)}"`, body: `<div class="form-grid">
        ${U.field({ label: 'Mã tòa', name: 'code', input: U.input({ name: 'code', value: b.code || '', placeholder: 'Để trống để tự sinh' }) })}
        ${U.field({ label: 'Tên tòa', req: true, name: 'name', input: U.input({ name: 'name', value: b.name || '', placeholder: 'Tòa Sunrise...' }) })}
        ${U.field({ label: 'Địa chỉ', req: true, name: 'address', input: U.input({ name: 'address', value: b.address || '', icon: 'map-pin' }), cls: 'span2' })}
        ${U.field({ label: 'Khu nhà quản lý', req: true, name: 'areaRef', input: `<div class="row gap8">${U.select({ name: 'areaRef', value: b.areaRef || '', placeholder: 'Chọn Khu nhà', options: areaOptions(), attrs: { style: 'flex:1' } })}${U.btn({ label: 'Thêm nhanh', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'quick-area', attrs: { 'data-ref': b.ref } })}</div>`, help: 'Danh mục quản lý dùng chung cho tòa, nhân sự và báo cáo.' })}
        ${U.field({ label: 'Quận/Huyện', input: U.input({ name: 'district', value: b.district || '', placeholder: 'Thông tin địa lý của tòa' }), help: 'Khác với Khu nhà quản lý.' })}
        ${U.field({ label: 'Tiền tố mã phòng', input: U.input({ name: 'prefix', value: b.prefix || '', placeholder: 'A', attrs: { maxlength: 2 } }), help: 'VD: A → A.01.01' })}
        ${U.field({ label: 'Số tầng', input: U.input({ name: 'floors', type: 'number', value: b.floors || 1, attrs: { min: 1 } }) })}
        ${U.field({ label: 'Số phòng / tầng', input: U.input({ name: 'perFloor', type: 'number', value: b.perFloor || 4, attrs: { min: 0 } }), help: 'Dùng để sinh phòng ở bước sau.' })}
        ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: b.managerId || w.landlord.managerId || '', options: managers }) })}
      </div>` })).join('');
      const contractCard = mode === 'none' ? '' : U.card({ title: 'Hợp đồng đầu vào', icon: 'file-text', sub: 'Tòa và phòng chỉ được đưa vào khai thác khi có HĐ với chủ nhà còn hiệu lực.', body: `<div class="col gap12">${existingLcs.length ? `<div class="col gap8">${existingLcs.map(c => U.radioCard({ name: 'contractMode', value: 'existing:' + c.id, checked: mode === 'existing:' + c.id, title: 'Gắn tòa vào ' + c.code, text: F.date(c.start) + ' – ' + F.date(c.end) + ' · ' + F.vnd(c.rent) + ' đ/tháng · ' + c.cycleMonths + ' tháng/lần', icon: 'file-check' })).join('')}${U.radioCard({ name: 'contractMode', value: 'new', checked: mode === 'new', title: 'Tạo hợp đồng mới', text: 'Điều khoản riêng cho các tòa bổ sung', icon: 'file-plus' })}</div>` : ''}
        ${mode === 'new' ? `<div class="form-grid">
        ${U.field({ label: 'Ngày ký', input: U.date({ name: 'signedDate', value: w.contract.signedDate }) })}${U.field({ label: 'Loại hợp đồng', input: U.select({ name: 'type', value: w.contract.type, options: ['Hợp đồng thuê tòa nhà', 'Hợp đồng hợp tác kinh doanh'] }) })}
        ${U.field({ label: 'Ngày bắt đầu', req: true, name: 'start', input: U.date({ name: 'start', value: w.contract.start }) })}${U.field({ label: 'Ngày kết thúc', req: true, name: 'end', input: U.date({ name: 'end', value: w.contract.end }) })}
        ${U.field({ label: 'Giá thuê / tháng', req: true, name: 'rent', input: U.money({ name: 'rent', value: w.contract.rent }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: w.contract.deposit }) })}
        ${U.field({ label: 'Thời gian giữ giá (tháng)', input: U.input({ name: 'priceHoldMonths', type: 'number', value: w.contract.priceHoldMonths || 24, attrs: { min: 0 } }), help: 'Chủ nhà không tăng giá trong thời gian này.' })}${U.field({ label: 'Chu kỳ trả', input: U.select({ name: 'cycleMonths', value: w.contract.cycleMonths || w.landlord.cycleMonths, options: [[3, '3 tháng/lần'], [4, '4 tháng/lần'], [6, '6 tháng/lần']] }), help: 'Lịch trả chủ nhà được sinh tự động theo chu kỳ.' })}
        ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: w.contract.note || '' }), cls: 'span2' })}
        </div>` : ''}</div>` });
      main = `<form id="onboard-contract">${editing ? '' : U.card({ body: U.check({ name: 'noContract', label: '<b>Chưa ký hợp đồng – chỉ lưu hồ sơ chủ nhà</b><br><span class="muted small">Tòa nhà, phòng và HĐ đầu vào sẽ bổ sung sau tại chi tiết chủ nhà.</span>', checked: !!w.noContract, attrs: { 'data-on': 'no-contract' } }) })}
      ${contractCard}</form>
      ${mode === 'none' ? U.note('info', 'Chỉ lưu hồ sơ chủ nhà', 'Bỏ qua tòa nhà và phòng. Khi ký hợp đồng, vào chi tiết chủ nhà → "Thêm tòa" để bổ sung.') : `${U.card({ title: 'Tòa thuộc hợp đồng – chọn tòa đã có', icon: 'square-check', sub: 'Chỉ tòa chưa có chủ nhà mới được chọn. Tòa đã thuộc chủ nhà khác được khóa để tránh chuyển chủ ngoài ý muốn.', body: existingRows || U.empty({ title: 'Chưa có tòa nhà trong hệ thống' }) })}
      ${U.section('Khai báo tòa mới', 'Có thể thêm nhiều tòa trong cùng hợp đồng.', U.btn({ label: 'Thêm tòa mới', icon: 'plus', cls: 'btn-primary', size: 'btn-sm', act: 'add-building' }))}${newCards || U.card({ body: U.empty({ icon: 'building', title: 'Chưa khai báo tòa mới', text: 'Chọn tòa có sẵn ở trên hoặc thêm một tòa mới.' }) })}`}
      <div class="wz-foot">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: 'to1' })}<div class="row">${U.btn({ label: 'Hủy', cls: 'btn-outline', act: 'cancel' })}${U.btn({ label: mode === 'none' ? 'Kiểm tra hồ sơ →' : 'Tiếp tục khai báo phòng →', cls: 'btn-primary', act: 'to3' })}</div></div>`;
    }

    if (step === 3) {
      ensureRoomSpecs();
      const specCards = selectedRefs().map(ref => {
        const s = roomSpecOf(ref); const b = refBuilding(ref) || {}; const px = refPrefix(ref); const n = roomCount(s);
        if (s.locked) return U.card({ title: esc(refLabel(ref)), icon: 'building', cls: 'mb16', body: U.note('info', 'Đã có ' + Q.roomsOf(b.id).length + ' phòng', 'Giữ nguyên danh sách phòng hiện có. Có thể thêm phòng tại chi tiết tòa.') });
        return U.card({ title: esc(refLabel(ref)), icon: 'building', cls: 'mb16', attrs: `data-room-spec="${esc(ref)}" data-prefix="${esc(px)}"`, actions: U.chip(n ? 'Sinh ' + n + ' phòng' : 'Không sinh phòng', n ? 'green' : 'gray'), body: `<div class="form-grid">
          ${U.field({ label: 'Từ tầng', name: 'floorFrom', input: U.input({ name: 'floorFrom', type: 'number', value: s.floorFrom, attrs: { min: 1 } }) })}${U.field({ label: 'Đến tầng', name: 'floorTo', input: U.input({ name: 'floorTo', type: 'number', value: s.floorTo, attrs: { min: 1 } }) })}
          ${U.field({ label: 'Số phòng / tầng', name: 'perFloor', input: U.input({ name: 'perFloor', type: 'number', value: s.perFloor, attrs: { min: 1, max: 20 } }) })}${U.field({ label: 'Loại phòng', input: U.select({ name: 'type', value: s.type, options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'] }) })}
          ${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'area', type: 'number', value: s.area, attrs: { min: 1 } }) })}${U.field({ label: 'Giá tham chiếu / tháng', req: true, name: 'price', input: U.money({ name: 'price', value: s.price }) })}
          <div class="span2 small muted" data-room-preview>${n ? 'Sinh <b>' + n + '</b> phòng · mã <b>' + px + '.' + F.pad(s.floorFrom) + '.01</b> → <b>' + px + '.' + F.pad(s.floorTo) + '.' + F.pad(s.perFloor) + '</b>' : 'Chưa sinh phòng'}</div>
          ${U.check({ name: 'skip', label: '<b>Nhập phòng sau</b> <span class="muted small">(Import phòng hoặc "Tạo nhiều phòng" ở chi tiết tòa)</span>', checked: !!s.skip, attrs: { 'data-on': 'room-skip' } })}
        </div>` });
      }).join('');
      main = `${U.card({ title: 'Bước 3 – Khai báo phòng theo tòa', icon: 'door', sub: 'Mã phòng sinh theo mẫu <tiền tố>.<tầng>.<số>; giá và loại phòng có thể sửa từng phòng sau khi tạo.', body: `<div class="small muted">Tổng: <b id="room-total">${totalRooms()}</b> phòng sẽ được tạo ở trạng thái Sẵn sàng.</div>` })}${specCards}
      <div class="wz-foot">${U.btn({ label: '← Quay lại hợp đồng & tòa', cls: 'btn-ghost', act: 'to2' })}<div class="row">${U.btn({ label: 'Hủy', cls: 'btn-outline', act: 'cancel' })}${U.btn({ label: 'Kiểm tra hồ sơ →', cls: 'btn-primary', act: 'to4' })}</div></div>`;
    }

    if (step === 4) {
      ensureRoomSpecs(); const mode = contractMode(); const sched = schedulePreview(); const existingLc = mode.startsWith('existing:') ? St.get('landlordContracts', mode.slice(9)) : null;
      const buildingReview = selectedRefs().map(ref => { const b = refBuilding(ref) || {}; const isNew = !String(ref).startsWith('existing:'); const s = roomSpecOf(ref); const n = roomCount(s); return `<tr><td><b>${esc(b.code || 'Tự sinh')}</b></td><td>${esc(b.name)}</td><td>${esc(isNew ? areaName(b.areaRef) : (Q.area(b.areaId).name || b.district || '-'))}</td><td>${isNew ? U.chip('Tạo mới', 'green') : U.chip('Có sẵn', 'blue')}</td><td class="num">${s && s.locked ? Q.roomsOf(b.id).length + ' <span class="muted">(đã có)</span>' : n ? n : '<span class="muted">nhập sau</span>'}</td></tr>`; }).join('');
      main = `${U.card({ title: 'Thông tin chủ nhà', icon: 'user-check', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'to1' }), body: U.kv([['Tên', esc(w.landlord.name)], ['Loại', w.landlord.type === 'company' ? 'Công ty' : 'Cá nhân'], ['Số điện thoại', esc(w.landlord.phone)], ['Email', esc(w.landlord.email || '-')], ['Địa chỉ', esc(w.landlord.address || '-')], ['Chu kỳ mặc định', w.landlord.cycleMonths + ' tháng']], 'one') })}
      ${U.card({ title: 'Hợp đồng đầu vào', icon: 'file-text', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'to2' }), body: mode === 'none' ? U.note('info', 'Chưa ký hợp đồng', 'Chỉ lưu hồ sơ chủ nhà. Bổ sung tòa và HĐ tại chi tiết chủ nhà.') : existingLc ? U.kv([['Gắn vào HĐ', esc(existingLc.code) + ' ' + Q.chip('lcontract', Q.lcStatus(existingLc))], ['Thời hạn', F.date(existingLc.start) + ' – ' + F.date(existingLc.end)], ['Giá thuê', F.vnd(existingLc.rent) + ' / tháng'], ['Số tòa bổ sung', selectedCount()]], 'one') : U.kv([['Thời hạn', F.date(w.contract.start) + ' – ' + F.date(w.contract.end)], ['Giá thuê', F.vnd(F.num(w.contract.rent)) + ' / tháng'], ['Tiền cọc', F.vnd(F.num(w.contract.deposit))], ['Giữ giá', (Number(w.contract.priceHoldMonths) || 0) + ' tháng'], ['Chu kỳ trả', w.contract.cycleMonths + ' tháng/lần'], ['Số tòa', selectedCount()]], 'one') })}
      ${mode === 'none' ? '' : U.card({ title: 'Tòa nhà & phòng', icon: 'building', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'to3' }), bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Mã</th><th>Tên tòa</th><th>Khu nhà quản lý</th><th>Nguồn</th><th class="num">Phòng sinh</th></tr></thead><tbody>${buildingReview}</tbody></table></div>` })}
      ${sched.length ? U.card({ title: 'Lịch trả chủ nhà (tự sinh ' + sched.length + ' kỳ)', icon: 'calendar', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Kỳ</th><th>Hạn trả</th><th class="num">Số tiền</th></tr></thead><tbody>${sched.slice(0, 6).map(x => `<tr><td>${esc(x.label)}</td><td>${F.date(x.dueDate)}</td><td class="num">${F.vnd(x.amount)}</td></tr>`).join('')}${sched.length > 6 ? `<tr><td colspan="3" class="muted tc">… và ${sched.length - 6} kỳ nữa đến ${F.date(sched[sched.length - 1].dueDate)}</td></tr>` : ''}</tbody></table></div>` }) : ''}
      <div class="wz-foot">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: mode === 'none' ? 'to2' : 'to3' })}<div class="row">${U.btn({ label: 'Hủy', cls: 'btn-outline', act: 'cancel' })}${U.btn({ label: editing ? 'Lưu bổ sung tòa nhà' : 'Hoàn tất onboarding', icon: 'check-circle', cls: 'btn-primary', act: 'submit' })}</div></div>`;
    }

    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Chủ nhà & đối tác', href: '#/landlords' }, { label: editing ? 'Bổ sung tòa nhà' : 'Thêm chủ nhà' }]);
    root.innerHTML = `${U.pageHead({ title: editing ? 'Bổ sung tòa nhà cho ' + esc(w.landlord.name) : 'Onboarding chủ nhà', sub: 'Chủ nhà → Hợp đồng đầu vào → Tòa nhà → Phòng trong một quy trình; lịch trả chủ nhà sinh tự động.', back: editing ? '#/landlords/' + w.landlordId + '?tab=buildings' : '#/landlords' })}${U.wizard(STEPS, step - 1)}<div class="two-col wide"><div class="side-stack">${main}</div><aside class="side-stack">${summary()}${U.card({ title: 'Nguyên tắc liên kết', icon: 'layers', body: '<div class="small muted">Chủ nhà → HĐ đầu vào → Tòa nhà → Phòng.<br>Mỗi tòa thuộc đúng một chủ nhà; phòng chỉ cho thuê khi tòa có HĐ đầu vào còn hiệu lực. Khu nhà quản lý là danh mục vận hành, không gắn với chủ nhà.</div>', collapsible: true, collapseKey: 'landlord-onboarding-rules' })}</aside></div>`;
    U.onInput(root, (e) => {
      const card = e.target.closest('[data-room-spec]'); if (!card) return; readRooms(false); const s = roomSpecOf(card.dataset.roomSpec); const n = roomCount(s); const px = card.dataset.prefix;
      const pv = card.querySelector('[data-room-preview]'); if (pv) pv.innerHTML = n ? 'Sinh <b>' + n + '</b> phòng · mã <b>' + px + '.' + F.pad(s.floorFrom) + '.01</b> → <b>' + px + '.' + F.pad(s.floorTo) + '.' + F.pad(s.perFloor) + '</b>' : 'Chưa sinh phòng';
      const chip = card.querySelector('.card-h .chip'); if (chip) { chip.textContent = n ? 'Sinh ' + n + ' phòng' : 'Không sinh phòng'; chip.className = 'chip ' + (n ? 'green' : 'gray'); }
      const tot = root.querySelector('#room-total'); if (tot) tot.textContent = totalRooms();
    });
    U.onChange(root, { 'no-contract': () => { readStep2(false); if (w.noContract) { w.selectedBuildingIds = []; w.buildings = []; w.rooms = []; } TH.router.refresh(); }, 'contract-mode': () => { readStep2(false); TH.router.refresh(); }, 'room-skip': () => { readRooms(false); TH.router.refresh(); } });
    root.querySelectorAll('input[name=contractMode]').forEach(el => el.setAttribute('data-on', 'contract-mode'));
    U.bind(root, {
      to1: () => { keepCurrentStep(); w.step = 1; TH.router.refresh(); },
      to2: () => { if (step === 1 && !readLandlord(true)) return; keepCurrentStep(); w.step = 2; TH.router.refresh(); },
      to3: () => { if (step === 2 && !readStep2(true)) return; keepCurrentStep(); w.step = w.noContract ? 4 : 3; TH.router.refresh(); },
      to4: () => { if (step === 3 && !readRooms(true)) return; keepCurrentStep(); w.step = 4; TH.router.refresh(); },
      'add-building': () => { readStep2(false); w.buildings.push({ ref: F.uid('newb'), code: '', name: '', address: '', areaRef: '', district: '', prefix: '', floors: 1, perFloor: 4, managerId: w.landlord.managerId || '' }); TH.router.refresh(); },
      'remove-building': (el) => { readStep2(false); w.buildings = w.buildings.filter(b => b.ref !== el.dataset.ref); w.rooms = (w.rooms || []).filter(r => r.ref !== el.dataset.ref); TH.router.refresh(); },
      'quick-area': (el) => {
        readStep2(false); const building = w.buildings.find(b => b.ref === el.dataset.ref); if (!building) return;
        const m = U.modal({ title: 'Thêm nhanh Khu nhà', size: 'sm', sub: 'Khu nhà chỉ được lưu khi hoàn tất onboarding.', body: `<div class="col gap12">${U.field({ label: 'Mã Khu nhà', input: U.input({ name: 'code', placeholder: 'Để trống để tự sinh' }) })}${U.field({ label: 'Tên Khu nhà', req: true, name: 'name', input: U.input({ name: 'name', placeholder: 'Khu Cầu Giấy' }) })}${U.field({ label: 'Quận/Huyện', input: U.input({ name: 'districtsText', value: building.district || '', placeholder: 'Cầu Giấy, Nam Từ Liêm' }), help: 'Có thể nhập nhiều quận/huyện, phân tách bằng dấu phẩy.' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Thêm Khu nhà', icon: 'plus', cls: 'btn-primary', act: 's' }) });
        U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); if (!String(d.name || '').trim()) return U.setErrors(m.el, { name: 'Nhập tên Khu nhà' }); const code = String(d.code || '').trim(); const candidates = [...persistedAreas.map(a => ({ ref: a.id, code: a.code, name: a.name })), ...w.areas]; const same = candidates.find(a => code ? String(a.code || '').toUpperCase() === code.toUpperCase() : F.norm(a.name) === F.norm(d.name)); if (same) { building.areaRef = same.ref; m.close(); U.toast('info', 'Đã chọn Khu nhà có sẵn', same.name); TH.router.refresh(); return; } const area = { ref: F.uid('newa'), code, name: String(d.name).trim(), districts: String(d.districtsText || '').split(',').map(x => x.trim()).filter(Boolean) }; w.areas.push(area); building.areaRef = area.ref; m.close(); TH.router.refresh(); } });
      },
      cancel: async () => { if (await U.confirm({ title: 'Hủy onboarding?', text: 'Toàn bộ chủ nhà, hợp đồng, tòa và phòng đang nhập sẽ không được lưu.', ok: 'Hủy onboarding', danger: true })) { delete TH._wz.landlordOnboarding; TH.go(editing ? '#/landlords/' + w.landlordId + '?tab=buildings' : '#/landlords'); } },
      submit: () => {
        const mode = contractMode(); const usedAreaRefs = new Set((w.buildings || []).map(b => b.areaRef));
        const payload = { landlord: Object.assign({}, w.landlord), areas: (w.areas || []).filter(a => usedAreaRefs.has(a.ref)), buildings: mode === 'none' ? [] : [...(w.selectedBuildingIds || []).map(id => ({ mode: 'existing', id, ref: 'existing:' + id })), ...(w.buildings || []).map(b => ({ mode: 'new', ref: b.ref, data: Object.assign({}, b) }))], contract: mode === 'none' ? null : Object.assign({}, w.contract, { mode, buildingRefs: selectedRefs() }), rooms: mode === 'none' ? [] : (w.rooms || []).filter(r => !r.skip && !r.locked).map(r => Object.assign({}, r)) };
        try {
          const res = X.createLandlordOnboarding(payload); delete TH._wz.landlordOnboarding;
          U.toast('ok', editing ? 'Đã bổ sung tòa nhà' : res.buildings.length ? 'Đã hoàn tất onboarding' : 'Đã lưu hồ sơ chủ nhà', [res.buildings.length ? res.buildings.length + ' tòa' : 'Chưa có tòa – bổ sung khi ký HĐ', res.rooms.length ? res.rooms.length + ' phòng' : '', res.contract ? res.contract.code : '', res.payments.length ? res.payments.length + ' kỳ trả' : ''].filter(Boolean).join(' · '), 6000); TH.go('#/landlords/' + res.landlord.id + '?tab=buildings');
        } catch (e) { U.toast('err', 'Không lưu được', e.message); }
      }
    });
  }, { menu: 'landlords', permission: 'landlords.manage' });

  TH.router.register('/landlords/:id', (root, p, q) => {
    const l = St.get('landlords', p.id); if (!l) { root.innerHTML = U.empty({ title: 'Không tìm thấy chủ nhà' }); return; }
    const tab = q.tab || 'contracts'; const lcs = Q.landlordContracts(l.id).sort((a, c) => F.cmp(c.end, a.end)); const lc = lcs.find(c => Q.lcStatus(c) !== 'ended') || lcs[0]; const pays = Q.landlordPayments(l.id); const docs = St.where('documents', d => d.entityType === 'landlord' && d.entityId === l.id);
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Chủ nhà & đối tác', href: '#/landlords' }, { label: 'Chi tiết chủ nhà' }]);
    const periodDue = pays.filter(x => F.period(x.dueDate) === St.state.meta.period);
    root.innerHTML = `${U.pageHead({ title: esc(l.name), chips: ' ' + Q.chipDot('landlord', Q.landlordStatus(l)), back: '#/landlords', sub: `<span class="chip blue">${esc(l.code)}</span> &nbsp; ${I('phone')} ${esc(l.phone)} &nbsp; ${I('building')} ${l.buildingIds.length} tòa phụ trách`, acts: [U.btn({ label: 'Sửa thông tin', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Tạo lịch thanh toán', icon: 'calendar', cls: 'btn-outline', act: 'schedule' }), U.btn({ label: 'Tải hồ sơ', icon: 'download', cls: 'btn-primary', act: 'dl-all' })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Số tòa liên kết', value: l.buildingIds.length, cap: l.buildingIds.map(id => Q.building(id).name).join(', ') || 'Chưa liên kết', icon: 'building', tone: 'blue' })}${U.kpi({ label: 'Giá trị thuê kỳ này', value: F.vnd(F.sum(periodDue, x => x.amount)), cap: 'Tổng tiền phải trả ' + F.periodLabel(St.state.meta.period).toLowerCase(), icon: 'dollar', tone: 'amber' })}${U.kpi({ label: 'Hợp đồng hiệu lực', value: lcs.filter(c => Q.lcStatus(c) !== 'ended').length, cap: lc && Q.lcStatus(lc) === 'expiring' ? 'Sắp hết hạn ' + F.date(lc.end) : 'Trong tổng ' + lcs.length + ' hợp đồng', icon: 'file-text', tone: lc && Q.lcStatus(lc) === 'expiring' ? 'amber' : 'green' })}${U.kpi({ label: 'Chu kỳ trả', value: (lc ? lc.cycleMonths : l.cycleMonths) + ' tháng', cap: 'Theo thỏa thuận hợp đồng', icon: 'clock', tone: 'purple' })}</div>
    ${U.tabs([{ key: 'overview', label: 'Tổng quan' }, { key: 'buildings', label: 'Tòa nhà' }, { key: 'contracts', label: 'Hợp đồng đầu vào' }, { key: 'payments', label: 'Lịch thanh toán' }, { key: 'docs', label: 'Tài liệu' }, { key: 'history', label: 'Lịch sử' }], tab)}<div id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    const payTable = (container, rows, pager) => U.table(container, { rows, noPager: !pager, unit: 'kỳ thanh toán', cols: [{ key: 'n', label: '#', render: (x, i) => i + 1, width: '40px' }, { key: 'periodLabel', label: 'Kỳ trả' }, { key: 'dueDate', label: 'Hạn thanh toán', sortable: true, render: x => F.date(x.dueDate) }, { key: 'amount', label: 'Số tiền (VND)', num: true, render: x => F.vnd(x.amount) }, { key: 'status', label: 'Trạng thái', render: x => Q.chip('lpay', x.status) }, { key: 'ev', label: 'Bằng chứng', render: x => x.evidence ? `<a class="link" data-act="dl" data-name="${esc(x.evidence)}" href="#">${I('file-text')} ${esc(x.evidence)}</a>` : '-' }, { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.iconBtn('eye', 'view-pay', 'Xem', { 'data-id': x.id }), U.moreBtn(x.id)]) }] });
    if (tab === 'contracts') {
      const milestones = [...(lc ? [{ when: F.date(lc.signedDate), title: 'Ký hợp đồng', sub: lc.code, color: 'blue', fill: true }, { when: F.date(lc.start), title: 'Bắt đầu hiệu lực', sub: 'Hợp đồng chính thức có hiệu lực', color: 'blue' }] : []), ...pays.filter(x => x.status === 'paid').slice(-3).map(x => ({ when: F.date(x.paidDate), title: 'Thanh toán ' + x.periodLabel.split(' (')[0].toLowerCase(), sub: F.vnd(x.amount) + ' VND', color: 'green', fill: true })), ...pays.filter(x => x.status === 'pending').slice(0, 1).map(x => ({ when: F.date(x.dueDate), title: 'Đến hạn thanh toán ' + x.periodLabel.split(' (')[0].toLowerCase(), sub: F.vnd(x.amount) + ' VND', color: 'amber' })), ...(lc ? [{ when: F.date(lc.end), title: 'Kết thúc hợp đồng', sub: 'Dự kiến kết thúc', color: 'gray' }] : [])];
      const related = [{ key: 'documents', title: 'Hồ sơ & tài liệu', icon: 'folder', summary: docs.length + ' tài liệu', meta: docs.length ? 'Hồ sơ chủ nhà đã lưu' : 'Chưa có hồ sơ', actions: `<a class="link small" href="#/landlords/${l.id}?tab=docs">Xem tất cả →</a>`, body: docs.length ? `<div class="file-list">${docs.slice(0, 4).map(d => U.fileItem(d, U.iconBtn('download', 'dl', 'Tải', { 'data-name': d.fileName }))).join('')}</div>` : U.empty({ title: 'Chưa có hồ sơ' }) }, { key: 'milestones', title: 'Lịch sử & mốc quan trọng', icon: 'history', summary: milestones.length + ' mốc', meta: lc ? 'Từ ' + F.date(lc.start) + ' đến ' + F.date(lc.end) : 'Chưa có hợp đồng', body: U.timeline(milestones) }];
      body.innerHTML = `${U.relatedStrip({ id: 'landlord-contract-related', items: related, cls: 'mb16' })}<div class="side-stack">${lc ? U.card({ title: 'Thông tin hợp đồng đầu vào', icon: 'file-text', actions: Q.chip('lcontract', Q.lcStatus(lc)) + U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit-lc', attrs: { 'data-id': lc.id } }), body: `<div class="grid grid-2">${U.kv([['Mã hợp đồng', esc(lc.code)], ['Thời gian thuê', F.date(lc.start) + ' - ' + F.date(lc.end) + ' (' + Math.round(F.daysBetween(lc.start, lc.end) / 365) + ' năm)'], ['Giá thuê', F.vnd(lc.rent) + ' VND/tháng', '(Bằng chữ: ' + F.words(lc.rent) + ')'], ['Tiền cọc', F.vnd(lc.deposit) + ' VND', lc.rent ? '(Bằng ' + Math.round(lc.deposit / lc.rent) + ' tháng tiền thuê)' : ''], ['Thời gian giữ giá', lc.priceHoldMonths + ' tháng đầu'], ['Chu kỳ trả', lc.cycleMonths + ' tháng/lần'], ['Ghi chú', esc(lc.note || 'Không có')]], 'one')}${U.kv([['Ngày ký hợp đồng', F.date(lc.signedDate)], ['Ngày bắt đầu', F.date(lc.start)], ['Ngày kết thúc', F.date(lc.end)], ['Loại hợp đồng', esc(lc.type)], ['Trạng thái', Q.chip('lcontract', Q.lcStatus(lc))], ['Người phụ trách', esc(Q.userName(lc.managerId))], ['Danh sách tòa liên kết', lc.buildingIds.map(id => U.chip(Q.building(id).name, 'blue')).join(' ')]], 'one')}</div>` }) : U.card({ body: U.empty({ icon: 'file-text', title: 'Chưa có hợp đồng đầu vào', action: U.btn({ label: 'Thêm hợp đồng', icon: 'plus', cls: 'btn-primary', size: 'btn-sm', act: 'add-lc' }) }) })}
        ${lc ? U.card({ title: 'Pháp lý, loại tòa & điều khoản (§12.3)', icon: 'shield-check', actions: `<span class="row gap4 wrap">${lc.status === 'draft' ? U.btn({ label: 'Kích hoạt', icon: 'check-circle', size: 'btn-sm', cls: 'btn-primary', act: 'lc-activate', attrs: { 'data-id': lc.id } }) : ''}${lc.status === 'active' ? U.btn({ label: 'Gia hạn', icon: 'refresh', size: 'btn-sm', cls: 'btn-outline', act: 'lc-renew', attrs: { 'data-id': lc.id } }) + U.btn({ label: 'Kết thúc', icon: 'x-circle', size: 'btn-sm', cls: 'btn-ghost', act: 'lc-end', attrs: { 'data-id': lc.id } }) : ''}</span>`, body: `<div class="grid grid-2">${U.kv([['Số hợp đồng', esc(lc.contractNo || '-')], ['Trạng thái HKD', Q.chip('hkd', lc.hkdStatus || 'unregistered') + ' ' + U.btn({ label: 'Điều chỉnh', size: 'btn-sm', cls: 'btn-ghost', act: 'lc-hkd', attrs: { 'data-id': lc.id } }) + (lc.hkdHistory && lc.hkdHistory.length ? '<div class="xs muted">' + lc.hkdHistory.slice(-1).map(h => F.datetime(h.at) + ' · ' + esc(h.reason || '')).join('') + '</div>' : '')], ['PCCC', Q.chip('pccc', Q.pcccStatus(lc)) + ((lc.pccc || {}).expiry ? ' đến ' + F.date(lc.pccc.expiry) : '') + ' ' + U.btn({ label: 'Cập nhật', size: 'btn-sm', cls: 'btn-ghost', act: 'lc-pccc', attrs: { 'data-id': lc.id } })], ['Ký hiệu / loại tòa theo HĐ', (lc.buildingType ? Q.buildingTypeLabel(lc.buildingType) + ' từ ' + F.date(lc.typeEffectiveFrom || lc.start) : '-') + ' ' + U.btn({ label: 'Cập nhật', size: 'btn-sm', cls: 'btn-ghost', act: 'lc-type', attrs: { 'data-id': lc.id } })], ['Ngày đến hạn thanh toán', 'Ngày ' + (lc.dueDay || 5) + ' của kỳ'], ['Tài khoản người nhận', esc([(lc.bankAccount || {}).bank, (lc.bankAccount || {}).name, (lc.bankAccount || {}).no].filter(Boolean).join(' · ') || '-')]], 'one')}${U.kv([['Lịch tăng giá', ((lc.priceSchedule || []).length ? '<table class="tbl compact"><tbody>' + lc.priceSchedule.map(x => '<tr><td>' + F.date(x.from) + '</td><td class="num"><b>' + F.vnd(x.price) + '</b></td><td class="xs muted">' + esc(x.note || '') + '</td></tr>').join('') + '</tbody></table>' : '<span class="muted">Chưa có</span>') + ' ' + U.btn({ label: 'Sửa lịch', size: 'btn-sm', cls: 'btn-ghost', act: 'lc-schedule', attrs: { 'data-id': lc.id } })], ['Giá áp dụng hôm nay', F.vnd(Q.lcPriceAt(lc)) + ' VND/tháng'], ['Tài sản bàn giao', esc(lc.handoverAssets || '-')], ['Hồ sơ pháp lý', ['hkd', 'pccc', 'deed', 'contract', 'annex', 'handover'].map(k => { const n = docs.filter(d => d.docType === k).length; return n ? U.chip(Q.label('docType', k) + ' ' + n, 'blue') : ''; }).filter(Boolean).join(' ') || '<span class="muted">Chưa có</span>'], ['Gia hạn', lc.renewedToId ? 'HĐ gia hạn ' + esc((St.get('landlordContracts', lc.renewedToId) || {}).code || '') : (lc.renewedFromId ? 'Gia hạn từ ' + esc((St.get('landlordContracts', lc.renewedFromId) || {}).code || '') : '-')]], 'one')}</div>` }) : ''}
        ${lcs.length > 1 ? U.card({ title: 'Các hợp đồng khác', bodyCls: 'tight', body: lcs.filter(c => c !== lc).map(c => `<div class="row between" style="padding:6px 0">${esc(c.code)} · ${F.date(c.start)} – ${F.date(c.end)} ${Q.chip('lcontract', Q.lcStatus(c))}</div>`).join('') }) : ''}
        ${U.card({ title: 'Lịch thanh toán', icon: 'calendar', actions: U.btn({ label: 'Thêm kỳ thanh toán', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'add-pay' }), body: null, id: 'pay-card' })}</div>`;
      const w = document.createElement('div'); body.querySelector('#pay-card').appendChild(w); payTable(w, pays, true);
    }
    if (tab === 'payments') { body.innerHTML = U.card({ title: 'Toàn bộ lịch thanh toán', icon: 'calendar', actions: U.btn({ label: 'Thêm kỳ', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'add-pay' }), body: null, id: 'pay-card' }); const w = document.createElement('div'); body.querySelector('#pay-card').appendChild(w); payTable(w, pays, true); }
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Thông tin chủ nhà', icon: 'user-check', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }), body: U.kv([['Mã', esc(l.code)], ['Tên', esc(l.name)], ['Loại', l.type === 'company' ? 'Công ty' : 'Cá nhân'], ['MST', esc(l.taxCode || '-')], ['SĐT', esc(l.phone)], ['Email', esc(l.email)], ['Địa chỉ', esc(l.address || '-')], ['Tài khoản nhận tiền', esc(l.bankAccount || '-')], ['Chu kỳ trả', l.cycleMonths + ' tháng'], ['Người phụ trách', esc(Q.userName(l.managerId))]], 'one') })}${U.card({ title: 'Tổng quan thanh toán', icon: 'bar-chart-2', body: `<div class="grid grid-3">${U.stat('Đã trả', pays.filter(x => x.status === 'paid').length + ' kỳ', F.vnd(F.sum(pays.filter(x => x.status === 'paid'), x => x.amount)))}${U.stat('Chờ trả', pays.filter(x => x.status === 'pending').length + ' kỳ', F.vnd(F.sum(pays.filter(x => x.status === 'pending'), x => x.amount)))}${U.stat('Chưa đến hạn', pays.filter(x => x.status === 'upcoming').length + ' kỳ')}</div>` })}</div>`;
    if (tab === 'buildings') { body.innerHTML = U.card({ title: 'Tòa nhà liên kết', icon: 'building', actions: U.btn({ label: 'Thêm tòa', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-building' }), body: null, id: 'bc' }); const w = document.createElement('div'); body.querySelector('#bc').appendChild(w); U.table(w, { rows: l.buildingIds.map(id => Q.building(id)).filter(Boolean), noPager: true, cols: [{ key: 'code', label: 'Mã tòa', render: b => U.link('#/buildings/' + b.id, esc(b.code)) }, { key: 'name', label: 'Tên tòa' }, { key: 'address', label: 'Địa chỉ' }, { key: 'area', label: 'Khu nhà quản lý', render: b => esc(Q.area(b.areaId).name || '-') }, { key: 'rooms', label: 'Số phòng', num: true, render: b => { const n = b.stub ? b.roomCount : Q.roomsOf(b.id).length; return n ? n : (TH.auth.can('rooms.manage') ? U.btn({ label: 'Tạo phòng', icon: 'grid', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-rooms', attrs: { 'data-id': b.id } }) : '0'); } }, { key: 'lc', label: 'HĐ đầu vào', render: b => { const c = Q.landlordContractOf(b.id); return c ? esc(c.code) + ' ' + Q.chip('lcontract', Q.lcStatus(c)) : U.chip('Chưa có HĐ', 'red'); } }, { key: 'cycle', label: 'Chu kỳ', render: b => b.payCycle + ' tháng' }, { key: 'st', label: 'Trạng thái', render: b => Q.chip('building', b.status) }] }); }
    if (tab === 'docs') { const cur = docs.filter(d => !d.supersededById); body.innerHTML = U.card({ title: 'Hồ sơ pháp lý & tài liệu (§4.5, §7.3)', icon: 'folder', sub: 'Theo loại hồ sơ; thay thế file tạo phiên bản mới, file cũ giữ trong lịch sử. Tải "Giấy đăng ký HKD" → HĐ đầu vào tự chuyển Đã đăng ký.', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload', attrs: { 'data-guide': 'landlord-upload' } }), bodyCls: 'tight', body: cur.length ? `<table class="tbl compact"><thead><tr><th>Loại</th><th>Tài liệu</th><th>Phiên bản</th><th>Ngày</th><th>Hết hạn</th><th>Người tải</th><th></th></tr></thead><tbody>${cur.map(d => `<tr><td>${Q.chip('docType', d.docType || 'other')}</td><td><b>${esc(d.name)}</b><div class="xs muted">${esc(d.fileName)} · ${esc(d.size || '')}</div></td><td>v${d.version || 1}${Q.documentVersions(d).length > 1 ? ' <span class="xs muted">(' + (Q.documentVersions(d).length - 1) + ' bản cũ)</span>' : ''}</td><td>${F.date(d.date)}</td><td>${d.expiry ? F.date(d.expiry) : '-'}</td><td class="xs">${esc(d.uploadedBy ? Q.userName(d.uploadedBy) : '')}</td><td class="tr nowrap">${U.iconBtn('download', 'dl', 'Tải', { 'data-name': d.fileName })}${U.iconBtn('upload', 'replace-doc', 'Thay thế (phiên bản mới)', { 'data-id': d.id })}${d.source === 'user' ? U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }) : ''}</td></tr>`).join('')}</tbody></table>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu' }) }); }
    if (tab === 'history') { const logs = St.where('auditLog', x => (x.entityType === 'landlord' && x.entityId === l.id) || (x.entityType === 'landlordContract' && lcs.some(c => c.id === x.entityId)) || (x.entityType === 'landlordPayment' && pays.some(c => c.id === x.entityId))); body.innerHTML = U.card({ title: 'Lịch sử thao tác', icon: 'history', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, {
      tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, edit: () => Fm.landlord(l), 'add-lc': () => Fm.landlordContract(l.id), 'edit-lc': (el) => Fm.landlordContract(l.id, St.get('landlordContracts', el.dataset.id)),
      'lc-activate': (el) => { try { X.activateLandlordContract(el.dataset.id); U.toast('ok', 'Đã kích hoạt HĐ đầu vào'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
      'lc-renew': (el) => { const x = St.get('landlordContracts', el.dataset.id); const m = U.modal({ title: 'Gia hạn HĐ đầu vào ' + x.code, size: 'sm', sub: 'Tạo HĐ mới Dự thảo từ ' + F.date(F.addDays(x.end, 1)) + '; HĐ cũ giữ nguyên lịch sử', body: `<div class="form-grid">${U.field({ label: 'Ngày kết thúc mới', req: true, input: U.date({ name: 'end', value: F.addDays(F.addMonths(x.end, 36), 0) }) })}${U.field({ label: 'Giá thuê mới', input: U.money({ name: 'rent', value: Q.lcPriceAt(x) }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: x.deposit }) })}${U.field({ label: 'Ngày ký', input: U.date({ name: 'signedDate', value: F.today() }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lập HĐ gia hạn', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); const n = X.renewLandlordContract(x.id, { end: d.end, rent: d.rent, deposit: d.deposit, signedDate: d.signedDate }); m.close(); U.toast('ok', 'Đã lập ' + n.code + ' (dự thảo)'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'lc-end': async (el) => { const r = await U.confirm({ title: 'Kết thúc HĐ đầu vào?', text: 'Tòa sẽ không còn HĐ đầu vào hiệu lực – không kích hoạt HĐ thuê mới được.', ok: 'Kết thúc', danger: true, body: U.field({ label: 'Ngày kết thúc', input: U.date({ name: 'end', value: F.today() }) }) + U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }) }); if (r) { try { X.endLandlordContract(el.dataset.id, { end: r.end, reason: r.reason }); U.toast('ok', 'Đã kết thúc HĐ đầu vào'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } },
      'lc-hkd': (el) => { const x = St.get('landlordContracts', el.dataset.id); const m = U.modal({ title: 'Trạng thái đăng ký HKD', size: 'sm', sub: 'Tự động Đã đăng ký khi tải "Giấy đăng ký HKD"; điều chỉnh tay phải có lý do và audit (§12.3.3)', body: `<div class="form-grid">${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: x.hkdStatus || 'unregistered', options: [['unregistered', 'Chưa đăng ký'], ['registered', 'Đã đăng ký']] }) })}${U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) })}</div>${(x.hkdHistory || []).length ? '<div class="mt8 xs muted">Lịch sử: ' + x.hkdHistory.map(h => F.datetime(h.at) + ' ' + h.from + '→' + h.to + (h.reason ? ' (' + esc(h.reason) + ')' : '')).join(' · ') + '</div>' : ''}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); X.setHkdStatus(x.id, d.status, d.reason); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'lc-pccc': (el) => { const x = St.get('landlordContracts', el.dataset.id); const m = U.modal({ title: 'PCCC', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: (x.pccc || {}).status || 'none', options: [['none', 'Chưa có'], ['valid', 'Có giấy PCCC']] }) })}${U.field({ label: 'Hạn hiệu lực', input: U.date({ name: 'expiry', value: (x.pccc || {}).expiry || '' }) })}${U.field({ label: 'Ghi chú', input: U.input({ name: 'note', value: (x.pccc || {}).note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.setPccc(x.id, m.data()); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'lc-type': (el) => { const x = St.get('landlordContracts', el.dataset.id); const m = U.modal({ title: 'Ký hiệu / loại tòa theo HĐ đầu vào', size: 'sm', sub: 'Ghi Building Type History có ngày hiệu lực, không ghi đè lịch sử (§12.3.4)', body: `<div class="form-grid">${U.field({ label: 'Loại tòa', input: U.select({ name: 'type', value: x.buildingType || 'T', options: Q.buildingTypeOptions() }) })}${U.field({ label: 'Ngày hiệu lực', input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.setLcBuildingType(x.id, m.data()); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'lc-schedule': (el) => { const x = St.get('landlordContracts', el.dataset.id); const rows0 = (x.priceSchedule || []).length ? x.priceSchedule : [{ from: F.addMonths(x.start, x.priceHoldMonths || 24), price: Math.round(x.rent * 1.05) }]; const row = (r, i) => `<tr><td>${U.date({ name: 'f_' + i, value: r.from, cls: 'sm' })}</td><td>${U.money({ name: 'p_' + i, value: r.price })}</td><td>${U.input({ name: 'n_' + i, value: r.note || '', cls: 'sm' })}</td></tr>`; const m = U.modal({ title: 'Lịch tăng giá – ' + x.code, sub: 'Mỗi dòng một mốc: từ ngày – giá mới (lưu lịch sử điều chỉnh giá)', body: `<table class="tbl compact"><thead><tr><th>Từ ngày</th><th>Giá mới</th><th>Ghi chú</th></tr></thead><tbody id="ps-body">${rows0.map(row).join('')}</tbody></table>` + U.btn({ label: 'Thêm mốc', icon: 'plus', size: 'btn-sm', cls: 'btn-ghost', act: 'add' }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu lịch', cls: 'btn-primary', act: 's' }) }); let n = rows0.length; U.bind(m.el, { c: () => m.close(), add: () => { m.el.querySelector('#ps-body').insertAdjacentHTML('beforeend', row({ from: '', price: '' }, n++)); }, s: () => { try { const d = m.data(); const list = Array.from({ length: n }, (_, i) => ({ from: d['f_' + i], price: d['p_' + i], note: d['n_' + i] })); X.savePriceSchedule(x.id, list); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      'add-building': () => openOnboarding(l, 2), 'bulk-rooms': (el) => Fm.roomsBulk(el.dataset.id),
      schedule: () => lc ? Fm.landlordSchedule(lc) : U.toast('warn', 'Cần có hợp đồng đầu vào trước'), 'add-pay': () => lc ? Fm.landlordPayment(lc) : U.toast('warn', 'Cần có hợp đồng đầu vào trước'),
      'dl-all': () => U.fakePdf('Ho so chu nha ' + l.code, ['Chủ nhà: ' + l.name, 'SĐT: ' + l.phone, ...docs.map(d => '- ' + d.name + ' (' + d.fileName + ')')]), dl: (el) => U.fakePdf(el.dataset.name, ['Chủ nhà: ' + l.name]), upload: () => Fm.upload('landlord', l.id), 'replace-doc': (el) => Fm.upload('landlord', l.id, null, { supersedesId: el.dataset.id }), 'rm-doc': (el) => X.removeDocument(el.dataset.id),
      'view-pay': (el) => { const x = St.get('landlordPayments', el.dataset.id); U.modal({ title: x.periodLabel, size: 'sm', body: U.kv([['Hạn thanh toán', F.date(x.dueDate)], ['Số tiền', F.vnd(x.amount) + ' VND'], ['Trạng thái', Q.chip('lpay', x.status)], ['Ngày thanh toán', x.paidDate ? F.date(x.paidDate) : '-'], ['Bằng chứng', esc(x.evidence || '-')]], 'one'), footer: x.status !== 'paid' ? U.btn({ label: 'Ghi nhận đã trả', cls: 'btn-primary', act: 'paid2', icon: 'check' }) : '' , onMount: (m) => U.bind(m.el, { paid2: () => { m.close(); Fm.landlordPaid(x); } }) }); },
      more: (el) => { const x = St.get('landlordPayments', el.dataset.id); U.menu(el, [x.status !== 'paid' ? { label: 'Ghi nhận đã trả', icon: 'check', onClick: () => Fm.landlordPaid(x) } : { label: 'Đã thanh toán ' + F.date(x.paidDate), icon: 'check-circle', disabled: true }, { label: 'Nhắc thanh toán (Zalo/Email)', icon: 'send', p2: true, title: TH.phase.on(2) ? 'Tạo đợt Zalo sự kiện Đến kỳ trả chủ nhà' : 'Kênh nhắc chủ nhà chưa chốt – OI-03', onClick: () => { if (!TH.auth.can('zalo.send')) return U.toast('err', 'Không có quyền gửi Zalo', 'Chỉ Admin được tạo đợt gửi (zalo.send)'); const ev = St.one('zaloEvents', z => z.key === 'landlord_due'); if (ev && !ev.enabled) return U.toast('warn', 'Rule "Đến kỳ trả chủ nhà" đang tắt', 'Bật tại Cấu hình Zalo trước (FR-ZAL-01)'); const tpl = Q.template(ev.templateId); const b = St.add('zaloBatches', { code: St.nextCode('zaloBatches', 'ZL-' + periodCode(F.period(x.dueDate)) + '-', 3), name: 'Nhắc trả chủ nhà ' + x.periodLabel, eventKey: 'landlord_due', sourceKey: 'landlord_due', audience: 'Chủ nhà', plannedCount: 1, sentCount: 0, failedCount: 0, sentAt: null, createdBy: TH.auth.user().id, status: 'draft', templateId: tpl.id, scopeLabel: Q.building(x.buildingId).name, period: F.period(x.dueDate), sendMode: 'now', rules: 'Nhắc kỳ thanh toán chủ nhà', phase: 2, log: [] }); const ll = St.get('landlords', x.landlordId) || {}; St.add('zaloMessages', { batchId: b.id, tenantId: null, landlordId: x.landlordId, roomId: null, buildingId: x.buildingId, invoiceId: null, channel: 'Zalo', templateCode: tpl.code, status: 'queued', errorCode: '', sentAt: null, phone: ll.phone || '', content: Q.renderTemplate(tpl.body, Q.templateCtx(null, { name: ll.name }, { buildingId: x.buildingId, amount: x.amount, due: x.dueDate })), amountAtSend: x.amount, retryOfId: null, attempt: 1, recipientName: ll.name }); St.audit('create', 'zaloBatch', b.id, 'Nhắc trả chủ nhà ' + b.code); X.startBatch(b.id); U.toast('ok', 'Đã tạo đợt nhắc chủ nhà ' + b.code); TH.go('#/zalo/batches/' + b.id); } }]); },
    });
  }, { menu: 'landlords', permission: 'landlords.view', resource: { type: 'landlord' } });
})(window.TH);
