/* Phase 2 – Bảo trì & sửa chữa: Sự cố (list/detail/drawer), Lịch bảo dưỡng (lịch tháng + bảng), NCC (tab danh mục) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, C = TH.chart, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const CATS = ['Điện', 'Nước', 'Điều hòa', 'Thang máy', 'Cửa khóa', 'Nội thất', 'PCCC', 'Chiếu sáng', 'Khác'];
  const EQUIP = ['Thang máy', 'Máy bơm', 'Máy giặt chung', 'Máy lọc nước', 'PCCC', 'Máy phát điện', 'Điều hòa', 'Khác'];
  const techUsers = () => St.where('users', u => u.status === 'active' && ['kythuat', 'ops'].includes(u.role));
  const bName = (id) => Q.building(id).name || '-';
  const dueCell = (i) => { const od = Q.incidentOverdue(i); return `<span class="${od ? 'red bold' : ''}">${F.date(i.dueDate)}</span>`; };
  const incStatus = (i) => Q.incidentOverdue(i) ? Q.chip('incident', 'overdue') : Q.chip('incident', i.status);
  const canManage = (incident) => TH.auth.can('maintenance.manage', incident ? { type: 'incident', record: incident } : undefined);

  /* ---- Forms ---- */
  Fm.incident = (i = {}, opts = {}) => {
    const bs = St.where('buildings', b => !b.stub && TH.auth.can('maintenance.manage', { buildingId: b.id })); const bId = i.buildingId || opts.buildingId || (bs[0] || {}).id;
    const roomOpts = (b) => St.where('rooms', r => r.buildingId === b).sort((a, c) => a.code.localeCompare(c.code)).map(r => [r.id, r.code + ' – ' + Q.label('room', r.status)]);
    const m = U.drawer({ title: i.id ? 'Sửa sự cố ' + i.code : 'Tạo sự cố', sub: 'Gắn tòa/phòng, ưu tiên, hạn xử lý, người phụ trách (FR-MNT-03)', body: `<div class="form-grid">${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: bId, options: bs.map(b => [b.id, b.name]), attrs: { id: 'inc-b' } }) })}${U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: i.roomId || opts.roomId || '', all: 'Khu vực chung', options: roomOpts(bId), attrs: { id: 'inc-r' } }) })}${U.field({ label: 'Hạng mục', req: true, input: U.select({ name: 'category', value: i.category || '', placeholder: 'Chọn hạng mục', options: CATS }) })}${U.field({ label: 'Mức độ ưu tiên', req: true, input: U.select({ name: 'priority', value: i.priority || 'medium', options: Object.entries(Q.L.priority).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Mô tả', req: true, input: U.textarea({ name: 'desc', value: i.desc || '', placeholder: 'Khách báo máy lạnh không lạnh, có tiếng kêu…' }), cls: 'span2' })}${U.field({ label: 'Hạn xử lý', input: U.date({ name: 'dueDate', value: i.dueDate || F.addDays(F.today(), 3) }), help: 'Để trống: tự tính theo ưu tiên (Khẩn 1 ngày, Cao 3, còn lại 7)' })}${U.field({ label: 'Người phụ trách', input: U.select({ name: 'assigneeId', value: i.assigneeId || '', all: 'Chưa phân công', options: techUsers().map(u => [u.id, u.name + ' – ' + TH.auth.ROLE_LABEL[u.role]]) }) })}${U.field({ label: 'Chi phí dự kiến (VND)', input: U.money({ name: 'cost', value: i.cost || '' }) })}${U.field({ label: 'Nhà cung cấp', input: U.select({ name: 'vendorId', value: i.vendorId || '', all: 'Tự xử lý', options: St.where('vendors', v => v.status === 'active').map(v => [v.id, v.name]) }) })}<div class="field span2"><label>Ảnh hiện trường</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng)' })}</div></div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: i.id ? 'Lưu thay đổi' : 'Tạo sự cố', icon: 'alert-triangle', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'incident-save' } }) });
    m.el.querySelector('#inc-b').addEventListener('change', (e) => { const sel = m.el.querySelector('#inc-r'); sel.innerHTML = '<option value="">Khu vực chung</option>' + roomOpts(e.target.value).map(([v, l]) => `<option value="${v}">${esc(l)}</option>`).join(''); });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = i.id; d.photos = U.dzFiles(m.el, 'ph').map(f => f.name); const r = X.saveIncident(d); m.close(); ok((i.id ? 'Đã cập nhật ' : 'Đã tạo sự cố ') + r.code, r.category + (r.roomId ? ' – ' + Q.room(r.roomId).code : '')); opts.after && opts.after(r); } });
  };
  Fm.schedule = (s = {}) => {
    const m = U.drawer({ title: s.id ? 'Sửa lịch ' + s.code : 'Tạo lịch bảo dưỡng', sub: 'Nhắc trước 7 ngày (BR-16); hoàn thành → tự sinh lịch kế tiếp theo chu kỳ', body: `<div class="form-grid">${U.field({ label: 'Hạng mục / thiết bị', req: true, input: U.select({ name: 'equipType', value: s.equipType || '', placeholder: 'Chọn thiết bị', options: EQUIP }) })}${U.field({ label: 'Tên lịch', input: U.input({ name: 'item', value: s.item || '', placeholder: 'Bảo dưỡng thang máy - A' }) })}${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: s.buildingId || '', placeholder: 'Chọn tòa', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]) }) })}${U.field({ label: 'Chu kỳ', req: true, input: U.select({ name: 'cycle', value: s.cycle || 'monthly', options: Object.entries(Q.L.cycle) }) })}${U.field({ label: 'Ngày dự kiến', req: true, input: U.date({ name: 'date', value: s.date || F.addDays(F.today(), 5) }) })}${U.field({ label: 'Nhà cung cấp', input: U.select({ name: 'vendorId', value: s.vendorId || '', all: 'Tự thực hiện', options: St.where('vendors', v => v.status === 'active').map(v => [v.id, v.name]) }) })}${U.field({ label: 'Phụ trách', input: U.select({ name: 'assigneeId', value: s.assigneeId || '', all: 'Chưa phân công', options: techUsers().map(u => [u.id, u.name]) }) })}${U.field({ label: 'Checklist (mỗi dòng 1 việc)', input: U.textarea({ name: 'checklist', value: (s.checklist || [{ text: 'Kiểm tra tổng thể' }, { text: 'Vệ sinh / tra dầu' }, { text: 'Chạy thử & ghi nhận' }]).map(x => x.text).join('\n'), rows: 4 }), cls: 'span2' })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: s.note || '' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: s.id ? 'Lưu' : 'Tạo lịch', icon: 'calendar', cls: 'btn-primary', act: 'save', attrs: { 'data-guide': 'schedule-save' } }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = s.id; d.item = d.item || d.equipType; d.checklist = String(d.checklist || '').split('\n').filter(Boolean).map(t => ({ text: t.trim(), done: false })); const r = X.saveSchedule(d); m.close(); ok((s.id ? 'Đã cập nhật ' : 'Đã tạo lịch ') + r.code, F.date(r.date)); } });
  };
  const completeIncident = (i) => { const m = U.modal({ title: 'Hoàn tất sự cố ' + i.code, sub: 'Chi phí > 0 → tạo chi phí nhóm Sửa chữa gắn tòa/phòng', body: `${U.field({ label: 'Chi phí thực tế (VND)', input: U.money({ name: 'cost', value: i.cost || 0 }) })}${U.field({ label: 'Nhà cung cấp', input: U.select({ name: 'vendorId', value: i.vendorId || '', all: 'Tự xử lý', options: St.where('vendors', v => v.status === 'active').map(v => [v.id, v.name]) }), cls: 'mt12' })}${U.field({ label: 'Ghi chú kết quả', input: U.textarea({ name: 'note', placeholder: 'Đã thay linh kiện…' }), cls: 'mt12' })}<div class="field mt12"><label>Ảnh sau xử lý</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng)' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Hoàn tất', icon: 'check', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'incident-done' } }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); d.photos = U.dzFiles(m.el, 'ph').map(f => f.name); const r = X.completeIncident(i.id, d); m.close(); ok('Đã hoàn tất ' + r.code, r.expenseId ? 'Đã tạo chi phí ' + F.vnd(r.cost) : ''); } }); };
  const assignModal = (ids) => { const m = U.modal({ title: 'Phân công ' + ids.length + ' sự cố', size: 'sm', body: U.field({ label: 'Người phụ trách', req: true, input: U.select({ name: 'assigneeId', placeholder: 'Chọn', options: techUsers().map(u => [u.id, u.name + ' – ' + TH.auth.ROLE_LABEL[u.role]]) }) }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Phân công', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const a = m.data().assigneeId; ids.forEach(id => X.assignIncident(id, a)); m.close(); ok('Đã phân công ' + ids.length + ' sự cố'); } }); };
  const incMenu = (el, i) => U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => TH.go('#/maintenance/incidents/' + i.id) }, { label: 'Sửa', icon: 'pencil', disabled: !canManage(i) || ['done', 'cancelled'].includes(i.status), onClick: () => Fm.incident(i) }, '-', { label: 'Phân công', icon: 'user', disabled: !TH.auth.can('maintenance.assign') || ['done', 'cancelled'].includes(i.status), onClick: () => assignModal([i.id]) }, { label: 'Bắt đầu xử lý', icon: 'play', disabled: !canManage(i) || !['new', 'assigned'].includes(i.status), onClick: () => { X.startIncident(i.id); ok('Đã bắt đầu xử lý ' + i.code); } }, { label: 'Hoàn tất', icon: 'check-circle', disabled: !canManage(i) || ['done', 'cancelled'].includes(i.status), onClick: () => completeIncident(i) }, '-', { label: 'Hủy sự cố', icon: 'x-circle', danger: true, disabled: TH.auth.role() === 'kythuat' || !canManage(i) || ['done', 'cancelled'].includes(i.status), onClick: async () => { const r = await U.confirm({ title: 'Hủy sự cố ' + i.code + '?', body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Hủy sự cố', danger: true }); if (r) { X.cancelIncident(i.id, r.reason || 'Không rõ'); ok('Đã hủy'); } } }]);
  TH.pages.incidentMenu = incMenu; TH.pages.completeIncident = completeIncident;

  /* ================= #/maintenance – Sự cố ================= */
  TH.router.register('/maintenance', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Bảo trì & sự cố' }]);
    const tab = q.tab || 'incidents'; const period = TH.router.periodOf(q) || St.state.meta.period;
    const f = { s: q.s || '', buildingId: q.buildingId || '', status: q.status || '', priority: q.priority || '', assignee: q.assignee || '' };
    const all = St.all('incidents').filter(i => i.status !== 'cancelled' || f.status === 'cancelled'); const inPeriod = all.filter(i => !period || F.period(i.createdAt) === period || F.period(i.dueDate) === period);
    const rows = inPeriod.filter(i => (!f.s || F.norm(i.code + ' ' + i.category + ' ' + i.desc + ' ' + (Q.room(i.roomId).code || '')).includes(F.norm(f.s))) && (!f.buildingId || i.buildingId === f.buildingId) && (!f.status || (f.status === 'overdue' ? Q.incidentOverdue(i) : i.status === f.status)) && (!f.priority || i.priority === f.priority) && (!f.assignee || (f.assignee === 'me' ? i.assigneeId === TH.auth.session().userId : i.assigneeId === f.assignee))).sort((a, b) => F.cmp(a.code, b.code));
    const open = rows.filter(i => !['done', 'cancelled'].includes(i.status)).length, doing = rows.filter(i => ['assigned', 'in_progress'].includes(i.status)).length, overdue = rows.filter(Q.incidentOverdue).length, schedThisMonth = St.where('maintenanceSchedules', s => F.period(s.date) === period && s.status !== 'cancelled').length;
    const cost = Q.maintenanceCost(period); const catColors = Q.L.incCat;
    const upcoming = St.where('maintenanceSchedules', s => ['scheduled', 'in_progress'].includes(s.status) && s.date >= F.today()).sort((a, b) => F.cmp(a.date, b.date)).slice(0, 5);
    const periods = [...new Set(all.map(i => F.period(i.createdAt)).concat(['2026-10', '2026-09']))].sort().reverse();
    root.innerHTML = `${U.pageHead({ title: 'Bảo trì & sự cố', phase: 2, sub: 'Quản lý lịch bảo dưỡng, sự cố phát sinh và kiểm kê định kỳ.', acts: [U.btn({ label: 'Tạo sự cố', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !canManage(), attrs: { 'data-guide': 'incident-add' } }), U.btn({ label: 'Tạo lịch bảo dưỡng', icon: 'calendar', cls: 'btn-outline', act: 'add-sch', disabled: TH.auth.role() === 'kythuat' || !TH.auth.can('maintenance.schedule') })] })}
    ${U.tabs([{ key: 'incidents', label: 'Sự cố', count: all.filter(i => i.status !== 'cancelled').length }, { key: 'schedules', label: 'Lịch bảo dưỡng', count: St.where('maintenanceSchedules', s => ['scheduled', 'in_progress'].includes(s.status)).length }, { key: 'inventory', label: 'Kiểm kê hàng tháng', icon: 'calendar', phase: 3 }], tab, 'boxed')}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã sự cố, hạng mục, mô tả...', icon: 'search', attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.incident).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Mức độ ưu tiên', input: U.select({ name: 'priority', value: f.priority, all: 'Tất cả', options: Object.entries(Q.L.priority).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${all.length === 0 && tab === 'incidents' ? U.note('info', 'Chưa có dữ liệu sự cố trong sổ nguồn', 'Các workbook hiện tại không ghi nhận work order hoặc sự cố bảo trì (X-03, ngoài phạm vi Phase 1).') : ''}<div class="grid grid-4 mb16">${U.kpi({ label: 'Sự cố mở', value: open, cap: 'Cần xử lý', icon: 'tool', tone: 'red' })}${U.kpi({ label: 'Đang xử lý', value: doing, cap: 'Đang thực hiện sửa chữa', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Quá hạn', value: overdue, cap: 'Cần xử lý gấp', icon: 'alert-triangle', tone: 'red' })}${U.kpi({ label: 'Lịch bảo dưỡng tháng này', value: schedThisMonth, cap: 'Đã lên lịch', icon: 'calendar-check', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'incidents-related', cls: 'mb16', items: [
      { key: 'upcoming', title: 'Lịch bảo dưỡng sắp tới', icon: 'calendar', summary: upcoming.length ? upcoming.length + ' lịch sắp tới' : 'Chưa có lịch', meta: upcoming.length ? F.date(upcoming[0].date) + ' · ' + esc(upcoming[0].item) + ' · ' + esc(bName(upcoming[0].buildingId)) : '', actions: '<a class="link small" href="#/maintenance/schedules">Xem tất cả →</a>', body: upcoming.map(s => `<div class="up-row"><div class="date-tile"><b>${s.date.slice(8, 10)}</b><small>Th${Number(s.date.slice(5, 7))}</small></div><div class="grow"><b>${esc(s.item)}</b><div class="small muted">${I('building')} ${esc(bName(s.buildingId))}<br>${I('user')} ${esc(Q.userName(s.assigneeId))}</div></div>${Q.chip('schedule', Q.scheduleStatus(s) === 'scheduled' ? 'scheduled' : Q.scheduleStatus(s))}</div>`).join('') || '<div class="muted small">Chưa có lịch</div>' },
      { key: 'cost', title: 'Tổng chi phí sửa chữa tháng', icon: 'bar-chart', summary: F.vnd(cost.total) + ' VND', meta: F.periodLabel(period) + ' · ' + Object.keys(cost.by).length + ' hạng mục', actions: `<span class="small muted">${F.periodLabel(period)}</span>`, body: `<div class="row between"><div><b style="font-size:24px;color:var(--text)">${F.vnd(cost.total)}</b> ${U.delta(18)}<div class="small muted">Tổng chi phí (VND)</div></div></div>${C.donutLegend(Object.entries(cost.by).map(([k, v]) => ({ label: k, value: v, color: catColors[k] || '#94A3B8', text: F.vnd(v) + ' (' + F.pct(v, cost.total) + '%)' })), 140, F.short(cost.total).replace(' ', ''), 'VND')}` }
    ] })}
    ${U.card({ title: 'Danh sách sự cố', icon: 'list', actions: U.btn({ label: 'Phân công (đã chọn)', icon: 'user', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-assign', disabled: !TH.auth.can('maintenance.assign') }), body: null, id: 'it', attrs: 'data-guide="incidents-table"' })}`;
    const tbl = U.table(root.querySelector('#it'), { rows, unit: 'sự cố', selectable: true, colPrefsKey: 'incidents', cols: [{ key: 'code', label: 'Mã sự cố', render: i => U.link('#/maintenance/incidents/' + i.id, esc(i.code), 'bold') }, { key: 'room', label: 'Phòng / Tòa', render: i => i.roomId ? U.cell2(`<span class="blue">${esc(Q.room(i.roomId).code)}</span>`, esc(bName(i.buildingId))) : esc(bName(i.buildingId)) }, { key: 'category', label: 'Hạng mục', sortable: true }, { key: 'priority', label: 'Mức độ ưu tiên', sortable: true, sortVal: i => ({ urgent: 0, high: 1, medium: 2, low: 3 })[i.priority], render: i => Q.chip('priority', i.priority) }, { key: 'assignee', label: 'Người phụ trách', render: i => esc(i.assigneeId ? Q.userName(i.assigneeId) : '–') }, { key: 'dueDate', label: 'Hạn xử lý', sortable: true, render: dueCell }, { key: 'status', label: 'Trạng thái', sortable: true, render: incStatus }, { key: 'cost', label: 'Chi phí liên quan', num: true, sortable: true, render: i => F.vnd(i.cost || 0) }, { key: 'actions', label: 'Thao tác', render: i => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': i.id } }), U.moreBtn(i.id)]), hideable: false }] });
    U.onChange(root, { f: () => TH.router.applyFilter(Object.assign({ tab }, f, { period }), U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { tab: (el) => { if (el.dataset.key === 'schedules') return TH.go('#/maintenance/schedules'); if (el.dataset.key === 'inventory') return TH.go(TH.phase.on(3) ? '#/assets/inventory' : '#/coming-soon/assets'); TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, add: () => Fm.incident({}), 'add-sch': () => Fm.schedule({}), view: (el) => TH.go('#/maintenance/incidents/' + el.dataset.id), more: (el) => incMenu(el, St.get('incidents', el.dataset.id)), 'bulk-assign': () => { const ids = tbl.selected(); if (!ids.length) return U.toast('warn', 'Chọn sự cố cần phân công'); assignModal(ids); } });
    if (q.create === '1') { TH.router.replaceQuery(Object.assign({}, f, { create: '' })); Fm.incident({}); }
  }, { menu: 'maintenance', permission: 'maintenance.view', phase: 2, scopeKey: 'maintenance' });

  /* ================= #/maintenance/incidents/:id ================= */
  TH.router.register('/maintenance/incidents/:id', (root, p) => {
    const i = St.get('incidents', p.id); if (!i) { root.innerHTML = U.empty({ title: 'Không tìm thấy sự cố' }); return; }
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Bảo trì & sự cố', href: '#/maintenance' }, { label: i.code }]);
    const ups = St.where('incidentUpdates', u => u.incidentId === i.id).sort((a, b) => F.cmp(b.at, a.at)); const ex = i.expenseId ? St.get('expenses', i.expenseId) : null; const room = i.roomId ? Q.room(i.roomId) : null;
    const acts = []; if (!['done', 'cancelled'].includes(i.status) && canManage(i)) { if (['new', 'assigned'].includes(i.status)) acts.push(U.btn({ label: 'Bắt đầu xử lý', icon: 'play', cls: 'btn-outline', act: 'start', attrs: { 'data-guide': 'incident-start' } })); acts.push(U.btn({ label: 'Hoàn tất', icon: 'check', cls: 'btn-primary', act: 'done', attrs: { 'data-guide': 'incident-done-btn' } })); } acts.push(U.iconBtn('more', 'more', 'Thêm', {}, 'bordered'));
    root.innerHTML = `${U.pageHead({ back: '#/maintenance', title: esc(i.code), phase: 2, chips: ' ' + Q.chip('priority', i.priority, 'lg') + ' ' + (Q.incidentOverdue(i) ? Q.chip('incident', 'overdue', 'lg') : Q.chip('incident', i.status, 'lg')), sub: `${esc(i.category)} • ${room ? 'Phòng ' + esc(room.code) + ' - ' : ''}${esc(bName(i.buildingId))} • Tạo ${F.datetime(i.createdAt)} bởi ${esc(Q.userName(i.createdBy))}`, acts })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Ưu tiên', value: Q.label('priority', i.priority), cap: i.category, icon: 'flame', tone: i.priority === 'urgent' ? 'red' : i.priority === 'high' ? 'amber' : 'blue' })}${U.kpi({ label: 'Hạn xử lý', value: F.date(i.dueDate), cap: Q.incidentOverdue(i) ? 'Quá hạn ' + F.daysOverdue(i.dueDate) + ' ngày' : i.status === 'done' ? 'Hoàn tất ' + F.datetime(i.doneAt) : 'Còn ' + F.daysUntil(i.dueDate) + ' ngày', icon: 'clock', tone: Q.incidentOverdue(i) ? 'red' : 'green', valueCls: Q.incidentOverdue(i) ? 'red' : '' })}${U.kpi({ label: 'Người phụ trách', value: esc(i.assigneeId ? Q.userName(i.assigneeId) : 'Chưa phân công'), cap: i.assigneeId ? TH.auth.ROLE_LABEL[Q.user(i.assigneeId).role] || '' : '', icon: 'hard-hat', tone: 'purple' })}${U.kpi({ label: 'Chi phí', value: F.vnd(i.cost || 0), cap: ex ? 'Chi phí ' + ex.code : i.status === 'done' ? 'Không phát sinh chi phí' : 'Dự kiến', icon: 'coins', tone: 'amber' })}</div>
    <div class="two-col"><div class="side-stack">${U.card({ title: 'Thông tin sự cố', icon: 'alert-triangle', actions: canManage(i) && !['done', 'cancelled'].includes(i.status) ? U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }) : '', body: U.kv([['Mô tả', esc(i.desc)], ['Tòa nhà', U.link('#/buildings/' + i.buildingId, esc(bName(i.buildingId)))], ['Phòng', room ? U.link('#/rooms/' + room.id, esc(room.code)) : 'Khu vực chung'], ['Nhà cung cấp', esc(Q.vendor(i.vendorId).name || 'Tự xử lý')], ['Kết quả', esc(i.doneNote || '-')], ['Lý do hủy', esc(i.cancelReason || '-')]], 'one') })}${U.card({ title: 'Ảnh hiện trường (' + (i.photos || []).length + ')', icon: 'image', body: `<div class="photo-grid">${(i.photos || []).map(ph => `<div class="photo" title="${esc(ph)}"></div>`).join('') || '<span class="muted small">Chưa có ảnh</span>'}</div>` })}${ex ? U.card({ title: 'Chi phí liên kết', icon: 'credit-card', body: U.kv([['Mã chi phí', U.link('#/expenses?s=' + encodeURIComponent(ex.code) + '&period=all', esc(ex.code))], ['Nhóm', esc(ex.group)], ['Số tiền', F.vnd(ex.amount)], ['Ngày', F.date(ex.date)], ['Chứng từ', esc(ex.evidence)]], 'one') }) : ''}</div>
    <aside class="side-stack">${U.card({ title: 'Cập nhật xử lý', icon: 'history', actions: U.btn({ label: 'Thêm cập nhật', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'update', disabled: ['cancelled'].includes(i.status) }), body: U.timeline(ups.map(u => ({ when: F.datetime(u.at), title: ({ create: 'Tạo sự cố', assign: 'Phân công', start: 'Bắt đầu xử lý', done: 'Hoàn tất', cancel: 'Hủy', note: 'Cập nhật', edit: 'Chỉnh sửa' })[u.type] || u.type, sub: esc(u.note) + (u.by ? ' · ' + esc(Q.userName(u.by)) : ''), color: u.type === 'done' ? 'green' : u.type === 'cancel' ? 'red' : 'blue', fill: true }))) })}</aside></div>`;
    U.bind(root, { start: () => { X.startIncident(i.id); ok('Đã bắt đầu xử lý'); }, done: () => completeIncident(i), edit: () => Fm.incident(i), more: (el) => incMenu(el, i), update: () => { const m = U.modal({ title: 'Thêm cập nhật', size: 'sm', body: U.field({ label: 'Nội dung', req: true, input: U.textarea({ name: 'note', rows: 3 }) }) + `<div class="field mt12"><label>Ảnh</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng)' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); if (!d.note) throw new Error('Nhập nội dung cập nhật'); X.addIncidentUpdate(i.id, d.note, U.dzFiles(m.el, 'ph').map(f => f.name)); m.close(); ok('Đã thêm cập nhật'); } }); } });
  }, { menu: 'maintenance', permission: 'maintenance.view', phase: 2, scopeKey: 'maintenance', resource: { type: 'incident' } });

  /* ================= #/maintenance/schedules ================= */
  const completeSchedule = (s) => { const m = U.modal({ title: 'Hoàn thành ' + s.code, sub: s.item + ' · ' + bName(s.buildingId), body: `<div class="check-list mb12">${(s.checklist || []).map((c, i) => `<label class="chk"><input type="checkbox" name="ck_${i}" checked> <span>${esc(c.text)}</span></label>`).join('') || '<span class="muted small">Không có checklist</span>'}</div>${U.field({ label: 'Chi phí (VND)', input: U.money({ name: 'cost', value: s.cost || 0 }), help: 'Chi phí > 0 → tạo chi phí nhóm Sửa chữa gắn tòa' })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note' }), cls: 'mt12' })}<div class="field mt12"><label>Ảnh nghiệm thu</label>${U.dropzone({ name: 'ph', hint: 'JPG/PNG (mô phỏng)' })}</div>${U.note('info', '', 'Chu kỳ ' + Q.L.cycle[s.cycle] + ' → tự sinh lịch kế tiếp ' + F.date(F.addMonths(s.date, { monthly: 1, q: 3, h: 6, y: 12 }[s.cycle] || 1)))}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Hoàn thành', icon: 'check', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const cl = (s.checklist || []).map((c, i) => ({ text: c.text, done: !!d['ck_' + i] })); const r = X.completeSchedule(s.id, { checklist: cl, cost: d.cost, note: d.note, photos: U.dzFiles(m.el, 'ph').map(f => f.name) }); m.close(); ok('Đã hoàn thành ' + r.code, r.nextId ? 'Đã sinh lịch kế tiếp' : ''); } }); };
  const schMenu = (el, s) => { const st = Q.scheduleStatus(s); const can = TH.auth.can('maintenance.schedule'); U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => schPopover(s) }, { label: 'Sửa / Đổi lịch', icon: 'pencil', disabled: !can || ['done', 'cancelled'].includes(st), onClick: () => Fm.schedule(s) }, '-', { label: 'Bắt đầu', icon: 'play', disabled: !can || !['scheduled', 'due_soon', 'overdue'].includes(st), onClick: () => { X.startSchedule(s.id); ok('Đã bắt đầu ' + s.code); } }, { label: 'Hoàn thành', icon: 'check-circle', disabled: !can || ['done', 'cancelled'].includes(st), onClick: () => completeSchedule(s) }, '-', { label: 'Hủy lịch', icon: 'x-circle', danger: true, disabled: !can || ['done', 'cancelled'].includes(st), onClick: async () => { if (await U.confirm({ title: 'Hủy lịch ' + s.code + '?', text: 'Không sinh nhắc mới cho lịch này (AC-MNT-01-2).', ok: 'Hủy lịch', danger: true })) { X.cancelSchedule(s.id, 'Hủy thủ công'); ok('Đã hủy lịch'); } } }]); };
  const schPopover = (s) => { const st = Q.scheduleStatus(s); const m = U.modal({ title: s.code + ' – ' + s.item, sub: bName(s.buildingId) + ' · ' + F.date(s.date) + ' · ' + Q.L.cycle[s.cycle], size: 'sm', body: `${Q.chip('schedule', st, 'lg')}<div class="mt12">${U.kv([['Nhà cung cấp', esc(Q.vendor(s.vendorId).name || 'Tự thực hiện')], ['Phụ trách', esc(Q.userName(s.assigneeId))], ['Chi phí', F.vnd(s.cost || 0)], ['Ghi chú', esc(s.note || '-')]], 'one')}</div><div class="bold mt12 mb4">Checklist</div><div class="check-list">${(s.checklist || []).map(c => `<div class="it">${I(c.done ? 'check-circle' : 'minus-circle', c.done ? 'green' : 'muted')}<span>${esc(c.text)}</span></div>`).join('') || '<span class="muted small">Không có</span>'}</div>`, footer: (['scheduled', 'due_soon', 'overdue'].includes(st) ? U.btn({ label: 'Bắt đầu', icon: 'play', cls: 'btn-outline', act: 'start' }) : '') + (!['done', 'cancelled'].includes(st) ? U.btn({ label: 'Hoàn thành', icon: 'check', cls: 'btn-primary', act: 'done' }) : U.btn({ label: 'Đóng', act: 'close2' })) }); U.bind(m.el, { start: () => { X.startSchedule(s.id); m.close(); ok('Đã bắt đầu'); }, done: () => { m.close(); completeSchedule(s); }, close2: () => m.close() }); };
  TH.router.register('/maintenance/schedules', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Bảo trì & sự cố', href: '#/maintenance' }, { label: 'Lịch bảo dưỡng' }]);
    const month = q.month || St.state.meta.period; const f = { buildingId: q.buildingId || '', equip: q.equip || '', status: q.status || '', assigneeId: q.assigneeId || '' }; const view = q.view || 'month'; const sel = q.date || '';
    const anchor = sel || (F.today().slice(0, 7) === month ? F.today() : month + '-01'); const dow = (F.parseISO(anchor).getDay() + 6) % 7; const weekStart = F.addDays(anchor, -dow), weekEnd = F.addDays(anchor, 6 - dow); const inRange = (s) => view === 'week' ? s.date >= weekStart && s.date <= weekEnd : view === 'day' ? s.date === anchor : true;
    const all = St.all('maintenanceSchedules').map(s => Object.assign({}, s, { st: Q.scheduleStatus(s) }));
    const inMonth = all.filter(s => F.period(s.date) === month);
    const rows = (f.status === 'due_soon' || ['week', 'day'].includes(view) ? all : inMonth).filter(s => (!f.buildingId || s.buildingId === f.buildingId) && (!f.equip || s.equipType === f.equip) && (!f.status || s.st === f.status) && (!f.assigneeId || s.assigneeId === f.assigneeId) && inRange(s)).sort((a, b) => F.cmp(a.date, b.date) || F.cmp(a.code, b.code));
    const cnt = (k) => all.filter(s => s.st === k).length;
    const colorOf = (s) => ({ due_soon: '#F59E0B', overdue: '#DC2626', done: '#16A34A', in_progress: '#2563EB', scheduled: '#64748B', cancelled: '#94A3B8' })[s.st];
    const upcoming = all.filter(s => s.st === 'due_soon' || (s.st === 'scheduled' && F.daysUntil(s.date) <= 7 && F.daysUntil(s.date) >= 0)).sort((a, b) => F.cmp(a.date, b.date)).slice(0, 5);
    const byEq = {}; inMonth.forEach(s => byEq[s.equipType] = (byEq[s.equipType] || 0) + 1);
    const months = [...new Set(all.map(s => F.period(s.date)).concat([month]))].sort().reverse();
    root.innerHTML = `${U.pageHead({ title: 'Lịch bảo dưỡng', phase: 2, sub: 'Lập kế hoạch, theo dõi và quản lý lịch bảo dưỡng định kỳ cho toàn bộ thiết bị, hệ thống.', acts: [U.btn({ label: 'Tạo lịch bảo dưỡng', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: TH.auth.role() === 'kythuat' || !TH.auth.can('maintenance.schedule'), attrs: { 'data-guide': 'schedule-add' } })] })}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'month', value: month, options: months.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại thiết bị', input: U.select({ name: 'equip', value: f.equip, all: 'Tất cả thiết bị', options: EQUIP, attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.schedule).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người phụ trách', input: U.select({ name: 'assigneeId', value: f.assigneeId, all: 'Tất cả nhân viên', options: techUsers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Sắp đến hạn', value: cnt('due_soon'), cap: 'Trong 7 ngày tới (BR-16)', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Đang thực hiện', value: cnt('in_progress'), cap: 'Đang triển khai bảo dưỡng', icon: 'settings', tone: 'blue' })}${U.kpi({ label: 'Hoàn thành', value: inMonth.filter(s => s.st === 'done').length, cap: 'Trong tháng này', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Quá hạn', value: cnt('overdue'), cap: 'Cần xử lý gấp', icon: 'alert-triangle', tone: 'red' })}</div>
    ${U.relatedStrip({ id: 'schedules-related', cls: 'mb16', items: [
      { key: 'upcoming7', title: 'Công việc sắp tới (7 ngày)', icon: 'calendar', summary: upcoming.length ? upcoming.length + ' công việc' : 'Không có', meta: upcoming.length ? F.date(upcoming[0].date) + ' · ' + esc(upcoming[0].item) + ' · ' + esc(bName(upcoming[0].buildingId)) : 'Không có việc trong 7 ngày tới', actions: '<a class="link small" href="#/maintenance/schedules?status=due_soon">Xem tất cả →</a>', body: upcoming.map(s => `<div class="up-row"><div class="date-tile"><b>${s.date.slice(8, 10)}</b><small>Th${Number(s.date.slice(5, 7))}</small></div><div class="grow"><b>${esc(s.item)}</b><div class="small muted">${I('building')} ${esc(bName(s.buildingId))}<br>${I('tool')} ${esc(s.equipType)}<br>${I('user')} ${esc(Q.userName(s.assigneeId))}</div></div>${Q.chip('schedule', 'due_soon')}</div>`).join('') || '<div class="muted small">Không có việc trong 7 ngày tới</div>' },
      { key: 'equip', title: 'Thống kê loại thiết bị (tháng ' + Number(month.slice(5)) + ')', icon: 'pie-chart', summary: inMonth.length + ' lịch BD · ' + Object.keys(byEq).length + ' loại', meta: Object.keys(byEq).length ? 'Nhiều nhất: ' + esc(Object.entries(byEq).sort((a, b) => b[1] - a[1])[0][0]) : '', body: C.donutLegend(Object.entries(byEq).map(([k, v]) => ({ label: k, value: v, color: Q.L.equip[k] || '#94A3B8', text: v + ' (' + F.pct(v, inMonth.length) + '%)' })), 140, String(inMonth.length), 'lịch BD') }
    ] })}
    <div class="side-stack">${U.card({ title: 'Lịch bảo dưỡng ' + F.periodLabel(month).toLowerCase(), icon: 'calendar-days', actions: `<div class="row gap12"><span class="row gap4">${U.iconBtn('chevron-left', 'prev', 'Tháng trước')}${U.iconBtn('chevron-right', 'next', 'Tháng sau')}${U.btn({ label: 'Hôm nay', size: 'btn-sm', cls: 'btn-outline', act: 'today' })}</span><div class="seg">${['month', 'week', 'day', 'list'].map(v => U.btn({ label: { month: 'Tháng', week: 'Tuần', day: 'Ngày', list: 'Danh sách' }[v], cls: view === v ? 'on' : '', act: 'view', attrs: { 'data-v': v } })).join('')}</div></div>`, body: view === 'list' ? '<div class="muted small">Chế độ danh sách – xem bảng bên dưới.</div>' : view === 'day' ? `<div class="bold mb8">${F.date(anchor)}</div><div class="mini-list">${rows.filter(s => s.st !== 'cancelled').map(s => `<div class="it" style="cursor:pointer" data-act="cal-more" data-id="${s.id}"><i style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${colorOf(s)}"></i><div class="grow"><b>${esc(s.item)}</b><small>${esc(bName(s.buildingId))} · ${esc(Q.userName(s.assigneeId))}</small></div>${Q.chip('schedule', s.st)}</div>`).join('') || '<div class="muted small">Không có lịch trong ngày</div>'}</div><div class="row gap4 mt8">${U.btn({ label: 'Ngày trước', size: 'btn-xs', cls: 'btn-outline', act: 'day-prev' })}${U.btn({ label: 'Ngày sau', size: 'btn-xs', cls: 'btn-outline', act: 'day-next' })}</div>` : `<div class="cal-wrap">${U.calendar({ month: view === 'week' ? anchor.slice(0, 7) : month, selected: sel, weekOf: view === 'week' ? anchor : '', events: (view === 'week' ? all.filter(inRange) : inMonth).filter(s => s.st !== 'cancelled').map(s => ({ date: s.date, label: s.item, color: colorOf(s), id: s.id })) })}</div>${view === 'week' ? `<div class="row gap4 mt8 small muted">Tuần ${F.date(weekStart)} – ${F.date(weekEnd)} ${U.btn({ label: 'Tuần trước', size: 'btn-xs', cls: 'btn-outline', act: 'week-prev' })}${U.btn({ label: 'Tuần sau', size: 'btn-xs', cls: 'btn-outline', act: 'week-next' })}</div>` : ''}<div class="row gap12 wrap mt8 xs muted">${[['Sắp đến hạn', '#F59E0B'], ['Quá hạn', '#DC2626'], ['Đang làm', '#2563EB'], ['Hoàn thành', '#16A34A'], ['Đã lên lịch', '#64748B']].map(([l, c]) => `<span><i style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${c}"></i> ${l}</span>`).join('')}${sel ? ` · Đang chọn ${F.date(sel)} <a class="link" data-act="clear-date">bỏ chọn</a>` : ''}</div>` })}
      ${U.card({ title: 'Danh sách lịch bảo dưỡng', icon: 'list', actions: `<div class="row">${U.btn({ label: 'Xuất dữ liệu', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export' })}${U.btn({ label: 'Tùy chỉnh cột', icon: 'settings', size: 'btn-sm', cls: 'btn-outline', act: 'cols' })}</div>`, body: null, id: 'sct', attrs: 'data-guide="schedules-table"' })}</div>`;
    const cols = [{ key: 'code', label: 'Mã lịch', render: s => `<span class="blue bold">${esc(s.code)}</span>` }, { key: 'item', label: 'Hạng mục', sortable: true }, { key: 'b', label: 'Tòa nhà', render: s => esc(bName(s.buildingId)) }, { key: 'cycle', label: 'Chu kỳ', render: s => Q.L.cycle[s.cycle] || s.cycle }, { key: 'date', label: 'Ngày dự kiến', sortable: true, render: s => `<span class="${s.st === 'overdue' ? 'red bold' : ''}">${F.date(s.date)}</span>` }, { key: 'vendor', label: 'Nhà cung cấp', render: s => esc(Q.vendor(s.vendorId).name || 'Tự thực hiện') }, { key: 'assignee', label: 'Người phụ trách', render: s => esc(Q.userName(s.assigneeId)) }, { key: 'st', label: 'Trạng thái', sortable: true, render: s => Q.chip('schedule', s.st) }, { key: 'actions', label: 'Thao tác', render: s => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': s.id } }), U.moreBtn(s.id)]), hideable: false }];
    const tbl = U.table(root.querySelector('#sct'), { rows, unit: 'lịch bảo dưỡng', selectable: true, colPrefsKey: 'schedules', cols });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({ view, date: sel }, d)); TH.router.refresh(); } });
    root.addEventListener('keydown', (e) => { if (e.target.closest('.cal-cell') && ['ArrowLeft', 'ArrowRight'].includes(e.key)) { const cells = [...root.querySelectorAll('.cal-cell')]; const i = cells.indexOf(e.target.closest('.cal-cell')); const nx = cells[i + (e.key === 'ArrowRight' ? 1 : -1)]; if (nx) nx.focus(); e.preventDefault(); } if (e.key === 'Enter' && e.target.closest('.cal-cell')) e.target.closest('.cal-cell').click(); });
    const goMonth = (n) => { TH.router.replaceQuery(Object.assign({}, f, { month: F.addMonths(month + '-01', n).slice(0, 7), view, date: '' })); TH.router.refresh(); };
    U.bind(root, { reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, add: () => Fm.schedule({}), prev: () => goMonth(-1), next: () => goMonth(1), today: () => { TH.router.replaceQuery(Object.assign({}, f, { month: F.today().slice(0, 7), view, date: F.today() })); TH.router.refresh(); }, view: (el) => { if (el.dataset.v) { TH.router.replaceQuery(Object.assign({}, f, { month, view: el.dataset.v, date: sel })); TH.router.refresh(); } else schPopover(St.get('maintenanceSchedules', el.dataset.id)); }, 'cal-pick': (el) => { TH.router.replaceQuery(Object.assign({}, f, { month: el.dataset.date.slice(0, 7), view: view === 'month' ? 'day' : view, date: el.dataset.date })); TH.router.refresh(); }, 'week-prev': () => { const d = F.addDays(anchor, -7); TH.router.replaceQuery(Object.assign({}, f, { month: d.slice(0, 7), view, date: d })); TH.router.refresh(); }, 'week-next': () => { const d = F.addDays(anchor, 7); TH.router.replaceQuery(Object.assign({}, f, { month: d.slice(0, 7), view, date: d })); TH.router.refresh(); }, 'day-prev': () => { const d = F.addDays(anchor, -1); TH.router.replaceQuery(Object.assign({}, f, { month: d.slice(0, 7), view, date: d })); TH.router.refresh(); }, 'day-next': () => { const d = F.addDays(anchor, 1); TH.router.replaceQuery(Object.assign({}, f, { month: d.slice(0, 7), view, date: d })); TH.router.refresh(); }, 'cal-more': (el) => schPopover(St.get('maintenanceSchedules', el.dataset.id)), 'clear-date': () => { TH.router.replaceQuery(Object.assign({}, f, { month, view: 'month', date: '' })); TH.router.refresh(); }, more: (el) => schMenu(el, St.get('maintenanceSchedules', el.dataset.id)), cols: (el) => U.columnMenu(el, tbl, cols), export: () => { F.download('lich-bao-duong-' + month + '.csv', F.csv(rows.map(s => [s.code, s.item, bName(s.buildingId), Q.L.cycle[s.cycle], s.date, Q.vendor(s.vendorId).name || '', Q.userName(s.assigneeId), Q.label('schedule', s.st)]), ['Mã', 'Hạng mục', 'Tòa', 'Chu kỳ', 'Ngày', 'NCC', 'Phụ trách', 'Trạng thái']), 'text/csv'); ok('Đã xuất dữ liệu'); } });
  }, { menu: 'tasks', permission: 'maintenance.view', phase: 2, scopeKey: 'tasks' });

  /* ================= Tab Nhà cung cấp trong Danh mục (khi P2 bật) ================= */
  TH.pages.vendorsTab = (root, head, tabs) => {
    const canEdit = TH.auth.can('manageCatalog'); const items = St.all('vendors');
    root.innerHTML = head + tabs + U.card({ title: 'Nhà cung cấp bảo trì ' + TH.phase.tag(2), sub: 'Danh mục NCC dùng cho sự cố và lịch bảo dưỡng', actions: U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add', disabled: !canEdit }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Tên</th><th>Lĩnh vực</th><th>Liên hệ</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(v => `<tr><td><b>${esc(v.name)}</b></td><td>${esc(v.field || '')}</td><td>${esc(v.contact || '')}</td><td>${U.chip(v.status === 'active' ? 'Đang hợp tác' : 'Ngừng', v.status === 'active' ? 'green' : 'gray')}</td><td class="tr">${U.iconBtn('pencil', 'edit', 'Sửa', { 'data-id': v.id, disabled: !canEdit })}${U.iconBtn('trash', 'rm', 'Xóa', { 'data-id': v.id, disabled: !canEdit })}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Chưa có</td></tr>'}</tbody></table>` });
    const edit = (v = {}) => { const m = U.modal({ title: v.id ? 'Sửa nhà cung cấp' : 'Thêm nhà cung cấp', size: 'sm', body: `<div class="col gap12">${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name', value: v.name || '' }) })}${U.field({ label: 'Lĩnh vực', input: U.select({ name: 'field', value: v.field || '', options: ['Thang máy', 'Điều hòa / Máy bơm', 'Vệ sinh / Máy giặt chung', 'PCCC', 'Máy lọc nước', 'Điện', 'Nước', 'Khác'] }) })}${U.field({ label: 'Liên hệ', input: U.input({ name: 'contact', value: v.contact || '' }) })}${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: v.status || 'active', options: [['active', 'Đang hợp tác'], ['inactive', 'Ngừng']] }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); d.id = v.id; X.saveVendor(d); m.close(); ok('Đã lưu nhà cung cấp'); } }); };
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'add-svc': () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); }, apply: () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); }, add: () => edit(), edit: (el) => edit(St.get('vendors', el.dataset.id)), rm: async (el) => { if (await U.confirm({ title: 'Xóa nhà cung cấp?', ok: 'Xóa', danger: true })) { X.removeVendor(el.dataset.id); ok('Đã xóa'); } } });
  };
})(window.TH);
