/* Phase 1 (spec v1.8 §4.13, §12.10) – Điện / Nước theo kỳ: kỳ → tòa → phòng → công tơ → chỉ số cũ/mới → sản lượng → ảnh; nhập từng dòng, import, copy kỳ trước, validate (mới<cũ, thiếu, trùng kỳ, bất thường), xác nhận, mở lại, export, lịch sử theo kỳ. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc, moneyCommon = n => F.vnd(Number(n)), perPerson = n => Number(n).toLocaleString('vi-VN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  TH.router.register('/meters', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Điện / Nước' }]);
    const period = q.period || St.state.meta.period; const f = { period, buildingId: q.buildingId || '', roomId: q.roomId || '', view: q.view || 'entry', issue: q.issue || '' };
    const canEdit = TH.auth.can('meterReadings.manage'); const locked = Q.periodLocked(period); const bp = Q.billingPeriod(period);
    const rows0 = Q.meterRows(period, { buildingId: f.buildingId, roomId: f.roomId }); const rows = rows0.filter(x => x.contract || x.electric.cur || x.water.cur).filter(x => !f.issue || x.electric.issues.includes(f.issue) || x.water.issues.includes(f.issue));
    const stats = { rooms: rows.length, entered: rows.filter(x => x.electric.cur && (x.water.cur || x.water.notApplicable)).length, missing: rows.filter(x => x.electric.issues.includes('missing') || x.water.issues.includes('missing')).length, issues: rows.filter(x => x.electric.issues.some(i => i !== 'missing') || x.water.issues.some(i => i !== 'missing')).length, confirmed: rows.filter(x => ['confirmed', 'used'].includes((x.electric.cur || {}).status) && (x.water.notApplicable || ['confirmed', 'used'].includes((x.water.cur || {}).status))).length, photos: rows.filter(x => (x.electric.cur || {}).photo || (x.water.cur || {}).photo).length };
    const periods = [...new Set([St.state.meta.period].concat(Q.meterPeriods(), Q.billingPeriods().map(b => b.code)))].sort().reverse();
    const issueChips = (m) => m.issues.map(i => { const d = Q.METER_ISSUE[i]; return U.chip(d[0], d[1]); }).join(' ');
    const stChip = (m) => m.cur ? Q.chip('readingStatus', m.cur.status) : '<span class="muted xs">chưa nhập</span>';
    const cell = (x, type) => { const m = x[type]; if (m.notApplicable) return '<div><b>Tính theo người</b> · ' + esc(m.people || '') + ' người × 120.000đ ' + TH.params.chip('P-31') + '</div><div class="xs muted">Workbook không có chỉ số nước công tơ cho phòng này</div>'; const ro = !canEdit || locked || (m.cur && m.cur.status === 'used'); return `<div class="row gap4" style="align-items:center"><span class="xs muted" style="width:52px">${m.prevValue}</span><span class="muted">→</span><input class="inp sm" type="number" style="width:84px" value="${m.cur ? m.cur.curr : ''}" data-on="rd" data-room="${x.room.id}" data-type="${type}" ${ro ? 'readonly' : ''} placeholder="mới"><span class="xs" style="width:60px">${m.use != null ? '= <b>' + m.use + '</b> ' + (type === 'electric' ? 'kWh' : 'm³') : ''}</span>${m.cur && m.cur.photo ? '<span class="chip green xs" title="' + esc(m.cur.photo) + '">' + I('image') + '</span>' : (canEdit && !locked ? U.iconBtn('camera', 'photo', 'Đính ảnh công tơ', { 'data-room': x.room.id, 'data-type': type }) : '')}</div><div class="xs">${stChip(m)} ${issueChips(m)}${m.prevUse != null ? ' <span class="muted">kỳ trước ' + m.prevUse + '</span>' : ''}${m.cur && m.cur.status !== 'draft' && ['admin', 'accountant', 'qltong'].includes(TH.auth.role()) && !locked ? ' <a class="link" data-act="reopen" data-id="' + m.cur.id + '">mở lại</a>' : ''}</div>`; };
    root.innerHTML = `${U.pageHead({ title: 'Điện / Nước theo kỳ', chips: bp ? ' ' + Q.chip('billingPeriod', bp.status) : '', sub: 'Chọn kỳ → tòa → phòng → công tơ → chỉ số cũ/mới → sản lượng → ảnh. Validate: chỉ số mới thấp hơn cũ, thiếu chỉ số, trùng kỳ, tiêu thụ bất thường (±50% so kỳ trước). Chỉ số đã dùng phát hành hóa đơn không sửa âm thầm (§12.10.3).', acts: [U.btn({ label: 'Import Excel', icon: 'upload', cls: 'btn-outline', act: 'import', disabled: !canEdit || locked }), U.btn({ label: 'Copy chỉ số kỳ trước', icon: 'copy', cls: 'btn-outline', act: 'copy', disabled: !canEdit || locked || !f.buildingId, title: f.buildingId ? '' : 'Chọn tòa trước' }), U.btn({ label: 'Xác nhận chỉ số', icon: 'check-circle', cls: 'btn-primary', act: 'confirm', disabled: !canEdit || locked, attrs: { 'data-guide': 'meter-confirm' } }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
      ${locked ? U.note('warn', 'Kỳ ' + F.periodLabel(period) + ' đã khóa', 'Chỉ xem; mở lại kỳ tại Tài chính → Kỳ hóa đơn nếu cần sửa.') : ''}
      <div class="grid grid-4 mb16">${U.kpi({ label: 'Phòng cần chốt', value: stats.rooms, cap: stats.entered + ' đã đủ chỉ số cần nhập', icon: 'door', tone: 'blue' })}${U.kpi({ label: 'Thiếu chỉ số', value: stats.missing, cap: 'HĐ hiệu lực chưa có chỉ số', icon: 'alert-circle', tone: stats.missing ? 'red' : 'green' })}${U.kpi({ label: 'Cần kiểm tra', value: stats.issues, cap: 'mới thấp hơn cũ · trùng kỳ · bất thường', icon: 'alert-triangle', tone: stats.issues ? 'amber' : 'green' })}${U.kpi({ label: 'Đã xác nhận', value: stats.confirmed, cap: stats.photos + ' phòng có ảnh', icon: 'check-circle', tone: 'green' })}</div>
      ${U.tabs([{ key: 'entry', label: 'Nhập & xác nhận' }, { key: 'history', label: 'Lịch sử theo kỳ' }], f.view)}
      ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: f.roomId, all: 'Tất cả phòng', options: (f.buildingId ? Q.roomsOf(f.buildingId) : []).map(r => [r.id, r.code]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Lỗi', input: U.select({ name: 'issue', value: f.issue, all: 'Tất cả', options: Object.entries(Q.METER_ISSUE).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
      <div id="body"></div>`;
    const body = root.querySelector('#body');
    if (f.view === 'entry') {
      body.innerHTML = U.card({ title: `Chỉ số kỳ ${F.periodLabel(period)} <span class="muted" style="font-weight:400">(${rows.length} phòng)</span>`, sub: 'Nhập chỉ số mới rồi rời ô để lưu nháp; bấm Xác nhận chỉ số để chốt cho tòa/kỳ', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Tòa / phòng</th><th>Khách / HĐ</th><th>Công tơ</th><th>Điện: cũ → mới</th><th>Nước: cũ → mới</th><th>Ngày chốt · người nhập</th></tr></thead><tbody>${rows.map(x => `<tr class="${x.electric.issues.length || x.water.issues.length ? 'row-warn' : ''}"><td>${U.cell2(U.link('#/rooms/' + x.room.id + '?tab=meters', esc(x.room.code), 'bold'), esc(x.building.name))}</td><td class="xs">${x.tenant ? esc(x.tenant.name) + '<br>' + U.link('#/contracts/' + x.contract.id, esc(x.contract.code)) : '<span class="muted">Không có HĐ</span>'}</td><td class="xs">${[x.electric.meter, x.water.meter].filter(Boolean).map(m => esc(m.code)).join('<br>') || '<span class="muted">-</span>'}</td><td>${cell(x, 'electric')}</td><td>${cell(x, 'water')}</td><td class="xs">${[x.electric.cur, x.water.cur].filter(Boolean).map(m => F.date(m.readingDate || '') + (m.enteredBy ? ' · ' + esc(Q.userName(m.enteredBy)) : '')).filter((v, i, a) => a.indexOf(v) === i).join('<br>') || '-'}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Không có phòng cần chốt trong phạm vi lọc</td></tr>'}</tbody></table>` });
    } else {
      const hist = St.rawAll('meterReadings').filter(m => m && (!f.buildingId || Q.room(m.roomId).buildingId === f.buildingId) && (!f.roomId || m.roomId === f.roomId)).sort((a, b) => F.cmp(b.period || b.readingDate || '', a.period || a.readingDate || '') || F.cmp(Q.room(a.roomId).code, Q.room(b.roomId).code));
      const byP = {}; hist.forEach(m => { const k = m.period || F.period(m.readingDate); (byP[k] = byP[k] || []).push(m); });
      body.innerHTML = Object.keys(byP).sort().reverse().slice(0, 6).map(k => U.card({ title: 'Kỳ ' + F.periodLabel(k) + ' (' + byP[k].length + ' chỉ số)', icon: 'history', collapsible: true, collapseKey: 'mt-' + k, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Phòng</th><th>Loại</th><th>Kiểu</th><th class="num">Cũ</th><th class="num">Mới</th><th class="num">Sản lượng</th><th>Ngày chốt</th><th>Ảnh</th><th>Trạng thái</th><th>Người nhập</th></tr></thead><tbody>${byP[k].slice(0, 200).map(m => `<tr><td>${U.link('#/rooms/' + m.roomId + '?tab=meters', esc(Q.room(m.roomId).code))} <span class="xs muted">${esc(Q.building(Q.room(m.roomId).buildingId).name)}</span></td><td>${m.type === 'electric' ? 'Điện' : 'Nước'}</td><td>${Q.chip('readingType', m.readingType || 'PERIOD')}</td><td class="num">${m.prev}</td><td class="num">${m.curr}</td><td class="num">${(m.readingType || 'PERIOD') === 'OPENING' ? '–' : m.curr - m.prev}</td><td>${m.readingDate ? F.date(m.readingDate) : '-'}</td><td class="xs">${m.photo ? I('image') + ' ' + esc(m.photo) : '-'}</td><td>${Q.chip('readingStatus', m.status || 'draft')}</td><td class="xs">${m.enteredBy ? esc(Q.userName(m.enteredBy)) : (m.sourceOcr ? 'OCR' : '')}</td></tr>`).join('')}</tbody></table>` })).join('') || U.empty({ title: 'Chưa có lịch sử chỉ số' });
    }
    if (f.view === 'entry' && period === '2026-09' && (!f.buildingId || Q.building(f.buildingId).code === 'G1')) {
      const common = St.rawAll('meterReadings').filter(x => x.type === 'common-electric' && x.period === period && Q.building(x.buildingId).code === 'G1');
      body.insertAdjacentHTML('beforeend', U.card({ title: 'Điện chung G1 · nguồn sổ 09/2026', cls: 'mt16', sub: 'Ba cách ghi trong cùng tòa; số đã tính không tự cộng vào Tổng dịch vụ khi sổ gốc chưa cộng. ' + TH.params.chip('P-13') + TH.params.chip('P-30'), body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Cụm phòng</th><th>Cách ghi</th><th class="num">CS cũ → mới</th><th class="num">Sản lượng</th><th class="num">Đơn giá</th><th class="num">Thành tiền</th><th class="num">Số người</th><th class="num">Mỗi người</th></tr></thead><tbody>${common.map(x => `<tr><td>${esc((x.sourceRooms||[]).join(', ')||x.sourceLabel||'—')}</td><td>${x.scope==='DIRECT_ENTRY'?'Ghi thẳng':x.scope==='FLOOR_GROUP'?'Cụm tầng':'Chia theo người'}</td><td class="num">${x.prev==null?'—':F.vnd(x.prev)+' → '+F.vnd(x.curr)}</td><td class="num">${x.usage}</td><td class="num">${moneyCommon(x.unitPrice)}</td><td class="num"><b>${moneyCommon(x.amount)}</b></td><td class="num">${x.people??'—'}</td><td class="num">${x.people?perPerson(x.amount/x.people):'Ghi thẳng'}</td></tr>`).join('')}</tbody></table></div>` }));
    }
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); if (d.buildingId !== f.buildingId) d.roomId = ''; TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); }, rd: (el) => { try { if (el.value === '') return; X.saveMeterRow({ roomId: el.dataset.room, period, type: el.dataset.type, curr: Number(el.value) }); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); TH.router.refresh(); } } });
    U.bind(root, {
      tab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { view: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({ period }); TH.router.refresh(); },
      import: () => TH.go('#/settings/import?type=meter'), copy: () => { try { const n = X.copyPrevReadings(period, f.buildingId); U.toast('ok', 'Đã copy chỉ số kỳ trước cho ' + n + ' công tơ', 'Sản lượng = 0 cho đến khi nhập chỉ số mới'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
      confirm: async () => { if (!(await U.confirm({ title: 'Xác nhận chỉ số kỳ ' + F.periodLabel(period) + '?', text: (f.buildingId ? 'Tòa ' + Q.building(f.buildingId).name + '. ' : 'Tất cả tòa trong phạm vi. ') + 'Chỉ số có lỗi mới<cũ / trùng kỳ sẽ bị bỏ qua; bất thường vẫn xác nhận (đã cảnh báo).' }))) return; try { const r = X.confirmReadings(period, { buildingId: f.buildingId || null }); U.toast(r.skipped.length ? 'warn' : 'ok', 'Đã xác nhận ' + r.confirmed + ' chỉ số', r.skipped.length ? 'Bỏ qua: ' + r.skipped.join(', ') : ''); TH.router.refresh(); } catch (e) { U.toast('err', 'Không xác nhận được', e.message); } },
      reopen: (el) => { const m = U.modal({ title: 'Mở lại chỉ số', size: 'sm', body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Mở lại', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { X.reopenReading(el.dataset.id, m.data().reason); m.close(); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      photo: (el) => { const m = U.modal({ title: 'Ảnh công tơ ' + Q.room(el.dataset.room).code, size: 'sm', body: U.dropzone({ name: 'ph', hint: 'JPG/PNG ảnh chụp công tơ (mô phỏng)', multiple: false, accept: '.jpg,.jpeg,.png' }), footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu ảnh', cls: 'btn-primary', act: 's' }) }); U.bindDropzones(m.el, () => {}); U.bind(m.el, { c: () => m.close(), s: () => { const files = U.dzFiles(m.el, 'ph'); const name = files[0] ? files[0].name : 'congto-' + Q.room(el.dataset.room).code + '-' + period + '.jpg'; try { let cur = St.one('meterReadings', x => x.roomId === el.dataset.room && x.period === period && x.type === el.dataset.type && x.readingType !== 'OPENING'); if (!cur) { const row = rows.find(x => x.room.id === el.dataset.room); cur = X.saveMeterRow({ roomId: el.dataset.room, period, type: el.dataset.type, curr: row[el.dataset.type].prevValue }); } X.attachReadingPhoto(cur.id, name); m.close(); U.toast('ok', 'Đã lưu ảnh ' + name); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); },
      export: () => X.exportCsv({ fileName: 'dien-nuoc-' + period + '.csv', entity: 'meterReadings', filters: f, header: ['Tòa', 'Phòng', 'Khách', 'Điện cũ', 'Điện mới', 'Điện SL', 'Nước cũ', 'Nước mới', 'Nước SL', 'Trạng thái điện', 'Trạng thái nước', 'Lỗi'], rows: rows.map(x => [x.building.name, x.room.code, x.tenant ? x.tenant.name : '', x.electric.prevValue, x.electric.cur ? x.electric.cur.curr : '', x.electric.use == null ? '' : x.electric.use, x.water.prevValue, x.water.cur ? x.water.cur.curr : '', x.water.use == null ? '' : x.water.use, (x.electric.cur || {}).status || '', (x.water.cur || {}).status || '', x.electric.issues.concat(x.water.issues).join('|')]) }),
    });
  }, { menu: 'meters', permission: 'invoices.view' });
})(window.TH);

