/* Phase 2 – Trích xuất hợp đồng (OCR): Tải file → Trích xuất → Review → Tạo hợp đồng (FR-CUS-02, BR-03)
   Template: "HỢP ĐỒNG CHO THUÊ PHÒNG" (HĐ mới của Linh, 4 trang). Parser thật tại core/ocr-parser.js; PDF text-based đọc bằng pdf.js, ảnh scan chưa hỗ trợ. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, P = TH.ocrParser, esc = F.esc;
  const O = {};
  /* File mẫu: HĐ của Linh đã điền cho một phòng Sẵn sàng của tòa Sunrise; 5 trường cố tình sai (tên không dấu, SĐT thiếu số, mã phòng thiếu dấu chấm, cọc lệch giá, ngày kết thúc sai năm) */
  O.sampleSpec = () => {
    const b = St.one('buildings', x => x.name === 'Tòa Sunrise') || St.where('buildings', x => !x.stub)[0]; const room = St.where('rooms', r => r.status === 'ready' && r.buildingId === b.id).sort((a, c) => a.code.localeCompare(c.code))[0] || St.where('rooms', r => r.status === 'ready')[0] || St.all('rooms')[0];
    const price = room.price, deposit = price, depositWrong = price + 500000;
    return { contractNo: '12/2026/HĐTP', signDate: '01/11/2026', tenantName: 'Nguyễn Thị Hương', tenantNameWrong: 'NGUYEN THI HUONG', dob: '12/05/1996', idNumber: '023456789012', idPlace: 'Cục Cảnh Sát', phone: '0938765432', phoneWrong: '093876543', address: '456 Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh', buildingName: b.name, buildingAddress: b.address, roomCode: room.code, roomCodeWrong: room.code.replace(/\./g, ''), roomType: room.type, area: room.area, start: '01/11/2026', end: '31/10/2027', endWrong: '31/10/2028', noticeDate: '01/10/2027', price, deposit, depositWrong, paidBefore: 1000000, paidAtSign: price - 1000000, elecIndex: 1250, waterIndex: 320, room };
  };
  const ASSET_ROWS = [['Giường', '1', 'Bình thường', 'Điều hòa và điều khiển', '1', 'Bình thường'], ['Tủ quần áo', '1', 'Bình thường', 'Bình nóng lạnh', '1', 'Bình thường'], ['Chăn ga gối', '1', 'Bình thường', 'Máy giặt', '', ''], ['Đệm', '1', 'Bình thường', 'Máy hút mùi', '', ''], ['Rèm', '1', 'Bình thường', 'Tủ lạnh', '1', 'Bình thường'], ['Bàn', '1', 'Bình thường', 'Thiết bị mạng', '1', 'Bình thường'], ['Ghế', '2', 'Bình thường', 'Quạt trần', '', ''], ['Kệ bếp, chậu rửa', '1', 'Bình thường', 'Bóng điện', '4', 'Bình thường'], ['Tủ bếp trên, dưới', '1', 'Bình thường', 'Ổ cắm điện', '6', 'Bình thường'], ['Cửa nhà vệ sinh', '1', 'Bình thường', 'Bồn rửa mặt', '1', 'Bình thường'], ['Cửa ra vào', '1', 'Bình thường', 'Gương', '1', 'Bình thường'], ['Cửa ban công', '1', 'Bình thường', 'Vòi sen, vòi xịt, bồn cầu', '1 bộ', 'Bình thường'], ['Cửa sổ', '1', 'Bình thường', 'Công tơ điện', '1', 'Bình thường'], ['Tường', '', 'Sạch', 'Đồng hồ nước', '1', 'Bình thường'], ['Đồ décor:', '', '', 'Chìa khóa phòng, cổng', '2', 'Bình thường']];
  O.sampleText = () => {
    const s = O.sampleSpec(); const v = (x) => F.vnd(x).replace(/,/g, '.') + 'đ';
    const L = ['CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM', 'Độc lập – Tự do - Hạnh phúc', '***', 'HỢP ĐỒNG CHO THUÊ PHÒNG', 'HĐ số: ' + s.contractNo, 'Hôm nay, ngày 01 tháng 11 năm 2026', 'Tại địa chỉ: ' + s.buildingAddress, 'Chúng tôi gồm:', 'BÊN CHO THUÊ PHÒNG (BÊN A):', '1. Đại diện chủ nhà (Ông/Bà): ĐỖ THỊ THÙY LINH', '- Số CMT/CCCD: 027303005504', 'Nơi cấp: Cục Cảnh Sát', '- Hộ khẩu thường trú: PHƯƠNG LIỄU - QUẾ VÕ - BẮC NINH', '- SĐT : 0364316435', '2 . BÊN THUÊ PHÒNG (BÊN B):', '- Họ tên đầy đủ: ' + s.tenantNameWrong + ' Ngày sinh: ' + s.dob, '- Các số điện thoại đang dùng: ' + s.phoneWrong, '- Số CCCD: ' + s.idNumber + ' Nơi cấp: ' + s.idPlace, '- Hộ khẩu thường trú (ghi chi tiết): ' + s.address, 'ĐIỀU 1: ĐỐI TƯỢNG CHO THUÊ VÀ MỤC ĐÍCH SỬ DỤNG', '1.1. Bên A đồng ý cho bên B thuê phòng số: ' + s.roomCodeWrong, '1.2. Bên B sử dụng phòng trên với mục đích để ở. Số lượng: 2 người. Số người tối đa là 2 người, Nếu bên B thêm người phải thông báo trước và phải được sự đồng ý của bên A. Nếu người mới đến ở quá 5 ngày thì tính thêm người. Trường hợp bên B muốn chuyển nhượng hợp đồng cho người khác phải được sự đồng ý của bên A. Số xe: 1', 'ĐIỀU 2: BÀN GIAO TÀI SẢN', '2.1. Tài sản sử dụng và bảo quản chung', 'Tất cả các tài sản chung bao gồm: thang bộ, thang máy, sân phơi, máy bơm, máy giặt chung (nếu có), hệ thống chiếu sáng, bể và bồn chứa nước, hệ thống thoát nước, hệ thống cây xanh, nhà để xe, camera đều sử dụng bình thường.', '2.2. Tài sản trong phòng', 'Tất cả tài sản dưới đây đã bàn giao cho bên B đều hoạt động bình thường.', 'Tên nội thất', 'Số', 'lượng', 'Tình trạng', 'Tên thiết bị', 'Số', 'lượng', 'Tình trạng'];
    ASSET_ROWS.forEach(r => r.forEach(c => L.push(c || ' ')));
    L.push('ĐIỀU 3: THỜI ĐIỂM GIAO NHẬN PHÒNG VÀ THỜI HẠN CHO THUÊ', '3.1. Thời điểm giao nhận phòng ở là ngày ' + s.start, '3.2. Thời điểm tính tiền phòng ở là ngày ' + s.start, '3.3. Thời hạn hợp đồng là: 12 tháng tính từ ngày ' + s.start + ' đến ngày ' + s.endWrong, '3.4. Trước 30 ngày hết hạn hợp đồng, nếu hai bên không có ý kiến gì thì thời hạn hợp đồng mặc nhiên kéo dài thêm mỗi lần 12 tháng và tự gia hạn mỗi lần kết thúc thời hạn hợp đồng.', 'Ví dụ: Bên B muốn chấm dứt hợp đồng thì phải báo cho bên A vào trước ngày ' + s.noticeDate, 'Qua ngày trên, hợp đồng mặc nhiên được gia hạn 12 tháng.', 'ĐIỀU 4: GIÁ CẢ VÀ PHƯƠNG THỨC THANH TOÁN', '4.1. Giá cho thuê phòng là: ' + v(s.price) + '/tháng (Bằng chữ: ' + F.words(s.price) + ').', '- Số tiền đã thanh toán trước khi ký hợp đồng: ' + v(s.paidBefore), '- Số tiền đóng thêm vào thời điểm ký hợp đồng: ' + v(s.paidAtSign), '4.2. Các khoản phí dịch vụ', 'Số điện: ' + s.elecIndex, 'Số nước: ' + s.waterIndex, 'Internet', '100.000đ /tháng', 'Điện:', '4.000đ /số', 'Nước:', '120.000đ /người  Xe đạp điện:', '150.000đ /xe', 'Dịch vụ chung', '(máy giặt, điện chung, thu rác, vệ sinh chung)', '120.000đ /người Xe điện dịch', 'vụ xanh SM:', '400.000/xe', '4.3. Tiền đặt cọc duy trì hợp đồng là 01 tháng tiền nhà: ' + v(s.depositWrong), '(Bằng chữ: ' + F.words(s.depositWrong) + ')', 'Tiền đặt cọc sẽ được bên A trả lại hoàn toàn cho bên B chuyển ra đúng thời hạn kết thúc hợp đồng và không có phát sinh nào xảy ra.', '4.4. Phương thức thanh toán', 'Vào ngày 25 hàng tháng, Bên A gửi thông báo tiền phòng của kì tiếp theo và tiền dịch vụ bên B đã sử dụng trong tháng đó cho bên B.', '4.4.1 Thời hạn thanh toán: Từ ngày 25 đến ngày 30 của kỳ thanh toán trước đó.', '4.4.2 Hình thức thanh toán: Chuyển khoản đến tài khoản ghi trên thông báo tiền phòng', '- Ngân hàng BIDV NGUYỄN THỊ HẰNG: 2120368058', 'Nếu Bên B chuyển vào tài khoản khác hoặc trả bằng tiền mặt, bên A không chịu trách nhiệm.', '4.4.3 Nội dung chuyển khoản: Phòng+Tòa ' + s.roomCodeWrong + ' ' + s.buildingName, '4.4.4 Bất cứ vì lí do nào đó mà bên B chậm trả tiền cho bên A thì bên B phải chịu phạt 200.000 đồng cho một ngày nộp muộn.', 'ĐIỀU 5: QUYỀN VÀ NGHĨA VỤ BÊN A', '5.2.6 Khi bên A muốn lấy lại phòng hoặc tăng giá phòng phải báo trước cho bên B một tháng.', 'ĐIỀU 6: QUYỀN VÀ NGHĨA VỤ CỦA BÊN B', '6.2.11 Trong tất cả các trường hợp chấm dứt hợp đồng, bên B phải báo trước cho bên A ít nhất 30 ngày.', 'ĐIỀU 7: CAM KẾT CÁC BÊN', '7.2. Hợp đồng được lập thành 02 bản và có giá trị như nhau. Mỗi bên giữ 01 bản.', 'ĐẠI DIỆN BÊN A', 'ĐẠI DIỆN BÊN B', '', '(File mẫu cho trích xuất OCR – demo TimoHouse Phase 2, theo template HĐ mới của Linh)');
    return L.join('\n');
  };
  /* 4 trang HTML mô phỏng template, mark = vị trí trường trên tài liệu */
  O.pages = (o) => {
    const fl = (k) => (o.fields || []).find(x => x.key === k); const mk = (k, text) => { const f = fl(k); if (!f) return esc(text || ''); const shown = text != null ? text : (f.value || '……………'); return `<mark data-ocr-mark="${k}" class="${f.confirmed ? 'ok' : 'check'}" title="${f.confirmed ? 'Đã nhận' : 'Cần kiểm tra – độ tin cậy ' + Math.round((f.confidence || 0) * 100) + '%'}">${esc(shown)}</mark>`; };
    const money = (k) => { const f = fl(k); return mk(k, f && f.value && !isNaN(Number(f.value)) ? F.vnd(Number(f.value)).replace(/,/g, '.') + 'đ' : undefined); };
    const assets = o.assets && o.assets.length ? o.assets : []; const fu = assets.filter(a => a.kind === 'furniture'), dv = assets.filter(a => a.kind === 'device'); const n = Math.max(fu.length, dv.length, 1);
    const cell = (a) => a ? `<td>${esc(a.name)}${a.desc ? ' ' + esc(a.desc) : ''}</td><td class="c">${esc(a.qty)}</td><td>${esc(a.condition)}</td>` : '<td></td><td></td><td></td>';
    const assetRows = (from, to) => Array.from({ length: Math.max(0, Math.min(to, n) - from) }, (_, i) => `<tr>${cell(fu[from + i])}${cell(dv[from + i])}</tr>`).join('');
    const p1 = `<h3>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</h3><p class="c"><b>Độc lập – Tự do - Hạnh phúc</b></p><p class="c">***</p><h4>HỢP ĐỒNG CHO THUÊ PHÒNG</h4><p class="c"><b>HĐ số:</b> ${mk('contractNo')}</p><p>Hôm nay, ngày ${mk('signDate')}<br>Tại địa chỉ: ${mk('signPlace')}<br>Chúng tôi gồm:</p><p><b>BÊN CHO THUÊ PHÒNG (BÊN A):</b><br>1. Đại diện chủ nhà (Ông/Bà): ${mk('landlordName')}<br>- Số CMT/CCCD: ${mk('landlordId')} &nbsp; Nơi cấp: ${mk('landlordIdPlace')}<br>- Hộ khẩu thường trú: ${mk('landlordAddress')}<br>- SĐT: ${mk('landlordPhone')}</p><p><b>2. BÊN THUÊ PHÒNG (BÊN B):</b><br>- Họ tên đầy đủ: ${mk('tenantName')} &nbsp; Ngày sinh: ${mk('dob')}<br>- Các số điện thoại đang dùng: ${mk('phone')}<br>- Số CCCD: ${mk('idNumber')} &nbsp; Nơi cấp: ${mk('idPlace')}<br>- Hộ khẩu thường trú (ghi chi tiết): ${mk('address')}</p><p><b>ĐIỀU 1: ĐỐI TƯỢNG CHO THUÊ VÀ MỤC ĐÍCH SỬ DỤNG</b><br>1.1. Bên A đồng ý cho bên B thuê phòng số: ${mk('roomCode')} (tòa ${mk('buildingName')})<br>1.2. Bên B sử dụng phòng trên với mục đích để ở. Số lượng: ${mk('occupants')} người. Số người tối đa là ${mk('maxOccupants')} người. Nếu người mới đến ở quá 5 ngày thì tính thêm người. Số xe: ${mk('vehicleCount')}</p><p><b>ĐIỀU 2: BÀN GIAO TÀI SẢN</b><br>2.1. Tài sản sử dụng và bảo quản chung: thang bộ, thang máy, sân phơi, máy bơm, hệ thống chiếu sáng, bể nước, nhà để xe, camera đều sử dụng bình thường.<br>2.2. Tài sản trong phòng – đã bàn giao cho bên B, hoạt động bình thường:</p><table class="dp-table"><tr><th>Tên nội thất</th><th>SL</th><th>Tình trạng</th><th>Tên thiết bị</th><th>SL</th><th>Tình trạng</th></tr>${assetRows(0, 7)}</table>`;
    const p2 = `<table class="dp-table">${assetRows(7, n)}</table><p><b>ĐIỀU 3: THỜI ĐIỂM GIAO NHẬN PHÒNG VÀ THỜI HẠN CHO THUÊ</b><br>3.1. Thời điểm giao nhận phòng ở là ngày ${mk('handoverDate')}<br>3.2. Thời điểm tính tiền phòng ở là ngày ${mk('billingStart')}<br>3.3. Thời hạn hợp đồng là: ${mk('months')} tháng tính từ ngày ${mk('start')} đến ngày ${mk('end')}<br>3.4. Trước 30 ngày hết hạn hợp đồng, nếu hai bên không có ý kiến gì thì thời hạn hợp đồng mặc nhiên kéo dài thêm mỗi lần 12 tháng. Ví dụ: Bên B muốn chấm dứt hợp đồng thì phải báo cho bên A vào trước ngày ${mk('noticeDate')}</p><p><b>ĐIỀU 4: GIÁ CẢ VÀ PHƯƠNG THỨC THANH TOÁN</b><br>4.1. Giá cho thuê phòng là: ${money('price')}/tháng (Bằng chữ: ${mk('priceWords')}).<br>- Số tiền đã thanh toán trước khi ký hợp đồng: ${money('paidBefore')}<br>- Số tiền đóng thêm vào thời điểm ký hợp đồng: ${money('paidAtSign')}<br>4.2. Các khoản phí dịch vụ &nbsp; Số điện: ${mk('elecIndex')} &nbsp; Số nước: ${mk('waterIndex')}</p><table class="dp-table dp-svc"><tr><td>Internet</td><td>${money('svc_internet')} /tháng</td><td></td><td></td></tr><tr><td>Điện:</td><td>${money('svc_electric')} /số</td><td></td><td></td></tr><tr><td>Nước:</td><td>${money('svc_water')} /người</td><td>Xe đạp điện:</td><td>${money('svc_ebike')} /xe</td></tr><tr><td>Dịch vụ chung (máy giặt, điện chung, thu rác, vệ sinh chung)</td><td>${money('svc_common')} /người</td><td>Xe điện dịch vụ xanh SM:</td><td>${money('svc_evcar')} /xe</td></tr></table><p>4.3. Tiền đặt cọc duy trì hợp đồng là 01 tháng tiền nhà: ${money('deposit')}<br>(Bằng chữ: ${mk('depositWords')})<br>Tiền đặt cọc sẽ được bên A trả lại hoàn toàn cho bên B chuyển ra đúng thời hạn kết thúc hợp đồng và không có phát sinh nào xảy ra. Bên thuê sẽ chịu phí nhượng phòng là 200.000đ.<br>4.4. Phương thức thanh toán: Vào ngày ${mk('payDay')} hàng tháng, Bên A gửi thông báo tiền phòng của kỳ tiếp theo.<br>4.4.1 Thời hạn thanh toán: Từ ngày 25 đến ngày 30 của kỳ thanh toán trước đó.<br>4.4.2 Hình thức thanh toán: Chuyển khoản – Ngân hàng ${mk('bankAccount')}<br><b>Nếu Bên B chuyển vào tài khoản khác hoặc trả bằng tiền mặt, bên A không chịu trách nhiệm.</b></p>`;
    const p3 = `<p>4.4.3 Nội dung chuyển khoản: Phòng+Tòa ${mk('transferNote')}<br>4.4.4 Bên B chậm trả tiền phải chịu phạt 200.000 đồng/ngày nộp muộn, tính từ ngày mùng 1 tháng sau. Thời hạn chậm trả không quá 03 ngày; quá hạn, bên A có quyền đơn phương chấm dứt hợp đồng và không trả lại tiền đặt cọc.</p><p><b>ĐIỀU 5: QUYỀN VÀ NGHĨA VỤ BÊN A</b><br>5.1. Yêu cầu bên B trả đủ tiền thuê và dịch vụ đúng hạn; đơn phương chấm dứt khi bên B vi phạm hợp đồng, nội quy tòa nhà.<br>5.2. Giao phòng và thiết bị đúng ngày; bảo hành thiết bị 10 ngày kể từ bàn giao; sửa chữa sự cố ngoài phòng; báo trước một tháng khi lấy lại phòng hoặc tăng giá.</p><p><b>ĐIỀU 6: QUYỀN VÀ NGHĨA VỤ CỦA BÊN B</b><br>6.1. Nhận phòng đúng ngày; yêu cầu bên A sửa chữa hư hỏng không do mình gây ra.<br>6.2. Sử dụng đúng mục đích; trả tiền đúng hạn; chấp hành nội quy; sau 10 ngày bảo hành tự chịu chi phí sửa chữa; làm bẩn tường phạt 600.000đ; thuê từ 3 tháng bồi thường khấu hao thiết bị ít nhất 200.000đ; đăng ký tạm trú; tuân thủ PCCC.</p>`;
    const p4 = `<p>6.2.9 – 6.2.12: Tự bảo quản tài sản, xe cộ; không đánh bạc, chất cấm, gây ồn; báo trước ít nhất 30 ngày khi chấm dứt hợp đồng và phối hợp cho khách mới xem phòng.</p><p><b>ĐIỀU 7: CAM KẾT CÁC BÊN</b><br>7.1. Hai bên cam kết thực hiện đúng nội dung đã ký; bên B vi phạm hoặc đơn phương chấm dứt trước hạn mất toàn bộ tiền cọc.<br>7.2. Hợp đồng lập thành 02 bản có giá trị như nhau, mỗi bên giữ 01 bản, có giá trị kể từ ngày ký.</p><div class="dp-sign"><div><b>ĐẠI DIỆN BÊN A</b><br><small>(Ký và ghi rõ họ tên)</small><br><br><br>${mk('landlordName')}</div><div><b>ĐẠI DIỆN BÊN B</b><br><small>(Ký và ghi rõ họ tên)</small><br><br><br>${mk('tenantName')}</div></div>`;
    return [p1, p2, p3, p4];
  };
  TH.ocr = O;
  TH.router.register('/contracts/ocr', (root, p, q) => {
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Trích xuất hợp đồng' }]);
    const o = q.id ? St.get('ocrExtractions', q.id) : null; const step = !o ? 1 : o.status === 'uploaded' || o.status === 'extracting' ? 2 : o.status === 'review' ? 3 : 4;
    const STEPS = [{ title: 'Tải file', sub: 'Tải lên hợp đồng' }, { title: 'Trích xuất', sub: 'Hệ thống nhận diện thông tin' }, { title: 'Review', sub: 'Kiểm tra và chỉnh sửa' }, { title: 'Hoàn tất', sub: 'Tạo hợp đồng' }];
    const head = U.pageHead({ title: step === 3 ? 'Review trích xuất hợp đồng' : 'Trích xuất hợp đồng (OCR)', phase: 2, sub: step === 3 ? 'Kiểm tra và chỉnh sửa thông tin trước khi tạo hợp đồng' : 'Tải hợp đồng theo mẫu "Hợp đồng cho thuê phòng" – PDF điền trên máy hoặc .txt (≤ 20MB, FR-DOC-01); ảnh scan chưa hỗ trợ. Hệ thống trích xuất trường, review confidence rồi tạo hợp đồng (BR-03).', acts: [U.btn({ label: 'Nhập tay (dự phòng)', icon: 'pencil', cls: 'btn-outline', act: 'manual' })] });
    if (step === 1) {
      const hist = St.all('ocrExtractions').sort((a, b) => F.cmp(b.createdAt, a.createdAt)).slice(0, 5);
      root.innerHTML = `${head}${U.wizard(STEPS, 0)}<div class="two-col">${U.card({ title: 'Bước 1 – Tải file hợp đồng', icon: 'upload', body: `${U.dropzone({ name: 'ocr', hint: 'PDF điền trên máy hoặc .txt theo mẫu HĐ cho thuê phòng · tối đa 20MB (FR-DOC-01)', multiple: false, accept: '.pdf,.txt' })}<div class="row mt12 gap12">${U.btn({ label: 'Dùng file mẫu (HD-cho-thue-phong-mau.txt – 5 trường cố tình sai)', icon: 'file-check', cls: 'btn-outline', act: 'sample', attrs: { 'data-guide': 'ocr-sample' } })}${U.btn({ label: 'Tải file mẫu (.txt)', icon: 'download', cls: 'btn-ghost', act: 'dl' })}</div>` })}<aside class="side-stack">${U.card({ title: 'Cách hoạt động', icon: 'info', body: `<div class="steps">${[['Tải file', 'PDF text-based hoặc .txt theo template HĐ cho thuê phòng (4 trang).'], ['Trích xuất', 'Nhận diện ' + P.FIELDS.length + ' trường theo Điều 1–4: bên A/B, phòng, thời hạn, giá, cọc, đơn giá dịch vụ, ngân hàng; đọc bảng tài sản bàn giao.'], ['Review', 'Trường confidence < 80% gắn chip "Cần kiểm tra"; trường ảnh hưởng tiền bắt buộc xác nhận (BR-03).'], ['Tạo hợp đồng', 'Prefill form HĐ P1 (khách, phòng, thời hạn, giá, cọc, dịch vụ, xe), nguồn = OCR; nhập tay vẫn là nhánh dự phòng.']].map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` })}${U.card({ title: 'Lần trích xuất gần đây', icon: 'history', bodyCls: 'tight', body: `<table class="tbl compact">${hist.map(x => `<tr><td>${U.link('#/contracts/ocr?id=' + x.id, esc(x.code))}</td><td class="small">${esc(x.fileName)}</td><td>${Q.chip('ocr', x.status)}</td></tr>`).join('') || '<tr><td class="muted tc">Chưa có</td></tr>'}</table>` })}</aside></div>`;
      U.bindDropzones(root, async (files) => { const f = files[0]; if (!f) return; try { if (f.size > 20 * 1024 * 1024) throw new Error('File tối đa 20MB (FR-DOC-01)'); U.toast('info', 'Đang đọc file…', f.name); const r = await P.readFile(f); if (!r.text || r.text.trim().length < 50) throw new Error('Không đọc được nội dung văn bản – file có thể là ảnh scan'); const x = X.ocrUpload({ fileName: f.name, size: f.size, text: r.text, pages: r.pages }); TH.go('#/contracts/ocr?id=' + x.id); } catch (e) { U.toast('err', 'Không tải được', e.message); } });
      U.bind(root, { manual: () => TH.go('#/contracts/new'), sample: () => { const x = X.ocrUpload({ fileName: 'HD-cho-thue-phong-mau.txt', size: 12 * 1024, sample: true, pages: 4 }); TH.go('#/contracts/ocr?id=' + x.id); }, dl: () => { F.download('HD-cho-thue-phong-mau.txt', O.sampleText()); U.toast('ok', 'Đã tải file mẫu', 'HĐ theo template của Linh đã điền, dùng để thử trích xuất'); } });
      return;
    }
    if (step === 2) {
      const np = o.pages || 4;
      root.innerHTML = `${head}${U.wizard(STEPS, 1)}${U.card({ title: 'Bước 2 – Đang trích xuất ' + esc(o.fileName), icon: 'scan', body: `<div class="tc" style="padding:30px 0"><div class="big" style="width:72px;height:72px;border-radius:20px;background:var(--blue-bg);color:var(--blue);display:grid;place-items:center;margin:0 auto 14px">${I('scan')}</div><b style="font-size:16px">Hệ thống đang nhận diện thông tin…</b><div class="muted small mt4">${esc(o.fileName)} · ${esc(o.size)} · ${np} trang</div><div class="progress mt16" style="max-width:420px;margin:16px auto 0"><i id="ocr-bar" style="width:5%;transition:width .4s"></i></div><div class="xs muted mt8" id="ocr-msg">Đọc trang 1/${np}…</div></div>` })}`;
      if (o.status === 'uploaded') X.ocrExtract(o.id);
      const bar = root.querySelector('#ocr-bar'), msg = root.querySelector('#ocr-msg'); let k = 0; const msgs = ['Đọc trang 1/' + np + '…', 'Nhận diện bên A / bên B…', 'Nhận diện phòng, tài sản & thời hạn…', 'Nhận diện giá, cọc & đơn giá dịch vụ…', 'Đối chiếu độ tin cậy…', 'Hoàn tất'];
      const t = setInterval(() => { k++; if (!document.contains(bar)) return clearInterval(t); bar.style.width = Math.min(100, k * 20) + '%'; msg.textContent = msgs[Math.min(k, 5)]; if (k >= 5) { clearInterval(t); try { X.ocrFinish(o.id); } catch (e) { U.toast('err', 'Trích xuất lỗi', e.message); } TH.router.refresh(); } }, 400);
      U.bind(root, { manual: () => TH.go('#/contracts/new') });
      return;
    }
    const fields = o.fields || []; const pending = fields.filter(f => !f.confirmed); const got = fields.length - pending.length; const page = Number(q.page || 1); const zoom = Number(q.zoom || 100); const reviewView = q.view || (pending.length ? 'pending' : 'all'); const npages = O.pages(o).length;
    const Fm = TH.forms; const E = P.entities(o); const fv = (k) => (fields.find(f => f.key === k) || {}).value || '';
    const bSel = St.one('buildings', b => b.name === fv('buildingName')) || E.building.match; const rooms = St.where('rooms', r => ['ready', 'held'].includes(r.status)); const roomSug = fv('roomCode') && bSel ? P.matchRoom(fv('roomCode'), bSel.id) : null;
    const chip = (f) => f.confirmed ? '' : `<span class="chip amber" title="Độ tin cậy ${Math.round(f.confidence * 100)}%">${I('alert-circle')} Cần kiểm tra</span>`;
    const inp = (f) => { if (!f || (reviewView === 'pending' && f.confirmed)) return ''; const k = f.key, d = P.field(k) || { type: 'text' }; const at = { 'data-on': 'field', 'data-k': k }; const control = k === 'buildingName' ? U.select({ name: k, value: f.value || (E.building.match ? E.building.match.name : ''), placeholder: f.value || E.building.match ? undefined : (E.building.hint ? 'HĐ ghi tòa "' + E.building.hint + '" – không có trong hệ thống, chọn tòa' : 'Chọn tòa nhà'), options: St.where('buildings', b => !b.stub).map(b => b.name), attrs: at }) : k === 'roomCode' ? U.select({ name: k, value: rooms.some(r => r.code === f.value) ? f.value : (roomSug && rooms.some(r => r.id === roomSug.id) ? roomSug.code : ''), placeholder: rooms.some(r => r.code === f.value) ? undefined : (f.value || 'Chưa có') + (roomSug ? ' → gợi ý ' + roomSug.code + ' (theo số ' + (f.value.match(/\d+/g) || []).join('') + ')' : ' (không khớp – chọn phòng)'), options: rooms.filter(r => !bSel || r.buildingId === bSel.id).map(r => [r.code, r.code + ' – ' + r.type + (roomSug && r.id === roomSug.id ? ' (gợi ý)' : '')]), attrs: at }) : k === 'payDay' ? U.select({ name: k, value: f.value, options: ['01', '05', '10', '15', '20', '25'], attrs: at }) : d.type === 'date' ? U.date({ name: k, value: F.fromVN(f.value), attrs: at }) : d.type === 'textarea' ? U.textarea({ name: k, value: f.value, rows: 2, attrs: at }) : U.input({ name: k, value: f.value, readonly: d.type === 'readonly', attrs: Object.assign({ inputmode: ['money', 'number'].includes(d.type) ? 'numeric' : undefined }, at) }); return `<div data-ocr-field="${k}">${U.field({ label: f.label + (f.money ? ' ⓘ' : ''), req: !!d.req, input: `<div class="row gap4 ocr-field" style="align-items:flex-start"><div class="grow">${control}</div>${f.confirmed ? '' : U.iconBtn('check', 'confirm', 'Xác nhận đúng', { 'data-k': k }, 'ok')}</div>`, help: chip(f) + (f.editedAt ? ' <span class="xs muted">đã sửa</span>' : '') + (k === 'roomCode' && roomSug && f.value !== roomSug.code ? ' <span class="xs muted">HĐ ghi "' + esc(f.value) + '"</span>' : ''), cls: d.type === 'textarea' ? 'span2' : '' })}</div>`; };
    const groups = P.GROUPS.slice(); fields.forEach(f => { if (!groups.some(g => g[0] === f.group)) groups.push([f.group, f.group === 'meta' ? 'Thông tin khác' : f.group, 'info']); });
    const assets = o.assets || []; const fu = assets.filter(a => a.kind === 'furniture'), dv = assets.filter(a => a.kind === 'device');
    const assetTable = (list) => `<table class="tbl compact"><tr><th>Tên</th><th class="r">SL</th><th>Tình trạng</th></tr>${list.map(a => `<tr><td>${esc(a.name)}${a.desc ? ' <span class="muted">' + esc(a.desc) + '</span>' : ''}</td><td class="r">${esc(a.qty || '–')}</td><td>${esc(a.condition || '–')}</td></tr>`).join('')}</table>`;
    /* Card Kết quả trích xuất: 5 thực thể + trạng thái khớp hệ thống + hành động (OCR đồng thời là bước tạo khách thuê) */
    const vnd = (n) => n ? F.vnd(n) + 'đ' : '–'; const T = E.tenant, C = E.contract; const MISS = { idNumber: 'CCCD', idPlace: 'nơi cấp', dob: 'ngày sinh', address: 'hộ khẩu' };
    const tenantRow = () => { const d = T.data; const info = `<b>${esc(d.name || '(chưa có tên)')}</b>${d.phone ? ' · ' + esc(d.phone) : ''}${d.idNumber ? ' · CCCD ' + esc(d.idNumber) : ''}${d.dob ? ' · ' + esc(d.dob) : ''}${d.address ? '<div class="xs muted">' + esc(d.address) + '</div>' : ''}`; if (T.match && T.weak) return [info + `<div class="mt4">${U.chip('Trùng tên với ' + T.match.code + ' (SĐT ' + T.match.phone + ') – kiểm tra có phải cùng người', 'amber')} ${U.link('#/tenants/' + T.match.id, 'Xem hồ sơ')}</div>`, U.btn({ label: 'Tạo khách mới', icon: 'user-plus', size: 'btn-sm', cls: 'btn-primary', act: 'tenant-create' }) + U.btn({ label: 'Dùng ' + T.match.code, icon: 'check', size: 'btn-sm', cls: 'btn-outline', act: 'tenant-use', attrs: { 'data-id': T.match.id } }) + U.btn({ label: 'Chọn có sẵn', icon: 'users', size: 'btn-sm', cls: 'btn-ghost', act: 'tenant-pick' })]; if (T.match) return [info + `<div class="mt4">${U.chip((o.tenantId === T.match.id ? 'Đã gán ' : 'Khớp ') + T.match.code + ' (' + T.matchBy + ')', 'green')} ${U.link('#/tenants/' + T.match.id, esc(T.match.name))}${T.missing.length ? ' <span class="xs muted">· hồ sơ thiếu ' + T.missing.map(k => MISS[k]).join(', ') + '</span>' : ''}</div>`, (T.missing.length ? U.btn({ label: 'Cập nhật hồ sơ từ HĐ', icon: 'refresh-cw', size: 'btn-sm', cls: 'btn-outline', act: 'tenant-update' }) : '') + U.btn({ label: 'Chọn khách khác', icon: 'users', size: 'btn-sm', cls: 'btn-ghost', act: 'tenant-pick' })]; return [info + `<div class="mt4">${U.chip('Chưa có trong hệ thống – sẽ tạo mới khi tạo hợp đồng', 'amber')}</div>`, U.btn({ label: 'Tạo khách thuê', icon: 'user-plus', size: 'btn-sm', cls: 'btn-primary', act: 'tenant-create', disabled: !d.name || !d.phone }) + U.btn({ label: 'Chọn có sẵn', icon: 'users', size: 'btn-sm', cls: 'btn-ghost', act: 'tenant-pick' })]; };
    const roomRow = () => { const b = E.building, r = E.room; const info = `<b>${esc(r.code || '(chưa có)')}</b>${b.hint ? ' · tòa "' + esc(b.hint) + '"' : ''}${b.match ? ' → ' + esc(b.match.name) : ''}`; if (r.match) return [info + `<div class="mt4">${U.chip('Khớp phòng ' + r.match.code, 'green')} ${Q.chip('room', r.match.status)}</div>`, U.link('#/rooms/' + r.match.id, 'Xem phòng')]; return [info + `<div class="mt4">${U.chip(r.suggested ? 'Gợi ý ' + r.suggested.code + ' theo số phòng – cần xác nhận' : b.match ? 'Không thấy phòng trong ' + b.match.name + ' – chọn phòng' : 'Tòa/phòng không có trong hệ thống – chọn tay', 'amber')}</div>`, U.btn({ label: 'Chọn tòa/phòng', icon: 'home', size: 'btn-sm', cls: 'btn-outline', act: 'jump-field', attrs: { 'data-k': b.match ? 'roomCode' : 'buildingName' } })]; };
    const contractRow = () => [`<b>${esc(C.start || '?')} → ${esc(C.end || '?')}</b>${C.months ? ' · ' + esc(C.months) + ' tháng' : ''} · giá <b>${vnd(C.price)}</b>/tháng · cọc <b>${vnd(C.deposit)}</b>${C.paidBefore || C.paidAtSign ? '<div class="xs muted">Đã trả trước ' + vnd(C.paidBefore) + ' · đóng thêm khi ký ' + vnd(C.paidAtSign) + ' · thanh toán ngày ' + esc(C.payDay) + ' hàng tháng' + (C.contractNo ? ' · HĐ số ' + esc(C.contractNo) : '') + '</div>' : ''}`, ''];
    const svcRow = () => [E.services.length ? E.services.map(s => esc(s.label) + ' <b>' + F.vnd(s.price) + '</b>/' + s.unit).join(' · ') + '<div class="xs muted">' + (E.vehicles ? E.vehicles + ' xe → dòng gửi xe trên hợp đồng; ' : '') + 'điện/nước tính theo công tơ' + (fv('elecIndex') || fv('waterIndex') ? ' (chỉ số đầu: điện ' + esc(fv('elecIndex') || '–') + ', nước ' + esc(fv('waterIndex') || '–') + ')' : '') + '</div>' : '<span class="muted">Không đọc được bảng đơn giá</span>', ''];
    const assetRow = () => [assets.length ? `<b>${assets.length}</b> hạng mục (${assets.filter(a => a.qty).length} có số lượng, ${assets.filter(a => /bình thường|sạch|tốt|mới/i.test(a.condition)).length} tình trạng tốt) – bàn giao theo Điều 2.2` : '<span class="muted">Không đọc được bảng tài sản</span>', assets.length ? U.btn({ label: 'Xem bảng', icon: 'package', size: 'btn-sm', cls: 'btn-ghost', act: 'assets-open' }) : ''];
    const entityCard = U.card({ attrs: 'data-collapse-ready="1"', title: `${I('layers')} Kết quả trích xuất`, sub: `Đã đọc ${o.pages || npages} trang · nhận ${fields.filter(f => f.value).length}/${fields.length} trường · ${assets.length} tài sản`, body: `<div class="ocr-entities">${[['user', 'Khách thuê', tenantRow()], ['home', 'Tòa & phòng', roomRow()], ['file-text', 'Hợp đồng', contractRow()], ['sliders', 'Dịch vụ', svcRow()], ['package', 'Tài sản', assetRow()]].map(([ic, lbl, [val, act]]) => `<div class="ocr-entity"><div class="lbl">${I(ic)} ${lbl}</div><div class="val">${val}</div><div class="act">${act || ''}</div></div>`).join('')}</div>` });
    root.innerHTML = `${head}${U.wizard(STEPS, step - 1)}<div class="ocr-mobile-banner">${U.note('info', 'Review OCR trên máy tính', 'Màn hình nhỏ chỉ hỗ trợ xem tóm tắt và tài liệu. Mở trên laptop/desktop để chỉnh sửa và xác nhận trường.')}</div><div class="two-col wide ocr-review-layout" style="grid-template-columns:minmax(0,1fr) minmax(0,1.15fr)">
      <div>${U.card({ title: `${I('file-text')} ${esc(o.fileName)}`, sub: `${esc(o.size)} · ${o.pages || npages} trang – đã đọc toàn bộ, cuộn để xem từng trang`, actions: U.btn({ label: 'Tải file khác', icon: 'upload', size: 'btn-sm', cls: 'btn-outline', act: 'other' }), body: U.docPreview({ pages: O.pages(o), page: Math.min(page, npages), zoom, fileName: o.fileName, stacked: true }) })}</div>
      <div class="side-stack">${entityCard}${U.card({ body: `<div class="ocr-review-summary"><div><b>${got}/${fields.length}</b><span>trường đã xác nhận · ${fields.filter(f => f.value).length} trường nhận được từ ${o.pages || npages} trang</span><div class="progress"><i style="width:${F.pct(got, fields.length)}%"></i></div></div><div class="ocr-review-modes">${U.btn({ label: 'Cần kiểm tra (' + pending.length + ')', icon: 'alert-circle', size: 'btn-sm', cls: reviewView === 'pending' ? 'btn-primary' : 'btn-outline', act: 'view-pending' })}${U.btn({ label: 'Tất cả trường', icon: 'list', size: 'btn-sm', cls: reviewView === 'all' ? 'btn-primary' : 'btn-outline', act: 'view-all' })}</div></div>${pending.length ? `<nav class="ocr-exception-list" aria-label="Trường cần kiểm tra">${pending.map(f => `<button type="button" data-act="jump-field" data-k="${f.key}"><span>${I('alert-circle')} ${esc(f.label)}${f.value ? '' : ' <em class="muted">(trống)</em>'}</span><b>${Math.round((f.confidence || 0) * 100)}%</b></button>`).join('')}</nav>` : U.note('ok', 'Đã kiểm tra xong', 'Tất cả trường bắt buộc đã được xác nhận.')}` })}
      ${step === 4 ? U.note('ok', 'Đã tạo hợp đồng từ trích xuất', 'Hợp đồng ' + U.link('#/contracts/' + o.contractId, esc((Q.contract(o.contractId) || {}).code || '')) + ' – nguồn OCR. Kích hoạt tại chi tiết hợp đồng.') : ''}
      <form id="of">${groups.map(([g, label, ic]) => { const gf = fields.filter(f => f.group === g && (reviewView === 'all' || !f.confirmed)); if (!gf.length) return ''; return `<div class="card ocr-group"><div class="card-b"><h4>${I(ic)} ${esc(label)}</h4><div class="form-grid">${gf.map(inp).join('')}</div></div></div>`; }).join('')}</form>
      ${assets.length ? `<details class="card ocr-group" id="ocr-assets"><summary class="card-b" style="cursor:pointer"><b>${I('package')} Tài sản bàn giao (Điều 2.2)</b> <span class="muted small">· ${assets.length} hạng mục, ${assets.filter(a => a.qty).length} có số lượng – chỉ đọc, không cần xác nhận</span></summary><div class="card-b" style="padding-top:0"><div class="grid grid-2">${assetTable(fu)}${assetTable(dv)}</div></div></details>` : ''}
      <div class="wz-foot">${U.btn({ label: 'Chạy lại trích xuất', icon: 'refresh-cw', cls: 'btn-outline', act: 'rerun', disabled: step === 4 })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${step === 4 ? U.btn({ label: 'Mở hợp đồng', icon: 'file-text', cls: 'btn-primary', act: 'open' }) : U.btn({ label: 'Tạo hợp đồng', icon: 'arrow-right', cls: 'btn-primary', act: 'create', attrs: { 'data-guide': 'ocr-create' } })}</div></div></div></div>`;
    const highlightPair = (k) => { root.querySelectorAll('.ocr-pair-active').forEach(x => x.classList.remove('ocr-pair-active')); const field = root.querySelector(`[data-ocr-field="${k}"]`), mark = root.querySelector(`[data-ocr-mark="${k}"]`); field && field.classList.add('ocr-pair-active'); mark && mark.classList.add('ocr-pair-active'); return { field, mark }; };
    const confirmInPlace = (k) => { const pair = highlightPair(k); const btn = pair.field && pair.field.querySelector('[data-act=confirm]'); btn && btn.remove(); const help = pair.field && pair.field.querySelector('.help'); if (help) help.innerHTML = '<span class="xs green">Đã xác nhận</span>'; root.querySelectorAll(`[data-ocr-mark="${k}"]`).forEach(m => { m.classList.remove('check'); m.classList.add('ok'); }); const jump = root.querySelector(`.ocr-exception-list [data-k="${k}"]`); jump && jump.remove(); };
    const focusPair = (k) => { const pair = highlightPair(k); if (pair.field) { pair.field.scrollIntoView({ behavior: 'smooth', block: 'center' }); pair.field.querySelector('input,select,textarea')?.focus(); } if (pair.mark) pair.mark.scrollIntoView({ behavior: 'smooth', block: 'center' }); };
    const tenantPrefill = () => { const d = E.tenant.data; return { name: d.name, phone: d.phone, idNumber: d.idNumber, idPlace: d.idPlace, dob: F.fromVN(d.dob) || '', address: d.address, note: 'Tạo từ trích xuất hợp đồng ' + o.code + (E.contract.contractNo ? ' (HĐ ' + E.contract.contractNo + ')' : '') }; };
    const pickTenant = () => { const list = St.all('tenants').sort((a, b) => F.cmp(a.name, b.name)); const m = U.modal({ title: 'Chọn khách thuê có sẵn', sub: 'Gán khách đã có hồ sơ cho trích xuất ' + o.code, body: `<div class="form-grid">${U.field({ label: 'Khách thuê', req: true, input: U.select({ name: 'tenantId', placeholder: 'Chọn khách', options: list.map(t => [t.id, t.name + ' (' + t.code + ') – ' + t.phone]) }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', cls: 'btn-outline', act: 'cancel' }) + U.btn({ label: 'Gán khách', icon: 'check', cls: 'btn-primary', act: 'ok' }) }); U.bind(m.el, { cancel: () => m.close(), ok: () => { const id = m.data().tenantId; if (!id) return U.toast('warn', 'Chọn khách thuê'); try { const t = X.ocrSetTenant(o.id, id); m.close(); U.toast('ok', 'Đã gán khách ' + t.name); TH.router.refresh(); } catch (e) { U.toast('err', 'Không gán được', e.message); } } }); };
    root.addEventListener('input', (e) => { const el = e.target.closest('[data-k]'); if (el) el._dirty = true; });
    root.addEventListener('focusin', (e) => { const el = e.target.closest('[data-k]'); if (el) highlightPair(el.dataset.k); });
    root.addEventListener('click', (e) => { const mark = e.target.closest('[data-ocr-mark]'); if (mark) { const pair = highlightPair(mark.dataset.ocrMark); pair.field && pair.field.scrollIntoView({ behavior: 'smooth', block: 'center' }); pair.field && pair.field.querySelector('input,select,textarea')?.focus(); } });
    U.onChange(root, { field: (el) => { const k = el.dataset.k; const d = P.field(k) || {}; let v = el.value; if (d.type === 'date') v = v ? F.date(v) : ''; if (['money', 'number'].includes(d.type)) v = v === '' ? '' : String(F.num(v)); X.ocrSetField(o.id, k, v, true); if (k === 'start' || k === 'end') { const s = F.fromVN(fv('start')), en = F.fromVN(fv('end')); if (s && en && en > s) X.ocrSetField(o.id, 'months', String(F.monthsDiff(s, en))); } if (k === 'buildingName') { const b = St.one('buildings', x => x.name === v); const sug = b ? P.matchRoom(fv('roomCode'), b.id) : null; X.ocrSetField(o.id, 'roomCode', sug ? sug.code : '', !!sug); } if (['buildingName', 'roomCode', 'start', 'end'].includes(k)) TH.router.refresh(); else confirmInPlace(k); } });
    U.bind(root, {
      manual: () => TH.go('#/contracts/new'), other: () => TH.go('#/contracts/ocr'), 'view-pending': () => { TH.router.replaceQuery({ id: o.id, page, zoom, view: 'pending' }); TH.router.refresh(); }, 'view-all': () => { TH.router.replaceQuery({ id: o.id, page, zoom, view: 'all' }); TH.router.refresh(); }, 'jump-field': (el) => { if (reviewView === 'pending' && !root.querySelector(`[data-ocr-field="${el.dataset.k}"]`)) { TH.router.replaceQuery({ id: o.id, page, zoom, view: 'all', focus: el.dataset.k }); return TH.router.refresh(); } focusPair(el.dataset.k); }, confirm: (el) => { X.ocrConfirmField(o.id, el.dataset.k); confirmInPlace(el.dataset.k); const next = root.querySelector('.ocr-exception-list [data-k]'); if (next) focusPair(next.dataset.k); }, rerun: async () => { if (await U.confirm({ title: 'Chạy lại trích xuất?', text: 'Các chỉnh sửa/xác nhận sẽ được đặt lại về kết quả gốc.', ok: 'Chạy lại' })) { X.ocrRerun(o.id); U.toast('ok', 'Đã chạy lại trích xuất'); } }, draft: () => U.toast('ok', 'Đã lưu nháp trích xuất', o.code + ' – tiếp tục review sau'), open: () => TH.go('#/contracts/' + o.contractId),
      'tenant-create': () => Fm.tenant(tenantPrefill(), (t) => { X.ocrSetTenant(o.id, t.id); TH.router.refresh(); }), 'tenant-pick': pickTenant, 'tenant-use': (el) => { try { const t = X.ocrSetTenant(o.id, el.dataset.id); U.toast('ok', 'Đã dùng khách ' + t.name); TH.router.refresh(); } catch (e) { U.toast('err', 'Không gán được', e.message); } }, 'tenant-update': () => { const t = E.tenant.match; if (!t) return; const d = { id: t.id }; E.tenant.missing.forEach(k => { d[k] = k === 'dob' ? F.fromVN(E.tenant.data.dob) : E.tenant.data[k]; }); try { X.saveTenant(Object.assign({}, t, d)); if (!o.tenantId) X.ocrSetTenant(o.id, t.id); U.toast('ok', 'Đã cập nhật hồ sơ ' + t.name, 'Bổ sung: ' + E.tenant.missing.map(k => MISS[k]).join(', ')); TH.router.refresh(); } catch (e) { U.toast('err', 'Không cập nhật được', e.message); } }, 'assets-open': () => { const d = root.querySelector('#ocr-assets'); if (d) { d.open = true; d.scrollIntoView({ behavior: 'smooth', block: 'start' }); } },
      'dp-zoom-in': () => { TH.router.replaceQuery({ id: o.id, page, zoom: Math.min(160, zoom + 10), view: reviewView }); TH.router.refresh(); }, 'dp-zoom-out': () => { TH.router.replaceQuery({ id: o.id, page, zoom: Math.max(60, zoom - 10), view: reviewView }); TH.router.refresh(); }, 'dp-hand': () => U.toast('info', 'Chế độ kéo trang', 'Cuộn/kéo trong khung xem'), 'dp-dl': () => { F.download(o.fileName.replace(/\.\w+$/, '') + '.txt', o.sample ? O.sampleText() : (o.text || '')); U.toast('ok', 'Đã tải bản văn bản của file'); },
      create: async () => { try { X.ocrReadyToCreate(o); } catch (e) { return U.toast('warn', 'Chưa thể tạo hợp đồng', e.message); } const T2 = P.entities(o).tenant; const useMatch = T2.match && !T2.weak; const tenantMsg = useMatch ? 'Khách thuê: ' + T2.match.name + ' (' + T2.match.code + ', khớp ' + T2.matchBy + ').' : 'Khách thuê "' + T2.data.name + '" chưa có trong hệ thống – sẽ được tạo mới từ thông tin hợp đồng (có thể chỉnh sửa sau tại hồ sơ khách).'; if (await U.confirm({ title: 'Tạo hợp đồng từ trích xuất?', text: tenantMsg + ' Form Tạo hợp đồng được điền sẵn từ ' + fields.filter(f => f.value).length + ' trường đã nhận (nguồn OCR). Bạn vẫn kiểm tra & kích hoạt theo quy trình Phase 1.', ok: 'Tạo hợp đồng' })) { try { if (!useMatch && T2.data.name && T2.data.phone) { const t = X.ocrCreateTenant(o.id); U.toast('ok', 'Đã tạo khách thuê ' + t.name + ' (' + t.code + ')', 'Từ thông tin hợp đồng – sửa tại hồ sơ khách nếu cần'); } else if (useMatch && !o.tenantId) X.ocrSetTenant(o.id, T2.match.id); } catch (e) { return U.toast('err', 'Không tạo được khách thuê', e.message); } TH.go('#/contracts/new?ocr=' + o.id); } } });
    const pageSel = root.querySelector('[data-dp-page]'); if (pageSel) pageSel.addEventListener('change', (e) => { const n = Math.max(1, Math.min(npages, Number(e.target.value) || 1)); const el = root.querySelector(`.dp-page[data-dp-n="${n}"]`); if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' }); TH.router.replaceQuery({ id: o.id, page: n, zoom, view: reviewView }); });
    if (q.focus) setTimeout(() => focusPair(q.focus), 50);
  }, { menu: 'ocr', permission: 'ocr.use', phase: 2, scopeKey: 'ocr', noAutoRefresh: 'timer' });
})(window.TH);
