/* Phase 1 (spec v1.8 §12.8) – OCR hợp đồng & Data Onboarding: Tải file → Trích xuất → Review theo 13 nhóm entity (Create/Link/Update/Ignore) → Validate → Commit 1 transaction → Kết quả.
   Template: "HỢP ĐỒNG CHO THUÊ PHÒNG" (4 trang). Parser core/ocr-parser.js, nhóm entity/validate core/ocr-onboarding.js, commit core/actions-ocr.js. PDF text-based đọc bằng pdf.js; JPG/PNG mô phỏng bằng file mẫu (engine mock-1). */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, P = TH.ocrParser, esc = F.esc;
  const O = {};
  /* File mẫu: HĐ của Linh đã điền cho một phòng Sẵn sàng của tòa Sunrise; 5 trường cố tình sai (tên không dấu, SĐT thiếu số, mã phòng thiếu dấu chấm, cọc lệch giá, ngày kết thúc sai năm) */
  O.sampleSpec = () => {
    const b = St.one('buildings', x => x.name === 'Tòa Sunrise') || St.where('buildings', x => !x.stub)[0]; const room = St.where('rooms', r => r.status === 'ready' && r.buildingId === b.id).sort((a, c) => a.code.localeCompare(c.code))[0] || St.where('rooms', r => r.status === 'ready')[0] || St.all('rooms')[0];
    const price = room.price, deposit = price, depositWrong = price + 500000;
    return { contractNo: '12/2026/HĐTP', signDate: '01/11/2026', tenantName: 'Nguyễn Thị Hương', tenantNameWrong: 'NGUYEN THI HUONG', dob: '12/05/1996', idNumber: '023456789012', idPlace: 'Cục Cảnh Sát', phone: '0938765432', phoneWrong: '093876543', address: '456 Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh', buildingName: b.name, buildingAddress: b.address, roomCode: room.code, roomCodeWrong: room.code.replace(/\./g, ''), roomType: room.type, area: room.area, start: '01/11/2026', end: '31/10/2027', endWrong: '31/10/2028', noticeDate: '01/10/2027', price, deposit, depositWrong, paidBefore: 1000000, paidAtSign: price - 1000000, elecIndex: 1250, waterIndex: 320, room };
  };
  const ASSET_ROWS = [['Giường', '1', 'Bình thường', 'Điều hòa và điều khiển', '1', 'Bình thường'], ['Tủ quần áo', '1', 'Bình thường', 'Bình nóng lạnh', '1', 'Bình thường'], ['Chăn ga gối', '1', 'Bình thường', 'Máy giặt', '', ''], ['Đệm', '1', 'Bình thường', 'Máy hút mùi', '', ''], ['Rèm', '1', 'Bình thường', 'Tủ lạnh', '1', 'Bình thường'], ['Bàn', '1', 'Bình thường', 'Thiết bị mạng', '1', 'Bình thường'], ['Ghế', '2', 'Bình thường', 'Quạt trần', '', ''], ['Kệ bếp, chậu rửa', '1', 'Bình thường', 'Bóng điện', '4', 'Bình thường'], ['Tủ bếp trên, dưới', '1', 'Bình thường', 'Ổ cắm điện', '6', 'Bình thường'], ['Cửa nhà vệ sinh', '1', 'Bình thường', 'Bồn rửa mặt', '1', 'Bình thường'], ['Cửa ra vào', '1', 'Bình thường', 'Gương', '1', 'Bình thường'], ['Cửa ban công', '1', 'Bình thường', 'Vòi sen, vòi xịt, bồn cầu', '1 bộ', 'Bình thường'], ['Cửa sổ', '1', 'Bình thường', 'Công tơ điện', '1', 'Bình thường'], ['Tường', '', 'Sạch', 'Đồng hồ nước', '1', 'Bình thường'], ['Đồ décor:', '', '', 'Chìa khóa phòng, cổng', '2', 'Bình thường']];
  O.sampleText = () => {
    const s = O.sampleSpec(); const v = (x) => F.vnd(x).replace(/,/g, '.') + 'đ';
    const L = ['CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM', 'Độc lập – Tự do - Hạnh phúc', '***', 'HỢP ĐỒNG CHO THUÊ PHÒNG', 'HĐ số: ' + s.contractNo, 'Hôm nay, ngày 01 tháng 11 năm 2026', 'Tại địa chỉ: ' + s.buildingAddress, 'Chúng tôi gồm:', 'BÊN CHO THUÊ PHÒNG (BÊN A):', '1. Đại diện chủ nhà (Ông/Bà): ĐỖ THỊ THÙY LINH', '- Số CMT/CCCD: 027303005504', 'Nơi cấp: Cục Cảnh Sát', '- Hộ khẩu thường trú: PHƯƠNG LIỄU - QUẾ VÕ - BẮC NINH', '- SĐT : 0364316435', '2 . BÊN THUÊ PHÒNG (BÊN B):', '- Họ tên đầy đủ: ' + s.tenantNameWrong + ' Ngày sinh: ' + s.dob, '- Các số điện thoại đang dùng: ' + s.phoneWrong, '- Số CCCD: ' + s.idNumber + ' Nơi cấp: ' + s.idPlace, '- Hộ khẩu thường trú (ghi chi tiết): ' + s.address, 'ĐIỀU 1: ĐỐI TƯỢNG CHO THUÊ VÀ MỤC ĐÍCH SỬ DỤNG', '1.1. Bên A đồng ý cho bên B thuê phòng số: ' + s.roomCodeWrong, '1.2. Bên B sử dụng phòng trên với mục đích để ở. Số lượng: 2 người. Số người tối đa là 2 người, Nếu bên B thêm người phải thông báo trước và phải được sự đồng ý của bên A. Nếu người mới đến ở quá 5 ngày thì tính thêm người. Trường hợp bên B muốn chuyển nhượng hợp đồng cho người khác phải được sự đồng ý của bên A. Số xe: 1', 'ĐIỀU 2: BÀN GIAO TÀI SẢN', '2.1. Tài sản sử dụng và bảo quản chung', 'Tất cả các tài sản chung bao gồm: thang bộ, thang máy, sân phơi, máy bơm, máy giặt chung (nếu có), hệ thống chiếu sáng, bể và bồn chứa nước, hệ thống thoát nước, hệ thống cây xanh, nhà để xe, camera đều sử dụng bình thường.', '2.2. Tài sản trong phòng', 'Tất cả tài sản dưới đây đã bàn giao cho bên B đều hoạt động bình thường.', 'Tên nội thất', 'Số', 'lượng', 'Tình trạng', 'Tên thiết bị', 'Số', 'lượng', 'Tình trạng'];
    ASSET_ROWS.forEach(r => r.forEach(c => L.push(c || ' ')));
    L.push('ĐIỀU 3: THỜI ĐIỂM GIAO NHẬN PHÒNG VÀ THỜI HẠN CHO THUÊ', '3.1. Thời điểm giao nhận phòng ở là ngày ' + s.start, '3.2. Thời điểm tính tiền phòng ở là ngày ' + s.start, '3.3. Thời hạn hợp đồng là: 12 tháng tính từ ngày ' + s.start + ' đến ngày ' + s.endWrong, '3.4. Trước 30 ngày hết hạn hợp đồng, nếu hai bên không có ý kiến gì thì thời hạn hợp đồng mặc nhiên kéo dài thêm mỗi lần 12 tháng và tự gia hạn mỗi lần kết thúc thời hạn hợp đồng.', 'Ví dụ: Bên B muốn chấm dứt hợp đồng thì phải báo cho bên A vào trước ngày ' + s.noticeDate, 'Qua ngày trên, hợp đồng mặc nhiên được gia hạn 12 tháng.', 'ĐIỀU 4: GIÁ CẢ VÀ PHƯƠNG THỨC THANH TOÁN', '4.1. Giá cho thuê phòng là: ' + v(s.price) + '/tháng (Bằng chữ: ' + F.words(s.price) + ').', '- Số tiền đã thanh toán trước khi ký hợp đồng: ' + v(s.paidBefore), '- Số tiền đóng thêm vào thời điểm ký hợp đồng: ' + v(s.paidAtSign), '4.2. Các khoản phí dịch vụ', 'Số điện: ' + s.elecIndex, 'Số nước: ' + s.waterIndex, 'Internet', '100.000đ /tháng', 'Điện:', '4.000đ /số', 'Nước:', '20.000đ /người  Xe đạp điện:', '100.000đ /xe', 'Dịch vụ chung', '(máy giặt, điện chung, thu rác, vệ sinh chung)', '150.000đ /người Xe điện dịch', 'vụ xanh SM:', '100.000/xe', '4.3. Tiền đặt cọc duy trì hợp đồng là 01 tháng tiền nhà: ' + v(s.depositWrong), '(Bằng chữ: ' + F.words(s.depositWrong) + ')', 'Tiền đặt cọc sẽ được bên A trả lại hoàn toàn cho bên B chuyển ra đúng thời hạn kết thúc hợp đồng và không có phát sinh nào xảy ra.', '4.4. Phương thức thanh toán', 'Vào ngày 25 hàng tháng, Bên A gửi thông báo tiền phòng của kì tiếp theo và tiền dịch vụ bên B đã sử dụng trong tháng đó cho bên B.', '4.4.1 Thời hạn thanh toán: Từ ngày 25 đến ngày 30 của kỳ thanh toán trước đó.', '4.4.2 Hình thức thanh toán: Chuyển khoản đến tài khoản ghi trên thông báo tiền phòng', '- Ngân hàng BIDV NGUYỄN THỊ HẰNG: 2120368058', 'Nếu Bên B chuyển vào tài khoản khác hoặc trả bằng tiền mặt, bên A không chịu trách nhiệm.', '4.4.3 Nội dung chuyển khoản: Phòng+Tòa ' + s.roomCodeWrong + ' ' + s.buildingName, '4.4.4 Bất cứ vì lí do nào đó mà bên B chậm trả tiền cho bên A thì bên B phải chịu phạt 200.000 đồng cho một ngày nộp muộn.', 'ĐIỀU 5: QUYỀN VÀ NGHĨA VỤ BÊN A', '5.2.6 Khi bên A muốn lấy lại phòng hoặc tăng giá phòng phải báo trước cho bên B một tháng.', 'ĐIỀU 6: QUYỀN VÀ NGHĨA VỤ CỦA BÊN B', '6.2.11 Trong tất cả các trường hợp chấm dứt hợp đồng, bên B phải báo trước cho bên A ít nhất 30 ngày.', 'ĐIỀU 7: CAM KẾT CÁC BÊN', '7.2. Hợp đồng được lập thành 02 bản và có giá trị như nhau. Mỗi bên giữ 01 bản.', 'ĐẠI DIỆN BÊN A', 'ĐẠI DIỆN BÊN B', '', '(File mẫu cho trích xuất OCR – demo TimoHouse Phase 2, theo template HĐ mới của Linh)');
    return L.join('\n');
  };
  /* 4 trang HTML mô phỏng template, mark = vị trí trường trên tài liệu */
  O.pages = (o) => {
    const fl = (k) => (o.fields || []).find(x => x.key === k); const mk = (k, text) => { const f = fl(k); if (!f) return esc(text || ''); const shown = text != null ? text : (f.value || '……………'); return `<mark data-ocr-mark="${k}" class="${f.confirmed ? 'ok' : 'check'}" title="${f.confirmed ? 'Đã nhận' : 'Cần kiểm tra – độ tin cậy ' + Math.round((f.confidence || 0) * 100) + '%'}">${esc(shown)}</mark>`; };
    const money = (k) => { const f = fl(k); return mk(k, f && f.value && !isNaN(Number(f.value)) ? F.vnd(Number(f.value)).replace(/,/g, '.') + 'đ' : undefined); };
    const assets = o.assets && o.assets.length ? o.assets : []; const fu = assets.filter(a => a.kind === 'furniture'), dv = assets.filter(a => a.kind === 'device'); const n = Math.max(fu.length, dv.length, 1);
    const cell = (a) => a ? `<td>${esc(a.name)}${a.desc ? ' ' + esc(a.desc) : ''}</td><td class="c">${esc(a.qty)}</td><td>${esc(a.condition)}</td>` : '<td></td><td></td><td></td>';
    const assetRows = (from, to) => Array.from({ length: Math.max(0, Math.min(to, n) - from) }, (_, i) => `<tr>${cell(fu[from + i])}${cell(dv[from + i])}</tr>`).join('');
    const p1 = `<h3>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</h3><p class="c"><b>Độc lập – Tự do - Hạnh phúc</b></p><p class="c">***</p><h4>HỢP ĐỒNG CHO THUÊ PHÒNG</h4><p class="c"><b>HĐ số:</b> ${mk('contractNo')}</p><p>Hôm nay, ngày ${mk('signDate')}<br>Tại địa chỉ: ${mk('signPlace')}<br>Chúng tôi gồm:</p><p><b>BÊN CHO THUÊ PHÒNG (BÊN A):</b><br>1. Đại diện chủ nhà (Ông/Bà): ${mk('landlordName')}<br>- Số CMT/CCCD: ${mk('landlordId')} &nbsp; Nơi cấp: ${mk('landlordIdPlace')}<br>- Hộ khẩu thường trú: ${mk('landlordAddress')}<br>- SĐT: ${mk('landlordPhone')}</p><p><b>2. BÊN THUÊ PHÒNG (BÊN B):</b><br>- Họ tên đầy đủ: ${mk('tenantName')} &nbsp; Ngày sinh: ${mk('dob')}<br>- Các số điện thoại đang dùng: ${mk('phone')}<br>- Số CCCD: ${mk('idNumber')} &nbsp; Nơi cấp: ${mk('idPlace')}<br>- Hộ khẩu thường trú (ghi chi tiết): ${mk('address')}</p><p><b>ĐIỀU 1: ĐỐI TƯỢNG CHO THUÊ VÀ MỤC ĐÍCH SỬ DỤNG</b><br>1.1. Bên A đồng ý cho bên B thuê phòng số: ${mk('roomCode')} (tòa ${mk('buildingName')})<br>1.2. Bên B sử dụng phòng trên với mục đích để ở. Số lượng: ${mk('occupants')} người. Số người tối đa là ${mk('maxOccupants')} người. Nếu người mới đến ở quá 5 ngày thì tính thêm người. Số xe: ${mk('vehicleCount')}</p><p><b>ĐIỀU 2: BÀN GIAO TÀI SẢN</b><br>2.1. Tài sản sử dụng và bảo quản chung: thang bộ, thang máy, sân phơi, máy bơm, hệ thống chiếu sáng, bể nước, nhà để xe, camera đều sử dụng bình thường.<br>2.2. Tài sản trong phòng – đã bàn giao cho bên B, hoạt động bình thường:</p><table class="dp-table"><tr><th>Tên nội thất</th><th>SL</th><th>Tình trạng</th><th>Tên thiết bị</th><th>SL</th><th>Tình trạng</th></tr>${assetRows(0, 7)}</table>`;
    const p2 = `<table class="dp-table">${assetRows(7, n)}</table><p><b>ĐIỀU 3: THỜI ĐIỂM GIAO NHẬN PHÒNG VÀ THỜI HẠN CHO THUÊ</b><br>3.1. Thời điểm giao nhận phòng ở là ngày ${mk('handoverDate')}<br>3.2. Thời điểm tính tiền phòng ở là ngày ${mk('billingStart')}<br>3.3. Thời hạn hợp đồng là: ${mk('months')} tháng tính từ ngày ${mk('start')} đến ngày ${mk('end')}<br>3.4. Trước 30 ngày hết hạn hợp đồng, nếu hai bên không có ý kiến gì thì thời hạn hợp đồng mặc nhiên kéo dài thêm mỗi lần 12 tháng. Ví dụ: Bên B muốn chấm dứt hợp đồng thì phải báo cho bên A vào trước ngày ${mk('noticeDate')}</p><p><b>ĐIỀU 4: GIÁ CẢ VÀ PHƯƠNG THỨC THANH TOÁN</b><br>4.1. Giá cho thuê phòng là: ${money('price')}/tháng (Bằng chữ: ${mk('priceWords')}).<br>- Số tiền đã thanh toán trước khi ký hợp đồng: ${money('paidBefore')}<br>- Số tiền đóng thêm vào thời điểm ký hợp đồng: ${money('paidAtSign')}<br>4.2. Các khoản phí dịch vụ &nbsp; Số điện: ${mk('elecIndex')} &nbsp; Số nước: ${mk('waterIndex')}</p><table class="dp-table dp-svc"><tr><td>Internet</td><td>${money('svc_internet')} /tháng</td><td></td><td></td></tr><tr><td>Điện:</td><td>${money('svc_electric')} /số</td><td></td><td></td></tr><tr><td>Nước:</td><td>${money('svc_water')} /người</td><td>Xe đạp điện:</td><td>${money('svc_ebike')} /xe</td></tr><tr><td>Dịch vụ chung (máy giặt, điện chung, thu rác, vệ sinh chung)</td><td>${money('svc_common')} /người</td><td>Xe điện dịch vụ xanh SM:</td><td>${money('svc_evcar')} /xe</td></tr></table><p>4.3. Tiền đặt cọc duy trì hợp đồng là 01 tháng tiền nhà: ${money('deposit')}<br>(Bằng chữ: ${mk('depositWords')})<br>Tiền đặt cọc sẽ được bên A trả lại hoàn toàn cho bên B chuyển ra đúng thời hạn kết thúc hợp đồng và không có phát sinh nào xảy ra. Bên thuê sẽ chịu phí nhượng phòng là 200.000đ.<br>4.4. Phương thức thanh toán: Vào ngày ${mk('payDay')} hàng tháng, Bên A gửi thông báo tiền phòng của kỳ tiếp theo.<br>4.4.1 Thời hạn thanh toán: Từ ngày 25 đến ngày 30 của kỳ thanh toán trước đó.<br>4.4.2 Hình thức thanh toán: Chuyển khoản – Ngân hàng ${mk('bankAccount')}<br><b>Nếu Bên B chuyển vào tài khoản khác hoặc trả bằng tiền mặt, bên A không chịu trách nhiệm.</b></p>`;
    const p3 = `<p>4.4.3 Nội dung chuyển khoản: Phòng+Tòa ${mk('transferNote')}<br>4.4.4 Bên B chậm trả tiền phải chịu phạt 200.000 đồng/ngày nộp muộn, tính từ ngày mùng 1 tháng sau. Thời hạn chậm trả không quá 03 ngày; quá hạn, bên A có quyền đơn phương chấm dứt hợp đồng và không trả lại tiền đặt cọc.</p><p><b>ĐIỀU 5: QUYỀN VÀ NGHĨA VỤ BÊN A</b><br>5.1. Yêu cầu bên B trả đủ tiền thuê và dịch vụ đúng hạn; đơn phương chấm dứt khi bên B vi phạm hợp đồng, nội quy tòa nhà.<br>5.2. Giao phòng và thiết bị đúng ngày; bảo hành thiết bị 10 ngày kể từ bàn giao; sửa chữa sự cố ngoài phòng; báo trước một tháng khi lấy lại phòng hoặc tăng giá.</p><p><b>ĐIỀU 6: QUYỀN VÀ NGHĨA VỤ CỦA BÊN B</b><br>6.1. Nhận phòng đúng ngày; yêu cầu bên A sửa chữa hư hỏng không do mình gây ra.<br>6.2. Sử dụng đúng mục đích; trả tiền đúng hạn; chấp hành nội quy; sau 10 ngày bảo hành tự chịu chi phí sửa chữa; làm bẩn tường phạt 600.000đ; thuê từ 3 tháng bồi thường khấu hao thiết bị ít nhất 200.000đ; đăng ký tạm trú; tuân thủ PCCC.</p>`;
    const p4 = `<p>6.2.9 – 6.2.12: Tự bảo quản tài sản, xe cộ; không đánh bạc, chất cấm, gây ồn; báo trước ít nhất 30 ngày khi chấm dứt hợp đồng và phối hợp cho khách mới xem phòng.</p><p><b>ĐIỀU 7: CAM KẾT CÁC BÊN</b><br>7.1. Hai bên cam kết thực hiện đúng nội dung đã ký; bên B vi phạm hoặc đơn phương chấm dứt trước hạn mất toàn bộ tiền cọc.<br>7.2. Hợp đồng lập thành 02 bản có giá trị như nhau, mỗi bên giữ 01 bản, có giá trị kể từ ngày ký.</p><div class="dp-sign"><div><b>ĐẠI DIỆN BÊN A</b><br><small>(Ký và ghi rõ họ tên)</small><br><br><br>${mk('landlordName')}</div><div><b>ĐẠI DIỆN BÊN B</b><br><small>(Ký và ghi rõ họ tên)</small><br><br><br>${mk('tenantName')}</div></div>`;
    return [p1, p2, p3, p4];
  };
  TH.ocr = O;
  /* ===================== Màn OCR & Data Onboarding (§12.8) ===================== */
  const STEPS = [{ title: 'Tải file', sub: 'PDF/JPG · kiểm tra hash' }, { title: 'Trích xuất', sub: 'OCR · chuẩn hóa · match' }, { title: 'Review', sub: '13 nhóm entity' }, { title: 'Xác nhận', sub: 'Validate → Commit' }, { title: 'Kết quả', sub: 'Entity đã tạo / liên kết' }];
  const stepOf = (j) => !j ? 0 : ['UPLOADED', 'PROCESSING', 'FAILED'].includes(j.status) ? 1 : ['READY_FOR_REVIEW', 'REVIEWING'].includes(j.status) ? 2 : ['VALIDATED', 'COMMIT_FAILED'].includes(j.status) ? 3 : 4;
  const confChip = (f) => f.decision === 'reject' ? U.chip('Bỏ qua', 'gray') : f.decision === 'pending' ? `<span class="chip amber" title="Độ tin cậy ${Math.round(f.confidence * 100)}%">${I('alert-circle')} ${Math.round(f.confidence * 100)}%</span>` : `<span class="chip ${f.decision === 'edit' ? 'blue' : 'green'}" title="${f.decision === 'edit' ? 'Đã sửa' : 'Đã xác nhận'} · ${Math.round(f.confidence * 100)}%">${I('check')} ${Math.round(f.confidence * 100)}%</span>`;
  const DEC = { create: ['Create', 'green'], link: ['Link', 'blue'], update: ['Update', 'amber'], ignore: ['Ignore', 'gray'] };
  const decChip = (d) => U.chip(DEC[d] ? DEC[d][0] : d, DEC[d] ? DEC[d][1] : 'gray');
  const vnd = (n) => n ? F.vnd(n) + 'đ' : '–';
  const uploadSample = (docType, opts = {}) => {
    const r = X.ocrUpload({ fileName: opts.image ? 'HD-cho-thue-phong-scan.jpg' : 'HD-cho-thue-phong-mau.txt', size: opts.image ? 1.6 * 1024 * 1024 : 12 * 1024, sample: !opts.image, text: opts.image ? O.sampleText() + '\n[scan ' + Date.now() + ']' : '', simulated: !!opts.image, pages: 4, docType });
    if (r.duplicate) { U.confirm({ title: 'File đã được tải trước đó', text: 'Hash trùng với job ' + r.code + ' (' + Q.label('ocrJob', r.status) + (r.result && r.result.contractId ? ', đã tạo HĐ ' + (Q.contract(r.result.contractId) || {}).code : '') + '). Không tạo job/hợp đồng trùng (AC-1).', ok: 'Mở job cũ', cancel: 'Tải bản sao mới (demo)' }).then(ok => { if (ok) TH.go('#/contracts/ocr?id=' + r.id); else { const x = X.ocrUpload({ fileName: 'HD-cho-thue-phong-mau-' + Date.now().toString().slice(-4) + '.txt', size: 12 * 1024, text: O.sampleText() + '\n[bản sao demo ' + Date.now() + ']', pages: 4, docType }); TH.go('#/contracts/ocr?id=' + x.id + (opts.fail ? '&fail=1' : '')); } }); return; }
    TH.go('#/contracts/ocr?id=' + r.id + (opts.fail ? '&fail=1' : ''));
  };
  TH.ocr.uploadSample = uploadSample;

  TH.router.register('/contracts/ocr', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Trích xuất hợp đồng (OCR)' }]);
    const Onb = TH.ocrOnb; const j = q.id ? Q.ocrJob(q.id) : null; const step = stepOf(j);
    const head = U.pageHead({ title: 'Trích xuất hợp đồng & Data Onboarding', chips: j ? ' ' + Q.chip('ocrJob', j.status, 'lg') : '', sub: j ? `${esc(j.code)} · ${esc(j.fileName)} · ${Q.label('docType', j.docType)} · engine ${esc(j.engine || 'mock-1')} · hash <span class="mono">${esc(String(j.fileHash || '').slice(0, 10))}</span>${j.uploadedBy ? ' · ' + esc(Q.userName(j.uploadedBy)) : ''}` : 'Bắt đầu nghiệp vụ từ file hợp đồng: OCR → chuẩn hóa → match dữ liệu có sẵn → review từng nhóm entity → Create / Link / Update / Ignore → Validate → Commit 1 transaction (spec v1.8 §12.8).', acts: j ? [U.btn({ label: 'Danh sách job', icon: 'list', cls: 'btn-outline', act: 'jobs' })] : [] });
    const wiz = U.wizard(STEPS, step);

    /* ---------- Bước 1: Upload + danh sách job ---------- */
    if (!j) {
      const jobs = Q.ocrJobs();
      root.innerHTML = head + wiz + `<div class="two-col wide" style="grid-template-columns:minmax(0,1fr) minmax(0,1.15fr)"><div class="side-stack">
        ${U.card({ title: 'Bước 1 – Tải file hợp đồng', icon: 'upload', body: `${U.field({ label: 'Loại tài liệu', input: U.select({ name: 'docType', value: 'contract', options: Object.entries(Q.L.docType).map(([k, v]) => [k, v[0]]), attrs: { id: 'ocr-doctype' } }), help: 'OCR Data Onboarding áp dụng cho Hợp đồng thuê; loại khác chỉ lưu vào Tài liệu' })}${U.dropzone({ name: 'ocr', hint: 'PDF điền trên máy, JPG/PNG (OCR ảnh mô phỏng) hoặc .txt theo mẫu HĐ cho thuê phòng · tối đa 20MB · trùng hash → mở job cũ (AC-1)', multiple: false, accept: '.pdf,.txt,.jpg,.jpeg,.png' })}<div class="row mt12 gap12 wrap">${U.btn({ label: 'Dùng file mẫu (.txt)', icon: 'file-text', cls: 'btn-primary', act: 'sample', attrs: { 'data-guide': 'ocr-sample' } })}${U.btn({ label: 'Mô phỏng ảnh JPG', icon: 'image', cls: 'btn-outline', act: 'sample-img' })}${U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-outline', act: 'dl' })}${U.btn({ label: 'Nhập tay', icon: 'pencil', cls: 'btn-ghost', act: 'manual' })}</div>` })}
        ${U.note('info', 'Trạng thái job (§12.8.3)', 'UPLOADED → PROCESSING → READY_FOR_REVIEW → REVIEWING → VALIDATED → COMMITTED · nhánh lỗi PROCESSING → FAILED, VALIDATED → COMMIT_FAILED (có "Xử lý lại"/"Thử lại"). Mỗi field lưu raw, normalized, confidence, trang, vùng, candidate, quyết định và người review (§12.8.4).')}
        <details class="card"><summary class="card-b" style="cursor:pointer"><b>${I('flask')} Kịch bản demo trong file mẫu</b></summary><div class="card-b small" style="padding-top:0"><ul style="padding-left:18px;margin:0 0 10px"><li>Khách: CCCD trùng hồ sơ <b>Nguyễn Thị Hương</b> (đang giữ chỗ) nhưng tên viết không dấu và SĐT thiếu số → cảnh báo xung đột, bắt buộc review (§12.8.6).</li><li>Tòa/phòng: khớp Tòa Sunrise, mã phòng thiếu dấu chấm → gợi ý LINK phòng có sẵn.</li><li>Dịch vụ: giá điện trên HĐ 4.000đ ≠ giá tòa Sunrise 3.800đ → chọn [Chỉ HĐ này] / [Cập nhật giá tòa] / [Ignore] (§12.8.10).</li><li>Cọc lệch giá, ngày kết thúc sai năm → trường Cần kiểm tra; chỉ số điện/nước đầu kỳ, tài sản bàn giao, điều khoản thanh toán, tự gia hạn 12 tháng/báo trước 30 ngày được tách thành entity riêng.</li></ul>${U.btn({ label: 'Mô phỏng lỗi xử lý (FAILED → Xử lý lại)', icon: 'alert-triangle', cls: 'btn-outline btn-sm', act: 'sample-fail' })}</div></details>
      </div><div>${U.card({ title: 'OCR Job', sub: jobs.length + ' job · ' + Q.ocrPending().length + ' chờ review', icon: 'layers', id: 'jobs-card', bodyCls: 'tight', body: '' })}</div></div>`;
      const wrap = root.querySelector('#jobs-card .card-b') || root.querySelector('#jobs-card'); const tbl = document.createElement('div'); wrap.appendChild(tbl);
      U.table(tbl, { rows: jobs, unit: 'job', pageSize: 8, cols: [{ key: 'code', label: 'Job', render: x => `<a class="link" href="#/contracts/ocr?id=${x.id}"><b>${esc(x.code)}</b></a><div class="xs muted">${esc(x.fileName)}${x.simulated ? ' · OCR ảnh mô phỏng' : ''}</div>` }, { key: 'docType', label: 'Loại', render: x => Q.chip('docType', x.docType || 'contract') }, { key: 'status', label: 'Trạng thái', render: x => Q.chip('ocrJob', x.status) + (x.error ? `<div class="xs red">${esc(x.error).slice(0, 60)}</div>` : '') }, { key: 'up', label: 'Tải lên', render: x => `${esc(Q.userName(x.uploadedBy))}<div class="xs muted">${F.datetime(x.uploadedAt || x.createdAt)}</div>` }, { key: 'hash', label: 'Hash', render: x => `<span class="mono xs">${esc(String(x.fileHash || '').slice(0, 10))}</span>` }, { key: 'res', label: 'Kết quả', render: x => x.result && x.result.contractId ? U.link('#/contracts/' + x.result.contractId, esc((Q.contract(x.result.contractId) || {}).code || 'HĐ')) : (x.status === 'COMMIT_FAILED' ? '<span class="red xs">Rollback</span>' : '<span class="muted">–</span>') }, { key: 'a', label: '', render: x => `<a class="btn btn-ghost btn-sm" href="#/contracts/ocr?id=${x.id}">Mở</a>` }], empty: U.empty({ icon: 'scan', title: 'Chưa có job OCR', text: 'Tải file hợp đồng hoặc dùng file mẫu để bắt đầu.' }) });
      U.bindDropzones(root, async (files) => { const f = files[0]; if (!f) return; const docType = root.querySelector('#ocr-doctype').value; try { if (f.size > 20 * 1024 * 1024) throw new Error('File tối đa 20MB (FR-DOC-01)'); U.toast('info', 'Đang đọc file…', f.name); const r = await P.readFile(f); if (!r.text || r.text.trim().length < 50) throw new Error('Không đọc được nội dung văn bản – file có thể là ảnh scan không rõ'); const x = X.ocrUpload({ fileName: f.name, size: f.size, text: r.text, pages: r.pages, docType, simulated: !!r.simulated }); if (x.duplicate) { U.toast('warn', 'File đã được tải trước đó', 'Trùng hash với job ' + x.code + ' – mở job cũ, không tạo trùng (AC-1)'); TH.go('#/contracts/ocr?id=' + x.id); return; } if (r.note) U.toast('info', 'OCR ảnh mô phỏng', r.note); TH.go('#/contracts/ocr?id=' + x.id); } catch (e) { U.toast('err', 'Không tải được', e.message); } });
      U.bind(root, { manual: () => TH.go('#/contracts/new'), sample: () => uploadSample(root.querySelector('#ocr-doctype').value), 'sample-img': () => uploadSample(root.querySelector('#ocr-doctype').value, { image: true }), 'sample-fail': () => uploadSample(root.querySelector('#ocr-doctype').value, { fail: true }), dl: () => { F.download('HD-cho-thue-phong-mau.txt', O.sampleText()); U.toast('ok', 'Đã tải file mẫu', 'HĐ theo template đã điền, dùng để thử trích xuất'); } });
      return;
    }

    /* ---------- Bước 2: Đang xử lý / FAILED ---------- */
    if (step === 1) {
      const np = j.pages || 4;
      if (j.status === 'FAILED') { root.innerHTML = head + wiz + U.card({ title: 'Trích xuất lỗi', icon: 'alert-circle', body: `${U.note('danger', 'PROCESSING → FAILED', esc(j.error || 'Lỗi không xác định') + '<div class="xs muted mt4">Job giữ nguyên file, hash và loại tài liệu; "Xử lý lại" chạy OCR lại từ đầu (§4.10 nhánh lỗi).</div>')}<div class="row gap12 mt12">${U.btn({ label: 'Xử lý lại', icon: 'refresh-cw', cls: 'btn-primary', act: 'retry' })}${U.btn({ label: 'Tải file khác', icon: 'upload', cls: 'btn-outline', act: 'jobs' })}</div>` }); U.bind(root, { retry: () => { try { X.ocrRetry(j.id); TH.go('#/contracts/ocr?id=' + j.id); } catch (e) { U.toast('err', 'Không xử lý lại được', e.message); } }, jobs: () => TH.go('#/contracts/ocr') }); return; }
      root.innerHTML = head + wiz + U.card({ title: 'Bước 2 – Đang trích xuất ' + esc(j.fileName), icon: 'scan', body: `<div class="tc" style="padding:30px 0"><div class="big" style="width:72px;height:72px;border-radius:20px;background:var(--blue-bg);color:var(--blue);display:grid;place-items:center;margin:0 auto 14px">${I('scan')}</div><b style="font-size:16px">Engine ${esc(j.engine || 'mock-1')} đang đọc ${np} trang${j.simulated ? ' (OCR ảnh mô phỏng)' : ''}</b><div class="muted small mt4" id="ocr-msg">Đọc trang 1/${np}…</div><div class="progress" style="max-width:360px;margin:16px auto 0"><i id="ocr-bar" style="width:5%"></i></div><div class="xs muted mt12">PROCESSING → chuẩn hóa → tách 13 nhóm entity → match khách (CCCD → SĐT → tên+ngày sinh), tòa (mã/tên/địa chỉ), phòng (tòa + mã), chống trùng HĐ (số HĐ / hash / khách+phòng+ngày)</div></div>` });
      if (j.status === 'UPLOADED') X.ocrExtract(j.id);
      const bar = root.querySelector('#ocr-bar'), msg = root.querySelector('#ocr-msg'); let k = 0; const msgs = ['Đọc trang 1/' + np + '…', 'Nhận diện bên A / bên B…', 'Tách nhóm entity & tài sản bàn giao…', 'Match dữ liệu hiện có (khách, tòa, phòng, giá tòa)…', 'Chấm điểm độ tin cậy…', 'Hoàn tất'];
      const t = setInterval(() => { k++; if (!document.contains(bar)) return clearInterval(t); bar.style.width = Math.min(100, k * 20) + '%'; msg.textContent = msgs[Math.min(k, 5)]; if (k >= 5) { clearInterval(t); try { X.ocrFinish(j.id, { simulateFail: q.fail === '1' }); } catch (e) { U.toast('err', 'Trích xuất lỗi', e.message); } TH.router.replaceQuery({ id: j.id }); TH.router.refresh(); } }, 380);
      U.bind(root, { jobs: () => TH.go('#/contracts/ocr') });
      return;
    }

    /* ---------- Bước 5: Kết quả (COMMITTED) ---------- */
    if (step === 4) {
      const res = j.result || { entities: [] }; const c = res.contractId ? Q.contract(res.contractId) : null;
      const byGroup = {}; res.entities.forEach(e => (byGroup[e.group] = byGroup[e.group] || []).push(e));
      root.innerHTML = head + wiz + `${U.note('ok', 'Đã ghi dữ liệu (COMMITTED)', 'Hợp đồng ' + (c ? U.link('#/contracts/' + c.id, esc(c.code)) : '') + ' ở trạng thái <strong>Dự thảo</strong> – OCR không tự kích hoạt (AC-11) và không tự gia hạn (AC-12). Commit lúc ' + F.datetime(j.committedAt) + ' bởi ' + esc(Q.userName(j.committedBy)) + ' · idempotency <span class="mono">' + esc(j.idempotencyKey) + '</span>')}
        <div class="two-col wide" style="grid-template-columns:minmax(0,1.3fr) minmax(0,1fr)"><div>${U.card({ title: 'Entity đã tạo / liên kết (§12.8.15)', icon: 'layers', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Nhóm</th><th>Hành động</th><th>Bản ghi</th><th>Xuất hiện tại</th></tr></thead><tbody>${res.entities.map(e => `<tr><td class="xs"><b>${esc(({ CONTRACT_TENANT: 'Người thuê' }[e.group]) || (P.ENTITY_GROUPS.find(g => g[0] === e.group) || [e.group, e.group])[1])}</b></td><td>${decChip(String(e.action || '').toLowerCase())}</td><td>${e.href ? U.link(e.href, esc(e.label)) : esc(e.label)}</td><td class="xs muted">${esc({ CUSTOMER: 'Khách thuê › hồ sơ', OCCUPANT: 'Khách thuê › hồ sơ', BUILDING: 'Tòa nhà', ROOM: 'Phòng', CONTRACT: 'Hợp đồng · Khách › Hợp đồng · Tòa/Phòng › Hợp đồng', CONTRACT_TENANT: 'Hợp đồng › Người thuê', CONTRACT_SERVICE: 'Hợp đồng › Dịch vụ (snapshot) · Tòa › Dịch vụ & Bảng giá', DEPOSIT: 'Hợp đồng › Cọc (Deposit Ledger)', VEHICLE: 'Hợp đồng › Dịch vụ & xe', METER_READING: 'Phòng › Chỉ số · Điện/Nước', HANDOVER_ASSET: 'Hợp đồng › Điều khoản & bàn giao', PAYMENT_TERM: 'Hợp đồng › Điều khoản & bàn giao', RENEWAL_CLAUSE: 'Hợp đồng › Điều khoản · Work Queue HĐ sắp hết', DOCUMENT: 'Hợp đồng › Tài liệu · Document Center' }[e.group] || '')}</td></tr>`).join('')}</tbody></table>` })}</div>
        <div class="side-stack">${U.card({ title: 'Bước tiếp theo', icon: 'arrow-right', body: `<div class="col gap8">${U.btn({ label: 'Mở hợp đồng ' + (c ? c.code : ''), icon: 'file-text', cls: 'btn-primary btn-block', act: 'open', attrs: { 'data-guide': 'ocr-open-contract' } })}${U.btn({ label: 'Kích hoạt hợp đồng (review → duyệt)', icon: 'check-circle', cls: 'btn-outline btn-block', act: 'activate', disabled: !c || c.status !== 'draft' })}${U.btn({ label: 'Tải file khác', icon: 'upload', cls: 'btn-ghost btn-block', act: 'jobs' })}</div>` })}${U.card({ title: 'Truy vết (§12.8.17)', icon: 'search', body: U.kv([['Job', esc(j.code)], ['File', esc(j.fileName) + ' · ' + esc(j.size || '')], ['Hash', '<span class="mono xs">' + esc(j.fileHash) + '</span>'], ['Engine', esc(j.engine)], ['Xử lý', (j.processingMs ? (j.processingMs / 1000).toFixed(1) + ' s · ' : '') + F.datetime(j.processedAt)], ['Review', esc(Q.userName(j.reviewedBy || j.validatedBy || j.committedBy))], ['Validate', F.datetime(j.validatedAt)], ['Commit', F.datetime(j.committedAt)]], 'one') + '<div class="xs muted mt8">Mỗi entity/field truy được: Job → File → Trang → Vùng → Raw → Normalized → Quyết định → Người review (lưu ở audit log với sourceOcr).</div>' })}</div></div>`;
      U.bind(root, { open: () => c && TH.go('#/contracts/' + c.id), activate: () => c && TH.go('#/contracts/new?id=' + c.id + '&step=5'), jobs: () => TH.go('#/contracts/ocr') });
      return;
    }

    /* ---------- Bước 3–4: Review theo nhóm entity + Validate/Commit ---------- */
    const fields = j.fields || []; const pending = fields.filter(f => f.decision === 'pending'); const page = Number(q.page || 1); const zoom = Number(q.zoom || 100); const npages = O.pages(j).length;
    const S = Onb.sections(j); const lastV = j.lastValidation || null; const errsOf = (g) => lastV ? lastV.errors.filter(e => e.group === g) : []; const warnsOf = (g) => lastV ? lastV.warnings.filter(e => e.group === g) : [];
    const openSet = new Set(String(q.open || '').split(',').filter(Boolean));
    const isOpen = (s) => openSet.size ? openSet.has(s.key) : (s.pending > 0 || (s.needsResolve && !s.resolved) || (s.unresolved && s.unresolved.length) || errsOf(s.key).length > 0 || ['CUSTOMER', 'ROOM', 'CONTRACT'].includes(s.key));
    const control = (f) => { const d = P.field(f.key) || { type: 'text' }; const at = { 'data-on': 'field', 'data-k': f.key }; if (d.type === 'date') return U.date({ name: f.key, value: F.fromVN(f.value) || '', attrs: at }); if (d.type === 'money') return U.money({ name: f.key, value: f.value === '' ? '' : F.num(f.value), attrs: at }); if (d.type === 'number' || (d.type === 'select' && f.key === 'payDay')) return U.input({ name: f.key, value: f.value, type: 'number', attrs: at }); return U.input({ name: f.key, value: f.value, attrs: at }); };
    const fieldRow = (f) => `<tr class="ocr-field ${f.decision === 'pending' ? 'is-pending' : ''}" data-ocr-field="${f.key}"><td class="xs" style="width:150px"><b>${esc(f.label)}</b>${f.raw !== f.value && f.decision !== 'reject' ? `<div class="xs muted" title="Raw OCR">raw: ${esc(f.raw || '∅')}</div>` : ''}</td><td>${f.decision === 'reject' ? '<span class="muted xs">— bỏ qua —</span>' : control(f)}</td><td style="width:70px">${confChip(f)}</td><td class="xs" style="width:52px"><a class="link" data-act="page" data-k="${f.key}" title="Trang ${f.page} · vùng ${f.bbox ? f.bbox.x + ',' + f.bbox.y + ' ' + f.bbox.w + '×' + f.bbox.h + '%' : ''}">Tr.${f.page || 1}</a></td><td class="tr nowrap" style="width:64px">${f.decision === 'pending' ? U.iconBtn('check', 'accept', 'Xác nhận', { 'data-k': f.key }) : ''}${f.decision !== 'reject' ? U.iconBtn('x', 'reject', 'Bỏ qua trường', { 'data-k': f.key }) : U.iconBtn('rotate-ccw', 'accept', 'Khôi phục', { 'data-k': f.key })}</td></tr>`;
    const fieldTable = (fs) => fs.length ? `<table class="tbl compact ocr-fields"><tbody>${fs.map(fieldRow).join('')}</tbody></table>` : '';
    const seg = (s) => `<div class="seg sm">${['create', 'link', 'update', 'ignore'].filter(d => s.allowed.includes(d) || (d === 'create' && s.createBlocked)).map(d => `<button type="button" class="${s.decision === d ? 'on' : ''}" data-act="dec" data-g="${s.key}" data-d="${d}" ${s.allowed.includes(d) ? '' : 'disabled title="' + esc(s.createBlocked || '') + '"'}>${DEC[d][0]}</button>`).join('')}</div>`;
    const candSel = (s, opts, label) => ['link', 'update'].includes(s.decision) ? U.field({ label, input: U.select({ name: 'cand_' + s.key, value: s.candidateId || '', placeholder: 'Chọn…', options: opts, attrs: { 'data-on': 'cand', 'data-g': s.key } }) }) : '';
    const secHead = (s) => { const errs = errsOf(s.key); return `<summary class="card-b ocr-sec-h"><span class="row gap8"><b>${I(s.icon)} ${esc(s.label)}</b>${decChip(s.decision)}${s.pending ? U.chip(s.pending + ' cần kiểm tra', 'amber') : ''}${s.needsResolve && !s.resolved ? U.chip('Xung đột', 'red') : ''}${s.unresolved && s.unresolved.length ? U.chip(s.unresolved.length + ' xung đột giá', 'red') : ''}${errs.length ? U.chip(errs.length + ' lỗi', 'red') : ''}</span><span class="xs muted">${esc(s.summary || '')}</span></summary>`; };
    const secBody = (s, inner) => `<div class="card-b" style="padding-top:0">${errsOf(s.key).map(e => `<div class="note-box danger sm">${I('alert-circle')}<div>${esc(e.msg)}</div></div>`).join('')}${warnsOf(s.key).map(e => `<div class="note-box warn sm">${I('alert-triangle')}<div>${esc(e.msg)}</div></div>`).join('')}<div class="row between wrap gap8 mb8"><div class="row gap8"><span class="xs muted">Quyết định</span>${seg(s)}</div>${s.fields.filter(f => f.decision === 'pending').length ? U.btn({ label: 'Xác nhận tất cả trường', icon: 'check', size: 'btn-sm', cls: 'btn-ghost', act: 'accept-group', attrs: { 'data-g': s.key } }) : ''}</div>${inner}</div>`;
    const sysTenant = (t) => t ? `<b>${esc(t.name)}</b> <span class="muted">${esc(t.code)} · ${esc(t.phone || '')}${t.idNumber ? ' · CCCD ' + esc(t.idNumber) : ''}${t.dob ? ' · ' + F.date(t.dob) : ''}</span>` : '';
    const render = {
      CUSTOMER: (s) => { const cand = s.candidateId ? St.rawGet('tenants', s.candidateId) : null; return secBody(s, `${s.conflicts.length ? U.note('danger', 'Xung đột dữ liệu – bắt buộc review (§12.8.6)', '<ul style="margin:4px 0 0 16px">' + s.conflicts.map(x => `<li>${esc(x.msg)}${x.system ? ': hệ thống <strong>' + esc(x.system) + '</strong>' : ''}${x.ocr ? ' ↔ OCR <strong>' + esc(x.ocr) + '</strong>' : ''}</li>`).join('') + '</ul><div class="xs mt4">Chọn <strong>Link</strong> (giữ hồ sơ hệ thống), <strong>Update</strong> (ghi giá trị OCR đè lên hồ sơ, có audit) hoặc <strong>Create</strong> nếu là người khác.</div>') : ''}${s.match ? `<div class="small mb8">${I('user-check')} Khớp theo <b>${esc(s.matchBy)}</b> (điểm ${Math.round(s.score * 100)}%): ${sysTenant(s.match)} ${U.link('#/tenants/' + s.match.id, 'Xem hồ sơ')}</div>` : s.weak ? `<div class="small mb8">${I('info')} Trùng tên với ${sysTenant(s.weak)} nhưng khác SĐT/CCCD/ngày sinh → đề xuất tạo khách mới; chọn Link nếu cùng người.</div>` : `<div class="small mb8 muted">${I('user-plus')} Không tìm thấy khách theo CCCD → SĐT → Họ tên + Ngày sinh → đề xuất <b>Create</b>.</div>`}${candSel(s, s.candidates.concat(St.rawAll('tenants').filter(t => t && !s.candidates.some(c => c.id === t.id)).sort((a, b) => F.cmp(a.name, b.name))).map(t => [t.id, t.name + ' · ' + (t.phone || '') + (t.idNumber ? ' · ' + t.idNumber : '') + ' (' + t.code + ')']), 'Hồ sơ khách hệ thống')}${cand && (s.diffs.length || s.missing.length) ? `<table class="tbl compact mb8"><thead><tr><th>Trường</th><th>Hệ thống</th><th>OCR</th><th>Khi Update</th></tr></thead><tbody>${s.diffs.map(x => `<tr><td class="xs">${esc((P.field({ name: 'tenantName', phone: 'phone', idNumber: 'idNumber', dob: 'dob', address: 'address' }[x.field]) || {}).label || x.field)}</td><td>${esc(x.system || '')}</td><td><b>${esc(x.ocr || '')}</b></td><td class="xs">${s.decision === 'update' ? '<span class="amber">Ghi đè</span>' : '<span class="muted">Giữ hệ thống</span>'}</td></tr>`).join('')}${s.missing.map(k => `<tr><td class="xs">${esc((P.field({ idNumber: 'idNumber', idPlace: 'idPlace', dob: 'dob', address: 'address', phone: 'phone' }[k]) || {}).label || k)}</td><td class="muted">∅</td><td><b>${esc(s.data[k] || '')}</b></td><td class="xs">${s.decision === 'update' ? '<span class="green">Bổ sung</span>' : '<span class="muted">Bỏ qua</span>'}</td></tr>`).join('')}</tbody></table>` : ''}${fieldTable(s.fields)}`); },
      BUILDING: (s) => secBody(s, `${s.match ? `<div class="small mb8">${I('building')} Liên kết <b>${esc(s.match.name)}</b> (${esc(s.match.code || '')}) – khớp theo <b>${esc(s.matchBy)}</b> · ${esc(s.match.address || '')} ${U.link('#/buildings/' + s.match.id, 'Xem tòa')}</div>` : `<div class="small mb8 red">${I('alert-circle')} Chưa khớp tòa nào – chọn tòa để liên kết.</div>`}${U.field({ label: 'Tòa nhà hệ thống', input: U.select({ name: 'cand_BUILDING', value: s.candidateId || '', placeholder: 'Chọn tòa…', options: s.candidates.map(b => [b.id, b.name + (b.code ? ' (' + b.code + ')' : '') + ' – ' + (b.address || '')]), attrs: { 'data-on': 'cand', 'data-g': 'BUILDING' } }) })}<div class="xs muted mb8">HĐ ghi: tòa "${esc(s.name || '–')}" · địa chỉ ký "${esc(s.address || '–')}" · chủ nhà "${esc(s.landlord || '–')}". ${esc(s.createBlocked)}.</div>${fieldTable(s.fields)}`),
      ROOM: (s) => secBody(s, `${s.match ? `<div class="small mb8">${I('home')} ${s.matchBy === 'chọn' ? 'Đã chọn' : 'Khớp theo <b>' + esc(s.matchBy) + '</b>'}: phòng <b>${esc(s.match.code)}</b> ${Q.chip('room', s.match.status)} · ${esc(s.match.type || '')} · ${s.match.area || ''} m² · giá niêm yết ${F.vnd(s.match.price)} ${U.link('#/rooms/' + s.match.id, 'Xem phòng')}</div>` : `<div class="small mb8 red">${I('alert-circle')} Không tìm thấy phòng "${esc(s.code)}" trong tòa – chọn phòng có sẵn.</div>`}${s.warnings.map(w => `<div class="note-box warn sm">${I('alert-triangle')}<div>${esc(w)}</div></div>`).join('')}${U.field({ label: 'Phòng hệ thống (theo tòa đã liên kết)', input: U.select({ name: 'cand_ROOM', value: s.candidateId || '', placeholder: 'Chọn phòng…', options: s.candidates.map(r => [r.id, r.code + ' · ' + Q.label('room', r.status) + ' · ' + F.vnd(r.price)]), attrs: { 'data-on': 'cand', 'data-g': 'ROOM' } }) })}${fieldTable(s.fields)}`),
      CONTRACT: (s) => secBody(s, `${s.duplicates.length ? U.note('danger', 'Trùng hợp đồng (AC-1)', s.duplicates.map(d => 'HĐ ' + U.link('#/contracts/' + d.contract.id, esc(d.contract.code)) + ' – ' + esc(d.by)).join('<br>')) : ''}<div class="xs muted mb8">HĐ mới ở trạng thái <b>Dự thảo</b>; giá niêm yết phòng ${F.vnd(s.listPrice)}; kỳ thuê ${s.data.months || '?'} tháng. OCR không tự kích hoạt (AC-11).</div>${fieldTable(s.fields)}`),
      OCCUPANT: (s) => secBody(s, `<div class="small mb8">HĐ ghi <b>${s.count || '?'}</b> người ở (tối đa ${s.max || '?'}). ${s.note ? '<span class="muted">' + esc(s.note) + '</span>' : ''}</div><table class="tbl compact mb8"><thead><tr><th>Họ tên</th><th>SĐT</th><th>CCCD</th><th>Ngày sinh</th><th>Hồ sơ khách</th><th></th></tr></thead><tbody>${s.rows.map((r, i) => `<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.phone || '')}</td><td>${esc(r.idNumber || '')}</td><td>${esc(r.dob || '')}</td><td class="xs">${r.match ? U.chip('Link ' + r.match.code, 'blue') + ' ' + esc(r.match.name) : (String(r.phone || '').replace(/\D/g, '').length === 10 ? U.chip('Create hồ sơ mới', 'green') : U.chip('Chưa liên kết (thiếu SĐT)', 'gray'))}</td><td class="tr">${U.iconBtn('trash', 'occ-rm', 'Xóa', { 'data-i': i })}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Chưa có người ở cùng</td></tr>'}</tbody></table>${U.btn({ label: 'Thêm người ở cùng', icon: 'user-plus', size: 'btn-sm', cls: 'btn-outline', act: 'occ-add' })}<span class="xs muted" style="margin-left:8px">Người ở cùng = hồ sơ khách riêng liên kết HĐ (§4.8)</span>`),
      CONTRACT_SERVICE: (s) => secBody(s, `${s.items.length ? `<table class="tbl compact mb8"><thead><tr><th>Dịch vụ (HĐ)</th><th>Danh mục</th><th class="num">Giá HĐ</th><th class="num">Giá tòa</th><th class="num">SL</th><th>Snapshot</th><th>Tin cậy</th></tr></thead><tbody>${s.items.map(i => `<tr class="${i.conflict && !i.resolved ? 'row-warn' : ''}"><td><b>${esc(i.label)}</b></td><td class="xs">${i.serviceId ? esc(i.serviceName) + ' <span class="muted">/' + esc(i.unit) + '</span>' : '<span class="amber">Không có trong danh mục</span>'}</td><td class="num"><b>${vnd(i.ocrPrice)}</b></td><td class="num">${i.serviceId ? vnd(i.buildingPrice) + `<div class="xs muted">${i.priceScope === 'BUILDING' ? 'giá riêng tòa' : 'giá mặc định'}</div>` : '–'}</td><td class="num">${i.isVehicle ? `<input class="inp sm" type="number" style="width:56px" value="${i.qty}" data-on="svc-qty" data-k="${i.key}">` : (i.method === 'meter' ? '<span class="xs muted">theo chỉ số</span>' : 1)}</td><td class="xs">${i.mode === 'ignore' ? U.chip('Ignore', 'gray') + ' <a class="link" data-act="svc-reset" data-k="' + i.key + '">dùng</a>' : i.conflict ? (i.resolved ? U.chip(i.mode === 'updateBuilding' ? 'HĐ + giá tòa từ ' + F.date(i.effectiveFrom) : 'Chỉ HĐ này', i.mode === 'updateBuilding' ? 'amber' : 'green') : '<span class="red">Chọn cách xử lý ↓</span>') : U.chip('= giá tòa', 'green') + ' <a class="link" data-act="svc-ignore" data-k="' + i.key + '">bỏ</a>'}</td><td>${confChip({ decision: 'accept', confidence: i.confidence })}</td></tr>${i.conflict ? `<tr class="${!i.resolved ? 'row-warn' : ''}"><td colspan="7" class="xs" style="padding-top:2px"><span class="row wrap gap12" style="align-items:center"><span class="muted">${I('alert-triangle')} Giá HĐ ${vnd(i.ocrPrice)} ≠ giá tòa ${vnd(i.buildingPrice)} →</span>${[['snapshot', 'Chỉ áp dụng cho HĐ này'], ['updateBuilding', 'Cập nhật giá tòa từ ngày…'], ['ignore', 'Ignore']].map(([m, l]) => `<label class="chk"><input type="radio" name="svm_${i.key}" value="${m}" ${i.mode === m && i.resolved ? 'checked' : ''} data-on="svc-mode" data-k="${i.key}"> ${l}</label>`).join('')}${i.mode === 'updateBuilding' && i.resolved ? U.date({ name: 'sveff_' + i.key, value: i.effectiveFrom, cls: 'sm', attrs: { 'data-on': 'svc-eff', 'data-k': i.key, style: 'width:140px' } }) : ''}</span></td></tr>` : ''}`).join('')}</tbody></table>` : '<div class="muted small mb8">Không đọc được đơn giá dịch vụ.</div>'}<div class="xs muted">Giá trên HĐ luôn lưu thành <b>Contract Service Price Snapshot</b>; "Cập nhật giá tòa" tạo Service Price record mới có ngày hiệu lực, không ghi đè lịch sử (§12.8.10). Điện/nước tính theo chỉ số công tơ; xe dùng số lượng từ nhóm Xe.</div>${fieldTable(s.fields)}`),
      DEPOSIT: (s) => secBody(s, `<div class="small mb8">Ghi <b>Deposit Ledger</b> loại <b>RECEIVABLE ${vnd(s.amount)}</b> ngày ký/bắt đầu; thu cọc thực tế ghi RECEIVED khi có phiếu thu (§10.11).</div>${s.warnings.map(w => `<div class="note-box warn sm">${I('alert-triangle')}<div>${esc(w)}</div></div>`).join('')}${fieldTable(s.fields)}`),
      VEHICLE: (s) => secBody(s, `<div class="small mb8">HĐ ghi <b>${s.count}</b> xe. Mỗi dòng → Contract Vehicle; phí gửi/sạc xe lấy từ nhóm Dịch vụ & Giá.</div><table class="tbl compact mb8"><thead><tr><th>#</th><th>Loại</th><th>Biển số</th><th></th></tr></thead><tbody>${s.rows.map((r, i) => `<tr><td>${i + 1}</td><td>${U.select({ name: 'vt_' + i, value: r.type || 'Xe máy', options: ['Xe máy', 'Xe đạp điện', 'Xe điện (ô tô)', 'Ô tô', 'Xe đạp'], cls: 'sm', attrs: { 'data-on': 'veh', 'data-i': i, 'data-f': 'type' } })}</td><td>${U.input({ name: 'vp_' + i, value: r.plate || '', placeholder: 'Biển số', cls: 'sm', attrs: { 'data-on': 'veh', 'data-i': i, 'data-f': 'plate' } })}</td><td class="tr">${U.iconBtn('trash', 'veh-rm', 'Xóa', { 'data-i': i })}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Không có xe</td></tr>'}</tbody></table>${U.btn({ label: 'Thêm xe', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'veh-add' })}${fieldTable(s.fields)}`),
      METER_READING: (s) => secBody(s, `<div class="small mb8">Chỉ số tại thời điểm bàn giao lưu <b>reading_type = OPENING</b> ngày ${F.date(s.date)}; kỳ chốt tiếp theo dùng làm chỉ số cũ (§12.8.11).</div><table class="tbl compact mb8"><thead><tr><th>Loại</th><th class="num">Chỉ số OCR</th><th>Công tơ</th><th>Chỉ số gần nhất của phòng</th><th>Trang</th></tr></thead><tbody>${s.rows.map(r => `<tr><td><b>${esc(r.label)}</b> <span class="muted xs">${esc(r.unit)}</span></td><td class="num"><b>${r.value}</b></td><td class="xs">${r.meter ? U.chip('Link ' + r.meter.code, 'blue') : U.chip('Create công tơ mới', 'green')}</td><td class="xs">${r.last ? esc(String(r.last.curr)) + ' (' + esc(r.last.period || r.last.readingDate || '') + ')' : '<span class="muted">–</span>'}${r.warn ? '<div class="xs amber">' + esc(r.warn) + '</div>' : ''}${r.exists ? '<div class="xs red">Đã có OPENING cùng ngày</div>' : ''}</td><td class="xs">Tr.${r.page || 2}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Không đọc được chỉ số</td></tr>'}</tbody></table>${fieldTable(s.fields)}`),
      HANDOVER_ASSET: (s) => secBody(s, `<div class="small mb8">${s.lines.length} dòng → <b>Handover Asset Line</b> của hợp đồng (§12.8.12); đối chiếu khi trả phòng.</div><div class="grid grid-2 gap12">${[['furniture', 'Nội thất'], ['device', 'Thiết bị']].map(([k, l]) => `<table class="tbl compact"><thead><tr><th>${l}</th><th class="num">SL</th><th>Tình trạng</th></tr></thead><tbody>${s.lines.filter(a => a.kind === k).map(a => `<tr><td>${esc(a.name)}${a.desc ? ' <span class="muted xs">' + esc(a.desc) + '</span>' : ''}</td><td class="num">${esc(a.qty || '1')}</td><td class="xs">${esc(a.condition || 'Bình thường')}</td></tr>`).join('') || '<tr><td colspan="3" class="muted tc">–</td></tr>'}</tbody></table>`).join('')}</div>`),
      PAYMENT_TERM: (s) => secBody(s, `<div class="small mb8">Lưu <b>Contract Payment Terms</b> – chỉ là cấu hình/tham chiếu cho billing & nhắc nợ, không tự thành Payment; phạt chậm trả chỉ phát sinh khi rule được duyệt (§12.8.13).</div>${U.kv([['Ngày gửi thông báo', s.data.notifyDay || '–'], ['Thanh toán', (s.data.payFrom || '–') + ' → ' + (s.data.payTo || '–') + ' của kỳ trước'], ['Ngân hàng / chủ TK / số TK', esc([s.data.bankName, s.data.bankAccountName, s.data.bankAccountNo].filter(Boolean).join(' · ') || '–')], ['Nội dung CK', esc(s.data.transferTemplate || '–')], ['Phạt chậm trả', s.data.lateFeePerDay ? F.vnd(s.data.lateFeePerDay) + 'đ/ngày, grace ' + s.data.graceDays + ' ngày' : '–']], 'one')}${fieldTable(s.fields)}`),
      RENEWAL_CLAUSE: (s) => secBody(s, `<div class="small mb8">Lưu <b>renewal_type = ${esc(s.data.renewalType)}</b>, ${s.data.renewalMonths || '–'} tháng, báo trước ${s.data.noticeDays || '–'} ngày → chỉ tạo cảnh báo/Work Queue HĐ sắp hết; <b>không tự gia hạn</b> (AC-12, §12.8.14).</div>${fieldTable(s.fields)}`),
      DOCUMENT: (s) => secBody(s, U.kv([['File', esc(s.fileName) + ' · ' + esc(s.size || '')], ['Loại', Q.chip('docType', s.docType)], ['Trang', s.pages], ['Hash', '<span class="mono xs">' + esc(s.hash) + '</span>'], ['Engine', esc(s.engine)]], 'one') + '<div class="xs muted mt8">Create = gắn file vào Hợp đồng › Tài liệu (docType contract, version 1, nguồn OCR).</div>'),
    };
    const sectionsHtml = S.map(s => `<details class="card ocr-sec" data-sec="${s.key}" ${isOpen(s) ? 'open' : ''}>${secHead(s)}${(render[s.key] || (x => secBody(x, fieldTable(x.fields))))(s)}</details>`).join('');
    const nAction = S.filter(s => (s.needsResolve && !s.resolved) || (s.unresolved && s.unresolved.length)).length; const got = fields.length - pending.length;
    const canCommit = j.status === 'VALIDATED';
    root.innerHTML = head + wiz + `<div class="ocr-mobile-banner">${U.note('info', 'Review OCR trên máy tính', 'Màn hình nhỏ chỉ xem tóm tắt/tài liệu; mở trên desktop để quyết định từng nhóm entity.')}</div>
      ${j.status === 'COMMIT_FAILED' ? U.note('danger', 'Commit lỗi – đã rollback toàn bộ (AC-9)', esc(j.error || '') + '<div class="xs mt4">Không có entity nào được ghi. Sửa dữ liệu (nếu cần) rồi <strong>Thử lại</strong>.</div>') : ''}
      <div class="two-col wide ocr-review-layout" style="grid-template-columns:minmax(0,1fr) minmax(0,1.25fr)">
      <div>${U.card({ title: `${I('file-text')} ${esc(j.fileName)}`, sub: `${esc(j.size || '')} · ${j.pages || npages} trang · bấm vào vùng đánh dấu để nhảy tới trường`, actions: U.btn({ label: 'Tải file khác', icon: 'upload', size: 'btn-sm', cls: 'btn-outline', act: 'jobs' }), body: U.docPreview({ pages: O.pages(j), page: Math.min(page, npages), zoom, fileName: j.fileName, stacked: true }) })}</div>
      <div class="side-stack">
        ${U.card({ body: `<div class="ocr-review-summary"><div><b>${got}/${fields.length}</b><span>trường đã xác nhận · ${pending.length} cần kiểm tra · ${nAction} nhóm cần xử lý xung đột</span><div class="progress"><i style="width:${F.pct(got, fields.length)}%"></i></div></div><div class="ocr-review-modes">${U.btn({ label: 'Mở tất cả', size: 'btn-sm', cls: 'btn-ghost', act: 'open-all' })}${U.btn({ label: 'Chỉ nhóm cần xử lý', size: 'btn-sm', cls: 'btn-ghost', act: 'open-need' })}${U.btn({ label: 'Xem payload', icon: 'code', size: 'btn-sm', cls: 'btn-outline', act: 'payload' })}${U.btn({ label: 'Validate', icon: 'shield-check', size: 'btn-sm', cls: canCommit ? 'btn-outline' : 'btn-primary', act: 'validate', attrs: { 'data-guide': 'ocr-validate' } })}</div></div>${lastV ? `<div class="mt8 ${lastV.errors.length ? 'red' : 'green'} small">${lastV.errors.length ? I('alert-circle') + ' Validate ' + F.datetime(lastV.at) + ': <b>' + lastV.errors.length + ' lỗi</b>, ' + lastV.warnings.length + ' cảnh báo – xem trong từng nhóm' : I('check-circle') + ' Validate đạt ' + F.datetime(lastV.at) + (lastV.warnings.length ? ' · ' + lastV.warnings.length + ' cảnh báo' : '') + ' → sẵn sàng commit'}</div>` : ''}` })}
        <div class="ocr-secs">${sectionsHtml}</div>
        <div class="wz-foot">${U.btn({ label: 'Chạy lại trích xuất', icon: 'refresh-cw', cls: 'btn-outline', act: 'rerun' })}<div class="row gap8">${U.btn({ label: 'Nhập tay', icon: 'pencil', cls: 'btn-ghost', act: 'manual' })}${j.status === 'COMMIT_FAILED' ? U.btn({ label: 'Thử lại commit', icon: 'refresh-cw', cls: 'btn-primary', act: 'retry-commit' }) : U.btn({ label: 'Xác nhận tạo hợp đồng', icon: 'check-circle', cls: 'btn-primary', act: 'commit', disabled: !canCommit, title: canCommit ? '' : 'Validate đạt trước khi commit', attrs: { 'data-guide': 'ocr-commit' } })}</div></div>
      </div></div>`;
    /* highlight cặp field ↔ vùng tài liệu */
    const pair = (k) => { root.querySelectorAll('.ocr-pair-active').forEach(x => x.classList.remove('ocr-pair-active')); const fld = root.querySelector(`[data-ocr-field="${k}"]`), mark = root.querySelector(`[data-ocr-mark="${k}"]`); fld && fld.classList.add('ocr-pair-active'); mark && mark.classList.add('ocr-pair-active'); return { fld, mark }; };
    root.addEventListener('focusin', (e) => { const el = e.target.closest('[data-k]'); if (el) pair(el.dataset.k); });
    root.addEventListener('click', (e) => { const mark = e.target.closest('[data-ocr-mark]'); if (!mark) return; const k = mark.dataset.ocrMark; const sec = root.querySelector(`details[data-sec="${(Q.ocrField(j, k) || {}).entityGroup}"]`); if (sec) sec.open = true; const pr = pair(k); if (pr.fld) { pr.fld.scrollIntoView({ behavior: 'smooth', block: 'center' }); const inp = pr.fld.querySelector('input,select,textarea'); inp && inp.focus(); } });
    const refresh = () => { const open = [...root.querySelectorAll('details.ocr-sec[open]')].map(d => d.dataset.sec).join(','); TH.router.replaceQuery({ id: j.id, page, zoom, open }); TH.router.refresh(); };
    const rows = (g) => (Onb.section(j, g) || {}).rows || [];
    const tryDo = (fn, okMsg) => { try { fn(); if (okMsg) U.toast('ok', okMsg); refresh(); } catch (e) { U.toast('err', 'Không thực hiện được', e.message); } };
    U.onChange(root, {
      field: (el) => { const k = el.dataset.k; const d = P.field(k) || {}; let v = el.value; if (d.type === 'date') v = v ? F.date(v) : ''; if (['money', 'number'].includes(d.type)) v = v === '' ? '' : String(F.num(v)); tryDo(() => { X.ocrSetField(j.id, k, v); if (k === 'start' || k === 'end') { const s = F.fromVN(Q.ocrValue(j, 'start')), en = F.fromVN(Q.ocrValue(j, 'end')); if (s && en && en > s) X.ocrSetField(j.id, 'months', String(F.monthsDiff(s, en))); } }); },
      cand: (el) => tryDo(() => X.ocrDecide(j.id, el.dataset.g, { candidateId: el.value || null, decision: (Onb.section(j, el.dataset.g).decision === 'create' && el.value) ? 'link' : Onb.section(j, el.dataset.g).decision })),
      'svc-mode': (el) => tryDo(() => X.ocrServiceMode(j.id, el.dataset.k, { mode: el.value })), 'svc-eff': (el) => tryDo(() => X.ocrServiceMode(j.id, el.dataset.k, { effectiveFrom: el.value })), 'svc-qty': (el) => tryDo(() => X.ocrServiceMode(j.id, el.dataset.k, { qty: el.value })),
      veh: (el) => { const r = rows('VEHICLE'); const i = Number(el.dataset.i); if (!r[i]) return; r[i][el.dataset.f] = el.value; try { X.ocrSetRows(j.id, 'VEHICLE', r); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
    });
    U.bind(root, {
      jobs: () => TH.go('#/contracts/ocr'), manual: () => TH.go('#/contracts/new'),
      accept: (el) => tryDo(() => X.ocrConfirmField(j.id, el.dataset.k)), reject: (el) => tryDo(() => X.ocrRejectField(j.id, el.dataset.k)), 'accept-group': (el) => tryDo(() => X.ocrAcceptGroup(j.id, el.dataset.g)),
      page: (el) => { const f = Q.ocrField(j, el.dataset.k); const pg = root.querySelector(`.dp-page[data-dp-n="${f ? f.page : 1}"]`); pg && pg.scrollIntoView({ behavior: 'smooth', block: 'start' }); const pr = pair(el.dataset.k); pr.mark && pr.mark.scrollIntoView({ behavior: 'smooth', block: 'center' }); },
      dec: (el) => { const g = el.dataset.g, d = el.dataset.d; const s = Onb.section(j, g); const patch = { decision: d }; if (['link', 'update'].includes(d) && !s.candidateId && s.candidates && s.candidates.length === 1) patch.candidateId = s.candidates[0].id; if (['link', 'update'].includes(d) && !patch.candidateId && !s.candidateId) { U.toast('warn', 'Chọn bản ghi hệ thống', 'Chọn ' + s.label.toLowerCase() + ' trong danh sách rồi bấm ' + DEC[d][0]); const det = root.querySelector(`details[data-sec="${g}"]`); det && (det.open = true); return; } tryDo(() => X.ocrDecide(j.id, g, patch)); },
      'svc-ignore': (el) => tryDo(() => X.ocrServiceMode(j.id, el.dataset.k, { mode: 'ignore' })), 'svc-reset': (el) => tryDo(() => X.ocrServiceMode(j.id, el.dataset.k, { mode: 'snapshot' })),
      'veh-add': () => tryDo(() => X.ocrSetRows(j.id, 'VEHICLE', rows('VEHICLE').concat([{ type: 'Xe máy', plate: '' }]))), 'veh-rm': (el) => tryDo(() => X.ocrSetRows(j.id, 'VEHICLE', rows('VEHICLE').filter((_, i) => i !== Number(el.dataset.i)))),
      'occ-rm': (el) => tryDo(() => X.ocrSetRows(j.id, 'OCCUPANT', rows('OCCUPANT').filter((_, i) => i !== Number(el.dataset.i)).map(r => ({ name: r.name, phone: r.phone, idNumber: r.idNumber, dob: r.dob, relation: r.relation })))),
      'occ-add': () => { const m = U.modal({ title: 'Thêm người ở cùng', sub: 'Hồ sơ khách riêng liên kết hợp đồng (§4.8) – hệ thống tự match CCCD → SĐT → tên+ngày sinh', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name' }), cls: 'span2' })}${U.field({ label: 'SĐT', input: U.input({ name: 'phone', placeholder: '10 số để tạo hồ sơ' }) })}${U.field({ label: 'CCCD', input: U.input({ name: 'idNumber' }) })}${U.field({ label: 'Ngày sinh', input: U.date({ name: 'dob' }) })}${U.field({ label: 'Quan hệ', input: U.select({ name: 'relation', value: 'Bạn cùng phòng', options: ['Vợ/Chồng', 'Bạn cùng phòng', 'Con', 'Anh/Chị/Em', 'Khác'] }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Thêm', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); if (!d.name) return U.toast('warn', 'Nhập họ tên'); m.close(); tryDo(() => X.ocrSetRows(j.id, 'OCCUPANT', rows('OCCUPANT').map(r => ({ name: r.name, phone: r.phone, idNumber: r.idNumber, dob: r.dob, relation: r.relation })).concat([{ name: d.name, phone: d.phone, idNumber: d.idNumber, dob: d.dob ? F.date(d.dob) : '', relation: d.relation }]))); } }); },
      'open-all': () => { root.querySelectorAll('details.ocr-sec').forEach(d => d.open = true); }, 'open-need': () => { root.querySelectorAll('details.ocr-sec').forEach(d => { const s = S.find(x => x.key === d.dataset.sec); d.open = !!(s && (s.pending || (s.needsResolve && !s.resolved) || (s.unresolved && s.unresolved.length) || errsOf(s.key).length)); }); },
      payload: () => { const pl = X.ocrPayload(j.id); const m = U.modal({ title: 'Payload commit (xem trước)', sub: 'Dữ liệu sẽ ghi trong 1 transaction – §12.8.9', wide: true, body: `<pre class="code" style="max-height:60vh;overflow:auto;font-size:12px">${esc(JSON.stringify(pl, null, 2))}</pre>`, footer: U.btn({ label: 'Đóng', act: 'c' }) + U.btn({ label: 'Tải JSON', icon: 'download', cls: 'btn-outline', act: 'dl' }) }); U.bind(m.el, { c: () => m.close(), dl: () => F.download('ocr-payload-' + j.code + '.json', JSON.stringify(pl, null, 2)) }); },
      validate: () => { try { const v = X.ocrValidate(j.id); j.lastValidation = { at: F.nowISO(), errors: v.errors, warnings: v.warnings }; St.save(); if (v.ok) U.toast('ok', 'Validate đạt', v.warnings.length + ' cảnh báo – có thể Xác nhận tạo hợp đồng'); else U.toast('warn', 'Validate ' + v.errors.length + ' lỗi', v.errors.slice(0, 3).map(e => e.msg).join(' · ')); const open = [...new Set(v.errors.map(e => e.group))].join(','); TH.router.replaceQuery({ id: j.id, page, zoom, open: open || undefined }); TH.router.refresh(); } catch (e) { U.toast('err', 'Không validate được', e.message); } },
      rerun: async () => { if (!(await U.confirm({ title: 'Chạy lại trích xuất?', text: 'Mọi chỉnh sửa và quyết định review sẽ được đặt lại theo kết quả OCR mới.' }))) return; tryDo(() => X.ocrRerun(j.id)); },
      commit: () => { const pl = X.ocrPayload(j.id); const m = U.modal({ title: 'Xác nhận tạo hợp đồng', sub: 'Commit 1 transaction: Customer → Building → Room → Contract (+ người thuê, dịch vụ snapshot, cọc, xe, chỉ số OPENING, tài sản bàn giao, điều khoản, tài liệu). Lỗi bất kỳ → rollback toàn bộ.', body: `${U.kv([['Khách hàng', pl.customer.action + (pl.customer.code ? ' · ' + pl.customer.code : '')], ['Tòa / Phòng', 'LINK ' + esc(pl.building.name || '') + ' · ' + esc(pl.room.code || '')], ['Hợp đồng', 'CREATE Dự thảo · ' + F.date(pl.contract.start) + ' → ' + F.date(pl.contract.end) + ' · ' + F.vnd(pl.contract.price) + 'đ/tháng'], ['Người thuê', pl.contractTenants.length + ' (1 đứng tên)'], ['Dịch vụ', pl.contractServices.length + ' dòng snapshot' + (pl.servicePriceUpdates.length ? ' · cập nhật giá tòa ' + pl.servicePriceUpdates.map(x => x.service).join(', ') : '')], ['Cọc', pl.depositLedger.length ? 'RECEIVABLE ' + F.vnd(pl.depositLedger[0].amount) : 'Ignore'], ['Xe / Chỉ số / Tài sản', pl.vehicles.length + ' xe · ' + pl.openingMeterReadings.length + ' chỉ số OPENING · ' + pl.handoverAssets.length + ' tài sản'], ['Điều khoản', (pl.paymentTerms ? 'Thanh toán' : '') + (pl.renewalClause ? ' · Gia hạn/báo trước' : '') || 'Ignore'], ['Tài liệu', pl.document ? pl.document.fileName : 'Ignore']], 'one')}<label class="chk mt12 xs"><input type="checkbox" name="simFail"> Mô phỏng lỗi kỹ thuật khi ghi để xem rollback (AC-9)</label>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Commit', icon: 'check-circle', cls: 'btn-primary', act: 's', attrs: { 'data-guide': 'ocr-commit-confirm' } }) }); U.bind(m.el, { c: () => m.close(), s: () => { const sim = !!m.data().simFail; m.close(); try { const r = X.ocrCommit(j.id, { simulateFail: sim }); U.toast('ok', 'Đã ghi dữ liệu', r.entities.length + ' entity – HĐ ' + (Q.contract(r.contractId) || {}).code); TH.router.replaceQuery({ id: j.id }); TH.router.refresh(); } catch (e) { U.toast('err', 'Commit lỗi – đã rollback', e.message); TH.router.replaceQuery({ id: j.id }); TH.router.refresh(); } } }); },
      'retry-commit': () => tryDo(() => { X.ocrRetry(j.id); }, 'Job trở lại VALIDATED – bấm Xác nhận tạo hợp đồng'),
      'dp-zoom-in': () => { TH.router.replaceQuery({ id: j.id, page, zoom: Math.min(160, zoom + 10) }); TH.router.refresh(); }, 'dp-zoom-out': () => { TH.router.replaceQuery({ id: j.id, page, zoom: Math.max(60, zoom - 10) }); TH.router.refresh(); }, 'dp-hand': () => U.toast('info', 'Chế độ kéo trang', 'Cuộn/kéo trong khung xem'), 'dp-dl': () => { F.download(j.fileName, j.sample ? O.sampleText() : (j.text || '')); },
    });
    const pageSel = root.querySelector('[data-dp-page]'); if (pageSel) pageSel.addEventListener('change', (e) => { const n = Math.max(1, Math.min(npages, Number(e.target.value) || 1)); const el = root.querySelector(`.dp-page[data-dp-n="${n}"]`); if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' }); TH.router.replaceQuery({ id: j.id, page: n, zoom }); });
    if (q.focus) setTimeout(() => { const pr = pair(q.focus); pr.fld && pr.fld.scrollIntoView({ block: 'center' }); }, 50);
  }, { menu: 'ocr', permission: 'ocr.use', scopeKey: 'ocr', noAutoRefresh: 'timer' });
})(window.TH);
