/* Phase 2 – Trích xuất hợp đồng (OCR): Tải file → Trích xuất → Review → Tạo hợp đồng (FR-CUS-02, BR-03) */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const O = {};
  /* File mẫu: chọn một phòng Sẵn sàng của tòa Sunrise; 5 trường cố tình sai (tên, mã phòng, cọc, ngày kết thúc, SĐT) */
  O.sampleSpec = () => {
    const b = St.one('buildings', x => x.name === 'Tòa Sunrise') || St.where('buildings', x => !x.stub)[0]; const room = St.where('rooms', r => r.status === 'ready' && r.buildingId === b.id).sort((a, c) => a.code.localeCompare(c.code))[0] || St.where('rooms', r => r.status === 'ready')[0] || St.all('rooms')[0];
    const price = room.price, deposit = price * 2;
    return { tenantName: 'Nguyễn Thị Hương', tenantNameWrong: 'NGUYEN THI HUONG', idNumber: '023456789012', phone: '0938 765 432', phoneWrong: '0938 765 43', address: '456 Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh', email: 'huongnt@gmail.com', buildingName: b.name, buildingAddress: b.address, roomCode: room.code, roomCodeWrong: room.code.replace('.', ''), roomType: room.type, area: room.area, start: '01/11/2024', end: '31/10/2025', endWrong: '31/10/2026', price, deposit, depositWrong: F.vnd(deposit).replace(/,(\d{3})$/, ',$15'), room };
  };
  O.sampleText = () => { const s = O.sampleSpec(); return ['CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM', 'Độc lập - Tự do - Hạnh phúc', '', 'HỢP ĐỒNG THUÊ NHÀ', 'Số: HD-2024-001', '', 'Hôm nay, ngày 01 tháng 11 năm 2024, tại Thành phố Hồ Chí Minh, chúng tôi gồm:', 'BÊN CHO THUÊ (BÊN A): Trần Văn Hải – CMND/CCCD 012345678901 – 123 Nguyễn Văn Cừ, Quận 1 – 0901 234 567', 'BÊN THUÊ (BÊN B): ' + s.tenantName + ' – CMND/CCCD ' + s.idNumber + ' – ' + s.address + ' – ' + s.phone, '', 'Điều 1. Tài sản thuê: căn hộ ' + s.roomCode + ' tại ' + s.buildingName + ', ' + s.buildingAddress + '. Diện tích: ' + s.area + ' m².', 'Điều 2. Thời hạn thuê: 12 tháng. Từ ngày ' + s.start + ' đến ngày ' + s.end + '.', 'Điều 3. Giá thuê và thanh toán: Giá thuê ' + F.vnd(s.price) + ' đồng/tháng. Tiền cọc: ' + F.vnd(s.deposit) + ' đồng. Thanh toán: chuyển khoản hàng tháng vào ngày 05.', 'Điều 4. Dịch vụ: Internet, giữ xe máy.', '', '(File mẫu cho trích xuất OCR – demo TimoHouse Phase 2)'].join('\n'); };
  O.pages = (o) => { const s = O.sampleSpec(); const v = (k) => { const f = (o.fields || []).find(x => x.key === k); return f ? f : { value: '', confirmed: true }; }; const mk = (k, text) => { const f = v(k); return `<mark class="${f.confirmed ? 'ok' : 'check'}" title="${f.confirmed ? 'Đã nhận' : 'Cần kiểm tra – độ tin cậy ' + Math.round((f.confidence || 0) * 100) + '%'}">${esc(text != null ? text : f.value)}</mark>`; };
    const p1 = `<h3>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</h3><p class="c"><b>Độc lập - Tự do - Hạnh phúc</b></p><h4>${mk('contractNo', 'HỢP ĐỒNG THUÊ NHÀ')}</h4><p class="c">Số: ${mk('contractNo')}</p><p>Hôm nay, ngày 01 tháng 11 năm 2024, tại Thành phố Hồ Chí Minh, chúng tôi gồm:</p><p><b>BÊN CHO THUÊ (BÊN A):</b></p><p>Họ và tên: ${mk('landlord')}<br>CMND/CCCD: 012345678901<br>Địa chỉ: 123 Nguyễn Văn Cừ, Quận 1, TP. Hồ Chí Minh<br>Số điện thoại: <mark class="ok">0901 234 567</mark></p><p><b>BÊN THUÊ (BÊN B):</b></p><p>Họ và tên: ${mk('tenantName', s.tenantName)}<br>CMND/CCCD: ${mk('idNumber')}<br>Địa chỉ: ${mk('address')}<br>Số điện thoại: ${mk('phone', s.phone)}</p><p>Hai bên cùng thỏa thuận ký kết hợp đồng thuê nhà với các điều khoản sau:</p><p><b>Điều 1. Tài sản thuê</b><br>Bên A đồng ý cho Bên B thuê ${mk('roomCode', 'căn hộ ' + s.roomCode)} tại Tòa nhà ${mk('buildingName')}, địa chỉ ${esc(s.buildingAddress)}.<br>Diện tích: ${mk('area', s.area + ' m²')}.</p><p><b>Điều 2. Thời hạn thuê</b><br>Thời hạn thuê: ${mk('months')}<br>Từ ngày ${mk('start')} đến ngày ${mk('end', s.end)}.</p><p><b>Điều 3. Giá thuê và thanh toán</b><br>Giá thuê: ${mk('price', F.vnd(s.price) + ' đồng/tháng')} (Bằng chữ: ${esc(F.words(s.price))}).<br>Tiền cọc: ${mk('deposit', F.vnd(s.deposit) + ' đồng')} (Bằng chữ: ${esc(F.words(s.deposit))}).<br>Thanh toán: ${mk('cycle', 'Chuyển khoản hàng tháng')} vào ngày ${mk('payDay')}.</p><p>…</p>`;
    return [p1, '<p class="c muted">Trang 2 – Điều 4. Dịch vụ đi kèm: ' + ['Internet', 'giữ xe máy'].join(', ') + '. Điều 5. Quyền và nghĩa vụ các bên…</p>', '<p class="c muted">Trang 3 – Điều 6. Điều khoản chấm dứt…</p>', '<p class="c muted">Trang 4 – Điều 7. Cam kết chung…</p>', '<p class="c muted">Trang 5 – Biên bản bàn giao tài sản…</p>', '<p class="c muted">Trang 6 – Chữ ký các bên.</p>']; };
  TH.ocr = O;
  const GROUPS = [['tenant', 'Khách thuê', 'user'], ['room', 'Phòng', 'home'], ['term', 'Thời hạn', 'calendar'], ['money', 'Giá thuê & cọc', 'coins'], ['services', 'Dịch vụ', 'sliders']];
  TH.router.register('/contracts/ocr', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Hợp đồng', href: '#/contracts' }, { label: 'Review trích xuất' }]);
    const o = q.id ? St.get('ocrExtractions', q.id) : null; const step = !o ? 1 : o.status === 'uploaded' || o.status === 'extracting' ? 2 : o.status === 'review' ? 3 : 4;
    const STEPS = [{ title: 'Tải file', sub: 'Tải lên hợp đồng' }, { title: 'Trích xuất', sub: 'Hệ thống nhận diện thông tin' }, { title: 'Review', sub: 'Kiểm tra và chỉnh sửa' }, { title: 'Hoàn tất', sub: 'Tạo hợp đồng' }];
    const head = U.pageHead({ title: step === 3 ? 'Review trích xuất hợp đồng' : 'Trích xuất hợp đồng (OCR)', phase: 2, sub: step === 3 ? 'Kiểm tra và chỉnh sửa thông tin trước khi tạo hợp đồng' : 'Tải file hợp đồng đã ký (PDF/JPG/PNG ≤ 20MB – FR-DOC-01), hệ thống trích xuất trường, review confidence rồi tạo hợp đồng (BR-03).', acts: [U.btn({ label: 'Nhập tay (dự phòng)', icon: 'pencil', cls: 'btn-outline', act: 'manual' })] });
    if (step === 1) {
      const hist = St.all('ocrExtractions').sort((a, b) => F.cmp(b.createdAt, a.createdAt)).slice(0, 5);
      root.innerHTML = `${head}${U.wizard(STEPS, 0)}<div class="two-col">${U.card({ title: 'Bước 1 – Tải file hợp đồng', icon: 'upload', body: `${U.dropzone({ name: 'ocr', hint: 'PDF, JPG, PNG · tối đa 20MB (FR-DOC-01)', multiple: false, accept: '.pdf,.jpg,.jpeg,.png,.txt' })}<div class="row mt12 gap12">${U.btn({ label: 'Dùng file mẫu (Hop_dong_thue_nha.pdf – 5 trường cố tình sai)', icon: 'file-check', cls: 'btn-outline', act: 'sample', attrs: { 'data-guide': 'ocr-sample' } })}${U.btn({ label: 'Tải file mẫu (.txt)', icon: 'download', cls: 'btn-ghost', act: 'dl' })}</div>` })}<aside class="side-stack">${U.card({ title: 'Cách hoạt động', icon: 'info', body: `<div class="steps">${[['Tải file', 'PDF/ảnh hợp đồng đã ký.'], ['Trích xuất', 'Nhận diện ~29 trường: khách, phòng, thời hạn, giá, cọc, dịch vụ.'], ['Review', 'Trường confidence < 80% gắn chip "Cần kiểm tra"; trường ảnh hưởng tiền bắt buộc xác nhận (BR-03).'], ['Tạo hợp đồng', 'Prefill form HĐ P1, nguồn = OCR; nhập tay vẫn là nhánh dự phòng.']].map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` })}${U.card({ title: 'Lần trích xuất gần đây', icon: 'history', bodyCls: 'tight', body: `<table class="tbl compact">${hist.map(x => `<tr><td>${U.link('#/contracts/ocr?id=' + x.id, esc(x.code))}</td><td class="small">${esc(x.fileName)}</td><td>${Q.chip('ocr', x.status)}</td></tr>`).join('') || '<tr><td class="muted tc">Chưa có</td></tr>'}</table>` })}</aside></div>`;
      U.bindDropzones(root, (files) => { const f = files[0]; if (!f) return; try { const x = X.ocrUpload({ fileName: f.name, size: f.size }); TH.go('#/contracts/ocr?id=' + x.id); } catch (e) { U.toast('err', 'Không tải được', e.message); } });
      U.bind(root, { manual: () => TH.go('#/contracts/new'), sample: () => { const x = X.ocrUpload({ fileName: 'Hop_dong_thue_nha.pdf', size: 2.4 * 1024 * 1024, sample: true }); TH.go('#/contracts/ocr?id=' + x.id); }, dl: () => { F.download('mau-hop-dong-ocr.txt', O.sampleText()); U.toast('ok', 'Đã tải file mẫu', 'Nội dung HĐ mẫu để "trích xuất"'); } });
      return;
    }
    if (step === 2) {
      root.innerHTML = `${head}${U.wizard(STEPS, 1)}${U.card({ title: 'Bước 2 – Đang trích xuất ' + esc(o.fileName), icon: 'scan', body: `<div class="tc" style="padding:30px 0"><div class="big" style="width:72px;height:72px;border-radius:20px;background:var(--blue-bg);color:var(--blue);display:grid;place-items:center;margin:0 auto 14px">${I('scan')}</div><b style="font-size:16px">Hệ thống đang nhận diện thông tin…</b><div class="muted small mt4">${esc(o.fileName)} · ${esc(o.size)} · ${o.pages} trang</div><div class="progress mt16" style="max-width:420px;margin:16px auto 0"><i id="ocr-bar" style="width:5%;transition:width .4s"></i></div><div class="xs muted mt8" id="ocr-msg">Đọc trang 1/6…</div></div>` })}`;
      if (o.status === 'uploaded') X.ocrExtract(o.id);
      const bar = root.querySelector('#ocr-bar'), msg = root.querySelector('#ocr-msg'); let k = 0; const msgs = ['Đọc trang 1/6…', 'Nhận diện bên thuê…', 'Nhận diện phòng & thời hạn…', 'Nhận diện giá thuê & cọc…', 'Đối chiếu độ tin cậy…', 'Hoàn tất'];
      const t = setInterval(() => { k++; if (!document.contains(bar)) return clearInterval(t); bar.style.width = Math.min(100, k * 20) + '%'; msg.textContent = msgs[Math.min(k, 5)]; if (k >= 5) { clearInterval(t); X.ocrFinish(o.id); TH.router.refresh(); } }, 400);
      U.bind(root, { manual: () => TH.go('#/contracts/new') });
      return;
    }
    const fields = o.fields || []; const pending = fields.filter(f => !f.confirmed); const got = fields.length - pending.length; const page = Number(q.page || 1); const zoom = Number(q.zoom || 100);
    const rooms = St.where('rooms', r => ['ready', 'held'].includes(r.status)); const fv = (k) => (fields.find(f => f.key === k) || {}).value || '';
    const chip = (f) => f.confirmed ? '' : `<span class="chip amber" title="Độ tin cậy ${Math.round(f.confidence * 100)}%">${I('alert-circle')} Cần kiểm tra</span>`;
    const inp = (k, extra = {}) => { const f = fields.find(x => x.key === k); if (!f) return ''; const isMoney = f.money && ['price', 'deposit'].includes(k); const control = k === 'buildingName' ? U.select({ name: k, value: f.value, options: St.where('buildings', b => !b.stub).map(b => b.name), attrs: { 'data-on': 'field', 'data-k': k } }) : k === 'roomCode' ? U.select({ name: k, value: f.value, placeholder: f.value + ' (không khớp – chọn phòng)', options: rooms.filter(r => Q.building(r.buildingId).name === fv('buildingName') || !fv('buildingName')).map(r => [r.code, r.code + ' – ' + r.type]), attrs: { 'data-on': 'field', 'data-k': k } }) : k === 'roomType' ? U.select({ name: k, value: f.value, options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'], attrs: { 'data-on': 'field', 'data-k': k } }) : k === 'cycle' ? U.select({ name: k, value: f.value, options: ['Hàng tháng', '3 tháng', '6 tháng'], attrs: { 'data-on': 'field', 'data-k': k } }) : k === 'payDay' ? U.select({ name: k, value: f.value, options: ['01', '05', '10', '15', '20', '25'], attrs: { 'data-on': 'field', 'data-k': k } }) : ['start', 'end'].includes(k) ? U.date({ name: k, value: F.fromVN(f.value), attrs: { 'data-on': 'field', 'data-k': k } }) : k === 'address' ? U.textarea({ name: k, value: f.value, rows: 2, attrs: { 'data-on': 'field', 'data-k': k } }) : U.input({ name: k, value: f.value, readonly: !!extra.readonly, attrs: { 'data-on': 'field', 'data-k': k, inputmode: isMoney ? 'numeric' : undefined } }); return U.field({ label: f.label + (isMoney ? ' ⓘ' : ''), req: !!extra.req, input: `<div class="row gap4 ocr-field" style="align-items:flex-start"><div class="grow">${control}</div>${f.confirmed ? '' : U.iconBtn('check', 'confirm', 'Xác nhận đúng', { 'data-k': k }, 'ok')}</div>`, help: chip(f) + (f.editedAt ? ' <span class="xs muted">đã sửa</span>' : ''), cls: extra.cls || '' }); };
    const svcRow = (k) => { const f = fields.find(x => x.key === k); return `<label class="chk"><input type="checkbox" name="${k}" ${f && f.value === 'true' ? 'checked' : ''} data-on="svc" data-k="${k}"> <span>${esc(f ? f.label : k)}</span></label>`; };
    root.innerHTML = `${head}${U.wizard(STEPS, step - 1)}<div class="two-col wide" style="grid-template-columns:minmax(0,1fr) minmax(0,1.15fr)">
      <div>${U.card({ title: `${I('file-text')} ${esc(o.fileName)} <span class="muted" style="font-weight:400">(${esc(o.size)})</span>`, actions: U.btn({ label: 'Tải file khác', icon: 'upload', size: 'btn-sm', cls: 'btn-outline', act: 'other' }), body: U.docPreview({ pages: O.pages(o), page, zoom, fileName: o.fileName }) })}</div>
      <div class="side-stack">${U.card({ body: `<div class="grid grid-2"><div class="row gap12"><div style="width:52px;height:52px;border-radius:12px;background:var(--green-bg);color:var(--green);display:grid;place-items:center">${I('check-circle')}</div><div><b style="font-size:24px;color:var(--text)">${got}</b> <b>trường đã nhận</b><div class="small muted">Tự động trích xuất từ file</div></div></div><div class="row gap12"><div style="width:52px;height:52px;border-radius:12px;background:var(--amber-bg);color:var(--amber);display:grid;place-items:center">${I('clock')}</div><div><b style="font-size:24px;color:var(--amber)">${pending.length}</b> <b>trường cần kiểm tra</b><div class="small muted">Vui lòng xem và xác nhận</div></div></div></div>` })}
      ${step === 4 ? U.note('ok', 'Đã tạo hợp đồng từ trích xuất', 'Hợp đồng ' + U.link('#/contracts/' + o.contractId, esc((Q.contract(o.contractId) || {}).code || '')) + ' – nguồn OCR. Kích hoạt tại chi tiết hợp đồng.') : ''}
      <form id="of">${GROUPS.map(([g, label, ic]) => `<div class="card ocr-group"><div class="card-b"><h4>${I(ic)} ${label}</h4>${g === 'tenant' ? `<div class="form-grid">${inp('tenantName', { req: true })}${inp('idNumber')}${inp('phone', { req: true })}${inp('address')}${inp('email')}</div>` : g === 'room' ? `<div class="form-grid-4">${inp('buildingName', { req: true })}${inp('roomCode', { req: true })}${inp('roomType')}${inp('area', { readonly: true })}</div>` : g === 'term' ? `<div class="form-grid-3">${inp('start', { req: true })}${inp('end', { req: true })}${inp('months', { readonly: true })}</div>` : g === 'money' ? `<div class="form-grid">${inp('price', { req: true })}${inp('deposit', { req: true })}</div><div class="form-grid-3 mt12">${inp('cycle', { req: true })}${inp('payDay', { req: true })}${inp('note')}</div>` : `<div class="small muted mb8">Các dịch vụ đi kèm trong hợp đồng</div><div class="row wrap gap16">${['svc_internet', 'svc_cable', 'svc_parking', 'svc_clean', 'svc_mgmt', 'svc_other'].map(svcRow).join('')}</div>`}</div></div>`).join('')}</form>
      <div class="wz-foot">${U.btn({ label: 'Chạy lại trích xuất', icon: 'refresh-cw', cls: 'btn-outline', act: 'rerun', disabled: step === 4 })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${step === 4 ? U.btn({ label: 'Mở hợp đồng', icon: 'file-text', cls: 'btn-primary', act: 'open' }) : U.btn({ label: 'Tạo hợp đồng', icon: 'arrow-right', cls: 'btn-primary', act: 'create', attrs: { 'data-guide': 'ocr-create' } })}</div></div></div></div>`;
    root.addEventListener('input', (e) => { const el = e.target.closest('[data-k]'); if (!el || el.type === 'checkbox') return; el._dirty = true; });
    U.onChange(root, { field: (el) => { const k = el.dataset.k; let v = el.value; if (['start', 'end'].includes(k)) v = F.date(v); if (['price', 'deposit'].includes(k)) v = String(F.num(v)); X.ocrSetField(o.id, k, v, true); if (k === 'start' || k === 'end') { const s = F.fromVN(fv('start')), en = F.fromVN(fv('end')); if (s && en && en > s) X.ocrSetField(o.id, 'months', F.monthsDiff(s, en) + ' tháng'); } if (k === 'buildingName') X.ocrSetField(o.id, 'roomCode', '', false); if (k === 'roomCode') { const r = St.one('rooms', x => x.code === v); if (r) { X.ocrSetField(o.id, 'roomType', r.type); X.ocrSetField(o.id, 'area', String(r.area)); } } TH.router.refresh(); }, svc: (el) => X.ocrSetField(o.id, el.dataset.k, el.checked ? 'true' : 'false', true) });
    U.bind(root, {
      manual: () => TH.go('#/contracts/new'), other: () => TH.go('#/contracts/ocr'), confirm: (el) => { X.ocrConfirmField(o.id, el.dataset.k); TH.router.refresh(); }, rerun: async () => { if (await U.confirm({ title: 'Chạy lại trích xuất?', text: 'Các chỉnh sửa/xác nhận sẽ được đặt lại về kết quả gốc.', ok: 'Chạy lại' })) { X.ocrRerun(o.id); U.toast('ok', 'Đã chạy lại trích xuất'); } }, draft: () => U.toast('ok', 'Đã lưu nháp trích xuất', o.code + ' – tiếp tục review sau'), open: () => TH.go('#/contracts/' + o.contractId),
      'dp-zoom-in': () => { TH.router.replaceQuery({ id: o.id, page, zoom: Math.min(160, zoom + 10) }); TH.router.refresh(); }, 'dp-zoom-out': () => { TH.router.replaceQuery({ id: o.id, page, zoom: Math.max(60, zoom - 10) }); TH.router.refresh(); }, 'dp-hand': () => U.toast('info', 'Chế độ kéo trang', 'Cuộn/kéo trong khung xem'), 'dp-dl': () => { F.download(o.fileName.replace(/\.\w+$/, '') + '.txt', O.sampleText()); U.toast('ok', 'Đã tải bản văn bản của file'); },
      create: async () => { try { X.ocrReadyToCreate(o); } catch (e) { return U.toast('warn', 'Chưa thể tạo hợp đồng', e.message); } if (await U.confirm({ title: 'Tạo hợp đồng từ trích xuất?', text: 'Form Tạo hợp đồng được điền sẵn ' + fields.length + ' trường (nguồn OCR). Bạn vẫn kiểm tra & kích hoạt theo quy trình Phase 1.', ok: 'Tạo hợp đồng' })) TH.go('#/contracts/new?ocr=' + o.id); } });
    root.querySelector('[data-dp-page]') && root.querySelector('[data-dp-page]').addEventListener('change', (e) => { TH.router.replaceQuery({ id: o.id, page: Math.max(1, Math.min(6, Number(e.target.value) || 1)), zoom }); TH.router.refresh(); });
  }, { menu: 'contracts', permission: 'ocr.use', phase: 2, scopeKey: 'ocr', noAutoRefresh: 'timer' });
})(window.TH);
