/* Phase 1 – Cơ cấu tổ chức (spec v1.8 §4.23, §12.17): cây số cấp linh hoạt, Lead duy nhất theo thời gian, xem cây theo ngày, lịch sử, export. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const canM = () => TH.auth.can('org.manage');
  const unitTypeOpts = () => (Q.md('orgUnitType').length ? Q.md('orgUnitType').map(m => [m.code, m.name]) : Object.entries(Q.L.orgUnitType).map(([k, v]) => [k, v[0]]));
  const empOpts = () => St.rawAll('employees').filter(e => e && e.status !== 'resigned').sort((a, b) => F.cmp(a.name, b.name)).map(e => [e.id, e.name + ' (' + e.code + ')']);

  /* ---- Forms ---- */
  const unitForm = (u = {}, parentId = '') => {
    const m = U.drawer({ title: u.id ? 'Sửa đơn vị ' + esc(u.name) : 'Tạo đơn vị tổ chức', sub: 'Quan hệ tổ chức phải có ngày hiệu lực; không ghi đè lịch sử (§10.4)', body: `<div class="form-grid">
      ${U.field({ label: 'Tên đơn vị', req: true, input: U.input({ name: 'name', value: u.name || '', placeholder: 'VD: TPVH 3' }), cls: 'span2' })}
      ${U.field({ label: 'Mã', input: U.input({ name: 'code', value: u.code || '', placeholder: 'Tự sinh nếu để trống', readonly: !!u.id }) })}
      ${U.field({ label: 'Loại đơn vị', req: true, input: U.select({ name: 'type', value: u.type || 'team', options: unitTypeOpts() }) })}
      ${U.field({ label: 'Đơn vị cha', input: U.select({ name: 'parentId', value: u.parentId || parentId || '', all: '— Gốc (Công ty) —', options: Q.orgOptions().filter(([id]) => id !== u.id) }), cls: 'span2' })}
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: u.effectiveFrom || F.today() }) })}
      ${U.field({ label: 'Ngày kết thúc', input: U.date({ name: 'effectiveTo', value: u.effectiveTo || '' }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: u.note || '', rows: 2 }), cls: 'span2' })}
      ${u.id ? U.field({ label: 'Lý do thay đổi', input: U.input({ name: 'reason', placeholder: 'Bắt buộc ghi audit (§19)' }), cls: 'span2' }) : ''}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: u.id ? 'Lưu thay đổi' : 'Tạo đơn vị', icon: 'save', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); const r = X.saveOrgUnit(Object.assign({ id: u.id }, d)); m.close(); ok(u.id ? 'Đã cập nhật ' + r.name : 'Đã tạo đơn vị ' + r.name); } catch (e) { U.toast('err', 'Không lưu được', e.message); } } });
  };
  const leadForm = (u) => {
    const cur = Q.orgLead(u.id);
    const m = U.modal({ title: 'Bổ nhiệm / thay Lead – ' + esc(u.name), sub: 'Mỗi đội/nhóm có đúng một Lead hiệu lực; nhiệm kỳ cũ được lưu lịch sử (§4.23)', body: `<div class="form-grid">${cur.id ? U.note('info', 'Lead hiện tại', esc(cur.name) + ' – nhiệm kỳ sẽ kết thúc ngày hiệu lực − 1') : ''}
      ${U.field({ label: 'Nhân viên', req: true, input: U.select({ name: 'employeeId', placeholder: 'Chọn nhân viên', options: empOpts() }), cls: 'span2' })}
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}
      ${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'Bổ nhiệm mới / thay thế…' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Bổ nhiệm', icon: 'user-check', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); X.setOrgLead(u.id, d.employeeId, d.effectiveFrom, d.reason); m.close(); ok('Đã bổ nhiệm Lead ' + u.name); } catch (e) { U.toast('err', 'Không bổ nhiệm được', e.message); } } });
  };
  const moveForm = (u) => {
    const m = U.modal({ title: 'Chuyển đơn vị ' + esc(u.name), size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Đơn vị cha mới', input: U.select({ name: 'parentId', value: u.parentId || '', all: '— Gốc —', options: Q.orgOptions().filter(([id]) => !Q.orgDescendants(u.id).includes(id)) }), cls: 'span2' })}${U.field({ label: 'Ngày hiệu lực', input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Chuyển', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); X.moveOrgUnit(u.id, d.parentId, d.effectiveFrom, d.reason); m.close(); ok('Đã chuyển đơn vị'); } catch (e) { U.toast('err', 'Không chuyển được', e.message); } } });
  };
  const employmentForm = (e, u) => {
    const m = U.modal({ title: 'Gán đơn vị / chức danh – ' + esc(e.name), sub: 'Điều chuyển tổ chức có ngày hiệu lực; lịch sử điều chuyển được giữ (§4.24)', body: `<div class="form-grid">
      ${U.field({ label: 'Đơn vị', req: true, input: U.select({ name: 'orgUnitId', value: (u || {}).id || '', placeholder: 'Chọn đơn vị', options: Q.orgOptions() }), cls: 'span2' })}
      ${U.field({ label: 'Chức danh', input: U.select({ name: 'positionId', value: (Q.employeePosition(e.id) || {}).id || '', all: 'Giữ nguyên / không đổi', options: St.rawAll('positions').filter(p => p && p.status !== 'inactive').map(p => [p.id, p.name]) }) })}
      ${U.field({ label: 'Hình thức', input: U.select({ name: 'isPrimary', value: '1', options: [['1', 'Đơn vị chính (điều chuyển)'], ['0', 'Kiêm nhiệm']] }) })}
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}
      ${U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Lưu', icon: 'save', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); X.setEmployment({ employeeId: e.id, orgUnitId: d.orgUnitId, positionId: d.positionId, effectiveFrom: d.effectiveFrom, isPrimary: d.isPrimary === '1', reason: d.reason }); m.close(); ok('Đã cập nhật quan hệ tổ chức của ' + e.name); } catch (e2) { U.toast('err', 'Không lưu được', e2.message); } } });
  };
  TH.forms.orgUnit = unitForm; TH.forms.orgLead = leadForm; TH.forms.employment = employmentForm;

  /* ---- Trang ---- */
  TH.router.register('/hr/org', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Cơ cấu tổ chức' }]);
    const date = q.date || F.today(); const sel = q.unit ? Q.orgUnit(q.unit) : null; const tree = Q.orgTree(date);
    const scopeOf = (u) => { const ids = Q.orgDescendants(u.id, date); const emps = Q.employeesOfUnits(ids, date); const bIds = Q.scopeBuildingIds({ orgUnitId: u.id, date }); return { units: ids.length - 1, emps: emps.length, buildings: bIds.length, rooms: F.sum(bIds, id => Q.roomsOf(id).length) }; };
    const row = (u) => { const lead = Q.orgLead(u.id, date); const sc = scopeOf(u); return `<div class="org-row ${sel && sel.id === u.id ? 'on' : ''}" style="padding-left:${12 + u.depth * 22}px" data-act="pick" data-id="${u.id}"><span class="org-caret">${u.depth ? '└' : ''}</span><span class="org-name"><b>${esc(u.name)}</b> <span class="chip gray xs">${esc(Q.label('orgUnitType', u.type))}</span> <span class="xs muted">${esc(u.code)}</span></span><span class="org-lead">${lead.name ? U.avatar(lead.name, 'sm') + ' ' + esc(lead.name) : '<span class="muted xs">Chưa có Lead</span>'}</span><span class="org-stats xs muted">${sc.emps} NV · ${sc.buildings} tòa · ${sc.rooms} phòng</span>${canM() ? U.iconBtn('more', 'more', 'Thao tác', { 'data-id': u.id }) : ''}</div>`; };
    root.innerHTML = `${U.pageHead({ title: 'Cơ cấu tổ chức', sub: 'Cây tổ chức số cấp linh hoạt; chọn đơn vị cha sẽ lấy toàn bộ đơn vị con → nhân sự → tòa/phòng phụ trách (§4.3, §4.23).', acts: [U.btn({ label: 'Thêm đơn vị', icon: 'plus', cls: 'btn-primary', act: 'add', disabled: !canM(), attrs: { 'data-guide': 'org-add' } }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Xem cây tại ngày', input: U.date({ name: 'date', value: date, attrs: { 'data-on': 'f' } }) }), U.field({ label: '', input: `<div class="help" style="padding-top:26px">Quan hệ tổ chức/phân công có hiệu lực theo thời gian – báo cáo kỳ cũ dùng đúng cây tại kỳ đó (§10.6)</div>`, cls: 'wide' })], U.btn({ label: 'Hôm nay', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="two-col wide"><div>${U.card({ title: 'Cây tổ chức', icon: 'layers', sub: tree.length + ' đơn vị hiệu lực tại ' + F.date(date), bodyCls: 'tight', body: `<div class="org-tree" data-guide="org-tree">${tree.map(row).join('') || U.empty({ title: 'Chưa có đơn vị' })}</div>` })}</div>
    <aside class="side-stack" id="org-side"></aside></div>`;
    const side = root.querySelector('#org-side');
    if (sel && sel.id) {
      const lead = Q.orgLead(sel.id, date); const ids = Q.orgDescendants(sel.id, date); const emps = Q.employeesOfUnits(ids, date); const bIds = Q.scopeBuildingIds({ orgUnitId: sel.id, date });
      side.innerHTML = `${U.card({ title: esc(sel.name), icon: 'building', actions: canM() ? U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }) : '', body: U.kv([['Mã', esc(sel.code)], ['Loại', Q.label('orgUnitType', sel.type)], ['Đường dẫn', esc(Q.orgPath(sel.id))], ['Lead hiện tại', lead.name ? U.link('#/hr/' + lead.id, esc(lead.name)) : '<span class="muted">Chưa có</span>'], ['Hiệu lực', F.date(sel.effectiveFrom) + (sel.effectiveTo ? ' – ' + F.date(sel.effectiveTo) : ' → nay')], ['Trạng thái', sel.status === 'inactive' ? U.chip('Ngừng hoạt động', 'gray') : U.chip('Hoạt động', 'green')]], 'one') + (canM() ? `<div class="row mt12 gap8 wrap">${U.btn({ label: 'Bổ nhiệm / thay Lead', icon: 'user-check', size: 'btn-sm', cls: 'btn-outline', act: 'lead' })}${U.btn({ label: 'Thêm đơn vị con', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'add-child' })}${U.btn({ label: 'Chuyển', icon: 'arrow-left-right', size: 'btn-sm', cls: 'btn-outline', act: 'move' })}${U.btn({ label: 'Ngừng hoạt động', icon: 'minus-circle', size: 'btn-sm', cls: 'btn-ghost', act: 'deactivate' })}</div>` : '') })}
      ${U.card({ title: 'Phạm vi dữ liệu (scope)', icon: 'search', sub: 'Đơn vị + ' + (ids.length - 1) + ' đơn vị con → ' + emps.length + ' nhân sự → ' + bIds.length + ' tòa', body: `<div class="grid grid-3">${U.stat('Nhân sự', emps.length)}${U.stat('Tòa', bIds.length)}${U.stat('Phòng', F.sum(bIds, id => Q.roomsOf(id).length))}</div><div class="mt8 row wrap gap4">${bIds.map(id => U.link('#/buildings/' + id, esc(Q.building(id).name), 'chip gray')).join(' ') || '<span class="muted small">Chưa có tòa nào do nhân sự đơn vị này làm Phụ trách chính</span>'}</div><div class="row mt12 gap8">${U.btn({ label: 'Dashboard theo đơn vị', icon: 'home', size: 'btn-sm', cls: 'btn-outline', act: 'go-dash' })}${U.btn({ label: 'Phân công', icon: 'building', size: 'btn-sm', cls: 'btn-outline', act: 'go-assign' })}</div>` })}
      ${U.card({ title: 'Nhân sự thuộc đơn vị (' + emps.length + ')', icon: 'users', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Nhân viên</th><th>Đơn vị</th><th>Chức danh</th><th>Tòa phụ trách</th><th></th></tr></thead><tbody>${emps.map(e => { const eu = Q.employeeUnit(e.id, date); const bs = Q.buildingsOfEmployee(e.id, date); return `<tr><td>${U.link('#/hr/' + e.id, esc(e.name), 'bold')}<div class="xs muted">${esc(e.code)}</div></td><td>${esc(eu.name || '-')}</td><td>${esc((Q.employeePosition(e.id, date) || {}).name || e.title || '-')}</td><td class="xs">${bs.map(b => esc(b.name)).join(', ') || '-'}</td><td class="tr">${canM() ? U.iconBtn('arrow-left-right', 'employment', 'Điều chuyển / kiêm nhiệm', { 'data-id': e.id }) : ''}</td></tr>`; }).join('') || '<tr><td colspan="5" class="muted tc">Chưa có nhân sự</td></tr>'}</tbody></table>` })}
      ${U.card({ title: 'Lịch sử Lead & thay đổi', icon: 'history', body: U.timeline([...(sel.leadHistory || []).map(h => ({ when: F.date(h.from) + (h.to ? ' – ' + F.date(h.to) : ' → nay'), title: 'Lead: ' + Q.employeeName(h.employeeId), sub: h.reason || '', color: h.to ? 'gray' : 'green', fill: !h.to })), ...(sel.moveHistory || []).map(h => ({ when: F.date(h.effectiveFrom), title: 'Chuyển sang ' + (h.to ? Q.orgUnit(h.to).name : 'gốc'), sub: h.reason || '', color: 'blue' }))]) || U.empty({ title: 'Chưa có lịch sử' }) })}`;
    } else side.innerHTML = U.card({ title: 'Hướng dẫn', icon: 'info', body: `<div class="small">Chọn một đơn vị để xem Lead, phạm vi dữ liệu và nhân sự. Ví dụ §4.3: chọn <b>TPVH 1</b> → scope = tòa của toàn bộ nhân sự TPVH 1; đổi "Xem cây tại ngày" sang 30/09/2026 để thấy tòa Central còn thuộc TPVH 1 (từ 01/10 thuộc TPVH 2).</div>` }) + U.card({ title: 'Quy tắc', icon: 'shield-check', body: `<ul class="small" style="padding-left:18px;line-height:1.8"><li>Mỗi đội/nhóm có đúng một Lead hiệu lực; thay Lead lưu lịch sử, không ghi đè nhiệm kỳ cũ.</li><li>Cây không có chu trình; thay đổi tương lai không tác động trước ngày hiệu lực.</li><li>Scope tổ chức gồm toàn bộ node con (§10.5); tòa chỉ tính một lần theo Phụ trách chính (§4.3).</li></ul>` });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, q, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, {
      pick: (el) => { TH.router.replaceQuery(Object.assign({}, q, { unit: el.dataset.id })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({ unit: q.unit || '' }); TH.router.refresh(); },
      add: () => unitForm({}, sel ? sel.id : ''), 'add-child': () => unitForm({}, sel.id), edit: () => unitForm(sel), lead: () => leadForm(sel), move: () => moveForm(sel), employment: (el) => employmentForm(St.rawGet('employees', el.dataset.id), sel),
      deactivate: async () => { const r = await U.confirm({ title: 'Ngừng hoạt động ' + sel.name + '?', text: 'Đơn vị không còn hiệu lực từ ngày chọn; lịch sử được giữ.', body: U.field({ label: 'Ngày kết thúc', input: U.date({ name: 'to', value: F.today() }) }) + U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Ngừng', danger: true }); if (r) { try { X.deactivateOrgUnit(sel.id, r.to, r.reason); ok('Đã ngừng hoạt động đơn vị'); } catch (e) { U.toast('err', 'Không ngừng được', e.message); } } },
      'go-dash': () => TH.go('#/dashboard?orgUnitId=' + sel.id), 'go-assign': () => TH.go('#/hr/assignments?orgUnitId=' + sel.id),
      export: () => { F.download('co-cau-to-chuc-' + date + '.csv', F.csv(tree.map(u => { const l = Q.orgLead(u.id, date); const sc = scopeOf(u); return [u.code, '  '.repeat(u.depth) + u.name, Q.label('orgUnitType', u.type), u.parentId ? Q.orgUnit(u.parentId).name : '', l.name || '', sc.emps, sc.buildings, sc.rooms, u.effectiveFrom]; }), ['Mã', 'Đơn vị', 'Loại', 'Đơn vị cha', 'Lead', 'Nhân sự', 'Tòa', 'Phòng', 'Hiệu lực từ']), 'text/csv'); ok('Đã xuất cây tổ chức'); },
      more: (el) => { const u = Q.orgUnit(el.dataset.id); U.menu(el, [{ label: 'Sửa', icon: 'pencil', onClick: () => unitForm(u) }, { label: 'Thêm đơn vị con', icon: 'plus', onClick: () => unitForm({}, u.id) }, { label: 'Bổ nhiệm / thay Lead', icon: 'user-check', onClick: () => leadForm(u) }, { label: 'Chuyển đơn vị cha', icon: 'arrow-left-right', onClick: () => moveForm(u) }, '-', { label: 'Ngừng hoạt động', icon: 'minus-circle', danger: true, onClick: async () => { const r = await U.confirm({ title: 'Ngừng hoạt động ' + u.name + '?', body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }), ok: 'Ngừng', danger: true }); if (r) { try { X.deactivateOrgUnit(u.id, F.today(), r.reason); ok('Đã ngừng'); } catch (e) { U.toast('err', 'Không ngừng được', e.message); } } } }]); },
    });
  }, { menu: 'org', permission: 'org.view' });
})(window.TH);
