(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  TH.router.register('/receivables', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Thu tiền & công nợ' }]);
    const period = TH.router.periodOf(q);
    const f = { period, buildingId: q.buildingId || '', age: q.age || '', pay: q.pay || '', reminded: q.reminded || '', s: q.s || '', overdue: q.overdue || '' };
    const all = Q.receivables({ period: f.period, buildingId: f.buildingId });
    const rows = all.filter(x => f.pay === 'paid' ? true : x.remaining > 0).filter(x => (!f.overdue || x.overdueDays > 0) && (!f.age || (f.age === '0' ? x.overdueDays === 0 : f.age === '1-7' ? x.overdueDays >= 1 && x.overdueDays <= 7 : f.age === '8-15' ? x.overdueDays >= 8 && x.overdueDays <= 15 : x.overdueDays > 15)) && (!f.pay || Q.invPayStatus(x.inv) === f.pay) && (!f.reminded || (f.reminded === 'yes' ? x.reminded : !x.reminded)) && (!f.s || F.norm(Q.room(x.inv.roomId).code + ' ' + Q.tenant(x.inv.tenantId).name + ' ' + x.inv.code).includes(F.norm(f.s)))).sort((a, b) => F.cmp(a.inv.dueDate, b.inv.dueDate));
    const rec = F.sum(all, x => x.inv.total), col = F.sum(all, x => x.paid), overdue = all.filter(x => x.overdueDays > 0);
    root.innerHTML = `${U.pageHead({ title: 'Thu tiền & công nợ', sub: 'Theo dõi, thu tiền và quản lý công nợ khách thuê', acts: [U.btn({ label: 'Thu tiền thủ công', icon: 'clipboard-check', cls: 'btn-outline', act: 'pay', title: 'Chọn khách, thu một phần, phân bổ thủ công', attrs: { 'data-guide': 'receivable-pay' } }), U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Phải thu', value: F.vnd(rec), cap: all.length + ' hóa đơn', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã thu', value: F.vnd(col), cap: F.pct(col, rec) + '% kế hoạch', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn phải thu', value: F.vnd(rec - col), cap: F.pct(rec - col, rec) + '% tổng phải thu', icon: 'coins', tone: 'amber' })}${U.kpi({ label: 'Quá hạn', value: F.vnd(F.sum(overdue, x => x.remaining)), cap: overdue.length + ' hóa đơn', icon: 'clock', tone: 'red' })}</div>
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: f.period, all: 'Tất cả kỳ', options: [...new Set(St.all('invoices').map(i => i.period))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tuổi nợ', input: U.select({ name: 'age', value: f.age, all: 'Tất cả', options: [['0', 'Chưa quá hạn'], ['1-7', '1–7 ngày'], ['8-15', '8–15 ngày'], ['15+', 'Trên 15 ngày']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái thu', input: U.select({ name: 'pay', value: f.pay, all: 'Tất cả', options: [['unpaid', 'Chưa thu'], ['partial', 'Thu một phần'], ['paid', 'Thu đủ']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Đã/Chưa nhắc', input: U.select({ name: 'reminded', value: f.reminded, all: 'Tất cả', options: [['yes', 'Đã nhắc'], ['no', 'Chưa nhắc']], attrs: { 'data-on': 'f' } }) })])}
    <div class="card filters"><div class="filterbar">${U.field({ input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo phòng, tên khách, mã hóa đơn...', icon: 'search', attrs: { id: 'rs' } }), cls: 'wide' })}${U.btn({ label: 'Tìm kiếm', icon: 'search', cls: 'btn-primary', act: 'search' })}${U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' })}</div></div>
    ${U.card({ title: `Danh sách công nợ <span class="muted" style="font-weight:400">(${rows.length} khoản)</span>`, actions: '<span id="bulk" class="row"></span>', body: null, id: 'tbl-card', attrs: 'data-guide="receivables-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const tbl = U.table(wrap, { rows, selectable: true, unit: 'khoản', rowKey: x => x.inv.id, sortKey: 'due', onSelect: (ids) => { const payable = ids.filter(id => Q.invRemaining(St.get('invoices', id)) > 0); root.querySelector('#bulk').innerHTML = ids.length ? `<span class="small muted">${ids.length} đã chọn</span>${U.btn({ label: 'Gửi nhắc Zalo', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-zalo', disabled: !payable.length })}${U.btn({ label: 'Xác nhận thu tiền' + (payable.length ? ' (' + payable.length + ')' : ''), icon: 'dollar', size: 'btn-sm', cls: 'btn-primary', act: 'bulk-pay', disabled: !payable.length, title: 'Thu đủ số còn lại kèm minh chứng' })}` : ''; }, cols: [
      { key: 'room', label: 'Phòng / Tòa', render: x => U.cell2(U.link('#/rooms/' + x.inv.roomId, esc(Q.room(x.inv.roomId).code)), esc(Q.building(x.inv.buildingId).name)) },
      { key: 't', label: 'Khách', render: x => { const t = Q.tenant(x.inv.tenantId); return U.cell2(U.link('#/tenants/' + t.id, esc(t.name)), esc(t.phone)); } },
      { key: 'inv', label: 'Hóa đơn', render: x => U.link('#/invoices/' + x.inv.id, esc(x.inv.code)) }, { key: 'due', label: 'Hạn thanh toán', sortable: true, sortVal: x => x.inv.dueDate, render: x => F.date(x.inv.dueDate) },
      { key: 'total', label: 'Tổng (VND)', num: true, render: x => F.vnd(x.inv.total) }, { key: 'paid', label: 'Đã thu (VND)', num: true, render: x => F.vnd(x.paid) }, { key: 'rem', label: 'Còn lại (VND)', num: true, sortable: true, sortVal: x => x.remaining, render: x => `<b class="${x.remaining ? '' : 'green'}">${F.vnd(x.remaining)}</b>` },
      { key: 'od', label: 'Số ngày quá hạn', sortable: true, sortVal: x => x.overdueDays, render: x => x.overdueDays ? `<span class="red bold">${x.overdueDays} ngày</span>` : (x.remaining ? `<span class="muted">${F.daysUntil(x.inv.dueDate) === 0 ? '0 ngày' : '-'}</span>` : '-') },
      { key: 'rm', label: 'Trạng thái nhắc', render: x => U.chip(x.reminded ? 'Đã nhắc' : 'Chưa nhắc', x.reminded ? 'green' : 'red') },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([x.remaining ? U.actBtn({ icon: 'dollar', label: 'Xác nhận thu tiền', act: 'pay-inv', tone: 'primary', attrs: { 'data-id': x.inv.id } }) : '', U.moreBtn(x.inv.id)]) }] });
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelectorAll('.filterbar')[0])) });
    root.querySelector('#rs').addEventListener('keydown', e => { if (e.key === 'Enter') TH.router.applyFilter(f, { s: e.target.value }); });
    U.bind(root, {
      pay: () => Fm.payment({}), 'pay-inv': (b) => Fm.confirmPayments({ invoiceIds: [b.dataset.id] }), 'bulk-pay': () => Fm.confirmPayments({ invoiceIds: tbl.selected() }), search: () => { TH.router.applyFilter(f, { s: root.querySelector('#rs').value }); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); },
      'bulk-zalo': () => Fm.zaloQuick({ invoiceIds: tbl.selected(), eventKey: 'debt', title: 'Nhắc công nợ qua Zalo' }), more: (b) => TH.pages.invMenu(b, St.get('invoices', b.dataset.id)),
      export: () => { F.download('cong-no-' + (f.period || 'all') + '.csv', F.csv(rows.map(x => [Q.room(x.inv.roomId).code, Q.building(x.inv.buildingId).name, Q.tenant(x.inv.tenantId).name, x.inv.code, x.inv.dueDate, x.inv.total, x.paid, x.remaining, x.overdueDays, x.reminded ? 'Đã nhắc' : 'Chưa nhắc']), ['Phòng', 'Tòa', 'Khách', 'Hóa đơn', 'Hạn', 'Tổng', 'Đã thu', 'Còn lại', 'Ngày quá hạn', 'Nhắc']), 'text/csv'); U.toast('ok', 'Đã xuất công nợ'); },
    });
  }, { menu: 'receivables', permission: 'payments.view' });

  /* ---------- Chi tiết khoản thu ---------- */
  TH.router.register('/payments/:id', (root, p) => {
    const pay = St.get('payments', p.id); if (!pay) { root.innerHTML = U.empty({ title: 'Không tìm thấy khoản thu' }); return; }
    const t = Q.tenant(pay.tenantId), r = Q.room(pay.roomId), b = Q.building(pay.buildingId), allocs = Q.payAllocs(pay.id); const allocTotal = F.sum(allocs, a => a.amount); const un = pay.amount - allocTotal;
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Thu tiền', href: '#/receivables' }, { label: 'Chi tiết khoản thu' }]);
    const reversed = pay.status === 'reversed';
    const evidenceBody = `<div class="row gap12" style="border:1px solid var(--border);border-radius:10px;padding:10px"><div class="fic pdf" style="width:44px;height:44px;border-radius:10px;display:grid;place-items:center;background:var(--red-bg);color:var(--red);font-size:20px">${I('file-text')}</div><div class="grow"><b>${esc(pay.evidence || 'bien_lai_' + pay.code + '.pdf')}</b><div class="xs muted">PDF · 512 KB</div></div>${U.btn({ label: 'Xem trước', icon: 'eye', size: 'btn-xs', cls: 'btn-outline', act: 'preview' })}</div><div class="xs muted mt12 mb8">Tệp đính kèm khác</div><div class="file-list">${U.fileItem({ name: 'bien_lai_' + pay.code + '.pdf', size: '512 KB', date: pay.date }, U.iconBtn('download', 'dl', 'Tải'))}${U.fileItem({ name: 'sao_ke_' + pay.date.slice(8) + pay.date.slice(5, 7) + '.png', size: '1.2 MB', date: pay.date }, U.iconBtn('download', 'dl', 'Tải'))}</div>`;
    const historyBody = U.timeline([{ when: F.datetime(pay.createdAt), title: 'Tạo khoản thu', sub: Q.userName(pay.createdBy) + ' tạo khoản thu', color: 'blue', fill: true }, { when: F.datetime(pay.createdAt), title: 'Kiểm tra ghép', sub: 'Đối chiếu khách, hóa đơn và số tiền', color: 'blue' }, { when: F.datetime(pay.createdAt), title: 'Xác nhận ghi nhận', sub: Q.userName(pay.createdBy) + ' xác nhận ghi nhận', color: 'green', fill: true }, { when: F.datetime(pay.createdAt), title: 'Phân bổ vào hóa đơn', sub: 'Phân bổ ' + allocs.length + ' hóa đơn', color: 'blue' }, ...((pay.history || []).slice(1).map(h => ({ when: F.datetime(h.at), title: h.what.split(':')[0], sub: h.who + (h.what.includes(':') ? ' – ' + h.what.split(':').slice(1).join(':') : ''), color: /Hoàn tác/.test(h.what) ? 'red' : 'amber', fill: true })))]);
    const related = [{ key: 'evidence', title: 'Chứng từ & bằng chứng', icon: 'file-text', summary: pay.evidence ? 'Đã có chứng từ' : 'Chứng từ mô phỏng', meta: esc(pay.evidence || 'bien_lai_' + pay.code + '.pdf'), body: evidenceBody }, { key: 'history', title: 'Lịch sử xử lý', icon: 'history', summary: (4 + (pay.history || []).slice(1).length) + ' mốc xử lý', meta: reversed ? 'Khoản thu đã hoàn tác' : 'Đã ghi nhận và phân bổ', body: historyBody + U.note('info', 'Lưu ý', 'Mọi thay đổi, điều chỉnh liên quan đến khoản thu này sẽ được lưu lại trong lịch sử xử lý để đảm bảo tính minh bạch.') }];
    root.innerHTML = `${U.pageHead({ back: '#/receivables', title: 'Chi tiết khoản thu', sub: 'Xem thông tin chi tiết, phân bổ công nợ và lịch sử xử lý của khoản thu.', acts: [U.btn({ label: 'Điều chỉnh', icon: 'pencil', cls: 'btn-outline', act: 'adjust', disabled: reversed || !TH.auth.can('adjustPayment'), title: TH.auth.can('adjustPayment') ? '' : 'Cần vai trò Admin/Kế toán' }), U.btn({ label: 'Hoàn tác ghi nhận', icon: 'undo', cls: 'btn-outline', act: 'reverse', disabled: reversed || !TH.auth.can('reversePayment'), title: TH.auth.can('reversePayment') ? '' : 'Cần vai trò Admin/Kế toán' }), U.btn({ label: 'Tải chứng từ', icon: 'download', cls: 'btn-primary', act: 'dl' })] })}
    ${reversed ? U.note('danger', 'Khoản thu đã hoàn tác', 'Lý do: ' + esc(pay.reverseReason || '') + ' – ' + F.datetime(pay.reversedAt) + '. Các hóa đơn đã được tính lại số còn nợ; dấu vết giữ nguyên (BR-22).') + '<div class="mb16"></div>' : ''}
    ${U.card({ cls: 'mb16', body: `<div class="grid grid-4" style="gap:20px">${[['Mã khoản thu', `<b>${esc(pay.code)}</b> ${Q.chip('payment', pay.adjusted && !reversed ? 'adjusted' : pay.status)}`, ''], ['Số tiền', `<b style="font-size:18px">${F.vnd(pay.amount)}</b> <span class="muted small">VND</span>`, ''], ['Ngày thu', `${I('calendar')} <b>${F.datetime(pay.createdAt && pay.createdAt.startsWith(pay.date) ? pay.createdAt : pay.date)}</b>`, ''], ['Phương thức', `${I('credit-card')} <b>${esc(pay.method)}</b>`, ''], ['Nguồn tham chiếu', `${I('landmark')} <b>${esc(pay.ref || '-')}</b>`, ''], ['Người nộp tiền', `${I('user')} <b>${esc(t.name)}</b><div class="xs muted">${esc(t.phone)}</div>`, ''], ['Phòng / Tòa nhà', `${I('home')} <b class="blue">${esc(r.code || '-')} / ${esc(b.name || '-')}</b>`, ''], ['Người tạo', `${I('user')} <b>${esc(Q.userName(pay.createdBy))}</b><div class="xs muted">${F.datetime(pay.createdAt)}</div>`, '']].map(([k, v]) => `<div><div class="xs muted" style="text-transform:uppercase;letter-spacing:.04em">${k}</div><div class="mt4">${v}</div></div>`).join('')}</div>` })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tiền nhận', value: F.vnd(pay.amount), cap: 'VND', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã phân bổ', value: F.vnd(allocTotal), cap: F.pct(allocTotal, pay.amount) + '%', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Chưa phân bổ', value: F.vnd(un), cap: F.pct(un, pay.amount) + '%', icon: 'alert-circle', tone: 'amber' })}${U.kpi({ label: 'Số hóa đơn liên quan', value: allocs.length, cap: 'hóa đơn', icon: 'receipt', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'payment-related', items: related, cls: 'mb16' })}<div class="side-stack">
      ${U.card({ title: 'Phân bổ công nợ', icon: 'clipboard-check', sub: 'Danh sách hóa đơn đã được phân bổ từ khoản thu này.', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Mã hóa đơn</th><th>Kỳ</th><th class="num">Phải thu (VND)</th><th class="num">Đã phân bổ (VND)</th><th class="num">Còn lại sau phân bổ (VND)</th><th>Trạng thái</th></tr></thead><tbody>${allocs.map((a, i) => { const inv = St.get('invoices', a.invoiceId); return `<tr><td>${i + 1}</td><td>${U.link('#/invoices/' + inv.id, inv.code)}</td><td>${F.periodLabel(inv.period)}</td><td class="num">${F.vnd(inv.total)}</td><td class="num">${F.vnd(a.amount)}</td><td class="num">${F.vnd(Q.invRemaining(inv))}</td><td>${Q.invPayChip(inv)}</td></tr>`; }).join('') || '<tr><td colspan="7" class="muted tc">Chưa phân bổ vào hóa đơn nào</td></tr>'}</tbody></table>`, footer: `<span>Tổng phân bổ</span><b style="font-size:15px">${F.vnd(allocTotal)} VND</b>` })}
      ${U.card({ title: 'Thông tin giao dịch', icon: 'landmark', body: `<div class="grid grid-2">${U.kv([['Ngân hàng nhận', esc(pay.bank || '-'), pay.bank ? 'Chi nhánh Hà Nội' : ''], ['Số tham chiếu', esc(pay.ref || '-')], ['Nội dung chuyển khoản', esc(pay.transferContent || '-')]], 'one')}${U.kv([['Nguồn ghi nhận', 'Khách thuê thanh toán'], ['Phương thức thanh toán', esc(pay.method)], ['Ghi chú', esc(pay.note || '-')]], 'one')}</div>` })}</div>`;
    U.bind(root, { adjust: () => Fm.adjustPayment(pay), reverse: () => Fm.reversePayment(pay), dl: () => U.fakePdf('Bien lai ' + pay.code, ['Khách: ' + t.name, 'Số tiền: ' + F.vnd(pay.amount), 'Ngày: ' + F.date(pay.date), 'Phương thức: ' + pay.method, ...allocs.map(a => 'Phân bổ ' + St.get('invoices', a.invoiceId).code + ': ' + F.vnd(a.amount))]), preview: () => U.modal({ title: 'Xem trước chứng từ', body: `<div class="empty">${I('file-text')}<b>${esc(pay.evidence || 'bien_lai.pdf')}</b><p>Bản demo mô phỏng xem trước PDF. Bản thật hiển thị file thực tế đã upload.</p></div>` }) });
  }, { menu: 'receivables', permission: 'payments.view', resource: { type: 'payment' } });
})(window.TH);
