(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  TH.router.register('/receivables', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Thu tiền & công nợ' }]);
    const period = TH.router.periodOf(q);
    const f = { period, orgUnitId: q.orgUnitId || '', employeeId: q.employeeId || '', areaId: q.areaId || '', buildingId: q.buildingId || '', roomId: q.roomId || '', tenantId: q.tenantId || '', buildingType: q.buildingType || '', managerId: q.managerId || '', leadId: q.leadId || '', age: q.age || '', pay: q.pay || '', reminded: q.reminded || '', s: q.s || '', overdue: q.overdue || '', due: q.due || '', group: q.group || '' }, scope = Q.scope({ period, orgUnitId: q.orgUnitId, employeeId: q.employeeId, areaId: q.areaId, buildingId: q.buildingId, buildingType: q.buildingType, managerId: q.managerId, leadId: q.leadId });
    const all = Q.receivables({ period: f.period }).filter(x => scope.buildingIds.includes(x.inv.buildingId || Q.contract(x.inv.contractId).buildingId));
    const rows = all.filter(x => f.pay === 'paid' || f.pay === 'overpaid' ? true : x.remaining > 0).filter(x => (!f.roomId || x.inv.roomId === f.roomId) && (!f.tenantId || x.inv.tenantId === f.tenantId) && (!f.due || (f.due === 'today' ? x.inv.dueDate === F.today() : f.due === 'week' ? x.inv.dueDate >= F.today() && x.inv.dueDate <= F.addDays(F.today(), 7) : x.inv.dueDate < F.today())) && (f.pay !== 'overpaid' || Q.invPayStatusW3(x.inv) === 'overpaid') && (!f.overdue || x.overdueDays > 0) && (!f.age || (f.age === '0' ? x.overdueDays === 0 : f.age === '1-7' ? x.overdueDays >= 1 && x.overdueDays <= 7 : f.age === '8-15' ? x.overdueDays >= 8 && x.overdueDays <= 15 : x.overdueDays > 15)) && (!f.pay || f.pay === 'overpaid' || Q.invPayStatus(x.inv) === f.pay) && (!f.reminded || (f.reminded === 'yes' ? x.reminded : !x.reminded)) && (!f.s || F.norm(Q.room(x.inv.roomId).code + ' ' + Q.tenant(x.inv.tenantId).name + ' ' + x.inv.code).includes(F.norm(f.s)))).sort((a, b) => F.cmp(a.inv.dueDate, b.inv.dueDate));
    const overdue = all.filter(x => x.overdueDays > 0), currentView = f.overdue ? 'overdue' : f.pay || '';
    root.innerHTML = `${U.pageHead({ title: 'Thu tiền & công nợ', sub: 'Ưu tiên các khoản đến hạn, quá hạn và ghi nhận thanh toán.', acts: [U.btn({ label: 'Tiền chưa xác định' + (St.where('payments', x => x.unidentified && x.status !== 'reversed').length ? ' (' + St.where('payments', x => x.unidentified && x.status !== 'reversed').length + ')' : ''), icon: 'help-circle', cls: 'btn-outline', act: 'unidentified', title: 'Ghi nhận khoản tiền chưa khớp khách/phòng (Unidentified Receipt) để ghép sau' }), U.btn({ label: 'Ghi nhận thu tiền', icon: 'clipboard-check', cls: 'btn-primary', act: 'pay', title: 'Chọn khách, thu một phần hoặc phân bổ thủ công', attrs: { 'data-guide': 'receivable-pay' } })] })}
    ${(() => { const un = St.where('payments', x => x.unidentified && x.status !== 'reversed'); const adv = St.where('payments', x => !x.unidentified && x.status !== 'reversed' && Q.paymentUnallocated(x) > 0.5); return un.length || adv.length ? U.note('warn', 'Khoản thu cần xử lý (§4.15)', (un.length ? un.length + ' khoản <strong>tiền chưa xác định</strong> ' + F.vnd(F.sum(un, x => x.amount)) + ' – ' + un.map(x => U.link('#/payments/' + x.id, esc(x.code))).join(', ') + '. ' : '') + (adv.length ? adv.length + ' khoản <strong>thu thừa / tạm ứng</strong> chưa phân bổ ' + F.vnd(F.sum(adv, x => Q.paymentUnallocated(x))) + ' – ' + adv.slice(0, 5).map(x => U.link('#/payments/' + x.id, esc(x.code))).join(', ') : '')) + '<div class="mb16"></div>' : ''; })()}
    ${U.statusTabs([{ key: '', label: 'Cần thu', count: all.filter(x => x.remaining > 0).length }, { key: 'overdue', label: 'Quá hạn', count: overdue.length, color: 'red' }, { key: 'partial', label: 'Thu một phần', count: all.filter(x => Q.invPayStatus(x.inv) === 'partial').length, color: 'amber' }, { key: 'paid', label: 'Đã thu đủ', count: all.filter(x => Q.invPayStatus(x.inv) === 'paid').length, color: 'green' }, { key: 'overpaid', label: 'Thu thừa', count: all.filter(x => Q.invPayStatusW3(x.inv) === 'overpaid').length, color: 'purple' }], currentView)}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Phòng, khách thuê hoặc mã hóa đơn...', icon: 'search', attrs: { id: 'rs' } }), cls: 'wide' }), U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: f.period, all: 'Tất cả kỳ', options: [...new Set(St.all('invoices').map(i => i.period))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), `<details class="filter-more"><summary>${I('filter')} Bộ lọc khác</summary><div class="filter-pop">${U.dimFields(f, ['orgUnitId', 'employeeId', 'areaId', 'buildingType', 'managerId', 'leadId'])}${U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: f.roomId, all: f.buildingId ? 'Tất cả phòng' : 'Chọn tòa trước', options: (f.buildingId ? Q.roomsOf(f.buildingId) : []).map(r => [r.id, r.code]), attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Khách', input: U.select({ name: 'tenantId', value: f.tenantId, all: 'Tất cả khách', options: [...new Set(all.map(x => x.inv.tenantId))].map(id => [id, Q.tenant(id).name]).sort((a, b) => F.cmp(a[1], b[1])), attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Hạn thanh toán', input: U.select({ name: 'due', value: f.due, all: 'Tất cả', options: [['today', 'Đến hạn hôm nay'], ['week', 'Trong 7 ngày'], ['past', 'Đã quá hạn']], attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Mốc M1/M2/M3', input: U.select({ name: 'milestone', value: '', all: 'Tất cả (gắn mốc ở W4)', options: [], attrs: { 'data-on': 'f', disabled: true } }) })}${U.field({ label: 'Tuổi nợ', input: U.select({ name: 'age', value: f.age, all: 'Tất cả', options: [['0', 'Chưa quá hạn'], ['1-7', '1–7 ngày'], ['8-15', '8–15 ngày'], ['15+', 'Trên 15 ngày']], attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Trạng thái thu', input: U.select({ name: 'pay', value: f.pay, all: 'Tất cả', options: [['unpaid', 'Chưa thu'], ['partial', 'Thu một phần'], ['paid', 'Thu đủ']], attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Nhắc thanh toán', input: U.select({ name: 'reminded', value: f.reminded, all: 'Tất cả', options: [['yes', 'Đã nhắc'], ['no', 'Chưa nhắc']], attrs: { 'data-on': 'f' } }) })}</div></details>`], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.card({ title: 'Tổng hợp công nợ theo ' + ({ building: 'tòa', manager: 'quản lý', room: 'phòng', tenant: 'khách' }[f.group || 'building']) + ' (§12.13.1)', icon: 'layers', collapsible: true, collapseKey: 'ar-summary', actions: `<div class="seg sm">${[['building', 'Tòa'], ['manager', 'Quản lý'], ['room', 'Phòng'], ['tenant', 'Khách']].map(([k, l]) => `<button type="button" class="${(f.group || 'building') === k ? 'on' : ''}" data-act="group" data-g="${k}">${l}</button>`).join('')}</div>`, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>${({ building: 'Tòa', manager: 'Quản lý', room: 'Phòng', tenant: 'Khách' }[f.group || 'building'])}</th><th class="num">Hóa đơn</th><th class="num">Phải thu</th><th class="num">Đã thu</th><th class="num">Còn nợ</th><th class="num">Quá hạn</th><th class="num">Tỷ lệ thu</th></tr></thead><tbody>${Q.receivableSummary(all, f.group || 'building').slice(0, 15).map(g => `<tr><td><b>${esc(g.label)}</b></td><td class="num">${g.count}</td><td class="num">${F.vnd(g.total)}</td><td class="num">${F.vnd(g.paid)}</td><td class="num ${g.remaining ? 'red' : ''}">${F.vnd(g.remaining)}</td><td class="num">${F.vnd(g.overdue)}</td><td class="num">${F.pct(g.paid, g.total)}%</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Không có dữ liệu</td></tr>'}</tbody></table>` })}
    ${U.card({ title: `Danh sách công nợ <span class="muted" style="font-weight:400">(${rows.length})</span>`, actions: '<span id="bulk" class="row"></span>' + U.btn({ label: 'Bộ cột', icon: 'columns', cls: 'btn-outline', size: 'btn-sm', act: 'cols' }) + U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', size: 'btn-sm', act: 'export' }), body: null, id: 'tbl-card', attrs: 'data-guide="receivables-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const tbl = U.table(wrap, { rows, selectable: true, unit: 'khoản', rowKey: x => x.inv.id, rowHref: x => '#/invoices/' + x.inv.id, densityControl: true, sortKey: 'due', colPrefsKey: 'receivables', onSelect: (ids) => { const payable = ids.filter(id => Q.invRemaining(St.get('invoices', id)) > 0); root.querySelector('#bulk').innerHTML = ids.length ? `<span class="small muted">${ids.length} đã chọn</span>${U.btn({ label: 'Gửi nhắc Zalo', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-zalo', disabled: !payable.length })}${U.btn({ label: 'Xác nhận thu tiền' + (payable.length ? ' (' + payable.length + ')' : ''), icon: 'dollar', size: 'btn-sm', cls: 'btn-primary', act: 'bulk-pay', disabled: !payable.length, title: 'Thu đủ số còn lại kèm minh chứng' })}` : ''; }, cols: [
      { key: 'party', label: 'Khách / Hóa đơn', render: x => { const t = Q.tenant(x.inv.tenantId); return U.cell2(U.link('#/tenants/' + t.id, esc(t.name)), U.link('#/invoices/' + x.inv.id, esc(x.inv.code))); } },
      { key: 'room', label: 'Phòng / Tòa', render: x => U.cell2(U.link('#/rooms/' + x.inv.roomId, esc(Q.room(x.inv.roomId).code)), esc(Q.building(x.inv.buildingId).name)) },
      { key: 'total', label: 'Phải thu', num: true, render: x => F.vnd(x.inv.total) },
      { key: 'rem', label: 'Đã thu / Còn lại', num: true, sortable: true, sortVal: x => x.remaining, render: x => U.cell2(F.vnd(x.paid), `<b class="${x.remaining ? 'red' : 'green'}">Còn ${F.vnd(x.remaining)}</b>`) },
      { key: 'due', label: 'Hạn thanh toán', sortable: true, sortVal: x => x.inv.dueDate, render: x => F.date(x.inv.dueDate) },
      { key: 'od', label: 'Số ngày quá hạn', sortable: true, sortVal: x => x.overdueDays, render: x => x.overdueDays ? `<span class="red bold">${x.overdueDays} ngày</span>` : (x.remaining ? `<span class="muted">${F.daysUntil(x.inv.dueDate) === 0 ? '0 ngày' : '-'}</span>` : '-') },
      { key: 'status', label: 'Trạng thái', render: x => U.cell2(Q.invPayStatusW3(x.inv) === 'overpaid' ? Q.chip('invPay', 'overpaid') : Q.invPayChip(x.inv), x.reminded ? 'Đã nhắc' : 'Chưa nhắc') },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([x.remaining ? U.actBtn({ icon: 'dollar', label: 'Xác nhận thu tiền', act: 'pay-inv', tone: 'primary', attrs: { 'data-id': x.inv.id } }) : '', U.moreBtn(x.inv.id)]) }] });
    tbl.state.opts.cols.push({ key: 'ref', label: 'Mã tòa · phòng', render: x => U.link('#/rooms/' + x.inv.roomId, esc(F.roomRef(Q.building(x.inv.buildingId), Q.room(x.inv.roomId))), 'bold') }, { key: 'manager', label: 'Quản lý', render: x => esc(Q.userName(Q.building(x.inv.buildingId).managerId)) }, { key: 'invoice', label: 'Hóa đơn', render: x => U.link('#/invoices/' + x.inv.id, esc(x.inv.code)) });
    tbl.state.opts.presets = { doisoat: { label: 'Đối soát', cols: ['ref', 'invoice', 'manager', 'total', 'rem', 'due', 'od', 'status', 'actions'] } }; tbl.render();
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelectorAll('.filterbar')[0])) });
    root.querySelector('#rs').addEventListener('keydown', e => { if (e.key === 'Enter') TH.router.applyFilter(f, { s: e.target.value }); });
    U.bind(root, {
      group: (el) => { TH.router.replaceQuery(Object.assign({}, f, { group: el.dataset.g })); TH.router.refresh(); }, unidentified: () => Fm.unidentified(), pay: () => Fm.payment({}), 'pay-inv': (b) => Fm.confirmPayments({ invoiceIds: [b.dataset.id] }), 'bulk-pay': () => Fm.confirmPayments({ invoiceIds: tbl.selected() }), stab: (el) => { const v = el.dataset.key; TH.router.replaceQuery(Object.assign({}, f, { overdue: v === 'overdue' ? '1' : '', pay: ['partial', 'paid'].includes(v) ? v : '' })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); },
      'bulk-zalo': () => Fm.zaloQuick({ invoiceIds: tbl.selected(), eventKey: 'debt', title: 'Nhắc công nợ qua Zalo' }), more: (b) => TH.pages.invMenu(b, St.get('invoices', b.dataset.id)), cols: b => U.columnMenu(b, tbl, tbl.state.opts.cols),
      export: () => { F.download('cong-no-' + (f.period || 'all') + '.csv', U.tableCsv(tbl, rows), 'text/csv'); U.toast('ok', 'Đã xuất công nợ theo bộ cột đang chọn'); },
    });
    // Quick create 'Ghi nhận thu tiền' (#/receivables?create=payment): mở drawer ngay, bỏ query để refresh không mở lại
    if (q.create === 'payment') { TH.router.replaceQuery(Object.assign({}, f, { create: '' })); Fm.payment({}); }
  }, { menu: 'receivables', permission: 'payments.view' });

  /* ---------- Chi tiết khoản thu ---------- */
  TH.router.register('/payments/:id', (root, p) => {
    const pay = St.get('payments', p.id); if (!pay) { root.innerHTML = U.empty({ title: 'Không tìm thấy khoản thu' }); return; }
    const t = Q.tenant(pay.tenantId), r = Q.room(pay.roomId), b = Q.building(pay.buildingId), allocs = Q.payAllocs(pay.id); const allocTotal = F.sum(allocs, a => a.amount); const un = pay.amount - allocTotal; const kind = Q.paymentKind(pay);
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Thu tiền & công nợ', href: '#/receivables' }, { label: 'Chi tiết khoản thu' }]);
    const reversed = pay.status === 'reversed';
    const evidenceBody = `<div class="row gap12" style="border:1px solid var(--border);border-radius:10px;padding:10px"><div class="fic pdf" style="width:44px;height:44px;border-radius:10px;display:grid;place-items:center;background:var(--red-bg);color:var(--red);font-size:20px">${I('file-text')}</div><div class="grow"><b>${esc(pay.evidence || 'bien_lai_' + pay.code + '.pdf')}</b><div class="xs muted">PDF · 512 KB</div></div>${U.btn({ label: 'Xem trước', icon: 'eye', size: 'btn-xs', cls: 'btn-outline', act: 'preview' })}</div><div class="xs muted mt12 mb8">Tệp đính kèm khác</div><div class="file-list">${U.fileItem({ name: 'bien_lai_' + pay.code + '.pdf', size: '512 KB', date: pay.date }, U.iconBtn('download', 'dl', 'Tải'))}${U.fileItem({ name: 'sao_ke_' + pay.date.slice(8) + pay.date.slice(5, 7) + '.png', size: '1.2 MB', date: pay.date }, U.iconBtn('download', 'dl', 'Tải'))}</div>`;
    const historyBody = U.timeline([{ when: F.datetime(pay.createdAt), title: 'Tạo khoản thu', sub: Q.userName(pay.createdBy) + ' tạo khoản thu', color: 'blue', fill: true }, { when: F.datetime(pay.createdAt), title: 'Kiểm tra ghép', sub: 'Đối chiếu khách, hóa đơn và số tiền', color: 'blue' }, { when: F.datetime(pay.createdAt), title: 'Xác nhận ghi nhận', sub: Q.userName(pay.createdBy) + ' xác nhận ghi nhận', color: 'green', fill: true }, { when: F.datetime(pay.createdAt), title: 'Phân bổ vào hóa đơn', sub: 'Phân bổ ' + allocs.length + ' hóa đơn', color: 'blue' }, ...((pay.history || []).slice(1).map(h => ({ when: F.datetime(h.at), title: h.what.split(':')[0], sub: h.who + (h.what.includes(':') ? ' – ' + h.what.split(':').slice(1).join(':') : ''), color: /Hoàn tác/.test(h.what) ? 'red' : 'amber', fill: true })))]);
    const related = [{ key: 'evidence', title: 'Chứng từ & bằng chứng', icon: 'file-text', summary: pay.evidence ? 'Đã có chứng từ' : 'Chứng từ mô phỏng', meta: esc(pay.evidence || 'bien_lai_' + pay.code + '.pdf'), body: evidenceBody }, { key: 'history', title: 'Lịch sử xử lý', icon: 'history', summary: (4 + (pay.history || []).slice(1).length) + ' mốc xử lý', meta: reversed ? 'Khoản thu đã hoàn tác' : 'Đã ghi nhận và phân bổ', body: historyBody + U.note('info', 'Lưu ý', 'Mọi thay đổi, điều chỉnh liên quan đến khoản thu này sẽ được lưu lại trong lịch sử xử lý để đảm bảo tính minh bạch.') }];
    root.innerHTML = `${U.pageHead({ back: '#/receivables', title: 'Chi tiết khoản thu', sub: 'Xem thông tin chi tiết, phân bổ công nợ và lịch sử xử lý của khoản thu.', acts: [kind === 'unidentified' || (un > 0.5 && !reversed) ? U.btn({ label: kind === 'unidentified' ? 'Ghép khách / hóa đơn' : 'Phân bổ phần chưa dùng', icon: 'link', cls: 'btn-primary', act: 'match' }) : '', kind !== 'unidentified' && un > 0.5 && !reversed ? U.btn({ label: pay.advance ? 'Bỏ đánh dấu tạm ứng' : 'Đánh dấu tạm ứng', icon: 'bookmark', cls: 'btn-outline', act: 'advance' }) : '', U.btn({ label: 'Điều chỉnh', icon: 'pencil', cls: 'btn-outline', act: 'adjust', disabled: reversed || !TH.auth.can('adjustPayment'), title: TH.auth.can('adjustPayment') ? '' : 'Cần vai trò Admin/Kế toán' }), U.btn({ label: 'Hoàn tác ghi nhận', icon: 'undo', cls: 'btn-outline', act: 'reverse', disabled: reversed || !TH.auth.can('reversePayment'), title: TH.auth.can('reversePayment') ? '' : 'Cần vai trò Admin/Kế toán' }), U.btn({ label: 'Tải chứng từ', icon: 'download', cls: 'btn-primary', act: 'dl' })] })}
    ${kind === 'unidentified' ? U.note('warn', 'Tiền chưa xác định (Unidentified Receipt)', 'Nội dung CK: <strong>' + esc(pay.transferContent || '-') + '</strong>. Chưa khớp khách/phòng/hóa đơn – ghép sau khi xác minh (§4.15).') + '<div class="mb16"></div>' : kind === 'advance' || kind === 'overpaid' ? U.note('info', Q.label('paymentKind', kind), 'Còn ' + F.vnd(un) + ' chưa phân bổ – có thể phân bổ vào hóa đơn kỳ sau hoặc đánh dấu tạm ứng.') + '<div class="mb16"></div>' : ''}${reversed ? U.note('danger', 'Khoản thu đã hoàn tác', 'Lý do: ' + esc(pay.reverseReason || '') + ' – ' + F.datetime(pay.reversedAt) + '. Các hóa đơn đã được tính lại số còn nợ; dấu vết giữ nguyên (BR-22).') + '<div class="mb16"></div>' : ''}
    ${U.card({ cls: 'mb16', body: `<div class="grid grid-4" style="gap:20px">${[['Mã khoản thu', `<b>${esc(pay.code)}</b> ${Q.chip('payment', pay.adjusted && !reversed ? 'adjusted' : pay.status)} ${Q.chip('paymentKind', kind)}`, ''], ['Số tiền', `<b style="font-size:18px">${F.vnd(pay.amount)}</b> <span class="muted small">VND</span>`, ''], ['Ngày thu', `${I('calendar')} <b>${F.datetime(pay.createdAt && pay.createdAt.startsWith(pay.date) ? pay.createdAt : pay.date)}</b>`, ''], ['Phương thức', `${I('credit-card')} <b>${esc(pay.method)}</b>`, ''], ['Nguồn tham chiếu', `${I('landmark')} <b>${esc(pay.ref || '-')}</b>`, ''], ['Người nộp tiền', `${I('user')} <b>${esc(t.name || 'Chưa xác định')}</b><div class="xs muted">${esc(t.phone || '')}</div>`, ''], ['Phòng / Tòa nhà', `${I('home')} <b class="blue">${esc(r.code || '-')} / ${esc(b.name || '-')}</b>`, ''], ['Người tạo', `${I('user')} <b>${esc(Q.userName(pay.createdBy))}</b><div class="xs muted">${F.datetime(pay.createdAt)}</div>`, '']].map(([k, v]) => `<div><div class="xs muted" style="text-transform:uppercase;letter-spacing:.04em">${k}</div><div class="mt4">${v}</div></div>`).join('')}</div>` })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tiền nhận', value: F.vnd(pay.amount), cap: 'VND', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã phân bổ', value: F.vnd(allocTotal), cap: F.pct(allocTotal, pay.amount) + '%', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Chưa phân bổ', value: F.vnd(un), cap: F.pct(un, pay.amount) + '%', icon: 'alert-circle', tone: 'amber' })}${U.kpi({ label: 'Số hóa đơn liên quan', value: allocs.length, cap: 'hóa đơn', icon: 'receipt', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'payment-related', items: related, cls: 'mb16' })}<div class="side-stack">
      ${U.card({ title: 'Phân bổ công nợ', icon: 'clipboard-check', sub: 'Danh sách hóa đơn đã được phân bổ từ khoản thu này.', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Mã hóa đơn</th><th>Kỳ</th><th class="num">Phải thu (VND)</th><th class="num">Đã phân bổ (VND)</th><th class="num">Còn lại sau phân bổ (VND)</th><th>Trạng thái</th></tr></thead><tbody>${allocs.map((a, i) => { const inv = St.get('invoices', a.invoiceId); return `<tr><td>${i + 1}</td><td>${U.link('#/invoices/' + inv.id, inv.code)}</td><td>${F.periodLabel(inv.period)}</td><td class="num">${F.vnd(inv.total)}</td><td class="num">${F.vnd(a.amount)}</td><td class="num">${F.vnd(Q.invRemaining(inv))}</td><td>${Q.invPayChip(inv)}</td></tr>`; }).join('') || '<tr><td colspan="7" class="muted tc">Chưa phân bổ vào hóa đơn nào</td></tr>'}</tbody></table>`, footer: `<span>Tổng phân bổ</span><b style="font-size:15px">${F.vnd(allocTotal)} VND</b>` })}
      ${U.card({ title: 'Thông tin giao dịch', icon: 'landmark', body: `<div class="grid grid-2">${U.kv([['Ngân hàng nhận', esc(pay.bank || '-'), pay.bank ? 'Chi nhánh Hà Nội' : ''], ['Số tham chiếu', esc(pay.ref || '-')], ['Nội dung chuyển khoản', esc(pay.transferContent || '-')]], 'one')}${U.kv([['Nguồn ghi nhận', 'Khách thuê thanh toán'], ['Phương thức thanh toán', esc(pay.method)], ['Ghi chú', esc(pay.note || '-')]], 'one')}</div>` })}</div>`;
    U.bind(root, { match: () => Fm.matchPayment(pay), advance: () => { try { X.markAdvance(pay.id, !pay.advance); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } }, adjust: () => Fm.adjustPayment(pay), reverse: () => Fm.reversePayment(pay), dl: () => U.fakePdf('Bien lai ' + pay.code, ['Khách: ' + t.name, 'Số tiền: ' + F.vnd(pay.amount), 'Ngày: ' + F.date(pay.date), 'Phương thức: ' + pay.method, ...allocs.map(a => 'Phân bổ ' + St.get('invoices', a.invoiceId).code + ': ' + F.vnd(a.amount))]), preview: () => U.modal({ title: 'Xem trước chứng từ', body: `<div class="empty">${I('file-text')}<b>${esc(pay.evidence || 'bien_lai.pdf')}</b><p>Bản demo mô phỏng xem trước PDF. Bản thật hiển thị file thực tế đã upload.</p></div>` }) });
  }, { menu: 'receivables', permission: 'payments.view', resource: { type: 'payment' } });
})(window.TH);
