(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const canApprove = () => TH.auth.can('approveRefund');
  const deductionStatus = (rf, d) => {
    if (rf.status === 'refunded' || d.status === 'refunded') return U.chip('Đã hoàn', 'green');
    if (d.status === 'confirmed' || d.evidenceCount) return U.chip('Đã xác nhận', 'green');
    return U.chip('Chờ xác nhận', 'amber');
  };
  const rfMenu = (btn, rf) => { const items = [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/refunds/' + rf.id) }];
    if (TH.auth.can('refunds.prepare') && ['draft', 'rejected', 'needs_edit'].includes(rf.status)) items.push({ label: 'Sửa phương án', icon: 'pencil', onClick: () => TH.go('#/refunds/new?id=' + rf.id + '&step=3') }, { label: 'Gửi duyệt', icon: 'send', onClick: () => { X.submitRefund(rf.id); U.toast('ok', 'Đã gửi duyệt ' + rf.code); } });
    if (rf.status === 'pending' && canApprove()) items.push({ label: 'Duyệt', icon: 'check-circle', onClick: () => Fm.refundApprove(rf) }, { label: 'Từ chối', icon: 'x-circle', danger: true, onClick: () => Fm.refundReject(rf) });
    if (rf.status === 'approved' && TH.auth.can('refunds.pay')) items.push({ label: 'Ghi nhận đã hoàn', icon: 'banknote', onClick: () => Fm.refundPaid(rf) });
    if (rf.status === 'refunded' && TH.auth.can('zalo.send')) items.push({ label: 'Gửi Zalo "Đã hoàn cọc"', icon: 'send', onClick: () => sendRefundZalo(rf) });
    items.push('-', { label: 'Tải hồ sơ', icon: 'download', onClick: () => U.fakePdf('Ho so hoan coc ' + rf.code, ['Khách: ' + Q.tenant(rf.tenantId).name, 'Phòng: ' + Q.room(rf.roomId).code, 'Cọc: ' + F.vnd(rf.deposit), 'Khấu trừ: ' + F.vnd(rf.deductionsTotal), 'Hoàn: ' + F.vnd(rf.refundAmount)]) }); U.menu(btn, items); };
  const sendRefundZalo = (rf) => { const recips = X.buildRecipients('refund_done', { refundId: rf.id }); const tpl = St.one('zaloTemplates', t => t.eventKey === 'refund_done'); try { const b = X.createZaloBatch({ name: 'Thông báo hoàn cọc ' + rf.code, eventKey: 'refund_done', sourceKey: 'refund_done', templateId: tpl.id, recipients: recips, sendMode: 'now', key: 'rfz:' + rf.id }); U.toast(b.duplicate ? 'warn' : 'ok', b.duplicate ? 'Đã gửi trước đó' : 'Đã tạo đợt gửi ' + b.code); if (!b.duplicate) TH.go('#/zalo/batches/' + b.id); } catch (e) { U.toast('err', 'Không gửi được', e.message); } };
  /* ---------- Danh sách ---------- */
  TH.router.register('/refunds', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hoàn cọc' }]);
    const f = { s: q.s || '', areaId: q.areaId || '', buildingId: q.buildingId || '', opsId: q.opsId || '', leadId: q.leadId || '', status: q.status || '', period: q.period || '', handlerId: q.handlerId || '', reason: q.reason || '' }, scope = Q.scope({ period: q.period, areaId: q.areaId, buildingId: q.buildingId, opsId: q.opsId, leadId: q.leadId });
    const all = St.all('refunds');
    const rows = all.filter(r => (!f.s || F.norm(r.code + ' ' + Q.tenant(r.tenantId).name + ' ' + Q.room(r.roomId).code).includes(F.norm(f.s))) && scope.buildingIds.includes(r.buildingId) && (!f.status || (f.status === 'processing' ? ['pending', 'approved'].includes(r.status) : r.status === f.status)) && (!f.period || F.period(r.moveOutDate) === f.period) && (!f.handlerId || r.handlerId === f.handlerId) && (!f.reason || f.reason !== 'break' || (() => { const c = Q.contract(r.contractId); return c.actualEnd && c.actualEnd < c.end; })())).sort((a, b) => F.cmp(b.requestDate, a.requestDate));
    const cnt = (s) => all.filter(r => r.status === s).length;
    root.innerHTML = `${U.pageHead({ title: 'Hoàn cọc', sub: 'Theo dõi các yêu cầu hoàn cọc, khấu trừ và tiến độ xử lý.', acts: [U.btn({ label: 'Tạo yêu cầu', icon: 'plus', cls: 'btn-primary', act: 'new', attrs: { 'data-guide': 'refund-new' } }), U.btn({ label: 'Xuất danh sách', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Tìm theo mã, tên khách thuê, số phòng...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.refund).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kỳ trả phòng', input: U.select({ name: 'period', value: f.period, all: 'Tất cả thời gian', options: [...new Set(all.map(r => F.period(r.moveOutDate)))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người duyệt / xử lý', input: U.select({ name: 'handlerId', value: f.handlerId, all: 'Tất cả nhân viên', options: St.where('users', u => ['admin', 'accountant', 'ops'].includes(u.role)).map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) }), U.dimMore(f, ['areaId', 'opsId', 'leadId'])], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Chờ duyệt', value: cnt('pending'), cap: 'Đang chờ phê duyệt', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Đã duyệt', value: cnt('approved'), cap: 'Đã duyệt, chờ hoàn tiền', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Đã hoàn', value: cnt('refunded'), cap: 'Đã chuyển khoản cho khách', icon: 'banknote', tone: 'blue' })}${U.kpi({ label: 'Từ chối', value: cnt('rejected'), cap: 'Không đủ điều kiện hoàn cọc', icon: 'x-circle', tone: 'red' })}</div>
    ${U.relatedStrip({ id: 'refund-list-related', cls: 'mb16', items: [
      { key: 'process', title: 'Quy trình hoàn cọc', icon: 'compass', summary: '4 bước xử lý', meta: 'Từ tạo yêu cầu đến hoàn tất', body: `<div class="steps">${[['Tạo yêu cầu', 'Nhập thông tin, đề xuất số tiền hoàn và khấu trừ (nếu có)'], ['Phê duyệt', 'Kế toán/Admin xem xét và phê duyệt yêu cầu (FR-FIN-07)'], ['Thực hiện hoàn tiền', 'Chuyển khoản cho khách thuê, ghi nhận kèm bằng chứng'], ['Hoàn tất', 'Cập nhật trạng thái và lưu hồ sơ; phòng vẫn cần xác nhận dọn xong (BR-02)']].map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` },
      { key: 'status-meaning', title: 'Ý nghĩa trạng thái', icon: 'info', summary: (TH.phase.on(2) ? 6 : 5) + ' trạng thái hồ sơ', meta: 'Theo dõi từ dự thảo đến hoàn tất', body: `<div class="legend-list">${[['draft', 'Yêu cầu đang soạn thảo, chưa gửi duyệt.'], ['pending', 'Đã gửi yêu cầu, chờ phê duyệt bởi kế toán/quản lý.']].concat(TH.phase.on(2) ? [['needs_edit', 'Người duyệt yêu cầu chỉnh sửa phương án; Vận hành sửa và gửi duyệt lại.']] : []).concat([['approved', 'Đã được phê duyệt, chờ thực hiện hoàn tiền.'], ['refunded', 'Đã chuyển khoản cho khách, hoàn tất quy trình.'], ['rejected', 'Không đủ điều kiện hoàn cọc hoặc bị từ chối.']]).map(([k, t]) => `<div class="it">${Q.chip('refund', k)}<span>${t}</span></div>`).join('')}</div>${U.note('info', 'Lưu ý', 'Các khoản khấu trừ cần có chứng từ hợp lệ (hóa đơn, biên bản bàn giao, ...) và được phê duyệt trước khi hoàn tiền. Khấu hao cố định 200.000đ/phòng (BR-12).')}` }
    ] })}
    ${U.card({ title: `Danh sách hoàn cọc <span class="muted" style="font-weight:400">(${rows.length} yêu cầu)</span>`, actions: U.btn({ label: 'Bộ cột', icon: 'columns', size: 'btn-sm', cls: 'btn-outline', act: 'cols' }), body: null, id: 'tbl-card', attrs: 'data-guide="refunds-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const tbl = U.table(wrap, { rows, selectable: true, unit: 'yêu cầu', colPrefsKey: 'refunds', cols: [
      { key: 'code', label: 'Mã hoàn cọc', sortable: true, render: r => U.link('#/refunds/' + r.id, esc(r.code), 'bold') }, { key: 't', label: 'Khách thuê', render: r => esc(Q.tenant(r.tenantId).name) }, { key: 'room', label: 'Phòng / Tòa', render: r => esc(Q.room(r.roomId).code) + ' / ' + esc(Q.building(r.buildingId).name) },
      { key: 'requestDate', label: 'Ngày đề nghị', sortable: true, render: r => F.date(r.requestDate) }, { key: 'deposit', label: 'Cọc giữ (VND)', num: true, render: r => F.vnd(r.deposit) }, { key: 'ded', label: 'Khấu trừ (VND)', num: true, render: r => `<span class="red">${F.vnd(r.deductionsTotal)}</span>` }, { key: 'refundAmount', label: 'Đề nghị hoàn (VND)', num: true, sortable: true, render: r => `<span class="green bold">${F.vnd(r.refundAmount)}</span>` },
      { key: 'status', label: 'Trạng thái', sortable: true, render: r => Q.chip('refund', r.status) }, { key: 'h', label: 'Người xử lý', render: r => r.handlerId ? esc(Q.userName(r.handlerId)) : '-' },
      { key: 'actions', label: 'Thao tác', render: r => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': r.id } }), U.moreBtn(r.id)]) }] });
    const ded = (r, code) => F.sum(Q.refundDeductions(r.id).filter(d => d.groupCode === code), d => d.amount || 0);
    tbl.state.opts.cols.push({ key: 'ref', label: 'Mã tòa · phòng', render: r => esc(F.roomRef(Q.building(r.buildingId), Q.room(r.roomId))) }, { key: 'refund', label: 'Tiền hoàn', num: true, render: r => F.vnd(r.refundAmount) }, { key: 'ded_KH', label: 'Khấu hao', num: true, render: r => F.vnd(ded(r, 'KH')) }, { key: 'ded_SC', label: 'Sửa chữa', num: true, render: r => F.vnd(ded(r, 'SC')) }, { key: 'ded_VS', label: 'Vệ sinh', num: true, render: r => F.vnd(ded(r, 'VS')) }, { key: 'ded_KHAC', label: 'Chi khác', num: true, render: r => F.vnd(ded(r, 'KHAC')) });
    tbl.state.opts.presets = { doisoat: { label: 'Đối soát', cols: ['ref', 'deposit', 'refund', 'ded_KH', 'ded_SC', 'ded_VS', 'ded_KHAC', 'status', 'actions'] } }; tbl.render();
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { new: () => TH.go('#/refunds/new'), stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { status: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => TH.go('#/refunds/' + b.dataset.id), more: (b) => rfMenu(b, St.get('refunds', b.dataset.id)), cols: b => U.columnMenu(b, tbl, tbl.state.opts.cols), export: () => { F.download('hoan-coc.csv', U.tableCsv(tbl, rows), 'text/csv'); U.toast('ok', 'Đã xuất danh sách theo bộ cột đang chọn'); } });
  }, { menu: 'refunds', permission: 'refunds.view' });

  /* ---------- Lập phương án (wizard) ---------- */
  const RSTEPS = [{ title: 'Chọn hợp đồng', sub: 'Chọn hợp đồng cần hoàn cọc' }, { title: 'Kiểm tra hiện trạng', sub: 'Rà soát tình trạng phòng' }, { title: 'Khấu trừ & tính toán', sub: 'Lập các khoản khấu trừ' }, { title: 'Review & gửi duyệt', sub: 'Kiểm tra và gửi phê duyệt' }];
  const GROUPS = ['Công nợ', 'Khấu hao', 'Dịch vụ', 'Sửa chữa', 'Khác'];
  TH.router.register('/refunds/new', (root, p, q) => {
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hoàn cọc', href: '#/refunds' }, { label: 'Lập phương án hoàn cọc' }]);
    let rf = q.id ? St.get('refunds', q.id) : (q.contract ? St.one('refunds', r => r.contractId === q.contract && ['draft', 'rejected'].includes(r.status)) : null);
    const contractId = rf ? rf.contractId : q.contract || ''; const c = contractId ? Q.contract(contractId) : null;
    const step = Number(q.step || (c ? 3 : 1));
    const eligible = St.where('contracts', x => x.status === 'ended' && !x.renewedToId && !St.one('refunds', r => r.contractId === x.id && !['draft', 'rejected'].includes(r.status))).sort((a, b) => F.cmp(b.actualEnd || b.end, a.actualEnd || a.end));
    const go = (extra) => { TH.router.replaceQuery(Object.assign({ id: rf ? rf.id : '', contract: contractId, step }, extra)); TH.router.refresh(); };
    let main = '';
    if (step === 1 || !c) main = U.card({ title: 'Bước 1 – Chọn hợp đồng cần hoàn cọc', icon: 'file-text', sub: 'Chỉ hiện hợp đồng Đã kết thúc và chưa có hồ sơ hoàn cọc đang xử lý', body: U.field({ label: 'Hợp đồng', input: U.select({ name: 'contractId', value: contractId, placeholder: 'Chọn hợp đồng', options: eligible.map(x => [x.id, x.code + ' – ' + Q.tenant(x.tenantId).name + ' – ' + Q.room(x.roomId).code + ' – trả phòng ' + F.date(x.actualEnd || x.end)]), attrs: { 'data-on': 'pick' } }) }) + (eligible.length ? '' : U.note('warn', 'Không có hợp đồng đủ điều kiện', 'Kết thúc một hợp đồng tại Vận hành → Hợp đồng để lập hoàn cọc.')) }) + `<div class="wz-foot"><span></span>${U.btn({ label: 'Tiếp tục →', cls: 'btn-primary', act: 'to2', disabled: !c })}</div>`;
    const t = c ? Q.tenant(c.tenantId) : null, room = c ? Q.room(c.roomId) : null;
    const debt = c ? F.sum(St.where('invoices', i => i.contractId === c.id && i.docStatus !== 'draft' && i.docStatus !== 'cancelled'), i => Q.invRemaining(i)) : 0;
    const infoCard = c ? U.card({ title: 'Thông tin hợp đồng', icon: 'file-text', cls: 'mb16', body: `<div class="grid grid-3" style="gap:14px">${[['Mã hợp đồng', `<b class="blue">${esc(c.code)}</b> ${U.chip('Đã trả phòng', 'green')}`], ['Khách thuê', `<b>${esc(t.name)}</b><div class="xs muted">${esc(t.phone)}</div>`], ['Phòng', `<b>${esc(room.code)}</b>`], ['Tòa nhà', `<b>${esc(Q.building(c.buildingId).name)}</b>`], ['Ngày trả phòng', `${I('calendar')} <b>${F.date(c.actualEnd || c.end)}</b>`], ['Tiền cọc ban đầu', `<b>${F.vnd(c.deposit)} VND</b>`]].map(([k, v]) => `<div><div class="xs muted">${k}</div><div class="mt4">${v}</div></div>`).join('')}</div>` }) : '';
    let deds = rf ? Q.refundDeductions(rf.id).map(d => Object.assign({}, d)) : Q.refundDefaults();
    const insp = rf && rf.inspection && Object.keys(rf.inspection).length ? rf.inspection : { wall: 'ok', furniture: 'minor', utilities: 'ok', devices: 'ok' };
    const offsetDebt = rf ? !!rf.offsetDebt : false;
    const dedRows = () => deds.map((d, i) => `<tr><td>${i + 1}</td><td>${U.select({ name: 'g_' + i, value: d.group, cls: 'sm', options: GROUPS })}</td><td>${U.input({ name: 'd_' + i, value: d.desc, cls: 'sm', placeholder: 'Mô tả' })}</td><td><input class="inp sm tr" data-money name="a_${i}" value="${F.vnd(d.amount)}" style="width:120px"></td><td>${d.evidenceCount ? U.btn({ label: 'Xem (' + d.evidenceCount + ')', icon: 'image', size: 'btn-xs', cls: 'btn-outline', act: 'ev', attrs: { 'data-i': i } }) : U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-xs', cls: 'btn-outline', act: 'add-ev', attrs: { 'data-i': i } })}</td><td>${U.chip(d.evidenceCount ? 'Đã xác nhận' : 'Chờ xác nhận', d.evidenceCount ? 'green' : 'amber')}</td><td>${U.iconBtn('trash', 'rm-ded', 'Xóa', { 'data-i': i }, 'red')}</td></tr>`).join('');
    const calc = () => { const ded = F.sum(deds, d => F.num(d.amount)); const dv = offsetDebt ? debt : 0; return { ded, dv, refund: Math.max(0, (c ? c.deposit : 0) - ded - dv), exceeds: ded + dv > (c ? c.deposit : 0) }; };
    if (step === 2 && c) main = infoCard + U.card({ title: 'Biên bản kiểm tra hiện trạng', icon: 'clipboard-check', sub: 'Tick hạng mục và ghi nhận ảnh hiện trạng khi nhận lại phòng', body: `<div class="inspect-tiles" id="insp">${[['wall', 'Tường'], ['furniture', 'Nội thất'], ['utilities', 'Điện nước'], ['devices', 'Thiết bị']].map(([k, l]) => `<div class="inspect-tile ${insp[k] === 'minor' ? 'warn' : 'on'}" data-act="insp" data-k="${k}"><input type="checkbox" checked hidden><div><b>${l}</b><small>${insp[k] === 'minor' ? 'Có hư hỏng nhỏ' : insp[k] === 'bad' ? 'Hư hỏng nặng' : (k === 'devices' ? 'Hoạt động tốt' : 'Bình thường')}</small></div></div>`).join('')}</div><div class="xs muted mt8">Nhấn để đổi: Bình thường → Hư hỏng nhỏ → Hư hỏng nặng</div><div class="mt16 small bold">Hình ảnh hiện trạng</div><div class="photo-grid mt8"><div class="photo"></div><div class="photo"><button data-act="noop">${I('trash')}</button></div><div class="photo"><button data-act="noop">${I('trash')}</button></div><div class="photo add" data-act="add-photo">${I('plus')} Thêm ảnh<br><span class="xs muted">JPG, PNG (tối đa 5MB)</span></div></div>` }) + `<div class="wz-foot">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: 'to1' })}${U.btn({ label: 'Tiếp tục khấu trừ →', cls: 'btn-primary', act: 'to3' })}</div>`;
    if (step === 3 && c) { const k = calc(); main = infoCard + `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tiền cọc ban đầu', value: F.vnd(c.deposit), cap: 'Theo hợp đồng', icon: 'shield', tone: 'amber' })}${U.kpi({ label: 'Công nợ còn lại', value: F.vnd(debt), cap: debt ? 'Chưa thanh toán' : 'Đã thu đủ', icon: 'receipt', tone: 'blue' })}${U.kpi({ label: 'Khấu trừ dự kiến', value: `<span id="k-ded">${F.vnd(k.ded)}</span>`, cap: `Tổng <span id="k-n">${deds.length}</span> khoản`, icon: 'minus-circle', tone: 'red' })}${U.kpi({ label: 'Số tiền hoàn', value: `<span id="k-ref" class="green">${F.vnd(k.refund)}</span>`, cap: 'Dự kiến hoàn cho khách', icon: 'check-circle', tone: 'green' })}</div>
      ${U.card({ title: 'Chi tiết khấu trừ', icon: 'list', actions: '<span class="small muted">Đơn vị: VND</span>', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact editable"><thead><tr><th>#</th><th>Nhóm</th><th>Mô tả</th><th class="num">Số tiền (VND)</th><th>Bằng chứng</th><th>Trạng thái</th><th></th></tr></thead><tbody id="ded-body">${dedRows()}</tbody></table></div><div style="padding:10px 0 4px">${U.btn({ label: 'Thêm dòng khấu trừ', icon: 'plus', cls: 'btn-dashed', size: 'btn-sm', act: 'add-ded' })}</div><div class="row gap12 mt8">${U.check({ name: 'offsetDebt', label: `Bù trừ công nợ còn lại (${F.vnd(debt)} đ) vào tiền cọc`, checked: offsetDebt, attrs: { 'data-on': 'offset' } })}</div><div class="xs muted mt4">${I('info')} Mặc định KHÔNG bù trừ công nợ vào cọc (OI-07 chưa chốt). Các khoản phí khấu trừ có thể được cấu hình trong danh mục phí và sẽ tự động gợi ý theo hiện trạng.</div>` })}
      <div class="wz-foot">${U.btn({ label: '← Quay lại hiện trạng', cls: 'btn-ghost', act: 'to2' })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${U.btn({ label: 'Review & gửi duyệt →', cls: 'btn-primary', act: 'to4', attrs: { 'data-guide': 'refund-review' } })}</div></div>`; }
    if (step === 4 && c && rf) { const k = Q.refundCompute(rf); const dd = Q.refundDeductions(rf.id); main = infoCard + U.card({ title: 'Review phương án ' + esc(rf.code), icon: 'clipboard-check', actions: Q.chip('refund', rf.status), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Nhóm</th><th>Mô tả</th><th class="num">Số tiền</th><th>Bằng chứng</th></tr></thead><tbody>${dd.map(d => `<tr><td>${esc(d.group)}</td><td>${esc(d.desc)}</td><td class="num">${F.vnd(d.amount)}</td><td>${d.evidenceCount ? U.chip(d.evidenceCount + ' tệp', 'green') : U.chip('Thiếu', 'red')}</td></tr>`).join('')}</tbody></table><div class="sum-box green" style="margin:12px 18px;border-radius:10px"><div class="it"><span>Tiền cọc</span><b>${F.vnd(rf.deposit)}</b></div><div class="it"><span>(-) Tổng khấu trừ</span><b class="red">${F.vnd(k.ded)}</b></div><div class="it"><span>(-) Bù trừ công nợ</span><b class="red">${F.vnd(k.debt)}</b></div><div class="it" style="border-top:1px solid var(--green-bg);padding-top:8px"><span class="bold">= Số tiền hoàn</span><b class="green" style="font-size:20px">${F.vnd(k.refund)}</b></div></div>${rf.exceeds ? U.note('danger', 'Khấu trừ vượt tiền cọc', 'Không thể gửi duyệt – xử lý theo OI-07.') : ''}` }) + `<div class="wz-foot">${U.btn({ label: '← Sửa khấu trừ', cls: 'btn-ghost', act: 'to3' })}<div class="row">${U.btn({ label: 'Giữ ở Nháp', cls: 'btn-outline', act: 'keep' })}${U.btn({ label: 'Gửi duyệt hoàn cọc', icon: 'send', cls: 'btn-primary', act: 'submit', disabled: rf.exceeds, attrs: { 'data-guide': 'refund-submit' } })}</div></div>`; }
    const side = c ? `<aside class="side-stack">${U.card({ title: 'Tóm tắt hoàn cọc', icon: 'coins', body: `<div id="sum-box">${sumBox()}</div>` })}${U.card({ title: 'Người duyệt', icon: 'user-check', body: U.field({ label: 'Chọn người duyệt', req: true, input: U.select({ name: 'approver', value: rf ? rf.approverRole : 'Kế toán trưởng', options: ['Kế toán trưởng', 'Quản trị viên'] }), help: 'Phương án sẽ được gửi đến người duyệt để phê duyệt. Chỉ Admin/Kế toán được duyệt (FR-FIN-07).' }) })}${U.card({ title: 'Tài liệu đính kèm', icon: 'folder', body: `<div class="file-list mb8">${['Bien_ban_hien_trang.pdf|2.3 MB', 'Hoa_don_sua_chua.jpg|1.1 MB', 'Bao_gia_ve_sinh.pdf|0.8 MB'].map(x => { const [n, s] = x.split('|'); return U.fileItem({ name: n, size: s, date: F.today() }, U.iconBtn('trash', 'noop', 'Xóa')); }).join('')}</div>${U.dropzone({ name: 'rfiles', hint: 'Hỗ trợ PDF, JPG, PNG (tối đa 10MB)' })}` })}</aside>` : '';
    function sumBox() { const k = calc(); return `${U.kv([['Tiền cọc ban đầu', F.vnd(c.deposit)], ['(-) Công nợ còn lại', `<span class="red">${F.vnd(k.dv)}</span>`], ['(-) Tổng khấu trừ', `<span class="red">${F.vnd(k.ded)}</span>`]], 'one')}<div class="hl-row green mt8" style="flex-direction:column;align-items:flex-start;gap:2px"><span>= Số tiền hoàn</span><span style="font-size:22px">${F.vnd(k.refund)} VND</span></div><div class="xs muted mt8">Bằng chữ: ${F.words(k.refund)}</div>${k.exceeds ? '<div class="xs red mt4">Khấu trừ vượt cọc – không thể gửi duyệt (OI-07)</div>' : ''}`; }
    root.innerHTML = `${U.pageHead({ title: 'Lập phương án hoàn cọc', sub: 'Tạo phương án hoàn cọc cho khách thuê dựa trên hiện trạng và các khoản cần khấu trừ.' })}${U.wizard(RSTEPS, step - 1)}<div class="two-col"><div>${main}</div>${side}</div>`;
    U.onInput(root); U.bindDropzones(root);
    const readDeds = () => { const v = U.formData(root); deds = deds.map((d, i) => Object.assign({}, d, { group: v['g_' + i] || d.group, desc: v['d_' + i] ?? d.desc, amount: F.num(v['a_' + i]) })); return deds; };
    const refreshCalc = () => { readDeds(); const k = calc(); const s = (id, v) => { const el = root.querySelector(id); if (el) el.textContent = v; }; s('#k-ded', F.vnd(k.ded)); s('#k-ref', F.vnd(k.refund)); s('#k-n', deds.length); const sb = root.querySelector('#sum-box'); if (sb) sb.innerHTML = sumBox(); };
    root.addEventListener('input', refreshCalc);
    const saveDraft = () => { readDeds(); const v = U.formData(root); return X.saveRefund({ id: rf ? rf.id : undefined, contractId, deductions: deds, offsetDebt: !!v.offsetDebt, approverRole: v.approver, inspection: insp, moveOutDate: c.actualEnd || c.end }); };
    U.onChange(root, { pick: (el) => { TH.router.replaceQuery({ contract: el.value, step: 1 }); TH.router.refresh(); }, offset: (el) => { rf = saveDraft(); TH.router.replaceQuery({ id: rf.id, contract: contractId, step: 3 }); TH.router.refresh(); } });
    U.bind(root, {
      to1: () => go({ step: 1 }), to2: () => { try { rf = saveDraft(); TH.router.replaceQuery({ id: rf.id, contract: contractId, step: 2 }); TH.router.refresh(); } catch (e) { go({ step: 2 }); } }, to3: () => { try { rf = saveDraft(); TH.router.replaceQuery({ id: rf.id, contract: contractId, step: 3 }); TH.router.refresh(); } catch (e) { go({ step: 3 }); } }, noop: () => U.toast('info', 'Demo', 'Ảnh/tệp mô phỏng'),
      insp: (el) => { const k = el.dataset.k; insp[k] = insp[k] === 'ok' ? 'minor' : insp[k] === 'minor' ? 'bad' : 'ok'; el.className = 'inspect-tile ' + (insp[k] === 'ok' ? 'on' : insp[k] === 'minor' ? 'warn' : ''); el.querySelector('small').textContent = insp[k] === 'ok' ? 'Bình thường' : insp[k] === 'minor' ? 'Có hư hỏng nhỏ' : 'Hư hỏng nặng'; if (insp[k] !== 'ok' && !deds.some(d => d.group === 'Sửa chữa' && d.amount > 0)) U.toast('info', 'Gợi ý', 'Thêm dòng Sửa chữa ở bước Khấu trừ kèm bằng chứng'); },
      'add-photo': () => U.toast('ok', 'Đã thêm ảnh hiện trạng (mô phỏng)'),
      'add-ded': () => { readDeds(); deds.push({ group: 'Khác', desc: '', amount: 0, evidenceCount: 0, status: 'pending' }); root.querySelector('#ded-body').innerHTML = dedRows(); refreshCalc(); }, 'rm-ded': (b) => { readDeds(); deds.splice(Number(b.dataset.i), 1); root.querySelector('#ded-body').innerHTML = dedRows(); refreshCalc(); },
      'add-ev': (b) => { readDeds(); const d = deds[Number(b.dataset.i)]; d.evidenceCount = 1; d.status = 'confirmed'; root.querySelector('#ded-body').innerHTML = dedRows(); refreshCalc(); U.toast('ok', 'Đã gắn bằng chứng (mô phỏng file)'); }, ev: (b) => U.modal({ title: 'Bằng chứng khấu trừ', size: 'sm', body: `<div class="photo-grid">${'<div class="photo"></div>'.repeat(deds[Number(b.dataset.i)].evidenceCount || 1)}</div><p class="small muted mt12">Ảnh/hóa đơn mô phỏng cho mục đích demo.</p>` }),
      draft: () => { try { rf = saveDraft(); U.toast('ok', 'Đã lưu nháp ' + rf.code); TH.router.replaceQuery({ id: rf.id, contract: contractId, step: 3 }); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      to4: () => { try { rf = saveDraft(); TH.router.replaceQuery({ id: rf.id, contract: contractId, step: 4 }); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      keep: () => { U.toast('ok', 'Hồ sơ ' + rf.code + ' ở trạng thái Nháp'); TH.go('#/refunds/' + rf.id); },
      submit: async () => { if (await U.confirm({ title: 'Gửi duyệt hoàn cọc ' + rf.code + '?', text: 'Đề nghị hoàn ' + F.vnd(rf.refundAmount) + ' đ. Hồ sơ chuyển Chờ duyệt; Admin/Kế toán sẽ duyệt hoặc từ chối.', ok: 'Gửi duyệt' })) { try { X.submitRefund(rf.id); U.toast('ok', 'Đã gửi duyệt ' + rf.code); TH.go('#/refunds/' + rf.id); } catch (e) { U.toast('err', 'Không gửi được', e.message); } } },
    });
  }, { menu: 'refunds', permission: 'refunds.prepare', noAutoRefresh: true });

  /* ---------- Chi tiết / duyệt ---------- */
  TH.router.register('/refunds/:id', (root, p) => {
    const rf = St.get('refunds', p.id); if (!rf) { root.innerHTML = U.empty({ title: 'Không tìm thấy hồ sơ' }); return; }
    const t = Q.tenant(rf.tenantId), room = Q.room(rf.roomId), c = Q.contract(rf.contractId), dd = Q.refundDeductions(rf.id), k = Q.refundCompute(rf);
    TH.router.crumb([{ label: 'Tài chính' }, { label: 'Hoàn cọc', href: '#/refunds' }, { label: rf.code }]);
    const acts = [];
    if (['draft', 'rejected', 'needs_edit'].includes(rf.status)) acts.push(U.btn({ label: 'Sửa phương án', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Gửi duyệt', icon: 'send', cls: 'btn-primary', act: 'submit' }));
    if (rf.status === 'pending') acts.push(U.btn({ label: 'Từ chối', icon: 'x-circle', cls: 'btn-danger', act: 'reject', disabled: !canApprove(), title: canApprove() ? '' : 'Chỉ Admin/Kế toán được từ chối (FR-FIN-07)' }), U.btn({ label: 'Duyệt hoàn cọc', icon: 'check-circle', cls: 'btn-primary', act: 'approve', disabled: !canApprove(), title: canApprove() ? '' : 'Chỉ Admin/Kế toán được duyệt (FR-FIN-07)', attrs: { 'data-guide': 'refund-approve' } }));
    if (rf.status === 'approved') acts.push(U.btn({ label: 'Ghi nhận đã hoàn', icon: 'banknote', cls: 'btn-primary', act: 'paid', disabled: !TH.auth.can('recordRefundPaid'), attrs: { 'data-guide': 'refund-paid' } }));
    if (rf.status === 'refunded') acts.push(U.btn({ label: 'Gửi Zalo "Đã hoàn cọc"', icon: 'send', cls: 'btn-outline', act: 'zalo' }), room.status === 'cleaning' ? U.btn({ label: 'Xác nhận dọn xong phòng', icon: 'check', cls: 'btn-primary', act: 'clean' }) : '');
    acts.push(U.btn({ label: 'Tải hồ sơ', icon: 'download', cls: 'btn-outline', act: 'dl' }), U.iconBtn('more', 'more', 'Thêm', {}, 'bordered'));
    const tl = [{ when: F.date(rf.requestDate), title: 'Tạo hồ sơ', sub: Q.userName(rf.handlerId), color: 'blue', fill: true }];
    if (rf.submittedAt || rf.status !== 'draft') tl.push({ when: rf.submittedAt ? F.datetime(rf.submittedAt) : F.date(rf.requestDate), title: 'Gửi duyệt', sub: 'Chờ ' + rf.approverRole, color: 'amber', fill: true });
    if (rf.status === 'rejected') tl.push({ when: F.datetime(rf.rejectedAt), title: 'Từ chối', sub: rf.rejectReason, color: 'red', fill: true });
    if (rf.approvedAt) tl.push({ when: F.datetime(rf.approvedAt), title: 'Đã duyệt', sub: Q.userName(rf.approvedBy) + ' – ' + F.vnd(rf.approvedAmount || rf.refundAmount), color: 'green', fill: true });
    if (rf.status === 'refunded') tl.push({ when: F.date(rf.paidDate), title: 'Đã hoàn tiền', sub: rf.paidMethod + ' · ' + (rf.paidRef || '') + ' · ' + rf.paidEvidence, color: 'green', fill: true });
    const refundFiles = [...new Set([...(rf.files && rf.files.length ? rf.files : ['Bien_ban_hien_trang.pdf']), ...(rf.paidEvidence ? [rf.paidEvidence] : [])])];
    const related = [
      { key: 'summary', title: 'Tóm tắt hoàn cọc', icon: 'coins', summary: F.vnd(k.refund) + ' VND', meta: Q.chip('refund', rf.status), body: `${U.kv([['Tiền cọc ban đầu', F.vnd(rf.deposit)], ['(-) Công nợ bù trừ', `<span class="red">${F.vnd(k.debt)}</span>`], ['(-) Tổng khấu trừ', `<span class="red">${F.vnd(k.ded)}</span>`]], 'one')}<div class="hl-row green mt8" style="flex-direction:column;align-items:flex-start;gap:2px"><span>= Số tiền hoàn</span><span style="font-size:22px">${F.vnd(k.refund)} VND</span></div><div class="xs muted mt8">Bằng chữ: ${F.words(k.refund)}</div>` },
      { key: 'approver', title: 'Người duyệt', icon: 'user-check', summary: rf.approvedBy ? esc(Q.userName(rf.approvedBy)) : esc(rf.approverRole), meta: rf.approvedAt ? F.datetime(rf.approvedAt) : 'Chưa phê duyệt', body: U.kv([['Cấp duyệt', esc(rf.approverRole)], ['Người duyệt', rf.approvedBy ? esc(Q.userName(rf.approvedBy)) : '-'], ['Thời điểm', rf.approvedAt ? F.datetime(rf.approvedAt) : '-'], ['Người lập', esc(Q.userName(rf.handlerId))]], 'one') },
      { key: 'progress', title: 'Tiến trình', icon: 'history', summary: tl.length + ' mốc xử lý', meta: Q.chip('refund', rf.status), body: U.timeline(tl) },
      { key: 'documents', title: 'Tài liệu đính kèm', icon: 'folder', summary: refundFiles.length + ' tài liệu', meta: rf.paidEvidence ? 'Đã có bằng chứng hoàn tiền' : 'Hồ sơ hoàn cọc', body: `<div class="file-list">${(rf.files && rf.files.length ? rf.files : ['Bien_ban_hien_trang.pdf']).map(n => U.fileItem({ name: n, size: '2.3 MB', date: rf.requestDate }, U.iconBtn('download', 'dl', 'Tải'))).join('')}${rf.paidEvidence ? U.fileItem({ name: rf.paidEvidence, size: '0.4 MB', date: rf.paidDate }, U.iconBtn('download', 'dl', 'Tải')) : ''}</div>` }
    ];
    root.innerHTML = `${U.pageHead({ back: '#/refunds', title: esc(rf.code), chips: ' ' + Q.chip('refund', rf.status, 'lg'), sub: `${esc(t.name)} • ${esc(room.code)} - ${esc(Q.building(rf.buildingId).name)} • Hợp đồng ${U.link('#/contracts/' + c.id, c.code)} • Trả phòng ${F.date(rf.moveOutDate)}`, acts })}
    ${rf.status === 'rejected' ? U.note('danger', 'Hồ sơ bị từ chối – cần chỉnh sửa', esc(rf.rejectReason) + ' (' + F.datetime(rf.rejectedAt) + ')') + '<div class="mb16"></div>' : ''}
    ${rf.status === 'approved' ? U.note('info', 'Đã duyệt – chưa chuyển tiền', 'Duyệt và chi là hai hành động tách biệt. Ghi nhận đã hoàn kèm bằng chứng khi hoàn tiền thực tế (FR-FIN-07).') + '<div class="mb16"></div>' : ''}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tiền cọc', value: F.vnd(rf.deposit), cap: 'Theo hợp đồng', icon: 'shield', tone: 'amber' })}${U.kpi({ label: 'Công nợ còn lại', value: F.vnd(Q.contractDebt(rf.contractId)), cap: (rf.offsetDebt ? 'Đã bù trừ vào cọc' : 'Không bù trừ (OI-07)') + (Math.abs(Q.contractDebt(rf.contractId) - (rf.debt || 0)) > 1 ? ' · lúc lập hồ sơ: ' + F.vnd(rf.debt) : ''), icon: 'receipt', tone: 'blue' })}${U.kpi({ label: 'Tổng khấu trừ', value: F.vnd(k.ded), cap: dd.length + ' khoản', icon: 'minus-circle', tone: 'red' })}${U.kpi({ label: rf.status === 'refunded' ? 'Đã hoàn' : 'Số tiền hoàn', value: F.vnd(k.refund), cap: rf.status === 'refunded' ? 'Ngày ' + F.date(rf.paidDate) : 'Dự kiến hoàn cho khách', icon: 'check-circle', tone: 'green', valueCls: 'green' })}</div>
    ${U.relatedStrip({ id: 'refund-detail-related', items: related, cls: 'mb16' })}<div class="side-stack">
      ${U.card({ title: 'Chi tiết khấu trừ', icon: 'list', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Nhóm</th><th>Mô tả</th><th class="num">Số tiền (VND)</th><th>Bằng chứng</th><th>Trạng thái</th></tr></thead><tbody>${dd.map((d, i) => `<tr><td>${i + 1}</td><td>${esc(d.group)}</td><td>${esc(d.desc)}</td><td class="num">${F.vnd(d.amount)}</td><td>${d.evidenceCount ? I('image') + ' ' + d.evidenceCount + ' tệp' : '-'}</td><td>${deductionStatus(rf, d)}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Không khấu trừ</td></tr>'}</tbody><tfoot><tr><td colspan="3">Tổng khấu trừ</td><td class="num red">${F.vnd(k.ded)}</td><td colspan="2"></td></tr></tfoot></table>` })}
      ${U.card({ title: 'Hiện trạng phòng khi nhận lại', icon: 'clipboard-check', body: `<div class="inspect-tiles">${[['wall', 'Tường'], ['furniture', 'Nội thất'], ['utilities', 'Điện nước'], ['devices', 'Thiết bị']].map(([kk, l]) => { const v = (rf.inspection || {})[kk] || 'ok'; return `<div class="inspect-tile ${v === 'ok' ? 'on' : 'warn'}"><div><b>${l}</b><small>${v === 'ok' ? 'Bình thường' : v === 'minor' ? 'Có hư hỏng nhỏ' : 'Hư hỏng nặng'}</small></div></div>`; }).join('')}</div><div class="row mt12 gap12"><span class="small muted">Trạng thái phòng hiện tại:</span>${Q.chipDot('room', room.status)}${room.status === 'cleaning' ? '<span class="xs muted">– phòng chỉ Sẵn sàng sau khi Vận hành xác nhận dọn xong (BR-02)</span>' : ''}</div>` })}</div>`;
    U.bind(root, { edit: () => TH.go('#/refunds/new?id=' + rf.id + '&step=3'), submit: async () => { if (await U.confirm({ title: 'Gửi duyệt ' + rf.code + '?', ok: 'Gửi duyệt' })) { try { X.submitRefund(rf.id); U.toast('ok', 'Đã gửi duyệt'); } catch (e) { U.toast('err', 'Không gửi được', e.message); } } }, approve: () => Fm.refundApprove(rf), reject: () => Fm.refundReject(rf), paid: () => Fm.refundPaid(rf), zalo: () => sendRefundZalo(rf), clean: async () => { if (await U.confirm({ title: 'Xác nhận dọn xong phòng ' + room.code + '?', ok: 'Xác nhận' })) { X.confirmCleaned(room.id); U.toast('ok', 'Phòng đã Sẵn sàng'); } }, dl: () => U.fakePdf('Ho so hoan coc ' + rf.code, ['Khách: ' + t.name, 'Phòng: ' + room.code, 'Cọc: ' + F.vnd(rf.deposit), ...dd.map(d => '- ' + d.group + ': ' + d.desc + ' ' + F.vnd(d.amount)), 'Hoàn: ' + F.vnd(k.refund)]), more: (el) => rfMenu(el, rf) });
  }, { menu: 'refunds', permission: 'refunds.view', resource: { type: 'refund' } });
})(window.TH);
