/* UI-17 Danh sách hoàn cọc · UI-18 Phiếu tính hoàn (BC/BD, E18 vượt cọc, duyệt kép admin + kế toán) · E19 bản in HĐ (HOÀN CỌC). */
(function (TH) {
  const S = TH.store, F = TH.f, U = TH.ui, K = TH.kit, Q = TH.q, X = TH.actions, esc = F.esc, R = TH.calc.refund;
  const ST = { draft: ['Chờ tính', 'gray'], calculated: ['Chờ duyệt', 'amber'], approved: ['Đã duyệt – chờ chi', 'blue'], paid: ['Đã hoàn', 'green'] };
  const chip = (r) => U.chip(ST[r.status][0], ST[r.status][1], true) + (r.bd < 0 ? ' ' + U.chip('Vượt cọc', 'red') : '');
  TH.router.handle('/refunds', (root, p, q) => {
    const detailed = Q.scoped(Q.refundRows(q)), rows = detailed.map(x => x.refund), detailOf = Object.fromEntries(detailed.map(x => [x.refund.id, x]));
    const counts = {}; Object.keys(ST).forEach(k => { counts[k] = rows.filter(r => r.status === k).length; });
    const scope = Q.scopeBuildingIds(q), pendingEnd = Q.scoped(S.all('stays')).filter(s => scope.has(s.buildingId) && s.status === 'ended' && s.endType === 'expired' && s.depositStatus === 'refund_pending' && !S.one('refunds', r => r.stayId === s.id));
    root.innerHTML = U.pageHead({ title: 'Hoàn cọc', sub: 'Chỉ khách hết hạn HĐ được hoàn; phá HĐ / bỏ trốn / bỏ cọc không lập phiếu', acts: [U.btn({ label: 'Xuất', icon: 'download', act: 'exp' })] })
      + `<div class="grid grid-4 mb16">${U.kpi({ label: 'Chờ tính / chờ duyệt', value: counts.draft + counts.calculated, icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Đã duyệt – chờ chi', value: counts.approved, icon: 'check-circle', tone: 'blue' })}
        ${U.kpi({ label: 'Đã hoàn', value: counts.paid, cap: F.vnd(rows.filter(r => r.status === 'paid').reduce((s, r) => s + (r.paidAmount || 0), 0)), icon: 'hand-coins', tone: 'green' })}${U.kpi({ label: 'Vượt cọc', value: rows.filter(r => r.bd < 0).length, cap: 'phần vượt → công nợ riêng', icon: 'alert-triangle', tone: 'red' })}</div>`
      + (pendingEnd.length ? U.note('warn', `${pendingEnd.length} lượt thuê hết hạn chưa có phiếu hoàn`, pendingEnd.slice(0, 8).map(s => `<a href="#/stays/${s.id}">${esc(s.code)}</a>`).join(', ')) : '')
      + K.filters([{ name: 'q', type: 'search', label: 'Tìm', placeholder: 'Mã phiếu, phòng, mã KH' }, { name: 'status', label: 'Trạng thái', options: [['open', 'Chưa hoàn'], ...Object.entries(ST).map(([k, v]) => [k, v[0]])] }, { name: 'dateBasis', label: 'Ngày lọc', options: [['handoverDate', 'Ngày bàn giao'], ['paidAt', 'Ngày chi hoàn']], value: 'handoverDate', all: false }, { name: 'from', type: 'date', label: 'Từ ngày' }, { name: 'to', type: 'date', label: 'Đến ngày' }, { name: 'area', label: 'Khu vực', options: K.areaOpts() }, { name: 'building', label: 'Tòa', options: K.buildingOpts() }, { name: 'manager', label: 'Quản lý', options: K.managerOpts() }, { name: 'leader', label: 'Leader', options: Q.teamLeaders().map(e => [e.id, e.name]) }, ...(q.leader ? [{ name: 'direct', label: 'Phạm vi team', options: [['1', 'Chỉ team trực tiếp']], all: 'Cả nhánh' }] : [])], q)
      + '<div class="mt16">' + K.tableCard('t', rows.length + ' phiếu') + '</div>';
    K.bindFilters(root);
    U.table(root.querySelector('#t'), { rows, pageSize: 25, stickyFirst: true, rowHref: r => '#/refunds/' + r.id, cols: [
      { key: 'code', label: 'Mã phiếu', render: r => `<b>${esc(r.code)}</b>` }, { key: 'room', label: 'Phòng', render: r => `<span class="code">${esc(Q.roomCode(r.roomId))}</span>` },
      { key: 'kh', label: 'Lượt thuê', render: r => { const s = Q.stay(r.stayId); return U.cell2(esc(s.code), esc((Q.customer(s.customerId) || {}).name || '')); } },
      { key: 'mgr', label: 'Quản lý / leader', render: r => { const x = detailOf[r.id]; return U.cell2(esc((x.manager || {}).name || 'Chưa phân công'), esc((x.leader || {}).name || 'Chưa có leader')); } },
      { key: 'h', label: 'Bàn giao', render: r => F.date(r.handoverDate) }, { key: 'i', label: 'Cọc (I)', num: true, render: r => F.vnd(r.deposit) }, { key: 'bc', label: 'Khấu trừ (BC)', num: true, render: r => F.vnd(r.bc) },
      { key: 'bd', label: 'Số tính hoàn (BD)', num: true, sortable: true, sortVal: r => r.bd, render: r => `<b class="${r.bd < 0 ? 'red' : ''}">${F.vnd(r.bd)}</b>` }, { key: 'paid', label: 'Thực chi', num: true, render: r => r.paidAmount != null ? F.vnd(r.paidAmount) : '–' },
      { key: 'ap', label: 'Duyệt', render: r => ['admin', 'ketoan'].map(x => (r.approvals || []).some(a => a.role === x) ? U.chip(x === 'admin' ? 'Admin ✓' : 'Kế toán ✓', 'green') : U.chip(x === 'admin' ? 'Admin' : 'Kế toán', 'gray')).join(' ') },
      { key: 'st', label: 'Trạng thái', render: chip }] });
    U.bind(root, { exp: () => K.csv('hoan-coc.csv', ['Mã', 'Phòng', 'Mã KH', 'Tòa', 'Khu vực', 'Quản lý', 'Leader', q.dateBasis === 'paidAt' ? 'Ngày chi hoàn' : 'Ngày bàn giao', 'Cọc', 'BC', 'BD', 'Thực chi', 'Trạng thái'], rows.map(r => { const x = detailOf[r.id]; return [r.code, x.room.code, x.stay.code, x.building.code, (S.get('areas', x.building.areaId) || {}).name || '', (x.manager || {}).name || '', (x.leader || {}).name || '', x.date, r.deposit, r.bc, r.bd, r.paidAmount || '', ST[r.status][0]]; }), ['Cọc', 'BC', 'BD', 'Thực chi']) });
  });

  TH.router.handle('/refunds/:id', (root, p) => {
    const r = S.get('refunds', p.id); if (!r) { root.innerHTML = U.empty({ title: 'Không tìm thấy phiếu' }); return; }
    if (!TH.auth.inScope(r.buildingId)) { root.innerHTML = U.card({ body: U.empty({ icon: 'lock', title: 'Phiếu hoàn ngoài phạm vi được giao' }) }); return; }
    const s = Q.stay(r.stayId); const editable = ['draft', 'calculated'].includes(r.status) && TH.auth.can('refunds.prepare');
    TH.layout.crumb([{ label: 'Hoàn cọc', href: '#/refunds' }, { label: r.code }]);
    const role = TH.auth.role(); const approved = (x) => (r.approvals || []).some(a => a.role === x);
    const steps = [{ title: 'Tính số hoàn', sub: r.status === 'draft' ? 'đang nhập' : 'xong' }, { title: 'Admin duyệt', sub: approved('admin') ? 'đã duyệt' : '' }, { title: 'Kế toán duyệt', sub: approved('ketoan') ? 'đã duyệt' : '' }, { title: 'Ghi chi & in phiếu', sub: r.status === 'paid' ? F.date(r.paidAt) : '' }];
    const cur = r.status === 'draft' ? 0 : r.status === 'paid' ? 4 : r.status === 'approved' ? 3 : approved('admin') ? 2 : 1;
    root.innerHTML = U.pageHead({ title: 'Phiếu hoàn cọc ' + esc(r.code) + ' ' + chip(r), back: '#/refunds', sub: `<a href="#/stays/${s.id}">${esc(Q.stayLabel(s))}</a> · Phòng ${esc(Q.roomCode(r.roomId))} · bàn giao ${F.date(r.handoverDate)}`, acts: [
      U.btn({ label: 'In mẫu hoàn', icon: 'printer', href: '#/print/refund/' + r.id }),
      editable ? U.btn({ label: 'Tính số hoàn', icon: 'refresh', act: 'calc' }) : '',
      ['calculated'].includes(r.status) && ((role === 'admin' && !approved('admin')) || (role === 'ketoan' && !approved('ketoan'))) ? U.btn({ label: 'Duyệt (' + TH.auth.roleLabel() + ')', icon: 'check-circle', cls: 'btn-success', act: 'approve' }) : '',
      r.status === 'approved' ? U.btn({ label: 'Ghi chi hoàn', icon: 'banknote', cls: 'btn-primary', act: 'pay', perm: 'refunds.pay' }) : ''] })
      + U.wizard(steps, cur)
      + (r.bd < 0 ? U.note('danger', 'Khấu trừ vượt cọc – không chi hoàn', r.excessInvoiceId ? `Số chi = 0. Phần vượt cọc ${F.vndd(-r.bd)} đã lập <a href="#/billing/invoices/${r.excessInvoiceId}">${esc((S.get('invoices', r.excessInvoiceId) || {}).code || '')}</a> (dòng 13 Thu khác) – theo dõi ở Công nợ, thu bằng phiếu thu.` : `Số chi = 0. Khi ghi chi, phần vượt cọc ${F.vndd(-r.bd)} tự lập hóa đơn thu riêng (dòng 13 Thu khác) của lượt thuê → Công nợ UI-14.`) : '')
      + `<div class="two-col"><div class="side-stack">${U.card({ title: 'Chi tiết khấu trừ trong cọc (BC)', icon: 'list', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Khoản</th><th>Chỉ số cũ → mới</th><th class="num">SL</th><th class="num">Đơn giá</th><th>Lý do</th><th class="num">Thành tiền</th><th>Truy vết</th></tr></thead><tbody id="dd">
        ${r.deductions.map((d, i) => `<tr><td>${editable ? U.select({ name: 'k' + i, value: d.kind, options: R.KINDS.map(k => [k.key, k.label]), cls: 'sm' }) : esc(R.kindLabel(d.kind))}</td><td>${d.prev != null || d.curr != null ? F.num0(d.prev) + ' → ' + F.num0(d.curr) : '–'}</td>
          <td class="num">${editable ? `<input class="inp sm tr" name="q${i}" value="${d.qty || ''}" style="width:70px">` : d.qty || ''}</td><td class="num">${editable ? `<input class="inp sm tr" data-money name="u${i}" value="${F.vnd(d.unit || 0)}" style="width:110px">` : F.vnd(d.unit)}</td><td>${editable ? `<input class="inp sm" name="n${i}" value="${esc(d.note || '')}" aria-label="Lý do khoản ${i+1}">` : esc(d.note || 'Dữ liệu lịch sử từ Excel')}</td><td class="num"><b>${F.vnd(d.amount)}</b></td><td>${U.actBtn({icon:'search',label:'Truy vết khoản khấu trừ',act:'trace',attrs:{'data-i':i}})}</td></tr>`).join('')}
        </tbody></table></div>${editable ? `<button type="button" class="btn btn-ghost btn-sm mt8" data-act="addline">+ Thêm khoản (sửa chữa, vệ sinh, sơn… theo chi phí thực tế)</button>` : ''}` })}
        ${r.extraRent ? U.card({ title: 'Tiền phòng ngày ở thêm', icon: 'calendar', body: `<p>${r.extraDays} ngày × ${F.vnd(s.rent)}/${TH.calc.dates.daysInMonth(F.period(r.handoverDate))} = <b>${F.vndd(r.extraRent)}</b></p>
          ${editable ? `<label class="chk mt8"><input type="checkbox" name="deductExtra" ${r.deductExtra ? 'checked' : ''}> <span>Khấu trừ vào cọc (tham số OQ-16 hiện: ${Q.param('refundDeductExtraDays', r.handoverDate || F.today()) ? 'CÓ trừ' : 'KHÔNG trừ – thu ở hóa đơn cuối'})</span></label><div class="mt8">${U.input({ name: 'extraReason', value: r.extraReason || '', placeholder: 'Lý do nếu trừ vào cọc' })}</div>` : `<p class="small muted">${r.deductExtra ? 'Đã trừ vào cọc: ' + esc(r.extraReason || '') : 'Không trừ vào cọc'}</p>`}` }) : ''}
      </div><div class="side-stack">${U.card({ title: 'Tính số hoàn', icon: 'calculator', body: `<div class="sum-box"><div class="it"><span>Tiền cọc (I)</span><b>${F.vndd(r.deposit)}</b></div><div class="it"><span>Tổng khấu trừ (BC)</span><b>− ${F.vndd(r.bc)}</b></div>
          <div class="it"><span>Số tính hoàn (BD = I − BC)</span><b class="${r.bd < 0 ? 'red' : 'green'}">${F.vndd(r.bd)}</b></div><div class="it"><span>Số chi thực tế</span><b>${r.paidAmount != null ? F.vndd(r.paidAmount) : 'Chưa ghi chi'}</b></div></div>
          ${r.excel ? `<p class="small muted mt8">Đối chiếu Excel ${esc(r.excel.src)}: BC ${F.vnd(r.excel.bc)} · BD ${F.vnd(r.excel.bd)}</p>` : ''}` })}
        ${U.card({ title: 'Duyệt & chi', icon: 'shield-check', body: U.kv([['Admin', approved('admin') ? '✓ ' + esc(r.approvals.find(a => a.role === 'admin').by) : 'Chưa duyệt'], ['Kế toán', approved('ketoan') ? '✓ ' + esc(r.approvals.find(a => a.role === 'ketoan').by) : 'Chưa duyệt'], ['Ngày chi', F.date(r.paidAt)], ['Phương thức', r.paidAt ? (r.method === 'cash' ? 'Tiền mặt' : 'Chuyển khoản') : '–']]) + U.note('info', '', 'Khấu hao hoàn cọc cố định ' + F.vnd(Q.param('refundDepreciation')) + 'đ/phòng (CH-17); admin và kế toán cùng duyệt số hoàn cuối.') })}
      </div></div>`;
    U.onInput(root);
    const readDeds = () => r.deductions.map((d, i) => { const k = root.querySelector('[name=k' + i + ']'); if (!k) return d; const qty = F.num(root.querySelector('[name=q' + i + ']').value), unit = F.num(root.querySelector('[name=u' + i + ']').value), note = root.querySelector('[name=n' + i + ']').value; return Object.assign({}, d, { kind: k.value, qty, unit, note, amount: d.prev != null && d.curr != null && d.kind === k.value && qty === d.qty && unit === d.unit ? d.amount : qty * unit }); });
    U.bind(root, {
      calc: () => { const de = root.querySelector('[name=deductExtra]'); K.act(() => X.updateRefund(r.id, { deductions: readDeds(), deductExtra: de && de.checked, extraReason: (root.querySelector('[name=extraReason]') || {}).value }), 'Đã tính số hoàn'); },
      addline: () => { S.update('refunds', r.id, { deductions: [...readDeds(), { kind: 'repair', qty: 1, unit: 0, amount: 0, note: '', enteredBy: (S.session || {}).name, sourceRef: 'manual-refund' }] }); TH.router.refresh(); },
      trace: el => { const d = r.deductions[Number(el.dataset.i)] || {}; U.drawer({ title: 'Truy vết khoản khấu trừ', sub: R.kindLabel(d.kind), body: U.kv([['Số tiền',F.vndd(d.amount)],['Lý do',esc(d.note || 'Dữ liệu lịch sử từ Excel')],['Người nhập',esc(d.enteredBy || r.preparedBy || 'Import Excel')],['Nguồn / chứng từ',esc(d.sourceRef || r.excel?.src || 'Chưa gắn chứng từ')],['Chỉ số',d.prev != null || d.curr != null ? `${d.prev ?? '–'} → ${d.curr ?? '–'}` : '–']]) + U.note('info','Liên kết nguồn',d.sourceRef && S.get('repairLogs',d.sourceRef) ? `<a href="#/repairs?job=${esc(d.sourceRef)}">Mở sổ sửa chữa</a>` : 'Khoản lịch sử giữ nguyên tham chiếu nguồn; khoản web mới bắt buộc lý do và người nhập.') }); },
      approve: () => K.act(() => X.approveRefund(r.id), 'Đã duyệt'),
      pay: () => K.formDrawer({ title: 'Ghi chi hoàn ' + r.code, modal: true, fields: [{ name: 'amount', label: 'Số chi', type: 'money', value: Math.max(0, r.bd), req: true }, { name: 'date', label: 'Ngày chi', type: 'date', value: F.today(), req: true }, { name: 'method', label: 'Phương thức', type: 'select', options: [['bank', 'Chuyển khoản'], ['cash', 'Tiền mặt']], value: 'bank' }, { name: 'reference', label: 'Mã giao dịch / biên nhận' }],
        submit: 'Ghi chi', onSubmit: (d) => { X.payRefund(r.id, d); U.toast('ok', 'Đã ghi chi hoàn'); } }),
    });
  });
  TH.router.handle('/print/refund/:id', (root, p) => {
    const r = S.get('refunds', p.id); if (!r) { root.innerHTML = 'Không tìm thấy phiếu'; return; }
    if (!TH.auth.inScope(r.buildingId)) { root.innerHTML = U.card({ body: U.empty({ icon: 'lock', title: 'Phiếu hoàn ngoài phạm vi được giao' }) }); return; }
    root.innerHTML = `<div class="print-bar no-print"><a class="btn btn-ghost" href="#/refunds/${r.id}">← Quay lại</a><span class="chip gray">HĐ (HOÀN CỌC)</span><button class="btn btn-primary" onclick="window.print()">In / Lưu PDF</button></div>${TH.print.refundHtml(r)}`;
  });
})(window.TH);
