(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, esc = F.esc, C = TH.chart;
  TH.router.register('/reports', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Báo cáo Phase 1' }]);
    const tab = q.tab || 'rooms'; const period = TH.router.periodOf(q) || St.state.meta.period; const bId = q.buildingId || '';
    const bs = St.where('buildings', b => !b.stub && (!bId || b.id === bId));
    root.innerHTML = `${U.pageHead({ title: 'Báo cáo Phase 1', sub: 'Ba báo cáo vận hành cơ bản: Phòng, Công nợ, Thu tiền (00_SCOPE §2.6). Report Hub, hiệu suất, lợi nhuận thuộc Phase 2 – công thức TBD.', acts: [U.btn({ label: 'Xuất CSV', icon: 'download', cls: 'btn-primary', act: 'export' }), U.btn({ label: 'Report Hub', icon: 'bar-chart', cls: 'btn-outline', p2: true })] })}
    ${U.tabs([{ key: 'rooms', label: 'Báo cáo phòng', icon: 'door' }, { key: 'debt', label: 'Báo cáo công nợ', icon: 'receipt' }, { key: 'collect', label: 'Báo cáo thu tiền', icon: 'wallet' }], tab, 'boxed')}
    ${U.filterbar([U.field({ label: 'Kỳ', input: U.select({ name: 'period', value: period, options: [...new Set(St.all('invoices').map(i => i.period))].sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: bId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) })])}
    <div id="rep"></div>`;
    const rep = root.querySelector('#rep'); let rows = [], headers = [];
    if (tab === 'rooms') { rows = bs.map(b => { const s = Q.roomStats(Q.roomsOf(b.id)); return [b.name, s.total, s.occupied, s.ready, s.held, s.cleaning, s.maintenance + s.inactive, F.pct(s.occupied, s.total) + '%']; }); headers = ['Tòa', 'Tổng phòng', 'Đang thuê', 'Sẵn sàng', 'Giữ chỗ', 'Chờ dọn', 'Bảo trì/Ngừng', 'Tỷ lệ lấp đầy']; const tot = Q.roomStats(bs.flatMap(b => Q.roomsOf(b.id)));
      rep.innerHTML = `<div class="grid grid-5 mb16">${Object.entries(Q.L.room).slice(0, 5).map(([k, v]) => U.kpi({ mini: true, label: v[0], value: tot[k] || 0, icon: 'door', tone: v[1] === 'orange' ? 'amber' : v[1] })).join('')}</div>` + U.card({ title: 'Báo cáo phòng theo tòa', icon: 'door', sub: 'Tỷ lệ lấp đầy = phòng đang thuê / tổng phòng (chỉ tiêu vận hành, không phải hiệu suất OI-12)', bodyCls: 'tight', body: table(headers, rows, [tot.total, tot.occupied, tot.ready, tot.held, tot.cleaning, tot.maintenance + tot.inactive, F.pct(tot.occupied, tot.total) + '%']) + `<div style="padding:18px">${C.stackedBar({ groups: bs.map(b => { const s = Q.roomStats(Q.roomsOf(b.id)); return { label: b.name, sub: '(' + s.total + ' phòng)', values: [s.occupied, s.ready, s.held, s.maintenance, s.cleaning + s.inactive] }; }), series: [{ color: '#1D4ED8' }, { color: '#BFDBFE', dark: true }, { color: '#FCD34D', dark: true }, { color: '#F97316' }, { color: '#CBD5E1', dark: true }], height: 200 })}</div>` }); }
    if (tab === 'debt') { rows = bs.map(b => { const x = Q.finance(period, { buildingId: b.id }); return [b.name, x.count, x.receivable, x.collected, x.remaining, x.overdue, x.overdueCount, x.pct + '%']; }); headers = ['Tòa', 'Số HĐ', 'Phải thu', 'Đã thu', 'Còn nợ', 'Quá hạn', 'Số HĐ quá hạn', 'Tỷ lệ thu']; const t = Q.finance(period, { buildingId: bId });
      rep.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Phải thu', value: F.vnd(t.receivable), cap: t.count + ' hóa đơn', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã thu', value: F.vnd(t.collected), cap: t.pct + '%', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn nợ', value: F.vnd(t.remaining), cap: (100 - t.pct) + '%', icon: 'coins', tone: 'amber' })}${U.kpi({ label: 'Quá hạn', value: F.vnd(t.overdue), cap: t.overdueCount + ' hóa đơn', icon: 'clock', tone: 'red' })}</div>` + U.card({ title: 'Báo cáo công nợ theo tòa – ' + F.periodLabel(period), icon: 'receipt', sub: 'Còn phải thu và Quá hạn hiển thị tách biệt (FR-FIN-04)', bodyCls: 'tight', body: table(headers, rows.map(r => r.map((v, i) => i >= 2 && i <= 5 ? F.vnd(v) : v)), [t.count, F.vnd(t.receivable), F.vnd(t.collected), F.vnd(t.remaining), F.vnd(t.overdue), t.overdueCount, t.pct + '%']) + `<div style="padding:18px">${C.barLine({ groups: bs.map(b => { const x = Q.finance(period, { buildingId: b.id }); return { label: b.name, a: x.collected, b: x.remaining }; }), height: 200 })}</div>` }); }
    if (tab === 'collect') { const pays = St.where('payments', x => x.status === 'recorded' && F.period(x.date) === period && (!bId || x.buildingId === bId)); const byM = F.by(pays, 'method'); const byD = F.by(pays, 'date'); const byU = F.by(pays, 'createdBy');
      rows = Object.keys(byD).sort().map(d => [F.date(d), byD[d].length, F.sum(byD[d], x => x.amount), [...new Set(byD[d].map(x => x.method))].join(', ')]); headers = ['Ngày thu', 'Số phiếu', 'Số tiền', 'Phương thức'];
      rep.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng thu trong kỳ', value: F.vnd(F.sum(pays, x => x.amount)), cap: pays.length + ' phiếu thu', icon: 'wallet', tone: 'green' })}${Object.entries(byM).slice(0, 3).map(([m, arr]) => U.kpi({ label: m, value: F.vnd(F.sum(arr, x => x.amount)), cap: arr.length + ' phiếu', icon: 'credit-card', tone: 'blue' })).join('')}</div><div class="grid grid-2">${U.card({ title: 'Thu tiền theo ngày – ' + F.periodLabel(period), icon: 'calendar', bodyCls: 'tight', body: table(headers, rows.map(r => [r[0], r[1], F.vnd(r[2]), r[3]]), [pays.length, F.vnd(F.sum(pays, x => x.amount)), '']) })}${U.card({ title: 'Theo người thu', icon: 'user', bodyCls: 'tight', body: table(['Người thu', 'Số phiếu', 'Số tiền'], Object.entries(byU).map(([u, arr]) => [Q.userName(u), arr.length, F.vnd(F.sum(arr, x => x.amount))])) })}</div>`; }
    function table(h, r, tot) { return `<div class="tbl-wrap"><table class="tbl compact"><thead><tr>${h.map((x, i) => `<th class="${i > 0 ? 'num' : ''}">${x}</th>`).join('')}</tr></thead><tbody>${r.map(row => `<tr>${row.map((v, i) => `<td class="${i > 0 ? 'num' : ''}">${v}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${h.length}" class="muted tc">Không có dữ liệu</td></tr>`}</tbody>${tot ? `<tfoot><tr><td>Tổng</td>${tot.map(v => `<td class="num">${v}</td>`).join('')}</tr></tfoot>` : ''}</table></div>`; }
    U.onChange(root, { f: () => TH.router.applyFilter({ tab, period, buildingId: bId }, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { tab: (el) => TH.router.applyFilter({ tab, period, buildingId: bId }, { tab: el.dataset.key }), export: () => { F.download('bao-cao-' + tab + '-' + period + '.csv', F.csv(rows, headers), 'text/csv'); U.toast('ok', 'Đã xuất báo cáo CSV'); } });
  }, { menu: 'reports', permission: 'reports.view' });
})(window.TH);
