/* Phase 2 – Bản ghi báo cáo: #/reports/hub (danh sách bản ghi), #/reports/new (chọn loại → tham số → tạo), #/reports/runs/:id (preview snapshot + tải CSV).
   Số liệu tính bằng TH.reportEngine (reportHub.js) và chốt (snapshot) lúc tạo: preview và CSV luôn cùng một bộ dữ liệu. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, esc = F.esc;
  const ok = (m, s) => U.toast('ok', m, s);
  const E = () => TH.reportEngine;
  const allowed = r => TH.auth.role() !== 'sale' || (!!r && r.cat === 'sales');
  const periodOpts = () => [...new Set(St.all('invoices').map(i => i.period).concat(St.all('periods').map(x => x.period), [St.state.meta.period, '2026-10', '2026-09']))].sort().reverse();
  const periodText = rec => rec.periods.length > 1 ? F.periodShort(rec.periods[0]) + ' → ' + F.periodShort(rec.periods[rec.periods.length - 1]) + ' (' + rec.periods.length + ' kỳ)' : F.periodLabel(rec.periods[0]);
  const DIM = { buildingId: ['Tòa', id => Q.building(id).name], areaId: ['Khu', id => Q.area(id).name], buildingType: ['Loại nhà', v => (Q.L.buildingType[v] || [v])[0]], managerId: ['Quản lý', Q.userName], leadId: ['Trưởng nhóm', id => (St.get('employees', id) || {}).name], opsId: ['Vận hành', id => (St.get('employees', id) || {}).name], shareholderId: ['Cổ đông', id => Q.shareholder(id).name], saleId: ['Sale', Q.userName], teamId: ['Team', id => (St.get('salesTeams', id) || {}).name] };
  const scopeText = params => Object.keys(DIM).filter(k => params[k]).map(k => DIM[k][0] + ': ' + (DIM[k][1](params[k]) || params[k])).join(' · ') || 'Tất cả tòa nhà';
  const catOf = rec => (E().CAT[rec.cat] || [rec.cat])[0];
  const download = rec => { F.download(rec.code + '.csv', E().toCsv(rec), 'text/csv'); ok('Đã tải CSV', rec.code + '.csv · ' + rec.rowCount + ' dòng'); };
  const rerun = rec => { const n = X.rerunReport(rec.id); ok('Đã tạo lại ' + n.code, 'Số liệu tính tại thời điểm hiện tại'); TH.go('#/reports/runs/' + n.id); };
  const remove = async rec => { if (await U.confirm({ title: 'Xóa bản ghi ' + rec.code + '?', text: esc(rec.name) + ' – snapshot sẽ mất, có thể tạo lại từ loại báo cáo.', ok: 'Xóa', danger: true })) { X.deleteReportRun(rec.id); ok('Đã xóa ' + rec.code); if (TH.router.current && TH.router.current.path === '/reports/hub') TH.router.refresh(); else TH.go('#/reports/hub'); } };
  const runMenu = (el, rec) => U.menu(el, [{ label: 'Xem bản ghi', icon: 'eye', onClick: () => TH.go('#/reports/runs/' + rec.id) }, { label: 'Tải CSV', icon: 'download', onClick: () => download(rec) }, { label: 'Tạo lại (số liệu hiện tại)', icon: 'refresh', onClick: () => rerun(rec) }, '-', { label: 'Xóa bản ghi', icon: 'trash', danger: true, onClick: () => remove(rec) }]);

  /* ================= #/reports/hub – danh sách bản ghi ================= */
  TH.router.register('/reports/hub', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Trung tâm báo cáo' }]);
    const f = { s: q.s || '', cat: q.cat || '', type: q.type || '', per: q.per || '', createdBy: q.createdBy || '' };
    const all = St.all('reportRuns').filter(allowed).sort((a, b) => F.cmp(b.createdAt, a.createdAt));
    const rows = all.filter(r => (!f.s || F.norm(r.code + ' ' + r.name).includes(F.norm(f.s))) && (!f.cat || r.cat === f.cat) && (!f.type || r.type === f.type) && (!f.per || r.periods.includes(f.per)) && (!f.createdBy || r.createdBy === f.createdBy));
    const types = [...new Set(all.map(r => r.type))].map(k => E().byKey(k)).filter(Boolean); const creators = [...new Set(all.map(r => r.createdBy).filter(Boolean))];
    const runnable = E().REPORTS.filter(E().isRunnable).filter(allowed).length;
    root.innerHTML = `${U.pageHead({ title: 'Trung tâm báo cáo', phase: 2, sub: 'Bản ghi báo cáo đã tạo – số liệu được chốt (snapshot) tại thời điểm lập; mở để xem trước hoặc tải CSV.', acts: [U.btn({ label: 'Tạo báo cáo', icon: 'plus', cls: 'btn-primary', act: 'new', attrs: { 'data-guide': 'report-new' } }), U.btn({ label: 'Dòng tiền & khóa kỳ', icon: 'arrow-left-right', cls: 'btn-outline', act: 'cashflow' }), U.btn({ label: 'Báo cáo Phase 1', icon: 'bar-chart', cls: 'btn-ghost', act: 'p1' })] })}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Bản ghi báo cáo', value: all.length, cap: 'Đã tạo trong hệ thống', icon: 'file-text', tone: 'blue', mini: true })}${U.kpi({ label: 'Tạo tháng này', value: all.filter(r => F.period(r.createdAt) === F.period(F.today())).length, cap: F.periodLabel(F.period(F.today())), icon: 'calendar', tone: 'green', mini: true })}${U.kpi({ label: 'Loại đã dùng', value: types.length, cap: runnable + ' loại chạy được', icon: 'layers', tone: 'purple', mini: true })}${U.kpi({ label: 'Dòng dữ liệu', value: F.sum(all, r => r.rowCount || 0), cap: 'Trong các snapshot', icon: 'table', tone: 'amber', mini: true })}</div>
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Mã / tên báo cáo', icon: 'search', attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Danh mục', input: U.select({ name: 'cat', value: f.cat, all: 'Tất cả danh mục', options: Object.entries(E().CAT).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại báo cáo', input: U.select({ name: 'type', value: f.type, all: 'Tất cả loại', options: types.map(r => [r.key, r.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Có kỳ', input: U.select({ name: 'per', value: f.per, all: 'Tất cả kỳ', options: periodOpts().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người tạo', input: U.select({ name: 'createdBy', value: f.createdBy, all: 'Tất cả', options: creators.map(id => [id, Q.userName(id)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${all.length ? U.card({ title: 'Bản ghi báo cáo (' + rows.length + ')', icon: 'file-text', bodyCls: 'tight', body: '<div id="rt"></div>' }) : U.card({ body: U.empty({ icon: 'file-text', title: 'Chưa có bản ghi báo cáo', text: 'Tạo báo cáo: chọn loại → điền kỳ và phạm vi → hệ thống chốt số liệu và lưu bản ghi để xem trước hoặc tải CSV.', action: U.btn({ label: 'Tạo báo cáo đầu tiên', icon: 'plus', cls: 'btn-primary', act: 'new' }) }) })}`;
    if (all.length) U.table(root.querySelector('#rt'), { rows, unit: 'bản ghi', rowHref: r => '#/reports/runs/' + r.id, empty: 'Không có bản ghi khớp bộ lọc', cols: [
      { key: 'code', label: 'Mã', render: r => U.link('#/reports/runs/' + r.id, esc(r.code), 'bold') },
      { key: 'name', label: 'Báo cáo', sortable: true, render: r => U.cell2(esc(r.name), esc((E().byKey(r.type) || {}).name || r.type) + ' · ' + esc(catOf(r))) },
      { key: 'periods', label: 'Kỳ', sortable: true, sortVal: r => r.periods[0], render: r => esc(periodText(r)) },
      { key: 'scope', label: 'Phạm vi', render: r => `<span class="small">${esc(scopeText(r.params || {}))}</span>` },
      { key: 'rowCount', label: 'Số dòng', num: true, sortable: true },
      { key: 'createdBy', label: 'Người tạo', render: r => esc(Q.userName(r.createdBy)) },
      { key: 'createdAt', label: 'Ngày tạo', sortable: true, render: r => F.datetime(r.createdAt) },
      { key: 'actions', label: 'Thao tác', hideable: false, render: r => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': r.id } }), U.iconBtn('download', 'dl', 'Tải CSV', { 'data-id': r.id }), U.moreBtn(r.id)]) }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { new: () => TH.go('#/reports/new'), cashflow: () => TH.go('#/reports/cashflow'), p1: () => TH.go('#/reports'), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: el => TH.go('#/reports/runs/' + el.dataset.id), dl: el => download(St.get('reportRuns', el.dataset.id)), more: el => runMenu(el, St.get('reportRuns', el.dataset.id)) });
  }, { menu: 'reports-detail', permission: 'reports.hub', phase: 2, scopeKey: 'reports-detail' });

  /* ================= #/reports/new – tạo báo cáo (2 bước) ================= */
  const STEPS = [{ title: 'Chọn loại báo cáo', sub: 'Danh mục 48 loại' }, { title: 'Điền thông tin', sub: 'Kỳ, phạm vi, tên' }, { title: 'Bản ghi báo cáo', sub: 'Xem trước · tải CSV' }];
  const typeCard = r => { const live = E().isRunnable(r); const p3 = r.impl === 'p3'; return `<div class="rc-card ${live ? '' : 'rc-muted'}"><div class="ic" style="background:var(--${r.tone}-bg);color:var(--${r.tone})">${I(r.icon)}</div><b>${esc(r.name)}${r.impl === 'todo' ? ' <span class="tag-p" title="Công thức chờ chốt ' + esc(r.oi) + '">OI</span>' : p3 ? TH.phase.tag(3) : ''}${r.assumed ? ' ' + U.assume() : ''}</b><p>${esc(r.desc)}</p><div class="tags">${r.tags.map(t => U.chip(t, 'gray')).join('')}</div><div class="btns">${live ? U.btn({ label: 'Chọn', icon: 'check', size: 'btn-sm', cls: 'btn-primary', act: 'pick', attrs: { 'data-k': r.key } }) : p3 ? `<a class="btn btn-outline btn-sm" href="${E().hrefOf(r)}">${I('external-link')}Mở trang Phase 3</a>` : U.btn({ label: 'Chờ chốt công thức', icon: 'lock', size: 'btn-sm', cls: 'btn-ghost', disabled: true, title: 'Chưa tạo được bản ghi – ' + r.oi })}</div></div>`; };
  TH.router.register('/reports/new', (root, p, q) => {
    const CAT = E().CAT, REPORTS = E().REPORTS.filter(allowed); const r = q.type ? E().byKey(q.type) : null; const step = r && E().isRunnable(r) && allowed(r) ? 1 : 0;
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Trung tâm báo cáo', href: '#/reports/hub' }, { label: 'Tạo báo cáo' }]);
    if (step === 0) {
      const cat = q.cat || '', s = q.s || '';
      const list = REPORTS.filter(x => (!cat || x.cat === cat) && (!s || F.norm(x.name + ' ' + x.desc + ' ' + x.tags.join(' ')).includes(F.norm(s))));
      const groups = cat || s ? [['', 'Kết quả (' + list.length + ')', list]] : Object.entries(CAT).map(([k, v]) => [k, v[0], list.filter(x => x.cat === k)]).filter(g => g[2].length);
      root.innerHTML = `${U.pageHead({ back: '#/reports/hub', title: 'Tạo báo cáo', phase: 2, sub: 'Bước 1/2 – chọn loại báo cáo. Loại gắn nhãn OI chưa chốt công thức nên chưa tạo được bản ghi; loại Phase 3 mở trang tương ứng.' })}${U.wizard(STEPS, 0)}
      <div class="side-stack">${U.card({ body: `<div class="row"><div class="inp-wrap grow">${I('search')}<input name="s" value="${esc(s)}" placeholder="Tìm loại báo cáo theo tên, mô tả, từ khóa…" id="rs"></div>${U.btn({ label: 'Tìm', cls: 'btn-primary', act: 'search' })}</div>` })}
        <div class="cat-chips">${[['', 'Tất cả', REPORTS.length, 'grid'], ...Object.entries(CAT).map(([k, v]) => [k, v[0], REPORTS.filter(x => x.cat === k).length, v[1]])].filter(x => x[2]).map(([k, l, n, ic]) => `<button type="button" class="cat-chip ${cat === k ? 'on' : ''}" data-act="cat" data-k="${k}">${I(ic)} ${l} (${n})</button>`).join('')}</div>
        ${groups.map(([k, label, rs]) => U.card({ title: `${k ? I(CAT[k][1]) + ' ' : ''}${esc(label)} <span class="muted small" style="font-weight:400">${k ? esc(CAT[k][2]) : ''}</span>`, actions: `<span class="small muted">${rs.filter(E().isRunnable).length}/${rs.length} chạy được</span>`, body: `<div class="rc-grid">${rs.map(typeCard).join('') || '<div class="muted">Không tìm thấy loại báo cáo</div>'}</div>` })).join('')}</div>`;
      root.querySelector('#rs').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery({ cat, s: e.target.value }); TH.router.refresh(); } });
      U.bind(root, { search: () => { TH.router.replaceQuery({ cat, s: root.querySelector('#rs').value }); TH.router.refresh(); }, cat: el => { TH.router.replaceQuery({ cat: el.dataset.k, s }); TH.router.refresh(); }, pick: el => { TH.router.replaceQuery({ type: el.dataset.k }); TH.router.refresh(); } });
      return;
    }
    const period = St.state.meta.period; const opts = periodOpts().map(x => [x, F.periodLabel(x)]);
    const dims = (r.dims || []).filter(d => d !== 'period'); const f = { period };
    const fields = [U.field({ label: 'Tên báo cáo', input: U.input({ name: 'name', value: '', placeholder: r.name + ' – ' + F.periodShort(period) }), help: 'Để trống: tự đặt theo loại và kỳ', cls: 'span2' }), U.field({ label: 'Từ kỳ', req: true, input: U.select({ name: 'periodFrom', value: period, options: opts }) }), U.field({ label: 'Đến kỳ', req: true, input: U.select({ name: 'periodTo', value: period, options: opts }), help: 'Tối đa 12 kỳ; nhiều kỳ → có bảng tổng hợp theo kỳ' })];
    if (dims.length) fields.push(U.dimFields(f, dims)); else if (!r.noBuilding) fields.push(U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: '', all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]) }) }));
    fields.push(U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: '', placeholder: 'Mục đích lập báo cáo, người nhận…', rows: 2 }), cls: 'span2' }));
    root.innerHTML = `${U.pageHead({ back: '#/reports/new', title: 'Tạo báo cáo', phase: 2, sub: 'Bước 2/2 – điền tham số. Hệ thống tính số liệu, chốt snapshot và lưu thành bản ghi.', chips: ' ' + U.chip(CAT[r.cat][0], 'gray') })}${U.wizard(STEPS, 1)}
    <div class="rp-wz">${U.card({ title: 'Thông tin báo cáo', icon: 'sliders', body: `<form class="form-grid" id="rpf" onsubmit="return false">${fields.join('')}</form>`, footer: U.btn({ label: 'Quay lại chọn loại', icon: 'arrow-left', cls: 'btn-outline', act: 'back' }) + U.btn({ label: 'Tạo báo cáo', icon: 'check', cls: 'btn-primary', act: 'create', attrs: { 'data-guide': 'report-create' } }) })}
      <div class="side-stack">${U.card({ title: 'Loại đã chọn', icon: r.icon, body: `<div class="row gap12 mb12"><div class="ic" style="width:40px;height:40px;border-radius:10px;display:grid;place-items:center;background:var(--${r.tone}-bg);color:var(--${r.tone})">${I(r.icon)}</div><div><b>${esc(r.name)}</b><div class="small muted">${esc(r.desc)}</div></div></div>${U.kv([['Danh mục', esc(CAT[r.cat][0])], ['Tham chiếu', esc(r.oi || '-')], ['Phạm vi', dims.length ? 'Chiều lọc: ' + dims.map(d => (DIM[d] || [d])[0]).join(', ') : r.noBuilding ? 'Toàn hệ thống' : 'Tất cả tòa hoặc 1 tòa'], ['Trạng thái', r.assumed ? U.assume('Giả định – chờ khách xác nhận') : U.chip('Chạy thật', 'green')]], 'one')}` })}
      ${r.metric ? U.card({ title: 'Công thức', icon: 'info', body: TH.metrics.info(r.metric) }) : ''}
      ${U.note('info', 'Sau khi tạo', 'Bản ghi lưu KPI và bảng chi tiết của từng kỳ tại thời điểm tạo. Dữ liệu thay đổi về sau không ảnh hưởng bản ghi; dùng "Tạo lại" để lấy số liệu mới.')}</div></div>`;
    U.bind(root, { back: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, create: () => { const d = U.formData(root.querySelector('#rpf')); const rec = X.createReportRun(Object.assign({ type: r.key }, d)); ok('Đã tạo báo cáo ' + rec.code, rec.name + ' · ' + rec.rowCount + ' dòng'); TH.go('#/reports/runs/' + rec.id); } });
  }, { menu: 'reports-detail', permission: 'reports.hub', phase: 2, scopeKey: 'reports-detail' });

  /* ================= #/reports/runs/:id – bản ghi báo cáo ================= */
  const docTable = (h, rows) => `<table class="dp-table"><thead><tr>${h.map(x => `<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map((v, i) => `<td class="${i > 0 ? 'num' : ''}">${esc(v)}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${h.length}" class="c">Không có dữ liệu</td></tr>`}</tbody></table>`;
  const docPage = (rec, r, title, sub, kpi, headers, rows) => `<h3>TIMOHOUSE · ${esc(catOf(rec).toUpperCase())}</h3><h4>${esc(title)}</h4><p class="c">${esc(sub)}</p>${kpi.length ? `<table class="dp-table rp-kpi"><tbody>${kpi.map(k => `<tr><td>${esc(k[0])}</td><td class="num"><b>${esc(k[1])}</b></td><td>${esc(k[2] || '')}</td></tr>`).join('')}</tbody></table>` : ''}${docTable(headers, rows)}<p class="small" style="color:#555">Nguồn: ${esc(r.name)} (${esc(r.oi || '')}) · Lập lúc ${F.datetime(rec.createdAt)} bởi ${esc(Q.userName(rec.createdBy))} · Mã ${esc(rec.code)}</p>`;
  TH.router.register('/reports/runs/:id', (root, p, q) => {
    const rec = St.get('reportRuns', p.id);
    if (!rec) { root.innerHTML = U.card({ body: U.empty({ icon: 'file-text', title: 'Không tìm thấy bản ghi báo cáo', action: U.btn({ label: 'Về Trung tâm báo cáo', cls: 'btn-outline', act: 'back' }) }) }); U.bind(root, { back: () => TH.go('#/reports/hub') }); return; }
    if (!allowed(rec)) { root.innerHTML = U.card({ body: U.empty({ icon: 'lock', title: 'Không có quyền truy cập', text: 'Vai trò Kinh doanh chỉ được xem nhóm báo cáo bán hàng.' }) }); return; }
    const r = E().byKey(rec.type) || { name: rec.type, icon: 'file-text', tone: 'blue', oi: '' }; const bp = (rec.snapshot || {}).byPeriod || []; const last = bp[bp.length - 1] || { kpi: [], headers: [], rows: [] }; const multi = bp.length > 1;
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Trung tâm báo cáo', href: '#/reports/hub' }, { label: rec.code }]);
    const sub = periodText(rec) + ' · ' + scopeText(rec.params || {});
    const sumHeaders = ['Kỳ'].concat(last.kpi.map(k => k[0])); const sumRows = bp.map(x => [F.periodLabel(x.period)].concat(x.kpi.map(k => k[1])));
    const pages = (multi ? [docPage(rec, r, rec.name + ' – Tổng hợp theo kỳ', sub, [], sumHeaders, sumRows)] : []).concat(bp.map(x => docPage(rec, r, rec.name, F.periodLabel(x.period) + ' · ' + scopeText(rec.params || {}), x.kpi, x.headers, x.rows)));
    let zoom = 100;
    root.innerHTML = `${U.pageHead({ back: '#/reports/hub', title: esc(rec.name), phase: 2, chips: ' ' + U.chip(rec.code, 'blue') + ' ' + U.chip(catOf(rec), 'gray') + ' ' + U.chip(periodText(rec), 'purple') + ' ' + U.chip('Snapshot ' + F.datetime(rec.createdAt), 'green'), sub: esc(r.name) + ' · ' + esc(scopeText(rec.params || {})) + ' · ' + rec.rowCount + ' dòng · tạo bởi ' + esc(Q.userName(rec.createdBy)), acts: [U.btn({ label: 'Tải CSV', icon: 'download', cls: 'btn-primary', act: 'dl', attrs: { 'data-guide': 'report-csv' } }), U.btn({ label: 'Tạo lại', icon: 'refresh', cls: 'btn-outline', act: 'rerun', title: 'Tạo bản ghi mới cùng tham số với số liệu hiện tại' }), U.btn({ label: 'Xem live', icon: 'external-link', cls: 'btn-ghost', act: 'live', disabled: !E().isRunnable(r) }), U.btn({ label: 'Xóa', icon: 'trash', cls: 'btn-ghost', act: 'del' })] })}
    ${last.kpi.length ? `<div class="grid grid-${Math.min(4, last.kpi.length)} mb16 kpi-fit">${last.kpi.slice(0, 4).map((k, i) => U.kpi({ label: k[0] + (multi ? ' (' + F.periodShort(last.period) + ')' : ''), value: k[1], cap: k[2] || '', icon: r.icon, tone: ['blue', 'green', 'amber', 'purple'][i % 4] })).join('')}</div>` : ''}
    <div class="rp-detail"><div class="side-stack">${multi ? U.card({ title: 'Tổng hợp theo kỳ', icon: 'layers', sub: bp.length + ' kỳ · KPI từng kỳ', bodyCls: 'tight', body: E().table(sumHeaders, sumRows.map(row => row.map(esc))) }) : ''}
      ${U.card({ title: 'Xem trước báo cáo', icon: 'eye', sub: pages.length + ' trang · snapshot ' + F.datetime(rec.createdAt), cls: 'rp-doc', attrs: 'data-collapse-ready="1"', body: U.docPreview({ pages, stacked: true, zoom, fileName: rec.code + '.csv' }) })}</div>
      <div class="side-stack">${U.card({ title: 'Thông tin bản ghi', icon: 'info', body: U.kv([['Mã', esc(rec.code)], ['Loại báo cáo', esc(r.name)], ['Danh mục', esc(catOf(rec))], ['Kỳ', esc(periodText(rec))], ['Phạm vi', esc(scopeText(rec.params || {}))], ['Số dòng', String(rec.rowCount)], ['Người tạo', esc(Q.userName(rec.createdBy))], ['Thời điểm', F.datetime(rec.createdAt)], ['Tạo lại từ', rec.rerunOf && St.get('reportRuns', rec.rerunOf) ? U.link('#/reports/runs/' + rec.rerunOf, esc(St.get('reportRuns', rec.rerunOf).code)) : '-'], ['Ghi chú', esc(rec.note || '-')]], 'one') })}
      ${U.card({ title: 'Cột dữ liệu', icon: 'table', body: `<div class="row gap4 wrap">${last.headers.map(h => U.chip(h, 'gray')).join('')}</div><div class="small muted mt8">CSV gồm ${multi ? 'cột "Kỳ" + ' : ''}${last.headers.length} cột · ${rec.rowCount} dòng · mã hóa UTF-8 (mở được bằng Excel).</div>` })}
      ${r.metric ? U.card({ title: 'Công thức', icon: 'info', body: TH.metrics.info(r.metric) }) : U.note('info', 'Số liệu đã chốt', 'Bản ghi không đổi khi dữ liệu gốc thay đổi. Dùng "Tạo lại" để lập bản ghi mới với số liệu hiện tại.')}</div></div>`;
    const applyZoom = () => { const w = root.querySelector('.dp-page-wrap'); if (w) w.style.transform = 'scale(' + zoom / 100 + ')'; const z = root.querySelector('.dp-zoom'); if (z) z.textContent = zoom + '%'; };
    const sel = root.querySelector('[data-dp-page]'); if (sel) sel.addEventListener('change', e => { const pg = root.querySelector('.dp-page[data-dp-n="' + e.target.value + '"]'); if (pg) pg.scrollIntoView({ behavior: 'smooth', block: 'start' }); });
    U.bind(root, { dl: () => download(rec), 'dp-dl': () => download(rec), rerun: () => rerun(rec), del: () => remove(rec), live: () => TH.go(E().hrefOf(r) + '?period=' + last.period + (rec.params.buildingId ? '&buildingId=' + rec.params.buildingId : '')), 'dp-zoom-in': () => { zoom = Math.min(160, zoom + 10); applyZoom(); }, 'dp-zoom-out': () => { zoom = Math.max(60, zoom - 10); applyZoom(); }, 'dp-hand': () => ok('Kéo trang', 'Cuộn trong khung xem trước (mô phỏng)') });
    X.touchReport(rec.type);
  }, { menu: 'reports-detail', permission: 'reports.hub', phase: 2, scopeKey: 'reports-detail' });
})(window.TH);
