/* Spec v1.8 §4.28 / §12.23 – Báo cáo Phase 1: Report A (#/reports/building-profit), Report B T/S/G (#/reports/business-summary), Kỳ báo cáo Open→Reviewing→Locked→Reopened (#/reports/periods),
   Đối soát golden dataset (#/reports/reconcile), Metric Registry (#/reports/metrics). Mọi số có metric_code + drill-down về chứng từ; kỳ đã khóa đọc snapshot. */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, E = TH.reportP1, M = TH.metrics, esc = F.esc, C = TH.chart;
  const ok = (m, s) => U.toast('ok', m, s);
  const fmt = (code, v) => M.fmt(M.P1_BY[code] || { unit: 'MONEY' }, v);
  const statusChip = (code) => M.statusChip(M.effectiveStatus(code));
  const periodSel = (period, extra = {}) => U.field({ label: 'Kỳ báo cáo', input: U.select({ name: 'period', value: period, options: Q.reportPeriods().map(p => [p, F.periodLabel(p) + (Q.reportPeriod(p) ? ' · ' + Q.label('reportPeriod', Q.reportPeriod(p).status) : '')]), attrs: Object.assign({ 'data-on': 'f' }, extra) }) });
  const periodStrip = (period) => { const rp = Q.reportPeriod(period); const st = rp ? rp.status : 'OPEN'; const steps = [{ label: 'Open', date: rp ? F.datetime((rp.history || []).find(h => h.type === 'open') ? (rp.history || []).find(h => h.type === 'open').at : rp.createdAt) : '' }, { label: 'Reviewing', date: rp && rp.cutoffAt ? 'cutoff ' + F.datetime(rp.cutoffAt) : '' }, { label: 'Locked', date: rp && rp.lockedAt ? F.datetime(rp.lockedAt) + ' · ' + Q.userName(rp.lockedBy) : '' }]; const cur = st === 'OPEN' ? 0 : st === 'REVIEWING' ? 1 : st === 'LOCKED' ? 3 : 1; return `<div class="row gap8 mb8" style="align-items:center;flex-wrap:wrap">${Q.chip('reportPeriod', st)}${rp ? `<span class="small muted">${esc(rp.code)} · metric ${esc(rp.metricVersion || M.version())}${rp.allocationVersion ? ' · allocation ' + esc(rp.allocationVersion) : ''}</span>` : '<span class="small muted">Chưa mở kỳ báo cáo – số liệu tính sống</span>'}${st === 'REOPENED' ? U.chip('Mở lại: ' + esc(rp.reopenReason || ''), 'red') : ''}<a class="link small" href="#/reports/periods">Quản lý kỳ →</a></div>${U.stepperStatus(steps, cur)}`; };
  const frozenNote = (r) => r.frozen ? U.note('ok', 'Snapshot đã khóa', 'Số liệu freeze lúc ' + F.datetime(r.snapshot.generatedAt) + ' bởi ' + esc(Q.userName(r.snapshot.generatedBy)) + ' · metric ' + esc((r.snapshot.sourceVersion || {}).metricVersion || '') + ' · loại tòa <b>' + esc(r.buildingType || '') + '</b> · share snapshot ' + ((r.shares && r.shares.rows) || []).length + ' cổ đông. Dữ liệu master/assignment đổi sau khóa không làm đổi báo cáo (§12.23.13). ' + liveDiff(r)) : U.note('info', 'Số liệu tính sống', 'Kỳ chưa khóa – mỗi lần mở tính lại từ Invoice Line / Deposit Ledger / Expense Allocation / Payroll Cost Allocation / Building Share. Khóa kỳ ở <a class="link" href="#/reports/periods">Kỳ báo cáo</a> để freeze snapshot.');
  const liveDiff = (r) => { try { const live = E.compute(r.period, r.buildingId).values; const n = M.P1.filter(d => Math.abs(Number(live[d.code] || 0) - Number(r.values[d.code] || 0)) > 0.005).length; return n ? '<span class="chip amber">Dữ liệu sống hiện lệch ' + n + ' chỉ tiêu – báo cáo vẫn giữ snapshot</span>' : '<span class="chip green">Dữ liệu sống khớp snapshot</span>'; } catch (e) { return ''; } };
  /* ---- Drill-down modal §12.23.10 ---- */
  const drillModal = (period, bid, code) => {
    const d = E.drill(period, bid, code); const def = d.def || {}; const b = Q.building(bid);
    const rows = d.rows || []; const total = F.sum(rows, x => Number(x.amount || 0));
    const body = `${M.info(code)}<div class="row gap8 mb8 mt8" style="align-items:center"><b>${esc(b.name || '')} · ${F.periodLabel(period)}</b><span class="chip ${d.frozen ? 'green' : 'gray'}">${d.frozen ? 'Snapshot' : 'Tính sống'}</span><span class="grow"></span><b>${fmt(code, d.value)}</b></div>
      ${d.composite ? U.note('info', 'Metric tổng hợp', 'Bấm vào metric thành phần để drill tiếp: Report → Metric → Tòa → Source entity → Chứng từ.') : ''}
      <div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>#</th><th>${d.composite ? 'Metric thành phần' : 'Chứng từ / đối tượng'}</th><th>Chuỗi drill-down</th><th class="num">${def.unit === 'COUNT' ? 'Số' : 'Số tiền'}</th><th></th></tr></thead><tbody>${rows.map((x, i) => `<tr><td>${i + 1}</td><td>${d.composite ? `<a class="link bold" data-act="drill" data-code="${esc(x.metric)}" href="javascript:void(0)">${esc(x.label)}</a><div class="xs muted"><code>${esc(x.sub)}</code></div>` : `<b>${esc(x.label)}</b><div class="xs muted">${esc(x.sub || '')}</div>`}</td><td class="xs muted">${d.composite ? statusChip(x.metric) : (x.chain || []).map(esc).join(' → ')}</td><td class="num">${d.composite ? fmt(x.metric, x.amount) : (def.unit === 'COUNT' ? x.amount : F.vnd(Math.round(Number(x.amount || 0) * 100) / 100))}</td><td>${!d.composite && x.href ? `<a class="btn btn-xs btn-outline" href="${esc(x.href)}">${I('external-link')} Mở</a>` : ''}</td></tr>`).join('') || `<tr><td colspan="5" class="muted tc">Không có chứng từ trong kỳ</td></tr>`}</tbody>${!d.composite && rows.length ? `<tfoot><tr class="dist-total"><td colspan="3">Tổng ${rows.length} dòng${(def.unit !== 'COUNT' && Math.abs(total - Number(d.value || 0)) > 0.5) ? ' (snapshot cắt còn 80 dòng đầu)' : ''}</td><td class="num">${def.unit === 'COUNT' ? rows.length : F.vnd(Math.round(total * 100) / 100)}</td><td></td></tr></tfoot>` : ''}</table></div>`;
    const m = U.modal({ title: 'Drill-down ' + esc(def.label || code) + ' <code>' + esc(code) + '</code>', wide: true, size: 'lg', body, footer: U.btn({ label: 'Đóng', act: 'c' }) });
    U.bind(m.el, { c: () => m.close(), drill: (el) => { m.close(); drillModal(period, bid, el.dataset.code); } });
  };
  TH.pages.reportDrill = drillModal;
  const metricRow = (d, valueHtml, extra = '') => `<tr data-code="${esc(d.code)}"><td><b>${esc(d.excel && d.excel !== d.label ? d.label + ' (' + d.excel + ')' : d.label)}</b><div class="xs muted"><code>${esc(d.code)}</code> · ${esc(d.source || '')}${d.dateBasis ? ' · ' + esc(d.dateBasis) : ''}</div></td>${valueHtml}<td>${statusChip(d.code)}${d.question ? ' <span class="xs muted">' + esc(d.question) + '</span>' : ''}</td>${extra}</tr>`;
  const groupRow = (g, span) => `<tr class="grp-row"><td colspan="${span}" style="background:var(--gray-50);font-weight:700">${esc(g)}</td></tr>`;

  /* ================= Report A ================= */
  TH.router.register('/reports/building-profit', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Báo cáo chi tiết tòa' }]);
    const period = q.period || St.state.meta.period; const bs = St.where('buildings', b => !b.stub); const bid = q.buildingId || (bs.find(b => b.code === 'G1') || bs[0] || {}).id;
    if (!bid) { root.innerHTML = U.pageHead({ title: 'Báo cáo chi tiết tòa' }) + U.empty({ title: 'Chưa có tòa' }); return; }
    const r = E.building(period, bid); const v = r.values; const golden = Q.goldenDatasets().find(g => g.reportType === 'A' && g.period === period && g.buildingCode === r.building.code);
    const canDist = TH.auth.can('distributions.manage') && r.frozen && Q.reportPeriod(period) && Q.reportPeriod(period).status === 'LOCKED'; const dist = Q.profitDistributions({ period, buildingId: bid }).find(d => d.status !== 'cancelled');
    root.innerHTML = `${U.pageHead({ title: 'Báo cáo chi tiết tòa (Report A)', sub: 'Mẫu "Báo cáo tháng 6" §12.23.3: doanh thu → cọc/hoàn cọc → số phòng → tiền nhà → dịch vụ → giá vốn → CPBH/VH → tổng chi phí → LN gộp → LN ròng → tỷ lệ → bảng cổ phần. Không nhập số tổng – mọi dòng drill-down được về chứng từ.', acts: [U.btn({ label: 'Xuất layout Excel (CSV)', icon: 'download', cls: 'btn-primary', act: 'export', attrs: { 'data-guide': 'ra-export' } }), golden ? U.btn({ label: 'Đối soát golden', icon: 'check-square', cls: 'btn-outline', act: 'recon', attrs: { 'data-guide': 'ra-recon' } }) : '', U.btn({ label: 'Báo cáo T/S/G', icon: 'layers', cls: 'btn-outline', act: 'rb' }), U.btn({ label: 'Metric Registry', icon: 'book', cls: 'btn-ghost', act: 'metrics' })] })}
    ${U.filterbar([periodSel(period), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: bid, options: bs.map(b => [b.id, b.name + ' (' + (Q.buildingTypeAt ? Q.buildingTypeAt(b.id, r.to) : b.buildingType || '') + ')']), attrs: { 'data-on': 'f' } }) })])}
    ${periodStrip(period)}${frozenNote(r)}
    <div class="grid grid-4 mb16 kpi-fit mt12">${U.kpi({ label: 'Tổng doanh thu', value: F.vnd(Math.round(v.TOTAL_REVENUE || 0)), cap: 'Tiền phòng ' + F.short(v.RENT_REVENUE || 0) + ' · DV ' + F.short(v.SERVICE_REVENUE || 0) + ' ' + (M.effectiveStatus('TOTAL_REVENUE') === 'CONFIRMED' ? '' : '· chờ chốt Q-RPT-001'), icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Giá vốn (COGS)', value: F.vnd(Math.round(v.COGS || 0)), cap: 'GV/DT ' + fmt('COGS_OVER_REVENUE', v.COGS_OVER_REVENUE), icon: 'package', tone: 'amber' })}${U.kpi({ label: 'Lợi nhuận gộp', value: F.vnd(Math.round(v.GROSS_PROFIT || 0)), cap: 'LNG/DT ' + fmt('GROSS_MARGIN', v.GROSS_MARGIN), icon: 'trending-up', tone: 'green' })}${U.kpi({ label: 'Lợi nhuận ròng', value: F.vnd(Math.round(v.NET_PROFIT || 0)), cap: 'LNR/DT ' + fmt('NET_MARGIN', v.NET_MARGIN) + ' · tổng CP ' + F.short(v.TOTAL_COST || 0), icon: 'bar-chart', tone: (v.NET_PROFIT || 0) >= 0 ? 'purple' : 'red', valueCls: (v.NET_PROFIT || 0) < 0 ? 'red' : '' })}</div>
    <div class="two-col"><div>${U.card({ title: 'Báo cáo tháng ' + F.periodShort(period) + ' – ' + esc(r.building.name || ''), icon: 'file-text', sub: 'Bấm kính lúp để drill-down (Report → Metric → Tòa → Source entity → Chứng từ)', bodyCls: 'tight', attrs: 'data-guide="ra-table"', body: `<div class="tbl-wrap"><table class="tbl compact" id="ra-tbl"><thead><tr><th>Dòng báo cáo</th><th class="num">Giá trị</th><th>Trạng thái metric</th><th></th></tr></thead><tbody>${E.layoutA().map(grp => groupRow(grp.group, 4) + grp.metrics.map(d => metricRow(d, `<td class="num"><b>${fmt(d.code, v[d.code])}</b>${(r.drill[d.code] || []).length ? '<div class="xs muted">' + (r.drill[d.code] || []).length + ' chứng từ</div>' : ''}</td>`, `<td>${U.btn({ label: '', icon: 'search', size: 'btn-xs', cls: 'btn-ghost', act: 'drill', attrs: { 'data-code': d.code, 'data-guide': d.code === 'RENT_REVENUE' ? 'ra-drill' : undefined, title: 'Drill-down' } })}</td>`)).join('')).join('')}</tbody></table></div>` })}</div>
    <aside class="side-stack">${U.card({ title: 'Cổ đông / vốn / chia lợi nhuận', icon: 'users', sub: '§12.23.9 – tỷ lệ snapshot tại ' + F.date(r.to) + (r.frozen ? ' (đã freeze khi khóa)' : ' (Building Share hiệu lực)'), bodyCls: 'tight', attrs: 'data-guide="ra-shares"', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Cổ đông</th><th class="num">Tỷ lệ %</th><th class="num">Vốn</th><th class="num">LN gộp × %</th><th class="num">LN ròng × %</th><th class="num">Tổng nhận</th></tr></thead><tbody>${(r.shares.rows || []).map(s => `<tr><td>${esc(s.name)}<div class="xs muted">${esc(s.code)} · từ ${F.date(s.effectiveFrom)}</div></td><td class="num">${s.percentage}%</td><td class="num">${F.vnd(s.capital)}</td><td class="num">${F.vnd(Math.round(s.grossShare))}</td><td class="num"><b>${F.vnd(Math.round(s.netShare))}</b></td><td class="num">${F.vnd(Math.round(s.totalReceive))}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Tòa chưa cấu hình cổ phần – <a class="link" href="#/investment/shares?buildingId=' + bid + '">cấu hình</a></td></tr>'}</tbody><tfoot><tr class="dist-total"><td>Tổng ${(r.shares.rows || []).length} cổ đông ${r.shares.ok ? U.chip('= 100%', 'green') : U.chip((r.shares.totalPct || 0) + '% ≠ 100%', 'red')}</td><td class="num">${r.shares.totalPct || 0}%</td><td class="num">${F.vnd(F.sum(r.shares.rows || [], s => s.capital))}</td><td class="num">${F.vnd(Math.round(F.sum(r.shares.rows || [], s => s.grossShare)))}</td><td class="num">${F.vnd(Math.round(F.sum(r.shares.rows || [], s => s.netShare)))}</td><td class="num">${F.vnd(Math.round(F.sum(r.shares.rows || [], s => s.totalReceive)))}</td></tr></tfoot></table></div><div class="row gap8 mt8" style="padding:0 12px 12px">${U.kv([['LNR/GV', fmt('NET_PROFIT_OVER_COGS', v.NET_PROFIT_OVER_COGS)], ['CP/LNG', fmt('TOTAL_COST_OVER_GROSS_PROFIT', v.TOTAL_COST_OVER_GROSS_PROFIT)]], 'one')}</div>`, actions: (dist ? `<a class="btn btn-sm btn-outline" href="#/investment/shareholders?tab=profit&period=${period}&buildingId=${bid}">${I('chart-pie')} ${esc(dist.code)} ${Q.chip('profitDist', dist.status)}</a>` : canDist ? U.btn({ label: 'Generate phân phối LN', icon: 'chart-pie', size: 'btn-sm', cls: 'btn-primary', act: 'gen-dist', attrs: { 'data-guide': 'ra-gen-dist' } }) : '') })}
    ${U.card({ title: 'Nguồn dữ liệu §4.28.3', icon: 'database', body: `<div class="small">${U.kv([['Invoice Line', 'Tiền phòng, dịch vụ'], ['Contract Event / Room Status History', 'Phòng mới, phá HĐ, phòng trống'], ['Deposit Ledger / Refund Case', 'Cọc mới, cọc giữ lại, hoàn cọc'], ['Expense / Expense Allocation', 'Thuê nhà, thiết bị, giá gốc DV, hoa hồng, marketing, sửa chữa, khác'], ['Payroll Cost Allocation', 'Chi phí lương (bảng lương đã khóa)'], ['Building Share / Capital', 'Tỷ lệ, vốn, LN được chia']], 'one')}</div>` })}
    ${U.card({ title: 'Cơ cấu chi phí', icon: 'pie-chart', body: C.donutLegend([{ label: 'Giá vốn', value: Math.max(0, v.COGS || 0), color: '#F59E0B', text: F.short(v.COGS || 0) }, { label: 'CPBH/VH', value: Math.max(0, v.OPERATING_SELLING_COST || 0), color: '#2563EB', text: F.short(v.OPERATING_SELLING_COST || 0) }, { label: 'LN ròng', value: Math.max(0, v.NET_PROFIT || 0), color: '#16A34A', text: ((v.NET_PROFIT || 0) < 0 ? '−' : '') + F.short(Math.abs(Math.round(v.NET_PROFIT || 0))) }], 130, F.short(v.TOTAL_REVENUE || 0).replace(' tỷ', 'B'), 'DT') })}</aside></div>`;
    U.onChange(root, { f: () => TH.router.applyFilter({ period, buildingId: bid }, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { export: () => { X.exportReportA(period, bid); ok('Đã xuất Report A theo layout Excel'); }, recon: () => TH.go('#/reports/reconcile?golden=' + golden.id), rb: () => TH.go('#/reports/business-summary?period=' + period), metrics: () => TH.go('#/reports/metrics'), drill: (el) => drillModal(period, bid, el.dataset.code), 'gen-dist': async () => { const c = await U.confirm({ title: 'Generate phân phối lợi nhuận ' + F.periodShort(period) + '?', text: 'Lợi nhuận được phân phối = NET_PROFIT snapshot ' + F.vnd(Math.round(v.NET_PROFIT || 0)) + ' × tỷ lệ cổ phần snapshot của từng cổ đông (§4.32). Có thể nhập số khác theo quyết định.', body: U.field({ label: 'Lợi nhuận được phân phối (để trống = NET_PROFIT snapshot)', input: U.money({ name: 'profit', value: '' }) }), ok: 'Generate' }); if (!c) return; try { const d = X.generateDistribution(period, bid, { profit: c.profit ? c.profit : null }); ok('Đã tạo bảng phân phối ' + d.code, F.vnd(d.profitDistributable) + ' · ' + d.lines.length + ' cổ đông'); TH.go('#/investment/shareholders?tab=profit&period=' + period + '&buildingId=' + bid); } catch (e) { U.toast('error', e.message); } } });
  }, { menu: 'report-a', permission: 'reports.view' });

  /* ================= Report B – T/S/G ================= */
  TH.router.register('/reports/business-summary', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Báo cáo kinh doanh T/S/G' }]);
    const period = q.period || St.state.meta.period; const s = E.summary(period); const v = s.values; const g = s.groups;
    const golden = Q.goldenDatasets().find(x => x.reportType === 'B' && x.period === period);
    const cell = (code, k) => { const val = (s.tsg[code] || {})[k]; return `<td class="num"><a class="link" data-act="grp" data-code="${esc(code)}" data-g="${k}" href="javascript:void(0)">${fmt(code, val)}</a></td>`; };
    const addCheck = M.P1.filter(d => d.additive).every(d => Math.abs(Number(v[d.code] || 0) - (Number((s.tsg[d.code] || {}).T || 0) + Number((s.tsg[d.code] || {}).S || 0) + Number((s.tsg[d.code] || {}).G || 0))) < 0.01);
    root.innerHTML = `${U.pageHead({ title: 'Báo cáo kinh doanh toàn hệ thống (Report B)', sub: 'Mẫu "Báo cáo kinh doanh Tháng 8" §12.23.8: cùng nguồn với báo cáo từng tòa, loại tòa resolve theo lịch sử tại kỳ, chi phí chung & lương allocation trước khi aggregate; TOTAL = T + S + G cho metric additive; tỷ lệ tính lại từ tử/mẫu.', acts: [U.btn({ label: 'Xuất layout Excel (CSV)', icon: 'download', cls: 'btn-primary', act: 'export', attrs: { 'data-guide': 'rb-export' } }), golden ? U.btn({ label: 'Đối soát golden', icon: 'check-square', cls: 'btn-outline', act: 'recon' }) : '', U.btn({ label: 'Kỳ báo cáo', icon: 'lock', cls: 'btn-outline', act: 'periods' })] })}
    ${U.filterbar([periodSel(period)])}${periodStrip(period)}
    ${s.frozen ? U.note('ok', 'Snapshot đã khóa', 'Freeze lúc ' + F.datetime(s.snapshot.generatedAt) + ' · ' + s.buildings.length + ' tòa · metric ' + esc((s.snapshot.sourceVersion || {}).metricVersion || '')) : U.note('info', 'Số liệu tính sống', s.buildings.length + ' tòa đang khai thác trong kỳ; loại tòa lấy từ Building Type History tại ' + F.date(Q.periodEndDate(period)) + ' (không dùng loại hiện tại).')}
    <div class="grid grid-4 mb16 kpi-fit mt12">${['T', 'S', 'G'].map(k => U.kpi({ label: 'Nhà ' + k, value: F.vnd(Math.round((s.tsg.TOTAL_REVENUE || {})[k] || 0)), cap: g[k].length + ' tòa · LN ròng ' + F.short((s.tsg.NET_PROFIT || {})[k] || 0) + ' · LNR/DT ' + fmt('NET_MARGIN', (s.tsg.NET_MARGIN || {})[k]), icon: 'building', tone: { T: 'blue', S: 'amber', G: 'green' }[k] })).join('')}${U.kpi({ label: 'Toàn hệ thống', value: F.vnd(Math.round(v.TOTAL_REVENUE || 0)), cap: s.buildings.length + ' tòa · LN ròng ' + F.short(v.NET_PROFIT || 0) + ' · LNR/DT ' + fmt('NET_MARGIN', v.NET_MARGIN) + ' ' + (addCheck ? '· TOTAL = T + S + G ✓' : '· ⚠ TOTAL ≠ T + S + G'), icon: 'layers', tone: 'purple' })}</div>
    ${U.card({ title: 'Báo cáo kinh doanh ' + F.periodLabel(period), icon: 'layers', sub: 'Bấm vào số của nhóm để xem danh sách tòa → Report A từng tòa', bodyCls: 'tight', attrs: 'data-guide="rb-table"', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Dòng báo cáo</th><th class="num">Total</th><th class="num">Nhà T (${g.T.length})</th><th class="num">Nhà S (${g.S.length})</th><th class="num">Nhà G (${g.G.length})</th><th>Trạng thái</th></tr></thead><tbody><tr><td><b>Số tòa</b></td><td class="num">${s.buildings.length}</td><td class="num">${g.T.length}</td><td class="num">${g.S.length}</td><td class="num">${g.G.length}</td><td>${U.chip('Building Type History', 'gray')}</td></tr>${E.layoutA().map(grp => groupRow(grp.group, 6) + grp.metrics.map(d => metricRow(d, `<td class="num"><b>${fmt(d.code, v[d.code])}</b></td>${cell(d.code, 'T')}${cell(d.code, 'S')}${cell(d.code, 'G')}`)).join('')).join('')}</tbody></table></div>` })}
    ${U.card({ title: 'Tòa trong kỳ (' + s.buildings.length + ')', icon: 'building', cls: 'mt16', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Tòa</th><th>Loại tại kỳ</th><th class="num">Tổng DT</th><th class="num">COGS</th><th class="num">CPBH/VH</th><th class="num">LN ròng</th><th class="num">LNR/DT</th><th></th></tr></thead><tbody>${s.buildings.map(b => `<tr><td><b>${esc(b.name)}</b> <span class="xs muted">${esc(b.code || '')}</span></td><td>${U.chip('Nhà ' + b.type, { T: 'blue', S: 'amber', G: 'green' }[b.type] || 'gray')}</td><td class="num">${F.vnd(Math.round(b.values.TOTAL_REVENUE || 0))}</td><td class="num">${F.vnd(Math.round(b.values.COGS || 0))}</td><td class="num">${F.vnd(Math.round(b.values.OPERATING_SELLING_COST || 0))}</td><td class="num ${(b.values.NET_PROFIT || 0) < 0 ? 'red' : ''}">${F.vnd(Math.round(b.values.NET_PROFIT || 0))}</td><td class="num">${fmt('NET_MARGIN', b.values.NET_MARGIN)}</td><td><a class="btn btn-xs btn-outline" href="#/reports/building-profit?period=${period}&buildingId=${b.buildingId}">${I('file-text')} Report A</a></td></tr>`).join('')}</tbody></table></div>` })}`;
    U.onChange(root, { f: () => TH.router.applyFilter({ period }, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { export: () => { X.exportReportB(period); ok('Đã xuất Report B (Total/T/S/G)'); }, recon: () => TH.go('#/reports/reconcile?golden=' + golden.id), periods: () => TH.go('#/reports/periods'), grp: (el) => { const k = el.dataset.g, code = el.dataset.code; const list = g[k]; const d = M.P1_BY[code]; const m = U.modal({ title: 'Nhà ' + k + ' · ' + esc(d.label) + ' <code>' + esc(code) + '</code>', size: 'lg', body: `${M.info(code)}<div class="tbl-wrap mt8"><table class="tbl compact"><thead><tr><th>Tòa</th><th class="num">Giá trị</th><th></th></tr></thead><tbody>${list.map(b => `<tr><td>${esc(b.name)}</td><td class="num">${fmt(code, b.values[code])}</td><td><a class="btn btn-xs btn-outline" href="#/reports/building-profit?period=${period}&buildingId=${b.buildingId}">${I('search')} Drill tòa</a></td></tr>`).join('') || '<tr><td colspan="3" class="muted tc">Không có tòa loại ' + k + ' trong kỳ</td></tr>'}</tbody><tfoot><tr class="dist-total"><td>Nhóm ${k}</td><td class="num">${fmt(code, (s.tsg[code] || {})[k])}</td><td>${d.additive ? 'Σ tòa' : 'Tính lại từ tử/mẫu nhóm'}</td></tr></tfoot></table></div>`, footer: U.btn({ label: 'Đóng', act: 'c' }) }); U.bind(m.el, { c: () => m.close() }); } });
  }, { menu: 'report-b', permission: 'reports.view' });

  /* ================= Kỳ báo cáo ================= */
  TH.router.register('/reports/periods', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Kỳ báo cáo' }]);
    const rows = Q.reportPeriodRows(); const cur = St.state.meta.period; const canLock = TH.auth.can('reports.lock'), canReopen = TH.auth.can('reports.reopen');
    root.innerHTML = `${U.pageHead({ title: 'Kỳ báo cáo & snapshot', sub: 'Open → Reviewing → Locked → Reopened (§12.23.13). Khi khóa: freeze Metric Definition Version, Allocation Version, loại tòa theo kỳ, Payroll Cost Allocation, Building Share Snapshot và toàn bộ metric value; mở lại bắt buộc có lý do/audit.', acts: [U.btn({ label: 'Report A', icon: 'file-text', cls: 'btn-outline', act: 'ra' }), U.btn({ label: 'Report B', icon: 'layers', cls: 'btn-outline', act: 'rb' })] })}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Kỳ đã khóa', value: rows.filter(r => r.status === 'LOCKED').length, cap: rows.filter(r => r.snapA).reduce((a, r) => a + r.snapA, 0) + ' snapshot tòa', icon: 'lock', tone: 'green' })}${U.kpi({ label: 'Đang review', value: rows.filter(r => r.status === 'REVIEWING').length, cap: 'Chờ kế toán khóa', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Đã mở lại', value: rows.filter(r => r.status === 'REOPENED').length, cap: 'Cần review & khóa lại', icon: 'refresh', tone: 'red' })}${U.kpi({ label: 'Metric version', value: M.version(), cap: M.defs1().filter(d => d.status === 'NEED_BUSINESS_CONFIRMATION').length + ' metric chờ chốt', icon: 'book', tone: 'blue' })}</div>
    ${U.card({ title: 'Kỳ báo cáo (' + rows.length + ')', icon: 'calendar', bodyCls: 'tight', attrs: 'data-guide="rp-table"', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Kỳ</th><th>Trạng thái</th><th>Cutoff</th><th>Khóa</th><th>Freeze</th><th class="num">Snapshot</th><th class="num">Phân phối LN</th><th>Thao tác</th></tr></thead><tbody>${rows.map(r => { const rp = r.rp || {}; const st = r.status; return `<tr><td><b>${F.periodLabel(r.period)}</b>${r.period === cur ? ' ' + U.chip('Kỳ hiện tại', 'blue') : ''}<div class="xs muted">${esc(rp.code || 'Chưa mở')}</div></td><td>${Q.chip('reportPeriod', st)}</td><td class="xs">${rp.cutoffAt ? F.datetime(rp.cutoffAt) : '—'}</td><td class="xs">${rp.lockedAt ? F.datetime(rp.lockedAt) + '<br>' + esc(Q.userName(rp.lockedBy)) : '—'}${rp.reopenReason ? '<div class="xs red">Mở lại: ' + esc(rp.reopenReason) + '</div>' : ''}</td><td class="xs muted">${rp.lockedAt ? 'metric ' + esc(rp.metricVersion || '') + '<br>alloc ' + esc(rp.allocationVersion || '-') + '<br>' + (rp.buildingCount || r.snapA) + ' tòa · share snapshot' : '—'}</td><td class="num">${r.snapA ? r.snapA + ' A + ' + r.snapB + ' B' : '—'}</td><td class="num">${r.dists || '—'}</td><td>${U.rowActions([st === 'OPEN' || st === 'REOPENED' ? U.btn({ label: 'Gửi review', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'review', attrs: { 'data-p': r.period, 'data-guide': 'rp-review' } }) : '', st === 'REVIEWING' && canLock ? U.btn({ label: 'Khóa kỳ', icon: 'lock', size: 'btn-sm', cls: 'btn-primary', act: 'lock', attrs: { 'data-p': r.period, 'data-guide': 'rp-lock' } }) : '', st === 'REVIEWING' ? U.btn({ label: 'Trả lại', icon: 'undo', size: 'btn-sm', cls: 'btn-ghost', act: 'return', attrs: { 'data-p': r.period } }) : '', st === 'LOCKED' && canReopen ? U.btn({ label: 'Mở lại', icon: 'unlock', size: 'btn-sm', cls: 'btn-ghost', act: 'reopen', attrs: { 'data-p': r.period, 'data-guide': 'rp-reopen' } }) : '', U.btn({ label: 'Lịch sử', icon: 'history', size: 'btn-sm', cls: 'btn-ghost', act: 'hist', attrs: { 'data-p': r.period } }), `<a class="btn btn-sm btn-ghost" href="#/reports/business-summary?period=${r.period}">${I('eye')} Xem</a>`])}</td></tr>`; }).join('')}</tbody></table></div>` })}
    ${U.note('info', 'Quy tắc', 'Kỳ Locked không tự thay đổi khi master data / assignment / cổ phần thay đổi sau đó (AC 16). Phân phối lợi nhuận chỉ generate từ kỳ Locked (event PROFIT_REPORT_LOCKED). Không mở lại kỳ đã có phân phối LN đã xác nhận.')}`;
    U.bind(root, { ra: () => TH.go('#/reports/building-profit'), rb: () => TH.go('#/reports/business-summary'), review: (el) => { try { X.reviewReportPeriod(el.dataset.p); ok('Kỳ ' + F.periodShort(el.dataset.p) + ' → Đang review', 'Cutoff ' + F.datetime(F.nowISO())); } catch (e) { U.toast('error', e.message); } }, lock: async (el) => { const period = el.dataset.p; const n = E.liveBuildings(period).length; const c = await U.confirm({ title: 'Khóa kỳ báo cáo ' + F.periodShort(period) + '?', text: 'Sinh ' + n + ' snapshot Report A + 1 snapshot T/S/G; freeze metric ' + M.version() + ', allocation rule, loại tòa theo kỳ, Payroll Cost Allocation và share snapshot. Sau khóa, thay đổi dữ liệu không làm đổi báo cáo.', ok: 'Khóa kỳ' }); if (!c) return; try { const rp = X.lockReportPeriod(period); ok('Đã khóa kỳ ' + rp.code, rp.buildingCount + ' tòa · PROFIT_REPORT_LOCKED'); } catch (e) { U.toast('error', e.message); } }, return: async (el) => { const c = await U.confirm({ title: 'Trả lại kỳ ' + F.periodShort(el.dataset.p), text: 'Có lỗi dữ liệu → về Open để sửa.', body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Thiếu hóa đơn tòa…' }) }), ok: 'Trả lại' }); if (!c) return; try { X.returnReportPeriod(el.dataset.p, c.reason); ok('Đã trả lại kỳ'); } catch (e) { U.toast('error', e.message); } }, reopen: async (el) => { const c = await U.confirm({ title: 'Mở lại kỳ ' + F.periodShort(el.dataset.p) + '?', text: 'Quyền đặc biệt – bắt buộc ghi lý do (audit). Kỳ về Reopened, phải review & khóa lại; snapshot cũ vẫn hiển thị cho tới khi khóa lại.', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Bổ sung chi phí thuê nhà tháng…' }) }), ok: 'Mở lại' }); if (!c) return; try { X.reopenReportPeriod(el.dataset.p, c.reason); ok('Đã mở lại kỳ – có audit'); } catch (e) { U.toast('error', e.message); } }, hist: (el) => { const rp = Q.reportPeriod(el.dataset.p); const m = U.drawer({ title: 'Lịch sử kỳ ' + F.periodLabel(el.dataset.p), body: rp ? U.timeline((rp.history || []).slice().reverse().map(h => ({ when: F.datetime(h.at), title: ({ open: 'Mở kỳ', review: 'Gửi review', return: 'Trả lại', lock: 'Khóa kỳ', reopen: 'Mở lại' })[h.type] || h.type, sub: (h.text || '') + (h.byName ? ' · ' + h.byName : ''), icon: h.type === 'lock' ? 'lock' : h.type === 'reopen' ? 'unlock' : 'activity', color: h.type === 'lock' ? 'green' : h.type === 'reopen' ? 'red' : 'blue' }))) : U.empty({ title: 'Kỳ chưa mở' }), footer: U.btn({ label: 'Đóng', act: 'c' }) }); U.bind(m.el, { c: () => m.close() }); } });
  }, { menu: 'report-periods', permission: 'reports.view' });

  /* ================= Đối soát golden dataset ================= */
  TH.router.register('/reports/reconcile', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Đối soát Excel (golden)' }]);
    const gs = Q.goldenDatasets(); const gid = q.golden || (gs[0] || {}).id; const r = gid ? E.reconcile(gid) : null;
    const cnt = (r && r.count) || {}; const S = E.RECON_STATUS;
    root.innerHTML = `${U.pageHead({ title: 'Đối soát với workbook nguồn (Golden Dataset)', sub: 'Mỗi kỳ migration/test xuất bảng metric_code / excel_value / system_value / difference / % / status / note (§12.23.12). Count phải khớp tuyệt đối; tiền theo rule làm tròn; không dùng tolerance để che lỗi mapping.', acts: [U.btn({ label: 'Xuất bảng đối soát', icon: 'download', cls: 'btn-primary', act: 'export', disabled: !r, attrs: { 'data-guide': 'rc-export' } }), r && r.building ? `<a class="btn btn-outline" href="#/reports/building-profit?period=${r.golden.period}&buildingId=${r.building.id}">${I('file-text')} Report A ${esc(r.building.code)}</a>` : r ? `<a class="btn btn-outline" href="#/reports/business-summary?period=${r.golden.period}">${I('layers')} Report B</a>` : ''] })}
    ${U.filterbar([U.field({ label: 'Golden dataset', input: U.select({ name: 'golden', value: gid, options: gs.map(g => [g.id, g.name]), attrs: { 'data-on': 'f' } }), cls: 'wide' })])}
    ${r ? `${U.note(r.golden.reportType === 'A' ? 'info' : 'warn', esc(r.golden.name), esc(r.golden.sourceSheet || '') + (r.golden.note ? ' · ' + esc(r.golden.note) : '') + (r.golden.reportType === 'A' ? ' · ' + (r.golden.shareholderCount || 0) + ' cổ đông = ' + (r.golden.shareTotal || 0) + '%' : '') + ' · số liệu hệ thống ' + (r.frozen ? 'từ snapshot đã khóa' : 'tính sống'))}
    <div class="grid grid-5 mb16 kpi-fit" data-guide="rc-kpis">${Object.keys(S).map(k => U.kpi({ mini: true, label: S[k][0], value: cnt[k] || 0, cap: k, icon: k === 'MATCH' ? 'check-circle' : k === 'NEED_BUSINESS_CONFIRMATION' ? 'help-circle' : 'alert-triangle', tone: S[k][1] === 'green' ? 'green' : S[k][1] === 'red' ? 'red' : S[k][1] === 'blue' ? 'blue' : 'amber' })).join('')}</div>
    ${U.card({ title: 'Bảng đối soát (' + r.rows.length + ' metric)', icon: 'check-square', bodyCls: 'tight', attrs: 'data-guide="rc-table"', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>metric_code</th><th class="num">excel_value</th><th class="num">system_value</th><th class="num">difference</th><th class="num">%</th><th>status</th><th>note</th></tr></thead><tbody>${r.rows.map(x => `<tr><td><code>${esc(x.code)}</code><div class="xs muted">${esc(x.label)}${x.excel && x.excel !== x.label ? ' (' + esc(x.excel) + ')' : ''} · ${M.statusChip(x.defStatus)}</div>${x.tsg ? `<div class="xs muted">Excel T ${F.vnd(x.tsg.T)} · S ${F.vnd(x.tsg.S)} · G ${F.vnd(x.tsg.G)}</div>` : ''}</td><td class="num">${fmt(x.code, x.excelValue)}</td><td class="num"><b>${x.systemValue == null ? '—' : fmt(x.code, x.systemValue)}</b>${x.sysTsg && x.tsg ? `<div class="xs muted">T ${F.vnd(Math.round(x.sysTsg.T || 0))} · S ${F.vnd(Math.round(x.sysTsg.S || 0))} · G ${F.vnd(Math.round(x.sysTsg.G || 0))}</div>` : ''}</td><td class="num ${x.diff ? (Math.abs(x.diff) < 1 ? 'muted' : 'red') : 'green'}">${x.diff == null ? '—' : (x.unit === 'PERCENT' ? (x.diff > 0 ? '+' : '') + x.diff + ' đ%' : x.unit === 'COUNT' ? (x.diff > 0 ? '+' : '') + x.diff : (x.diff > 0 ? '+' : '') + F.vnd(Math.round(x.diff * 100) / 100))}</td><td class="num muted">${x.pctDiff == null ? '—' : x.pctDiff + '%'}</td><td>${Q.chip('reconStatus', x.status)}</td><td class="xs muted">${esc(x.note || '')}</td></tr>`).join('')}</tbody></table></div>` })}
    ${U.note('info', 'Tolerance', 'Count: khớp tuyệt đối · Tiền: lệch < 1 VND = làm tròn · Percentage: ±0,05 điểm % · Metric chờ chốt (hoặc phụ thuộc metric chờ chốt) luôn hiển thị NEED_BUSINESS_CONFIRMATION dù giá trị khớp – xem <a class="link" href="#/reports/metrics">Metric Registry</a> để ký xác nhận Q-RPT.')}` : U.empty({ title: 'Chưa có golden dataset' })}`;
    U.onChange(root, { f: () => TH.router.applyFilter({}, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { export: () => { X.exportReconcile(gid); ok('Đã xuất bảng đối soát'); } });
  }, { menu: 'report-reconcile', permission: 'reports.view' });

  /* ================= Metric Registry ================= */
  TH.router.register('/reports/metrics', (root, p, q) => {
    TH.router.crumb([{ label: 'Báo cáo' }, { label: 'Metric Registry' }]);
    const f = { status: q.status || '', group: q.group || '', s: q.s || '' }; const canM = TH.auth.can('metrics.manage');
    const defs = M.defs1().filter(d => (!f.status || M.effectiveStatus(d.code) === f.status) && (!f.group || d.group === f.group) && (!f.s || F.norm(d.code + ' ' + d.label + ' ' + (d.excel || '') + ' ' + (d.formula || '')).includes(F.norm(f.s))));
    const need = M.defs1().filter(d => d.status === 'NEED_BUSINESS_CONFIRMATION');
    root.innerHTML = `${U.pageHead({ title: 'Metric Registry (spec v1.8 §7.6 / §12.23)', sub: 'Dashboard & Report dùng chung: metric_code, tên, nhóm, đơn vị, loại công thức, biểu thức, nguồn, date basis, version, hiệu lực, business_confirmation_status. Metric chưa chốt hiển thị tag "Chờ chốt", không hard-code suy đoán.', acts: [U.btn({ label: 'Report A', icon: 'file-text', cls: 'btn-outline', act: 'ra' }), U.btn({ label: 'Đối soát golden', icon: 'check-square', cls: 'btn-outline', act: 'rc' })] })}
    ${U.filterbar([U.field({ label: 'Tìm', input: U.input({ name: 's', value: f.s, placeholder: 'metric_code, tên, công thức…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.metricStatus).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Nhóm báo cáo', input: U.select({ name: 'group', value: f.group, all: 'Tất cả nhóm', options: M.P1_GROUPS.map(g => [g, g]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Metric', value: M.P1.length, cap: M.P1.filter(d => d.formulaType === 'SOURCE').length + ' SOURCE · ' + M.P1.filter(d => d.formulaType === 'FORMULA').length + ' FORMULA', icon: 'book', tone: 'blue' })}${U.kpi({ label: 'Đã xác nhận', value: M.defs1().filter(d => d.status === 'CONFIRMED').length, cap: 'Có nguồn, date basis, công thức, version', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Chờ chốt', value: need.length, cap: need.map(d => d.question).filter((x, i, a) => x && a.indexOf(x) === i).join(', '), icon: 'help-circle', tone: 'amber' })}${U.kpi({ label: 'Metric version', value: M.version(), cap: 'Freeze vào report_period khi khóa', icon: 'lock', tone: 'purple' })}</div>
    ${U.relatedStrip({ id: 'metrics-related', cls: 'mb16', items: [{ key: 'q', title: 'Câu hỏi phải ký xác nhận (§12.23.15)', icon: 'help-circle', summary: Object.keys(M.P1_QUESTIONS).length + ' câu Q-RPT', meta: need.length + ' metric đang chờ', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Mã</th><th>Câu hỏi</th><th>Metric liên quan</th></tr></thead><tbody>${Object.entries(M.P1_QUESTIONS).map(([k, t]) => `<tr><td><code>${k}</code></td><td>${esc(t)}</td><td class="xs">${M.defs1().filter(d => d.question === k).map(d => '<code>' + esc(d.code) + '</code> ' + M.statusChip(d.status)).join(' ') || '<span class="muted">Rule allocation / làm tròn</span>'}</td></tr>`).join('')}</tbody></table></div>` }] })}
    ${U.card({ title: 'Metric Definition (' + defs.length + ')', icon: 'book', bodyCls: 'tight', attrs: 'data-guide="metrics-table"', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>metric_code</th><th>Nhóm</th><th>Đơn vị · loại</th><th>Công thức</th><th>Nguồn · date basis</th><th>Version</th><th>Trạng thái</th><th></th></tr></thead><tbody>${defs.map(d => `<tr><td><code><b>${esc(d.code)}</b></code><div class="xs">${esc(d.label)}${d.excel && d.excel !== d.label ? ' <span class="muted">(' + esc(d.excel) + ')</span>' : ''}</div></td><td class="xs">${esc(d.group)}</td><td class="xs">${d.unit}<br>${d.formulaType}</td><td class="xs" style="max-width:280px">${esc(d.formula || '')}${d.note ? '<div class="muted">' + esc(d.note) + '</div>' : ''}</td><td class="xs">${esc(d.source || '')}<br><span class="muted">${esc(d.dateBasis || '')}</span></td><td class="xs">v${d.version}<br><span class="muted">${F.date(d.effectiveFrom)}</span>${d.confirmedBy ? '<br><span class="muted">' + esc(Q.userName(d.confirmedBy)) + '</span>' : ''}</td><td>${M.statusChip(d.status)}${M.effectiveStatus(d.code) !== d.status ? '<div class="xs muted">phụ thuộc chờ chốt</div>' : ''}${d.question ? '<div class="xs muted">' + esc(d.question) + '</div>' : ''}</td><td>${U.rowActions([d.status === 'NEED_BUSINESS_CONFIRMATION' && canM ? U.btn({ label: 'Xác nhận', icon: 'check', size: 'btn-sm', cls: 'btn-primary', act: 'confirm', attrs: { 'data-code': d.code, 'data-guide': 'metric-confirm' } }) : '', d.status === 'CONFIRMED' && d.history && d.history.length && canM ? U.btn({ label: 'Về chờ chốt', icon: 'undo', size: 'btn-sm', cls: 'btn-ghost', act: 'revert', attrs: { 'data-code': d.code } }) : '', U.btn({ label: 'Chi tiết', icon: 'info', size: 'btn-sm', cls: 'btn-ghost', act: 'info', attrs: { 'data-code': d.code } })])}</td></tr>`).join('')}</tbody></table></div>` })}`;
    U.onChange(root, { f: () => TH.router.applyFilter(f, U.formData(root.querySelector('.filterbar'))) });
    U.bind(root, { ra: () => TH.go('#/reports/building-profit'), rc: () => TH.go('#/reports/reconcile'), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, info: (el) => { const d = M.def(el.dataset.code); const m = U.modal({ title: 'Metric ' + esc(d.code), body: M.info(d.code) + (d.history && d.history.length ? U.card({ title: 'Lịch sử version', icon: 'history', cls: 'mt12', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Thời điểm</th><th>Version</th><th>Từ → đến</th><th>Quyết định</th></tr></thead><tbody>${d.history.slice().reverse().map(h => `<tr><td class="xs">${F.datetime(h.at)}<br>${esc(h.byName || '')}</td><td>v${h.version}</td><td class="xs">${esc(h.from)} → ${esc(h.to)}</td><td class="xs">${esc(h.decision || '')}</td></tr>`).join('')}</tbody></table>` }) : ''), footer: U.btn({ label: 'Đóng', act: 'c' }) }); U.bind(m.el, { c: () => m.close() }); }, confirm: async (el) => { const d = M.def(el.dataset.code); const c = await U.confirm({ title: 'Xác nhận metric ' + d.code + '?', text: (d.question ? d.question + ': ' + M.P1_QUESTIONS[d.question] + '. ' : '') + 'Chuyển NEED_BUSINESS_CONFIRMATION → CONFIRMED, tăng version (' + M.version() + ' → mới), ghi người ký. Kỳ đã khóa vẫn giữ version cũ.', body: U.field({ label: 'Quyết định nghiệp vụ đã chốt', req: true, input: U.textarea({ name: 'decision', rows: 2, placeholder: 'VD: Tổng doanh thu = Tiền phòng + Dịch vụ + Cọc giữ lại; ký bởi Ngọc 30/10/2026' }) }), ok: 'Xác nhận' }); if (!c) return; try { const o = X.confirmMetric(d.code, { decision: c.decision }); ok('Đã xác nhận ' + d.code + ' v' + o.version); } catch (e) { U.toast('error', e.message); } }, revert: async (el) => { const c = await U.confirm({ title: 'Đưa ' + el.dataset.code + ' về chờ chốt?', body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) }), ok: 'Đồng ý', danger: true }); if (!c) return; try { X.revertMetric(el.dataset.code, c.reason); ok('Đã cập nhật'); } catch (e) { U.toast('error', e.message); } } });
  }, { menu: 'metrics', permission: 'reports.view' });
})(window.TH);
