(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const ok = (msg) => { U.toast('ok', msg); };
  TH.pages.roomMenu = (btn, room) => {
    const roomId = room && room.id ? room.id : btn && btn.dataset && btn.dataset.id;
    const r = roomId ? St.get('rooms', roomId) : null;
    if (!r) {
      U.toast('err', 'Không thực hiện được', 'Không tìm thấy phòng. Vui lòng tải lại danh sách.');
      return null;
    }
    const c = Q.activeContractOfRoom(r.id); const items = [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => { if (!St.get('rooms', r.id)) return U.toast('err', 'Không thực hiện được', 'Phòng không còn tồn tại.'); TH.go('#/rooms/' + r.id); } }, { label: 'Sửa phòng', icon: 'pencil', onClick: () => { const current = St.get('rooms', r.id); if (!current) return U.toast('err', 'Không thực hiện được', 'Phòng không còn tồn tại.'); Fm.room(current); } }, '-'];
    if (r.status === 'ready') items.push({ label: 'Giữ chỗ', icon: 'clock', onClick: () => Fm.hold(r.id) }, { label: 'Tạo hợp đồng', icon: 'file-plus', onClick: () => TH.go('#/contracts/new?room=' + r.id) }, { label: 'Chuyển Bảo trì / Ngừng khai thác', icon: 'wrench', onClick: () => Fm.roomStatus(r) });
    if (r.status === 'held') items.push({ label: 'Tạo hợp đồng cho khách giữ chỗ', icon: 'file-plus', onClick: () => { const h = Q.roomHold(r.id); TH.go('#/contracts/new?room=' + r.id + (h ? '&tenant=' + h.tenantId : '')); } }, { label: 'Hủy giữ chỗ', icon: 'x-circle', danger: true, onClick: () => { X.releaseHold(r.id); ok('Đã hủy giữ chỗ'); } });
    if (r.status === 'occupied' && c) items.push({ label: 'Xem hợp đồng', icon: 'file-text', onClick: () => { const current = St.get('contracts', c.id); if (!current) return U.toast('err', 'Không thực hiện được', 'Hợp đồng không còn tồn tại.'); TH.go('#/contracts/' + current.id); } }, { label: 'Tạo hóa đơn', icon: 'receipt', onClick: () => { const current = St.get('rooms', r.id); if (!current) return U.toast('err', 'Không thực hiện được', 'Phòng không còn tồn tại.'); TH.go('#/invoices/batch?buildingId=' + current.buildingId + '&room=' + current.id); } }, { label: 'Kết thúc hợp đồng', icon: 'x-circle', danger: true, onClick: () => { const current = St.get('contracts', c.id); if (!current || current.status !== 'active') return U.toast('err', 'Không thực hiện được', 'Hợp đồng không còn hiệu lực.'); Fm.terminate(current); } });
    if (r.status === 'vacating' && c) items.push({ label: 'Xem hợp đồng (chờ kết thúc)', icon: 'file-text', onClick: () => TH.go('#/contracts/' + c.id) }, { label: 'Quyết toán / kết thúc HĐ', icon: 'x-circle', onClick: () => Fm.terminate(c) });
    if (r.status === 'cleaning') items.push({ label: 'Xác nhận dọn xong → Sẵn sàng', icon: 'check-circle', onClick: () => { X.confirmCleaned(r.id); ok('Phòng ' + r.code + ' đã Sẵn sàng'); } }, { label: 'Cần sửa chữa → Bảo trì', icon: 'wrench', onClick: () => { X.confirmCleaned(r.id, { toMaintenance: true }); ok('Phòng ' + r.code + ' → Bảo trì'); } });
    if (r.status === 'maintenance') items.push({ label: 'Nghiệm thu → Sẵn sàng', icon: 'check', onClick: () => { X.acceptMaintenance(r.id); ok('Phòng đã Sẵn sàng'); } });
    if (r.status === 'inactive') items.push({ label: 'Khai thác lại → Sẵn sàng', icon: 'check', onClick: () => { X.setRoomStatus(r.id, 'ready', 'Khai thác lại'); ok('Phòng đã Sẵn sàng'); } });
    items.push({ label: 'Cập nhật giá niêm yết', icon: 'dollar', onClick: () => Fm.roomPrice(r) });
    items.push('-', { label: 'Tạo sự cố', icon: 'alert-triangle', p2: true, disabled: TH.phase.on(2) && !TH.auth.can('maintenance.manage', { buildingId: r.buildingId }), onClick: () => TH.forms.incident({}, { buildingId: r.buildingId, roomId: r.id }) });
    return U.menu(btn, items);
  };
  const rowActions = (r) => {
    const c = Q.activeContractOfRoom(r.id); const a = [];
    if (r.status === 'ready') a.push(U.actBtn({ icon: 'clock', label: 'Giữ chỗ', act: 'hold', attrs: { 'data-id': r.id } }), U.actBtn({ icon: 'plus', label: 'Tạo hợp đồng', act: 'newc', attrs: { 'data-id': r.id }, tone: 'primary' }));
    if (r.status === 'occupied' && c) a.push(U.actBtn({ icon: 'file-text', label: 'Xem hợp đồng', act: 'viewc', attrs: { 'data-id': c.id } }), U.actBtn({ icon: 'receipt', label: 'Tạo hóa đơn', act: 'inv', attrs: { 'data-id': r.id } }));
    if (r.status === 'cleaning') a.push(U.actBtn({ icon: 'check', label: 'Xác nhận dọn xong', act: 'clean', attrs: { 'data-id': r.id, 'data-guide': 'confirm-clean' }, tone: 'success' }));
    if (r.status === 'held') a.push(U.actBtn({ icon: 'plus', label: 'Tạo hợp đồng', act: 'newc', attrs: { 'data-id': r.id }, tone: 'primary' }));
    if (r.status === 'vacating' && c) a.push(U.actBtn({ icon: 'file-text', label: 'HĐ chờ kết thúc', act: 'viewc', attrs: { 'data-id': c.id } }));
    if (r.status === 'maintenance') a.push(U.actBtn({ icon: 'check', label: 'Nghiệm thu', act: 'accept', attrs: { 'data-id': r.id }, tone: 'success' }));
    if (r.status === 'inactive') a.push('<span class="muted">-</span>');
    a.push(U.moreBtn(r.id)); return U.rowActions(a);
  };
  /* ---------- Danh sách phòng ---------- */
  TH.router.register('/rooms', (root, p, q) => {
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Phòng' }]);
    const f = { s: q.s || '', areaId: q.areaId || '', buildingId: q.buildingId || '', floor: q.floor || '', status: q.status || '', vac: q.vac || '', avail: q.avail || '', managerId: q.managerId || '', leadId: q.leadId || '' };
    const scope = Q.scope({ areaId: f.areaId, buildingId: f.buildingId, leadId: f.leadId });
    // Other buildings contain room codes cited by refund/termination sheets, not a complete inventory.
    const all = St.all('rooms').filter(r => !Q.building(r.buildingId).summaryOnly); const st = Q.roomStats(all);
    const rows = all.filter(r => (!f.s || F.norm(r.code + ' ' + Q.building(r.buildingId).name + ' ' + ((Q.roomTenant(r.id) || {}).name || '')).includes(F.norm(f.s))) && scope.buildingIds.includes(r.buildingId) && (!f.floor || String(r.floor) === f.floor) && (!f.status || (f.status === 'maintenance' ? r.status === 'maintenance' : r.status === f.status)) && (!f.vac || Q.roomVacancy(r, St.state.meta.period) === f.vac) && (!f.managerId || r.managerId === f.managerId) && (!f.avail || (f.avail === 'yes' ? ['ready'].includes(r.status) : !['ready'].includes(r.status)))).sort((a, b) => a.code.localeCompare(b.code));
    const tabs = [{ key: '', label: 'Tất cả', count: st.total }, { key: 'ready', label: 'Sẵn sàng', count: st.ready, color: 'green' }, { key: 'held', label: 'Giữ chỗ', count: st.held, color: 'amber' }, { key: 'vacating', label: 'Sắp trống', count: st.vacating, color: 'purple' }, { key: 'occupied', label: 'Đang thuê', count: st.occupied, color: 'blue' }, { key: 'cleaning', label: 'Chờ dọn', count: st.cleaning, color: 'orange' }, { key: 'maintenance', label: 'Bảo trì', count: st.maintenance, color: 'red' }, { key: 'inactive', label: 'Ngừng khai thác', count: st.inactive, color: 'gray' }];
    root.innerHTML = `${U.pageHead({ title: 'Phòng', sub: 'Theo dõi khả dụng và xử lý nhanh vòng đời cho thuê.', acts: [U.btn({ label: 'Tạo hợp đồng', icon: 'plus', cls: 'btn-primary', act: 'newc-any' }), TH.auth.can('rooms.manage') ? U.btn({ label: 'Thêm phòng', icon: 'door', cls: 'btn-outline', act: 'add-room' }) : ''] })}
    ${U.statusTabs(tabs, f.status)}
    ${St.all('rooms').length > all.length ? U.note('info', 'Phạm vi danh mục phòng', (St.all('rooms').length - all.length) + ' mã phòng khác chỉ có trong chứng từ hoàn cọc/phá hợp đồng; chưa có hồ sơ quỹ phòng đầy đủ nên không cộng vào số phòng vận hành.') : ''}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Mã phòng, tòa hoặc khách thuê...', icon: 'search' }), cls: 'wide' }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tầng', input: U.select({ name: 'floor', value: f.floor, all: 'Tất cả tầng', options: [...new Set(all.map(r => r.floor))].sort((a, b) => a - b).map(x => [x, 'Tầng ' + x]), attrs: { 'data-on': 'f' } }) }), `<details class="filter-more"><summary>${I('filter')} Bộ lọc khác</summary><div class="filter-pop">${U.field({ label: 'Phân loại trống', input: U.select({ name: 'vac', value: f.vac, all: 'Tất cả', options: Object.entries(Q.L.vacancy).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Khu nhà', input: U.select({ name: 'areaId', value: f.areaId, all: 'Tất cả khu nhà', options: Q.areas().map(a => [a.id, a.name]), attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Trưởng nhóm', input: U.select({ name: 'leadId', value: f.leadId, all: 'Tất cả trưởng nhóm', options: St.all('employees').filter(e => e.status === 'working').map(e => [e.id, e.name]), attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Khả dụng', input: U.select({ name: 'avail', value: f.avail, all: 'Tất cả', options: [['yes', 'Khả dụng'], ['no', 'Không khả dụng']], attrs: { 'data-on': 'f' } }) })}${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả nhân viên', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })}</div></details>`], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${U.card({ title: `Danh sách phòng <span class="muted" style="font-weight:400">(${rows.length})</span>`, actions: U.btn({ label: 'Xuất', icon: 'download', cls: 'btn-outline', size: 'btn-sm', act: 'export' }), body: null, id: 'tbl-card', attrs: 'data-guide="rooms-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, selectable: true, unit: 'phòng', colPrefsKey: 'rooms', densityControl: true, rowHref: r => '#/rooms/' + r.id, rowClass: r => ({ held: 'tint-amber', occupied: '', cleaning: 'tint-orange', maintenance: 'tint-red', inactive: 'tint-red' })[r.status] || '', cols: [
      { key: 'code', label: 'Phòng / Tòa', sortable: true, render: r => U.cell2(U.link('#/rooms/' + r.id, esc(r.code), 'bold'), esc(Q.building(r.buildingId).name) + ' · Tầng ' + r.floor) },
      { key: 'status', label: 'Trạng thái', sortable: true, render: r => { const c = r.status === 'vacating' ? Q.activeContractOfRoom(r.id) : null; return (r.status === 'maintenance' ? U.chip('Bảo trì', 'red', true) : Q.chipDot('room', r.status)) + (c && c.moveOutDate ? '<div class="xs muted">ra ' + F.date(c.moveOutDate) + '</div>' : ''); } },
      { key: 'vacancy', label: 'Phân loại trống', render: r => { const k = Q.roomVacancy(r, St.state.meta.period); return k ? Q.chip('vacancy', k) + ' ' + U.assume() : '-'; } },
      { key: 'tenant', label: 'Khách hiện tại', render: r => { if (r.status === 'held') { const h = Q.roomHold(r.id); return h ? esc(Q.tenant(h.tenantId).name) + ' <span class="xs muted">(giữ đến ' + F.date(h.until) + ')</span>' : '-'; } const t = Q.roomTenant(r.id); return t ? U.link('#/tenants/' + t.id, esc(t.name)) : '-'; } },
      { key: 'price', label: 'Giá niêm yết', num: true, sortable: true, render: r => F.vnd(r.price) + (Q.roomPriceHistory(r.id).length > 1 ? ' <span class="xs muted" title="Có lịch sử giá">↺</span>' : '') },
      { key: 'exp', label: 'HĐ hết hạn', render: r => { const c = Q.activeContractOfRoom(r.id); if (!c) return '-'; const d = F.daysUntil(c.end); return `<span class="${d <= 35 ? 'red bold' : ''}">${F.date(c.end)}</span>`; } },
      { key: 'mgr', label: 'Người phụ trách', render: r => esc(Q.userName(r.managerId)) },
      { key: 'actions', label: 'Thao tác', render: r => rowActions(r), hideable: false }] });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, {
      stab: (el) => { TH.router.replaceQuery(Object.assign({}, f, { status: el.dataset.key })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); },
      export: () => { F.download('phong.csv', F.csv(rows.map(r => [r.code, Q.building(r.buildingId).name, r.floor, Q.label('room', r.status), r.price, (Q.roomTenant(r.id) || {}).name || '']), ['Mã phòng', 'Tòa', 'Tầng', 'Trạng thái', 'Giá', 'Khách']), 'text/csv'); U.toast('ok', 'Đã xuất danh sách phòng'); },
      'newc-any': () => TH.go('#/contracts/new'), 'add-room': () => Fm.room({}, q.buildingId || ''), hold: (b) => Fm.hold(b.dataset.id), newc: (b) => { const h = Q.roomHold(b.dataset.id); TH.go('#/contracts/new?room=' + b.dataset.id + (h ? '&tenant=' + h.tenantId : '')); }, viewc: (b) => TH.go('#/contracts/' + b.dataset.id), inv: (b) => { const r = St.get('rooms', b.dataset.id); TH.go('#/invoices/batch?buildingId=' + r.buildingId + '&room=' + r.id); },
      clean: async (b) => { const r = St.get('rooms', b.dataset.id); if (await U.confirm({ title: 'Xác nhận dọn xong phòng ' + r.code + '?', text: 'Phòng chuyển sang Sẵn sàng và xuất hiện trong danh sách cho thuê (BR-02).', ok: 'Xác nhận dọn xong' })) { X.confirmCleaned(r.id); ok('Phòng ' + r.code + ' đã Sẵn sàng'); } },
      accept: (b) => { try { X.acceptMaintenance(b.dataset.id); ok('Phòng đã Sẵn sàng'); } catch (e) { U.toast('err', 'Lỗi', e.message); } }, viewc: (b) => TH.go('#/contracts/' + b.dataset.id),
      more: (b) => TH.pages.roomMenu(b, St.get('rooms', b.dataset.id)),
    });
  }, { menu: 'rooms', permission: 'rooms.view' });

  /* ---------- Chi tiết phòng ---------- */
  TH.router.register('/rooms/:id', (root, p, q) => {
    const r = St.get('rooms', p.id); if (!r) { root.innerHTML = U.empty({ title: 'Không tìm thấy phòng' }); return; }
    const b = Q.building(r.buildingId); const c = Q.activeContractOfRoom(r.id); const t = c ? Q.tenant(c.tenantId) : null; const tab = q.tab || 'overview'; const debt = Q.roomDebt(r.id);
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Phòng', href: '#/rooms' }, { label: r.code }]);
    const invs = St.where('invoices', i => i.roomId === r.id && i.docStatus !== 'cancelled').sort((a, z) => F.cmp(z.period, a.period));
    const svcs = c ? Q.contractServices(c.id) : (r.defaultServiceIds || []).map(id => { const s = Q.service(id); return { name: s.name, price: s.price, unit: s.unit, qty: 1, def: true }; });
    const assets = St.where('roomAssets', a => a.roomId === r.id); const hist = Q.contractsOfRoom(r.id);
    root.innerHTML = `${U.pageHead({ title: esc(r.code), chips: ' ' + Q.chipDot('room', r.status), sub: `${esc(b.name)} • Tầng ${r.floor} • ${esc(r.type)}`, back: '#/rooms', acts: [c ? U.btn({ label: 'Xem hợp đồng', icon: 'file-text', cls: 'btn-outline', act: 'viewc' }) : '', r.status === 'occupied' ? U.btn({ label: 'Tạo hóa đơn', icon: 'plus', cls: 'btn-primary', act: 'inv' }) : r.status === 'ready' || r.status === 'held' ? U.btn({ label: 'Tạo hợp đồng', icon: 'plus', cls: 'btn-primary', act: 'newc' }) : r.status === 'cleaning' ? U.btn({ label: 'Xác nhận dọn xong', icon: 'check', cls: 'btn-primary', act: 'clean' }) : '', U.btn({ label: 'Hành động', icon: 'chevron-down', cls: 'btn-outline', act: 'more' })] })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Giá thuê', value: F.vnd(c ? c.price : r.price), cap: 'VND/tháng' + (c ? '' : ' (tham chiếu)'), icon: 'dollar', tone: 'amber' })}${U.kpi({ label: 'Tiền cọc', value: F.vnd(c ? c.deposit : 0), cap: 'VND', icon: 'shield', tone: 'blue' })}${U.kpi({ label: 'Công nợ hiện tại', value: F.vnd(debt), cap: 'VND', icon: 'alert-circle', tone: 'red', valueCls: debt ? 'red' : '' })}${U.kpi({ label: c ? 'HĐ còn lại' : 'Hợp đồng', value: c ? F.durationText(F.today(), c.end) : '—', cap: c ? 'Kết thúc ' + F.date(c.end) : 'Chưa có hợp đồng hiệu lực', icon: 'clock', tone: 'green' })}</div>
    ${U.tabs([{ key: 'overview', label: 'Tổng quan', icon: 'grid' }, { key: 'history', label: 'Lịch sử thuê', icon: 'history' }, { key: 'services', label: 'Dịch vụ', icon: 'sliders' }, { key: 'assets', label: 'Tài sản', icon: 'package' }, { key: 'meters', label: 'Chỉ số điện nước', icon: 'zap' }, { key: 'debt', label: 'Công nợ', icon: 'alert-circle' }, { key: 'statushist', label: 'Lịch sử trạng thái', icon: 'activity' }, { key: 'price', label: 'Lịch sử giá', icon: 'dollar' }, { key: 'issues', label: 'Sự cố', icon: 'alert-triangle', p2: true }, { key: 'docs', label: 'Tài liệu', icon: 'folder' }, { key: 'log', label: 'Lịch sử', icon: 'clock' }], tab, 'card-tabs')}<div id="tab-body"></div>`;
    const body = root.querySelector('#tab-body');
    const svcTable = (withState) => `<table class="tbl compact"><thead><tr><th>#</th><th>Dịch vụ</th><th class="num">Đơn giá (VND)</th><th>Chu kỳ</th><th>Trạng thái</th></tr></thead><tbody>${svcs.length ? svcs.map((s, i) => `<tr><td>${i + 1}</td><td>${esc(s.name)}${s.qty > 1 ? ' <span class="muted">× ' + s.qty + '</span>' : ''}</td><td class="num">${F.vnd(s.price)}</td><td>Tháng</td><td>${U.chip(s.def ? 'Mặc định' : 'Đang áp dụng', s.def ? 'blue' : 'green', true)}</td></tr>`).join('') : `<tr><td colspan="5" class="muted tc">Chưa có dịch vụ</td></tr>`}</tbody></table>`;
    const ll = St.get('landlords', b.landlordId); const lc = Q.landlordContractOf(b.id);
    if (tab === 'overview') body.innerHTML = `<div class="grid grid-2">
      ${U.card({ title: 'Thông tin phòng', icon: 'door', actions: U.btn({ label: 'Chỉnh sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }), body: U.kv([['Mã phòng', esc(r.code)], ['Tòa nhà', U.link('#/buildings/' + b.id, esc(b.name))], ['Tầng', r.floor], ['Loại phòng', esc(r.type)], ['Diện tích', r.area + ' m²'], ['Tình trạng vật lý', Q.chipDot('physical', r.physical)], ['Khả dụng', Q.chipDot('room', r.status)], ['Hướng phòng', esc(r.direction || '-')], ['Trang bị nội thất', esc(r.furniture || '-')], ['Người phụ trách', esc(Q.userName(r.managerId))]]) })}
      ${U.card({ title: 'Dịch vụ đang áp dụng', icon: 'sliders', actions: U.btn({ label: 'Quản lý dịch vụ', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'svc' }), body: svcTable(), bodyCls: 'tight' })}
      ${U.card({ title: 'Khách thuê hiện tại', icon: 'user', actions: t ? U.btn({ label: 'Xem khách thuê', icon: 'arrow-left-right', size: 'btn-sm', cls: 'btn-outline', act: 'viewt' }) : '', body: t ? `<div class="row gap12 mb12">${U.avatar(t.name, 'lg')}<div><b style="font-size:15px;color:var(--text)">${esc(t.name)}</b> ${U.chip('Khách thuê', 'green')}<div class="small muted mt4">${I('phone')} ${esc(t.phone)} &nbsp; ${I('mail')} ${esc(t.email || '-')}</div></div></div>${U.kv([['Mã hợp đồng', U.link('#/contracts/' + c.id, c.code)], ['Ngày chuyển vào', F.date(c.start)], ['Thời hạn hợp đồng', F.date(c.start) + ' - ' + F.date(c.end)], ['Thời gian ở', F.durationText(c.start, F.today())]], 'one')}` : r.status === 'held' ? (() => { const h = Q.roomHold(r.id); const ht = h ? Q.tenant(h.tenantId) : {}; return `${U.note('warn', 'Đang giữ chỗ', `${esc(ht.name || '')} – giữ đến ${h ? F.date(h.until) : '-'}, tiền giữ ${h ? F.vnd(h.deposit) : 0} đ`)}<div class="row mt12">${U.btn({ label: 'Tạo hợp đồng', icon: 'file-plus', cls: 'btn-primary', size: 'btn-sm', act: 'newc' })}${U.btn({ label: 'Hủy giữ chỗ', size: 'btn-sm', cls: 'btn-danger', act: 'release' })}</div>`; })() : U.empty({ icon: 'user', title: 'Phòng chưa có khách', text: r.status === 'cleaning' ? 'Phòng đang chờ dọn – xác nhận dọn xong để mở cho thuê.' : 'Tạo hợp đồng để đưa phòng vào khai thác.' }) })}
      ${U.card({ title: 'Chủ nhà & HĐ đầu vào', icon: 'user-check', sub: 'Chuỗi pháp lý: Chủ nhà → HĐ đầu vào → Tòa → Phòng', actions: `<a class="link small" href="#/buildings/${b.id}?tab=landlord">Xem tại tòa →</a>`, body: ll ? U.kv([['Chủ nhà', U.link('#/landlords/' + ll.id, esc(ll.name)) + ' ' + Q.chip('landlord', Q.landlordStatus(ll))], ['HĐ đầu vào', lc ? esc(lc.code) + ' ' + Q.chip('lcontract', Q.lcStatus(lc)) : U.chip('Chưa có HĐ hiệu lực', 'red')], ['Hiệu lực', lc ? F.date(lc.start) + ' – ' + F.date(lc.end) + (c && c.end > lc.end ? ' <span class="amber">(HĐ khách kết thúc sau ' + F.date(lc.end) + ')</span>' : '') : '-'], ['Chu kỳ trả chủ nhà', (lc ? lc.cycleMonths : b.payCycle) + ' tháng/lần']], 'one') + (lc ? '' : U.note('warn', 'Chưa thể cho thuê', 'Tòa chưa có HĐ đầu vào hiệu lực – bổ sung hợp đồng với chủ nhà trước khi giữ chỗ / kích hoạt HĐ.')) : U.empty({ title: 'Tòa chưa gán chủ nhà', text: 'Bổ sung qua Onboarding chủ nhà.' }) })}
      ${U.card({ title: 'Tài sản trong phòng', icon: 'package', actions: U.btn({ label: 'Quản lý tài sản', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'add-asset' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Tên tài sản</th><th class="num">Số lượng</th><th>Tình trạng</th><th></th></tr></thead><tbody>${assets.length ? assets.map((a, i) => `<tr><td>${i + 1}</td><td>${esc(a.name)}</td><td class="num">${a.qty}</td><td>${U.chip(a.condition, a.condition === 'Tốt' ? 'green' : a.condition === 'Hỏng' ? 'red' : 'amber')}</td><td class="tr">${U.iconBtn('pencil', 'edit-asset', 'Sửa', { 'data-id': a.id })}${U.iconBtn('trash', 'rm-asset', 'Xóa', { 'data-id': a.id })}</td></tr>`).join('') : '<tr><td colspan="5" class="muted tc">Chưa ghi nhận tài sản</td></tr>'}</tbody></table>` })}
      ${U.card({ title: 'Hóa đơn gần đây', icon: 'receipt', actions: `<a class="link small" href="#/invoices?room=${r.id}&period=all">Xem tất cả →</a>`, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Mã hóa đơn</th><th>Kỳ</th><th>Ngày phát hành</th><th>Hạn thanh toán</th><th class="num">Số tiền (VND)</th><th>Trạng thái</th><th></th></tr></thead><tbody>${invs.length ? invs.slice(0, 5).map((i, k) => `<tr><td>${k + 1}</td><td>${U.link('#/invoices/' + i.id, i.code)}</td><td>${F.periodShort(i.period)}</td><td>${F.date(i.issueDate)}</td><td>${F.date(i.dueDate)}</td><td class="num">${F.vnd(i.total)}</td><td>${i.docStatus === 'draft' ? Q.chip('invDoc', 'draft') : Q.invPayChip(i)}</td><td>${U.actBtn({ icon: 'eye', label: 'Xem', act: 'viewi', attrs: { 'data-id': i.id } })}</td></tr>`).join('') : '<tr><td colspan="8" class="muted tc">Chưa có hóa đơn</td></tr>'}</tbody></table>` })}
      ${U.card({ title: 'Sự cố gần nhất', icon: 'alert-triangle', actions: U.btn({ label: 'Tạo sự cố', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', p2: true, act: 'new-inc', disabled: TH.phase.on(2) && !TH.auth.can('maintenance.manage', { buildingId: r.buildingId }), title: TH.phase.on(2) && !TH.auth.can('maintenance.manage', { buildingId: r.buildingId }) ? 'Cần quyền quản lý bảo trì (Admin/Vận hành/Kỹ thuật)' : '', attrs: { 'data-guide': 'room-incident' } }), body: TH.phase.on(2) ? (TH.pages.roomIncidents ? TH.pages.roomIncidents(r, 3) : '') : U.empty({ icon: 'wrench', title: 'Bảo trì – Sửa chữa thuộc Phase 2', text: 'Ghi nhận sự cố, phân công, mức độ và trạng thái xử lý (FR-MNT-03).' }) })}</div>`;
    if (tab === 'history') body.innerHTML = U.card({ title: 'Lịch sử thuê', icon: 'history', body: null, id: 'hc' });
    if (tab === 'history') { const w = document.createElement('div'); body.querySelector('#hc').appendChild(w); U.table(w, { rows: hist, noPager: true, cols: [{ key: 'code', label: 'Mã HĐ', render: x => U.link('#/contracts/' + x.id, x.code) }, { key: 't', label: 'Khách thuê', render: x => U.link('#/tenants/' + x.tenantId, esc(Q.tenant(x.tenantId).name)) }, { key: 'start', label: 'Bắt đầu', render: x => F.date(x.start) }, { key: 'end', label: 'Kết thúc', render: x => F.date(x.actualEnd || x.end) }, { key: 'price', label: 'Giá thuê', num: true, render: x => F.vnd(x.price) }, { key: 'dep', label: 'Cọc', num: true, render: x => F.vnd(x.deposit) }, { key: 'st', label: 'Trạng thái', render: x => Q.chip('contract', Q.contractStatus(x)) }], empty: U.empty({ title: 'Chưa có lịch sử thuê' }) }); }
    if (tab === 'services') body.innerHTML = U.card({ title: c ? 'Dịch vụ theo hợp đồng ' + c.code : 'Dịch vụ mặc định của phòng', icon: 'sliders', sub: 'Giá dịch vụ trong HĐ là snapshot; đổi danh mục không hồi tố (BR-21)', actions: U.btn({ label: 'Quản lý dịch vụ', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'svc' }), bodyCls: 'tight', body: svcTable() });
    if (tab === 'meters') { const meters = Q.roomMeters(r.id); const reads = St.rawAll('meterReadings').filter(m => m && m.roomId === r.id).sort((a, b) => F.cmp(b.readingDate || b.period || '', a.readingDate || a.period || '') || F.cmp(a.type, b.type)); body.innerHTML = U.card({ title: 'Công tơ & chỉ số (§12.10)', icon: 'zap', sub: 'Mỗi phòng có công tơ điện/nước; chỉ số OPENING ghi khi bàn giao (từ OCR/HĐ), PERIOD theo kỳ hóa đơn, CLOSING khi trả phòng', bodyCls: 'tight', body: `<div class="row wrap gap8" style="padding:10px 12px">${meters.map(m => `<span class="chip ${m.status === 'replaced' ? 'gray' : 'blue'}">${I(m.type === 'electric' ? 'zap' : 'droplet')} ${esc(m.code)} · ${esc(m.unit)}${m.installedAt ? ' · lắp ' + F.date(m.installedAt) : ''}</span>`).join('') || '<span class="muted small">Chưa có công tơ</span>'}</div><table class="tbl compact"><thead><tr><th>Ngày / kỳ</th><th>Loại</th><th>Kiểu</th><th class="num">Cũ</th><th class="num">Mới</th><th class="num">Tiêu thụ</th><th>Trạng thái</th><th>Hợp đồng</th><th>Nguồn</th></tr></thead><tbody>${reads.map(m => `<tr><td>${m.readingDate ? F.date(m.readingDate) : ''}${m.period ? '<div class="xs muted">' + F.periodLabel(m.period) + '</div>' : ''}</td><td>${m.type === 'electric' ? 'Điện' : 'Nước'}</td><td>${Q.chip('readingType', m.readingType || 'PERIOD')}</td><td class="num">${m.prev}</td><td class="num">${m.curr}</td><td class="num">${(m.readingType || 'PERIOD') === 'OPENING' ? '–' : (m.curr - m.prev)}</td><td class="xs">${esc(m.status || '')}</td><td class="xs">${m.contractId ? U.link('#/contracts/' + m.contractId, esc((Q.contract(m.contractId) || {}).code || '')) : '-'}</td><td class="xs">${m.sourceOcr ? U.link('#/contracts/ocr?id=' + m.sourceOcr.jobId, 'OCR tr.' + (m.sourcePage || '')) : (m.enteredBy ? esc(Q.userName(m.enteredBy)) : '')}</td></tr>`).join('') || '<tr><td colspan="9" class="muted tc">Chưa có chỉ số</td></tr>'}</tbody></table>` }); }
    if (tab === 'debt') { const dr = invs.filter(i => i.docStatus !== 'draft').map(i => ({ inv: i, paid: Q.invPaid(i), remaining: Q.invRemaining(i), overdueDays: Q.invOverdueDays(i) })); body.innerHTML = `<div class="grid grid-3 mb16">${U.kpi({ mini: true, label: 'Phải thu', value: F.vnd(F.sum(dr, x => x.inv.total)), icon: 'receipt', tone: 'blue' })}${U.kpi({ mini: true, label: 'Đã thu', value: F.vnd(F.sum(dr, x => x.paid)), icon: 'check-circle', tone: 'green' })}${U.kpi({ mini: true, label: 'Còn nợ', value: F.vnd(F.sum(dr, x => x.remaining)), icon: 'alert-circle', tone: debt ? 'red' : 'green' })}</div>` + U.card({ title: 'Công nợ theo hóa đơn (drill-down hóa đơn → payment)', icon: 'alert-circle', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Hóa đơn</th><th>Khách</th><th>Kỳ</th><th>Hạn</th><th class="num">Tổng</th><th class="num">Đã thu</th><th class="num">Còn lại</th><th>Trạng thái</th><th>Payment</th></tr></thead><tbody>${dr.map(x => `<tr><td>${U.link('#/invoices/' + x.inv.id, esc(x.inv.code))}</td><td>${esc(Q.tenant(x.inv.tenantId).name)}</td><td>${F.periodShort(x.inv.period)}</td><td>${F.date(x.inv.dueDate)}</td><td class="num">${F.vnd(x.inv.total)}</td><td class="num">${F.vnd(x.paid)}</td><td class="num ${x.remaining ? 'red bold' : ''}">${F.vnd(x.remaining)}</td><td>${Q.chip('invPay', Q.invPayStatusW3(x.inv))}</td><td class="xs">${St.where('paymentAllocations', a => a.invoiceId === x.inv.id).map(a => U.link('#/payments/' + a.paymentId, esc((St.rawGet('payments', a.paymentId) || {}).code || ''))).join(', ') || '-'}</td></tr>`).join('') || '<tr><td colspan="9" class="muted tc">Chưa có hóa đơn</td></tr>'}</tbody></table>` }); }
    if (tab === 'statushist') { const sh = Q.roomStatusHistory(r.id); body.innerHTML = U.card({ title: 'Room Status History (§12.5.4 – nguồn tính vacancy/occupancy)', icon: 'activity', sub: 'Chuyển được từ ' + Q.label('room', r.status) + ': ' + (Q.ROOM_TRANSITIONS[r.status] || []).map(k => Q.label('room', k)).join(', '), actions: TH.auth.can('rooms.manage') && !['occupied', 'vacating', 'held'].includes(r.status) ? U.btn({ label: 'Chuyển trạng thái', icon: 'refresh', size: 'btn-sm', cls: 'btn-outline', act: 'status' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Thời điểm</th><th>Từ</th><th>→ Đến</th><th>Người</th><th>Lý do</th><th>Tham chiếu</th></tr></thead><tbody>${sh.map(h => `<tr><td>${F.datetime(h.at)}</td><td>${h.from ? Q.chip('room', h.from) : '<span class="muted">–</span>'}</td><td>${Q.chip('room', h.to)}</td><td class="xs">${esc(h.byName || (h.by ? Q.userName(h.by) : 'Hệ thống'))}</td><td class="xs">${esc(h.reason || '')}</td><td class="xs">${h.refType === 'contract' && h.refId ? U.link('#/contracts/' + h.refId, esc((Q.contract(h.refId) || {}).code || 'HĐ')) : ''}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Chưa có lịch sử</td></tr>'}</tbody></table>` }); }
    if (tab === 'price') { const ph = Q.roomPriceHistory(r.id); body.innerHTML = U.card({ title: 'Lịch sử giá niêm yết (§12.5.1)', icon: 'dollar', sub: 'Giá có ngày hiệu lực; HĐ đang thuê giữ giá snapshot ' + (c ? F.vnd(c.price) : ''), actions: U.btn({ label: 'Cập nhật giá', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'price', disabled: !TH.auth.can('rooms.manage') }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Hiệu lực từ</th><th class="num">Giá</th><th>Lý do</th><th>Người cập nhật</th><th>Trạng thái</th></tr></thead><tbody>${ph.map((h, i) => `<tr><td>${F.date(h.effectiveFrom)}</td><td class="num"><b>${F.vnd(h.price)}</b></td><td class="xs">${esc(h.reason || '')}</td><td class="xs">${esc(h.byName || (h.by ? Q.userName(h.by) : ''))}</td><td>${h.effectiveFrom > F.today() ? U.chip('Sắp hiệu lực', 'blue') : i === ph.findIndex(x => x.effectiveFrom <= F.today()) ? U.chip('Đang áp dụng', 'green') : U.chip('Hết hiệu lực', 'gray')}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Chưa có</td></tr>'}</tbody></table>` }); }
    if (tab === 'assets') body.innerHTML = U.card({ title: 'Tài sản trong phòng', icon: 'package', sub: TH.phase.on(3) ? 'Kiểm kê hàng tháng / khấu hao xem tại Sổ tài sản ' + TH.phase.tag(3) : 'Mức cơ bản Phase 1; kiểm kê/khấu hao thuộc Phase 3', actions: (TH.phase.on(3) ? U.btn({ label: 'Sổ tài sản', icon: 'package', size: 'btn-sm', cls: 'btn-outline', act: 'go-assets' }) : '') + U.btn({ label: 'Thêm tài sản', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-asset' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Tên tài sản</th><th class="num">Số lượng</th><th>Tình trạng</th><th></th></tr></thead><tbody>${assets.map((a, i) => `<tr><td>${i + 1}</td><td>${esc(a.name)}${TH.phase.on(3) ? (() => { const x = St.one('assets', z => z.roomAssetId === a.id); return x ? ` <a class="link small" href="#/assets?s=${x.code}">${esc(x.code)}</a>` : ''; })() : ''}</td><td class="num">${a.qty}</td><td>${U.chip(a.condition, a.condition === 'Tốt' ? 'green' : 'amber')}</td><td class="tr">${U.iconBtn('pencil', 'edit-asset', 'Sửa', { 'data-id': a.id })}${U.iconBtn('trash', 'rm-asset', 'Xóa', { 'data-id': a.id })}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Chưa có tài sản</td></tr>'}</tbody></table>` });
    if (tab === 'issues') body.innerHTML = TH.phase.on(2) ? U.card({ title: 'Sự cố của phòng ' + TH.phase.tag(2), icon: 'alert-triangle', actions: U.btn({ label: 'Tạo sự cố', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'new-inc', disabled: !TH.auth.can('maintenance.manage', { buildingId: r.buildingId }) }), body: TH.pages.roomIncidents(r, 50) }) : U.card({ body: U.empty({ icon: 'wrench', title: 'Sự cố – Phase 2', text: 'Xem scope tại 00_SCOPE_3_PHASE.md §3.3', action: U.btn({ label: 'Xem chi tiết scope', size: 'btn-sm', cls: 'btn-outline', act: 'p2' }) }) });
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'room' && d.entityId === r.id); body.innerHTML = U.card({ title: 'Tài liệu phòng', icon: 'folder', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu', text: 'Biên bản bàn giao, ảnh hiện trạng…' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => (x.entityType === 'room' && x.entityId === r.id) || (x.entityType === 'contract' && hist.some(h => h.id === x.entityId))); body.innerHTML = U.card({ title: 'Lịch sử thao tác', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, {
      tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, edit: () => Fm.room(r), svc: () => c ? U.toast('info', 'Dịch vụ theo hợp đồng', 'Sửa dịch vụ tại chi tiết hợp đồng ' + c.code) && TH.go('#/contracts/' + c.id + '?tab=services') : Fm.roomServices(r),
      viewc: () => TH.go('#/contracts/' + c.id), viewt: () => TH.go('#/tenants/' + t.id), viewi: (el) => TH.go('#/invoices/' + el.dataset.id), inv: () => TH.go('#/invoices/batch?buildingId=' + r.buildingId + '&room=' + r.id), newc: () => { const h = Q.roomHold(r.id); TH.go('#/contracts/new?room=' + r.id + (h ? '&tenant=' + h.tenantId : '')); }, release: () => { X.releaseHold(r.id); ok('Đã hủy giữ chỗ'); },
      clean: async () => { if (await U.confirm({ title: 'Xác nhận dọn xong phòng ' + r.code + '?', text: 'Phòng chuyển sang Sẵn sàng (BR-02).', ok: 'Xác nhận' })) { X.confirmCleaned(r.id); ok('Phòng đã Sẵn sàng'); } },
      'add-asset': () => Fm.roomAsset(r), 'go-assets': () => TH.go('#/assets?roomId=' + r.id), 'edit-asset': (el) => Fm.roomAsset(r, St.get('roomAssets', el.dataset.id)), 'rm-asset': (el) => { X.removeRoomAsset(el.dataset.id); }, upload: () => Fm.upload('room', r.id), 'rm-doc': (el) => X.removeDocument(el.dataset.id), p2: () => TH.go('#/coming-soon/maintenance'), 'new-inc': () => Fm.incident({}, { buildingId: r.buildingId, roomId: r.id }), 'inc-view': (el) => TH.go('#/maintenance/incidents/' + el.dataset.id),
      price: () => Fm.roomPrice(r), status: () => Fm.roomStatus(r), more: (el) => TH.pages.roomMenu(el, r),
    });
  }, { menu: 'rooms', permission: 'rooms.view', resource: { type: 'room' } });
  /* Phase 2: bảng sự cố của phòng (dùng ở card Tổng quan và tab Sự cố) */
  TH.pages.roomIncidents = (r, n) => { const list = Q.incidentsOfRoom ? Q.incidentsOfRoom(r.id).slice(0, n) : []; return list.length ? `<table class="tbl compact"><thead><tr><th>Mã</th><th>Hạng mục</th><th>Ưu tiên</th><th>Hạn</th><th>Trạng thái</th><th class="num">Chi phí</th><th></th></tr></thead><tbody>${list.map(i => `<tr><td>${U.link('#/maintenance/incidents/' + i.id, esc(i.code), 'bold')}</td><td>${esc(i.category)}</td><td>${Q.chip('priority', i.priority)}</td><td class="${Q.incidentOverdue(i) ? 'red bold' : ''}">${F.date(i.dueDate)}</td><td>${Q.incidentOverdue(i) ? Q.chip('incident', 'overdue') : Q.chip('incident', i.status)}</td><td class="num">${F.vnd(i.cost || 0)}</td><td>${U.actBtn({ icon: 'eye', label: 'Xem', act: 'inc-view', attrs: { 'data-id': i.id } })}</td></tr>`).join('')}</tbody></table>` : U.empty({ icon: 'wrench', title: 'Chưa có sự cố', text: 'Ghi nhận sự cố cho phòng này (FR-MNT-03).' }); };
})(window.TH);
