/* Spec v1.8 §4.26.8–4.26.11 – Chi lương (#/hr/salary-payments): danh sách sinh từ bảng lương Đã khóa; lọc kỳ / đơn vị / NV / trạng thái; tổng phải chi / đã chi / còn phải chi;
   ghi nhận chi từng người (partial), chi hàng loạt, import kết quả giao dịch, export, chứng từ & lịch sử chi. Không tạo Expense (§4.27.4). */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  TH.router.register('/hr/salary-payments', (root, p, q) => {
    TH.router.crumb([{ label: 'Nhân sự' }, { label: 'Chi lương' }]);
    const period = q.period || (Q.salaryPayments({}).map(s => s.period).sort().reverse()[0] || St.state.meta.period);
    const f = { period, orgUnitId: q.orgUnitId || '', employeeId: q.employeeId || '', status: q.status || '' };
    const pr = Q.payroll(period); const all = Q.salaryPayments({ period }); const rows = Q.salaryPayments(f); const t = Q.salaryTotals(all); const canPay = TH.auth.can('salary.pay');
    const periods = [...new Set(St.all('salaryPayments').map(s => s.period).concat(St.all('payrolls').map(x => x.period)).concat([St.state.meta.period]))].sort().reverse();
    root.innerHTML = `${U.pageHead({ title: 'Chi lương nhân viên', sub: 'Bảng lương đã khóa → danh sách chi lương → kiểm tra tài khoản nhận → ghi nhận lần chi → theo dõi trạng thái → hoàn tất kỳ (§4.26.8). Chi lương vào báo cáo qua Payroll/Salary Payment, không nhập lại Expense.', acts: [U.btn({ label: 'Import kết quả GD', icon: 'upload', cls: 'btn-outline', act: 'import', disabled: !canPay }), U.btn({ label: 'Export', icon: 'download', cls: 'btn-outline', act: 'export' }), U.btn({ label: 'Chi hàng loạt', icon: 'banknote', cls: 'btn-primary', act: 'bulk-pay', disabled: !canPay || !all.some(s => ['unpaid', 'partial', 'failed'].includes(s.status)), attrs: { 'data-guide': 'salary-bulk' } })] })}
    ${U.filterbar([U.field({ label: 'Kỳ lương', input: U.select({ name: 'period', value: period, options: periods.map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Đơn vị', input: U.select({ name: 'orgUnitId', value: f.orgUnitId, all: 'Toàn công ty', options: Q.orgOptions ? Q.orgOptions() : [], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Nhân viên', input: U.select({ name: 'employeeId', value: f.employeeId, all: 'Tất cả nhân viên', options: all.map(s => [s.employeeId, Q.employeeName(s.employeeId)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái chi', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.salaryPay).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    ${!pr ? U.note('info', 'Chưa có bảng lương ' + F.periodLabel(period), 'Mở kỳ lương ở Nhân sự → Bảng lương.') + '<div class="mb16"></div>' : pr.status !== 'locked' ? U.note('warn', 'Bảng lương ' + esc(pr.code) + ' đang ' + Q.label('payroll', pr.status), 'Chỉ bảng lương <b>Đã khóa</b> mới sinh danh sách chi lương (§4.26.10). ' + U.link('#/hr/payroll?period=' + period, 'Mở bảng lương →')) + '<div class="mb16"></div>' : ''}
    <div class="grid grid-4 mb16 kpi-fit">${U.kpi({ label: 'Tổng phải chi', value: F.vnd(t.due), cap: t.count + ' nhân viên · ' + F.periodLabel(period), icon: 'banknote', tone: 'blue' })}${U.kpi({ label: 'Đã chi', value: F.vnd(t.paid), cap: t.done + ' đã chi đủ · ' + t.partial + ' chi một phần', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn phải chi', value: F.vnd(t.remaining), cap: t.unpaid + ' chưa chi · ' + t.failed + ' chi lỗi', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Tiến độ', value: F.pct(t.paid, t.due) + '%', cap: pr ? 'Bảng lương ' + pr.code + ' · ' + Q.label('payroll', pr.status) : 'Chưa có bảng lương', icon: 'trending-up', tone: 'purple' })}</div>
    ${U.card({ title: 'Danh sách chi lương ' + F.periodLabel(period) + ' (' + rows.length + ')', icon: 'clipboard-list', actions: '<span id="bulk" class="row"></span>', body: null, id: 'sal-tbl', attrs: 'data-guide="salary-table"' })}`;
    const tbl = U.table(root.querySelector('#sal-tbl'), { rows, unit: 'khoản', selectable: canPay, pageSize: 15, colPrefsKey: 'salaryPayments', onSelect: (ids) => { const payable = ids.filter(id => { const s = St.get('salaryPayments', id); return s && ['unpaid', 'partial', 'failed'].includes(s.status); }); root.querySelector('#bulk').innerHTML = ids.length ? `<span class="small muted">${ids.length} đã chọn</span>${U.btn({ label: 'Chi ' + payable.length + ' khoản đã chọn', icon: 'banknote', size: 'btn-sm', cls: 'btn-primary', act: 'bulk-sel', disabled: !payable.length })}` : ''; }, footer: (rs) => { const tt = Q.salaryTotals(rs); return `<tr class="dist-total"><td colspan="3">Tổng (${rs.length})</td><td class="num">${F.vnd(tt.due)}</td><td class="num">${F.vnd(tt.paid)}</td><td class="num">${F.vnd(tt.remaining)}</td><td colspan="5"></td></tr>`; }, cols: [
      { key: 'code', label: 'Mã', sortable: true, render: s => `<b>${esc(s.code)}</b>` },
      { key: 'emp', label: 'Nhân viên', sortable: true, sortVal: s => Q.employeeName(s.employeeId), render: s => U.cell2(U.link('#/hr/' + s.employeeId, esc(Q.employeeName(s.employeeId))), esc((Q.employeeUnit(s.employeeId) || {}).name || Q.employee(s.employeeId).code || '')) },
      { key: 'acc', label: 'TK nhận (snapshot)', render: s => s.bankAccount ? U.cell2(esc(s.bankAccount.bank || '-'), esc(s.bankAccount.number || '')) : '<span class="muted">Chưa có TK</span>' },
      { key: 'due', label: 'Thực nhận', num: true, sortable: true, sortVal: s => s.amountDue, render: s => F.vnd(s.amountDue) },
      { key: 'paid', label: 'Đã chi', num: true, render: s => F.vnd(s.amountPaid) },
      { key: 'rem', label: 'Còn phải chi', num: true, sortable: true, sortVal: s => s.amountDue - s.amountPaid, render: s => { const r = Math.max(0, s.amountDue - s.amountPaid); return `<b class="${r ? 'red' : 'green'}">${F.vnd(r)}</b>`; } },
      { key: 'date', label: 'Ngày chi', render: s => s.lastPaidAt ? F.date(s.lastPaidAt) : '-' },
      { key: 'ref', label: 'Mã GD / chứng từ', render: s => { const last = (s.payments || []).filter(x => !x.failed).slice(-1)[0]; return last ? U.cell2(esc(last.ref || '-'), esc(last.evidence || last.method || '')) : '-'; } },
      { key: 'by', label: 'Người thực hiện', render: s => s.paidBy ? esc(Q.userName(s.paidBy)) : '-' },
      { key: 'status', label: 'Trạng thái', sortable: true, render: s => Q.chip('salaryPay', s.status) + (s.failReason ? `<div class="xs red">${esc(s.failReason)}</div>` : '') },
      { key: 'actions', label: 'Thao tác', render: s => U.rowActions([['unpaid', 'partial', 'failed', 'adjusted'].includes(s.status) && canPay ? U.actBtn({ icon: 'banknote', label: 'Ghi nhận chi', act: 'pay', tone: 'primary', attrs: { 'data-id': s.id, 'data-guide': 'salary-pay' } }) : '', U.moreBtn(s.id)]), hideable: false }] });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, U.formData(root.querySelector('.filterbar')))); TH.router.refresh(); } });
    U.bind(root, { reset: () => { TH.router.replaceQuery({ period }); TH.router.refresh(); }, pay: (b) => Fm.salaryPayment(St.get('salaryPayments', b.dataset.id)), 'bulk-pay': () => Fm.bulkSalary(period), 'bulk-sel': () => Fm.bulkSalary(period, tbl.selected()), import: () => TH.go('#/settings/import?type=salaryResult&period=' + period + '&back=' + encodeURIComponent('#/hr/salary-payments?period=' + period)), export: () => { const n = X.exportSalaryPayments(rows, period); U.toast('ok', 'Đã xuất danh sách chi lương', n + ' dòng'); },
      more: (b) => { const s = St.get('salaryPayments', b.dataset.id); U.menu(b, [{ label: 'Chi tiết & lịch sử chi', icon: 'history', onClick: () => Fm.salaryPayment(s) }, { label: 'Mở bảng lương', icon: 'banknote', onClick: () => TH.go('#/hr/payroll?period=' + s.period + '&emp=' + s.employeeId) }, '-', { label: 'Đánh dấu chi lỗi', icon: 'alert-triangle', disabled: !canPay || ['paid', 'cancelled'].includes(s.status), onClick: () => Fm.salaryFail(s) }, { label: 'Điều chỉnh số phải chi', icon: 'pencil', disabled: !canPay || s.status === 'cancelled', onClick: () => Fm.salaryAdjust(s) }, { label: 'Hủy khoản chi', icon: 'x-circle', danger: true, disabled: !canPay || s.amountPaid > 0 || s.status === 'cancelled', onClick: () => Fm.salaryCancel(s) }]); } });
  }, { menu: 'salary-payments', permission: 'salary.view', scopeKey: 'hr' });
})(window.TH);
