(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  /* ---------- Tài khoản & phân quyền ---------- */
  TH.router.register('/settings/users', (root, p, q) => {
    TH.router.crumb([{ label: 'Cấu hình' }, { label: 'Tài khoản & phân quyền' }]);
    if (!TH.auth.can('manageUsers')) { root.innerHTML = U.card({ body: U.empty({ icon: 'lock', title: 'Chỉ Quản trị viên truy cập', text: 'FR-IAM-02: quản lý tài khoản và phân công thuộc Admin. Chuyển vai trò ở menu góc phải để demo.', action: U.btn({ label: 'Về Tổng quan', cls: 'btn-primary', size: 'btn-sm', act: 'home' }) }) }); U.bind(root, { home: () => TH.go('#/dashboard') }); return; }
    const f = { s: q.s || '', role: q.role || '', scope: q.scope || '', status: q.status || '' };
    const all = St.all('users'); const rows = all.filter(u => (!f.s || F.norm(u.name + u.email + u.phone).includes(F.norm(f.s))) && (!f.role || u.role === f.role) && (!f.scope || F.norm(u.scope).includes(F.norm(f.scope))) && (!f.status || u.status === f.status));
    const cnt = (s) => all.filter(u => u.status === s).length;
    root.innerHTML = `${U.pageHead({ title: 'Tài khoản & phân quyền', sub: 'Quản lý tài khoản người dùng, vai trò và phân quyền truy cập hệ thống.', acts: [U.btn({ label: 'Tạo tài khoản', icon: 'user-plus', cls: 'btn-primary', act: 'add', attrs: { 'data-guide': 'user-add' } })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập tên, email, SĐT...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Vai trò', input: U.select({ name: 'role', value: f.role, all: 'Tất cả vai trò', options: Object.entries(TH.auth.ROLE_LABEL), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phạm vi', input: U.select({ name: 'scope', value: f.scope, all: 'Tất cả khu vực', options: ['Toàn hệ thống', 'Tài chính', ...St.where('buildings', b => !b.stub).map(b => b.name)], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.user).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Đăng nhập gần nhất', input: U.input({ name: 'range', type: 'date', attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng tài khoản', value: all.length, cap: 'Tổng số người dùng trong hệ thống', icon: 'users', tone: 'blue' })}${U.kpi({ label: 'Đang hoạt động', value: cnt('active'), cap: F.pct(cnt('active'), all.length) + '% tổng tài khoản', icon: 'user-check', tone: 'green' })}${U.kpi({ label: 'Tài khoản bị khóa', value: cnt('locked'), cap: F.pct(cnt('locked'), all.length) + '% tổng tài khoản', icon: 'lock', tone: 'red' })}${U.kpi({ label: 'Tài khoản hết hiệu lực', value: cnt('expired'), cap: F.pct(cnt('expired'), all.length) + '% tổng tài khoản', icon: 'clock', tone: 'amber' })}</div>
    ${U.card({ title: `Danh sách người dùng <span class="muted" style="font-weight:400">(${rows.length} tài khoản)</span>`, actions: U.btn({ label: 'Xuất dữ liệu', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export' }) + U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', cls: 'btn-outline', act: 'cols' }), body: null, id: 'tbl-card' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const cols = [
      { key: 'name', label: 'Người dùng', sortable: true, render: u => `<span class="row">${U.avatar(u.name, 'sm')}<b>${esc(u.name)}</b>${u.source === 'user' ? '<span class="chip blue xs">mới</span>' : ''}</span>` }, { key: 'email', label: 'Email / SĐT', render: u => U.cell2(esc(u.email), esc(u.phone)) },
      { key: 'role', label: 'Vai trò', sortable: true, render: u => Q.chip('role', u.role) + (['sale', 'tech', 'kythuat'].includes(u.role) ? TH.phase.tag(2) : '') }, { key: 'scope', label: 'Phạm vi phụ trách', render: u => esc(u.scope) }, { key: 'status', label: 'Trạng thái', sortable: true, render: u => Q.chip('user', u.status) },
      { key: 'lastLogin', label: 'Đăng nhập gần nhất', sortable: true, render: u => u.lastLogin ? F.datetime(u.lastLogin) : '-' }, { key: 'effectiveDate', label: 'Ngày hiệu lực', render: u => F.date(u.effectiveDate) },
      { key: 'actions', label: 'Thao tác', render: u => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': u.id } }), U.moreBtn(u.id)]) }];
    const tbl = U.table(wrap, { rows, cols, selectable: true, unit: 'tài khoản', colPrefsKey: 'users' });
    const view = (u) => U.modal({ title: u.name, sub: TH.auth.ROLE_LABEL[u.role], body: U.kv([['Tên đăng nhập', esc(u.username)], ['Email', esc(u.email)], ['SĐT', esc(u.phone)], ['Vai trò', Q.chip('role', u.role)], ['Phạm vi', esc(u.scope)], ['Trạng thái', Q.chip('user', u.status)], ['Ngày hiệu lực', F.date(u.effectiveDate)], ['Đăng nhập gần nhất', u.lastLogin ? F.datetime(u.lastLogin) : '-'], ['Ghi chú', esc(u.note || '-')]], 'one'), footer: U.btn({ label: 'Sửa', icon: 'pencil', cls: 'btn-outline', act: 'e' }) + U.btn({ label: 'Đóng', cls: 'btn-primary', act: 'c' }), onMount: (m) => U.bind(m.el, { e: () => { m.close(); Fm.user(u); }, c: () => m.close() }) });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); delete d.range; TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { add: () => Fm.user(), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, cols: (b) => U.columnMenu(b, tbl, cols), view: (b) => view(St.get('users', b.dataset.id)), export: () => { F.download('tai-khoan.csv', F.csv(rows.map(u => [u.name, u.email, u.phone, TH.auth.ROLE_LABEL[u.role], u.scope, Q.label('user', u.status), u.lastLogin || '', u.effectiveDate]), ['Tên', 'Email', 'SĐT', 'Vai trò', 'Phạm vi', 'Trạng thái', 'Đăng nhập', 'Hiệu lực']), 'text/csv'); U.toast('ok', 'Đã xuất dữ liệu'); },
      more: (b) => { const u = St.get('users', b.dataset.id); U.menu(b, [{ label: 'Xem', icon: 'eye', onClick: () => view(u) }, { label: 'Sửa / Phân công tòa', icon: 'pencil', onClick: () => Fm.user(u) }, { label: 'Đặt lại mật khẩu', icon: 'key', onClick: () => { X.resetPassword(u.id); U.toast('ok', 'Đã gửi email đặt lại mật khẩu (mô phỏng)', u.email); } }, '-', u.status === 'locked' ? { label: 'Mở khóa', icon: 'unlock', onClick: () => { X.setUserStatus(u.id, 'active'); U.toast('ok', 'Đã mở khóa'); } } : { label: 'Khóa tài khoản', icon: 'lock', danger: true, disabled: u.id === TH.auth.session().userId, title: u.id === TH.auth.session().userId ? 'Không khóa tài khoản đang đăng nhập' : '', onClick: () => { X.setUserStatus(u.id, 'locked'); U.toast('ok', 'Đã khóa tài khoản', 'Lịch sử giao dịch của người này được giữ (FR-IAM-02)'); } }]); } });
  }, { menu: 'users', permission: 'users.manage' });

  /* ---------- Danh mục dùng chung ---------- */
  TH.router.register('/settings/catalog', (root, p, q) => {
    TH.router.crumb([{ label: 'Cấu hình' }, { label: 'Danh mục dùng chung' }]);
    const tab = q.tab || 'services'; const canEdit = TH.auth.can('manageCatalog');
    const head = U.pageHead({ title: 'Danh mục dùng chung', sub: 'Quản lý dịch vụ, bảng giá, nhóm chi phí và các danh mục tham chiếu trong hệ thống.', acts: [U.btn({ label: 'Áp dụng bảng giá', icon: 'table', cls: 'btn-outline', act: 'apply', disabled: !canEdit }), U.btn({ label: 'Thêm dịch vụ', icon: 'plus', cls: 'btn-primary', act: 'add-svc', disabled: !canEdit, title: canEdit ? '' : 'Cần vai trò Admin/Kế toán' })] });
    const tabs = U.tabs([{ key: 'services', label: 'Dịch vụ & Bảng giá', icon: 'settings' }, { key: 'areas', label: 'Khu nhà', icon: 'map-pin' }, { key: 'teams', label: 'Team kinh doanh', icon: 'users' }, { key: 'groups', label: 'Nhóm chi phí', icon: 'layers' }, { key: 'methods', label: 'Phương thức thanh toán', icon: 'credit-card' }, { key: 'master', label: 'Master Data', icon: 'database' }, { key: 'positions', label: 'Chức danh', icon: 'briefcase' }, { key: 'sources', label: 'Nguồn khách', icon: 'user', p2: true }, ...(TH.phase.on(2) ? [{ key: 'vendors', label: 'Nhà cung cấp', icon: 'hard-hat', phase: 2 }] : [])], tab, 'boxed');
    if (tab === 'services') {
      const f = { s: q.s || '', group: q.group || '', status: q.status || '' }; const svcs = St.all('services'); const rows = svcs.filter(s => (!f.s || F.norm(s.name).includes(F.norm(f.s))) && (!f.group || s.group === f.group) && (!f.status || s.status === f.status));
      const sel = St.get('services', q.sel) || null; const hist = sel ? St.where('priceHistory', h => h.serviceId === sel.id).sort((a, b) => F.cmp(b.date, a.date)) : []; const prices = sel ? Q.servicePrices(sel.id) : []; const usage = sel ? Q.servicePriceUsage(sel.id) : [];
      const METHODS = { fixed: 'Theo gói cố định', meter: 'Theo chỉ số', per_room: 'Theo phòng', per_vehicle: 'Theo xe' };
      root.innerHTML = head + tabs + `${U.card({ title: `Danh sách dịch vụ <span class="muted" style="font-weight:400">(${rows.length})</span>`, body: null, id: 'svc-card', attrs: 'data-guide="catalog-table"' })}
        <div id="svc-editor-source" hidden><div class="side-stack"><form id="svcf">${sel ? U.card({ title: 'Thông tin dịch vụ', icon: 'info', actions: U.btn({ label: 'Xóa', icon: 'trash', size: 'btn-sm', cls: 'btn-danger', act: 'del', disabled: !canEdit }), body: `<div class="col" style="gap:12px">
          ${U.field({ label: 'Tên dịch vụ', req: true, input: U.input({ name: 'name', value: sel.name }) })}${U.field({ label: 'Nhóm chi phí', req: true, input: U.select({ name: 'group', value: sel.group, options: ['Dịch vụ tiện ích', 'Dịch vụ chung', 'Dịch vụ khác'] }) })}
          <div class="form-grid">${U.field({ label: 'Đơn vị', req: true, input: U.select({ name: 'unit', value: sel.unit, options: [sel.unit, 'Tháng', 'kWh', 'm³', 'Xe/tháng', 'Lần'].filter((v, i, a) => a.indexOf(v) === i) }) })}${U.field({ label: 'Cách tính', req: true, input: U.select({ name: 'method', value: sel.method, options: Object.entries(METHODS) }) })}</div>
          ${U.field({ label: 'Giá mặc định (VND)', req: true, input: U.money({ name: 'price', value: sel.price }) })}
          <div class="field"><label>Phạm vi áp dụng<span class="req">*</span></label><div class="col gap4"><label class="chk"><input type="radio" name="scope" value="all" ${sel.scope === 'all' ? 'checked' : ''}> Tất cả tòa nhà</label><label class="chk"><input type="radio" name="scope" value="buildings" ${sel.scope === 'buildings' ? 'checked' : ''}> Theo tòa nhà</label><label class="chk"><input type="radio" name="scope" value="group" disabled> Theo nhóm phòng <span class="tag-p">P2</span></label></div></div>
          ${U.field({ label: 'Chọn tòa nhà', input: `<div class="row wrap gap12">${St.where('buildings', b => !b.stub).map(b => U.check({ name: 'b_' + b.id, label: b.name, checked: (sel.buildingIds || []).includes(b.id), attrs: sel.scope !== 'buildings' ? { disabled: true } : {} })).join('')}</div>` })}
          <div class="form-grid">${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: sel.effectiveFrom }) })}${U.field({ label: 'Ngày hết hiệu lực', input: U.date({ name: 'effectiveTo', value: sel.effectiveTo || '' }) })}</div>
          ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: sel.note || '', attrs: { maxlength: 500 } }), help: (sel.note || '').length + '/500' })}
          <div class="row between"><div><b class="small">Trạng thái</b><div class="xs muted">Dịch vụ sẽ hiển thị và áp dụng trong hệ thống</div></div><span class="row gap4"><span class="small ${sel.status === 'active' ? 'green' : 'muted'}">${sel.status === 'active' ? 'Đang hoạt động' : 'Ngừng hoạt động'}</span>${U.toggle(sel.status === 'active', 'toggle')}</span></div>
          ${U.btn({ label: 'Lưu thay đổi', icon: 'save', cls: 'btn-primary btn-block', act: 'save', disabled: !canEdit })}<div class="xs muted">Đổi giá tạo dòng lịch sử mới; hóa đơn đã phát hành không bị hồi tố (BR-21).</div></div>` }) : ''}</form>
        ${sel ? U.card({ title: 'Bảng giá 2 lớp (§12.9)', icon: 'layers', sub: 'Giá riêng theo tòa đang hiệu lực → ưu tiên; ngược lại dùng giá mặc định', actions: U.btn({ label: 'Override theo tòa', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'override', disabled: !canEdit }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Phạm vi</th><th class="num">Giá</th><th>Từ</th><th>Đến</th><th>Trạng thái</th><th>Lý do</th><th></th></tr></thead><tbody>${prices.map(p => `<tr><td>${p.scope === 'GLOBAL' ? U.chip('Mặc định', 'gray') : U.chip(Q.building(p.buildingId).name || 'Tòa', 'purple')}</td><td class="num"><b>${F.vnd(p.price)}</b></td><td>${F.date(p.effectiveFrom)}</td><td>${p.effectiveTo ? F.date(p.effectiveTo) : '—'}</td><td>${U.chip(p.status === 'inactive' ? 'Đã ngừng' : p.effectiveFrom > F.today() ? 'Sắp hiệu lực' : (!p.effectiveTo || p.effectiveTo >= F.today()) ? 'Đang hiệu lực' : 'Hết hiệu lực', p.status === 'inactive' ? 'gray' : p.effectiveFrom > F.today() ? 'blue' : (!p.effectiveTo || p.effectiveTo >= F.today()) ? 'green' : 'gray')}</td><td class="xs">${esc(p.reason || '')}${p.sourceOcr ? ' <span class="purple">· OCR ' + esc(p.sourceOcr.jobCode || '') + '</span>' : ''}</td><td class="tr">${p.scope === 'BUILDING' && p.status !== 'inactive' && (!p.effectiveTo || p.effectiveTo >= F.today()) ? U.iconBtn('minus-circle', 'end-price', 'Ngừng hiệu lực', { 'data-id': p.id, disabled: !canEdit }) : ''}</td></tr>`).join('') || '<tr><td colspan="7" class="muted tc">Chưa có bảng giá</td></tr>'}</tbody></table><div class="card-b" style="border-top:1px solid var(--border)"><b class="small">Tòa nào đang dùng giá nào (hôm nay)</b><div class="row wrap gap8 mt8">${usage.map(u => `<span class="chip ${u.scope === 'BUILDING' ? 'purple' : 'gray'}" title="${u.scope === 'BUILDING' ? 'Giá riêng tòa' : 'Giá mặc định'}">${esc(u.building.name)} · ${F.vnd(u.price)}</span>`).join('')}</div></div>` }) : ''}
        ${sel ? U.card({ title: 'Lịch sử áp dụng', icon: 'history', actions: '<span class="small muted">' + hist.length + ' lần</span>', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Thời gian áp dụng</th><th class="num">Giá (VND)</th><th>Phạm vi</th><th>Người cập nhật</th></tr></thead><tbody>${hist.map((h, i) => `<tr><td>${i + 1}</td><td>${F.date(h.date)}</td><td class="num">${F.vnd(h.price)}</td><td>${esc(h.scope)}</td><td>${esc(h.userName || Q.userName(h.userId))}</td></tr>`).join('')}</tbody></table>` }) : ''}</div></div>`;
      const card = root.querySelector('#svc-card');
      card.insertAdjacentHTML('beforeend', `<div class="filterbar" style="border-bottom:1px solid var(--border)">${U.field({ input: U.input({ name: 's', value: f.s, placeholder: 'Tìm kiếm dịch vụ...', icon: 'search', attrs: { 'data-on': 'sf' } }), cls: 'wide' })}${U.field({ input: U.select({ name: 'group', value: f.group, all: 'Tất cả nhóm', options: ['Dịch vụ tiện ích', 'Dịch vụ chung', 'Dịch vụ khác'], attrs: { 'data-on': 'sf' } }) })}${U.field({ input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: [['active', 'Đang hoạt động'], ['inactive', 'Ngừng hoạt động']], attrs: { 'data-on': 'sf' } }) })}${U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' })}</div>`);
      const wrap = document.createElement('div'); card.appendChild(wrap);
      U.table(wrap, { rows, selectable: true, unit: 'dịch vụ', rowClass: s => sel && s.id === sel.id ? 'selected' : '', cols: [
        { key: 'name', label: 'Tên dịch vụ', sortable: true, render: s => `<a class="row link" data-act="sel" data-id="${s.id}"><span class="svc-icon">${I(s.icon || 'package')}</span><b>${esc(s.name)}</b></a>` }, { key: 'unit', label: 'Đơn vị' }, { key: 'method', label: 'Cách tính', render: s => METHODS[s.method] || s.method }, { key: 'price', label: 'Giá mặc định', num: true, sortable: true, render: s => F.vnd(Q.servicePrice(s.id, null)) }, { key: 'ovr', label: 'Giá riêng theo tòa', render: s => { const n = St.rawAll('servicePrices').filter(p => p && p.serviceId === s.id && p.scope === 'BUILDING' && p.status !== 'inactive' && (!p.effectiveTo || p.effectiveTo >= F.today())).length; return n ? U.chip(n + ' tòa', 'purple') : '<span class="muted xs">—</span>'; } },
        { key: 'scope', label: 'Phạm vi áp dụng', render: s => s.scope === 'all' ? 'Tất cả tòa nhà' : (s.buildingIds || []).map(id => Q.building(id).name).join(', ') || 'Theo tòa' }, { key: 'eff', label: 'Hiệu lực', render: s => F.date(s.effectiveFrom) }, { key: 'status', label: 'Trạng thái', render: s => U.chip(s.status === 'active' ? 'Đang hoạt động' : 'Ngừng hoạt động', s.status === 'active' ? 'green' : 'gray') }, { key: 'actions', label: '', render: s => U.moreBtn(s.id) }] });
      const editorSource = root.querySelector('#svc-editor-source');
      const editor = sel ? U.drawer({ title: 'Thông tin dịch vụ', sub: esc(sel.name), wide: true, body: editorSource.innerHTML, onClose: () => { TH.router.replaceQuery(Object.assign({}, f, { sel: '' })); root.querySelectorAll('tr.selected').forEach(row => row.classList.remove('selected')); } }) : null;
      editorSource.remove();
      const form = editor ? editor.el.querySelector('#svcf') : null;
      form && form.addEventListener('change', (e) => { if (e.target.name === 'scope') form.querySelectorAll('input[name^=b_]').forEach(c => c.disabled = e.target.value !== 'buildings'); });
      U.onChange(root, { sf: () => { const d = U.formData(card.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d, { sel: sel ? sel.id : '' })); TH.router.refresh(); } });
      const reopenEditor = () => { if (editor) editor.close(); TH.router.replaceQuery(Object.assign({}, f, { sel: sel.id })); TH.router.refresh(); };
      const handlers = {
        tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, sel: (el) => { TH.router.replaceQuery(Object.assign({}, f, { sel: el.dataset.id })); TH.router.refresh(); }, reset: () => { TH.router.replaceQuery({ sel: sel ? sel.id : '' }); TH.router.refresh(); },
        'add-svc': () => { const m = U.modal({ title: 'Thêm dịch vụ', body: `<div class="form-grid">${U.field({ label: 'Tên dịch vụ', req: true, input: U.input({ name: 'name', placeholder: 'Sạc xe điện' }), cls: 'span2' })}${U.field({ label: 'Đơn vị', req: true, input: U.input({ name: 'unit', value: 'Tháng' }) })}${U.field({ label: 'Cách tính', input: U.select({ name: 'method', value: 'fixed', options: Object.entries(METHODS) }) })}${U.field({ label: 'Giá mặc định', req: true, input: U.money({ name: 'price' }) })}${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Nhóm', input: U.select({ name: 'group', value: 'Dịch vụ tiện ích', options: ['Dịch vụ tiện ích', 'Dịch vụ chung', 'Dịch vụ khác'] }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu dịch vụ', cls: 'btn-primary', act: 's', icon: 'save' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const s = X.saveService(m.data()); m.close(); U.toast('ok', 'Đã thêm dịch vụ ' + s.name); TH.router.replaceQuery({ sel: s.id }); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } } }); },
        save: () => { try { const d = U.formData(form); d.buildingIds = St.all('buildings').filter(b => d['b_' + b.id]).map(b => b.id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); d.id = sel.id; X.saveService(d); U.toast('ok', 'Đã lưu dịch vụ ' + d.name); reopenEditor(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
        toggle: () => { try { X.saveService({ id: sel.id, status: sel.status === 'active' ? 'inactive' : 'active', name: sel.name, unit: sel.unit, price: sel.price, effectiveFrom: sel.effectiveFrom }); U.toast('ok', 'Đã đổi trạng thái'); reopenEditor(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
        del: async () => { if (await U.confirm({ title: 'Xóa dịch vụ ' + sel.name + '?', text: 'Bị chặn nếu đang dùng trong hợp đồng hiệu lực – nên dùng Ngừng hoạt động.', ok: 'Xóa', danger: true })) { try { X.deleteService(sel.id); U.toast('ok', 'Đã xóa'); if (editor) editor.close(); TH.router.replaceQuery({}); TH.router.refresh(); } catch (e) { U.toast('err', 'Không xóa được', e.message); } } },
        apply: () => { const m = U.modal({ title: 'Áp dụng bảng giá', sub: 'Cập nhật dịch vụ mặc định cho phòng chưa có hợp đồng trong các tòa đã chọn. Hợp đồng hiệu lực giữ snapshot (BR-21).', body: `<div class="field"><label>Tòa nhà</label><div class="row wrap gap12">${St.where('buildings', b => !b.stub).map(b => U.check({ name: 'b_' + b.id, label: b.name, checked: true })).join('')}</div></div><div class="field mt12"><label>Dịch vụ mặc định</label><div class="row wrap gap12">${St.where('services', s => s.status === 'active' && s.method !== 'meter').map(s => U.check({ name: 's_' + s.id, label: s.name, checked: ['INTERNET', 'QUANLY', 'GUIXE'].includes(s.code) })).join('')}</div></div>${U.field({ label: 'Ngày hiệu lực', input: U.date({ name: 'eff', value: F.today() }), cls: 'mt12' })}`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Áp dụng', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); const bIds = St.all('buildings').filter(b => d['b_' + b.id]).map(b => b.id); const sIds = St.all('services').filter(s => d['s_' + s.id]).map(s => s.id); try { const n = X.applyPriceList({ buildingIds: bIds, serviceIds: sIds, effectiveFrom: d.eff }); m.close(); U.toast('ok', 'Đã áp bảng giá cho ' + n + ' phòng'); } catch (e) { U.toast('err', 'Không áp được', e.message); } } }); },
        more: (b) => { const s = St.get('services', b.dataset.id); U.menu(b, [{ label: 'Chọn / xem chi tiết', icon: 'eye', onClick: () => { TH.router.replaceQuery(Object.assign({}, f, { sel: s.id })); TH.router.refresh(); } }, { label: s.status === 'active' ? 'Ngừng hoạt động' : 'Kích hoạt', icon: s.status === 'active' ? 'minus-circle' : 'check', onClick: () => X.saveService({ id: s.id, status: s.status === 'active' ? 'inactive' : 'active', name: s.name, unit: s.unit, price: s.price, effectiveFrom: s.effectiveFrom }) }]); },
        override: () => TH.forms.servicePrice({ serviceId: sel ? sel.id : '', scope: 'BUILDING' }), 'end-price': async (b) => { if (!(await U.confirm({ title: 'Ngừng giá riêng theo tòa?', text: 'Tòa sẽ dùng giá mặc định từ hôm nay; lịch sử giữ nguyên.' }))) return; try { X.endServicePrice(b.dataset.id, F.today(), 'Ngừng từ Danh mục dịch vụ'); U.toast('ok', 'Đã ngừng giá riêng'); reopenEditor(); } catch (e) { U.toast('err', 'Lỗi', e.message); } },
      };
      U.bind(root, handlers); if (editor) U.bind(editor.el, handlers);
    } else if (tab === 'areas' || tab === 'teams') {
      const col = tab === 'areas' ? 'areas' : 'salesTeams', items = St.all(col);
      const leadName = it => tab === 'areas' ? ((St.get('employees', it.leadEmployeeId) || {}).name || '-') : Q.userName(it.leadUserId);
      root.innerHTML = head + tabs + U.card({ title: tab === 'areas' ? 'Khu nhà' : 'Team kinh doanh', sub: tab === 'areas' ? 'Dimension dùng chung cho tòa, nhân sự, tài chính và báo cáo.' : 'Nhóm nhân viên kinh doanh dùng cho CRM và sổ đối soát.', actions: U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add', disabled: !canEdit }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Tên</th><th>${tab === 'areas' ? 'Quận/huyện' : 'Thành viên'}</th><th>Trưởng nhóm</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(it => `<tr><td class="mono">${esc(it.code)}</td><td><b>${esc(it.name)}</b></td><td>${tab === 'areas' ? esc((it.districts || []).join(', ')) : St.where('users', u => u.teamId === it.id).length + ' người'}</td><td>${esc(leadName(it))}</td><td>${U.chip(it.status === 'active' ? 'Đang hoạt động' : 'Ngừng', it.status === 'active' ? 'green' : 'gray')}</td><td>${U.iconBtn('pencil', 'edit', 'Sửa', { 'data-id': it.id, disabled: !canEdit })}</td></tr>`).join('')}</tbody></table>` });
      const editMaster = (it = {}) => { const employeeOpts = St.where('employees', e => e.status === 'working').map(e => [e.id, e.name]), saleOpts = Q.salesUsers().map(u => [u.id, u.name]); const m = U.modal({ title: (it.id ? 'Sửa ' : 'Thêm ') + (tab === 'areas' ? 'khu nhà' : 'team kinh doanh'), size: 'sm', body: `<div class="col gap12">${U.field({ label: 'Mã', input: U.input({ name: 'code', value: it.code || '' }) })}${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name', value: it.name || '' }) })}${tab === 'areas' ? U.field({ label: 'Quận/huyện', input: U.input({ name: 'districtsText', value: (it.districts || []).join(', '), placeholder: 'Cầu Giấy, Nam Từ Liêm' }) }) + U.field({ label: 'Trưởng khu', input: U.select({ name: 'leadEmployeeId', value: it.leadEmployeeId || '', all: 'Chưa gán', options: employeeOpts }) }) : U.field({ label: 'Trưởng team', input: U.select({ name: 'leadUserId', value: it.leadUserId || '', all: 'Chưa gán', options: saleOpts }) })}${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: it.status || 'active', options: [['active', 'Đang hoạt động'], ['inactive', 'Ngừng']] }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); if (!d.name) throw new Error('Nhập tên'); if (d.districtsText !== undefined) { d.districts = d.districtsText.split(',').map(x => x.trim()).filter(Boolean); delete d.districtsText; } if (it.id) d.id = it.id; X.saveCatalogItem(col, d); m.close(); U.toast('ok', 'Đã lưu'); TH.router.refresh(); } }); };
      U.bind(root, { tab: el => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, add: () => editMaster(), edit: el => editMaster(St.get(col, el.dataset.id)) });
    } else if (tab === 'vendors' && TH.phase.on(2)) { TH.pages.vendorsTab(root, head, tabs);
    } else if (tab === 'master') {
      // Spec v1.8 §7.5 Master Data: danh mục cấu hình được (loại tòa, loại phòng, trạng thái khách, lý do kết thúc, vai trò phân công, loại đơn vị, sự kiện thông báo, mốc thu)
      const KINDS = [['buildingType', 'Ký hiệu / loại tòa', 'Mở rộng ngoài T/S/G; áp dụng theo hiệu lực trên từng tòa (§4.6)'], ['roomType', 'Loại phòng', '§4.7'], ['customerStatus', 'Trạng thái khách hàng', 'Chỉ 1 field Trạng thái, cấu hình được (§4.8 – đã chốt)'], ['contractEndReason', 'Lý do kết thúc hợp đồng', '§4.17'], ['assignmentRole', 'Vai trò phân công', 'Phụ trách chính quyết định quản lý tòa (§4.25.2)'], ['orgUnitType', 'Loại đơn vị tổ chức', '§4.23'], ['notificationEvent', 'Sự kiện thông báo', '§4.20'], ['milestone', 'Mốc thu M1/M2/M3', 'Ngày mốc cấu hình được (§4.26.2)']];
      const kind = q.kind || 'buildingType'; const cur = KINDS.find(k => k[0] === kind) || KINDS[0]; const items = Q.md(kind, false); const canMD = TH.auth.can('masterData.manage');
      root.innerHTML = head + tabs + `<div class="two-col wide" style="grid-template-columns:260px minmax(0,1fr)"><div>${U.card({ title: 'Danh mục', icon: 'database', bodyCls: 'tight', body: `<div class="org-tree">${KINDS.map(k => `<div class="org-row ${k[0] === kind ? 'on' : ''}" data-act="kind" data-k="${k[0]}"><span class="org-name"><b>${esc(k[1])}</b><div class="xs muted">${Q.md(k[0], false).length} mục</div></span></div>`).join('')}</div>` })}</div>
        <div>${U.card({ title: esc(cur[1]), icon: 'list', sub: esc(cur[2]), actions: U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'md-add', disabled: !canMD, title: canMD ? '' : 'Chỉ Admin (§7.5)' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Tên</th>${kind === 'milestone' ? '<th class="num">Ngày trong tháng</th>' : ''}${['buildingType', 'customerStatus', 'assignmentRole'].includes(kind) ? '<th>Màu</th>' : ''}<th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(it => `<tr><td class="mono">${esc(it.code)}</td><td><b>${esc(it.name)}</b></td>${kind === 'milestone' ? `<td class="num">${esc(String(it.day || ''))}</td>` : ''}${['buildingType', 'customerStatus', 'assignmentRole'].includes(kind) ? `<td>${U.chip(it.color || 'gray', it.color || 'gray')}</td>` : ''}<td>${U.chip(it.status === 'inactive' ? 'Ngừng' : 'Đang dùng', it.status === 'inactive' ? 'gray' : 'green')}</td><td class="tr">${U.iconBtn('pencil', 'md-edit', 'Sửa', { 'data-id': it.id, disabled: !canMD })}${U.iconBtn(it.status === 'inactive' ? 'check' : 'minus-circle', 'md-toggle', it.status === 'inactive' ? 'Kích hoạt' : 'Ngừng dùng', { 'data-id': it.id, disabled: !canMD })}</td></tr>`).join('') || '<tr><td colspan="6" class="muted tc">Chưa có mục</td></tr>'}</tbody></table>` })}${U.note('info', 'Quy tắc', 'Không xóa cứng mục đã dùng – chỉ Ngừng dùng; mọi thay đổi có audit (§19). Loại tòa và trạng thái khách được hệ thống tham chiếu theo mã.')}</div></div>`;
      const edit = (it = {}) => { const m = U.modal({ title: (it.id ? 'Sửa ' : 'Thêm ') + cur[1], size: 'sm', body: `<div class="col gap12">${U.field({ label: 'Mã', input: U.input({ name: 'code', value: it.code || '', readonly: !!it.id, placeholder: 'Tự sinh nếu trống' }) })}${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name', value: it.name || '' }) })}${kind === 'milestone' ? U.field({ label: 'Ngày trong tháng', req: true, input: U.input({ name: 'day', type: 'number', value: it.day || '' }) }) : ''}${['buildingType', 'customerStatus', 'assignmentRole'].includes(kind) ? U.field({ label: 'Màu', input: U.select({ name: 'color', value: it.color || 'gray', options: ['blue', 'green', 'amber', 'red', 'purple', 'teal', 'orange', 'gray'] }) }) : ''}${it.id ? U.field({ label: 'Lý do thay đổi', input: U.input({ name: 'reason' }) }) : ''}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); if (kind === 'milestone') d.day = Number(d.day); X.saveMasterData(Object.assign({ id: it.id, kind }, d)); m.close(); U.toast('ok', 'Đã lưu ' + cur[1]); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } } }); };
      U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, kind: (el) => { TH.router.replaceQuery({ tab: 'master', kind: el.dataset.k }); TH.router.refresh(); }, 'md-add': () => edit(), 'md-edit': (b) => edit(St.rawGet('masterData', b.dataset.id)), 'md-toggle': (b) => { try { X.toggleMasterData(b.dataset.id); TH.router.refresh(); } catch (e) { U.toast('err', 'Không đổi được', e.message); } }, 'add-svc': () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); }, apply: () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); } });
    } else if (tab === 'positions') {
      const items = St.rawAll('positions').filter(Boolean); const canMD = TH.auth.can('masterData.manage') || TH.auth.can('org.manage');
      root.innerHTML = head + tabs + U.card({ title: 'Chức danh (§12.17.2)', sub: 'Mã, tên, cấp quản lý, loại đơn vị áp dụng, ngày hiệu lực', actions: U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add', disabled: !canMD }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Tên</th><th class="num">Cấp</th><th>Loại đơn vị</th><th>Hiệu lực</th><th class="num">NV đang giữ</th><th>Trạng thái</th><th></th></tr></thead><tbody>${items.sort((a, b) => (a.level || 9) - (b.level || 9)).map(it => `<tr><td class="mono">${esc(it.code)}</td><td><b>${esc(it.name)}</b></td><td class="num">${it.level || '-'}</td><td class="xs">${(it.unitTypes || []).map(t => Q.label('orgUnitType', t)).join(', ')}</td><td>${F.date(it.effectiveFrom)}</td><td class="num">${St.rawAll('employmentAssignments').filter(a => a && a.positionId === it.id && !a.effectiveTo).length}</td><td>${U.chip(it.status === 'inactive' ? 'Ngừng' : 'Đang dùng', it.status === 'inactive' ? 'gray' : 'green')}</td><td class="tr">${U.iconBtn('pencil', 'edit', 'Sửa', { 'data-id': it.id, disabled: !canMD })}</td></tr>`).join('')}</tbody></table>` });
      const edit = (it = {}) => { const m = U.modal({ title: (it.id ? 'Sửa ' : 'Thêm ') + 'chức danh', size: 'sm', body: `<div class="col gap12">${U.field({ label: 'Mã', input: U.input({ name: 'code', value: it.code || '', readonly: !!it.id }) })}${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name', value: it.name || '' }) })}${U.field({ label: 'Cấp quản lý (1 = cao nhất)', input: U.input({ name: 'level', type: 'number', value: it.level || 4 }) })}${U.field({ label: 'Loại đơn vị áp dụng', input: `<div class="row wrap gap12">${Object.entries(Q.L.orgUnitType).map(([k, v]) => U.check({ name: 'ut_' + k, label: v[0], checked: (it.unitTypes || []).includes(k) })).join('')}</div>` })}${U.field({ label: 'Ngày hiệu lực', input: U.date({ name: 'effectiveFrom', value: it.effectiveFrom || F.today() }) })}${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: it.status || 'active', options: [['active', 'Đang dùng'], ['inactive', 'Ngừng']] }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); if (!d.name) throw new Error('Nhập tên'); const unitTypes = Object.keys(Q.L.orgUnitType).filter(k => d['ut_' + k]); const rec = { name: d.name, level: Number(d.level) || 4, unitTypes, effectiveFrom: d.effectiveFrom, status: d.status }; if (it.id) St.update('positions', it.id, rec); else St.add('positions', Object.assign({ code: d.code || St.nextCode('positions', 'CD', 2) }, rec)); St.audit(it.id ? 'update' : 'create', 'position', it.id || '', (it.id ? 'Cập nhật' : 'Thêm') + ' chức danh ' + d.name); m.close(); U.toast('ok', 'Đã lưu chức danh'); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } } }); };
      U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, add: () => edit(), edit: (b) => edit(St.rawGet('positions', b.dataset.id)), 'add-svc': () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); }, apply: () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); } });
    } else if (tab === 'groups' || tab === 'methods' || (tab === 'sources' && TH.phase.on(2))) {
      const col = tab === 'groups' ? 'expenseGroups' : tab === 'methods' ? 'payMethods' : 'leadSources'; const items = St.all(col);
      root.innerHTML = head + tabs + U.card({ title: tab === 'groups' ? 'Nhóm chi phí (FR-FIN-12)' : tab === 'sources' ? 'Nguồn khách (CRM – Q18) ' + TH.phase.tag(2) : 'Phương thức thanh toán', actions: U.btn({ label: 'Thêm', icon: 'plus', size: 'btn-sm', cls: 'btn-primary', act: 'add', disabled: !canEdit }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Tên</th>${tab === 'groups' ? '<th>Nhóm cha</th><th>Nhóm đầy đủ</th>' : ''}<th>Trạng thái</th><th></th></tr></thead><tbody>${items.map(it => `<tr><td class="mono">${esc(it.code)}</td><td><b>${esc(it.name)}</b></td>${tab === 'groups' ? `<td>${esc((Q.expenseCategory(it.parentCode) || {}).name || '— Cấp 1 —')}</td><td>${esc(it.fullName || '')}</td>` : ''}<td>${U.chip(it.status === 'active' ? 'Đang hoạt động' : 'Ngừng', it.status === 'active' ? 'green' : 'gray')}</td><td class="tr">${U.iconBtn('pencil', 'edit', canEdit ? 'Sửa' : 'Cần vai trò Admin/Kế toán', { 'data-id': it.id, disabled: !canEdit })}${U.iconBtn('trash', 'rm', canEdit ? 'Xóa' : 'Cần vai trò Admin/Kế toán', { 'data-id': it.id, disabled: !canEdit })}</td></tr>`).join('')}</tbody></table>` });
      const edit = (it = {}) => { const m = U.modal({ title: (it.id ? 'Sửa ' : 'Thêm ') + (tab === 'groups' ? 'nhóm chi phí' : tab === 'sources' ? 'nguồn khách' : 'phương thức'), size: 'sm', body: `<div class="col gap12">${U.field({ label: 'Tên', req: true, input: U.input({ name: 'name', value: it.name || '' }) })}${tab === 'groups' ? U.field({ label: 'Nhóm cha', input: U.select({ name: 'parentCode', value: it.parentCode || '', all: '— Đây là nhóm cấp 1 —', options: St.all('expenseGroups').filter(g => !g.parentCode && g.id !== it.id).map(g => [g.code, g.name]) }) }) + U.field({ label: 'Nhóm đầy đủ', input: U.input({ name: 'fullName', value: it.fullName || '' }) }) : ''}${tab === 'sources' ? U.field({ label: 'Loại nguồn', input: U.select({ name: 'kind', value: it.kind || 'internal', options: [['internal', 'Nội bộ'], ['partner', 'Đối tác']] }) }) : ''}${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: it.status || 'active', options: [['active', 'Đang hoạt động'], ['inactive', 'Ngừng']] }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { const d = m.data(); if (!d.name) throw new Error('Nhập tên'); if (it.id) d.id = it.id; X.saveCatalogItem(col, d); m.close(); U.toast('ok', 'Đã lưu'); TH.router.refresh(); } }); };
      U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, add: () => edit(), edit: (b) => edit(St.get(col, b.dataset.id)), rm: async (b) => { if (await U.confirm({ title: 'Xóa mục này?', ok: 'Xóa', danger: true })) { try { X.removeCatalogItem(col, b.dataset.id); } catch (e) { U.toast('err', 'Không xóa được', e.message); } } }, 'add-svc': () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); }, apply: () => { TH.router.replaceQuery({ tab: 'services' }); TH.router.refresh(); } });
    } else { root.innerHTML = head + tabs + U.card({ body: U.empty({ icon: 'user', title: 'Nguồn khách – Phase 2 (CRM)', text: 'Danh mục Facebook, Tờ rơi, Đăng tin, Zalo (Q18) dùng cho Lead/CRM.', action: U.btn({ label: 'Xem scope', size: 'btn-sm', cls: 'btn-outline', act: 'p2' }) }) }); U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, p2: () => TH.go('#/coming-soon/crm') }); }
  }, { menu: 'catalog', permission: 'catalog.view', noAutoRefresh: 'timer' });

  /* ---------- Import wizard ---------- */
  const ITYPES = { tenant: { label: 'Khách thuê', icon: 'users', fields: [['name', 'Tên khách thuê', true], ['phone', 'Số điện thoại', true], ['idNumber', 'Số giấy tờ', false], ['roomCode', 'Mã phòng', false], ['start', 'Ngày vào ở', false], ['zalo', 'Số Zalo', false], ['email', 'Email', false], ['job', 'Nghề nghiệp', false]], aliases: { name: ['họ tên', 'ho ten', 'tên', 'name'], phone: ['sđt', 'sdt', 'số điện thoại', 'phone'], idNumber: ['cccd', 'cmnd', 'giấy tờ'], roomCode: ['phòng', 'phong', 'mã phòng', 'room'], start: ['ngày bắt đầu', 'ngày vào', 'start'], zalo: ['zalo'], email: ['email'], job: ['nghề', 'nghe', 'job'] }, rules: [['Không cho phép trùng SĐT trong hệ thống', 'Mỗi số điện thoại chỉ được sử dụng cho 1 khách thuê.'], ['Phòng phải tồn tại trong hệ thống', 'Mã phòng (nếu có) phải đúng với danh sách phòng hiện có.'], ['Ngày vào ở không lớn hơn ngày hiện tại', 'Ngày bắt đầu thuê phải nhỏ hơn hoặc bằng ngày hôm nay.'], ['CCCD là tùy chọn', 'Có thể để trống nhưng nếu có thì phải đúng định dạng 12 số.']], sample: [['Họ tên', 'SĐT', 'CCCD', 'Phòng', 'Ngày bắt đầu thuê', 'Zalo'], ['Nguyễn Văn An', '0901 111 222', '012345678901', 'A.01.01', '2026-10-01', 'an.nguyen93'], ['Trần Thị Bình', '0902 333 444', '012345678902', 'B.01.02', '2026-10-05', ''], ['Lê Quang Huy', '0987 654 321', '', 'C.08.02', '2026-10-10', ''], ['Phạm Thu Trang', '0904 555 666', '01234', 'A.16.08', '2026-10-12', ''], ['Hoàng Nam Khánh', '', '012345678905', 'D.03.06', '2027-01-01', ''], ['Vũ Thị Mai', '0905 777 888', '012345678906', 'Z.99.99', '2026-09-30', ''], ['Đặng Quốc Bảo', '0906 999 000', '', 'A.02.02', '2026-10-15', 'bao.dq'], ['Ngô Yến Nhi', '0907 121 212', '012345678908', 'B.02.01', '2026-10-18', ''], ['Phan Văn Long', '0908 343 434', '012345678909', 'C.01.01', '2026-10-20', ''], ['Bùi Thị Hạnh', '0909 565 656', '012345678910', 'D.01.01', '2026-10-22', '']] },
    room: { label: 'Phòng', icon: 'door', fields: [['buildingCode', 'Mã tòa', true], ['code', 'Mã phòng', true], ['floor', 'Tầng', false], ['type', 'Loại phòng', false], ['area', 'Diện tích', false], ['price', 'Giá tham chiếu', true]], aliases: { buildingCode: ['tòa', 'toa', 'mã tòa', 'building'], code: ['mã phòng', 'phòng', 'room', 'code'], floor: ['tầng', 'tang', 'floor'], type: ['loại', 'loai', 'type'], area: ['diện tích', 'dien tich', 'area'], price: ['giá', 'gia', 'price'] }, rules: [['Tòa phải tồn tại', 'Mã tòa phải khớp danh mục tòa.'], ['Mã phòng duy nhất trong tòa', 'Không trùng mã phòng hiện có (FR-BLD-03).'], ['Giá tham chiếu > 0', 'Giá bắt buộc, số nguyên VND.']], sample: [['Mã tòa', 'Mã phòng', 'Tầng', 'Loại', 'Diện tích', 'Giá'], ['TH-HBT-01', 'A.17.01', '17', 'Căn hộ Studio', '30', '6500000'], ['TH-HBT-01', 'A.17.02', '17', 'Căn hộ 1PN', '42', '8000000'], ['TH-PXL-02', 'B.13.01', '13', 'Phòng đơn', '22', '4500000'], ['TH-XXX-99', 'X.01.01', '1', 'Phòng đơn', '20', '4000000'], ['TH-HBT-01', 'A.12.03', '12', 'Studio', '30', '6500000']] },
    contract: { label: 'Hợp đồng', icon: 'file-text', fields: [['phone', 'SĐT khách', true], ['roomCode', 'Mã phòng', true], ['start', 'Ngày bắt đầu', true], ['end', 'Ngày kết thúc', true], ['price', 'Giá thuê', true], ['deposit', 'Tiền cọc', false]], aliases: { phone: ['sđt', 'sdt', 'phone'], roomCode: ['phòng', 'mã phòng', 'room'], start: ['bắt đầu', 'start'], end: ['kết thúc', 'end'], price: ['giá', 'price'], deposit: ['cọc', 'coc', 'deposit'] }, rules: [['Khách tồn tại theo SĐT', 'SĐT phải khớp khách thuê đã có.'], ['Phòng tồn tại', 'Mã phòng đúng danh mục.'], ['Hợp đồng nhập ở trạng thái Dự thảo', 'Cần kích hoạt thủ công sau khi kiểm tra (FR-CUS-02).']], sample: [['SĐT', 'Phòng', 'Bắt đầu', 'Kết thúc', 'Giá', 'Cọc'], ['0901 234 567', 'A.01.01', '2026-11-01', '2027-10-31', '6500000', '13000000']] },
    meter: { label: 'Chỉ số điện nước', icon: 'zap', fields: [['roomCode', 'Mã phòng', true], ['period', 'Kỳ (YYYY-MM)', true], ['electricPrev', 'Điện cũ', false], ['electricCurr', 'Điện mới', true], ['waterPrev', 'Nước cũ', false], ['waterCurr', 'Nước mới', true]], aliases: { roomCode: ['mã phòng', 'phòng', 'room'], period: ['kỳ', 'ky', 'period'], electricPrev: ['điện cũ', 'dien cu'], electricCurr: ['điện mới', 'dien moi'], waterPrev: ['nước cũ', 'nuoc cu'], waterCurr: ['nước mới', 'nuoc moi'] }, rules: [['Phòng tồn tại', 'Mã phòng đúng danh mục.'], ['Chỉ số mới ≥ chỉ số cũ', 'Chỉ số mới nhỏ hơn cũ cần luồng thay công tơ, không tự tính âm (FR-FIN-02).'], ['Không ghi đè chỉ số đã dùng lập hóa đơn', 'Chỉ số đã phát hành hóa đơn bị bỏ qua.']], sample: null },
    invoice: { label: 'Hóa đơn', icon: 'receipt', fields: [['roomCode', 'Mã phòng', true], ['period', 'Kỳ (YYYY-MM)', true], ['rent', 'Tiền phòng', false], ['electric', 'Tiền điện', false], ['water', 'Tiền nước', false], ['other', 'Dịch vụ khác', false], ['otherDesc', 'Mô tả dịch vụ khác', false], ['dueDate', 'Hạn thanh toán', false], ['note', 'Ghi chú', false]], aliases: { roomCode: ['mã phòng', 'ma phong', 'room'], period: ['kỳ', 'ky', 'period'], rent: ['tiền phòng', 'tien phong', 'rent'], electric: ['tiền điện', 'tien dien', 'electric'], water: ['tiền nước', 'tien nuoc', 'water'], other: ['dịch vụ khác', 'dich vu khac', 'other'], otherDesc: ['mô tả', 'mo ta', 'desc'], dueDate: ['hạn', 'han', 'due'], note: ['ghi chú', 'ghi chu', 'note'] }, rules: [['Phòng phải có hợp đồng hiệu lực', 'Hóa đơn gắn vào HĐ đang thuê của phòng; phòng trống/giữ chỗ bị bỏ qua.'], ['Không tạo trùng hóa đơn HĐ + kỳ', 'Phòng đã có hóa đơn (nháp/đã phát hành) kỳ đó sẽ bị bỏ qua.'], ['Kỳ định dạng YYYY-MM', 'Ví dụ 2026-11. Tiền phòng trống = giá HĐ; hạn trống = ngày thanh toán HĐ.'], ['Hóa đơn nhập ở trạng thái Nháp', 'Kiểm tra rồi Phát hành thủ công/hàng loạt (FR-FIN-01).']], sample: null },
    statement: { label: 'Bảng kê thu tiền', icon: 'database', p2: true, route: '#/finance/statement-import' },
    lead: { label: 'Lead (CRM)', icon: 'user', p2: true, route: '#/crm/leads', fields: [['name', 'Họ tên', true], ['phone', 'Số điện thoại', true], ['email', 'Email', false], ['source', 'Nguồn', false], ['building', 'Tòa quan tâm', false], ['budget', 'Ngân sách', false], ['note', 'Ghi chú', false]], aliases: { name: ['họ tên', 'ho ten', 'tên', 'name'], phone: ['sđt', 'sdt', 'điện thoại', 'phone'], email: ['email'], source: ['nguồn', 'nguon', 'source'], building: ['tòa', 'toa', 'building'], budget: ['ngân sách', 'ngan sach', 'budget'], note: ['ghi chú', 'note'] }, rules: [['Không trùng SĐT lead đang mở', 'Cảnh báo trùng SĐT (FR-SAL-01).'], ['Nguồn khớp danh mục', 'Tên nguồn không khớp → dùng nguồn mặc định.']], sample: null } };
  TH.router.register('/settings/import', (root, p, q) => {
    TH.router.crumb([{ label: 'Cấu hình' }, { label: 'Import dữ liệu' }]);
    const allowedTypes = TH.auth.importTypes().concat(TH.phase.on(2) && TH.auth.can('crm.manage') ? ['lead'] : []); const requestedType = q.type || allowedTypes[0]; const type = allowedTypes.includes(requestedType) ? requestedType : allowedTypes[0]; const T = ITYPES[type]; const step = Number(q.step || 1); const job = TH._import && TH._import.type === type ? TH._import : null;
    const go = (extra) => { TH.router.replaceQuery(Object.assign({ type, step }, q, extra)); TH.router.refresh(); };
    const meterSample = () => { const rooms = St.where('rooms', r => r.status === 'occupied').slice(0, 6); const per = q.period || St.state.meta.period; return [['Mã phòng', 'Kỳ', 'Điện cũ', 'Điện mới', 'Nước cũ', 'Nước mới'], ...rooms.map((r, i) => { const e = St.where('meterReadings', m => m.roomId === r.id && m.type === 'electric').sort((a, b) => F.cmp(b.period, a.period))[0]; const w = St.where('meterReadings', m => m.roomId === r.id && m.type === 'water').sort((a, b) => F.cmp(b.period, a.period))[0]; const ep = e ? e.curr : 1000, wp = w ? w.curr : 100; return [r.code, per, ep, i === 4 ? ep - 20 : ep + 150 + i * 7, wp, wp + 12 + i]; })]; };
    // Mẫu hóa đơn: HĐ hiệu lực chưa có hóa đơn kỳ (kỳ hiện tại, thiếu thì kỳ kế) + 3 dòng lỗi cố ý
    const invoiceSample = () => { const cur = q.period || St.state.meta.period; let per = cur; const free = (p) => St.where('contracts', c => c.status === 'active' && !St.one('invoices', i => i.contractId === c.id && i.period === p && i.docStatus !== 'cancelled')).sort((a, b) => F.cmp(Q.room(a.roomId).code, Q.room(b.roomId).code)); if (free(per).length < 5) per = per.slice(5) === '12' ? (Number(per.slice(0, 4)) + 1) + '-01' : per.slice(0, 4) + '-' + F.pad(Number(per.slice(5)) + 1); const cs = free(per).slice(0, 6); const has = St.one('invoices', i => i.period === cur && i.docStatus !== 'cancelled' && Q.contract(i.contractId).status === 'active');
      return [['Mã phòng', 'Kỳ', 'Tiền phòng', 'Tiền điện', 'Tiền nước', 'Dịch vụ khác', 'Mô tả dịch vụ khác', 'Hạn thanh toán', 'Ghi chú'], ...cs.map((c, i) => [Q.room(c.roomId).code, per, c.price, 350000 + i * 10000, 120000 + i * 5000, i % 2 ? 100000 : '', i % 2 ? 'Phí gửi xe' : '', per + '-05', i === 0 ? 'Nhập từ bảng kê' : '']), ['Z.99.99', per, 5000000, 300000, 100000, '', '', per + '-05', 'Phòng không tồn tại'], ...(has ? [[Q.room(has.roomId).code, cur, '', 300000, 100000, '', '', cur + '-05', 'Đã có hóa đơn kỳ này']] : []), [cs[0] ? Q.room(cs[0].roomId).code : 'A.01.01', per.slice(5) + '/' + per.slice(0, 4), '', 300000, 100000, '', '', '', 'Kỳ sai định dạng']]; };
    const sampleRows = () => T.sample || (type === 'invoice' ? invoiceSample() : type === 'lead' ? TH.imp.leadSample() : meterSample());
    const parse = (rows) => { const hdr = rows[0].map(h => F.norm(h)); const map = {}; T.fields.forEach(([k, l]) => { const idx = hdr.findIndex(h => (T.aliases[k] || []).some(a => h.includes(F.norm(a))) || h === F.norm(l)); if (idx >= 0) map[k] = idx; }); return { header: rows[0], map, data: rows.slice(1) }; };
    const validate = (parsed) => parsed.data.map((row, i) => { const d = {}; Object.entries(parsed.map).forEach(([k, idx]) => d[k] = (row[idx] || '').trim()); const issues = []; let status = 'ok';
      if (type === 'tenant') { if (!d.name) issues.push('Thiếu họ tên'); if (!d.phone) issues.push('Thiếu SĐT'); else if (St.one('tenants', t => t.phone.replace(/\s/g, '') === d.phone.replace(/\s/g, ''))) issues.push('Trùng SĐT ' + d.phone); if (d.idNumber && !/^\d{12}$/.test(d.idNumber)) issues.push('CCCD không đúng 12 số'); if (d.roomCode && !St.one('rooms', r => r.code === d.roomCode)) issues.push('Phòng ' + d.roomCode + ' không tồn tại'); if (d.start && d.start > F.today()) issues.push('Ngày vào ở sau hôm nay'); status = issues.some(x => /Thiếu|Trùng/.test(x)) ? 'error' : issues.length ? 'warn' : 'ok'; }
      if (type === 'room') { const b = St.one('buildings', x => x.code === d.buildingCode); if (!b) issues.push('Tòa ' + d.buildingCode + ' không tồn tại'); if (!d.code) issues.push('Thiếu mã phòng'); else if (b && St.one('rooms', r => r.buildingId === b.id && r.code === d.code)) issues.push('Trùng mã phòng'); if (!F.num(d.price)) issues.push('Giá không hợp lệ'); status = issues.length ? 'error' : 'ok'; }
      if (type === 'meter') { const r = St.one('rooms', x => x.code === d.roomCode); if (!r) issues.push('Phòng không tồn tại'); if (!/^\d{4}-\d{2}$/.test(d.period)) issues.push('Kỳ sai định dạng'); if (F.num(d.electricCurr) < F.num(d.electricPrev)) issues.push('Điện mới < điện cũ'); if (F.num(d.waterCurr) < F.num(d.waterPrev)) issues.push('Nước mới < nước cũ'); if (r && St.one('meterReadings', m => m.roomId === r.id && m.period === d.period && m.status === 'used')) issues.push('Đã lập hóa đơn kỳ này'); status = issues.some(x => /không tồn tại|sai định dạng|Đã lập/.test(x)) ? 'error' : issues.length ? 'warn' : 'ok'; if (status === 'warn') status = 'error'; }
      if (type === 'invoice') { const r = St.one('rooms', x => x.code === d.roomCode); const c = r ? Q.activeContractOfRoom(r.id) : null; if (!r) issues.push('Phòng ' + d.roomCode + ' không tồn tại'); else if (!c) issues.push('Phòng chưa có HĐ hiệu lực'); if (!/^\d{4}-\d{2}$/.test(d.period)) issues.push('Kỳ sai định dạng (YYYY-MM)'); else if (c && St.one('invoices', i => i.contractId === c.id && i.period === d.period && i.docStatus !== 'cancelled')) issues.push('Đã có hóa đơn kỳ này'); ['rent', 'electric', 'water', 'other'].forEach(k => { if (d[k] && isNaN(Number(String(d[k]).replace(/[.,\s]/g, '')))) issues.push('Số tiền không hợp lệ: ' + d[k]); }); if (d.dueDate && !/^\d{4}-\d{2}-\d{2}$/.test(d.dueDate)) issues.push('Hạn thanh toán sai định dạng (YYYY-MM-DD)'); if (c && (F.num(d.rent) || c.price) + F.num(d.electric) + F.num(d.water) + F.num(d.other) <= 0) issues.push('Tổng hóa đơn phải > 0'); status = issues.length ? 'error' : 'ok'; }
      if (type === 'lead') { if (!d.name) issues.push('Thiếu họ tên'); if (!d.phone) issues.push('Thiếu SĐT'); else if (St.one('leads', l => l.phone.replace(/\s/g, '') === d.phone.replace(/\s/g, ''))) issues.push('Trùng SĐT lead'); status = issues.length ? 'error' : 'ok'; }
      if (type === 'contract') { if (!St.one('tenants', t => t.phone.replace(/\s/g, '') === (d.phone || '').replace(/\s/g, ''))) issues.push('Không tìm thấy khách'); if (!St.one('rooms', x => x.code === d.roomCode)) issues.push('Phòng không tồn tại'); if (!d.start || !d.end || d.end <= d.start) issues.push('Ngày không hợp lệ'); status = issues.length ? 'error' : 'ok'; }
      return { i: i + 1, data: d, issues, status }; });
    const tiles = `<div class="obj-tiles">${Object.entries(ITYPES).filter(([k, v]) => allowedTypes.includes(k) || (v.p2 && (k !== 'lead' || TH.phase.on(2)))).map(([k, v]) => `<div class="obj-tile ${k === type ? 'on' : ''}" data-act="type" data-k="${k}">${I(v.icon)} ${v.label}${v.p2 ? TH.phase.tag(2) : ''}</div>`).join('')}</div>`;
    const steps = U.wizard([{ title: 'Tải file', sub: 'Tải lên file dữ liệu' }, { title: 'Mapping cột', sub: 'Ánh xạ với trường hệ thống' }, { title: 'Kiểm tra dữ liệu', sub: 'Kiểm tra và xử lý lỗi' }, { title: 'Preview & xác nhận', sub: 'Xem trước và hoàn tất' }], step - 1);
    let main = '', side = '';
    if (T.p2 && type !== 'lead') { main = U.card({ body: U.empty({ icon: 'database', title: 'Import bảng kê thu tiền – Phase 2', text: 'Mapping, auto-match hóa đơn, review, Data Jobs, retry dòng lỗi (§3.4).', action: U.btn({ label: 'Xem scope', size: 'btn-sm', cls: 'btn-outline', act: 'p2' }) }) }); }
    else if (step === 1 || !job) main = U.card({ title: 'Bước 1 – Tải file', icon: 'upload', sub: 'Chấp nhận CSV (UTF-8). File .xlsx: xuất sang CSV trước (bản demo offline không kèm thư viện đọc Excel).', body: `${U.dropzone({ name: 'imp', hint: 'CSV, tối đa 5MB', multiple: false, accept: '.csv,.txt,.xlsx,.xls' })}<div class="row mt12 gap12">${U.btn({ label: 'Dùng file mẫu (' + (sampleRows().length - 1) + ' dòng, có lỗi cố ý)', icon: 'file-check', cls: 'btn-outline', act: 'use-sample', attrs: { 'data-guide': 'import-sample' } })}${U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-ghost', act: 'dl-sample' })}</div>` });
    else if (step === 2) main = U.card({ title: 'Bước 2 – Mapping cột', icon: 'arrow-left-right', sub: job.fileName + ' · ' + job.parsed.data.length + ' dòng · ' + job.parsed.header.length + ' cột', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Cột file</th><th>Ví dụ dữ liệu</th><th>Trường hệ thống</th><th>Bắt buộc</th></tr></thead><tbody>${job.parsed.header.map((h, idx) => { const k = Object.entries(job.parsed.map).find(([kk, v]) => v === idx); return `<tr><td><b>${esc(h)}</b></td><td class="muted">${esc((job.parsed.data[0] || [])[idx] || '')}</td><td>${U.select({ name: 'm_' + idx, value: k ? k[0] : '', all: '— Bỏ qua —', options: T.fields.map(f => [f[0], f[1]]), cls: 'sm', attrs: { 'data-on': 'map' } })}</td><td>${k && T.fields.find(f => f[0] === k[0])[2] ? U.chip('Có', 'red') : U.chip('Không', 'gray')}</td></tr>`; }).join('')}</tbody></table>` }) + `<div class="wz-foot">${U.btn({ label: '← Tải file khác', cls: 'btn-ghost', act: 'to1' })}${U.btn({ label: 'Tiếp tục kiểm tra →', cls: 'btn-primary', act: 'to3', disabled: T.fields.some(f => f[2] && !(f[0] in job.parsed.map)) })}</div>${T.fields.some(f => f[2] && !(f[0] in job.parsed.map)) ? U.note('warn', 'Thiếu trường bắt buộc', T.fields.filter(f => f[2] && !(f[0] in job.parsed.map)).map(f => f[1]).join(', ')) : ''}`;
    else if (step >= 3) { const res = job.rows; const ok = res.filter(r => r.status === 'ok').length, warn = res.filter(r => r.status === 'warn').length, err = res.filter(r => r.status === 'error').length;
      main = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng dòng', value: res.length, cap: 'Tổng số dòng trong file', icon: 'list', tone: 'blue' })}${U.kpi({ label: 'Hợp lệ', value: ok, cap: 'Dữ liệu hợp lệ', icon: 'check-circle', tone: 'green', delta: F.pct(ok, res.length) })}${U.kpi({ label: 'Cần kiểm tra', value: warn, cap: 'Cần kiểm tra, bổ sung', icon: 'alert-triangle', tone: 'amber', delta: F.pct(warn, res.length), deltaDir: 'down' })}${U.kpi({ label: 'Lỗi', value: err, cap: 'Dòng không thể import', icon: 'x-circle', tone: 'red', delta: F.pct(err, res.length), deltaDir: 'down' })}</div>
      ${step === 3 ? U.card({ title: 'Bảng mapping & kiểm tra dữ liệu', icon: 'clipboard-check', sub: 'Kiểm tra kết quả mapping và tình trạng dữ liệu của từng cột.', actions: U.btn({ label: 'Chỉnh sửa mapping', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'to2' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Cột file</th><th>Ví dụ dữ liệu</th><th>Trường hệ thống</th><th>Bắt buộc</th><th>Trạng thái</th></tr></thead><tbody>${Object.entries(job.parsed.map).map(([k, idx]) => { const fdef = T.fields.find(f => f[0] === k); const bad = res.filter(r => r.issues.some(x => F.norm(x).includes(F.norm(fdef[1].split(' ')[0])) || (k === 'phone' && /SĐT/.test(x)) || (k === 'roomCode' && /Phòng/.test(x)) || (k === 'idNumber' && /CCCD/.test(x)) || (k === 'start' && /Ngày/.test(x)) || (k === 'period' && /Kỳ/.test(x)) || (k === 'dueDate' && /Hạn/.test(x)) || (['rent', 'electric', 'water', 'other'].includes(k) && /Số tiền|Tổng/.test(x)))).length; return `<tr><td><b>${esc(job.parsed.header[idx])}</b></td><td class="muted">${esc((job.parsed.data[0] || [])[idx] || '')}</td><td>${esc(fdef[1])}</td><td>${fdef[2] ? U.chip('Có', 'red') : U.chip('Không', 'gray')}</td><td>${bad ? U.chip('⚠ ' + bad + ' dòng cần kiểm tra', 'amber') : U.chip('✔ Hợp lệ', 'green')}</td></tr>`; }).join('')}</tbody></table>` }) : ''}
      <div class="mt16">${U.card({ title: step === 3 ? 'Preview 5 dòng đầu' : 'Toàn bộ dữ liệu sau kiểm tra', sub: step === 3 ? 'Xem trước một số dòng dữ liệu sau khi mapping.' : 'Dòng lỗi sẽ bị bỏ qua khi import', bodyCls: 'tight', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>STT</th>${T.fields.filter(f => f[0] in job.parsed.map).map(f => `<th>${f[1]}</th>`).join('')}<th>Trạng thái import</th></tr></thead><tbody>${(step === 3 ? res.slice(0, 5) : res).map(r => `<tr class="${r.status === 'error' ? 'tint-red' : r.status === 'warn' ? 'tint-amber' : ''}"><td>${r.i}</td>${T.fields.filter(f => f[0] in job.parsed.map).map(f => `<td>${esc(r.data[f[0]] || '')}</td>`).join('')}<td>${U.chip(r.status === 'ok' ? '✔ Hợp lệ' : r.status === 'warn' ? '⚠ Cần kiểm tra' : '✕ Lỗi dữ liệu', r.status === 'ok' ? 'green' : r.status === 'warn' ? 'amber' : 'red')}${r.issues.length ? `<div class="xs muted">${esc(r.issues.join('; '))}</div>` : ''}</td></tr>`).join('')}</tbody></table></div>` })}</div>
      <div class="wz-foot">${U.btn({ label: step === 3 ? '← Sửa mapping' : '← Quay lại kiểm tra', cls: 'btn-ghost', act: step === 3 ? 'to2' : 'to3' })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${step === 3 ? U.btn({ label: 'Tiếp tục review →', cls: 'btn-primary', act: 'to4' }) : U.btn({ label: 'Xác nhận import ' + (ok + warn) + ' dòng', icon: 'check', cls: 'btn-primary', act: 'commit', disabled: !(ok + warn), attrs: { 'data-guide': 'import-commit' } })}</div></div>`;
      side = `<aside class="side-stack">${U.card({ title: 'Quy tắc kiểm tra', icon: 'shield-check', body: `<div class="steps">${T.rules.map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` })}${U.card({ title: 'Kết quả dự kiến', icon: 'check-circle', body: `<div class="check-list">${[[I('check-circle', 'green'), 'Có thể tạo mới <b>' + ok + '</b> ' + T.label.toLowerCase(), U.chip(F.pct(ok, res.length) + '%', 'green')], [I('alert-triangle', 'amber'), 'Cần kiểm tra <b>' + warn + '</b> dòng (vẫn import, có cảnh báo)', U.chip(F.pct(warn, res.length) + '%', 'amber')], [I('x-circle', 'red'), 'Bỏ qua <b>' + err + '</b> dòng lỗi', U.chip(F.pct(err, res.length) + '%', 'red')]].map(([ic, t, c]) => `<div class="it">${ic}<span class="grow">${t}</span>${c}</div>`).join('')}</div>` })}</aside>`; }
    if (step === 1 && (!T.p2 || type === 'lead')) side = `<aside class="side-stack">${U.card({ title: 'Quy tắc kiểm tra', icon: 'shield-check', body: `<div class="steps">${T.rules.map(([t, s], i) => `<div class="st"><div class="n">${i + 1}</div><div><b>${t}</b><small>${s}</small></div></div>`).join('')}</div>` })}${U.card({ title: 'Lịch sử import', icon: 'history', bodyCls: 'tight', body: `<table class="tbl compact">${St.where('importJobs', j => j.type === type).slice(-5).reverse().map(j => `<tr><td>${esc(j.fileName)}</td><td class="num">${j.rows} dòng</td><td>${U.chip('Tạo ' + (j.created ?? j.valid), 'green')}</td><td class="xs muted">${F.datetime(j.createdAt)}</td></tr>`).join('') || '<tr><td class="muted tc">Chưa có</td></tr>'}</table>` })}</aside>`;
    root.innerHTML = `${U.pageHead({ title: 'Import dữ liệu', sub: 'Nhập dữ liệu từ file Excel/CSV để tạo mới hoặc cập nhật thông tin trong hệ thống.', acts: [U.btn({ label: 'Tải file mẫu', icon: 'download', cls: 'btn-outline', act: 'dl-sample' })] })}${U.card({ title: 'Đối tượng import', sub: 'Chọn loại dữ liệu bạn muốn import', cls: 'mb16', body: tiles })}${T.p2 && type !== 'lead' ? '' : steps}<div class="two-col">${main}${side}</div>`;
    U.bindDropzones(root, (files) => { const f = files[0]; if (!f) return; if (/\.xlsx?$/i.test(f.name)) { U.toast('warn', 'File Excel', 'Bản demo offline chỉ đọc CSV – hãy "Lưu dưới dạng CSV" rồi tải lại, hoặc dùng file mẫu.'); return; } const rd = new FileReader(); rd.onload = () => { const rows = F.parseCSV(rd.result); if (rows.length < 2) return U.toast('err', 'File rỗng'); const parsed = parse(rows); TH._import = { type, fileName: f.name, parsed, rows: validate(parsed), checksum: F.hash(rd.result) }; go({ step: 2 }); }; rd.readAsText(f, 'utf-8'); });
    U.onChange(root, { map: () => { const m = {}; root.querySelectorAll('select[name^=m_]').forEach(s => { if (s.value) m[s.value] = Number(s.name.slice(2)); }); job.parsed.map = m; job.rows = validate(job.parsed); go({ step: 2 }); } });
    U.bind(root, {
      type: (el) => { const tt = ITYPES[el.dataset.k]; if (tt && tt.p2 && el.dataset.k !== 'lead') { if (TH.phase.on(2) && tt.route) return TH.go(tt.route); return TH.go('#/coming-soon/statement'); } if (!allowedTypes.includes(el.dataset.k)) return U.toast('err', 'Không có quyền import loại dữ liệu này'); TH._import = null; TH.router.replaceQuery({ type: el.dataset.k, step: 1, period: q.period || '', back: q.back || '' }); TH.router.refresh(); }, p2: () => TH.go('#/coming-soon/statement'),
      to1: () => go({ step: 1 }), to2: () => go({ step: 2 }), to3: () => { job.rows = validate(job.parsed); go({ step: 3 }); }, to4: () => go({ step: 4 }),
      'dl-sample': () => { F.download('mau-import-' + type + '.csv', F.csv(sampleRows().slice(1), sampleRows()[0]), 'text/csv'); U.toast('ok', 'Đã tải file mẫu ' + T.label); },
      'use-sample': () => { const rows = sampleRows().map(r => r.map(String)); const parsed = parse(rows); TH._import = { type, fileName: 'mau-import-' + type + '.csv', parsed, rows: validate(parsed), checksum: F.hash(JSON.stringify(rows) + type) }; go({ step: 2 }); },
      draft: () => U.toast('ok', 'Đã lưu nháp phiên import', 'Tiếp tục khi quay lại trang'),
      commit: async () => { const okN = job.rows.filter(r => r.status !== 'error').length; if (await U.confirm({ title: 'Xác nhận import ' + okN + ' dòng ' + T.label.toLowerCase() + '?', text: 'Dòng lỗi bị bỏ qua. Import idempotent theo checksum file – chạy lại không tạo trùng.', ok: 'Import' })) { try { const r = type === 'lead' ? X.importLeads({ rows: job.rows, fileName: job.fileName, checksum: job.checksum }) : X.runImport({ type, fileName: job.fileName, rows: job.rows, checksum: job.checksum }); if (r.duplicate) U.toast('warn', 'File này đã import trước đó', 'Không tạo bản ghi trùng'); else { const tst = U.toast('ok', 'Import xong: tạo ' + r.created + ', bỏ qua ' + r.skipped, TH.phase.on(2) && r.code ? 'Tác vụ ' + r.code + ' – bấm để xem Data Job' : '', 6000); if (TH.phase.on(2) && r.id) { tst.style.cursor = 'pointer'; tst.onclick = () => TH.go('#/settings/jobs/' + r.id); } } TH._import = null; if (type === 'lead') return TH.go('#/crm/leads?view=table'); if (q.back) TH.go(decodeURIComponent(q.back)); else TH.go(type === 'tenant' ? '#/tenants' : type === 'room' ? '#/rooms' : type === 'contract' ? '#/contracts?status=draft' : type === 'invoice' ? '#/invoices?tab=draft&period=all' : '#/invoices/batch?step=2'); } catch (e) { U.toast('err', 'Import thất bại', e.message); } } },
    });
  }, { menu: 'import', permission: 'import.view', noAutoRefresh: true });
})(window.TH);
