/* UI-31 Cổ đông & tỷ lệ góp theo tòa (E24 tổng tỷ lệ ≠ 100% chặn khóa) · UI-32 Bảng kê chia lãi theo tòa (G1 – SRC-07).
   Chỉ admin / kế toán. Tổng nhận M là số phải chia, không phải khoản chi (chi thực cho cổ đông ở UI-33 – Phase 3). */
(function (TH) {
  const S = TH.store, F = TH.f, U = TH.ui, K = TH.kit, Q = TH.q, X = TH.actions, esc = F.esc;
  const pct = (v) => String(Math.round(v * 100) / 100).replace('.', ',') + '%';
  const dec = (v, d = 2) => v == null ? '–' : Number(v).toLocaleString('vi-VN', { maximumFractionDigits: d });
  TH.router.handle('/shares', (root, p, q) => {
    if (TH.auth.role() === 'codong') {
      const sh = Q.shareholder(TH.auth.shareholderId()), rows = Q.scopedBuildings().map(b => ({ b, pct: Q.shareRatios(b.id).filter(r => r.shareholderId === sh.id).reduce((s, r) => s + r.pct, 0) }));
      root.innerHTML = U.pageHead({ title: 'Cổ phần của tôi', sub: sh.code + ' · ' + sh.name }) + (rows.length ? TH.pages.shareNav(rows[0].b.id, '/shares') : '') + U.card({ title: 'Tòa có tỷ lệ góp hiệu lực', body: `<table class="tbl compact"><thead><tr><th>Tòa</th><th>Tỷ lệ của tôi</th><th></th></tr></thead><tbody>${rows.map(r => `<tr><td>${esc(r.b.code)}</td><td>${r.pct}%</td><td><a href="#/shares/${r.b.id}">Bảng kê chia</a> · <a href="#/shares/capital?building=${r.b.id}">Góp vốn / chi thực</a></td></tr>`).join('')}</tbody></table>` }); return;
    }
    const blds = Q.shareBuildings();
    const bid = q.building || (blds[0] || {}).id;
    const date = q.date || F.today();
    const ratios = bid ? Q.shareRatios(bid, date) : [];
    const v = TH.calc.share.valid(ratios);
    const shx = q.sh && Q.shareholder(q.sh) ? { sh: Q.shareholder(q.sh), rows: S.all('buildings').map(bb => ({ b: bb, r: Q.shareRatios(bb.id, date).find(x => x.shareholderId === q.sh) })).filter(x => x.r) } : null;
    const hist = bid ? S.where('shareRatios', r => r.buildingId === bid).sort((a, b) => String(b.from).localeCompare(String(a.from))) : [];
    const shareHistory = bid ? [
      ...hist.map(r => ({ at: r.from, title: `Tỷ lệ ${(Q.shareholder(r.shareholderId) || {}).name || ''}: ${pct(r.pct)}`, sub: r.reason || 'Phiên tỷ lệ lịch sử', color: 'blue' })),
      ...S.where('shareRuns', r => r.buildingId === bid).map(r => ({ at: r.lockedAt || (r.period + '-28'), title: `Khóa bảng kê ${F.periodShort(r.period)} · phiên ${r.version || 1}`, sub: `${r.lockedBy || 'Hệ thống'} · ${r.status === 'superseded' ? 'đã được thay thế' : r.status}`, color: 'purple' })),
      ...S.where('shareTxns', t => t.buildingId === bid).map(t => ({ at: t.date, title: `${t.kind === 'payout' ? 'Chi thực' : t.kind === 'withdraw' ? 'Rút vốn' : 'Góp vốn'} · ${t.code}`, sub: `${(Q.shareholder(t.shareholderId) || {}).name || ''} · ${F.vnd(t.amount)} · ${t.status === 'void' ? 'đã hủy' : t.by || ''}`, color: t.status === 'void' ? 'red' : 'green' }))
    ].sort((a, b) => String(b.at).localeCompare(String(a.at))) : [];
    root.innerHTML = U.pageHead({ title: 'Cổ đông & tỷ lệ góp', sub: 'Nhà đầu tư – tòa nhiều-nhiều; tỷ lệ nhập tay có ngày hiệu lực (CH-30); tổng tỷ lệ tòa phải đủ 100% trước khi khóa bảng kê chia', acts: [U.btn({ label: 'Thêm cổ đông', icon: 'user-plus', act: 'addsh', perm: 'shares.manage' }), U.btn({ label: 'Sửa tỷ lệ', icon: 'percent', cls: 'btn-primary', act: 'ratio', perm: 'shares.manage' })] })
      + K.filters([{ name: 'building', label: 'Tòa', options: [...blds.map(b => [b.id, b.code]), ...S.all('buildings').filter(b => !blds.includes(b)).map(b => [b.id, b.code + ' (chưa có tỷ lệ)'])], value: bid, all: false }, { name: 'date', label: 'Tại ngày', type: 'date', value: F.today() }, { name: 'sh', label: 'Xem theo cổ đông', options: S.all('shareholders').map(x => [x.id, x.code + ' · ' + x.name]) }], q)
      + `<div class="grid grid-3 mt16">${U.kpi({ label: 'Số cổ đông của tòa', value: ratios.length, cap: blds.length + ' tòa đã có tỷ lệ', icon: 'users', tone: 'blue' })}${U.kpi({ label: 'Tổng tỷ lệ', value: pct(v.sum), cap: v.ok ? 'đủ 100% – khóa được bảng kê' : 'chưa đủ 100% – không khóa được (E24)', icon: 'percent', tone: v.ok ? 'green' : 'red' })}
        ${U.kpi({ label: 'Bảng kê đã khóa', value: S.where('shareRuns', r => r.buildingId === bid).length, cap: bid ? `<a href="#/shares/${bid}">Mở bảng kê chia</a>` : '', icon: 'lock', tone: 'purple' })}</div>`
      + (!v.ok && ratios.length ? U.note('danger', `Tổng tỷ lệ tòa ${esc((Q.building(bid) || {}).code)} = ${pct(v.sum)}`, 'Phải đủ 100% mới khóa được bảng kê chia (E24). Sửa tỷ lệ với ngày hiệu lực mới.') : '')
      + (shx ? '<div class="mt16">' + U.card({ title: 'Tòa tham gia – ' + esc(shx.sh.code + ' · ' + shx.sh.name), sub: 'Liên hệ: ' + esc(shx.sh.phone || '–') + ' · Tài khoản nhận: ' + esc(shx.sh.bank || '–') + ' (chỉ admin / kế toán)' + ((shx.sh.history || []).length ? ' · đã sửa ' + shx.sh.history.length + ' lần' : ''), bodyCls: 'flush',
          actions: U.btn({ label: 'Sửa thông tin', icon: 'pencil', size: 'btn-xs', act: 'editsh', perm: 'shares.manage' }) + ' ' + (TH.auth.can('documents.upload') ? U.btn({ label: 'Tải chứng từ góp vốn', icon: 'upload', size: 'btn-xs', act: 'capdoc', perm: 'shares.manage' }) : ''),
          body: shx.rows.length ? `<table class="tbl compact"><thead><tr><th>Tòa</th><th class="num">Tỷ lệ</th><th>Hiệu lực từ</th><th></th></tr></thead><tbody>${shx.rows.map(x => `<tr><td><b>${esc(x.b.code)}</b></td><td class="num">${pct(x.r.pct)}</td><td>${F.date(x.r.from)}</td><td><a href="#/shares/${x.b.id}">Bảng kê chia</a></td></tr>`).join('')}</tbody></table>` : U.empty({ title: 'Không tham gia tòa nào tại ngày này' }) })
        + '<div class="mt12">' + U.card({ title: 'Chứng từ góp vốn', icon: 'file-text', body: TH.pages.docDownloadList(Q.documentsScoped().filter(d => d.objectType === 'shareholder' && d.objectId === shx.sh.id && d.status === 'current')) }) + '</div></div>' : '')
      + `<div class="grid grid-2 mt16"><div>${K.tableCard('t', 'Tỷ lệ góp hiệu lực ' + F.date(date))}</div><div>${K.tableCard('h', 'Lịch sử tỷ lệ')}</div></div>`;
    if (TH.ms.on('3') && bid) root.insertAdjacentHTML('afterbegin', TH.pages.shareNav(bid, '/shares'));
    if (bid) root.insertAdjacentHTML('beforeend', '<div class="mt16">' + U.card({ title: 'Lịch sử tổng hợp cổ đông', icon: 'history', sub: 'Tỷ lệ · khóa/lại bảng kê · góp/rút vốn · chi thực · hủy giao dịch', body: shareHistory.length ? U.timeline(shareHistory.slice(0, 80).map(x => ({ when: F.datetime(x.at), title: esc(x.title), sub: esc(x.sub), color: x.color }))) : U.empty({ title: 'Chưa có lịch sử cho tòa này' }) }) + '</div>');
    K.bindFilters(root);
    U.table(root.querySelector('#t'), { rows: ratios, noPager: true, empty: U.empty({ icon: 'percent', title: 'Tòa chưa có tỷ lệ góp', text: 'Bấm "Sửa tỷ lệ" để nhập.' }), cols: [
      { key: 'c', label: 'Mã', render: r => esc((Q.shareholder(r.shareholderId) || {}).code) }, { key: 'n', label: 'Nhà đầu tư', render: r => { const sh = Q.shareholder(r.shareholderId) || {}; return esc(sh.name) + (sh.common ? ' ' + U.chip('nhận chênh làm tròn', 'blue') : ''); } },
      { key: 'p', label: 'Tỷ lệ', num: true, render: r => `<b>${pct(r.pct)}</b>` }, { key: 'f', label: 'Hiệu lực từ', render: r => F.date(r.from) }, { key: 'a', label: '', render: r => U.link('#/shares?building=' + bid + '&sh=' + r.shareholderId, 'Hồ sơ') }],
      footer: () => `<tr><td></td><td><b>Tổng</b></td><td class="num"><b class="${v.ok ? 'green' : 'red'}">${pct(v.sum)}</b></td><td></td><td></td></tr>` });
    U.table(root.querySelector('#h'), { rows: hist, pageSize: 12, cols: [{ key: 'n', label: 'Cổ đông', render: r => esc((Q.shareholder(r.shareholderId) || {}).name) }, { key: 'p', label: 'Tỷ lệ', num: true, render: r => pct(r.pct) }, { key: 'f', label: 'Từ', render: r => F.date(r.from) }, { key: 't', label: 'Đến', render: r => r.to ? F.date(r.to) : 'hiện tại' }, { key: 'r', label: 'Căn cứ', render: r => `<span class="small muted">${esc(r.reason || '')}</span>` }] });
    U.bind(root, { docdl: (el) => TH.pages.docDownload(el.dataset.id),
      editsh: () => K.formDrawer({ title: 'Sửa cổ đông – ' + esc(shx.sh.code), modal: true, note: U.note('info', '', 'Lưu lịch sử thay đổi. Tỷ lệ góp sửa riêng ở "Sửa tỷ lệ" (có ngày hiệu lực).'), fields: [{ name: 'name', label: 'Tên', req: true, value: shx.sh.name }, { name: 'phone', label: 'Liên hệ', value: shx.sh.phone || '' }, { name: 'bank', label: 'Tài khoản nhận', value: shx.sh.bank || '' }, { name: 'note', label: 'Ghi chú', span: true, value: shx.sh.note || '' }],
        submit: 'Lưu', onSubmit: (x) => { X.updateShareholder(shx.sh.id, x); U.toast('ok', 'Đã cập nhật cổ đông'); } }),
      capdoc: () => K.formDrawer({ title: 'Chứng từ góp vốn – ' + esc(shx.sh.code), modal: true, fields: [{ name: 'buildingId', label: 'Tòa góp vốn', type: 'select', req: true, options: shx.rows.map(x => [x.b.id, x.b.code]), value: bid }, TH.pages.documentFileField, { name: 'name', label: 'Tên hiển thị (để trống dùng tên file)' }, { name: 'note', label: 'Nội dung (số tiền, ngày góp…)', span: true }],
        submit: 'Tải lên', onSubmit: async (x,drawer) => { await TH.pages.storeDocumentFile({ type: 'capital', buildingId: x.buildingId, objectType: 'shareholder', objectId: shx.sh.id, name: x.name, note: x.note },drawer,x.buildingId); U.toast('ok', 'Đã tải chứng từ góp vốn'); } }),
      addsh: () => K.formDrawer({ title: 'Thêm cổ đông / nhà đầu tư', modal: true, fields: [{ name: 'name', label: 'Tên', req: true }, { name: 'phone', label: 'Liên hệ' }, { name: 'bank', label: 'Tài khoản nhận' }, { name: 'note', label: 'Ghi chú', span: true }], submit: 'Lưu', onSubmit: (x) => { X.addShareholder(x); U.toast('ok', 'Đã thêm cổ đông'); } }),
      ratio: () => {
        const cur = {}; ratios.forEach(r => { cur[r.shareholderId] = r.pct; });
        K.formDrawer({ title: 'Tỷ lệ góp – tòa ' + esc((Q.building(bid) || {}).code), wide: true, note: U.note('info', '', 'Nhập % cho từng cổ đông (để trống = không góp). Lưu được khi chưa đủ 100% nhưng không khóa được bảng kê.'),
          fields: [...S.all('shareholders').map(sh => ({ name: 'p_' + sh.id, label: sh.code + ' · ' + sh.name, type: 'number', value: cur[sh.id] || '' })), { name: 'from', label: 'Hiệu lực từ', type: 'date', value: F.today(), req: true }, { name: 'reason', label: 'Căn cứ / lý do', req: true, span: true }],
          submit: 'Lưu tỷ lệ', onSubmit: (x) => { const rows = S.all('shareholders').map(sh => ({ shareholderId: sh.id, pct: F.num(x['p_' + sh.id]) })); const r = X.setShareRatios(bid, rows, x.from, x.reason); U.toast(r.ok ? 'ok' : 'warn', 'Đã lưu tỷ lệ', 'Tổng ' + pct(r.sum) + (r.ok ? '' : ' – chưa đủ 100%')); } });
      },
    });
  });

  TH.router.handle('/shares/:id', (root, p, q) => {
    const b = Q.building(p.id); if (!b || !TH.auth.inScope(b.id)) { root.innerHTML = U.card({ body: U.empty({ title: 'Không tìm thấy tòa trong phạm vi được xem' }) }); return; } // Phase 3: cổ đông chỉ xem tòa mình góp vốn
    const period = q.period || '2026-08'; const source = TH.auth.role() !== 'codong' && q.source === 'excel' ? 'excel' : 'web';
    TH.layout.crumb([{ label: 'Cổ đông', href: '#/shares?building=' + b.id }, { label: 'Bảng kê chia ' + b.code }]);
    const run = Q.shareRun(b.id, period, source); const vari = TH.auth.role() === 'codong' || run && run.locked ? null : Q.shareVariance(b.id, period);
    const relock = run && run.locked && Q.shareRelockable(b.id, period);
    const excelAvail = TH.auth.role() !== 'codong' && !!Q.shareBase(b.id, period, 'excel');
    const drill = '#/reports/buildings?period=' + period + '&group=' + b.group + '&building=' + b.id; // C22 / C73 / C74 → báo cáo tòa UI-28
    root.innerHTML = TH.pages.shareNav(b.id, '/shares/' + b.id) + U.pageHead({ title: 'Bảng kê chia lãi – tòa ' + esc(b.code), back: '#/shares?building=' + b.id, sub: 'Cơ sở là Báo cáo tổng của tòa; kỳ lịch sử giữ số Excel, kỳ web hiển thị riêng chênh làm tròn (OQ-08)',
      acts: [U.btn({ label: 'Xuất Excel', icon: 'download', act: 'exp' }), run && source === 'web' && (!run.locked ? Q.shareLockable(period) : relock) ? U.btn({ label: run.locked ? 'Khóa phiên mới' : 'Khóa bảng kê', icon: 'lock', cls: 'btn-primary', act: 'lock', perm: 'shares.lock' }) : ''] })
      + K.filters([{ name: 'period', label: 'Kỳ', options: S.all('periods').map(x => [x.id, F.periodLabel(x.id)]), value: '2026-08', all: false }, { name: 'source', label: 'Nguồn số', options: [['web', 'Báo cáo tổng tòa (web)'], ...(excelAvail ? [['excel', 'Như Excel SRC-07 (đối chiếu)']] : [])], value: 'web', all: false }], q)
      + (!run ? U.card({ body: U.empty({ title: 'Chưa có số báo cáo tòa kỳ này' }) }) : `<div class="mt16"></div>`
        + (relock ? U.note('warn', 'Kỳ báo cáo đã mở lại sau lần khóa bảng kê phiên ' + (run.version || 1), 'Bảng kê đang hiện là ảnh chụp cũ – khóa phiên mới sau khi kỳ được khóa lại để lấy số báo cáo mới.') : '')
        + (!run.locked && source === 'web' && !Q.shareLockable(period) ? U.note('info', 'Kỳ ' + F.periodShort(period) + ' chưa khóa số báo cáo', 'Đây là số tính thử; khóa kỳ ở UI-38 rồi mới khóa bảng kê.') : '')
        + (run.locked ? U.note('ok', 'Đã khóa ' + F.datetime(run.lockedAt) + ' – ' + esc(run.lockedBy) + (run.version > 1 ? ' (phiên ' + run.version + ')' : ''), 'Ảnh chụp số tại thời điểm khóa; sửa tỷ lệ sau đó không làm đổi bảng kê này.') : !run.valid.ok ? U.note('danger', 'Tổng tỷ lệ = ' + pct(run.valid.sum), 'Không khóa được bảng kê (E24) – sửa tỷ lệ ở UI-31.') : U.note('info', 'Tính thử', 'Bảng kê chưa khóa – số theo tỷ lệ hiệu lực cuối kỳ ' + F.date(TH.calc.dates.periodEnd(period)) + '.'))
        + (run.roundingMode === 'explicitDelta' && run.rounding && (run.rounding.H || run.rounding.I || run.rounding.J) ? U.note('warn', 'Chênh làm tròn chưa xử lý', `H ${run.rounding.H} · I ${run.rounding.I} · J ${run.rounding.J}. Không tự dồn vào CHUNG; không khóa cho đến khi OQ-08 được xác nhận.`) : '')
        + `<div class="grid grid-4 mb16">${U.kpi({ label: 'Vốn (tiền thuê 1 tháng – dòng 20)', value: U.link(drill, F.vnd(run.base.rent)), icon: 'building', tone: 'blue' })}${U.kpi({ label: 'LN gộp (dòng 45)', value: U.link(drill, dec(run.base.lng)), icon: 'trending-up', tone: 'green' })}
          ${U.kpi({ label: 'LN ròng (dòng 46)', value: U.link(drill, dec(run.base.lnr)), cap: run.base.src ? esc(run.base.src) : '', icon: 'wallet', tone: 'purple' })}${U.kpi({ label: 'Σ Tổng nhận (M = H + J)', value: F.vnd(run.totals.M), cap: 'LNR/GV ' + dec(run.K) + ' · CP/LNG ' + dec(run.L, 4), icon: 'hand-coins', tone: 'amber' })}</div>`
        + K.tableCard('t', 'Bảng kê chia – ' + F.periodLabel(period) + (source === 'excel' ? ' (như Excel)' : ''))
        + (vari && source === 'web' ? U.note('warn', 'Chênh so với bảng kê Excel SRC-07 (K-9)', `Vốn ${F.vnd(vari.rent)} · LNG ${dec(vari.lng)} · LNR <b>${dec(vari.lnr)}</b>đ. Ô C43 của file G1 dùng mẫu số 1.343 thay vì 1.382 cho lương sửa chữa (GĐ OQ-04): 25.000.000 × 15 / 1.343 − 25.000.000 × 15 / 1.382 = ${dec(vari.oq04)}đ; phần còn lại ${dec(vari.lnr - vari.oq04)}đ là sai số làm tròn của các ô liên kết ngoài.`) : ''));
    K.bindFilters(root);
    if (run) U.table(root.querySelector('#t'), { rows: run.rows, noPager: true, cols: [{ key: 'n', label: 'Cổ đông', render: r => { const sh = Q.shareholder(r.id) || {}; return esc(sh.code + ' · ' + sh.name) + (r.common && run.roundingMode === 'commonFund' && run.rounding && (run.rounding.I || run.rounding.J || run.rounding.H) ? ` <small class="muted">(+ chênh làm tròn: H ${run.rounding.H}, I ${run.rounding.I}, J ${run.rounding.J})</small>` : ''); } },
      { key: 'g', label: 'G – Tỷ lệ', num: true, render: r => pct(r.pct) }, { key: 'h', label: 'H – Vốn', num: true, render: r => F.vnd(r.H) }, { key: 'i', label: 'I – LN gộp', num: true, render: r => F.vnd(r.I) }, { key: 'j', label: 'J – LN ròng', num: true, render: r => F.vnd(r.J) }, { key: 'm', label: 'M – Tổng nhận', num: true, render: r => `<b>${F.vnd(r.M)}</b>` }],
      footer: () => `<tr><td><b>Tổng</b></td><td class="num"><b>${pct(run.totals.pct)}</b></td><td class="num"><b>${F.vnd(run.totals.H)}</b></td><td class="num"><b>${F.vnd(run.totals.I)}</b></td><td class="num"><b>${F.vnd(run.totals.J)}</b></td><td class="num"><b>${F.vnd(run.totals.M)}</b></td></tr><tr><td colspan="4" class="muted small">Chỉ tiêu dòng tổng (SRC-07 cột K, L)</td><td class="num small">K – LNR/GV <b>${dec(run.K)}</b></td><td class="num small">L – CP/LNG <b>${dec(run.L, 4)}</b></td></tr>` });
    U.bind(root, {
      lock: () => K.act(() => X.lockShareRun(b.id, period, source), 'Đã khóa bảng kê'),
      exp: () => run && K.xls('chia-co-dong-' + b.code + '-' + period + '.xls', 'Chia ' + b.code, ['Bảng kê chia lãi ' + b.code + ' – ' + F.periodLabel(period), ['Cách tính', run.roundingMode === 'commonFund' ? 'Làm tròn theo Excel lịch sử' : 'Chênh làm tròn thành dòng riêng'], ['Trạng thái nghiệp vụ', (run.roundingPolicy || {}).status === 'confirmed' ? 'Đã xác nhận' : 'Chờ khách xác nhận OQ-08'], ['Phiên bản quy tắc', (run.roundingPolicy || {}).effectiveFrom || period], ['Nguồn', run.base.src || source], ['Trạng thái bảng kê', run.locked ? 'Đã khóa ' + F.datetime(run.lockedAt) : 'Tính thử'], ['Ghi chú', 'M là số phải chia, không phải khoản chi']],
        ['Cổ đông', 'G %', 'H Vốn', 'I LN gộp', 'J LN ròng', 'M Tổng nhận'], [...run.rows.map(r => [(Q.shareholder(r.id) || {}).name, r.pct, r.H, r.I, r.J, r.M]), ['Tổng', run.totals.pct, run.totals.H, run.totals.I, run.totals.J, run.totals.M], [run.roundingMode === 'commonFund' ? 'Chênh làm tròn dồn CHUNG (lịch sử)' : 'Chênh làm tròn riêng – chờ OQ-08', '', (run.rounding || {}).H || 0, (run.rounding || {}).I || 0, (run.rounding || {}).J || 0, ''], ['K – LNR/GV (× 100)', '', '', '', '', run.K], ['L – CP/LNG', '', '', '', '', run.L]]),
    });
  });
})(window.TH);
