(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const tMenu = (btn, t) => { const c = Q.activeContractOfTenant(t.id); U.menu(btn, [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/tenants/' + t.id) }, { label: 'Sửa', icon: 'pencil', onClick: () => Fm.tenant(t) }, '-', c ? { label: 'Xem hợp đồng ' + c.code, icon: 'file-text', onClick: () => TH.go('#/contracts/' + c.id) } : { label: 'Tạo hợp đồng', icon: 'file-plus', onClick: () => TH.go('#/contracts/new?tenant=' + t.id) }, { label: 'Thu tiền thủ công', icon: 'clipboard-check', onClick: () => Fm.payment({ tenantId: t.id }) }, { label: 'Gửi Zalo nhắc tiền', icon: 'send', onClick: () => Fm.zaloQuick({ tenantIds: [t.id], invoiceIds: St.where('invoices', i => i.tenantId === t.id && Q.invRemaining(i) > 0 && i.docStatus !== 'draft' && i.docStatus !== 'cancelled').map(i => i.id), eventKey: 'debt' }) }]); };
  TH.router.register('/tenants', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Khách thuê' }]);
    const f = { s: q.s || '', buildingId: q.buildingId || '', status: q.status || '', debt: q.debt || '', exp: q.exp || '', managerId: q.managerId || '' };
    const all = St.all('tenants').map(t => { const c = Q.activeContractOfTenant(t.id); return { t, c, status: Q.tenantStatus(t), debt: Q.tenantDebt(t.id), room: c ? Q.room(c.roomId) : null }; });
    const rows = all.filter(x => (!f.s || F.norm(x.t.name + x.t.code + x.t.phone + (x.t.email || '')).includes(F.norm(f.s))) && (!f.buildingId || (x.c && x.c.buildingId === f.buildingId)) && (!f.status || (f.status === 'renting' ? ['renting', 'expiring'].includes(x.status) : x.status === f.status)) && (!f.debt || (f.debt === 'yes' ? x.debt > 0 : x.debt === 0)) && (!f.exp || x.status === 'expiring') && (!f.managerId || x.t.managerId === f.managerId)).sort((a, b) => F.cmp(b.t.createdAt, a.t.createdAt));
    const cnt = (s) => all.filter(x => x.status === s).length;
    root.innerHTML = `${U.pageHead({ title: 'Khách thuê', sub: 'Quản lý khách thuê, hợp đồng và tình trạng công nợ.', acts: [U.btn({ label: 'Thêm khách thuê', icon: 'plus', cls: 'btn-primary', act: 'add', attrs: { 'data-guide': 'tenant-add' } }), U.btn({ label: 'Import khách', icon: 'upload', cls: 'btn-outline', act: 'import' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập mã, họ tên, SĐT, email...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái thuê', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Object.entries(Q.L.tenant).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Công nợ', input: U.select({ name: 'debt', value: f.debt, all: 'Tất cả', options: [['yes', 'Còn nợ'], ['no', 'Không nợ']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'HĐ sắp hết hạn', input: U.select({ name: 'exp', value: f.exp, all: 'Tất cả', options: [['1', 'Trong 35 ngày']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả nhân viên', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng khách thuê', value: all.length, cap: 'Tổng số khách thuê trong hệ thống', icon: 'users', tone: 'green', delta: 12 })}${U.kpi({ label: 'Đang thuê', value: cnt('renting') + cnt('expiring'), cap: F.pct(cnt('renting') + cnt('expiring'), all.length) + '% tổng khách (gồm HĐ sắp hết hạn)', icon: 'user-check', tone: 'blue', delta: 8 })}${U.kpi({ label: 'HĐ sắp hết hạn', value: cnt('expiring'), cap: 'Cần gia hạn trong 35 ngày tới', icon: 'clock', tone: 'amber', delta: 20, deltaDir: 'down' })}${U.kpi({ label: 'Chờ hoàn cọc', value: cnt('awaiting_refund'), cap: 'Đã trả phòng, chờ hoàn cọc', icon: 'hand-coins', tone: 'red', delta: 33 })}</div>
    ${U.card({ title: 'Danh sách khách thuê', actions: U.btn({ label: 'Lưu bộ lọc', icon: 'bookmark', size: 'btn-sm', p2: true, act: 'save-filter' }) + U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', act: 'cols' }), body: null, id: 'tbl-card', attrs: 'data-guide="tenants-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const cols = [
      { key: 'code', label: 'Mã KH', sortable: true, sortVal: x => x.t.code, render: x => U.link('#/tenants/' + x.t.id, esc(x.t.code), 'bold') }, { key: 'name', label: 'Họ tên', sortable: true, sortVal: x => x.t.name, render: x => `<b>${esc(x.t.name)}</b>${x.t.source === 'user' ? ' <span class="chip blue xs">mới</span>' : ''}` },
      { key: 'room', label: 'Phòng / Tòa', render: x => x.room ? U.cell2(U.link('#/rooms/' + x.room.id, x.room.code), esc(Q.building(x.room.buildingId).name)) : '-' }, { key: 'phone', label: 'Số điện thoại', render: x => esc(x.t.phone) },
      { key: 'status', label: 'Trạng thái', sortable: true, sortVal: x => x.status, render: x => Q.chip('tenant', x.status) },
      { key: 'contract', label: 'Hợp đồng hiện tại', render: x => x.c ? U.cell2(U.link('#/contracts/' + x.c.id, x.c.code), F.date(x.c.start) + ' - ' + F.date(x.c.end)) : '-' },
      { key: 'debt', label: 'Công nợ (VND)', num: true, sortable: true, sortVal: x => x.debt, render: x => `<span class="${x.debt ? 'red bold' : ''}">${F.vnd(x.debt)}</span>` },
      { key: 'dep', label: 'Tiền cọc (VND)', num: true, render: x => F.vnd(x.c ? x.c.deposit : 0) }, { key: 'mgr', label: 'Người phụ trách', render: x => esc(Q.userName(x.t.managerId)) },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': x.t.id } }), U.moreBtn(x.t.id)]), hideable: false }];
    const tbl = U.table(wrap, { rows, cols, selectable: true, unit: 'khách thuê', colPrefsKey: 'tenants', rowKey: x => x.t.id });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { add: () => Fm.tenant(), import: () => TH.go('#/settings/import?type=tenant'), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, cols: (b) => U.columnMenu(b, tbl, cols), view: (b) => TH.go('#/tenants/' + b.dataset.id), more: (b) => tMenu(b, St.get('tenants', b.dataset.id)) });
  }, { menu: 'tenants', permission: 'tenants.view' });

  TH.router.register('/tenants/:id', (root, p, q) => {
    const t = St.get('tenants', p.id); if (!t) { root.innerHTML = U.empty({ title: 'Không tìm thấy khách' }); return; }
    const tab = q.tab || 'finance'; const cs = Q.contractsOfTenant(t.id); const c = cs.find(x => x.status === 'active'); const room = c ? Q.room(c.roomId) : null; const st = Q.tenantStatus(t);
    const invs = St.where('invoices', i => i.tenantId === t.id && i.docStatus !== 'cancelled').sort((a, b) => F.cmp(b.period, a.period)); const issued = invs.filter(i => i.docStatus !== 'draft');
    const tot = F.sum(issued, i => i.total), paid = F.sum(issued, i => Q.invPaid(i)), rem = tot - paid, over = issued.filter(i => Q.invOverdue(i));
    const refunds = St.where('refunds', r => r.tenantId === t.id); const refund = refunds[0];
    const activeBuilding = room ? (Q.building(room.buildingId) || {}) : null; const mgr = (room ? Q.user(room.managerId) : Q.user(t.managerId)) || {};
    const relatedItems = [
      { key: 'room', title: 'Phòng đang thuê', icon: 'door', summary: room ? esc(room.code) : 'Chưa có phòng', meta: room ? esc(activeBuilding.name || '-') : 'Không có phòng đang thuê', actions: room ? U.btn({ label: 'Xem phòng', size: 'btn-sm', cls: 'btn-outline', act: 'go-room' }) : '', body: room ? U.kv([['Loại phòng', esc(room.type)], ['Diện tích', room.area + ' m²'], ['Giá thuê', F.vnd(c.price) + '/tháng'], ['Ngày nhận phòng', F.date(c.start)]], 'one') : U.empty({ icon: 'door', title: 'Không có phòng đang thuê' }) },
      { key: 'contract', title: 'Hợp đồng hiện tại', icon: 'file-text', summary: c ? esc(c.code) : 'Chưa có hợp đồng', meta: c ? Q.chip('contract', Q.contractStatus(c)) : 'Không có hợp đồng hiệu lực', actions: c ? U.btn({ label: 'Xem hợp đồng', size: 'btn-sm', cls: 'btn-outline', act: 'go-contract' }) : '', body: c ? U.kv([['Thời hạn', F.date(c.start) + ' - ' + F.date(c.end)], ['Thời gian còn lại', `<span class="${F.daysUntil(c.end) <= 35 ? 'red' : 'green'}">${F.durationText(F.today(), c.end)}</span>`], ['Giá thuê', F.vnd(c.price) + '/tháng'], ['Ngày ký', F.date(c.signedDate)]], 'one') : U.empty({ icon: 'file-text', title: 'Chưa có hợp đồng hiệu lực' }) },
      { key: 'deposit', title: 'Tiền cọc đang giữ', icon: 'shield', summary: c ? F.vnd(c.deposit) + ' VND' : refund ? F.vnd(refund.deposit) + ' VND' : 'Không có tiền cọc', meta: c ? U.chip('Đang giữ', 'green') : refund ? Q.chip('refund', refund.status) : 'Chưa phát sinh', actions: c ? U.btn({ label: 'Xem chi tiết', size: 'btn-sm', cls: 'btn-outline', act: 'go-contract' }) : '', body: c ? U.kv([['Tiền cọc', F.vnd(c.deposit) + ' VND'], ['Ngày đặt cọc', F.date(c.signedDate) + ' <span class="xs muted">(ngày ký HĐ)</span>'], ['Hợp đồng', U.link('#/contracts/' + c.id, esc(c.code))], ['Trạng thái', U.chip('Đang giữ', 'green')]], 'one') : refund ? `<div>${Q.chip('refund', refund.status)} ${U.link('#/refunds/' + refund.id, refund.code)}<div class="small muted mt4">Cọc ${F.vnd(refund.deposit)} · đề nghị hoàn ${F.vnd(refund.refundAmount)}</div></div>` : U.empty({ icon: 'shield', title: 'Không có cọc đang giữ' }) },
      { key: 'manager', title: 'Người quản lý', icon: 'user', summary: esc(mgr.name || 'Chưa phân công'), meta: room ? 'Quản lý ' + esc(activeBuilding.name || '-') : TH.auth.ROLE_LABEL[mgr.role] || 'Chưa có thông tin', actions: U.btn({ label: 'Liên hệ', icon: 'phone', size: 'btn-sm', cls: 'btn-outline', act: 'call', attrs: { 'data-p': mgr.phone || '' } }), body: `<div class="row gap12">${U.avatar(mgr.name || '?')}<div class="grow"><b style="color:var(--text)">${esc(mgr.name || 'Chưa phân công')}</b><div class="small muted">${room ? 'Quản lý ' + esc(activeBuilding.name || '-') : TH.auth.ROLE_LABEL[mgr.role] || 'Chưa có thông tin'}</div></div></div>` }
    ];
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Khách thuê', href: '#/tenants' }, { label: t.code }]);
    root.innerHTML = `${U.pageHead({ back: '#/tenants', title: `${U.avatar(t.name, 'lg')} ${esc(t.name)}`, chips: ' ' + Q.chipDot('tenant', st), sub: `Mã khách hàng: <a class="link">${esc(t.code)}</a> &nbsp; ${I('phone')} ${esc(t.phone)} &nbsp; ${I('briefcase')} ${esc(t.job || '-')} &nbsp; <span class="chip ${t.verified ? 'green' : 'gray'} xs">Zalo ${t.verified ? '✓ Đã xác minh' : 'chưa xác minh'}</span>`, acts: [c ? U.btn({ label: 'Gia hạn hợp đồng', icon: 'refresh', cls: 'btn-primary', act: 'renew' }) : U.btn({ label: 'Tạo hợp đồng', icon: 'file-plus', cls: 'btn-primary', act: 'newc' }), U.btn({ label: 'Sửa thông tin', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Xem lịch sử thuê', icon: 'history', cls: 'btn-outline', act: 'tab-hist' })] })}
    ${U.tabs([{ key: 'info', label: 'Thông tin' }, { key: 'history', label: 'Lịch sử thuê' }, { key: 'contracts', label: 'Hợp đồng' }, { key: 'finance', label: 'Tài chính' }, { key: 'refunds', label: 'Hoàn cọc' }, { key: 'docs', label: 'Tài liệu' }, { key: 'log', label: 'Lịch sử' }], tab)}
    <div id="tab-body"></div>${U.relatedStrip({ id: 'tenant-related', items: relatedItems, cls: 'mt24' })}`;
    const body = root.querySelector('#tab-body');
    const invTable = (rows) => { const w = document.createElement('div'); U.table(w, { rows, unit: 'hóa đơn', cols: [{ key: 'n', label: '#', render: (x, i) => i + 1, width: '40px' }, { key: 'code', label: 'Hóa đơn', render: i => U.link('#/invoices/' + i.id, i.code) }, { key: 'room', label: 'Phòng / Tòa', render: i => U.cell2(esc(Q.room(i.roomId).code), esc(Q.building(i.buildingId).name)) }, { key: 'period', label: 'Kỳ', render: i => F.periodShort(i.period) }, { key: 'total', label: 'Tổng tiền', num: true, render: i => F.vnd(i.total) }, { key: 'paid', label: 'Đã thu', num: true, render: i => F.vnd(Q.invPaid(i)) }, { key: 'rem', label: 'Còn lại', num: true, render: i => `<span class="${Q.invRemaining(i) ? 'red bold' : ''}">${F.vnd(Q.invRemaining(i))}</span>` }, { key: 'due', label: 'Hạn thanh toán', render: i => `<span class="${Q.invOverdue(i) ? 'red' : ''}">${F.date(i.dueDate)}</span>` }, { key: 'st', label: 'Trạng thái', render: i => i.docStatus === 'draft' ? Q.chip('invDoc', 'draft') : Q.invPayChip(i) }, { key: 'a', label: '', render: i => U.moreBtn(i.id) }] }); return w; };
    if (tab === 'finance') { body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng phải thu', value: F.vnd(tot), cap: issued.length + ' hóa đơn', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã thu', value: F.vnd(paid), cap: issued.filter(i => Q.invPayStatus(i) === 'paid').length + ' hóa đơn', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn phải thu', value: F.vnd(rem), cap: issued.filter(i => Q.invRemaining(i) > 0).length + ' hóa đơn', icon: 'coins', tone: 'amber' })}${U.kpi({ label: 'Hóa đơn quá hạn', value: F.vnd(F.sum(over, i => Q.invRemaining(i))), cap: over.length + ' hóa đơn', icon: 'file-x', tone: 'red', valueCls: over.length ? 'red' : '' })}</div>${U.card({ title: 'Danh sách hóa đơn / giao dịch', actions: U.btn({ label: 'Thu tiền thủ công', icon: 'clipboard-check', size: 'btn-sm', cls: 'btn-outline', act: 'pay', title: 'Chọn hóa đơn, thu một phần, phân bổ thủ công' }) + U.btn({ label: 'Xuất Excel', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export' }), body: null, id: 'ic' })}`; body.querySelector('#ic').appendChild(invTable(invs)); }
    if (tab === 'info') body.innerHTML = U.card({ title: 'Hồ sơ khách thuê', icon: 'user', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }), body: U.kv([['Mã khách', esc(t.code)], ['Họ tên', esc(t.name)], ['SĐT', esc(t.phone)], ['Zalo', esc(t.zalo || '-')], ['Email', esc(t.email || '-')], ['CMND/CCCD', esc(t.idNumber || '-')], ['Ngày sinh', t.dob ? F.date(t.dob) : '-'], ['Nghề nghiệp', esc(t.job || '-')], ['Phân khúc', esc(t.segment || 'Chưa xác định')], ['Người phụ trách', esc(Q.userName(t.managerId))], ['Ghi chú', esc(t.note || '-')], ['Xe khai báo', c ? (Q.contractServices(c.id).filter(s => /xe/i.test(s.name)).map(s => s.qty + ' xe').join(', ') || 'Không') : '-']]) });
    if (tab === 'history' || tab === 'contracts') { body.innerHTML = U.card({ title: tab === 'history' ? 'Lịch sử thuê' : 'Hợp đồng', icon: 'history', sub: 'Một khách có thể có nhiều lần thuê; lịch sử không bị ghi đè (FR-CUS-01)', actions: U.btn({ label: 'Tạo hợp đồng', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'newc' }), body: null, id: 'hc' }); const w = document.createElement('div'); body.querySelector('#hc').appendChild(w); U.table(w, { rows: cs, noPager: true, cols: [{ key: 'code', label: 'Mã HĐ', render: x => U.link('#/contracts/' + x.id, x.code) }, { key: 'room', label: 'Phòng / Tòa', render: x => esc(Q.room(x.roomId).code) + ' · ' + esc(Q.building(x.buildingId).name) }, { key: 'start', label: 'Bắt đầu', render: x => F.date(x.start) }, { key: 'end', label: 'Kết thúc', render: x => F.date(x.actualEnd || x.end) }, { key: 'price', label: 'Giá thuê', num: true, render: x => F.vnd(x.price) }, { key: 'dep', label: 'Cọc', num: true, render: x => F.vnd(x.deposit) }, { key: 'st', label: 'Trạng thái', render: x => Q.chip('contract', Q.contractStatus(x)) }], empty: U.empty({ title: 'Chưa có hợp đồng' }) }); }
    if (tab === 'refunds') { body.innerHTML = U.card({ title: 'Hồ sơ hoàn cọc', icon: 'hand-coins', body: null, id: 'rc' }); const w = document.createElement('div'); body.querySelector('#rc').appendChild(w); U.table(w, { rows: refunds, noPager: true, cols: [{ key: 'code', label: 'Mã', render: r => U.link('#/refunds/' + r.id, r.code) }, { key: 'room', label: 'Phòng', render: r => esc(Q.room(r.roomId).code) }, { key: 'd', label: 'Ngày đề nghị', render: r => F.date(r.requestDate) }, { key: 'dep', label: 'Cọc', num: true, render: r => F.vnd(r.deposit) }, { key: 'ded', label: 'Khấu trừ', num: true, render: r => F.vnd(r.deductionsTotal) }, { key: 'ref', label: 'Hoàn', num: true, render: r => F.vnd(r.refundAmount) }, { key: 'st', label: 'Trạng thái', render: r => Q.chip('refund', r.status) }], empty: U.empty({ title: 'Chưa có hồ sơ hoàn cọc' }) }); }
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'tenant' && d.entityId === t.id); body.innerHTML = U.card({ title: 'Tài liệu', icon: 'folder', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu', text: 'CCCD, hợp đồng đã ký, biên bản…' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => (x.entityType === 'tenant' && x.entityId === t.id) || (x.entityType === 'contract' && cs.some(h => h.id === x.entityId)) || (x.entityType === 'payment' && St.get('payments', x.entityId) && St.get('payments', x.entityId).tenantId === t.id)); body.innerHTML = U.card({ title: 'Lịch sử thao tác', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'tab-hist': () => { TH.router.replaceQuery({ tab: 'history' }); TH.router.refresh(); }, edit: () => Fm.tenant(t), newc: () => TH.go('#/contracts/new?tenant=' + t.id), renew: () => Fm.renew(c), 'go-room': () => TH.go('#/rooms/' + room.id), 'go-contract': () => TH.go('#/contracts/' + c.id), pay: () => Fm.payment({ tenantId: t.id }), upload: () => Fm.upload('tenant', t.id), 'rm-doc': (el) => X.removeDocument(el.dataset.id), call: (el) => U.toast('info', 'Liên hệ ' + (mgr.name || ''), el.dataset.p || 'Chưa có SĐT'),
      export: () => { F.download('hoa-don-' + t.code + '.csv', F.csv(invs.map(i => [i.code, i.period, i.total, Q.invPaid(i), Q.invRemaining(i), i.dueDate, Q.label('invPay', Q.invPayStatus(i))]), ['Mã', 'Kỳ', 'Tổng', 'Đã thu', 'Còn lại', 'Hạn', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất Excel (CSV)'); },
      more: (el) => { const inv = St.get('invoices', el.dataset.id); U.menu(el, [{ label: 'Xem hóa đơn', icon: 'eye', onClick: () => TH.go('#/invoices/' + inv.id) }, { label: 'Xác nhận thu tiền', icon: 'dollar', disabled: Q.invRemaining(inv) <= 0 || inv.docStatus === 'draft', onClick: () => Fm.confirmPayments({ invoiceIds: [inv.id] }) }, { label: 'Thu một phần / phân bổ thủ công', icon: 'clipboard-check', disabled: Q.invRemaining(inv) <= 0 || inv.docStatus === 'draft', onClick: () => Fm.payment({ invoiceId: inv.id }) }, { label: 'Gửi nhắc Zalo', icon: 'send', disabled: Q.invRemaining(inv) <= 0, onClick: () => Fm.zaloQuick({ invoiceIds: [inv.id], eventKey: 'debt' }) }]); } });
  }, { menu: 'tenants', permission: 'tenants.view', resource: { type: 'tenant' } });
})(window.TH);
