(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const tMenu = (btn, t) => { const c = Q.activeContractOfTenant(t.id); U.menu(btn, [{ label: 'Xem', icon: 'eye', onClick: () => TH.go('#/tenants/' + t.id) }, { label: 'Sửa', icon: 'pencil', onClick: () => Fm.tenant(t) }, '-', c ? { label: 'Xem hợp đồng ' + c.code, icon: 'file-text', onClick: () => TH.go('#/contracts/' + c.id) } : { label: 'Tạo hợp đồng', icon: 'file-plus', onClick: () => TH.go('#/contracts/new?tenant=' + t.id) }, { label: 'Thu tiền thủ công', icon: 'clipboard-check', onClick: () => Fm.payment({ tenantId: t.id }) }, { label: 'Gửi Zalo nhắc tiền', icon: 'send', onClick: () => Fm.zaloQuick({ tenantIds: [t.id], invoiceIds: St.where('invoices', i => i.tenantId === t.id && Q.invRemaining(i) > 0 && i.docStatus !== 'draft' && i.docStatus !== 'cancelled').map(i => i.id), eventKey: 'debt' }) }]); };
  TH.router.register('/tenants', (root, p, q) => {
    TH.router.crumb([{ label: 'Vận hành' }, { label: 'Khách thuê' }]);
    const f = { s: q.s || '', orgUnitId: q.orgUnitId || '', managerId: q.managerId || '', buildingId: q.buildingId || '', roomId: q.roomId || '', status: q.status || '', hasContract: q.hasContract || '', debt: q.debt || '', zalo: q.zalo || '', role: q.role || '', flag: q.flag || '', createdFrom: q.createdFrom || '', exp: q.exp || '' };
    const scope = Q.scope({ orgUnitId: f.orgUnitId, managerId: f.managerId, buildingId: f.buildingId });
    const all = St.all('tenants').map(t => { const fl = Q.tenantFlags(t); const c = fl.activeContract || fl.cohabitantOf[0] || null; return { t, c, fl, debt: fl.debt, room: c ? Q.room(c.roomId) : null, role: fl.activeContract ? 'primary' : (fl.cohabitantOf.length ? 'cohabitant' : '') }; });
    const rows = all.filter(x => {
      if (f.s) { const hay = F.norm([x.t.name, x.t.code, x.t.phone, x.t.idNumber, x.t.email, ((x.c && x.c.vehicles) || []).map(v => v.plate).join(' ')].join(' ')); if (!hay.includes(F.norm(f.s))) return false; }
      if ((f.orgUnitId || f.managerId || f.buildingId) && !(x.room && scope.buildingIds.includes(x.room.buildingId))) return false;
      if (f.roomId && !(x.room && x.room.id === f.roomId)) return false;
      if (f.status && (x.t.status || 'active') !== f.status) return false;
      if (f.hasContract === 'yes' && !x.fl.activeContract) return false; if (f.hasContract === 'no' && x.fl.activeContract) return false;
      if (f.debt === 'yes' && !(x.debt > 0)) return false; if (f.debt === 'no' && x.debt > 0) return false;
      if (f.zalo === 'yes' && !x.fl.zalo && !x.t.verified) return false; if (f.zalo === 'no' && (x.fl.zalo || x.t.verified)) return false;
      if (f.role && x.role !== f.role) return false;
      if (f.exp && !x.fl.expiring) return false;
      if (f.flag === 'refund' && !x.fl.awaitingRefund) return false; if (f.flag === 'held' && !x.fl.held) return false; if (f.flag === 'moved' && !x.fl.movedOut) return false;
      if (f.createdFrom && String(x.t.createdAt || '').slice(0, 10) < f.createdFrom) return false;
      return true;
    });
    const canManage = TH.auth.can('tenants.manage');
    const roomOpts = f.buildingId ? Q.roomsOf(f.buildingId).map(r => [r.id, r.code]) : [];
    root.innerHTML = `${U.pageHead({ title: 'Khách thuê', sub: 'Hồ sơ khách (một field Trạng thái cấu hình được); cờ HĐ hiệu lực / sắp hết / công nợ / hoàn cọc / Zalo là thuộc tính suy ra (§4.8).', acts: [U.btn({ label: 'Thêm khách thuê', icon: 'plus', cls: 'btn-primary', act: 'add', attrs: { 'data-guide': 'tenant-add' } }), U.btn({ label: 'Import khách', icon: 'upload', cls: 'btn-outline', act: 'import' })] })}
    ${U.filterbar([U.field({ label: 'Từ khóa (tên / SĐT / CCCD / mã / biển số)', input: U.input({ name: 's', value: f.s, placeholder: 'Tên, SĐT, CCCD…', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: f.status, all: 'Tất cả', options: Q.customerStatusOptions(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tổ chức', input: U.select({ name: 'orgUnitId', value: f.orgUnitId, all: 'Tất cả', options: Q.orgOptions(), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Quản lý (phân công)', input: U.select({ name: 'managerId', value: f.managerId, all: 'Tất cả', options: Q.managers().map(u => [u.id, u.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: f.roomId, all: f.buildingId ? 'Tất cả phòng' : 'Chọn tòa trước', options: roomOpts, attrs: { 'data-on': 'f' } }) }), U.field({ label: 'HĐ hiệu lực', input: U.select({ name: 'hasContract', value: f.hasContract, all: 'Tất cả', options: [['yes', 'Có HĐ hiệu lực'], ['no', 'Không có HĐ']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Công nợ', input: U.select({ name: 'debt', value: f.debt, all: 'Tất cả', options: [['yes', 'Còn nợ'], ['no', 'Không nợ']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Zalo', input: U.select({ name: 'zalo', value: f.zalo, all: 'Tất cả', options: [['yes', 'Đã liên kết'], ['no', 'Chưa liên kết']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Vai trò', input: U.select({ name: 'role', value: f.role, all: 'Tất cả', options: [['primary', 'Khách đứng tên'], ['cohabitant', 'Người ở cùng']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Cờ khác', input: U.select({ name: 'flag', value: f.flag, all: 'Tất cả', options: [['refund', 'Chờ hoàn cọc'], ['held', 'Đang giữ chỗ'], ['moved', 'Đã trả phòng']], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tạo từ ngày', input: U.date({ name: 'createdFrom', value: f.createdFrom, attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Khách trong hệ thống', value: all.length, cap: rows.length + ' theo bộ lọc', icon: 'users', tone: 'green' })}${U.kpi({ label: 'Có HĐ hiệu lực', value: all.filter(x => x.fl.activeContract).length, cap: all.filter(x => x.role === 'cohabitant').length + ' người ở cùng', icon: 'user-check', tone: 'blue' })}${U.kpi({ label: 'Sắp hết HĐ / còn nợ', value: all.filter(x => x.fl.expiring).length + ' / ' + all.filter(x => x.fl.hasDebt).length, cap: 'cờ suy ra, không phải trạng thái', icon: 'clock', tone: 'amber' })}${U.kpi({ label: 'Chờ hoàn cọc', value: all.filter(x => x.fl.awaitingRefund).length, cap: 'hồ sơ hoàn cọc đang xử lý', icon: 'hand-coins', tone: 'red' })}</div>
    ${U.card({ title: 'Danh sách khách thuê', actions: `<span id="bulk" class="row gap8"></span>` + U.btn({ label: 'Xuất theo bộ lọc', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export', title: 'Xuất đúng tập kết quả đang lọc (hoặc dòng đang chọn)' }) + U.btn({ label: 'Lưu bộ lọc', icon: 'bookmark', size: 'btn-sm', p2: true, act: 'save-filter' }) + U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', act: 'cols' }), body: null, id: 'tbl-card', attrs: 'data-guide="tenants-table"' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    const cols = [
      { key: 'code', label: 'Mã KH', sortable: true, sortVal: x => x.t.code, render: x => U.link('#/tenants/' + x.t.id, esc(x.t.code), 'bold') }, { key: 'name', label: 'Họ tên', sortable: true, sortVal: x => x.t.name, render: x => U.cell2(U.link('#/tenants/' + x.t.id, esc(x.t.name)), x.role === 'cohabitant' ? '<span class="xs teal">Người ở cùng</span>' : '') }, { key: 'phone', label: 'SĐT', render: x => esc(x.t.phone) }, { key: 'idNumber', label: 'CCCD', render: x => esc(x.t.idNumber || '-') },
      { key: 'status', label: 'Trạng thái', sortable: true, sortVal: x => x.t.status || 'active', render: x => Q.customerStatusChip(x.t) }, { key: 'flags', label: 'Cờ', render: x => Q.tenantFlagChips(x.t, x.fl) || '<span class="muted">-</span>' },
      { key: 'room', label: 'Tòa / phòng hiện tại', render: x => x.room ? U.cell2(U.link('#/rooms/' + x.room.id, x.room.code), esc(Q.building(x.room.buildingId).name)) : '-' },
      { key: 'contract', label: 'HĐ hiệu lực', render: x => x.fl.activeContract ? U.cell2(U.link('#/contracts/' + x.fl.activeContract.id, x.fl.activeContract.code), F.date(x.fl.activeContract.start) + ' – ' + F.date(x.fl.activeContract.end)) : (x.c ? U.cell2(U.link('#/contracts/' + x.c.id, x.c.code), 'ở cùng') : '-') },
      { key: 'debt', label: 'Công nợ (VND)', num: true, sortable: true, sortVal: x => x.debt, render: x => `<span class="${x.debt ? 'red bold' : ''}">${F.vnd(x.debt)}</span>` },
      { key: 'zalo', label: 'Zalo', render: x => x.fl.zalo || x.t.verified ? U.chip('Đã liên kết', 'green') : U.chip('Chưa', 'gray') }, { key: 'mgr', label: 'Quản lý / tổ chức', render: x => x.room ? U.cell2(esc(Q.buildingManagerName(x.room.buildingId)), esc((Q.buildingUnit(x.room.buildingId) || {}).name || '')) : esc(Q.userName(x.t.managerId)) }, { key: 'created', label: 'Ngày tạo', sortable: true, sortVal: x => x.t.createdAt || '', render: x => F.date(String(x.t.createdAt || '').slice(0, 10)) },
      { key: 'actions', label: 'Thao tác', render: x => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': x.t.id } }), U.moreBtn(x.t.id)]), hideable: false }];
    let selected = [];
    const tbl = U.table(wrap, { rows, cols, selectable: true, unit: 'khách thuê', colPrefsKey: 'tenants2', rowKey: x => x.t.id, onSelect: (ids) => { selected = ids; const b = root.querySelector('#bulk'); if (b) b.innerHTML = ids.length ? `<span class="small muted">Đã chọn ${ids.length}</span>` + U.btn({ label: 'Cập nhật trạng thái', icon: 'refresh', size: 'btn-sm', cls: 'btn-primary', act: 'bulk-status', disabled: !canManage }) + U.btn({ label: 'Gửi Zalo', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'bulk-zalo' }) : U.btn({ label: 'Cập nhật trạng thái tất cả kết quả (' + rows.length + ')', icon: 'refresh', size: 'btn-sm', cls: 'btn-ghost', act: 'bulk-all', disabled: !canManage || !rows.length }); }, presets: { ops: { label: 'Vận hành', cols: ['code', 'name', 'phone', 'status', 'flags', 'room', 'contract', 'mgr', 'actions'] }, debt: { label: 'Công nợ', cols: ['code', 'name', 'phone', 'room', 'contract', 'debt', 'zalo', 'actions'] } } });
    root.querySelector('#bulk').innerHTML = U.btn({ label: 'Cập nhật trạng thái tất cả kết quả (' + rows.length + ')', icon: 'refresh', size: 'btn-sm', cls: 'btn-ghost', act: 'bulk-all', disabled: !canManage || !rows.length });
    const bulk = (ids, label) => { const m = U.modal({ title: 'Cập nhật trạng thái hàng loạt', size: 'sm', sub: label, body: `${U.note('warn', 'Ảnh hưởng ' + ids.length + ' khách', 'Chỉ update field Trạng thái; audit theo batch + từng khách (§12.6.5). Không đổi cờ HĐ/công nợ.')}<div class="form-grid mt12">${U.field({ label: 'Trạng thái mới', req: true, input: U.select({ name: 'status', options: Q.customerStatusOptions() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Xác nhận cập nhật ' + ids.length + ' khách', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); const r = X.bulkTenantStatus(ids, d.status, d.reason); m.close(); U.toast('ok', 'Đã cập nhật ' + r.updated + ' khách', 'Batch ' + r.batchId); TH.router.refresh(); } catch (e) { U.toast('err', 'Không cập nhật được', e.message); } } }); };
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); if (d.buildingId !== f.buildingId) d.roomId = ''; TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { add: () => Fm.tenant(), import: () => TH.go('#/settings/import?type=tenant'), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, cols: (b) => U.columnMenu(b, tbl, cols), view: (b) => TH.go('#/tenants/' + b.dataset.id), more: (b) => tMenu(b, St.get('tenants', b.dataset.id)),
      'bulk-status': () => bulk(selected, selected.length + ' khách đang chọn'), 'bulk-all': () => bulk(rows.map(x => x.t.id), 'Tất cả kết quả tìm kiếm hiện tại (' + rows.length + ' khách)'), 'bulk-zalo': () => Fm.zaloQuick({ tenantIds: selected, eventKey: 'debt' }),
      export: () => { const list = selected.length ? rows.filter(x => selected.includes(x.t.id)) : rows; X.exportCsv({ fileName: 'khach-thue-' + F.today() + '.csv', entity: 'tenant', filters: Object.assign({ selected: selected.length ? selected.length + ' dòng' : 'toàn bộ kết quả' }, f), header: ['Mã KH', 'Họ tên', 'SĐT', 'CCCD', 'Trạng thái', 'Cờ', 'Tòa', 'Phòng', 'HĐ hiệu lực', 'Công nợ', 'Zalo', 'Quản lý', 'Ngày tạo'], rows: list.map(x => [x.t.code, x.t.name, x.t.phone, x.t.idNumber || '', x.t.status || 'active', [x.fl.activeContract ? 'HĐ hiệu lực' : '', x.fl.expiring ? 'Sắp hết' : '', x.fl.hasDebt ? 'Còn nợ' : '', x.fl.awaitingRefund ? 'Chờ hoàn cọc' : ''].filter(Boolean).join('|'), x.room ? Q.building(x.room.buildingId).name : '', x.room ? x.room.code : '', x.fl.activeContract ? x.fl.activeContract.code : '', x.debt, x.fl.zalo || x.t.verified ? 'Có' : 'Không', x.room ? Q.buildingManagerName(x.room.buildingId) : '', String(x.t.createdAt || '').slice(0, 10)]) }); U.toast('ok', 'Đã xuất ' + list.length + ' khách theo bộ lọc'); } });
  }, { menu: 'tenants', permission: 'tenants.view' });

  TH.router.register('/tenants/:id', (root, p, q) => {
    const t = St.get('tenants', p.id); if (!t) { root.innerHTML = U.empty({ title: 'Không tìm thấy khách' }); return; }
    const tab = q.tab || 'info'; const cs = Q.contractsOfTenant(t.id); const fl = Q.tenantFlags(t); const c = fl.activeContract; const coC = fl.cohabitantOf; const room = c ? Q.room(c.roomId) : (coC[0] ? Q.room(coC[0].roomId) : null); const st = Q.tenantStatus(t); const pays = Q.tenantPayments(t.id); const vehicles = Q.tenantVehicles(t);
    const invs = St.where('invoices', i => i.tenantId === t.id && i.docStatus !== 'cancelled').sort((a, b) => F.cmp(b.period, a.period)); const issued = invs.filter(i => i.docStatus !== 'draft');
    const tot = F.sum(issued, i => i.total), paid = F.sum(issued, i => Q.invPaid(i)), rem = tot - paid, over = issued.filter(i => Q.invOverdue(i));
    const refunds = St.where('refunds', r => r.tenantId === t.id); const refund = refunds[0];
    const activeBuilding = room ? (Q.building(room.buildingId) || {}) : null; const mgr = (room ? Q.user(room.managerId) : Q.user(t.managerId)) || {};
    const relatedItems = [
      { key: 'room', title: 'Phòng đang thuê', icon: 'door', summary: room ? esc(room.code) : 'Chưa có phòng', meta: room ? esc(activeBuilding.name || '-') : 'Không có phòng đang thuê', actions: room ? U.btn({ label: 'Xem phòng', size: 'btn-sm', cls: 'btn-outline', act: 'go-room' }) : '', body: room ? U.kv([['Loại phòng', esc(room.type)], ['Diện tích', room.area + ' m²'], ['Giá thuê', F.vnd(c.price) + '/tháng'], ['Ngày nhận phòng', F.date(c.start)]], 'one') : U.empty({ icon: 'door', title: 'Không có phòng đang thuê' }) },
      { key: 'contract', title: 'Hợp đồng hiện tại', icon: 'file-text', summary: c ? esc(c.code) : 'Chưa có hợp đồng', meta: c ? Q.chip('contract', Q.contractStatus(c)) : 'Không có hợp đồng hiệu lực', actions: c ? U.btn({ label: 'Xem hợp đồng', size: 'btn-sm', cls: 'btn-outline', act: 'go-contract' }) : '', body: c ? U.kv([['Thời hạn', F.date(c.start) + ' - ' + F.date(c.end)], ['Thời gian còn lại', `<span class="${F.daysUntil(c.end) <= 35 ? 'red' : 'green'}">${F.durationText(F.today(), c.end)}</span>`], ['Giá thuê', F.vnd(c.price) + '/tháng'], ['Ngày ký', F.date(c.signedDate)]], 'one') : U.empty({ icon: 'file-text', title: 'Chưa có hợp đồng hiệu lực' }) },
      { key: 'deposit', title: 'Tiền cọc đang giữ', icon: 'shield', summary: c ? F.vnd(c.deposit) + ' VND' : refund ? F.vnd(refund.deposit) + ' VND' : 'Không có tiền cọc', meta: c ? U.chip('Đang giữ', 'green') : refund ? Q.chip('refund', refund.status) : 'Chưa phát sinh', actions: c ? U.btn({ label: 'Xem chi tiết', size: 'btn-sm', cls: 'btn-outline', act: 'go-contract' }) : '', body: c ? U.kv([['Tiền cọc', F.vnd(c.deposit) + ' VND'], ['Ngày đặt cọc', F.date(c.signedDate) + ' <span class="xs muted">(ngày ký HĐ)</span>'], ['Hợp đồng', U.link('#/contracts/' + c.id, esc(c.code))], ['Trạng thái', U.chip('Đang giữ', 'green')]], 'one') : refund ? `<div>${Q.chip('refund', refund.status)} ${U.link('#/refunds/' + refund.id, refund.code)}<div class="small muted mt4">Cọc ${F.vnd(refund.deposit)} · đề nghị hoàn ${F.vnd(refund.refundAmount)}</div></div>` : U.empty({ icon: 'shield', title: 'Không có cọc đang giữ' }) },
      { key: 'manager', title: 'Người quản lý', icon: 'user', summary: esc(mgr.name || 'Chưa phân công'), meta: room ? 'Quản lý ' + esc(activeBuilding.name || '-') : TH.auth.ROLE_LABEL[mgr.role] || 'Chưa có thông tin', actions: U.btn({ label: 'Liên hệ', icon: 'phone', size: 'btn-sm', cls: 'btn-outline', act: 'call', attrs: { 'data-p': mgr.phone || '' } }), body: `<div class="row gap12">${U.avatar(mgr.name || '?')}<div class="grow"><b style="color:var(--text)">${esc(mgr.name || 'Chưa phân công')}</b><div class="small muted">${room ? 'Quản lý ' + esc(activeBuilding.name || '-') : TH.auth.ROLE_LABEL[mgr.role] || 'Chưa có thông tin'}</div></div></div>` }
    ];
    TH.router.crumb([{ label: 'Quản lý cho thuê' }, { label: 'Khách thuê', href: '#/tenants' }, { label: t.code }]);
    root.innerHTML = `${U.pageHead({ back: '#/tenants', title: `${U.avatar(t.name, 'lg')} ${esc(t.name)}`, chips: ' ' + Q.customerStatusChip(t) + ' ' + Q.tenantFlagChips(t, fl), sub: `Mã khách hàng: <a class="link">${esc(t.code)}</a> &nbsp; ${I('phone')} ${esc(t.phone)} &nbsp; ${I('briefcase')} ${esc(t.job || '-')} &nbsp; <span class="chip ${t.verified ? 'green' : 'gray'} xs">Zalo ${t.verified ? '✓ Đã xác minh' : 'chưa xác minh'}</span>`, acts: [c ? U.btn({ label: 'Gia hạn hợp đồng', icon: 'refresh', cls: 'btn-primary', act: 'renew' }) : U.btn({ label: 'Tạo hợp đồng', icon: 'file-plus', cls: 'btn-primary', act: 'newc' }), U.btn({ label: 'Sửa thông tin', icon: 'pencil', cls: 'btn-outline', act: 'edit' }), U.btn({ label: 'Đổi trạng thái', icon: 'refresh', cls: 'btn-outline', act: 'status', disabled: !TH.auth.can('tenants.manage') })] })}
    ${U.tabs([{ key: 'info', label: 'Thông tin' }, { key: 'contracts', label: 'Hợp đồng', count: cs.length }, { key: 'residence', label: 'Nơi ở' }, { key: 'cohab', label: 'Người ở cùng' }, { key: 'vehicles', label: 'Xe', count: vehicles.length }, { key: 'invoices', label: 'Hóa đơn', count: invs.length }, { key: 'payments', label: 'Thanh toán', count: pays.length }, { key: 'debt', label: 'Công nợ' }, { key: 'zalo', label: 'Zalo' }, { key: 'refunds', label: 'Hoàn cọc', count: refunds.length }, { key: 'docs', label: 'Tài liệu' }, { key: 'log', label: 'Lịch sử' }], tab)}
    <div id="tab-body"></div>${U.relatedStrip({ id: 'tenant-related', items: relatedItems, cls: 'mt24' })}`;
    const body = root.querySelector('#tab-body');
    const invTable = (rows) => { const w = document.createElement('div'); U.table(w, { rows, unit: 'hóa đơn', cols: [{ key: 'n', label: '#', render: (x, i) => i + 1, width: '40px' }, { key: 'code', label: 'Hóa đơn', render: i => U.link('#/invoices/' + i.id, i.code) }, { key: 'room', label: 'Phòng / Tòa', render: i => U.cell2(esc(Q.room(i.roomId).code), esc(Q.building(i.buildingId).name)) }, { key: 'period', label: 'Kỳ', render: i => F.periodShort(i.period) }, { key: 'total', label: 'Tổng tiền', num: true, render: i => F.vnd(i.total) }, { key: 'paid', label: 'Đã thu', num: true, render: i => F.vnd(Q.invPaid(i)) }, { key: 'rem', label: 'Còn lại', num: true, render: i => `<span class="${Q.invRemaining(i) ? 'red bold' : ''}">${F.vnd(Q.invRemaining(i))}</span>` }, { key: 'due', label: 'Hạn thanh toán', render: i => `<span class="${Q.invOverdue(i) ? 'red' : ''}">${F.date(i.dueDate)}</span>` }, { key: 'st', label: 'Trạng thái', render: i => i.docStatus === 'draft' ? Q.chip('invDoc', 'draft') : Q.invPayChip(i) }, { key: 'a', label: '', render: i => U.moreBtn(i.id) }] }); return w; };
    if (tab === 'invoices' || tab === 'finance') { body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng phải thu', value: F.vnd(tot), cap: issued.length + ' hóa đơn', icon: 'dollar', tone: 'blue' })}${U.kpi({ label: 'Đã thu', value: F.vnd(paid), cap: issued.filter(i => Q.invPayStatus(i) === 'paid').length + ' hóa đơn', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Còn phải thu', value: F.vnd(rem), cap: issued.filter(i => Q.invRemaining(i) > 0).length + ' hóa đơn', icon: 'coins', tone: 'amber' })}${U.kpi({ label: 'Hóa đơn quá hạn', value: F.vnd(F.sum(over, i => Q.invRemaining(i))), cap: over.length + ' hóa đơn', icon: 'file-x', tone: 'red', valueCls: over.length ? 'red' : '' })}</div>${U.card({ title: 'Danh sách hóa đơn / giao dịch', actions: U.btn({ label: 'Thu tiền thủ công', icon: 'clipboard-check', size: 'btn-sm', cls: 'btn-outline', act: 'pay', title: 'Chọn hóa đơn, thu một phần, phân bổ thủ công' }) + U.btn({ label: 'Xuất Excel', icon: 'download', size: 'btn-sm', cls: 'btn-outline', act: 'export' }), body: null, id: 'ic' })}`; body.querySelector('#ic').appendChild(invTable(invs)); }
    if (tab === 'info') body.innerHTML = U.card({ title: 'Hồ sơ khách thuê', icon: 'user', actions: U.btn({ label: 'Sửa', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'edit' }), body: U.kv([['Mã khách', esc(t.code)], ['Trạng thái khách', Q.customerStatusChip(t) + (t.statusAt ? ' <span class="xs muted">· ' + F.datetime(t.statusAt) + '</span>' : '') + ' <span class="xs muted">(field lưu, cấu hình tại Master Data)</span>'], ['Cờ suy ra', Q.tenantFlagChips(t, fl) || '-'], ['Họ tên', esc(t.name)], ['SĐT', esc(t.phone)], ['Zalo', esc(t.zalo || '-')], ['Email', esc(t.email || '-')], ['CMND/CCCD', esc(t.idNumber || '-') + (t.idPlace ? ' <span class="muted small">· cấp tại ' + esc(t.idPlace) + '</span>' : '')], ['Ngày sinh', t.dob ? F.date(t.dob) : '-'], ['Hộ khẩu thường trú', esc(t.address || '-')], ['Nghề nghiệp', esc(t.job || '-')], ['Phân khúc', esc(t.segment || 'Chưa xác định')], ['Người phụ trách', esc(Q.userName(t.managerId))], ['Ghi chú', esc(t.note || '-')], ['Phương tiện', c && (c.vehicles || []).length ? c.vehicles.map(v => esc(v.type) + ' · <b>' + esc(v.plate || '-') + '</b>').join('<br>') : 'Không']]) });
    if (tab === 'residence') body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Nơi ở hiện tại', icon: 'home', body: room ? U.kv([['Tòa nhà', U.link('#/buildings/' + room.buildingId, esc(Q.building(room.buildingId).name))], ['Phòng', U.link('#/rooms/' + room.id, esc(room.code)) + ' ' + Q.chipDot('room', room.status)], ['Vai trò', c ? Q.chip('contractTenantRole', 'primary') : Q.chip('contractTenantRole', 'cohabitant')], ['Hợp đồng', U.link('#/contracts/' + (c || coC[0]).id, esc((c || coC[0]).code)) + ' ' + Q.chip('contract', Q.contractStatus(c || coC[0]))], ['Thời hạn', F.date((c || coC[0]).start) + ' – ' + F.date((c || coC[0]).end)], ['Quản lý tòa', esc(Q.buildingManagerName(room.buildingId))], ['Đơn vị', esc((Q.buildingUnit(room.buildingId) || {}).name || '-')]], 'one') : U.empty({ title: 'Không có nơi ở hiện tại', text: 'Khách chưa gắn HĐ hiệu lực nào.' }) })}${U.card({ title: 'Lịch sử nơi ở', icon: 'history', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Phòng / Tòa</th><th>Vai trò</th><th>Từ</th><th>Đến</th><th>HĐ</th></tr></thead><tbody>${cs.map(x => `<tr><td>${esc(Q.room(x.roomId).code)} · ${esc(Q.building(x.buildingId).name)}</td><td>${Q.chip('contractTenantRole', 'primary')}</td><td>${F.date(x.start)}</td><td>${F.date(x.actualEnd || x.end)}</td><td>${U.link('#/contracts/' + x.id, esc(x.code))} ${Q.chip('contract', Q.contractStatus(x))}</td></tr>`).concat(St.where('contractTenants', ct => ct.tenantId === t.id && ct.role === 'cohabitant').map(ct => { const x = Q.contract(ct.contractId); return x ? `<tr><td>${esc(Q.room(x.roomId).code)} · ${esc(Q.building(x.buildingId).name)}</td><td>${Q.chip('contractTenantRole', 'cohabitant')}</td><td>${F.date(ct.from || x.start)}</td><td>${ct.to ? F.date(ct.to) : F.date(x.actualEnd || x.end)}</td><td>${U.link('#/contracts/' + x.id, esc(x.code))}</td></tr>` : ''; })).join('') || '<tr><td colspan="5" class="muted tc">Chưa có</td></tr>'}</tbody></table>` })}</div>`;
    if (tab === 'cohab') { const mine = c ? Q.contractCohabitants(c.id) : []; body.innerHTML = U.card({ title: 'Người ở cùng (§4.8 – hồ sơ khách riêng liên kết HĐ)', icon: 'users', actions: c ? U.btn({ label: 'Thêm người ở cùng', icon: 'user-plus', size: 'btn-sm', cls: 'btn-primary', act: 'add-cohab' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Họ tên</th><th>Hồ sơ</th><th>SĐT</th><th>CCCD</th><th>Quan hệ</th><th>Từ – đến</th><th>HĐ</th></tr></thead><tbody>${mine.map(m => { const tt = m.tenantId ? Q.tenant(m.tenantId) : null; return `<tr class="${m.to ? 'muted' : ''}"><td><b>${esc(tt ? tt.name : m.name)}</b></td><td>${tt ? U.link('#/tenants/' + tt.id, esc(tt.code)) : U.chip('Chưa liên kết', 'amber')}</td><td>${esc(tt ? tt.phone : m.phone || '-')}</td><td>${esc(tt ? tt.idNumber || '-' : m.idNumber || '-')}</td><td>${esc(m.relation || '-')}</td><td class="xs">${F.date(m.from || c.start)} – ${m.to ? F.date(m.to) : 'nay'}</td><td>${U.link('#/contracts/' + c.id + '?tab=members', esc(c.code))}</td></tr>`; }).join('') || `<tr><td colspan="7" class="muted tc">${c ? 'Chưa có người ở cùng' : 'Khách không đứng tên HĐ hiệu lực'}${coC.length ? ' · khách này là người ở cùng của HĐ ' + coC.map(x => U.link('#/contracts/' + x.id, esc(x.code))).join(', ') : ''}</td></tr>`}</tbody></table>` }); }
    if (tab === 'vehicles') body.innerHTML = U.card({ title: 'Phương tiện', icon: 'car', sub: 'Theo hợp đồng hiệu lực; phí gửi/sạc xe theo dịch vụ HĐ', actions: c ? U.btn({ label: 'Sửa xe (tại HĐ)', icon: 'pencil', size: 'btn-sm', cls: 'btn-outline', act: 'go-contract-services' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Loại</th><th>Biển số</th><th>Hợp đồng</th></tr></thead><tbody>${vehicles.map((v, i) => `<tr><td>${i + 1}</td><td>${esc(v.type)}</td><td><b>${esc(v.plate || '-')}</b></td><td>${U.link('#/contracts/' + v.contract.id, esc(v.contract.code))}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Không có xe đăng ký</td></tr>'}</tbody></table>` });
    if (tab === 'payments') body.innerHTML = U.card({ title: 'Thanh toán', icon: 'wallet', actions: U.btn({ label: 'Ghi nhận thu tiền', icon: 'dollar', size: 'btn-sm', cls: 'btn-primary', act: 'pay' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã</th><th>Ngày</th><th class="num">Số tiền</th><th>Phương thức</th><th>Loại</th><th>Phân bổ</th><th>Tham chiếu</th></tr></thead><tbody>${pays.map(p => { const al = St.where('paymentAllocations', a => a.paymentId === p.id); return `<tr><td>${U.link('#/payments/' + p.id, esc(p.code))}</td><td>${F.date(p.date)}</td><td class="num"><b>${F.vnd(p.amount)}</b></td><td>${esc(p.method || '')}</td><td>${Q.chip('paymentKind', Q.paymentKind(p))}</td><td class="xs">${al.map(a => esc((St.rawGet('invoices', a.invoiceId) || {}).code || '') + ' ' + F.vnd(a.amount)).join('<br>') || '<span class="muted">chưa phân bổ ' + F.vnd(Q.paymentUnallocated(p)) + '</span>'}</td><td class="xs">${esc(p.ref || '')}</td></tr>`; }).join('') || '<tr><td colspan="7" class="muted tc">Chưa có khoản thu</td></tr>'}</tbody></table>` });
    if (tab === 'debt') { const dr = issued.map(i => ({ inv: i, paid: Q.invPaid(i), remaining: Q.invRemaining(i), overdueDays: Q.invOverdueDays(i) })); body.innerHTML = `<div class="grid grid-4 mb16">${U.kpi({ mini: true, label: 'Tổng phải thu', value: F.vnd(tot), icon: 'receipt', tone: 'blue' })}${U.kpi({ mini: true, label: 'Đã thu', value: F.vnd(paid), icon: 'check-circle', tone: 'green' })}${U.kpi({ mini: true, label: 'Còn nợ', value: F.vnd(rem), icon: 'alert-circle', tone: rem ? 'red' : 'green' })}${U.kpi({ mini: true, label: 'Quá hạn', value: F.vnd(F.sum(over, i => Q.invRemaining(i))), cap: over.length + ' hóa đơn', icon: 'clock', tone: 'amber' })}</div>` + U.card({ title: 'Công nợ theo hóa đơn → payment', icon: 'alert-circle', actions: rem > 0 ? U.btn({ label: 'Nhắc Zalo', icon: 'send', size: 'btn-sm', cls: 'btn-outline', act: 'zalo-debt' }) : '', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Hóa đơn</th><th>Phòng</th><th>Kỳ</th><th>Hạn</th><th class="num">Tổng</th><th class="num">Đã thu</th><th class="num">Còn lại</th><th>Trạng thái</th><th>Payment</th></tr></thead><tbody>${dr.map(x => `<tr><td>${U.link('#/invoices/' + x.inv.id, esc(x.inv.code))}</td><td>${esc(Q.room(x.inv.roomId).code)}</td><td>${F.periodShort(x.inv.period)}</td><td>${F.date(x.inv.dueDate)}${x.overdueDays > 0 && x.remaining > 0 ? ' <span class="red xs">+' + x.overdueDays + 'd</span>' : ''}</td><td class="num">${F.vnd(x.inv.total)}</td><td class="num">${F.vnd(x.paid)}</td><td class="num ${x.remaining ? 'red bold' : ''}">${F.vnd(x.remaining)}</td><td>${Q.chip('invPay', Q.invPayStatusW3(x.inv))}</td><td class="xs">${St.where('paymentAllocations', a => a.invoiceId === x.inv.id).map(a => U.link('#/payments/' + a.paymentId, esc((St.rawGet('payments', a.paymentId) || {}).code || ''))).join(', ') || '-'}</td></tr>`).join('') || '<tr><td colspan="9" class="muted tc">Không có công nợ</td></tr>'}</tbody></table>` }); }
    if (tab === 'zalo') { const msgs = St.where('zaloMessages', m => m.tenantId === t.id).sort((a, b) => F.cmp(b.createdAt || '', a.createdAt || '')); body.innerHTML = `<div class="grid grid-2">${U.card({ title: 'Liên kết Zalo', icon: 'send', body: U.kv([['SĐT Zalo', esc(t.zalo || t.phone || '-')], ['Trạng thái liên kết', fl.zalo || t.verified ? U.chip('Đã liên kết', 'green') : U.chip('Chưa liên kết', 'gray')], ['Zalo ID', esc(t.zaloId || '-')], ['Đồng ý nhận thông báo', t.zaloOptOut ? 'Không' : 'Có']], 'one') + '<div class="mt8">' + U.btn({ label: fl.zalo || t.verified ? 'Hủy liên kết' : 'Liên kết Zalo (mô phỏng)', icon: 'link', size: 'btn-sm', cls: 'btn-outline', act: 'zalo-link' }) + '</div>' })}${U.card({ title: 'Tin đã gửi (' + msgs.length + ')', icon: 'history', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Thời gian</th><th>Sự kiện</th><th>Trạng thái</th></tr></thead><tbody>${msgs.slice(0, 20).map(m => `<tr><td class="xs">${F.datetime(m.sentAt || m.createdAt)}</td><td class="xs">${esc(m.eventKey || m.templateName || '')}</td><td>${Q.chip('zmsg', m.status)}</td></tr>`).join('') || '<tr><td colspan="3" class="muted tc">Chưa gửi tin nào</td></tr>'}</tbody></table>` })}</div>`; }
    if (tab === 'history' || tab === 'contracts') { body.innerHTML = U.card({ title: tab === 'history' ? 'Lịch sử thuê' : 'Hợp đồng', icon: 'history', sub: 'Một khách có thể có nhiều lần thuê; lịch sử không bị ghi đè (FR-CUS-01)', actions: U.btn({ label: 'Tạo hợp đồng', icon: 'plus', size: 'btn-sm', cls: 'btn-outline', act: 'newc' }), body: null, id: 'hc' }); const w = document.createElement('div'); body.querySelector('#hc').appendChild(w); U.table(w, { rows: cs, noPager: true, cols: [{ key: 'code', label: 'Mã HĐ', render: x => U.link('#/contracts/' + x.id, x.code) }, { key: 'room', label: 'Phòng / Tòa', render: x => esc(Q.room(x.roomId).code) + ' · ' + esc(Q.building(x.buildingId).name) }, { key: 'start', label: 'Bắt đầu', render: x => F.date(x.start) }, { key: 'end', label: 'Kết thúc', render: x => F.date(x.actualEnd || x.end) }, { key: 'price', label: 'Giá thuê', num: true, render: x => F.vnd(x.price) }, { key: 'dep', label: 'Cọc', num: true, render: x => F.vnd(x.deposit) }, { key: 'st', label: 'Trạng thái', render: x => Q.chip('contract', Q.contractStatus(x)) }], empty: U.empty({ title: 'Chưa có hợp đồng' }) }); }
    if (tab === 'refunds') { body.innerHTML = U.card({ title: 'Hồ sơ hoàn cọc', icon: 'hand-coins', body: null, id: 'rc' }); const w = document.createElement('div'); body.querySelector('#rc').appendChild(w); U.table(w, { rows: refunds, noPager: true, cols: [{ key: 'code', label: 'Mã', render: r => U.link('#/refunds/' + r.id, r.code) }, { key: 'room', label: 'Phòng', render: r => esc(Q.room(r.roomId).code) }, { key: 'd', label: 'Ngày đề nghị', render: r => F.date(r.requestDate) }, { key: 'dep', label: 'Cọc', num: true, render: r => F.vnd(r.deposit) }, { key: 'ded', label: 'Khấu trừ', num: true, render: r => F.vnd(r.deductionsTotal) }, { key: 'ref', label: 'Hoàn', num: true, render: r => F.vnd(r.refundAmount) }, { key: 'st', label: 'Trạng thái', render: r => Q.chip('refund', r.status) }], empty: U.empty({ title: 'Chưa có hồ sơ hoàn cọc' }) }); }
    if (tab === 'docs') { const docs = St.where('documents', d => d.entityType === 'tenant' && d.entityId === t.id); body.innerHTML = U.card({ title: 'Tài liệu', icon: 'folder', actions: U.btn({ label: 'Tải lên', icon: 'upload', size: 'btn-sm', cls: 'btn-primary', act: 'upload' }), body: docs.length ? `<div class="file-list">${docs.map(d => U.fileItem(d, U.iconBtn('trash', 'rm-doc', 'Xóa', { 'data-id': d.id }))).join('')}</div>` : U.empty({ icon: 'folder', title: 'Chưa có tài liệu', text: 'CCCD, hợp đồng đã ký, biên bản…' }) }); }
    if (tab === 'log') { const logs = St.where('auditLog', x => (x.entityType === 'tenant' && x.entityId === t.id) || (x.entityType === 'contract' && cs.some(h => h.id === x.entityId)) || (x.entityType === 'payment' && St.get('payments', x.entityId) && St.get('payments', x.entityId).tenantId === t.id)); body.innerHTML = U.card({ title: 'Lịch sử thao tác', icon: 'clock', body: logs.length ? U.timeline(logs.map(x => ({ when: F.datetime(x.at), title: x.summary, sub: x.userName, color: 'blue' }))) : U.empty({ title: 'Chưa có lịch sử' }) }); }
    U.bind(root, { tab: (el) => { TH.router.replaceQuery({ tab: el.dataset.key }); TH.router.refresh(); }, 'tab-hist': () => { TH.router.replaceQuery({ tab: 'contracts' }); TH.router.refresh(); }, edit: () => Fm.tenant(t), status: () => { const m = U.modal({ title: 'Đổi trạng thái khách', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: t.status || 'active', options: Q.customerStatusOptions() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) })}</div>`, footer: U.btn({ label: 'Hủy', act: 'c' }) + U.btn({ label: 'Lưu', cls: 'btn-primary', act: 's' }) }); U.bind(m.el, { c: () => m.close(), s: () => { try { const d = m.data(); X.setTenantStatus(t.id, d.status, d.reason); m.close(); U.toast('ok', 'Đã đổi trạng thái'); TH.router.refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } }); }, 'add-cohab': () => c && TH.go('#/contracts/' + c.id + '?tab=members'), 'go-contract-services': () => c && TH.go('#/contracts/' + c.id + '?tab=services'), 'zalo-debt': () => Fm.zaloQuick({ tenantIds: [t.id], invoiceIds: issued.filter(i => Q.invRemaining(i) > 0).map(i => i.id), eventKey: 'debt' }), 'zalo-link': () => { t.zaloLinked = !(fl.zalo || t.verified); t.verified = t.zaloLinked; t.zaloId = t.zaloLinked ? 'zl_' + String(t.phone || '').replace(/\D/g, '').slice(-6) : ''; St.audit('zalo_link', 'tenant', t.id, (t.zaloLinked ? 'Liên kết' : 'Hủy liên kết') + ' Zalo khách ' + t.name); St.save(); TH.router.refresh(); }, newc: () => TH.go('#/contracts/new?tenant=' + t.id), renew: () => Fm.renew(c), 'go-room': () => TH.go('#/rooms/' + room.id), 'go-contract': () => TH.go('#/contracts/' + c.id), pay: () => Fm.payment({ tenantId: t.id }), upload: () => Fm.upload('tenant', t.id), 'rm-doc': (el) => X.removeDocument(el.dataset.id), call: (el) => U.toast('info', 'Liên hệ ' + (mgr.name || ''), el.dataset.p || 'Chưa có SĐT'),
      export: () => { F.download('hoa-don-' + t.code + '.csv', F.csv(invs.map(i => [i.code, i.period, i.total, Q.invPaid(i), Q.invRemaining(i), i.dueDate, Q.label('invPay', Q.invPayStatus(i))]), ['Mã', 'Kỳ', 'Tổng', 'Đã thu', 'Còn lại', 'Hạn', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất Excel (CSV)'); },
      more: (el) => { const inv = St.get('invoices', el.dataset.id); U.menu(el, [{ label: 'Xem hóa đơn', icon: 'eye', onClick: () => TH.go('#/invoices/' + inv.id) }, { label: 'Xác nhận thu tiền', icon: 'dollar', disabled: Q.invRemaining(inv) <= 0 || inv.docStatus === 'draft', onClick: () => Fm.confirmPayments({ invoiceIds: [inv.id] }) }, { label: 'Thu một phần / phân bổ thủ công', icon: 'clipboard-check', disabled: Q.invRemaining(inv) <= 0 || inv.docStatus === 'draft', onClick: () => Fm.payment({ invoiceId: inv.id }) }, { label: 'Gửi nhắc Zalo', icon: 'send', disabled: Q.invRemaining(inv) <= 0, onClick: () => Fm.zaloQuick({ invoiceIds: [inv.id], eventKey: 'debt' }) }]); } });
  }, { menu: 'tenants', permission: 'tenants.view', resource: { type: 'tenant' } });
})(window.TH);
