(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc, C = TH.chart;
  const EV_ICON = { reminder: 'dollar', contract_expiry: 'file-text', refund_done: 'hand-coins', landlord_due: 'landmark', broadcast: 'megaphone', viewing_reminder: 'calendar-check', maintenance_due: 'wrench' };
  const SOURCES = [['issued', 'Hóa đơn vừa phát hành', 'Gửi hóa đơn kỳ hiện tại tới khách thuê', 'reminder', 'receipt', 'blue'], ['due_soon', 'Nhắc trước hạn', 'Hóa đơn đến hạn trong 3 ngày tới, còn nợ', 'reminder', 'clock', 'amber'], ['overdue', 'Công nợ quá hạn', 'Khách thuê có công nợ quá hạn thanh toán', 'debt', 'alert-circle', 'red'], ['debt', 'Cần xử lý công nợ', 'Hóa đơn phát hành ≥ 5 ngày còn nợ (BR-07)', 'debt', 'receipt', 'purple'], ['contract_expiry', 'HĐ sắp hết hạn', 'Hợp đồng còn ≤ 35 ngày', 'contract_expiry', 'file-text', 'amber'], ['refund_done', 'Đã hoàn cọc', 'Hồ sơ hoàn cọc đã hoàn tiền', 'refund_done', 'hand-coins', 'green'], ['broadcast', 'Thông báo chung', 'Toàn bộ cư dân đang thuê trong phạm vi', 'broadcast', 'megaphone', 'gray']];
  /* ---------- Cấu hình ---------- */
  TH.router.register('/zalo/config', (root, p, q) => {
    TH.router.crumb([{ label: 'Cài đặt' }, { label: 'Thông báo & nhắc việc' }]);
    const evs = St.where('zaloEvents', e => !e.phase || TH.phase.on(e.phase)).map(e => Object.assign({}, e, { p2: e.p2 && !TH.phase.on(2), p2on: (e.p2 || e.phase) && TH.phase.on(2) })); const key = q.ev || 'reminder'; const ev = evs.find(e => e.key === key) || evs[0]; const tpls = St.where('zaloTemplates', t => t.eventKey === ev.key || ev.key === 'broadcast'); const tpl = Q.template(ev.templateId);
    const sampleInv = St.where('invoices', i => i.docStatus !== 'draft' && Q.invRemaining(i) > 0)[0]; const sampleT = sampleInv ? Q.tenant(sampleInv.tenantId) : St.all('tenants')[0];
    const recent = St.all('zaloBatches').sort((a, b) => F.cmp(b.createdAt || '', a.createdAt || '')).slice(0, 5);
    const canCfg = TH.auth.can('zaloConfig');
    root.innerHTML = `${U.pageHead({ title: 'Thông báo & nhắc việc', sub: 'Quản lý cấu hình nhắc tiền và thông báo tự động qua Zalo (ZBS Template Message).', acts: [U.btn({ label: 'Lưu cấu hình', icon: 'save', cls: 'btn-primary', act: 'save', disabled: !canCfg || ev.p2, title: canCfg ? '' : 'Chỉ Admin cấu hình (FR-ZAL-01)' }), U.btn({ label: 'Gửi thử', icon: 'send', cls: 'btn-outline', act: 'test' }), U.btn({ label: 'Xem đợt gửi', icon: 'history', cls: 'btn-outline', act: 'history' })] })}
    <div class="ev-tiles">${evs.map(e => `<div class="ev-tile ${e.key === ev.key ? 'on' : ''}" data-act="pick" data-k="${e.key}"><div class="row between"><div class="ic">${I(EV_ICON[e.key])}</div>${e.p2 || e.p2on ? TH.phase.tag(2) : ''}</div><b>${esc(e.name)}</b><small>${esc(e.desc)}</small>${U.chip(e.enabled ? 'Đang kích hoạt' : 'Chưa kích hoạt', e.enabled ? 'green' : 'gray', true)}</div>`).join('')}</div>
    <div class="two-col wide"><div class="side-stack"><form id="evf">${U.card({ title: 'Cấu hình sự kiện: ' + esc(ev.name), icon: 'sliders', actions: `<span class="row gap12"><span class="small ${ev.enabled ? 'green' : 'muted'}">${ev.enabled ? 'Đang kích hoạt' : 'Đang tắt'}</span>${(canCfg && !ev.p2) ? U.toggle(ev.enabled, 'toggle') : U.toggle(ev.enabled, '', { style: 'opacity:.45;cursor:not-allowed', title: ev.p2 ? 'Sự kiện Phase 2' : 'Cần vai trò Quản trị viên' })}</span>`, body: ev.p2 ? U.note('warn', 'Sự kiện thuộc Phase 2', 'Nhắc kỳ trả chủ nhà cần chốt thời điểm/kênh/người nhận (OI-03). Không thể kích hoạt trong bản demo Phase 1.') : `<div class="col" style="gap:14px">
        ${U.field({ label: 'Sự kiện', req: true, input: U.input({ name: 'name', value: ev.name, readonly: true, icon: EV_ICON[ev.key] }), help: esc(ev.desc) })}
        ${U.field({ label: 'Điều kiện áp dụng', input: U.select({ name: 'condition', value: ev.condition, options: [ev.condition, 'Tất cả khách thuê có hóa đơn chưa thanh toán', 'Chỉ hóa đơn quá hạn', 'Hợp đồng còn hiệu lực dưới 35 ngày', 'Hồ sơ hoàn cọc ở trạng thái Đã hoàn', 'Toàn bộ cư dân trong phạm vi'].filter((v, i, a) => a.indexOf(v) === i) }), help: 'Áp dụng cho các hóa đơn đến hạn và chưa thanh toán; re-check trước khi gửi (FR-ZAL-02)' })}
        ${U.field({ label: 'Tòa / Phòng', input: U.select({ name: 'buildingId', value: ev.buildingId || '', all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]) }), help: 'Để trống nếu áp dụng cho toàn bộ hệ thống' })}
        <div class="field"><label>Thời điểm gửi<span class="req">*</span></label><div class="row"><input class="inp" type="number" name="offsetDays" value="${ev.offsetDays}" style="width:80px"><select class="inp" name="unit" style="width:auto"><option>ngày</option></select>${U.select({ name: 'offsetDir', value: ev.offsetDir, options: [['before', 'trước ngày đến hạn'], ['after', 'sau sự kiện']], cls: '', attrs: { style: 'width:auto' } })}</div><div class="help">Ví dụ: gửi trước 3 ngày so với ngày đến hạn thanh toán. Lịch chạy hàng ngày 09:00.</div></div>
        <div class="field"><label>Mẫu template Zalo<span class="req">*</span></label><div class="row">${U.select({ name: 'templateId', value: ev.templateId, options: tpls.map(t => [t.id, t.name]), attrs: { 'data-on': 'tpl' } })}${U.btn({ label: 'Xem mẫu', icon: 'pencil', cls: 'btn-outline', act: 'view-tpl' })}</div><div class="help">Nội dung tin nhắn sẽ được cá nhân hóa theo thông tin từng khách</div></div>
        <div class="form-grid">${U.field({ label: 'Kênh chính', req: true, input: U.select({ name: 'channel', value: ev.channel, options: ['Zalo (OA TimoHouse)', 'ZBS Template Message'] }) })}${U.field({ label: 'Kênh fallback', input: U.select({ name: 'fallback', value: 'Không sử dụng', options: [['Không sử dụng', 'Không sử dụng'], ['SMS', TH.phase.on(2) ? 'SMS (mô phỏng – OI-21)' : 'SMS (Phase 2 – OI-21)'], ['Email', TH.phase.on(2) ? 'Email (mô phỏng)' : 'Email (Phase 2)']], attrs: { 'data-on': 'fb' } }), help: 'Nếu gửi qua kênh chính thất bại, sẽ thử kênh này. Phase 1 chưa chốt phương án fallback.' })}</div>
        ${U.field({ label: 'Người nhận', req: true, input: U.select({ name: 'recipient', value: ev.recipient, options: ['Khách thuê (người đại diện hợp đồng)', 'Khách thuê + thành viên ở', 'Quản lý tòa'] }), help: 'Có thể chọn thêm người nhận khác' })}
        ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: ev.note || '', placeholder: 'Nhập ghi chú (tùy chọn)...', attrs: { maxlength: 500 } }), help: '<span id="note-cnt">' + (ev.note || '').length + '</span>/500' })}</div>` })}</form>
      ${U.card({ title: 'Các đợt gửi gần đây', icon: 'history', actions: `<a class="link small" href="#/zalo/history">Xem tất cả →</a>`, bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>#</th><th>Thời gian gửi</th><th>Sự kiện</th><th>Phạm vi</th><th class="num">Dự kiến người nhận</th><th class="num">Đã gửi</th><th>Trạng thái</th><th></th></tr></thead><tbody>${recent.map((b, i) => `<tr><td>${i + 1}</td><td>${F.datetime(b.sentAt || b.createdAt)}</td><td>${esc(Q.L.eventName[b.eventKey] || b.eventKey)}</td><td>${esc(b.scopeLabel)}</td><td class="num">${b.plannedCount}</td><td class="num">${b.sentCount}</td><td>${Q.chip('zbatch', b.status)}</td><td>${U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': b.id } })}</td></tr>`).join('')}</tbody></table>` })}</div>
      <aside class="side-stack">${U.card({ title: 'Xem trước nội dung Zalo', icon: 'message', actions: U.btn({ label: 'Thay đổi mẫu', icon: 'upload', size: 'btn-xs', cls: 'btn-outline', act: 'edit-tpl' }), body: `<div id="prev">${U.phone(Q.renderTemplate(tpl.body || '', Q.templateCtx(sampleInv, sampleT, { end: F.addDays(F.today(), 12), paidDate: F.today() })))}</div>` })}
      ${U.card({ title: 'Hướng dẫn', icon: 'info', body: `<ol class="small" style="padding-left:18px;line-height:1.8"><li>Sử dụng các biến trong mẫu: <code>{ten_khach}</code>, <code>{toa_nha}</code>, <code>{so_phong}</code>, <code>{so_tien}</code>, <code>{ngay_den_han}</code>...</li><li>Tin nhắn sẽ được cá nhân hóa theo từng khách thuê.</li><li>Nên gửi trước 2-5 ngày để khách có thời gian chuẩn bị.</li><li>Có thể gửi thử để kiểm tra nội dung trước khi kích hoạt.</li></ol><a class="link small" href="#/coming-soon/zalo-advanced">Xem thêm hướng dẫn →</a>` })}${TH.phase.on(2) && TH.pages.zaloPolicyCard ? TH.pages.zaloPolicyCard() : ''}</aside></div>`;
    const form = root.querySelector('#evf');
    const renderPrev = () => { const tid = form.querySelector('select[name=templateId]'); const t = Q.template(tid ? tid.value : ev.templateId); root.querySelector('#prev').innerHTML = U.phone(Q.renderTemplate(t.body || '', Q.templateCtx(sampleInv, sampleT, { end: F.addDays(F.today(), 12), paidDate: F.today() }))); };
    form.addEventListener('input', (e) => { if (e.target.name === 'note') root.querySelector('#note-cnt').textContent = e.target.value.length; });
    U.onChange(root, { tpl: renderPrev, fb: (el) => { if (el.value !== 'Không sử dụng' && !TH.phase.on(2)) { U.p2Toast('Kênh fallback ' + el.value); el.value = 'Không sử dụng'; } else if (el.value !== 'Không sử dụng') U.toast('info', 'Fallback ' + el.value + ' (mô phỏng – OI-21)', 'Bật trong Chính sách retry để tự gửi SMS khi lỗi vĩnh viễn'); } });
    U.bind(root, {
      pick: (el) => { TH.router.replaceQuery({ ev: el.dataset.k }); TH.router.refresh(); }, history: () => TH.go('#/zalo/history'), view: (b) => TH.go('#/zalo/batches/' + b.dataset.id), test: () => { if (ev.p2) return U.p2Toast('Gửi thử sự kiện ' + ev.name); Fm.zaloTest(ev.key); },
      toggle: () => { try { X.toggleZaloEvent(ev.id, !ev.enabled); U.toast('ok', (ev.enabled ? 'Đã bật' : 'Đã tắt') + ' rule ' + ev.name, ev.enabled ? 'Lịch hàng ngày sẽ tạo đợt gửi khi đủ điều kiện' : 'Rule tắt không sinh đợt gửi mới (FR-ZAL-01)'); } catch (e) { U.toast('err', 'Không đổi được', e.message); } },
      save: () => { try { const d = U.formData(form); X.saveZaloEvent({ id: ev.id, condition: d.condition, buildingId: d.buildingId, offsetDays: Number(d.offsetDays), offsetDir: d.offsetDir, templateId: d.templateId, channel: d.channel, fallback: TH.phase.on(2) ? d.fallback : 'Không sử dụng', recipient: d.recipient, note: d.note }); U.toast('ok', 'Đã lưu cấu hình ' + ev.name); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      'view-tpl': () => { const tid = form.querySelector('select[name=templateId]'); Fm.template(Q.template(tid ? tid.value : ev.templateId)); }, 'edit-tpl': () => Fm.template(tpl),
    });
  }, { menu: 'zalo-config', permission: 'zalo.config', noAutoRefresh: 'timer' });

  /* ---------- Tạo đợt gửi ---------- */
  const ZSTEPS = [{ title: 'Chọn nguồn dữ liệu', sub: 'Chọn đối tượng cần gửi' }, { title: 'Chọn mẫu thông báo', sub: 'Lựa chọn nội dung mẫu' }, { title: 'Preview người nhận', sub: 'Kiểm tra và chọn danh sách' }, { title: 'Xác nhận & gửi', sub: 'Hoàn tất và gửi thông báo' }];
  TH.router.register('/zalo/batches/new', (root, p, q) => {
    TH.router.crumb([{ label: 'Thông báo' }, { label: 'Thông báo Zalo', href: '#/zalo/history' }, { label: 'Tạo đợt gửi' }]);
    const src = SOURCES.find(s => s[0] === q.src) || null; const step = (Number(q.step || 1) >= 3 && !src) ? 1 : Number(q.step || 1); const buildingId = q.buildingId || ''; const onlyOk = q.only !== '0'; const sendMode = q.mode || 'now';
    const tpls = src ? St.where('zaloTemplates', t => t.eventKey === src[3] || (src[3] === 'debt' && t.eventKey === 'reminder')) : St.all('zaloTemplates');
    const templateId = q.tpl || (tpls[0] ? tpls[0].id : '');
    const go = (extra) => { TH.router.replaceQuery(Object.assign({ step, src: src ? src[0] : '', buildingId, tpl: templateId, only: onlyOk ? '1' : '0', mode: sendMode }, extra)); TH.router.refresh(); };
    let recips = src ? (TH._zRecips && TH._zRecipsKey === src[0] + buildingId ? TH._zRecips : X.buildRecipients(src[0], { buildingId, period: St.state.meta.period })) : [];
    TH._zRecips = recips; TH._zRecipsKey = src ? src[0] + buildingId : '';
    const ok = recips.filter(r => r.elig === 'ok'), skip = recips.filter(r => r.elig === 'skip'), errs = recips.filter(r => r.elig === 'error'); const selected = ok.filter(r => r.selected !== false);
    const tpl = Q.template(templateId); const first = ok[0] || recips[0];
    const preview = first ? U.phone(Q.renderTemplate(tpl.body || '', Q.templateCtx(first.invoiceId ? St.get('invoices', first.invoiceId) : null, Q.tenant(first.tenantId), { room: Q.room(first.roomId), buildingId: first.buildingId, amount: first.amount, due: first.due, end: first.contractId ? Q.contract(first.contractId).end : null, paidDate: first.refundId ? (St.get('refunds', first.refundId) || {}).paidDate : null }))) : U.empty({ title: 'Chưa có người nhận' });
    let main = '';
    if (step === 1) main = U.card({ title: 'Bước 1 – Chọn nguồn dữ liệu', icon: 'database', sub: 'Đối tượng nhận được xác định từ nghiệp vụ (hóa đơn, hợp đồng, hoàn cọc) và re-check trước khi gửi', body: `<div class="grid grid-2">${SOURCES.map(s => `<div class="radio-card ${src && src[0] === s[0] ? 'on' : ''}" data-act="src" data-k="${s[0]}"><div class="ic" style="background:var(--${s[5]}-bg);color:var(--${s[5]})">${I(s[4])}</div><div><b>${s[1]}</b><span>${s[2]}</span></div><span class="dot"></span></div>`).join('')}</div><div class="form-grid mt16">${U.field({ label: 'Phạm vi tòa', input: U.select({ name: 'buildingId', value: buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'b' } }) })}${U.field({ label: 'Kỳ áp dụng', input: U.input({ name: 'period', value: F.periodLabel(St.state.meta.period), readonly: true }) })}</div>` }) + `<div class="wz-foot"><span></span>${U.btn({ label: 'Tiếp tục chọn mẫu →', cls: 'btn-primary', act: 'to2', disabled: !src })}</div>`;
    if (step === 2) main = U.card({ title: 'Bước 2 – Chọn mẫu thông báo', icon: 'message', body: `<div class="col gap12">${tpls.map(t => `<label class="radio-card ${t.id === templateId ? 'on' : ''}" style="align-items:center"><input type="radio" name="tpl" value="${t.id}" ${t.id === templateId ? 'checked' : ''} hidden data-on="tpl"><div class="ic" style="background:var(--blue-bg);color:var(--blue)">${I('message')}</div><div><b>${esc(t.name)}</b><span class="mono xs">${esc(t.code)} · ${esc(Q.L.eventName[t.eventKey] || t.eventKey)}</span></div><span class="dot"></span></label>`).join('')}</div><div class="row mt12">${U.btn({ label: 'Tạo mẫu mới', icon: 'plus', cls: 'btn-outline', size: 'btn-sm', act: 'new-tpl', disabled: !TH.auth.can('zaloConfig') })}${U.btn({ label: 'Xem/sửa mẫu đang chọn', icon: 'pencil', cls: 'btn-outline', size: 'btn-sm', act: 'edit-tpl' })}</div>` }) + `<div class="wz-foot">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: 'to1' })}${U.btn({ label: 'Tiếp tục preview →', cls: 'btn-primary', act: 'to3', disabled: !templateId })}</div>`;
    if (step >= 3) main = `${U.card({ cls: 'mb16', body: `<div class="row between"><div class="row gap12"><div class="ic" style="width:44px;height:44px;border-radius:10px;background:var(--${src[5]}-bg);color:var(--${src[5]});display:grid;place-items:center;font-size:20px">${I(src[4])}</div><div><div class="xs muted">Nguồn dữ liệu đã chọn</div><b style="font-size:15px;color:var(--text)">${src[1]}</b><div class="xs muted">${src[2]}${buildingId ? ' · ' + esc(Q.building(buildingId).name) : ''}</div></div></div>${U.btn({ label: 'Thay đổi', cls: 'btn-outline', size: 'btn-sm', act: 'to1' })}</div>` })}
      <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng người nhận', value: recips.length, cap: 'Từ nguồn dữ liệu đã chọn', icon: 'users', tone: 'blue' })}${U.kpi({ label: 'Đủ điều kiện gửi', value: ok.length, cap: 'SĐT/Zalo hợp lệ, có quyền nhận', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Bỏ qua', value: skip.length, cap: 'Đã gửi gần đây hoặc đã trả đủ', icon: 'minus-circle', tone: 'amber' })}${U.kpi({ label: 'Có lỗi dữ liệu', value: errs.length, cap: 'Thiếu SĐT hoặc thông tin', icon: 'x-circle', tone: 'red' })}</div>
      ${U.card({ title: `Danh sách người nhận <span class="muted" style="font-weight:400">(${recips.length} khách thuê)</span>`, actions: U.check({ name: 'only', label: 'Chỉ hiển thị người đủ điều kiện gửi', checked: onlyOk, attrs: { 'data-on': 'only' } }) + U.btn({ label: 'Tùy chỉnh cột', icon: 'columns', size: 'btn-sm', cls: 'btn-outline', p2: true, act: 'cols-p2' }), body: null, id: 'rt', attrs: 'data-guide="zalo-recipients"' })}
      <div class="wz-foot">${U.btn({ label: '← Quay lại', cls: 'btn-ghost', act: 'to2' })}<div class="row">${U.btn({ label: 'Lưu nháp', icon: 'save', cls: 'btn-outline', act: 'draft' })}${U.btn({ label: 'Xác nhận gửi', icon: 'send', cls: 'btn-primary', act: 'send', disabled: !selected.length, attrs: { 'data-guide': 'zalo-send' } })}</div></div>`;
    const side = `<aside class="side-stack">${U.card({ title: 'Xem trước mẫu thông báo', icon: 'message', body: preview })}${step >= 3 ? U.card({ title: 'Tóm tắt đợt gửi', icon: 'clipboard-check', actions: `<a class="link small" data-act="to2">${I('pencil')} Chỉnh sửa</a>`, body: U.kv([['Nguồn dữ liệu', `<span class="blue">${src ? src[1] : '-'}</span>`], ['Mẫu thông báo', esc(tpl.name || '-')], ['Tổng người nhận', recips.length + ' khách thuê'], ['Đủ điều kiện gửi', `<span class="green">${ok.length} người</span>`], ['Đã chọn gửi', `<b>${selected.length} người</b>`], ['Bỏ qua', `<span class="amber">${skip.length} người</span>`], ['Có lỗi dữ liệu', `<span class="red">${errs.length} người</span>`], ['Thời gian gửi', `${I('clock')} <b>${sendMode === 'now' ? 'Gửi ngay' : 'Hẹn 09:00 ngày mai'}</b> <a class="link" data-act="mode">Thay đổi</a>`]], 'one') }) : ''}</aside>`;
    root.innerHTML = `${U.pageHead({ title: 'Tạo đợt gửi thông báo', sub: 'Tạo và gửi thông báo tự động qua Zalo đến khách thuê, khách hàng của TimoHouse.' })}${U.wizard(ZSTEPS, step - 1)}<div class="two-col wide"><div>${main}</div>${side}</div>`;
    if (step >= 3) U.table(root.querySelector('#rt'), { rows: recips.filter(r => !onlyOk || r.elig === 'ok'), selectable: true, selectableIf: r => r.elig === 'ok', rowKey: r => r.tenantId + '|' + (r.invoiceId || r.contractId || r.refundId || ''), unit: 'người', pageSize: 10, onRender: (c) => { c.querySelectorAll('input[data-act=tsel]').forEach(chk => { const r = recips.find(x => x.tenantId + '|' + (x.invoiceId || x.contractId || x.refundId || '') === chk.dataset.k); if (r && r.elig === 'ok') chk.checked = r.selected !== false; }); }, onSelect: () => { }, cols: [
      { key: 'n', label: '#', render: (r, i) => i + 1, width: '40px' }, { key: 'room', label: 'Phòng', render: r => `<b>${esc(Q.room(r.roomId).code || '-')}</b>` }, { key: 't', label: 'Khách thuê', render: r => esc(Q.tenant(r.tenantId).name) }, { key: 'ph', label: 'SĐT / Zalo', render: r => `<span class="blue">${esc(Q.tenant(r.tenantId).phone || '-')}</span>` },
      { key: 'amt', label: 'Số tiền nợ', num: true, render: r => r.amount ? F.vnd(r.amount) : '-' }, { key: 'st', label: 'Trạng thái', render: r => U.chip(r.elig === 'ok' ? 'Đủ điều kiện' : r.elig === 'skip' ? 'Bỏ qua' : 'Lỗi dữ liệu', r.elig === 'ok' ? 'green' : r.elig === 'skip' ? 'amber' : 'red') }, { key: 'reason', label: 'Ghi chú', render: r => esc(r.reason) }] });
    root.addEventListener('change', (e) => { if (e.target.matches('input[data-act=tsel]')) { const r = recips.find(x => x.tenantId + '|' + (x.invoiceId || x.contractId || x.refundId || '') === e.target.dataset.k); if (r) r.selected = e.target.checked; const sel = recips.filter(x => x.elig === 'ok' && x.selected !== false).length; const btn = root.querySelector('[data-act=send]'); if (btn) btn.disabled = !sel; } if (e.target.matches('input[data-act=tsel-all]')) { recips.forEach(r => { if (r.elig === 'ok') r.selected = e.target.checked; }); } });
    U.onChange(root, { b: (el) => go({ buildingId: el.value }), tpl: (el) => go({ tpl: el.value }), only: (el) => go({ only: el.checked ? '1' : '0' }) });
    U.bind(root, {
      src: (el) => { TH._zRecips = null; go({ src: el.dataset.k, tpl: '' }); }, to1: () => go({ step: 1 }), to2: () => go({ step: 2 }), to3: () => go({ step: 3 }), mode: () => go({ mode: sendMode === 'now' ? 'later' : 'now' }),
      'new-tpl': () => Fm.template({}, src ? src[3] : 'reminder'), 'edit-tpl': () => Fm.template(tpl),
      draft: () => { try { const b = X.createZaloBatch({ name: src[1] + ' ' + F.date(F.today()), eventKey: src[3], sourceKey: src[0], templateId, recipients: recips, sendMode: 'later', scopeLabel: buildingId ? Q.building(buildingId).name : 'Tất cả tòa nhà', period: St.state.meta.period, key: F.uid('zb') }); b.status = 'draft'; St.save(); U.toast('ok', 'Đã lưu nháp đợt gửi ' + b.code); TH._zRecips = null; TH.go('#/zalo/batches/' + b.id); } catch (e) { U.toast('err', 'Không lưu được', e.message); } },
      send: async () => { if (await U.confirm({ title: 'Xác nhận gửi ' + selected.length + ' tin Zalo?', text: 'Hệ thống re-check công nợ ngay trước khi gửi; khách đã trả đủ sẽ bị bỏ qua (FR-ZAL-02). Mỗi khách nhận tối đa 1 tin / kỳ.', ok: 'Gửi ngay' })) { try { const b = X.createZaloBatch({ name: src[1] + ' ' + F.date(F.today()), eventKey: src[3], sourceKey: src[0], templateId, recipients: recips, sendMode, sendAt: sendMode === 'later' ? F.addDays(F.today(), 1) + 'T09:00' : null, scopeLabel: buildingId ? Q.building(buildingId).name : 'Tất cả tòa nhà', period: St.state.meta.period, key: F.uid('zb') }); U.toast('ok', 'Đã tạo đợt gửi ' + b.code, sendMode === 'now' ? 'Đang gửi… theo dõi tiến độ ở chi tiết đợt' : 'Đã hẹn giờ gửi'); TH._zRecips = null; TH.go('#/zalo/batches/' + b.id); } catch (e) { U.toast('err', 'Không gửi được', e.message); } } },
    });
  }, { menu: 'zalo-new', permission: 'zalo.send', noAutoRefresh: true });

  /* ---------- Chi tiết đợt gửi ---------- */
  TH.router.register('/zalo/batches/:id', (root, p, q) => {
    const b = St.get('zaloBatches', p.id); if (!b) { root.innerHTML = U.empty({ title: 'Không tìm thấy đợt gửi' }); return; }
    TH.router.crumb([{ label: 'Thông báo' }, { label: 'Thông báo Zalo', href: '#/zalo/history' }, { label: 'Đợt gửi' }, { label: b.code }]);
    const msgs = Q.batchMessages(b.id); const c = Q.batchCounts(b.id); const tpl = Q.template(b.templateId); const legacy = !msgs.length && b.source === 'seed'; if (legacy) { c.delivered = b.sentCount || 0; c.failed = b.failedCount || 0; c.total = b.plannedCount || 0; } const total = msgs.length ? c.total : (b.plannedCount || 0); const processed = c.delivered + c.failed + c.unknown + c.skipped; const pct = total ? Math.round(processed / total * 100) : 100;
    const f = { s: q.s || '', st: q.st || '', buildingId: q.buildingId || '' };
    const rows = msgs.filter(m => (!f.st || m.status === f.st) && (!f.buildingId || m.buildingId === f.buildingId) && (!f.s || F.norm(Q.tenant(m.tenantId).name + ' ' + (m.phone || '') + ' ' + ((St.get('invoices', m.invoiceId) || {}).code || '')).includes(F.norm(f.s)))).sort((a, z) => F.cmp(a.status, z.status));
    const retryable = msgs.filter(m => ['failed', 'unknown'].includes(m.status) && !m.retried && !St.one('zaloMessages', x => x.retryOfId === m.id)).length;
    root.innerHTML = `${U.pageHead({ back: '#/zalo/history', title: 'Chi tiết đợt gửi ' + (Q.L.eventName[b.eventKey] || '').toLowerCase().replace('nhắc tiền phòng', 'nhắc tiền'), chips: ' ' + Q.chip('zbatch', b.status, 'lg'), sub: `Mã đợt gửi: <b>${esc(b.code)}</b> &nbsp;|&nbsp; Tạo lúc: <b>${F.datetime(b.createdAt)}</b> &nbsp;|&nbsp; Bởi: <a class="link">${esc(Q.userName(b.createdBy))}</a>`, acts: [U.btn({ label: 'Thử lại các tin đủ điều kiện' + (retryable ? ' (' + retryable + ')' : ''), icon: 'refresh', cls: 'btn-outline', act: 'retry', disabled: !retryable, attrs: { 'data-guide': 'zalo-retry' } }), b.status === 'draft' || b.status === 'scheduled' ? U.btn({ label: 'Gửi ngay', icon: 'send', cls: 'btn-primary', act: 'start' }) : '', U.btn({ label: 'Xem lịch sử', icon: 'history', cls: 'btn-outline', act: 'history' }), U.btn({ label: 'Xuất kết quả', icon: 'download', cls: 'btn-primary', act: 'export' })] })}
    ${U.card({ title: 'Thông tin đợt gửi', icon: 'info', cls: 'mb16', body: `<div class="grid grid-7" style="gap:14px">${[['Sự kiện', I('calendar') + ' <b>' + esc(b.name) + '</b>', esc(Q.L.eventName[b.eventKey] || '')], ['Kênh', '<b>Zalo</b>', 'Gửi qua Zalo OA / ZBS'], ['Kỳ', I('calendar') + ' <b>' + F.periodLabel(b.period) + '</b>', 'Hóa đơn đến hạn trong kỳ'], ['Số hóa đơn', '<b>' + msgs.filter(m => m.invoiceId).length + '</b>', 'Hóa đơn cần nhắc'], ['Số người nhận', '<b>' + new Set(msgs.map(m => m.tenantId)).size + '</b>', 'Khách thuê (Số điện thoại)'], ['Số tin dự kiến', '<b>' + total + '</b>', 'Tin nhắn'], ['Trạng thái đợt gửi', Q.chip('zbatch', b.status), b.startedAt ? 'Bắt đầu lúc ' + F.datetime(b.startedAt) : (b.sendAt ? 'Hẹn ' + F.datetime(b.sendAt) : 'Chưa gửi')]].map(([k, v, s]) => `<div><div class="xs muted">${k}</div><div class="mt4">${v}</div><div class="xs muted">${s}</div></div>`).join('')}</div>` })}
    ${U.card({ title: 'Tiến độ gửi tin', icon: 'activity', cls: 'mb16', actions: `<span class="small muted">Đã xử lý ${processed}/${total} tin (${pct}%)</span>`, body: `<div class="progress mb16"><i style="width:${pct}%"></i></div><div class="grid grid-7">${[['queued', 'clock', 'amber'], ['sending', 'send', 'blue'], ['accepted', 'check', 'teal'], ['delivered', 'check-circle', 'green'], ['failed', 'x-circle', 'red'], ['unknown', 'help-circle', 'purple'], ['skipped', 'minus-circle', 'gray']].map(([k, ic, tone]) => `<div class="stat-tile row gap12" style="cursor:pointer" data-act="fst" data-k="${k}"><div class="ic ${tone}" style="width:34px;height:34px;border-radius:9px;display:grid;place-items:center;background:var(--${tone}-bg);color:var(--${tone})">${I(ic)}</div><div><div class="lb">${Q.label('zmsg', k)}</div><div class="vl">${c[k]}</div><div class="cap">${total ? Math.round(c[k] / total * 1000) / 10 : 0}%</div></div></div>`).join('')}</div>` })}
    ${U.card({ title: 'Cấu hình đợt gửi', icon: 'sliders', cls: 'mb16', body: `<div class="grid grid-5" style="gap:14px">${[['Phạm vi gửi', `<b>${esc(b.scopeLabel)}</b>`, 'Loại trừ: khách đã thanh toán đủ, khách đang chấm dứt hợp đồng'], ['Quy tắc gửi', '<b>Gửi cho hóa đơn còn nợ > 0</b>', esc(b.rules || '')], ['Template sử dụng', `<b class="mono">${esc(tpl.code || '-')}</b>`, `<a class="link" data-act="tpl">Xem nội dung template</a>`], ['Người tạo', `<b>${esc(Q.userName(b.createdBy))}</b>`, TH.auth.ROLE_LABEL[Q.user(b.createdBy).role] || ''], ['Thời gian tạo', `<b>${F.datetime(b.createdAt)}</b>`, b.finishedAt ? 'Kết thúc ' + F.datetime(b.finishedAt) : '']].map(([k, v, s]) => `<div><div class="xs muted">${k}</div><div class="mt4">${v}</div><div class="xs muted">${s}</div></div>`).join('')}</div>` })}
    ${legacy ? U.note('info', 'Đợt gửi lịch sử', 'Đợt này được nhập từ dữ liệu quá khứ – chỉ có số liệu tổng (' + (b.sentCount || 0) + ' đã giao, ' + (b.failedCount || 0) + ' thất bại), không có chi tiết từng tin nên không thể thử lại.') : ''}
    ${U.card({ title: `Danh sách tin nhắn trong đợt gửi <span class="muted" style="font-weight:400">(${msgs.length})</span>`, actions: `<div class="row">${U.input({ name: 's', value: f.s, placeholder: 'Tìm theo tên, SĐT, mã hóa đơn...', icon: 'search', cls: 'sm', attrs: { id: 'ms', style: 'width:240px' } })}${U.select({ name: 'st', value: f.st, all: 'Tất cả trạng thái', options: Object.entries(Q.L.zmsg).map(([k, v]) => [k, v[0]]), cls: 'sm', attrs: { 'data-on': 'f', style: 'width:auto' } })}${U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', x => !x.stub).map(x => [x.id, x.name]), cls: 'sm', attrs: { 'data-on': 'f', style: 'width:auto' } })}${U.btn({ label: 'Làm mới', icon: 'refresh', size: 'btn-sm', cls: 'btn-light', act: 'reload' })}</div>`, body: null, id: 'mt' })}`;
    U.table(root.querySelector('#mt'), { rows, unit: 'tin', cols: [
      { key: 'n', label: '#', render: (m, i) => i + 1, width: '40px' }, { key: 't', label: 'Người nhận', render: m => U.cell2(`<b>${esc(Q.tenant(m.tenantId).name)}</b>`, esc(m.phone || Q.tenant(m.tenantId).phone)) }, { key: 'room', label: 'Phòng / Tòa', render: m => U.cell2(esc(Q.room(m.roomId).code || '-'), esc(Q.building(m.buildingId).name || '')) },
      { key: 'inv', label: 'Hóa đơn', render: m => m.invoiceId ? U.link('#/invoices/' + m.invoiceId, (St.get('invoices', m.invoiceId) || {}).code || '-') : (m.contractId ? U.link('#/contracts/' + m.contractId, Q.contract(m.contractId).code || '-') : '-') }, { key: 'ch', label: 'Kênh', render: () => 'Zalo' }, { key: 'tp', label: 'Template', render: m => `<span class="mono xs">${esc(m.templateCode)}</span>` },
      { key: 'status', label: 'Trạng thái giao', sortable: true, render: m => Q.chip('zmsg', m.status) + (m.retryOfId ? ' <span class="xs muted">lần ' + m.attempt + '</span>' : '') + (m.retried ? ' <span class="xs muted">đã thử lại</span>' : '') }, { key: 'err', label: 'Mã lỗi', render: m => m.errorCode ? `<span class="red bold">${esc(m.errorCode)}</span>` : (m.skipReason ? `<span class="xs muted">${esc(m.skipReason)}</span>` : '-') },
      { key: 'debt', label: 'Còn nợ hiện tại', num: true, render: m => m.invoiceId ? F.vnd(Q.invRemaining(St.get('invoices', m.invoiceId) || { total: 0 })) : '-' },
      { key: 'actions', label: 'Thao tác', render: m => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem', act: 'view', attrs: { 'data-id': m.id } }), U.moreBtn(m.id)]) }] });
    U.onChange(root, { f: () => { const st = root.querySelector('select[name=st]').value, bId = root.querySelector('select[name=buildingId]').value; TH.router.replaceQuery({ s: root.querySelector('#ms').value, st, buildingId: bId }); TH.router.refresh(); } });
    root.querySelector('#ms').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    root.querySelector('#ms').addEventListener('input', e => TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })));
    root.querySelector('#ms').addEventListener('focus', () => { TH._msFocus = true; }); root.querySelector('#ms').addEventListener('blur', () => { TH._msFocus = false; });
    if (TH._msFocus) { const el = root.querySelector('#ms'); el.focus(); el.setSelectionRange(el.value.length, el.value.length); }
    const showMsg = (m) => U.modal({ title: 'Tin nhắn tới ' + Q.tenant(m.tenantId).name, sub: Q.label('zmsg', m.status) + (m.errorCode ? ' · ' + m.errorCode + ' (' + (m.errorCode === 'ZLM-1001' ? 'SĐT không hợp lệ / không có Zalo' : m.errorCode === 'ZLM-2003' ? 'Khách chặn tin OA' : 'Lỗi nhà cung cấp') + ')' : ''), body: U.phone(m.content || Q.renderTemplate(tpl.body || '', Q.templateCtx(m.invoiceId ? St.get('invoices', m.invoiceId) : null, Q.tenant(m.tenantId), { room: Q.room(m.roomId), buildingId: m.buildingId })), m.sentAt ? F.datetime(m.sentAt) : 'Chưa gửi') + U.note('info', '', 'Gửi thành công không phải bằng chứng khách đã thanh toán (FR-ZAL-05).') });
    U.bind(root, {
      history: () => TH.go('#/zalo/history'), reload: () => TH.router.refresh(), fst: (el) => { TH.router.replaceQuery(Object.assign({}, f, { st: f.st === el.dataset.k ? '' : el.dataset.k })); TH.router.refresh(); }, tpl: () => Fm.template(tpl), start: () => { X.startBatch(b.id); U.toast('ok', 'Bắt đầu gửi ' + b.code); }, view: (el) => showMsg(St.get('zaloMessages', el.dataset.id)),
      retry: async () => { if (await U.confirm({ title: 'Thử lại ' + retryable + ' tin đủ điều kiện?', text: 'Chỉ tin Thất bại / Chưa rõ kết quả chưa được thử lại. Không gửi lại người đã nhận thành công (FR-ZAL-04).', ok: 'Thử lại' })) { try { const n = X.retryBatch(b.id); U.toast('ok', 'Đã xếp hàng thử lại ' + n + ' tin'); } catch (e) { U.toast('err', 'Không thử lại được', e.message); } } },
      export: () => { F.download(b.code + '-ket-qua.csv', F.csv(msgs.map(m => [Q.tenant(m.tenantId).name, m.phone, Q.room(m.roomId).code, (St.get('invoices', m.invoiceId) || {}).code || '', Q.label('zmsg', m.status), m.errorCode || '', m.sentAt || '']), ['Khách', 'SĐT', 'Phòng', 'Hóa đơn', 'Trạng thái', 'Mã lỗi', 'Thời gian']), 'text/csv'); U.toast('ok', 'Đã xuất kết quả'); },
      more: (el) => { const m = St.get('zaloMessages', el.dataset.id); U.menu(el, [{ label: 'Xem nội dung đã gửi', icon: 'message', onClick: () => showMsg(m) }, { label: 'Thử lại tin này', icon: 'refresh', disabled: !['failed', 'unknown'].includes(m.status) || !!St.one('zaloMessages', x => x.retryOfId === m.id), onClick: () => { X.retryMessage(m.id); U.toast('ok', 'Đã xếp hàng thử lại'); } }, m.invoiceId ? { label: 'Mở hóa đơn', icon: 'receipt', onClick: () => TH.go('#/invoices/' + m.invoiceId) } : { label: 'Mở khách thuê', icon: 'user', onClick: () => TH.go('#/tenants/' + m.tenantId) }, { label: 'Xem hội thoại Zalo', icon: 'message', p2: true, onClick: () => TH.pages.zaloThread && TH.pages.zaloThread(m) }]); },
    });
  }, { menu: 'zalo-history', permission: 'zalo.view', resource: { type: 'zaloBatch' } });

  /* ---------- Lịch sử gửi ---------- */
  TH.router.register('/zalo/history', (root, p, q) => {
    TH.router.crumb([{ label: 'Thông báo' }, { label: 'Thông báo Zalo' }, { label: 'Lịch sử gửi' }]);
    const period = q.period !== undefined && q.period !== 'all' ? q.period : ''; const f = { s: q.s || '', period, type: q.type || '', status: q.status || '', channel: q.channel || '', buildingId: q.buildingId || '', createdBy: q.createdBy || '', hasFailed: q.hasFailed || '' };
    const all = St.all('zaloBatches').filter(b => !f.period || F.period(b.createdAt || '') === f.period).sort((a, b) => F.cmp(b.createdAt || '', a.createdAt || ''));
    const rows = all.filter(b => (!f.s || F.norm(b.name + ' ' + b.code).includes(F.norm(f.s))) && (!f.type || b.eventKey === f.type) && (!f.status || b.status === f.status) && (!f.buildingId || b.scopeLabel === Q.building(f.buildingId).name) && (!f.createdBy || b.createdBy === f.createdBy) && (!f.hasFailed || Q.batchMessages(b.id).some(m => m.status === 'failed' && !m.retried)));
    const cnt = (s) => all.filter(b => b.status === s).length; const proc = all.filter(b => ['sending', 'scheduled', 'draft'].includes(b.status)).length;
    const errs = all.filter(b => b.failedCount > 0 && b.errors).slice(0, 5);
    root.innerHTML = `${U.pageHead({ title: 'Lịch sử gửi thông báo', sub: 'Theo dõi lịch sử các đợt gửi thông báo qua Zalo đến khách hàng một cách chi tiết.', acts: [U.btn({ label: 'Tạo đợt gửi', icon: 'plus', cls: 'btn-primary', act: 'new' }), U.btn({ label: 'Xuất lịch sử', icon: 'download', cls: 'btn-outline', act: 'export' })] })}
    ${U.filterbar([U.field({ label: 'Tìm kiếm', input: U.input({ name: 's', value: f.s, placeholder: 'Nhập tên đợt gửi, nội dung...', icon: 'search', attrs: { 'data-on': 'f' } }), cls: 'wide' }), U.field({ label: 'Thời gian gửi', input: U.select({ name: 'period', value: f.period, all: 'Tất cả', options: [...new Set(St.all('zaloBatches').map(b => F.period(b.createdAt || '')))].filter(Boolean).sort().reverse().map(x => [x, F.periodLabel(x)]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Loại thông báo', input: U.select({ name: 'type', value: f.type, all: 'Tất cả loại', options: Object.entries(Q.L.eventName).filter(([k]) => !['due_soon', 'overdue', 'issued'].includes(k)).map(([k, v]) => [k, v]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Trạng thái gửi', input: U.select({ name: 'status', value: f.status, all: 'Tất cả trạng thái', options: Object.entries(Q.L.zbatch).map(([k, v]) => [k, v[0]]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Kênh gửi', input: U.select({ name: 'channel', value: f.channel, all: 'Tất cả kênh', options: ['Zalo'], attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Tòa nhà', input: U.select({ name: 'buildingId', value: f.buildingId, all: 'Tất cả tòa nhà', options: St.where('buildings', b => !b.stub).map(b => [b.id, b.name]), attrs: { 'data-on': 'f' } }) }), U.field({ label: 'Người tạo', input: U.select({ name: 'createdBy', value: f.createdBy, all: 'Tất cả người tạo', options: [...new Set(St.all('zaloBatches').map(b => b.createdBy))].map(id => [id, Q.userName(id)]), attrs: { 'data-on': 'f' } }) })], U.btn({ label: 'Làm mới', icon: 'refresh', cls: 'btn-light', act: 'reset' }))}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng đợt gửi', value: all.length, cap: f.period ? 'Trong ' + F.periodLabel(f.period).toLowerCase() : 'Tất cả thời gian', icon: 'send', tone: 'blue', delta: 12 })}${U.kpi({ label: 'Thành công', value: cnt('done'), cap: F.pct(cnt('done'), all.length) + '% tổng đợt gửi', icon: 'check-circle', tone: 'green', delta: 18 })}${U.kpi({ label: 'Thất bại', value: cnt('failed'), cap: F.pct(cnt('failed'), all.length) + '% tổng đợt gửi', icon: 'x-circle', tone: 'red', delta: 33, deltaDir: 'down' })}${U.kpi({ label: 'Đang xử lý', value: proc, cap: F.pct(proc, all.length) + '% tổng đợt gửi', icon: 'clock', tone: 'amber', delta: 0, deltaDir: 'up' })}</div>
    ${U.relatedStrip({ id: 'zalo-history-related', cls: 'mb16', items: [
      { key: 'quick-stats', title: 'Thống kê nhanh', icon: 'pie-chart', summary: all.length + ' đợt gửi', meta: cnt('done') + ' thành công · ' + cnt('failed') + ' thất bại', actions: U.select({ name: 'qp', value: f.period, all: 'Tất cả', options: [['2024-10', 'Tháng 10/2024'], ['2024-09', 'Tháng 9/2024']], cls: 'sm', attrs: { style: 'width:auto', 'data-on': 'qp' } }), body: C.donut({ items: [{ label: 'Thành công', value: cnt('done'), color: '#16A34A' }, { label: 'Một phần', value: cnt('partial'), color: '#F59E0B' }, { label: 'Thất bại', value: cnt('failed'), color: '#DC2626' }, { label: 'Đang xử lý', value: proc, color: '#2563EB' }], centerLabel: String(all.length), centerSub: 'đợt gửi' }) + `<div class="legend-list mt12">${[['Thành công', cnt('done'), '#16A34A'], ['Một phần', cnt('partial'), '#F59E0B'], ['Thất bại', cnt('failed'), '#DC2626'], ['Đang xử lý', proc, '#2563EB']].map(([l, v, col]) => `<div class="it" style="align-items:center"><span class="sw" style="width:10px;height:10px;border-radius:3px;background:${col};display:inline-block"></span><span>${l}</span><b class="ml-auto">${v} <span class="muted small">(${F.pct(v, all.length)}%)</span></b></div>`).join('')}</div>` },
      { key: 'recent-errors', title: 'Lỗi gửi gần đây', icon: 'alert-triangle', summary: errs.length + ' lỗi gần đây', meta: errs.length ? 'Cần kiểm tra và xử lý' : 'Không có lỗi gửi', actions: `<a class="link small" href="#/zalo/history?status=failed">Xem tất cả →</a>`, body: errs.length ? `<div class="err-list">${errs.map(b => `<div class="it"><span class="d"></span><div><b>${esc(b.code)}</b><small>${esc(b.errors)}<br>${F.datetime(b.sentAt || b.createdAt)}</small></div></div>`).join('')}</div>` : U.empty({ title: 'Không có lỗi gửi' }) }
    ] })}
    ${U.card({ title: `Danh sách đợt gửi thông báo <span class="muted" style="font-weight:400">(${rows.length} đợt)</span>`, body: null, id: 'tbl-card' })}`;
    const wrap = document.createElement('div'); root.querySelector('#tbl-card').appendChild(wrap);
    U.table(wrap, { rows, selectable: true, unit: 'đợt gửi', cols: [
      { key: 'code', label: 'Mã đợt gửi', sortable: true, render: b => U.link('#/zalo/batches/' + b.id, esc(b.code), 'bold') }, { key: 'name', label: 'Tên đợt gửi', render: b => esc(b.name) }, { key: 'type', label: 'Loại thông báo', render: b => `${I(EV_ICON[b.eventKey] || 'message')} ${esc(Q.L.eventName[b.eventKey] || b.eventKey)}${b.eventKey.startsWith('p2_') || b.phase ? TH.phase.tag(2) : ''}` }, { key: 'aud', label: 'Đối tượng nhận', render: b => esc(b.audience) },
      { key: 'plannedCount', label: 'Số người nhận', num: true, sortable: true }, { key: 'sentCount', label: 'Thành công', num: true, render: b => `<span class="green bold">${b.sentCount}</span>` }, { key: 'failedCount', label: 'Thất bại', num: true, render: b => `<span class="${b.failedCount ? 'red bold' : ''}">${b.failedCount}</span>` },
      { key: 'sentAt', label: 'Thời gian gửi', sortable: true, render: b => F.datetime(b.sentAt || b.createdAt) }, { key: 'by', label: 'Người tạo', render: b => esc(Q.userName(b.createdBy)) }, { key: 'status', label: 'Trạng thái', sortable: true, render: b => Q.chip('zbatch', b.status) },
      { key: 'actions', label: 'Thao tác', render: b => U.rowActions([U.actBtn({ icon: 'eye', label: 'Xem chi tiết', act: 'view', attrs: { 'data-id': b.id } }), U.moreBtn(b.id)]) }] });
    U.onChange(root, { f: () => { const d = U.formData(root.querySelector('.filterbar')); TH.router.replaceQuery(Object.assign({}, f, d)); TH.router.refresh(); }, qp: (el) => { TH.router.replaceQuery(Object.assign({}, f, { period: el.value })); TH.router.refresh(); } });
    root.querySelector('input[name=s]').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.bind(root, { new: () => TH.go('#/zalo/batches/new'), reset: () => { TH.router.replaceQuery({}); TH.router.refresh(); }, view: (b) => TH.go('#/zalo/batches/' + b.dataset.id), export: () => { F.download('lich-su-zalo.csv', F.csv(rows.map(b => [b.code, b.name, Q.L.eventName[b.eventKey] || b.eventKey, b.plannedCount, b.sentCount, b.failedCount, b.sentAt || '', Q.userName(b.createdBy), Q.label('zbatch', b.status)]), ['Mã', 'Tên', 'Loại', 'Người nhận', 'Thành công', 'Thất bại', 'Thời gian', 'Người tạo', 'Trạng thái']), 'text/csv'); U.toast('ok', 'Đã xuất lịch sử'); },
      more: (el) => { const b = St.get('zaloBatches', el.dataset.id); const retryable = Q.batchMessages(b.id).filter(m => ['failed', 'unknown'].includes(m.status) && !St.one('zaloMessages', x => x.retryOfId === m.id)).length; U.menu(el, [{ label: 'Xem chi tiết', icon: 'eye', onClick: () => TH.go('#/zalo/batches/' + b.id) }, { label: 'Thử lại tin lỗi' + (retryable ? ' (' + retryable + ')' : ''), icon: 'refresh', disabled: !retryable, onClick: () => { try { X.retryBatch(b.id); U.toast('ok', 'Đã xếp hàng thử lại'); } catch (e) { U.toast('err', 'Không thử lại được', e.message); } } }, { label: 'Nhân bản đợt gửi', icon: 'copy', disabled: b.eventKey.startsWith('p2_') || (b.phase && !TH.phase.on(2)), onClick: () => TH.go('#/zalo/batches/new?step=3&src=' + (b.sourceKey === 'test' || b.sourceKey === 'manual' ? 'overdue' : (b.sourceKey || 'overdue')) + '&tpl=' + b.templateId) }, { label: 'Xuất kết quả', icon: 'download', onClick: () => TH.go('#/zalo/batches/' + b.id) }]); } });
  }, { menu: 'zalo-history', permission: 'zalo.view' });
})(window.TH);
