/* Phase 2 – Zalo nâng cao: chi tiết lần gửi (provider code, retry 403/408, log, donut lỗi), chính sách retry/fallback SMS, quản lý mẫu, hội thoại */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc, C = TH.chart;
  const ok = (m, s) => U.toast('ok', m, s);
  const recipName = (m) => m.recipientName || (m.tenantId ? Q.tenant(m.tenantId).name : m.leadId ? Q.lead(m.leadId).name : m.landlordId ? (St.get('landlords', m.landlordId) || {}).name : '') || '-';
  const sendChip = (m) => { const c = Q.providerOf(m); if (m.status === 'delivered' || m.status === 'accepted') return U.chip('Thành công', 'green'); if (m.status === 'failed') return Q.msgRetryWait(m) ? U.chip('Đang chờ retry', 'amber') : U.chip(c === '300' ? 'Lỗi số Zalo' : c === '403' ? 'Từ chối mẫu' : 'Thất bại', 'red'); if (m.status === 'skipped') return U.chip('Bỏ qua', 'gray'); if (m.status === 'unknown') return U.chip('Chưa rõ', 'purple'); return U.chip(Q.label('zmsg', m.status), 'blue'); };
  const provCell = (m) => { const c = Q.providerOf(m); return c ? `<span class="${c === '200' ? 'green' : 'red'}">${c} - ${esc(m.providerMsg || Q.providerMsg(c))}</span>` : '-'; };
  TH.pages.zaloThread = (m) => U.modal({ title: 'Hội thoại Zalo – ' + recipName(m), sub: 'Timeline tin đã gửi cho người nhận (đọc từ zaloMessages)', body: `<div class="timeline compact">${St.where('zaloMessages', x => (m.tenantId && x.tenantId === m.tenantId) || (m.leadId && x.leadId === m.leadId)).sort((a, b) => F.cmp(a.sentAt || a.createdAt, b.sentAt || b.createdAt)).map(x => `<div class="tl-it"><div class="when">${F.datetime(x.sentAt || x.createdAt)}</div><div class="dot ${x.status === 'delivered' ? 'green' : x.status === 'failed' ? 'red' : 'blue'} fill"></div><div><b>${esc((St.get('zaloBatches', x.batchId) || {}).name || '')} · ${esc(x.channel || 'Zalo')}</b><small>${esc((x.content || '').slice(0, 120))}${(x.content || '').length > 120 ? '…' : ''}<br>${Q.label('zmsg', x.status)}${x.providerCode ? ' · ' + x.providerCode : ''}</small></div></div>`).join('') || '<div class="muted small">Chưa có tin</div>'}</div>${U.note('info', '', 'Hội thoại 2 chiều (khách trả lời) thuộc FR-ZAL-06 – mockup chỉ hiển thị tin đã gửi.')}` });
  TH.pages.zaloPolicyCard = () => { const p = St.state.meta.zaloPolicy || {}; const tpls = St.all('zaloTemplates'); return U.card({ title: 'Chính sách retry ' + TH.phase.tag(2), icon: 'refresh-cw', body: `<form id="zpf"><div class="form-grid">${U.field({ label: 'Số lần retry tối đa', input: U.input({ name: 'maxRetry', value: p.maxRetry || 3, type: 'number', attrs: { min: 1, max: 5 } }) })}${U.field({ label: 'Khoảng cách (phút)', input: U.input({ name: 'gapMinutes', value: p.gapMinutes || 15, type: 'number' }) })}</div><div class="field mt8"><label>Nhóm lỗi được retry</label><div class="row gap12 wrap">${[['300', '300 – Số không tồn tại (lỗi vĩnh viễn, không retry)', true], ['403', '403 – Template rejected'], ['408', '408 – Timeout']].map(([c, l, off]) => U.check({ name: 'rc_' + c, label: l, checked: !off && (p.retryCodes || []).includes(c), attrs: off ? { disabled: true } : {} })).join('')}</div></div>${U.check({ name: 'fallbackSms', label: 'Fallback SMS khi lỗi vĩnh viễn (mô phỏng – OI-21, tối đa 1 tin/sự kiện)', checked: !!p.fallbackSms })}<div class="row end mt8">${U.btn({ label: 'Lưu chính sách', icon: 'save', size: 'btn-sm', cls: 'btn-primary', act: 'save-policy', disabled: !TH.auth.can('zaloConfig') })}</div></form>` }) + U.card({ title: 'Quản lý mẫu ' + TH.phase.tag(2), icon: 'file-text', bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Mã mẫu</th><th>Sự kiện</th><th>Biến</th><th>Duyệt mẫu</th><th></th></tr></thead><tbody>${tpls.map(t => `<tr><td class="mono xs">${esc(t.code)}</td><td class="small">${esc(Q.L.eventName[t.eventKey] || t.eventKey)}</td><td class="xs muted">${esc(((t.body || '').match(/\{\w+\}/g) || []).length + ' biến')}</td><td>${U.chip(t.approval === 'rejected' ? 'Bị từ chối' : t.approval === 'pending' ? 'Chờ Zalo duyệt' : 'Đã duyệt', t.approval === 'rejected' ? 'red' : t.approval === 'pending' ? 'amber' : 'green')}</td><td class="tr">${U.iconBtn('eye', 'tpl-view', 'Xem', { 'data-id': t.id })}${U.iconBtn('refresh-cw', 'tpl-appr', 'Gửi duyệt lại mẫu', { 'data-id': t.id })}</td></tr>`).join('')}</tbody></table>` }); };
  document.addEventListener('click', (e) => { const el = e.target.closest('[data-act="save-policy"],[data-act="tpl-view"],[data-act="tpl-appr"]'); if (!el || el.disabled) return; e.preventDefault(); const act = el.dataset.act; if (act === 'save-policy') { const d = U.formData(document.getElementById('zpf')); X.saveZaloPolicy({ maxRetry: d.maxRetry, gapMinutes: d.gapMinutes, retryCodes: ['403', '408'].filter(c => d['rc_' + c]), fallbackSms: d.fallbackSms }); ok('Đã lưu chính sách retry'); } else if (act === 'tpl-view') Fm.template(St.get('zaloTemplates', el.dataset.id)); else { const t = St.get('zaloTemplates', el.dataset.id); X.setTemplateApproval(t.id, t.approval === 'pending' ? 'approved' : 'pending'); ok(t.approval === 'pending' ? 'Zalo đã duyệt mẫu ' + t.code : 'Đã gửi duyệt mẫu ' + t.code, 'Mô phỏng quy trình duyệt template ZNS'); } });
  document.addEventListener('click', (e) => { const el = e.target.closest('[data-act="cols-p2"]'); if (!el || el.disabled) return; e.preventDefault(); U.menu(el, [{ header: 'Tùy chỉnh cột' }, ...['Phòng', 'Hóa đơn', 'Còn nợ', 'Lý do'].map(c => ({ label: '☑ ' + c, onClick: () => U.toast('info', 'Cột "' + c + '"', 'Tùy chỉnh cột người nhận (mô phỏng)') }))]); });

  /* ---- Chi tiết lần gửi nâng cấp (PNG 05/05) ---- */
  const rt = TH.router.routes.find(r => r.pattern === '/zalo/batches/:id'); const p1 = rt && rt.handler;
  const detailP2 = (root, p, q) => {
    const b = St.get('zaloBatches', p.id); if (!b) { root.innerHTML = U.empty({ title: 'Không tìm thấy đợt gửi' }); return; }
    TH.router.crumb([{ label: 'Kinh doanh' }, { label: 'Thông báo Zalo', href: '#/zalo/config' }, { label: 'Lịch sử gửi', href: '#/zalo/history' }, { label: 'Chi tiết' }]);
    const msgs = Q.batchMessages(b.id).filter(m => !m.retried); const tpl = Q.template(b.templateId); const legacy = !msgs.length && b.source === 'seed';
    const total = msgs.length || b.plannedCount || 0; const okN = legacy ? b.sentCount : msgs.filter(m => ['delivered', 'accepted'].includes(m.status)).length; const waitN = msgs.filter(Q.msgRetryWait).length; const failN = legacy ? b.failedCount : msgs.filter(m => (m.status === 'failed' && !Q.msgRetryWait(m)) || m.status === 'unknown').length; const pend = msgs.filter(m => ['queued', 'sending'].includes(m.status)).length;
    const pct = (n) => total ? Math.round(n / total * 1000) / 10 : 0; const f = { s: q.s || '', st: q.st || '' };
    const rows = msgs.filter(m => (!f.st || (f.st === 'ok' ? ['delivered', 'accepted'].includes(m.status) : f.st === 'wait' ? Q.msgRetryWait(m) : f.st === 'fail' ? m.status === 'failed' && !Q.msgRetryWait(m) : m.status === f.st)) && (!f.s || F.norm(recipName(m) + ' ' + (m.phone || '') + ' ' + (Q.room(m.roomId).code || '')).includes(F.norm(f.s)))).sort((a, z) => F.cmp(a.sentAt || '', z.sentAt || ''));
    const pol = St.state.meta.zaloPolicy || { retryCodes: ['403', '408'], maxRetry: 3 }; const retryable = msgs.filter(m => ['failed', 'unknown'].includes(m.status) && !St.one('zaloMessages', x => x.retryOfId === m.id) && (m.status === 'unknown' || (pol.retryCodes.includes(Q.providerOf(m)) && (m.attempt || 1) < pol.maxRetry))).length;
    const ps = Q.batchProviderStats(b.id); const errTotal = ps[300] + ps[403] + ps[408] + ps.other;
    const log = (b.log && b.log.length ? b.log : msgs.filter(m => m.sentAt).slice(0, 5).map((m, i) => ({ at: m.sentAt + ':' + F.pad((i * 7 + 11) % 60), roomId: m.roomId, phone: m.phone, code: Q.providerOf(m), msg: m.providerMsg || Q.providerMsg(Q.providerOf(m)) }))).slice(0, 5);
    const stage = b.status === 'draft' || b.status === 'scheduled' ? 0 : b.status === 'sending' ? 2 : 3;
    root.innerHTML = `${U.pageHead({ title: 'Chi tiết lần gửi thông báo', phase: 2, sub: 'Xem chi tiết kết quả gửi thông báo qua Zalo và trạng thái từng người nhận.', acts: [U.btn({ label: 'Quay lại', icon: 'arrow-left', cls: 'btn-outline', act: 'back' }), U.btn({ label: 'Tải log (.xlsx)', icon: 'download', cls: 'btn-outline', act: 'export', title: 'Bản demo offline xuất CSV' }), b.status === 'draft' || b.status === 'scheduled' ? U.btn({ label: 'Gửi ngay', icon: 'send', cls: 'btn-primary', act: 'start' }) : U.btn({ label: 'Retry bản ghi lỗi' + (retryable ? ' (' + retryable + ')' : ''), icon: 'refresh-cw', cls: 'btn-primary', act: 'retry', disabled: !retryable || !TH.auth.can('zalo.send'), title: retryable ? 'Chỉ retry 403/408 (300 = lỗi vĩnh viễn)' : 'Không có tin đủ điều kiện retry', attrs: { 'data-guide': 'zalo-retry' } })] })}
    ${U.card({ cls: 'mb16', body: `<div class="grid grid-4" style="gap:14px">${[['Mã đợt gửi', `<b style="font-size:15px;color:var(--text)">${esc(b.code)}</b> ${U.iconBtn('copy', 'copy', 'Sao chép', { 'data-v': b.code })}`, ''], ['Tên đợt gửi', `<b>${esc(b.name)}</b> ${U.iconBtn('copy', 'copy', 'Sao chép', { 'data-v': b.name })}`, ''], ['Thời gian gửi', `${I('calendar')} <b>${F.datetime(b.startedAt || b.sentAt || b.createdAt)}${b.finishedAt ? ' - ' + b.finishedAt.slice(11, 16) : ''}</b> ${Q.chip('zbatch', b.status)}`, ''], ['Người tạo', `<div class="row gap12">${U.avatar(Q.userName(b.createdBy))}<div><b>${esc(Q.userName(b.createdBy))}</b><div class="xs muted">${F.datetime(b.createdAt)}</div></div></div>`, ''], ['Template sử dụng', `${I('file-text')} <b>${esc(tpl.name || tpl.code || '-')}</b><div class="mt4"><a class="link small" data-act="tpl">Xem mẫu</a></div>`, ''], ['Đối tượng nhận', `${I('users')} <b>${esc(b.audience || 'Khách thuê')}</b>`, esc(b.scopeLabel || '') + (b.rules ? ', ' + esc(b.rules.split(' · ')[0].toLowerCase()) : '')], ['Nội dung tin nhắn', `${I('message')} <span class="small">${esc((tpl.body || '').slice(0, 90))}…</span><div class="mt4"><a class="link small" data-act="tpl">Xem đầy đủ</a></div>`, ''], ['Ghi chú', esc(b.note || '-'), '']].map(([k, v, s]) => `<div><div class="xs muted">${k}</div><div class="mt4 small">${v}</div>${s ? `<div class="xs muted">${s}</div>` : ''}</div>`).join('')}</div>` })}
    <div class="grid grid-4 mb16">${U.kpi({ label: 'Tổng người nhận', value: total, cap: '100% trong danh sách', icon: 'users', tone: 'blue' })}${U.kpi({ label: 'Đã gửi thành công', value: okN, cap: pct(okN) + '%', icon: 'check-circle', tone: 'green' })}${U.kpi({ label: 'Thất bại', value: failN, cap: pct(failN) + '%', icon: 'x-circle', tone: 'red' })}${U.kpi({ label: 'Đang chờ retry', value: waitN + pend, cap: pct(waitN + pend) + '%', icon: 'clock', tone: 'amber' })}</div>
    ${legacy ? U.note('info', 'Đợt gửi lịch sử', 'Chỉ có số liệu tổng (' + b.sentCount + ' đã giao, ' + b.failedCount + ' thất bại), không có chi tiết từng tin nên không thể thử lại.') + '<div class="mb16"></div>' : ''}
    ${U.relatedStrip({ id: 'batch-related', cls: 'mb16', items: [
      { key: 'progress', title: 'Tiến trình gửi thông báo', icon: 'activity', summary: ['Đã tạo đợt gửi', 'Bắt đầu gửi', 'Đang gửi', 'Hoàn thành gửi'][Math.min(stage, 3)], meta: stage >= 3 ? 'Xong lúc ' + (b.finishedAt || '').slice(11, 16) + ' · ' + okN + ' thành công / ' + failN + ' thất bại' : 'Đang xử lý ' + total + ' người nhận', body: U.timeline([{ when: (b.createdAt || '').slice(11, 16), title: 'Tạo đợt gửi', sub: Q.userName(b.createdBy) + ' tạo đợt gửi ' + b.code, color: 'green', fill: true }, { when: (b.startedAt || b.sentAt || '').slice(11, 16), title: 'Bắt đầu gửi', sub: 'Hệ thống bắt đầu gửi tin nhắn qua Zalo OA', color: stage >= 1 ? 'green' : 'gray', fill: stage >= 1 }, { when: (b.sentAt || '').slice(11, 16), title: 'Đang gửi', sub: 'Đang xử lý ' + total + ' người nhận…', color: stage >= 2 ? (stage === 2 ? 'blue' : 'green') : 'gray', fill: stage >= 2 }, { when: (b.finishedAt || '').slice(11, 16), title: 'Hoàn thành gửi', sub: stage >= 3 ? 'Đã gửi xong tất cả tin nhắn' : 'Chưa hoàn thành', color: stage >= 3 ? 'green' : 'gray', fill: stage >= 3 }]) },
      { key: 'log', title: 'Log phản hồi từ Zalo', icon: 'file-text', summary: log.length + ' dòng log', meta: log.length ? 'Gần nhất ' + esc((log[0].at || '').slice(11)) + ' · ' + esc(log[0].code) + ' ' + esc(log[0].msg) : 'Chưa có phản hồi', actions: '<a class="link small" data-act="log-all">Xem tất cả →</a>', body: `<div class="tbl-wrap"><table class="tbl compact pill-log"><thead><tr><th>Thời gian</th><th>Phòng</th><th>SĐT/Zalo</th><th>Phản hồi</th><th>Mô tả</th></tr></thead><tbody>${log.map(l => `<tr><td>${esc((l.at || '').slice(11))}</td><td class="blue">${esc(Q.room(l.roomId).code || '-')}</td><td>${esc(l.phone || '')}</td><td class="${l.code === '200' ? 'green' : 'red'} bold">${esc(l.code)}</td><td>${esc(l.msg)}</td></tr>`).join('') || '<tr><td colspan="5" class="muted tc">Chưa có log</td></tr>'}</tbody></table></div>` },
      { key: 'errors', title: 'Thống kê lỗi', icon: 'pie-chart', summary: errTotal + ' lỗi (' + pct(errTotal) + '%)', meta: errTotal ? 'Zalo không tồn tại ' + ps[300] + ' · Template ' + ps[403] + ' · Timeout ' + ps[408] + ' · Khác ' + ps.other : 'Không có lỗi', actions: '<a class="link small" data-act="fst" data-k="fail">Xem chi tiết →</a>', body: C.donutLegend([{ label: 'Số Zalo không tồn tại', value: ps[300], color: '#DC2626', text: ps[300] + ' (' + F.pct(ps[300], errTotal) + '%)' }, { label: 'Template bị từ chối', value: ps[403], color: '#F97316', text: ps[403] + ' (' + F.pct(ps[403], errTotal) + '%)' }, { label: 'Timeout', value: ps[408], color: '#F59E0B', text: ps[408] + ' (' + F.pct(ps[408], errTotal) + '%)' }, { label: 'Khác', value: ps.other, color: '#94A3B8', text: ps.other + ' (' + F.pct(ps.other, errTotal) + '%)' }], 130, errTotal + ' lỗi', '(' + pct(errTotal) + '%)') }
    ] })}
    ${U.card({ title: `Danh sách người nhận (${msgs.length})`, icon: 'list', actions: `<div class="row">${U.input({ name: 's', value: f.s, placeholder: 'Tìm kiếm theo phòng, tên khách, SĐT…', icon: 'search', cls: 'sm', attrs: { id: 'ms', style: 'width:240px' } })}${U.select({ name: 'st', value: f.st, all: 'Tất cả trạng thái', options: [['ok', 'Thành công'], ['fail', 'Thất bại'], ['wait', 'Đang chờ retry'], ['queued', 'Chờ xử lý'], ['skipped', 'Bỏ qua']], cls: 'sm', attrs: { 'data-on': 'f', style: 'width:auto' } })}</div>`, body: null, id: 'mt' })}`;
    U.table(root.querySelector('#mt'), { rows, unit: 'người nhận', cols: [{ key: 'n', label: 'STT', render: (m, i) => i + 1, width: '48px' }, { key: 'room', label: 'Phòng', render: m => m.roomId ? U.link('#/rooms/' + m.roomId, esc(Q.room(m.roomId).code || '-')) : '-' }, { key: 'name', label: 'Khách thuê', render: m => esc(recipName(m)) }, { key: 'phone', label: 'SĐT / Zalo', render: m => esc(m.phone || '-') }, { key: 'content', label: 'Nội dung rút gọn', render: m => `<span class="small muted">${esc((m.content || tpl.body || '').replace(/\n/g, ' ').slice(0, 22))}…</span>` }, { key: 'status', label: 'Trạng thái gửi', sortable: true, render: sendChip }, { key: 'prov', label: 'Nhà cung cấp phản hồi', render: provCell }, { key: 'time', label: 'Thời gian', sortable: true, sortVal: m => m.sentAt || '', render: m => m.sentAt ? m.sentAt.slice(8, 10) + '/' + m.sentAt.slice(5, 7) + ' ' + m.sentAt.slice(11, 16) : '-' }, { key: 'retry', label: 'Retry', render: m => (m.status === 'failed' || m.status === 'unknown') && !St.one('zaloMessages', x => x.retryOfId === m.id) && (m.status === 'unknown' || (pol.retryCodes.includes(Q.providerOf(m)) && (m.attempt || 1) < pol.maxRetry)) && TH.auth.can('zalo.send') ? U.iconBtn('refresh-cw', 'retry-one', 'Thử lại tin này', { 'data-id': m.id }, 'blue') : (m.attempt > 1 ? `<span class="xs muted">lần ${m.attempt}</span>` : '-') }, { key: 'actions', label: 'Thao tác', render: m => U.rowActions([U.btn({ label: 'Xem', icon: 'eye', size: 'btn-sm', cls: 'btn-outline', act: 'view', attrs: { 'data-id': m.id } }), U.iconBtn('message', 'thread', 'Xem hội thoại Zalo', { 'data-id': m.id })]), hideable: false }] });
    root.querySelector('#ms').addEventListener('keydown', e => { if (e.key === 'Enter') { TH.router.replaceQuery(Object.assign({}, f, { s: e.target.value })); TH.router.refresh(); } });
    U.onChange(root, { f: () => { TH.router.replaceQuery(Object.assign({}, f, { st: root.querySelector('select[name=st]').value })); TH.router.refresh(); } });
    const showMsg = (m) => U.modal({ title: 'Tin nhắn tới ' + recipName(m), sub: Q.label('zmsg', m.status) + (Q.providerOf(m) ? ' · ' + Q.providerOf(m) + ' ' + (m.providerMsg || Q.providerMsg(Q.providerOf(m))) : ''), body: U.phone(m.content || Q.renderTemplate(tpl.body || '', Q.templateCtx(m.invoiceId ? St.get('invoices', m.invoiceId) : null, m.tenantId ? Q.tenant(m.tenantId) : { name: recipName(m) }, { room: Q.room(m.roomId), buildingId: m.buildingId })), m.sentAt ? F.datetime(m.sentAt) : 'Chưa gửi') + `<div class="bold mt12 mb4">Log nhà cung cấp</div><table class="tbl compact pill-log"><tbody>${(m.attempts || [{ n: m.attempt || 1, at: m.sentAt, code: Q.providerOf(m), msg: m.providerMsg || Q.providerMsg(Q.providerOf(m)) }]).map(a => `<tr><td>#${a.n}</td><td>${esc(a.at ? F.datetime(a.at) : '-')}</td><td class="${a.code === '200' ? 'green' : 'red'} bold">${esc(a.code || '-')}</td><td>${esc(a.msg || '')}</td></tr>`).join('')}</tbody></table>` + U.note('info', '', 'Gửi thành công không phải bằng chứng khách đã thanh toán (FR-ZAL-05).') });
    U.bind(root, { back: () => TH.go('#/zalo/history'), start: () => { X.startBatch(b.id); ok('Bắt đầu gửi ' + b.code); }, copy: (el) => { try { navigator.clipboard.writeText(el.dataset.v); } catch (e) { } ok('Đã sao chép', el.dataset.v); }, tpl: () => Fm.template(tpl), view: (el) => showMsg(St.get('zaloMessages', el.dataset.id)), thread: (el) => TH.pages.zaloThread(St.get('zaloMessages', el.dataset.id)), collapse: () => U.toast('info', 'Thu gọn', 'Mô phỏng'), fst: (el) => { TH.router.replaceQuery(Object.assign({}, f, { st: el.dataset.k })); TH.router.refresh(); },
      'log-all': () => U.modal({ title: 'Log phản hồi từ Zalo – ' + b.code, body: `<div class="tbl-wrap"><table class="tbl compact pill-log"><thead><tr><th>Thời gian</th><th>Phòng</th><th>SĐT</th><th>Mã</th><th>Mô tả</th></tr></thead><tbody>${(b.log && b.log.length ? b.log : msgs.map(m => ({ at: m.sentAt, roomId: m.roomId, phone: m.phone, code: Q.providerOf(m), msg: m.providerMsg || Q.providerMsg(Q.providerOf(m)) }))).map(l => `<tr><td>${esc(l.at || '-')}</td><td>${esc(Q.room(l.roomId).code || '-')}</td><td>${esc(l.phone || '')}</td><td class="${l.code === '200' ? 'green' : 'red'} bold">${esc(l.code)}</td><td>${esc(l.msg)}</td></tr>`).join('')}</tbody></table></div>` }),
      retry: async () => { if (await U.confirm({ title: 'Retry ' + retryable + ' bản ghi lỗi?', text: 'Chỉ tin lỗi 403/408 (theo chính sách retry) được xếp hàng lại; 300 – số không tồn tại là lỗi vĩnh viễn' + (pol.fallbackSms ? ' → tạo tin SMS fallback (mô phỏng)' : '') + '. Không gửi lại người đã nhận (FR-ZAL-04).', ok: 'Retry' })) { try { const n = X.retryBatch(b.id); ok('Đã xếp hàng retry ' + n + ' tin'); } catch (e) { U.toast('err', 'Không retry được', e.message); } } }, 'retry-one': (el) => { try { X.retryMessage(el.dataset.id); ok('Đã xếp hàng thử lại'); } catch (e) { U.toast('err', 'Không thử lại được', e.message); } },
      export: () => { F.download(b.code + '-log.csv', F.csv(msgs.map(m => [recipName(m), m.phone, Q.room(m.roomId).code || '', Q.label('zmsg', m.status), Q.providerOf(m), m.providerMsg || Q.providerMsg(Q.providerOf(m)), m.sentAt || '', m.attempt || 1]), ['Khách', 'SĐT', 'Phòng', 'Trạng thái', 'Mã NCC', 'Phản hồi', 'Thời gian', 'Lần']), 'text/csv'); ok('Đã tải log (CSV)', 'Bản demo offline không kèm SheetJS – nhãn .xlsx giữ theo PNG'); } });
  };
  if (rt) rt.handler = (root, p, q) => (TH.phase.on(2) ? detailP2 : p1)(root, p, q);
})(window.TH);
