import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {boot} from './_app.mjs';
import {ROOT} from './_load.mjs';

const ownerDraft=t=>{
  const d=t.intake.blank('owner');d.id='intake-test-owner';d.reviewed=true;
  d.data={name:'PHÍ VĂN THẮNG',phone:'0916122338',idNo:'001070018351',operatorName:'NGUYỄN ĐÌNH CHUNG',buildingCode:'TH01',buildingAddress:'số 25 Nguyễn Cơ Thạch, phường Từ Liêm, Hà Nội',contractCode:'HĐCN-TH01-2026-001',signDate:'2026-08-25',startDate:'2026-09-01',handoverDate:'2026-09-01',endDate:'2031-08-31',rent:114000000,deposit:114000000,payMonths:3,dueDay:10,floors:10,areaId:'A2',managerId:t.store.all('employees')[0].id};
  d.rooms=[{code:'302TH01',number:'302',floor:3,exploitation:'timehouse',listPrice:4500000,mgmtPrice:4500000,price:4500000},{code:'000TH01',number:'000',floor:0,exploitation:'meter_common'}];return d;
};
const tenantDraft=t=>{
  const d=t.intake.blank('tenant');d.id='intake-test-tenant';d.reviewed=true;
  d.data={name:'TRẦN MINH AN',phone:'0988123456',idNo:'001098000001',buildingCode:'TH01',buildingAddress:'số 25 Nguyễn Cơ Thạch, phường Từ Liêm, Hà Nội',roomCode:'302TH01',contractCode:'HĐKH-TH01-P302-2026-001',signDate:'2026-09-17',startDate:'2026-10-01',moveInDate:'2026-10-01',svcStart:'2026-10-01',endDate:'2027-09-30',rent:4500000,deposit:4500000,payMonths:1,people:2,status:'pending',declaredPaid:9000000,paidDeposit:4500000,paidRent:4500000,elOpen:1250,waOpen:85};
  d.items={electric:{unit:4000,method:'meter'},water:{unit:120000,method:'person'}};return d;
};
test('six entry modes converge: owner→room→pending stay with proposal, idempotent and atomic',()=>{
  const t=boot();const o=ownerDraft(t),x=t.intake.commit(o);
  assert.equal(t.store.get('rooms','r_000TH01').exploitation,'meter_common');
  assert.equal(t.store.where('rooms',r=>r.buildingId==='b_TH01').length,2);
  assert.equal(t.store.where('ownerPayments',p=>p.contractId===x.targetId)[0].amountDue,342000000);
  assert.equal(t.intake.commit(o).targetId,x.targetId);
  assert.equal(t.store.where('ownerContracts',c=>c.buildingId==='b_TH01').length,1);
  const d=tenantDraft(t),res=t.intake.commit(d),s=t.store.get('stays',res.targetId);
  assert.equal(s.status,'pending');assert.equal(s.openingReadings.electric,1250);
  const rate=t.q.rateOf(s.id,d.data.startDate);
  assert.equal(rate.source,'intake');assert.equal(rate.intakeId,d.id);
  const version=t.store.get('stayVersions',rate.contractVersionId);
  assert.equal(version.rates.rateVersionId,rate.id);assert.equal(version.rates.items.water.unit,120000);
  assert.equal(version.sourceRef,d.id);
  assert.equal(t.store.where('depositLedger',l=>l.stayId===s.id).length,0);
  assert.equal(t.store.where('payments',p=>p.stayId===s.id).length,0);
  assert.equal(t.store.where('intakePaymentProposals',p=>p.stayId===s.id)[0].amount,9000000);
  const proposal=t.store.one('intakePaymentProposals',p=>p.stayId===s.id);
  t.actions.confirmIntakePayment(proposal.id,{stayId:s.id,type:'deposit',amount:4500000,receivedAt:t.f.today(),reference:'CK-DEMO-01',allocations:[]});
  assert.equal(t.intake.proposalBalance(proposal),4500000);
  assert.equal(t.actions.depositBalance(s.id),4500000);
  t.actions.confirmIntakePayment(proposal.id,{stayId:s.id,type:'prepay',amount:4500000,receivedAt:t.f.today(),reference:'CK-DEMO-02',allocations:[]});
  assert.equal(t.intake.proposalBalance(proposal),0);
  assert.throws(()=>t.actions.confirmIntakePayment(proposal.id,{stayId:s.id,type:'deposit',amount:1,receivedAt:t.f.today(),reference:'DUP',allocations:[]}));
  assert.equal(t.intake.commit(d).targetId,s.id);
  const reimportOwner=ownerDraft(t);reimportOwner.id='intake-owner-reimport';t.intake.commit(reimportOwner);
  const reimportTenant=tenantDraft(t);reimportTenant.id='intake-tenant-reimport';t.intake.commit(reimportTenant);
  assert.equal(t.store.where('ownerContracts',c=>c.buildingId==='b_TH01').length,1);
  assert.equal(t.store.where('stays',s=>s.roomId==='r_302TH01').length,1);
  assert.equal(t.store.where('intakePaymentProposals',p=>p.stayId===s.id).length,1);
  t.actions.addRoom('b_TH01',{number:'303',floor:3,exploitation:'timehouse',price:3800000});
  const converted=tenantDraft(t);converted.id='intake-converted';Object.assign(converted.data,{name:'KHÁCH CŨ',phone:'0988123458',idNo:'001098000003',roomCode:'303TH01',contractCode:'OLD-303',status:'active',openingDeposit:3800000,openingAsOf:'2026-09-01',declaredPaid:0,paidDeposit:0,paidRent:0});
  const oldStay=t.intake.commit(converted);
  assert.equal(t.actions.depositBalance(oldStay.targetId),3800000);
  assert.equal(t.store.where('payments',p=>p.stayId===oldStay.targetId).length,0);
  const bad=tenantDraft(t);bad.id='invalid-target';bad.data.roomCode='000TH01';
  assert.match(t.intake.validate(bad).errors.join(' '),/Đồng hồ chung/);
  assert.throws(()=>t.intake.commit(bad));
  assert.equal(t.store.get('intakeResults','invalid-target'),null);
});
test('source NHÀ G: 302G1 keeps three prices and held deposit; 000G1 is common meter',()=>{
  const context={};vm.createContext(context);
  vm.runInContext(fs.readFileSync(path.join(ROOT,'mockup/vendor/intake/xlsx.full.min.js'),'utf8'),context);
  const file=fs.readdirSync(path.join(ROOT,'docs_timonouse')).find(f=>f.startsWith('Hoá đơn')&&f.endsWith('.xlsx'));
  const book=context.XLSX.read(fs.readFileSync(path.join(ROOT,'docs_timonouse',file)),{type:'buffer',cellFormula:true,cellDates:true});
  const sheet=book.Sheets['NHÀ G'],rows=context.XLSX.utils.sheet_to_json(sheet,{header:1,defval:null,raw:true});
  const t=boot(),tenant=t.intake.fromRows('tenant',rows,{file,sheet:'NHÀ G',cells:sheet}).find(d=>d.data.roomCode==='302G1');
  assert.equal(tenant.data.listPrice,4000000);assert.equal(tenant.data.mgmtPrice,3800000);assert.equal(tenant.data.rent,3800000);
  assert.equal(tenant.data.openingDeposit,3800000);assert.equal(tenant.data.deposit,undefined);assert.equal(tenant.data.declaredPaid,4692000);
  assert.equal(tenant.items.water.method,'person');assert.equal(tenant.sources.rent.cell,'I11');assert.equal(tenant.sources.openingDeposit.cell,'F11');
  const owner=t.intake.fromRows('owner',rows,{file,sheet:'NHÀ G',cells:sheet}).find(d=>d.data.buildingCode==='G1');
  assert.equal(owner.rooms.find(r=>r.code==='000G1').exploitation,'meter_common');
  assert.equal(owner.data.name,undefined);assert.equal(owner.data.rent,undefined);
  const news=book.Sheets['PHÒNG MỚI THÁNG 9'],newRows=context.XLSX.utils.sheet_to_json(news,{header:1,defval:null,raw:true});
  const fresh=t.intake.fromRows('tenant',newRows,{file,sheet:'PHÒNG MỚI THÁNG 9',cells:news}).find(d=>d.data.roomCode==='402S44');
  assert.equal(fresh.data.rent,2600000);assert.equal(fresh.data.deposit,2600000);
  assert.equal(fresh.sources.rent.cell,'G11');
  const refunds=book.Sheets['HOÀN CỌC'],refundRows=context.XLSX.utils.sheet_to_json(refunds,{header:1,defval:null,raw:true});
  const reference=t.intake.fromRows('tenant',refundRows,{file,sheet:'HOÀN CỌC',cells:refunds})[0];
  assert.equal(reference.data.status,'ended');assert.equal(reference.data.rent,undefined);
  assert.equal(t.intake.validate(reference).status,'Không thuộc phạm vi nhập');
});
test('permission and conflict block intake before any mutation',()=>{
  const t=boot(),d=ownerDraft(t);d.conflicts.push({key:'rent',before:114000000,next:120000000,source:{file:'other.xlsx',cell:'F9'}});
  assert.match(t.intake.validate(d).errors.join(' '),/xung đột/);
  assert.throws(()=>t.intake.commit(d));
  const limited=boot({user:'vanhanh'}),other=ownerDraft(limited);
  assert.match(limited.intake.validate(other).errors.join(' '),/quyền/i);
  assert.throws(()=>limited.intake.commit(other));
  const before=t.store.all('rooms').length;
  assert.throws(()=>t.store.atomic(()=>{t.store.add('rooms',{id:'r_Temporary',code:'Temporary'});throw new Error('Lưu lỗi');}),/Lưu lỗi/);
  assert.equal(t.store.all('rooms').length,before);
  const badFormula=t.intake.fromRows('tenant',[['name','rent','roomCode'],['A',null,'101TH01']],{sheet:'DATA',cells:{B2:{formula:'A2+1',value:null}}})[0];
  assert.match(badFormula.sourceErrors[0].message,/công thức/);
});
test('contract plus spreadsheet fills missing room prices and exposes conflicting source cells',()=>{
  const t=boot(),d=t.intake.blank('owner');d.data={buildingCode:'TH01'};d.rooms=[{code:'302TH01',number:'302',exploitation:'timehouse',source:{file:'owner.pdf',page:2}}];
  t.intake.merge(d,{data:{buildingCode:'TH01'},rooms:[{code:'302TH01',number:'302',listPrice:4500000,source:{file:'rooms.xlsx',sheet:'DATA',cell:'C2'},sources:{listPrice:{file:'rooms.xlsx',sheet:'DATA',cell:'D2'}}}]});
  assert.equal(d.rooms[0].listPrice,4500000);assert.equal(d.rooms[0].sources.listPrice.cell,'D2');assert.equal(d.conflicts.length,0);
  t.intake.merge(d,{data:{},rooms:[{code:'302TH01',number:'302',listPrice:4600000,sources:{listPrice:{file:'changed.xlsx',sheet:'DATA',cell:'G9'}}}]});
  assert.equal(d.conflicts[0].source.cell,'G9');assert.equal(d.rooms[0].listPrice,4500000);
});
test('existing building address requires an explicit source choice before update',()=>{
  const t=boot();t.intake.commit(ownerDraft(t));
  const d=ownerDraft(t);d.id='new-term-owner';d.data.contractCode='HD-TH01-2031';d.data.startDate='2031-09-01';d.data.endDate='2033-08-31';d.data.signDate='2031-08-15';d.data.handoverDate='2031-09-01';d.data.buildingAddress='số 27 Nguyễn Cơ Thạch, phường Từ Liêm, Hà Nội';
  d.sources.buildingAddress={file:'appendix.pdf',page:1,raw:d.data.buildingAddress};
  const before=t.intake.validate(d);
  assert.equal(before.existingConflicts[0].key,'buildingAddress');
  assert.match(before.errors.join(' '),/Địa chỉ tòa khác/);
  d.existingChoices={buildingAddress:'source'};
  assert.equal(t.intake.validate(d).errors.length,0);
  t.intake.commit(d);
  assert.equal(t.store.get('buildings','b_TH01').address,d.data.buildingAddress);
});


test('structured intake errors identify fields without changing commit guards',()=>{
  const t=boot(),owner=ownerDraft(t);
  owner.data.phone='123';owner.data.endDate=owner.data.startDate;owner.data.payMonths=5;owner.rooms[1].exploitation='timehouse';
  const review=t.intake.validate(owner);
  assert.match(review.fieldErrors.phone,/10 chữ số/);
  assert.match(review.fieldErrors.endDate,/sau ngày bắt đầu/);
  assert.match(review.fieldErrors.payMonths,/Kỳ thanh toán/);
  assert.match(review.fieldErrors.rooms,/đồng hồ chung/);
  assert.ok(review.errors.includes(review.fieldErrors.phone));
  assert.throws(()=>t.intake.commit(owner));
  assert.equal(t.store.get('intakeResults',owner.id),null);
  const valid=ownerDraft(t);assert.deepEqual(Object.keys(t.intake.validate(valid).fieldErrors),[]);t.intake.commit(valid);
  const tenant=tenantDraft(t);tenant.data.openingDebt=100000;tenant.data.openingDeposit=100000;
  const incomplete=t.intake.validate(tenant);
  assert.match(incomplete.fieldErrors.openingPeriod,/kỳ/);
  assert.match(incomplete.fieldErrors.openingAsOf,/ngày/);
  tenant.data.openingAsOf='2026-09-01';tenant.data.openingPeriod='2026-09';
  tenant.items.water.unit=-1;
  assert.match(t.intake.validate(tenant).fieldErrors['fee:water'],/Biểu phí/);
});
