/* UI kit Phase 3: avatar+tên, thumb tài sản, ô ngày, hero hồ sơ, hàng progress, lưới chấm công, QR giả, icon mới. Không đổi hành vi P1/P2. */
(function (TH) {
  const F = TH.f, U = TH.ui, esc = F.esc, I = TH.icon;
  /* ---- icon mới (Lucide subset) ---- */
  Object.assign(TH.icons, {
    'qr-code': '<rect width="5" height="5" x="3" y="3" rx="1"/><rect width="5" height="5" x="16" y="3" rx="1"/><rect width="5" height="5" x="3" y="16" rx="1"/><path d="M21 16h-3a2 2 0 0 0-2 2v3M21 21v.01M12 7v3a2 2 0 0 1-2 2H7M3 12h.01M12 3h.01M12 16v.01M16 12h1M21 12v.01M12 21v-1"/>',
    camera: '<path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z"/><circle cx="12" cy="13" r="3"/>',
    'id-card': '<path d="M16 10h2M16 14h2M6.17 15a3 3 0 0 1 5.66 0"/><circle cx="9" cy="11" r="2"/><rect x="2" y="5" width="20" height="14" rx="2"/>',
    award: '<circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/>',
    'file-badge': '<path d="M4 22h14a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v2"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><circle cx="6" cy="14" r="3"/><path d="M4.5 17 4 22l2-1 2 1-.5-5"/>',
    'clipboard-list': '<rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2M12 11h4M12 16h4M8 11h.01M8 16h.01"/>',
    'user-cog': '<circle cx="18" cy="15" r="3"/><circle cx="9" cy="7" r="4"/><path d="M10 15H6a4 4 0 0 0-4 4v2M21.7 16.4l-.9-.3M15.2 13.9l-.9-.3M16.6 18.7l.3-.9M19.1 12.2l.3-.9M19.6 18.7l-.4-1M16.8 12.3l-.4-1M14.3 16.6l1-.4M20.7 13.8l1-.4"/>',
    'calendar-x': '<rect width="18" height="18" x="3" y="4" rx="2" ry="2"/><line x1="16" x2="16" y1="2" y2="6"/><line x1="8" x2="8" y1="2" y2="6"/><line x1="3" x2="21" y1="10" y2="10"/><path d="m14 14-4 4M10 14l4 4"/>',
    'chart-pie': '<path d="M21 12c.552 0 1.005-.449.95-.998a10 10 0 0 0-8.953-8.951c-.55-.055-.998.398-.998.95v8a1 1 0 0 0 1 1z"/><path d="M21.21 15.89A10 10 0 1 1 8 2.83"/>',
    'arrow-up-right': '<path d="M7 7h10v10M7 17 17 7"/>',
    'building-2': '<path d="M6 22V4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v18Z"/><path d="M6 12H4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h2M18 9h2a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-2M10 6h4M10 10h4M10 14h4M10 18h4"/>',
  });
  /* avatar initials + tên + dòng phụ (người kiểm kê, cổ đông, nhân viên) */
  U.avatarCell = ({ name, sub = '', size = 'sm', href = '' }) => `<div class="av-cell">${U.avatar(name || '?', size)}<div class="cell2"><span>${href ? `<a class="link bold" href="${href}">${esc(name || '-')}</a>` : `<b>${esc(name || '-')}</b>`}</span>${sub ? `<small>${sub}</small>` : ''}</div></div>`;
  /* ô ảnh tài sản 40×40: màu theo loại + icon (không dùng ảnh ngoài) */
  const CAT_ICON = { dienlanh: 'droplet', pccc: 'flame', thangmay: 'move-up', chieusang: 'zap', anninh: 'camera', noithat: 'grid', dien: 'plug', mayphat: 'battery-charging', khac: 'package' };
  U.thumb = (a, size = 40) => { const q = TH.q; const color = q.assetCatColor ? q.assetCatColor(a.category) : '#94A3B8'; return `<div class="thumb" style="width:${size}px;height:${size}px;background:${color}1a;color:${color}" title="${esc(a.name || '')}">${I(CAT_ICON[a.category] || 'package')}</div>`; };
  /* ô ngày lớn "25 / Th10" (tái dùng kiểu date-tile của P2) */
  U.dateTile = (iso, tone = '') => `<div class="date-tile ${tone}"><b>${iso ? iso.slice(8, 10) : '--'}</b><small>Th${iso ? Number(iso.slice(5, 7)) : ''}</small></div>`;
  /* hero hồ sơ: avatar lớn + tên + chip + meta */
  U.profileHero = ({ name, chip = '', meta = [], avatarCls = '' }) => `<div class="card mb16"><div class="card-b profile-hero"><div class="avatar xl ${avatarCls}">${esc(F.initials(name))}</div><div class="grow"><div class="row gap12 wrap"><h2 class="ph-name">${esc(name)}</h2>${chip}</div><div class="ph-meta">${meta.map(([k, v, sub]) => `<div class="ph-m"><span>${esc(k)}</span><b>${v}</b>${sub ? `<small>${sub}</small>` : ''}</div>`).join('')}</div></div></div></div>`;
  /* hàng progress: nhãn · số · thanh · % */
  U.progressRows = (rows) => `<div class="prog-rows">${rows.map(r => `<div class="prog-row"><span class="dot" style="background:${r.color || 'var(--primary)'}"></span><span class="lb">${esc(r.label)}</span><span class="cnt muted small">${r.count != null ? esc(String(r.count)) : ''}</span><div class="progress grow"><i style="width:${Math.max(0, Math.min(100, r.pct || 0))}%;background:${r.color || 'var(--primary)'}"></i></div><b class="pct">${Math.round(r.pct || 0)}%</b></div>`).join('')}</div>`;
  /* lưới chấm công: hàng = NV, cột = ngày; ô có data-att để bấm đổi ký hiệu */
  U.attendanceGrid = ({ employees, period, sheets, editable = false, today = F.today() }) => {
    const [y, m] = period.split('-').map(Number); const n = new Date(y, m, 0).getDate(); const days = Array.from({ length: n }, (_, i) => period + '-' + F.pad(i + 1));
    const dow = (iso) => ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'][new Date(iso + 'T00:00').getDay()];
    const head = `<tr><th class="sticky">Nhân viên</th>${days.map(dd => `<th class="${dd === today ? 'today' : ''} ${dow(dd) === 'CN' ? 'sun' : ''}"><b>${Number(dd.slice(8))}</b><small>${dow(dd)}</small></th>`).join('')}<th class="num">Công</th><th class="num">Nghỉ</th><th class="num">OT</th></tr>`;
    const body = employees.map(e => { const t = sheets[e.id] || { days: {}, workDays: 0, offDays: 0, otHours: 0, status: 'draft' }; const locked = !editable || t.status === 'confirmed'; return `<tr><td class="sticky">${U.avatarCell({ name: e.name, sub: e.code, href: '#/hr/' + e.id })}</td>${days.map(dd => { const c = (t.days || {})[dd] || ''; return `<td class="att ${c ? 'c-' + c : ''} ${dd > today ? 'future' : ''}"><button type="button" class="att-btn" ${locked || dd > today ? 'disabled' : `data-act="att" data-emp="${e.id}" data-date="${dd}"`} title="${esc(c ? TH.q.label('attCode', c) : 'Chưa chấm')}">${c || '·'}</button></td>`; }).join('')}<td class="num bold">${t.workDays || 0}</td><td class="num">${t.offDays || 0}</td><td class="num">${t.otHours || 0}</td></tr>`; }).join('');
    return `<div class="tbl-wrap att-wrap"><table class="tbl compact att-grid"><thead>${head}</thead><tbody>${body || `<tr><td colspan="${n + 4}">${U.empty({ title: 'Không có nhân viên phù hợp' })}</td></tr>`}</tbody></table></div>`;
  };
  /* QR giả: ma trận 21×21 deterministic từ hash chuỗi (mô phỏng, không quét được) */
  U.qrBox = (text, size = 140) => { let h = 2166136261; const s = String(text || 'TIMO'); const bit = () => { h ^= h << 13; h ^= h >>> 17; h ^= h << 5; return (h >>> 0) & 1; }; for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619); const N = 21; let cells = ''; const finder = (x, y) => (x < 7 && y < 7) || (x >= N - 7 && y < 7) || (x < 7 && y >= N - 7); for (let y = 0; y < N; y++) for (let x = 0; x < N; x++) { let on; if (finder(x, y)) { const fx = x % (N - 7) < 7 ? x % (N - 7) : x, fy = y % (N - 7) < 7 ? y % (N - 7) : y; const lx = x >= N - 7 ? x - (N - 7) : x, ly = y >= N - 7 ? y - (N - 7) : y; on = lx === 0 || lx === 6 || ly === 0 || ly === 6 || (lx >= 2 && lx <= 4 && ly >= 2 && ly <= 4); void fx; void fy; } else on = bit(); if (on) cells += `<rect x="${x}" y="${y}" width="1" height="1"/>`; } return `<svg class="qr" viewBox="0 0 ${N} ${N}" width="${size}" height="${size}" shape-rendering="crispEdges" fill="#0F172A" style="background:#fff;border:1px solid var(--border);border-radius:8px;padding:6px;box-sizing:border-box">${cells}</svg>`; };
  /* ô KPI nhỏ có màu (KPI cá nhân, Thống kê nhanh) */
  U.miniStat = ({ label, value, icon = 'info', tone = 'blue', delta = null }) => `<div class="mini-stat t-${tone}"><div class="ic ${tone}">${I(icon)}</div><div class="grow"><div class="vl">${value}${delta != null ? ' ' + U.delta(delta) : ''}</div><div class="lb">${esc(label)}</div></div></div>`;
  /* thẻ dự án (grid) */
  U.projectCard = (r) => `<div class="proj-card card" data-act="open" data-id="${r.p.id}"><div class="proj-img" style="background:linear-gradient(135deg,var(--primary-100),var(--blue-bg))">${I('building-2')}</div><div class="card-b"><div class="row between"><b>${esc(r.p.name)}</b>${TH.q.chip('project', r.p.status)}</div><div class="small muted mt4">${I('building')} ${esc(r.b.name || '')} · ${esc(r.b.district || '')}</div><div class="row between mt12 small"><span class="muted">Vốn điều lệ</span><b>${F.vnd(r.p.capital)}</b></div><div class="row between small mt4"><span class="muted">Thực góp</span><b>${F.vnd(r.paid)} (${r.pct}%)</b></div><div class="progress mt8"><i style="width:${r.pct}%"></i></div><div class="row between mt12 small"><span>${I('users')} ${r.shareholders} cổ đông</span><span>${I('package')} ${r.assets} tài sản</span><span class="${r.roi.tone === 'good' ? 'green' : r.roi.tone === 'fair' ? 'amber' : 'red'} bold">ROI ${r.roi.roi}%</span></div></div></div>`;
})(window.TH);
