/* Forms – Spec v1.8 Wave 4: phiếu chi phí §4.27.2 (+ hoa hồng §4.27.5, phân bổ §4.27.7), phân bổ chi phí chung, điều chỉnh/khấu trừ lương có lý do (§4.26.10),
   cấu phần lương NV (§4.26.5), Payroll Rule Version (§4.26.4), mở lại bảng lương, ghi nhận chi lương từng người / hàng loạt / lỗi / hủy / điều chỉnh (§4.26.8-9). */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, St = TH.store, X = TH.actions, Fm = TH.forms, esc = F.esc;
  const refresh = () => { TH.layout.refreshTop(); TH.router.refresh(); };
  const footer = (saveLabel = 'Lưu', icon = 'save', extra = '', guide = '') => extra + U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn(Object.assign({ label: saveLabel, act: 'save', cls: 'btn-primary', icon }, guide ? { attrs: { 'data-guide': guide } } : {}));
  const run = (m, fn, okMsg) => { try { const r = fn(); if (r && r.duplicate) U.toast('warn', 'Yêu cầu trùng – không tạo thêm', 'Idempotency key đã tồn tại'); else if (okMsg) U.toast('ok', typeof okMsg === 'function' ? okMsg(r) : okMsg); m.close(true); refresh(); return r; } catch (e) { U.toast('err', 'Không lưu được', e.message); U.setErrors(m.el, e.fields || {}); } };
  const liveB = () => St.where('buildings', b => !b.stub && b.status !== 'inactive');
  const bOpts = () => liveB().map(b => [b.id, b.name + ' (' + b.code + ')']);
  const catOptions = () => Q.expenseTree().flatMap(p => [[p.code, '— ' + p.name + ' —', true], ...p.children.map(c => [c.code, '  ' + c.name + ' (' + c.code + ')'])]);
  const typeOpts = () => (Q.buildingTypeOptions ? Q.buildingTypeOptions() : Object.entries(Q.L.buildingType).map(([k, v]) => [k, v[0]]));

  /* ---------- Khối phân bổ chi phí chung (dùng chung cho Fm.expense & Fm.allocateExpense) ---------- */
  const allocBlock = (ex, init = {}) => {
    const method = init.method || Q.defaultAllocMethod(ex.categoryCode || ''); const ids = new Set(init.buildingIds || []);
    return `<div class="fs" id="alloc-sec"><div class="fs-h">${I('percent')}Phân bổ chi phí chung (§4.27.7)</div>
      <div class="form-grid">${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'allocMethod', value: method, options: Object.entries(Q.L.allocMethod).filter(([k]) => k !== 'DIRECT').map(([k, v]) => [k, v[0]]) }), help: 'Mặc định theo Allocation Rule ' + ((Q.allocationRule() || {}).code || '-') + ' cho hạng mục' })}${U.field({ label: 'Phạm vi', input: U.select({ name: 'allocScope', value: init.buildingType ? 'type' : 'buildings', options: [['buildings', 'Chọn tòa'], ['type', 'Nhóm tòa T/S/G']] }) })}</div>
      <div id="alloc-buildings" class="mt8"><div class="row wrap gap12">${liveB().map(b => U.check({ name: 'ab_' + b.id, label: b.name.replace('Tòa ', ''), checked: ids.size ? ids.has(b.id) : true })).join('')}</div></div>
      <div id="alloc-type" class="mt8" hidden>${U.field({ label: 'Nhóm tòa (loại hiệu lực trong kỳ)', input: U.select({ name: 'allocType', value: init.buildingType || 'T', options: typeOpts() }) })}</div>
      <div class="tbl-wrap mt8"><table class="tbl compact"><thead><tr><th>Tòa nhà</th><th class="num">Cơ sở</th><th class="num">Tỷ lệ (%)</th><th class="num">Số tiền (VND)</th></tr></thead><tbody id="alloc-body"></tbody><tfoot><tr><td>Tổng</td><td></td><td class="num" id="alloc-pct">-</td><td class="num" id="alloc-total">-</td></tr></tfoot></table></div>
      <div class="xs muted mt8">Mỗi lần phân bổ lưu phiếu nguồn, tòa nhận, số tiền/tỷ lệ, phương thức, kỳ và người xác nhận (Expense Allocation §12.21.4).</div></div>`;
  };
  const allocRead = (el) => { const method = el.querySelector('select[name=allocMethod]').value; const scope = el.querySelector('select[name=allocScope]').value; const ratios = {}; el.querySelectorAll('#alloc-body input[name^=ar_]').forEach(i => { ratios[i.name.slice(3)] = Number(i.value) || 0; }); return { method, buildingType: scope === 'type' ? el.querySelector('select[name=allocType]').value : '', buildingIds: scope === 'type' ? [] : [...el.querySelectorAll('#alloc-buildings input[type=checkbox]:checked')].map(c => c.name.slice(3)), ratios }; };
  const allocSync = (el, amountGetter, period) => { const a = allocRead(el); el.querySelector('#alloc-buildings').hidden = !!a.buildingType; el.querySelector('#alloc-type').hidden = !a.buildingType; const pv = Q.allocationPreview({ amount: amountGetter(), method: a.method, buildingIds: a.buildingIds, buildingType: a.buildingType, period, ratios: a.ratios }); const manual = a.method === 'MANUAL_RATIO'; el.querySelector('#alloc-body').innerHTML = pv.rows.map(r => `<tr><td>${esc(r.name)}</td><td class="num">${manual ? `<input class="inp sm tr" name="ar_${r.buildingId}" type="number" value="${a.ratios[r.buildingId] != null ? a.ratios[r.buildingId] : Math.round(100 / pv.rows.length)}" style="width:80px">` : (pv.basis === 'doanh thu' ? F.vnd(r.basis) : r.basis + ' ' + pv.basis)}</td><td class="num">${r.pct}%</td><td class="num">${F.vnd(r.amount)}</td></tr>`).join('') || '<tr><td colspan="4" class="muted tc">Chọn tòa / nhóm tòa</td></tr>'; const tp = Math.round(F.sum(pv.rows, r => r.pct)); el.querySelector('#alloc-pct').textContent = tp + '%'; el.querySelector('#alloc-pct').className = 'num ' + (Math.abs(tp - 100) <= 1 || !pv.rows.length ? 'green' : 'red'); el.querySelector('#alloc-total').textContent = F.vnd(pv.total); };

  /* ---------- Phiếu chi phí (§4.27.2) ---------- */
  Fm.expense = (ex = {}, opts = {}) => {
    const canCommon = TH.auth.can('expenses.manageCommon'); const sales = St.where('users', u => u.role === 'sale' && u.status === 'active');
    const isCommon = ex.id ? !ex.buildingId : false; const cm = ex.commission || {};
    const m = U.drawer({ title: ex.id ? 'Sửa chi phí ' + ex.code : 'Thêm chi phí', wide: true, sub: 'Dữ liệu tối thiểu §4.27.2 · danh mục §4.27.3 · lương/chi lương không nhập ở đây (§4.27.4)', body: `
      <div class="form-grid">${U.field({ label: 'Ngày chứng từ', req: true, input: U.date({ name: 'docDate', value: ex.docDate || ex.date || F.today() }) })}${U.field({ label: 'Ngày ghi nhận', input: U.date({ name: 'recordDate', value: ex.recordDate || F.today() }) })}${U.field({ label: 'Kỳ hạch toán', input: U.input({ name: 'accountingPeriod', value: ex.accountingPeriod || F.period(ex.date || F.today()), placeholder: 'YYYY-MM' }), help: 'Mặc định theo ngày chứng từ' })}${U.field({ label: 'Nguồn dữ liệu', input: U.select({ name: 'dataSource', value: ex.dataSource || 'manual', options: Object.entries(Q.L.expenseSource).map(([k, v]) => [k, v[0]]) }) })}
      ${U.field({ label: 'Hạng mục chi phí', req: true, input: U.select({ name: 'categoryCode', value: Q.expenseAlias(ex.categoryCode || ''), placeholder: 'Chọn hạng mục', options: catOptions(), attrs: { id: 'ex-cat' } }), cls: 'span2', help: 'Giá vốn · Chi phí bán hàng (Marketing, Hoa hồng) · Chi phí vận hành (Sửa chữa, Thay thế, Văn phòng, Khác)' })}
      ${U.field({ label: 'Nội dung', req: true, input: U.input({ name: 'desc', value: ex.desc || '', placeholder: 'Tiền điện tháng 10/2026' }), cls: 'span2' })}
      ${U.field({ label: 'Số tiền (VND)', req: true, input: U.money({ name: 'amount', value: ex.amount || '', attrs: { id: 'ex-amount' } }) })}${U.field({ label: 'Nhà cung cấp / người nhận', input: U.input({ name: 'supplier', value: ex.supplier || '', placeholder: 'EVN, Cấp nước, nhân viên…' }) })}
      ${U.field({ label: 'Phương thức thanh toán', input: U.select({ name: 'payMethod', value: ex.payMethod || 'bank', options: Object.entries(Q.L.expensePayMethod).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Loại ghi nhận', input: U.select({ name: 'recordType', value: ex.recordType && ex.recordType !== 'common' ? ex.recordType : 'ops', options: [['ops', 'Chi phí vận hành'], ['asset', 'Mua sắm tài sản']] }) })}</div>
      <div class="field mt12"><label>Tòa nhà hoặc phạm vi phân bổ<span class="req">*</span></label><div class="row gap16"><label class="chk"><input type="radio" name="mode" value="building" ${!isCommon ? 'checked' : ''}> Gắn trực tiếp một tòa</label>${canCommon ? `<label class="chk"><input type="radio" name="mode" value="common" ${isCommon ? 'checked' : ''}> Chi phí chung – phân bổ nhiều tòa / nhóm T-S-G</label>` : ''}</div>${U.select({ name: 'buildingId', value: ex.buildingId || '', placeholder: 'Chọn tòa nhà', options: bOpts(), cls: 'mt8' })}</div>
      <div class="fs mt12" id="comm-sec" hidden><div class="fs-h">${I('hand-coins')}Hoa hồng Phase 1 (§4.27.5 – nhập vào Chi phí, chưa có Commission Engine)</div><div class="form-grid">${U.field({ label: 'Sale / người nhận', input: U.select({ name: 'saleId', value: cm.saleId || '', all: 'Chọn nhân viên KD', options: sales.map(u => [u.id, u.name]) }) })}${U.field({ label: 'Tên người nhận (nếu ngoài hệ thống)', input: U.input({ name: 'recipient', value: cm.recipient || '' }) })}${U.field({ label: 'Phòng', input: U.select({ name: 'roomId', value: cm.roomId || '', all: 'Chọn phòng', options: St.where('rooms', r => !ex.buildingId || r.buildingId === ex.buildingId).slice(0, 400).map(r => [r.id, r.code + ' · ' + (Q.building(r.buildingId).name || '')]) }) })}${U.field({ label: 'Ngày thanh toán hoa hồng', input: U.date({ name: 'paidDate', value: cm.paidDate || '' }) })}</div></div>
      <div class="field mt12"><label>Chứng từ</label>${U.dropzone({ name: 'ev', hint: 'PDF, JPG, PNG (mô phỏng)' })}${ex.evidence ? '<div class="xs muted mt4">Hiện có: ' + esc(ex.evidence) + '</div>' : ''}</div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: ex.note || '' }), cls: 'mt12' })}
      <div class="mt12" id="alloc-wrap" ${isCommon ? '' : 'hidden'}>${canCommon ? allocBlock(ex, ex.allocation || {}) : ''}</div>`, footer: footer('Lưu chi phí', 'save', '', 'expense-save') });
    const el = m.el; const amt = () => F.num(el.querySelector('#ex-amount').value);
    const period = () => el.querySelector('input[name=accountingPeriod]').value || F.period(el.querySelector('input[name=docDate]').value || F.today());
    const sync = () => { const common = (el.querySelector('input[name=mode]:checked') || {}).value === 'common'; el.querySelector('select[name=buildingId]').disabled = common; el.querySelector('#alloc-wrap').hidden = !common; el.querySelector('#comm-sec').hidden = Q.expenseAlias(el.querySelector('#ex-cat').value) !== 'BH-HH'; if (common && canCommon) allocSync(el, amt, period()); };
    el.addEventListener('change', sync); el.addEventListener('input', (e) => { if (e.target.id === 'ex-amount' || e.target.name.startsWith('ar_')) sync(); }); sync();
    U.bind(el, { cancel: () => m.close(), save: () => { const d = m.data(); const common = d.mode === 'common'; const f = U.dzFiles(el, 'ev')[0]; if (!common && !d.buildingId) { U.toast('err', 'Chọn tòa nhà hoặc chuyển sang Chi phí chung'); return; } const payload = { id: ex.id, docDate: d.docDate, recordDate: d.recordDate, accountingPeriod: d.accountingPeriod, dataSource: d.dataSource, categoryCode: d.categoryCode, desc: d.desc, amount: d.amount, supplier: d.supplier, payMethod: d.payMethod, recordType: common ? 'common' : d.recordType, buildingId: common ? null : d.buildingId, evidence: f ? f.name : (ex.evidence || ''), note: d.note, saleId: d.saleId, recipient: d.recipient, roomId: d.roomId, paidDate: d.paidDate, allocation: common && canCommon ? allocRead(el) : null }; run(m, () => X.saveExpense(payload), r => 'Đã lưu chi phí ' + r.code + ' – ' + Q.label('expenseStatus', r.status)); } });
  };
  Fm.allocateExpense = (ex) => {
    const m = U.drawer({ title: 'Phân bổ chi phí ' + ex.code, sub: esc(ex.desc || '') + ' · ' + F.vnd(ex.amount) + ' · kỳ ' + F.periodLabel(ex.accountingPeriod || F.period(ex.date)), body: allocBlock(ex, ex.allocation || {}), footer: footer('Xác nhận phân bổ', 'percent', '', 'expense-allocate') });
    const el = m.el; const sync = () => allocSync(el, () => ex.amount, ex.accountingPeriod || F.period(ex.date)); el.addEventListener('change', sync); el.addEventListener('input', (e) => { if (e.target.name && e.target.name.startsWith('ar_')) sync(); }); sync();
    U.bind(el, { cancel: () => m.close(), save: () => run(m, () => X.allocateExpense(ex.id, allocRead(el)), r => 'Đã phân bổ cho ' + r.rows.length + ' tòa') });
  };
  Fm.reverseExpense = async (ex) => { const r = await U.confirm({ title: 'Hủy phiếu chi phí ' + ex.code + '?', text: 'Phiếu chuyển trạng thái Đã hủy, phân bổ bị gỡ, giữ dấu vết audit (§12.21.3 Reverse).', ok: 'Hủy phiếu', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Nhập nhầm / trùng chứng từ…' }) }) }); if (r) { try { X.reverseExpense(ex.id, r.reason); U.toast('ok', 'Đã hủy phiếu ' + ex.code); refresh(); } catch (e) { U.toast('err', 'Không hủy được', e.message); } } };

  /* ---------- Bảng lương ---------- */
  Fm.payrollAdjust = (period, employeeId) => { const e = Q.employee(employeeId); const m = U.modal({ title: 'Điều chỉnh lương – ' + esc(e.name), size: 'sm', sub: 'Điều chỉnh tăng/giảm bắt buộc có lý do, ghi audit (§4.26.10)', body: `${U.field({ label: 'Số tiền (+ tăng / − giảm)', req: true, input: U.input({ name: 'amount', type: 'number', placeholder: '500000 hoặc -200000' }) })}${U.field({ label: 'Lý do', req: true, input: U.textarea({ name: 'reason', placeholder: 'Thưởng hỗ trợ bàn giao / trừ tạm ứng…' }), cls: 'mt12' })}`, footer: footer('Lưu điều chỉnh') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.adjustPayrollLine(period, employeeId, { amount: d.amount, reason: d.reason }), 'Đã điều chỉnh lương ' + e.name); } }); };
  Fm.payrollDeduction = (period, employeeId) => { const e = Q.employee(employeeId); const p = Q.payroll(period); const r = p ? Q.payrollResult(p.id, employeeId) : {}; const m = U.modal({ title: 'Khấu trừ – ' + esc(e.name), size: 'sm', body: `${U.field({ label: 'Số tiền khấu trừ (VND)', req: true, input: U.money({ name: 'amount', value: (r || {}).deductions || 0 }) })}${U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', value: (r || {}).deductionNote || '', placeholder: 'Tạm ứng / bồi thường…' }), cls: 'mt12' })}`, footer: footer('Lưu khấu trừ') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.setPayrollDeduction(period, employeeId, { amount: d.amount, reason: d.reason }), 'Đã cập nhật khấu trừ'); } }); };
  Fm.payrollReturn = (period) => { const m = U.modal({ title: 'Trả lại bảng lương ' + F.periodLabel(period), size: 'sm', body: U.field({ label: 'Lý do', req: true, input: U.textarea({ name: 'reason', placeholder: 'Cần rà lại hiệu suất tòa…' }) }), footer: footer('Trả lại', 'undo') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.returnPayroll(period, d.reason), 'Đã trả lại bảng lương'); } }); };
  Fm.payrollReopen = (period) => { const m = U.modal({ title: 'Mở lại bảng lương ' + F.periodLabel(period), size: 'sm', sub: 'Chỉ Admin; kỳ đã chi lương không mở lại; ghi audit lý do (§4.26.10)', body: U.field({ label: 'Lý do mở lại', req: true, input: U.textarea({ name: 'reason', placeholder: 'Sai phân công tòa Sunrise tháng này…' }) }), footer: footer('Mở lại', 'unlock') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.reopenPayroll(period, d.reason), 'Đã mở lại bảng lương – trạng thái Nháp'); } }); };
  Fm.payrollConfig = (e) => { const c = Q.employeePayroll(e); const ba = c.bankAccount || {}; const m = U.drawer({ title: 'Cấu phần lương – ' + esc(e.name), sub: 'Lương cơ bản, PC ăn trưa, PC xăng xe, lương trưởng nhóm, lương hỗ trợ (§4.26.5) + tài khoản nhận (snapshot khi chi lương)', body: `<div class="form-grid">${U.field({ label: 'Lương cơ bản', req: true, input: U.money({ name: 'base', value: c.base }) })}${U.field({ label: 'Phụ cấp ăn trưa', input: U.money({ name: 'lunch', value: c.lunch }) })}${U.field({ label: 'Phụ cấp xăng xe', input: U.money({ name: 'fuel', value: c.fuel }) })}${U.field({ label: 'Lương trưởng nhóm', input: U.money({ name: 'leadAllowance', value: c.leadAllowance }) })}${U.field({ label: 'Lương hỗ trợ', input: U.money({ name: 'support', value: c.support }) })}<div></div>${U.field({ label: 'Ngân hàng', input: U.input({ name: 'bank', value: ba.bank || '' }) })}${U.field({ label: 'Số tài khoản', input: U.input({ name: 'number', value: ba.number || '' }) })}${U.field({ label: 'Tên tài khoản', input: U.input({ name: 'accName', value: ba.name || '' }), cls: 'span2' })}</div>${U.note('info', '', 'Lương hiệu suất theo phòng không nhập tay – tính từ thu M1/M2/M3 × Payroll Rule khi mở kỳ lương.')}`, footer: footer('Lưu cấu phần') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.savePayrollConfig(e.id, { base: d.base, lunch: d.lunch, fuel: d.fuel, leadAllowance: d.leadAllowance, support: d.support, bankAccount: { bank: d.bank, number: d.number, name: d.accName } }), 'Đã lưu cấu phần lương'); } }); };
  Fm.payrollRule = (r = {}) => {
    const tiers = (r.tiers && r.tiers.length ? r.tiers : [{ from: 90, to: null, rate: 150000 }, { from: 75, to: 90, rate: 120000 }, { from: 60, to: 75, rate: 90000 }, { from: 0, to: 60, rate: 60000 }]);
    const rowsHtml = (ts) => ts.map((t, i) => `<tr><td><input class="inp sm" name="tf_${i}" type="number" value="${t.from}" style="width:80px"></td><td><input class="inp sm" name="tt_${i}" type="number" value="${t.to == null ? '' : t.to}" placeholder="∞" style="width:80px"></td><td><input class="inp sm tr" name="tr_${i}" type="number" value="${t.rate}" style="width:120px"></td><td>${U.iconBtn('trash', 'rm', 'Bỏ', { 'data-i': i })}</td></tr>`).join('');
    const m = U.drawer({ title: r.id ? 'Payroll Rule ' + r.code : 'Payroll Rule Version mới', sub: 'Bậc hiệu suất → mức lương/phòng; version hóa theo ngày hiệu lực – kỳ cũ không đổi (§4.26.4)', body: `<div class="form-grid">${U.field({ label: 'Mã version', req: true, input: U.input({ name: 'code', value: r.code || ('PR-' + F.today().slice(0, 7).replace('-', '') + '-' + F.pad(Q.payrollRules().length + 1, 2)) }) })}${U.field({ label: 'Tên', input: U.input({ name: 'name', value: r.name || '' }) })}${U.field({ label: 'Hiệu lực từ', req: true, input: U.date({ name: 'effectiveFrom', value: r.effectiveFrom || F.today() }) })}${U.field({ label: 'Đến', input: U.date({ name: 'effectiveTo', value: r.effectiveTo || '' }) })}${U.field({ label: 'Đối tượng (vai trò phân công)', input: U.select({ name: 'role', value: (r.roles || ['manager'])[0], options: [['manager', 'Phụ trách chính'], ['support', 'Hỗ trợ']] }) })}${U.field({ label: 'Công thức Tổng DT thu được', input: U.select({ name: 'collectedFormula', value: r.collectedFormula || 'M123_MINUS_SERVICE_PLUS_EXTRA', options: [['M123_MINUS_SERVICE_PLUS_EXTRA', 'M1+M2+M3 − Dịch vụ + Thu thêm'], ['M123_PLUS_EXTRA', 'M1+M2+M3 + Thu thêm'], ['M123_MINUS_SERVICE', 'M1+M2+M3 − Dịch vụ'], ['M123', 'M1+M2+M3']] }), help: 'Chờ chốt nghiệp vụ (§4.26.3)' })}</div><div class="tbl-wrap mt12"><table class="tbl compact"><thead><tr><th>Hiệu suất từ (%)</th><th>Đến (%)</th><th class="num">Mức lương/phòng (VND)</th><th></th></tr></thead><tbody id="tiers">${rowsHtml(tiers)}</tbody></table></div>${U.btn({ label: 'Thêm bậc', icon: 'plus', act: 'add', cls: 'btn-dashed btn-block mt8', size: 'btn-sm' })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: r.note || '' }), cls: 'mt12' })}`, footer: footer('Lưu rule') });
    const el = m.el; const read = () => [...el.querySelectorAll('#tiers tr')].map(tr => ({ from: tr.querySelector('input[name^=tf_]').value, to: tr.querySelector('input[name^=tt_]').value, rate: tr.querySelector('input[name^=tr_]').value }));
    U.bind(el, { cancel: () => m.close(), add: () => { const ts = read(); ts.push({ from: 0, to: '', rate: 0 }); el.querySelector('#tiers').innerHTML = rowsHtml(ts); }, rm: (b) => { const ts = read(); ts.splice(Number(b.dataset.i), 1); el.querySelector('#tiers').innerHTML = rowsHtml(ts); }, save: () => { const d = m.data(); run(m, () => X.savePayrollRule({ id: r.id, code: d.code, name: d.name, effectiveFrom: d.effectiveFrom, effectiveTo: d.effectiveTo, roles: [d.role], collectedFormula: d.collectedFormula, tiers: read(), note: d.note }), 'Đã lưu Payroll Rule'); } });
  };

  /* ---------- Chi lương (§4.26.8) ---------- */
  Fm.salaryPayment = (s) => {
    const e = Q.employee(s.employeeId); const rem = Math.max(0, s.amountDue - s.amountPaid); const ba = s.bankAccount || {};
    const m = U.drawer({ title: 'Ghi nhận chi lương – ' + esc(e.name), sub: s.code + ' · kỳ ' + F.periodLabel(s.period) + ' · ' + Q.label('salaryPay', s.status), body: `<div class="grid grid-3 mb12">${U.miniStat({ label: 'Phải chi', value: F.vnd(s.amountDue), icon: 'banknote', tone: 'blue' })}${U.miniStat({ label: 'Đã chi', value: F.vnd(s.amountPaid), icon: 'check-circle', tone: 'green' })}${U.miniStat({ label: 'Còn phải chi', value: F.vnd(rem), icon: 'clock', tone: 'amber' })}</div>
      ${U.kv([['Ngân hàng / TK nhận (snapshot)', esc((ba.bank || '-') + ' · ' + (ba.number || '-'))], ['Tên tài khoản', esc(ba.name || '-')]], 'one')}
      <div class="form-grid mt12">${U.field({ label: 'Số tiền chi (VND)', req: true, input: U.money({ name: 'amount', value: rem }), help: 'Cho phép chi một phần (partial)' })}${U.field({ label: 'Ngày chi', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'method', value: 'Chuyển khoản', options: ['Chuyển khoản', 'Tiền mặt'] }) })}${U.field({ label: 'Mã tham chiếu giao dịch', input: U.input({ name: 'ref', placeholder: 'UNC-…' }) })}</div>
      <div class="field mt12"><label>Chứng từ thanh toán</label>${U.dropzone({ name: 'ev', hint: 'UNC / ảnh chuyển khoản (mô phỏng)' })}</div>${U.field({ label: 'Ghi chú', input: U.input({ name: 'note' }), cls: 'mt12' })}
      ${(s.payments || []).length ? '<div class="small bold mt12">Lịch sử chi</div><table class="tbl compact mt8"><thead><tr><th>Ngày</th><th class="num">Số tiền</th><th>PT</th><th>Mã GD</th><th>Người thực hiện</th></tr></thead><tbody>' + s.payments.map(p => `<tr><td>${F.date(p.date)}</td><td class="num">${p.failed ? '<span class="red">lỗi</span>' : F.vnd(p.amount)}</td><td>${esc(p.method || '')}</td><td>${esc(p.ref || '')}${p.evidence ? ' · ' + esc(p.evidence) : ''}</td><td>${esc(Q.userName(p.by))}</td></tr>`).join('') + '</tbody></table>' : ''}`, footer: footer('Ghi nhận chi', 'banknote', '', 'salary-record') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; run(m, () => X.recordSalaryPayment(s.id, { amount: d.amount, date: d.date, method: d.method, ref: d.ref, evidence: f ? f.name : '', note: d.note }), r => 'Đã ghi nhận chi lương – ' + Q.label('salaryPay', r.status)); } });
  };
  Fm.bulkSalary = (period, ids) => { const rows = Q.salaryPayments({ period }).filter(s => (!ids || !ids.length || ids.includes(s.id)) && ['unpaid', 'partial', 'failed'].includes(s.status)); const total = F.sum(rows, s => s.amountDue - s.amountPaid); const m = U.modal({ title: 'Chi lương hàng loạt ' + F.periodLabel(period), size: 'sm', sub: rows.length + ' nhân viên · ' + F.vnd(total), body: `${U.field({ label: 'Ngày chi', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', input: U.select({ name: 'method', value: 'Chuyển khoản', options: ['Chuyển khoản', 'Tiền mặt'] }), cls: 'mt12' })}${U.field({ label: 'Mã tham chiếu (tiền tố)', input: U.input({ name: 'ref', value: 'UNC-' + period.replace('-', '') }), cls: 'mt12' })}<div class="field mt12"><label>Chứng từ (bảng kê chi)</label>${U.dropzone({ name: 'ev', hint: 'Bảng kê UNC (mô phỏng)' })}</div>${U.note('info', '', 'Mỗi nhân viên được chi đủ phần còn phải chi; khoản Chi lỗi được chi lại.')}`, footer: footer('Chi ' + rows.length + ' khoản', 'banknote') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; run(m, () => X.bulkSalaryPayments(period, { ids: rows.map(s => s.id), date: d.date, method: d.method, ref: d.ref, evidence: f ? f.name : '' }), r => 'Đã chi ' + r.count + ' khoản – ' + F.vnd(r.total)); } }); };
  Fm.salaryFail = async (s) => { const r = await U.confirm({ title: 'Đánh dấu chi lỗi ' + s.code + '?', text: 'Giao dịch không thành công (sai TK, ngân hàng từ chối…). Có thể chi lại sau.', ok: 'Ghi nhận lỗi', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) }) }); if (r) { try { X.markSalaryFailed(s.id, r.reason); U.toast('ok', 'Đã ghi nhận chi lỗi'); refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } };
  Fm.salaryCancel = async (s) => { const r = await U.confirm({ title: 'Hủy khoản chi ' + s.code + '?', text: 'Chỉ hủy khoản chưa chi; giữ audit.', ok: 'Hủy khoản chi', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }) }) }); if (r) { try { X.cancelSalaryPayment(s.id, r.reason); U.toast('ok', 'Đã hủy'); refresh(); } catch (e) { U.toast('err', 'Lỗi', e.message); } } };
  Fm.salaryAdjust = (s) => { const m = U.modal({ title: 'Điều chỉnh khoản chi ' + s.code, size: 'sm', body: `${U.field({ label: 'Số phải chi mới (VND)', req: true, input: U.money({ name: 'amountDue', value: s.amountDue }) })}${U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason' }), cls: 'mt12' })}`, footer: footer('Lưu điều chỉnh') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.adjustSalaryPayment(s.id, { amountDue: d.amountDue, reason: d.reason }), 'Đã điều chỉnh khoản chi'); } }); };
})(window.TH);
