/* Form/drawer dùng chung giữa các trang */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, X = TH.actions, St = TH.store, esc = F.esc;
  const Fm = {};
  const refresh = () => { TH.layout.refreshTop(); TH.router.refresh(); };
  const footer = (saveLabel = 'Lưu', icon = 'save', extra = '') => extra + U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: saveLabel, act: 'save', cls: 'btn-primary', icon });
  const run = (m, fn, okMsg) => { try { const r = fn(); if (r && r.duplicate) U.toast('warn', 'Yêu cầu trùng – không tạo thêm', 'Idempotency key đã tồn tại'); else if (okMsg) U.toast('ok', typeof okMsg === 'function' ? okMsg(r) : okMsg); m.close(true); refresh(); return r; } catch (e) { U.toast('err', 'Không lưu được', e.message); U.setErrors(m.el, e.fields || {}); } };
  const opt = {
    buildings: (all) => St.where('buildings', b => !b.stub || all).map(b => [b.id, b.name + ' (' + b.code + ')']),
    tenants: () => St.all('tenants').slice().sort((a, b) => a.name.localeCompare(b.name, 'vi')).map(t => [t.id, t.name + ' (' + t.code + ') – ' + t.phone]),
    managers: () => Q.managers().map(u => [u.id, u.name]),
    landlords: () => St.all('landlords').map(l => [l.id, l.name + ' (' + l.code + ')']),
    methods: () => St.where('payMethods', m => m.status === 'active').map(m => m.name),
    groups: () => St.all('expenseGroups').map(g => g.name),
    roomsReady: () => St.where('rooms', r => ['ready', 'held'].includes(r.status)).sort((a, b) => a.code.localeCompare(b.code)).map(r => [r.id, r.code + ' · ' + Q.building(r.buildingId).name + ' · ' + F.vnd(r.price)]),
  };
  Fm.opt = opt;

  /* ---- Khách thuê ---- */
  Fm.tenant = (t = {}, cb) => {
    const m = U.drawer({ title: t.id ? 'Sửa khách thuê' : 'Thêm khách thuê', sub: t.id ? t.code : 'Tạo hồ sơ khách thuê mới. Trạng thái thuê được suy ra từ hợp đồng.', body: `<div class="form-grid">
      ${U.field({ label: 'Họ tên', req: true, name: 'name', input: U.input({ name: 'name', value: t.name || '', placeholder: 'Nhập họ và tên' }), cls: 'span2' })}
      ${U.field({ label: 'Số điện thoại', req: true, name: 'phone', input: U.input({ name: 'phone', value: t.phone || '', placeholder: '09xx xxx xxx', icon: 'phone' }) })}
      ${U.field({ label: 'Zalo', input: U.input({ name: 'zalo', value: t.zalo || '', placeholder: 'SĐT Zalo (mặc định = SĐT)' }), help: 'SĐT không phải bằng chứng đã xác minh tài khoản Zalo (FR-CUS-01)' })}
      ${U.field({ label: 'Email', input: U.input({ name: 'email', value: t.email || '', type: 'email', placeholder: 'email@domain.com', icon: 'mail' }) })}
      ${U.field({ label: 'CMND/CCCD', input: U.input({ name: 'idNumber', value: t.idNumber || '', placeholder: '12 số' }), help: 'Tùy chọn – nếu có phải đúng 12 số' })}
      ${U.field({ label: 'Ngày sinh', input: U.date({ name: 'dob', value: t.dob || '' }) })}
      ${U.field({ label: 'Nghề nghiệp', input: U.input({ name: 'job', value: t.job || '', placeholder: 'Nhân viên văn phòng…' }) })}
      ${U.field({ label: 'Phân khúc khách', input: U.select({ name: 'segment', value: t.segment || '', all: 'Chưa xác định', options: ['Văn phòng', 'Sinh viên', 'Gia đình', 'Chuyên gia', 'Lao động'] }), help: 'Khai báo trực tiếp, không suy từ nghề nghiệp (BR-18)' })}
      ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: t.managerId || (TH.auth.session() || {}).userId, options: opt.managers() }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: t.note || '', placeholder: 'Phương tiện, yêu cầu đặc biệt…' }), cls: 'span2' })}
      ${U.check({ name: 'verified', label: 'Đã xác minh Zalo (đánh dấu thủ công)', checked: !!t.verified })}</div>`, footer: footer(t.id ? 'Lưu thay đổi' : 'Lưu khách thuê', 'user-plus') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (t.id) d.id = t.id; const r = run(m, () => X.saveTenant(d), (r) => 'Đã lưu khách ' + r.name + ' (' + r.code + ')'); if (r && cb) cb(r); } });
    return m;
  };
  /* ---- Tòa ---- */
  Fm.building = (b = {}) => {
    const m = U.drawer({ title: b.id ? 'Sửa tòa nhà' : 'Thêm tòa nhà', sub: 'Thông tin tòa, chủ nhà và chu kỳ trả chủ nhà (3/4/6 tháng – BR-11)', body: `<div class="form-grid">
      ${U.field({ label: 'Mã tòa', input: U.input({ name: 'code', value: b.code || '', placeholder: 'TH-XXX-11 (để trống tự sinh)' }) })}
      ${U.field({ label: 'Tên tòa', req: true, name: 'name', input: U.input({ name: 'name', value: b.name || '', placeholder: 'Tòa …' }) })}
      ${U.field({ label: 'Địa chỉ', req: true, name: 'address', input: U.input({ name: 'address', value: b.address || '', icon: 'map-pin' }), cls: 'span2' })}
      ${U.field({ label: 'Khu vực', input: U.input({ name: 'district', value: b.district || '', placeholder: 'Quận/Huyện', attrs: { list: 'dl-district' } }) })}<datalist id="dl-district">${Q.districts().map(d => `<option value="${esc(d)}">`).join('')}</datalist>
      ${U.field({ label: 'Tiền tố mã phòng', input: U.input({ name: 'prefix', value: b.prefix || '', placeholder: 'A', attrs: { maxlength: 2 } }), help: 'VD: A → A.01.01' })}
      ${U.field({ label: 'Số tầng', input: U.input({ name: 'floors', type: 'number', value: b.floors || 1 }) })}
      ${U.field({ label: 'Số phòng / tầng (dự kiến)', input: U.input({ name: 'perFloor', type: 'number', value: b.perFloor || 0 }) })}
      ${U.field({ label: 'Chủ nhà', input: U.select({ name: 'landlordId', value: b.landlordId || '', all: 'Chưa gán', options: opt.landlords() }) })}
      ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: b.managerId || '', options: opt.managers() }) })}
      ${U.field({ label: 'Chu kỳ trả chủ nhà', input: U.select({ name: 'payCycle', value: b.payCycle || 3, options: [[3, '3 tháng/lần'], [4, '4 tháng/lần'], [6, '6 tháng/lần']] }) })}
      ${U.field({ label: 'Ngày trả trong kỳ', input: U.input({ name: 'payDay', type: 'number', value: b.payDay || 5 }) })}
      ${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: b.status || 'active', options: [['active', 'Đang hoạt động'], ['maintenance', 'Bảo trì, sửa chữa'], ['inactive', 'Tạm ngừng']] }) })}
      ${U.field({ label: 'Trạng thái ĐKKD', input: U.select({ name: 'license', value: b.license || 'Đã đăng ký', options: ['Đã đăng ký', 'Đang làm hồ sơ', 'Chưa đăng ký'] }) })}</div>`, footer: footer(b.id ? 'Lưu thay đổi' : 'Lưu tòa nhà') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (b.id) d.id = b.id; d.floors = Number(d.floors) || 1; d.perFloor = Number(d.perFloor) || 0; d.payCycle = Number(d.payCycle); d.payDay = Number(d.payDay) || 5; run(m, () => X.saveBuilding(d), r => 'Đã lưu tòa ' + r.name); } });
  };
  /* ---- Phòng ---- */
  Fm.room = (r = {}, buildingId) => {
    const svcs = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const m = U.drawer({ title: r.id ? 'Sửa phòng ' + r.code : 'Thêm phòng', sub: 'Mã phòng duy nhất trong tòa (FR-BLD-03). Dịch vụ mặc định sẽ nạp vào hợp đồng mới.', body: `<div class="form-grid">
      ${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: r.buildingId || buildingId || '', placeholder: 'Chọn tòa', options: opt.buildings() }) })}
      ${U.field({ label: 'Mã phòng', req: true, name: 'code', input: U.input({ name: 'code', value: r.code || '', placeholder: 'A.01.01' }) })}
      ${U.field({ label: 'Tầng', input: U.input({ name: 'floor', type: 'number', value: r.floor || 1 }) })}
      ${U.field({ label: 'Loại phòng', input: U.select({ name: 'type', value: r.type || 'Phòng đơn', options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'] }) })}
      ${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'area', type: 'number', value: r.area || 25 }) })}
      ${U.field({ label: 'Giá tham chiếu', req: true, input: U.money({ name: 'price', value: r.price || '' }) })}
      ${U.field({ label: 'Hướng phòng', input: U.input({ name: 'direction', value: r.direction || '' }) })}
      ${U.field({ label: 'Nội thất', input: U.select({ name: 'furniture', value: r.furniture || 'Cơ bản', options: ['Đầy đủ', 'Cơ bản', 'Trống'] }) })}
      ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: r.managerId || '', all: 'Theo tòa', options: opt.managers() }) })}
      ${r.id ? '' : U.field({ label: 'Trạng thái ban đầu', input: U.select({ name: 'status', value: 'ready', options: [['ready', 'Sẵn sàng'], ['maintenance', 'Bảo trì'], ['inactive', 'Ngừng sử dụng']] }) })}
      <div class="field span2"><label>Dịch vụ mặc định</label><div class="row wrap gap12">${svcs.map(s => U.check({ name: 'svc_' + s.id, label: s.name + ' – ' + F.vnd(s.price) + '/' + s.unit, checked: (r.defaultServiceIds || []).includes(s.id) })).join('')}</div></div></div>`, footer: footer(r.id ? 'Lưu thay đổi' : 'Lưu phòng') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const ids = svcs.filter(s => d['svc_' + s.id]).map(s => s.id); svcs.forEach(s => delete d['svc_' + s.id]); d.defaultServiceIds = ids; d.floor = Number(d.floor) || 1; d.area = Number(d.area) || 0; if (r.id) d.id = r.id; if (!d.price) throw new Error('Giá tham chiếu là bắt buộc'); run(m, () => X.saveRoom(d), x => 'Đã lưu phòng ' + x.code); } });
  };
  Fm.roomsBulk = (buildingId) => {
    const b = Q.building(buildingId);
    const m = U.modal({ title: 'Tạo nhiều phòng', sub: 'Sinh mã theo mẫu ' + b.prefix + '.<tầng>.<số>, bỏ qua mã đã tồn tại', body: `<div class="form-grid">${U.field({ label: 'Từ tầng', input: U.input({ name: 'floorFrom', type: 'number', value: (b.floors || 0) + 1 }) })}${U.field({ label: 'Đến tầng', input: U.input({ name: 'floorTo', type: 'number', value: (b.floors || 0) + 1 }) })}${U.field({ label: 'Số phòng mỗi tầng', input: U.input({ name: 'perFloor', type: 'number', value: b.perFloor || 4 }) })}${U.field({ label: 'Giá tham chiếu', input: U.money({ name: 'price', value: 5000000 }) })}${U.field({ label: 'Loại phòng', input: U.select({ name: 'type', value: 'Phòng đơn', options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'] }), cls: 'span2' })}</div>`, footer: footer('Tạo phòng', 'grid') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.createRoomsBulk({ buildingId, floorFrom: Number(d.floorFrom), floorTo: Number(d.floorTo), perFloor: Number(d.perFloor), price: d.price, type: d.type }), r => 'Đã tạo ' + r.made.length + ' phòng' + (r.skipped ? ', bỏ qua ' + r.skipped + ' trùng mã' : '')); } });
  };
  Fm.roomStatus = (room) => {
    const m = U.modal({ title: 'Đổi trạng thái phòng ' + room.code, size: 'sm', body: U.field({ label: 'Trạng thái mới', input: U.select({ name: 'status', value: room.status === 'maintenance' ? 'ready' : 'maintenance', options: [['ready', 'Sẵn sàng'], ['maintenance', 'Bảo trì'], ['inactive', 'Ngừng sử dụng']].filter(([k]) => k !== room.status) }) }) + U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', placeholder: 'Lý do…' }), cls: 'mt12' }), footer: footer('Cập nhật') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.setRoomStatus(room.id, d.status, d.note), 'Đã đổi trạng thái phòng'); } });
  };
  Fm.hold = (roomId) => {
    const r = Q.room(roomId);
    const m = U.modal({ title: 'Giữ chỗ phòng ' + r.code, sub: 'Phòng chuyển sang Giữ chỗ, khóa khỏi danh sách sẵn sàng đến hết hạn giữ', body: `<div class="form-grid">${U.field({ label: 'Khách', req: true, input: U.select({ name: 'tenantId', placeholder: 'Chọn khách', options: opt.tenants() }), cls: 'span2', help: 'Chưa có khách? Tạo tại Khách thuê → Thêm khách thuê' })}${U.field({ label: 'Giữ đến ngày', req: true, input: U.date({ name: 'until', value: F.addDays(F.today(), 7) }) })}${U.field({ label: 'Tiền giữ chỗ', input: U.money({ name: 'deposit', value: 2000000 }) })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note' }), cls: 'span2' })}</div>`, footer: footer('Xác nhận giữ chỗ', 'clock') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.roomId = roomId; run(m, () => X.holdRoom(d), 'Đã giữ chỗ phòng ' + r.code); } });
  };
  /* ---- Chủ nhà ---- */
  Fm.landlord = (l = {}) => {
    const m = U.drawer({ title: l.id ? 'Sửa chủ nhà' : 'Thêm chủ nhà', sub: 'Hồ sơ chủ nhà / đối tác cho thuê đầu vào (FR-BLD-01/06)', body: `<div class="form-grid">
      ${U.field({ label: 'Loại', input: U.select({ name: 'type', value: l.type || 'person', options: [['person', 'Cá nhân'], ['company', 'Công ty']] }) })}
      ${U.field({ label: 'Tên chủ nhà / đối tác', req: true, name: 'name', input: U.input({ name: 'name', value: l.name || '' }) })}
      ${U.field({ label: 'Số điện thoại', req: true, name: 'phone', input: U.input({ name: 'phone', value: l.phone || '', icon: 'phone' }) })}
      ${U.field({ label: 'Email', input: U.input({ name: 'email', value: l.email || '', icon: 'mail' }) })}
      ${U.field({ label: 'Mã số thuế', input: U.input({ name: 'taxCode', value: l.taxCode || '' }) })}
      ${U.field({ label: 'Tài khoản nhận tiền', input: U.input({ name: 'bankAccount', value: l.bankAccount || '', placeholder: 'Ngân hàng – số TK' }) })}
      ${U.field({ label: 'Địa chỉ', input: U.input({ name: 'address', value: l.address || '' }), cls: 'span2' })}
      ${U.field({ label: 'Chu kỳ trả mặc định', input: U.select({ name: 'cycleMonths', value: l.cycleMonths || 3, options: [[3, '3 tháng'], [4, '4 tháng'], [6, '6 tháng']] }) })}
      ${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: l.status || 'active', options: [['active', 'Đang hợp tác'], ['expiring', 'Sắp hết hạn'], ['paused', 'Tạm ngừng']] }) })}
      <div class="field span2"><label>Tòa liên kết</label><div class="row wrap gap12">${opt.buildings(true).map(([id, nm]) => U.check({ name: 'b_' + id, label: nm, checked: (l.buildingIds || []).includes(id) })).join('')}</div></div></div>`, footer: footer(l.id ? 'Lưu thay đổi' : 'Lưu chủ nhà') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = opt.buildings(true).filter(([id]) => d['b_' + id]).map(([id]) => id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); d.cycleMonths = Number(d.cycleMonths); if (l.id) d.id = l.id; run(m, () => X.saveLandlord(d), r => 'Đã lưu chủ nhà ' + r.name); } });
  };
  Fm.landlordContract = (landlordId, c = {}) => {
    const l = St.get('landlords', landlordId);
    const m = U.drawer({ title: c.id ? 'Sửa hợp đồng đầu vào' : 'Thêm hợp đồng đầu vào', sub: l.name + ' – chu kỳ trả 3/4/6 tháng theo thỏa thuận (BR-11)', body: `<div class="form-grid">
      ${U.field({ label: 'Ngày ký', input: U.date({ name: 'signedDate', value: c.signedDate || F.today() }) })}${U.field({ label: 'Loại hợp đồng', input: U.select({ name: 'type', value: c.type || 'Hợp đồng thuê tòa nhà', options: ['Hợp đồng thuê tòa nhà', 'Hợp đồng hợp tác kinh doanh'] }) })}
      ${U.field({ label: 'Ngày bắt đầu', req: true, input: U.date({ name: 'start', value: c.start || F.today() }) })}${U.field({ label: 'Ngày kết thúc', req: true, input: U.date({ name: 'end', value: c.end || F.addMonths(F.today(), 36) }) })}
      ${U.field({ label: 'Giá thuê / tháng', req: true, input: U.money({ name: 'rent', value: c.rent || '' }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: c.deposit || '' }) })}
      ${U.field({ label: 'Thời gian giữ giá (tháng)', input: U.input({ name: 'priceHoldMonths', type: 'number', value: c.priceHoldMonths || 24 }), help: 'Chủ nhà không tăng giá trong thời gian giữ giá (Q05)' })}${U.field({ label: 'Chu kỳ trả', req: true, input: U.select({ name: 'cycleMonths', value: c.cycleMonths || l.cycleMonths || 3, options: [[3, '3 tháng/lần'], [4, '4 tháng/lần'], [6, '6 tháng/lần']] }) })}
      <div class="field span2"><label>Tòa liên kết<span class="req">*</span></label><div class="row wrap gap12">${opt.buildings(true).map(([id, nm]) => U.check({ name: 'b_' + id, label: nm, checked: (c.buildingIds || l.buildingIds || []).includes(id) })).join('')}</div></div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: c.note || '' }), cls: 'span2' })}</div>`, footer: footer('Lưu hợp đồng') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = opt.buildings(true).filter(([id]) => d['b_' + id]).map(([id]) => id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); if (!d.buildingIds.length) throw new Error('Chọn ít nhất một tòa'); d.landlordId = landlordId; d.cycleMonths = Number(d.cycleMonths); d.priceHoldMonths = Number(d.priceHoldMonths); if (c.id) d.id = c.id; run(m, () => X.saveLandlordContract(d), 'Đã lưu hợp đồng đầu vào'); } });
  };
  Fm.landlordSchedule = (lc) => {
    const m = U.modal({ title: 'Tạo lịch thanh toán', size: 'sm', sub: 'Sinh các kỳ theo chu kỳ ' + lc.cycleMonths + ' tháng, số tiền = giá thuê × chu kỳ', body: `<div class="form-grid">${U.field({ label: 'Kỳ đầu từ ngày', input: U.date({ name: 'from', value: lc.start }) })}${U.field({ label: 'Số kỳ', input: U.input({ name: 'periods', type: 'number', value: 4 }) })}</div>`, footer: footer('Tạo lịch', 'calendar') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.generateLandlordSchedule(lc.id, { from: d.from, periods: Number(d.periods) }), r => 'Đã tạo ' + r.length + ' kỳ thanh toán'); } });
  };
  Fm.landlordPayment = (lc) => {
    const m = U.modal({ title: 'Thêm kỳ thanh toán', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Tên kỳ', input: U.input({ name: 'periodLabel', value: 'Kỳ ' + (Q.landlordPayments(lc.landlordId).length + 1) }) })}${U.field({ label: 'Hạn thanh toán', req: true, input: U.date({ name: 'dueDate', value: F.today() }) })}${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount', value: lc.rent * lc.cycleMonths }), cls: 'span2' })}</div>`, footer: footer('Thêm kỳ') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.addLandlordPayment(Object.assign(d, { landlordContractId: lc.id, landlordId: lc.landlordId, buildingId: lc.buildingIds[0] })), 'Đã thêm kỳ thanh toán'); } });
  };
  Fm.landlordPaid = (p) => {
    const m = U.modal({ title: 'Ghi nhận đã trả chủ nhà', size: 'sm', sub: p.periodLabel + ' – hạn ' + F.date(p.dueDate), body: `<div class="form-grid">${U.field({ label: 'Ngày thanh toán', req: true, input: U.date({ name: 'paidDate', value: F.today() }) })}${U.field({ label: 'Số tiền', input: U.money({ name: 'amount', value: p.amount }) })}${U.field({ label: 'Bằng chứng', input: U.dropzone({ name: 'ev', hint: 'PDF/JPG ủy nhiệm chi' }), cls: 'span2' })}</div>`, footer: footer('Xác nhận đã trả', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; run(m, () => X.markLandlordPaid(p.id, { paidDate: d.paidDate, amount: d.amount, evidence: f ? f.name : 'uy_nhiem_chi.pdf' }), 'Đã ghi nhận thanh toán chủ nhà'); } });
  };
  /* ---- Hợp đồng ---- */
  Fm.renew = (c) => {
    const m = U.modal({ title: 'Gia hạn hợp đồng ' + c.code, sub: 'Tạo hợp đồng mới liên kết hợp đồng cũ; hợp đồng cũ chuyển Đã kết thúc ngày ' + F.date(c.end) + ' (FR-CUS-04)', body: `<div class="form-grid">${U.field({ label: 'Ngày bắt đầu mới', input: U.input({ name: 'startX', value: F.date(F.addDays(c.end, 1)), readonly: true }) })}${U.field({ label: 'Ngày kết thúc mới', req: true, input: U.date({ name: 'end', value: F.addDays(F.addMonths(c.end, 12), 0) }) })}${U.field({ label: 'Giá thuê mới', input: U.money({ name: 'price', value: c.price }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: c.deposit }), help: 'Giữ nguyên cọc đang giữ nếu không đổi' })}</div>`, footer: footer('Xác nhận gia hạn', 'refresh') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const r = run(m, () => X.renewContract(c.id, { end: d.end, price: d.price, deposit: d.deposit }), r => 'Đã gia hạn → ' + r.code); if (r) TH.go('#/contracts/' + r.id); } });
  };
  Fm.terminate = (c) => {
    const room = Q.room(c.roomId); const debt = Q.contractDebt(c.id);
    const m = U.modal({ title: 'Kết thúc hợp đồng ' + c.code, sub: Q.tenant(c.tenantId).name + ' – phòng ' + room.code, body: `${debt > 0 ? U.note('warn', 'Còn công nợ ' + F.vnd(debt) + ' đ', 'Công nợ sẽ hiển thị trong hồ sơ hoàn cọc; không tự bù trừ vào cọc (OI-07).') : U.note('ok', 'Không còn công nợ', 'Các hóa đơn của hợp đồng đã được thu đủ.')}<div class="form-grid mt12">${U.field({ label: 'Ngày kết thúc thực tế', req: true, input: U.date({ name: 'actualEnd', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.select({ name: 'reason', value: 'Hết hạn, không gia hạn', options: ['Hết hạn, không gia hạn', 'Khách trả phòng sớm', 'Phá hợp đồng', 'Chuyển phòng', 'Khác'] }) })}<div class="span2 col gap4">${U.check({ name: 'toCleaning', label: 'Chuyển phòng sang <b>Chờ dọn</b> (BR-02: phòng chỉ Sẵn sàng sau khi xác nhận dọn xong). Bỏ tick = phòng Sẵn sàng ngay, không qua bước dọn.', checked: true })}${U.check({ name: 'createRefund', label: 'Tạo hồ sơ hoàn cọc (Nháp) với cọc ' + F.vnd(c.deposit) + ' đ', checked: true })}</div></div>`, footer: footer('Xác nhận kết thúc', 'x-circle') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const r = run(m, () => X.terminateContract(c.id, { actualEnd: d.actualEnd, reason: d.reason, toCleaning: d.toCleaning, createRefund: d.createRefund }), r => 'Đã kết thúc hợp đồng' + (r.refund ? ' – tạo hồ sơ hoàn cọc ' + r.refund.code : '')); if (r && r.refund) setTimeout(() => U.toast('info', 'Bước tiếp theo', 'Lập phương án hoàn cọc tại Tài chính → Hoàn cọc'), 1200); } });
  };
  Fm.cancelContract = async (c) => { const r = await U.confirm({ title: 'Hủy hợp đồng nháp ' + c.code + '?', text: 'Hợp đồng chuyển trạng thái Hủy, phòng không đổi.', ok: 'Hủy hợp đồng', danger: true, body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }) }); if (r) { X.cancelContract(c.id, r.reason); U.toast('ok', 'Đã hủy hợp đồng'); refresh(); } };
  /* ---- Thu tiền (drawer lớn) ---- */
  Fm.payment = ({ tenantId, invoiceId, onDone } = {}) => {
    let tId = tenantId || (invoiceId ? St.get('invoices', invoiceId).tenantId : '');
    const openInvoices = (tid) => St.where('invoices', i => i.tenantId === tid && i.docStatus !== 'draft' && i.docStatus !== 'cancelled' && Q.invRemaining(i) > 0).sort((a, b) => F.cmp(a.dueDate, b.dueDate));
    const allocTable = (tid, amount, prefill) => { const invs = openInvoices(tid); if (!invs.length) return U.empty({ icon: 'check-circle', title: 'Khách không còn hóa đơn nợ', text: 'Khoản thu sẽ ghi nhận là chưa phân bổ.' }); return `<table class="tbl compact"><thead><tr><th></th><th>Hóa đơn</th><th>Hạn thanh toán</th><th class="num">Còn lại (VND)</th><th class="num">Số tiền phân bổ (VND)</th></tr></thead><tbody>${invs.map(i => { const rem = Q.invRemaining(i); const v = prefill && prefill[i.id] != null ? prefill[i.id] : 0; return `<tr><td><input type="checkbox" data-alloc-chk="${i.id}" ${v > 0 ? 'checked' : ''}></td><td><a class="link" href="#/invoices/${i.id}">${i.code}</a><div class="xs muted">${F.periodLabel(i.period)}${Q.invOverdue(i) ? ' · <span class="red">quá hạn ' + Q.invOverdueDays(i) + ' ngày</span>' : ''}</div></td><td>${F.date(i.dueDate)}</td><td class="num">${F.vnd(rem)}</td><td class="num"><input class="inp sm tr" data-money data-alloc="${i.id}" data-rem="${rem}" value="${v ? F.vnd(v) : '0'}" style="width:130px"></td></tr>`; }).join('')}</tbody></table>`; };
    const body = `<div data-guide="pay-form">${U.field({ label: 'Khách thuê', req: true, input: U.select({ name: 'tenantId', value: tId, placeholder: 'Chọn khách thuê', options: opt.tenants(), attrs: { 'data-on': 'tenant' } }) })}
      <div id="pay-tenant-card" class="mt8"></div>
      <div class="form-grid mt12">${U.field({ label: 'Ngày thu', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount', value: '', attrs: { id: 'pay-amount' } }) })}</div>
      ${U.field({ label: 'Phương thức thanh toán', req: true, input: U.select({ name: 'method', value: 'Chuyển khoản', options: opt.methods() }), cls: 'mt12' })}
      ${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref', placeholder: 'CK289104' }), help: 'Mã giao dịch ngân hàng, mã phiếu thu...', cls: 'mt12' })}
      <div class="field mt12"><label>File bằng chứng</label>${U.dropzone({ name: 'evidence', hint: 'Hỗ trợ JPG, PNG, PDF (tối đa 5MB)' })}</div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', placeholder: 'Khách thanh toán tiền nhà tháng 10' }), cls: 'mt12' })}
      <div class="fs"><div class="fs-h">${I('clipboard-check')}Phân bổ vào hóa đơn<span class="ml-auto">${U.btn({ label: 'Tự động phân bổ', icon: 'refresh', act: 'auto', cls: 'btn-light', size: 'btn-sm' })}</span></div><div id="alloc-wrap" class="tbl-wrap"></div>
      <div class="sum-box mt12" id="alloc-sum"></div></div></div>`;
    const m = U.drawer({ title: 'Ghi nhận thu tiền', sub: 'Tạo phiếu thu và phân bổ vào các hóa đơn', body, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Review', act: 'review', cls: 'btn-light' }) + U.btn({ label: 'Xác nhận ghi nhận', act: 'save', cls: 'btn-primary', icon: 'check' }) });
    const el = m.el; const key = F.uid('pay');
    const tenantCard = () => { const c = el.querySelector('#pay-tenant-card'); const t = Q.tenant(tId); if (!t.id) { c.innerHTML = ''; return; } const room = Q.tenantRoom(t); c.innerHTML = `<div class="row" style="border:1px solid var(--border);border-radius:9px;padding:8px 12px">${U.avatar(t.name, 'sm')}<div class="grow"><b>${esc(t.name)}</b><div class="xs muted">${room ? room.code + ' – ' + Q.building(room.buildingId).name + ' | ' : ''}${esc(t.phone)} · Công nợ: <span class="red bold">${F.vnd(Q.tenantDebt(t.id))}</span></div></div></div>`; };
    const recalc = () => { const amt = F.num(el.querySelector('#pay-amount').value); let alloc = 0; el.querySelectorAll('[data-alloc]').forEach(inp => { const chk = el.querySelector(`[data-alloc-chk="${inp.dataset.alloc}"]`); const v = chk && chk.checked ? F.num(inp.value) : 0; alloc += v; inp.classList.toggle('red', v > Number(inp.dataset.rem)); }); const un = amt - alloc; el.querySelector('#alloc-sum').innerHTML = `<div class="it"><span>Khoản thu</span><b>${F.vnd(amt)}</b></div><div class="it"><span>Đã phân bổ</span><b class="green">${F.vnd(alloc)}</b></div><div class="it"><span>Chưa phân bổ</span><b class="${un < 0 ? 'red' : un > 0 ? 'amber' : 'red'}">${F.vnd(un)}</b></div>${un < 0 ? '<div class="xs red">Tổng phân bổ vượt khoản thu</div>' : ''}`; };
    const renderAlloc = (prefill) => { el.querySelector('#alloc-wrap').innerHTML = allocTable(tId, F.num(el.querySelector('#pay-amount').value), prefill); recalc(); };
    const autoAlloc = () => { let amt = F.num(el.querySelector('#pay-amount').value); const pre = {}; openInvoices(tId).forEach(i => { const rem = Q.invRemaining(i); const v = Math.min(rem, amt); if (v > 0) { pre[i.id] = v; amt -= v; } }); renderAlloc(pre); };
    tenantCard(); if (invoiceId) { const inv = St.get('invoices', invoiceId); el.querySelector('#pay-amount').value = F.vnd(Q.invRemaining(inv)); renderAlloc({ [invoiceId]: Q.invRemaining(inv) }); } else renderAlloc({});
    el.addEventListener('change', (e) => { if (e.target.name === 'tenantId') { tId = e.target.value; tenantCard(); renderAlloc({}); } if (e.target.matches('[data-alloc-chk]')) { const inp = el.querySelector(`[data-alloc="${e.target.dataset.allocChk}"]`); if (e.target.checked && F.num(inp.value) === 0) { const amt = F.num(el.querySelector('#pay-amount').value); let used = 0; el.querySelectorAll('[data-alloc]').forEach(x => { if (x !== inp) { const c = el.querySelector(`[data-alloc-chk="${x.dataset.alloc}"]`); if (c.checked) used += F.num(x.value); } }); inp.value = F.vnd(Math.max(0, Math.min(Number(inp.dataset.rem), amt - used))); } recalc(); } });
    el.addEventListener('input', (e) => { if (e.target.matches('[data-alloc]')) { const chk = el.querySelector(`[data-alloc-chk="${e.target.dataset.alloc}"]`); if (chk && F.num(e.target.value) > 0) chk.checked = true; } recalc(); });
    const collect = () => { const d = m.data(); d.allocations = []; el.querySelectorAll('[data-alloc]').forEach(inp => { const chk = el.querySelector(`[data-alloc-chk="${inp.dataset.alloc}"]`); if (chk && chk.checked && F.num(inp.value) > 0) d.allocations.push({ invoiceId: inp.dataset.alloc, amount: F.num(inp.value) }); }); const f = U.dzFiles(el, 'evidence')[0]; d.evidence = f ? f.name : ''; return d; };
    U.bind(el, {
      cancel: () => m.close(), auto: () => autoAlloc(),
      review: async () => { const d = collect(); const t = Q.tenant(d.tenantId); const ok = await U.confirm({ title: 'Review khoản thu', ok: 'Đúng, ghi nhận', body: U.kv([['Khách thuê', esc(t.name || '-')], ['Ngày thu', F.date(d.date)], ['Số tiền', F.vnd(d.amount) + ' đ'], ['Phương thức', esc(d.method)], ['Mã tham chiếu', esc(d.ref || '-')], ['Phân bổ', d.allocations.map(a => St.get('invoices', a.invoiceId).code + ': ' + F.vnd(a.amount)).join('<br>') || 'Chưa phân bổ'], ['Bằng chứng', esc(d.evidence || 'Chưa đính kèm')]], 'one') }); if (ok) el.querySelector('[data-act=save]').click(); },
      save: () => { const d = collect(); const r = run(m, () => X.recordPayment(d, key), r => 'Đã ghi nhận khoản thu ' + r.code + ' – ' + F.vnd(r.amount) + ' đ'); if (r) { if (onDone) onDone(r); else TH.go('#/payments/' + r.id); } },
    });
    return m;
  };
  /* Xác nhận thu tiền đơn giản: chọn hóa đơn → thu đủ số còn lại kèm minh chứng (đường nâng cao vẫn là Fm.payment) */
  Fm.confirmPayments = ({ invoiceIds = [], onDone } = {}) => {
    const all = invoiceIds.map(id => St.get('invoices', id)).filter(Boolean); const invs = all.filter(i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0); const dropped = all.length - invs.length;
    if (!invs.length) return U.toast('info', 'Không có hóa đơn còn nợ để xác nhận', dropped ? 'Hóa đơn nháp hoặc đã thu đủ không thể xác nhận thu' : '');
    const total = F.sum(invs, i => Q.invRemaining(i)); const tenants = [...new Set(invs.map(i => i.tenantId))];
    const body = `<div data-guide="confirm-pay-form">${dropped ? U.note('info', 'Đã bỏ ' + dropped + ' hóa đơn', 'Hóa đơn nháp hoặc đã thu đủ không nằm trong danh sách xác nhận.') + '<div class="mb12"></div>' : ''}
      <div class="tbl-wrap" style="max-height:220px;overflow:auto"><table class="tbl compact"><thead><tr><th>Hóa đơn</th><th>Khách</th><th>Phòng</th><th>Kỳ</th><th class="num">Còn lại (VND)</th></tr></thead><tbody>${invs.map(i => `<tr><td><a class="link" href="#/invoices/${i.id}">${esc(i.code)}</a></td><td>${esc(Q.tenant(i.tenantId).name)}</td><td>${esc(Q.room(i.roomId).code)}</td><td>${F.periodShort(i.period)}</td><td class="num"><b>${F.vnd(Q.invRemaining(i))}</b>${Q.invOverdue(i) ? '<div class="xs red">quá hạn ' + Q.invOverdueDays(i) + ' ngày</div>' : ''}</td></tr>`).join('')}</tbody><tfoot><tr><td colspan="4"><b>Tổng thu (${invs.length} hóa đơn${tenants.length > 1 ? ' · ' + tenants.length + ' khoản thu theo khách' : ''})</b></td><td class="num"><b class="green">${F.vnd(total)}</b></td></tr></tfoot></table></div>
      <div class="form-grid mt12">${U.field({ label: 'Ngày thu', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'method', value: 'Chuyển khoản', options: opt.methods() }) })}</div>
      ${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref', placeholder: 'Mã giao dịch ngân hàng, số phiếu thu…' }), cls: 'mt12' })}
      <div class="field mt12"><label>Minh chứng thu tiền <span class="req">*</span></label>${U.dropzone({ name: 'evidence', hint: 'Ảnh chuyển khoản / biên lai – JPG, PNG, PDF (tối đa 5MB)' })}<div class="xs muted mt4">Bản demo: <a class="link" data-act="demo-ev">Dùng minh chứng mẫu</a> nếu không có file thật.</div></div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', rows: 2, placeholder: 'Khách chuyển khoản đủ tiền nhà…' }), cls: 'mt12' })}</div>`;
    const m = U.modal({ title: 'Xác nhận thu tiền', sub: 'Thu đủ số còn lại của ' + invs.length + ' hóa đơn · ' + F.vnd(total) + ' đ', size: 'md', body, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Xác nhận thu tiền', act: 'save', cls: 'btn-primary', icon: 'check', attrs: { 'data-guide': 'confirm-pay' } }) });
    const key = F.uid('cpay');
    U.bind(m.el, {
      cancel: () => m.close(),
      'demo-ev': () => { const dz = m.el.querySelector('[data-dz=evidence]'); dz._files = [{ name: 'bien_lai_' + F.today().replace(/-/g, '') + '.jpg', size: 245 * 1024 }]; dz._render && dz._render(); },
      save: () => { const d = m.data(); d.invoiceIds = invs.map(i => i.id); d.evidence = (U.dzFiles(m.el, 'evidence')[0] || {}).name || ''; const r = run(m, () => X.confirmPayments(d, key), r => 'Đã xác nhận thu ' + r.invoices.length + ' hóa đơn – ' + F.vnd(r.total) + ' đ (' + r.payments.map(p => p.code).join(', ') + ')'); if (r && onDone) onDone(r); },
    });
    return m;
  };
  Fm.adjustInvoice = (inv) => {
    const m = U.modal({ title: 'Điều chỉnh hóa đơn ' + inv.code, sub: 'Thêm dòng điều chỉnh, giữ nguyên bản phát hành gốc (FR-FIN-08). Chứng từ chuyển "Đã điều chỉnh".', body: `<div class="form-grid">${U.field({ label: 'Mô tả điều chỉnh', req: true, input: U.input({ name: 'desc', placeholder: 'Điều chỉnh tiền điện kỳ trước' }), cls: 'span2' })}${U.field({ label: 'Số tiền (âm = giảm)', req: true, input: U.input({ name: 'amount', type: 'number', value: -160000 }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'Nhập lý do' }) })}</div>${U.note('info', '', 'Tổng hiện tại ' + F.vnd(inv.total) + ' đ; đã thu ' + F.vnd(Q.invPaid(inv)) + ' đ.')}`, footer: footer('Xác nhận điều chỉnh', 'pencil') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.adjustInvoice(inv.id, { desc: d.desc, amount: Number(d.amount), reason: d.reason }), r => 'Đã điều chỉnh, tổng mới ' + F.vnd(r.total)); } });
  };
  Fm.reversePayment = async (p) => { const r = await U.confirm({ title: 'Hoàn tác ghi nhận ' + p.code + '?', text: 'Khoản thu chuyển "Đã hoàn tác", các hóa đơn tính lại số còn nợ. Dấu vết được giữ trong lịch sử (BR-22).', ok: 'Hoàn tác', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Nhập nhầm số tiền / sai khách…' }) }) }); if (r) { try { X.reversePayment(p.id, r.reason); U.toast('ok', 'Đã hoàn tác khoản thu'); refresh(); } catch (e) { U.toast('err', 'Không hoàn tác được', e.message); } } };
  Fm.adjustPayment = (p) => {
    const invs = St.where('invoices', i => i.tenantId === p.tenantId && i.docStatus !== 'draft' && i.docStatus !== 'cancelled'); const cur = F.by(Q.payAllocs(p.id), 'invoiceId');
    const m = U.drawer({ title: 'Điều chỉnh phân bổ ' + p.code, sub: 'Khoản thu ' + F.vnd(p.amount) + ' đ – phân bổ lại vào các hóa đơn của khách', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Hóa đơn</th><th class="num">Tổng</th><th class="num">Còn lại (chưa tính phiếu này)</th><th class="num">Phân bổ</th></tr></thead><tbody>${invs.map(i => { const mine = cur[i.id] ? cur[i.id][0].amount : 0; const remOther = Q.invRemaining(i) + mine; return `<tr><td>${i.code}<div class="xs muted">${F.periodLabel(i.period)}</div></td><td class="num">${F.vnd(i.total)}</td><td class="num">${F.vnd(remOther)}</td><td class="num"><input class="inp sm tr" data-money data-alloc="${i.id}" value="${mine ? F.vnd(mine) : ''}" style="width:130px"></td></tr>`; }).join('')}</tbody></table></div>${U.field({ label: 'Lý do điều chỉnh', req: true, input: U.input({ name: 'reason' }), cls: 'mt12' })}`, footer: footer('Lưu điều chỉnh') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const allocs = []; m.el.querySelectorAll('[data-alloc]').forEach(inp => allocs.push({ invoiceId: inp.dataset.alloc, amount: F.num(inp.value) })); const d = m.data(); run(m, () => X.adjustPaymentAllocations(p.id, allocs, d.reason), 'Đã điều chỉnh phân bổ'); } });
  };
  /* ---- Hoàn cọc ---- */
  Fm.refundReject = async (rf) => { const r = await U.confirm({ title: 'Từ chối hồ sơ ' + rf.code + '?', text: 'Hồ sơ quay lại trạng thái Cần chỉnh sửa; chưa ghi nhận chi tiền, chưa gửi tin (AC-FR-FIN-07-2).', ok: 'Từ chối', danger: true, body: U.field({ label: 'Lý do từ chối', req: true, input: U.textarea({ name: 'reason', placeholder: 'Thiếu chứng từ sửa chữa…' }) }) }); if (r) { try { X.rejectRefund(rf.id, r.reason); U.toast('ok', 'Đã từ chối hồ sơ'); refresh(); } catch (e) { U.toast('err', 'Không thực hiện được', e.message); } } };
  Fm.refundApprove = async (rf) => { const ok = await U.confirm({ title: 'Duyệt hoàn cọc ' + rf.code + '?', text: 'Số tiền hoàn ' + F.vnd(rf.refundAmount) + ' đ. Duyệt ≠ đã chuyển tiền; bước tiếp theo là Ghi nhận đã hoàn kèm bằng chứng.', ok: 'Duyệt' }); if (ok) { try { X.approveRefund(rf.id); U.toast('ok', 'Đã duyệt hồ sơ hoàn cọc'); refresh(); } catch (e) { U.toast('err', 'Không duyệt được', e.message); } } };
  Fm.refundPaid = (rf) => {
    const m = U.modal({ title: 'Ghi nhận đã hoàn cọc', sub: rf.code + ' – ' + F.vnd(rf.refundAmount) + ' đ cho ' + Q.tenant(rf.tenantId).name, body: `<div class="form-grid">${U.field({ label: 'Ngày hoàn', req: true, input: U.date({ name: 'paidDate', value: F.today() }) })}${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'paidMethod', value: 'Chuyển khoản', options: opt.methods() }) })}${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'paidRef', placeholder: 'Mã UNC / phiếu chi' }), cls: 'span2' })}<div class="field span2"><label>Bằng chứng hoàn tiền<span class="req">*</span></label>${U.dropzone({ name: 'ev', hint: 'PDF/JPG ủy nhiệm chi hoặc biên nhận', multiple: false })}</div></div>${U.note('info', '', 'Phòng KHÔNG tự chuyển Sẵn sàng khi hoàn cọc; cần Vận hành xác nhận dọn xong (BR-02).')}`, footer: footer('Xác nhận đã hoàn', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; d.paidEvidence = f ? f.name : ''; run(m, () => X.recordRefundPaid(rf.id, d), 'Đã ghi nhận hoàn cọc'); } });
  };
  /* ---- Chi phí ---- */
  Fm.expense = (ex = {}) => {
    const bs = opt.buildings(); const canCommon = TH.auth.can('expenses.manageCommon'); const allocs = ex.id ? St.where('expenseAllocations', a => a.expenseId === ex.id) : [];
    const allocRows = (rows) => rows.map((a, i) => `<tr><td>${U.select({ name: 'ab_' + i, value: a.buildingId || '', cls: 'sm', placeholder: 'Chọn tòa', options: bs })}</td><td><input class="inp sm tr" name="ap_${i}" type="number" value="${a.pct}" style="width:80px"></td><td class="num" data-amt="${i}">0</td><td>${U.iconBtn('trash', 'rm-alloc', 'Bỏ', { 'data-i': i })}</td></tr>`).join('');
    let rows = allocs.length ? allocs.map(a => ({ buildingId: a.buildingId, pct: a.pct })) : [{ buildingId: bs[0] && bs[0][0], pct: 40 }, { buildingId: bs[1] && bs[1][0], pct: 30 }, { buildingId: bs[2] && bs[2][0], pct: 20 }, { buildingId: bs[3] && bs[3][0], pct: 10 }];
    const m = U.drawer({ title: ex.id ? 'Sửa chi phí ' + ex.code : 'Thêm chi phí', sub: 'Tạo mới khoản chi phí trong hệ thống', body: `
      ${U.field({ label: 'Ngày chi', req: true, input: U.date({ name: 'date', value: ex.date || F.today() }) })}
      ${U.field({ label: 'Nhóm chi', req: true, input: U.select({ name: 'group', value: ex.group || '', placeholder: 'Chọn nhóm chi', options: opt.groups() }), cls: 'mt12' })}
      ${U.field({ label: 'Diễn giải', input: U.input({ name: 'desc', value: ex.desc || '', placeholder: 'Tiền điện tháng 10/2024' }), cls: 'mt12' })}
      <div class="field mt12"><label>Tòa / Chi phí chung<span class="req">*</span></label><div class="row gap16"><label class="chk"><input type="radio" name="mode" value="building" ${!ex.id || ex.buildingId || !canCommon ? 'checked' : ''}> Chọn tòa nhà</label>${canCommon ? `<label class="chk"><input type="radio" name="mode" value="common" ${ex.id && !ex.buildingId ? 'checked' : ''}> Chi phí chung</label>` : ''}</div>${U.select({ name: 'buildingId', value: ex.buildingId || '', placeholder: 'Chọn tòa nhà', options: bs, cls: 'mt8' })}</div>
      ${U.field({ label: 'Số tiền (VND)', req: true, input: U.money({ name: 'amount', value: ex.amount || '', attrs: { id: 'ex-amount' } }), cls: 'mt12' })}
      <div class="field mt12"><label>Phương thức ghi nhận<span class="req">*</span></label><div class="row gap16 wrap"><label class="chk"><input type="radio" name="method" value="cash" ${ex.method !== 'depreciation' ? 'checked' : ''}> Tiền mặt <span class="muted">(Chi phí ngay)</span></label><label class="chk"><input type="radio" name="method" value="depreciation" ${ex.method === 'depreciation' ? 'checked' : ''}> Khấu hao <span class="muted">(Phân bổ theo kỳ)</span><span class="tag-p">P2</span></label></div><div class="help">Khấu hao theo kỳ thuộc Phase 2 (OI-11) – bản demo chỉ lưu nhãn, không sinh lịch khấu hao.</div></div>
      ${U.field({ label: 'Loại ghi nhận', input: U.select({ name: 'recordType', value: ex.recordType || 'ops', options: [['ops', 'Chi phí vận hành'], ['asset', 'Mua sắm tài sản'], ...(canCommon ? [['common', 'Chi phí chung']] : [])] }), cls: 'mt12' })}
      <div class="field mt12"><label>Chứng từ</label>${U.dropzone({ name: 'ev', hint: 'Hỗ trợ: PDF, JPG, PNG (tối đa 10MB)' })}</div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: ex.note || '', placeholder: 'Nhập ghi chú...' }), cls: 'mt12' })}
      <div class="fs" id="alloc-sec" ${canCommon ? '' : 'hidden'}><div class="fs-h">${I('percent')}Phân bổ theo tòa <span class="muted small" style="font-weight:400">(Chỉ áp dụng khi chọn Chi phí chung)</span></div>${U.note('info', '', 'Chia khoản chi phí này cho các tòa nhà theo tỷ lệ. Tổng phải bằng 100% (FR-FIN-05).')}<div class="tbl-wrap mt8"><table class="tbl compact"><thead><tr><th>Tòa nhà</th><th>Tỷ lệ (%)</th><th class="num">Số tiền (VND)</th><th></th></tr></thead><tbody id="alloc-body">${allocRows(rows)}</tbody><tfoot><tr><td>Tổng cộng</td><td id="alloc-pct">100%</td><td class="num" id="alloc-total">0</td><td></td></tr></tfoot></table></div>${U.btn({ label: 'Thêm tòa nhà', icon: 'plus', act: 'add-alloc', cls: 'btn-dashed btn-block mt8', size: 'btn-sm' })}</div>`, footer: footer('Lưu chi phí') });
    const el = m.el;
    const sync = () => { const common = el.querySelector('input[name=mode]:checked').value === 'common'; el.querySelector('select[name=buildingId]').disabled = common; el.querySelector('#alloc-sec').style.opacity = common ? 1 : .5; const amt = F.num(el.querySelector('#ex-amount').value); let pct = 0; el.querySelectorAll('#alloc-body tr').forEach((tr, i) => { const p = Number(tr.querySelector('input[type=number]').value) || 0; pct += p; tr.querySelector('[data-amt]').textContent = F.vnd(Math.round(amt * p / 100)); }); el.querySelector('#alloc-pct').textContent = pct + '%'; el.querySelector('#alloc-pct').className = pct === 100 ? 'green' : 'red'; el.querySelector('#alloc-total').textContent = F.vnd(common ? amt : 0); };
    el.addEventListener('input', sync); el.addEventListener('change', sync); sync();
    U.bind(el, { cancel: () => m.close(), 'add-alloc': () => { rows = readRows(); rows.push({ buildingId: '', pct: 0 }); el.querySelector('#alloc-body').innerHTML = allocRows(rows); sync(); }, 'rm-alloc': (b) => { rows = readRows(); rows.splice(Number(b.dataset.i), 1); el.querySelector('#alloc-body').innerHTML = allocRows(rows); sync(); },
      save: () => { const d = m.data(); const common = d.mode === 'common'; const f = U.dzFiles(el, 'ev')[0]; const payload = { id: ex.id, date: d.date, group: d.group, desc: d.desc, buildingId: common ? null : d.buildingId, amount: d.amount, method: d.method, recordType: common ? 'common' : d.recordType, evidence: f ? f.name : (ex.evidence || ''), note: d.note, allocations: common ? readRows() : [] }; if (!common && !payload.buildingId) throw new Error('Chọn tòa nhà hoặc chuyển sang Chi phí chung'); run(m, () => X.saveExpense(payload), r => 'Đã lưu chi phí ' + r.code); } });
    function readRows() { return [...el.querySelectorAll('#alloc-body tr')].map(tr => ({ buildingId: tr.querySelector('select').value, pct: Number(tr.querySelector('input[type=number]').value) || 0 })); }
  };
  /* ---- Tài khoản ---- */
  Fm.user = (u = {}) => {
    const m = U.drawer({ title: u.id ? 'Sửa tài khoản' : 'Tạo tài khoản', sub: u.id ? u.email : 'Thêm tài khoản người dùng mới vào hệ thống.', body: `<div class="col" style="gap:14px">
      ${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name', value: u.name || '', placeholder: 'Nhập họ và tên' }) })}
      ${U.field({ label: 'Email', req: true, input: U.input({ name: 'email', value: u.email || '', type: 'email', placeholder: 'Nhập địa chỉ email' }) })}
      ${U.field({ label: 'Số điện thoại', req: true, input: U.input({ name: 'phone', value: u.phone || '', placeholder: 'Nhập số điện thoại' }) })}
      ${U.field({ label: 'Vai trò', req: true, input: U.select({ name: 'role', value: u.role || '', placeholder: 'Chọn vai trò', options: [['admin', 'Quản trị viên'], ['accountant', 'Kế toán'], ['ops', 'Quản lý / Vận hành'], ['sale', 'Sale (Phase 2)'], ['tech', 'Kỹ thuật (Phase 2)']] }), help: 'Phase 1: Admin, Kế toán, Quản lý/Vận hành' })}
      ${U.field({ label: 'Khu vực', req: true, input: U.select({ name: 'region', value: u.region || 'Tất cả khu vực', options: ['Tất cả khu vực', ...Q.districts()] }) })}
      <div class="field"><label>Tòa/Phòng phụ trách</label><div class="row wrap gap12">${opt.buildings().map(([id, nm]) => U.check({ name: 'b_' + id, label: nm.split(' (')[0], checked: (u.buildingIds || []).includes(id) })).join('')}</div><div class="help">Có thể chọn nhiều tòa/phòng</div></div>
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveDate', value: u.effectiveDate || F.today() }) })}
      ${U.field({ label: 'Trạng thái', req: true, input: U.select({ name: 'status', value: u.status || 'active', options: [['active', 'Đang hoạt động'], ['locked', 'Tài khoản bị khóa'], ['expired', 'Hết hiệu lực']] }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: u.note || '', placeholder: 'Nhập ghi chú...' }) })}</div>`, footer: footer(u.id ? 'Lưu thay đổi' : 'Lưu tài khoản', 'user-plus') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = opt.buildings().filter(([id]) => d['b_' + id]).map(([id]) => id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); d.scope = d.buildingIds.length ? d.buildingIds.map(id => Q.building(id).name).join(', ') : (d.role === 'admin' ? 'Toàn hệ thống' : d.role === 'accountant' ? 'Tài chính' : d.region); if (u.id) d.id = u.id; run(m, () => X.saveUser(d), r => 'Đã lưu tài khoản ' + r.name); } });
  };
  /* ---- Upload tài liệu ---- */
  Fm.upload = (entityType, entityId, cb) => {
    const m = U.modal({ title: 'Tải lên tài liệu', size: 'sm', sub: 'PDF/JPG/PNG, tối đa 20 MB/tệp (FR-DOC-01). File chỉ mô phỏng, không upload thật.', body: U.field({ label: 'Loại hồ sơ', input: U.select({ name: 'label', value: '', options: ['Hợp đồng', 'Biên bản bàn giao', 'Sổ đỏ', 'PCCC', 'Giấy tờ khách', 'Biên lai', 'Khác'] }) }) + `<div class="field mt12">${U.dropzone({ name: 'f', hint: 'PDF, JPG, PNG (tối đa 20MB)' })}</div>`, footer: footer('Tải lên', 'upload') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const files = U.dzFiles(m.el, 'f'); if (!files.length) throw new Error('Chọn ít nhất một tệp'); const d = m.data(); files.forEach(f => { if (f.size > 20 * 1024 * 1024) throw new Error(f.name + ' vượt 20MB'); if (!/\.(pdf|jpe?g|png|docx?)$/i.test(f.name)) throw new Error(f.name + ': định dạng không hỗ trợ'); X.addDocument(entityType, entityId, { name: f.name, size: f.size, label: d.label + ' – ' + f.name }); }); U.toast('ok', 'Đã tải lên ' + files.length + ' tệp'); m.close(); refresh(); cb && cb(); } });
  };
  /* ---- Zalo: gửi nhanh cho danh sách hóa đơn / khách ---- */
  Fm.zaloQuick = ({ invoiceIds = [], tenantIds = [], eventKey = 'debt', title = 'Gửi nhắc tiền qua Zalo' }) => {
    const ev = St.one('zaloEvents', e => e.key === (eventKey === 'debt' ? 'reminder' : eventKey)) || St.all('zaloEvents')[0];
    const tpls = St.all('zaloTemplates').filter(t => !['landlord_due'].includes(t.eventKey));
    let templateId = (tpls.find(t => t.eventKey === eventKey) || tpls[0]).id;
    let force = false; let recips = X.buildRecipients('manual', { invoiceIds, tenantIds });
    const recent = () => recips.filter(r => /3 ngày/.test(r.reason || '')).length;
    const renderList = () => `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th></th><th>Khách</th><th>Phòng</th><th class="num">Số tiền nợ</th><th>Trạng thái</th></tr></thead><tbody>${recips.map((r, i) => { const t = Q.tenant(r.tenantId); return `<tr><td><input type="checkbox" data-ri="${i}" ${r.elig === 'ok' ? 'checked' : 'disabled'}></td><td>${esc(t.name)}<div class="xs muted">${esc(t.phone)}</div></td><td>${esc(Q.room(r.roomId).code || '-')}</td><td class="num">${F.vnd(r.amount)}</td><td>${U.chip(r.elig === 'ok' ? 'Đủ điều kiện' : r.elig === 'skip' ? 'Bỏ qua' : 'Lỗi dữ liệu', r.elig === 'ok' ? 'green' : r.elig === 'skip' ? 'amber' : 'red')}<div class="xs muted">${esc(r.reason)}</div></td></tr>`; }).join('')}</tbody></table></div>`;
    const preview = () => { const r = recips.find(x => x.elig === 'ok') || recips[0]; if (!r) return ''; const inv = r.invoiceId ? St.get('invoices', r.invoiceId) : null; return U.phone(Q.renderTemplate(Q.template(templateId).body, Q.templateCtx(inv, Q.tenant(r.tenantId), { room: Q.room(r.roomId), amount: r.amount, due: r.due }))); };
    const m = U.drawer({ title, wide: true, sub: 'Hệ thống re-check công nợ trước khi gửi: đã trả đủ → bỏ qua; trả một phần → gửi số còn nợ (FR-ZAL-02)', body: `<div class="grid grid-2" style="grid-template-columns:1fr 300px"><div>${U.field({ label: 'Mẫu thông báo', input: U.select({ name: 'templateId', value: templateId, options: tpls.map(t => [t.id, t.name]), attrs: { 'data-on': 'tpl' } }) })}<div class="mt12" id="zq-list">${renderList()}</div><div class="mt8" id="zq-recent">${recent() ? U.note('warn', recent() + ' khách đã nhận tin trong 3 ngày qua – bị bỏ qua theo rule', U.check({ name: 'force', label: 'Vẫn gửi cho các khách này (ghi đè rule 3 ngày)', attrs: { 'data-on': 'force' } })) : ''}</div></div><div><div class="small bold mb8">Xem trước nội dung Zalo</div><div id="zq-prev">${preview()}</div></div></div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: 'Xác nhận gửi', act: 'send', icon: 'send', cls: 'btn-primary' }) });
    m.el.addEventListener('change', (e) => { if (e.target.name === 'templateId') { templateId = e.target.value; m.el.querySelector('#zq-prev').innerHTML = preview(); } if (e.target.matches('[data-ri]')) recips[Number(e.target.dataset.ri)].selected = e.target.checked; if (e.target.name === 'force') { force = e.target.checked; recips = X.buildRecipients('manual', { invoiceIds, tenantIds, ignoreRecent: force }); m.el.querySelector('#zq-list').innerHTML = renderList(); m.el.querySelector('#zq-prev').innerHTML = preview(); } });
    U.bind(m.el, { cancel: () => m.close(), send: () => { const r = run(m, () => X.createZaloBatch({ name: (Q.L.eventName[eventKey] || 'Nhắc tiền') + ' ' + F.date(F.today()), eventKey, sourceKey: 'manual', templateId, recipients: recips, sendMode: 'now', key: F.uid('zb') }), r => 'Đã tạo đợt gửi ' + r.code); if (r) TH.go('#/zalo/batches/' + r.id); } });
  };
  Fm.template = (tpl = {}, eventKey) => {
    const sample = Q.templateCtx(St.where('invoices', i => i.docStatus !== 'draft')[0], St.all('tenants')[0]);
    const m = U.drawer({ title: tpl.id ? 'Mẫu ' + tpl.code : 'Tạo mẫu Zalo', wide: true, sub: 'Biến: {ten_khach} {toa_nha} {so_phong} {so_tien} {ngay_den_han} {ky} {con_lai} {qua_han} {ngay_het_han} {ngay_hoan} {noi_dung}', body: `<div class="grid grid-2"><div>${U.field({ label: 'Tên mẫu', req: true, input: U.input({ name: 'name', value: tpl.name || '' }) })}${U.field({ label: 'Sự kiện', input: U.select({ name: 'eventKey', value: tpl.eventKey || eventKey || 'reminder', options: [['reminder', 'Nhắc tiền'], ['debt', 'Nhắc công nợ'], ['contract_expiry', 'HĐ sắp hết hạn'], ['refund_done', 'Đã hoàn cọc'], ['broadcast', 'Thông báo chung']] }), cls: 'mt12' })}${U.field({ label: 'Nội dung', req: true, input: U.textarea({ name: 'body', value: tpl.body || '', rows: 12 }), cls: 'mt12' })}</div><div><div class="small bold mb8">Xem trước (dữ liệu mẫu)</div><div id="tpl-prev">${U.phone(Q.renderTemplate(tpl.body || '', sample))}</div>${U.note('info', '', 'Mẫu ZBS Template Message phải qua kiểm duyệt Zalo trước khi dùng thật (OI-20).')}</div></div>`, footer: footer('Lưu mẫu') });
    m.el.addEventListener('input', (e) => { if (e.target.name === 'body') m.el.querySelector('#tpl-prev').innerHTML = U.phone(Q.renderTemplate(e.target.value, sample)); });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (tpl.id) d.id = tpl.id; run(m, () => X.saveTemplate(d), 'Đã lưu mẫu'); } });
  };
  Fm.zaloTest = (eventKey) => {
    const m = U.modal({ title: 'Gửi thử', size: 'sm', sub: 'Tạo đợt gửi 1 tin cho khách được chọn để kiểm tra nội dung', body: U.field({ label: 'Khách nhận thử', input: U.select({ name: 'tenantId', options: opt.tenants(), placeholder: 'Chọn khách' }) }), footer: footer('Gửi thử', 'send') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (!d.tenantId) throw new Error('Chọn khách'); const r = run(m, () => X.sendTest(eventKey, d.tenantId), r => 'Đã gửi thử – đợt ' + r.code); if (r) TH.go('#/zalo/batches/' + r.id); } });
  };
  Fm.roomServices = (room) => {
    const svcs = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const m = U.modal({ title: 'Quản lý dịch vụ phòng ' + room.code, sub: 'Dịch vụ mặc định nạp vào hợp đồng mới. Hợp đồng hiện tại giữ nguyên snapshot giá (BR-21).', body: `<div class="col gap12">${svcs.map(s => U.check({ name: 's_' + s.id, label: `<b>${esc(s.name)}</b> – ${F.vnd(s.price)} đ/${esc(s.unit)}`, checked: (room.defaultServiceIds || []).includes(s.id) })).join('')}</div>`, footer: footer('Lưu dịch vụ') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.saveRoomServices(room.id, svcs.filter(s => d['s_' + s.id]).map(s => s.id)), 'Đã lưu dịch vụ mặc định'); } });
  };
  Fm.roomAsset = (room, a = {}) => {
    const m = U.modal({ title: a.id ? 'Sửa tài sản' : 'Thêm tài sản trong phòng', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Tên tài sản', req: true, input: U.input({ name: 'name', value: a.name || '' }), cls: 'span2' })}${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', type: 'number', value: a.qty || 1 }) })}${U.field({ label: 'Tình trạng', input: U.select({ name: 'condition', value: a.condition || 'Tốt', options: ['Tốt', 'Cần bảo dưỡng', 'Hỏng'] }) })}</div>`, footer: footer('Lưu') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (!d.name) throw new Error('Nhập tên tài sản'); d.roomId = room.id; d.qty = Number(d.qty) || 1; if (a.id) d.id = a.id; run(m, () => X.saveRoomAsset(d), 'Đã lưu tài sản'); } });
  };
  TH.forms = Fm;
})(window.TH);
