/* Form/drawer dùng chung giữa các trang */
(function (TH) {
  const F = TH.f, U = TH.ui, I = TH.icon, Q = TH.q, X = TH.actions, St = TH.store, esc = F.esc;
  const Fm = {};
  const refresh = () => { TH.layout.refreshTop(); TH.router.refresh(); };
  const footer = (saveLabel = 'Lưu', icon = 'save', extra = '') => extra + U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: saveLabel, act: 'save', cls: 'btn-primary', icon });
  const run = (m, fn, okMsg) => { try { const r = fn(); if (r && r.duplicate) U.toast('warn', 'Yêu cầu trùng – không tạo thêm', 'Idempotency key đã tồn tại'); else if (okMsg) U.toast('ok', typeof okMsg === 'function' ? okMsg(r) : okMsg); m.close(true); refresh(); return r; } catch (e) { U.toast('err', 'Không lưu được', e.message); U.setErrors(m.el, e.fields || {}); } };
  const opt = {
    buildings: (all) => St.where('buildings', b => !b.stub || all).map(b => [b.id, b.name + ' (' + b.code + ')']),
    tenants: () => St.all('tenants').slice().sort((a, b) => a.name.localeCompare(b.name, 'vi')).map(t => [t.id, t.name + ' (' + t.code + ') – ' + t.phone]),
    managers: () => Q.managers().map(u => [u.id, u.name]),
    landlords: () => St.all('landlords').map(l => [l.id, l.name + ' (' + l.code + ')']),
    methods: () => St.where('payMethods', m => m.status === 'active').map(m => m.name),
    groups: () => St.all('expenseGroups').map(g => g.name),
    roomsReady: () => St.where('rooms', r => ['ready', 'held'].includes(r.status)).sort((a, b) => a.code.localeCompare(b.code)).map(r => [r.id, r.code + ' · ' + Q.building(r.buildingId).name + ' · ' + F.vnd(r.price)]),
  };
  Fm.opt = opt;

  /* ---- Khách thuê ---- */
  Fm.tenant = (t = {}, cb) => {
    const dupWarn = (root) => { const d = U.formData(root); const r = Q.tenantMatch ? Q.tenantMatch({ name: d.name, phone: d.phone, idNumber: d.idNumber, dob: d.dob }, t.id) : { match: null }; const box = root.querySelector('#tenant-dup'); if (!box) return; if (r.match) box.innerHTML = U.note('warn', 'Có thể trùng hồ sơ', 'Khớp theo ' + esc(r.matchBy) + ': <strong>' + esc(r.match.name) + '</strong> (' + esc(r.match.code) + ' · ' + esc(r.match.phone || '') + (r.match.idNumber ? ' · CCCD ' + esc(r.match.idNumber) : '') + ')' + (r.conflicts.length ? ' – ' + r.conflicts.map(x => esc(x.msg)).join('; ') : '') + '. ' + U.link('#/tenants/' + r.match.id, 'Mở hồ sơ') + ' thay vì tạo mới (§12.8.6).'); else if (r.weak) box.innerHTML = U.note('info', 'Trùng tên', 'Đã có khách <strong>' + esc(r.weak.name) + '</strong> (' + esc(r.weak.code) + ') nhưng khác SĐT/CCCD/ngày sinh – kiểm tra trước khi tạo.'); else box.innerHTML = ''; };
    const m = U.drawer({ title: t.id ? 'Sửa khách thuê' : 'Thêm khách thuê', sub: t.id ? t.code : 'Tạo hồ sơ khách thuê mới. Trạng thái thuê được suy ra từ hợp đồng.', body: `<div class="form-grid">
      <div id="tenant-dup" class="span2"></div>
      ${U.field({ label: 'Họ tên', req: true, name: 'name', input: U.input({ name: 'name', value: t.name || '', placeholder: 'Nhập họ và tên' }), cls: 'span2' })}
      ${U.field({ label: 'Số điện thoại', req: true, name: 'phone', input: U.input({ name: 'phone', value: t.phone || '', placeholder: '09xx xxx xxx', icon: 'phone' }) })}
      ${U.field({ label: 'Zalo', input: U.input({ name: 'zalo', value: t.zalo || '', placeholder: 'SĐT Zalo (mặc định = SĐT)' }), help: 'SĐT không phải bằng chứng đã xác minh tài khoản Zalo (FR-CUS-01)' })}
      ${U.field({ label: 'Email', input: U.input({ name: 'email', value: t.email || '', type: 'email', placeholder: 'email@domain.com', icon: 'mail' }) })}
      ${U.field({ label: 'CMND/CCCD', input: U.input({ name: 'idNumber', value: t.idNumber || '', placeholder: '12 số' }), help: 'Tùy chọn – nếu có phải đúng 12 số' })}
      ${U.field({ label: 'Nơi cấp CCCD', input: U.input({ name: 'idPlace', value: t.idPlace || '', placeholder: 'Cục Cảnh sát QLHC về TTXH' }) })}
      ${U.field({ label: 'Ngày sinh', input: U.date({ name: 'dob', value: t.dob || '' }) })}
      ${U.field({ label: 'Hộ khẩu thường trú', input: U.input({ name: 'address', value: t.address || '', placeholder: 'Số nhà, đường, phường/xã, tỉnh/thành', icon: 'map-pin' }), cls: 'span2' })}
      ${U.field({ label: 'Nghề nghiệp', input: U.input({ name: 'job', value: t.job || '', placeholder: 'Nhân viên văn phòng…' }) })}
      ${U.field({ label: 'Phân khúc khách', input: U.select({ name: 'segment', value: t.segment || '', all: 'Chưa xác định', options: ['Văn phòng', 'Sinh viên', 'Gia đình', 'Chuyên gia', 'Lao động'] }), help: 'Khai báo trực tiếp, không suy từ nghề nghiệp (BR-18)' })}
      ${U.field({ label: 'Người phụ trách', input: U.select({ name: 'managerId', value: t.managerId || (TH.auth.session() || {}).userId, options: opt.managers() }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: t.note || '', placeholder: 'Phương tiện, yêu cầu đặc biệt…' }), cls: 'span2' })}
      ${U.check({ name: 'verified', label: 'Đã xác minh Zalo (đánh dấu thủ công)', checked: !!t.verified })}</div>`, footer: footer(t.id ? 'Lưu thay đổi' : 'Lưu khách thuê', 'user-plus') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (t.id) d.id = t.id; const r = run(m, () => X.saveTenant(d), (r) => 'Đã lưu khách ' + r.name + ' (' + r.code + ')'); if (r && cb) cb(r); } });
    m.el.addEventListener('change', (e) => { if (['name', 'phone', 'idNumber', 'dob'].includes(e.target.name)) dupWarn(m.el); }); if (t.name || t.phone || t.idNumber) dupWarn(m.el);
    return m;
  };
  /* ---- Tòa ---- */
  // Tòa mới luôn đi qua onboarding chủ nhà (Chủ nhà → HĐ đầu vào → Tòa → Phòng); drawer chỉ dùng để sửa
  /* §12.9 Bảng giá 2 lớp: override giá theo tòa / đổi giá mặc định – có ngày hiệu lực, không ghi đè lịch sử */
  Fm.servicePrice = ({ serviceId = '', buildingId = '', scope = 'BUILDING' } = {}, cb) => {
    const svcs = St.where('services', x => x.status === 'active'); const bs = St.where('buildings', x => !x.stub);
    const cur = serviceId ? Q.servicePriceRecord(serviceId, buildingId || null) : null;
    const m = U.modal({ title: scope === 'GLOBAL' ? 'Đổi giá mặc định' : 'Override giá theo tòa', sub: 'Tạo Service Price record mới có hiệu lực; dòng cũ tự đóng ngày hiệu lực − 1; hóa đơn đã phát hành không đổi (§12.9.5)', body: `<div class="form-grid">${U.field({ label: 'Dịch vụ', req: true, input: U.select({ name: 'serviceId', value: serviceId, placeholder: 'Chọn dịch vụ', options: svcs.map(x => [x.id, x.name + ' (' + x.unit + ')']) }), cls: scope === 'GLOBAL' ? 'span2' : '' })}${scope === 'GLOBAL' ? '' : U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: buildingId, placeholder: 'Chọn tòa', options: bs.map(x => [x.id, x.name]) }) })}${U.field({ label: 'Giá mới (VND)', req: true, input: U.money({ name: 'price', value: cur ? cur.price : '' }), help: cur ? 'Đang áp dụng ' + F.vnd(cur.price) + ' (' + (cur.scope === 'BUILDING' ? 'giá riêng tòa' : 'giá mặc định') + ' từ ' + F.date(cur.effectiveFrom) + ')' : '' })}${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'VD: HĐ đầu vào mới, điều chỉnh theo EVN…' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Lưu bảng giá', icon: 'save', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); const rec = X.saveServicePrice({ serviceId: d.serviceId, scope, buildingId: d.buildingId || null, price: F.num(d.price), effectiveFrom: d.effectiveFrom, reason: d.reason }); m.close(); U.toast('ok', 'Đã lưu bảng giá', 'Hiệu lực từ ' + F.date(d.effectiveFrom)); cb && cb(rec); TH.router.refresh(); } catch (e) { U.toast('err', 'Không lưu được', e.message); } } });
  };
  /* §4.6 Ký hiệu/loại tòa: sửa phải nhập ngày hiệu lực, lưu lịch sử, không ghi đè quá khứ */
  Fm.buildingType = (b) => {
    const cur = Q.buildingTypeAt(b.id);
    const m = U.modal({ title: 'Cập nhật ký hiệu / loại tòa – ' + esc(b.name), sub: 'Giá trị phụ thuộc hợp đồng đầu vào/giai đoạn; báo cáo kỳ cũ dùng ký hiệu hiệu lực tại kỳ (§4.6)', body: `<div class="form-grid">${U.field({ label: 'Ký hiệu loại tòa', req: true, input: U.select({ name: 'type', value: cur, options: Q.buildingTypeOptions() }), help: 'Danh mục mở rộng được tại Master Data (§7.5)' })}${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'VD: HĐ đầu vào mới / chuyển sang góp vốn cổ đông' }), cls: 'span2' })}</div>`, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Lưu (tạo bản ghi lịch sử)', icon: 'save', act: 'save', cls: 'btn-primary' }) });
    U.bind(m.el, { cancel: () => m.close(), save: () => { try { const d = m.data(); X.setBuildingType({ buildingId: b.id, type: d.type, effectiveFrom: d.effectiveFrom, reason: d.reason }); m.close(); U.toast('ok', 'Đã cập nhật loại tòa', 'Hiệu lực từ ' + F.date(d.effectiveFrom) + ' – lịch sử được giữ'); } catch (e) { U.toast('err', 'Không cập nhật được', e.message); } } });
  };
  Fm.building = (b = {}) => {
    if (!b.id) {
      const lls = St.where('landlords', l => l.status !== 'paused').sort((a, c) => a.name.localeCompare(c.name, 'vi'));
      const m = U.modal({ title: 'Thêm tòa nhà', size: 'sm', sub: 'Tòa nhà phải thuộc một chủ nhà và có hợp đồng đầu vào. Chọn chủ nhà để tiếp tục khai báo HĐ, tòa và phòng.', body: U.field({ label: 'Chủ nhà', req: true, input: U.select({ name: 'landlordId', value: '', options: [['', 'Chủ nhà mới – tạo hồ sơ'], ...lls.map(l => [l.id, l.name + ' (' + l.code + ')'])] }) }), footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: 'Tiếp tục', icon: 'arrow-right', cls: 'btn-primary', act: 'go' }) });
      U.bind(m.el, { cancel: () => m.close(), go: () => { const d = m.data(); m.close(); TH._wz = TH._wz || {}; delete TH._wz.landlordOnboarding; TH.go('#/landlords/new' + (d.landlordId ? '?landlordId=' + encodeURIComponent(d.landlordId) : '')); } });
      return;
    }
    const ll = St.get('landlords', b.landlordId);
    const m = U.drawer({ title: 'Sửa tòa nhà', sub: 'Thông tin tòa và chu kỳ trả chủ nhà (3/4/6 tháng – BR-11). Chủ nhà thay đổi qua hợp đồng đầu vào.', body: `<div class="form-grid">
      ${U.field({ label: 'Mã tòa', input: U.input({ name: 'code', value: b.code || '', placeholder: 'TH-XXX-11 (để trống tự sinh)' }) })}
      ${U.field({ label: 'Tên tòa', req: true, name: 'name', input: U.input({ name: 'name', value: b.name || '', placeholder: 'Tòa …' }) })}
      ${U.field({ label: 'Địa chỉ', req: true, name: 'address', input: U.input({ name: 'address', value: b.address || '', icon: 'map-pin' }), cls: 'span2' })}
      ${U.field({ label: 'Quận/Huyện', input: U.input({ name: 'district', value: b.district || '', placeholder: 'Thông tin địa lý của tòa', attrs: { list: 'dl-district' } }), help: 'Khác với Khu nhà quản lý.' })}<datalist id="dl-district">${Q.districts().map(d => `<option value="${esc(d)}">`).join('')}</datalist>
      ${U.field({ label: 'Khu nhà quản lý', input: U.select({ name: 'areaId', value: b.areaId || '', all: 'Chưa gán', options: Q.areas().map(a => [a.id, a.name]) }), help: 'Danh mục dùng chung cho tòa, nhân sự và báo cáo.' })}
      ${U.field({ label: 'Loại nhà', input: U.select({ name: 'buildingType', value: b.buildingType || 'T', options: Object.entries(Q.L.buildingType).map(([k, v]) => [k, v[0]]) }), help: 'Giả định theo workbook: T thuê lại · S sở hữu · G góp vốn' })}
      ${U.field({ label: 'Tiền tố mã phòng', input: U.input({ name: 'prefix', value: b.prefix || '', placeholder: 'A', attrs: { maxlength: 2 } }), help: 'VD: A → A.01.01' })}
      ${U.field({ label: 'Số tầng', input: U.input({ name: 'floors', type: 'number', value: b.floors || 1 }) })}
      ${U.field({ label: 'Số phòng / tầng (dự kiến)', input: U.input({ name: 'perFloor', type: 'number', value: b.perFloor || 0 }) })}
      ${U.field({ label: 'Diện tích tòa (m²)', input: U.input({ name: 'areaM2', type: 'number', value: b.areaM2 || 0 }) })}
      ${U.field({ label: 'Tình trạng tòa', input: U.select({ name: 'condition', value: b.condition || 'medium', options: [['new', 'Mới'], ['medium', 'Trung bình'], ['old', 'Cũ'] ] }) })}
      ${U.field({ label: 'Vận hành từ', input: U.date({ name: 'operatingSince', value: b.operatingSince || F.today() }) })}
      ${U.field({ label: 'Chủ nhà', input: `<div class="static-val">${ll ? U.link('#/landlords/' + ll.id, esc(ll.name)) + ' <span class="muted small">(' + esc(ll.code) + ')</span>' : '<span class="red">Chưa gán – bổ sung qua Onboarding chủ nhà</span>'}</div>`, help: 'Đổi chủ nhà bằng cách tạo HĐ đầu vào mới cho tòa.' })}
      ${b.id ? U.field({ label: 'Quản lý hiện tại', input: `<div class="static-val">${esc(Q.buildingManagerName(b.id))}</div>`, help: 'Đọc từ Nhân sự → Phân công tòa nhà; đổi quản lý tại đó (§4.6, §10.17)' }) : U.field({ label: 'Phụ trách chính ban đầu', input: U.select({ name: 'managerId', value: b.managerId || '', all: 'Phân công sau', options: opt.managers() }), help: 'Sẽ tạo phân công Phụ trách chính hiệu lực từ ngày vận hành' })}
      ${U.field({ label: 'Chu kỳ trả chủ nhà', input: U.select({ name: 'payCycle', value: b.payCycle || 3, options: [[3, '3 tháng/lần'], [4, '4 tháng/lần'], [6, '6 tháng/lần']] }) })}
      ${U.field({ label: 'Ngày trả trong kỳ', input: U.input({ name: 'payDay', type: 'number', value: b.payDay || 5 }) })}
      ${U.field({ label: 'Trạng thái', input: U.select({ name: 'status', value: b.status || 'active', options: [['active', 'Đang hoạt động'], ['maintenance', 'Bảo trì, sửa chữa'], ['inactive', 'Tạm ngừng']] }) })}
      ${U.field({ label: 'Trạng thái ĐKKD', input: U.select({ name: 'license', value: b.license || 'Đã đăng ký', options: ['Đã đăng ký', 'Đang làm hồ sơ', 'Chưa đăng ký'] }) })}
      ${U.field({ label: 'ĐKKD hết hạn', input: U.date({ name: 'licenseExpiry', value: b.licenseExpiry || '' }) })}
      ${U.field({ label: 'PCCC', input: U.select({ name: 'pcccStatus', value: (b.pccc || {}).status || 'valid', options: [['valid', 'Còn hiệu lực'], ['missing', 'Thiếu hồ sơ'], ['expired', 'Hết hạn']] }) })}
      ${U.field({ label: 'PCCC hết hạn', input: U.date({ name: 'pcccExpiry', value: (b.pccc || {}).expiry || '' }) })}</div>`, footer: footer('Lưu thay đổi') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.id = b.id; d.floors = Number(d.floors) || 1; d.perFloor = Number(d.perFloor) || 0; d.areaM2 = Number(d.areaM2) || 0; d.payCycle = Number(d.payCycle); d.payDay = Number(d.payDay) || 5; d.pccc = { status: d.pcccStatus, expiry: d.pcccExpiry }; delete d.pcccStatus; delete d.pcccExpiry; run(m, () => X.saveBuilding(d), r => 'Đã lưu tòa ' + r.name); } });
  };
  /* ---- Phòng ---- */
  Fm.room = (r = {}, buildingId) => {
    const svcs = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const m = U.drawer({ title: r.id ? 'Sửa phòng ' + r.code : 'Thêm phòng', sub: 'Mã phòng duy nhất trong tòa (FR-BLD-03). Dịch vụ mặc định sẽ nạp vào hợp đồng mới.', body: `<div class="form-grid">
      ${U.field({ label: 'Tòa nhà', req: true, input: U.select({ name: 'buildingId', value: r.buildingId || buildingId || '', placeholder: 'Chọn tòa', options: opt.buildings() }) })}
      ${U.field({ label: 'Mã phòng', req: true, name: 'code', input: U.input({ name: 'code', value: r.code || '', placeholder: 'A.01.01' }) })}
      ${U.field({ label: 'Tầng', input: U.input({ name: 'floor', type: 'number', value: r.floor || 1 }) })}
      ${U.field({ label: 'Loại phòng', input: U.select({ name: 'type', value: r.type || 'Phòng đơn', options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'] }) })}
      ${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'area', type: 'number', value: r.area || 25 }) })}
      ${r.id ? U.field({ label: 'Giá niêm yết', input: `<div class="static-val">${F.vnd(r.price)} đ</div>`, help: 'Đổi giá tại chi tiết phòng → Cập nhật giá (có ngày hiệu lực, lưu lịch sử)' }) : U.field({ label: 'Giá niêm yết', req: true, input: U.money({ name: 'price', value: r.price || '' }) })}
      ${U.field({ label: 'Hướng phòng', input: U.input({ name: 'direction', value: r.direction || '' }) })}
      ${U.field({ label: 'Nội thất', input: U.select({ name: 'furniture', value: r.furniture || 'Cơ bản', options: ['Đầy đủ', 'Cơ bản', 'Trống'] }) })}
      ${U.field({ label: 'Người phụ trách', input: `<div class="static-val">${esc(r.buildingId || buildingId ? Q.buildingManagerName(r.buildingId || buildingId) : 'Theo tòa')}</div>`, help: 'Theo Phụ trách chính của tòa (Phân công tòa nhà)' })}
      ${r.id ? '' : U.field({ label: 'Trạng thái ban đầu', input: U.select({ name: 'status', value: 'ready', options: [['ready', 'Sẵn sàng'], ['maintenance', 'Bảo trì'], ['inactive', 'Ngừng khai thác']] }) })}
      <div class="field span2"><label>Dịch vụ mặc định</label><div class="row wrap gap12">${svcs.map(s => U.check({ name: 'svc_' + s.id, label: s.name + ' – ' + F.vnd(s.price) + '/' + s.unit, checked: (r.defaultServiceIds || []).includes(s.id) })).join('')}</div></div></div>`, footer: footer(r.id ? 'Lưu thay đổi' : 'Lưu phòng') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const ids = svcs.filter(s => d['svc_' + s.id]).map(s => s.id); svcs.forEach(s => delete d['svc_' + s.id]); d.defaultServiceIds = ids; d.floor = Number(d.floor) || 1; d.area = Number(d.area) || 0; if (r.id) { d.id = r.id; d.price = r.price; } if (!d.price) throw new Error('Giá niêm yết là bắt buộc'); run(m, () => X.saveRoom(d), x => 'Đã lưu phòng ' + x.code); } });
  };
  Fm.roomsBulk = (buildingId) => {
    const b = Q.building(buildingId);
    const m = U.modal({ title: 'Tạo nhiều phòng', sub: 'Sinh mã theo mẫu ' + b.prefix + '.<tầng>.<số>, bỏ qua mã đã tồn tại; số tầng / phòng mỗi tầng của tòa được cập nhật theo', body: `<div class="form-grid">${U.field({ label: 'Từ tầng', input: U.input({ name: 'floorFrom', type: 'number', value: 1, attrs: { min: 1 } }) })}${U.field({ label: 'Đến tầng', input: U.input({ name: 'floorTo', type: 'number', value: b.floors || 1, attrs: { min: 1 } }) })}${U.field({ label: 'Số phòng mỗi tầng', input: U.input({ name: 'perFloor', type: 'number', value: b.perFloor || 4, attrs: { min: 1, max: 20 } }) })}${U.field({ label: 'Diện tích (m²)', input: U.input({ name: 'area', type: 'number', value: 25 }) })}${U.field({ label: 'Giá tham chiếu', input: U.money({ name: 'price', value: 5000000 }) })}${U.field({ label: 'Loại phòng', input: U.select({ name: 'type', value: 'Phòng đơn', options: ['Căn hộ Studio', 'Căn hộ 1PN', 'Căn hộ 2PN', 'Phòng đơn', 'Phòng đôi'] }), cls: 'span2' })}</div>`, footer: footer('Tạo phòng', 'grid') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.createRoomsBulk({ buildingId, floorFrom: Number(d.floorFrom), floorTo: Number(d.floorTo), perFloor: Number(d.perFloor), price: d.price, type: d.type, area: Number(d.area) }), r => 'Đã tạo ' + r.made.length + ' phòng' + (r.skipped ? ', bỏ qua ' + r.skipped + ' trùng mã' : '')); } });
  };
  Fm.roomStatus = (room) => {
    const m = U.modal({ title: 'Đổi trạng thái phòng ' + room.code, size: 'sm', body: U.field({ label: 'Trạng thái mới', input: U.select({ name: 'status', value: room.status === 'maintenance' ? 'ready' : 'maintenance', options: (Q.ROOM_TRANSITIONS[room.status] || ['ready']).filter(k => !['held', 'vacating'].includes(k)).map(k => [k, Q.label('room', k)]) }), help: 'Chuyển được: ' + (Q.ROOM_TRANSITIONS[room.status] || []).map(k => Q.label('room', k)).join(', ') + ' (§12.5.3)' }) + U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', placeholder: 'Lý do…' }), cls: 'mt12' }), footer: footer('Cập nhật') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.setRoomStatus(room.id, d.status, d.note), 'Đã đổi trạng thái phòng'); } });
  };
  Fm.hold = (roomId) => {
    const r = Q.room(roomId);
    const m = U.modal({ title: 'Giữ chỗ phòng ' + r.code, sub: 'Phòng chuyển sang Giữ chỗ, khóa khỏi danh sách sẵn sàng đến hết hạn giữ', body: `<div class="form-grid">${U.field({ label: 'Khách', req: true, input: U.select({ name: 'tenantId', placeholder: 'Chọn khách', options: opt.tenants() }), cls: 'span2', help: 'Chưa có khách? Tạo tại Khách thuê → Thêm khách thuê' })}${U.field({ label: 'Giữ đến ngày', req: true, input: U.date({ name: 'until', value: F.addDays(F.today(), 7) }) })}${U.field({ label: 'Tiền giữ chỗ', input: U.money({ name: 'deposit', value: 2000000 }) })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note' }), cls: 'span2' })}</div>`, footer: footer('Xác nhận giữ chỗ', 'clock') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.roomId = roomId; run(m, () => X.holdRoom(d), 'Đã giữ chỗ phòng ' + r.code); } });
  };
  /* ---- Chủ nhà ---- */
  Fm.landlord = (l = {}) => {
    if (!l.id) { TH._wz = TH._wz || {}; delete TH._wz.landlordOnboarding; TH.go('#/landlords/new'); return; }
    const m = U.drawer({ title: l.id ? 'Sửa chủ nhà' : 'Thêm chủ nhà', sub: 'Hồ sơ chủ nhà / đối tác cho thuê đầu vào (FR-BLD-01/06)', body: `<div class="form-grid">
      ${U.field({ label: 'Loại', input: U.select({ name: 'type', value: l.type || 'person', options: [['person', 'Cá nhân'], ['company', 'Công ty']] }) })}
      ${U.field({ label: 'Tên chủ nhà / đối tác', req: true, name: 'name', input: U.input({ name: 'name', value: l.name || '' }) })}
      ${U.field({ label: 'Số điện thoại', req: true, name: 'phone', input: U.input({ name: 'phone', value: l.phone || '', icon: 'phone' }) })}
      ${U.field({ label: 'Email', input: U.input({ name: 'email', value: l.email || '', icon: 'mail' }) })}
      ${U.field({ label: 'Mã số thuế', input: U.input({ name: 'taxCode', value: l.taxCode || '' }) })}
      ${U.field({ label: 'Tài khoản nhận tiền', input: U.input({ name: 'bankAccount', value: l.bankAccount || '', placeholder: 'Ngân hàng – số TK' }) })}
      ${U.field({ label: 'Địa chỉ', input: U.input({ name: 'address', value: l.address || '' }), cls: 'span2' })}
      ${U.field({ label: 'Chu kỳ trả mặc định', input: U.select({ name: 'cycleMonths', value: l.cycleMonths || 3, options: [[3, '3 tháng'], [4, '4 tháng'], [6, '6 tháng']] }) })}
      ${U.field({ label: 'Trạng thái hợp tác', input: U.select({ name: 'status', value: l.status === 'paused' ? 'paused' : 'active', options: [['active', 'Đang hợp tác'], ['paused', 'Tạm ngừng']] }), help: 'Sắp hết hạn được tính tự động theo HĐ đầu vào.' })}
      <div class="field span2"><label>Tòa liên kết</label><div class="row wrap gap12">${opt.buildings(true).map(([id, nm]) => U.check({ name: 'b_' + id, label: nm, checked: (l.buildingIds || []).includes(id) })).join('')}</div></div></div>`, footer: footer(l.id ? 'Lưu thay đổi' : 'Lưu chủ nhà') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = opt.buildings(true).filter(([id]) => d['b_' + id]).map(([id]) => id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); d.cycleMonths = Number(d.cycleMonths); if (l.id) d.id = l.id; run(m, () => X.saveLandlord(d), r => 'Đã lưu chủ nhà ' + r.name); } });
  };
  Fm.landlordContract = (landlordId, c = {}) => {
    const l = St.get('landlords', landlordId);
    const m = U.drawer({ title: c.id ? 'Sửa hợp đồng đầu vào' : 'Thêm hợp đồng đầu vào', sub: l.name + ' – chu kỳ trả 3/4/6 tháng theo thỏa thuận (BR-11)', body: `<div class="form-grid">
      ${U.field({ label: 'Ngày ký', input: U.date({ name: 'signedDate', value: c.signedDate || F.today() }) })}${U.field({ label: 'Loại hợp đồng', input: U.select({ name: 'type', value: c.type || 'Hợp đồng thuê tòa nhà', options: ['Hợp đồng thuê tòa nhà', 'Hợp đồng hợp tác kinh doanh'] }) })}
      ${U.field({ label: 'Ngày bắt đầu', req: true, input: U.date({ name: 'start', value: c.start || F.today() }) })}${U.field({ label: 'Ngày kết thúc', req: true, input: U.date({ name: 'end', value: c.end || F.addDays(F.addMonths(F.today(), 36), -1) }) })}
      ${U.field({ label: 'Giá thuê / tháng', req: true, input: U.money({ name: 'rent', value: c.rent || '' }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: c.deposit || '' }) })}
      ${U.field({ label: 'Thời gian giữ giá (tháng)', input: U.input({ name: 'priceHoldMonths', type: 'number', value: c.priceHoldMonths || 24 }), help: 'Chủ nhà không tăng giá trong thời gian giữ giá (Q05)' })}${U.field({ label: 'Chu kỳ trả', req: true, input: U.select({ name: 'cycleMonths', value: c.cycleMonths || l.cycleMonths || 3, options: [[3, '3 tháng/lần'], [4, '4 tháng/lần'], [6, '6 tháng/lần']] }) })}
      <div class="field span2"><label>Tòa thuộc hợp đồng<span class="req">*</span></label><div class="row wrap gap12">${St.all('buildings').map(b => { const other = b.landlordId && b.landlordId !== landlordId; return U.check({ name: 'b_' + b.id, label: esc(b.name) + ' (' + esc(b.code) + ')' + (other ? ' <span class="chip gray">Thuộc ' + esc((St.get('landlords', b.landlordId) || {}).name || '') + '</span>' : ''), checked: !other && (c.buildingIds || l.buildingIds || []).includes(b.id), attrs: other ? { disabled: true } : {} }); }).join('')}</div><div class="help">Chỉ tòa của chủ nhà này hoặc chưa có chủ nhà. Lưu HĐ mới sẽ tự sinh lịch trả theo chu kỳ.</div></div>
      ${U.field({ label: 'Số hợp đồng', input: U.input({ name: 'contractNo', value: c.contractNo || '', placeholder: 'VD: 01/2026/HĐT' }) })}${U.field({ label: 'Ngày đến hạn thanh toán (ngày trong tháng)', input: U.input({ name: 'dueDay', type: 'number', value: c.dueDay || 5 }) })}
      ${U.field({ label: 'Ký hiệu / loại tòa theo HĐ (§4.6)', input: U.select({ name: 'buildingType', value: c.buildingType || 'T', options: Q.buildingTypeOptions() }), help: 'Ghi Building Type History khi kích hoạt, có ngày hiệu lực' })}${U.field({ label: 'Ngày hiệu lực loại tòa', input: U.date({ name: 'typeEffectiveFrom', value: c.typeEffectiveFrom || c.start || F.today() }) })}
      ${U.field({ label: 'Trạng thái HKD', input: U.select({ name: 'hkdStatus', value: c.hkdStatus || 'unregistered', options: [['unregistered', 'Chưa đăng ký'], ['registered', 'Đã đăng ký']] }), help: 'Tự chuyển Đã đăng ký khi tải "Giấy đăng ký HKD"' })}${U.field({ label: 'PCCC', input: `<div class="row gap8">${U.select({ name: 'pcccStatus', value: (c.pccc || {}).status || 'none', options: [['none', 'Chưa có'], ['valid', 'Có – còn hiệu lực']], cls: 'sm' })}${U.date({ name: 'pcccExpiry', value: (c.pccc || {}).expiry || '', cls: 'sm' })}</div>` })}
      ${U.field({ label: 'Tài khoản người nhận', input: `<div class="row gap8">${U.input({ name: 'bankName', value: (c.bankAccount || {}).bank || '', placeholder: 'Ngân hàng', cls: 'sm' })}${U.input({ name: 'bankAccountName', value: (c.bankAccount || {}).name || '', placeholder: 'Chủ TK', cls: 'sm' })}${U.input({ name: 'bankAccountNo', value: (c.bankAccount || {}).no || '', placeholder: 'Số TK', cls: 'sm' })}</div>`, cls: 'span2' })}
      ${U.field({ label: 'Lịch tăng giá (từ ngày – giá mới; mỗi dòng một mốc)', input: U.textarea({ name: 'priceScheduleText', value: (c.priceSchedule || []).map(x => F.date(x.from) + ' – ' + F.vnd(x.price)).join('\n'), rows: 2, placeholder: '01/11/2028 – 63.000.000' }), cls: 'span2', help: 'Sau khi lưu có thể sửa chi tiết tại thẻ Lịch tăng giá' })}
      ${U.field({ label: 'Tài sản bàn giao', input: U.textarea({ name: 'handoverAssets', value: c.handoverAssets || '', rows: 2, placeholder: 'Danh sách tài sản chủ nhà bàn giao…' }), cls: 'span2' })}
      ${c.id ? '' : U.field({ label: 'Trạng thái sau khi lưu', input: U.select({ name: 'status', value: 'active', options: [['draft', 'Dự thảo (kích hoạt sau)'], ['active', 'Kích hoạt ngay']] }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: c.note || '' }), cls: 'span2' })}</div>`, footer: footer('Lưu hợp đồng') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = St.all('buildings').filter(b => d['b_' + b.id]).map(b => b.id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); if (!d.buildingIds.length) return U.toast('warn', 'Chọn ít nhất một tòa'); d.landlordId = landlordId; d.cycleMonths = Number(d.cycleMonths); d.priceHoldMonths = Number(d.priceHoldMonths); d.pccc = { status: d.pcccStatus, expiry: d.pcccExpiry }; delete d.pcccStatus; delete d.pcccExpiry; d.bankAccount = { bank: d.bankName, name: d.bankAccountName, no: d.bankAccountNo }; delete d.bankName; delete d.bankAccountName; delete d.bankAccountNo; d.priceSchedule = String(d.priceScheduleText || '').split(/\n/).map(l => { const mm = l.match(/(\d{1,2})\/(\d{1,2})\/(\d{4})\s*[–-]\s*([\d.,]+)/); return mm ? { from: mm[3] + '-' + F.pad(Number(mm[2])) + '-' + F.pad(Number(mm[1])), price: F.num(mm[4]) } : null; }).filter(Boolean); delete d.priceScheduleText; if (c.id) { d.id = c.id; delete d.status; } run(m, () => { const r = X.saveLandlordContract(d); if (r.buildingType && r.status !== 'draft' && X.setLcBuildingType) { try { X.setLcBuildingType(r.id, { type: r.buildingType, effectiveFrom: r.typeEffectiveFrom || r.start, reason: 'Theo HĐ đầu vào ' + r.code }); } catch (e) { /* trùng ngày hiệu lực */ } } return r; }, r => 'Đã lưu hợp đồng đầu vào ' + r.code + (c.id ? '' : ' – lịch trả đã sinh tự động')); } });
  };
  Fm.landlordSchedule = (lc) => {
    const m = U.modal({ title: 'Tạo lịch thanh toán', size: 'sm', sub: 'Bổ sung kỳ còn thiếu theo chu kỳ ' + lc.cycleMonths + ' tháng, số tiền = giá thuê × chu kỳ (kỳ đã có được giữ nguyên)', body: `<div class="form-grid">${U.field({ label: 'Kỳ đầu từ ngày', input: U.date({ name: 'from', value: lc.start }) })}${U.field({ label: 'Số kỳ', input: U.input({ name: 'periods', type: 'number', value: Q.landlordSchedulePreview(lc).length }) })}</div>`, footer: footer('Tạo lịch', 'calendar') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.generateLandlordSchedule(lc.id, { from: d.from, periods: Number(d.periods) }), r => 'Đã tạo ' + r.length + ' kỳ thanh toán'); } });
  };
  Fm.landlordPayment = (lc) => {
    const m = U.modal({ title: 'Thêm kỳ thanh toán', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Tên kỳ', input: U.input({ name: 'periodLabel', value: 'Kỳ ' + (Q.landlordPayments(lc.landlordId).length + 1) }) })}${U.field({ label: 'Hạn thanh toán', req: true, input: U.date({ name: 'dueDate', value: F.today() }) })}${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount', value: lc.rent * lc.cycleMonths }), cls: 'span2' })}</div>`, footer: footer('Thêm kỳ') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.addLandlordPayment(Object.assign(d, { landlordContractId: lc.id, landlordId: lc.landlordId, buildingId: lc.buildingIds[0] })), 'Đã thêm kỳ thanh toán'); } });
  };
  Fm.landlordPaid = (p) => {
    const m = U.modal({ title: 'Ghi nhận đã trả chủ nhà', size: 'sm', sub: p.periodLabel + ' – hạn ' + F.date(p.dueDate), body: `<div class="form-grid">${U.field({ label: 'Ngày thanh toán', req: true, input: U.date({ name: 'paidDate', value: F.today() }) })}${U.field({ label: 'Số tiền', input: U.money({ name: 'amount', value: p.amount }) })}${U.field({ label: 'Bằng chứng', input: U.dropzone({ name: 'ev', hint: 'PDF/JPG ủy nhiệm chi' }), cls: 'span2' })}</div>${U.note('info', 'Ghi sổ chi phí', 'Khoản này được ghi nhận thành chi phí <b>Thuê nhà</b> ' + F.vnd(p.amount) + ' cho tòa ' + esc(Q.building(p.buildingId).name || '') + ' vào kỳ theo ngày thanh toán, xuất hiện ở Chi phí và Dòng tiền.')}`, footer: footer('Xác nhận đã trả', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; run(m, () => X.markLandlordPaid(p.id, { paidDate: d.paidDate, amount: d.amount, evidence: f ? f.name : 'uy_nhiem_chi.pdf' }), 'Đã ghi nhận thanh toán chủ nhà'); } });
  };
  /* ---- Hợp đồng ---- */
  Fm.renew = (c) => {
    const m = U.modal({ title: 'Gia hạn hợp đồng ' + c.code, sub: 'Lập hợp đồng gia hạn ở trạng thái Nháp (dịch vụ, thành viên được sao chép, có thể sửa). Hợp đồng cũ chỉ kết thúc khi hợp đồng mới được kích hoạt.', body: `<div class="form-grid">${U.field({ label: 'Ngày bắt đầu mới', input: U.input({ name: 'startX', value: F.date(F.addDays(c.end, 1)), readonly: true }) })}${U.field({ label: 'Ngày kết thúc mới', req: true, input: U.date({ name: 'end', value: F.addDays(F.addMonths(c.end, 12), 0) }) })}${U.field({ label: 'Giá thuê mới', input: U.money({ name: 'price', value: c.price }) })}${U.field({ label: 'Tiền cọc', input: U.money({ name: 'deposit', value: c.deposit }), help: 'Giữ nguyên cọc đang giữ nếu không đổi' })}</div>`, footer: footer('Xác nhận gia hạn', 'refresh') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const r = run(m, () => X.renewContract(c.id, { end: d.end, price: d.price, deposit: d.deposit }), r => 'Đã lập HĐ gia hạn ' + r.code + ' (nháp) – kiểm tra rồi kích hoạt'); if (r) TH.go('#/contracts/new?id=' + r.id + '&step=5'); } });
  };
  /* Kết thúc / trả phòng (§4.17, §12.16): loại kết thúc → ngày → chỉ số cuối → hóa đơn cuối → công nợ (bù trừ được phép) → cọc → khấu trừ → hồ sơ hoàn cọc (Nháp) → HĐ Chờ quyết toán */
  Fm.terminate = (c) => {
    const room = Q.room(c.roomId); const debt = Q.contractDebt(c.id); const bal = Q.depositBalance(c.id); const held = bal.holding > 0 ? bal.holding : Number(c.deposit) || 0; const assets = Q.contractHandoverAssets(c.id);
    const lastOf = (type) => { const l = St.rawAll('meterReadings').filter(m => m && m.roomId === c.roomId && m.type === type && m.readingType !== 'CLOSING').sort((a, b) => F.cmp(b.period || b.readingDate || '', a.period || a.readingDate || ''))[0]; return l ? { v: Number(l.curr), when: l.period ? F.periodLabel(l.period) : F.date(l.readingDate) } : { v: 0, when: '' }; };
    const lE = lastOf('electric'), lW = lastOf('water'); const pE = X.meterPrice ? X.meterPrice(c, 'DIEN', F.period(F.today())) : 0, pW = X.meterPrice ? X.meterPrice(c, 'NUOC', F.period(F.today())) : 0;
    const defDed = Q.refundDefaults().slice(0, 1); const groups = Object.entries(Q.L.deductionGroup || { KH: ['Khấu hao'], SC: ['Sửa chữa'], VS: ['Dịch vụ'], CN: ['Công nợ'], KHAC: ['Khác'] }).map(([k, v]) => [k, v[0]]);
    const dedRows = (rows) => rows.map((d, i) => `<tr><td>${U.select({ name: 'dg_' + i, value: d.groupCode || 'VS', options: groups, cls: 'sm' })}</td><td>${U.input({ name: 'dd_' + i, value: d.desc || '', cls: 'sm', placeholder: 'Diễn giải / chứng từ' })}</td><td>${U.money({ name: 'da_' + i, value: d.amount || '' })}</td><td class="tr">${U.iconBtn('trash', 'ded-rm', 'Xóa', { 'data-i': i })}</td></tr>`).join('');
    const m = U.drawer({ title: 'Kết thúc hợp đồng ' + c.code, wide: true, sub: Q.tenant(c.tenantId).name + ' – phòng ' + room.code + ' · ' + esc(Q.building(c.buildingId).name) + ' · Luồng §4.17: xác nhận ngày ra → chốt điện nước → hóa đơn cuối → công nợ → cọc → khấu trừ → hồ sơ hoàn cọc', body: `<div class="col gap12">
      ${U.card({ title: '1. Loại kết thúc & ngày', icon: 'calendar', body: `<div class="form-grid">${U.field({ label: 'Loại kết thúc', req: true, input: U.select({ name: 'endType', value: c.endType || (F.daysUntil(c.end) <= 0 ? 'on_time' : 'early_tenant'), options: Object.entries(Q.L.endType).filter(([k]) => k !== 'renew').map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Lý do chuẩn (Master Data)', input: U.select({ name: 'reasonCode', value: c.endReasonCode || '', all: 'Chọn lý do…', options: Q.endReasonOptions() }) })}${U.field({ label: 'Ngày thông báo', input: U.date({ name: 'noticeDate', value: c.noticeDate || F.today() }) })}${U.field({ label: 'Ngày ra thực tế', req: true, input: U.date({ name: 'actualEnd', value: c.moveOutDate || F.today() }), help: 'HĐ đến ' + F.date(c.end) + (c.moveOutDate ? ' · đã xác nhận trả ' + F.date(c.moveOutDate) : '') })}${U.field({ label: 'Mô tả', input: U.textarea({ name: 'note', value: c.endNote || '', rows: 2 }), cls: 'span2' })}</div>` })}
      ${U.card({ title: '2. Chốt điện nước (chỉ số cuối)', icon: 'zap', sub: 'Ghi meterReadings CLOSING; chênh lệch so với chỉ số gần nhất tính vào hóa đơn cuối', body: `<div class="form-grid">${U.field({ label: 'Điện – chỉ số gần nhất ' + (lE.when ? '(' + lE.when + ')' : ''), input: U.input({ name: 'elecPrev', value: lE.v, readonly: true }) })}${U.field({ label: 'Điện – chỉ số cuối (kWh)', input: U.input({ name: 'elecCurr', type: 'number', value: lE.v, attrs: { 'data-on': 'calc' } }), help: 'Đơn giá ' + F.vnd(pE) + ' đ/kWh' })}${U.field({ label: 'Nước – chỉ số gần nhất ' + (lW.when ? '(' + lW.when + ')' : ''), input: U.input({ name: 'waterPrev', value: lW.v, readonly: true }) })}${U.field({ label: 'Nước – chỉ số cuối (m³)', input: U.input({ name: 'waterCurr', type: 'number', value: lW.v, attrs: { 'data-on': 'calc' } }), help: 'Đơn giá ' + F.vnd(pW) + ' đ/m³' })}</div>` })}
      ${U.card({ title: '3. Hóa đơn cuối / quyết toán', icon: 'receipt', body: `<div id="final-preview" class="small"></div><div class="mt8">${U.check({ name: 'issueFinal', label: 'Phát hành hóa đơn cuối ngay (tính vào công nợ quyết toán)', checked: true })}</div>` })}
      ${U.card({ title: '4. Công nợ & cọc (§4.18)', icon: 'wallet', body: `<div class="grid grid-3 mb8">${U.kpi({ mini: true, label: 'Công nợ đã phát hành', value: F.vnd(debt), icon: 'alert-circle', tone: debt ? 'red' : 'green' })}${U.kpi({ mini: true, label: 'Cọc đang giữ (ledger)', value: F.vnd(held), icon: 'shield', tone: 'blue' })}${U.kpi({ mini: true, label: 'Dự kiến thực hoàn', value: '<span id="refund-preview">' + F.vnd(Math.max(0, held - debt - F.sum(defDed, d => d.amount))) + '</span>', icon: 'hand-coins', tone: 'green' })}</div><div class="form-grid">${U.field({ label: 'Công nợ được phép bù trừ vào cọc', input: U.money({ name: 'debtOffset', value: debt, attrs: { 'data-on': 'calc' } }), help: 'Thực hoàn = Cọc đang giữ − công nợ được phép bù trừ − phạt − sửa chữa − vệ sinh − khác. Nhập 0 nếu thu công nợ riêng.' })}${U.field({ label: 'Phạt theo điều khoản (nếu có)', input: U.money({ name: 'penalty', value: 0, attrs: { 'data-on': 'calc' } }), help: 'Đưa vào hóa đơn cuối dòng PENALTY' })}</div>` })}
      ${U.card({ title: '5. Khấu trừ & tình trạng tài sản', icon: 'package', sub: 'Mọi khấu trừ phải có dòng chi tiết (§12.16.4); đối chiếu ' + assets.length + ' tài sản bàn giao', actions: U.btn({ label: 'Thêm dòng', icon: 'plus', size: 'btn-sm', cls: 'btn-ghost', act: 'ded-add' }), bodyCls: 'tight', body: `<table class="tbl compact"><thead><tr><th>Nhóm</th><th>Diễn giải</th><th class="num">Số tiền</th><th></th></tr></thead><tbody id="ded-body">${dedRows(defDed)}</tbody></table>${assets.length ? `<div class="card-b" style="border-top:1px solid var(--border)"><b class="small">Tình trạng tài sản bàn giao</b><div class="row wrap gap8 mt8">${assets.slice(0, 12).map((a, i) => `<label class="chk xs"><input type="checkbox" name="ast_${a.id}" checked> ${esc(a.name)} OK</label>`).join('')}${assets.length > 12 ? '<span class="xs muted">+' + (assets.length - 12) + ' tài sản khác</span>' : ''}</div><div class="xs muted mt4">Bỏ tick = hư hỏng/thiếu → thêm dòng khấu trừ Sửa chữa kèm bằng chứng.</div></div>` : ''}` })}
      ${U.note('info', 'Sau khi xác nhận', 'HĐ → <strong>Chờ quyết toán</strong>, phòng → Sắp trống/Chờ dọn theo ngày ra; hồ sơ hoàn cọc (Nháp) tạo ở Tài chính → Hoàn cọc: gửi duyệt → duyệt → ghi nhận hoàn → HĐ Đã kết thúc → phòng Chờ dọn → nghiệm thu → Sẵn sàng. Hoàn cọc không tự làm phòng Sẵn sàng.')}
    </div>`, footer: footer('Xác nhận kết thúc', 'x-circle') });
    let dedCount = defDed.length;
    const calc = () => { const d = U.formData(m.el); const useE = Math.max(0, F.num(d.elecCurr) - lE.v), useW = Math.max(0, F.num(d.waterCurr) - lW.v); const period = F.period(d.actualEnd || F.today()); const existing = St.one('invoices', i => i.contractId === c.id && i.period === period && i.docStatus !== 'cancelled'); const lines = []; if (!existing) { const [y, mo] = period.split('-').map(Number); const dim = new Date(y, mo, 0).getDate(); const startDay = F.period(c.start) === period ? Number(c.start.slice(8, 10)) : 1; const days = Number((d.actualEnd || F.today()).slice(8, 10)) - startDay + 1; lines.push(['Tiền phòng ' + days + '/' + dim + ' ngày', Math.round(c.price * days / dim / 1000) * 1000]); Q.contractServices(c.id).forEach(sv => { if (Q.service(sv.serviceId).method !== 'meter') lines.push([sv.name + ' (kỳ cuối)', sv.price * sv.qty]); }); } if (useE) lines.push(['Điện ' + useE + ' kWh × ' + F.vnd(pE), useE * pE]); if (useW) lines.push(['Nước ' + useW + ' m³ × ' + F.vnd(pW), useW * pW]); if (F.num(d.penalty) > 0) lines.push(['Phạt theo điều khoản', F.num(d.penalty)]); const total = F.sum(lines, l => l[1]); const box = m.el.querySelector('#final-preview'); if (box) box.innerHTML = (existing ? '<div class="xs muted mb4">Kỳ ' + F.periodLabel(period) + ' đã có hóa đơn ' + esc(existing.code) + ' – hóa đơn cuối chỉ gồm điện/nước chốt & phạt.</div>' : '') + (lines.length ? '<table class="tbl compact"><tbody>' + lines.map(l => '<tr><td>' + esc(l[0]) + '</td><td class="num">' + F.vnd(l[1]) + '</td></tr>').join('') + '<tr><td><b>Tổng hóa đơn cuối</b></td><td class="num"><b>' + F.vnd(total) + '</b></td></tr></tbody></table>' : '<span class="muted">Không phát sinh hóa đơn cuối (không có tiêu thụ/phạt).</span>'); const ded = F.sum(Array.from({ length: dedCount }, (_, i) => F.num(d['da_' + i])), x => x); const off = Math.min(F.num(d.debtOffset), debt + (d.issueFinal ? total : 0)); const rp = m.el.querySelector('#refund-preview'); if (rp) rp.textContent = F.vnd(Math.max(0, held - off - ded)); };
    m.el.addEventListener('input', () => calc()); m.el.addEventListener('change', () => calc()); setTimeout(calc, 30);
    U.bind(m.el, { cancel: () => m.close(), 'ded-add': () => { const tb = m.el.querySelector('#ded-body'); tb.insertAdjacentHTML('beforeend', dedRows([{ groupCode: 'SC', desc: '', amount: '' }]).replace(/_0\b/g, '_' + dedCount)); dedCount++; }, 'ded-rm': (el) => { el.closest('tr').remove(); calc(); },
      save: () => { const d = U.formData(m.el); const deductions = Array.from({ length: dedCount }, (_, i) => d['dd_' + i] !== undefined || d['da_' + i] !== undefined ? { groupCode: d['dg_' + i], group: (groups.find(g => g[0] === d['dg_' + i]) || ['', 'Khác'])[1], desc: d['dd_' + i], amount: F.num(d['da_' + i]), evidenceCount: F.num(d['da_' + i]) > 0 ? 1 : 0 } : null).filter(x => x && (x.desc || x.amount)); const assetCheck = assets.map(a => ({ id: a.id, name: a.name, condition: d['ast_' + a.id] ? 'ok' : 'damaged' })); const r = run(m, () => X.endContract(c.id, { endType: d.endType, reasonCode: d.reasonCode, noticeDate: d.noticeDate, actualEnd: d.actualEnd, note: d.note, readings: { electric: d.elecCurr, water: d.waterCurr }, issueFinal: !!d.issueFinal, debtOffset: F.num(d.debtOffset), penalties: F.num(d.penalty) > 0 ? [{ item: 'Phạt', desc: 'Phạt theo điều khoản hợp đồng', amount: F.num(d.penalty) }] : [], deductions, assetCheck }), r => 'Đã quyết toán trả phòng – HĐ Chờ quyết toán' + (r.invoice ? ', hóa đơn cuối ' + r.invoice.code : '') + (r.refund ? ', hồ sơ hoàn cọc ' + r.refund.code : '')); if (r && r.refund) setTimeout(() => U.toast('info', 'Bước tiếp theo', 'Hoàn thiện phương án hoàn cọc ' + r.refund.code + ' tại Tài chính → Hoàn cọc'), 1200); } });
  };
  Fm.endContract = Fm.terminate;
  /* Xác nhận trả phòng (khách báo trả) – HĐ Chờ kết thúc, phòng Sắp trống */
  Fm.confirmMoveOut = (c) => {
    const m = U.modal({ title: 'Xác nhận trả phòng – ' + c.code, sub: 'Khách báo trả → HĐ chuyển Chờ kết thúc, phòng chuyển Sắp trống đến ngày ra (§12.5.3, §12.7.3)', body: `<div class="form-grid">${U.field({ label: 'Loại kết thúc', req: true, input: U.select({ name: 'endType', value: F.daysUntil(c.end) <= 35 ? 'on_time' : 'early_tenant', options: Object.entries(Q.L.endType).filter(([k]) => !['renew'].includes(k)).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Lý do chuẩn', input: U.select({ name: 'reasonCode', all: 'Chọn lý do…', options: Q.endReasonOptions() }) })}${U.field({ label: 'Ngày thông báo', input: U.date({ name: 'noticeDate', value: F.today() }) })}${U.field({ label: 'Ngày ra dự kiến', req: true, input: U.date({ name: 'moveOutDate', value: F.daysUntil(c.end) <= 35 ? c.end : F.addDays(F.today(), 30) }) })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', rows: 2 }), cls: 'span2' })}</div>`, footer: footer('Xác nhận trả phòng', 'log-out') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.confirmMoveOut(c.id, d), 'Đã xác nhận trả phòng – HĐ Chờ kết thúc, phòng Sắp trống'); } });
  };
  Fm.returnContract = (c) => { const m = U.modal({ title: 'Trả sửa hợp đồng ' + c.code, size: 'sm', body: U.field({ label: 'Lý do', req: true, input: U.textarea({ name: 'reason', rows: 3 }) }), footer: footer('Trả sửa', 'rotate-ccw') }); U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.returnContract(c.id, d.reason), 'Đã trả sửa – HĐ về Dự thảo'); } }); };
  Fm.followUp = (c, cb) => {
    const emps = St.rawAll('employees').filter(e => e && e.status !== 'resigned').sort((a, b) => F.cmp(a.name, b.name)).map(e => [e.id, e.name]);
    const m = U.modal({ title: 'Ghi nhận liên hệ gia hạn – ' + c.code, sub: Q.tenant(c.tenantId).name + ' · ' + Q.room(c.roomId).code + ' · hết hạn ' + F.date(c.end) + ' (' + F.daysUntil(c.end) + ' ngày)', body: `<div class="form-grid">${U.field({ label: 'Kênh', input: U.select({ name: 'channel', value: 'Điện thoại', options: ['Điện thoại', 'Zalo', 'Gặp trực tiếp', 'Email'] }) })}${U.field({ label: 'Kết quả', req: true, input: U.select({ name: 'result', value: 'contacted', options: Object.entries(Q.L.followUp).map(([k, v]) => [k, v[0]]) }) })}${U.field({ label: 'Người xử lý', input: U.select({ name: 'assigneeId', value: c.followUpAssigneeId || '', all: 'Giữ nguyên', options: emps }) })}${U.field({ label: 'Deadline xử lý tiếp', input: U.date({ name: 'nextDeadline', value: F.addDays(F.today(), 3) }) })}${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', rows: 2 }), cls: 'span2' })}</div>${U.note('info', 'Quy tắc', 'Hệ thống chỉ tạo work queue – chọn <strong>Gia hạn</strong> sẽ lập HĐ mới Dự thảo để review/duyệt; <strong>Trả phòng</strong>/<strong>Chấm dứt sớm</strong> mở luồng kết thúc; không tự gia hạn/kết thúc (§4.11).')}`, footer: footer('Ghi nhận', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const r = run(m, () => X.addFollowUp({ contractId: c.id, channel: d.channel, result: d.result, note: d.note, nextDeadline: d.nextDeadline, assigneeId: d.assigneeId || null }), 'Đã ghi nhận liên hệ'); if (!r) return; if (d.result === 'renew') { const cur = St.get('contracts', c.id); if (cur.status === 'active') Fm.renew(cur); } else if (d.result === 'on_time' || d.result === 'early') { const cur = St.get('contracts', c.id); if (['active', 'pending_renewal'].includes(cur.status)) Fm.confirmMoveOut(cur); } cb && cb(); } });
  };
  Fm.roomPrice = (room) => {
    const m = U.modal({ title: 'Cập nhật giá niêm yết – ' + room.code, size: 'sm', sub: 'Giá có ngày hiệu lực, lưu lịch sử (§12.5.1); HĐ đang thuê giữ giá snapshot', body: `<div class="form-grid">${U.field({ label: 'Giá hiện tại', input: U.input({ value: F.vnd(room.price), readonly: true }) })}${U.field({ label: 'Giá mới (VND)', req: true, input: U.money({ name: 'price', value: room.price }) })}${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveFrom', value: F.today() }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'Điều chỉnh theo thị trường…' }) })}</div>`, footer: footer('Lưu giá', 'save') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.updateRoomPrice({ roomId: room.id, price: d.price, effectiveFrom: d.effectiveFrom, reason: d.reason }), 'Đã cập nhật giá phòng'); } });
  };
  Fm.cancelContract = async (c) => { const r = await U.confirm({ title: 'Hủy hợp đồng nháp ' + c.code + '?', text: 'Hợp đồng chuyển trạng thái Hủy, phòng không đổi.', ok: 'Hủy hợp đồng', danger: true, body: U.field({ label: 'Lý do', input: U.input({ name: 'reason' }) }) }); if (r) { X.cancelContract(c.id, r.reason); U.toast('ok', 'Đã hủy hợp đồng'); refresh(); } };
  /* ---- Thu tiền (drawer lớn) ---- */
  Fm.payment = ({ tenantId, invoiceId, onDone } = {}) => {
    let tId = tenantId || (invoiceId ? St.get('invoices', invoiceId).tenantId : '');
    const openInvoices = (tid) => St.where('invoices', i => i.tenantId === tid && i.docStatus !== 'draft' && i.docStatus !== 'cancelled' && Q.invRemaining(i) > 0).sort((a, b) => F.cmp(a.dueDate, b.dueDate));
    const allocTable = (tid, amount, prefill) => { const invs = openInvoices(tid); if (!invs.length) return U.empty({ icon: 'check-circle', title: 'Khách không còn hóa đơn nợ', text: 'Khoản thu sẽ ghi nhận là chưa phân bổ.' }); return `<table class="tbl compact"><thead><tr><th></th><th>Hóa đơn</th><th>Hạn thanh toán</th><th class="num">Còn lại (VND)</th><th class="num">Số tiền phân bổ (VND)</th></tr></thead><tbody>${invs.map(i => { const rem = Q.invRemaining(i); const v = prefill && prefill[i.id] != null ? prefill[i.id] : 0; return `<tr><td><input type="checkbox" data-alloc-chk="${i.id}" ${v > 0 ? 'checked' : ''}></td><td><a class="link" href="#/invoices/${i.id}">${i.code}</a><div class="xs muted">${F.periodLabel(i.period)}${Q.invOverdue(i) ? ' · <span class="red">quá hạn ' + Q.invOverdueDays(i) + ' ngày</span>' : ''}</div></td><td>${F.date(i.dueDate)}</td><td class="num">${F.vnd(rem)}</td><td class="num"><input class="inp sm tr" data-money data-alloc="${i.id}" data-rem="${rem}" value="${v ? F.vnd(v) : '0'}" style="width:130px"></td></tr>`; }).join('')}</tbody></table>`; };
    const body = `<div data-guide="pay-form">${U.field({ label: 'Khách thuê', req: true, input: U.select({ name: 'tenantId', value: tId, placeholder: 'Chọn khách thuê', options: opt.tenants(), attrs: { 'data-on': 'tenant' } }) })}
      <div id="pay-tenant-card" class="mt8"></div>
      <div class="form-grid mt12">${U.field({ label: 'Ngày thu', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount', value: '', attrs: { id: 'pay-amount' } }) })}</div>
      ${U.field({ label: 'Phương thức thanh toán', req: true, input: U.select({ name: 'method', value: 'Chuyển khoản', options: opt.methods() }), cls: 'mt12' })}
      ${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref', placeholder: 'CK289104' }), help: 'Mã giao dịch ngân hàng, mã phiếu thu...', cls: 'mt12' })}
      <div class="field mt12"><label>File bằng chứng</label>${U.dropzone({ name: 'evidence', hint: 'Hỗ trợ JPG, PNG, PDF (tối đa 5MB)' })}</div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', placeholder: 'Khách thanh toán tiền nhà tháng 10' }), cls: 'mt12' })}
      <div class="fs"><div class="fs-h">${I('clipboard-check')}Phân bổ vào hóa đơn<span class="ml-auto">${U.btn({ label: 'Tự động phân bổ', icon: 'refresh', act: 'auto', cls: 'btn-light', size: 'btn-sm' })}</span></div><div id="alloc-wrap" class="tbl-wrap"></div>
      <div class="sum-box mt12" id="alloc-sum"></div></div></div>`;
    const m = U.drawer({ title: 'Ghi nhận thu tiền', sub: 'Tạo phiếu thu và phân bổ vào các hóa đơn', body, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Review', act: 'review', cls: 'btn-light' }) + U.btn({ label: 'Xác nhận ghi nhận', act: 'save', cls: 'btn-primary', icon: 'check' }) });
    const el = m.el; const key = F.uid('pay');
    const tenantCard = () => { const c = el.querySelector('#pay-tenant-card'); const t = Q.tenant(tId); if (!t.id) { c.innerHTML = ''; return; } const room = Q.tenantRoom(t); c.innerHTML = `<div class="row" style="border:1px solid var(--border);border-radius:9px;padding:8px 12px">${U.avatar(t.name, 'sm')}<div class="grow"><b>${esc(t.name)}</b><div class="xs muted">${room ? room.code + ' – ' + Q.building(room.buildingId).name + ' | ' : ''}${esc(t.phone)} · Công nợ: <span class="red bold">${F.vnd(Q.tenantDebt(t.id))}</span></div></div></div>`; };
    const recalc = () => { const amt = F.num(el.querySelector('#pay-amount').value); let alloc = 0; el.querySelectorAll('[data-alloc]').forEach(inp => { const chk = el.querySelector(`[data-alloc-chk="${inp.dataset.alloc}"]`); const v = chk && chk.checked ? F.num(inp.value) : 0; alloc += v; inp.classList.toggle('red', v > Number(inp.dataset.rem)); }); const un = amt - alloc; el.querySelector('#alloc-sum').innerHTML = `<div class="it"><span>Khoản thu</span><b>${F.vnd(amt)}</b></div><div class="it"><span>Đã phân bổ</span><b class="green">${F.vnd(alloc)}</b></div><div class="it"><span>Chưa phân bổ</span><b class="${un < 0 ? 'red' : un > 0 ? 'amber' : 'red'}">${F.vnd(un)}</b></div>${un < 0 ? '<div class="xs red">Tổng phân bổ vượt khoản thu</div>' : ''}`; };
    const renderAlloc = (prefill) => { el.querySelector('#alloc-wrap').innerHTML = allocTable(tId, F.num(el.querySelector('#pay-amount').value), prefill); recalc(); };
    const autoAlloc = () => { let amt = F.num(el.querySelector('#pay-amount').value); const pre = {}; openInvoices(tId).forEach(i => { const rem = Q.invRemaining(i); const v = Math.min(rem, amt); if (v > 0) { pre[i.id] = v; amt -= v; } }); renderAlloc(pre); };
    tenantCard(); if (invoiceId) { const inv = St.get('invoices', invoiceId); el.querySelector('#pay-amount').value = F.vnd(Q.invRemaining(inv)); renderAlloc({ [invoiceId]: Q.invRemaining(inv) }); } else renderAlloc({});
    el.addEventListener('change', (e) => { if (e.target.name === 'tenantId') { tId = e.target.value; tenantCard(); renderAlloc({}); } if (e.target.matches('[data-alloc-chk]')) { const inp = el.querySelector(`[data-alloc="${e.target.dataset.allocChk}"]`); if (e.target.checked && F.num(inp.value) === 0) { const amt = F.num(el.querySelector('#pay-amount').value); let used = 0; el.querySelectorAll('[data-alloc]').forEach(x => { if (x !== inp) { const c = el.querySelector(`[data-alloc-chk="${x.dataset.alloc}"]`); if (c.checked) used += F.num(x.value); } }); inp.value = F.vnd(Math.max(0, Math.min(Number(inp.dataset.rem), amt - used))); } recalc(); } });
    el.addEventListener('input', (e) => { if (e.target.matches('[data-alloc]')) { const chk = el.querySelector(`[data-alloc-chk="${e.target.dataset.alloc}"]`); if (chk && F.num(e.target.value) > 0) chk.checked = true; } recalc(); });
    const collect = () => { const d = m.data(); d.allocations = []; el.querySelectorAll('[data-alloc]').forEach(inp => { const chk = el.querySelector(`[data-alloc-chk="${inp.dataset.alloc}"]`); if (chk && chk.checked && F.num(inp.value) > 0) d.allocations.push({ invoiceId: inp.dataset.alloc, amount: F.num(inp.value) }); }); const f = U.dzFiles(el, 'evidence')[0]; d.evidence = f ? f.name : ''; return d; };
    U.bind(el, {
      cancel: () => m.close(), auto: () => autoAlloc(),
      review: async () => { const d = collect(); const t = Q.tenant(d.tenantId); const ok = await U.confirm({ title: 'Review khoản thu', ok: 'Đúng, ghi nhận', body: U.kv([['Khách thuê', esc(t.name || '-')], ['Ngày thu', F.date(d.date)], ['Số tiền', F.vnd(d.amount) + ' đ'], ['Phương thức', esc(d.method)], ['Mã tham chiếu', esc(d.ref || '-')], ['Phân bổ', d.allocations.map(a => St.get('invoices', a.invoiceId).code + ': ' + F.vnd(a.amount)).join('<br>') || 'Chưa phân bổ'], ['Bằng chứng', esc(d.evidence || 'Chưa đính kèm')]], 'one') }); if (ok) el.querySelector('[data-act=save]').click(); },
      save: () => { const d = collect(); const r = run(m, () => X.recordPayment(d, key), r => 'Đã ghi nhận khoản thu ' + r.code + ' – ' + F.vnd(r.amount) + ' đ'); if (r) { if (onDone) onDone(r); else TH.go('#/payments/' + r.id); } },
    });
    return m;
  };
  /* Xác nhận thu tiền đơn giản: chọn hóa đơn → thu đủ số còn lại kèm minh chứng (đường nâng cao vẫn là Fm.payment) */
  Fm.confirmPayments = ({ invoiceIds = [], onDone } = {}) => {
    const all = invoiceIds.map(id => St.get('invoices', id)).filter(Boolean); const invs = all.filter(i => !['draft', 'cancelled'].includes(i.docStatus) && Q.invRemaining(i) > 0); const dropped = all.length - invs.length;
    if (!invs.length) return U.toast('info', 'Không có hóa đơn còn nợ để xác nhận', dropped ? 'Hóa đơn nháp hoặc đã thu đủ không thể xác nhận thu' : '');
    const total = F.sum(invs, i => Q.invRemaining(i)); const tenants = [...new Set(invs.map(i => i.tenantId))];
    const body = `<div data-guide="confirm-pay-form">${dropped ? U.note('info', 'Đã bỏ ' + dropped + ' hóa đơn', 'Hóa đơn nháp hoặc đã thu đủ không nằm trong danh sách xác nhận.') + '<div class="mb12"></div>' : ''}
      <div class="tbl-wrap" style="max-height:220px;overflow:auto"><table class="tbl compact"><thead><tr><th>Hóa đơn</th><th>Khách</th><th>Phòng</th><th>Kỳ</th><th class="num">Còn lại (VND)</th></tr></thead><tbody>${invs.map(i => `<tr><td><a class="link" href="#/invoices/${i.id}">${esc(i.code)}</a></td><td>${esc(Q.tenant(i.tenantId).name)}</td><td>${esc(Q.room(i.roomId).code)}</td><td>${F.periodShort(i.period)}</td><td class="num"><b>${F.vnd(Q.invRemaining(i))}</b>${Q.invOverdue(i) ? '<div class="xs red">quá hạn ' + Q.invOverdueDays(i) + ' ngày</div>' : ''}</td></tr>`).join('')}</tbody><tfoot><tr><td colspan="4"><b>Tổng thu (${invs.length} hóa đơn${tenants.length > 1 ? ' · ' + tenants.length + ' khoản thu theo khách' : ''})</b></td><td class="num"><b class="green">${F.vnd(total)}</b></td></tr></tfoot></table></div>
      <div class="form-grid mt12">${U.field({ label: 'Ngày thu', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'method', value: 'Chuyển khoản', options: opt.methods() }) })}</div>
      ${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref', placeholder: 'Mã giao dịch ngân hàng, số phiếu thu…' }), cls: 'mt12' })}
      <div class="field mt12"><label>Minh chứng thu tiền <span class="req">*</span></label>${U.dropzone({ name: 'evidence', hint: 'Ảnh chuyển khoản / biên lai – JPG, PNG, PDF (tối đa 5MB)' })}<div class="xs muted mt4">Bản demo: <a class="link" data-act="demo-ev">Dùng minh chứng mẫu</a> nếu không có file thật.</div></div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', rows: 2, placeholder: 'Khách chuyển khoản đủ tiền nhà…' }), cls: 'mt12' })}</div>`;
    const m = U.modal({ title: 'Xác nhận thu tiền', sub: 'Thu đủ số còn lại của ' + invs.length + ' hóa đơn · ' + F.vnd(total) + ' đ', size: 'md', body, footer: U.btn({ label: 'Hủy', act: 'cancel', cls: 'btn-ghost' }) + U.btn({ label: 'Xác nhận thu tiền', act: 'save', cls: 'btn-primary', icon: 'check', attrs: { 'data-guide': 'confirm-pay' } }) });
    const key = F.uid('cpay');
    U.bind(m.el, {
      cancel: () => m.close(),
      'demo-ev': () => { const dz = m.el.querySelector('[data-dz=evidence]'); dz._files = [{ name: 'bien_lai_' + F.today().replace(/-/g, '') + '.jpg', size: 245 * 1024 }]; dz._render && dz._render(); },
      save: () => { const d = m.data(); d.invoiceIds = invs.map(i => i.id); d.evidence = (U.dzFiles(m.el, 'evidence')[0] || {}).name || ''; const r = run(m, () => X.confirmPayments(d, key), r => 'Đã xác nhận thu ' + r.invoices.length + ' hóa đơn – ' + F.vnd(r.total) + ' đ (' + r.payments.map(p => p.code).join(', ') + ')'); if (r && onDone) onDone(r); },
    });
    return m;
  };
  Fm.adjustInvoice = (inv) => {
    const m = U.modal({ title: 'Điều chỉnh hóa đơn ' + inv.code, sub: 'Thêm dòng điều chỉnh, giữ nguyên bản phát hành gốc (FR-FIN-08). Chứng từ chuyển "Đã điều chỉnh".', body: `<div class="form-grid">${U.field({ label: 'Mô tả điều chỉnh', req: true, input: U.input({ name: 'desc', placeholder: 'Điều chỉnh tiền điện kỳ trước' }), cls: 'span2' })}${U.field({ label: 'Số tiền (âm = giảm)', req: true, input: U.input({ name: 'amount', type: 'number', value: -160000 }) })}${U.field({ label: 'Lý do', input: U.input({ name: 'reason', placeholder: 'Nhập lý do' }) })}</div>${U.note('info', '', 'Tổng hiện tại ' + F.vnd(inv.total) + ' đ; đã thu ' + F.vnd(Q.invPaid(inv)) + ' đ.')}`, footer: footer('Xác nhận điều chỉnh', 'pencil') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.adjustInvoice(inv.id, { desc: d.desc, amount: Number(d.amount), reason: d.reason }), r => 'Đã điều chỉnh, tổng mới ' + F.vnd(r.total)); } });
  };
  Fm.reversePayment = async (p) => { const r = await U.confirm({ title: 'Hoàn tác ghi nhận ' + p.code + '?', text: 'Khoản thu chuyển "Đã hoàn tác", các hóa đơn tính lại số còn nợ. Dấu vết được giữ trong lịch sử (BR-22).', ok: 'Hoàn tác', danger: true, body: U.field({ label: 'Lý do', req: true, input: U.input({ name: 'reason', placeholder: 'Nhập nhầm số tiền / sai khách…' }) }) }); if (r) { try { X.reversePayment(p.id, r.reason); U.toast('ok', 'Đã hoàn tác khoản thu'); refresh(); } catch (e) { U.toast('err', 'Không hoàn tác được', e.message); } } };
  Fm.adjustPayment = (p) => {
    const invs = St.where('invoices', i => i.tenantId === p.tenantId && i.docStatus !== 'draft' && i.docStatus !== 'cancelled'); const cur = F.by(Q.payAllocs(p.id), 'invoiceId');
    const m = U.drawer({ title: 'Điều chỉnh phân bổ ' + p.code, sub: 'Khoản thu ' + F.vnd(p.amount) + ' đ – phân bổ lại vào các hóa đơn của khách', body: `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th>Hóa đơn</th><th class="num">Tổng</th><th class="num">Còn lại (chưa tính phiếu này)</th><th class="num">Phân bổ</th></tr></thead><tbody>${invs.map(i => { const mine = cur[i.id] ? cur[i.id][0].amount : 0; const remOther = Q.invRemaining(i) + mine; return `<tr><td>${i.code}<div class="xs muted">${F.periodLabel(i.period)}</div></td><td class="num">${F.vnd(i.total)}</td><td class="num">${F.vnd(remOther)}</td><td class="num"><input class="inp sm tr" data-money data-alloc="${i.id}" value="${mine ? F.vnd(mine) : ''}" style="width:130px"></td></tr>`; }).join('')}</tbody></table></div>${U.field({ label: 'Lý do điều chỉnh', req: true, input: U.input({ name: 'reason' }), cls: 'mt12' })}`, footer: footer('Lưu điều chỉnh') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const allocs = []; m.el.querySelectorAll('[data-alloc]').forEach(inp => allocs.push({ invoiceId: inp.dataset.alloc, amount: F.num(inp.value) })); const d = m.data(); run(m, () => X.adjustPaymentAllocations(p.id, allocs, d.reason), 'Đã điều chỉnh phân bổ'); } });
  };
  /* ---- Hoàn cọc ---- */
  Fm.refundReject = async (rf) => { const r = await U.confirm({ title: 'Từ chối hồ sơ ' + rf.code + '?', text: 'Hồ sơ chuyển sang Từ chối (Vận hành có thể sửa phương án và gửi duyệt lại); chưa ghi nhận chi tiền, chưa gửi tin.', ok: 'Từ chối', danger: true, body: U.field({ label: 'Lý do từ chối', req: true, input: U.textarea({ name: 'reason', placeholder: 'Thiếu chứng từ sửa chữa…' }) }) }); if (r) { try { X.rejectRefund(rf.id, r.reason); U.toast('ok', 'Đã từ chối hồ sơ'); refresh(); } catch (e) { U.toast('err', 'Không thực hiện được', e.message); } } };
  Fm.refundApprove = async (rf) => { const ok = await U.confirm({ title: 'Duyệt hoàn cọc ' + rf.code + '?', text: 'Số tiền hoàn ' + F.vnd(rf.refundAmount) + ' đ. Duyệt ≠ đã chuyển tiền; bước tiếp theo là Ghi nhận đã hoàn kèm bằng chứng.', ok: 'Duyệt' }); if (ok) { try { X.approveRefund(rf.id); U.toast('ok', 'Đã duyệt hồ sơ hoàn cọc'); refresh(); } catch (e) { U.toast('err', 'Không duyệt được', e.message); } } };
  Fm.refundPaid = (rf) => {
    const m = U.modal({ title: 'Ghi nhận đã hoàn cọc', sub: rf.code + ' – ' + F.vnd(rf.refundAmount) + ' đ cho ' + Q.tenant(rf.tenantId).name, body: `<div class="form-grid">${U.field({ label: 'Ngày hoàn', req: true, input: U.date({ name: 'paidDate', value: F.today() }) })}${U.field({ label: 'Phương thức', req: true, input: U.select({ name: 'paidMethod', value: 'Chuyển khoản', options: opt.methods() }) })}${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'paidRef', placeholder: 'Mã UNC / phiếu chi' }), cls: 'span2' })}<div class="field span2"><label>Bằng chứng hoàn tiền<span class="req">*</span></label>${U.dropzone({ name: 'ev', hint: 'PDF/JPG ủy nhiệm chi hoặc biên nhận', multiple: false })}</div></div>${U.note('info', '', 'Phòng KHÔNG tự chuyển Sẵn sàng khi hoàn cọc; cần Vận hành xác nhận dọn xong (BR-02).')}`, footer: footer('Xác nhận đã hoàn', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const f = U.dzFiles(m.el, 'ev')[0]; d.paidEvidence = f ? f.name : ''; run(m, () => X.recordRefundPaid(rf.id, d), 'Đã ghi nhận hoàn cọc'); } });
  };
  /* ---- Chi phí ---- */
  Fm.expense = (ex = {}) => {
    const bs = opt.buildings(); const canCommon = TH.auth.can('expenses.manageCommon'); const allocs = ex.id ? St.where('expenseAllocations', a => a.expenseId === ex.id) : [];
    const expenseOptions = (Q.expenseTree ? Q.expenseTree() : []).flatMap(p => [[p.code, '— ' + p.name + ' —', true], ...p.children.map(c => [c.code, '  ' + c.name])]);
    const allocRows = (rows) => rows.map((a, i) => `<tr><td>${U.select({ name: 'ab_' + i, value: a.buildingId || '', cls: 'sm', placeholder: 'Chọn tòa', options: bs })}</td><td><input class="inp sm tr" name="ap_${i}" type="number" value="${a.pct}" style="width:80px"></td><td class="num" data-amt="${i}">0</td><td>${U.iconBtn('trash', 'rm-alloc', 'Bỏ', { 'data-i': i })}</td></tr>`).join('');
    let rows = allocs.length ? allocs.map(a => ({ buildingId: a.buildingId, pct: a.pct })) : [{ buildingId: bs[0] && bs[0][0], pct: 40 }, { buildingId: bs[1] && bs[1][0], pct: 30 }, { buildingId: bs[2] && bs[2][0], pct: 20 }, { buildingId: bs[3] && bs[3][0], pct: 10 }];
    const m = U.drawer({ title: ex.id ? 'Sửa chi phí ' + ex.code : 'Thêm chi phí', sub: 'Tạo mới khoản chi phí trong hệ thống', body: `
      ${U.field({ label: 'Ngày chi', req: true, input: U.date({ name: 'date', value: ex.date || F.today() }) })}
      ${U.field({ label: 'Mã chi phí', req: true, input: U.select({ name: 'categoryCode', value: ex.categoryCode || '', placeholder: 'Chọn danh mục chi phí', options: expenseOptions }), help: 'Taxonomy 2 cấp dùng chung cho báo cáo workbook', cls: 'mt12' })}
      ${U.field({ label: 'Diễn giải', input: U.input({ name: 'desc', value: ex.desc || '', placeholder: 'Tiền điện tháng 10/2026' }), cls: 'mt12' })}
      <div class="field mt12"><label>Tòa / Chi phí chung<span class="req">*</span></label><div class="row gap16"><label class="chk"><input type="radio" name="mode" value="building" ${!ex.id || ex.buildingId || !canCommon ? 'checked' : ''}> Chọn tòa nhà</label>${canCommon ? `<label class="chk"><input type="radio" name="mode" value="common" ${ex.id && !ex.buildingId ? 'checked' : ''}> Chi phí chung</label>` : ''}</div>${U.select({ name: 'buildingId', value: ex.buildingId || '', placeholder: 'Chọn tòa nhà', options: bs, cls: 'mt8' })}</div>
      ${U.field({ label: 'Số tiền (VND)', req: true, input: U.money({ name: 'amount', value: ex.amount || '', attrs: { id: 'ex-amount' } }), cls: 'mt12' })}
      <div class="field mt12"><label>Phương thức ghi nhận<span class="req">*</span></label><div class="row gap16 wrap"><label class="chk"><input type="radio" name="method" value="cash" ${ex.method !== 'depreciation' ? 'checked' : ''}> Tiền mặt <span class="muted">(Chi phí ngay)</span></label><label class="chk"><input type="radio" name="method" value="depreciation" ${ex.method === 'depreciation' ? 'checked' : ''} ${TH.phase.on(2) ? '' : 'disabled title="Khấu hao thuộc Phase 2 – bật Phase 2 trong Công cụ nâng cao"'}> Khấu hao <span class="muted">(Phân bổ theo kỳ)</span>${TH.phase.tag(2)}</label></div>${TH.phase.on(2) ? `<div class="row gap12 mt8" id="dep-months" ${ex.method === 'depreciation' ? '' : 'hidden'}>${U.field({ label: 'Số tháng khấu hao', input: U.input({ name: 'depreciationMonths', value: ex.depreciationMonths || 36, type: 'number', attrs: { min: 1, max: 120, style: 'width:120px' } }), help: 'Đường thẳng: ' + (ex.amount ? F.vnd(Math.round(ex.amount / (ex.depreciationMonths || 36))) + ' đ/tháng · ' : '') + '3–5 năm là giả định (OI-11) – không vào dòng tiền, có vào kết quả vận hành (BR-08)' })}</div>` : '<div class="help">Khấu hao theo kỳ thuộc Phase 2 (OI-11) – bản demo chỉ lưu nhãn, không sinh lịch khấu hao.</div>'}</div>
      ${U.field({ label: 'Loại ghi nhận', input: U.select({ name: 'recordType', value: ex.recordType || 'ops', options: [['ops', 'Chi phí vận hành'], ['asset', 'Mua sắm tài sản'], ...(canCommon ? [['common', 'Chi phí chung']] : [])] }), cls: 'mt12' })}
      <div class="field mt12"><label>Chứng từ</label>${U.dropzone({ name: 'ev', hint: 'Hỗ trợ: PDF, JPG, PNG (tối đa 10MB)' })}</div>
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: ex.note || '', placeholder: 'Nhập ghi chú...' }), cls: 'mt12' })}
      <div class="fs" id="alloc-sec" ${canCommon ? '' : 'hidden'}><div class="fs-h">${I('percent')}Phân bổ theo tòa <span class="muted small" style="font-weight:400">(Chỉ áp dụng khi chọn Chi phí chung)</span></div>${U.note('info', '', 'Chia khoản chi phí này cho các tòa nhà theo tỷ lệ. Tổng phải bằng 100% (FR-FIN-05).')}<div class="tbl-wrap mt8"><table class="tbl compact"><thead><tr><th>Tòa nhà</th><th>Tỷ lệ (%)</th><th class="num">Số tiền (VND)</th><th></th></tr></thead><tbody id="alloc-body">${allocRows(rows)}</tbody><tfoot><tr><td>Tổng cộng</td><td id="alloc-pct">100%</td><td class="num" id="alloc-total">0</td><td></td></tr></tfoot></table></div>${U.btn({ label: 'Thêm tòa nhà', icon: 'plus', act: 'add-alloc', cls: 'btn-dashed btn-block mt8', size: 'btn-sm' })}</div>`, footer: footer('Lưu chi phí') });
    const el = m.el;
    const sync = () => { const common = el.querySelector('input[name=mode]:checked').value === 'common'; el.querySelector('select[name=buildingId]').disabled = common; el.querySelector('#alloc-sec').style.opacity = common ? 1 : .5; const amt = F.num(el.querySelector('#ex-amount').value); let pct = 0; el.querySelectorAll('#alloc-body tr').forEach((tr, i) => { const p = Number(tr.querySelector('input[type=number]').value) || 0; pct += p; tr.querySelector('[data-amt]').textContent = F.vnd(Math.round(amt * p / 100)); }); el.querySelector('#alloc-pct').textContent = pct + '%'; el.querySelector('#alloc-pct').className = pct === 100 ? 'green' : 'red'; el.querySelector('#alloc-total').textContent = F.vnd(common ? amt : 0); };
    el.addEventListener('input', sync); el.addEventListener('change', sync); sync(); el.addEventListener('change', (e) => { if (e.target.name === 'method') { const dm = el.querySelector('#dep-months'); if (dm) dm.hidden = e.target.value !== 'depreciation'; } });
    U.bind(el, { cancel: () => m.close(), 'add-alloc': () => { rows = readRows(); rows.push({ buildingId: '', pct: 0 }); el.querySelector('#alloc-body').innerHTML = allocRows(rows); sync(); }, 'rm-alloc': (b) => { rows = readRows(); rows.splice(Number(b.dataset.i), 1); el.querySelector('#alloc-body').innerHTML = allocRows(rows); sync(); },
      save: () => { const d = m.data(); const common = d.mode === 'common'; const f = U.dzFiles(el, 'ev')[0]; const cat = Q.expenseCategory(d.categoryCode); if (!cat.id || !cat.parentCode) throw new Error('Chọn danh mục chi phí cấp chi tiết'); const payload = { id: ex.id, date: d.date, categoryCode: d.categoryCode, group: cat.name, desc: d.desc, buildingId: common ? null : d.buildingId, amount: d.amount, method: d.method, depreciationMonths: d.method === 'depreciation' ? (Number(d.depreciationMonths) || 36) : undefined, recordType: common ? 'common' : d.recordType, evidence: f ? f.name : (ex.evidence || ''), note: d.note, allocations: common ? readRows() : [] }; if (!common && !payload.buildingId) throw new Error('Chọn tòa nhà hoặc chuyển sang Chi phí chung'); run(m, () => X.saveExpense(payload), r => 'Đã lưu chi phí ' + r.code); } });
    function readRows() { return [...el.querySelectorAll('#alloc-body tr')].map(tr => ({ buildingId: tr.querySelector('select').value, pct: Number(tr.querySelector('input[type=number]').value) || 0 })); }
  };
  /* ---- Tài khoản ---- */
  Fm.user = (u = {}) => {
    const m = U.drawer({ title: u.id ? 'Sửa tài khoản' : 'Tạo tài khoản', sub: u.id ? u.email : 'Thêm tài khoản người dùng mới vào hệ thống.', body: `<div class="col" style="gap:14px">
      ${U.field({ label: 'Họ tên', req: true, input: U.input({ name: 'name', value: u.name || '', placeholder: 'Nhập họ và tên' }) })}
      ${U.field({ label: 'Email', req: true, input: U.input({ name: 'email', value: u.email || '', type: 'email', placeholder: 'Nhập địa chỉ email' }) })}
      ${U.field({ label: 'Số điện thoại', req: true, input: U.input({ name: 'phone', value: u.phone || '', placeholder: 'Nhập số điện thoại' }) })}
      ${U.field({ label: 'Vai trò', req: true, input: U.select({ name: 'role', value: u.role || '', placeholder: 'Chọn vai trò', options: [['admin', 'Quản trị viên'], ['accountant', 'Kế toán'], ['ops', 'Quản lý / Vận hành'], ['sale', 'Sale (Phase 2)'], ['kythuat', 'Kỹ thuật (Phase 2)'], ['hr', 'Nhân sự (Phase 3)'], ['codong', 'Cổ đông (Phase 3)']] }), help: [TH.phase && TH.phase.on(2) ? 'Phase 2 đang bật: có thể tạo Sale / Kỹ thuật' : '', TH.phase && TH.phase.on(3) ? 'Phase 3 đang bật: có thể tạo Nhân sự / Cổ đông' : ''].filter(Boolean).join(' · ') || 'Phase 1: Admin, Kế toán, Quản lý/Vận hành' })}
      ${U.field({ label: 'Khu vực', req: true, input: U.select({ name: 'region', value: u.region || 'Tất cả khu vực', options: ['Tất cả khu vực', ...Q.districts()] }) })}
      <div class="field"><label>Tòa/Phòng phụ trách</label><div class="row wrap gap12">${opt.buildings().map(([id, nm]) => U.check({ name: 'b_' + id, label: nm.split(' (')[0], checked: (u.buildingIds || []).includes(id) })).join('')}</div><div class="help">Có thể chọn nhiều tòa/phòng</div></div>
      ${U.field({ label: 'Ngày hiệu lực', req: true, input: U.date({ name: 'effectiveDate', value: u.effectiveDate || F.today() }) })}
      ${U.field({ label: 'Trạng thái', req: true, input: U.select({ name: 'status', value: u.status || 'active', options: [['active', 'Đang hoạt động'], ['locked', 'Tài khoản bị khóa'], ['expired', 'Hết hiệu lực']] }) })}
      ${U.field({ label: 'Ghi chú', input: U.textarea({ name: 'note', value: u.note || '', placeholder: 'Nhập ghi chú...' }) })}</div>`, footer: footer(u.id ? 'Lưu thay đổi' : 'Lưu tài khoản', 'user-plus') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); d.buildingIds = opt.buildings().filter(([id]) => d['b_' + id]).map(([id]) => id); Object.keys(d).forEach(k => k.startsWith('b_') && delete d[k]); d.scope = d.buildingIds.length ? d.buildingIds.map(id => Q.building(id).name).join(', ') : (d.role === 'admin' ? 'Toàn hệ thống' : d.role === 'accountant' ? 'Tài chính' : d.region); if (u.id) d.id = u.id; run(m, () => X.saveUser(d), r => 'Đã lưu tài khoản ' + r.name); } });
  };
  /* ---- Upload tài liệu ---- */
  Fm.upload = (entityType, entityId, cb, opts = {}) => {
    const old = opts.supersedesId ? St.rawGet('documents', opts.supersedesId) : null;
    const m = U.modal({ title: old ? 'Thay thế tài liệu (phiên bản mới)' : 'Tải lên tài liệu', size: 'sm', sub: (old ? 'File cũ "' + esc(old.name || old.fileName) + '" (v' + (old.version || 1) + ') được giữ trong lịch sử, không ghi đè (§4.5). ' : '') + 'PDF/JPG/PNG, tối đa 20 MB/tệp (FR-DOC-01). File chỉ mô phỏng.', body: U.field({ label: 'Loại tài liệu', req: true, input: U.select({ name: 'docType', value: old ? old.docType : (opts.docType || 'contract'), options: Q.DOC_TYPES() }), help: entityType === 'landlordContract' || entityType === 'building' || entityType === 'landlord' ? 'Loại "Đăng ký HKD" gắn đúng HĐ đầu vào/tòa sẽ tự chuyển HKD = Đã đăng ký (§4.5)' : '' }) + U.field({ label: 'Ngày hết hạn', input: U.date({ name: 'expiry', value: old ? old.expiry || '' : '' }), help: 'Để trống nếu tài liệu không có hạn' }) + `<div class="field mt12">${U.dropzone({ name: 'f', hint: 'PDF, JPG, PNG (tối đa 20MB)' })}</div>`, footer: footer(old ? 'Tải phiên bản mới' : 'Tải lên', 'upload') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const files = U.dzFiles(m.el, 'f'); if (!files.length) throw new Error('Chọn ít nhất một tệp'); const d = m.data(); files.forEach(f => { if (f.size > 20 * 1024 * 1024) throw new Error(f.name + ' vượt 20MB'); if (!/\.(pdf|jpe?g|png|docx?)$/i.test(f.name)) throw new Error(f.name + ': định dạng không hỗ trợ'); X.addDocument(entityType, entityId, { name: f.name, size: f.size, label: Q.label('docType', d.docType) + ' – ' + f.name, expiry: d.expiry, docType: d.docType, supersedesId: old ? old.id : null }); }); U.toast('ok', old ? 'Đã tải phiên bản mới' : 'Đã tải lên ' + files.length + ' tệp'); m.close(); refresh(); cb && cb(); } });
  };
  /* Tiền chưa xác định / ghép khoản thu (§4.15) */
  Fm.unidentified = () => {
    const m = U.modal({ title: 'Ghi nhận tiền chưa xác định', size: 'sm', sub: 'Khoản tiền vào tài khoản nhưng chưa khớp khách/phòng/hóa đơn (Unidentified Receipt) – ghép sau khi xác minh', body: `<div class="form-grid">${U.field({ label: 'Số tiền', req: true, input: U.money({ name: 'amount' }) })}${U.field({ label: 'Ngày nhận', req: true, input: U.date({ name: 'date', value: F.today() }) })}${U.field({ label: 'Phương thức', input: U.select({ name: 'method', value: 'Chuyển khoản', options: ['Chuyển khoản', 'Tiền mặt'] }) })}${U.field({ label: 'Mã tham chiếu', input: U.input({ name: 'ref' }) })}${U.field({ label: 'Nội dung chuyển khoản', input: U.input({ name: 'transferContent', placeholder: 'Nội dung CK gốc' }), cls: 'span2' })}${U.field({ label: 'Ghi chú', input: U.input({ name: 'note' }), cls: 'span2' })}</div>`, footer: footer('Ghi nhận', 'check') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.recordUnidentified(d), r => 'Đã ghi nhận ' + r.code + ' – tiền chưa xác định'); } });
  };
  Fm.matchPayment = (pay) => {
    const un = Q.paymentUnallocated(pay); const tenants = St.all('tenants').sort((a, b) => F.cmp(a.name, b.name));
    const m = U.modal({ title: 'Ghép khoản thu ' + pay.code, sub: 'Chọn khách → phân bổ vào hóa đơn còn nợ (một payment nhiều hóa đơn) hoặc ghi nhận tạm ứng phần còn lại', body: `<div class="form-grid">${U.field({ label: 'Khách', req: true, input: U.select({ name: 'tenantId', value: pay.tenantId || '', placeholder: 'Chọn khách', options: tenants.map(t => [t.id, t.name + ' · ' + (t.phone || '') + ' (' + t.code + ')']), attrs: { id: 'mp-tenant' } }), cls: 'span2' })}</div><div id="mp-inv" class="mt8"></div>${U.check({ name: 'advance', label: 'Phần chưa phân bổ ghi nhận là <b>tạm ứng</b> cho kỳ sau' })}`, footer: footer('Ghép', 'link') });
    const renderInv = () => { const tid = m.el.querySelector('#mp-tenant').value; const box = m.el.querySelector('#mp-inv'); if (!tid) { box.innerHTML = ''; return; } const invs = St.where('invoices', i => i.tenantId === tid && i.docStatus !== 'draft' && i.docStatus !== 'cancelled' && Q.invRemaining(i) > 0).sort((a, b) => F.cmp(a.dueDate, b.dueDate)); let left = un; box.innerHTML = invs.length ? `<table class="tbl compact"><thead><tr><th>Hóa đơn</th><th>Kỳ</th><th class="num">Còn nợ</th><th class="num">Phân bổ</th></tr></thead><tbody>${invs.map(i => { const a = Math.min(left, Q.invRemaining(i)); left -= a; return `<tr><td>${esc(i.code)}</td><td>${F.periodShort(i.period)}</td><td class="num">${F.vnd(Q.invRemaining(i))}</td><td>${U.money({ name: 'al_' + i.id, value: a })}</td></tr>`; }).join('')}</tbody></table><div class="xs muted mt4">Số tiền chưa phân bổ: ${F.vnd(un)}</div>` : '<div class="muted small">Khách không còn hóa đơn nợ – toàn bộ ' + F.vnd(un) + ' sẽ là thu thừa/tạm ứng.</div>'; };
    m.el.querySelector('#mp-tenant').addEventListener('change', renderInv); renderInv();
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); const allocations = Object.keys(d).filter(k => k.startsWith('al_')).map(k => ({ invoiceId: k.slice(3), amount: F.num(d[k]) })); run(m, () => X.matchPayment(pay.id, { tenantId: d.tenantId, allocations, advance: !!d.advance }), 'Đã ghép khoản thu'); } });
  };
  /* ---- Zalo: gửi nhanh cho danh sách hóa đơn / khách ---- */
  Fm.zaloQuick = ({ invoiceIds = [], tenantIds = [], eventKey = 'debt', title = 'Gửi nhắc tiền qua Zalo' }) => {
    const ev = St.one('zaloEvents', e => e.key === (eventKey === 'debt' ? 'reminder' : eventKey)) || St.all('zaloEvents')[0];
    const tpls = St.all('zaloTemplates').filter(t => !['landlord_due'].includes(t.eventKey));
    let templateId = (tpls.find(t => t.eventKey === eventKey) || tpls[0]).id;
    let force = false; let recips = X.buildRecipients('manual', { invoiceIds, tenantIds });
    const recent = () => recips.filter(r => /3 ngày/.test(r.reason || '')).length;
    const renderList = () => `<div class="tbl-wrap"><table class="tbl compact"><thead><tr><th></th><th>Khách</th><th>Phòng</th><th class="num">Số tiền nợ</th><th>Trạng thái</th></tr></thead><tbody>${recips.map((r, i) => { const t = Q.tenant(r.tenantId); return `<tr><td><input type="checkbox" data-ri="${i}" ${r.elig === 'ok' ? 'checked' : 'disabled'}></td><td>${esc(t.name)}<div class="xs muted">${esc(t.phone)}</div></td><td>${esc(Q.room(r.roomId).code || '-')}</td><td class="num">${F.vnd(r.amount)}</td><td>${U.chip(r.elig === 'ok' ? 'Đủ điều kiện' : r.elig === 'skip' ? 'Bỏ qua' : 'Lỗi dữ liệu', r.elig === 'ok' ? 'green' : r.elig === 'skip' ? 'amber' : 'red')}<div class="xs muted">${esc(r.reason)}</div></td></tr>`; }).join('')}</tbody></table></div>`;
    const preview = () => { const r = recips.find(x => x.elig === 'ok') || recips[0]; if (!r) return ''; const inv = r.invoiceId ? St.get('invoices', r.invoiceId) : null; return U.phone(Q.renderTemplate(Q.template(templateId).body, Q.templateCtx(inv, Q.tenant(r.tenantId), { room: Q.room(r.roomId), amount: r.amount, due: r.due }))); };
    const m = U.drawer({ title, wide: true, sub: 'Hệ thống re-check công nợ trước khi gửi: đã trả đủ → bỏ qua; trả một phần → gửi số còn nợ (FR-ZAL-02)', body: `${ev && !ev.enabled ? U.note('warn', 'Rule "' + esc(ev.name) + '" đang tắt', 'Đợt gửi sẽ bị từ chối. <a class="link" href="#/zalo/config">Mở Thông báo & nhắc việc</a> để bật rule trước khi gửi.') + '<div class="mb12"></div>' : ''}<div class="grid grid-2" style="grid-template-columns:1fr 300px"><div>${U.field({ label: 'Mẫu thông báo', input: U.select({ name: 'templateId', value: templateId, options: tpls.map(t => [t.id, t.name]), attrs: { 'data-on': 'tpl' } }) })}<div class="mt12" id="zq-list">${renderList()}</div><div class="mt8" id="zq-recent">${recent() ? U.note('warn', recent() + ' khách đã nhận tin trong 3 ngày qua – bị bỏ qua theo rule', U.check({ name: 'force', label: 'Vẫn gửi cho các khách này (ghi đè rule 3 ngày)', attrs: { 'data-on': 'force' } })) : ''}</div></div><div><div class="small bold mb8">Xem trước nội dung Zalo</div><div id="zq-prev">${preview()}</div></div></div>`, footer: U.btn({ label: 'Hủy', act: 'cancel' }) + U.btn({ label: 'Xác nhận gửi', act: 'send', icon: 'send', cls: 'btn-primary' }) });
    m.el.addEventListener('change', (e) => { if (e.target.name === 'templateId') { templateId = e.target.value; m.el.querySelector('#zq-prev').innerHTML = preview(); } if (e.target.matches('[data-ri]')) recips[Number(e.target.dataset.ri)].selected = e.target.checked; if (e.target.name === 'force') { force = e.target.checked; recips = X.buildRecipients('manual', { invoiceIds, tenantIds, ignoreRecent: force }); m.el.querySelector('#zq-list').innerHTML = renderList(); m.el.querySelector('#zq-prev').innerHTML = preview(); } });
    U.bind(m.el, { cancel: () => m.close(), send: () => { const r = run(m, () => X.createZaloBatch({ name: (Q.L.eventName[eventKey] || 'Nhắc tiền') + ' ' + F.date(F.today()), eventKey, sourceKey: 'manual', templateId, recipients: recips, sendMode: 'now', key: F.uid('zb') }), r => 'Đã tạo đợt gửi ' + r.code); if (r) TH.go('#/zalo/batches/' + r.id); } });
  };
  Fm.template = (tpl = {}, eventKey) => {
    const sample = Q.templateCtx(St.where('invoices', i => i.docStatus !== 'draft')[0], St.all('tenants')[0]);
    const m = U.drawer({ title: tpl.id ? 'Mẫu ' + tpl.code : 'Tạo mẫu Zalo', wide: true, sub: 'Biến: {ten_khach} {toa_nha} {so_phong} {so_tien} {ngay_den_han} {ky} {con_lai} {qua_han} {ngay_het_han} {ngay_hoan} {noi_dung}', body: `<div class="grid grid-2"><div>${U.field({ label: 'Tên mẫu', req: true, input: U.input({ name: 'name', value: tpl.name || '' }) })}${U.field({ label: 'Sự kiện', input: U.select({ name: 'eventKey', value: tpl.eventKey || eventKey || 'reminder', options: [['reminder', 'Nhắc tiền'], ['debt', 'Nhắc công nợ'], ['contract_expiry', 'HĐ sắp hết hạn'], ['refund_done', 'Đã hoàn cọc'], ['broadcast', 'Thông báo chung']] }), cls: 'mt12' })}${U.field({ label: 'Nội dung', req: true, input: U.textarea({ name: 'body', value: tpl.body || '', rows: 12 }), cls: 'mt12' })}</div><div><div class="small bold mb8">Xem trước (dữ liệu mẫu)</div><div id="tpl-prev">${U.phone(Q.renderTemplate(tpl.body || '', sample))}</div>${U.note('info', '', 'Mẫu ZBS Template Message phải qua kiểm duyệt Zalo trước khi dùng thật (OI-20).')}</div></div>`, footer: footer('Lưu mẫu') });
    m.el.addEventListener('input', (e) => { if (e.target.name === 'body') m.el.querySelector('#tpl-prev').innerHTML = U.phone(Q.renderTemplate(e.target.value, sample)); });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (tpl.id) d.id = tpl.id; run(m, () => X.saveTemplate(d), 'Đã lưu mẫu'); } });
  };
  Fm.zaloTest = (eventKey) => {
    const m = U.modal({ title: 'Gửi thử', size: 'sm', sub: 'Tạo đợt gửi 1 tin cho khách được chọn để kiểm tra nội dung', body: U.field({ label: 'Khách nhận thử', input: U.select({ name: 'tenantId', options: opt.tenants(), placeholder: 'Chọn khách' }) }), footer: footer('Gửi thử', 'send') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (!d.tenantId) throw new Error('Chọn khách'); const r = run(m, () => X.sendTest(eventKey, d.tenantId), r => 'Đã gửi thử – đợt ' + r.code); if (r) TH.go('#/zalo/batches/' + r.id); } });
  };
  Fm.roomServices = (room) => {
    const svcs = St.where('services', s => s.status === 'active' && s.method !== 'meter');
    const m = U.modal({ title: 'Quản lý dịch vụ phòng ' + room.code, sub: 'Dịch vụ mặc định nạp vào hợp đồng mới. Hợp đồng hiện tại giữ nguyên snapshot giá (BR-21).', body: `<div class="col gap12">${svcs.map(s => U.check({ name: 's_' + s.id, label: `<b>${esc(s.name)}</b> – ${F.vnd(s.price)} đ/${esc(s.unit)}`, checked: (room.defaultServiceIds || []).includes(s.id) })).join('')}</div>`, footer: footer('Lưu dịch vụ') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); run(m, () => X.saveRoomServices(room.id, svcs.filter(s => d['s_' + s.id]).map(s => s.id)), 'Đã lưu dịch vụ mặc định'); } });
  };
  Fm.roomAsset = (room, a = {}) => {
    const m = U.modal({ title: a.id ? 'Sửa tài sản' : 'Thêm tài sản trong phòng', size: 'sm', body: `<div class="form-grid">${U.field({ label: 'Tên tài sản', req: true, input: U.input({ name: 'name', value: a.name || '' }), cls: 'span2' })}${U.field({ label: 'Số lượng', input: U.input({ name: 'qty', type: 'number', value: a.qty || 1 }) })}${U.field({ label: 'Tình trạng', input: U.select({ name: 'condition', value: a.condition || 'Tốt', options: ['Tốt', 'Cần bảo dưỡng', 'Hỏng'] }) })}</div>`, footer: footer('Lưu') });
    U.bind(m.el, { cancel: () => m.close(), save: () => { const d = m.data(); if (!d.name) throw new Error('Nhập tên tài sản'); d.roomId = room.id; d.qty = Number(d.qty) || 1; if (a.id) d.id = a.id; run(m, () => X.saveRoomAsset(d), 'Đã lưu tài sản'); } });
  };
  TH.forms = Fm;
})(window.TH);
