import {chromium} from 'playwright-core';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
const port=8765+Math.floor(Math.random()*100),baseURL=process.env.INTAKE_BASE_URL || `http://localhost:${port}`;
const server=process.env.INTAKE_BASE_URL ? null : spawn(process.execPath,['scripts/serve.mjs'],{env:{...process.env,PORT:String(port)},stdio:'ignore'});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 for(let n=0;n<25;n++){try{await page.goto(baseURL);break;}catch(e){if(n===24)throw e;await new Promise(r=>setTimeout(r,150));}}
 await page.evaluate(()=>{TH.auth.login('admin');TH.go('#/owners/new');});
 await page.waitForSelector('#intake-file',{state:'attached'});
 await page.locator('#intake-file').setInputFiles(path.resolve('docs/contracts_demo/Hop_dong_chu_nha_TH01_demo_dong_bo.pdf'));
 await page.waitForFunction(()=>document.querySelector('#intake-progress')?.textContent.includes('Đã đọc'),{},{timeout:60000});
 const ownerExtraction=await page.evaluate(async()=>{const ds=await TH.intakeFiles.drafts('owner');return ds.find(d=>d.data.buildingCode==='TH01');});
 assert.equal(ownerExtraction.rooms.length,30);assert.equal(ownerExtraction.data.rent,114000000);
 await page.locator('[data-step="2"]').click();
 await page.locator('#intake-areaId').selectOption('A2');
 await page.locator('#intake-managerId').selectOption(await page.evaluate(()=>TH.store.all('employees')[0].id));
 await page.locator('[data-step="3"]').click();
 await page.locator('#intake-confirm').check();
 if(await page.locator('[data-intake="commit"]').isDisabled())throw new Error('Review blocked: '+await page.locator('[role="alert"]').innerText());await page.locator('[data-intake="commit"]').click();
 await page.waitForURL(/owner-profiles/);
 assert.equal(await page.evaluate(()=>TH.store.where('rooms',r=>r.buildingId==='b_TH01').length),30);
 await page.evaluate(()=>TH.go('#/tenants/intake'));
 await page.waitForSelector('#intake-file',{state:'attached'});
 await page.locator('#intake-file').setInputFiles(path.resolve('docs/contracts_demo/Hop_dong_khach_thue_P302_TH01_demo_dong_bo.pdf'));
 await page.waitForFunction(()=>document.querySelector('#intake-progress')?.textContent.includes('Đã đọc'),{},{timeout:60000});
 const tenantExtraction=await page.evaluate(async()=>{const ds=await TH.intakeFiles.drafts('tenant');return ds.find(d=>d.data.roomCode==='302TH01');});
 assert.equal(tenantExtraction.data.declaredPaid,9000000);assert.equal(tenantExtraction.items.water.method,'person');
 await page.locator('[data-step="3"]').click();await page.locator('#intake-confirm').check();await page.locator('[data-intake="commit"]').click();
 await page.waitForURL(/stays/);
 const result=await page.evaluate(()=>{const s=TH.store.one('stays',s=>s.roomId==='r_302TH01');return {s,rate:TH.q.rateOf(s.id),ledger:TH.store.where('depositLedger',d=>d.stayId===s.id),proposals:TH.store.where('intakePaymentProposals',p=>p.stayId===s.id)};});
 assert.equal(result.s.status,'pending');assert.equal(result.s.rent,4500000);assert.equal(result.s.openingReadings.electric,1250);assert.equal(result.ledger.length,0);assert.equal(result.proposals[0].amount,9000000);
 assert.equal(result.rate.source,'intake');assert.ok(result.rate.contractFileId);assert.ok(result.rate.contractVersionId);
 assert.equal(await page.evaluate(id=>TH.store.get('stayVersions',id).documentIds.length,result.rate.contractVersionId),1);
 await page.reload();await page.waitForFunction(()=>window.TH?.store?.state);
 assert.equal(await page.evaluate(()=>TH.store.where('rooms',r=>r.buildingId==='b_TH01').length),30);
 assert.equal((await page.evaluate(async()=>{const d=(await TH.intakeFiles.drafts('owner'))[0];return (await TH.intakeFiles.file(d.files[0].id)).blob.size;}))>1000,true);
 const pdf=fs.readFileSync(path.resolve('docs/contracts_demo/Hop_dong_khach_thue_P302_TH01_demo_dong_bo.pdf'));
 const png=await page.evaluate(async b64=>{const mod=await import('/vendor/intake/pdf/pdf.mjs');mod.GlobalWorkerOptions.workerSrc='/vendor/intake/pdf/pdf.worker.mjs';const doc=await mod.getDocument({data:Uint8Array.from(atob(b64),c=>c.charCodeAt(0)),standardFontDataUrl:'/vendor/intake/standard_fonts/'}).promise,p=await doc.getPage(1),viewport=p.getViewport({scale:2});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await p.render({canvasContext:canvas.getContext('2d'),viewport}).promise;return canvas.toDataURL('image/png').split(',')[1];},pdf.toString('base64'));
 await page.evaluate(()=>TH.go('#/tenants/intake'));
 await page.locator('#intake-file').setInputFiles({name:'hop-dong-scan.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await page.waitForFunction(()=>document.querySelector('#intake-progress')?.textContent.includes('Đã đọc'),{},{timeout:120000});
 const ocr=await page.evaluate(async()=>{const ds=await TH.intakeFiles.drafts('tenant');return ds.at(-1)?.extractedPages?.[0]?.text.slice(0,250);});
 assert.match(ocr,/HỢP ĐỒNG|HOP DONG|BÊN|BEN/i);
 await page.evaluate(()=>TH.go('#/tenants/intake?mode=excel'));
 await page.waitForSelector('#intake-file',{state:'attached'});
 const workbook=fs.readdirSync('docs_timonouse').find(n=>n.startsWith('Hoá đơn')&&n.endsWith('.xlsx'));
 await page.locator('#intake-file').setInputFiles(path.resolve('docs_timonouse',workbook));
 await page.waitForSelector('#intake-sheet',{timeout:60000});
 await page.locator('#intake-sheet').selectOption({label:'NHÀ G'});
 await page.locator('[data-intake="sheet"]').click();
 await page.waitForFunction(()=>document.body.textContent.includes('302G1'),{timeout:30000});
 await page.locator('tr:has-text("302G1") [data-intake="queue"]').first().click();
 const source=await page.evaluate(async()=>{const ds=await TH.intakeFiles.drafts('tenant');const d=ds.find(d=>d.data.roomCode==='302G1'&&d.sources.rent?.sheet==='NHÀ G');return{price:d.data.rent,list:d.data.listPrice,mgmt:d.data.mgmtPrice,oldDeposit:d.data.openingDeposit,source:d.sources.rent.cell};});
 assert.deepEqual(source,{price:3800000,list:4000000,mgmt:3800000,oldDeposit:3800000,source:'I11'});
 assert.deepEqual(errors,[]);console.log('PASS: real PDFs, image OCR, original XLSX, owner/building/30 rooms, pending stay, proposal, reload originals');
}catch(e){console.error('PAGE:',await page.locator('#content').innerText());await page.screenshot({path:'tmp/intake-failure.png',fullPage:true});throw e;}finally{await browser.close();server?.kill();}
